### ISSUE TITLE
"Too many open files" error

### ISSUE THREAD

**Issue by wuyilei** [nextflow-io/nextflow#100]
when running nextflow on a grid engine cluster, always got a "too many open files" error during the middle of the running. detailed log as follows.

$ cat .command.log
finding positions of the duplicate reads in the file...
sambamba-markdup: Cannot open or create file './sambamba-pid6283-ztgh/sorted.50.bam' : Too many open files

is it possible related to nextflow?

**Comment by pditommaso** [comment]
This is not directly related to nextflow. That error is reported by the `sambamba-markdup` tool. If you are using nextflow to launch many instances of that tool it could happen that you reached the maximum amount of files that can be opened in your system. 

The easiest solution is to increase that limit with `ulimit`. See for example here http://askubuntu.com/questions/162229/how-do-i-increase-the-open-files-limit-for-a-non-root-user

**Comment by pditommaso** [comment]
I'm closing the issue. Feel free to comment if you need more explanations.

**Comment by wuyilei** [comment]
unfortunately, our ulimit is set to unlimited

**Comment by pditommaso** [comment]
That is weird, are you sure you are checking that in the cluster computing
node?

**Comment by wuyilei** [comment]
i found the following link may be helpful to solve it.

https://github.com/lomereiter/sambamba/issues/177

**Comment by wuyilei** [comment]
yes, we check ulimit on every node of the cluster

**Comment by pditommaso** [comment]
Yes, this confirms that it's a problem with sambamba.
