### ISSUE TITLE
Nextflow doesn't wait for WebLogObserver to transmit all http messages before exiting.

### ISSUE THREAD

**Issue by olifly** [nextflow-io/nextflow#1010]
### Expected behavior and actual behavior

Expected: When executing nextflow with the `-with-weblog [url]` parameter then nextflow should send (taken from [https://www.nextflow.io/docs/latest/tracing.html#weblog-via-http](url))

> detailed workflow execution metadata and runtime statistics to a HTTP endpoint.

Nextflow should ensure that all trace messages have been sent successfully to the HTTP endpoint before shutting down.

Actual:  Nextflow sends HTTP messages asynchronously to the HTTP endpoint. When it exits it doesn't check if all the HTTP messages have been sent causing the web endpoint to potentially miss out on HTTP messages (especially if the HTTP endpoint is slow to respond).

_sidte note: The weblog only accepts HTTP status code 200 as success, everything else is a failure. This is less than optimal since  HTTP POST endpoints often reply with other 2XX statuses (201 - Created for example).  Accepting all 2XX status codes as success would be a preferable change._

### Steps to reproduce the problem

1. Run the following command: `./nextflow -log output.log run hello -with-weblog https://httpbin.org/post && grep -c "code 200" output.log`

This should count how many times the WebObserver receives status code 200 from the HTTP endpoint when executing the standard hello nextflow script.  The count depends on how many times nextflow manages to send HTTP messages before terminating (on my computer it fluctuates between 3 and 4).

2. Save the following nf script as hello-wait.nf

```
#!/usr/bin/env nextflow
echo true

cheers = Channel.from 'Bonjour', 'Ciao', 'Hello', 'Hola'

process sayHello {
  input: 
    val x from cheers
  script:
    """
    echo '$x world!'
    """
}

workflow.onComplete = {
    println "Pipeline complete"
    sleep(4000)
}
```

3. Execute the following command: `./nextflow -log output.log run hello-wait.nf -with-weblog https://httpbin.org/post && grep -c "code 200" output.log`
 
Inserting the wait at the end should give nextflow enough time to send all queued up HTTP messages before terminating (the count should be 13)

### Environment 

* Nextflow version: nextflow version 19.01.0-edge.5050 
* Java version: 1.8.0_144
* Operating system: macOS Mojave 10.14.2 (18C54)

Best Regards,
Ólafur Haukur Flygenring

**Comment by apeltzer** [comment]
@sven1103 you might be interested in this !

**Comment by sven1103** [comment]
@olifly I apologise for not responding. I addressed the status code thing in #1077 , you were absolutely right. Please have a look and comment, much appreciated!

**Comment by olifly** [comment]
@sven1103 - Thanks,this solves the HTTP status problem nicely.

Now we just need the Observer to emit all messages before exiting :o)

**Comment by MRTFrank** [comment]
hi, I have a question how i can send weblog via https ? i can't find where to configure ssl certificate
