### ISSUE TITLE
Unnecessary creation of tmp files

### ISSUE THREAD

**Issue by aresDeathscythe** [nextflow-io/nextflow#1019]
## Bug report 

Hi,

I figured out following behaviour of nextflow by running > 2000 .fastq files as input on nextflow cluster (nextflow cloud with Apache Ignite):

I always tell nextflow with -w option where to store the tmp files created by the workflow. If I do store them locally on my AWS EBS or EC2 instance the tmp files are stored in the tmp folder where I wanted them to be. If I store them at e.g. s3://tmp_dir/tmp, the tmp files are stored there but nextflow creates on the EC2 instance in /tmp nxf-*** folders which fill up the disk space if I run a big amount of fastq files at the same time (I only have 50 GB disk space in my root directory) and therefore the nextflow workflow breaks because it does not delete the tmp folders as fast as it is processing files. I don't know if this is a bug or a misbehaviour of nextflow but I am open for any input because in future I want to store my tmp directories only on S3.

Thanks for helping

Best Regards,
Marko

### Environment 

* Nextflow version: 18.10.1
* Java version "1.8.0_191"
  Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
  Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
* Operating system: Linux

**Comment by pditommaso** [comment]
When using S3 storage as work directory, remote files need to be downloaded locally, therefore are crated in at tmp local scratch. You can set to a different (local) path using `NXF_TEMP` env variable.

**Comment by aresDeathscythe** [comment]
@pditommaso thanks for the answer, will use your advice. Can be closed.
