### ISSUE TITLE
Error When Running Google Pipelines API

### ISSUE THREAD

**Issue by mahdi-b** [nextflow-io/nextflow#1023]
### Expected behavior and actual behavior

Running with a simple cloud Docker image to test NextFlow in the Google Cloud does not work. I have a simple docker image that contains a bash script that just prints its input, but I cannot seem to get it to run. The same setup works well locally but gives the following error when run on Google Cloud:
```
Execution failed: action 1: starting container: running container: running ["docker" "run" "-d" "--env-file" "/tmp/environment895126202" "--name" "nf-8c58a5ec7ae728626e402bb51e6296cf-stage" "--network" "pipelines" "-v" "/mnt/disks/nf-pipeline-work:/:rslave" "-v" "/var/lib/pipelines/google:/google:ro,rslave" "google/cloud-sdk:alpine" "bash" "-c" "mkdir -p /8c/58a5ec7ae728626e402bb51e6296cf; (echo start | gsutil -q cp  -c - gs://nextflow.command.begin || true; gsutil -m -q cp gs\\://nextflow.command.sh .command.sh; gsutil -m -q cp gs\\://nextflow.command.run .command.run) 2>&1 > .command.log"]: exit status 125 (standard error: "docker: Error response from daemon: invalid volume specification: '/mnt/disks/nf-pipeline-work:/:rslave': invalid mount config for type \"bind\": invalid specification: destination can't be '/'.\nSee 'docker run --help'.\n")
```

### Steps to reproduce the problem

Dockerfile:
```
FROM ubuntu:14.04
RUN mkdir /app
COPY printMessage.sh /
```

printMessage.sh file: 

```
#!/bin/bash
echo $1
```
NextFlow File (main.rf):

```
#!/usr/bin/env nextflow
LETTERS = Channel.from(['A','B'])
process PrintMessage {
    input:
	val(x) from LETTERS
    output:
	stdout result

    """
    bash /printMessage.sh ${x}
    """
}

result.subscribe {
    println it.trim()
}
```

NextFlow Configuration file:
```
process {
	container = 'container/name'
	executor = 'google-pipelines'
}

docker {
       enabled = true
}
cloud{
	instanceType = 'n1-standard-1'
}
google {
    project = 'project name'
    zone = 'us-west1-a'
}
```

### Environment 

* Nextflow version: NXF_VER=18.12.0-edge 
* Operating system: Docker and Google Cloud API

### Additional context

[_nextflow.log](https://github.com/nextflow-io/nextflow/files/2843902/_nextflow.log)

**Comment by pditommaso** [comment]
Try using specifying a sub-directory in the working bucket e.g. gs://bucket/work. Also make sure you are able to list/read/write that path with `gsutil` tool.

Please add the new .nextflow.log if continues to fail.

**Comment by mahdi-b** [comment]
Creating a sub-directory in the working bucket solves the problem! Would you mind explaining what you think was causing the issue?

**Comment by pditommaso** [comment]
It happens because the subdirectory structure is used to create the task scratch work directory in hte cloud instance. I will add a note in the documentation.
