### ISSUE TITLE
maxForks incompatible with storeDir?

### ISSUE THREAD

**Issue by pinin4fjords** [nextflow-io/nextflow#1026]
## Bug report 

When running Nexflow, defining maxForks as well as storeDir for a channel, only the first <maxForks> runs of the process work. Further actions are skipped with messages like:

```
[skipping] Stored process > download_fastqs (656)
```

### Expected behavior and actual behavior

When specifying maxForks and storeDir, I expect all actions for channel to complete (<maxForks> at a time), with all results going to permanent cache in <storeDir>

### Steps to reproduce the problem

Use maxForks with a value lower than the number of process executions, specify storeDir, and observe the skipping

### Program output 

Lines like:

```
[skipping] Stored process > download_fastqs (660)
[skipping] Stored process > download_fastqs (661)
[skipping] Stored process > download_fastqs (662)
[skipping] Stored process > download_fastqs (663)
[skipping] Stored process > download_fastqs (664)
[skipping] Stored process > download_fastqs (665)
```

### Environment 

* Nextflow version: version 19.01.0 
* Java version: openjdk 10.0.2 
* Operating system: linux

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Can you provide a snippet replicating the problem ?

**Comment by pinin4fjords** [comment]
@pditommaso , sorry, I'm a bit short on time for making a fully reproducible example outside of our things. But here is the process definition:

```
process download_fastqs {
    
    maxForks 8
    storeDir "$SCXA_DATA/raw_data/${params.name}"

    input:
        set runId, runFastq from FASTQ_RUNS
    
    output:
        set val(runId), file("${runId}_1.fastq.gz") optional true into DOWNLOADED_FASTQS_R1
        set val(runId), file("${runId}_2.fastq.gz") optional true into DOWNLOADED_FASTQS_R2
        set val(runId), file("${runId}.fastq.gz") optional true into DOWNLOADED_FASTQS_UNPAIRED

    """
        ${params.software.srr_download} ${runFastq}
    """
}
```

FASTQ_RUNS is a channel with ENA run IDs. In this case you just get 8 downloads, however many runs are in FASTQ_RUNS.

**Comment by pditommaso** [comment]
You need to guarantee an unique storeDir path for each run, for example, using the `runId` in the storeDir path.

**Comment by pinin4fjords** [comment]
Ahh, I see, thanks
