### ISSUE TITLE
No re-submit despite errorStrategy 'retry'

### ISSUE THREAD

**Issue by bosterholz** [nextflow-io/nextflow#103]
Hi,

my process code looks like this:

```
process getFasta {

    cpus 4
    time '30m'
    memory '4 GB'
    errorStrategy 'retry'
    maxRetries 4

    input:
    val contigLine from uniq_lines
    
    output:
    file 'uniq_out'
    file 'cut_faa'
    
    script:
    """
    #!/bin/sh
    $PYTHON ${baseDir}/scripts/getFasta.py --i "${contigLine}" --g "${genomeFaa}" --b "$baseDir"
    """  

}
```
some times this process fails and should be re-submitted. But when I look at the .log file, that didn't happen. What did I do wrong ?
 
[.nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/95998/default.nextflow.log.txt)
[trace.csv.txt](https://github.com/nextflow-io/nextflow/files/95999/trace.csv.txt)

**Comment by pditommaso** [comment]
Actually the log file shows this line: 

    :
    [5f/be454a] Re-submitted process > getFasta (10)

Thus it retries to execute it again. However it's true that it should try execute it more times, not only 2.

Do you set the `maxErrors` in a nextflow configuration file?

**Comment by bosterholz** [comment]
No, the documentation said that the `maxErrors` default value should be three. The above case was the first time that I ever saw him re-submit. So, I always thought that three should be enough because he should try at least one additional time.
I launched a run with `process.maxErrors = 10` just now. If that was the problem, it would be great.

**Comment by pditommaso** [comment]
You can even disable the `maxErrors` limit setting it to `-1`

**Comment by pditommaso** [comment]
I'm assuming that you have solved the problem. Feel free to reopen this issue if it is not the case.
