### ISSUE TITLE
Inconsistent `projectDir` return path

### ISSUE THREAD

**Issue by huguesfontenelle** [nextflow-io/nextflow#1037]
## Bug report 

The the nextflow script is in a subfolder, the `workflow.projectDir` property returns a different path, depending if the pipeline is ran locally or remotely.

### Expected behavior and actual behavior

When ran locally, projectDir includes the **subfolder** (here named `pipelines`); when ran remotely, projectDir returns the **root** folder.
Example:
- locally: `/Users/hugues/learn/bug_nextflow_projectDir/pipelines`
- remotely: `/Users/hugues/.nextflow/assets/huguesfontenelle/bug_nextflow_projectDir`(doesn't include `pipelines`)

### Steps to reproduce the problem

I wrote a test.nf (in the `pipelines` subfolder) that prints out diverse workflow objects:
https://github.com/huguesfontenelle/bug_nextflow_projectDir

### Program output 

**locally**
```
$ git checkout huguesfontenelle/bug_nextflow_projectDir
$ cd bug_nextflow_projectDir
$ nextflow run pipelines/test.nf
N E X T F L O W  ~  version 19.01.0
Launching `pipelines/test.nf` [distracted_galileo] - revision: 61cdfe87d7
scriptFile: /Users/hugues/learn/bug_nextflow_projectDir/pipelines/test.nf
projectDir: /Users/hugues/learn/bug_nextflow_projectDir/pipelines
launchDir: /Users/hugues/learn/bug_nextflow_projectDir
workDir: /Users/hugues/learn/bug_nextflow_projectDir/work
```

**remotely**
```
$nextflow run huguesfontenelle/bug_nextflow_projectDir/pipelines/test.nf
N E X T F L O W  ~  version 19.01.0
Pulling huguesfontenelle/bug_nextflow_projectDir ...
 downloaded from https://github.com/huguesfontenelle/bug_nextflow_projectDir.git
Launching `huguesfontenelle/bug_nextflow_projectDir` [condescending_northcutt] - revision: 3737ebf617 [master]
scriptFile: /Users/hugues/.nextflow/assets/huguesfontenelle/bug_nextflow_projectDir/pipelines/test.nf
projectDir: /Users/hugues/.nextflow/assets/huguesfontenelle/bug_nextflow_projectDir
launchDir: /Users/hugues/learn/bug_nextflow_projectDir
workDir: /Users/hugues/learn/bug_nextflow_projectDir/work
```

### Environment 

* Nextflow version: 19.01.0
* Java version: 11.0.2
* Operating system: macOS

### Additional context

I went bug hunting this morning and couldn't find anything more serious, sorry ;-)
I guess it's _LowPri_.

**Comment by pditommaso** [comment]
Thanks for reporting this. I will check it.
