### ISSUE TITLE
when evaluated after input?

### ISSUE THREAD

**Issue by lucidv01d** [nextflow-io/nextflow#104]
I have a situation where a parameter switch determines if process A, process B, or both processes run. Afterwards (and for any case) I'd like to run a post process just once. I'm having trouble implementing this in nextflow, but came up with the following solution:

```
process A {
	echo true

	output:
	val 'A' into a_done

	when:
	params.type == "A" || params.type == "AB"

	shell:
	'''
	echo "A running"
	'''
}

process B {
	echo true

	output:
	val 'B' into b_done

	when:
	params.type == "B" || params.type == "AB"

	shell:
	'''
	echo "B running"
	'''
}



process postProcess {
	echo true

	input:
	val a_done
	val b_done

	when:
	params.type == "AB"

	shell:
	'''
	echo "Post process AB"
	'''
}

process postProcessA {
	echo true

	input:
	val a_done

	when:
	params.type == "A"

	shell:
	'''
	echo "Post process A"
	'''
}


process postProcessB {
	echo true

	input:
	val b_done

	when:
	params.type == "B"

	shell:
	'''
	echo "Post process B"
	'''
}
```

In this example, the three postProcess functions should handle each of the three run situations:
```
nextflow run test.nf --type A
nextflow run test.nf --type B
nextflow run test.nf --type AB
```

However, nextflow hangs, presumably because the post processes are waiting for input on their channels. I was wondering if there was a clean way of doing this without having to do complicated channel splits and duplications. One suggestion is to have the **when** clause evaluate before **input**, but I don't know if this is ideal. 

Obviously this is an abuse of nextflow and not an important issue, but I was just curious if there is an easy workaround. 

Thanks!

**Comment by pditommaso** [comment]
Your code it's almost correct. It hangs because you are using `a_done` twice as input in two different processes and this is not allowed (the same for `b_done`).

The `when` clause is implicitly evaluated after the input (independently if you write before or after it)

**Comment by lucidv01d** [comment]
Cool, thanks!
