### ISSUE TITLE
Private gitlab and kuberun

### ISSUE THREAD

**Issue by KevinSayers** [nextflow-io/nextflow#1040]
### Expected behavior and actual behavior

After putting private **Gitlab** credentials in SCM file I am able to run locally pulling from this repository, but when used with `kuberun` I receive an error that the **Github** repository does not exist.

The kuberun command should still be able to use the credentials in the SCM file to pull from private Gitlab repositories. 

### Steps to reproduce the problem

Run a workflow from a private gitlab server using `kuberun`.

### Program output 

```
N E X T F L O W  ~  version 19.01.0
Pulling biwg/helloworld ...
Cannot find `biwg/helloworld` -- Make sure exists a GitHub repository at this address `https://github.com/biwg/helloworld`
```

Relevant portion from trace:

```
Feb-19 15:54:59.008 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.01.0
Feb-19 15:55:00.022 [main] INFO  nextflow.cli.CmdRun - Pulling biwg/helloworld ...
Feb-19 15:55:00.027 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/biwg/helloworld/contents/nextflow.config
Feb-19 15:55:00.483 [main] DEBUG nextflow.scm.AssetManager - Project manifest does not exist: https://api.github.com/repos/biwg/helloworld/contents/nextflow.config
Feb-19 15:55:00.501 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/biwg/helloworld/contents/main.nf
Feb-19 15:55:00.674 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/biwg/helloworld
Feb-19 15:55:00.887 [main] DEBUG nextflow.cli.Launcher - Operation aborted
java.io.FileNotFoundException: https://api.github.com/repos/biwg/helloworld
```

### Environment 

* Nextflow version: 19.01.0
* Java version: 1.8
* Operating system: Ubuntu

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
These are the best issues :D
