### ISSUE TITLE
.buffer on large amount of input results in NullPointerException

### ISSUE THREAD

**Issue by glormph** [nextflow-io/nextflow#1048]
### Expected behavior and actual behavior

Expected: channel is buffered without problems no matter how many inputs.
Actual: at a large amount of inputs, nextflow errors with `NullPointerException`

### Steps to reproduce the problem

The following script runs only with a lower `--value`, e.g. 10. Otherwise it errors.
```
params.value = 2500

Channel
  .from(0..params.value)
  .tap{ collector }
  .count()
  .set{ amount }

collector
  .buffer(size: amount.value )
```

### Program output 

```
$ nextflow run test_error.nf
N E X T F L O W  ~  version 19.01.0
Launching `test_error.nf` [condescending_thompson] - revision: 39b255af5c
ERROR ~ Unexpected error [NullPointerException]

 -- Check script 'test_error.nf' at line: 9 or see '.nextflow.log' file for more details
```

### Environment 

* Nextflow version: [19.01.0] 
* Java version: [OpenJDK 10.0.2]
* Operating system: [Linux]
* 250G RAM

**Comment by glormph** [comment]
[.nextflow.log](https://github.com/nextflow-io/nextflow/files/2904144/nextflow.log)

**Comment by pditommaso** [comment]
Emm .. I guess you wanted to write 

```
collector
  .buffer(size: params.value )
``` 

not `amount.value`

**Comment by glormph** [comment]
Ah yes you can do that here of course. This script is a bit reduced from the original, where the input was not a range of numbers but files from a path.

**Comment by pditommaso** [comment]
Without a test case can't help 🤷‍♂️

**Comment by glormph** [comment]
I thought this was the test case?

If I do:
```
Channel
  .from(0..params.value)
  .tap{ collector }
  .count()
  .view()
  .set{ amount }

println(amount.value)
```

`.view()` returns the correct amount (for high numbers), whereas the `println` call returns `null`.
This does not happen with `--params 10`.

**Comment by pditommaso** [comment]
`amount.value` is not a proper attribute of a channel. I'm surprised that's working in this snippet.

**Comment by glormph** [comment]
Ah, thanks, didnt know that 🤦‍♂️  

I'll have to figure out how to access the value of a value channel in another way then.
