### ISSUE TITLE
k8s appears not to honour serviceAccount (OpenShift)

### ISSUE THREAD

**Issue by alanbchristie** [nextflow-io/nextflow#1049]
## Bug report 

Launching Pods in an OpenShift (kubernetes) environment with the k8s config, the spawned pods do not appear to honour the `serviceAccount` property. Although there's evidence that nextflow is picking up the config the launched pods have `serviceAccount` and `serviceAccountName` set to  `default`

### Expected behavior and actual behavior

When provided with the following configuration: -

```
k8s {
  storageClaimName = 'squonk-work-dir-pvc'
  storageMountPath = '/squonk/work/docker'
  storageSubPath = 'be66471d-1cfa-4b1f-9c99-c3f181c597b8'
  serviceAccount = 'squonk'
  debug.yaml = true
}
```

I would expect the launched pod specs to be: -

```
spec:
  serviceAccount: squonk
  serviceAccountName: squonk
```

Instead this is used:

```
spec:
  serviceAccount: default
  serviceAccountName: default
```

### Steps to reproduce the problem

In an OpenShift execution environment run nextflow using `k8s` config that sets `serviceAccount`.

### Program output 

Nextflow does not fail, but the launched pods use the incorrect (default) service account.

### Environment 

* Nextflow container image: [informaticsmatters/nextflow:18.10.1]
* Nextflow version: [18.10.1] 
* Java version: [1.8.0_191]
* Operating system: [OpenShift OKD 3.11]

### Additional context

[nf.log](https://github.com/nextflow-io/nextflow/files/2905289/nf.log)
[pod.txt](https://github.com/nextflow-io/nextflow/files/2905305/pod.txt)

**Comment by pditommaso** [comment]
Could you try with latest edge release:

```
NXF_VER=19.02.0-edge nextflow run/kuberun .. etc
```

**Comment by alanbchristie** [comment]
The pods launched with `Version: 19.02.0-edge build 5055` still apply the default SA. Just to be clear ... the pods run, there are no errors, so nothing critical but the Pod service account is not what I expect.

**Comment by pditommaso** [comment]
Solved in the master
