### ISSUE TITLE
Value of Nextflow channel evaluates to null

### ISSUE THREAD

**Issue by PhilPalmer** [nextflow-io/nextflow#1052]
### Expected behavior and actual behavior

I have this script: 
```nextflow
#!/usr/bin/env nextflow

params.intervals = false

if (params.intervals) {
    Channel.fromPath(params.intervals)
           .ifEmpty { exit 1, "Interval list file for HaplotypeCaller not found: ${params.intervals}" }
           .splitText()
           .map { it -> it.trim() as Path }
           .into { interval_list; intervals; count_intervals }
}


n_intervals = count_intervals.count().value.toInteger()
println n_intervals
```

When I run it locally on my mac it runs successfult & returns:
```
Unable to find any JVMs matching version "1.8".
N E X T F L O W  ~  version 18.10.1
Launching `main.nf` [golden_raman] - revision: 28b001fc56
3
2.7 GB
```

When I run it on an EC2 instance it returns:
```
N E X T F L O W  ~  version 19.01.0
Launching `main.nf` [romantic_albattani] - revision: 310b2e8eec
ERROR ~ Cannot invoke method toInteger() on null object

 -- Check script 'main.nf' at line: 14 or see '.nextflow.log' file for more details
```

If I print the value of `count_intervals.count()` I get `DataflowVariable(value=3)`. However then when I add `.value` it returns `null`. This only occurs on the EC2 instance. Do you know what is causing this behaviour? I tested it with the older version of Nextflow and still get the problem. So I don't think the issue is caused by the different Nextflow versions. I think its more likely another problem I am causing between the two different environments. Presumably, there shouldn't be a problem with the channel being consumed because its a value channel. Any ideas?

### Steps to reproduce the problem

1) Save scirpt above 
2) Run script 
```
nextflow run main.nf --intervals testdata/intervals.interval_list
```

### Program output 

[nextflow.log](https://github.com/nextflow-io/nextflow/files/2909993/nextflow.log)

### Environment 

* Nextflow version: 18.10.1 & 19.01.0
* Java version: [?]
* Operating system: macOS & Linux

### Additional context

Any ideas whats causing the problem? 

Any help would be much appreciated. Thanks in advance

EDIT: I think the problem may have been because the `as Path` in the mapping that caused the values to be treated as files. This then meant that the channel was a queue channel meaning it was consumed.

I ended up using this to acheive the same effect though:
```nextflow
n_intervals = 0
intervals_file = file(params.intervals)
intervals_file.eachLine { n_intervals++ }
```

**Comment by mohammedkhalfan** [comment]
I'm facing this same issue. Creating an iterator to track count is not ideal. How to we assign the value from count() to a variable? Suggest to re-open issue.

**Comment by pa-beaufort** [comment]
Hello, I encounter the same issue in a different context. I have value evaluated to null.

**Comment by bentsherman** [comment]
`.value` and `.getVal()` don't work anymore. the `count` operator returns a value channel, so you must use something like `map` or `subscribe` to access the count value.
