### ISSUE TITLE
file access to pulic s3 bucket fails when checkIfExists: true

### ISSUE THREAD

**Issue by sb43** [nextflow-io/nextflow#1055]
### Expected behavior and actual behavior

testfile = Channel.fromPath("s3://ref/test/genome.fa.fai", checkIfExists: true)
Mar-01 11:56:36.524 [PathVisitor-1] ERROR nextflow.Channel - null (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID:-XXXXXX -default; S3 Extended Request ID: 144c2bfe-default-default)

When using private s3 bucket file access works with both true and false.
When checkIfExists: false it works fine.

### Steps to reproduce the problem
cat test.nf
testfile = Channel.fromPath("s3://ref/test/genome.fa.fai", checkIfExists: true)

nextflow run test.nf

### Program output 

Mar-01 12:28:14.810 [PathVisitor-1] ERROR nextflow.Channel - null (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: tx000000000000003e8cd66-005c79255e-13d7a414-default; S3 Extended Request ID: 13d7a414-default-default)
com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: tx000000000000003e8cd66-005c79255e-13d7a414-default; S3 Extended Request ID: 13d7a414-default-default)
### Environment 

* Nextflow version: 19.01.0.5050
* Java version: [?]
* Operating system: [ Linux]

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Closing in favour of https://github.com/nextflow-io/nextflow-s3fs/issues/14
