### ISSUE TITLE
Improve DAG rendering

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#1056]
## Scenario 
Nextflow supports the rendering of the workflow DAG either in html and Graphviz DOT, which in turns allows the generation in several other formats including pdf, svg, png, etc. 

However the current implementation provides a very basic pictorial representational and does not clearly represents some important elements such as inputs and outputs. See an example below:

![dag](https://user-images.githubusercontent.com/816968/53697338-ab6c3c80-3dd0-11e9-9b97-826f7e337b9a.png)

Moreover it does not allows the DAG rending without fully execute the workflow application.  

## Deliverable  

The goal of this enhancement is to improve the Nextflow DAG rendering so that: 
1. inputs and outputs are grouped together and more easily identifiable
2. use a color code to better highlight different workflow components 
3. render sub-workflows and custom function/operators implemented in the new dsl 
4. allow interactive navigation of the graph when the DAG is rendered in HTML format.
5. report the number of executed tasks for each node (see #1025)
6. add the ability to render the DAG without the need to run the workflow application (dry run mode)

The resulting graph should be compatible at pictorial level with the DAG generated by the [CWL viewer](https://view.commonwl.org/), for example: 

<img width="742" alt="screenshot 2019-03-03 at 16 44 47" src="https://user-images.githubusercontent.com/816968/53697638-b379ab80-3dd3-11e9-98df-af05e5509a20.png">

**Comment by heuermh** [comment]
Small typo: Moreover it does now &rarr; Moreover it does not

I'm interested in producing an interactive version of this graph in [Cytoscape](https://cytoscape.org/), but I understand thick clients aren't really in vogue any more.  Since this issue is linked to from the GSoC page, let me know if this comment is out of scope and I'll delete it.

**Comment by pditommaso** [comment]
The html dag rendering already uses Cytoscape. What's your plan improve it? I would suggest a separate issue tho. 

> Small typo

Fixed. Thanks!

**Comment by pditommaso** [comment]
Interesting library for graph rendering https://github.com/kieler/elkjs/

**Comment by sfehrmann** [comment]
Might [PlantUML](https://plantuml.com/) support what you're looking for? Especially the deployment section is quite powerful, though I got the job done with the object representation (for internal use, that is)

**Comment by lukbut** [comment]
This would be beneficial for us as our engineers value this graphical representation of workflow definitions

**Comment by bentsherman** [comment]
Made some headway on this effort today. I took the workflow diagram for nf-core/fetchngs (because it is relatively small) and modified it by hand as follows:

- remove operator nodes and channel annotations, show only empty nodes for branching
- add subgraph for each workflow
- add subgraphs for workflow inputs and outputs

Already it's a huge improvement, and I think I can automate it without modifying the DAG. Next step would be to better annotate the workflow inputs and outputs, maybe keep some of the process input/output channel labels as well. I would like to be able to click on subworkflows to collapse/expand them. Mermaid has some support for [interactivity](https://mermaid.js.org/syntax/flowchart.html#interaction), but haven't used it before.

Once I automate this part, then I'll try it on rnaseq and sarek 😄 

Before:
```mermaid
flowchart TD
    p0[Channel.from]
    p1([splitCsv])
    p2([map])
    p3([unique])
    p4[Channel.empty]
    p5[ ]
    p6([NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO])
    p7([first])
    p8([mix])
    p9([NFCORE_FETCHNGS:SRA:SRA_RUNINFO_TO_FTP])
    p10([first])
    p11([mix])
    p12([splitCsv])
    p13([map])
    p14([unique])
    p15([first])
    p16([mix])
    p17([map])
    p18([branch])
    p19([NFCORE_FETCHNGS:SRA:SRA_FASTQ_FTP])
    p20(( ))
    p21([first])
    p22([mix])
    p23([map])
    p24[Channel.empty]
    p25([NFCORE_FETCHNGS:SRA:FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:CUSTOM_SRATOOLSNCBISETTINGS])
    p26([mix])
    p27[ ]
    p28([NFCORE_FETCHNGS:SRA:FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:SRATOOLS_PREFETCH])
    p29([first])
    p30([mix])
    p31[ ]
    p32([NFCORE_FETCHNGS:SRA:FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:SRATOOLS_FASTERQDUMP])
    p33([first])
    p34([mix])
    p35([first])
    p36([mix])
    p37([mix])
    p38([map])
    p39[ ]
    p40[ ]
    p41[ ]
    p42([NFCORE_FETCHNGS:SRA:SRA_TO_SAMPLESHEET])
    p43([collect])
    p44([collect])
    p45([NFCORE_FETCHNGS:SRA:SRA_MERGE_SAMPLESHEET])
    p46(( ))
    p47([mix])
    p48([NFCORE_FETCHNGS:SRA:MULTIQC_MAPPINGS_CONFIG])
    p49(( ))
    p50([mix])
    p51([unique])
    p52([collectFile])
    p53([NFCORE_FETCHNGS:SRA:CUSTOM_DUMPSOFTWAREVERSIONS])
    p54(( ))
    p55(( ))
    p56(( ))
    p0 --> p1
    p1 --> p2
    p2 --> p3
    p3 -->|ids| p6
    p4 -->|ch_versions| p8
    p5 -->|fields| p6
    p6 --> p9
    p6 --> p7
    p7 --> p8
    p8 -->|ch_versions| p11
    p9 --> p12
    p9 --> p10
    p10 --> p11
    p11 -->|ch_versions| p16
    p12 --> p13
    p13 --> p14
    p14 -->|ch_sra_metadata| p17
    p9 --> p15
    p15 --> p16
    p16 -->|ch_versions| p22
    p17 --> p18
    p18 --> p23
    p18 --> p19
    p19 --> p37
    p19 --> p20
    p19 --> p21
    p21 --> p22
    p22 -->|ch_versions| p36
    p23 -->|ch_sra_ids| p28
    p24 -->|ch_versions| p26
    p25 -->|ch_ncbi_settings| p28
    p25 --> p26
    p26 -->|ch_versions| p30
    p27 -->|certificate| p28
    p28 --> p32
    p28 --> p29
    p29 --> p30
    p30 -->|ch_versions| p34
    p25 -->|ch_ncbi_settings| p32
    p31 -->|certificate| p32
    p32 -->|reads| p37
    p32 --> p33
    p33 --> p34
    p34 -->|versions| p35
    p35 --> p36
    p36 -->|ch_versions| p47
    p37 --> p38
    p38 -->|ch_sra_metadata| p42
    p39 -->|pipeline| p42
    p40 -->|strandedness| p42
    p41 -->|mapping_fields| p42
    p42 --> p43
    p42 --> p44
    p43 --> p45
    p44 --> p45
    p45 --> p46
    p45 --> p48
    p45 --> p47
    p47 -->|ch_versions| p50
    p48 --> p49
    p48 --> p50
    p50 -->|ch_versions| p51
    p51 --> p52
    p52 --> p53
    p53 --> p56
    p53 --> p55
    p53 --> p54
```

After:
```mermaid
flowchart TD
    subgraph inputs
    p0[Channel.from]
    p5(( ))
    p27(( ))
    p31(( ))
    p39(( ))
    p40(( ))
    p41(( ))
    end

    subgraph outputs
    p20(( ))
    p46(( ))
    p49(( ))
    p54(( ))
    p55(( ))
    p56(( ))
    end

    subgraph NFCORE_FETCHNGS
    subgraph SRA
    p6([SRA_IDS_TO_RUNINFO])
    p9([SRA_RUNINFO_TO_FTP])
    p18(( ))
    p19([SRA_FASTQ_FTP])
    p37(( ))
    p42([SRA_TO_SAMPLESHEET])
    p45([SRA_MERGE_SAMPLESHEET])
    p48([MULTIQC_MAPPINGS_CONFIG])
    p50(( ))
    p53([CUSTOM_DUMPSOFTWAREVERSIONS])
    subgraph FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS
    p25([CUSTOM_SRATOOLSNCBISETTINGS])
    p28([SRATOOLS_PREFETCH])
    p32([SRATOOLS_FASTERQDUMP])
    end
    p0 -->|ids| p6
    p5 -->|fields| p6
    p6 --> p9
    p6 --> p50
    p9 --> p18
    p9 --> p50
    p18 --> p28
    p18 --> p19
    p19 --> p37
    p19 --> p20
    p19 --> p50
    p25 --> p28
    p25 --> p50
    p27 -->|certificate| p28
    p28 --> p32
    p28 --> p50
    p25 --> p32
    p31 -->|certificate| p32
    p32 --> p37
    p32 --> p50
    p37 --> p42
    p39 -->|pipeline| p42
    p40 -->|strandedness| p42
    p41 -->|mapping_fields| p42
    p42 --> p45
    p45 --> p46
    p45 --> p48
    p45 --> p50
    p48 --> p49
    p48 --> p50
    p50 --> p53
    p53 --> p54
    p53 --> p55
    p53 --> p56
    end
    end
```
