### ISSUE TITLE
Apache Ignite - Nextflow hangs when two workflows are executed

### ISSUE THREAD

**Issue by evanfloden** [nextflow-io/nextflow#1057]
### Expected behavior and actual behavior

Nextflow hangs when two workflows are executed using Apache Ignite.  

### Steps to reproduce the problem

Start Ignite:
```
nextflow node
```

Start first workflow:
```
nextflow run nextflow-io/rnaseq-nf -process.executor ignite -with-docker
```
then second
```
nextflow run nextflow-io/rnaseq-nf -process.executor ignite -with-docker
```

The second run will hang indefinitely.

### Program output 

N/A

### Environment 

* Nextflow version: 18.10
* Java version: openjdk version "1.8.0_121"
* Operating system: macOS

### Additional context

N/A

**Comment by pditommaso** [comment]
This is not a bug, when launching separate instance in the same node a unique multicast IP address should be provided otherwise they will try to join the same cluster e.g. 

```
export NXF_CLUSTER_SEED=$(shuf -i 0-16777216 -n 1)
```

**Comment by tdudgeon** [comment]
This is not working for me, but then I don't fully understand what is happening.
I'm using a shared directory for discovery, not IP multicast.
For each independent execution of `nextflow run ...` I have set the  `NXF_CLUSTER_SEED` env variable to a random value.
I still get the same behaviour - the first workflow executes to completion. 
If the second workflow is started whilst the first one is running then the first task gets submitted but never completes. Even after workflow 1 completes.

**Comment by pditommaso** [comment]
> I'm using a shared directory for discovery, not IP multicast.

Are you specifying a different directory for discovery, for each different run?

**Comment by tdudgeon** [comment]
No. I'm hoping I can have a permanently running set of servers running the nextfow background process and then just throw workflows at them. Having to jump onto every server and start a new nextfow background process for every workflow (and then stop them after completion) would be pretty painful.

**Comment by pditommaso** [comment]
> No

You have to.

**Comment by tdudgeon** [comment]
So Ignite does not seem to be a very useful executor?
Ignite looked nice as it was built into Nextflow. But if I need to use a different one then which one?
Ideally should be simple to deploy and configure. And must allow multiple workflows to run simultaneously, preferably allowing different priorities.

**Comment by pditommaso** [comment]
Tim, was designed to work with a cloud transient VM instances. Moreover I don't see what the big issue in creating a unique folder in the shared file system to share the cluster status?

**Comment by tdudgeon** [comment]
That's not the problem, it's having to ssh onto each node to run the `nextflow node -bg -cluster.join path:$HOME/cluster/xyz` command before executing the workflow, and then having to ssh again after completion to shut it down.
Just running with executor like `sge` seems so much simpler.

**Comment by pditommaso** [comment]
Likely, Unive posted a nice post at this regard.

**Comment by tdudgeon** [comment]
Yes, but I need an open source (or a least free to use) option. Any experiences with what works best and is easy to setup and use?

**Comment by pditommaso** [comment]
Maybe Amazon ParallelCluster? or there was a tool named EasyCluster if I'm not wrong.

**Comment by pditommaso** [comment]
I'm concluding that NF was hanging because a unique path was not specified. Feel free to comment or reopen if needed.
