### ISSUE TITLE
Setting up Google Cloud Credentials

### ISSUE THREAD

**Issue by ecerami** [nextflow-io/nextflow#1059]
I am following the documentation here:  https://www.nextflow.io/docs/edge/google.html, to set up NextFlow to run on Google Genomics API.

The documentation has a section on "Credentials", and describes how to set up a service account.  But, it's not clear to me which specific roles I should assign to my service key.  I tried to enable all the options under Google Genomics API and Google Storage, but I still get:

```
ERROR ~ Error executing process > 'convertSam2Bam (1)'
Caused by:
  403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "The caller does not have permission",
    "reason" : "forbidden"
  } ],
  "message" : "The caller does not have permission",
  "status" : "PERMISSION_DENIED"
}
```
Any advice most welcome!

**Comment by pditommaso** [comment]
Google Cloud IAM permission is quite tricky. The only advice I can give is to make sure you are able to able to access the required Google Storage bucket using the `gsutil` tool.

**Comment by pditommaso** [comment]
Closing this in favour of #1068
