### ISSUE TITLE
trace.csv is not a csv file (it is tab-separated)

### ISSUE THREAD

**Issue by dctrud** [nextflow-io/nextflow#106]
The file `trace.csv` produced by `-enable-trace` is not a comma-separated CSV file. The content is tab-separated. This is confusing when opening into Excel / R etc. especially any tool which is going to guess the format from the extension. Extension should reflect the content.

Could it either become `trace.[tsv|tab|txt]`, or be output in CSV comma-separated format?

**Comment by pditommaso** [comment]
You are right, we should change the extension to `tsv` or `txt`. However the separator character is configurable using the `trace.sep` configuration property as described in the doc. 

http://www.nextflow.io/docs/latest/config.html#scope-trace

**Comment by pditommaso** [comment]
Fixed in version 0.17.2
