### ISSUE TITLE
Execute file permissions are lost when using nextflow clone in nextflow Docker image

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1060]
### Expected behavior and actual behavior

Downloading a nextflow pipeline via `nextflow clone` should preserve file permissions from the git repo (such as executable scripts). However, when using the `nextflow/nextflow` Docker image, the execute permissions are lost. This causes issues particularly with `nextflow kuberun`, which uses this Docker image to pull the nextflow pipeline to a k8s cluster and then run the pipeline.

### Steps to reproduce the problem

```bash
docker run --rm -it nextflow/nextflow bash
> nextflow clone systemsgenetics/GEMmaker
> ls -l GEMmaker/bin
```

You will see that the scripts in this directory have lost their execute permissions. When I run these commands in my Ubuntu environment, I don't have this issue.

### Program output 

Expected output:
```bash
$ ls -l GEMmaker/bin/
total 28
-rwxrwxr-x 1 root root 2976 Mar  5 11:42 create-gem.py
-rwxrwxr-x 1 root root  410 Mar  5 11:42 irods-load.sh
-rwxrwxr-x 1 root root  409 Mar  5 11:42 irods-save.sh
-rwxrwxr-x 1 root root 9148 Mar  5 11:42 retrieve-sra-metadata.py
-rwxrwxr-x 1 root root 2570 Mar  5 11:42 split-sra-ids.py
```

Actual (incorrect) output:
```bash
$ ls -l GEMmaker/bin/
total 28
-rw-r--r-- 1 root root 2976 Mar  5 16:47 create-gem.py
-rw-r--r-- 1 root root  410 Mar  5 16:47 irods-load.sh
-rw-r--r-- 1 root root  409 Mar  5 16:47 irods-save.sh
-rw-r--r-- 1 root root 9409 Mar  5 16:47 retrieve_sra_metadata.py
-rw-r--r-- 1 root root 2570 Mar  5 16:47 split-sra-ids.py
```

### Environment 

Using the latest `nextflow/nextflow` Docker image.

**Comment by pditommaso** [comment]
I guess this is kind of security enforced by K8s. Not sure what's the right thing to do here. Should NF change the permission fo all files the bin folder? it could not a such safe thing.

**Comment by bentsherman** [comment]
I think it's the NF docker image that is the problem, not K8S. The docker image is based on Alpine Linux so the problem may have something to do with Alpine. Additionally, if I clone the repo using git, the file permissions are preserved, even in the docker container:
```bash
apk update && apk add git
git clone https://github.com/SystemsGenetics/GEMmaker.git
```

So I think there must be some elegant way to fix ths. I definitely would rather not brute force the bin directory either.

**Comment by pditommaso** [comment]
> Additionally, if I clone the repo using git, the file permissions are preserved, even in the docker container 

So, not necessarily it's an alpine problem. It could also be an issue of the JGit library used by NF. Anyhow if you identify and different base image fixing the issue, I would be happy to update it.

**Comment by bentsherman** [comment]
Interesting, I just tried to use centos:7 and ubuntu:16.04 as base images, and in both cases the problem still occurs. I think that narrows it down to nextflow itself. With regard to this issue it behaves differently in a container than it does in a native environment. Could be that some dependency is missing. I think that JGit library might be worth looking into.

**Comment by pditommaso** [comment]
Ummm https://www.eclipse.org/forums/index.php/t/1078227/

**Comment by pditommaso** [comment]
OK, I was able to replicate the problem cloning a repo using: 

```
https://repo.eclipse.org/content/groups/releases//org/eclipse/jgit/org.eclipse.jgit.pgm/4.8.0.201706111038-r/org.eclipse.jgit.pgm-4.8.0.201706111038-r.sh
```

Instead the permission are OK using the latest JGit version: 

```
https://repo.eclipse.org/content/groups/releases//org/eclipse/jgit/org.eclipse.jgit.pgm/5.2.1.201812262042-r/org.eclipse.jgit.pgm-5.2.1.201812262042-r.sh
```

**Comment by pditommaso** [comment]
Fixed upgrading JGit to version 5.2

**Comment by Nitin123-4** [comment]
I am facing the same issue. Not able to understand it.
I can see this permission issue with the publish files.

-rw-r--r--  file.bam
-rw-r--r--  example.gvcf
-rw-r--r--  result.txt

**Comment by bentsherman** [comment]
Hi @Nitin123-4 , this issue is very old. Which version of Nextflow are you using?
