### ISSUE TITLE
watchPath() does not work for files added/ updated from a different machine

### ISSUE THREAD

**Issue by pinin4fjords** [nextflow-io/nextflow#1061]
### Expected behavior and actual behavior

Expect that files updated/ added to a directory will trigger watchPath() and downstream operations regardless of the machine from which those updates are made.

Actual behaviour seems to be that file additions/ updates are only noticed when done from the same machine. 

### Steps to reproduce the problem

Make a workflow with a watchDir() like:

```
#!/usr/bin/env nextflow

// Watch the SDRF directory for incoming SDRF files

sdrfDir = '/path/to/sdrf_dir'

Channel
    .watchPath( "${sdrfDir}/*.sdrf.txt", 'create,modify' )
    .subscribe { println "SDRF file: $it" }

...
```
Then test it by adding files to the watched directory a) from the same machine and b) by submitting the 'watcher' Nextflow to a cluster node, and running file updates from the head.

In a) the file additions/ updates are detected, in b) they are not. If you then SSH to the cluster node which is running the watcher, and do file updates there, this will trigger the expected behaviour.

### Environment 

* Nextflow version: 19.03.0-SNAPSHOT.5058
* Java version: openjdk 10.0.2 2018-07-17
* Operating system: Linux

**Comment by pditommaso** [comment]
This depends on the Java [watch api](https://docs.oracle.com/javase/tutorial/essential/io/notification.html#overview) which in turns depends by the file system implementation. On shared file system there may be tricky behaviour. 

I'm labelling as a known issue and for which it would desirable a better implementation.

**Comment by apeltzer** [comment]
Ran into this again as well, can confirm that this is indeed not working on NFS shared network mounts unfortunately as expected. Our pipeline works either via `Channel.fromFile()` or via  `Channel.watchPath()`  - the latter just works on local storage and not on network file systems.

**Comment by pditommaso** [comment]
This is a grey area. NF relies on Java file watch API which in turn relies on POSIX notify events, that not all NFS implementation support (any?) 

https://unix.stackexchange.com/questions/81663/why-are-inotify-events-different-on-an-nfs-mount
