### ISSUE TITLE
NCBI SRA channel factory a.k.a. SRA-Explorer

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#1070]
Inspired by @ewels [SRA-Explorer](https://ewels.github.io/sra-explorer/) I've added a new built-in channel factory to Nextflow that creates a channel emitting the read fastq URLs for a given accession number or project ID. 

For example:

```nextflow
Channel.fromSRA('ERP009109')
```

create a channel emitting the following entries: 

```
[ERR908507, [ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908507/ERR908507_1.fastq.gz, ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908507/ERR908507_2.fastq.gz]]
[ERR908506, [ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908506/ERR908506_1.fastq.gz, ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908506/ERR908506_2.fastq.gz]]
[ERR908505, [ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908505/ERR908505_1.fastq.gz, ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908505/ERR908505_2.fastq.gz]]
[ERR908502, [ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908502/ERR908502_1.fastq.gz, ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908502/ERR908502_2.fastq.gz]]
[ERR908501, [ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908501/ERR908501_1.fastq.gz, ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908501/ERR908501_2.fastq.gz]]
[ERR908500, [ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908500/ERR908500_1.fastq.gz, ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908500/ERR908500_2.fastq.gz]]
[ERR908499, [ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908499/ERR908499_1.fastq.gz, ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908499/ERR908499_2.fastq.gz]]
[ERR908508, [ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908508/ERR908508_1.fastq.gz, ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908508/ERR908508_2.fastq.gz]]
[ERR908504, [ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908504/ERR908504_1.fastq.gz, ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908504/ERR908504_2.fastq.gz]]
[ERR908503, [ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908503/ERR908503_1.fastq.gz, ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR908/ERR908503/ERR908503_2.fastq.gz]]]
```

The channel can then be used as input of any process, which will automatically download the fastq files. 

It could be interesting to extend the `fromSRA` method adding the ability to better filter/select the required reads. Any suggestion in this direction is welcome.

**Comment by evanfloden** [comment]
Fantastic, great addition. 

My only suggestion for this would be to have a way (or provide use case) on how to handle paired and non-paired reads.

**Comment by pditommaso** [comment]
> how to handle paired and non-paired reads

Currently it's implicit in the reads (runs) returned by the api query ie. depending the accession it can return either a single file or pairs. Therefore the method above can return also 

```
[SRR1448795, /vol1/fastq/SRR144/005/SRR1448795/SRR1448795.fastq.gz]
[SRR1448792, /vol1/fastq/SRR144/002/SRR1448792/SRR1448792.fastq.gz]
[SRR1448793, /vol1/fastq/SRR144/003/SRR1448793/SRR1448793.fastq.gz]
[SRR1910483, /vol1/fastq/SRR191/003/SRR1910483/SRR1910483.fastq.gz]
[SRR1910482, /vol1/fastq/SRR191/002/SRR1910482/SRR1910482.fastq.gz]
[SRR1448791, [/vol1/fastq/SRR144/001/SRR1448791/SRR1448791_1.fastq.gz, /vol1/fastq/SRR144/001/SRR1448791/SRR1448791_2.fastq.gz]]
[SRR1448790, [/vol1/fastq/SRR144/000/SRR1448790/SRR1448790_1.fastq.gz, /vol1/fastq/SRR144/000/SRR1448790/SRR1448790_2.fastq.gz]]
```

**Comment by evanfloden** [comment]
Cool. 

I really like the functionality of the explorer, ie being able to browse and select.

Once this is out, let's do a PR request for SRA Explorer that creates an option for the selected samples something like:

### Nextflow channel of FastQ files 

```
Channel
    .fromSRA([SRR1448795, SRR1448792, SRR1448793, SRR1910483, SRR1910482, SRR1448791, SRR1448790])
```

Also, an option to return a map of the metadata would be awesome.

**Comment by ewels** [comment]
Sounds good! I could do a basic `tsv`  of this stuff right away perhaps - then we could just pull this in to nextflow... What do you think?

**Comment by pditommaso** [comment]
Mumble, mumble, maybe it's better to keep it simpler. I was thinking just a copy&paste as in the spirit of the SRA-explorer page.

**Comment by pditommaso** [comment]
@ewels I've noticed that for some accession there's not an related fastq ftp entry. For example: 

https://www.ebi.ac.uk/ena/data/warehouse/filereport?result=read_run&fields=fastq_ftp&accession=SRR7226521

How are you managing this?

**Comment by JoseEspinosa** [comment]
Would it be possible to create a parameter such  as `downloadMode` that by default would be set as  `ftp` but that can be also set to `aspera` to allow the download using the [aspera dowload tool](https://downloads.asperasoft.com/en/downloads/8?list) (as in the SRA explorer)?

**Comment by pditommaso** [comment]
We have opened the pandora box ! 😂

**Comment by pditommaso** [comment]
> Can be also set to aspera to allow the download

Eventually, not doing at this iteration. Sorry jose ;)

**Comment by JoseEspinosa** [comment]
I need to try... 😄

**Comment by pditommaso** [comment]
Added url requests caching, api key, max results options and docs. Available for testing using version `19.03.0-SNAPSHOT`.

**Comment by pinin4fjords** [comment]
This is very cool. Can we have a tweak to get data from EBI /DDBJ instead where requested? So URLs like ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR102/003/SRR1026963/SRR1026963_1.fastq.gz instead of the SRA ones.

**Comment by pditommaso** [comment]
Currently URLs are resolved against [ebi.ac.uk](https://github.com/nextflow-io/nextflow/blob/97d57c96a8632e9576815dd394f3bda0863fa7c7/modules/nextflow/src/main/groovy/nextflow/datasource/SraExplorer.groovy#L256-L269), but other endpoints could be used. I leave this as a community enhancement.

**Comment by pinin4fjords** [comment]
Sorry, yes I skim-read and didn't see that they were EBI already. Good for me already then :-)

**Comment by pditommaso** [comment]
~~European~~ British bias .. 😆

**Comment by ewels** [comment]
> I've noticed that for some accession there's not an related fastq ftp entry. For example:
> 
> https://www.ebi.ac.uk/ena/data/warehouse/filereport?result=read_run&fields=fastq_ftp&accession=SRR7226521
> 
> How are you managing this?

@pditommaso I don't understand sorry - I get a FastQ FTP entry for that link:

```
fastq_ftp
ftp.sra.ebi.ac.uk/vol1/fastq/SRR722/001/SRR7226521/SRR7226521.fastq.gz
```

**Comment by pditommaso** [comment]
Oh, I *was* getting only `fastq_ftp` for that accession and others. Now it looks fine, better!

**Comment by ewels** [comment]
Ok, SRA-Explorer now updated to give full output as TSV / JSON / YAML files. I also added file download buttons and polished a few other bits :) https://ewels.github.io/sra-explorer/

@evanfloden - could add a minimal example of a nextflow channel factory consuming this TSV or something if you like? Let me know.

**Comment by pditommaso** [comment]
@ewels I think you just invented a new bioinformatics database format 😆

**Comment by ewels** [comment]
![standards](https://imgs.xkcd.com/comics/standards.png)

**Comment by drpatelh** [comment]
Thank God for the ENA!

**Comment by pditommaso** [comment]
I think I'll close this first iteration. The file format is nice, but I will add later depending users feedback. it would also be interesting to explore the support for filtering on metadata.

**Comment by ewels** [comment]
I wasn't really expecting you to add parsing for this "file format" to nextflow to be honest. I was more thinking that we could just have an example nextflow snippet on the SRA-explorer website that people could copy if they wanted.

**Comment by pditommaso** [comment]
Indeed, both are good ideas, but it would make sense to add that snippet once this feature is released as stable (likely next month release).
