### ISSUE TITLE
Add ability to check for 'valid' params.

### ISSUE THREAD

**Issue by jfy133** [nextflow-io/nextflow#1074]
## New feature
[Disclaimer: apologies if I get terminology or some concepts wrong, I am reporting this as an end user of nextflow scripts and not a script-writer (at the moment)]

Add the ability to either warn that there is an unassigned parameter, or check across all params supplied by the user.

## Usage scenario 

I encountered an issue when running one of the nf-core pipelines (https://github.com/nf-core/eager/issues/153) that when there was a 'typo' in a particular flag I wanted to turn on, the pipeline essentially 'ignored' the flag and proceeded to run but without the settings the flag was meant to set.

This produced no error nor evidence that that flag (i.e. parameter) was (erroneous) supplied but was not utilised.

A simple fake example:

```
## Runs correctly: param.filter_on 
nextflow run <pipeline> --filter_on

## Missing param but runs anyway with that filter off
nextflow run <pipeline> --filteron
```

Where internally

```
## Runs correctly
param.filter_on = 'true'

## Missing param but runs anyway with that filter off
param.filter_on = 'false'
(param.filteron = 'true') ## this is now assigned but does exist within the nextflow main.nf
```

This issue is very important when you have novice users who are not well-experienced with the command line, or do not have expectations on what the output should look like. They will, most l likely be familiar with the behaviour of most e.g. bash programs which throw an error and help message if there is an unknown flag/option supplied.

## Suggest(ed) implementation 

Either throw a warning if a supplied param is not utilised at any point in the nextflow script

or

Add the functionality along the lines of all of the params supplied by the user are stored in an array or vector, which the script writer can add their own checks.

Copied from https://github.com/nf-core/eager/issues/153#issuecomment-470008443: 
I'm thinking more from my knowledge of R, but assuming somehow all input `params.*` are stored in a single place somewhere (like an array or vector), as `input_params`, and acceptable params in another one called `acceptable_params` :

```
for (input_params in params.*){
  if ( !input_param %in% acceptable_params ){
     cat(paste("Error:", input_param, "is not valid - please check"))
     quit()
  }
} 
```
or bash

```
for i in ${input_params[@]}; do
  if [[ "${input_params[*]}" != "$i" ]]; then
    print "Error " input_params "incorrect. Please check"
 fi
done
```

**Comment by lch14forever** [comment]
I second this for adding internal validation for the parameters. I am using the following snippet at the moment:

```nextflow
def parameters_expected = ['read_path', 'reads', 'outdir', 'help', 
    ...
    ] as Set

...

// Parameters sanity checking
def parameter_diff = params.keySet() - parameters_expected
if (parameter_diff.size() != 0){
   exit 1, "[Pipeline error] Parameter(s) $parameter_diff is/are not valid in the pipeline!\n"
}
```
However, it is a bit messy to hardcode all the expected parameters for the pipeline, especially when there are parameters defined in the config files. I wonder if nextflow provides an API for accessing the parameters defined in the nf scripts and config files only, i.e. excluding parameters provided by the user via command line or -params-file.
