### ISSUE TITLE
Remove potential sensitive environment vars

### ISSUE THREAD

**Issue by rsuchecki** [nextflow-io/nextflow#1075]
### Expected behavior and actual behavior

HTML report uses information from trace to render various statistics. However trace contains information from `env` scope. These are not displayed in the report but are present in the generated HTML file. This may expose sensitive information when sharing execution reports.

### Steps to reproduce the problem

`main.nf`:

```
config.env.SECRET = 'If you want to keep a secret, you must also hide it from yourself - George Orwell, 1984'

process x {
 input:
   val x from 1

  """

  """
}
```

```
nextflow run main.nf -with-report report.html && grep -o 'SECRET.*1984' report.html
```

### Program output 

```
N E X T F L O W  ~  version 19.01.0
Launching `main.nf` [special_albattani] - revision: 420393f557
[warm up] executor > local
[54/414754] Submitted process > x
SECRET=If you want to keep a secret, you must also hide it from yourself - George Orwell, 1984
```

### Environment 

* Nextflow version: 19.01.0 
* Java version: 10
* Operating system: Linux

**Comment by pditommaso** [comment]
Actually I'm not even sure why env vars are embedded in this report?

**Comment by rsuchecki** [comment]
I gather that this is the trace info used to populate most of the report,

https://github.com/nextflow-io/nextflow/blob/a9381f1ba88970b693a8ddf18685c4eaa4d36c00/modules/nextflow/src/main/resources/nextflow/trace/ReportTemplate.html#L337

the only problem is that `env` is included but not used


```
  // Nextflow report data
  window.data = { "trace":[
{"task_id":"1","hash":"3b\/2f7cd5","native_id":"103","process":"x","module":"-","container":"-","tag":"-","name":"x","status":"COMPLETED","exit":"0","submit":"1553055808224","start":"1553055808385","complete":"1553055809857","duration":"1633","realtime":"107","%cpu":"0.0","%mem":"0.0","rss":"0","vmem":"0","peak_rss":"0","peak_vmem":"0","rchar":"0","wchar":"0","syscr":"0","syscw":"0","read_bytes":"0","write_bytes":"0","attempt":"1","workdir":"\/home\/rad\/work\/3b\/2f7cd579d940a952e8e30dc4a5d0be","script":"\n \n  ","scratch":"-","queue":"-","cpus":"1","memory":"-","disk":"-","time":"-","env":"SECRET=If you want to keep a secret, you must also hide it from yourself - George Orwell, 1984\n","error_action":"-"}], "summary":{"x":{"cpu":null,"mem":null,"time":{"mean":107,"min":107,"q1":107,"q2":107,"q3":107,"max":107,"minLabel":"x","maxLabel":"x","q1Label":"x","q2Label":"x","q3Label":"x"},"reads":null,"writes":null,"cpuUsage":null,"memUsage":null,"timeUsage":null}} };
```

**Comment by pditommaso** [comment]
I see, that's the env the tasks. Dropping all the environment doesn't see a good idea. Maybe we should blacklist some expected sentive vars: 

* AWS_SECRET_ACCESS_KEY
* AWS_ACCESS_KEY_ID
* AWS_ACCESS_KEY
* AWS_SECRET_KEY

(append yours)

**Comment by rsuchecki** [comment]
I would say anything that has a `TOKEN` as a sub-string e.g  `GH_TOKEN`

Are you thinking of excluding these from trace or just the report? If just the report, whole `env` could be excluded unless there is a valid case for rendering any of it. I think currently it just sits embedded but not displayed in the report unless I am missing something.

**Comment by pditommaso** [comment]
That's true. It's also retained in the internal cache db. Maybe It should be stripped at that level.

**Comment by pditommaso** [comment]
OK, blacklisted any var whose name matches ^AWS|TOKEN|SECRET
