### ISSUE TITLE
Retry-on-failure / short delay when looking for output files

### ISSUE THREAD

**Issue by photocyte** [nextflow-io/nextflow#1078]
## Retry-on-failure / short delay when looking for output files

After the `.exitcode` file is found, and the Nextflow main program is looking for the output files, add a retry-on-failure / short delay if the output files are not found.

## Usage scenario 

Filesystem caching & a non guarantee of the order-of-appearance of files on NFS can cause the .exitcode file to appear before the output files on a shared network filesystem, even though the .exitcode file was written after the output files.  This leads to a failure.  Nextflow should be robust to such filesystem timing quirks.

## Suggest implementation 

Some suggested implementations can be found in #931

**Comment by tomas-pluskal** [comment]
Since nextFlow already has the executor.exitReadTimeout variable, why not add a similar executor.outputReadTimeout variable for situations when output files are a bit delayed?
