### ISSUE TITLE
Channel operations `toList` followed by `merge` hang

### ISSUE THREAD

**Issue by glormph** [nextflow-io/nextflow#1083]
### Expected behavior and actual behavior

Converting a channel to a list with `toList`, followed by `merge` to another channel works as expected (it merges the channels), but actual behaviour is that this happens, but the pipeline hangs after all the steps have been processed. Not sure if I'm doing it wrong here.

### Steps to reproduce the problem

```
q1 = Channel.from([0, 'a'])

process test {
  output:
  file('hello') into q2

  """
  touch hello
  """
}

q1
  .toList()  // replacing with .buffer(size: 2) works fine.
  .merge(q2)
  .println{it}
```

### Program output 
```
$ nextflow run  small_tolist.nf
N E X T F L O W  ~  version 18.10.1
Launching `/Z/jorrit/repos/testnfcddadeq/small_tolist.nf` [awesome_murdock
[nextflow.log](https://github.com/nextflow-io/nextflow/files/2987949/nextflow.log)
] - revision: 690b801a5c
[warm up] executor > local
[15/261c24] Submitted process > test
[0, a, /path/to/nfrepo/work/15/261c24a59553470addc29f88b57e5e/hello]

... minutes pass ...

^C
$ 
```

### Environment 

* Nextflow version: [18.10.1, 19.01.0.5050] 
* Java version: [11]
* Operating system: [Ubuntu 18.04]

**Comment by glormph** [comment]
If it's any but interesting, I can add that using `collect` results in the same behaviour.

**Comment by pditommaso** [comment]
Found the problem, thanks for reporting it.

**Comment by glormph** [comment]
Thank you very much for fixing! :) 👍
