### ISSUE TITLE
Singularity --bind

### ISSUE THREAD

**Issue by asura117** [nextflow-io/nextflow#1086]
Hi, 
I try to  bind my paths the following way 

In my terminal before i run my nextflow script:
/usr/bin/singularity
export SINGULARITY_BIND="/mnt/scratch,/data/rds"

However when running a nextflow pipeline the 
nexflow run example.nf

.command.run does not run as the paths are not seemed to bind. 
singularity exec ./commands

i.e if i edit .command.run to do this singularity exec --bind ./commands then it runs smoothly when i  'bash .command.run '

Can anyone tell me why the nextflow pipeline is not recognizing my  export SINGULARITY_BIND="/mnt/scratch,/data"

singularity
3.0.2-1.el7

**Comment by vsoch** [comment]
hey @asura117 did you try `SINGULARITY_BINDPATH` ? That might be why the variable isn't detected. See the [docs here](https://www.sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html#).

**Comment by pditommaso** [comment]
Use the singularity `--bind` option using the [containerOptions](https://www.nextflow.io/docs/latest/process.html#containeroptions) directive.

**Comment by pditommaso** [comment]
Closing this because there's no feedback any more.

**Comment by asura117** [comment]
Hi Paulo,
I have been playing with the config files to go with my nextflow but I am new to this so still figuring it out.  Hence the delay in feedback. Thanks for the suggestions.
I tried SINGULARITY_BINDPATH but it doesnt solve it. Looks like containerOptions may be the way to go.
