### ISSUE TITLE
Tool in process' conda environment not found

### ISSUE THREAD

**Issue by winni2k** [nextflow-io/nextflow#1087]
#### Expected

When I run `nextflow run nextflow.nf` my pipeline runs through successfully.

#### Actual

My nextflow pipeline stops with exit status 127 (command not found).

### Steps to reproduce the problem

The nextflow pipeline and input reads are located at https://gist.github.com/winni2k/4ce8b260294011f96ee5e46a3c17e05a

A working installation of conda is required.

To reproduce the problem I run `nextflow run nextflow.nf`

### Program output 

```
N E X T F L O W  ~  version 19.01.0
Launching `nextflow.nf` [gloomy_bohr] - revision: dd2415482b
[warm up] executor > local
Creating Conda env: transabyss [cache /Users/winni/tmp/work/conda/env-a5f2b21dd7c4651f2cd509dbe7528f33]
[b3/c7930b] Submitted process > test
ERROR ~ Error executing process > 'test'

Caused by:
  Process `test` terminated with an error exit status (127)

Command executed:

  transabyss --single input.fa         --outdir ./tabyss         --length 100         --threads 2

Command exit status:
  127

Command output:
  (empty)

Command wrapper:
  pyenv: .command.run: command not found

Work dir:
  /Users/winni/tmp/work/b3/c7930b2a4f8a858b69bfe0ff028213

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```

[nextflow.log](https://github.com/nextflow-io/nextflow/files/3008015/nextflow.log)

### Environment 

* Nextflow version: 19.01.0 
* Java version: 

```
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

* Operating system: macOS

### Additional context

If I change directory to the work directory of the test process and manually activate the conda environment created for this process, then the `transabyss` executable is found.

**Comment by pditommaso** [comment]
I think something is messed up with `pyenv` (this is he ultimate python packing tool right ... :D)

**Comment by winni2k** [comment]
I can totally imagine that it's something to do with my conda setup. It was never the same after I installed pyenv and fish O,o. I'll have a go on a different machine and see if this persists.

**Comment by winni2k** [comment]
Ok, this does not reproduce on a linux machine that I tried. I suppose my Mac is just broken :/

**Comment by nmendozam** [comment]
I had the same problem in a Linux server. I think it happens after several runs in the same directory, the conda handler tries to create an environment and for some reason it fails. 
```
Apr-25 10:50:16.351 [Actor Thread 23] INFO  nextflow.conda.CondaCache - Creating env using mamba: bioconda::eggnog-mapper [cache /.../work/conda/env-c7deaafe03756e04c90da7e026d3472e]
Apr-25 10:50:17.149 [Actor Thread 23] DEBUG nextflow.conda.CondaCache - 'mamba' create complete env=bioconda::eggnog-mapper path=/.../work/conda/env-c7deaafe03756e04c90da7e026d3472e
Apr-25 10:50:17.153 [Actor Thread 13] DEBUG nextflow.util.CacheHelper - Unable to get file attributes file:/.../work/conda/env-c7deaafe03756e04c90da7e026d3472e -- Cause: java.nio.file.NoSuchFileException: /.../work/conda/env-c7deaafe03756e04c90da7e026d3472e
```
When checking `work/conda`, the directory for the environment (`env-c7deaafe03756e04c90da7e026d3472e`) indeed does not exist. After the error happens, no matter how many retries, it still happens. I was able to solve the problem by removing all the cache files:
```bash
rm -rf work out .nextflow*
```

Sadly, I am not able to find a way to replicate the issue.
