### ISSUE TITLE
nextflow doesn't recognise k8s current context

### ISSUE THREAD

**Issue by olatarkowska** [nextflow-io/nextflow#1089]
## Bug report 

Kubernetes nicely manage multiple cluster configs using environment variable `KUBECONFIG`. Context can be switched using `kubectl use-context`, for more details see https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration

Nextflow assumes there is one path to the config exported to the KUBECONFIG
```
Mar-28 10:06:10.311 [main] DEBUG nextflow.k8s.client.ConfigDiscovery - K8s config file does not exist: /home/ola/.kube/production-new.config:/home/ola/.kube/config.local
```

### Expected behavior and actual behavior

use currect context `kubectl config current-context	`

### Steps to reproduce the problem

export multiple configs

### Environment 

* Nextflow version: nextflow version 19.01.0.5050
* Java version: JDK 1.8
* Operating system: osx

cc'd: @wikiselev

**Comment by pditommaso** [comment]
It may be related to #1049. Please try version `19.03.0-edge`.

**Comment by pditommaso** [comment]
Sorry I hadn't realised properly the issue you are rasing. Basically, the `KUBECONFIG` can list more than one path separating them with a `:` character that needs to be merged according to the logic described [here](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#merging-kubeconfig-files).

**Comment by pditommaso** [comment]
The merging logic could be tricky to implement. I'm tempted to use the `kubectl config view --raw` to  merge the yaml files and parse the resulting output.
