### ISSUE TITLE
Config loading arguments (-c, -C) not documented in executable

### ISSUE THREAD

**Issue by winni2k** [nextflow-io/nextflow#1091]
The documentation mentions the `-c` and `-C` options at https://www.nextflow.io/docs/latest/config.html?highlight=environment#configuration-file, but when I run `nextflow run -help`, then I do not see documentation for these two arguments:

[help.txt](https://github.com/nextflow-io/nextflow/files/3022949/help.txt)

**Comment by pditommaso** [comment]
Because it's `nextflow -help` not `nextflow run -help`

**Comment by winni2k** [comment]
Huh. Do the `-c/-C` options work with the `run` command?

**Comment by pditommaso** [comment]
TLDR; In the early `-c` was an option of the `run` command. Then, the `-c` *and* `-C` where added as top-level options and the `-c` was left for backward compatibility to the `run` command. 

In conclusion `-C` is only top level, `-c` both top level and as `run` option. Suggestion, use `-c/C` s top-level option and forget the one on `run`.

**Comment by winni2k** [comment]
I'm just trying to figure out if we can clean up the documentation somehow because I find the section I linked to above confusing? 

I would find an example of command line use of the `-C/-c` arguments useful.  Right now there are only snippets in the main body and `Tip` section, but it's not clear to me that I can't use these arguments with the `nextflow run` subcommand. That might be good to point out for users who are not experts?

**Comment by pditommaso** [comment]
I understand. Maybe it would more clear adding a command line example in the [docs](https://www.nextflow.io/docs/latest/config.html).

**Comment by winni2k** [comment]
Excellent. I'll see about creating a PR.
