### ISSUE TITLE
Problem with pipeline to read file with s3 links

### ISSUE THREAD

**Issue by vinay631** [nextflow-io/nextflow#1095]
Hi,

I am creating a pipeline which will, given some sample ids and group id (shard id in this case), create files for each group id with s3 links for sample data for that group. The next process then reads each of these files and passes the s3 files as parameters to the a script. 

For example, I have 3 groups 1, 2, and 3 and 3 samples s1, s2, and s3. For each group, I have parts of each sample (s1_g1, s2_g1, s3_g1...) in different s3 locations. In first step of pipeline, I collect s3 location for all the data for each group in a file. So in this case there will be 3 files with 3 s3 location each. These files get passed to next step where download all three s3 data in a file and pass those downloaded files as parameter to a script. (I have replaced the script with `echo` in the script below)

This is the script I have so far. 

```
#! /usr/bin/env nextflow

shard_file = file(params.shards)
samples_file = file(params.samples)
outpath = params.outpath
shard_source = params.shard_source

ref_fasta = file(params.fasta_ref)
ref_fasta_index = file(params.fasta_ref+'.fai')

shard_sequence = Channel.from(1 .. 3)

process ParseShardList {

    input:
    val genomic_shard from Channel.from(shard_file.splitText()).map{ it.strip() }
    val shard_id from shard_sequence
    file samples_file


    output:
    set shard_id, genomic_shard into shard
    file "shardfiles_${shard_id}.txt" into jointcalling_sourcefile
   
    script:
    """
    while IFS='' read -r line || [[ -n "\$line" ]]; do
        echo "${shard_source}/\${line}/\${line}-shard-${shard_id}.vcf.gz" >> shardfiles_${shard_id}.txt
    done < "${samples_file}"
    """
}

process JointCallerTest {

    input:
    set shard_id, genomic_shard from shard
    file index_channel from jointcalling_sourcefile.flatten().splitText().map{ x -> file(x.strip()) }

    output:
    set shard_id, genomic_shard into shard_output
    file "GVCFtyper-shard_${shard_id}.vcf" into joint_output

    script:

    """
    echo "${index_channel}" >> GVCFtyper-shard_${shard_id}.vcf

    """
}
```

The issue I am running into is that I can only access one s3 file from one group in the second process (`JointCallerTest`). I don't know if this is the right way to access s3 link in each file - ` file index_channel from jointcalling_sourcefile.flatten().splitText().map{ x -> file(x.strip()) }`. 

I would really appreciate any help on this. Thanks!

**Comment by pditommaso** [comment]
Sorry, this is a general nextflow programming question. Please post in the google forum or the gitter channel. You can find the link at nextflow.io home page.
