### ISSUE TITLE
ListeningTaskMonitor

### ISSUE THREAD

**Issue by ptravers** [nextflow-io/nextflow#1097]
## New feature

Hi! I would like to create a new type of monitor that listens for events about a job instead of polling to get the results of it. By providing a open port that can be sent notifications when jobs complete. At first this would function over http by opening port so that REST events can be sent back to nextflow. I would like to target the AWS Batch Excecutor initially but I believe it should be possible to make the solution more general and encompass other backends. 

## Usage scenario 

Large numbers of running nextflow instances can overwhelm AWS API rate limits with AWS Batch polling. By creating a listening mode the instances can be updated by an external system removing the need for large numbers of requests to be sent by nextflow.

## Suggest implementation 

A ListeningTaskMonitor to expose the port and the ability to configure the task monitor to be used in the executor

**Comment by pditommaso** [comment]
This would be a nice improvement, which I thought in the past as well. However, never implemented to keep the monitor logic as simple as possible.

**Comment by ptravers** [comment]
cool! did you have any thoughts on preferred ways to implement? I am primarily a Scala developer so I do not have a deep grasp of groovy styles or the preferred way to structure this inside the code base. At the moment I have been planning to extend the TaskMonitor trait and add the ability to configure different task monitors. Not sure if that would potentially become to lengthy of a PR though.

**Comment by pditommaso** [comment]
Not sure. It can be more complex than expected to handle job executions at scale. It can also to be tricky to configure in environments with constrained internet access.

**Comment by pditommaso** [comment]
Tagging as `wishlist` to denote it's a desirable feature in the long run.
