### ISSUE TITLE
Dynamic errorStrategy is not evaluated correctly with > 1 retry

### ISSUE THREAD

**Issue by pinin4fjords** [nextflow-io/nextflow#1099]
## Bug report 

(closely related to long-closed https://github.com/nextflow-io/nextflow/issues/183).

### Expected behavior and actual behavior

Expect that:

```
errorStrategy { task.attempt <= 3 ? 'retry' : 'ignore' }
```

will cause a process to retry 3 times, then ignore. In fact, process is retried once, then terminates. 

### Steps to reproduce the problem

For example, this works, ignoring on the second retry:

```
#!/usr/bin/env nextflow

ch = Channel.from(1)

process rerun {

    errorStrategy { task.attempt == 1 ? 'retry' : 'ignore' }

    input:
    val(no) from ch

    """
    echo "rerun ${no}: ${task.attempt}"
    exit 9
    """
}
```

This does not, terminating on the second retry:

```
#!/usr/bin/env nextflow

ch = Channel.from(1)

process rerun {

    errorStrategy { task.attempt <= 3 ? 'retry' : 'ignore' }

    input:
    val(no) from ch

    """
    echo "rerun ${no}: ${task.attempt}"
    exit 9
    """
}
```

### Program output 

```
N E X T F L O W  ~  version 19.01.0
Launching `main.nf` [compassionate_bohr] - revision: 8b9aa83a09
[warm up] executor > local
[bc/09d004] Submitted process > rerun (1)
[bc/09d004] NOTE: Process `rerun (1)` terminated with an error exit status (9) -- Execution is retried (1)
[a0/01cb38] Re-submitted process > rerun (1)
ERROR ~ Error executing process > 'rerun (1)'

Caused by:
  Process `rerun (1)` terminated with an error exit status (9)

Command executed:

  echo "rerun 1: 2"
  exit 9

Command exit status:
  9

Command output:
  rerun 1: 2

Command wrapper:
  rerun 1: 2

Work dir:
  /nfs/production3/ma/home/jmanning/projects/nextflow_test/work/a0/01cb3844ea2abea973849c9fc46944

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

### Environment 

* Nextflow version: 19.01.0
* Java version: openjdk 10.0.2 2018-07-17
* Operating system: Linux

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
You need to specify [maxRetries](https://www.nextflow.io/docs/latest/process.html#maxretries) which by default is 1.

**Comment by pinin4fjords** [comment]
Okay, thanks. But that being the case I'd expect it to retry the once and ignore, not terminate. Is that not still a bit of a bug?

**Comment by pinin4fjords** [comment]
Oh wait, I see. It only ignores if attempt <= 3- never mind. Thanks again.
