### ISSUE TITLE
resolved path doesn't match opened path

### ISSUE THREAD

**Issue by asura117** [nextflow-io/nextflow#1101]
Hi 
I am running a nextflow script from github (Sarek; main.nf)
Bu I get the following error message. Is anyone familiar with this issue?

Command exit status:
255

Command output:
(empty)

Command error:
FATAL: resolved path /containers/sarek-latest.simg doesn't match with opened path /containers/sarek-latest.simg (deleted)
ERROR : Child exit with status 255

Work dir:
/work/11/9bf34e8a12305c98e2ec87bfdc1e2e

Tip: view the complete command output by changing to the process work dir and entering the command cat .command.out
WARN: Killing pending tasks (50)
[b6/480ed9] NOTE: Process RunFastQC (79887-1) terminated with an error exit status (255) -- Error is ignored
[c7/c51326] NOTE: Process RunFastQC (79880-1) terminated with an error exit status (255) -- Error is ignored
[29/7de678] NOTE: Process RunFastQC (79890-1) terminated with an error exit status (255) -- Error is ignored
[11/0cf4a8] NOTE: Process RunFastQC (79893-1) terminated with an error exit status (255) -- Error is ignored
[b9/694c31] NOTE: Process RunFastQC (79894-1) terminated with an error exit status (255) -- Error is ignored
[94/53d0c5] NOTE: Process RunFastQC (79882-1) terminated with an error exit status (255) -- Error is ignored
[ef/d77902] NOTE: Process RunFastQC (79904-1) terminated with an error exit status (255) -- Error is ignored
[46/548ef9] NOTE: Process RunFastQC (79898-1) terminated with an error exit status (255) -- Error is ignored
[ae/3631f4] NOTE: Process RunFastQC (79885-1) terminated with an error exit status (255) -- Error is ignored
[b3/9bc6cc] NOTE: Process RunFastQC (79895-1) terminated with an error exit status (255) -- Error is ignored
[1d/d7b428] NOTE: Process RunFastQC (79919-1) terminated with an error exit status (255) -- Error is ignored

I am running with singularity images installed locally and using necessary modified config files.

**Comment by pditommaso** [comment]
I think it makes more sense to post this in the [Sarek project](https://github.com/SciLifeLab/Sarek).

**Comment by asura117** [comment]
sure, thanks.
