### ISSUE TITLE
Do not mount inputs when stageInMode==copy

### ISSUE THREAD

**Issue by acerjanic** [nextflow-io/nextflow#1105]
#### Expected behavior:
When using `stageInMode = 'copy'` and the docker executor, Nextflow only mounts the work directory after copying the input files to the process work directory

#### Actual behavior:
When using `stageInMode = 'copy'` and the docker executor, Nextflow tries to mount the directory containing the original locations of input files as well as the process work directory. 

### Steps to reproduce the problem
Using the following test workflow, I get the following docker run command in the `.command.run` in the work directory.

The environment variable `NXF_WORK=/scratch`. 

```
 #!/usr/bin/env nextflow

params.infile = "Test123.txt"
inputFile = file(params.infile)

process reconSenFM {
    
    container = "ubuntu:latest"
    containerOptions = ''
    stageInMode = 'copy'
    scratch = true

    input:
    file inFile from inputFile
    
    output: 
    file 'outfile' into outputFile
    script:
    """
    cp ./${inFile} ./outfile
    """
}
```

### Program output 

```shell
docker run -i -v /shared/mrfil-data/acerja2/repos/test/sms-recon/SpinVeyor:/shared/mrfil-data/acerja2/repos/test/sms-recon/SpinVeyor \ 
-v /scratch/a0/1253c904b5c66bdf247d13d6af66b3:/scratch/a0/1253c904b5c66bdf247d13d6af66b3 \ 
-v "$PWD":"$PWD" -w "$PWD" --entrypoint /bin/bash --name $NXF_BOXID ubuntu:latest \ 
-c "/bin/bash -ue /scratch/a0/1253c904b5c66bdf247d13d6af66b3/.command.sh"
```

This first bind mount is contrary to the expected behavior when using docker and `stageInMode = 'copy'`. It points to the original file, which defeats the purpose of copying the input file to the work directory.

At best it is redundant, at worst it is destructive as the original file could be modified leading to data loss or destruction by accident. Additionally, docker generally runs as root, so depending on the local environment (such as the case of root squashed NFS mounts) data might live on a share that docker will not have permissions for. 

### Environment 

* Nextflow version:  19.01.0 build 5050
* Java version: 1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12
* Operating system: Ubuntu 16.04 LTS
### Additional context

None at the moment.

**Comment by pditommaso** [comment]
Should be fixed in the master branch. You can give a try to it using the command below: 

```
NXF_VER=19.04.0-SNAPSHOT nextflow run .. etc 
```

**Comment by acerjanic** [comment]
Yep! It looks much better. I don't see the original file location included in the docker run line.

Thanks!

**Comment by pditommaso** [comment]
Excellent.
