### ISSUE TITLE
Qstat options error - PBS

### ISSUE THREAD

**Issue by wmaguire-gladstone** [nextflow-io/nextflow#1106]
### Expected behavior and actual behavior

When running nextflow with PBS set as the executor, an error is given regarding these specific options for qstat. If using the -1 option, it requires -n or -s.

### Steps to reproduce the problem

Set executor to 'pbs'
Try executing a nf workflow

### Program output 

``` WARN: [PBS] queue (this_queue) status cannot be fetched 
- cmd executed: bash -c set -o pipefail; qstat -f -1 this_queue | { egrep 
'(Job Id:|job_state =)' || true; } 
- exit status : 2 
- output      : 
  qstat: conflicting options. 
  usage: 
  qstat [-f] [-J] [-p] [-t] [-x] [ job_identifier... | destination... ] 
  qstat [-a|-i|-r|-H|-T] [-J] [-t] [-u user] [-n] [-s] [-G|-M] [-1] [-w] 
        [ job_identifier... | destination... ] 
  qstat -Q [-f] [ destination... ] 
  qstat -q [-G|-M] [ destination... ] 
  qstat -B [-f] [ server_name... ] 
  qstat --version 
```

### Environment 

* Nextflow version: 19.01.0.5050
* Java version: 1.8.0_151
* Operating system: RHEL 7.4

### Additional context

pbs_version = PBSPro_13.1.0.160576

**Comment by wmaguire-gladstone** [comment]
https://github.com/nextflow-io/nextflow/blob/08a3d1b26d58a70df29243d1edb0e8f52c87592e/modules/nextflow/src/main/groovy/nextflow/executor/PbsExecutor.groovy#L125

**Comment by pditommaso** [comment]
Use `pbspro` executor instead of `pbs`

**Comment by wmaguire-gladstone** [comment]
Okay, with pbspro as executor, it gives an error with the qsub line:

```[redact]$ nextflow run 
alt-splice.nf -with-dag -with-report -with-trace -resume 
N E X T F L O W  ~  version 19.01.0 
Launching `alt-splice.nf` [maniac_ardinghelli] - revision: 506e02ff77 
name                   : RNA-Seq Abundance & Alt-splice Analysis 
reads                  : 
/data/projects/redact
transcriptome          : hg19 
bootstraps             : 100 
experimental design    : /data/projects/redact

[warm up] executor > pbspro 
[c9/2367c4] Cached process > trim (YS_CPC_Gata4KD_rep1) 
[f8/091f59] Cached process > trim (YS_CPC_controlKD_rep2) 
[91/856a1e] Cached process > trim (YS_CPC_controlKD_rep1) 
[1b/57f373] Cached process > trim (YS_CPC_Gata4KD_rep2) 
[0c/ae5f4a] Cached process > kallisto_quant (YS_CPC_Gata4KD_rep1) 
[87/cf67ff] Cached process > kallisto_quant (YS_CPC_controlKD_rep1) 
[fd/b38240] Cached process > kallisto_quant (YS_CPC_Gata4KD_rep2) 
[f2/d6953c] Cached process > kallisto_quant (YS_CPC_controlKD_rep2) 
ERROR ~ Error executing process > 'sleuth (null)' 

Caused by: 
  Failed to submit process to grid scheduler for execution 

Command executed: 

  qsub -N nf-sleuth_null .command.run 

Command exit status: 
  5 

Command output: 
  qsub: "-lresource=" cannot be used with "select" or "place", 
resource is: ncpus 

Work dir: 
  /data/projects/redact

Tip: you can try to figure out what's wrong by changing to the process 
work dir and showing the script file named `.command.s 
h` 

 -- Check '.nextflow.log' file for details 
Execution cancelled -- Finishing pending tasks before exit 
Oops something went wrong 
Pipeline completed at: Thu Apr 11 12:30:36 PDT 2019 
Execution status: failed 
```

The nextflow.config:

```[redact]$ cat nextflow.config 
//nextflow.config
//A:redact
//D: 04/02/2019

//Configuration file for alternative splicing pipeline

manifest {
    mainScript = 'alt-splice.nf'
}

process {
	executor =  'pbspro' // set executor (i.e. queue management system)
	queue = 'Bio' // set the queue's name
	time = '1h'
	memory = '4 GB'
	cpus = 2
	clusterOptions = '-V -W group_list=bioqueue'
	errorStrategy = 'finish'
}

trace {
	enabled = true
	file = 'pipeline_trace.txt'
	fields = 'task_id,name,status,exit,realtime,%cpu,rss'
}

timeline.enabled = true
report.enabled = true
```

**Comment by pditommaso** [comment]
The `-lresource` is not used by NF, have no idea what's setting that option. Also the `null` in the task name is not reassuring.

**Comment by pditommaso** [comment]
Closing this because there's any more feedback. Feel free to comment/reopen if needed.

**Comment by wanyuac** [comment]
I encounded the same issue when using PBS as the executor.

**Program output**
```
[warm up] executor > pbs
[22/123a9f] Submitted process > trimmomatic (1)
[74/dd7cad] Submitted process > fastqc (2)
[58/807ce8] Submitted process > trimmomatic (2)
[12/04a243] Submitted process > fastqc (1)
WARN: [PBS] queue status cannot be fetched
- cmd executed: bash -c set -o pipefail; qstat -f -1 | { egrep '(Job Id:|job_state =)' || true; }
- exit status : 1
- output      :
  qstat: conflicting options.
  usage:
  qstat [-f] [-J] [-p] [-t] [-x] [-E] [-F format] [-D delim] [ job_identifier... | destination... ]
  qstat [-a|-i|-r|-H|-T] [-J] [-t] [-u user] [-n] [-s] [-G|-M] [-1] [-w]
        [ job_identifier... | destination... ]
  qstat -Q [-f] [-F format] [-D delim] [ destination... ]
  qstat -q [-G|-M] [ destination... ]
  qstat -B [-f] [-F format] [-D delim] [ server_name... ]
  qstat --version
```

**Environment**
- nextflow version 19.01.0.5050
- openjdk 10.0.2 2018-07-17
- OpenJDK Runtime Environment Zulu10.3+5 (build 10.0.2+13)
- OpenJDK 64-Bit Server VM Zulu10.3+5 (build 10.0.2+13, mixed mode)
- Operating system: CentOS Linux 7
- `qstat` shows the pbs_version = 18.2.3.20181206140456

**Comment by johnds123** [comment]
NextFlow's usage of qstat -f -1 makes it the most perfect DOS attack service one can think of.

That happened just for us last week-end on a 600 node cluster.
This software should be banned for anything else than a user's personal laptop.

The be constructive the code should be fixed in two ways:
1. Run qstat without -f -1
2. Make sure that qstat is provided a JOBID. 
The current version fails to pass the JOBID resulting in a qstat -f -1 to be executed.
On  a system with a high throughput like our this can easily result in NextFlow querying 10000's of jobs (queued, running and terminated) from a set of 100's of jobs effectively bringing the queuing system to a halt.

**Comment by pditommaso** [comment]
Provided the statement * This software should be banned ..etc" doesn't look very constructive, If I'm understanding correctly you are saying that we should spawn 10000 `qstat JOBID` instead of one `qstat -f` ?

**Comment by johnds123** [comment]
No, if you read carefully I suggest you fix your code so qstat is passed a JOBID.
With the current version this doesn't work and NextFlow simply executes qstat -f -1 .
On my setup NextFlow will not be allowed until this is fixed. But of course if you don't care about citations just ignore my request.

**Comment by pditommaso** [comment]
Let me see, running `qstat JOBID` the status of one job is retrieved. If a pipeline is running 10000 jobs how you are expecting to query to status for all jobs?

**Comment by johnds123** [comment]
If you are not keeping track of your job submissions I dare not think of the quality of the results from the computations.

**Comment by pditommaso** [comment]
Not useful feedback
