### ISSUE TITLE
Limit the number of jobs submitted to the cluster

### ISSUE THREAD

**Issue by maosa** [nextflow-io/nextflow#1110]
Hello,

We have a pipeline for analysing single-cell RNA-seq data. At some point, the pipeline runs several jobs in parallel and when many jobs are submitted at the same time, many of the cluster nodes become unresponsive due to high memory usage.

Is there a way to specify the number of jobs submitted to the cluster? Would it be possible for example to have a constant number of jobs running at the same time (i.e. 20 jobs running and when one completes, another one is submitted)? Or maybe submitting jobs at constant time intervals (i.e. 10 jobs every 10 minutes) hoping that some of the jobs running would have completed by the time the next batch is submitted, preventing system overload.

Thanks

**Comment by pditommaso** [comment]
What cluster/executor are you using ?

**Comment by maxibor** [comment]
Have you tried the `queueSize` executor setting ? [nextflow.io/docs/latest/config.html?highlight=queuesize#scope-executor](https://www.nextflow.io/docs/latest/config.html?highlight=queuesize#scope-executor)

**Comment by maosa** [comment]
We are using SGE! We did specify queueSize and submitRateLimit in specific processes but they seemed to be ignored. Only when specified within the conf file they were taken into account.

Ideally what we'd like is something like the following:

    executor{
    name='sge'
    cpus=2
    memory='2 GB'
    queueSize=20
    submitRateLimit='20 / 3min'
    }

The above would be specified only for certain processes but it seems that when placed within a specific process, those parameters are ignored; however, when placed in the conf file, they are used as expected (an applied to all processes). The reason why we would like to have this only inside certain processes is to avoid placing those limits on all the other processes.

The conf file also contains:

    process.queue='infini.q'
    process.clusterOptions='-S /bin/bash'
    process.scratch=true
    params.scratch=/scratch/user
    process.penv=make

I'm not sure if by specifying the above parameters/options, the conf file overwrites anything that might be specified within specific processes.

**Comment by pditommaso** [comment]
umm I think the main issue is that you are using the wrong options in the executor context. try the following: 

```
executor{
  queueSize=20
}

process {
  executor='sge'
  cpus=2
  memory='2 GB'
  queue='infini.q'
  clusterOptions='-S /bin/bash'
  scratch=true
  scratch=/scrat
}
```

**Comment by maosa** [comment]
I see...Ok, so what I did (and it worked!!!) was to specify `cpus` and `memory` inside specific processes and then added the following in the conf file:

    executor {
        name='sge'
        queueSize=20
    }

    process {
        queue='infini.q'
        clusterOptions='-S /bin/bash'
        scratch=true
        scratch='/scratch/user/'
    }

Works as expected!!! Thanks a lot @pditommaso :))

**Comment by pditommaso** [comment]
:v:
