### ISSUE TITLE
Stopping the nextflow pipeline without use kill

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#1111]
## Usage scenario 

I think it is kind of weird to kill the NF process to stop the pipeline. I suggest adding a simple command nextflow stop that is able to read the pid in the .nextflow.pid file and execute the killing. I know it won't be top priority but I'm sure it will be useful.

**Comment by lucacozzuto** [comment]
I have more people asking for this feature! :)

**Comment by lucacozzuto** [comment]
Hi! Some users of a Nextflow pipeline I made are asking for a better system to stop it. So I'm just wondering if we can reopen this issue :) cc @enovoa @soniacruciani

**Comment by pditommaso** [comment]
We have a full-featured frontend for NF now 👉 htts://tower.nf

**Comment by lucacozzuto** [comment]
I know and I'm happy to use it! But some people are running the pipeline on some small GPU machines that can be not connected to internet.

**Comment by pditommaso** [comment]
This is open source! fork it, implement it, and make a pull request for it! 😆

**Comment by lucacozzuto** [comment]
Ehehehe. Sorry, it is out of my possibilities :) however, I think that having a proper 'nextflow stop' command would be a nice feature. But you choose :)

**Comment by pditommaso** [comment]
I'm sure at CRG there is enough expertise to develop this

**Comment by lucacozzuto** [comment]
No java / groovy developers afaik.

**Comment by pditommaso** [comment]
![](https://media1.giphy.com/media/cwTtbmUwzPqx2/giphy.gif)
