### ISSUE TITLE
"echo" directive not working and weird stdout behaviour when using ansi console logging output

### ISSUE THREAD

**Issue by olifly** [nextflow-io/nextflow#1112]
### Expected behavior and actual behavior

**Expected:** Each process should echo it's output to the console and the output from each process should be printed by the subscription to the "o" channel.

**Actual:** The processes don't echo their output "despite having the echo true directive" and the "o" channel doesn't output the outputs form all of the processes started (only the output of 2 of the 3 processes started is printed).

### Steps to reproduce the problem

1. Run nextflow version that has the ANSI console (19.02.0-edge or 19.03.0-edge)
  ```
export NXF_VER='19.02.0-edge'
or
export NXF_VER='19.03.0-edge'
```

2. Make sure that the ANSI console is enabled (it should by by default, but to make sure use):
`export NXF_ANSI_LOG=true` 

3. Run nextflow on the script attached to this issue

4. The output is not as expected.

5. Disable the ANSI console output:
`export NXF_ANSI_LOG=false`

6. Run nextflow again on the provided script

7. The output is now as expected

### Program output 

**with ANSI Console**

```
N E X T F L O W  ~  version 19.03.0-edge
Launching `test.nf` [agitated_kowalevski] - revision: 3d7079e89e
executor >  local (3)
[31/154570] process > basicExample [  0%] 0 of 3
process job 2

process job 1

executor >  local (3)
[31/154570] process > basicExample [100%] 3 of 3 ✔
Completed at: 11-Apr-2019 13:14:02
Duration    : 1.7s
CPU hours   : (a few seconds)
Succeeded   : 3

```

**without ANSI Console**

```
N E X T F L O W  ~  version 19.03.0-edge
Launching `test.nf` [focused_goldberg] - revision: 3d7079e89e
[warm up] executor > local
[e0/a6024e] Submitted process > basicExample (2)
[6b/71b2c1] Submitted process > basicExample (3)
[bb/13b3cf] Submitted process > basicExample (1)
process job 3
process job 3

process job 2
process job 2

process job 1
process job 1
```

### Environment 

* Nextflow version: 19.02.0-edge and 19.03.0-edge
* Java version: 1.8.0_181
* Operating system: MacOS 10.14.4

### Test Script

```
num = Channel.from( 1, 2, 3 )

process basicExample {
  echo true 
  
  input:
  val num

  output:
   stdout into o

  "echo process job $num"

}

o.subscribe {
    println it
}
```

**Comment by pditommaso** [comment]
Thanks for pointing this out. The `echo` was disabled on purpose when the ansi log is enabled but I agree but not a great idea. 

Instead, when using `subscribe { println it }` that's it's expected to break the ansi rendering. It should be used `subscribe { log.info(it) }`.
