### ISSUE TITLE
Issue transiting between local execution and aws-batch with a trivial example

### ISSUE THREAD

**Issue by KennethLim314** [nextflow-io/nextflow#1116]
## Bug report 

(Reporting an issue with aws-batch on a seemingly trivial process)

### Expected behavior and actual behavior

(Give an brief description of the expected behavior 
and actual behavior)

### Steps to reproduce the problem

Steps to reproduce:

**Pipeline**

```
process sayHello {
    publishDir params.pub_dir
    output:
    file "test.out" into test1

    script:
    """
    echo Hello World! > test.out
    """
}
```

**AMI**

default Amazon ECS optimized linux 2 (tini was installed in addition)

**Configfile (Not exact)**

```
aws {
accessKey = *****
secretKey = *****
region = "ap-southeast-1"
}
process {
    executor = "awsbatch"
    withName:sayHello{
    container = <containername>
    }
}
```

### Program output 

On local, successful. On aws-batch:

```
Status reason Essential container in task exited
Container message

/usr/bin/python2.7: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

Nextflow logs

Apr-17 06:25:21.803 [Task monitor] DEBUG n.c.aws.batch.AwsBatchTaskHandler - [AWS BATCH] Cannot read exitstatus for task: `sayHello`
```

### Environment 

* Nextflow version: [19.04.0]
* Operating system: [ECS optimized Amazon Linux 2]

**Comment by KennethLim314** [comment]
Upon closer inspection, to me, this seems like it might be similar to #1109

**Comment by pditommaso** [comment]
It looks a problem with the installation of python/aws cli in your custom AMI

**Comment by pditommaso** [comment]
Any progress on this?

**Comment by KennethLim314** [comment]
Apologies for the late reply. I've rebuilt the AMI from scratch and switched from using the AMI's awscli to installing awscli in each image and that seems to have fixed it. I'm going to see if I can figure out exactly what's causing that specific error.

**Comment by pditommaso** [comment]
Feel free to re-open/comment if the problem persists.
