### ISSUE TITLE
Include network usage in performance trace

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1117]
## New feature

The trace feature currently includes statistics for CPU, memory, and disk. The other important factor when profiling an application is network usage, which is pretty relevant for any application that downloads data from a remote repository, for example. So I think it would be useful to include some statistic(s) for network usage, perhaps min/mean/max, in the trace fields.

## Usage scenario 

For any application that downloads or uploads a lot of data to remote repositories. Especially in the context of a shared HPC cluster where we have to be careful not to abuse resources.

## Suggest implementation 

I don't have a ton of experience with network monitoring tools, but each tool offers a different level of specificity. It looks like `iftop` or `nethogs` would do the job, `wireshark` would be overkill. We don't need to know which ports each process is using, just the steady-state network usage per process, as provided by `top` for CPU and memory. The issue is that both of these tools seem to require root privileges to run (at least at first glance). Perhaps there is a tool that can monitor only the current users processes without root privileges?

**Comment by pditommaso** [comment]
Nextflow only uses the Linux [proc](http://man7.org/linux/man-pages/man5/proc.5.html) pseudo file system to collect process metrics. This is done to avoid to depend on third part deps. 

The good news is that there should be such info in the proc file system, however I don't think it's a trivial task to determine such info. 

Any contribution in such direction is welcome.
