### ISSUE TITLE
Override project manifest with local nextflow.config (to use different mainScript)

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1118]
## New feature

When I run a nextflow pipeline using `nextflow run` or `nextflow kuberun` with `-C nextflow.config`, I would like to be able to override the `manifest` scope with my local `nextflow.config`. Specifically, I would like to be able to control which pipeline script is used as I have workflows with multiple pipeline scripts.

## Usage scenario 

I have a nextflow pipeline with two scripts, `main.nf` and `main-e2e.nf`. If I use `run` or `kuberun` the pipeline will use `main.nf` by default. However, I also use a local `nextflow.config` in order to override project params. I tried to change `manifest.mainScript` to `main-e2e.nf` to make nextflow use this other script but it doesn't seem to work that way. Not sure if that's a bug or a feature.

## Suggest implementation 

Same deal as other scopes like `params`, where the local `nextflow.config` overrides the project's config file. But extend this to also override `manifest` settings.

**Comment by pditommaso** [comment]
You should be able to specify the script to use con the command line eg. 

```
nextflow run org/project/script.nf
```

**Comment by bentsherman** [comment]
Ah perfect. This feature should be documented if it isn't already, I've never seen this syntax before.
