### ISSUE TITLE
Trace report name 

### ISSUE THREAD

**Issue by grafitos** [nextflow-io/nextflow#1119]
## Bug report 

In trace report (-with-trace), name field output in trace.txt is "name (tag)" should be "name", as tag is an optional field in trace configuration.

### Expected behavior and actual behavior

**With config:**

trace {
    enabled = true
    file = 'trace.txt'
    fields = 'name'
}

**and process:**

process myProcess{
 tag "myTag"
}

**Actual behavior (in trace.txt):**

myProcess (myTag)

**Expected behavior (in trace.txt):**

myProcess

### Environment 

* Nextflow version: all versions that support "-with-trace"

**Comment by pditommaso** [comment]
Actually is expected. Use `process` if you want to omit the tag name.
