### ISSUE TITLE
The join operator is not returning the expected number of joined items.

### ISSUE THREAD

**Issue by tinyheero** [nextflow-io/nextflow#1122]
## Bug report 

The `join` operator is not returning the expected number of joined items.

### Expected behavior and actual behavior

I have two channels each consisting of 251 features generated from the same input file. When joining these two channels, I expected to get 251 elements returned. But I am getting less than that. Also repeated runs produce different results. 

### Steps to reproduce the problem

I've created a separate repository that produces a test case and more detailed description of what is happening:

https://github.com/tinyheero/Nextflow-join-operator-bug

### Program output 

```
N E X T F L O W  ~  version 19.01.0
Launching `workflow.nf` [nauseous_marconi] - revision: e01d871b41
Number of elements in vcfChannel: 251
Number of elements in mutationBamsChannel: 251
Number of elements after joining the mutationBamsChannel and vcfChannel: 206
```

[nextflow.log](https://github.com/nextflow-io/nextflow/files/3100655/nextflow.log)

### Environment 

* Nextflow version: 19.01.0
* Java version: 1.8.0_171
* Operating system: Linux

### Additional context

N/A

**Comment by pditommaso** [comment]
Thanks. This is a perfect example to show the importance of declaring closure variables local using the `def` keyword. 

Replacing `variant = item["key"]` with `def variant = item["key"]` it works as expected (same for [bam](https://github.com/tinyheero/Nextflow-join-operator-bug/blob/master/workflow.nf#L11) and [vcf](https://github.com/tinyheero/Nextflow-join-operator-bug/blob/master/workflow.nf#L32)).

**Comment by tinyheero** [comment]
Ah. Many thanks for that. Saving me a big headache!
