### ISSUE TITLE
Wrong exit code being returned by nextflow bash script when it fails to initialize its enrivonment

### ISSUE THREAD

**Issue by olifly** [nextflow-io/nextflow#1126]
### Expected behavior and actual behavior

**Expected:** The nextflow script should return a non-zero exit code if it fails to initialize it's environment (and for all terminal errors that crop up during it's execution)

**Actual:**  The script checks if there is an error, but returns the exit code of the echo command it uses to report the error.

### Steps to reproduce the problem

Run nextflow in a way that it can't initialize its environment (unable to download dependencies for example).

### Program output 

The error is because of this line:

```
cli=($("$JAVA_CMD" "${JAVA_OPTS[@]}" -jar "$NXF_BIN"))
[[ $? -ne 0 ]] && echo_red 'Unable to initialize nextflow environment' && exit $?

```

The error returned by the last exit command is actually the exit code of echo_red, and not the exit code that triggered the if expression.

### Environment 

* Nextflow version: v18.10.1 
* Java version: openjdk version "1.8.0_191"
* Operating system: Ubuntu 16.04

**Comment by pditommaso** [comment]
Thanks for reporting this. It should be enough to `exit 1`.
