### ISSUE TITLE
Other location of `.nextflow.log`

### ISSUE THREAD

**Issue by vladsaveliev** [nextflow-io/nextflow#1132]
Wondering if it's possible to make Nextflow write `.nextflow.log*` files into a different location, e.g. the work directory, or the output directory, or anything custom? It would be nice to avoid cluttering cwd (unless I'm misunderstanding the standard usage pattern)

Vlad

**Comment by pditommaso** [comment]
Yes, use the `-log` top option eg. 

```
nextflow -log /full/path/my.log run <project>
```

**Comment by vladsaveliev** [comment]
Ah, thanks! Couldn't find anything with `nextflow run -help` - didn't realize I can do `nextflow help` for more options. Awesome, thanks for the pointer!
