### ISSUE TITLE
Feature Request: workflow.onStart event handler

### ISSUE THREAD

**Issue by csawye01** [nextflow-io/nextflow#1138]
## New feature

A workflow.onStart (like workflow.onComplete) event handler for pipelines. 

## Usage scenario 

It would be useful if a Nextflow pipeline could send a notification email that says the workflow has started in a situation where the pipeline is automatically triggered at the presence of specific files in a directory.

## Suggest implementation 

May be able to reuse some of the code developed for workflow.onComplete event handler to implement the workflow start event handler.

**Comment by SamStudio8** [comment]
@pditommaso Is this still `wontfix`? It is an unfortunate API choice to support `onComplete` and `onError` but not `onStart`. It would be nice to be able to fully decouple any "housekeeping" from the workflow itself, but at the moment we're left with no choice but to pollute the entrypoint workflow with any "onStart" activities; while post-workflow housekeeping is treated differently and can be separated into the handlers provided.

**Comment by pditommaso** [comment]
The rationale was the start of the execution is the execution of the script itself. However, using DSL2, this could make more sense.

What's your use case?

**Comment by SamStudio8** [comment]
@pditommaso Our use case is nothing that can't be done in the start of the workflow (eg. notifications), it's just the API in its current form is asymmetric. We have workflow complete/error handling notifications in their own handlers, but workflow start handling must be placed inside the workflow itself. It would be cleaner for user code and clearer for the language to introduce an onStart.
