### ISSUE TITLE
Custom messages in weblog/traceobservers.

### ISSUE THREAD

**Issue by olifly** [nextflow-io/nextflow#1139]
## Usage scenario 

We're using the Weblog to integrate with our services/applications and to monitor the progress of scripts as they are executing. For our usage scenarios it would be ideal to be able to emit custom messages to the weblog allowing us to act upon/display results and messages coming from the script and its processes while it is executing.

## Suggest implementation 

Add a function to emit messages to the Weblog/TraceObservers from within the script where applicable:
* emitMessage(_"< message you want to emit >"_)

A totally fictional usage could be:

```nextflow
process word_count {

    input:
    file input_file from input_file_channel
    each word from word_channel

    output:
    set val(word), stdout into count_output_channel
    file 

    script:
    """
    grep -c $word $input_file
    """
}

count_output_channel.subscribe {word,count ->
    emitMessage("Count for word '$word': $count") 
    if((count as Integer) > params.threshold) {
        emitMessage("Too many occurrences of $word.  Please simplify") 
    } else {
        emitMessage("Occurrences of $word are below our threshold.") 
    }
}
```

Adding directives to processes allowing us to emit trace messages before and after could also be useful, but of limited value unless/until we are able to reference output values in the directive.  
* beforeMessage _'< message you want to emit >'_
* afterMessage _'< message you want to emit >'_

The usage from above could me made even more  compact if we could reference output values from directives (but would probably require some overhaul of script/process execution).  Then this could theoretically be something like this:

```nextflow
process word_count {

    beforeMessage "Counting word '$word' in '${input_file.name}'"
    afterMessage {(count as Integer) > params.threshold ? 
        "Too many occurrences of $word.  Please simplify" : 
        emitMessage("Occurrences of $word are below our threshold."
    }

    input:
    file input_file from input_file_channel
    each word from word_channel

    output:
    set val(word), stdout as count into count_output_channel //here we have a theoretical feature of naming output values
    file 

    script:
    """
    grep -c $word $input_file
    """
}
```

The Weblog message emitted for these custom messages could be like this for example:

```json
{
  "runName": "friendly_pesquet",
  "runId": "170aa09c-105f-49d0-99b4-8eb6a146e4a7",
  "event": "message",
  "utcTime": "2018-10-07T11:42:08Z",
  "message": "Occurrences of 'process' are below our threshold.",
  "metadata": "{...}"
}
```

**Comment by pditommaso** [comment]
Not sure about this, could we use the existing [tag](https://www.nextflow.io/docs/latest/process.html#tag)?

**Comment by olifly** [comment]
@pditommaso The directives is not something that makes sense at the moment since we can't reference output values. You could pretty much replicate the funciontality using the tag directive as it stands,  but for me at least, that's using that directive in a way it was quite intended. 

The first point, adding a functio that allows you to emit a message to the webLog/TraceObservers in your script outside of processes is something that would be of immediate value to us, and can't, as for as I know, be replicated with any directives :)

**Comment by pditommaso** [comment]
I see your point, but this would introduce a generic message event, somehow similar to the existing `log.info/warn` and above out of the scope of the task execution.

It could message sense to introduce a message event, but IMO it would be preferable to keep in the context of the task execution of using the pattern discussed here #903. I agree that this would required the access to the task inputs and outputs that something we are planning to implement.
