### ISSUE TITLE
Improve the "reliability" of the weblog

### ISSUE THREAD

**Issue by olifly** [nextflow-io/nextflow#1145]
## Usage scenario 

We're using the weblog feature to integrate with other services we're running.  The weblog today is rather unreliable when it comes to ensuring that it's listener receives all messages that it should emit.  This "new feature" would enhance the reliability of the weblog (and other TraceObservers).

## Suggest implementation 

The main culprit is that the weblog is emitting messages asynchronously using an Agent.  When the nextflow Session class finishes (successfully, aborted or is cancelled) it doesn't ensure that all observers that is has registered have finished emitting messages/events/traces/etc before it terminates.

The implementation would add an await() method to the TraceObserver interface that observers can override to ensure that they have finished emitting all events they have received.

The Session object would then make sure that before it finishes, to loop through all of its observers and call await().

This implementation would fix issue https://github.com/nextflow-io/nextflow/issues/1010

**Comment by pditommaso** [comment]
More than happy to review a PR for this issue. Not sure to understand what this would bring more that then #1010.

**Comment by olifly** [comment]
@pditommaso The workaround shown in #1010 (using a sleep in workflow.onComplete) doesn't assure we get onFlowError messages when there are syntax errors in the script being executed for example.  This would also fix that

**Comment by pditommaso** [comment]
Provided that #1010 that should be fixed and the `sleep` is not supposed to be a valid patch, still not understanding what this issue would bring more.

**Comment by pditommaso** [comment]
Solved by #1010.
