### ISSUE TITLE
Failed to get status for SLURM job that was reassigned to a different partition

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#1151]
## Bug report 

For Nextflow tasks that were submitted with the SLURM executor and a `queue` directive, Nextflow is unable to correctly track the task completion after SLURM reassigns the job to a different queue/partition.

### Steps to reproduce the problem

Run Nextflow pipeline where:

- `process.executor = 'slurm'`
- `process.queue` is set to some SLURM queue/partition name
- `process.cpus`, `process.time`,  `process.memory` are all set to some value
- SLURM reassigns the Nextflow job to a different queue than the one specified due to its own internal scheduling logic

(optionally)
- `executor$slurm.exitReadTimeout` is set to some value, in this case `30min`

### Program output 

Nextflow stdout log shows error message such as this:

```
ERROR ~ Error executing process > 'mutect2 (228)'

Caused by:
  Process `mutect2 (228)` terminated for an unknown reason -- Likely it has been terminated by the external system
```

Nextflow thinks that the process may have been terminated. However, the process completed successfully: 

```
# inside the process `workDir`

$ lt
total 437K
drwxrws--- 25 vasudv02 8.0K May 13 20:36 ..
-rw-rw----  1 kellys04 1009 May 13 20:36 .command.sh
-rw-rw----  1 kellys04 3.5K May 13 20:36 .command.stub
-rw-rw----  1 kellys04 6.0K May 13 20:36 .command.run
-rw-rw----  1 kellys04    0 May 13 20:39 .command.begin
-rw-rw----  1 kellys04 5.9K May 13 20:39 .env.begin
# a bunch of files
-rw-rw----  1 kellys04   29 May 13 21:15 .command.out
-rw-rw----  1 kellys04 1.3K May 13 21:15 .command.err
-rw-rw-r--  1 kellys04  196 May 13 21:15 .command.trace
-rw-rw----  1 kellys04 1.9K May 13 21:15 .command.log
-rw-rw----  1 kellys04 7.0K May 13 21:15 .env.end
drwsrws---  2 kellys04 8.0K May 13 21:15 .
-rw-rw----  1 kellys04    1 May 13 21:15 .exitcode

$ cat .exitcode
0
```

SLURM also reports that the task completed successfully:

```
$ sacct -j 1962787 --format="JobID,JobName,Partition,Submit,Start,End,Timelimit,NodeList,State,ExitCode"
       JobID    JobName  Partition              Submit               Start                 End  Timelimit        NodeList      State ExitCode
------------ ---------- ---------- ------------------- ------------------- ------------------- ---------- --------------- ---------- --------
1962787      nf-mutect+  cpu_short 2019-05-13T20:36:39 2019-05-13T20:39:24 2019-05-13T21:15:02   06:00:00         cn-0031  COMPLETED      0:0
1962787.bat+      batch            2019-05-13T20:39:24 2019-05-13T20:39:24 2019-05-13T21:15:02                    cn-0031  COMPLETED      0:0
1962787.ext+     extern            2019-05-13T20:39:24 2019-05-13T20:39:24 2019-05-13T21:15:02                    cn-0031  COMPLETED      0:0

```

The `.command.run` file produced by Nextflow, showing the SLURM submission settings:

```
$ head .command.run
#!/bin/bash
#SBATCH -D /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1
#SBATCH -J nf-mutect2_(228)
#SBATCH -o /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1/.command.log
#SBATCH --no-requeue
#SBATCH -t 06:00:00
#SBATCH --mem 12288
#SBATCH -p cpu_long
#SBATCH --ntasks-per-node=1 --export=NONE --export=NTHREADS
```

Note here that the SLURM job was submitted under the queue `cpu_long`, however it actually ran on queue `cpu_short`. This is because on our system, SLURM reassigns jobs to different queues based on their requested time. In this case, 6 hours was requested, which falls under the time limit of the `cpu_short` queue, so SLURM put it there instead. 

This queue reassignment seems to have caused trouble for Nextflow. From the `.nextflow.log` file:

```
# searching for the SLURM job id

$ grep 1962787 .nextflow.log -A 5 -B 5 | less

May-13 20:36:39.417 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SLURM] submitted process mutect2 (228) > jobId: 1962787; workDir: /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1

```
- job successfully submitted to SLURM

```
May-13 20:39:29.476 [Task monitor] TRACE nextflow.executor.GridTaskHandler - JobId `1962787` exit file: /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1/.exitcode -
lastModified: null - size: null
May-13 20:39:29.478 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SLURM] getting queue (cpu_long) status > cmd: squeue --noheader -o %i %t -t all -p cpu_long -u kellys04
May-13 20:39:37.769 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SLURM] queue (cpu_long) status > cmd exit: 0

May-13 20:39:37.769 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SLURM] queue (cpu_long) status >
  (empty)
May-13 20:39:37.769 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SLURM] queue (cpu_long) status > map does not contain jobId: `1962787`
May-13 20:39:39.449 [Task monitor] TRACE nextflow.executor.GridTaskHandler - JobId `1962794` exit file: /somedir/demo-data-test2/work/f8/2579bb2193277d65c562df90265e7a/.exitcode - lastModified: null - size: null
May-13 20:39:39.449 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SLURM] queue (cpu_long) status > map does not contain jobId: `1962794`
May-13 20:39:39.963 [Task monitor] TRACE nextflow.executor.GridTaskHandler - JobId `1962337` exit file: /somedir/demo-data-test2/work/43/72affaa8188a5ba8fa655ca66ae811/.exitcode - lastModified: null - size: null
May-13 20:39:39.963 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SLURM] queue (gpu8_long) status > jobId `1962337` active status: true
May-13 20:39:40.810 [Task monitor] TRACE nextflow.executor.GridTaskHandler - JobId `1962787` exit file: /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1/.exitcode - lastModified: null - size: null
```
- Nextflow trying to check the status of the SLURM job (?), but fails to find it in `cpu_long` queue (because it got reassigned to `cpu_short`)

  - Note that Nextflow appears to be using this command to find the jobs in the queue: `squeue --noheader -o %i %t -t all -p cpu_long -u kellys04`: this will only return jobs in `cpu_long`; if `-p cpu_long` had been omitted, it might have found the job successfully

  - Another side note: when I try to run the command myself, it gives an error: `squeue: error: Unrecognized option: %t`; not sure if this makes a difference. 

```
May-13 20:42:15.376 [Task monitor] TRACE nextflow.executor.GridTaskHandler - JobId `1962787` exit file: /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1/.exitcode - lastModified: null - size: null
May-13 20:42:15.376 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SLURM] queue (cpu_long) status > map does not contain jobId: `1962787`
May-13 20:42:15.737 [Task monitor] TRACE nextflow.executor.GridTaskHandler - Exit file does not exist for and the job is not running for task: TaskHandler[jobId: 1962787; id: 2538; name: mutect2 (228); status: RUNNING; exit: -; error: -; workDir: /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1 started: 1557794368929; exited: -; ] -- Try to wait before kill it
May-13 20:42:16.329 [Task monitor] TRACE nextflow.executor.GridTaskHandler - JobId `1962794` exit file: /somedir/demo-data-test2/work/f8/2579bb2193277d65c562df90265e7a/.exitcode - lastModified: null - size: null
```

- Nextflow decides that the job is in an error state (?) because it cannot be found in the `cpu_long` queue

- `.exitcode` file for the job cannot be found, because the job is still running at this point

- Nextflow starts the 30 minutes countdown, as set with `executor$slurm.exitReadTimeout`

```
May-13 21:12:15.997 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SLURM] queue (cpu_long) status > map does not contain jobId: `1962748`
May-13 21:12:15.997 [Task monitor] TRACE nextflow.executor.GridTaskHandler - JobId `1962787` exit file: /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1/.exitcode - lastModified: null - size: null
May-13 21:12:15.997 [Task monitor] TRACE n.executor.AbstractGridExecutor - [SLURM] queue (cpu_long) status > map does not contain jobId: `1962787`
May-13 21:12:15.998 [Task monitor] DEBUG nextflow.executor.GridTaskHandler - Failed to get exit status for process TaskHandler[jobId: 1962787; id: 2538; name: mutect2 (228); status: RUNNING; exit: -; error: -; workDir: /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1 started: 1557794368929; exited: -; ] -- exitStatusReadTimeoutMillis: 1800000; delta: 1800260
Current queue status:
>   (empty)

Content of workDir: /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1
null
May-13 21:12:15.998 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 1962787; id: 2538; name: mutect2 (228); status: COMPLETED; exit: -; error: -; workDir: /somedir/demo-data-test2/work/e8/a18315a4a44272eda33d3ac25cddc1 started: 1557794368929; exited: -; ]
May-13 21:12:16.112 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'mutect2 (228)'

Caused by:
  Process `mutect2 (228)` terminated for an unknown reason -- Likely it has been terminated by the external system
```

- 30 minutes have elapsed and Nextflow still cannot find the `.exitcode` file, nor the SLURM job in the `cpu_long` queue, and halts the pipeline. Note that `retries` is enabled here so this actually happened several times before this point. Also note that the SLURM job did finish, 3 minutes after this...

  - Note: I am not sure why `Content of workDir:` is `null`, or what the significance of this is, maybe something worth a separate Issue?

So the conclusion seems to be that when a SLURM job gets reassigned to a different queue, Nextflow seems to lose track of it and thinks it is in an error state, which ends up killing the pipeline. 

One thing I am not clear on is why Nextflow is checking the SLURM queues individually with `squeue --noheader -o %i %t -t all -p cpu_long -u $USERNAME`; if it checked instead for the job ID in the entire queue or in the `sacct` output, it might have found it there. 

In the current configuration, it seems that it is a requirement for `exitReadTimeout` to be set to the longest expected time for a SLURM job to run, but this does not seem like an ideal solution.

### Environment 

* Nextflow version: 19.01.0

* Java version: 
```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)
```
* Operating system: RHEL 7

* SLURM 17.11.7

**Comment by pditommaso** [comment]
> Note here that the SLURM job was submitted under the queue cpu_long, however it actually ran on queue cpu_short

This is a scenario not taken into consideration by NF, therefore it's expected that the task status is not correctly determined.

**Comment by stevekm** [comment]
Is there a suggested solution? It seems odd that Nextflow would check each partition individually ( `squeue --noheader -o '%i %t' -t all -p cpu_long -u $USERNAME`) and only look in those partitions for the specified job, instead of just looking at all running jobs (`squeue --noheader -o '%i %t' -t all -u $USERNAME`) and finding the jobs that match based on SLURM job id along. 

Not sure how it is for other job schedulers, but the (re)assignment of a partition in SLURM seems to be something that is intentionally left up to the system admins to implement, so it does not seem like something that Nextflow should be making assumptions about the handling of.

**Comment by pditommaso** [comment]
Not sure what to add. NF does not support this use case.

**Comment by haqle314** [comment]
I ran into this same issue with SLURM. Like @stevekm mentioned, you can just not specify partition when checking job status. So could you at least explain why is it necessary to have the partition constraint when checking job status? More specifically this part in `queueStatusCommand` in `SlurmExecutor.groovy`
```groovy
        if( queue )
            result << '-p' << queue.toString()
```

**Comment by pditommaso** [comment]
Fair enough. The queue (partial) is specified to avoid `squeue` to return to many jobs. Are you willing to modify the above code as suggested and to test if solve the problem?

**Comment by haqle314** [comment]
As far as changing the code, I think it's just deleting the part that I mentioned and I'd be happy to do that. However, since this behavior can't be reliably reproduced, I'm not sure on what/how to test the modified code.

**Comment by stevekm** [comment]
I'm regards to working in reproducing the issues, I already started work on methods a little while ago to get a semi-scripted SLURM instance set up as a dev environment. Might be useful for this; https://github.com/stevekm/slurm-cluster-vagrant

**Comment by biomadeira** [comment]
Hi @pditommaso

This is still an issue for me. Has this or would this be reconsidered at all? 
As someone stated above, the allocation of jobs is often done by SLURM as configured by cluster admins. There are no options for users in such cases. Is there any workaround (for example with `clusterOptions`) to get this working?

TIA!

**Comment by cxtaslim** [comment]
Hi @bentsherman ,

How exactly can I set the `executor.queueGlobalStatus = true` ?

I tried setting this inside `nextflow.config`, but it doesn't work.
```
process {
			 time = '7d 00h 00m 00s'
			 queue = 'serial'
			 executor.queueGlobalStatus = true
			 cpus = 1
			 email = ''
			 clusterOptions = '-A PAS3043'
			 exitStatusReadTimeoutMillis = 600000
}
process.executor = 'slurm'
```
If I set it to the specific queue that I know it'll get assigned to (i.e. serial-40core instead of serial) it works:

```
process {
			 time = '7d 00h 00m 00s'
			 queue = 'serial-40core'
			 cpus = 1
			 email = ''
			 clusterOptions = '-A PAS3043'
			 exitStatusReadTimeoutMillis = 600000
}
process.executor = 'slurm'
```
