### ISSUE TITLE
PBSPro 18.2.3 qstat CLI changes.

### ISSUE THREAD

**Issue by cerebis** [nextflow-io/nextflow#1152]
### Expected behavior and actual behavior

Under PBSPro 18.2.3 the following warning is issued during a nextflow run:

```
WARN: [PBS] queue status cannot be fetched
- cmd executed: bash -c set -o pipefail; qstat -f -1 | { egrep '(Job Id:|job_state =)' || true; }
- exit status : 2
- output      :
  qstat: conflicting options.
  usage: 
  qstat [-f] [-J] [-p] [-t] [-x] [-E] [-F format] [-D delim] [ job_identifier... | destination... ]
  qstat [-a|-i|-r|-H|-T] [-J] [-t] [-u user] [-n] [-s] [-G|-M] [-1] [-w]
  	[ job_identifier... | destination... ]
  qstat -Q [-f] [-F format] [-D delim] [ destination... ]
  qstat -q [-G|-M] [ destination... ]
  qstat -B [-f] [-F format] [-D delim] [ server_name... ]
  qstat --version
```
### Steps to reproduce the problem

Submit any type of job to pbs executor with PBSPro as the underlying queue manager.

### Program output 

see above

### Environment 

* Nextflow version: 19.04.1
* Java version: OpenJDK 1.8.0_212
* Operating system: Linux CentOS 6.10 

### Additional context

Nextflow still finishes properly.

The offending option is `-1` which is no longer possible with `-f`.

Looking at the release notes of [PBSPro 18.2.3](https://www.pbsworks.com/pdfs/PBSReleaseNotesBinary18.2.3.pdf) there may be suitable new options for controlling qstat. The long format for job information now can be in json or dsv (delimiter separated values). This latter format option may be what is desired, producing a single line.

So `qstat -f -F dsv | {egrep ....` would get you the same functionality I think.

**Comment by pditommaso** [comment]
Use `pbspro` executor.

**Comment by pditommaso** [comment]
Oops, closed by mistake. Anyhow feel free to reopen if it doesn't solve it.

**Comment by cerebis** [comment]
Whoops, I didn't realize this executor was added back in October. Cheers!
