### ISSUE TITLE
Kuberun should honour -bg (background) option

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1159]
## New feature

`nextflow kuberun` creates a pod spec, launches it on a k8s cluster, and streams the log output of the pod. It would be convenient in some cases for `kuberun` to simply launch the pod and then exit. That is, since `kuberun` creates a "head node" on the k8s cluster which pefrorms the rest of the workflow, it is not necessary to have the local machine tethered to the entire process.

## Usage scenario 

Maybe I want to start the workflow and then turn off my machine for a week while the workflow proceeds on the k8s cluster.

## Suggest implementation 

Add an option to `kuberun` (something like `--standalone` or `--batch`) which simply causes `kuberun` to exit after submitting the pod.

If the user then wants to view the pod output, they can do so with `kubectl logs <pod-name>`.

**Comment by pditommaso** [comment]
Make sense. Actually, there's already a [background option](https://github.com/nextflow-io/nextflow/blob/651af95a59a8d7325ba46109ff325c247de509a8/modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy#L169). When used on the `kuberun` command it should behave accordingly.

**Comment by bentsherman** [comment]
Not quite the same, actually. With this option nextflow is still running on the local machine such that the k8s job would be disrupted if the local machine turns off. The local process must exit after submitting the controller pod, not merely run in the background.

**Comment by pditommaso** [comment]
Indeed. What I'm saying is that when `-bg` is specified on `kuberun` it should do what you are proposing.
