### ISSUE TITLE
Submit processes as Jobs instead of Pods for k8s / kuberun

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1162]
## New feature

One of my main concerns with the k8s executor and `kuberun` right now is that they don't always clean up after themselves. If a process fails, the pod is left hanging around, and `kuberun` also doesn't clean up the ConfigMaps and pods that it creates, regardless of whether they fail or complete successfully.

The problem is that pods are mapped to physical nodes, so if they aren't cleaned up then they take up physical resources even if they just sit there. I hope that Kubernetes improves it's support for batch processing in the future, but for now I think the best solution for nextflow would be to __submit a process as a Job with 1 completion rather than a Pod__. The job will automatically create a pod with the correct spec and delete it when it completes or fails. Similarly, `nextflow kuberun` should submit the controller pod as a Job with 1 completion.

## Usage scenario 

Pods that are submitted by themselves rather than by a controller (aka Job or Deployment) are hard to control in a shared batch processing system. Therefore the sys-admins of my k8s cluster are restricting such standalone pods to 2 CPUs / 8 GB memory / 6 hour wall-time, which is much less than what I need for my nextflow pipelines.

This may seem like a very particular use case but standalone pods are a major issue because they consume physical resources but there is no mechanism to clean them up easily without using a controller. A Job, on the other hand, does not consume resources by itself, and it will automatically manage the creation and deletion of pods.

## Suggest implementation 

Example of an existing pod spec:
```
apiVersion: v1
kind: Pod
spec:
  containers:
  - ...
```

Example of wrapping the pod spec in a job:
```
apiVersion: batch/v1
kind: Job
spec:
  completions: 1
  activeDeadlineSeconds: <value from time directive>
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - ...
```

**Comment by pditommaso** [comment]
This is an interesting pod. Unfortunately, we don't have resources in the short term to spend on this. A pull request would be welcomed.

**Comment by bentsherman** [comment]
Added some relevant fields to the job spec. Information about Jobs can be found here:

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

**Comment by bentsherman** [comment]
As far as code changes go, the k8s interface will simply create and delete jobs instead of pods. But you must still interact directly with the pod for things like checking status and streaming logs, so you will have to go through the job to do that.

For example, if I create a job called `example`, it will in turn create a pod called something like `example-ae8cv` (job name with random characters appended). As per the k8s documentation linked above, you can get the pods belonging to a job with this command:
```
kubectl get pods --selector=job-name=example --output=jsonpath='{.items[*].metadata.name}'
```

**Comment by xhejtman** [comment]
We are working on this.
