### ISSUE TITLE
Add possibility to store process log files in publishDir or central log directory

### ISSUE THREAD

**Issue by zichner** [nextflow-io/nextflow#1166]
## Usage scenario 

The easiest way to deal with a large `work` directory is to delete it after a pipeline completed successfully. Overall, this is perfectly fine, however, in many cases it would be nice to keep the information stored in the `.command` files to be able to check it later in case any questions regarding overlooked error messages, warnings, etc come up.

One way to deal with this would be to keep the `work` directory and to selectively delete unnecessary files from it (see #668). However, in my opinion it would be even better to be able to have files containing the log messages together with all other output in a directory specified using `publishDir`.

## Suggest implementation 

Would it be possible to add a process directive that allows to copy one or multiple `.command` files into the `publishDir` directory, potentially with a self-defined name?

Alternatively, it might be interesting to be able to define a log-directory, where all `.command` files of a run a stored using some naming scheme (something like `PROCESS-NAME_PROCESS-TAG.log`, ...).

Thank you very much!

**Comment by pditommaso** [comment]
> Would it be possible to add a process directive that allows to copy one or multiple .command files into the publishDir directory, potentially with a self-defined name?

You should already be able doing that declaring `file '.command.*' as an output.

**Comment by zichner** [comment]
Thank you very much for the hint. I overlooked this possibility.
In order to avoid modifying every single process definition, I now use the following workaround:

```
params.logDir = "./log"

process.afterScript = {
    logMainDir = params.logDir

    // Check whether log dir is located in S3 if using awsbatch and is a local directory otherwise
    if (workflow.profile == "aws") {
        if (!logMainDir.matches("^s3://.*")) logMainDir = "s3:/" + workflow.workDir.toString() + "/log"
    } else {
        logMainDir = workflow.launchDir.resolve(logMainDir).toString()
        if (!logMainDir.matches("^/.*")) logMainDir = workflow.launchDir.toString() + "/log"
    }

    // Build log directory path based on task name
    logSubDir = task.name.replace(" (null)", "").replace(" ", "/").replaceAll(" ", "_").replaceAll("[()]", "")
    logDir = logMainDir + "/" + logSubDir

    // Define command to copy log files 
    cpLogCmd = workflow.profile == "aws" ?
        "nxf_s3_upload '*.txt' ${logDir}; " :
        "mkdir -p ${logDir}; cp -a *.txt ${logDir}; "

    // Assemble final command
    cmd = "ls -alR --full-time > .command.ls; "
    cmd += "mkdir nxf_log; "
    cmd += "for file in .command.*; do cp -a \${file} nxf_log/\${file#.}.txt; done; "
    cmd += "cd nxf_log; "
    cmd += cpLogCmd
    cmd += "cd ..;"
    cmd
}
```

After the successful finishing of a process, the `process.afterScript` copies all `.command.*` files as well as a file listing into a dedicated log directory (the name of the subdirectory is based on the task name). If the job runs in AWS, the log directory has to be an S3 bucket; if the job runs locally (or on HPC), the log directory has to be a local directory.

Obviously, this solution is not super elegant (especially because of the need to distinguish between local and AWS execution), however it seems to do the job quite nicely; and the actual pipeline doesn't need to be modified.

Are there any plans to allow users to store log files separately from the working directory?

Thanks a lot for all the work put into Nextflow!

**Comment by pditommaso** [comment]
Nice trick. 

> Are there any plans to allow users to store log files separately from the working directory?

There are plans to provide more controls on monitoring and logging abilities, but it would be implemented outside nextflow because it's clearly a requirement for professional users.
 
> Thanks a lot for all the work put into Nextflow!

Thank you!

**Comment by Santy-8128** [comment]
The suggestion by @zichner works great for local/SGE running. For AWS running however, it does not seem to work on the `.command.log` file (which has the main log output). I think the reason it doesn't work is because aws-batch is being called with the following command, whereas the contents of afterScript go inside `.command.run` (thus, .command.log has still not been created while its running. I wonder if there are any suggestions to save the log file from the AWS runs. 

```aws --region us-west-2 s3 cp --only-show-errors s3://***/.command.run - | bash 2>&1 | tee .command.log```

**Comment by VasLem** [comment]
> Thank you very much for the hint. I overlooked this possibility. In order to avoid modifying every single process definition, I now use the following workaround:
> 
> ```
> params.logDir = "./log"
> 
> process.afterScript = {
>     logMainDir = params.logDir
> 
>     // Check whether log dir is located in S3 if using awsbatch and is a local directory otherwise
>     if (workflow.profile == "aws") {
>         if (!logMainDir.matches("^s3://.*")) logMainDir = "s3:/" + workflow.workDir.toString() + "/log"
>     } else {
>         logMainDir = workflow.launchDir.resolve(logMainDir).toString()
>         if (!logMainDir.matches("^/.*")) logMainDir = workflow.launchDir.toString() + "/log"
>     }
> 
>     // Build log directory path based on task name
>     logSubDir = task.name.replace(" (null)", "").replace(" ", "/").replaceAll(" ", "_").replaceAll("[()]", "")
>     logDir = logMainDir + "/" + logSubDir
> 
>     // Define command to copy log files 
>     cpLogCmd = workflow.profile == "aws" ?
>         "nxf_s3_upload '*.txt' ${logDir}; " :
>         "mkdir -p ${logDir}; cp -a *.txt ${logDir}; "
> 
>     // Assemble final command
>     cmd = "ls -alR --full-time > .command.ls; "
>     cmd += "mkdir nxf_log; "
>     cmd += "for file in .command.*; do cp -a \${file} nxf_log/\${file#.}.txt; done; "
>     cmd += "cd nxf_log; "
>     cmd += cpLogCmd
>     cmd += "cd ..;"
>     cmd
> }
> ```
> 
> After the successful finishing of a process, the `process.afterScript` copies all `.command.*` files as well as a file listing into a dedicated log directory (the name of the subdirectory is based on the task name). If the job runs in AWS, the log directory has to be an S3 bucket; if the job runs locally (or on HPC), the log directory has to be a local directory.
> 
> Obviously, this solution is not super elegant (especially because of the need to distinguish between local and AWS execution), however it seems to do the job quite nicely; and the actual pipeline doesn't need to be modified.
> 
> Are there any plans to allow users to store log files separately from the working directory?
> 
> Thanks a lot for all the work put into Nextflow!

Thanks @zichner for this handy script, my two cents, I adapted it for GCP and made it save the logs into the publishDir .nextflow directory, whenever provided:
```
process.afterScript = {
  if (task.publishDir.path != null) {
    logDir = task.publishDir.path[0].toUri()
    logDir = "${logDir}/.nextflow"
    // Define command to copy log files 
    cpLogCmd = workflow.profile == "standard" ?
        "gsutil cp '*' ${logDir}; " :
        "mkdir -p ${logDir}; cp -a * ${logDir}; "

    // Assemble final command
    cmd = "ls -alR --full-time > .command.ls; "
    cmd += "mkdir nxf_log; "
    cmd += "for file in .command.*; do cp -a \${file} nxf_log/\${file#.}; done; "
    cmd += "cd nxf_log; "
    cmd += cpLogCmd
    cmd += "cd ..;"
    cmd
  }
}
```

**Comment by miraep8** [comment]
Not sure if anyone would be interested in this or not - but I have a "beta" version plugin that will move the '.command.err', 'command.out' and '.command.sh' files out of the work dir to a log saver dir, and rename them (based on the step name and hash.  Currently trying to merge it into the Nextflow plugin repo, but if anyone wants to try it out/has feedback it would be most welcome! :) Currently lives here: https://github.com/miraep8/nf-logsaver

Update:  This has been merged into the nextflow pplugin repository - so you should be able to use it by adding: `-plugins nf-logsaver@0.1.0` to your pipelines :)
