### ISSUE TITLE
Unexpected config selector warning

### ISSUE THREAD

**Issue by drpatelh** [nextflow-io/nextflow#1167]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

This warning should not be produced when running the pipeline:
`WARN: There's no process matching config selector: get_software_versions`

### Steps to reproduce the problem

`nextflow run nf-core/chipseq -profile test,docker -r dev`

### Environment 

* Nextflow version: [19.05.0-edge] 
* Java version: [1.8.0_172]
* Operating system: [Linux]

### Additional context

The warning isnt generated by Nextflow v0.32.0 but is by Nextflow 19.05.0-edge.

Warning disappears if I comment out these lines:
https://github.com/nf-core/chipseq/blob/83dc9cb9c5149cafbae06576199aff657c4830e1/conf/base.config#L41-L43

The `process` does exist:
https://github.com/nf-core/chipseq/blob/83dc9cb9c5149cafbae06576199aff657c4830e1/main.nf#L1377

**Comment by pditommaso** [comment]
Good spot!
