### ISSUE TITLE
When using scratch=true nxf_unstage can fail silently

### ISSUE THREAD

**Issue by mozack** [nextflow-io/nextflow#1172]
## Bug report 

nxf_unstage() appears to add || true to each cp command.  This can cause a copy failure to be silently ignored.

### Expected behavior and actual behavior

Copying from a compute node's scratch space back to the working dir should fail on copy error and trigger a retry (either of the copy or just restart the process from scratch).

The current silent failure creates an unrecoverable failure for downstream processes.

### Steps to reproduce the problem

I've run into this problem testing at GCP using slurm-gcp and using gcpfuse for storing the work dir in a cloud storage bucket and /tmp for the compute scratch space.  It is possible that gcpfuse may be more prone to write errors than typical network attached storage.  

### Program output 

Below is the nxf_unstage() function for the problematic job:
```
nxf_unstage() {
    true
    cp .command.out /mnt/lccc/ccle/rna-seq-quant2/nf-work-20b/c8/5a97b4d612d9891062e7ace146a0d7/.command.out || true
    cp .command.err /mnt/lccc/ccle/rna-seq-quant2/nf-work-20b/c8/5a97b4d612d9891062e7ace146a0d7/.command.err || true
    cp .command.trace /mnt/lccc/ccle/rna-seq-quant2/nf-work-20b/c8/5a97b4d612d9891062e7ace146a0d7/.command.trace || true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
    mkdir -p /mnt/lccc/ccle/rna-seq-quant2/nf-work-20b/c8/5a97b4d612d9891062e7ace146a0d7
    cp -fRL r1.fastq.gz /mnt/lccc/ccle/rna-seq-quant2/nf-work-20b/c8/5a97b4d612d9891062e7ace146a0d7 || true
    cp -fRL r2.fastq.gz /mnt/lccc/ccle/rna-seq-quant2/nf-work-20b/c8/5a97b4d612d9891062e7ace146a0d7 || true
}
```
For the problematic run, the fastqs (output of this process) failed on copy back to the work dir.  However, Nextflow viewed the process as having completed successfully.  Processes downstream were unable to complete successfully due to the incomplete fastq output.

### Environment 

* Nextflow version: 19.04.1
* Java version: 1.8.0_212
* Operating system: Centos 7

**Comment by pditommaso** [comment]
Solved by ead29c11.
