### ISSUE TITLE
README suggested installation is insecure

### ISSUE THREAD

**Issue by sb10** [nextflow-io/nextflow#1173]
README.md has the suggested installation:

```
curl -fsSL get.nextflow.io | bash
```

But this does not redirect to `https://`, so you're suggesting people pipe a script from an insecure `http` site directly in to bash, which is dangerous.

https://www.nextflow.io has the better install suggestion of:

```
curl -s https://get.nextflow.io | bash
```

Can README.md be updated to the above, or perhaps:

```
curl -fsSL https://get.nextflow.io | bash
```

**Comment by pditommaso** [comment]
Fair enough.
