### ISSUE TITLE
Function inheritance issue

### ISSUE THREAD

**Issue by hydriniumh2** [nextflow-io/nextflow#1177]
## Bug report 

When running a function it overrides the variable outside the scope of the function

### Expected behavior and actual behavior
Expected behavior
```
a = 1
def test() {
a = 2
}
test()
assert a == 1
```
Actual Behavior
```
a = 1
def test() {
a = 2
}
test()
assert a == 2
```
The function has changed the value of `a` outside of its scope. 
### Steps to reproduce the problem

See above

### Program output 

See above

### Environment 

* Nextflow version: version 19.05.0-edge build 5098
* Java version: 1.8.0_202
* Operating system: macOS

**Comment by pditommaso** [comment]
This coherent that `a` is defined in the global scope. If you want a local var declared it as `def a=2`.

**Comment by hydriniumh2** [comment]
Didn't realize that , my bad
