### ISSUE TITLE
Cannot set scoped parameters from the command line

### ISSUE THREAD

**Issue by madkinsz** [nextflow-io/nextflow#1182]
### Expected behavior and actual behavior

**nextflow.config**
```
params {
    subparams.x = 1
    y = 2
}
```

**example.nf**
```
println(params.subparams.x)
println(params.y)
```

`nextflow example.nf --y 3 --subparams.x 2` should update the parameters `x` and `y` and print 2 then 3, but does not update parameter `x`

### Steps to reproduce the problem

See above. Attempt to change any scoped parameter from the command line.

### Program output 

```
❯ nextflow example.nf --y 3 --subparams.x 2
N E X T F L O W  ~  version 19.04.1
Launching `example.nf` [backstabbing_hoover] - revision: d076e55780
1
3
```

### Environment 

* Nextflow version:
```
      N E X T F L O W
      version 19.04.1 build 5072
      last modified 03-05-2019 12:29 UTC (07:29 CDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io
```
* Java version:
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```
* Operating system: AWS Linux, OSX

**Comment by pditommaso** [comment]
Well, this was never intended to work in this way.

**Comment by madkinsz** [comment]
Why not? / Is it technically challenging to implement?

**Comment by ewels** [comment]
Would love for this feature to be implemented 👍🏻

**Comment by drpatelh** [comment]
Yes, this would be really nice to pass additional options to the current DSL2 modules implementation we have on nf-core.

**Comment by combiz** [comment]
Agree, it would be great to see this implemented!  It could also provide a mechanism for a JSON variable defined as an array to be specified at the command prompt.

**Comment by pditommaso** [comment]
Ok, now dots in the parameter names allow the creation of nested scopes eg `--x.y.z Hello`

Not sure it should be possible to escape the dot to avoid it eg. `--x\.y\.z Hello`. It looks a bit overkill to me.

**Comment by drpatelh** [comment]
Amazing!! Thank you. This didn't make it into today's release? Will make it so much easier to change tool specific commands via the CLI.

> `--x\.y\.z Hello`
Maybe just don't use dots in parameter names?! If you think it's a possibility it possibly is! 😅

**Comment by grst** [comment]
> --x\.y\.z Hello

How would I even do that in a config file?

**Comment by pditommaso** [comment]
> This didn't make it into today's release?

Today release is yesterday release 😁 too late sorry. 

> If you think it's a possibility it possibly is! 

Done 

> How would I even do that in a config file? 

The config file is already supported and has nothing changed.
