### ISSUE TITLE
`run` and `pull` subcommands always default to GitHub, even if a full URL is supplied

### ISSUE THREAD

**Issue by wjv** [nextflow-io/nextflow#1186]
### Expected behavior and actual behavior
There are several indications in the documentation that a full URL is sufficient to `run` a pipeline hosted on a remote code repository.

However, even when a full URL pointing to a private repository server is supplied, `nextflow run` and `nextflow pull` will always attempt to access the *qualified name* (i.e. *owner*/*repository*) on `github.com`, irrespective of the repository specified in the URL.

### Steps to reproduce the problem

* Push a Nextflow pipeline project to a repository on a privately hosted server, e.g. `http://private.server.org/owner/somerepo`

* Try to run the pipeline from the repository by supplying the full URL:
   ```   
    nextflow run http://private.server.org/owner/somerepo
   ```

* Nextflow tries to access `https://github.com/owner/somerepo` instead

### Program output 

```
:/tmp$ nextflow run https://vcs.xxx.xxx.de/visagie/sediment_nf
N E X T F L O W  ~  version 19.04.1
Pulling visagie/sediment_nf ...
Cannot find `visagie/sediment_nf` -- Make sure exists a GitHub repository at this address `https://github.com/visagie/sediment_nf`
```

From `.nextflow.log`:

```
Jun-12 21:54:29.575 [main] DEBUG nextflow.cli.Launcher - $> nextflow run 'https://vcs.xxx.xxx.de/visagie/sediment_nf'
Jun-12 21:54:29.666 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.04.1
Jun-12 21:54:29.921 [main] DEBUG nextflow.scm.AssetManager - Repository URL: https://vcs.xxx.xxx.de/visagie/sediment_nf; Project: visagie/sediment_nf; Hub provider: null
Jun-12 21:54:29.952 [main] INFO  nextflow.cli.CmdRun - Pulling visagie/sediment_nf ...
Jun-12 21:54:29.954 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/visagie/sediment_nf/contents/nextflow.config
Jun-12 21:54:31.199 [main] DEBUG nextflow.scm.AssetManager - Project manifest does not exist: https://api.github.com/repos/visagie/sediment_nf/contents/nextflow.config
Jun-12 21:54:31.213 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/visagie/sediment_nf/contents/main.nf
Jun-12 21:54:31.490 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/visagie/sediment_nf
Jun-12 21:54:32.068 [main] DEBUG nextflow.cli.Launcher - Operation aborted
java.io.FileNotFoundException: https://api.github.com/repos/visagie/sediment_nf
```

### Environment 

* Nextflow version: 19.04.1
* Java version: openjdk 10.0.2
* Operating system: Linux 4.4.0 (Ubuntu)

The same behaviour was observed on two systems:

```
  Version: 19.04.1 build 5072
  Modified: 03-05-2019 12:29 UTC (14:29 CEST)
  System: Linux 4.4.0-116-generic
  Runtime: Groovy 2.5.6 on OpenJDK 64-Bit Server VM 10.0.2+13
  Encoding: UTF-8 (UTF-8)
```

```
  Version: 19.04.1 build 5072
  Modified: 03-05-2019 12:29 UTC (14:29 CEST)
  System: Mac OS X 10.14.5
  Runtime: Groovy 2.5.6 on OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
  Encoding: UTF-8 (UTF-8)
```

### Additional context

* `nextflow run` and `nextflow pull` are both affected.

* A workaround is to create a `~/.nextflow/scm` file with the configuration of the private server, and then use the `-hub` flag. This makes it more difficult to give instructions for running pipelines to end users, however.

**Comment by pditommaso** [comment]
=> `[credentials -:-]`, it looks credentials are not provided.

**Comment by wjv** [comment]
The repository on the private server is "public" (to anyone on the local network). When I work around the issue with a `~/.nextflow/scm` file, it contains only:

```
providers {
    orgname {
        server = 'https://vcs.xxx.xxx.de'
        platform = 'gitlab'
    }
}
```
… i.e. no credentials! And then `nextflow pull` works if I use `-hub orgname`.

**Comment by pditommaso** [comment]
Does it work using the `-hub` option instead?

**Comment by wjv** [comment]
Yes, I use `-hub` to get around the problem, as I said in my previous comment. 😄 

Unfortunately that makes the process of distributing pipelines to end users a little more difficult, since I have to first coach them into creating a `~/.nextflow/scm` file.
