### ISSUE TITLE
Setting environment variables for labelled process fails

### ISSUE THREAD

**Issue by klmr** [nextflow-io/nextflow#1187]
### Expected behavior and actual behavior

I am trying to conditionally set environment variables for labelled processes inside `nextflow.config` via a `withLabel` selector. The expected behaviour is that all processes with the chosen label have the environment variable set, and other processes don’t have it set.

What actually happens is that *no* process has the environment variable set, unless the configuration contains a global `env{}` scope (which can be empty) *before* the `process` scope. In that case, **all** processes have the environment variable set, regardless of label.

#### :memo: `main.nf`

```nextflow
process foo {
    label 'foo'
    echo true

    script:
    '''
    echo [foo] ${LABELLED-unset}
    '''
}

process bar {
    echo true

    script:
    '''
    echo [bar] ${LABELLED-unset}
    '''
}
```

#### :memo:  `nextflow.config`

```groovy
process {
    withLabel: 'foo' {
        env { LABELLED = 'labelled' }
    }
}
```

### Program output 

The relevant part of the program output is:

```
[bar] unset

[foo] unset
```

(I expect the last line to read `[foo] labelled`.)
 
<details><summary>:page_facing_up: <code>.nextflow.log</code></summary>

```
Jun-13 15:02:54.644 [main] DEBUG nextflow.cli.Launcher - $> nextflow run main.nf
Jun-13 15:02:54.742 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.04.1
Jun-13 15:02:54.756 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [agitated_hodgkin] - revision: cf7a7fc11e
Jun-13 15:02:54.767 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /raid/konrad/experiments/pipelines/mwe/nextflow.config
Jun-13 15:02:54.767 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /raid/konrad/experiments/pipelines/mwe/nextflow.config
Jun-13 15:02:54.786 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jun-13 15:02:55.214 [main] DEBUG nextflow.Session - Session uuid: d2396d68-5ad6-4fd1-86b3-bb98d9657806
Jun-13 15:02:55.214 [main] DEBUG nextflow.Session - Run name: agitated_hodgkin
Jun-13 15:02:55.214 [main] DEBUG nextflow.Session - Executor pool size: 80
Jun-13 15:02:55.268 [main] DEBUG nextflow.cli.CmdRun -
  Version: 19.04.1 build 5072
  Modified: 03-05-2019 12:29 UTC
  System: Linux 4.15.0-50-generic
  Runtime: Groovy 2.5.6 on OpenJDK 64-Bit Server VM 11.0.3+7-Ubuntu-1ubuntu218.04.1
  Encoding: UTF-8 (UTF-8)
  Process: 24128@harp [127.0.0.1]
  CPUs: 80 - Mem: 125.6 GB (15 GB) - Swap: 128 GB (126.5 GB)
Jun-13 15:02:55.288 [main] DEBUG nextflow.Session - Work-dir: /raid/konrad/experiments/pipelines/mwe/work [ext2/ext3]
Jun-13 15:02:55.289 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /raid/konrad/experiments/pipelines/mwe/bin
Jun-13 15:02:55.383 [main] DEBUG nextflow.Session - Session start invoked
Jun-13 15:02:55.387 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Jun-13 15:02:55.389 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Jun-13 15:02:55.538 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jun-13 15:02:55.614 [main] DEBUG nextflow.util.CacheHelper - Config settings `withLabel:foo` matches label `foo` for process with name foo
Jun-13 15:02:55.617 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jun-13 15:02:55.617 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jun-13 15:02:55.621 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jun-13 15:02:55.623 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Jun-13 15:02:55.626 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=80; memory=125.6 GB; capacity=80; pollInterval=100ms; dumpInterval=5m
Jun-13 15:02:55.629 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Jun-13 15:02:55.630 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Jun-13 15:02:55.664 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Jun-13 15:02:55.737 [main] DEBUG nextflow.Session - >>> barrier register (process: foo)
Jun-13 15:02:55.740 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > foo -- maxForks: 80
Jun-13 15:02:55.771 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jun-13 15:02:55.771 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jun-13 15:02:55.771 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jun-13 15:02:55.773 [main] DEBUG nextflow.Session - >>> barrier register (process: bar)
Jun-13 15:02:55.774 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > bar -- maxForks: 80
Jun-13 15:02:55.777 [main] DEBUG nextflow.script.ScriptRunner - > Await termination
Jun-13 15:02:55.777 [main] DEBUG nextflow.Session - Session await
Jun-13 15:02:56.202 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jun-13 15:02:56.208 [Task submitter] INFO  nextflow.Session - [d6/07c7be] Submitted process > bar
Jun-13 15:02:56.219 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jun-13 15:02:56.220 [Task submitter] INFO  nextflow.Session - [cc/a6725a] Submitted process > foo
Jun-13 15:02:56.276 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 2; name: bar; status: COMPLETED; exit: 0; error: -; workDir: /raid/konrad/experiments/pipelines/mwe/work/d6/07c7be813202c43b35a0755d763f31]
Jun-13 15:02:56.286 [Actor Thread 4] DEBUG nextflow.Session - <<< barrier arrive (process: bar)
Jun-13 15:02:56.287 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: foo; status: COMPLETED; exit: 0; error: -; workDir: /raid/konrad/experiments/pipelines/mwe/work/cc/a6725a45417b0ce4d4944b071aa98d]
Jun-13 15:02:56.288 [Actor Thread 4] DEBUG nextflow.Session - <<< barrier arrive (process: foo)
Jun-13 15:02:56.289 [main] DEBUG nextflow.Session - Session await > all process finished
Jun-13 15:02:56.289 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Jun-13 15:02:56.289 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jun-13 15:02:56.298 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=2; failedCount=0; ignoredCount=0; cachedCount=0; succeedDuration=3ms; failedDuration=0ms; cachedDuration=0ms]
Jun-13 15:02:56.455 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Jun-13 15:02:56.470 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

</details>

The `work/*/*/.command.run` scripts for `foo` and `bar` either both include the `LABELLED` export inside `nxf_main()`, or neither does, consistent with the output I’m getting.

### Environment 

* Nextflow version: 19.04.1.5072
* Java version: OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
* Operating system: Ubuntu 18.04.2 LTS

### Additional context

I might have a major misunderstanding of how the `env` scope is supposed to function, because I observed several other issues related to the above:

* As noted, if `env {}` is included at the beginning of the configuration file, the program output changes to

     ```
    [bar] labelled

    [foo] labelled
     ```

    However, if `env {}` is included at the *end* of the configuration file, I instead get an error:

    > ERROR ~ Unknown config attribute `env` -- check config file

* My understanding of scope syntax [based on the documentation](https://www.nextflow.io/docs/latest/config.html#config-scopes) is that writing `env.LABELLED = 'labelled'` should be equivalent to `env { LABELLED = 'labelled' }` in the above. However, this leads to another error:

    > ERROR ~ Unknown config attribute `env` -- check config file

    … but this happens once again only if the configuration includes a global `env {}` scope.

* When including a *non-empty* `env {}` scope, the error message from the previous bullet point changes:

    > ERROR ~ Unknown config attribute `process.withLabel:foo` -- check config file

**Comment by pditommaso** [comment]
No. This is not supposed to work. You can only use [process directive](https://www.nextflow.io/docs/latest/process.html#directives) in that context.

As a workaround, you can use an [input env](https://www.nextflow.io/docs/latest/process.html#input-of-type-env) in the process definition.

**Comment by klmr** [comment]
I see, that’s actually clearly documented. The lack of error message, combined with the varying behaviour is just confusing. Would it be a lot of effort to include more stringent verification and an explicit error message when parsing the configuration?

**Comment by skelly02** [comment]
@pditommaso  It seems like there should be a process directive that allows for exporting extra env vars, because otherwise there does not appear to be a clear method for conditionally setting env vars for a specific task. This is a problem with something like GPU-enabled Nextflow tasks that need extra env vars if GPU is used

**Comment by stevekm** [comment]
@pditommaso It seems like there should be a process directive that allows for exporting extra env vars, because otherwise there does not appear to be a clear method for conditionally setting env vars for a specific task. This is a problem with something like GPU-enabled Nextflow tasks that need extra env vars if GPU is used

Using an env input item is not really a good solution since I think that would break the ability to conditionally include extra env vars or not based on e.g. if CUDA is required

**Comment by bentsherman** [comment]
I think with static types we will refactor the `env` input as a directive, allowing you to declare arbitrary env vars based on the task inputs. But I'll have to think about whether it makes sense to allow that from the config

**Comment by stevekm** [comment]
thanks, the use case for this is actually from the situation here; https://github.com/nf-core/scdownstream/issues/202

when using GPU, you need to set extra env vars

I could not figure out any way to do that with something like `process.env` or `process { withLabel: "process_gpu" env = "FOO=bar" }`

**Comment by jpfeuffer** [comment]
Same issue for me. I already had three use-cases where specific processes need a different environment variable depending on the user's setup. I do not want to hard code complex logic based on parameters in my pipeline but want that environment variables of e.g. modules can just be overwritten by a config, which currently seems impossible.
