### ISSUE TITLE
key 

### ISSUE THREAD

**Issue by mndavies286** [nextflow-io/nextflow#1193]
Hi! Thanks for using Nextflow. 

If you need help about Nextflow scripting language, 
configuration options and general Nextflow usage the better 
channels to post this kind of questions are: 

* Google group: https://groups.google.com/forum/#!forum/nextflow
* Gitter channel: https://gitter.im/nextflow-io/nextflow

Also you may also want to have a look at the patterns page 
for common solutions to recurrent implementation problems: 
http://nextflow-io.github.io/patterns/index.html

**Comment by pditommaso** [comment]
?

**Comment by mndavies286** [comment]
Hi

I'm having an issue loading multiple files from an s3 object.

bam = Channel.fromPath("s3://sample-input/*bam")

produces the error

"ERROR ~ Key cannot be empty"

The files are there and can be called individually. So I suspect I'm not calling them in the correct way. Can you tell me how to put multiple files from an S3 object into a channel?

BW

Matt
