### ISSUE TITLE
splitCsv "sep" parameter no longer accepts regex

### ISSUE THREAD

**Issue by photocyte** [nextflow-io/nextflow#1197]
## Bug report 

Hi there,
In the past (version 19.01.0), one could pass a regex to splitCsv
```
toParse.splitCsv(sep:'[ \t]+',header:false)
     .map{ row ->
     println row
     return tuple(file(row[2]), file(row[3])) }
     .set{ readPairs_ch }
```

### Expected behavior and actual behavior

In version 19.04.1, the actual expected behavior would be that the regex would be accepted.  But instead an error message is produced:

```
[warm up] executor > local
ERROR ~ Not a valid CVS character: [ 	]+
``` 

I expect this behavior is a side effect due to the changes in:
https://github.com/nextflow-io/nextflow/issues/1102

Is it possible to have regex supported again in splitCsv?  I found it to be a useful feature.

**Comment by pditommaso** [comment]
What if you use `/[ \t]+/` instead of `'[ \t]+'` ?

**Comment by photocyte** [comment]
Doesn't look like it quite works.  Seems to parse every character as a delimiter.

Input file (first row is separated by spaces, second row separated by tabs):
[samples.txt](https://github.com/nextflow-io/nextflow/files/3311125/samples.txt)


Nextflow code:
```
toParse.splitCsv(sep:/[ \t]+/,header:false)
     .map{ row ->
     println row
     return tuple(file(row[2]), file(row[3])) }
     .set{ readPairs_ch }
```

Output (of println)
```
[SRR6345446, SRR6345446-rep1, ./head-100k_SRR6345446_1.fas, q.gz, ./head-100k_SRR6345446_2.fas, q.gz]
[SRR7345580     SRR7345580-rep1 ./head-100k_SRR7345580_1.fas, q.gz      ./head-100k_SRR7345580_2.fas, q.gz]
```
(note that it is splitting on "t", and spaces, but not tabs)

**Comment by pditommaso** [comment]
True, the previous implementation was using `StringUtils.splitPreserveAllTokens(line, sep)` which was interpreting the `sep` string a sequence of character separators, actually as a regex looking at your example. However, it was never meant to be used, not sure this should be considered a bug.
