### ISSUE TITLE
Transferring binary data through `stdout`/`stdin` fails

### ISSUE THREAD

**Issue by wjv** [nextflow-io/nextflow#1199]
## Bug report 

I’ve been invited by @pditommaso to file an issue on this during a Gitter discussion.

Briefly, sending binary data from one process to another via a `stdout` output and a `stdin` input does not function as expected, and causes an exception.

### Expected behavior and actual behavior

One would expect to be able to pass both text and binary data between processes using `stdout` and `stdin`.

### Steps to reproduce the problem

I’ve created a small test case to demonstrate the problem. It can be downloaed from this gist:

https://gist.github.com/wjv/09b1f7d5ac5f45f9ef967c8f79be1eb2

It may be run with `nextflow run binpipe.nf`.

The pipeline contains two processes:

* `getBam` obtains an example BAM file using `curl`, and outputs it on `stdout`
* `viewBam` gets BAM data on `stdin`, converts it to SAM, and outputs it

This fails to work.

Additionally, the pipeline contains a process `viewPipedBam` which duplicates the above processes in one, using a shell pipe. This alternate implementation can be run with the `--shellpipe` flag. This was included merely to show that ordinarily, this should work!

### Program output 

Execution encounters an exception `java.nio.charset.MalformedInputException: Input length = 1`

The `.nextflow.log` generated by the pipeline is at this gist:

https://gist.github.com/wjv/f9810c3f1b2c6fe73b466022552332c6

### Environment 

  Version: 19.04.1 build 5072
  Modified: 03-05-2019 12:29 UTC (14:29 CEST)
  System: Mac OS X 10.14.5
  Runtime: Groovy 2.5.6 on OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
  Encoding: UTF-8 (UTF-8)

### Additional context

None.

**Comment by wjv** [comment]
This issue still persists in Nextflow 19.07.0 build 5106.

Tested on macOS 10.14.6 and Ubuntu 16.04.6, both using using the same JDK as above.

**Comment by liameabbott** [comment]
Are there any updates here? I'm currently running into this issue in v20.07.1 build 5412.
