### ISSUE TITLE
DSL-2 process input set does not work

### ISSUE THREAD

**Issue by rithy8** [nextflow-io/nextflow#1200]
## Bug report 

I ran the following program below, and there are bugs

### Expected behavior and actual behavior

Expected one process running, but two processes ran. Also, input files did not linked.

### Steps to reproduce the problem
Below is my script.
```
nextflow.preview.dsl=2

aFile = Channel.fromPath("/Users/rothr11/dev/nextflow/sandbox/a.txt")
bFile = Channel.fromPath("/Users/rothr11/dev/nextflow/sandbox/b.txt")

tuple = Channel.from( aFile, bFile )

process setExample {
    input:
    set file(aFile), file(bFile)

    script:
    """
    echo "hello" > hello.txt
    """
}
setExample(tuple)
```
### Program output 

```
N E X T F L O W  ~  version 19.05.0-edge
Launching `aaa.nf` [agitated_albattani] - revision: f3400f61fe
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
[warm up] executor > local
executor >  local (2)
[b5/de6bb9] process > setExample (1) [100%] 2 of 2 ✔
WARN: Input tuple does not match input set cardinality declared by process `setExample` -- offending value: DataflowBroadcast around DataflowStream[?]
WARN: Task runtime metrics are not reported when using macOS without a container engine
```

Work dir:
total 24
lrwxr-xr-x  1 rothr11  staff  86 Jun 22 13:29 input.2 -> /Users/rothr11/dev/nextflow/sandbox/work/tmp/2c/1564d666a7e3765e5b74d499289209/input.2
lrwxr-xr-x  1 rothr11  staff  86 Jun 22 13:29 input.1 -> /Users/rothr11/dev/nextflow/sandbox/work/tmp/af/700974ef022fe94b4cf49a27794e6b/input.1
-rw-r--r--  1 rothr11  staff   6 Jun 22 13:29 hello.txt

### Environment 

* Nextflow version: [19.05.0-edge]
* Java version: [1.8.0_131]
* Operating system: [macOS]

**Comment by pditommaso** [comment]
The following line is not expected to work 

```
tuple = Channel.from( aFile, bFile )
```

You need either to change the input declaration as shown below: 

```
process setExample {
    input:
    set file(aFile), file(bFile)

    script:
    """
    echo "hello" > hello.txt
    """
}
``` 

or create a new channel holding the values from both using [join](https://www.nextflow.io/docs/latest/operator.html#join) or [merge](https://www.nextflow.io/docs/latest/operator.html#merge).

**Comment by rithy8** [comment]
Thank you for correcting me. I am sorry I misunderstood.
