### ISSUE TITLE
New path input/output process qualifier

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#1201]
This enhancement adds a new `path` qualifier in the process definition either for input and output clauses. 

#### 1. Avoid double typing and enhance readability 
 
Currently, the process `file` qualifier requires an input file to be explicitly converted to a file object, either using `file()` function of the `Channel.fromPath` channel factory method. 

This is counter-intuitive and results in ugly definitions such as: 

```nextflow
process foo {
   input:
     file x from file('/some/data')
  """
    etc
  """
}  
```

When using the `path` qualifier and input string is implicitly converted to a `Path` object without the need of an explicit conversion. For example: 

```nextflow
process foo {
  input: 
    path x from '/data/file.txt'
  output: 
    path 'result.txt'
  """
  cat $x > result.txt
  """  
}
``` 

This makes also much easier to ingest csv/txt file containing a collection of path locations without the need to converting the path to a file object.

The path location string *must* be a string not containing any special character and it must start with a `/` character (absolute path) or URL protocol prefix.  

#### 2. Enable the specification of file input/output file options 

The `path` should allow the setting of optional parameters using the column key-pair syntax, eg 

```nextflow 
process foo {
  output:
   path 'file.txt', hidden:true, maxDepth: 3 into result_ch
  """
    echo Hello > file.txt
  """
}
```

The above syntax sets the of the optional `hidden` and `maxDepth` parameters in the output definition. 

This also makes it possible to specify path specific setting when declaring a composed output as `set`. 

~~#### 3. Allow optional input paths~~

It should be possible to declare an optional input `path`. The input will be considered as not provided when the channel will provide a `null` value instead of a path string. 

```nextflow
process foo {
  input:
  path x, optional:true from ch
  script:
  if( x ) 
   /command --input $x/
  else 
   /command --no-input/
} 
```

~~#### 4. Allow named input/output paths~~

The `path` syntax should allow the definition of a name alias to reference either input and output variables

```nextflow
process foo {
  input:
    path 'file.x' as x 
  output:
   path 'result.txt' as z
  """
    cat $x > result.txt
  """
}

foo.out.z.view()
```

See also #1181.

**Comment by pditommaso** [comment]
Goal 3 and 4 are moved to separate enhancements.

**Comment by felixschlesinger** [comment]
> Goal 3 and 4 are moved to separate enhancements.

Is there a separate issue for these? I couldn't find it.
