### ISSUE TITLE
file method does not follow redirects on http paths

### ISSUE THREAD

**Issue by tobsecret** [nextflow-io/nextflow#1204]
### Expected behavior and actual behavior

I am using a remote file from an http server:

```
ref = file('https://plasmodb.org/common/downloads/release-10.0/PvivaxSal1/fasta/data/PlasmoDB-10.0_PvivaxSal1_Genome.fasta')
```
wget fetches the file in question just fine, however, nextflow fetches the first http response it gets, which in this case is:
```
<html> 
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```
This means the http request was redirected.
Expected behaviour is that nextflow follows the redirect on a response like that.

### Steps to reproduce the problem
```
ref = file('https://plasmodb.org/common/downloads/release-10.0/PvivaxSal1/fasta/data/PlasmoDB-10.0_PvivaxSal1_Genome.fasta')
println ref.text
```

### Program output 
```
<html> 
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```
### Environment 

* Nextflow version: 19.04.0.5069
* Java version: openjdk version "1.8.0_171"
* Operating system: Linux (CentOS Linux 7 (Core))

**Comment by pditommaso** [comment]
Doesn't look a redirect file 

```
curl --max-redirs 0  -I https://plasmodb.org/common/downloads/release-10.0/PvivaxSal1/fasta/data/PlasmoDB-10.0_PvivaxSal1_Genome.fasta

HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Mon, 08 Jul 2019 14:06:24 GMT
Content-Type: application/x-fasta
Content-Length: 27725373
Connection: keep-alive
Last-Modified: Fri, 11 Oct 2013 14:21:12 GMT
ETag: "1a70e3d-4e877d4930600"
Accept-Ranges: bytes
X-FRAME-OPTIONS: SAMEORIGIN
```

**Comment by tobsecret** [comment]
Hmmmm, weird - now it works just fine. Maybe it was a server-side problem? Or it was a reaction to me sending too many requests that day :thinking:
