### ISSUE TITLE
input from a channel of null value makes execution hang

### ISSUE THREAD

**Issue by yunfeiguo** [nextflow-io/nextflow#1208]
## Bug report 

Hi Paolo,

I have the following script where a process takes a `null` value in input channel, the process hangs rather than skipping execution as one would expect. Wonder if it's related to #764?
Also just to confirm is `when` directive supposed to be evaluated after the input channel is evaluated?
### Expected behavior and actual behavior

expect execution to skip due to no legitimate input

### Steps to reproduce the problem

```
x = null
if (x) {
println('yes')
}
process j {
        input:
        val(a) from Channel.from(x)
        when:
        x
        script:
        println(a)
        """
        true
        """
}
```

### Program output 

```
N E X T F L O W  ~  version 19.04.1
Launching `t.nf` [insane_almeida] - revision: aeab1ff168
[warm up] executor > local
```
[nextflow.log](https://github.com/nextflow-io/nextflow/files/3343569/nextflow.log)

### Environment 

* Nextflow version: 19.04.1 
* Java version: 1.8.0_60
* Operating system: macOS

**Comment by pditommaso** [comment]
Yes, this should not happen, thanks for reporting. So far the only workaround is to prevent to have `null` values as input.

**Comment by yunfeiguo** [comment]
Got it. Thanks!
