### ISSUE TITLE
Allow publishDir "move" mode for non-terminating processes

### ISSUE THREAD

**Issue by mfoll** [nextflow-io/nextflow#121]
Currently the "move" mode in publishDir is only working for a terminating process i.e. a process whose output is not consumed by any other downstream process. It would be useful for pipelines creating large intermediate files to be able to do it for any process, to avoid having to copy those files. One option would be to move the files and to create a symlink pointing to them in the work folder. Another possibility would be to postpone the move of the files to the end of the pipeline.

**Comment by qobilidop** [comment]
You might want to use [storeDir](https://www.nextflow.io/docs/latest/process.html#storedir) for this.
