### ISSUE TITLE
DSL-2 job won't run in sge

### ISSUE THREAD

**Issue by rithy8** [nextflow-io/nextflow#1212]
## Bug report 

Job submitted to SGE won't run.

### Expected behavior and actual behavior

With nextflow version older than 19.01.0, nextflow process that requires 10 cores and a total of 120GB of memory can run successfully.

With DSL-2 the process cannot run( stay in "qw" state).  In the .command.run file, there is this option: 
```#$ -l h_rss=122880M,mem_free=122880M```

If the "mem_free" portion is removed, the process can run

### Steps to reproduce the problem

aFile = Channel.fromPath("hello.txt")

process aaa{
   memory  '120 GB'
   cpus  10
   clusterOptions = '-l h_vmem=12G ' + clusterOptions
   input:
      file(aFile)
  script:
     """
     echo "world" > world.txt
    """   
}

### Environment 

* Nextflow version: [19.05.0-edge] 
* Java version: [1.8.0_92]
* Operating system: [CentOs-07]

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
This is unrelated to DSL2, the mem requirement is there because in the process is specified `memory '120 GB'`.

**Comment by grayshiwb512** [comment]
@pditommaso, I have the same problem. The same memory requirement definition works well for release older than v19.01.0, but the jobs stay in 'qw' when I use the latest Nextflow releases. Do we still need to define `memory` in the process? Does the docker run set up the memory requirement based on `memory` defined in the process?
thanks,

**Comment by grayshiwb512** [comment]
@pditommaso, I found the following description of `mem_free` usage, which explained to me why the job will stay in 'qw'. Briefly, the `mem_free` need to set to the same amount as `h_vmem`, which is per slot memory, when you specify `-pe`, then the total memory will be multiplication of `mem_free` and the number of slots. However, in the latest releases of Nextflow, the `mem_free` use the value defined in the `memory` in the process.

```
To run a multi-core job on a single node you must request a parallel environment with multiple slots (where one slot corresponds to one CPU-core). In addition, if the cluster is busy, it is critical to tell SGE to reserve slots for your job, otherwise, a sufficient number of slots may never become available for your job. The problem is that your multi-slot job gets “starved” because individual slots are filled by single-slot jobs as quickly as they are freed up by terminating jobs.

Use the   -pe local K   option to request K slots on a single cluster node.
use the -R y option to turn on slot reservation.
Use the  mem_free=NG  option to specify N Gigabytes of memory your job.  Important: the value, n, you set in mem_free is the total memory you need divided by the number of slots specified for -pe. In other words n=N/K.
Use h_vmem= nG to set the hard memory limit for your job. Important: the value, n, you set in h_vmem is the total memory you set via  mem_free divided by the number of slots specified for -pe. In other words n=N/K.
For example, suppose your job needs 6 slots and we want to use slot reservation because the cluster is busy. Moreover, suppose we expect our job to need 36G. We would submit the job with the following command:

     qsub -pe local 6 -R y -l mem_free=6G,h_vmem=6G  myScript.sh
```
Is this could be a bug?

**Comment by pditommaso** [comment]
Since version 19.04.1, NF uses physical memory instead of virtual mem for SGE job requests for consistency with other batch schedulers. 

In particular in your example you are specifying  `memory '120 GB'` ie. 120 GB of RAM, then using clusterOption `'-l h_vmem=12G '` ie. 12 GB of virtual memory which makes no sense and likely cause the job to stall

**Comment by emi80** [comment]
Hi @grayshiwb512, I think this really depends on you cluster configuration.

What do you get if you run the following command for you queue?

```
qstat -F mem_free,h_vmem -q <YOUR_QUEUE>
```

**Comment by grayshiwb512** [comment]
Hi @pditommaso ,
Here is an example of output from `qstat -F mem_free,h_vmem -q <YOUR_QUEUE>`

```
[shiw14@lb094dev ~]$ qstat -F mem_free,h_vmem -q all.q|head
queuename                      qtype resv/used/tot. np_load  arch          states
---------------------------------------------------------------------------------
all.q@lb001.sc1.sci BIP   0/0/28         0.00     lx-amd64      d
	hl:mem_free=240.447G
	hc:h_vmem=250.000G
---------------------------------------------------------------------------------
all.q@lb002.sc1.sci BIP   0/0/28         0.00     lx-amd64      d
	hl:mem_free=239.414G
	hc:h_vmem=250.000G
---------------------------------------------------------------------------------
```
And in my test job, the `mem_free=120G`.
thanks,
