### ISSUE TITLE
STDOUT is left aligned when using ANSI mode

### ISSUE THREAD

**Issue by chadisaad** [nextflow-io/nextflow#1219]
The STDOUT output in terminal is aligned to left, all left spaces are removed !

Exemple:
`nextflow-19.04.1-all run main.nf`

![bug2](https://user-images.githubusercontent.com/4546477/60803998-c3880a00-a17c-11e9-904b-ae3848a835d3.png)

when deactivating ANSI mode, problem is resolved
`NXF_ANSI_LOG=false  nextflow-19.04.1-all run main.nf`

![bug1](https://user-images.githubusercontent.com/4546477/60803970-aeab7680-a17c-11e9-8309-70f60e1d2105.png)

**Comment by pditommaso** [comment]
Have fun 

https://github.com/nextflow-io/nextflow/blob/de5fd58bcc1e91f3fbe09a7e6039e0ad0ac5dec1/modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy#L213-L233


😅

**Comment by pditommaso** [comment]
Unable to replicate
