### ISSUE TITLE
Process `start` time is not reported correctly when using the Ignite executor

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#122]
The Ignite executor reports as process `start` time the same value as the `submit` time. Thus, it does not take into account possible delay in task scheduling due to missing computing resources. 

As a consequence the trace and timeline files reports invalid process start execution time.

![vc8shblj](https://cloud.githubusercontent.com/assets/816968/14172078/9bd0173a-f736-11e5-93a1-297ef929e6de.jpg)
 
In the above examples all the mapping processes appear to start at the same time and having a long delay to complete (grey area). Instead the grey area should be reported on the left for some of them.

**Comment by robsyme** [comment]
Nice. Thanks Paolo.

**Comment by pditommaso** [comment]
Just in case, did you have change to verify it is working fine?
