### ISSUE TITLE
Google Pipelines - Support for customized disk size

### ISSUE THREAD

**Issue by mozack** [nextflow-io/nextflow#1220]
## New feature

I'd like to propose using the ```disk``` process directive to define the disk size used when running using the google-pipelines executor

## Usage scenario 

Many jobs require less than the default 500GB of disk and we can use fewer resources (and money) by customizing the disk needs.  Similarly, some jobs will require more than 500GB and cannot currently be run at all.

## Suggest implementation 

I believe we can simply use the existing disk directive and propagate the disk size in GB to disk.setSizeGb() in GooglePipelinesHelper.groovy.  I need to test this to confirm though.

If you agree with the suggested implementation, I will try it out and submit a Pull Request if it behaves as expected.

**Comment by pditommaso** [comment]
It makes sense 👍

**Comment by daudn** [comment]
How would I set disk size at runtime? My pipeline spins up quite a lot of instances, and so 500GB is way too much.

**Comment by daudn** [comment]
Or rather, replace this disk with Filestore that is shared amongst all the instances?

**Comment by mozack** [comment]
Use the disk directive to set instance level disk size:
https://www.nextflow.io/docs/latest/process.html#disk

My experiments with Filestore disk went poorly.  I do not believe it is intended for high throughput with many instances.

**Comment by daudn** [comment]
This is the usual disk that's attached to the instance and is 10GB by default. There is a google-pipelines additional disk which has a default of 500 GB. How can we customize that? Also, I had a mnaual workflow where Filestore worked quite welll, given all the files being operated on were in seperate directories. Is it possible to attach the filestore to any given instance? Possibly if Nextflow could use an instance template of my choosing, I could attach the filestore in the startup script!

**Comment by mozack** [comment]
The disk directive functionality was added after 19.07, so you will need to use one of the more recent edge releases.  You can add the following to use a specific release:

export NXF_VER=19.09.0-edge

Then you should see "additional disk" be set to the size you specify.
