### ISSUE TITLE
DSL2 nextflow stopped when put into background in shell

### ISSUE THREAD

**Issue by rithy8** [nextflow-io/nextflow#1221]
## Bug report 

bash shell running nextflow stopped when running in background mode. When running in foreground everything worked.

### Expected behavior and actual behavior

nextflow should continue to run when launched in background mode.

### Steps to reproduce the problem
Below is my script. I ran it with the following command line:

```nextflow run dotestsub.nf 2>&1 > foo.txt &```
And, when I tailed foo.txt, nextflow stuck at this line:

```
N E X T F L O W  ~  version 19.05.0-edge
Launching `dotestsub.nf` [disturbed_liskov] - revision: cfa14e665c
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
[warm up] executor > sge

```
When I type `jobs -l`, my system showed the following:
```
[1]+ 29350 Stopped (tty output)    nextflow run dotestsub.nf 2>&1 > foo.txt
```

```
nextflow.preview.dsl=2

process sayHello {
  echo true
  cpus 1
  memory '1 GB'
  container interopImage
  clusterOptions = '-l h_vmem=1G ' + '-S /bin/bash -l docker_version=new -P onco'
  executor = 'sge'
  queue = 'all.q'
  penv = 'smp'

  input:
      val(aaa)
  script:
  """
  echo "hello" > hello.txt
  """
}

sayHello("bbb")
```

### Program output 

```
N E X T F L O W  ~  version 19.05.0-edge
Launching `dotestsub.nf` [disturbed_liskov] - revision: cfa14e665c
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
[warm up] executor > sge
```
When I type `jobs -l`, my system showed the following:
```
[1]+ 29350 Stopped (tty output)    nextflow run dotestsub.nf 2>&1 > foo.txt
```

### Environment 

* Nextflow version: [19.05.0-edge] 
* Java version: [1.8.0_92]
* Operating system: [CentOS Linux]

### Additional context

Please help me. Thanks

**Comment by pditommaso** [comment]
When running in the background you should specify the `-bg` command-line option.

**Comment by rithy8** [comment]
Oh, did not know nextflow has background option. Thank you.

**Comment by grayshiwb512** [comment]
Thank you, @pditommaso !
Does the "-bg" command-line option documented? I search the documentation and cannot find it as shown below,
![image](https://user-images.githubusercontent.com/11650908/61068378-bc503e80-a3be-11e9-8ca9-ea17a69c3c81.png)

thanks,
Paul

**Comment by pditommaso** [comment]
It should, so far the only doc is available through `nextflow run -h`
