### ISSUE TITLE
k8s executor should delete pods if nextflow is killed

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1222]
The k8s executor is generally very good about cleaning up after itself, i.e. when the workflow completes or fails. However, if the user kills the workflow with Ctrl-C it looks like nextflow just exits immediately and does not delete running pods.

The k8s executor should delete all the pods that it submitted, and kuberun should delete the controller pod that it created. I think kuberun login already does this correctly.

**Comment by bentsherman** [comment]
Some additional context: exiting kuberun via Ctrl-C doesn't terminate the workflow on the k8s cluster, it just terminates kuberun, which is only forwarding the logs from the workflow pod. However, deleting the workflow pod does not cause the task pods to be deleted, whereas they probably should. It may be possible to implement a delete operation as a termination hook in the workflow pod. The task pods can also be deleted by an external service (i.e. nf-tower) by querying all pods that match `.metadata.labels.runName`.

**Comment by pditommaso** [comment]
Do I remember correctly that K8s jobs do not need to be deleted?

**Comment by bentsherman** [comment]
@pditommaso I'm not sure, maybe there was a discussion elsewhere about it. I think 95% of the time the pods will finish on their own. But there are edge cases. Pods can get stuck in a pending state. On a cloud platform, users may want the pods to be deleted immediately because they are being charged.

The thing is that I am conflicted on who should be responsible for the cleanup. We could add a prestop hook to the workflow pod, or we could leave it up to the user / external service to clean up dangling pods. It can be done with two kubectl calls:
```
# query list of pods
PODS=`kubectl get pods --output custom-columns=NAME:.metadata.name,RUN:.metadata.labels.runName \
	| grep ${RUN_NAME} \
	| awk '{ print $1 }'`

# delete pods
if [[ ! -z ${PODS} ]]; then
	kubectl delete pods ${PODS}
fi
```
