### ISSUE TITLE
how to set job priority

### ISSUE THREAD

**Issue by feihongloveworld** [nextflow-io/nextflow#1225]
hi sir：
how to set job priority base on sample_data size? i want that bigger data sample run before small one.
can nextflow do that?

**Comment by pditommaso** [comment]
?

**Comment by feihongloveworld** [comment]
hi sir：
     how to set job priority base on sample_data size? i want that bigger data sample run before small one.

**Comment by pditommaso** [comment]
What is written in the first comment you posted?

**Comment by feihongloveworld** [comment]
> What is written in the first comment you posted?

just a mistake  - . -

**Comment by feihongloveworld** [comment]
> What is written in the first comment you posted?

can nextflow set the  priority of difference jobs ?

**Comment by elmsly** [comment]
Hi, I'm also interested in this. Simplifying slightly: I have two processes, both of which need to run a large number of times.

- The first process downloads a large file to scratch
- The second process moves that file to a large datastore

The move operation needs to happen in a special staging queue on our grid scheduler, and that queue should not be used for other processing. I also limit the queue size to keep the number of concurently running tasks down so I don't swamp the grid with these download tasks.

The problem I'm running into is that nextflow will queue up all instances of the first process, and only when they are all downloaded will it start any instances of the second process. This is quite taxing on disk space, so I'd like some way of telling nextflow to prioritise running the second move process as soon as possible.

Is it all possible to set the priority of different jobs in nextflow's internal queue? Alternatively should I be designing my workflow differently?

Thanks!

**Comment by pditommaso** [comment]
There's no concept of job priority in NF. You need to refactor your script to have a big block-the-world task.

**Comment by scottgigante-immunai** [comment]
I am also interested in this. I have two sets of jobs: long-running jobs A, and short-running jobs B that depend on jobs from A. If there is capacity to run an additional job, I'd rather it come from A -- but if all the submitted jobs in A are already running and there is still capacity, I'd still rather run a job from B than wait for a block-the-world process for all of A to finish.

**Comment by mribeirodantas** [comment]
Hello, @scottgigante-immunai. Depending on where you're running your pipeline, you can assign different processes [to different queues](https://www.nextflow.io/docs/latest/process.html?highlight=queue#queue), for example. Also, you can control `maxForks` at the process level, so if you're willing to [let one process have more instances in parallel than others](https://www.nextflow.io/docs/latest/process.html?highlight=queue#maxforks).

As job priority is very tied to where you're running your pipeline, it doesn't make sense to handle that at the Nextflow level, so Nextflow depends on what's provided by each executor.

**Comment by scottgigante-immunai** [comment]
That's helpful, thanks! So in my case (running on AWS Batch) I just set the priority by assigning to different queues which have priority set in the AWS console. Thanks!
