### ISSUE TITLE
Allow for a per-job memory limit for LSF executor

### ISSUE THREAD

**Issue by mfoll** [nextflow-io/nextflow#123]
LSF implements both a per-process or a per-job memory limit: https://www.ibm.com/support/knowledgecenter/#!/SSETD4_9.1.3/lsf_config_ref/lsf.conf.lsb_job_memlimit.5.dita

Currently nextflow assumes it's a per-process limit and therefore divides the amount of memory requested by the number of cpus requested (https://github.com/nextflow-io/nextflow/blob/c49f5613521500c24f6d57482e4d45dcbd86249b/src/main/groovy/nextflow/executor/LsfExecutor.groovy#L66). 

It would be useful to have a flag in the nextflow config file to control for this and avoid dividing if the limit is per-job.

**Comment by pditommaso** [comment]
OK. I've uploaded a new snapshot including this patch. 

You can switch to the per-job memory limit mode adding the following config setting in your `nextflow.config` file. 

    executor {
         perJobMemLimit=true
    }


To use this snapshot prepend the variable `NXF_VER=0.18.0-SNAPSHOT` to your nextflow command line, for example: 

    NXF_VER=0.18.0-SNAPSHOT nextflow run .. 

Could you please give it a try to verify that this and #124 are working as expected?

**Comment by mfoll** [comment]
Thanks, I just tried and it's working great! Just one thing for #124, when `perJobMemLimit=false` you should still not divide the memory by the number of cpus for the reservation.

**Comment by pditommaso** [comment]
Oops, you are right. Thanks!
