### ISSUE TITLE
Log completed processes in the non-ANSI log

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1231]
## New feature

The nice thing about the ANSI log (aside from being more compact) is that it provides a measure of progress, whereas the old logger only prints when a process is submitted or failed. But the old logger is still useful in cases like kubernetes where the log is streamed remotely.

I think a simple solution would be for the old logger to log completed processes as well. Like this:
```
[d1/1c4fb6] Submitted process > import_emx (Yeast.emx)
...
[d1/1c4fb6] Completed process > import_emx (Yeast.emx)
```

**Comment by pditommaso** [comment]
In principle, the ansi logging should work also when streaming it remotely. There's should be some encoding problem I didn't manage to figure it out. 

IMO, the best solution would be to allow the ANSI logging also when using `kuberun`.

**Comment by bentsherman** [comment]
It does work but it's a bit unwieldy because it prints the entire log when anything changes, so it ends up being very long and hard to read.

Aside from that, in principle it makes sense to log completed processes because the ANSI logging provides that as well.
