### ISSUE TITLE
errorStrategy retryAndIgnore a combination of retry and ignore

### ISSUE THREAD

**Issue by davidcotter** [nextflow-io/nextflow#1238]
## New feature

I would like an error strategy of retryAndIgnore

that would perform as retry as it does with the "retry" but if all retries fail would ignore the error as "ignore" does.

## Usage scenario 
I have an long running pipeline where I expect certain steps to fail but this can be because of temporary network issues so a retry can solve this but sometimes it is permanent and in this case I would like the pipeline to continue rather than stop.

## Suggest implementation 
This is a combination of the "retry" and "ignore" strategies currently implemented

**Comment by pditommaso** [comment]
Duplicate of #563
