### ISSUE TITLE
Wildcards input in Google Storage path not working (Genomics Pipelines)

### ISSUE THREAD

**Issue by replikation** [nextflow-io/nextflow#1239]
## Bug report

* wildcards not working for google genomics pipeline (?)

### Expected behavior and actual behavior

* I want to use multiple input files that are stored on a google bucket to analyse them in parallel
* If i am using wildcards in the Google Storage path Nextflow can't finde these files
* Is there a way to use multiple files stored in a google cloud bucket?
* Everything works as intended if i don't use wildcards.

#### 1. Working command (no wildcards)

This command without wildcards **is working**:

```bash
nextflow run main_small.nf --reads 'gs://nextflow-auto-bucket/nextflow-workdir/fastq/sample09.fastq' \
-profile gcloud -bucket-dir gs://nextflow-auto-bucket/nextflow-workdir
```

**program output:**

```bash
N E X T F L O W  ~  version 19.04.1
Launching `main_small.nf` [infallible_euclid] - revision: f46f2ae052
[warm up] executor > google-pipelines
[warm up] executor > local
Got: [sample09, /nextflow-workdir/fastq/sample09.fastq]
executor >  google-pipelines (1), local (1)
[85/9876a8] process > assembly [100%] 1 of 1 ✔
[40/567f72] process > bandage  [100%] 1 of 1 ✔
Completed at: 22-Jul-2019 12:56:36
Duration    : 21m
CPU hours   : 5.5
Succeeded   : 2
```

#### 2. NOT Working command (with wildcard)

This command (with wildcard) is **not working**:

```bash
nextflow run main_small.nf --reads 'gs://nextflow-auto-bucket/nextflow-workdir/fastq/sample*' \
-profile gcloud -bucket-dir gs://nextflow-auto-bucket/nextflow-workdir
```

**program output:**
```bash
N E X T F L O W  ~  version 19.04.1
Launching `main_small.nf` [insane_bhaskara] - revision: f46f2ae052
[warm up] executor > google-pipelines
[warm up] executor > local
ERROR ~ No files match pattern `sample*` at path: /nextflow-workdir/fastq/

 -- Check '.nextflow.log' file for details
```

#### Code from the script

code from the `main_small.nf` for the file input

```Java
if (params.reads == '') {exit 1, "--reads is a required parameter"}

readFileList_ch = Channel
              .fromPath( params.reads , checkIfExists: true)
              .map { file -> tuple(file.simpleName, file)}
readFileList_ch.into { filter_assembly_ch; readList_report_ch }
readList_report_ch.subscribe { println "Got: ${it}" }
```

### Program output

* i attached also the log file, the (maybe) important part is this:

```java
Jul-22 12:41:21.098 [PathVisitor-1] ERROR nextflow.Channel - No files match pattern `sample*` at path: /nextflow-workdir/fastq/
java.lang.IllegalArgumentException: No files match pattern `sample*` at path: /nextflow-workdir/fastq/
	at nextflow.file.PathVisitor.pathImpl(PathVisitor.groovy:160)
	at nextflow.file.PathVisitor.applyGlobPattern0(PathVisitor.groovy:110)
	at nextflow.file.PathVisitor.apply(PathVisitor.groovy:70)
	at nextflow.file.PathVisitor$_applyAsync_closure1.doCall(PathVisitor.groovy:76)
	at nextflow.file.PathVisitor$_applyAsync_closure1.call(PathVisitor.groovy)
	at groovy.lang.Closure.run(Closure.java:486)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jul-22 12:41:21.102 [PathVisitor-1] DEBUG nextflow.Session - Session aborted -- Cause: No files match pattern `sample*` at path: /nextflow-workdir/fastq/
```

### Environment

* Nextflow version: version 19.04.1 build 5072
* Java version: openjdk version "1.8.0_212"
* Operating system: Ubuntu 16.04.6 LTS

### Additional context

* wildcards work if i use local files 
* this works:

```bash
nextflow run main_small.nf --reads 'fastq/sample*' \
-profile gcloud -bucket-dir gs://nextflow-auto-bucket/nextflow-workdir
```
[nextflow_gcloud.log](https://github.com/nextflow-io/nextflow/files/3416947/nextflow_gcloud.log)

**Comment by pditommaso** [comment]
The `gs://` protocol must prefix the path e.g. 

```
Channel
 .fromPath('gs://nf-demo/rnaseq/data/*.fq')
 .view()
```

**Comment by replikation** [comment]
but i added the `gs://` in front of the commands. So why is the prefix removed in the log files? 
i used now your code, directly with the channel to show that its not working for me with wild cards:

**cant find file** 
```bash 
Channel
.fromPath('gs://nextflow-auto-bucket/nextflow-workdir/fastq/sample*.fastq', checkIfExists: true)
.view()
```
___________________
This is able to find the file within the cloud storage (This is just to show you that the gs:// path is working and the file location is correct)
```bash
Channel
.fromPath('gs://nextflow-auto-bucket/nextflow-workdir/fastq/sample09.fastq', checkIfExists: true)
.view()
```

**Comment by pditommaso** [comment]
> So why is the prefix removed in the log files?

That's a quirk behaviour of the Java api. If you use this snippet, it will print the full URI 

```
Channel
 .fromPath('gs://nf-demo/rnaseq/data/*.fq')
 .view { it.toUriString() }
```

If still does not work it may be a permission problem in your bucket.

**Comment by replikation** [comment]
Okay it showed the fully path with `.view { it.toUriString() }`, but its still not working.

i even executed everything directly through the cloud shell - to avoid possible permission issues of a service account with JSON key. While `gsutil ls gs://nextflow-open/fastq/*.fastq` is working fine with a wildcard, nextflow still cant find the files with a wildcard. If its a permission problem i'am not sure how to fix it for nextflow. I added stuff like Storage Admin, Storage Object Admin to the bucket and accounts etc. I also tryed the "Bucket Policy Only".

Would still be nice if nextflow.io could clarify what permissions are needed, but thanks anyway.

**Comment by phiweger** [comment]
I can replicate this problem. Like the OP, I am not sure what else to try. @pditommaso are you able to use wildcards in the above mentioned use case? Thanks a lot!

**Comment by pditommaso** [comment]
Yes, the above snippet just work. This is a permission problem. I have the bucket configured with *Storage Admin* permissions.

**Comment by replikation** [comment]
Hi, thanks for the reply. Its still not working. 
+ I'am currently using a workaround for nextflow
     + its a text file with one sample path per line, so i can run multiple samples in parallel

For the Wildcard issue:
* The **account** roles of the service account via IAM is: 
     * `Owner` 
     * `Storage Admin`
* The **bucket** roles of the service account is:
    * `Storage Admin` (Inherited from the IAM role)
    * `Storage Legacy Bucket Owner`
* The bucket `Access control model` is set to `Bucket policy & ACLs`. 


+  `gsutil acl get` tells me the role of my account is "owner".

Is there any other information i can provide?

**Comment by replikation** [comment]
Okay, I've identified the problem: 
* Apparently I can not access anything from my service account that I've uploaded with my regular account and vice versa. 
* Although both are storage administrators and Owner.

The Wildcards worked with the files that Nextflow had automatically uploaded into the workdir `stage`:
So this command worked correctly:
`--reads" gs: //nextflow-pipeline/workdir/stage/*/*/S_41_17_Cf*.R {1,2} .fastq.gz "`

I noticed this issues on my regular account. i mountet the bucket in cloud shell and was not able to access the nextflow workdir.
I think its similar to this issue: [link](https://serverfault.com/questions/811456/why-cant-i-access-a-cloud-storage-object-despite-being-a-project-owner)

**Comment by phiweger** [comment]
@pditommaso 

> I have the bucket configured with Storage Admin permissions.

Can you elaborate? Do you assign these permissions to the service account? 

Thanks a lot!

**Comment by phiweger** [comment]
For example, I created a bucket `foobar-bucket` with IAM permissions (not ACL) at the bucket level (not object level).

I then add a service account to the project `foobar`. I then use the project's email as it appears in the corresponding key file, e.g. `foobar-key@foobar.iam.gserviceaccount.com`.

Then, in the bucket permissions, I add permissions for this email with roles "Storage Admin" and "Storage Object Admin".

No change. I can `.view()` files that I specify with the exact path (`gs://foobar-bucket/reads/mock.fastq.gz`), but not using wildcards (`gs://foobar-bucket/reads/*.fastq.gz`).

If it is a permission issue, where do I make a mistake in the above mentioned settings?

Thanks a lot!

**Comment by pditommaso** [comment]
@olifly @moschetti Have you any idea what could be the problem using glob patterns with Google Storage?

**Comment by tamuanand** [comment]
Hi @replikation 

Can you share this workaround - I seem to have a similar issue trying to access S3 buckets,

> * I'am currently using a workaround for nextflow, which works:
>   * its a text file with one sample path per line, so i can run multiple samples in parallel
> 

Thanks,

**Comment by replikation** [comment]
@tamuanand
* my work around is only tested via google buckets, so i dont know how the absolut S3 bucket path looks like
* the idea is to give a input file with all the absolut paths at once without wildcards
* for this example: ``nextflow run main.nf --fasta input.csv``
* the input via (`params.fasta`) looks like this:
````bash
input_ch = Channel
        .fromPath( params.fasta, checkIfExists: true )
        .splitCsv()
        .map { row -> ["${row[0]}", file("${row[1]}")] }
        .view() }
````
* the input `input.csv` looks like this (it has one sample per line):
* basically `[value,file-path-in-bucket]`
````
sample1,gs://path-to-file1
sample2,gs://path-to-file2
sample3,gs://path-to-file3
sample4,gs://path-to-file4
````

**Comment by tamuanand** [comment]
Thanks @replikation

**Comment by phiweger** [comment]
@tamuanand so you run into the same problem?

**Comment by tamuanand** [comment]
@phiweger Yes - I ran into the same problem.  The workaround suggested by @replikation  works well.

**Comment by rafaelscs** [comment]
Hi, I'm facing the same issue reported here. Although the solution provided by @replikation solves it, it's not practical to create a .csv in my case, in which I will have a pipeline running several times and with different files. Does anyone know what is causing this issue? 

In my case, the nextflow is also not recognizing glob patterns in my bucket. 

- For example, If I try to create a channel with `gs://bck_data/genomes_new/genome/data/GCF_000261505.1/GCF*fna`, I get the error `No files match pattern GCF*fna at path: /genomes_new/genome/data/GCF_000261505.1/`.

- But if I try `gs://bck_data/genomes_new/genome/data/GCF_000261505.1/GCF_000261505.1_05737_genomic.fna` it works just fine.

I saw the same behavior even when I try to pull files from public bucktes, like from rnaseq-nf. If I use `gs://rnaseq-nf/data/*/gut_{1,2}.fq` it gives me the same error and I'm not sure how to fix it.

Thanks,

**Comment by replikation** [comment]
@rafaelscs this is (i believe) somehow completely related to the admin rights of the bucket. but I could not pinpoint the issue of this. in most cases wildcards do work for me, in some cases, they won't. e.g. I think if nextflow is, for instance, staging the files from a local computer (so the service account uploads) the wildcard will work for the files in the staging dir of the bucket.

**Comment by rafaelscs** [comment]
@replikation, thank you very much for your help! I tried different rights configurations for the service account accessing the bucket, but I was unable to pinpoint the issue. I will try to automate the creation of the .csv file the way you suggested. Thanks!
