### ISSUE TITLE
Support for Kubernetes pod annotations

### ISSUE THREAD

**Issue by olifly** [nextflow-io/nextflow#1241]
## Usage scenario 

Alot of kubernetes tools like log scrapers, metric collectors and autoscalers use annotations on pods to decide how to handle specifics for that pod _(what kinda log format is being emited by the pod, if it is safe to evict a pod from a node that the autoscaler wan't to remove etc)._

See: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

Today nextflow has support for labels, but not annotations.

## Suggest implementation 

I've submitted a pull request that adds support for annotations in a very similar manner to the way nextflow support kubernetes labels: https://github.com/nextflow-io/nextflow/pull/1240

**Comment by pditommaso** [comment]
Thanks Ólafur, I'll review on my earliest convenience.
