### ISSUE TITLE
how to use bot 'each' and 'set' input qualifiers together?

### ISSUE THREAD

**Issue by rgiannico** [nextflow-io/nextflow#1246]
Hello, 
How can I use an 'each' input qualifier for a channel containing a key and some files like this? `[file1,[file1.bam,file1.bam.bai]] [file2,[file2.bam,file2.bam.bai]]` 

#### What I have
I have an input folder with some BAM files, and I have a channel producing some accessory files (for example BED files). Let's keep it simple with only one accessory bam file for the example: 
```nextflow
Channel
     .fromFilePairs("${params.dir}/*.bam*",size:-1) {file -> file.name.split(/.bam/)[0]}
     .tap { c_bamfiles }
     // looks like this:    [file1,[file1.bam,file1.bam.bai]] [file2,[file2.bam,file2.bam.bai]]
Channel
      .fromPath('/mypath/fileA.bed')
      .tap { c_bedfileA}
```

#### What I want 
I need to build a process where an instance runs for `file1.bam file1.bam.bai fileA.bed` and their bam key 'file1' ; than another process instance runs for `file2.bam file2.bam.bai fileA.bed` and their bam key 'file2'. 
I understand I need to use the 'each' input qualifier for the c_bamfiles channel like this: 
```nextflow
process test{
   input:
   each file(bamfiles) from c_bamfiles.map{it[1]}
   file bedfile from c_bedfileA
}
``` 
And this works because I cut the key out using map: `each file(bamfiles) from c_bamfiles.map{it[1]}` but what if I need the key and I don't want to cut it off? 

#### What I tried: 
Conceptually it would be something like this `each set val(bamname), file(bamfiles) from c_bamfiles` but it doesn't work, is there something else I can do?
I also tried this: `each ( set( val(bamname), file(bamfiles) ) ) from c_bamlist` but I get `ERROR ~ No such variable: bamname` on this line. 
I also tried this: `set( val(bamname), each (file(bamfiles) ) ) from c_bamlist` but I get `ERROR ~ No such variable: bamfiles` on this line. 

I believe there could be 2 uggly workaround:
- to drop the key (as I did in my 'what I want' code) and reparse the key from the bam name, but it's quite uggly, I hope there is a better way
- manipulating somehow all of the channels together into a single channel collecting each element needed for each iteration, but it could be quite confusing for an extarnal reader, expecially if I have many single channels (like the bed file) to be merged together with the bam files channel. 

Is there another smart solution I can't see right now? 
Or if not (and the only way are the 2 workaround) could it be a nice feature request?

**Comment by pditommaso** [comment]
No, `each` is not meant to be used in this manner. You should use [groupTuple](https://www.nextflow.io/docs/latest/operator.html#grouptuple) or [combine](https://www.nextflow.io/docs/latest/operator.html#combine) to achieve that.

**Comment by rgiannico** [comment]
Yes thanks, `combine` is the way. 
This is the full solution: 
```nextflow
Channel
     .fromFilePairs("${params.dir}/*.bam*",size:-1) {file -> file.name.split(/.bam/)[0]}
     .tap { c_bamfiles }
     // looks like this:    [file1,[file1.bam,file1.bam.bai]] [file2,[file2.bam,file2.bam.bai]]
Channel
      .fromPath('/mypath/fileA.bed')
      .tap { c_bedfileA}

c_bamfiles.combine(c_bedfileA).tap(c_list)
// c_list looks like this: [file1,[file1.bam,file1.bam.bai], fileA.bed] [file2,[file2.bam,file2.bam.bai], fileA.bed]

process test{
   input:
   set val(bamname), file(bamfiles) , file(bedfile)  from c_list
   script: 
   def bam=bamfiles.findAll{ it.toString() =~ /.bam$/ }.join('')
   """
   echo "bamfiles: ${bamfiles} "     # file1.bam file1.bam.bai 
   echo "bam: ${bam} "               # file1.bam
   echo "name: ${name} "             # file1
   echo "string: ${bedfile} "        # fileA.bed
   """
}
```

**Comment by kemin711** [comment]
Related question: The document used value type for each qualifier.  Can you apply each to a tuple, say, val(value1), file(somefile)?
