### ISSUE TITLE
logs, work folder 

### ISSUE THREAD

**Issue by alabrashJr** [nextflow-io/nextflow#1247]
I'm going to run my pipeline over more than 1M samples, I noticed that the work folder and the logs take up too much space. Is there a way or specific parameter to disable log and work folder generation.

Best Regards

**Comment by pditommaso** [comment]
Work folders creation it's a core feature. You cannot switch it off. What do you mean by *log*?

**Comment by alabrashJr** [comment]
when nextflow runs a .nextflow.log.[1-9] is created. those logs

**Comment by pditommaso** [comment]
It unusable that files are big. Anyhow if you really want to prevent the creation you can redirect it to /dev/null eg 

```
nextflow -log /dev/null run .. etc
```
