### ISSUE TITLE
Include doesn't resolve in nested workflows

### ISSUE THREAD

**Issue by JonathanCSmith** [nextflow-io/nextflow#1249]
### Expected behavior and actual behavior

An include statement within a workflow that has already been loaded via include should resolve (I think?).

### Steps to reproduce the problem

Create the following three files and run with "nextflow run outer.nf"

**outer.nf:**
```
#!/usr/bin/env nextflow

nextflow.preview.dsl=2

Channel.from(9, 10, 11).set{ numbers}

include 'middle'
middle(numbers)
```
**middle.nf:**
```
#!/usr/bin/env nextflow

workflow middle(numbers) {
    include 'inner'
    inner(numbers)
}
```
**inner.nf:**
```
#!/usr/bin/env nextflow

process innerProcess {
    input:
      val(number)

    """
    echo $number
    """
}

workflow inner(numbers) {
    innerProcess(numbers)
}
```
### Program output 

Unknown method `inner`

 -- Check script 'middle.nf' at line: 5 or see '.nextflow.log' file for more details

### Environment 

* Nextflow version: 19.07.0-edge
* Java version: 1.8.0_202-b08
* Operating system: linux (centos)

### Additional context

I am not sure if this is actually as intended as DSL2 is for good reason very undocumented, but I thought it worth bringing up.

**Comment by pditommaso** [comment]
Have you tried to put `include 'inner'` at the beginning of the middle script?

**Comment by JonathanCSmith** [comment]
Yes this works great. It was a little counter intuitive for me as I envisaged the outermost (i.e. default) workflow to have an undeclared but implicit 'workflow' wrapped around it - hence why I thought declaring an import within an explicit workflow declaration would work. Thanks for clearing this up - as long as its intended no need to fix.

**Comment by JonathanCSmith** [comment]
So this solution (having the includes declared outside of the middle workflow) worked fine for us for a while, but we now wish to propagate several params which are coming from the outermost workflow to the innermost workflow. Having the imports here implies that the params from the outermost workflow are not yet available.

Any ideas on this?

**Comment by tverbeiren** [comment]
@JonathanCSmith You could pass a second argument to (all) your workflow(s) containing the required parameters. You would want it to be a `Channel` as well, though. This can make parametrisation more dynamic, as I think that's what you're looking for.

The example above, but with a twist (and according to the DSL2 API in 19.11.0-edge):

`inner.nf`:

```
#!/usr/bin/env nextflow
nextflow.preview.dsl=2

process innerProcess {
    input:
    val(number)
    val(pars)

    """
    echo $number
    echo $pars
    """
}

workflow inner {
    take:
    numbers
    pars

    main:
    innerProcess(numbers, pars).view()
}
```

`middle.nf`:

```
#!/usr/bin/env nextflow
nextflow.preview.dsl=2
include './inner'

workflow middle {
    take:
    numbers
    parsChannel

    main:
    def new_parsChannel = parsChannel.map{ pars -> 
        if (pars.var1 == 9) { return pars + [ var3 : "test" ] }
        else { return pars }
    }
    inner(numbers, new_parsChannel)
}
```

`outer.nf`:

```
#!/usr/bin/env nextflow
nextflow.preview.dsl=2
include './middle'

Channel.from(9, 10, 11).set{numbers}
numbers.map{ [ var1 : it, var2 : it + 2] }.set{pars}

workflow {
    middle(numbers, pars)
}
```

The _output_ (due to the `view()` in `inner.nf`) would be something along these lines:

```
N E X T F L O W  ~  version 19.11.0-edge
Launching `outer.nf` [distracted_bhaskara] - revision: e77fe8ff05
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
executor >  local (3)
[5e/cee88f] process > middle:inner:innerProcess (1) [100%] 3 of 3 ✔
10
[var1:10, var2:12]

11
[var1:11, var2:13]

9
[var1:9, var2:11, var3:test]
```

**Comment by JonathanCSmith** [comment]
I will close this in favour of discussing in the other issue.
