### ISSUE TITLE
ERROR ~ Unknown EC2 instance type: t2.micro (region: cn-northwest-1)

### ISSUE THREAD

**Issue by lch14forever** [nextflow-io/nextflow#1251]
Hi,

I could not create a cluster using nextflow on AWS specifically in region "cn-northwest-1" (China Ningxia). I am using the following version of nextflow:

```
| ~> nextflow -version

      N E X T F L O W
      version 19.04.1 build 5072
      last modified 03-05-2019 12:29 UTC (20:29 HKST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io

| ~> java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
and here is what has been cached:

```
| ~> ls -la ~/.nextflow/aws/
total 671180
drwxrwxr-x 2 lichenhao lichenhao      4096 Jul 26 22:24 .
drwxrwxr-x 6 lichenhao lichenhao      4096 Jul 26 22:19 ..
-rw-rw-r-- 1 lichenhao lichenhao        21 Jul 26 22:24 ec2-instance-types-cn-northwest-1.bin
-rw-rw-r-- 1 lichenhao lichenhao 687268953 Jul 26 22:23 ec2-pricing.csv
```
I had no problem with this in a different region "ap-southeast-1".  Any suggestions on what the cause could be?

**Comment by pditommaso** [comment]
Can you delete the folder `~/.nextflow/aws/` and try it again?

**Comment by lch14forever** [comment]
It didn't help unfortunately.

```
Fetching EC2 prices (it can take a few seconds depending your internet connection) ..
WARN: Unknown instance type: c4.xlarge
WARN: Unknown instance type: r5.24xlarge
WARN: Unknown instance type: r5d.2xlarge
WARN: Unknown instance type: m4.large
WARN: Unknown instance type: m5d.8xlarge
WARN: Unknown instance type: m5a.large
...
```

**Comment by lch14forever** [comment]
It seems that the hash map `ec2-instance-types-cn-northwest-1.bin` was empty. May I know the mechanism or API (AWS SDK?) nextflow uses to fetch this information? I am in contact with the AWS architects to find out what could the issue be also.

Thanks!

**Comment by pditommaso** [comment]
It uses the AWS price API 

http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/price-changes.html

The parsing is managed by [this class](https://github.com/nextflow-io/nextflow/blob/b49e6d74dae782def6be2b087d06fdd8fa6b9291/modules/nextflow/src/main/groovy/nextflow/cloud/aws/AmazonPriceReader.groovy#L40).

**Comment by lch14forever** [comment]
I am not familiar with groovy, but I think the script is trying to read the CSV file to get a hashmap of the price. However, regions in China (China (Beijing) and China (Ningxia)) are not it the CSV file.

**Comment by pditommaso** [comment]
Yes, there are 

https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/cloud/aws/AmazonPriceReader.groovy#L81-L82

**Comment by lch14forever** [comment]
Sorry. I meant the regions in China were not in this CSV file (https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.csv)...

**Comment by pditommaso** [comment]
Oh, that sounds bad. There's little it could be done on NF side then.

**Comment by hy714335634** [comment]
@pditommaso @lch14forever
the endpoint is different between global and china, I find the endpoint is ```https://pricing.us-east-1.amazonaws.com```in [AmazonPriceReader](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/cloud/aws/AmazonPriceReader.groovy#L81-L82),but in china,such as BJS, we can not use https://pricing.cn-north-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json to get response,because the endpoint is ```https://pricing.cn-north-1.amazonaws.com.cn```, so https://pricing.cn-north-1.amazonaws.com.cn/offers/v1.0/aws/AmazonEC2/current/index.json will be work

reference：https://docs.amazonaws.cn/aws/latest/userguide/billing-and-payment.html

**Comment by pditommaso** [comment]
Oh, fascinating.. a pull request fixing this is welcome.

**Comment by lch14forever** [comment]
Created the PS #1323 . Not sure if it is the best way to fix this though.
