### ISSUE TITLE
K8sTaskhandler never sets it status to TaskStatus.RUNNING

### ISSUE THREAD

**Issue by olifly** [nextflow-io/nextflow#1255]
### Expected behavior and actual behavior

**Expected:** When a pod starts running a task the K8sTaskHandler should change the state to _RUNNING_.

**Actual:** The K8sTaskHandler checkIfRunning never sets the status to Running, but just returns true if the task is running.

This behaviour is not consistent with the behaviour of other task handlers and has the side effect of letting the TaskMonitor send process_started message to all observations each time it check task statuses until the tasks complete. 

### Steps to reproduce the problem

* Run a workflow with the k8s executor with weblog enabled to see all of the process_started messages sent for every task that is running each time the TaskMonitor check the status of the tasks (default poll time is 5 seconds for the k8s executor.

* Check the nextflow log when running a workflow with the k8s executor.  All of the tasks that are listed by _dumpPendingTasks_ have SUBMITTED status even though they are running.

### Environment 

* Nextflow version: 19.07.0
* Java version: Java 8
* Operating system: macOS

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Thanks for the patch.
