### ISSUE TITLE
Possibility to define local variable of the process inside nextflow.config

### ISSUE THREAD

**Issue by onuryukselen** [nextflow-io/nextflow#1258]
Hi,
I would like to have to possibility to define a local variable of the process inside nextflow.config. In the following example, I would overwrite localVariable of the foo process without 
changing localVariable of the bar process. This way, I would easily execute same processes with different parameters without defining the localVarible in the input section of the processes.

Suggested feature in nextflow.config:
```
process.params {
    withName:foo {
        localVariable= "-p 5"
    }
}
```

Example process in main.nf:
```
process foo {

    input:
    val sample_id from myinput 

    script:
    localVariable="-p 3"
    '''
    do something ${localVariable} ${sample_id}
    '''
}

process bar {

    input:
    val sample_id from myinput2 

    script:
    localVariable="-p 3"
    '''
    do something ${localVariable} ${sample_id}
    '''
}
```

**Comment by pditommaso** [comment]
You can do this using `params. localVariable`

**Comment by pditommaso** [comment]
What you can try is to create that paras as a map object

```
params.varx.foo = '-p 1'
params.varx.bar = '-p 2'
```

then get the value as 

```
    script:
    localVariable=params.varx[task.process] ?: 'default'
    '''
    do something ${localVariable} ${sample_id}
    '''
```

**Comment by onuryukselen** [comment]
Perfect. Thanks a lot for the explanation.
