### ISSUE TITLE
[SECURITY] The 'nextflow' script downloads jars without checking fingerprints

### ISSUE THREAD

**Issue by yurivict** [nextflow-io/nextflow#1260]
It is insecure to download binaries (or any files) and run them without checking fingerprints.

**Comment by pditommaso** [comment]
Can you propose a patch?

**Comment by yurivict** [comment]
> Can you propose a patch?

No, fingerprints should be generated and maintained by you.

It has to be installed through the package. But it isn't clear how to do this from the documentation.

**Comment by pditommaso** [comment]
Fingerprints are generate and managed by the maven plugin when uploading/downloading the jar. To which download are you exactly referring?
