### ISSUE TITLE
Reintroduction of `set` operator

### ISSUE THREAD

**Issue by robsyme** [nextflow-io/nextflow#1262]
## New feature

It has been idiomatic to use set/tap operators to set the name of output Channels. Quoting from the docs:

> ... (T)he `set` operator is more idiomatic in Nextflow scripting, since it can be used at the end of a chain of operator transformations, thus resulting in a more fluent and readable operation.

The 'chronological' feel introduced by naming pipes is particularly helpful as chained operators grow, increasing the distance the users has to back-track to remember where the data ends up after reading through the list of operations. 

The introduction of a pipe operator in DSL2 encourages users to set up even longer sets of processes than pre-pipe Nextflow, making tail-end pipe naming an even better proposition.

## Usage scenario 

Named pipes are not a problem when the final operation is a process, as the `Name.out` idiom can be used:

```groovy
BlastXCollected = Trinity.out \
| combine( MakeBlastDB.out ) \
| BlastX

BlastX.out \
| Newprocess \
| Bar

BlastX.out \
| Foo
| Foo2
```

We run into difficulty, however, when the final process is an operator. In these circumstances, the user is forced back into naming the output before the pipeline:

```groovy
BlastXCollected = Trinity.out \
| splitFasta( by: 5000, file: true ) \
| combine( MakeBlastDB.out ) \
| BlastX \
| collectFile() { dbname, file -> [ "${dbname}.txt", file.text ] }
```

## Suggest implementation 

I'd suggest reintroducing `set` to enable something like:

```groovy
Trinity.out \
| splitFasta( by: 5000, file: true ) \
| combine( MakeBlastDB.out ) \
| BlastX \
| collectFile() { dbname, file -> [ "${dbname}.txt", file.text ] } \
| set { BlastXCollected }
```

**Comment by pditommaso** [comment]
We have it! use `NXF_VER=19.08.0-SNAPSHOT`.
