### ISSUE TITLE
Can't assume IAM role when launching nextflow job from a container running on ECS

### ISSUE THREAD

**Issue by kdi-insitro** [nextflow-io/nextflow#1264]
### Expected behavior and actual behavior

I am trying to start nextflow jobs that run on AWS batch from inside a container. When nextflow is launched from a container running on ECS it can't assume the IAM task role from the container, which is required for S3 and batch communication. This is likely because in a container the credentials metadata is stored at `http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` not at the EC2 ip address `169.254.169.254`. 

### Steps to reproduce the problem

Following this guide but using ECS in place of batch to launch the jobs: https://docs.opendata.aws/genomics-workflows/orchestration/nextflow/nextflow-overview/

### Program output 

`Missing AWS security credentials -- Provide access/security keys pair or define a IAM instance profile (suggested)`

Nextflow runs successfully if keys are provided, but this is not ideal to have security keys hardcoded into the container. We would much prefer to use IAM roles. The container can submit batch jobs outside of nextflow using the awscli, so the IAM permissions are correct for the container, nextflow just can't find them. 

### Environment 

* Nextflow version: 19.07.0 
* Java version: openjdk version "1.8.0_201"
* Operating system: amazon linux 2

**Comment by pditommaso** [comment]
That's not documentation maintained by the project. Please report in the respective repository. https://github.com/aws-samples/aws-genomics-workflows

**Comment by kdi-insitro** [comment]
Hi @pditommaso, thanks for your quick reply. This isn't an issue with the aws documentation, this has to do with how nextflow determines its IAM role. In the AmazonCloudDriver code function `fetchIamRole()`, it looks like the role is determined from `getUrl('http://169.254.169.254/latest/meta-data/iam/security-credentials/').readLines()` which has the EC2 ip address hardcoded in. This doesn't work when nextflow is running from inside a container because the metadata location in containers running in ECS is located in a variable at the ip: `http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`. Would it be possible to update the code to look in both places before failing?

**Comment by pditommaso** [comment]
Thanks for clarifying. I would consider a PR patching this problem.

**Comment by dekinsitro** [comment]
Hi,
I've written a provisional patch for this and functionally it seems to work.  It uses the environment variable provided by ECS to fetch from http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI.
when that variable is defined.

I want to add a test to AmazonCloudDriverTest, but it looks like I would need to update the test process environment with that variable.  I don't know Groovy particularly well, so I need a bit of advice:

1) One way to test this would be to temporarily modify the environment variable (I have examples of Java code which use reflection to modify the in-process environment), run the test, then restore the variable.  However, my attempt to do this fails:
        def env = System.getenv()
        def field = env.metaClass.m
        field.setAccessible(true)
        field.get(env).put("AWS_CONTAINER_CREDENTIALS_RELATIVE_URI", "/foobar")
        def result = driver.fetchIamRole()
        field.get(env).delete()

because field is null, not an actual field.  

2) I guess I could make "in_ecs" some sort of constructor argument and arrange for instrances of AmazonCloudDriver to have that value passed in based on the env var.  Then the test would just inject "in_ecs=True" for the test.

**Comment by dekinsitro** [comment]
@pditommaso Paolo, we've got a patch we thinks works and are just stuck on the testing issue.  Can you look at my comment above about how to test code that needs an environment variable set?  I'm basically trying to implement this Java idiom in Groovy:
https://stackoverflow.com/questions/318239/how-do-i-set-environment-variables-from-java
but it crashes at runtime when I attempt to fetch the field 'm'.

**Comment by dekinsitro** [comment]
@pditommaso @kdi-insitro I've uploaded my patch https://github.com/nextflow-io/nextflow/pull/1296 which still lacks a good test to verify that it works (see my previous comment).
@kdi-insitro will take over upstreaming this patch as I am transitioning off this project.

**Comment by pditommaso** [comment]
Sorry for the late reply. The system env is supposed to be a read-only map, then trying to alter it using reflection is not a good idea. 

The best way to handle this test is to add in the class an `env` attribute initialised to the `System.getenv()`, then in the test you inject a map mimic the configuration you want to test. 

Have a look here for example 

https://github.com/nextflow-io/nextflow/blob/b49e6d74dae782def6be2b087d06fdd8fa6b9291/modules/nextflow/src/test/groovy/nextflow/mail/MailerTest.groovy#L281-L308
