### ISSUE TITLE
Combine operation incorrectly represented in DAG

### ISSUE THREAD

**Issue by rsuchecki** [nextflow-io/nextflow#1268]
## Bug report 

Combine operation in the rendered DAG is incorrectly disconnected since version `19.05.0-edge` up to and including latest release (`19.07.0`).

#### Expected (and actual  `<= 19.04.1`)
![dag1_19 04 1](https://user-images.githubusercontent.com/5534231/62749610-2df1da00-ba9c-11e9-9a14-c8f4537a3ba6.png)

#### Actual (`>= 19.05.0-edge`)
![dag1_19 05 0-edge](https://user-images.githubusercontent.com/5534231/62749628-3ea25000-ba9c-11e9-9b35-2db3f5a0397e.png)

### Steps to reproduce the problem

Run the following with appropriate `NXF_VER`

```nextflow
Channel.from('foo').set{ chn1 }
Channel.from('bar').set{ chn2 }
chn1.combine(chn2)
```

### Additional info

```dot
digraph "dag1_19041" {
p0 [shape=point,label="",fixedsize=true,width=0.1,xlabel="Channel.from"];
p2 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="combine"];
p0 -> p2 [label="chn1"];

p1 [shape=point,label="",fixedsize=true,width=0.1,xlabel="Channel.from"];
p2 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="combine"];
p1 -> p2 [label="chn2"];

p2 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="combine"];
p3 [shape=point];
p2 -> p3;

}
```

```dot
digraph "dag1_19050edge" {
p0 [shape=point,label="",fixedsize=true,width=0.1,xlabel="Channel.from"];
p3 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="combine"];
p0 -> p3 [label="chn1"];

p1 [shape=point,label="",fixedsize=true,width=0.1,xlabel="Channel.from"];
p2 [shape=point];
p1 -> p2 [label="chn2"];

p3 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="combine"];
p4 [shape=point];
p3 -> p4;

}
```

**Comment by pditommaso** [comment]
Thanks for reporting this issue!

**Comment by rsuchecki** [comment]
That was quick! Thanks @pditommaso!

🥇

**Comment by replikation** [comment]
i have the same issue but with `.join` in nextflow  v19.10.0 

```
Channel.from('foo').set{ chn1 }
Channel.from('bar').set{ chn2 }
chn1.join(chn2)
```

**Comment by pditommaso** [comment]
@replikation please report as a new issue.
