### ISSUE TITLE
Mixed content errors if timeline.html served over HTTPS

### ISSUE THREAD

**Issue by dctrud** [nextflow-io/nextflow#127]
Hi,

We are using nextflow within a workflow platform that has a web interface with access over https. The platform serves up the nextflow timeline.html so users can look at the timeline of their jobs.

At present this won't work as the resources timeline.html is brining in from the web are being pulled over http:

```html
<head>
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script src="http://www.nextflow.io/js/d3-timeline.js"></script>
```
If the page itself is accessed over https then browsers refuse to load the resources over http, e.g. from chrome:

```
Mixed Content: The page at 'https://xxx.xxx.xxx.xxx/workflow/api/run/8/timeline_html' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery-latest.min.js'. This request has been blocked; the content must be served over HTTPS.
````
Could nextflow switch to using https for the external resources pulled in by timeline.html, to avoid mixed content errors?

**Comment by pditommaso** [comment]
I see. I think this could be fixed with some javascript hacking in the [timeline html template](https://github.com/nextflow-io/nextflow/blob/master/src/main/resources/nextflow/trace/TimelineTemplate.html#L24-L27).

Would you like to propose a fix and submit a pull request for that?

**Comment by dctrud** [comment]
I can do a PR with JS to mangle things, but thinking about it, the JS approach is unnecessary. If the URLs are all made https then it'll be fine regardless of if the page is served over http or https.

The jquery and d3js.org urls work just replacing http with https. However, www.nextflow.io isn't answering https:

https://www.nextflow.io/js/d3-timeline.js

Regardless of whether using JS to rewrite http->https, or just changing all to https d3-timeline.js will have to be hosted somewhere that supports https access.

**Comment by dctrud** [comment]
Erk  - just saw it's an s3 website. See link below talking about same mixed content issue:

http://knightlab.northwestern.edu/2015/05/21/implementing-ssl-on-amazon-s3-static-websites/

**Comment by pditommaso** [comment]
You are definitely right. Time to get a SSL certificate for nextflow.io web site --> https://letsencrypt.org

(thanks for the S3 configuration tutorial)

**Comment by pditommaso** [comment]
To make it faster, instead of configuring a SSL certificate for nextflow.io, I'm serving the script file from Github. However just switching to `https` brokens the report when opening the html offline. 

I'm using the following javascript snippet, could you please verify that it works for you as well, replacing it in a timeline that you already have? 

    <script type="text/javascript">
    var prot = (("https:" == document.location.protocol) ? "https://" : "http://");
    document.write(unescape("%3Cscript src='" + prot + "code.jquery.com/jquery-latest.min.js' type='text/javascript' %3E%3C/script%3E"));
    document.write(unescape("%3Cscript src='" + prot + "d3js.org/d3.v3.min.js' charset='utf-8' type='text/javascript' %3E%3C/script%3E"));
    document.write(unescape("%3Cscript src='" + prot + "cdn.rawgit.com/nextflow-io/d3-timeline/master/src/d3-timeline.js' type='text/javascript' %3E%3C/script%3E"));
    document.write(unescape("%3Clink href='" + prot + "' rel='stylesheet' type='text/css' %3E%3C/link%3E"));
    </script>

**Comment by dctrud** [comment]
Sorry I didn't get back to you on this earlier - hectic day. That does indeed fix the issue.

Many Thanks!

**Comment by pditommaso** [comment]
No pb. Thanks for your feedback.
