### ISSUE TITLE
GA4GH Workflow Execution Service (WES) API

### ISSUE THREAD

**Issue by fkaercher** [nextflow-io/nextflow#1272]
Support for the [ GA4GH Workflow Execution Service API](https://github.com/ga4gh/workflow-execution-service-schemas).
This new feature would allow to execute workflows by a standardized API.

In #866, there was already a discussion about it and maybe it is already planned. However, it would be good to have a separate issue for it.

**Comment by pditommaso** [comment]
We are looking for an org/person willing to contribute this.

**Comment by pditommaso** [comment]
Moving this to NF Tower https://github.com/seqeralabs/nf-tower/issues/179.

**Comment by marcadella** [comment]
> Moving this to NF Tower [seqeralabs/nf-tower#179](https://github.com/seqeralabs/nf-tower/issues/179).

Doesn't seem to be any activity there. Is anyone working on this issue?
