### ISSUE TITLE
[Request] Publish the Nextflow GroovyDoc

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#1274]
Hi Nextflow team,

I'm experimenting with embedding nextflow in a java application and I tried finding the API documentation ( rather then ther user documentation) for the project. I have searched on the main website and tried other resources but I can't find it. Please also consider publishing the API doc for this wonderful tool, Nextflow.

**Comment by pditommaso** [comment]
The Java doc is not published because the internal data structures are not supposed to be a public api. If you still want to access it, you can create by your self cloning the project and using the following command: 

```
./gradlew groovydoc 
```

**Comment by abhi18av** [comment]
Yup, it worked perfectly. Thanks for the pointer @pditommaso 👍 

Closing this issue now.
