### ISSUE TITLE
Specify sub-params on the command line using '.' delimiter

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1279]
## New feature

You can specify params on the command line, but it seems like you can only specify "first-level" params. Sub-params (and sub-sub-params) are not recognized.

## Usage Scenario

```
# given this param config
params {
  foo {
    a = true
    b = true
  }

  bar {
    a = true
    b = true
  }
}

# I should be able to do this
nextflow run main.nf --foo.a true --bar.b false

# (alternative)
nextflow run main.nf --foo-a true --bar-b false
```

## Suggest Implementation

Nextflow should be able to simply split the command-line param by a delimiter such as "." or "-" and index into the params object accordingly.

**Comment by pditommaso** [comment]
Duplicate of #1182

**Comment by bentsherman** [comment]
Whoops. I'll move to the other thread.
