### ISSUE TITLE
K8S - volumeClaim pod directive/config creates multiple volumes for a single pvc

### ISSUE THREAD

**Issue by olifly** [nextflow-io/nextflow#1283]
**Expected behaviour:** 

Multiple *volumeClaim* pod directives/config for the same pvc, but mounted at different paths and/or have different subpaths should create 1 volumeMount per directive, but only only 1 volume per pvc name.

Given the following volumeClaim directives:

```
[volumeClaim: 'first', mountPath: '/work']
[volumeClaim: 'first', mountPath: '/work2', subPath: '/bar']
[volumeClaim: 'second', mountPath: '/data', subPath: '/foo']
[volumeClaim: 'second', mountPath: '/data2', subPath: '/fooz']
``` 

should result in the following pod mounts:

```
volumeMounts:[
    [name:'vol-1', mountPath:'/work'],
    [name:'vol-1', mountPath:'/work2', subPath: '/bar'],
    [name:'vol-2', mountPath:'/data', subPath: '/foo'],
    [name:'vol-2', mountPath:'/data2', subPath: '/fooz']
]
```

and the following volumes:

```
volumes:[
    [name:'vol-1', persistentVolumeClaim:[claimName:'first']],
    [name:'vol-2', persistentVolumeClaim:[claimName:'second']] ]
```

**Actual behaviour:**

The behaviour as it is today results in the following volumeMounts and volumes:

```
volumeMounts:[
    [name:'vol-1', mountPath:'/work'],
    [name:'vol-2', mountPath:'/work2', subPath: '/bar'],
    [name:'vol-3', mountPath:'/data', subPath: '/foo'],
    [name:'vol-4', mountPath:'/data2', subPath: '/fooz']
]
```
```
volumes:[
    [name:'vol-1', persistentVolumeClaim:[claimName:'first']],
    [name:'vol-2', persistentVolumeClaim:[claimName:'first']],
    [name:'vol-3', persistentVolumeClaim:[claimName:'second']],
    [name:'vol-4', persistentVolumeClaim:[claimName:'second']] ]
```

*Having multiple volumes for the same pvc results in the pod not being scheduled.*

### Steps to reproduce the problem

Run a workflow using the k8s executor that has processes configured to use the same volumeClaim at different paths and/or subpaths.

### Environment 

* Nextflow version: 19.07.0
* Java version: 1.8
* Operating system: macOS Mojave

**Comment by pditommaso** [comment]
Solved by #1284
