### ISSUE TITLE
Allow other files besides main.nf to be run from repository invocation

### ISSUE THREAD

**Issue by micans** [nextflow-io/nextflow#1286]
## New feature

Introduce a Nextflow invocation mode that allows e.g.

```
nextflow run someaccount/shinyrepo -entry runfoo
```

where `runfoo.nf` is a file in the repository, similar to `main.nf`.

## Usage scenario 

This feature will allow related workflows to be shipped in a single repository, to be modularised using sub-workflows, and invoked directly from a source repository.

**Comment by bentsherman** [comment]
You can already do this, it's just not documented:
```
nextflow run someaccount/shinyrepo/runfoo.nf
```

**Comment by micans** [comment]
@bentsherman thanks! I seem to remember this was not possible a while back, but anyway, perhaps it was and it certainly is now.
