### ISSUE TITLE
Nextflow process with SSH remote login

### ISSUE THREAD

**Issue by ssamberkar** [nextflow-io/nextflow#1287]
Hi,

I'm trying to execute a process in a Nextflow pipeline with a process that logs onto a remote server, copies some files and deploys a docker image for a webapp. I'm not sure if something like this can be achieved through Nextflow but I don't see any reason for a limitation. My code looked something like this:

`
process DeployOXL {
	
	"""
	ssh user@remote-server
	scp user@remote-server2:/remote/path/to/the/graph/file/test_nf.oxl /local/path/to/the/graph/file/network.oxl
	

	docker run -it --detach -p 8083:8083 --name nf-test --memory 20G --volume /local/path/to/the/some_data_folder/:/root/knet-dataset knet/knetminer:review test
	"""

}
`

Do I have incorrect syntax or am I missing something?

Best,
Sandeep

**Comment by pditommaso** [comment]
Sorry, this space if for NF development and related issues.
