### ISSUE TITLE
Ansi log flickers when variable-length tags are used

### ISSUE THREAD

**Issue by wjv** [nextflow-io/nextflow#1288]
### Expected behavior and actual behavior

Presumably due to the enhancement in #1144, command-line output is now quite unstable when tags of variable length are used.

It seems that column widths are recalculated on each refresh. Since the tag is in a middle column, the rest of the columns continually “jump” left and right if the tags are of varying lengths.

This is best illustrated with a short video:

![out](https://user-images.githubusercontent.com/295282/63588797-ac27a380-c5a7-11e9-9d81-11a827fd049d.gif)

### Environment 

```
  Version: 19.07.0 build 5106
  Created: 27-07-2019 13:22 UTC (15:22 CEST)
  System: Linux 4.4.0-112-generic
  Runtime: Groovy 2.5.6 on OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
  Encoding: UTF-8 (UTF-8)
```

**Comment by pditommaso** [comment]
Test case 

```
process foo {
    maxForks 1
    tag { 'x' * new Random().nextInt(20) }
    input: 
    val x from 1..10
    /sleep 0.1/
}
```
