### ISSUE TITLE
Allow parameter array of values when the same CLI opt is repeted

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#129]
Currently script command line parameters do not allow list of value. The semantic of the CLI option mechanism can be extend in such a way that when the same CLI option it repeated more than on time the values are collected to an array. For example: 

```
nextflow run <script> --alpha 2 --alpha 1 --alpha 3 
```

The `alpha` parameter should hold the value `[2,1,3]`

**Comment by senkin** [comment]
Hello @pditommaso , I'm wondering if this has ever been implemented (perhaps in DSL2) or planned to? Essentially `nextflow run <script> --alpha [2,1,3]` would be perfect.

**Comment by mgratigny** [comment]
Hello everybody,
Any news about this potential feature ?

**Comment by qscacheri** [comment]
Bump

**Comment by abhi18av** [comment]
Perhaps the `-params-file yaml/json_file`  might be a better solution for providing complex arguments and all the while, capturing the args provided for a run.

**Comment by qscacheri** [comment]
Oh awesome, didn't realize the -params-file would work for this. Thanks!
