### ISSUE TITLE
Process named output channels

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#1290]
The goal of this enhancement is to implement the ability to associate a custom name to each output channel declared in the process definition.

For example: 

```
process foo {
  output:
    set val(sample_name), file('*_trimmed.fastq'), emit: named_fastq
    set val('trimmed'), file('*_trimmed.fastq'), emit: flagged_fastq
    file '*.log', emit: logs
  """
  command_here
  """
}
```

Using the above syntax the `emit:` option allows the association of a name that can be used to reference the channel output once the process has been invoked. For example: 

```
workflow {
  foo()
  foo.out.named_fastq.view()
  foo.out.flagged_fastq.view()
}
```

This is similar to the request made by #1181, however, the use of `as` is discouraged because is a groovy lang keyword. Moreover the use of `emit:` is consistent with the new workflow output syntax definition  #1276.

**Comment by mes5k** [comment]
This could be really nice!

I was thinking of a related feature, which is just the ability to destructure the output list, something like:
```
workflow {
  named_fastq, flagged_fastq = foo()
}
```

**Comment by pditommaso** [comment]
You can. `foo.out` implements a `List` therefore you can assign it as 

```
workflow {
 foo()
 (named_fastq, flagged_fastq) = foo.out
}
```

**Comment by mes5k** [comment]
Oh perfect!  I think I just had a bug in my test script that was leading me astray.

**Comment by pditommaso** [comment]
Use `19.08.1-edge` for testing.
