### ISSUE TITLE
google-genomics does not support docker images with ENTRYPOINT

### ISSUE THREAD

**Issue by huguesfontenelle** [nextflow-io/nextflow#1291]
### Expected behavior and actual behavior

Whenever I use a Docker image with an ENTRYPOINT, it fails.
The exact error message varies depending on the Docker image used.

### Steps to reproduce the problem

I tried a Minimally Reproducible Bug repo at https://github.com/huguesfontenelle/nextflow-gcp-entrypoint
The[ README.md](https://github.com/huguesfontenelle/nextflow-gcp-entrypoint/blob/master/README.md) shows the commands for running the pipeline
- locally using ubuntu image. SUCCESS obviously
- locally using ubuntu with an ENTRYPOINT (recipe in [Dockerfile](https://github.com/huguesfontenelle/nextflow-gcp-entrypoint/blob/master/Dockerfile)). SUCCESS, Nextflow properly overrides. 
- on google-genomics using ubuntu image. SUCCESS
- on google-genomics using ubuntu with an ENTRYPOINT. **FAIL**

### Program output 

[.nextflow.log](https://github.com/huguesfontenelle/nextflow-gcp-entrypoint/blob/master/.nextflow.log) file.
(It seems to be that the error message is misleading)

### Environment 

* Nextflow version: 2019.07.0
* Java version: 11
* Operating system: macOS, google-genomics

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
This feature was implemented in the new `google-lifesciences` executor.
