### ISSUE TITLE
Google Genomics Pipelines API - Shutdown on error

### ISSUE THREAD

**Issue by mozack** [nextflow-io/nextflow#1293]
### Expected behavior and actual behavior

I am seeing some cases where Nextflow shuts down on back end errors when using the Google Pipelines API.  Attached are 3 distinct cases from the same run where Nextflow shutdown I believe unnecessarily.  After each error, I reran Nextflow using the -resume option.

1) Transient error on docker pull. 
```
Execution failed: pulling image: docker pull: running ["docker" "pull" "google/cloud-sdk:alpine"]: exit status 1 (standard error: "filesystem layer verification failed for digest sha256:7713a967496cab34cdaeb5dc2ca0b913ecf15ae336c8ad54a7c95ab04d7b3ed6\n")
```

See neosplice.log.1.dockerpullfailure and nextflow.log.1.dockerpullerror

2) Backend Error (410 / 503 Error)

```
Caused by:
  410 Gone
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 503,
  "message": "Backend Error"
 }neosplice.log.1.dockerpullfailure
}
```
See neosplice.log.2.410goneerror and nextflow.log.2.410goneerror

3) Program failure (should be retried and then ignored)
In this case a program is crashing.  The expectation here is that it would be retried and eventually ignored as we have the following errorStrategy in the workflow:

```
errorStrategy { task.attempt < 5 ? 'retry' : 'ignore' }
maxRetries 6
```

See neosplice.log.3.failure_no_ignore and nextflow.log.3.failure_no_ignore

### Program output 

Please see attached log files.

### Environment 

* Nextflow version: 19.07.0-edge
* Java version: 1.8.0_144
* Operating system: Linux

### Additional context

Failures 1 and 2 appear to have been transient errors.  I was able to resume and those errors did not reappear.  It would be nice to not shutdown in these cases.

Failure 3 was persistent.  However, the expectation is that it would retry and then eventually the error would be ignored.  I have seen this work for another consistently failing job in the same workflow.

Please see logs, workflow and config file attached.

[nextflow_logs.tar.gz](https://github.com/nextflow-io/nextflow/files/3556843/nextflow_logs.tar.gz)
[stdout_logs.tar.gz](https://github.com/nextflow-io/nextflow/files/3556844/stdout_logs.tar.gz)
[workflow.tar.gz](https://github.com/nextflow-io/nextflow/files/3556845/workflow.tar.gz)

**Comment by pditommaso** [comment]
Copy the failure for case 3 here for future reference 

```
Aug-16 10:54:51.960 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'tumor_specific_kmers (tumor_specific_kmers_TCGA-22-4593)'

Caused by:
  410 Gone
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 503,
  "message": "Backend Error"
 }
}


com.google.cloud.storage.StorageException: 410 Gone
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 503,
  "message": "Backend Error"
 }
}

	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:704)
	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:47)
	at com.google.cloud.BaseWriteChannel.close(BaseWriteChannel.java:161)
	at com.google.cloud.storage.contrib.nio.CloudStorageWriteChannel.close(CloudStorageWriteChannel.java:57)
	at java.nio.channels.Channels$1.close(Channels.java:178)
	at java.nio.file.Files.write(Files.java:3300)
	at nextflow.executor.BashWrapperBuilder.build(BashWrapperBuilder.groovy:283)
	at nextflow.executor.BashWrapperBuilder$build.call(Unknown Source)
	at nextflow.cloud.google.pipelines.GooglePipelinesTaskHandler.createTaskWrapper(GooglePipelinesTaskHandler.groovy:291)
	at nextflow.cloud.google.pipelines.GooglePipelinesTaskHandler.submit(GooglePipelinesTaskHandler.groovy:265)
	at nextflow.processor.TaskPollingMonitor.submit(TaskPollingMonitor.groovy:195)
	at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:557)
	at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:385)
```

**Comment by pditommaso** [comment]
Actually several tasks are re-executed many times. 

```
Aug-16 22:39:25.557 [Task monitor] INFO  nextflow.processor.TaskProcessor - [7e/6920e2] NOTE: Process `tumor_specific_kmers (tumor_specific_kmers_TCGA-22-5482)` terminated with an error exit status (14) -- Execution is retried (1)
Aug-16 23:09:32.030 [Task monitor] INFO  nextflow.processor.TaskProcessor - [88/fb36f1] NOTE: Process `tumor_specific_kmers (tumor_specific_kmers_TCGA-B0-5709)` terminated with an error exit status (14) -- Execution is retried (1)
Aug-17 00:07:26.679 [Task monitor] INFO  nextflow.processor.TaskProcessor - [a2/508d43] NOTE: Process `tumor_specific_kmers (tumor_specific_kmers_TCGA-KN-8428)` terminated with an error exit status (1) -- Execution is retried (1)
Aug-17 00:38:13.392 [Task monitor] INFO  nextflow.processor.TaskProcessor - [97/383524] NOTE: Process `tumor_specific_kmers (tumor_specific_kmers_TCGA-KN-8428)` terminated with an error exit status (14) -- Execution is retried (2)
Aug-17 01:35:49.161 [Task monitor] INFO  nextflow.processor.TaskProcessor - [a6/e83d43] NOTE: Process `tumor_specific_kmers (tumor_specific_kmers_TCGA-IN-8663)` terminated with an error exit status (14) -- Execution is retried (1)
Aug-17 04:37:42.266 [Task monitor] INFO  nextflow.processor.TaskProcessor - [c3/9f8f02] NOTE: Process `tumor_specific_kmers (tumor_specific_kmers_TCGA-IN-8663)` terminated with an error exit status (14) -- Execution is retried (2)
```
It's not clear why that is causing the program to stop on case 3. Are you sure you are not setting `maxErrors` other than `maxRetries`  ?

**Comment by mozack** [comment]
No, maxErrors is not set. I've attached the workflow and config file here.

[neo_splice.nf.gz](https://github.com/nextflow-io/nextflow/files/3595862/neo_splice.nf.gz)
[nextflow.config.gz](https://github.com/nextflow-io/nextflow/files/3595864/nextflow.config.gz)

Yes, the behavior seems inconsistent.  I've seen some jobs fail several times and then be ignored as expected.

Also, I've not seen the problem on exit code 14, which I believe may be due to preempts and is by far the most frequent failure mode.  It looks like there is some special logic around this case here:

https://github.com/nextflow-io/nextflow/blob/5bc323a05eb392a87563a8a0c216fbf935751ff9/modules/nf-google/src/main/nextflow/cloud/google/pipelines/GooglePipelinesTaskHandler.groovy#L219

**Comment by pditommaso** [comment]
I was checking the reason for the `StorageException` reported above. That is caused when NF tries to create the job launcher script in the target bucket. 

I was thinking to add a re-try strategy on it, however, I've noticed that the GS library is already implementing a retry for that error. 

```java
 public final class StorageException extends BaseHttpServiceException {

  // see: https://cloud.google.com/storage/docs/resumable-uploads-xml#practices
  private static final Set<Error> RETRYABLE_ERRORS =
      ImmutableSet.of(
          new Error(504, null),
          new Error(503, null),
          new Error(502, null),
          new Error(500, null),
          new Error(429, null),
          new Error(408, null),
          new Error(null, "internalError"));

  private static final long serialVersionUID = -4168430271327813063L;

  public StorageException(int code, String message) {
    this(code, message, null);
  }

  public StorageException(int code, String message, Throwable cause) {
    super(code, message, null, true, RETRYABLE_ERRORS, cause);
  }

  public StorageException(IOException exception) {
    super(exception, true, RETRYABLE_ERRORS);
  }

  public StorageException(GoogleJsonError error) {
    super(error, true, RETRYABLE_ERRORS);
  }

  /**
   * Translate RetryHelperException to the StorageException that caused the error. This method will
   * always throw an exception.
   *
   * @throws StorageException when {@code ex} was caused by a {@code StorageException}
   */
  public static StorageException translateAndThrow(RetryHelperException ex) {
    BaseServiceException.translate(ex);
    throw new StorageException(UNKNOWN_CODE, ex.getMessage(), ex.getCause());
  }
}
```

Therefore not sure if it makes sense. @kemp-google @moschetti Any suggestion?

**Comment by kemp-google** [comment]
I'm not familiar with the Java libraries for Cloud Storage, but assuming this snippet is from those libraries, yes I agree it likely doesn't make sense for you to retry on top of it.

**Comment by pditommaso** [comment]
Therefore, we must conclude that this error was expected. The problem at point 2 was due by invalid handling of the preemptive termination.
