### ISSUE TITLE
Calling 'error' or 'exit' in a script doesn't trigger onFlowComplete in Observers

### ISSUE THREAD

**Issue by olifly** [nextflow-io/nextflow#1294]
This issue is really bad for WebLogObserver since it relies on OnFlowComplete being called to ensure it sends all queued http messages.

**Expected:** 
Calling _abort_ or _exit_ from a script should trigger onFlowComplete in observers. 

**Actual:** _abort_ and _exit_ go down a codepath in nextflow that doesn't end with triggering onFlowComplete.  

*  _error:_  This triggers onFlowError (though not detailing the error in the message) but not onFlowComplete. 

* _exit:_ This does not trigger onFlowError if errorcode > 0 (which I would think is the expected behaviour) and not onFlowComplete.

### Steps to reproduce the problem

* Create a request bin bucket (use https://requestbin.com for example)
* Run the scripts at the end of this issue:
  * _error.nf:_ You should _(hopefully)_ get an onFlowStarted event, _(hopefully)_ and onFlowError event, but no onFlowComplete.
  * _exit_0.nf:_ You should _(hopefully)_ get an onFlowStarted event, but no onFlowComplete.
  * _exit_1.nf:_ You should _(hopefully)_ get an onFlowStarted event, but no onFlowComplete. Furthermore you could argue that you should also get an OnFlowError event since a non-zero exit code usually signals an error.

### Environment 

* Nextflow version: 19.08.1-edge
* Java version: 1.8.0
* Operating system: MacOS.

#### error.nf
```
/* We need to sleep here a little to get at least the onFlowStart event.  
 * Remove the sleep and you will probably get no events.
 */
sleep(5000) 

/* We might not get the onFlowError since nextflow doesn't wait for WeblogObserver to finish sending
 * all queued up message before exiting.  That happens in onFlowComplete (which is not called when 
 * a script aborts because of 'error' keyword)
 */
error  "Terminal error" 
```
#### exit_0.nf
```
/* We need to sleep here a little to get at least the onFlowStart event.  
 * Remove the sleep and you will probably get no events.
 */
sleep(5000) 

/* OnFlowComplete is not called when using the 'exit' keyword.
 */
exit 0, "Normal termination"
```
#### exit_1.nf
```
/* We need to sleep here a little to get at least the onFlowStart event.  
 * Remove the sleep and you will probably get no events.
 */
sleep(5000) 

/* OnFlowComplete is not called when using the 'exit' keyword. Furthermore perhaps onFlowError
 * should be called when the exit code is not 0 (which usually indicated an error).
 */
exit 1, "Abnormal termination"
```

**Comment by pditommaso** [comment]
Duplicate of #1352 (?)
