### ISSUE TITLE
Permission error when running process inside Docker with a custom user

### ISSUE THREAD

**Issue by haqle314** [nextflow-io/nextflow#1295]
## Bug report 

Possible permission issue when UID of host user doesnt match UID of user inside Docker.

Some container such as `biocontainers/samtools` specify a custom user instead of
`root`. Since `nextflow` doesn't do anything special for the working directory,
the working directory and its children have the current user in host's UID/GID.
If this custom user has a different UID then it doesn't have write permission in
the working directory.

You can see the mismatch IDs from output of `id` and `ls -la`.

### Steps to reproduce the problem

```nextflow
// main.nf
nextflow.preview.dsl = 2

process doFoo {
    echo true
    container 'biocontainers/samtools'
    output: file "foo"
    shell:
    '''
    id
    ls -la
    echo "Hello World!" > foo
    '''
}
doFoo | view { it.text }
```

### Program output 

```
N E X T F L O W  ~  version 19.07.0
Launching `main.nf` [adoring_einstein] - revision: 29fdc52d17
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
executor >  local (1)
[f4/7f9e73] process > doFoo [100%] 1 of 1, failed: 1 ✘
Error executing process > 'doFoo'

Caused by:
  Process `doFoo` terminated with an error exit status (1)

Command executed:

  id
  ls -la
  echo "Hello World!" >> foo

Command exit status:
  1

Command output:
  uid=1000(biodocker) gid=1001(biodocker) groups=1001(biodocker),27(sudo),1000(fuse)
  total 24
  drwxrwxr-x 2 1004 1005 4096 Sep  3 20:16 .
  drwxr-xr-x 3 root root 4096 Sep  3 20:16 ..
  -rw-rw-r-- 1 1004 1005    0 Sep  3 20:16 .command.begin
  -rw-rw-r-- 1 1004 1005    0 Sep  3 20:16 .command.err
  -rw-rw-r-- 1 1004 1005   83 Sep  3 20:16 .command.log
  -rw-rw-r-- 1 1004 1005   83 Sep  3 20:16 .command.out
  -rw-rw-r-- 1 1004 1005 2567 Sep  3 20:16 .command.run
  -rw-rw-r-- 1 1004 1005   53 Sep  3 20:16 .command.sh

Command error:
  .command.sh: line 4: foo: Permission denied

Work dir:
  /home/hale/nf-bug/work/f4/7f9e73b071436c0e59d98ae710df81

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

### Environment 

* Nextflow version: `19.07.0` 
* Java version: `openjdk version "10.0.2" 2018-07-17`
* Operating system: `Linux`

### Possible Solution
I don't know if this is the best solution but I'm thinking we could check the
user inside Docker with:
- `docker run --rm ${container} id -u`
- `docker run --rm ${container} id -g`

If the UID/GID is different from the current user then `chown` working directory
before and after executing the actual command.

**Comment by pditommaso** [comment]
Related to #515

**Comment by huguesfontenelle** [comment]
I do not get any "Permission denied".

Anyway, have you tried forcing the docker container to use root as user?
```
    container 'biocontainers/samtools:1.3'
    containerOptions = "--user root"
```

**Comment by haqle314** [comment]
Yep, I'm using that as a temporary workaround. I don't think it's ideal though. This only happens when the UID of the current user differs from the UID of `biodocker` (1000). Thus it might work on one machine but not another. And the user has to be aware of this issue already in order to know about adding `--user root` to `containerOptions`. Otherwise, the error message `Permission denied` is not super helpful. There might also be a piece of code somewhere that expects the user to be `biodocker` and not `root`.

**Comment by pditommaso** [comment]
Not much that can be done on NF side. This is a flaw in Docker design.
