### ISSUE TITLE
Pipeline sharing support for alternative BitBucket Server

### ISSUE THREAD

**Issue by piotr-faba-ardigen** [nextflow-io/nextflow#1297]
## New feature

Nextflow currently supports in its pipelines [sharing feature](https://www.nextflow.io/docs/latest/sharing.html) a product called BitBucket Cloud. This is different from a product called BitBucket Server (aka Stash in the past) which is BitBucket on premise at the moment. Graphical user interfaces look almost the same, but the API is different. Hence, the current implementation is not compatible with Bitbucket Server. The details about differences between those two products are discussed [here](https://community.atlassian.com/t5/Answers-Developer-Questions/Is-there-documentation-on-REST-API-differences-Bitbucket-Server/qaq-p/497461). 

Is there anything against adding this support?

## Usage scenario 

The feature will be useful to anyone attempting to use [Nextflow sharing](https://www.nextflow.io/docs/latest/sharing.html) with BitBucket Server, which is typically the on-premise version of BitBucket.

## Suggested implementation 

Most probably all is needed it to create new class for the BitBucket Server provider: `nextflow/scm/BitbucketServerRepositoryProvider.groovy`, add tests similar to other providers, and add case `bitbucket-server` in `nextflow/scm/RepositoryProvider.groovy`.

Does this sound reasonable?

**Comment by pditommaso** [comment]
A pull request is welcome

**Comment by piotr-faba-ardigen** [comment]
A pull request is submitted: https://github.com/nextflow-io/nextflow/pull/1309

**Comment by pditommaso** [comment]
Solved by 6af6a902.
