### ISSUE TITLE
moving stageMode to the level of file

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#1298]
Hi,
sometimes you may want to have different stageModes for different elements in a process (particularly when you have big a small files). I don't know how complex could be to implement this.

```
process test {
    input:
    set file(a), file(b, stageMode="copy") my_channel

}
```

**Comment by pditommaso** [comment]
Sot supporting this request. Why the need for different `stageMode` modes?

**Comment by lucacozzuto** [comment]
Because if I have 3 different big inputs and I need to copy only one of them it would be nice

**Comment by pditommaso** [comment]
How copying the file is better over symlinking it?

**Comment by lucacozzuto** [comment]
Some shitty programs need to modify the input file.




Il sab 19 ott 2019, 16:55 Paolo Di Tommaso <notifications@github.com> ha
scritto:

**Comment by lucacozzuto** [comment]
And you might have input files that are not writable

L

Il sab 19 ott 2019, 16:55 Paolo Di Tommaso <notifications@github.com> ha
scritto:

**Comment by pditommaso** [comment]
Use `cp` !

**Comment by lucacozzuto** [comment]
Uff

**Comment by pditommaso** [comment]
😄

**Comment by Midnighter** [comment]
I felt the same need where I'm modifying a SQLite database and would like the pipeline to resume if possible. The answer I came up with is (inspired by https://stackoverflow.com/a/17882368):

```bash
 cp --remove-destination "$(realpath -e ${input})" "${input}"
```

**Comment by Midnighter** [comment]
Here is a little example pipeline I've defined to test my needs.

```groovy
#!/usr/bin/env nextflow

nextflow.preview.dsl=2

params.database = 'db.sqlite'
params.outdir = 'results'

process first_task {
    output:
    path "${params.database}"

    """
    sqlite3 ${params.database} "create table tbl1(one varchar(10), two smallint);"
    """
}

process second_task {
    input:
    path db

    output:
    path "${db.getName()}"

    """
    cp --remove-destination "\$(realpath -e ${db})" "${db.getName()}"
    sqlite3 ${db.getName()} "insert into tbl1 values('hello!',10);"
    """
}

process third_task {
    publishDir "${params.outdir}", mode: 'copy'

    input:
    path db

    output:
    path "${db.getName()}"

    """
    cp --remove-destination "\$(realpath -e ${db})" "${db.getName()}"
    sqlite3 ${db.getName()} "insert into tbl1 values('goodbye', 20);"
    """
}

workflow {
    first_task | second_task | third_task
}
```
