### ISSUE TITLE
process is executing whereas input not declared

### ISSUE THREAD

**Issue by tdelhomme** [nextflow-io/nextflow#130]
I have this toy example:
```bash
#!/usr/bin/env nextflow

str = Channel.from('hello', 'hola', 'bonjour', 'ciao')

params.no_print = false

process printHello {

   input:
   val str

   output: 
   file 'test.txt' into result_print

   """
   if [ ${params.no_print} == false ]
   then
	echo $str > test.txt
   else
        touch test.txt
   fi
   """
}	

process empty_test {

  input:
  file 'test.txt' from result_print.filter { file -> !file.isEmpty() }

  output:
  file 'test2.txt' into result_empty_test

  """
  cp test.txt test2.txt
  """
}

process try_concat {

  input:
  file('*.txt') from result_empty_test.toList()

  output:
  file('concat.txt') into last_result

  """
  cat *.txt > concat.txt
  """
}
```

Run this without any option is ok, but with option `no_print` the process `try_concat` is executing and creates an error because `result_empty_test.toList()` is empty (`result_empty_test` not declared).
If I replace `result_empty_test.toList()` by `result_empty_test` it works with option `no_print` (means nextflow does not execute the last process).

**Comment by pditommaso** [comment]
When I run it with `--no_print true` I get the following error: 

    Error executing process > 'try_concat (1)'

    Caused by:
      Process 'try_concat (1)' terminated with an error exit status

    Command executed:

      cat *.txt > concat.txt

    Command exit status:
      1

    Command output:
      (empty)

    Command error:
      cat: *.txt: No such file or directory

That mean that it tried to execute the `try_concat` process but it failed because there are no files. So it is working as expected. The problem is how you want to manage this condition: skip the execution of `try_concat` ? stop the pipeline reporting and error? provide a default value?

**Comment by tdelhomme** [comment]
Ideally would be to skip the execution of `try_concat`

**Comment by tdelhomme** [comment]
But I don't understand why it tries to execute `try_concat` whereas the input channel does not exist (the same for the process `empty_test` and however it is not executed...)

**Comment by pditommaso** [comment]
Because `toList()` returns an *empty* list value that is different from *no* value.

**Comment by tdelhomme** [comment]
yes I see
The idea would be to add a `when` condition to test if this list is empty?

**Comment by pditommaso** [comment]
In your real pipeline you only need `try_concat` to concatenate multiple files? or you are doing other things?

**Comment by tdelhomme** [comment]
[This](https://github.com/IARCbioinfo/needlestack/blob/master/needlestack.nf#L276) is my real process.
It just concatenates vcf files from the list `vcf.toList()` and I would like to skip the process if this list is empty.

**Comment by pditommaso** [comment]
What if you replace `result_empty_test.toList()` with `result_empty_test.collectFile()` ?

That will merge all the files, if any. Then in the process you can apply the `sed` command.

**Comment by tdelhomme** [comment]
Oups sorry on my real process I do another thing after concatenate...
And if I replace this in the toy example I get this:
```
ERROR ~ No signature of method: groovyx.gpars.dataflow.DataflowQueue.collectFiles() is applicable for argument types: () values: []
Possible solutions: collectFile(), collectFile(groovy.lang.Closure), collectFile(java.util.Map), collectFile(java.util.Map, groovy.lang.Closure), collect()
```

**Comment by tdelhomme** [comment]
hum ok syntax error....
Yes it works here!

**Comment by pditommaso** [comment]
Here as well :)

**Comment by tdelhomme** [comment]
Why this does not work?
```
when:
vcf.toList().length() > 0
```

**Comment by pditommaso** [comment]
Because the result of `vcf.toList()` is a dataflow variable not a list. The following should work: 

    when:
    vcf.toList().val.length() > 0

**Comment by pditommaso** [comment]
Well, no. You should invoke `toList()` only one time, thus you should do something like this 

    list = result_empty_test.toList() 

    process try_concat {

      when:
      list.val.size()>0

      input:
      file('*.txt') from list 
  
      :
    }  


Still thinking `collectFile` is the best solution.

**Comment by tdelhomme** [comment]
I will try
Yes but actually I was wrong because I do not exactly concatenate files, I use `vcfoverlay` which does not strictly concatenate...

**Comment by pditommaso** [comment]
I see

**Comment by tdelhomme** [comment]
It seems to work fine and do what I want :+1:

**Comment by pditommaso** [comment]
Anyway your point makes sense. I will try to improve in such a way that when the resulting list is empty it cause to skip the process.

**Comment by tdelhomme** [comment]
Ok cool!  :+1:
