### ISSUE TITLE
Links published by publishDir are not updated on reruns

### ISSUE THREAD

**Issue by haqle314** [nextflow-io/nextflow#1303]
#### Expected
Links published with `publishDir` always point to the most recent run's output.

#### Actual
On subsequent runs, the published link still links to the first run's output.

### Steps to reproduce the problem
Rerun the following script multiple time. The paths matched on the first run but
the published link is not updated on subsequent runs

```nextflow
nextflow.preview.dsl = 2

process date {
    output: path "time.txt"
    shell: "date > time.txt"
}

workflow {
    date() | view {
        produced = file(PWD).relativize(it)
        published = file(PWD).relativize(file("readlink time.txt".execute().text))
        "Produced: ${produced}\nPublished: ${published}"
    }
    publish:
    date.out to: "${PWD}"
}
```

### Environment

* Nextflow version: `19.07.0` 
* Java version: `openjdk version "10.0.2" 2018-07-17`
* Operating system: `Linux`

**Comment by pditommaso** [comment]
Workflow `publish` is not supported anymore.
