### ISSUE TITLE
DSL-2 Publish process outputs with identical filenames

### ISSUE THREAD

**Issue by stekaz** [nextflow-io/nextflow#1306]
I've been playing around with the new DSL #1276 and was wondering if there's a convenient way to publish process outputs that have the same output filenames? This seems a pretty common scenario so I suspect it's just me doing bad things (again...)

```
nextflow.preview.dsl=2

test_input = Channel.from( ['one', 'alpha'], ['two', 'beta'], ['three', 'delta'] )

params.outdir = './results'

process foo {

    tag { sample }

    input:
    tuple val(sample), file('latin.txt') 
    
    output:
    path "foobar.txt"
    
    """
    touch foobar.txt
    """
}   

workflow {

    main:
    foo(test_input)

    publish:
    foo.out to: "${params.outdir}/foo"
}
```

Then run using:

```
NXF_VER=19.08.1-edge nextflow run main.nf
```

In the 'results' folder we find just a single output file. It looks like it clobbered the other two output files. It would be great if there was a way to dynamically publish these, so files with identical names don't get blown away immediately. Ideally, I was looking for something like:

```
workflow {

    ...

    publish:
    foo.out to: "${params.outdir}/foo/${sample}"
}
```

**Comment by pditommaso** [comment]
Good point, this is something that needs to be addressed. I think so far the best workaround is to create the resulting output in a sub-directory eg. 

```
process foo {

    tag { sample }

    input:
    tuple val(sample), file('foobar.txt') 
    
    output:
    path "$sample/foobar.txt"
    
    """
    touch $sample/foobar.txt
    """
} 
```

The syntax could be extended adding a new option to `path` to declare the target file name of a published file, eg


```
    output:
    path "foobar.txt", publishAs: "$sample/foobar.txt"
    
    """
    touch $sample/foobar.txt
    """
```

cc @emi80

**Comment by bio15anu** [comment]
Connected to this: if you have multiple processes publishing to the same `"$sample/"` directory would these not then overwrite each other? And would it be possible also to set `publishAs: null` in the case that you might sometimes want to pass a conditional closure to the publish directive eg. to allow the user to decide whether they want to keep certain files or not?

**Comment by pditommaso** [comment]
The `publish:` will be deprecated in favour of a different mechanism to handle workflow outputs. I'll blog in the following days about that. Closing this feature.

**Comment by DaGaMs** [comment]
Any update on this new mechanism? I'm again hitting a situation where I would need channel-based `publish`, rather than process-based. What I mean is that I have a sub-workflow which does some QC using the same process as for the main data, but I don't want to publish all the QC intermediate steps, I just want to publish the output further down the line. I don't currently see a way to do that without the workflow `publish` directive.

**Comment by yumyai** [comment]
> Any update on this new mechanism? I'm again hitting a situation where I would need channel-based `publish`, rather than process-based. What I mean is that I have a sub-workflow which does some QC using the same process as for the main data, but I don't want to publish all the QC intermediate steps, I just want to publish the output further down the line. I don't currently see a way to do that without the workflow `publish` directive.

I don't know if there is an "official" way to do it, but maybe you can use .onComplete for that?
