### ISSUE TITLE
Error message: Can't open cache DB - Needs file system that supports file locks

### ISSUE THREAD

**Issue by achamess** [nextflow-io/nextflow#1310]
## Bug report 

I'm trying to use Nextflow on my HPC. I installed nextflow via Conda. It installed and can be called. But when I call it, I get the following message:

```
Can't open cache DB: /scratch/a.chamessian/FW_AVP_OXT/.nextflow/cache/75719e7f-e52b-412e-8a50-c37ccd1263d5/db

Nextflow needs to be executed in a shared file system that supports file locks.
Alternatively you can run it in a local directory and specify the shared work
directory by using by `-w` command line option.
```

### Environment 

* Nextflow version: [19.07.0] 
* Java version: openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)
* Operating system: Linux

**Comment by achamess** [comment]
Hi. Just following up on this. Any guidance?

**Comment by pditommaso** [comment]
I think the error is quite self-describing and provides guidance. Have you tried that?

**Comment by achamess** [comment]
Forgive my ignorance, but I'm not exactly sure how to do that. I used Conda to install Nextflow on my cluster. It's in one of my created environments. Do you mean that I should have the nextflow executable installed on some local directory? Not sure how that would differ from how I currently have it.

**Comment by pditommaso** [comment]
Difficult to help more, nextflow needs to be execute in a directory when it can write files and create file system locks. It looks your system for some reason is preventing that. Try to ask to your sysdamins.

**Comment by achamess** [comment]
Hi. I checked with my sysadmin. His response was:

> Both scratch and home directory are shared file system.
They are also Lustre file system that may not have any sense of file locking.
I am not sure what I can do.

Is there something special i need to do to work with a Lustre file system?

**Comment by pditommaso** [comment]
Not sure how can help more 🤷‍♂️

**Comment by nick297** [comment]
BTW in case this helps anyone. I've just had the same error running nextflow with Docker. It crashed with the following error message after I let it run out of space.

```#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007fd545880d45, pid=21612, tid=30272
#
# JRE version: OpenJDK Runtime Environment (11.0.6+10) (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x18ed45]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /mnt/Data2/staph_nano_muts/core.21612)
#
# An error report file with more information is saved as:
# /mnt/Data2/staph_nano_muts/hs_err_pid21612.log
Compiled method (nm) 35503582 3619     n 0       jdk.internal.misc.Unsafe::copyMemory0 (native)
 total in heap  [0x00007fd52c3e8010,0x00007fd52c3e83c8] = 952
 relocation     [0x00007fd52c3e8188,0x00007fd52c3e81b8] = 48
 main code      [0x00007fd52c3e81c0,0x00007fd52c3e83c8] = 520
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
#
```

Then when trying to run again I get this error message.
```ERROR ~ Can't open cache DB: /mnt/Data2/staph_nano_muts/.nextflow/cache/fb3e8f9f-eaad-4988-a009-248f18d631aa/db

Nextflow needs to be executed in a shared file system that supports file locks.
Alternatively you can run it in a local directory and specify the shared work
directory by using by `-w` command line option.

 -- Check '.nextflow.log' file for details
```
I deleted the LOCK file (and made some space)

```
rm .nextflow/cache/fb3e8f9f-eaad-4988-a009-248f18d631aa/db/LOCK
```
But now it can't read the history file, so won't resume. I guess running out of space has messed it up. Not a problem for this run as I'm just testing.

**Comment by ad2021** [comment]
I also received this message when my docker profiled job ran out of local disk space.

**Comment by MauriAndresMU1313** [comment]
Is there any way that could be related to `SELinux` security measures?
