### ISSUE TITLE
Google Cloud Engine Failed to notify task completion

### ISSUE THREAD

**Issue by billgreenwald** [nextflow-io/nextflow#1312]
## Bug report 

During execution, all tasks get submitted (beyond the number of available cores) in a google cloud engine setup, and eventually all tasks stall out and must be force stopped.

Output becomes: 
ERROR ~ === Failed to notify task completion

### Expected behavior and actual behavior

Expected behavior is to submit tasks up to the number of available cores across all machines, wait until more free up, and then submit more, without losing the pipeline's ability to complete and have the error occur.

### Program output 

ERROR ~ === Failed to notify task completion

### Environment 

* Nextflow version: 19.01.0
* Java version: 1.8.0_211
* Operating system: Ubuntu

### Additional context

The pipeline submits the correct number of jobs on a local execution, and stopping the pipeline and resuming clears the errors and keeps the pipeline running fine.

**Comment by pditommaso** [comment]
This feature is going to be deprecated. Consider using [Google Life Sciences](https://www.nextflow.io/docs/latest/google.html#cloud-life-sciences) executor.
