### ISSUE TITLE
process level profiles

### ISSUE THREAD

**Issue by JonathanCSmith** [nextflow-io/nextflow#1314]
## New feature

Would it be possible to have profiles declared at the process level? I would like to support both modules and docker containers depending on where my pipeline are being executed. I know I can achieve this at the configuration level but it feels like it would be more intuitive and in keeping with the other process directives to have these kind of conditional profiles declarable on the process itself. It also feels more manageable as the number of process scale. The profiles could then easily declare other per process per profile properties such as executors and cpus etc (not sure if per process executors is actually supported or not but I hope you understand my thought process).

## Usage scenario 

Usage would be identical to current. Call nextflow with your desired profile.

## Suggest implementation 

The current scenario:

nextflow.config:
```
profile {
    moduleProfile {
        $process1.module = 'a/module'
        $process2.module = 'a/module'
        $process3.module = 'a/module'
        ...
    }

    containerProfile {
        $process1.container = 'a/container'
        $process2.container = 'a/container'
        $process3.container = 'a/container'
    }
}
```

would become:
```
process1 {
    
    profiles {  // This outermost nesting level is probably redundant, but optionally fine
        moduleProfile {
            module 'a/module'
        }

        containerProfile {
            container 'a/container'
        }
    }
}
```

**Comment by pditommaso** [comment]
I think the same can be done using existing [process selectors](https://www.nextflow.io/docs/latest/config.html#process-selectors).

**Comment by JonathanCSmith** [comment]
I would need a way to switch label a process is associated with depending on execution profile then. 1) its not clear that this is doable and 2) I would need to create two labels per process. The overhead seems quite large?

**Comment by pditommaso** [comment]
[This blog](https://medium.com/@lucacozzuto/using-gpu-within-nextflow-19cd185d5e69) is showing a parametric label. 

You can even define the `container` directive using a dynamic rule eg. 

```
process foo {
  container { params.x == 'something' ? 'container_a' : 'container_b' }
  '''
  your_command
  '''
}
```

The dynamic rule can obviously contain any valid groovy expression ie. you can use a custom function for complex logic.

**Comment by JonathanCSmith** [comment]
This would work well for conditional container switching - I am not sure if it will work for switching between container and module dependencies?

**Comment by pditommaso** [comment]
I see, then better the `label` approach using different profiles.
