### ISSUE TITLE
Singularity - cannot open file

### ISSUE THREAD

**Issue by Lcornet** [nextflow-io/nextflow#1315]
Dear NF team,

I am very new to Nextflow so I try in a very simple way, using a singularity image. The idea was to design a simple script using BLAST in a singularity image. I have the following error when I try my Nextflow pipeline with singularity :   

N E X T F L O W  ~  version 19.07.0
Launching `test-infile.nf` [crazy_noyce] - revision: 58338f4417
WARN: Access to undefined parameter `help` -- Initialise it to a default value eg. `params.help = some_value`
executor >  local (1)
executor >  local (1)
[8d/c1e43b] process > test (1) [100%] 1 of 1, failed: 1 ✘
Error executing process > 'test (1)'

Caused by:
  Process `test (1)` terminated with an error exit status (1)

Command executed:

  head -n10 GCF_900093115.1_18090_8_61_genomic.fna > temp.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  head: cannot open 'GCF_900093115.1_18090_8_61_genomic.fna' for reading: No such file or directory

When I run the same command without singularity, it works :  
[lcornet@lemaitre3 ~]$ nextflow run test-infile.nf --query /home/ulg/medgen/lcornet/files/head.fasta --database /home/ulg/medgen/lcornet/files/GCF_900093115.1_18090_8_61_genomic.fna

N E X T F L O W  ~  version 19.07.0
Launching `test-infile.nf` [jovial_fermat] - revision: 58338f4417
WARN: Access to undefined parameter `help` -- Initialise it to a default value eg. `params.help = some_value`
executor >  local (1)
[10/1019b2] process > test (1) [100%] 1 of 1 ✔

I have the same issue if I create a config file like this  (and if a use blast from the container)
process.container = '/path/to/singularity.img'
singularity.enabled = true

Singularity (version 3.1.1-1.el7) seems to work : 
[lcornet@lemaitre3 ~]$ singularity exec singularity-img/singularity-BLAST.img head -n10 files/GCF_900093115.1_18090_8_61_genomic.fna 
>NZ_FLWB01000038.1 Klebsiella pneumoniae strain PB484, whole genome shotgun sequence
CGAGTGACCTGCCCCCAGGATTAGATACAACCGTCAGTTAGTAAGGTCGGTTTGTTTACCTTCACATTTTCCATTTCGCC
ACCGTGCTGCAAACTCTGATGGCGTCTGATAATTCAGTGCTGAATGTGGACGACACTCGTTATAATCCTGCCGCCAGTCA
TTAATGATTTTCCTTGCGTGAACGATATCGCTGAACCAGTGCTCATTCAGGCATTCATCGCGAAATCGTCCGTTAAAGCT
CTCAATAAATCCGTTCTGCGTTGGCTTCCCGGCTGGATTAAGCGCAACTCAACACCATGCTCAAA
...

Can you help me to understand the problem?
Thanks for your help

This is the script : 
#!/usr/bin/env nextflow

params.query = "NA"
if (params.query == "NA") {
	exit 1, "Query option mandatory, currently defined as NA : use --query= PATH-2-data option"
}

params.database = "NA"
if (params.database == "NA") {
	exit 1, "Database option mandatory, currently defined as NA : use --database= PATH-2-data option"
}

//Core program
query_ch = Channel
				.fromPath(params.query)
				.ifEmpty { error "Cannot read file: ${params.query}" } 
	
query_db = Channel
				.fromPath(params.database)
				.ifEmpty { error "Cannot read file: ${params.database}" }

process test {
    input:
    file database from query_db
    
	output:
	file "temp.txt" into temp_ch

    """
    head -n10 $database > temp.txt
    """
}

**Comment by stekaz** [comment]
I may be wrong, but I don't think this has anything to do with Singularity.

> Command error:
head: cannot open 'GCF_900093115.1_18090_8_61_genomic.fna' for reading: No such file or directory

Basically, this just means that your database file could not be staged into the process working directory. In most cases, this is because the path you've provided doesn't exist on your filesystem. I would first check the file inputs to the first command that you used created the error. You may have a typo in the path to your database file.

**Comment by stekaz** [comment]
Also, this doesn't actually check that your file exists or can be read:

> .ifEmpty { error "Cannot read file: ${params.database}" }

The [ifEmpty](https://www.nextflow.io/docs/latest/operator.html#ifempty) operator will only fire when the channel itself is empty. Usually it's used to emit a default value. It's not really needed here. I have refactored your example to instead use value channels:

```
#!/usr/bin/env nextflow

params.query = null
if (!params.query) {
    exit 1, "Query file required, please use the `--query` option"
}

params.database = null
if (!params.database) {
    exit 1, "Database file required, please use the `--database` option"
}

// Core program
query_fa = file(params.query)
query_db = file(params.database)


process test {

    input:
    file query_db

    output:
    file "temp.txt" into temp_ch

    """
    head -n 10 "${query_db}" > temp.txt
    """
}
```

**Comment by Lcornet** [comment]
Thanks stekaz for the help and advise on the script, it help.

The solution was actually quite simple, I create a nextflow.config file process.container = '/home/users/l/c/lcornet/singularity-img/singularity-BLAST.img'
singularity.enabled = true
singularity.autoMounts = true

the autoMounts was the solution to work on the cluster.

Thanks,
