### ISSUE TITLE
Google Pipelines - support for Preemptible VMs

### ISSUE THREAD

**Issue by technivore** [nextflow-io/nextflow#1317]
## New feature

Currently it is possible to use Google's [Preemptible VMs](https://cloud.google.com/preemptible-vms/) via the Google Genomics Pipelines API, but Nextflow does not expose this functionality. Instead, VMs created by Nextflow via the Google Genomics Pipelines API are always non-preemptible, full-price VMs. Allowing users to specify that VMs should be preemptible will allow for lower cost usage of GCP, especially in combination with #1220.

## Usage scenario 

Allowing users to specify "preemptible = true" in their `google` configuration should cause Nextflow to [setPreemptible(true)](https://developers.google.com/resources/api-libraries/documentation/genomics/v2alpha1/java/latest/com/google/api/services/genomics/v2alpha1/model/VirtualMachine.html#setPreemptible-java.lang.Boolean-) when instantiating the pipeline.

## Suggest implementation 

This could be implemented just like #1220, defaulting to `false`. I'd be happy to submit a PR.

**Comment by kdbinder** [comment]
From https://github.com/nextflow-io/nextflow/blob/master/docs/google.rst


Preemptible instances
An optional parameter allows you to set the instance to be preemptible. Both master and worker instances can be set to be preemptible. The following example shows a cluster configuration with a preemptible setting:

cloud {
    imageId = 'rare-lattice-222412/global/images/seqvm-1'
    instanceType = 'n1-highcpu-8'
    preemptible = true
}
Setting an instance to preemptible allows the administrator to kill the VM at will and may affect the pricing of the instance.

**Comment by technivore** [comment]
Huh. I have no idea how I missed that. Thanks!
