### ISSUE TITLE
Mode flatten adds null to empty lists

### ISSUE THREAD

**Issue by szymonwieloch** [nextflow-io/nextflow#1318]
```
process test {
  input:
  
  output:
    val(a) into aChannel mode flatten
    val(b) into bChannel mode flatten
  exec:
  a = [1,2,3]
  b = []
}

aChannel.println()
bChannel.println()
```

In this case you would expect that the a channel will print 3 elements and the b channel will print 0 (none) elements. But in fact the b channel is not empty and will print one null element.

This causes problems when for example you read data from a file and you create a channel with data to be processed. In case you read zero elements, the channel is not empty and the null value usually does not match input of next processes, therefore it breaks the pipeline.

To illustrate this problem better here is another example:
```
process generateData {
  output:
    val(out) into chann mode flatten
  exec:
  rnd = new Random()
  out = []
  num = rnd.nextInt(3)
  num.times{
      out.add(['number:', i])
  }
}


process processData {
  input:
  set val(first), val(second) from chann
  
  script:
  """
  echo $first $second
  """
}
```

Process generateData generates 0-3 elements randomly and in 1/3 of cases you will see the following message:

> WARN: Input tuple does not match input set cardinality declared by process `processData` -- offending value: null

**Comment by pditommaso** [comment]
I agree that sounds bad. However, the plan is to deprecated *mode flatten* in future releases. Use the `flatten` operator instead. 

```
process test {
  input:
  
  output:
    val(a) into aChannel 
    val(b) into bChannel 
  exec:
  a = [1,2,3]
  b = []
}

aChannel.flatten().println { "a: $it" }
bChannel.flatten().println { "b: $it" }
```
