### ISSUE TITLE
Using Instance templates with Nextflow on GCP

### ISSUE THREAD

**Issue by daudn** [nextflow-io/nextflow#1320]
I have two questions regarding Nextflow on Google Cloud Platform. 

1. Can we give a process an instance template? 
2. Each instance seems to have a 500GB Persistent Disk attached to it, and that slowly exhausts my disk quota. Is there any way to customize/remove/use a filestore in place of this?

The reason I want to use an Instance Template is so that I can mount a filestore to each instance that is spun up. In the workflow I'm trying to create, I have approx 50 processes happening in parallel and they all work on the same files (in different folders) and so Filestore is the most ideal solution. Having instance templates means I can have startup scripts and those scripts can attach the Filestore to the instance, and into the Docker being run through Nextflow. In case I cannot use an instance template, I see the instances already has a startup script. Am I allowed to edit this startup script to suit my needs?

For the persistent disk being attached, I'm not entirely sure why a process would need 500 GB of space if the instance is going to die directly after. I also looked at the scope "Disk" that can be added in with the process. That value doesn't seem to affect the local bootable disk attached to these instances. But the major issue is the 500 GB standard persistent disk. Cause lets say I have a total of 50 instances running. 500 GB soon becomes 25,000 GB I could increase my quota, but I'd rather decrease the 500GB to say, 50 GB (at least)

**Comment by pditommaso** [comment]
Can you provide more detail about this feature? Whis the respective Google API involved?
