### ISSUE TITLE
automatically create output directories

### ISSUE THREAD

**Issue by grst** [nextflow-io/nextflow#1321]
I recently switched from Snakemake to nextflow, and a feature that I miss is the automatic creation of the output folder structure (but maybe I miss something...). 

What I mean is the following: 
Say, I have a rule that creates a lot of output files and I want to organize them within the `work` directory. For instance:

```nextflow
// using DSL2
output:
    file "filtered/adata.h5ad" 
    file "corrected/adata.h5ad"
    file "reports/filter.html" 
```

From the process, I call a script that does some stuff and generates `reports/filter.html`. The script fails, because the `reports` directory does not exist. Of course, I could create it manually at some point, but I think that's something the pipeline engine could take care of for me. 

So what I would like nextflow to do is, to parse the output files for each process, and create all directories that do not exist yet in the `work` directory. 

Cheers, 
Gregor

**Comment by apeltzer** [comment]
You can use a `publishDir` directive https://www.nextflow.io/docs/latest/process.html#publishdir to adjust that. See an example here: https://github.com/nf-core/rnaseq/blob/37f260d360e59df7166cfd60e2b3c9a3999adf75/main.nf#L473

**Comment by grst** [comment]
But that would be to organize the `publishDir`, wouldn't it? 
What if I want to organize files already in the `work` directory?

**Comment by apeltzer** [comment]
You don't need to do that. That directory is for temporary data that shouldn't be referred to anyways - if you want to have specific files as output, define them in the `publishDir` directive, potentially using a closure to stage them to your desired results folder or pass them on to the next process via channels. Its fundamentally different file handling than in Snakemake but you'll see it makes sense ;-)

**Comment by grst** [comment]
Ok, maybe I have to describe my special use-case. Maybe it is also so special that I can as well create the directories manually. Or maybe I have to re-think how I handle it. 

I use nextflow to integrate jupyter notebooks into a pipeline. Each process renders a notebook and the next process depends on the results of the previous notebook. I want the results to appear in a results directory `results/notebook_XX`. So far, so good. Easily doable with `publishDir`. 

But, I want also to be able to execute the notebooks interactively in jupyter notebook (to develop & debug). I therefore have to specify the full `results` path in the notebook, because the notebook doesn't know about `publishDir`. 

This is why I am using non "nextflowic" (can you say that? :D) output paths like `results/notebook_01/report.html`.

**Comment by grst** [comment]
Anyway, [parameterizing notebooks](https://papermill.readthedocs.io/en/latest/usage-parameterize.html) seems the more elegant solution.

Thanks for the discussion, this helped finding the proper way ;)
