### ISSUE TITLE
`.command.run: line 184: echo: write error: Broken pipe`

### ISSUE THREAD

**Issue by LukeGoodsell** [nextflow-io/nextflow#1322]
I'm using Nextflow 19.07.0. I have one process that occassionally fails with this error message:

```
  Command exit status:
    1

  Command output:
    (empty)

  Command error:
    .command.run: line 184: echo: write error: Broken pipe
```

I have been unable to identify the root cause, but it appears to occur when the compute node it is on has a peak in I/O latency. I suspect that this causes the commands in `nxf_trace_linux` after the `.command.sh` process has finished to take more than 10 seconds to complete, resulting in `nxf_mem_watch` exiting before it receives the `DONE` signal from `nxf_trace_linux`.

When I have tried to reproduce this error, in the most extreme example it appears to take only a little more than 10s to complete. An easy fix would therefore be to rase the timeout [here](https://github.com/nextflow-io/nextflow/blob/3766842ae2b93aebc298783f5a091f9d96b97683/modules/nextflow/src/main/resources/nextflow/executor/command-trace.txt#L112) from 10 seconds to, say, 60 seconds. Alternatively, we could have `nxf_mem_watch` monitor the trace file until a message is written by the calling context, e.g. "nextflow.trace/v2".

Are either of these options acceptable? Do you have a preference/suggestion? I'm happy to raise a PR with an acceptable change.

Incidentally, the contents of `nxf_write_trace` is duplicated in `nxf_trace_linux` - I'd suggest that the above PR can include modifying `nxf_trace_linux` to simply call `nxf_write_trace` instead.

**Comment by pditommaso** [comment]
Can you report which exactly is the line 184? Also, can you check which version of Bash are you suing in your cluster?

**Comment by pditommaso** [comment]
Latest [20.01.0-edge](https://github.com/nextflow-io/nextflow/releases/tag/v20.01.0-edge) includes some fixes for the job launcher script. Can you check if this problem still happens with this version?

**Comment by FilipeJesus** [comment]
@pditommaso 

1. We believe the error occurs at [line 202](https://github.com/nextflow-io/nextflow/blob/3766842ae2b93aebc298783f5a091f9d96b97683/modules/nextflow/src/main/resources/nextflow/executor/command-trace.txt#L202) as nxf_trace_linux attempts to send the signal "DONE" to file descriptor 10 after the nxf_mem_watch subshell has finished.
2. We are using version 4.2.46(2)-release of bash.

**Comment by pditommaso** [comment]
Please provide context. Which NF version are you running? which batch scheduler?

**Comment by FilipeJesus** [comment]
We are using Nextflow `19.07.0` and the Sun Grid Engine as our scheduler. I am currently trying to reproduce the error on `20.01.0-edge`. As mentioned by OP we believe this bug is due to  `nxf_trace_linux` taking longer than the timeout time (10s) of `nxf_mem_watch` to complete. The bug is difficult to reproduce but has occurred to multiple of our users.

**Comment by pditommaso** [comment]
I would suggest to test it again using latest stable 20.04.1.
