### ISSUE TITLE
Publishdir copy and symlink to copied output

### ISSUE THREAD

**Issue by Brandon1805** [nextflow-io/nextflow#1325]
Hi! I was wondering if there was an option to perform a PublishDir copy directive and then perform a PublishDir symlinks directive that produces a link to the copied published output instead of to the output in the original work directory. 

I need to do this since I need to wipe the work directory after each run, but I need to keep a hard copy of the output as well as a link for another user.

**Comment by pditommaso** [comment]
No. Consider using a (hard) link instead, provided your file system allow that https://www.nextflow.io/docs/latest/process.html#publishdir.
