### ISSUE TITLE
Input files containing a parenthesis in the path are not staged properly 

### ISSUE THREAD

**Issue by JoseEspinosa** [nextflow-io/nextflow#133]
I have a folder with several files to process downloaded from a DB, some of them containing parentheses. Files without parenthesis are correctly executed by the process, however, files with parentheses are not. When I checked the work folder for each respective case, I found that the problem is that the symbolic link that nextflow generates inside the work folder was not correctly generated in the case of files with parentheses inside its name.

To clarify my issue:

```
mat_files_path = "${params.path_files}*.mat" mat_files = Channel.fromPath(mat_files_path) 
// Files inside the folder can be of type:
// foo(1).mat
// or
// foo 1.mat

process get_speed { 
  input: file file_worm from mat_files 
  ... 
}
```

**Comment by pditommaso** [comment]
Fixed in version `0.18.1`
