### ISSUE TITLE
convert arguments to string for .txt files to read them in R.script

### ISSUE THREAD

**Issue by nilaycan** [nextflow-io/nextflow#1330]
Hello!

I am trying to "convert arguments to string" for .txt files to read them in my .R script. 

**I have a script for the process in main.nf like:**

` script:
    """
    Rscript ${baseDir}/bin/script.R ${params.parameter} dir1 dir2 dir3
    """
`
**and I want to use those dirs in my Rscript like**

env= paste(args[2], "env.txt", sep = .Platform$file.sep)
cov= paste(args[2], "cov.txt", sep = .Platform$file.sep)
meth= paste(args[3], "methylation.txt", sep = .Platform$file.sep)
Emodel_result= paste(args[4], "result.txt", sep = .Platform$file.sep)
Emodel_result_qqplot= paste(args[4], "QQplot.jpg", sep = .Platform$file.sep)

**then call the function like:**

function(env, cov, meth, args[1], Emodel_result, Emodel_qqplot, savePlot=FALSE)

I defined dir1,dir2,dir3 like:

dir1 --> ${output_path}/dir1
dir2--> ${output_path}/..../dir2
dir3 --> ${output_path}/..../dir3

Am I doing something wrong or? I definitely need to read the .txt file as converted into string for the function in my script.R so this way seems OK? Something seems unpleasant because I got an error.

Thanks in advance!

**Comment by pditommaso** [comment]
Not sure to understand what the problem is, however you can find a similar example at this link

https://github.com/cbcrg/kallisto-nf/blob/master/kallisto.nf#L139
https://github.com/cbcrg/kallisto-nf/blob/master/bin/sleuth.R#L6

**Comment by nilaycan** [comment]
Actually what I would like to do is:

Get directories as an argument, concatenate them while converting them into a character.

directory is smt like this: ${outputh_path}/dir1/dir2/${smt}/dir3

What I will do is:

Rscript ${baseDir}/bin/myscript.R ${smt.param} ${outputh_path}/dir1/dir2/${smt}/dir3

So, I will use args[2] in "myscript.R" like:

file= paste(args[2], "file.txt", sep="/")

but somehow it is not working. Now problem is clear and you have an idea?

Thanks for the links btw!

**Comment by pditommaso** [comment]
This looks more a problem with the R script than with NF. My suggestion is to decompose the problem in such a way you are able to test and run the R script independently NF, then it should be straightforward to invoke it from the pipeline script. Hope it helps.
