### ISSUE TITLE
env variables in config are exported with strange syntax with running with singularity

### ISSUE THREAD

**Issue by shyama-mama** [nextflow-io/nextflow#1335]
### Expected behaviour and actual behaviour

When declaring env variables in config. It is expected to be exported into a process as follows:
`export NAME="VAL"`
When executing on local, expected behaviour is achieved. But when running with a singularity image it is exported as 
`export NAME=\"VAL\"`
Which breaks many things especially if `VAL` is a path. 

### Steps to reproduce the problem
test.nf file: 
```
#!/usr/bin/env nextflow

process someProcess {
    executor 'local'

    echo true

    script:
    """
    ls \${REFERENCE_FA}
    """
}
```
nextflow.config file

```
env {
  REFERENCE_FA = "/data/genome/hs37d5x.fa"
}
```

### Program output 

When running on the local machine
```
nextflow run test.nf
```
the program gives the following output without any issues.
```
/data/genome/hs37d5x.fa
```
But running with a singularity container:
```
nextflow run test.nf -with-singularity /PATH/TO/IMG
```
Seems  to give the following error:

```
Command error:
  ls: cannot access '"/data/genome/hs37d5x.fa"': No such file or directory
```
I can confirm that the singularity image does have a `/data/genome/hs37d5x.fa` file. 

Looking at the `.command.run` file. It looks like when running with singularity enabled the export command tries to escape the double quotes as seen below:
```
nxf_container_env() {
cat << EOF
export REFERENCE_FA=\"/data/genome/hs37d5x.fa\"
EOF
}
```

I edited the `.command.run` file to the following (removed the slash that escaped the double quote)
```
nxf_container_env() {
cat << EOF
export REFERENCE_FA="/data/genome/hs37d5x.fa"
EOF
}
```

And that fixes the issue and behaves as expected. Not sure why nextflow is trying to escape the double quotes. Is this expected behaviour? What purpose does escaping the double quotes serve?

### Environment 

* Nextflow version: 19.07.0
* Java version: 1.8.0_101
* Operating system: Linux

**Comment by pditommaso** [comment]
Should be solved by #1289

**Comment by pditommaso** [comment]
Duplicated of #1289

**Comment by shyama-mama** [comment]
That's awesome. Thanks for that!
