### ISSUE TITLE
accelerator does not generate GPU details in AWS Batch job definition and job is stuck in RUNNABLE

### ISSUE THREAD

**Issue by toniher** [nextflow-io/nextflow#1339]
### Expected behavior and actual behavior

Using AWS Batch profile and accelerator for GPU processes, jobs are stuck in runnable status: eg.:

```
process baseCalling {

    label (params.GPU == "ON" ? 'basecall_gpus': 'basecall_cpus')

    accelerator 1
```
 
If accelerator is skipped, job is run but it fails since no GPU seems to be mobilized (libcuda.so.1 missing error). Job definition from Nextflow process misses any reference to GPU in its JSON...

It's worth noting that if the affected process is run interactively in an EC2 instance, instead of SPOT AWS Batch Job, no problem...

### Steps to reproduce the problem

Example profile excerpt:

```
  withLabel: basecall_gpus {
        container = 'mycontainer'
        maxForks = 1
        containerOptions = { workflow.containerEngine == "singularity" ? '--nv':
           ( workflow.containerEngine == "docker" ? '-u $(id -u):$(id -g) --gpus all': null ) } 

  } 

profiles {
  
  awsbatch {
    workDir = 's3://frankfurt-nf/work'
    process.executor = 'awsbatch'
    process.queue = 'gspot'
    aws.batch.cliPath = '/home/ubuntu/miniconda/bin/aws'
    aws.region = 'eu-central-1'    
    docker.enabled = true
  }

}
```

### Environment 

* Nextflow version: 19.09.0-edge
* Java version: openjdk version "1.8.0_222"
* Operating system: Linux
* Instance/type in Cluster environment: p3

**Comment by pditommaso** [comment]
Not sure the problem is on NF side. Jobs that remain in RUNNABLE status usually signal that the AWS was not able to fulfil your request. Was the Spot Instance request created? Also have you checked that your request was not overcoming your limits for that instance type (see below)?

<img width="1149" alt="Screenshot 2019-10-19 at 14 27 05" src="https://user-images.githubusercontent.com/816968/67144902-8c95ba00-f27c-11e9-8c93-17ef05e951c7.png">

**Comment by toniher** [comment]
Yes, spot instance is created and eventually fulfilled. As I comment, when the process is CPU based (but using p3 instances), no problem actually happens. As a next bit of information, I tried to comment this part:

```
           ( workflow.containerEngine == "docker" ? '-u $(id -u):$(id -g) --gpus all': null ) } 
```

GPU actually appeared in job definition, but it remained stuck in RUNNABLE.

I would think there does not seem to be a limit problem. Check screenshot below:

![Screenshot_2019-10-19 EC2 Management Console](https://user-images.githubusercontent.com/535539/67145752-4b090d00-f284-11e9-8754-6111898256ba.png)

I'll try to see if I can provide a public use case example. Any tip regarding debugging this kind of cases would be appreciated!

**Comment by tbugfinder** [comment]
Which AMI are you using?

**Comment by toniher** [comment]
It is a custom created AMI based on Ubuntu 18.04 based on these instructions: https://docs.aws.amazon.com/batch/latest/userguide/create-batch-ami.html and this software instructions: https://medium.com/@lpryszcz/containers-with-cuda-support-5467f393649f

**Comment by tbugfinder** [comment]
Did you try to output env ?
I suspect that the lib path setup isn't complete.

**Comment by pditommaso** [comment]
I was able to replicate the problem in my test. Asking to AWS for support I got this reply: 

>They have advised that the Custom AMI that's being used with the compute environment needs to have the base AMI as 'Amazon ECS GPU-optimized AMI' [1], please allow me to explain further.
>
>From the description of the AMI 'ami-649b3d1d', the AMI is based on the ECS-Optimized Amazon Linux AMI. At this time the base AMI needs to be the 'Amazon ECS GPU-optimized AMI' , this is because the base ECS-Optimized AMI doesn't run the 'nvidi-docker' [2] agent that is required.
>
>Without this version of docker, Batch isn't aware that there is a GPU available for use within the Compute environment. As such this will then prevent Batch from placing the Job, as it doesn't know there is available GPU resources for the job. This also explains why this job doesn't run when the GPU value is set to one in the Job definition, but runs without issue when it's not.
