### ISSUE TITLE
Adding credentials support for `with-weblog` configuration

### ISSUE THREAD

**Issue by ebenz99** [nextflow-io/nextflow#1340]
## Allowing Nextflow to POST logs to a endpoint with credentials

Hi all. I'm more-or-less proposing the expansion of the `with-weblog` configuration to allow for credential passing to an endpoint (e.g. an AWS S3 bucket). As it stands currently, logs can only be saved locally or POSTed to a public endpoint.

## Usage scenario 

In any case where a workflow is being run from a machine not owned by the user, workflow logs are in danger if only saved locally to the machine. For persistence, an easy solution is the cloud. While the `with-weblog` Nextflow configuration allows for the POSTing of logs to an endpoint, it's useless if that endpoint were to require credentials (like an S3 bucket does).

## Suggest implementation 

Since Nextflow already allows for an `aws` configuration, the easiest way to add this functionality might be somehow allowing the `with-weblog` scope to use the information provided by the `aws` scope for posting.

**Comment by pditommaso** [comment]
There's no plan to support since it overlaps with Nextflow Tower project https://github.com/seqeralabs/nf-tower
