### ISSUE TITLE
Join operation incorrectly represented in DAG

### ISSUE THREAD

**Issue by replikation** [nextflow-io/nextflow#1346]
## Bug report 

* Join operation in the rendered DAG is incorrectly disconnected in nextflow  v19.10.0 
* `combine`, `cross` are working fine

### Expected behavior and actual behavior
**expected behavior tested with version `19.04.1`**
![chart](https://user-images.githubusercontent.com/35726766/67498404-ac175300-f67f-11e9-8a43-2d43976fc2b2.png)

**actual behavior with version `19.10.0`**
![test](https://user-images.githubusercontent.com/35726766/67495831-cd764000-f67b-11e9-851a-406dae1b8d9a.png)

### Steps to reproduce the problem

```
Channel.from('foo').set{ chn1 }
Channel.from('bar').set{ chn2 }
chn1.join(chn2)
```

### Environment 

* Nextflow version: v19.10.0 
* Java version: OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
* Operating system: [ubuntu:xenial]

### Additional context

maybe a similar problem like in #1268 but with `.join` ?

**Comment by gongyixiao** [comment]
Same thing happens for `combine` operator. My nextflow version is `v19.07.0`

**Comment by pditommaso** [comment]
Solved. Thanks for reporting it.
