### ISSUE TITLE
nextflow -help doesn't mention console

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#1347]
Running `nextflow -help` gives no mention of the `nextflow console` subcommand:

```console
$ nextflow -h | grep console
```

https://www.nextflow.io/blog/2015/introducing-nextflow-console.html

..any other subcommands it's missing? 😅

**Comment by pditommaso** [comment]
damn, one more issue 😄

**Comment by pditommaso** [comment]
Fixed

**Comment by ewels** [comment]
🎉 🙏
