### ISSUE TITLE
problem with exponential backoff example

### ISSUE THREAD

**Issue by jaredo** [nextflow-io/nextflow#1350]
### Expected behavior and actual behavior

I am trying the dynamic retry with backoff example from the [documentation](https://www.nextflow.io/docs/latest/process.html#dynamic-retry-with-backoff) and am receiving the error : `Unknown process directive: sleep`.

### Steps to reproduce the problem

```
process test {
   errorStrategy { sleep(Math.pow(2, task.attempt) * 200); return 'retry' }
   maxRetries 2

   output:
   file('2')

   shell:
   """
   touch ${task.attempt}
   """
}
```

### Program output 

```
$ grep sleep .nextflow.log
nextflow.exception.IllegalDirectiveException: Unknown process directive: `sleep`
```

### Environment 

* Nextflow version: 19.10
* Java version: java 10.0.1 2018-04-17
* Operating system: macOS 10.14.6

**Comment by jaredo** [comment]
[nextflow.log](https://github.com/nextflow-io/nextflow/files/3779684/nextflow.log)

**Comment by pditommaso** [comment]
It happens because `pow` returns a double type, instead `sleep` expected a `long`, the following works: 

```
sleep(Math.pow(2, task.attempt) * 200 as long)
```
