### ISSUE TITLE
Nextflow fails to resubmit SLURM jubs after they are killed due to memory or time limit

### ISSUE THREAD

**Issue by kauralasoo** [nextflow-io/nextflow#1354]
## Bug report 

Nextflow fails to resubmit SLURM jobs after they are killed due to exceeding memory or time limit.

### Expected behavior and actual behavior

Nextflow detects that the job was killed by SLURM due to exceeding memory or time limits and resubmits the job with increased resource allocation. 

This used to work previously, but does not work anymore on our system. I am not sure if the error was caused by upgrading Nextflow to the latest version or if there have been some changes to our SLURM configuration so that SLURM is no longer returning correct exit codes to Nextflow.

### Steps to reproduce the problem

Relevant sections from the config file:

```
process{
  maxRetries = 3
  maxErrors = '-1'

  errorStrategy = { task.exitStatus in [143,137,104,134,139,9] ? 'retry' : 'terminate' }

  withName: crossmap_genotypes {
    memory = { check_max( 10.MB * task.attempt, 'memory' ) }
    cpus = 1
    time = { check_max( 15.m * task.attempt, 'time' ) }
  }
}
```

### Program output 

Output from nextflow:
```
> Error executing process > 'crossmap_genotypes (11)'
> 
> Caused by:
>   Process `crossmap_genotypes (11)` terminated for an unknown reason -- Likely it has been terminated by the external system
> 
> Command executed:
> 
>   CrossMap.py vcf GRCh37_to_GRCh38.chain chr17.dose.vcf.gz Homo_sapiens.GRCh38.dna.primary_assembly.fa chr17_mapped.vcf
>   bgzip chr17_mapped.vcf
> 
> Command exit status:
>  
> 
> Command output:
>   (empty)
```
Nextflow does not seem to detect command exit status?

Slurm output:
```
(base) [a72094@stage1 genotype_qc]$ sacct -j 6908911 --format=User,JobID,Jobname,partition,state,time,start,end,elapsed,MaxRss,MaxVMSize,nnodes,ncpus,nodelist,ExitCode
     User        JobID    JobName  Partition      State  Timelimit               Start                 End    Elapsed     MaxRSS  MaxVMSize   NNodes      NCPUS        NodeList ExitCode
--------- ------------ ---------- ---------- ---------- ---------- ------------------- ------------------- ---------- ---------- ---------- -------- ---------- --------------- --------
   a72094 6908911      nf-crossm+       main    TIMEOUT   00:15:00 2019-10-30T11:56:19 2019-10-30T12:11:25   00:15:06                              1          1         stage22      0:0
          6908911.bat+      batch             CANCELLED            2019-10-30T11:56:19 2019-10-30T12:11:56   00:15:37    110372K    762812K        1          1         stage22      0:9
```
Exit code seems to be 9, could this be the problem?

.command.log
```
(base) [a72094@stage1 fd54ada11677c8bce799a816150847]$ less .command.log
ESC[33mWARNING: Not mounting requested bind point (already mounted in container): /gpfs/hpc/home/a72094
ESC[0m@ 2019-10-30 09:56:22: Read chain_file:  GRCh37_to_GRCh38.chain
@ 2019-10-30 09:56:22: Creating index for Homo_sapiens.GRCh38.dna.primary_assembly.fa
@ 2019-10-30 09:56:58: Updating contig field ...
slurmstepd: error: *** JOB 6908911 ON stage22 CANCELLED AT 2019-10-30T12:11:25 DUE TO TIME LIMIT ***
```
Log file clearly states that the job was killed due to exceeding time limit.

Another example where the job exceeds memory limit:

.command.log
```
(base) [a72094@stage1 2f47daeba7010d88c7eba0d2da8c1c]$ less .command.log
ESC[33mWARNING: Not mounting requested bind point (already mounted in container): /gpfs/hpc/home/a72094
ESC[0mslurmstepd: error: Job 6926754 exceeded memory limit (26496 > 10240), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 6926754 ON stage17 CANCELLED AT 2019-10-31T11:56:40 ***
slurmstepd: error: Job 6926754 exceeded memory limit (21916 > 10240), being killed
```

Slurm output:
```
(base) [a72094@stage1 2f47daeba7010d88c7eba0d2da8c1c]$ sacct -j 6926754 --format=User,JobID,Jobname,partition,state,time,start,end,elapsed,MaxRss,MaxVMSize,nnodes,ncpus,nodelist,ExitCode
     User        JobID    JobName  Partition      State  Timelimit               Start                 End    Elapsed     MaxRSS  MaxVMSize   NNodes      NCPUS        NodeList ExitCode
--------- ------------ ---------- ---------- ---------- ---------- ------------------- ------------------- ---------- ---------- ---------- -------- ---------- --------------- --------
   a72094 6926754      nf-crossm+       main CANCELLED+   00:15:00 2019-10-31T11:56:10 2019-10-31T11:56:40   00:00:30                              1          1         stage17      0:0
          6926754.bat+      batch             CANCELLED            2019-10-31T11:56:10 2019-10-31T11:57:11   00:01:01     26496K    766444K        1          1         stage17      0:9
```

### Environment 

* Nextflow version: 19.07.0 
* Java version: 1.8.0_40
* Operating system: Linux
* Slurm version: slurm 17.11.13-2

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Nextflow reads the exit status from the file `.exitcode` in the task work directory. Does this file exist? Likely Slurm kills the job abruptly (kill -9), and there's no way handle this event.

**Comment by kauralasoo** [comment]
Thanks, Paolo!

I checked and there is no `.exitcode` file in the the task work directory. Is this consistent with `kill -9` signal form Slurm? What's interesting is that this feature used to work earlier. Could it be that there has been a change in Slurm configuration?

**Comment by kauralasoo** [comment]
From old log files I managed to figure out that I was previously using Nextflow version 18.10.1 before upgrading to version 19.07.0. I reran the workflow with `NXF_VER=18.10.1` environmental variable set and now everything works fine. The `.exitcode` file gets created and it contains the value 143. If I run the same workflow with nextflow version 19.07.0 then there is no `.exitcode` file in the task work directory and the workflow fails as described in the initial post.

As a workaround, I can keep using the nextflow version 18.10.1 for the time being.

**Comment by pditommaso** [comment]
Could you provide a `.command.run` created by the version `18.10.1` and the one created instead by the `19.07.0`?

**Comment by kauralasoo** [comment]
Sure! Here they are:
[command.run.19.07.0.txt](https://github.com/nextflow-io/nextflow/files/3809498/command.run.19.07.0.txt)
[command.run.18.10.1.txt](https://github.com/nextflow-io/nextflow/files/3809500/command.run.18.10.1.txt)

**Comment by pditommaso** [comment]
Related to #1561. Closing in favour of the latter.
