### ISSUE TITLE
Module loads are corrupted by export PATH

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1355]
## Bug report 

When I try to load modules via the `module` directive, they get corrupted if I modify `PATH` in my nextflow config because the `.command.run` script applys the `env` scope after applying the module directives.

### Expected behavior and actual behavior

Nextflow should apply the `env` block before the module directives so that the module directives don't get overwritten or corrupted.

### Steps to reproduce the problem

I have this defined in my config:
```
// PWD in this case is /home/btsheal/tesseract
env {
    PATH = "${PATH}:${PWD}/bin"
}
```

And then I load a module via nextflow:
```
process foo {
    module = "KINC/v1"
}
```

Which generates this code in `.command.run`:
```
    set +u
    nxf_module_load KINC v1
    set -u

    export PATH="/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/default/bin:/home/btsheal/tesseract/bin"
```

Note that `PATH` contains the expansion specified by the `env` block but does not contain the paths that would have been appended by the KINC/v1 module. In other words, Nextflow has overwritten it's own module load. It seems to me that the solution would be to apply the `env` block first and then load modules:
```
    export PATH="/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/default/bin:/home/btsheal/tesseract/bin"

    set +u
    nxf_module_load KINC v1
    set -u
```

### Program output 

The task fails because it can't find the `kinc` binary in the `PATH`.

### Environment 

* Nextflow version: 20.07.1
* Java version: 1.8.0
* Operating system: RHEL Linux, PBS

**Comment by bentsherman** [comment]
I think the code that generates this part of the run script is here:
https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy#L237

and here:
https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L1796

and the actual rendering happens here:
https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/util/MustacheTemplateEngine.groovy#L55

It's unclear where `template` and `environment` are coming from, but it seems like the template needs to be modified so that the bash environment is inserted before the modules are loaded.

Not really familiar with this code base but I'm trying to make it easier for a developer to find what I'm talking about. This issue can be really annoying because it essentially renders the module directives ineffective.

**Comment by DaGaMs** [comment]
+1 on that. In my case, I have an `env` scope in my `nextflow.config` file that amends `$PATH`:

```bash
// Default environment variables for all scripts
env {
	PATH='$PATH:/users/bschuster/octopus/bin'
}
```

and I use `module` in my process definitions. The result is that `$PATH` is overwritten after module inclusion, as described above.

**Comment by DaGaMs** [comment]
I think the following code is the issue here:

https://github.com/nextflow-io/nextflow/blob/4812080340ccdfffccce49e1a77af1800c92a06c/modules/nextflow/src/main/resources/nextflow/executor/command-run.txt#L109-L115

But I'm not sure if it's safe to re-arrange the order of `{{module_load}}` and `{{task_env}}` - this might have side-effects that I can't predict. @pditommaso would need to weigh in here?

**Comment by bentsherman** [comment]
bump

**Comment by bentsherman** [comment]
I think moving `{{task_env}}` before the `set +u/-u` block (before line 109) would do the trick. I do not foresee any issues from this, in fact if anything I think the user would expect the environment variables to be set before any of those three commands. Thoughts @pditommaso ? This seems like a simply enough change.

**Comment by pditommaso** [comment]
Are you defining the PATH in the nextflow config file? how?

**Comment by DaGaMs** [comment]
in my case I have a section

```groovy
env {
	PATH="\$PATH:$HOME/bin:$PWD/bin:$PWD/modules/bin"
}
```

**Comment by pditommaso** [comment]
I'm not understanding why the PATH gets expanded in the top example

**Comment by bentsherman** [comment]
@pditommaso In my case, the PATH expansion comes from my .bashrc. In my .bashrc I loaded modules which modify the PATH. Its seems nextflow passes the environment created by my .bashrc to the task, which is fine. But it does so after applying the module directives which means the `nxf_module_load` commands get overwritten.

**Comment by bentsherman** [comment]
@pditommaso Actually I took a closer look and it turns out the root cause in my case was not my .bashrc but the same as @DaGaMs. I also was modifying PATH in my env scope and that is what overwrites the module load. I have updated my original post with this information. The solution is the same as far as I can tell.

**Comment by pditommaso** [comment]
Using this config (w/o modules)

```
env {
    PATH = "\$PATH:$PWD/bin"
}
```

I've got this the .command.run 

```
    export PATH="$PATH:/Users/pditommaso/Projects/nextflow/bin"
```

Would not this solve your problem?

**Comment by bentsherman** [comment]
That would work, however I would argue that it is a subtle detail that most users will probably not realize. Users will not know whether this `env` block gets applied before or after `module` directives, or that one could overwrite the other, so they will likely not think to do this and they will be confused like I was when their modules don't load correctly.

Therefore I still think the .command.run template should be updated as we suggested, or at least add a note to the documentation on the `env` scope, so that this issue is not repeated in the future.

**Comment by pditommaso** [comment]
I'm resisting to alter the en order because it could have unpredictable side effects on existing pipelines. 

+1 to better document that.

**Comment by bentsherman** [comment]
Sounds good to me.

**Comment by pditommaso** [comment]
need to add a tip in the document to cover this corner case
