### ISSUE TITLE
Two documentation suggestions

### ISSUE THREAD

**Issue by wwood** [nextflow-io/nextflow#1356]
Hi. I just finished working out why nextflow wasn't working with the PBS pro setup I have access to. Tasks weren't being detected as unfinished (i.e. `Process X terminated for an unknown reason -- Likely it has been terminated by the external system`) because I had set the queue to `workq`, which is where all jobs are routed through. The actual jobs are not run on this queue, so when nextflow does the querying with `qstat -f {queuename}` nothing was returned, so nextflow incorrectly deduced that the job was finished (I was able to workaround simply by not specifying a queue). I think it might be helpful to state in the documentation that the queue is not just for submission, but also for polling. I assume there is some reason for specifying the queue there, for other systems?

It took me some time to work that out - in the end I resorted to reading the nextflow code and guessing, because the default output did not detail the commands that were being run. More generally, it wasn't obvious to me how nextflow logging could be turned on. Trying to work out that is hard to google because nextflow logs using means something else. So, would it be possible to give some documentation on how to configure nextflow to output its logging info? I imagine that might be helpful for resolving issues here on GitHub also.

Thanks, ben

**Comment by jlboat** [comment]
I'm curious if this solution completely resolved your error. I had a similar problem, but even after removing the queue designation, it looks like I had the supplemental issue that my jobs were being preempted by other higher-priority jobs #1367

**Comment by wwood** [comment]
Hi, yes it did resolve my error, though I made a number of other changes too to ultimately get my pipeline working (like bugs in my scripts). I wonder if your issue might also be resolved by removing the `{quename}`, but I think your error is rather different, I'm afraid.

**Comment by jlboat** [comment]
Gotcha, thanks for the feedback.
