### ISSUE TITLE
channel of collected channels causes undefined behavior

### ISSUE THREAD

**Issue by esrice** [nextflow-io/nextflow#1357]
### Expected behavior and actual behavior

I'm trying to collect the outputs of two channels and then make a new channel that emits the collected output of the first, and then the collected output of the second. The results are not always the same.

### Steps to reproduce the problem

Here is a toy example:

```
Channel.fromPath('a.*.txt').set { a }
Channel.fromPath('b.*.txt').set { b }

Channel.of(
    tuple('a', a.collect()),
    tuple('b', b.collect())
).set { both }

both.view { "$it" }
```

### Program output 

```
esrbhb@login nf_test $ nextflow run test.nf
N E X T F L O W  ~  version 19.10.0
Launching `test.nf` [intergalactic_heisenberg] - revision: ba1ec57e2e
[a, DataflowVariable(value=null)]
[b, DataflowVariable(value=null)]
esrbhb@login nf_test $ nextflow run test.nf
N E X T F L O W  ~  version 19.10.0
Launching `test.nf` [wise_meitner] - revision: ba1ec57e2e
[a, DataflowVariable(value=[/storage/htc/warrenlab/esrbhb/astyanax/nf_test/a.1.txt, /storage/htc/warrenlab/esrbhb/astyanax/nf_test/a.2.txt])]
[b, DataflowVariable(value=[/storage/htc/warrenlab/esrbhb/astyanax/nf_test/b.1.txt, /storage/htc/warrenlab/esrbhb/astyanax/nf_test/b.2.txt])]
```

The second is what I expect/want. Sometimes one of them is null and one of them is correct.

I've been able to get around this by doing
```
a.map { tuple('a', it) }.set { a_tuples }
b.map { tuple('b', it) }.set { b_tuples }
a_tuples.concat(b_tuples).groupTuple().set { both }
```
but this seems rather convoluted to me.

### Environment 

* Nextflow version: 19.10.10 build 5170
* Java version: openjdk 1.8.0_222
* Operating system: Linux

### Additional context

Thanks a bunch!

**Comment by pditommaso** [comment]
That's not expected to workflow `Channel.of/from` cannot take another channel as input.
