### ISSUE TITLE
tutorial.nf output HELLO WORLD! on 1 line (not splitted)

### ISSUE THREAD

**Issue by amayer21** [nextflow-io/nextflow#1366]
## Bug report 

I know this isn't a major issue, but I'm new to Nextflow, I'm trying the tutorial pipeline from https://www.nextflow.io/docs/latest/getstarted.html and can't reproduce the expected output, so I would like to understand if I'm doing something wrong or if something has been changed in that pipeline

### Expected behavior and actual behavior

Expected to print the 2 strings 'HELLO ' and 'WORLD!' on 2 separated lines. Actually printed one line with both ('HELLO WORLD!')

### Steps to reproduce the problem

I've followed the step explained in the tutorial, i.e.
(1) creating the `tutorial.nf` file with 
```
#!/usr/bin/env nextflow

params.str = 'Hello world!'

process splitLetters {

    output:
    file 'chunk_*' into letters

    """
    printf '${params.str}' | split -b 6 - chunk_
    """
}


process convertToUpper {

    input:
    file x from letters.collect()

    output:
    stdout result

    """
    cat $x | tr '[a-z]' '[A-Z]'
    """
}

result.view { it.trim() }
```

then I ran it with
```
nextflow run tutorial.nf
```

### Program output 

Expected output:
```
N E X T F L O W  ~  version 19.04.0
executor >  local (3)
[69/c8ea4a] process > splitLetters   [100%] 1 of 1 ✔
[84/c8b7f1] process > convertToUpper [100%] 2 of 2 ✔
HELLO
WORLD!
```

Actual output:
```
N E X T F L O W  ~  version 19.07.0
Launching `tutorial.nf` [awesome_sinoussi] - revision: f00f869a5c
executor >  local (2)
[ff/3f4151] process > splitLetters   [100%] 1 of 1 ✔
[b6/4d7ace] process > convertToUpper [100%] 1 of 1 ✔
HELLO WORLD!
```
The first step is working fine: I have the 2 files in `work/ff/3f415121ab76b8273450f5b1773819/`, one with 'Hello ', the other one with 'world!'. It looks like the second step is concatenating the 2 files ????

Log file: [nextflow.log](https://github.com/nextflow-io/nextflow/files/3825456/nextflow.log)

### Environment 

* Nextflow version: 19.07.0
* Java version: 8 (openjdk version "1.8.0_111")
* Operating system: Linux (Scientific Linux release 7.2 (Nitrogen))

### Additional context

Thank you very much for your help!
All the best,
Alice

**Comment by pditommaso** [comment]
Attach your script here! 😉

**Comment by amayer21** [comment]
Hi Paolo, 
Sorry I didn't attached the script but I copied it in the "Steps to reproduce the problem" section... Here is the file: [tutorial.nf.txt](https://github.com/nextflow-io/nextflow/files/3839981/tutorial.nf.txt) 
(Github doesn't accept a `.nf` file so I added `.txt` extension that need removing before to use it)
Thank you very much

**Comment by pditommaso** [comment]
You are definitely right. There's a mistake in the documentation, apology 🤦‍♂. The correct version should use `.flatten()` instead of `.collect()`. See the usage here 606a0a3.

**Comment by amayer21** [comment]
It works :-) And got me to read more about nextflow operators :-)
Thank you very much!
All the best,
Alice
