### ISSUE TITLE
PBS Pro : Job Preemption

### ISSUE THREAD

**Issue by jlboat** [nextflow-io/nextflow#1367]
### Expected behavior and actual behavior

Our cluster (running PBS Pro) allows individuals or groups to purchase nodes for priority use. When the nodes are not being used by owners, others are allowed to use those resources. When the owner decides that they'd like to run a job, non-owner jobs get preempted and requeued to different nodes, whereby Nextflow loses track of the job(s) [terminates with error exit status (143)] and the job(s) continue until completion.

### Steps to reproduce the problem

This is likely an architecture-specific issue. So, I'm not sure how to provide a reproducible test case.

### Program output 

tracejob 7537771 -n 2

Job: 7537771.pbs02
11/06/2019 13:40:14  S    Job Queued at request of jboatw2@stackmaster02.palmetto.clemson.edu, owner = jboatw2@stackmaster02.palmetto.clemson.edu, job name = nf-cleanReads_1, queue = c1_single
11/06/2019 13:40:15  S    Job Modified at request of Scheduler@pbs02.palmetto.clemson.edu
11/06/2019 14:52:21  S    Job Run at request of Scheduler@pbs02.palmetto.clemson.edu on exec_vnode (node0027:ncpus=6:mem=12582912kb:ngpus=0:nphis=0)
11/06/2019 14:52:21  L    Job run
11/06/2019 14:54:53  S    Job Rerun at request of Scheduler@pbs02.palmetto.clemson.edu
11/06/2019 14:54:53  L    Simulation: preempting job
11/06/2019 14:55:00  S    Obit received momhop:1 serverhop:1 state:4 substate:60
11/06/2019 14:55:01  L    Job preempted by requeuing
11/06/2019 14:55:02  S    Job Modified at request of Scheduler@pbs02.palmetto.clemson.edu
11/06/2019 14:55:20  L    Node is in an ineligible state: down
11/06/2019 14:55:23  L    Considering job to run
11/06/2019 14:55:23  S    Job Run at request of Scheduler@pbs02.palmetto.clemson.edu on exec_vnode (node0027:ncpus=6:mem=12582912kb:ngpus=0:nphis=0)
11/06/2019 14:55:23  S    Job Modified at request of Scheduler@pbs02.palmetto.clemson.edu
11/06/2019 14:55:23  L    Job run
11/06/2019 15:08:11  S    Obit received momhop:2 serverhop:2 state:4 substate:42
11/06/2019 15:08:11  S    Exit_status=0 resources_used.cpupercent=578 resources_used.cput=01:03:34 resources_used.mem=2015296kb resources_used.ncpus=6 resources_used.vmem=3879012kb
                          resources_used.walltime=00:12:48

Nextflow log attached
[nextflow.log](https://github.com/nextflow-io/nextflow/files/3831754/nextflow.log)

### Environment 

* Nextflow version: version 19.10.0 build 5170
* Java version: java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
* Operating system: Oracle Linux Server 7.6

**Comment by bentsherman** [comment]
Sharing some notes here as I have had the same issue from time to time with the PBS cluster at my university.

Preempted jobs are terminated with exit code 143. Unfortunately, 143 is also used when a job exceeds its resource allocation (walltime, cpu percent, memory, etc), so I don't know if there is a way to tell if a job was preempted.

If you let the restarted job run to completion, you can actually recover it with a resumed run. The outputs, command logs, command trace, everything is there. But there is some weirdness:
- the command log includes output from the original job and restarted job
- I think the command trace is somewhat distorted, i.e. `realtime` includes the runtime of both attempts, but I can't confirm
- the exit code of the task is still 143

Here is a potential solution from the `qsub` manpages:
```
       -r <y|n>
               Declares whether the job is rerunnable.  Sets job's Rerunable attribute to the argument value.  Does not affect how the job is  handled
               in the case where the job was unable to begin execution.
```

Perhaps Nextflow should use `-r n` with PBS. That way job preemptions would be handled properly by Nextflow's error strategy. Alternatively, we could add a tip to the documentation about recovering preempted tasks via resume. But I think the latter option is largely undefined behavior. Would love to hear your thoughts @pditommaso

**Comment by pditommaso** [comment]
Think the best way to handle this is to consider it as a failure and let NF to re-execute it using `errorStrategy = 'retry'`

**Comment by bentsherman** [comment]
No, I don't see any issues with making jobs not rerunnable. In my experience it is rare for a job to be preempted more than once.
