### ISSUE TITLE
Singularity execution fails when image path contains a blank char

### ISSUE THREAD

**Issue by marcodelapierre** [nextflow-io/nextflow#1368]
disclaimer: I can't change the pathname as it's fixed in the system...otherwise I would have !! :-)

**Comment by pditommaso** [comment]
I'm unable to replicate this problem. Can you provide a test case?

**Comment by marcodelapierre** [comment]
My bad Paolo, did not provide full specs on the case, here we go.
The key extra requirement is using singularity containers. 

Example:

script "main.nf":
`
in_ch = Channel.fromPath('input')
  
process io {
publishDir '.'

input:
file('input') from in_ch

output:
file('output') into out_ch

script:
'''
cp input output
echo 'world' >>output
'''
}
`

config file "nextflow.config":
`
process.container = 'ubuntu:18.04'

singularity.enabled = true
singularity.autoMounts = true
`

input file "input":
`
hello
`

Now let's create a directory with space and dash in the name, and then put those 3 files in there:
`
> mkdir 'why - space' && cd 'why - space'
> ls
input  main.nf  nextflow.config
`


This will succeed (no singularity):
`
> touch empty.config
> nextflow -C empty.config run main.nf
N E X T F L O W  ~  version 19.10.0
Launching `io.nf` [desperate_brenner] - revision: 6b3e52723e
[99/d6a064] Submitted process > io (1)
`
`
> cat output
hello
world
`

But this will fail
`
> nextflow run main.nf
N E X T F L O W  ~  version 19.10.0
Launching `main.nf` [exotic_goldberg] - revision: e2a36be8af
[e5/cf0530] Submitted process > io (1)
Error executing process > 'io (1)'

Caused by:
  Process `io (1)` terminated with an error exit status (255)

Command executed:

  cp input output
  echo 'world' >>output

Command exit status:
  255

Command output:
  (empty)

Command error:
  FATAL:   failed to retrieve path for /group/pawsey0001/mdelapierre/devel/sgl-space/why: lstat /group/pawsey0001/mdelapierre/devel/sgl-space/why: no such file or directory

Work dir:
  /group/pawsey0001/mdelapierre/devel/sgl-space/why - space/work/e5/cf0530c08d7d8923a5188247905363

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

`

Best, Marco

**Comment by pditommaso** [comment]
Ah! raising the bar! :)

**Comment by pditommaso** [comment]
Found. It was missing to escape blanks in the image path.
