### ISSUE TITLE
Reject runs with unrecognised command-line parameters

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#1375]
##  Usage scenario 

When launching a nextflow run, the config is loaded by first parsing the config files and then the command-line arguments. This is great, apart from the fact that command-line typos are very difficult to spot. If the user does `--foo-bar` instead of `--foo_bar` then the pipeline will run without any problem and use the default `params.food_bar` value from the config file. Another common scenario is to confuse core nextflow options and use two hyphens (eg. `--resume`).

It would be ideal if nextflow could recognise parameters supplied on the command line which do not match any listed in the config files. It could then exit with an error before launching the run.

## Suggest implementation 

Originally I was hoping to implement this in @nf-core pipelines by using the `parameters.settings.json` parameter description approach. It's pretty easy to recognise params which shouldn't be there and to throw an error. However, the problem with this is that the user may have custom config files which need various custom parameters to function. The main pipeline code won't know about these parameters and would block execution if they are specified.

The only method that I can think of to handle this solution is to modify core nextflow behaviour, as it should be possible to add this check in between the config parsing and command line parsing stages.

There aren't any downsides that I can think of, except maybe if params are used within pipelines _without_ having a default specified within the config. But nextflow has been throwing warnings about this behaviour for ages now, so it shouldn't be happening in any pipelines... right? 😉

**Comment by pditommaso** [comment]
Basically the idea is to use the `parameters.settings.json` to validate the command line options, isn't it? being so makes a lot of sense. is there any document describing the latest version of the json file syntax?

**Comment by ewels** [comment]
Yes, but..

> However, the problem with this is that the user may have custom config files which need various custom parameters to function. The main pipeline code won't know about these parameters and would block execution if they are specified.

**Comment by pditommaso** [comment]
How do you define a custom parameter? One that is not defined in the `parameters.settings.json` ?

**Comment by ewels** [comment]
Yes, that is in a config file created by the user and that is not know about by the pipeline. For example `params.clusterOptions` in the [uppmax cluster config](https://github.com/nf-core/configs/blob/bc9ecf50acc8f8ca1b8a9e92229f0666223ec2f5/conf/uppmax.config#L14).

Not a great example, but I could imagine users writing configs that have flags to turn stuff on and off. The pipeline params definition cannot know about these if they’re separate from the pipeline.

**Comment by pditommaso** [comment]
But why should not be included in the `parameters.settings.json` (provided nextflow would be able to parse that file directly)?

**Comment by pditommaso** [comment]
My guess is that your SGE cluster is not using `bash` as default shell. 

https://stackoverflow.com/questions/2020957/how-to-change-the-default-shell-for-the-sun-grid-engine

**Comment by pditommaso** [comment]
Oops, wrong issue sorry

**Comment by ewels** [comment]
Because the parameters file is bundled with the pipeline for all users. The above example would typically be sat in someone’s home directory or provided with `-c`. If such parameters are _user specific_ then they can’t be specified in the bundled `parameters.settings.json` file.

**Comment by ewels** [comment]
This feature would also help people running pipelines that don’t have a `parameters.settings.json` file.

**Comment by pditommaso** [comment]
To summarise you have params that are defined in the user-specific config files and you would like to detect command-line options that do not match the ones in the define in the config. 

The problem of this approach is that we config is not aware of the params defined in the pipeline script, therefore the validation would be incomplete.

Maybe with a heavy reimplementation of config parsing and validation, it could be possible, need to check.

**Comment by pditommaso** [comment]
Should be said that params defined as in [this line](https://github.com/nf-core/configs/blob/bc9ecf50acc8f8ca1b8a9e92229f0666223ec2f5/conf/uppmax.config#L14) ie with a closure it's *very* hard to be detected because that basically defined a piece of code instead of a data structure. Low chances to solve the problem with this approach.

**Comment by ewels** [comment]
Aha, I had forgotten that `main.nf` wasn’t parsed ahead of time. I guess such a refactoring would also fix https://github.com/nextflow-io/nextflow/issues/876 and https://github.com/nextflow-io/nextflow/issues/889 🙃

The closure thing shouldn’t be a problem, as they’re on the right hand side of the `=` sign. I only care about stuff on the left. If such a params is only on the right nextflow should already throw a warning, right?

**Comment by ewels** [comment]
@pditommaso - is this issue affected by #889 being resolved?
