### ISSUE TITLE
DSL-2 modules include from external repository

### ISSUE THREAD

**Issue by piotr-faba-ardigen** [nextflow-io/nextflow#1376]
## New feature

I wonder what do you think about having an ability to include a repository that contains modules in DSL-2. I see this as ability to abstract really general modules that can be shared between multiple pipelines. What I'm not sure about is how often this could actually become useful (how often you come across general modules).

## Usage scenario 

My example is based on modules example based on rnaseq demo pipeline. It's on [modules branch](https://github.com/nextflow-io/rnaseq-nf/tree/modules).

The modification is to use in main.nf:
```
// import modules
include 'https://github.com/nextflow-io/rnaseq-nf/blob/modules/modules/rnaseq' params(params)
```
instead of:
```
// import modules
include 'modules/rnaseq' params(params)
```

Currently this generates an error:
```
Module path must start with / or ./ prefix -- Offending module: https://github.com/nextflow-io/rnaseq-nf/blob/modules/modules/rnaseq
```

## Suggest implementation 

I don't have idea for implementing this yet. Let's first establish if this is a valid use case.

**Comment by pditommaso** [comment]
Don't think we are going to have support for remote modules soon. Remote resources are volatile over time and the resulting pipeline would be not reproducible any more. 

The best practice consists including such depending to the main project as git module or git subtree dependencies.
