### ISSUE TITLE
Module directive not work when using with Local executor

### ISSUE THREAD

**Issue by sinonkt** [nextflow-io/nextflow#1377]
## Bug report
not sure is this unexpected behaviour or not. 
when using `module` directive whether inside process definition or in `nextflow.config` while executor is `local`, module will not loaded as expected. but if executor is other everything work well.

### Expected behavior and actual behavior
`main.nf`
``` 
process Test {
    script:
        """
        java -jar \$EBROOTGATK/GenomeAnalysisTK.jar --help
        """
}
```
`nextflow.config` that work when use executor as `sge`
```
profiles {
        cloudnative {
            process {
                executor = 'sge'
                queue = 'biotec.q'
                clusterOptions = '-S /bin/bash'
                penv = 'orte'
                withName: Test {
                    module = 'GATK/3.8-1-Java-1.8.0_144'
                }
            }
        }
}
```
`nextflow.config` that doesn't work
```
profiles {
        cloudnative {
            process {
                executor = 'local'
                withName: Test {
                    module = 'GATK/3.8-1-Java-1.8.0_144'
                }
            }
        }
}
```
this one should work as well, as i run on same environment that have all modules available

### Steps to reproduce the problem
use `module` directive with any pipeline and use `executor` as `local`

### Program output 
```
Error executing process > 'Test'

Caused by:
  Process `Test` terminated with an error exit status (1)

Command executed:

  echo 2
         java -jar $EBROOTGATK/GenomeAnalysisTK.jar --help

Command exit status:
  1

Command output:
  2

Command error:
  .command.sh: line 3: EBROOTGATK: unbound variable

Work dir:
  /colossus/home/krittin/test/work/16/78044c36d3712ace7b52506c5a22b7

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Environment 

* Nextflow version: Nextflow/19.07.0
* Java version: Java/1.8.0_201
* Operating system: Linux [Centos 7.5]

**Comment by pditommaso** [comment]
Does the generated `.command.run` contains the expected `module load` command?

**Comment by sinonkt** [comment]
sorry for late reply, it has an expected module as following.
```
nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR1 USR2

    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /colossus/home/krittin/test/work/16/78044c36d3712ace7b52506c5a22b7/.command.begin
    set +u
    nxf_module_load GATK 3.8-1-Java-1.8.0_144
    set -u
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}
```
but After i use Nextflow/19.10.0, I can't reproduce this issue. it works well on many setting.
I'll let you know if it happens again.

Another question please. Is there any limitations I should be aware of on using local executor as i seen the docs stated that it should be use only while developing pipeline script. Can i use it as production one? Thank you in advance!
