### ISSUE TITLE
error in sge jobs_scripts

### ISSUE THREAD

**Issue by cmatKhan** [nextflow-io/nextflow#1378]
### Expected behavior and actual behavior

On a cluster with the sge executor using the nf-core rnaseq pipeline, I am getting the following error in the .command.log:

```
$ cat .command.log
/var/spool/sge/wynton/msg-iogpu13/job_scripts/8948872: line 23: syntax error near unexpected token `<'
```
This is the function which contains line 23 in the .command.run:

```
nxf_tree() {
    local pid=$1

    declare -a ALL_CHILDREN
    while read P PP;do
        ALL_CHILDREN[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    pstat() {
        local x_pid=$1
        local STATUS=$(2> /dev/null < /proc/$1/status egrep 'Vm|ctxt')

        if [ $? = 0 ]; then
        local  x_vsz=$(echo "$STATUS" | grep VmSize | awk '{print $2}' || echo -n '0')
        local  x_rss=$(echo "$STATUS" | grep VmRSS | awk '{print $2}' || echo -n '0')
        local x_peak=$(echo "$STATUS" | egrep 'VmPeak|VmHWM' | sed 's/^.*:\s*//' | sed 's/[\sa-zA-Z]*$//' | tr '\n' ' ' || echo -n '0 0')
        local x_pmem=$(awk -v rss=$x_rss -v mem_tot=$mem_tot 'BEGIN {printf "%.0f", rss/mem_tot*100*10}' || echo -n '0')
        local vol_ctxt=$(echo "$STATUS" | grep '\bvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        local inv_ctxt=$(echo "$STATUS" | grep '\bnonvoluntary_ctxt_switches' | awk '{print $2}' || echo -n '0')
        cpu_stat[x_pid]="$x_pid $x_pmem $x_vsz $x_rss $x_peak $vol_ctxt $inv_ctxt"
        fi
    }

    pwalk() {
        pstat $1
        for i in ${ALL_CHILDREN[$1]:=}; do pwalk $i; done
    }

    pwalk $1
}
```

line 23 itself is:

```
done < <(ps -e -o pid= -o ppid=)
```
which is the 6th line in the larger code above.

### Steps to reproduce the problem

this is the command I am using:

```
nextflow run ~/rnaseq-nextflow-dev \
             -c ~/rnaseq-nextflow-dev/conf/ucsf_wynton.config \
             -with-singularity ~/nf-core-rnaseq-dev.img \
             --reads "/data/fastq/*R{1,2}*.fastq.gz" \
             -resume \
             --genome ncbi-ise6 \
             --fcGroupFeatures 'gene' \
             --saveReference \
             --outdir ~/ise6_nextflow_output/
```
my configuration specifies the processor:

```
process {
  executor = 'sge'
  penv = 'smp'
  errorStrategy = { task.attempt < 2 ? 'retry' : 'finish' }
  scratch = true
}
```

### Program output 

```
~]$ cat work/6c/563d15d2d93b7aaeb9db5eba8f0475/.command.log
/var/spool/sge/wynton/cc-idgpu2/job_scripts/8949951: line 23: syntax error near unexpected token `<'
```

### Environment 

* Nextflow version: 19.07.0 build 5106
* Java version: openJDK 1.8.0_232
* Operating system: linux. CentOS with SGE job scheduler

### Additional context

(Add any other context about the problem here)

**Comment by cmatKhan** [comment]
after consulting the nf-core slack, I was directed here

https://stackoverflow.com/questions/36144610/syntax-error-near-unexpected-token/36147054#36147054

**Comment by pditommaso** [comment]
Is this happening only with the pipeline or any job submitted by NF?

**Comment by cmatKhan** [comment]
I haven't been able to re-create the error without the pipeline, but I also haven't written anything in NF of any complexity to test it. I will this weekend, and update if I can re-create the error.

**Comment by pditommaso** [comment]
My guess is that your SGE cluster is not using `bash` as default shell. 

https://stackoverflow.com/questions/2020957/how-to-change-the-default-shell-for-the-sun-grid-engine

**Comment by cmatKhan** [comment]
Yes -- @pditommaso , this worked!

sorry...I should have figured this out on my own. Thank you for your help -- much appreciated.

**Comment by pditommaso** [comment]
Nice!
