### ISSUE TITLE
publishDir enabled: false creates empty directory

### ISSUE THREAD

**Issue by gsainsbury86** [nextflow-io/nextflow#1381]
## Bug report 

Creating a process with a publishDir enabled set to false will create the output directory anyway.

### Expected behavior and actual behavior

* Expected behaviour would be that enabled: false would not create any files or directories.
* Actual behaviour is that an empty directory of that name is created.

### Steps to reproduce the problem

```
process publishDirBug {
	publishDir 'out', enabled: false
	
	output:
	file("a.txt")
	
	script:
	"""
	touch a.txt
	"""

}

```

### Program output 

Execution does not fail.

### Environment 

* Nextflow version: nextflow version 19.10.0.5170
* Java version: java version "10.0.2" 2018-07-17
* Operating system: macOS 10.15.1 (19B88)

### Additional context

It's possible this is a design choice, rather than a bug. My use case is in image processing. I have an optional output of intermediary images that I sometimes would like to produce. If I have one directory per image, there are potentially thousands of empty directories created.

**Comment by haqle314** [comment]
From what I can gather, the `enabled` param is checked too late. Simply checking
`enabled` earlier like this should do the trick. Is there anything that I
missed, @pditommaso?

```groovy
// PublishDir.groovy:181
void apply( List<Path> files, Path sourceDir ) {
    // Check here instead of inside void apply(Path source, boolean inProcess)
    if( !files || !enabled )
        return
    this.sourceDir = sourceDir
    this.sourceFileSystem = sourceDir ? sourceDir.fileSystem : null
    apply0(files)
}
```

**Comment by pditommaso** [comment]
Well spotted, yes the patch suggested should do the trick.
