### ISSUE TITLE
Segmentation Fault with large input channel

### ISSUE THREAD

**Issue by gsainsbury86** [nextflow-io/nextflow#1385]
### Expected behavior and actual behavior

When an input channel consists of a large number of files (~5000 or more), a segmentation fault occurs.

I have opened a discussion on stackoverflow here: https://stackoverflow.com/questions/58948617/segmentation-fault-core-dumped-in-simple-but-long-bash-function

### Steps to reproduce the problem

This minimal example will re-produce the problem for me in multiple environments. Essentially, it writes 5000 empty files then tries to concatenate them. I believe the error occurs in bash when trying to define/call a function over a particular size. When I look at the `.command.run` script that Nextflow generates, it will error when it gets to the large nxf_stage function which appears to be 5000 `rm -f` commands, followed by 5000 `ln -s` commands.

```
process create_files {

        output:
                file "empty_file*.txt" into files_ch
        script:
        """
                for count in {0..5000}; do touch empty_file_\$count.txt; done
        """
}

process merge_files{
        input:
                file in_file from files_ch.collect()
        output:
                file "output.txt"
        script:
        """
                cat empty_file*.txt > output.txt
        """
}
```

### Program output 

This is the Nextlow output.

```
Error executing process > 'merge_files'

Caused by:
  Process `merge_files` terminated with an error exit status (139)

Command executed:

  cat empty_file*.txt > output.txt

Command exit status:
  139

Command output:
  (empty)

Work dir:
  /Users/a1132077/development/tpa-scripts/work/0d/17761b14d8dc1fa8cef6d3e0d68ffc

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

When I modified the `.command.run` script to include a `set -x` as the first command, then ran with `bash -x` (per advice from stackoverflow), this is the output:

```
ubuntu@tpa-zegami:~/plantcv-pipeline$ /bin/bash -x 76k_command.run 
+ set -x
+ set -e
+ set -u
+ NXF_DEBUG=0
+ [[ 0 > 1 ]]
+ NXF_ENTRY=nxf_main
+ nxf_main
+ trap on_exit EXIT
+ trap on_term TERM INT USR1 USR2
++ dd bs=18 count=1 if=/dev/urandom
++ base64
++ tr +/ 0A
+ export NXF_BOXID=nxf-n8ZxJIZPDZERdhKLMUULqbl3
+ NXF_BOXID=nxf-n8ZxJIZPDZERdhKLMUULqbl3
+ NXF_SCRATCH=
+ [[ 0 > 0 ]]
+ touch /home/ubuntu/plantcv-pipeline/work/ec/da7ca4e909b2cc4a74ed8963cc5feb/.command.begin
+ set +u
+ set -u
+ [[ -n '' ]]
+ nxf_stage
Segmentation fault (core dumped)
```

### Environment 

* Nextflow version:       version 19.10.0 build 5170
* Java version: Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
* Operating system: macOS 10.15.1 (19B88)

### Additional context
I suspect a simple fix might be to break the `nxf_stage()` function into chunks of a limit. E.g. perhaps limiting to 1000 files at a time.

**Comment by gsainsbury86** [comment]
Duplicate of https://github.com/nextflow-io/nextflow/issues/1364

**Comment by gsainsbury86** [comment]
#

**Comment by gsainsbury86** [comment]
Duplicate of #1364

**Comment by gsainsbury86** [comment]
Successful workaround adding `beforeScript 'ulimit -Ss unlimited` to process.

**Comment by pditommaso** [comment]
Nice. Thanks for reporting this workaround.
