### ISSUE TITLE
Singularity env variables are not accessible

### ISSUE THREAD

**Issue by marcodelapierre** [nextflow-io/nextflow#1386]
Singularity allows users to define lots of behaviours using environment variables, see
https://sylabs.io/guides/3.5/user-guide/appendix.html

It would be nice if all these variables were retained at runtime when using singularity...
or at least if there were a config option to switch on this behaviour.

envWhitelist does not work in this case, at it adds an undesired prefix to the variables, SINGULARITYENV_. This is good for normal variables, but not for singularity ones that must retain the original name, e.g. SINGULARITY_BINDPATH

Current situation in .command.run: only SINGULARITYENV_TMP and SINGULARITYENV_TMPDIR
```
nxf_launch() {
    set +u; env - PATH="$PATH" SINGULARITYENV_TMP="$TMP" SINGULARITYENV_TMPDIR="$TMPDIR" singularity exec /group/pawsey0001/mdelapierre/devel/nextflow/ignite/work/singularity/ubuntu-18.04.img /bin/bash -c "cd $PWD; /bin/bash -ue /group/pawsey0001/mdelapierre/devel/nextflow/ignite/work/e0/5663f2c41af07a6118e246bafb14ae/.command.sh"
}
```

**Comment by pditommaso** [comment]
Ouch. Maybe the simplest trick would be to not prefix with `SINGULARITYENV_` singularity vars. That should do the trick.

**Comment by marcodelapierre** [comment]
Yep, sounds sensible to me, I'd say envWhitelist should not alter any variable whose name starts with "SINGULARITY".

**Comment by pditommaso** [comment]
@marcodelapierre for your review 036af4a6.

**Comment by marcodelapierre** [comment]
@pditommaso , sorry to re-open this, the behaviour is still not the expected one, i.e. env variables starting with SINGULARITYENV_ are not brought in the nxf_launch function in .command.run
