### ISSUE TITLE
Limit number of threads for non local executor

### ISSUE THREAD

**Issue by timeu** [nextflow-io/nextflow#1393]
We have many users that use Nextflow on our SLURM cluster. 
They typically start their nextflow pipelines from the login node. 
However it seems that the default behavior of nextflow is to start as many threads as there are processors available. 
Our login nodes have 76 cores and thus nextflow will spawn 76 threads. This causes huge memory consumption on the login nodes (see screenshot). Is there a way to limit the number of threads that are started globally ? 
I checked the documentation but could not find any information about this. 
![nextflow](https://user-images.githubusercontent.com/374296/69955661-7aa36a00-14fe-11ea-9182-8be0b92eda78.png)

**Comment by timeu** [comment]
Ok it seems that some of nextflow processes that consumed a lot of memory was not due to the number of threads but to an issue in the user's pipeline which we will investigate. However it would be still good if there is a config variable to restrict the number of threads that are spawned by default.

**Comment by tbugfinder** [comment]
Hi @timeu !
this might be more a JVM question than nextflow.
It's possible to add JAVA options the nextflow's JVM. So you could limit the threadstacksize or available memory.
https://gitter.im/nextflow-io/nextflow?at=588a3f6bcd69d9b15828f88b

Running nextflow itself within a container (docker, singularity) could limit the number of CPUs and memory, too.
