### ISSUE TITLE
Feature request: reproducible builds

### ISSUE THREAD

**Issue by anadon** [nextflow-io/nextflow#1395]
As per https://reproducible-builds.org/ I would like builds to be bit reproducible.  I will be creating a package in guix soon for nextflow, but it runs against a number of best practices by design.  It appears that there is no tooling for this in the project either.

**Comment by pditommaso** [comment]
>  It appears that there is no tooling for this in the project either.

What do you mean?

**Comment by anadon** [comment]
I missed some documentation:
https://docs.gradle.org/current/userguide/building_java_projects.html#sec:properties_files
https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives

I'll do some testing later to see if reproducible builds are currently a thing.  Making sure this is explicitly supported is important going forward when comparing to other tools.

**Comment by pditommaso** [comment]
NF builds are reproducible.
