### ISSUE TITLE
Feature Request: Dynamically created module include paths

### ISSUE THREAD

**Issue by aunderwo** [nextflow-io/nextflow#1396]
## New feature
Allow module include paths to be created dynamically

## Usage scenario 
Currently module include paths require a string literal.
There are occasions where a hard coded relative or absolute path may not work because the pipeline directory structure differs between set up. Being able to create the module include path dynamically would allow for this situation and give greatest flexibility. 

## Suggest implementation 
Allow the module include path to include a variable by string interpolation and/or set a module search path as a config setting or environmental variable.

**Comment by pditommaso** [comment]
> pipeline directory structure differs between set up

This is exactly what we are trying to prevent at least at this stage. Having untracked module files will quite certainly break the pipeline reproducibility. 

The current approach consist including module files using abs paths for dev purpose and including them using Git [modules](https://www.vogella.com/tutorials/GitSubmodules/article.html) or [subtrees](https://www.atlassian.com/git/tutorials/git-subtree) for sharing it. 

In the future, we may have a native module versioning system.

**Comment by pditommaso** [comment]
Closing this for now.
