### ISSUE TITLE
podman support

### ISSUE THREAD

**Issue by tbugfinder** [nextflow-io/nextflow#1397]
## New feature

Starting with RHEL7.7 / RHEL8 RedHat is providing a new set of container tools like podman, buildah and skopeo.
Podman is almost a 1:1 replacement of docker commands and even an alias docker=podman does it's job. Nevertheless it would make sense to enable nextflow for podman.

## Usage scenario 

Run containers using podman.

## Suggest implementation 

Alias or duplicate the docker commands.

**Comment by pditommaso** [comment]
I agree that would be useful, tho I think podman it's not stable enough for real usage. Contributions are welcome.

**Comment by tbugfinder** [comment]
Looking at the code base a contribution looks quite straightforward. I haven't faced Podman stability issues (yet) once setup is done.
