### ISSUE TITLE
ifNotEmpty()

### ISSUE THREAD

**Issue by ii-bioinfo-thomas** [nextflow-io/nextflow#1399]
## New feature

Analogous to `x.ifEmpty(y)` it would be helpful that there is a method `x.ifNotEmpty(y)` which emits `y` if `x` is not empty otherwise `Channel.empty()`.

For some reason following doesn't work in DSL2 for me (I guess due to different scopes). It's waiting forever but it evaluates in DSL (not tested if I could have used it in if statement in DSL):

```
nextflow.preview.dsl=2

workflow {
    x = Channel.empty()

    choice = x.toList().val.isEmpty()
    println choice
}
```

## Usage scenario 

Use processes only if a certain Channel is set. The process not necessarily needs the populated channel itself. Probably, I overlooked a similar feature...

## Suggest implementation 
```
nextflow.preview.dsl=2

workflow {

    x = Channel.empty()
    y = Channel.from('xEmpty1', 'xEmpty2')

    x \
    | ifEmpty([]) \
    | combine(y) \
    | filter{ it.size() == 2 } \
    | map{it -> it[1]} \
    | unique \
    | ifEmpty(['X was empty']) \
    | view()

    x1 = Channel.from('notEmpty', 'notEmpty2')
    y1 = Channel.from('xNotEmpty1', 'xNotEmpty2')

    x1 \
    | ifEmpty([]) \
    | combine(y1) \
    | filter{ it.size() == 2 } \
    | map{it -> it[1]} \
    | unique \
    | ifEmpty(['X1 was empty']) \
    | view()
}
```

First returns (should be actually Channel.empty()...):

```
[X was empty]
```

Second returns:

```
xNotEmpty1
xNotEmpty2
```

**Comment by pditommaso** [comment]
> Use processes only if a certain Channel is set

By definition a process is executed as many times are the elements emitted by the channel. I don't see how a special ifNotEmpty could be useful.
