### ISSUE TITLE
Ability to customize job name submitted to scheduler (e.g., SGE)

### ISSUE THREAD

**Issue by fac2003** [nextflow-io/nextflow#140]
(Copied and organized from discussion on the forum.)
When looking at the output of qstat (used to monitor the progress of SGE jobs), we see:

ubuntu@frontend001:~$ qstat

job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID 

-----------------------------------------------------------------------------------------------------------------

    379 0.75000 nf-Kallist ubuntu       r     04/02/2016 13:01:58 all.q@compute002                   1        

    380 0.58696 nf-Kallist ubuntu       r     04/02/2016 13:24:58 all.q@compute003                   1        

    381 0.58696 nf-Kallist ubuntu       r     04/02/2016 13:27:28 all.q@compute005                   1        

    382 0.58696 nf-Kallist ubuntu       r     04/02/2016 13:49:13 all.q@compute004                   1        

    383 0.58696 nf-Kallist ubuntu       r     04/02/2016 13:54:28 all.q@compute001                   1        

    384 0.58696 nf-Kallist ubuntu       qw    04/02/2016 05:19:28                                    1        

    385 0.42391 nf-Kallist ubuntu       qw    04/02/2016 05:19:43                                    1        

    386 0.42391 nf-Kallist ubuntu       qw    04/02/2016 05:19:43                                    1        

    387 0.42391 nf-Kallist ubuntu       qw    04/02/2016 05:19:43                                    1        

    388 0.41304 nf-Kallist ubuntu       qw    04/02/2016 05:19:44                                    1        

    389 0.41304 nf-Kallist ubuntu       qw    04/02/2016 05:19:44                                    1        

    390 0.25000 nf-Kallist ubuntu       qw    04/02/2016 05:19:59                                    1    

As you can see, the job name is set to a long string that starts with a constant bit: nf-Kallist. qstat shows only the beginning of the job name (first 10 chars). 

We can use qstat -j to find out the full name, for instance:

job_name:                   nf-KallistoHDF5WithTuples_(32)

When starting this process, nextflow printed:
  [sshexec] [d1/d1bc6c] Submitted process > KallistoHDF5WithTuples (32)

So I think it would be nice to set the beginning of the job name to something that is more informative when looking at a qstat output. For instance, I think it would be useful to either
1. set the name to the start of the d1/d1bc6c string.
2. set the name to start with 32|d1/d1bc6c 

Paolo, is there a simple way to configure this with nextflow, or is something that could be added? 

From Paolo:

Regarding your request, in the past we discussed about the job names to be displayed by the grid scheduler and at the end we decided to not use the process hash number because it would not be easily human readable. 

However I understand users may have different requirements depending specific use cases, thus a solution could be to add a directive that could be used to customize the process name or the cluster job name as you prefer. For example: 

   process foo {
     jobName "${ <your logic here> }"
   
    } 

Which looks great, thus this feature request.

**Comment by pditommaso** [comment]
I've an optional property `jobName` that can be specified in the `executor` scope in the nextflow.config file. It needs specified as a closure that returns the wanted job name. The closure can access the `task` context properties for example: 

    executor.$sge.jobName = { "$task.name - $task.hash" }

**Comment by antortjim** [comment]
Where can I find more about the task context? I can't find it anywhere in the documentation. What is the difference between task and process? Thank you
