### ISSUE TITLE
Google Cloud pipeline - provided ssh command fails.

### ISSUE THREAD

**Issue by durrantmm** [nextflow-io/nextflow#1400]
## Bug report 

I have been following the instructions in the documetnation to set up my own cluster in Google Cloud: [https://www.nextflow.io/docs/latest/google.html#](https://www.nextflow.io/docs/latest/google.html#).

Everything works as expected until I use the provided ssh command to connect to the master node:

`ssh -i /home/mdurrant/.ssh/id_rsa mdurrant@41.78.188.35.bc.googleusercontent.com`

The command times out, failing to connect.

Could this be some issue with my key? Is the image that I'm using not configured properly?

### Environment 

* Nextflow version: 19.01.0 
* Java version: 1.8.0_222
* Operating system: Linux

**Comment by pditommaso** [comment]
Hard to say, maybe you are behind a firewall that closes port 22? Consider using the Google Pipelines executor instead.
