### ISSUE TITLE
general closure to capture variables in the surrounding scope

### ISSUE THREAD

**Issue by kemin711** [nextflow-io/nextflow#1404]
## Capture variables when using closures such as filter, map

When I use a variable in the input or scripts body in the filter operator inside the output scope, I got an error for variable not found.  Looks like the closures in nextflow cannot capture enclosing scopes variable. This will greatly limit the power of composing more complicated pipelines.  Simply:
input:
val(x) from someChannel
ouput:
Channel.fromSomething().filter { row-> row[3] != x }

## Usage scenario 

(What's the main usage case and the deployment scenario addressed by this proposal)

## Suggest implementation 

(Highlight the main building blocks of a possible implementation and/or related components)

**Comment by pditommaso** [comment]
This syntax is not allowed.
