### ISSUE TITLE
fromFilePairs can't take list of paths

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#1405]
### Expected behavior and actual behavior

We'd like to be able to specify a list of specific URLs for use with fromFilePairs as follows, however it doesn't yet seem to be possible.

### Steps to reproduce the problem

```nextflow
ch_read_files = Channel.fromFilePairs([
  'https://github.com/nf-core/test-datasets/raw/methylseq/testdata/SRR389222_sub1.fastq.gz',
  'https://github.com/nf-core/test-datasets/raw/methylseq/testdata/SRR389222_sub2.fastq.gz',
  'https://github.com/nf-core/test-datasets/raw/methylseq/testdata/SRR389222_sub3.fastq.gz'
], size: 1)
```

### Program output 

```
Invalid method `call` invocation with arguments: /nf-core/test-datasets/raw/methylseq/testdata/SRR389222_sub1.fastq.gz (nextflow.file.http.XPath) on _fromFilePairs0_closure10 type
```

### Environment 

* Nextflow version: 19.11.0-edge build 5173
* Java version: java version "1.8.0_144"
* Operating system: macOS

### Additional context

Related: https://github.com/nextflow-io/nextflow/issues/874#issuecomment-427063183 and https://github.com/nextflow-io/nextflow/issues/946

**Comment by pditommaso** [comment]
Ok, solved. It will be included in the next release.

**Comment by ewels** [comment]
Thank you! 🙏🏻

**Comment by ewels** [comment]
Is it available in an edge version already?

**Comment by pditommaso** [comment]
Nope, only avail on master. I'll make an edge release in a couple of weeks.
