### ISSUE TITLE
SLURM with singularity

### ISSUE THREAD

**Issue by efratushava** [nextflow-io/nextflow#1407]
I have a problem running SLURM (sbatch) with singularity.

The nextflow command is :
`nextflow -log methylseq_try run try/try_fastqc.nf -with-singularity /tmp/ekushele-singularity/bismark_python.img -profile singularity`

The config file looks like this:
```
process.container = 'nfcore/methylseq:1.4'

profiles {
 singularity {
      singularity.enabled = true
      singularity.autoMounts = true
  }
}
```
When running with local executer, eveything works fine.
If I want to run it through sbatch, I add the following to my config file:
```
process {
  executor='slurm'
  time = '1.5h'
  memory = '5GB'
  clusterOptions = '--job-name=nxf_test'
}
```
 and I get the following error:
```
Error executing process > 'trim_galore (248933-cf-M.ben_list.b37)'

Caused by:
  Process `trim_galore (248933-cf-M.ben_list.b37)` terminated with an error exit status (255)

Command executed:

  trim_galore --paired --fastqc --gzip   --clip_r2 14   248933-cf-M.ben_list.b37.sorted_1.fastq 248933-cf-M.ben_list.b37.sorted_2.fastq

Command exit status:
  255

Command output:
  (empty)

Command error:
  ERROR  : Image path /tmp/ekushele-singularity/bismark_python.img doesn't exist: No such file or directory
  ABORT  : Retval = 255
  

Work dir:
  /path/to/home/work/83/ee334e8476b3192997e7d8418c941e

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out
```

Somehow, with sbatch, the singularity image cannot be found!
sbatch can be executed from the cluster I'm using.
Nextflow version 19.10.0

**Comment by max-l** [comment]
@efratushava have you solved this problem ? 
I'm running into it, in my case I get:

     Command error:
        env: ‘singularity’: No such file or directory

Because singularity is not avalable without first calling "module add" on the node.

I could of course call "singularity exec" in a shell script, but it kind of defeats the purpose, i.e. I loose the transparency
