### ISSUE TITLE
Task parameters ordering may invalidate task cache

### ISSUE THREAD

**Issue by emorice** [nextflow-io/nextflow#1408]
### Expected behavior and actual behavior

Adding a blank line between processes definition (not inside process definitions), thus changing nothing but line numbers in the main script, causes the processes after to be flagged as changed, under some specific circumstances. It would be expected that the hash of these tasks do not change and `-resume` simply get them from the cache.

### Steps to reproduce the problem

Get a recent nextflow release :
```
wget https://get.nextflow.io -O nextflow
chmod +x nextflow
```
and create an example pipeline `test.nf` containing exactly (do not change a single character):
```
process A {
	output:
		file 'a' into chan
	"""
		echo 'foo' > a
	"""
}

prog = ''
var = 'c'

process B {
        output:
                file('b') into result


        """
	echo $prog xxx > b ; touch $var

        """
}
```
Process A is actually irrelevant, but I left it as a control process to highlight the problem with B.
Then run the pipeline two or three time:

Run 1, initial run, behave as expected:
```
./nextflow run test.nf -resume
```
and runs both tasks:
```
N E X T F L O W  ~  version 19.10.0
Launching `test.nf` [suspicious_koch] - revision: e33cd08ab1
WARN: It appears you have never run this project before -- Option `-resume` is ignored
executor >  local (2)
[d3/9eddc1] process > A [100%] 1 of 1 ✔
[5a/6f88e3] process > B [100%] 1 of 1 ✔
```
Optional: Run 2, exact rerun, behaves as expected:
```
./nextflow run test.nf -resume
```
both processes are cached and recovered:
```
N E X T F L O W  ~  version 19.10.0
Launching `test.nf` [marvelous_shannon] - revision: e33cd08ab1
[d3/9eddc1] process > A [100%] 1 of 1, cached: 1 ✔
[5a/6f88e3] process > B [100%] 1 of 1, cached: 1 ✔
```

Run 3, single blank line change, fails to hit cache:
Change the `test.nf` file and insert a single blank line after the `var` declaration, so that it now looks like this:
```
process A {
	output:
		file 'a' into chan
	"""
		echo 'foo' > a
	"""
}

prog = ''
var = 'c'


process B {
        output:
                file('b') into result


        """
	echo $prog xxx > b ; touch $var

        """
}
```
and run again:
```
./nextflow run test.nf -resume
```
process A is correctly recovered, process B isn't though nothing has changed but line numbers:
```
N E X T F L O W  ~  version 19.10.0
Launching `test.nf` [small_jepsen] - revision: 9cfa9c418a
executor >  local (1)
[d3/9eddc1] process > A [100%] 1 of 1, cached: 1 ✔
[68/742c78] process > B [100%] 1 of 1 ✔
```
One can control the actual scripts did not change in any way (from a different reproduction, hence the different job hashes compared to above) :
```
$ sha256sum work/[89]*/*/.command.sh
93f60dc85ad0889cd3114480aa141e9f5cf8c74d50cb75f8690abd0de2720a7a  work/86/a075596d92b123fa768ed1b2bd8197/.command.sh
93f60dc85ad0889cd3114480aa141e9f5cf8c74d50cb75f8690abd0de2720a7a  work/92/a8e87464784ced4ad9e67fdf37450e/.command.sh
```
Of course here B is a toy process, in my initial problem it was a process lauching 400 psiblast jobs on a SLURM cluster which I cannot afford to rerun every time.

### Environment 

* Nextflow version: [19.10] , also tested with some other recent versions (.9 and .11 I think). edit: just reproduced on master (e0c1a3ac at this moment)
* Java version:
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Debian-1deb10u1, mixed mode, sharing)
```
edit: reproduced on other java version, namely
```
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```
* Operating system: [GNU/Linux Debian 10.2], reproduced on other linux distributions.

### Additional context

Important: this only happens under very particular, seemingly random cases that I encountered by chance. For instance, the problem do not happen if I redo all the steps above with `xx` instead of `xxx` in the B shell script. This leads me to believe there is a strange hashing happening incorrectly somewhere but I do not know where to start looking.

**Comment by emorice** [comment]
Ok, after discovering `-dump-hashes` and taking a closer look at the code, I think I guess what's happening:
 * `BodyDef` stores the variables referenced as a `Set` of `TokenValRef`. Since `TokenValRef` objects include line and col numbers, the (unspecified) underlying order in which these refs are in the Set depends pseudo-randomly on line numbers, and can change when a single blank line is inserted above.
* `TaskContext` get the variables names as a `Set<String>`, so again an unordered collection that in this case seems to retain the  (unspecified) original underlying order (no idea what happens exactly, I imagine `Set` do not attempt to hash/sort values under a given size threshold maybe ?)
* `TaskProcessor` iterate over the set it retrieves from the `TaskContext`, in this same unspecified order which happens to be the original, hashed-line-numbers-dependent order from the `TokenValRef` set. These values are passed as an ordered `List` to the CacheHelper, which then hashes them in an order-dependent way, resulting in unpredictable hash changes if the line and col numbers change.

See below the outputs after enabling some messages :
```
N E X T F L O W  ~  version 19.11.0-edge
Launching `test.nf` [grave_fourier] - revision: e33cd08ab1
[bd/444d4e] process > A [100%] 1 of 1, cached: 1 ✔
[d3/07d5f0] process > B [100%] 1 of 1, cached: 1 ✔
[A] cache hash: 756b8c155fef2748f8b7584b9cc19605; mode: STANDARD; entries: 
  4ae512429e09924d76a6dddfa742bbd7 [java.util.UUID] 8cd586a9-302f-40b8-b3f4-964cee4154ee 
  846b07c9c6fbf3d041357db6998e359f [java.lang.String] A 
  6c2e058d2d3977996c0ac3d1780ae5f2 [java.lang.String] """
                echo 'foo' > a
        """
 
  4f9d4b0d22865056c37fb6d9c2a04a67 [java.lang.String] $ 
  16fe7483905cce7a85670e43e4678877 [java.lang.Boolean] true
[B] cache hash: 87830bbbd85a120d34e13bdbc48818ac; mode: STANDARD; entries: 
  4ae512429e09924d76a6dddfa742bbd7 [java.util.UUID] 8cd586a9-302f-40b8-b3f4-964cee4154ee 
  249d12344b12b9e15ccc8fe2a99e5a46 [java.lang.String] B 
  2a8cd33365abce7ff47976b10a31d9ee [java.lang.String] """
        echo $prog xxx > b ; touch $var

        """
 
  4f9d4b0d22865056c37fb6d9c2a04a67 [java.lang.String] $ 
  16fe7483905cce7a85670e43e4678877 [java.lang.Boolean] true 
  4e5403a6ed3a625bfcce7a4a3715956c [java.lang.String] prog 
  00000000000000000000000000000000 [java.lang.String]  
  898e4aa8402cf383746cb3426cac6e06 [java.lang.String] var 
  8ebb8b6854c5ac9d4475bac0025eaf81 [java.lang.String] c
WARN: Binding names for 'A' > []
WARN: Binding names for 'B' > [prog, var]
WARN: Task: B > Adding script vars hash code: [prog:, var:c]
```
as opposed to:
```
N E X T F L O W  ~  version 19.11.0-edge
Launching `test.nf` [grave_kimura] - revision: 9cfa9c418a
executor >  local (1)
[bd/444d4e] process > A [100%] 1 of 1, cached: 1 ✔
[4d/abace4] process > B [100%] 1 of 1 ✔
[B] cache hash: 3dc9717b09c7f46f0bd3757a12dc30d2; mode: STANDARD; entries: 
  4ae512429e09924d76a6dddfa742bbd7 [java.util.UUID] 8cd586a9-302f-40b8-b3f4-964cee4154ee 
  249d12344b12b9e15ccc8fe2a99e5a46 [java.lang.String] B 
  2a8cd33365abce7ff47976b10a31d9ee [java.lang.String] """
        echo $prog xxx > b ; touch $var

        """
 
  4f9d4b0d22865056c37fb6d9c2a04a67 [java.lang.String] $ 
  16fe7483905cce7a85670e43e4678877 [java.lang.Boolean] true 
  898e4aa8402cf383746cb3426cac6e06 [java.lang.String] var 
  8ebb8b6854c5ac9d4475bac0025eaf81 [java.lang.String] c 
  4e5403a6ed3a625bfcce7a4a3715956c [java.lang.String] prog 
  00000000000000000000000000000000 [java.lang.String]
[A] cache hash: 756b8c155fef2748f8b7584b9cc19605; mode: STANDARD; entries: 
  4ae512429e09924d76a6dddfa742bbd7 [java.util.UUID] 8cd586a9-302f-40b8-b3f4-964cee4154ee 
  846b07c9c6fbf3d041357db6998e359f [java.lang.String] A 
  6c2e058d2d3977996c0ac3d1780ae5f2 [java.lang.String] """
                echo 'foo' > a
        """
 
  4f9d4b0d22865056c37fb6d9c2a04a67 [java.lang.String] $ 
  16fe7483905cce7a85670e43e4678877 [java.lang.Boolean] true
WARN: Binding names for 'A' > []
WARN: Binding names for 'B' > [var, prog]
WARN: Task: B > Adding script vars hash code: [var:c, prog:]
```

If this is indeed the problem, can we simply hash the referenced variables as an unordered collection instead, or was there a reason to hash them in an order-dependant way in the first place ?

**Comment by emorice** [comment]
Seems like a sort when going from unordered (Set) to ordered (List) is enough. 1f219fca appears to solve my case. Would that have other consequences ? Should this be addressed somewhere else ?

**Comment by pditommaso** [comment]
Interesting. Would you like to add a unit test and make a pull request?

**Comment by pditommaso** [comment]
Thanks for having spotted this. It was quite a ticky bug. I solved adding the task vars as an entry map (which is order insensitive) instead of sorting the map. See 4c692641.

**Comment by pditommaso** [comment]
Warning: this patch will invalidate existing caches having one or more task params.
