### ISSUE TITLE
Use AWS Batch without S3 (local input/output files)

### ISSUE THREAD

**Issue by connorcarolan** [nextflow-io/nextflow#1410]
## New feature

Use AWS Batch executor without needing to stage input files and upload output files to S3. In AWS you can configure the compute nodes to mount a local file system and therefore access the input files and write the output files to a local path.

## Usage scenario 

1. When submitting jobs from an AWS Ec2 instance. Configure the AWS Batch compute nodes to mount the Ec2 instances volumes, allowing the Batch nodes to access the files locally.
2. Store static input files on a persistent AWS volume (EBS/EFS) and mount the volume on the Batch compute nodes.

## Suggest implementation 

Add a flag onto the nextflow run command to specify using a local directory or S3.

**Comment by pditommaso** [comment]
The plan is to support this feature as a commercial extension. therefore closing this ticket.

**Comment by Nitin123-4** [comment]
Is it implemented ?

**Comment by jjyotikataria** [comment]
@connorcarolan Hi ConnorCarolon

I would like to know if you got any progress to use AWS Batch executor without needing to stage input files and upload output files to S3. If yes, can you please share any working example as staging will retard our pipeline running time drastically.
