### ISSUE TITLE
provide s3 object as input to -params-file   

### ISSUE THREAD

**Issue by nhoffman** [nextflow-io/nextflow#1412]
## New feature

Greetings - I'd like to suggest that ``-params-file`` should accept a url for an s3 object. 

## Usage scenario 

I'm setting up a pipleine in AWS batch in which I expect all inputs to be provided as s3 objects. Being able to specify these inputs via an s3 object would support pipeline execution with all run-specific assets in the cloud using a single command line parameter. 

I can think of other use cases, for example, to provide parameters to a service for launching nextflow pipelines.

## Suggest implementation 

Functionality for reading from s3 endpoints already appears to be supported within a pipleine. I think that it would be safe to assume the user would be responsible for configuring an environment that provided credentials for access to the resource.

**Comment by pditommaso** [comment]
It does! 

```
nextflow run <script> -params-file s3://YOUR_BUCKET/some-params.yml
```
