### ISSUE TITLE
nextflow launch script needs to pass -cluster.* args to ignite worker nodes

### ISSUE THREAD

**Issue by BlakeGFitch** [nextflow-io/nextflow#1413]
## Bug report 

The nextflow launch script doesn't pass cluster.* args to the Ignite worker nodes when launching on a cluster (-with-mpi) but these nodes may need that info to, for example, join the ignite cluster.

A proposed solution is appended at the bottom.

### Expected behavior and actual behavior

Expected to be able to form the nextflow command line in a SLURM job script including -cluster.* args such as to place the join path or cpu count.

### Steps to reproduce the problem

To reproduce this problem, nextflow with -with-mpi and -cluster.join parameters, for example:
```
srun ./nextflow -c tclust_sing.conf run tractoflow/main.nf --root Penthera_subset --dti_shells "0 1000" --fodf_shells "0 1000" --step 4.0 -with-singularity tractoflow_2.0.0_8b39aee_2019-04-26.img -with-mpi -resume -cluster.join path:/home/bfitch/nextflow_ignite_path -cluster.maxCpus ${SLURM_CPUS_PER_TASK} -cluster.group nextflow
```
### Program output 

Execution doesn't fail. All ignite processes run on node 0 and not on the ignite worker nodes.

### Environment 

* Nextflow version: [19.11.0] 
* Java version: [openjdk version "1.8.0_232"]
* Operating system: [linux centos 7]

### Additional context

Here is a patch to the nextflow launch script that seems to work.
```
[bfitch@devnode bfitch]$ diff -Naur nextflow/nextflow workflow-nextflow-tractoflow/nextflow
--- nextflow/nextflow	2019-12-10 10:20:38.000000000 +0100
+++ workflow-nextflow-tractoflow/nextflow	2019-12-10 10:22:17.000000000 +0100
@@ -158,7 +158,17 @@
             export NXF_EXECUTOR='ignite'
             export NXF_CLUSTER_SHUTDOWNONCOMPLETE='true'
         else
-            args=(-log .nextflow_node_${rank}.log node ignite)
+            argsCount=${#args[@]}
+            clusterArgs=()
+            for (( a=0; a<${argsCount}-1; a++ ));
+            do
+              if [[ "${args[$a]}" == "-cluster."* ]]; then
+                clusterArgs+=" ${args[$a]} "
+                clusterArgs+=" ${args[$a+1]} "
+                ((a=a+1))
+              fi
+            done
+            args=(-log .nextflow_node_${rank}.log node ignite ${clusterArgs} )
         fi
     # start in daemon mode
     elif [[ "$bg" ]]; then
```

**Comment by BlakeGFitch** [comment]
Hi @pditommaso ,

Is there a reason not to fix this? We are running a modified nextflow on site so it would be helpful to be able to use ignite with slurm. The patch seems fairly minimal. 

I hope you'll reconsider or suggest another workaround.

Thanks!!

Best,
Blake

**Comment by pditommaso** [comment]
This issue was closed automatically because there wasn't any on-going activity. Regarding the subject of the issue, feel free to submit a PR.

**Comment by BlakeGFitch** [comment]
I can submit a PR but I was concerned about whether my approach made sense in the grander scheme of things.

**Comment by pditommaso** [comment]
The Ignite executor is not more actively developed. If the impact of your patch is limited it can be included in the main codebase.
