### ISSUE TITLE
DSL2 issue: multiple use of emit Channel operator in same process definition results in error

### ISSUE THREAD

**Issue by bobamess** [nextflow-io/nextflow#1414]
## Bug report 

There appears to be a problem when including multiple `emit` Channel operators to define more than one name identifier within the same process. The example given in the documentation for DSL2 only has one instance of `emit` (https://www.nextflow.io/docs/edge/dsl2.html 
in section title 'Process named output'), but the DSL! documentation for process clearly states that the output block can contain one or more output declarations.  So, how can this be achieved in DSL2?  I had expected that my example below would work, but it fails.

### Expected behavior and actual behavior

For the DSL1 version, the expected dummy *.trimmed.fastq.gz and *trim_report.txt files were produced.  However, for the DSL2 version an apparent syntax error is reported (see Program output below).  This may be due to my misunderstanding of the use of the workflow directive and its components/elements in DSL2.  However, the documentation and available example scripts are somewhat limited. Indeed, in order to get other similar pipelines to work in DSL2 subtle changes in syntax were required such as the removal of parentheses from the tuple definition in DSL2, which are necessary in DSL1 but break the script if included in DSL2 e.g.

DSL1

```
tuple(val(runId), file('reads_?.fastq.gz')) from reads_ch
```

DSL2

```
tuple val(runId), file('reads_?.fastq.gz')
```

These changes were found necessary in addition to excluding the `from` keyword and channel identifier in the input directive, replacing `into` with `emit` where a channel output identifier is required, and using the `path` keyword instead of `file` whenever an `emit` operator is required for the output directive.  

Several variations in the use or omission of commas in the offending line and previous lines were attempted, but none either seemed appropriate, or fixed the problem.  Maybe I've missed something obvious, otherwise it appears to be a bug.

### Steps to reproduce the problem

Save the following DSL1 and DSL2 version scripts as multi_emit_dslX.nf, where X = 1 for DSL1, X = 2 for DSL2 and run on the head node (i.e the scripts use executor 'local', since there is no requirement for lengthy processing) as below with suitable parameter substitutions in the command line to access your paired .fastq.gz files and attached nextflow.config file.  The scripts only consume 2 pairs of .fastq.gz files as the input channel uses the take filter operator.

`nextflow run multi_emit_dslX.nf --fastqDir <dir_path>`

multi_emit_dsl1.nf

```
#!/usr/bin/env nextflow

Channel
	.fromFilePairs( "${params.fastqDir}/WTCHG*_{1,2}.fastq.gz", checkIfExists: true).take(2)
	.set { reads_ch }
	
// quality and adapter trim the fastq files
process trimReads {
	publishDir 'Results/TrimReports', mode: 'move', pattern: '*.txt', overwrite: false

	executor 'local'
	
	input:
		tuple(val(runId), file('reads_?.fastq.gz')) from reads_ch

	output:
		tuple(val(runId), file("*.trimmed.fastq.gz")) into trimmed_reads_ch
		path('*.txt')

	script:
	"""
		# dummy code below
	    echo "${runId}_1" | gzip -c > ${runId}_1.trimmed.fastq.gz
	    echo "${runId}_2" | gzip -c > ${runId}_2.trimmed.fastq.gz
	    uuidgen > ${runId}_trim_report.txt
	"""
}
```

multi_emit_dsl2.nf

```
#!/usr/bin/env nextflow

nextflow.preview.dsl=2

Channel
	.fromFilePairs( "${params.fastqDir}/WTCHG*_{1,2}.fastq.gz", checkIfExists: true).take(2)
	.set { reads_ch }
	
// quality and adapter trim the fastq files
process trimReads {

	executor 'local'
	
	input:
		tuple val(runId), file('reads_?.fastq.gz')

	output:
		tuple val(runId), path("*.trimmed.fastq.gz"), emit: trim_tup
		path('*.txt'), emit: trim_rep

	script:
	"""
		# dummy code below
	    echo "${runId}_1" | gzip -c > ${runId}_1.trimmed.fastq.gz
	    echo "${runId}_2" | gzip -c > ${runId}_2.trimmed.fastq.gz
	    uuidgen > ${runId}_trim_report.txt
	"""
}


workflow {
	
	main:
		
		trimReads(reads_ch)
	
	publish:
	
		trimReads.out.trim_rep to: 'Results/TrimReports', mode: 'move', pattern: "*.txt", overwrite: false
		
}
```

### Program output 

For DSL1, 

```
nextflow run multi_emit_dsl1.nf --fastqDir "/well/l udwig/users/benjamin/TAPS_miseq_validation/Data/fastq/tissue"
N E X T F L O W  ~  version 19.10.0
Launching `multi_emit_dsl1.nf` [cheeky_mayer] - revision: 2c3a390156
[-        ] process > trimReads -
executor >  local (2)
[11/ed5ddc] process > trimReads (1) [  0%] 0 of 2
executor >  local (2)
[11/ed5ddc] process > trimReads (1) [100%] 2 of 2 ✔
Pipeline complete
Command line: nextflow run multi_emit_dsl1.nf --fastqDir /well/ludwig/users/benjamin/TAPS_miseq_validation/Data/fastq/tissue
executor >  local (2)
[11/ed5ddc] process > trimReads (1) [100%] 2 of 2 ✔
```

For DSL2, 

```
nextflow run multi_emit_dsl2.nf --fastqDir "/well/l udwig/users/benjamin/TAPS_miseq_validation/Data/fastq/tissue"
N E X T F L O W  ~  version 19.10.0
Launching `multi_emit_dsl2.nf` [distracted_stone] - revision: b11cf99def
Oops .. something went wrong
Script compilation error
- file : /gpfs0/users/ludwig/krn062/scripts/test_dsl2/multi_emit_dsl2.nf
- cause: expecting '}', found ',' @ line 19, column 16.
                path('*.txt'), emit: trim_rep
                  ^
1 error
```

### Environment 

* Nextflow version: 19.10.0
* Java version: 1.8.0_141
* Operating system: CentOS Linux 7

### Additional context

Grid engine: UGE 8.5.0
Groovy version: 2.5.8 JVM: 1.8.0_112 Vendor: Oracle Corporation OS: Linux

[nextflow.zip](https://github.com/nextflow-io/nextflow/files/3944674/nextflow.zip)
[multi_emit.zip](https://github.com/nextflow-io/nextflow/files/3944716/multi_emit.zip)

By the way, as you will see, I have had problems inserting the code as part of it ends up in the text despite inserting all of it together after clicking the <> icon.  I am using Google Chrome as the Browser (Version 78.0.3904.108 (Official Build) (64-bit)).

**Comment by bobamess** [comment]
Updated nextflow.config file in attached zip as original was missing the definition of 

`params.fastqDir  = ""`

in last few lines.

[nextflow.zip](https://github.com/nextflow-io/nextflow/files/3944797/nextflow.zip)

**Comment by bobamess** [comment]
Apologies, but discovered that my example files were not sufficiently generic so now attach updated scripts with the line
`.fromFilePairs( "${params.fastqDir}/WTCHG*_{1,2}.fastq.gz", checkIfExists: true).take(2)`
updated to
 `.fromFilePairs( "${params.fastqDir}/*_{1,2}.fastq.gz", checkIfExists: true).take(2)`
[multi_emit.zip](https://github.com/nextflow-io/nextflow/files/3946106/multi_emit.zip)

**Comment by jerdra** [comment]
to add to this it seems like when the second output is also a tuple, things will work as expected.
For example:
```
executor 'local'

input:
	tuple val(runId), file('reads_?.fastq.gz')

output:
	tuple val(runId), path("*.trimmed.fastq.gz"), emit: trim_tup
	tuple path('*.txt'), emit: trim_rep

script:
"""
	# dummy code below
    echo "${runId}_1" | gzip -c > ${runId}_1.trimmed.fastq.gz
    echo "${runId}_2" | gzip -c > ${runId}_2.trimmed.fastq.gz
    uuidgen > ${runId}_trim_report.txt
"""
```

**Comment by bobamess** [comment]
Have discovered that if the second output has the brackets removed so now 
`path '*.txt', emit: trim_rep`
It works as expected.  But if the brackets for path are removed in the preceding line as in
`tuple val(runId), path "*.trimmed.fastq.gz", emit: trim_tup`
this results in a similar error to before e.g.
`- cause: expecting '}', found ',' @ line 18, column 46.
   Id), path "*.trimmed.fastq.gz", emit: tr`

In summary, below works:

`output:
tuple val(runId), path("*.trimmed.fastq.gz"), emit: trim_tup
path '*.txt', emit: trim_rep`

and the following two variations both fail:

`output:
tuple val(runId), path("*.trimmed.fastq.gz"), emit: trim_tup
path('*.txt'), emit: trim_rep`

and

`output:
tuple val(runId), path "*.trimmed.fastq.gz", emit: trim_tup
path '*.txt', emit: trim_rep`

To me, this is inconsistent syntax, which is not helpful.

By the way, return line feeds in code are stripped out in Preview, which is also not helpful and tab does not work in Write mode..

**Comment by bobamess** [comment]
Further to this.  It appears that the behaviour is such that in the 2nd output, the  `emit` part is an argument to the `path ` method call.  This can be demonstrated by using  `path('*.txt', emit: trim_rep)` which also works and similar was given as the correct syntax in #1311.
  
However, for the 1st output, `emit ` is not an argument to `path`  and instead  `path("*.trimmed.fastq.gz")` is an argument to the `tuple `  method and the `emit `  part needs to be separated from `tuple ` and its arguments. Although doing this by enclosing tuple's arguments 
 in parentheses as in `tuple(val(runId), path("*.trimmed.fastq.gz")), emit: trim_tup`  results in an error, which seems inconsistent.

However, #1311 does not say that enclosing `emit ` in path's parentheses will not work if `path ` is part of a `tuple.` 

#1276 includes examples of using `emit ` with  `workflow,` but I haven't yet found an example that covers the use of `tuple ` with `path ` and `emit ` in DSL1 or DSL2.
 
The optional use of parentheses in Groovy is BRIEFLY described in http://groovy-lang.org/semantics.html#_optional_parentheses para 4.1.  
How this is supposed to translate to how parentheses should be used, or not, in Nextflow is, in my opinion, challenging.

I would greatly encourage more examples that work in DSL2 and cover such method calls to be offered.

**Comment by pditommaso** [comment]
The problem was `emit:` is an option of the top-level component and therefore it should be inside the parenthesis (when used). 

Therefore, the following are correct: 

```
  path '*.txt', emit: trim_rep
  path('*.txt', emit: trim_rep)
```

This is invalid

```
  path('*.txt'), emit: trim_rep
```

I know this is a bit tricky, but it's a limitation of the underlying parser.
