### ISSUE TITLE
Feature Request: Allow for workflow-level job submissions (DSL2)

### ISSUE THREAD

**Issue by jerdra** [nextflow-io/nextflow#1415]
## New feature
Allow for SLURM/TORQUE/PBS/etc job submissions to be configuired at the level of a workflow. That is, workflows themselves should be submitted as jobs. 

## Usage scenario 

With DSL2 comes a different way of structuring nextflow scripts. When working with SLURM/PBS/TORQUE workflow-level job submissions often makes more sense than independent process job submissions. 

This is the case when working on a module (containing a workflow) which contains many single-computation processes. In these cases it doesn't feel intuitive/practical to submit/configure at the level of single process. Combining single-function processes into larger processes could somewhat resolve this but you trade-off Nextflow's excellent input/output management for in-process script solutions. 

In addition, when sharing modules, it would be useful to package them and include overall workflow requirements rather than requirements for every process within a workflow - greatly simplifying the process of setting up configuration files.

## Suggest implementation 
Treat workflows like processes for execution, in a configuration file:
```
workflow{
 withName: wf{ executor = 'slurm', time = ..., }
}
```

**Comment by pditommaso** [comment]
This should already be possible already using a process selector and specifying `name-of-the-workflow:*` as name.

**Comment by jerdra** [comment]
@pditommaso just to clarify will this specify the same execution config for every process in workflow (all processes in a workflow will submit independently but with the same config) or will it submit the workflow as a single entity? 

I'm hoping for the latter. 

Thanks

**Comment by pditommaso** [comment]
As long you include a process in a subworkflow eg 

```
workflow foo {
   bar()
}
```

You can provide the config for it using the process fully qualifier name as `foo:bar`. Using a `foo:*` pattern it should be possible to match all procs in the `foo` execution scope.

**Comment by jerdra** [comment]
Right, so bar() would be submitted as a job with parameters determined by the config spec given by:

<code>foo:*</code>

This is close, but not exactly what I am hoping for. Given a workflow <code>foo</code>, my request was such that:

```
workflow foo{
       bar1()
       bar2()
}

```

That with a config specifying <code>foo:{ ... }</code>. That *both* <code>bar1()</code> and <code>bar2()</code> would be submitted as a single job rather - the workflow is a single submission with specified parameters.

However, I am beginning to realize that collection operators within a workflow may cause issues with  a single submission with the current design of starting processes as soon as inputs are available...
