### ISSUE TITLE
Automatically disable ansi in non-interactive shells

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#1417]
## New feature

Generally, big ❤️ to ansi logging. However, in non-interactive terminals, it is a bit of a mess and very difficult to read.

It would be great if nextflow could do the same thing so that we don't have to add `-with-ansi false` everywhere

## Usage scenario 

Typically CI tests and running on non-interactive cluster jobs  ([example](https://github.com/nf-core/rnaseq/runs/336458608)).

## Suggest implementation 

Other tools ([`bat`](https://github.com/sharkdp/bat) and others) are able to detect when the terminal is detached and not use ansi formatting as a result. It should be possible by [looking for $PS1](https://www.gnu.org/software/bash/manual/html_node/Is-this-Shell-Interactive_003f.html) or other methods.

**Comment by pditommaso** [comment]
It should already, maybe it needs to be a bit refined 

https://github.com/nextflow-io/nextflow/blob/86ebcfac66b1ea0855219970936745b57109311c/modules/nextflow/src/main/groovy/nextflow/cli/CliOptions.groovy#L90-L109

**Comment by ewels** [comment]
Ah I'd forgotten about `$NXF_ANSI_LOG`, that's nicer at least. How is `background` decided? I guess that's the bit that detects the terminal type?

**Comment by pditommaso** [comment]
The `background` flag is set by the `run -bg` option. Also the last line should do what you are suggesting, at least I was hoping that 

https://github.com/nextflow-io/nextflow/blob/86ebcfac66b1ea0855219970936745b57109311c/modules/nextflow/src/main/groovy/nextflow/cli/CliOptions.groovy#L109

**Comment by pditommaso** [comment]
Not sure how to improve this, line 109 reported above should do what you are mentioning. Any suggestion is welcome.

**Comment by ewels** [comment]
From a bit of googling, this is my best guess:

```java
import static org.fusesource.jansi.internal.CLibrary.isatty;
System.out.println( isatty(STDIN_FILENO) );
```
From https://stackoverflow.com/a/52526450/713980

Then turn off ansi mode if we are running in a tty. Of course, GitHub actions / Travis etc. could be doing all kinds of weird stuff so it may well do exactly the same thing.. I have a nasty feeling that they will report that they _are_ an interactive terminal so that tools give coloured output etc. But it's just the redrawing of existing lines that is broken. See for example this travis GitHub issue: https://github.com/travis-ci/travis-ci/issues/1337#issuecomment-22747694

So sounds like you could potentially look for environment variables such as [`CONTINUOUS_INTEGRATION`](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables) (Travis) or [`GITHUB_ACTIONS`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environment-variables) (GH actions). But that's getting a little hacky.. and I'm not sure that it's much better than people just setting the NF `DISABLE_ANSI` variable in their CI config.

Based on this, I'll close as I think you already have the functionality that I'm asking for and there isn't really a nice easy fix after all 😊

**Comment by pditommaso** [comment]
Nice spot the `isatty` function, I didn't know it. Actually it could do a better job here. I'm adding it  as default result.
