### ISSUE TITLE
BitBucketServer authentication not working

### ISSUE THREAD

**Issue by tverbeiren** [nextflow-io/nextflow#1418]
### Expected behavior and actual behavior

I'm using NXF 19.11.0-edge with DSL2. Everything is working as expected, but now I want to run my pipeline immediately from a bitbucket server instance provided by the IT department.

I created the `~/.nextflow/scm` file and provided the appropriate configuration there. I use the `-hub` command line argument to specify the profile. I also provided username and password via the CLI. But none of these work.

When I base64 encode the combination `<username>:<password>` and pass this via cURL to the same endpoint, it works. So the server side accepts authentication requests using Basic Auth over SSL. As far as I can tell, when run through NXF it's basically doing the same behind the scenes, but in this case I get an authentication failure.

I can also use tokens to access the API using cURL, but AFAIK the NextFlow provider for bitbucket server does not handle this case.

### Steps to reproduce the problem

I don't know of a publicly available private bitbucket server instance, so this is impossible.

### Program output 

The log file mentions (redacted):

```
Dec-11 14:34:04.837 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials <username>:***********] -> https://<host>/rest/api/1.0/projects/...
Dec-11 14:34:05.193 [main] DEBUG nextflow.scm.RepositoryProvider - Response status: 403 -- error code: 1010
Dec-11 14:34:05.203 [main] WARN  nextflow.scm.AssetManager - Cannot read project manifest -- Cause: Forbidden -- Check that the BitBucketServer user name and password provided are correct
```

### Environment 

* Nextflow version: 19.11.0-edge
* Java version: openjdk version "1.8.0_232"
* macOS

**Comment by pditommaso** [comment]
Closing because this bug report does not include expected information to replicate the issue. Make sure you are using the proper config. Note: `bitbucket` != `bitbucketserver` https://www.nextflow.io/docs/latest/sharing.html#bitbucket-server-credentials
