### ISSUE TITLE
If statements stopped working in withLabel selector in config files

### ISSUE THREAD

**Issue by MaxUlysse** [nextflow-io/nextflow#1420]
## Bug report 

cf: https://github.com/nf-core/configs/pull/110

No idea where this coming from, but we had that in our config files which has been tested and was working:
```Nextflow
process {
  withLabel:sentieon {
    if (params.sentieon) {
      module = 'sentieon/201808.05'
      container = null
    }
}
```

Then this error appeared:
```Bash
Unknown config attribute `process.withLabel:sentieon`
```

Managed to fix if by using ternary operator:
```Nextflow
process {
  withLabel:sentieon {
    module = {params.sentieon ? 'sentieon/201808.05' : null}
    container = {params.sentieon ? null : container}
  }
}
```

I tried to find out which Nextflow version was used for our previous tests, but couldn't find out (cf: https://github.com/seqeralabs/nf-tower/issues/208)

I'm trying to look for any explanation (missing `(`,`{` or`[` or typos or whatever) regarding that matter.
If anyone has any idea, I'll welcome any clue.

### Expected behavior and actual behavior

(Give an brief description of the expected behavior 
and actual behavior)

### Steps to reproduce the problem

Managed to make a minimal example:
main.nf:
```Nextflow
#!/usr/bin/env nextflow

process Process {
    label 'label'

    input:

    output:

    script:
    """
    touch ${task.cpus}
    """
}
```

nextflow.config:
```Nextflow
process {
  withLabel:label {
    if (params.cpus) cpus = 3
  }
}
```

### Program output 

Output is:
```Bash
Unknown config attribute `process.withLabel:label.params.cpus`
```

When changing the nextflow.config to:
```Nextflow
process {
  withLabel:label {
    cpus = {params.cpus ? 3 : cpus}
  }
}
```

Error is now longer there...

### Environment 

* Nextflow version: [version 19.10.0 build 5170] 
* Java version: [1.8.0_201]
* Operating system: [Linux]

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Conditional expression ie. ternary operator is the proper way to handle this.
