### ISSUE TITLE
Solution in #1249 does not allowed chained parameter setting in nesting workflows

### ISSUE THREAD

**Issue by JonathanCSmith** [nextflow-io/nextflow#1424]
## Bug report 

See #1249 for core information - however, the issue is that the solution suggested does not allow double nested workflows to have parameters set by the outermost workflow.

### Expected behavior and actual behavior

I expect to be able to nest workflows recursively, allowing me to build complexity and allow reusability. Currently it seems like double nesting of workflows can only be performed by declaring the imports outside of the workflow scope. This prevents parameters from being chained to the innermost workflow.

### Steps to reproduce the problem

See #1249 but attempt to provide params in the outermost workflow and then access them in the innermost.

### Program output 

'Undefined parameter'

### Environment 

* Nextflow version: 19.10.0 
* Java version: [?]
* Operating system: CentOS

**Comment by tverbeiren** [comment]
Please take a look at my comment here: https://github.com/nextflow-io/nextflow/issues/1249#issuecomment-565464362

**Comment by tverbeiren** [comment]
If the configuration does not need to be dynamic, would the following work for you use-case? `params` is taken from `nextflow.config`. This way, you don't need to pass those as arguments:

```
include module  from "./module.nf"  params(params)
```

**Comment by JonathanCSmith** [comment]
Unfortunately above is the exact use case that does not work. If we declare the module imports outside of the workflow declaration in the middle workflow, then the params have not yet been instantiated (my intuition only - I haven't looked into the code). Does that make sense? Basically if you try your above solution (which is my preference) then the innermost modules will not have properly filled params.

**Comment by pditommaso** [comment]
Closing in favour of #1484, which should address the issue.
