### ISSUE TITLE
turn current process output into a channel

### ISSUE THREAD

**Issue by kemin711** [nextflow-io/nextflow#1426]
## convert output file or directory into a channel

It looks that currently we can only turn a global already known file or directory into a channel.  For example Channel.filePairs("some/directpry/*{1,2}.suffix").set{name_of_channel} will turn a directory into a channel.  and Channel.fromPath("afile").splitCsv() will turn a file into a channel

It would be nice that the directory and file could be produced by the current process. This requires the output section be executed after the script section has done the work. Or it is working on the work if turning directories into a channel.

## Usage scenario 

Here is an example to turn a file into a channel

```
#!/usr/bin/env nextflow
  
/**
 * how to turn a tabular file into a channel 
 */
process tab2channel {

   output:
   //Channel.fromPath($tabfile).splitCsv().set{ fourval_ch }  // error No such variable: $tabfile
   Channel.fromPath("tabularfile.txt").splitCsv().set{ fourval_ch }
   // first run: No such file: /where/script/is/launched/directory/tabularfile.txt
   // fromPath file means the script home directory
   // as a result, the pipeline is executed zero times 

   script:
   tabfile="tabularfile.txt"
   """
   touch $tabfile
   echo "id1\tvalX1\tvalY1\tvalZ1" > $tabfile
   echo "id2\tvalX2\tvalY2\tvalZ2" >> $tabfile
   echo "id3\tvalX3\tvalY3\tvalZ3" >> $tabfile
   """
}

process usetable {
   input:
   tuple val(id), val(vx), val(vy), val(vz) from fourval_ch

   script:
   """
   touch marer.txt
   echo "The four values: $id $vx $vy $vz"
   """
}
```

One component of the pipeline may produce many files or one file with more processing instructions.  This feature will be make nextflow very powerful.

## Suggest implementation 

Delay the execution of the output section until the script section have either finished in the case of file situation.  In the case of directory situation, you need an event listener to monitor the appearance of files matching certain regular expression.  The monitoring process will stop when the script section either crashed or terminated normally.

**Comment by pditommaso** [comment]
Any process output is implicitly a channel, therefore I'm not understanding this request.
