### ISSUE TITLE
Support AWS Batch Array Jobs

### ISSUE THREAD

**Issue by tbugfinder** [nextflow-io/nextflow#1427]
## New feature

Submission of thousands of similar jobs to AWS Batch by nextflow has a major trade-off in regards to API throttling and therefore slow scaling and startup of compute instances.
AWS Batch supports so called [array jobs](https://docs.aws.amazon.com/batch/latest/userguide/array_jobs.html) for launching this type of jobs. AWS Batch array jobs compare to SGE, Slurm job arrays.

## Usage scenario 

Submitting (hundreds of) thousands of jobs of comparable type. The difference could just be a file to operate on which is usually an input within the job.
Using array jobs, arrays of filenames could be provided and each child selects the file by using `AWS_BATCH_JOB_ARRAY_INDEX` env.

## Suggest implementation 

Add an additional parameter arraysize to executor.

It would be even more advanced if the input data could already be prepared to match the environment settings of AWS Batch.

**Comment by tbugfinder** [comment]
[ListJobs](https://docs.aws.amazon.com/batch/latest/APIReference/API_ListJobs.html#API_ListJobs_RequestSyntax) response includes all child jobIds.

**Comment by pditommaso** [comment]
Same as #1477.
