### ISSUE TITLE
Qsub error

### ISSUE THREAD

**Issue by onurtugalan** [nextflow-io/nextflow#1428]
Qsub error, doesnt execute the command

Hi,

Just started using nextflow and I have a problem. I test nextflow using 2 docker images and when I run it locally it works like charm though when I run it with executor mode sge I have an error as the one below. I have to kill the process otherwise it takes too long for hpc to kill it. I checked lots of errors in this group but none of them worked for me even though some of them are similar.

Dec-13 11:29:01.048 [main] DEBUG nextflow.cli.Launcher - $> nextflow -trace nextflow.executor.GridTaskHandler run tutorial.nf
Dec-13 11:29:01.109 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 19.10.0
Dec-13 11:29:01.133 [main] INFO  nextflow.cli.CmdRun - Launching `tutorial.nf` [berserk_kalman] - revision: 55044159ed
Dec-13 11:29:01.164 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /mnt/hiseq1-galaxy/galaxy_devel_working_dir/ot/nextflow/nextflow.config
Dec-13 11:29:01.166 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /mnt/hiseq1-galaxy/galaxy_devel_working_dir/ot/nextflow/nextflow.config
Dec-13 11:29:01.205 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Dec-13 11:29:02.361 [main] DEBUG nextflow.extension.OperatorEx - Dataflow extension methods: branch,buffer,chain,choice,collate,collect,collectFile,combine,concat,count,countBy,countFasta,countFastq,countLines,countText,cross,distinct,filter,first,flatMap,flatten,fork,groupBy,groupTuple,ifEmpty,into,join,last,map,max,mean,merge,min,mix,phase,print,println,randomSample,reduce,separate,set,splitCsv,splitFasta,splitFastq,splitText,spread,subscribe,sum,take,tap,toDouble,toFloat,toInteger,toList,toLong,toSortedList,transpose,unique,until,view
Dec-13 11:29:02.370 [main] DEBUG nextflow.Session - Session uuid: 688da2f9-18f1-40f9-90b7-989dd1ee0226
Dec-13 11:29:02.371 [main] DEBUG nextflow.Session - Run name: berserk_kalman
Dec-13 11:29:02.372 [main] DEBUG nextflow.Session - Executor pool size: 16
Dec-13 11:29:02.391 [main] DEBUG nextflow.cli.CmdRun -
  Version: 19.10.0 build 5170
  Created: 21-10-2019 15:07 UTC (17:07 CEST)
  System: Linux 3.10.0-514.21.1.el7.x86_64
  Runtime: Groovy 2.5.8 on OpenJDK 64-Bit Server VM 1.8.0_191-b12
  Encoding: UTF-8 (UTF-8)
  Process: 4625@srv1356.intern.gatc-biotech.com [xxx.xx..x..x...x.]
  CPUs: 16 - Mem: 47 GB (939.8 MB) - Swap: 23.6 GB (18 GB)
Dec-13 11:29:02.452 [main] DEBUG nextflow.Session - Work-dir: /mnt/hiseq1-galaxy/galaxy_devel_working_dir/ot/nextflow/work [nfs]
Dec-13 11:29:02.452 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /mnt/hiseq1-galaxy/galaxy_devel_working_dir/ot/nextflow/bin
Dec-13 11:29:02.488 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Dec-13 11:29:02.492 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Dec-13 11:29:02.779 [main] DEBUG nextflow.Session - Session start invoked
Dec-13 11:29:03.030 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Dec-13 11:29:03.235 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:cutadapt` matches process cutadapt
Dec-13 11:29:03.247 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Dec-13 11:29:03.247 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Dec-13 11:29:03.271 [main] DEBUG nextflow.executor.Executor - [warm up] executor > sge
Dec-13 11:29:03.286 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'sge' > capacity: 100; pollInterval: 5s; dumpInterval: 5m
Dec-13 11:29:03.296 [main] DEBUG n.executor.AbstractGridExecutor - Creating executor 'sge' > queue-stat-interval: 1m
Dec-13 11:29:03.401 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > cutadapt -- maxForks: 16
Dec-13 11:29:03.479 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withName:flash` matches process flash
Dec-13 11:29:03.480 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: sge
Dec-13 11:29:03.480 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'sge'
Dec-13 11:29:03.483 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > flash -- maxForks: 16
Dec-13 11:29:03.491 [main] DEBUG nextflow.script.BaseScript - No entry workflow defined
Dec-13 11:29:03.492 [main] DEBUG nextflow.script.ScriptRunner - > Await termination
Dec-13 11:29:03.492 [main] DEBUG nextflow.Session - Session await
Dec-13 11:29:03.749 [Task submitter] TRACE nextflow.executor.GridTaskHandler - start process cutadapt > cli: [qsub, -terse, .command.run]
Dec-13 11:29:03.791 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process cutadapt > jobId: 1013647; workDir: /mnt/hiseq1-galaxy/galaxy_devel_working_dir/ot/nextflow/work/b8/f515d90c3c8de7edef5e06763c955d
Dec-13 11:29:03.798 [Task submitter] INFO  nextflow.Session - [b8/f515d9] Submitted process > cutadapt
Dec-13 11:29:30.050 [SIGINT handler] DEBUG nextflow.Session - Session aborted -- Cause: SIGINT
Dec-13 11:29:30.089 [SIGINT handler] DEBUG nextflow.Session - The following nodes are still active:
[process] flash
  status=ACTIVE
  port 0: (value) OPEN  ; channel: x1
  port 1: (value) OPEN  ; channel: x2
  port 2: (cntrl) -     ; channel: $

Dec-13 11:29:30.093 [main] DEBUG nextflow.Session - Session await > all process finished
Dec-13 11:29:30.094 [main] DEBUG nextflow.Session - Session await > all barriers passed
Dec-13 11:29:30.106 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (1)
Dec-13 11:29:30.146 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=0; failedCount=1; ignoredCount=0; cachedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms]
Dec-13 11:29:30.279 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Dec-13 11:29:30.313 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

**Comment by onurtugalan** [comment]
config file 
process {
    executor ='sge'
    withName:cutadapt {
      container = 'registry.intern.gatc-biotech.com/bioit-devel/bioit-tools/cutadapt'
       }
    withName:flash {
       container = 'registry.intern.gatc-biotech.com/bioit-devel/bioit-tools/flash'
    }
}
docker {
    enabled = true
}

nextflow file

chain='^GTGBCAGCMGCCGCGGTAA...GGATTAGAKACCCBNGTAGTC -A ^GACTACNVGGGTMTCTAATCC...TTACCGCGGCKGCTGVCAC'
process cutadapt {
   publishDir "$PWD/result"
   executor 'sge'
   clusterOptions '-S /bin/sh -q devel.q@srv205'
   input:
      path x from '/mnt/hiseq1-galaxy/galaxy_devel_working_dir/ot/nextflow/fastq/NG-20494_583_063_291_lib350172_6518_1_1.fastq.gz'
      path y from '/mnt/hiseq1-galaxy/galaxy_devel_working_dir/ot/nextflow/fastq/NG-20494_583_063_291_lib350172_6518_1_2.fastq.gz'
   output:
      file 'onur1.fastq.gz' into result1
      file 'onur2.fastq.gz' into result2
   """
      cutadapt -a $chain -j 4 -o onur1.fastq.gz -p onur2.fastq.gz $x $y
   """
}
process flash {
   publishDir "$PWD/result"
   input:
      file x1 from result1
      file x2 from result2
   output:
      file 'out*' into out1
   """
      flash -o "out" $x1 $x2
   """
}

**Comment by tbugfinder** [comment]
Hi @onurtugalan 
would you mind formatting your logs and code snippet using tripple backticks?

**Comment by tbugfinder** [comment]
This log-line would point to a missing mount on the given execution host: ` - Script base path does not exist or is not a directory: /mnt/hiseq1-galaxy/galaxy_devel_working_dir/ot/nextflow/bin`

Could you verify that it is available on all nodes?

**Comment by tbugfinder** [comment]
@onurtugalan 
Did you try to submit the job using the command given by the trace?
`qsub -terse .command.run`? Maybe also check the created `.command.run` file.

**Comment by pditommaso** [comment]
Closing for lack of feedback.
