### ISSUE TITLE
Processes not executed show up in the dag and in the trace

### ISSUE THREAD

**Issue by dweemx** [nextflow-io/nextflow#1429]
### Expected behavior and actual behavior

I noticed that even though a process is not executed it is still present in the DAG and in the trace. I was wondering if this was a bug or this was done on purpose because then the DAG is not really telling the truth about what has been run.

### Steps to reproduce the problem

I'm running the example from https://github.com/nextflow-io/patterns/blob/master/docs/conditional-process.adoc using `nextflow run  conditional_process.nf --flag -with-dag`.

### Program output 

- trace
```
N E X T F L O W  ~  version 19.09.1-SNAPSHOT
Launching `conditional_process.nf` [prickly_edison] - revision: 143d3e9f9f
executor >  local (2)
[-        ] process > foo       -
[f0/3a9f38] process > bar       [100%] 1 of 1 ✔
[28/098cbe] process > omega (1) [100%] 1 of 1 ✔
```
- DAG
![image](https://user-images.githubusercontent.com/16015936/71078541-e6860380-2189-11ea-9d2f-4ba36df8d33e.png)

### Environment 

* Nextflow version: 19.09.1-SNAPSHOT build 5132
* Java version: java version "1.8.0_201"
* Operating system: Ubuntu 18.04

### Additional context

None

**Comment by pditommaso** [comment]
This is expected because the DAG represents the connectivity graph not the graph of the executed tasks.
