### ISSUE TITLE
timeline.html no longer works in Safari

### ISSUE THREAD

**Issue by mfoll** [nextflow-io/nextflow#143]
Tested with Safari Version 9.1 under OS X. It works ok with Google Chrome and Firefox. Under Safari it only shows:
![timeline_safari](https://cloud.githubusercontent.com/assets/3366818/14988403/f2412a50-1153-11e6-9824-27288de3c124.jpg)

**Comment by pditommaso** [comment]
Just uploaded `0.18.3-SNAPSHOT` fixing this.
