### ISSUE TITLE
Support Azure Batch as additonal executor

### ISSUE THREAD

**Issue by tbugfinder** [nextflow-io/nextflow#1430]
## New feature - Azure Batch Support

Microsoft Azure is still a growing compute environment. Azure Batch itself does support singularity and docker images and containers. Especially singularity is a unique feature.

## Usage scenario 

Execute container workload within Azure.

## Suggest implementation 

add additional executor by using the [azure-java-sdk](https://github.com/Azure/azure-sdk-for-java).

**Comment by pditommaso** [comment]
Related https://github.com/Azure/azure-sdk-for-java/issues/7158#issuecomment-590496687

**Comment by arnaudceol** [comment]
@tbugfinder this would be a useful feature. Many institutes rely on Azure (as an extension to all others office 365 services).

On the other way, Azure also offers a free Kubernete service (you pay for the nodes). Did you already evaluate what would be the advantages of using Azure batch over a more standard Azure Kubernetes service?

**Comment by GHAStVHenry** [comment]
Any thoughts on this? from Nextflow team? I agree with the utility of this, my institute requires Azure for any cloud resources!

**Comment by pditommaso** [comment]
Not in the very short term but there are some chances to have in the second half of the year.

**Comment by andersgs** [comment]
@pditommaso just wanted to check in to see if there is any progress here. Thank you!

**Comment by pditommaso** [comment]
Still pending :/

**Comment by vsmalladi** [comment]
@pditommaso to get this to work we would have to use [Azure BATCH API](https://docs.microsoft.com/en-us/rest/api/batchservice/ )
and mimic [AWS Batch]( https://github.com/nextflow-io/nextflow/tree/master/modules/nf-amazon/src/main/nextflow/cloud/aws/batch )

**Comment by vsmalladi** [comment]
Great will learn more about Azure batch api

**Comment by vsmalladi** [comment]
@pditommaso you have documentation on how you worked out gcp or aws implementation?

**Comment by tbugfinder** [comment]
Hi @vsmalladi 
are you trying to develop it? I could support with prereqs but not sure about the nf pieces.
IMHO, sdk docu and https://batch-shipyard.readthedocs.io/en/latest/00-introduction/ should help.

**Comment by vsmalladi** [comment]
Hi @tbugfinder ,
Yes trying to develop and build it out

**Comment by pditommaso** [comment]
> @pditommaso you have documentation on how you worked out gcp or aws implementation?

Unfortunately nothing more than the cloud provider docs

**Comment by lvclark** [comment]
I'm working with a group that is interested in this feature, just for maximum portability of our Nextflow pipeline, so I've subscribed!

**Comment by pditommaso** [comment]
We are starting to work soon on this. Stay tuned.

**Comment by sminot** [comment]
I just wanted to add to the thread and say that I would also be very interested in using this feature!

**Comment by abhi18av** [comment]
Just posting an update if anyone would like to take this for a spin and share feedback 😉 
https://github.com/nextflow-io/nextflow/tree/master/plugins/nf-azure

**Comment by sminot** [comment]
Looks like we've got an implementation to try out, @pditommaso?

https://github.com/nextflow-io/nextflow/tree/master/plugins/nf-azure

**Comment by pditommaso** [comment]
The support for Azure Batch is finally available https://twitter.com/nextflowio/status/1364215305359269891

**Comment by pditommaso** [comment]
More details at this link https://www.nextflow.io/docs/edge/azure.html

**Comment by tmuylder** [comment]
We've been very happy with the release of support for Azure Batch !! I started testing it and got stuck now with the following note:
```
Install is not supported on dev mode - Missing plugin nf-azure
```
Even though the plugin is there ... Any ideas?  
I'm running with version `21.02.0-edge` manually installed, the following command: `./nextflow-21.02.0-edge/launch.sh run nf-core-rnaseq/main.nf -profile test,docker -w az://nf-blob-container/work` following guidelines in the article + documentation. So `nextflow.config` defines plugin id, azure executor, and other azure settings...

**Comment by pditommaso** [comment]
Open a separate issue  including the command line you are using and the `.nextflow.log` create by NF
