### ISSUE TITLE
IO with aws batch

### ISSUE THREAD

**Issue by GHAStVHenry** [nextflow-io/nextflow#1431]
3 issues with AWS Batch... all are intermittent...
All using Nextflow 19.09.0 using AWS Batch, work and output is a S3 Bucket

1. Occasionally a process's input files don't copy to the work directory which causes an error. I've never noticed it locally, and half the time, the exact same run will fail and the other half it will pass
2. Publish of output fail when process uses "move" mode instead of "copy" exactly like #160... as I said I'm using 19.09.0.
3. Not all the files copy to output... I have a process, which uses a batch script to run 4 Rscripts in parallel (there is a wait at the end of the bash script)... each of which outputs pngs into 4 different sub-directories. The process then gets splint into chunks based on a file which was split with splitText. When run locally all the pngs from all the chunks in all 4 sub-directories get's copied into output (output is `file(**/*.png)`)... when ran in AWS, a "large" run will only copy 1 subdirectory from each chunk. Interestingly the same data but a less memory intense version (same number of files) seems to copy all of them.

Hope y'all can help!

**Comment by pditommaso** [comment]
Sorry, no support for deployment-specific problems here.
