### ISSUE TITLE
Default Timeline Naming Behavior of "Timeline" and "Trace"

### ISSUE THREAD

**Issue by JohnHadish** [nextflow-io/nextflow#1435]
## New feature
When a workflow is resumed with this command:

```
nextflow run main.nf -with-report -with-timeline  -resume
```
The current `timeline.html` and `report.html` are overwritten with new files. This means that **the timeline and report from the first part of the workflow are lost**.

## Suggest implementation 

**My first and preferred option**
I think that a nice behavior would be to  concatenate new information onto the existing report when a `-resume` tag is used in the command.

I know that the user can rename the timeline each time that they resume, but that is kind of annoying to have to do, and is easy to forget. I think that the best way to do this would be to just **concatenate new information onto the existing `timeline.html` and  `report.html` files whenever the `-resume` tag is used**. This is more intuitive than the default behavior of overwriting these reports. A line in the timeline that says where the restart occurred would be beneficial information (see below mock-up).

Here is a mock-up of what I think the `timeline` file should look like when a `-resume` flag is used:

![Screenshot from 2020-01-02 16-55-30](https://user-images.githubusercontent.com/35115540/71701827-d1f85c80-2d80-11ea-879e-b2a3e53c02c1.png)

This would allow the user to see where the restart occurred, and have the entire timeline.

**A second option** would be to simply add another copy of the reports with a new number like how the "nextflow.log" files get renumbered.
Here is how the nextflow.log files look when there is more than 1:
```
.nextflow.log
.nextflow.log.1
.nextflow.log.2
```
Proposed:
```
timeline.html
timeline.1.html
timeline.2.html
```
Unfortunately, the nature of the `report.html` and the `timeline.html` are kind of different that the `.nextflow.log`, so I personally think that **concatenation would be the superior option** .

## Usage scenario 

Default behavior of `-with-report` and ` -with-timeline` tags when used in combination with the `-resume` tag

**Comment by pditommaso** [comment]
Nice idea, help wanted!
