### ISSUE TITLE
"\n" and "\r" not work in Python, and cause IndentationError

### ISSUE THREAD

**Issue by jqd** [nextflow-io/nextflow#1438]
## Bug report 
"\n" and "\r" not work in Python, and the generated ".command.sh" file has extra space from the second line.

### Expected behavior and actual behavior
want to add a new line to the output, but this causes an indentation error. It works in Perl.
In python, a backslash "\\" is needed to solve the problem.

### Steps to reproduce the problem
```
process foo {
    script:
    """
        #!/usr/bin/env perl
        print("Testing new line \t");
        print("Testing new line \n");
        print("Testing new line \r");
    """
}
```
```
process bar {
    script:
    """
        #!/usr/bin/env python
        print("Testing new line \t")
        print("Testing new line \n")
        print("Testing new line \r")    
    """
}
```
### Program output 
```
executor >  local (2)
[ef/59d613] process > foo [100%] 1 of 1 ✔
[83/add8f3] process > bar [100%] 1 of 1, failed: 1 ✘
Error executing process > 'bar'

Caused by:
  Process `bar` terminated with an error exit status (1)


Command executed:

  #!/usr/bin/env python
          print("Testing new line       ")
          print("Testing new line
  ")
          print("Testing new line
  ")

Command exit status:
  1

Command output:
  (empty)

Command error:
    File ".command.sh", line 2
      print("Testing new line   ")
      ^
  IndentationError: unexpected indent
```

### Environment 

* Nextflow version: [19.10.0] 
* Java version: [10.0.2]
* Operating system: [Linux]

### Additional context

(Add any other context about the problem here)

**Comment by haqle314** [comment]
Looking at the reported command executed, you can tell what's going on. The escape characters are processed by nextflow/groovy and replaced with the actual characters (tab, or newline, ...). And Python being Python, bitches about whitespace. You have two options, either replace every instance of `\` with `\\`. This way, nextflow sees `\\n` and passes along `\n` to the subprocess. Or you can tell nextflow to not touch backslash by delimiting your code with `$/` and `/$` instead of `"""`.

```nextflow
$/
#!/usr/bin/env python
print("Testing new line \n")
/$
```
    
It's a [Groovy feature](http://groovy-lang.org/syntax.html#_dollar_slashy_string). It might messes with something else though, I'm not familiar with this enough to be able to tell.

**Comment by jqd** [comment]
@haqle314 Thanks, I prefer the `$/…​/$` option without changing the original python code. 
Anyway to stop nextflow/Groovy processing special characters this way?

**Comment by haqle314** [comment]
Skimming the Groovy document that I linked in my previous comment, I don't think there's one. But maybe someone more knowledgeable on this matter could chime in.

**Comment by jqd** [comment]
Also, why nextflow process the tab and newline characters in Perl and Python differently? I think it just copy the code in the `"""` section, and save it into the `.command.sh` file.

**Comment by haqle314** [comment]
You can take a look at the content of `.command.sh` and check. I'm 90% certain that nextflow doesn't do anything differently. It's just that the same piece of code is valid in Perl but not in Python.

**Comment by pditommaso** [comment]
NF does not handle differently python vs perl snippet. The error depends on the underlying interpreter. 

Use [slashy strings](https://groovy-lang.org/syntax.html#_slashy_string) if you want to prevent special character escaping.
