### ISSUE TITLE
cleanup after failed conda creation

### ISSUE THREAD

**Issue by karl616** [nextflow-io/nextflow#1445]
## New feature

If the creation of a conda environment fails it would be nice if nextflow recognized this and cleaned up the folder.

Alternatively, but I think that is harder, nextflow should recognize partial conda environments fail with a informative error

## Usage scenario 

When nextflow has to create a conda environment and another process fails during this, it seems to interrupt conda without taking further action. This leaves conda environment folders with the correct hash id. Subsequent nextflow (-resume) executions treat these as a complete installation and often fails, or worse, end up using other software present in the path.

## Suggest implementation 

When the creation of a conda environment interrupted or fails, catch this and clean up the folder. Alternatively rename it in order to allow user inspection.

**Comment by andersgs** [comment]
Any updates on this? I have run into the same problem. Something failed in the conda env creation. And, now it won't go forward.

**Comment by karl616** [comment]
The work-around is often to remove the partial conda environment in
work/conda.

Den fre 13 nov. 2020 20:53Anders Goncalves da Silva <
notifications@github.com> skrev:

**Comment by jonalim** [comment]
This is still a problem for me, as of v23.10.0. Feels like a major gap in the user experience.

**Comment by pditommaso** [comment]
Consider using Conda-based containers provisioned via [Wave](https://www.nextflow.io/docs/latest/wave.html#build-conda-based-containers). This is much more reliable in our experience.
