### ISSUE TITLE
Missing forward slash in concatenated strings

### ISSUE THREAD

**Issue by SergejN** [nextflow-io/nextflow#1446]
### Expected behavior and actual behavior

```
params.db = '/path/to/my/Blast/NR/nr'
println(file(params.db).parent + '/' + file(params.db).name + '*')
```
expected output: `/path/to/my/Blast/NR/nr*`
actual output: `/path/to/my/Blast/NRnr*`

### Environment 

* Nextflow version: 19.10.0
* Operating system: Linux

### Additional context

A slightly modified version of code works fine:

```
params.db = '/path/to/my/Blast/NR/nr'
println(file(params.db).parent + '/*'' + file(params.db).name + '*')
```
prints `/path/to/my/Blast/NR/*nr*`

thanks!

**Comment by SergejN** [comment]
thanks to @micans on Gitter there is a workaround! This code works as expected.

`println(file(params.db).parent.toString() + '/' + file(params.db).name.toString() + '*')`

**Comment by pditommaso** [comment]
This is expected. File objects ie. [Path](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html) implicitly remove any ending `/` from file/dir names
