### ISSUE TITLE
Resume misses completed tasks on slurm when nextflow process is killed

### ISSUE THREAD

**Issue by alneberg** [nextflow-io/nextflow#1448]
### Expected behavior and actual behavior

We have an issue where the nextflow process gets abruptly killed for some reason (different story). It does not kill it's active tasks so in our case, these continue running. These tasks goes on and produce a proper `.exitcode` file with a `0`, therefore we would assume that using `-resume`, Nextflow would be able to use cache for tasks. Instead, they are resubmitted.

### Steps to reproduce the problem

Using the getting started template:
#### main.nf:
```

params.str = 'Hello World!'

process splitLetters {

    output:
    file 'chunk_*' into letters

    """
    printf '${params.str}' | split -b 6 - chunk_
    """
}

process convertToUpper {

   input:
   file x from letters.flatten()

   output:
   stdout result

   """
   sleep 100
   rev $x
   """
}

result.view { it.trim() }
```

#### nextflow.config:
```
process {
     executor='slurm'
     clusterOptions = { "-A $params.project" }
     cpus = 1
     time = 1.h
}
```

1. Start nextflow:
```
$ nextflow main.nf --str "this is my parameter" --project ngi2016004 -resume
N E X T F L O W  ~  version 19.04.1
Launching `main.nf` [stoic_lumiere] - revision: f655835c1e
WARN: It appears you have never run this project before -- Option `-resume` is ignored
[warm up] executor > slurm
executor >  slurm (5)
[9a/76f9d6] process > splitLetters   [100%] 1 of 1 ✔
[fb/6e965f] process > convertToUpper [  0%] 0 of 4
Killed
```
2. Kill the nextflow process to simulate the real failure using `kill -9`. The `-9` makes sure that the running tasks are not terminated.

3. Wait

4. Make sure the tasks finished correctly:
```
$ cat work/*/*/.exitcode
00000
```

5. Restart using `-resume`:
```
$ nextflow main.nf --str "this is my parameter" --project ngi2016004 -resume
```

### Program output 
```
N E X T F L O W  ~  version 19.04.1
Launching `main.nf` [small_dijkstra] - revision: f655835c1e
[warm up] executor > slurm
executor >  slurm (4)
[9a/76f9d6] process > splitLetters   [100%] 1 of 1, cached: 1 ✔
[12/f542ac] process > convertToUpper [100%] 4 of 4 ✔
re
i siht
temara
p ym s
Completed at: 09-Jan-2020 15:11:11
Duration    : 1m 45s
CPU hours   : 0.1 (0% cached)
Succeeded   : 4
Cached      : 1

```

### Environment 

* Nextflow version: 19.04.1
* Java version: ~~Java(TM) SE Runtime Environment (build 1.7.0_25-b15)~~ Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
* Operating system: CentOS Linux 7

Thanks!

**Comment by alneberg** [comment]
Realised the java version looked ancient, but found that I had `NXF_JAVA_HOME=/sw/comp/java/x86_64/sun_jdk1.8.0_151` set as well, so that ought to be the one used.

**Comment by alneberg** [comment]
Reproduced this on a different (but similar) system with:

 - Nextflow version: 19.10.0
 - Java version: OpenJDK Runtime Environment (build 1.8.0_232-b09)

**Comment by pditommaso** [comment]
It may be related to #1358 or #1408.
