### ISSUE TITLE
Error: Invalid or corrupt jarfile if your CTRL-C initial run of nextflow

### ISSUE THREAD

**Issue by tseemann** [nextflow-io/nextflow#145]
My first run of nextflow was interrupted with CTRL-C and it seems to leave a partially downloaded corrupt `.jar` file?   Perhaps it should download to a tmp folder then do an atomic move when successful.

```
% nextflow
Downloading nextflow dependencies. It may require some seconds, please wait .. ^C

% nextflow
Error: Invalid or corrupt jarfile /home/tseemann/.nextflow/framework/0.17.3/nextflow-0.17.3-one.jar
Unable to initialize nextflow environment
```

**Comment by pditommaso** [comment]
It makes sense, thanks for the suggestion. You can recover the installation deleting the `/home/tseemann/.nextflow/` folder and downloading it again.

**Comment by tseemann** [comment]
Yeah I just deleted the corrupt JAR and all was well. Thanks.

**Comment by pditommaso** [comment]
Version 0.18.3
