### ISSUE TITLE
Message Queue / Kafka integration

### ISSUE THREAD

**Issue by fwip** [nextflow-io/nextflow#1456]
## New feature

I would like to propose native integration with messaging queues, in the same way that we integrate with executors. Kafka is my personal preference. This would include the ability to read data from a message queue into a channel, and also to write back into a message queue.

## Usage scenario 

This could be used to construct long-running (or indefinitely-running) pipelines in a more robust way than `Channel.watchPath()`. This would help enable using Nextflow as the core of a processing pipeline - reading information continuously from a message queue, spawning the necessary processes, and writing information about the completion of the job back to the message queue.

This is similar to the `Channel.watchPath()` usage, and also to https://github.com/nextflow-io/nextflow/issues/743. 

## Suggest implementation 

I've put together a proof-of-principle here: https://gist.github.com/fwip/d802e11f27d30861972deba7dfb85d56. This doesn't modify any of nextflow's core code, but I imagine it would be cleaner if implemented in Nextflow itself. (Specifically, I don't understand the channel processing loop, so I spawned a new thread simply to poll kafka for updates indefinitely. Cleanup is also kind of an open question.)

I think ideally for the user, it could be as simple as `Channel.fromTopic(topic_name)`, with configuration (choice of provider, connection parameters, etc) handled in the config file.

As an alternative, an easy way to construct an unbounded channel would be appreciated. I know that DSL2 deprecates `Channel.create()` and `.bind()`, so I believe the only supported way is the `.watchPath()` method. Something like `Channel.fromIterator(java.util.Iterator)` might be a lot easier to implement, and allow for more custom strategies that might not deserve first-class support.

**Comment by SvenDowideit** [comment]
yes please - this is similar to the idea of a web event watch we discussed in Perth :)
