### ISSUE TITLE
squeue status cannot be fetched

### ISSUE THREAD

**Issue by peter-yufan-zeng** [nextflow-io/nextflow#1459]
## Bug report 

squeue status cannot be retrieved

`WARN: [SLURM] queue status cannot be fetched                                                                            - cmd executed: squeue --noheader -o %i %t -t all -u zyfniu                                                             - exit status : 1                                                                                                       - output      :                                                                                                           slurm_load_jobs error: Socket timed out on send/recv operation`

### Expected behavior and actual behavior

I believe the above command is missing " " around the %i and %t

so instead of 
`squeue --noheader -o %i %t -t all -u zyfniu`

it should be

`squeue --noheader -o "%i %t" -t all -u zyfniu `

### Steps to reproduce the problem

I am using the nf-core/sarek pipeline 

### Program output 

`WARN: [SLURM] queue status cannot be fetched                                                                            - cmd executed: squeue --noheader -o %i %t -t all -u zyfniu                                                             - exit status : 1                                                                                                       - output      :                                                                                                           slurm_load_jobs error: Socket timed out on send/recv operation`

### Environment 

* Nextflow version: 19.10.0.5170
* Java version: openjdk version "1.8.0_152-release"                                                                                     OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)                                                          OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)      
* Operating system: CentOS cluster w slurm

**Comment by pontus** [comment]
(This came up in the nf-core sarek), and I mentioned this there as well;

to me it looks like a local cluster issue (and a nextflow bug in representing that line?)

The `Socket timed out` strongly suggests it speaks to slurm but does not finish the conversation in the expected time.

I don't think there are actually missing quotes around the -o options, I'd expect something similar to `squeue: error: Unrecognized option: %t` if that was the case.

**Comment by pditommaso** [comment]
Indeed, the cli command print does not include the quotes, but they are there for the reason explained. This looks a network/connection issue with your cluster.

**Comment by pontus** [comment]
OP replied in that slack:

> `i came to that conclusion because when I run squeue --noheader -o %i %t -t all -u zyfniu in a 
> terminal, I get that exact same error

> However, when i run squeue --noheader -o "%i %t" -t all -u zyfniu I get the correct output

It seems unexpected for me, but I can hardly say their system does not behave so).

**Comment by peter-yufan-zeng** [comment]
However, if you refer to the squeue usage page [here](https://slurm.schedmd.com/squeue.html), you can see in the -o page that 

`-o <output_format>, --format=<output_format>
Specify the information to be displayed, its size and position (right or left justified). Also see the -O <output_format>, --Format=<output_format> option described below (which supports less flexibility in formatting, but supports access to all fields). The default formats with various options are
default
"%.18i %.9P %.8j %.8u %.2t %.10M %.6D %R"
-l, --long
"%.18i %.9P %.8j %.8u %.8T %.10M %.9l %.6D %R"
-s, --steps
"%.15i %.8j %.9P %.8u %.9M %N"
The format of each field is "%[[.]size]type".`

Maybe this is an issue with different versions of slurm installed?

Thanks again for your help guys!

**Comment by peter-yufan-zeng** [comment]
The problem is that my cluster treats %t as a option, rather than a continuation of %i %t. 

For example, this line also output correctly
`squeue --noheader -o %i\ %t -t all -u zyfniu`

`26229251 R
26388220 R
26388881 PD
26388882 PD
26388883 PD`

**Comment by StevenWingett** [comment]
Hi,

I'm a novice when it comes to setting up Nextflow an a compute cluster, but I believe I am experiencing a similar problem.

When I run the Nextflow nf-core/rnaseq pipeline it will sometimes run to completion or sometimes fail with the message shown below.  (Just to be clear, if I run exactly the same pipeline with the same input data and command etc., then sometimes it works and sometimes it fails in an apparently random fashion.)   

Command run:

nextflow run nf-core/rnaseq -r 3.4 --input samplesheet.csv --genome GRCh38_v102 -config lmb_orignal.config -bg

The pipleine ran for many steps and then generated the error message:

WARN: [SLURM] queue status cannot be fetched
- cmd executed: squeue --noheader -o %i %t -t all -u swingett
- exit status : 1
- output      :
  slurm_load_jobs error: Socket timed out on send/recv operation


If I enter that command in the command line I get:

[swingett@hex paired_end]$ squeue --noheader -o %i %t -t all -u swingett
squeue: error: Unrecognized option: %t

However, as peter-yufan-zeng mentioned, if I use quotes the option is recognised:

[swingett@hex paired_end]$ squeue --noheader -o "%i %t" -t all -u swingett
480145 PD
480144 R

Sorry if I am missing an obvious solution, but do I need to alter my settings in some way to overcome this problem?

If it helps, my environment was:
Nextflow v21.10.6 (build 5660)
Scientific Linux 7.9 (Nitrogen)
slurm 21.08.0
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

Many thanks for your assistance.

All the best,

Steven

**Comment by bentsherman** [comment]
For anyone who stumbles on this issue, the error about the output format options being in quotes is a red herring. Nextflow does execute the command with `-o "%i %t"`, but the error message is printed in a way that doesn't show the quotes. You have to check the rest of the error message reported by Nextflow.

For example, if you see something like:
```
output :
slurm_load_jobs error: Socket timed out on send/recv operation
```

That probably means that there were connectivity issues with your SLURM cluster.
