### ISSUE TITLE
Can't find git repository config file -- Repository may be corrupted

### ISSUE THREAD

**Issue by mroorda** [nextflow-io/nextflow#1460]
### Expected behavior and actual behavior

I ran the rnaseq pipeline a couple of months ago on a cluster, and tried to run it again this week. I ran into 2 issues:

### Steps to reproduce the problem

I followed the installation guide located here (https://nf-co.re/usage/installation)

# Make sure that Java v8+ is installed:
java -version

# Install Nextflow
curl -fsSL get.nextflow.io | bash

# Add Nextflow binary to your PATH:
mv nextflow ~/bin/
# OR system-wide installation:
# sudo mv nextflow /usr/local/bin

wget https://github.com/nf-core/rnaseq/archive/master.zip
mkdir -p ~/my-pipelines/nf-core/
unzip master.zip -d ~/my-pipelines/nf-core/
cd ~/my_data/
nextflow run ~/my-pipelines/nf-core/rnaseq-master

### Program output 

[user]$`nextflow run nf-core/rnaseq --profile test`
N E X T F L O W  ~  version 19.10.0
Can't find git repository config file -- Repository may be corrupted: /home/p273324/.nextflow/assets/nf-core/rnaseq

[user/rnaseq]$ `nextflow run nf-core/rnaseq-master --profile test`
N E X T F L O W  ~  version 19.10.0
Pulling nf-core/rnaseq-master ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nf-core/rnaseq-master/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nf-core/rnaseq-master/contents/main.nf

### Environment 

* Nextflow version:   N E X T F L O W
      version 19.10.0 build 5170
      created 21-10-2019 15:07 UTC (17:07 CEST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io

* Java version: openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

* Operating system: Linux (cluster)

**Comment by bentsherman** [comment]
You don't need to download pipelines explicity, just install nextflow and run the pipeline:
```
curl -fsSL get.nextflow.io | bash
mv nextflow ~/bin/
nextflow run nf-core/rnaseq -profile test
```

Nextflow will download the pipeline for you. Also make sure to specify `-profile` with one dash not two dashes, otherwise it will not be recognized.

**Comment by Ashok-pappu** [comment]
Hello !
Environment:

N E X T F L O W
      version 24.04.4 build 5917
      created 01-08-2024 07:05 UTC (12:35 IDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io

JAVA
openjdk 21-internal 2023-09-19
OpenJDK Runtime Environment (build 21-internal-adhoc.conda.src)
OpenJDK 64-Bit Server VM (build 21-internal-adhoc.conda.src, mixed mode, sharing)

While running nextflow run epi2me-labs, facing this issue.

Pulling nextflow-io/epi2me-labs ...

WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nextflow-io/epi2me-labs/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/nextflow-io/epi2me-labs/contents/main.nf
