### ISSUE TITLE
Jobs temporary stopped (throttled) by uge are considered terminated by Nextflow

### ISSUE THREAD

**Issue by DaGaMs** [nextflow-io/nextflow#1461]
### Expected behavior and actual behavior

Jobs should be left running if the job state changes to `Tr`, which in Univa grid engine means that a job was suspended because of an alarm, e.g. low memory on the node, but the job is not killed and will resume later.

### Program output 

Here is a `qstat` output for my job, as it was when Nextflow thought it was bening killed:

```
qstat -j 22569786
==============================================================
job_number:                 22569786
jclass:                     NONE
exec_file:                  job_scripts/22569786
submission_time:            01/15/2020 17:56:28.077
owner:                      benjamin
uid:                        30084
group:                      ludwig
gid:                        30012
supplementary group:        ludwig
sge_o_home:                 /users/ludwig/benjamin
sge_o_log_name:             benjamin
sge_o_path:                 /users/ludwig/benjamin/perl5/bin:/apps/well/perl/5.16.3/bin:/mgmt/uge/8.5.0/bin/lx-amd64:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/usr/lpp/mmfs/bin:/users/ludwig/benjamin/bin:/users/ludwig/benjamin/perl5/bin:/apps/htseq/samtools-1.9:/apps/htseq/bcftools-1.9:/users/ludwig/benjamin/.methodicate
sge_o_shell:                /bin/bash
sge_o_workdir:              /gpfs2/well/ludwig/users/benjamin/Octopus_test/work/2e/675be0adfb87307a70a4d40148dba7
sge_o_host:                 rescomp1
account:                    sge
cwd:                        /gpfs2/well/ludwig/users/benjamin/Octopus_test/work/2e/675be0adfb87307a70a4d40148dba7
merge:                      y
mail_list:                  benjamin@rescomp1
notify:                     TRUE
job_name:                   nf-bamToFastq_(1)
stdout_path_list:           NONE:NONE:/gpfs2/well/ludwig/users/benjamin/Octopus_test/work/2e/675be0adfb87307a70a4d40148dba7/.command.log
priority:                   0
jobshare:                   0
hard_queue_list:            long.qc
env_list:                   BASH_ENV=/etc/profile.d/modules.sh
script_file:                .command.run
parallel environment:  shmem range: 3
project:                    ludwig.prjc
department:                 defaultdepartment
binding:                    NONE
mbind:                      NONE
submit_cmd:                 qsub -terse .command.run
start_time            1:    01/15/2020 18:35:11.377
job_state             1:    Tr
exec_host_list        1:    compE047:3
usage                 1:    wallclock=00:11:33, cpu=00:12:59, mem=12.78595 GBs, io=15.51348 GB, iow=0.000 s, ioops=184757403, vmem=86.086M, maxvmem=95.676M
scheduling info:            (Collecting of scheduler job information is turned off)
```

and here is how the job looked like 10 minutes later:

```
qstat -j 22569786 -f
==============================================================
job_number:                 22569786
jclass:                     NONE
exec_file:                  job_scripts/22569786
submission_time:            01/15/2020 17:56:28.077
owner:                      benjamin
uid:                        30084
group:                      ludwig
gid:                        30012
supplementary group:        ludwig
sge_o_home:                 /users/ludwig/benjamin
sge_o_log_name:             benjamin
sge_o_path:                 /users/ludwig/benjamin/perl5/bin:/apps/well/perl/5.16.3/bin:/mgmt/uge/8.5.0/bin/lx-amd64:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/usr/lpp/mmfs/bin:/users/ludwig/benjamin/bin:/users/ludwig/benjamin/perl5/bin:/apps/htseq/samtools-1.9:/apps/htseq/bcftools-1.9:/users/ludwig/benjamin/.methodicate
sge_o_shell:                /bin/bash
sge_o_workdir:              /gpfs2/well/ludwig/users/benjamin/Octopus_test/work/2e/675be0adfb87307a70a4d40148dba7
sge_o_host:                 rescomp1
account:                    sge
cwd:                        /gpfs2/well/ludwig/users/benjamin/Octopus_test/work/2e/675be0adfb87307a70a4d40148dba7
merge:                      y
mail_list:                  benjamin@rescomp1
notify:                     TRUE
job_name:                   nf-bamToFastq_(1)
stdout_path_list:           NONE:NONE:/gpfs2/well/ludwig/users/benjamin/Octopus_test/work/2e/675be0adfb87307a70a4d40148dba7/.command.log
priority:                   0
jobshare:                   0
hard_queue_list:            long.qc
env_list:                   BASH_ENV=/etc/profile.d/modules.sh
script_file:                .command.run
parallel environment:  shmem range: 3
project:                    ludwig.prjc
department:                 defaultdepartment
binding:                    NONE
mbind:                      NONE
submit_cmd:                 qsub -terse .command.run
start_time            1:    01/15/2020 18:35:11.377
job_state             1:    r
exec_host_list        1:    compE047:3
usage                 1:    wallclock=00:11:33, cpu=00:12:59, mem=12.78595 GBs, io=15.51348 GB, iow=0.000 s, ioops=184757403, vmem=86.086M, maxvmem=95.676M
scheduling info:            (Collecting of scheduler job information is turned off)
```

As you can see, the job was simply resumed.

### Environment 

* Nextflow version: 19.12.0-edge
* Java version: openjdk version "1.8.0_141"
* Operating system: linux
* UGE version: 8.5.0

**Comment by pditommaso** [comment]
Thanks for reporting this. Just pushed a patch on the master branch.

**Comment by DaGaMs** [comment]
Inexplicably, I now get a job state of just `T` and not `Tr` sometimes. The subtleties of univa grid engine job states are not entirely clear to me I must admit, but from all I can tell, `T` also indicates a job where 

> T(hreshold) state shows that at least one suspend threshold of the  corresponding queue was exceeded and that the job has been suspended as a consequence.

**Comment by DaGaMs** [comment]
Here's the full section from the `qstat` man page:

>  The state *d*(eletion) indicates that a qdel has been used to initiate job deletion. The states *t*(ransfering) and *r*(unning) indicate that a job is about to be executed or is already executing, whereas the states *s*(uspended), *S*(uspended), e(*N*)hanced suspended, (*P*)reempted and *T*(hreshold) show that an already running jobs has been suspended. The *s*(uspended) state is caused by suspending the job via the qmod -s command, the *S*(uspended) state indicates either that the queue containing the job is suspended and therefore the job is also suspended or that a pending job got (*S*)uspended due to a preemptive action that was either triggered automatically by the system or by a manual preemption request triggered via qmod -p ... S. e(*N*)hanced suspended and (*P*)reempted jobs in the pending jobs list are also preemptive states shown for pending jobs triggered either automatically or via qmod -p ... N or -p ... P. *T*(hreshold) state shows that at least one suspend threshold of the corresponding queue was exceeded (see queueconf) and that the job has been suspended as a consequence. The state *R*(estarted) indicates that the job was restarted. This can be caused by a job migration or because of one of the reasons described in the -r section of the qsub command. The states *w*(aiting) and *h*(old) only appear for pending jobs. The *h*(old) state indicates that a job currently is not eligible for execution due to a hold state assigned to it via qhold, qalter or the qsub -h option or that the job is waiting for completion of the jobs to which job dependencies have been assigned to the job via the -hold_jid or -hold_jid-ad options of qsub or qalter. The state *E*(rror) appears for pending jobs that couldn't be started due to job properties.

**Comment by pditommaso** [comment]
Feel free to submit a pull request 

https://github.com/nextflow-io/nextflow/blob/20408e4b1c21659afa7aa5222db60a0cd6170150/modules/nextflow/src/main/groovy/nextflow/executor/SgeExecutor.groovy#L134-L140
