### ISSUE TITLE
Allow data to be accessed from Requester Pays bucket on Google Cloud  

### ISSUE THREAD

**Issue by twbattaglia** [nextflow-io/nextflow#1466]
## New feature

Currently, any data that is within a Requester Pays bucket cannot be accessed for processing, as  a billable project ID must be provided. For each `gsutil` request the `-u` flag needs to be used (https://cloud.google.com/storage/docs/using-requester-pays#storage-download-file-requester-pays-python). As the project ID are provided within `GOOGLE_APPLICATION_CREDENTIALS` and `google.project` it would be convenient to include these projects in the calls for file staging. 

Previous discussion about this feature: https://groups.google.com/forum/#!searchin/nextflow/Requester$20pays%7Csort:date/nextflow/LpJRX8Xm9lc/-rd2GTIaCQAJ

## Usage scenario 
For large study datasets that rely on Cloud Identity and Access Management to give permissions to individual files and do not want to incur charges for data retrieval.

## Suggest implementation 

The project ID can be included in the staging command that downloads the file using `gsutil`. 

**GoogleLifeSciencesFileCopyStrategy.groovy**
```
...
        for( String stageName : inputFiles.keySet() ) {
            final storePath = inputFiles.get(stageName)
            final storePathIsDir = storePath.isDirectory()
            final stagePath = Paths.get(stageName)
            final parent = stagePath.parent
            final escapedStoreUri = Escape.uriPath(storePath)
            final escapedStageName = Escape.path(stageName)

            //check if we need to create parent dirs for staging file since gsutil doesn't create them for us
            if(parent) {
                createDirectories << "mkdir -p $localTaskDir/${Escape.path(parent)}".toString()
            }

            if(storePathIsDir) {
                stagingCommands << "gsutil -u PROJECTID -m -q cp -R $escapedStoreUri/ $localTaskDir".toString()
                //check if we need to move the directory (gsutil doesn't support renaming directories on copy)
                if(parent || !storePath.toString().endsWith(stageName)) {
                    stagingCommands << "mv $localTaskDir/${Escape.path(storePath.name)} $localTaskDir/$escapedStageName".toString()
                }
            } else {

                stagingCommands << "gsutil -u PROJECTID -m -q cp $escapedStoreUri $localTaskDir/$escapedStageName".toString()
            }
        }
...
```

Also the project ID can be included in the call that retrieves the Google Cloud Storage FileSystem object `CloudStorageFileSystem.forBucket()` by using the `CloudStorageConfiguration` found here: https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/storage/contrib/nio/CloudStorageFileSystem.html#forBucket-java.lang.String-com.google.cloud.storage.contrib.nio.CloudStorageConfiguration-

**GsPathFactory.groovy**
```
package nextflow.cloud.google.util

import java.nio.file.Path

import com.google.cloud.storage.contrib.nio.CloudStorageFileSystem
import com.google.cloud.storage.contrib.nio.CloudStorageConfiguration
import groovy.transform.CompileStatic
import nextflow.file.FileSystemPathFactory

/**
 * Implements FileSystemPathFactory interface for Google storage
 *
 * @author Paolo Di Tommaso <paolo.ditommaso@gmail.com>
 */
@CompileStatic
class GsPathFactory extends FileSystemPathFactory {

    @Override
    protected Path parseUri(String uri) {
        if( !uri.startsWith('gs://') )
            return null
        final str = uri.substring(5)
        final p = str.indexOf('/')
        String userProjectId = 'PROJECTID'
        return ( p==-1
                ? CloudStorageFileSystem.forBucket(str, CloudStorageConfiguration.builder().userProject(userProjectId).build()).getPath('')
                : CloudStorageFileSystem.forBucket(str.substring(0,p), CloudStorageConfiguration.builder().userProject(userProjectId).build()).getPath(str.substring(p)) )
    }
}
```

**Comment by emi80** [comment]
Hey @pditommaso,

I am finally giving a try at implementing this. As I would definitely consider it as opt-in, I was wondering what would be better in terms of config attribute specification:

- add a `useRequesterPays` boolean attribute that, when true, makes `google.project` the requester pays project
- add a `requesterPaysProject` string attribute that, when set, is used as the requester pays project

The first is nicer if the requester pays project is the same as the main project, while the second would allow to have a different project for requester pays calls. I am not sure whether the second is a common use case...

**Comment by pditommaso** [comment]
What I'm missing here is what happens when trying to access such bucket without specifying the project id.

**Comment by emi80** [comment]
This is the error I get when I run `gsutil ls <bucket>` on a bucket with requester pays set:
```
BadRequestException: 400 Bucket is requester pays bucket but no user project provided.
```

**Comment by pditommaso** [comment]
Ok, but it can provided any user project? @moschetti maybe can help to highlight which is the common use case for this option.

**Comment by emi80** [comment]
As far as I know the most common use case is for data owners to make data accessible to everyone without having to pay every time someone reads or copies the data from a different region.

I think any user project can be used as the billing project.

**Comment by moschetti** [comment]
Any project where a user has the permissions associated with [roles/serviceusage.serviceUsageConsumer](https://cloud.google.com/iam/docs/understanding-roles#service-usage-roles) can be used as the project. The common use case though is for all use of a workflow (compute, storage, networking, egress, etc) to be charged to the same project. But since we're in this code now, it would be good to add that support in case I'm missing a use case to avoid having to context switch back to this later.

My preference would be the following:

* `google.useRequesterPays` is a boolean 
* `google.requesterPaysProject` is an optional string
* If the boolean is set to `true`, and no `google.requesterPaysProject` is set, then the `google.project` is used as the default, but if a user sets a `google.requesterPaysProject` then it overrides default
 
If that's not feasible, I think the proposed implementation above of assuming `google.project` to be the project used would be reasonable.

**Comment by emi80** [comment]
Hi @moschetti,
what you propose seems reasonable to me and is definitely feasible. Let's see what @pditommaso says about it.

**Comment by pditommaso** [comment]
The possibility to specify a paying projet other the current one would be nice, but it would open a nightmare on the implementation side because we should differentiate each GS file access and apply the corresponding paying project. 

I would suggest to keep it simple and only provide the ability to enable this feature using the launching project as the original request.

**Comment by pditommaso** [comment]
Tho no sure with the option naming. `useRequesterPays` is ambiguous on what the requests, what about: 
1. `requesterPaysBucketAccess`  
2. `allowRequerPayBuckets`
3. other?

**Comment by emi80** [comment]
I think that `requesterPays` is clearly related to storage and specifically to bucket access. Anyway I like `allowRequesterPaysBuckets` or alternatively we could simply have `requesterPaysBuckets`.

**Comment by pditommaso** [comment]
Ok, let's go with `enableRequesterPaysBuckets` then.

**Comment by pditommaso** [comment]
Solved
