### ISSUE TITLE
Weblog resume field should convey runName/runId if provided

### ISSUE THREAD

**Issue by lepsalex** [nextflow-io/nextflow#1467]
### Expected behavior and actual behavior

When resuming a run by passing a `runId` or `runName` (ex. `nextflow run main.nf -resume UUID-OR-RUN-NAME`) the weblog for the workflow event should contain the name/id under the `resume` field. Instead we only get a true/false.

### Steps to reproduce the problem

Resume a job (`nextflow run main.nf -resume UUID-OR-RUN-NAME`) with weblog setup in your config and observe the events being generated.

### Program output 
```
...
"stats": { ... },
"resume": true,
"success": true,
...
```

### Environment 

* Nextflow version: 19.10.0 
* Java version: openjdk 11.0.6 2020-01-14
* Operating system: linux (manjaro)

**Comment by nkrumm** [comment]
FWIW, you may be able to work around this issue by passing a URL parameter in your weblog url:


`nextflow run main.nf -config nextflow.config -with-weblog 'http://your.endpoint.com/api/v1/weblog?resumeArn=UUID-OR-RUN-NAME' -with-trace -resume UUID-OR-RUN-NAME`

Your `/weblog` endpoint can then link incoming data with resumed runs. We use this in production to pass additional metadata to the weblog endpoint.

**Comment by pditommaso** [comment]
Future devs will be focused on [Tower](https://github.com/seqeralabs/nf-tower) client.
