### ISSUE TITLE
publishDir: specify target path dynamically using a closure

### ISSUE THREAD

**Issue by huguesfontenelle** [nextflow-io/nextflow#1469]
## New feature

Ability to publish files in different folders, and/or rename them with a condition

## Usage scenario 

```
publishDir path: { it == 'foo' ? "/some/path/foo" : "/some/where/else"  }
```

```
publishDir "/some/path",  saveAs: { it == 'bar' ? "bar.renamed" : it  }
```

or both.
For renaming I could `saveAs: { it.replaceFirst(/bar\//, "bar.renamed") }` but this then applied to all files.

## Suggest implementation 

(Highlight the main building blocks of a possible implementation and/or related components)

**Comment by bentsherman** [comment]
This should already be possible with the `saveAs` option, in fact the second usage scenario you gave should work just fine. Did that not work for you?

**Comment by huguesfontenelle** [comment]
You're right, it works fine.

Not sure what went wrong the other day, sorry.
