### ISSUE TITLE
Unable to specify nextflow script when using full URL of a project

### ISSUE THREAD

**Issue by mozack** [nextflow-io/nextflow#1470]
## Bug report 

Unable to specify nextflow script when using full URL of a project.  This is related to: #1118 

### Steps to reproduce the problem

The following works fine:
```
nextflow run mozack/nf-test/test2.nf
N E X T F L O W  ~  version 19.10.0
Launching `mozack/nf-test` [festering_dubinsky] - revision: 17a7008d10 [master]
test2
```

However, when the full URL is specified, I get:
```
nextflow run https://github.com/mozack/nf-test/test2.nf
N E X T F L O W  ~  version 19.10.0
Can't find git repository config file -- Repository may be corrupted: /home/lmose/.nextflow/assets/mozack/nf-test/test2.nf
```

### Environment 

* Nextflow version: 19.10.0
* Java version: 1.8.0_144
* Operating system: Centos7

### Additional context

This is an issue for us because we are using our own Gitlab repository with a directory hierarchy above the workflow definition and would like to be able to run specific Nextflow scripts.

i.e.
` nextflow run https://sc.unc.edu/lbg/workflows/nextflow/rna-seq-quant/rna_seq_quant.nf`
or
` nextflow run https://sc.unc.edu/lbg/workflows/nextflow/rna-seq-quant/rna_seq_quant_summary.nf`

The following works fine for a single script:
` nextflow run https://sc.unc.edu/lbg/workflows/nextflow/rna-seq-quant`

Alternatively, being able to run the above without the URL, may be an option, but currently does not work:
```
nextflow pull https://sc.unc.edu/lbg/workflows/nextflow/rna-seq-quant/ -user XXXX
Checking https://sc.unc.edu/lbg/workflows/nextflow/rna-seq-quant/ ...
Enter your unc_gitlab password: 
Already-up-to-date - revision: bbc488c249 [master]

nextflow run lbg/workflows/nextflow/rna-seq-quant/
N E X T F L O W  ~  version 19.10.0
Not a valid project name: lbg/workflows/nextflow/rna-seq-quant/

nextflow run lbg/workflows/nextflow/rna-seq-quant/rna_seq_quant.nf
N E X T F L O W  ~  version 19.10.0
Can't find git repository config file -- Repository may be corrupted: /home/lmose/.nextflow/assets/lbg/workflows
```

**Comment by dantefff** [comment]
In fact runing from a plain git repository over ssh also would be very appreciated

**Comment by dantefff** [comment]
This issue is still active

**Comment by emi80** [comment]
> In fact running from a plain git repository over ssh also would be very appreciated

Hi @dantefff, 

I am also interested in running a pipeline from a git repository over ssh. I mostly see the use case where I have bare repository on my server and ask `nextflow` to pull it locally and run it. 
Were you thinking about other possible use cases?

**Comment by pditommaso** [comment]
A new `-main-script` option has been added to the `run` command as of version 20.09.1-edge` to support this use case. Closing this.
