### ISSUE TITLE
.collectFile(... sort: true, ...) fails to sort the data as expected.  

### ISSUE THREAD

**Issue by alanhoyle** [nextflow-io/nextflow#1472]
### Expected behavior and actual behavior

I'm trying to combine multiple files together using the collectFile() operator.  The sort parameter appears to base the sort on the filename or file name hash value, not the contents/lines in the files.  

Further note:  the [collectFile() documentation](https://www.nextflow.io/docs/latest/operator.html#collectfile) fails to mention that any values aside from "`true`" or "`false`" for the `sort: VALUE` need to be quoted.  i.e. you need to do `sort: 'deep'` to have it do anything else.

It appears that `sort: 'hash'` gives varied output depending on the run.  

### Steps to reproduce the problem

Clone this git repository:
    https://github.com/alanhoyle/nf-sort-problem
then
   `nextflow run collectsort.nf`

### Program output 

In the github above, look at the `expected.txt` for expected output, and the `actual_*.txt` for the results from a given `sort: 'ENTRY'`

### Environment 

* Nextflow version: 19.10.0 build 5170
* Java version: 1.8.0_231
* Operating system: tested on macOS Catalina and  RedHat

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Yes, correct. The sort is applied to the elements emitted by channel, that in your case are file path objects, not to the file content for performance purpose (expect when using `deep` which however sort the file content by the content hash code and therefore it's not a lexicographic sorting). 

If you want to sort by the file content use `sort: { file -> file.text }` 

(I've fixed the docs regarding the use of quoted values, thanks for reporting)
