### ISSUE TITLE
Nextflow-HTCondor works without a shared filesystem?

### ISSUE THREAD

**Issue by lmichael107** [nextflow-io/nextflow#1473]
## New feature

Either: Have Nextflow work with HTCondor *without* requiring shared filesystem across the HTCondor Cluster by using HTCondor's file transfer mechanism (for input and software), -OR- add notes to the Nextflow documentation (Requirements, and HTCondor description) specifying that a shared filesystem is required, given that HTCondor can work (an is commonly configured to work) without a shared filesystem.

## Usage scenario 

Many HTCondor clusters are configured without a single shared filesystem across all worker nodes, which is an distinguishing and commonly-implemented feature of HTCondor. It's currently unclear in the documentation that (1) Nextflow requires a shared filesystem, regardless of the "Executor", and that (2) Nextflow will not work with HTCondor cluster's that use HTCondor's file transfer mechanism instead of a shared filesystem. Ideally, Nextflow WOULD be made to work with HTCondor's file transfer mechanism (which can also be invoked even in the context of a shared filesystem).

## Suggest implementation 

Nextflow would need to communicate necessary software and input files to be transferred for each job, using existing HTCondor submit file options, and may benefit from using them also to dictate specific output to be transferred back to the submission server.

**Comment by pditommaso** [comment]
A pull request is welcome!

**Comment by lmichael107** [comment]
A pull request for updating the documentation? I guess part of what I'm looking for, here, is a decision from the developers on which route - clarification in documentation, and/or feature addition to fully integrate with HTCondor (which is probably more than a quick pull request, and which I'm definitely not capable of) - they'd like to pursue. If the latter, I work with the HTCondor team and can help make connections for discussions that would guide the most appropriate integration solution.

**Comment by pditommaso** [comment]
Sorry, I was on mobile and I had misread your request. I will add a note in the HTCondor executor documentation mentioning in an explicit manner the need for a shared file system to avoid doubts. 

However, I agree that a proper support HTC file transfer mechanism would a better solution. Any contribution in this direction is welcome.

**Comment by pditommaso** [comment]
Added a note a this regard. See f0af66de493f0e2abf0bd60f1482725b260655b4.

**Comment by lmichael107** [comment]
I can contribute by connecting you with the HTCondor development lead (my colleague) if that will be helpful? I'd be happy to join a first conversation.

**Comment by pditommaso** [comment]
Thanks for that. As core maintainer, I can provide advice on NF internals but I don't have resources to allocate on the implementation of this feature. Somebody in the community needs to take the lead.

**Comment by pditommaso** [comment]
Updated requirements 0add7b88.

**Comment by lmichael107** [comment]
@toddtannenba

**Comment by chasemc** [comment]
Think that was supposed to be @tannenba
