### ISSUE TITLE
Pre-flight modules

### ISSUE THREAD

**Issue by SergejN** [nextflow-io/nextflow#1476]
## New feature

On some cluster systems (like ours), Singularity/Docker are only available if you load them with 'module load'. However,  if the NextFlow pipeline specifies a Singularity/Docker image file, which should be pulled from a remote library, it fails because by the time "singularity pull" is executed the module is not loaded, yet. It can of course be simply solved by loading the singularity module before running the pipeline, but it would be convenient to include a list of pre-flight modules to load at startup.

**Comment by bentsherman** [comment]
I get around this on my cluster by putting `module load singularity` in my `.bashrc`. Since it should always be there anyway I have no problem with always loading it upon login.

**Comment by pditommaso** [comment]
Docker/singularity/etc are expected to be provided/configured by the hosting env.
