### ISSUE TITLE
Job array for more efficient SGE cluster management

### ISSUE THREAD

**Issue by mgandal** [nextflow-io/nextflow#1477]
I am using nextflow with a SGE task scheduler. I've noticed that the pipeline submits many very similar jobs that are batched across a number of samples (e.g., FastQC on hundreds of RNA-seq files with the nextflow/rnaseq pipeline). Some job schedulers cannot handle this many jobs being submitted at a time. I know there are ways to reduce the speed and frequency of job submission. However, it would be much more efficient to be able to use job arrays for these highly repetitive tasks.
E.g., `qsub -t 1:400 this_task`

**Comment by tbugfinder** [comment]
I'm also interested in support of array jobs for Slurm and AWS Batch. I' wondering if the foundation for all executors is within one class or if this has to be implemented per executor.

https://github.com/nextflow-io/nextflow/issues/1427

**Comment by tbugfinder** [comment]
https://slurm.schedmd.com/job_array.html

**Comment by KevinSayers** [comment]
I think you can make this work currently using clusterOptions and the task id environment variable for the scheduler. Toy example below for slurm. 

```
process foo{                                                                                                                                                                                          
   time '5m'                                                                                                                                                                                          
   executor 'slurm'                                                                                                                                                                                   
   clusterOptions '--array=1-10'                                                                                                                                                    
                                                                                                                                                                                                     
   '''                                                                                                                                                                                                
   echo ${SLURM_ARRAY_TASK_ID} > new_${SLURM_ARRAY_TASK_ID}.txt                                                                                                                                       
   '''                                                                                                                                                                                                
}  
```

**Comment by pditommaso** [comment]
Job array does not match NF design by which each task should have its own work dir. No plan in the short/medium term.

**Comment by idot** [comment]
> I think you can make this work currently using clusterOptions and the task id environment variable for the scheduler. Toy example below for slurm.
> 
> ```
> process foo{                                                                                                                                                                                          
>    time '5m'                                                                                                                                                                                          
>    executor 'slurm'                                                                                                                                                                                   
>    clusterOptions '--array=1-10'                                                                                                                                                    
>                                                                                                                                                                                                      
>    '''                                                                                                                                                                                                
>    echo ${SLURM_ARRAY_TASK_ID} > new_${SLURM_ARRAY_TASK_ID}.txt                                                                                                                                       
>    '''                                                                                                                                                                                                
> }  
> ```

I tried this and i think the task finishes as soon as the first array task finishes. The other tasks continue to run, but the results will not be in the output.

**Comment by krokicki** [comment]
I just wanted to add a vote for this feature and add some more rationale. 

Nextflow is a great workflow language, but it's hard to justify its claim of scalability if it cannot handle more than ~500 concurrent jobs, as demonstrated here: https://www.biorxiv.org/content/10.1101/2021.04.03.437906v1.full.pdf  

I've reproduced the same result with LSF, and it's not very surprising given that job schedulers are not meant to function at scale for individual jobs. With array jobs on LSF, we can efficiently submit many thousands of jobs, which is the level of parallelism required for effectively working with data that's hundreds of terabytes in size.

That being said, I can definitely see how it's not trivial to square with the current task design.

For anyone else looking for a stop-gap solution, there's this awesome hack on the Gitter:
https://gitter.im/nextflow-io/nextflow?at=5f736648f41f4105e4e5a0b4

**Comment by pditommaso** [comment]
I don't think that benchmark is accurate and looking at the implementation, I'm quite convinced that the problem is caused by wrong use of the `maxForks` directive 

https://github.com/pditommaso/scalability-tst/commit/41ddbf2224832c713aee5b8920c5fcb4059c2d3a

NF can scale well beyond the 500 parallel tasks. I'm not even convinced that array jobs are much more efficient than normal jobs, the scheduler should in any case track their status independently.

**Comment by krokicki** [comment]
Thanks for debunking that. I double checked my own tests and it seems that I was running up against executor.queueSize, which has a default of 100. Increasing this helped a ton. 

But still, as far as I can tell, independent jobs don't come close to array jobs in job submission performance.

Here's a benchmark I just ran on our mostly-empty LSF cluster:

```
#!/bin/bash
echo "Running job#$LSB_JOBINDEX on "`hostname`
sleep 5
echo "Done"
```

`bsub -J "scale_test[1-1000]" -o $PWD/output/output.%I $PWD/scale.sh`

The job submission is instantaneous, and the time from invocation to the final job finishing was **1m1s**. I ran the test two more times and got 55s and 53s.

I tried this with Nextflow:
```
counter_channel = Channel.of(1..1000)
process test {
    input:
    val counter from counter_channel
    """
    echo "Running job#$counter on "`hostname`
    sleep 5
    echo "Done"
    """
}
```

My nextflow.config:
```
executor {
    queueSize = 1000
    pollInterval = "2 sec"
}
```

Nextflow reports **3m2s** for the workflow. When I reran I got 3m4s and 3m30s.

This is mainly due to overhead for individually submitting the jobs. It's about 2.5 minutes before the job counter ticks up to 1000. I see basically the same behavior with a bash loop: each bsub has some ~130ms latency and this just adds up.

**Comment by pditommaso** [comment]
NF is designed for large grain tasks parallelisation, not for short live task executions. Therefore this magnitude of overhead is somehow expected since it would have a minimal impact on the overall pipeline duration.

**Comment by krokicki** [comment]
Makes sense. I just wanted to shed some more light on the use case, in case there is some redesign or extension in the future that could address it. Thanks for considering!

**Comment by pditommaso** [comment]
Thanks for your feedback!

**Comment by tardigradus** [comment]
> I don't think that benchmark is accurate and looking at the implementation, I'm quite convinced that the problem is caused by wrong use of the `maxForks` directive
> 
> [pditommaso/scalability-tst@41ddbf2](https://github.com/pditommaso/scalability-tst/commit/41ddbf2224832c713aee5b8920c5fcb4059c2d3a)
> 
> NF can scale well beyond the 500 parallel tasks. I'm not even convinced that array jobs are much more efficient than normal jobs, the scheduler should in any case track their status independently.

Just some information about the effect of submitting a large number of individual jobs with Slurm.  Each job has to be entered into the database as soon as it is submitted and each job, whether pending or running, is listed individually in the list of jobs produces by ```squeue```.  Thus, the submission of a large number of jobs within a very short time can make the database  become unresponsive and will make the list of pending jobs become very long.

On the other hand, when the jobs are submitted via a job array, all pending jobs are represented as a single database entry and only get an individual entry once running.  In the job list, pending array jobs can be listed as a single line.

Thus, from the point of view of the system admin, it is much more desirable if a large number of jobs is submitted as a job array. In particular, the creation of job entries in the database is actually more efficient for a job array (assuming there are not enough resources for all the jobs to start immediately).

**Comment by pditommaso** [comment]
Let's re-open this

**Comment by pditommaso** [comment]
A challenging aspect of implementing the support for job array is that Nextflow is modelled around the idea that a job a *function* with no side effects. 

In practical terms, this means each job needs to be assigned its own work directory so that outputs do not overlap each other. 

How is the working directory managed for jobs array with SGE or Slurm? I guess child jobs in the array they all have allocated with the same work directory.

**Comment by tardigradus** [comment]
For each element of a Slurm job array, the environment variable ```SLURM_ARRAY_TASK_ID``` contains the value of the index.  This can then be used to construct unique subdirectory names.

**Comment by tardigradus** [comment]
Looking at this again, I wonder whether it is not already possible to use Slurm job arrays.  If I write ```clusterOptions = '--array=0-999'```, can't I make use of ```SLURM_ARRAY_TASK_ID``` in my Slurm batch script and start each job in the array with, say, its own input and output directory?

Essentially this would just entail moving the lowest level of pipeline granularity (say a loop over the values of a parameter) out of nextflow into Slurm.

WDYT?

**Comment by pditommaso** [comment]
This could work provided, but I guess the aim of this issue is to provide more native integration with jobs array. 

Somehow related to this there's an interesting proposal to add the support for [HyperQueue](https://github.com/It4innovations/hyperqueue) to Nextflow, which looks like to provide a solution to the handling of high jobs throughput that better fits the nextflow model. 
 
https://github.com/nextflow-io/nextflow/issues/2867

**Comment by tardigradus** [comment]
> This could work provided, but I guess the aim of this issue is to provide more native integration with jobs array.
> 
> Somehow related to this there's an interesting proposal to add the support for [HyperQueue](https://github.com/It4innovations/hyperqueue) to Nextflow, which looks like to provide a solution to the handling of high jobs throughput that better fits the nextflow model.
> 
> #2867

According to [this information](https://it4innovations.github.io/hyperqueue/v0.11.0/jobs/arrays/) while [HyperQueue](https://github.com/It4innovations/hyperqueue) does support job arrays, it does not make use of the job array mechanism provided by Slurm.  Therefore it does not (currently) address the issue raised here.

**Comment by emyr666** [comment]
One of the main benefits of job arrays is that they reduce the size of the scheduling processing queue.  Slurm - and no doubt tother schedulers -  has specific performance improvements implemented regarding job arrays. Also when looking for jobs that can potentially backfill, it constiders a certain number of jobs at the top of the scheduling queue. A job array fills one slot in this list so it can potentially get a chance to consider far more different types of job for backfilling when using job arrays. This is needed to fill as much of the potential of the cluster with useful work as possible. Without this you end up with a lot of scheduling gaps wasting the potential of a cluster,  money spent on buying it and electricity cost in running it.

**Comment by tardigradus** [comment]
I hadn't been aware of the potential problem with backfilling.  That is also something we would take very seriously as Nextflow allows relatively inexperienced users, who might overestimate their job requirements, to generate a large number of jobs without using a job array.  Without Nextflow, the users will have to code some other mechanism for submitting jobs, so these users will tend to be rather more advanced.  Although that is still also no guarantee that they will get their job requirements right, it is usually easier to explain the problem to them.

**Comment by pditommaso** [comment]
something advanced like: 

```
for x in {1..1000000}; do 
  qsub my-job.sh
done
```

**Comment by muffato** [comment]
Can the LSF label be added ? LSF also understands (and prefers) job arrays

**Comment by santy-ttam** [comment]
Hi Paolo, 

I think at the scale we are using NF at ttam, we would really benefit from this. We are currently being bottlenecked by UGE as it takes like 5-10 mins to submit 1,000 jobs (while as an array job it should take a second). As a result often we are resulting in jobs submitting faster than UGE can queue them.

**Comment by wookietreiber** [comment]
I'm a sysadmin of an HPC cluster. We ran SGE/UGE in the past and are currently using SLURM. I can confirm that it's far more efficient for scheduling systems to use array jobs than `for` looping `qsub` or `sbatch`. For this reason, to encourage our community to use array jobs, we even set default per-user job/submission limits, so we don't get spammed by non-array jobs, e.g. via `MaxSubmitJobsPerUser` in SLURM. This can obviously conflict with the way nextflow currently works and is another reason for first-class support of array jobs in nextflow.

**Comment by tardigradus** [comment]
> For this reason, to encourage our community to use array jobs, we even set default per-user job/submission limits, so we don't get spammed by non-array jobs, e.g. via `MaxSubmitJobsPerUser` in SLURM.

Does this actually work?  My understanding of https://bugs.schedmd.com/show_bug.cgi?id=3409 is that each array task is treated as a single job w.r.t. limits such as ```MaxSubmitJobsPerUser```. Is this not the case?

**Comment by bentsherman** [comment]
We're thinking about implementing job arrays in the form of a new executor (e.g. `array` or `batch` executor) which, given a "target" executor and batch size, submits tasks to the target executor as array jobs. So you spend a little more time waiting for enough tasks to be created before submitting them, but then you hopefully save more time by submitting them as array jobs.

It looks like the executors people have requested so far are:
- SLURM
- SGE
- LSF
- AWS Batch

Also I know from experience that PBS supports job arrays.

The main thing I'm wondering is, how do you specify resources for array jobs? If people could chime in for their executor, that would be great. For example, if I was going to submit an array job with 1000 tasks and 1 cpu + 2 GB mem + 1 hr walltime per task:

1. What would the submit options look like?
2. Would the walltime constraint apply to the entire array job or each task independently (or maybe that doesn't matter if they all start at the same time)?

**Comment by tardigradus** [comment]
I'm glad to see this going forward.

> The main thing I'm wondering is, how do you specify resources for array jobs? If people could chime in for their executor, that would be great. For example, if I was going to submit an array job with 1000 tasks and 1 cpu + 2 GB mem + 1 hr walltime per task:
> 
>     1. What would the submit options look like?
```
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G
#SBATCH --time=01:00:00
#SBATCH --array=0-999
```

>     2. Would the walltime constraint apply to the entire array job or each task independently (or maybe that doesn't matter if they all start at the same time)?

All parameters except ```--array``` apply to each element of the array, so specifically, the walltime constraint of one hour applies to each element.  In general, the elements of an array will not start at the same time.

**Comment by muffato** [comment]
On LSF, the CPU, runtime, and memory requirements apply to the individual tasks.

The parameters are passed the same way as for individual tasks, but with an extra one:
```
#BSUB -J array_name[1-1000]
```
You can choose how to name the array elements. The above is 1-based, but `0-999` should work too.

**Comment by bentsherman** [comment]
Thanks guys. I have some more questions:

- Does the array job have it's own status in the scheduler? I would rather just check that instead of checking each job individually, if possible.

- What happens if some of the child jobs fail? Does the whole thing fail, or would the other child jobs be allowed to complete?

**Comment by muffato** [comment]
On LSF, if you do `bjobs <array-job-id>` you'll see 1 row per child job that is not done yet. I don't think arrays have an overall status, therefore the array wouldn't "fail" if a child job fails. After submission, all child jobs run independently from one another.

**Comment by bentsherman** [comment]
Does that mean that, if I want to kill the array job, I have to kill all the child jobs individually?

**Comment by muffato** [comment]
All LSF commands still accept the job_id of the array and apply the command of all child jobs. For instance `bkill 1234` is equivalent to `bkill 1234[1]; bkill 1234[2]; (...)`

**Comment by tardigradus** [comment]
> Thanks guys. I have some more questions:
> 
>     * Does the array job have it's own status in the scheduler? I would rather just check that instead of checking each job individually, if possible.

For Slurm, AFAIK, not as such.  The elements of the array are still just jobs.  Some elements of the array could be pending, some could be running, whilst others could have already completed.

>     * What happens if some of the child jobs fail? Does the whole thing fail, or would the other child jobs be allowed to complete?

In Slurm, they are not really child jobs, but just associated jobs and, as such, potentially fully independent of one another, so one job failing does not necessarily affect another. However, it is possible to define dependencies between jobs, if one so wishes.  For example, you might want some jobs only to start if other previous jobs have completed successfully.

**Comment by emyr666** [comment]
If you do qdel in SGE or scancel in slurm giving just the ID of the job
array itself it will kill all currently running and yet to be run subtasks.
Don't forget to add the ability to limit the number of concurrent tasks
which may be important if you don't want to swamp the IO for example. use
-tc on SGE and % x in the array limit spec in slurm.
For me, as well as submit efficiency, the improvement in backfilling is an
important reason to add job array support.

This should well be another issue but since I am not fully up to speed with
the internals of nextflow yet it may be irrelevant....
 If adding job array support is it also possble to add job dependency
support too?

One of the advantages of this is that you can queue the pipeline all up at
once right at the start. The more you tell the scheduler what is coming the
better it can pack the jobs in and reduce scheduling gaps.It also allows
the submitted dependent jobs to accrue priority as they wait which means
less waiting around in the queue for the bits of the pipeline yet to run.

**Comment by bentsherman** [comment]
I think the initial support will focus on just the submission, since it seems like in every case the array "child" jobs behave like regular jobs after they are submitted. We may also support batch killing, but Nextflow already has a mechanism for that so it might not be needed.

As for dependencies, I think we will consider that in a separate effort if at all. We can only tell the scheduler about dependencies as soon as Nextflow knows about them, and in general Nextflow discovers the full dependency graph as it goes (e.g. because a task could produce a dynamic set of files that trigger a dynamic set of downstream tasks).

**Comment by bentsherman** [comment]
Folks, I have added tentative support for several grid executors in the linked PR: SLURM, LSF, PBS, and SGE. For each executor I have defined:
- the array job CLI option (`getArrayDirective()`)
- the array index environment variable (`getArrayIndexName()`)
- the array job child ID (`getArrayTaskId()`)

Please feel free to check the relevant code for your executor and make sure it is correct. You can comment directly on the code if something is wrong. I pieced everything together from the comments here and the documentation for each scheduler.

Later I will ask for volunteers to test this new feature on their cluster...

**Comment by bentsherman** [comment]
Can I have some volunteers test the array job PR on their cluster? We only have a SLURM environment for testing, so we need people to test on LSF and SGE.

Here's how to build and test the PR:
```bash
# build
git clone -b 1477-job-array-executor git@github.com:nextflow-io/nextflow.git
cd nextflow
make compile

# test
./launch.sh run <script> ...
```

**Comment by ThankGodE** [comment]
> Can I have some volunteers test the array job PR on their cluster? We only have a SLURM environment for testing, so we need people to test on LSF and SGE.
> 
> Here's how to build and test the PR:
> 
> ```shell
> # build
> git clone -b 1477-job-array-executor git@github.com:nextflow-io/nextflow.git
> cd nextflow
> make compile
> 
> # test
> ./launch.sh run <script> ...
> ```

I'm just wondering if job array submission on SLURM is now fully implemented in Nextflow? I can't seem to find it in the documentation yet andI'm wondering if this is still at the testing phase?

**Comment by bentsherman** [comment]
Hi @ThankGodE , it's still just a PR, so if you want to test it then you'll have to build Nextflow from the PR branch and run it that way, using the instructions you quoted. But the SLURM array job support is fully implemented in the PR.

**Comment by ahstram** [comment]
HI @bentsherman , just FYI, my colleague @protocellular tested the 1477-job-array-executor branch on our Altair Grid Engine cluster (AGE is a successor to SGE, and should be 100% relevant to SGE support). There are some minor changes that are necessary, but otherwise it seems to be working smoothly. She'll submit a PR with the needed changes when we've finished our testing.

Thanks,

Alexander Stram
Associate Director, Bioinformatics Engineering
Personalis, Inc.

**Comment by ahstram** [comment]
Also-- it may be necessary for certain schedulers to automatically whitelist certain variables via envWhitelist (#803).

In SGE is it difficult to use array jobs effectively without accessing ${SGE_TASK_ID}, so perhaps scheduler specific variables like ${SGE_TASK_ID} should be white listed to containers by default, rather than having to be specified in nextflow.config manually?

Alexander Stram
Associate Director, Bioinformatics Engineering
Personalis, Inc.

**Comment by bentsherman** [comment]
@ahstram any update on your testing? I have since added the SGE_TASK_ID to the whitelist, and I found a bug where the array index was starting at 0 instead of 1. Some clusters are zero-based and some aren't. If you found any other issues, you can also just report them here, if that would be easier than trying to fix it yourself.

**Comment by ahstram** [comment]
Hi @bentsherman , yes, the zero-base indexing was one thing we had to change. I'll defer to @protocellular for more. We had to pivot over to novel functionality development recently, but should be coming back to array job support as we move into the optimization phase of our latest product.

Alexander Stram
Associate Director, Bioinformatics Engineering
Personalis, Inc.

**Comment by toniher** [comment]
Hi,

I'm making a try in the test branch for SGE:

I added this below in nextflow.config:
`clusterOptions = '-t 2-10'`

but I am receiving this error:
```
Caused by:
  Invalid SGE submit response:
90741210.2-10:1




Command executed:

  qsub -terse .command.run
```
What am I doing wrong?

**Comment by bentsherman** [comment]
Hi @toniher , you don't need to specify the SGE array job options, just add `array 10` to your process (or `process.array = 10` to your config) and Nextflow will take care of the rest.

**Comment by emyr666** [comment]
but then the array would start from 1 not 2. also, what about the -tc option which lets you control concurrency. for instance I use this for a job array that loads data into a database across the array. i set tc to 16 so that I don't swamp the database server with anymore than 16 loads at a time

**Comment by emyr666** [comment]
i do the same on a slurm cluster but it has different syntax e.g. --array=0-64%16

**Comment by toniher** [comment]
> Hi @toniher , you don't need to specify the SGE array job options, just add `array 10` to your process (or `process.array = 10` to your config) and Nextflow will take care of the rest.

I pulled ``https://github.com/nextflow-io/rnaseq-nf`` ,  added ```process.array = 10``` in nextflow.config and run `` ./launch.sh run rnaseq-nf``, but jobs and whole Nextflow seem to get stuck.
I am not sure if I see anything about arrays in ``.command.sh``, though:

```
#!/bin/bash
#$ -N nf-RNASEQ_FASTQC_(FASTQC_on_null)
#$ -o /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/0c/947fd163d14a7092abd2161bdfdcb2/.command.log
#$ -j y
#$ -terse
#$ -notify
```

**Comment by bentsherman** [comment]
@emyr666 why would you need to start from 2? The array index is only used internally by Nextflow, not meant to be used by the task script, so it shouldn't matter. As for concurrency, that might be something we need to add, e.g. `array 64, parallel: 16`. You could also use `maxForks` to limit the total number of parallel tasks for a process, would that be enough?

@toniher can you try the test pipeline that I have in #3892 ? And check the `.nextflow.log` for any errors when you run it.

**Comment by bentsherman** [comment]
I think Nextflow will probably still fail on SGE because it won't recognize the array job id format::
```
Invalid SGE submit response:
90741210.2-10:1
```

We'll have to improve the regex to accommodate the array job id.

**Comment by emyr666** [comment]
> You could also use `maxForks` to limit the total number of parallel tasks for a process, would that be enough?

These jobs are not parallel. They just wake up on a node, see what the SGE_TASK_ID is and do the appropriate thing. They wll start whenever there is a slot so sometimes only one mayy be running, then none for a bit, a few more may get slots etc. etc. This is just saying that at any one time no more than 16 should be allowed to run so it could be any number between 0 and 16 depending on what is going on with the cluster at the time. The array syntax for both SGE and slurm allows you to specify

For slurm the docs have this : 

# Submit a job array with index values between 0 and 31
$ sbatch --array=0-31    -N1 tmp

# Submit a job array with index values of 1, 3, 5 and 7
$ sbatch --array=1,3,5,7 -N1 tmp

# Submit a job array with index values between 1 and 7
# with a step size of 2 (i.e. 1, 3, 5 and 7)
$ sbatch --array=1-7:2   -N1 tmp

So there needs to be a start index, a stop index and a stride index, or the possibility to enter a list.

grid engine has similar functionality, again from the docs...

qsub -l h_cpu=0:45:0 -t 2-10:2 render.sh data.in

-t option defines the task index range. In this case, 2-10:2 specifies
that 2 is the lowest index number, and 10 is
the highest index number. Only every second index, the :2 part
of the specification, is used. Thus, the array job is made up of 5
tasks with the task indices 2, 4, 6, 8, and 10. Each task requests
a hard CPU time limit of 45 minutes  with the -l option.
Each task executes the job script render.sh once the task is dispatched and started by the grid engine system.
Tasks can use SGE_TASK_ID to find their index number,
which they can use to find their input data record in the data file data.in

The slurm version is more powerful because you can run it with a full array spec with low resources, then if any fail by being out of time or using up too much ram you can do the array job again but only specifying the failed indices and asking for more ram 7 runtime for instance to get the last few through.

**Comment by toniher** [comment]
> @toniher can you try the test pipeline that I have in #3892 ? And check the `.nextflow.log` for any errors when you run it.

Things seem to get stuck, and I don't get any error in the process ```workdir```.
I see in ``.nextflow.log`` that processes would seem to be submitted as job array:

```

de juny-30 19:16:03.380 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [CRG] submitted process foo (18) > jobId: 90741746; workDir: /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/47/89a50304008f8b29fa1c35e6b871e1
de juny-30 19:16:03.381 [Task submitter] INFO  nextflow.Session - [68/7659c5] Submitted process > foo (18)
de juny-30 19:16:03.383 [Task submitter] INFO  nextflow.Session - [5e/07f5fa] Submitted process > foo (20)
de juny-30 19:16:03.384 [Task submitter] INFO  nextflow.Session - [b0/141418] Submitted process > foo (24)
de juny-30 19:16:03.385 [Task submitter] INFO  nextflow.Session - [48/e77535] Submitted process > foo (17)
de juny-30 19:16:03.386 [Task submitter] INFO  nextflow.Session - [7b/5e1028] Submitted process > foo (19)
de juny-30 19:16:03.387 [Task submitter] INFO  nextflow.Session - [3d/43af34] Submitted process > foo (29)
de juny-30 19:16:03.389 [Task submitter] INFO  nextflow.Session - [35/b1989a] Submitted process > foo (27)
de juny-30 19:16:03.390 [Task submitter] INFO  nextflow.Session - [af/5d4cf5] Submitted process > foo (26)
de juny-30 19:16:03.391 [Task submitter] INFO  nextflow.Session - [fe/1c310a] Submitted process > foo (28)
de juny-30 19:16:03.392 [Task submitter] INFO  nextflow.Session - [13/e5a23a] Submitted process > foo (32)
de juny-30 19:16:05.553 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [CRG] submitted process foo (34) > jobId: 90741748; workDir: /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/0c/0c729f94cd5b636938dd66bafd1c28
de juny-30 19:16:05.554 [Task submitter] INFO  nextflow.Session - [d5/119fb9] Submitted process > foo (34)
de juny-30 19:16:05.555 [Task submitter] INFO  nextflow.Session - [14/630930] Submitted process > foo (31)
de juny-30 19:16:05.556 [Task submitter] INFO  nextflow.Session - [56/86fb52] Submitted process > foo (33)
de juny-30 19:16:05.557 [Task submitter] INFO  nextflow.Session - [33/098806] Submitted process > foo (35)
de juny-30 19:16:05.558 [Task submitter] INFO  nextflow.Session - [26/23e114] Submitted process > foo (30)
de juny-30 19:16:05.559 [Task submitter] INFO  nextflow.Session - [e9/6877bf] Submitted process > foo (44)
de juny-30 19:16:05.560 [Task submitter] INFO  nextflow.Session - [ec/783746] Submitted process > foo (36)
de juny-30 19:16:05.561 [Task submitter] INFO  nextflow.Session - [8e/a6e3e4] Submitted process > foo (37)
```
but nothing happens... The jobs appear in the queue and shortly after they die. Then I have to kill the launch process...

**Comment by bentsherman** [comment]
> This is just saying that at any one time no more than 16 should be allowed to run so it could be any number between 0 and 16 depending on what is going on with the cluster at the time.

@emyr666 this is what `maxForks` does, just add e.g. `maxForks 16` to your process

> The jobs appear in the queue and shortly after they die.

@toniher one thing you can try is to go to the array job work dir e.g. `work/47/89a50304008f8b29fa1c35e6b871e1` and run the array job directly: `qsub -terse .command.run`. Then see if you get any errors during submit or in the `.command.log`. You can also visit the child task directories defined in the array job's `.command.sh` and check their error logs.

**Comment by toniher** [comment]
> @toniher one thing you can try is to go to the array job work dir e.g. `work/47/89a50304008f8b29fa1c35e6b871e1` and run the array job directly: `qsub -terse .command.run`. Then see if you get any errors during submit or in the `.command.log`. You can also visit the child task directories defined in the array job's `.command.sh` and check their error logs.

When I try ``qsub -terse .command.run``, considering what I have in ``.command.sh``

```
#!/bin/bash -ue
array=( /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/68/7659c5ace329a4300fe74c4749f920 /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/5e/07f5fa4b6349c214efaec1603f884f /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/b0/1414188673455b47595e9e322d7b53 /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/48/e7753572090341806236874e9b4cd2 /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/7b/5e1028f8c1a4f8648343191daa98ae /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/3d/43af34c556659d38ba4e7dc51f33a1 /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/35/b1989ab655cd8c91f54467db842ccd /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/af/5d4cf587ce4610c834565c4e7ece61 /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/fe/1c310a69e319d34002b996d6b1a15c /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/13/e5a23a00fed9c56f63cc817d97e88a )
export task_dir=${array[SGE_TASK_ID - 1]}
bash -o pipefail -c 'bash ${task_dir}/.command.run 2>&1 | tee ${task_dir}/.command.log'
```
the error I get in ``.command.err`` is

```
/nfs/users/bi/thermoso/soft/nexflow/nextflow/work/47/89a50304008f8b29fa1c35e6b871e1/.command.sh: line 3: undefined: unbound variable
```
and in ``.command.log``

```
/nfs/users/bi/thermoso/soft/nexflow/nextflow/work/47/89a50304008f8b29fa1c35e6b871e1/.command.sh: line 3: undefined: unbound variable
TERM environment variable not set.
/nfs/users/bi/thermoso/soft/nexflow/nextflow/work/47/89a50304008f8b29fa1c35e6b871e1/.command.sh: line 3: undefined: unbound variable
TERM environment variable not set.
```

**Comment by bentsherman** [comment]
@toniher sorry for the delayed response. It looks like the array job script doesn't work in your environment, either `array` or `SGE_TASK_ID` is not defined on line 3. You'll have to play around with the script to see how to make it work. Can you figure out which variable isn't defined?

There are a few other ways to declare a bash array, such as `delcare -a array=...`. If you can find another syntax that works in your environment, maybe we can use that instead.

**Comment by muffato** [comment]
@toniher double check the indices of the array/job too. In my case (LSF) I got `undefined: unbound variable` at some point because of 0-based vs 1-based. That's been fixed, but perhaps SGE is a bit different

**Comment by toniher** [comment]
@bentsherman the script seems to be OK, the fact is that a simple `qsub -terse .command.run` does not work, and I need to define something like: `qsub -terse -t 1:n .command.run` to iterate through the array. It works then, but I suspect Nextflow is then not appending that `-t 1:n` bit.

@muffato SGE seems to be 1-based. 
```
qsub -terse -t 0-5 .command.run                         
Unable to run job: job rejected: 0 is an invalid task id.
Exiting.
```
I suspect that `${array[SGE_TASK_ID - 1]}` is actually taking care of that...

**Comment by bentsherman** [comment]
@toniher it turns out I added the 1-based index only half way. The array job script is correct but the header in `.command.run` was still 0-based. I just pushed a fix, try it again?

**Comment by toniher** [comment]
@bentsherman I pulled your last change https://github.com/nextflow-io/nextflow/commit/d4ab783dd354807f4889aceda87f2a010fb07932 but no luck running but no luck so far. Where should I check in `.command.run ` ?

**Comment by toniher** [comment]
Considering in `.nextflow.log`
```
de jul.-13 21:43:27.047 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [CRG] submitted process foo (1) > jobId: 90871167; workDir: /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/01/7bd5d2912e42c52dc72cdf5690b66a
de jul.-13 21:43:27.050 [Task submitter] INFO  nextflow.Session - [b1/1272c4] Submitted process > foo (1)
de jul.-13 21:43:27.055 [Task submitter] INFO  nextflow.Session - [45/02aefb] Submitted process > foo (9)
de jul.-13 21:43:27.057 [Task submitter] INFO  nextflow.Session - [76/25b3e8] Submitted process > foo (15)
de jul.-13 21:43:27.058 [Task submitter] INFO  nextflow.Session - [98/5fdb73] Submitted process > foo (13)
de jul.-13 21:43:27.060 [Task submitter] INFO  nextflow.Session - [c7/4db313] Submitted process > foo (10)
de jul.-13 21:43:27.061 [Task submitter] INFO  nextflow.Session - [98/902969] Submitted process > foo (16)
de jul.-13 21:43:27.062 [Task submitter] INFO  nextflow.Session - [f8/5329a8] Submitted process > foo (11)
de jul.-13 21:43:27.064 [Task submitter] INFO  nextflow.Session - [80/a76e34] Submitted process > foo (7)
de jul.-13 21:43:27.065 [Task submitter] INFO  nextflow.Session - [42/24f46b] Submitted process > foo (5)
de jul.-13 21:43:27.067 [Task submitter] INFO  nextflow.Session - [23/d325d8] Submitted process > foo (3)
```
Going to ``/nfs/users/bi/thermoso/soft/nexflow/nextflow/work/01/7bd5d2912e42c52dc72cdf5690b66a``

in `.command.run` I don't see any '#$ -t'.

in the header only this:

```
#!/bin/bash
#$ -N nf-foo_(1)
#$ -o /nfs/users/bi/thermoso/soft/nexflow/nextflow/work/01/7bd5d2912e42c52dc72cdf5690b66a/.command.log
#$ -j y
#$ -terse
#$ -notify
NXF_CHDIR=/nfs/users/bi/thermoso/soft/nexflow/nextflow/work/01/7bd5d2912e42c52dc72cdf5690b66a
# NEXTFLOW TASK: foo (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}
```

and grepping '\#\$ -t ' nowhere in work directory.

**Comment by bentsherman** [comment]
Looks like it's just not using array jobs. Are you sure they're enabled for process `foo`? Did you make any changes to the example pipeline?

**Comment by toniher** [comment]
@bentsherman this is what I have in test.nf:

```
params.n_tasks = 50

process foo {
    array 10

    input: val index
    output: path 'output.txt'

    """
    echo "Hello from task ${index}!" > output.txt
    """
}

process bar {
    debug true
    array 10

    input: path 'input.txt'

    """
    cat input.txt
    """
}

workflow {
    Channel.of(1 .. params.n_tasks) | foo | bar
}
```

and I run it this way: ``./launch.sh run test.nf``

**Comment by toniher** [comment]
Hey @bentsherman, any idea of anything I could check? I wonder if anyone else in this thread is experiencing the same issue with this branch test or knows where to look for...

**Comment by bentsherman** [comment]
Hey @toniher , sorry for the lack of response. Unfortunately I can't tell what's going wrong in your environment. Feel free to message me on Slack if you're still having issues, as I think we can troubleshoot more easily that way and not fill up this thread. I'm sure if we can dig a little deeper we can find your issue.

**Comment by andre-marcos-perez** [comment]
Just double-checking: would you say I can mirror Slurm's [job grid configuration](https://slurm.schedmd.com/sbatch.html#OPT_array)`--array=0-A:B` with the configuration below?

```
process { 
    executor = 'slurm'
    array = A
    maxForks = B
}
```

**Comment by bentsherman** [comment]
The `B` in that case is a step size, which is not used by Nextflow. If you need the array index to be a multiple of `B` for some reason, you can just multiply the index in the job script
