### ISSUE TITLE
Script template fails to render list of files

### ISSUE THREAD

**Issue by emi80** [nextflow-io/nextflow#1478]
### Expected behavior and actual behavior

When using a `BlankSeparatedList` as an interpolated string in a process script the output should give a string of space separated values. This behavior should be the same using templates too. In version 20.01.0-edge that's not the case while it works with version 19.10.

### Steps to reproduce the problem

```
process foo {

    output:
    file('*.txt') into (reads,reads1)
    
    """
    touch {a,b}.txt
    """
}

process bar {
    echo true

    input:
    file reads from reads

    script:
    template('script.sh')
}

process baz {
    echo true

    input:
    file reads from reads1

    """
    echo ${reads}
    """   
}
```

### Program output 

```
N E X T F L O W  ~  version 20.01.0-edge
Launching `test.nf` [tiny_watson] - revision: 02020e101c
executor >  local (3)
[b2/ce1316] process > foo [100%] 1 of 1 ✔
[53/5a57dc] process > bar [100%] 1 of 1 ✔
[b4/306d2a] process > baz [100%] 1 of 1 ✔
a.txt b.txt

[a.txt, b.txt]
```

### Environment 

* Nextflow version: `20.01.0-edge`
* Java version: `1.8.0_242`
* Operating system: `Linux`

**Comment by pditommaso** [comment]
😖😖😖

**Comment by pditommaso** [comment]
This is a regression introduced by #1392
