### ISSUE TITLE
Deprecate generic module inclusion

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#1483]
Currently, DSL2 allow a generic component inclusion which includes all components defined in the module script. For example: 

```
include './some/module'
include './other/module'

workflow {
  foo()
  bar()
}
```

While this is convenient for quick prototyping, makes the code difficult to read to people who didn't write those modules and hard to maintain as the number of components grows over time. 

The above notation should be deprecated in favour of explicit module inclusion, eg: 

```
include foo from './some/module'
include bar from './other/module'

workflow {
  foo()
  bar()
}
```

Which makes clear from where the component is included. Feature #1482 will simplify the inclusion of many components from the same module file.

**Comment by DaGaMs** [comment]
I respectfully disagree with deprecating generic module inclusion. This should be a developer's choice, just like in many scripting languages that alllow things like `import * from myModule`. Why force people to write `include {func1; func2; func3; func4; func5; func6; func7; ...} from 'myModule'`?
