### ISSUE TITLE
Module should inherit params from the owner scope

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#1484]
The `params` implicit variable provides *read-only* scope that allows the definition of global parameters that can be overridden at execution time. 

Modules introduced with DSL2 allow the use of the `params` variables to provide module-specific parameters. To avoid collision with params with the same name and a different semantic declared in different modules, was chosen to keep the `params` scope in the module separate from the global workflow `params`, and the module params  need to be provided in the module inclusion, eg: 

```
include foo from `./some/module` params(something: 'value')
```

However, this can result in recurrent boilerplate code to pass along the params to each included module and promote the proliferation of different param names in each module file. 

In order to avoid this, a module should implicitly inherit the `params` defined in the owner scope when the module is included and if no explicit params are specified, eg:

```
params.x='hello'
params.y='world' 
include foo from `./some/module`
```

The module `./some/module` will be able to access to `params.x` `and params.y`.

To prevent the params propagation to the included module or provide module-specific params, the `params` option can still be used in the `include` definition. 

```   
params.x='hello'
params.y='world' 
include foo from `./some/module` params(z: 'value')
```

The module `./some/module` should only be able to access `params.z`.

**Comment by bobamess** [comment]
The proposed change, if I have understood it correctly, to allow modules to inherit `params `definitions from the owner's scope, but with the option to override these, is welcome.  
However, the example shown implies that if `./some/module` also requires access to `params.x `then this will still have to be explicitly added as in:

```
params.x='hello'
params.y='world'
include foo from `./some/module` params(x: 'hello', z: 'value')
```

However, this loses some of the advantages of the proposed change and could still lead to unnecessarily verbose code.

To clarify, if, instead, your example had been the following:

```
params.x='hello'
params.y='world' 
include foo from `./some/module` params(x: 'ciao', z: 'value')
```

where, the module `./some/module` can still access `params.y,` while `params.x` is redefined and `params.z` is added,  this would have made more sense, in my opinion. But, it seems, with the proposed change `params.y `would not be accessible by `./some/module` in the above and we would instead require:

```
params.x='hello'
params.y='world' 
include foo from `./some/module` params(x: 'ciao', y: 'world', z: 'value')
```

Please clarify.

**Comment by pditommaso** [comment]
> However, the example shown implies that if ./some/module also requires access to params.x then this will still have to be explicitly added as in:

Yes, it's correct. I think it still valuable to provide a way to isolate the included module from any params but the specified ones. 

At the same time, I understand your requirement. It could be managed in a couple of ways: 
1) Adding to `params` the ability to handle the following declaration `params(params, x: 'ciao')` which should take all the current `params` map and override the `x` value. 
2) Add a new include option `addParams` eg `addParams(x: 'ciao', z: 'value')` which should extend the current params with the new values as you are proposing.

**Comment by pditommaso** [comment]
The support for `addParams` has been implemented.
