### ISSUE TITLE
No signature of method: groovy.util.ConfigObject.intdiv() when runing from github

### ISSUE THREAD

**Issue by dantefff** [nextflow-io/nextflow#1485]
I'm trying to proportionally and dinamically ditribute resources for a process. To achieve this and make users easy to limit the cores used in its local machines I use a file called `conf/cores.config` with the only purpose to define the local processor limitations.

Then in the `nextflow.config` file, I make decissions about how many cores (from the total) each process can use. To make this decision I make integer operations over the `executor.cpus` parameter.

I have made a git repository with a test case: [https://github.com/dantefff/testNextFlow.git](https://github.com/dantefff/testNextFlow.git)

### Expected behavior and actual behavior

Runing `nextflow run https://github.com/dantefff/testNextFlow.git` The nextflow workflow should execute ok, but I get:
`N E X T F L O W  ~  version 19.10.0
Pulling dantefff/testNextFlow ...
Project config file is malformed -- Cause: No signature of method: groovy.util.ConfigObject.intdiv() is applicable for argument types: (Integer) values: [2]
Possible solutions: find(), find(groovy.lang.Closure), inject(groovy.lang.Closure), take(int), find(groovy.lang.Closure)`

If you make a git clone for this repo and then you run the workflow locally it works ok.
```
git clone https://github.com/dantefff/testNextFlow.git deleteme
nextflow deleteme/holamundo.nf
```

### Steps to reproduce the problem

1. git clone https://github.com/dantefff/testNextFlow.git deleteme
2. nextflow deleteme/holamundo.nf
3. THIS WORKS
4. rm -rf deleteme
5. nextflow run https://github.com/dantefff/testNextFlow.git
6. THIS FAILS

### Program output 
`#nextflow run https://github.com/dantefff/testNextFlow.git

N E X T F L O W  ~  version 19.10.0
Pulling dantefff/testNextFlow ...
Project config file is malformed -- Cause: No signature of method: groovy.util.ConfigObject.intdiv() is applicable for argument types: (Integer) values: [2]
Possible solutions: find(), find(groovy.lang.Closure), inject(groovy.lang.Closure), take(int), find(groovy.lang.Closure)`

And this is the nextflow.log content:
[nextflow.log](https://github.com/nextflow-io/nextflow/files/4148008/nextflow.log)

### Environment 

* Nextflow version: [19.10.0.5170] 
* Java version: [openjdk version "1.8.0_222"]
* Operating system: [Debian stretch]

**Comment by pditommaso** [comment]
You can't access `cpus` on the `executor` object. 

https://github.com/dantefff/testNextFlow/blob/master/nextflow.config#L10
