### ISSUE TITLE
DAG edges not connected correctly

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#1486]
## Bug report 

The DAG image generated with the `-with-dag` option doesn't produce the correct output. There are erroneous, unlabeled edges added and correctly labeled edges aren't connected to the correct operators and processes.

### Expected behavior and actual behavior

In the example below, there are three edges incoming to the `combine` node, when there should only be two and one of the edges that _should_ be incoming to the `combine` node (`chan_two`) is not.

The edge between the `example` and `view` nodes is labeled with "-" and I'm not sure where that's coming from.

### Steps to reproduce the problem

This program illustrates the problem:

```
nextflow.preview.dsl=2

workflow {
    process example {
        input:
        tuple val(x), val(y)

        output:
        stdout()

        script:
        """
        printf "${x}${y}"
        """
    }

    chan_one = Channel.from(1,2,3)
    chan_two = Channel.from("a","b","c")

    chan_one \
        | combine(chan_two) \
        | example \
        | view

}
```
Run `nextflow run -with-dag bad.png main.nf` to reproduce.

### Program output 

This is the generated dot file:
```
digraph "bad" {
p0 [shape=point,label="",fixedsize=true,width=0.1,xlabel="Channel.from"];
p5 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="combine"];
p0 -> p5 [label="chan_one"];

p1 [shape=point,label="",fixedsize=true,width=0.1,xlabel="Channel.from"];
p2 [shape=point];
p1 -> p2 [label="chan_two"];

p3 [shape=point,label="",fixedsize=true,width=0.1];
p5 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="combine"];
p3 -> p5;

p4 [shape=point,label="",fixedsize=true,width=0.1];
p5 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="combine"];
p4 -> p5;

p5 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="combine"];
p6 [label="example"];
p5 -> p6;

p6 [label="example"];
p7 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="view"];
p6 -> p7 [label="-"];

p7 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="view"];
p8 [shape=point];
p7 -> p8;

}
```

I would expect it to generate something more like this:

```
digraph "expected" {

p0 [shape=point,label="",fixedsize=true,width=0.1,xlabel="Channel.from"];
p1 [shape=point,label="",fixedsize=true,width=0.1,xlabel="Channel.from"];
p5 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="combine"];
p6 [label="example"];
p7 [shape=circle,label="",fixedsize=true,width=0.1,xlabel="view"];

p0 -> p5 [label="chan_one"];
p1 -> p5 [label="chan_two"];
p5 -> p6
p6 -> p7

}
```

### Environment 

* Nextflow version: 19.10.0 build 5170 
* Java version: Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
* Operating system: macOS

**Comment by mes5k** [comment]
Here's what the code currently produces:

![bad](https://user-images.githubusercontent.com/492641/73785454-27db6e00-474c-11ea-9d82-bd57d505d264.png)

Here's what I'd expect it to produce:

![expected](https://user-images.githubusercontent.com/492641/73785464-2b6ef500-474c-11ea-8204-1c3324ac25f9.png)

**Comment by mes5k** [comment]
Will this comment delay the stalebot?  AFAIK, this is still a problem.

**Comment by mes5k** [comment]
@pditommaso Well, I think I've identified the problem, but I'm not sure how to solve it.  In the example above, the outgoing channel objects (edges) of `Channel.from` are not the same incoming channel objects (edges) of the `combine` operator.  Basically, [this method](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/dag/DAG.groovy#L265-L267) isn't working as expected because the channel objects don't  match. This results in extra edges getting created in the [inbound](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/dag/DAG.groovy#L169) and [outbound](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/dag/DAG.groovy#L208) methods.  I have no idea _why_ the channel objects are different. I see some whose _toString()_ methods identify them as _DataFlowStream_ and some as _DataFlowBroadcast_.  I'm guessing there's some sort of channel matching or linking code elsewhere in the codebase, but I have no idea where or what it might look like.  Any ideas?

**Comment by pditommaso** [comment]
The DataflowBroadcast is the object that allows DSL2 to use the same channel multiple times. This is done invoking on-fly a *read* channel from it, that's essentially a different object and likely it's the one breaking the graph. 

I think the critical point is this, possible the new references returned by `read0` and `read1` are not tracked correctly for the graph generation 

https://github.com/nextflow-io/nextflow/blob/6c112b8fe25bc6e92205af63cb20a777dc347027/modules/nextflow/src/main/groovy/nextflow/extension/OpCall.groovy#L158-L161

**Comment by mes5k** [comment]
Yup, at least one of the problems is that a DataflowBroadcast arg to the `combine` operator gets converted to a read channel in `read1`.  Is there a way to reverse this, i.e. given the read channel look up the DataflowBroadcast?  I've been assuming not and that I'll need to create a lookup in `read0` with that information and send it in `addGraphNode`.  I'll keep trying.

**Comment by pditommaso** [comment]
I was expecting this 👉 dec43123 to fix, instead, break it even more :/

**Comment by mes5k** [comment]
Alright, I think I've fixed _this_ problem.  See my changes here: https://github.com/mes5k/nextflow/tree/bug_1486_dag_edge_fix. 

The main problem was that the DataflowBroadcast object was getting "erased" by the `read0` method in OpCall. To fix this I store a map from read channel to dataflow broadcast channel, so that when we create the DAG we can get from the read channel _back_ to the dataflow broadcast channel.  It's more overhead, but seems OK.

Another problem was the extra null node and edge beneath the `view` node in the example above. The null node is because the edge has no `to` node, so the old `normalizeMissingVertices` method added the extra node. I'm not sure why you were adding "missing" nodes in the first place, so maybe this change needs to be re-thought.  My change simply filters out any edges without a `to` or `from` node. 

 If this makes sense to you, I can work on better comments, unit tests, and creating a proper PR.

**Comment by pditommaso** [comment]
Oh, nice. Yes, please make a PR, I'll check it asap.
