### ISSUE TITLE
Incorrect computation of resources for Executor `lsf` in specific LSF instances

### ISSUE THREAD

**Issue by akahles** [nextflow-io/nextflow#1487]
### Expected behavior and actual behavior

Using Nextflow with the `lsf` executor and running a task that requires multiple CPUs, the expectation is that the requested memory is divided by the number of CPUs, as LSF will request the memory per CPU in the task (unless `RESOURCE_RESERVE_PER_TASK=N` is configured in LSF). 

### Steps to reproduce the problem

As the behavior depends on a specific LSF installation, I will describe the problem here as detailed as possible. The main problem lies in how the `RESOURCE_RESERVE_PER_TASK` setting is read.

Nextflow will use this setting to determine whether the memory should be provided per core or not (https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy#L88). The value of `perTaskReserve` is collected from `$LSF_ENVDIR/lsf.conf`, which is specific to the LSF setup. 

The problem in our case is that we are working with an HPC system that does not define `RESOURCE_RESERVE_PER_TASK` in `$LSF_ENVDIR/lsf.conf` and as a consequence `perTaskReserve` will always evaluate to `false`.  (The consequence is that the amount of memory requested is multiplied by the number of CPUs for the task by LSF.)

After consulting our local system admins, we were advised that the correct location for defining `RESOURCE_RESERVE_PER_TASK` would be in `$LSF_ENVDIR/lsbatch/<CLUSTERNAME>/configdir/lsb.params`, where `<CLUSTERNAME>` is a value specific to the installation. (They are following IBM's instructions: https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_config_ref/lsb.params.resource_reserve_per_task.5.html).

It was also made clear to us that the setting cannot be added to `$LSF_ENVDIR/lsf.conf` in our case. Would it be possible to generally redirect Nextflow to use the `lsb.params` for filling the `conf` object or could a Nextflow environment variable be added (e.g. `NXF_LSF_ENVDIR`), so it can be pointed to the correct configuration file?

### Program output 

No specific output - see description above.

### Environment 

* Nextflow version: 20.01.0-edge.5246 
* Java version: openjdk version "11.0.1" 2018-10-16 LTS
* Operating system: CentOS 7

**Comment by pditommaso** [comment]
This looks specific to your configuration. I advise setting the `LSF_ENVDIR` accordingly in the node lanching the NF execution or just in wrapper script for it.

**Comment by akahles** [comment]
Dear @pditommaso,

Thank you for responding. Unfortunately, your suggested solution would not work for us, as relevant parameters need to be collected from *two* places:
1) `${LSF_ENVDIR}/lsf.conf`
2) `${LSF_ENVDIR}/lsbatch/${CLUSTER_NAME}/configdir/lsb.params`

After talking with our admins, it is my understanding that this is the correct setup of LSF if one runs multiple cluster setups (distinguished by `${CLUSTER_NAME}`) on the same system.

Just changing `${LSF_ENVDIR}` will not be successful, as for one nextflow only uses the path-prefix, but hardcodes the `lsf.conf` and second, I would be missing settings from one of the two locations.

If it is helpful, here a link to a patch which I wrote to run nextflow in our system (setting an additional variable `NX_LSF_ENVDIR`:
https://github.com/ratschlab/nextflow/blob/lsf/modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy#L234

This has worked for us, but would require us to maintain our own fork of nextflow.

Thanks and Cheers,
Andre

**Comment by jpadesousa** [comment]
Hi @akahles and @pditommaso,

I am also from ETH Zurich. I am using the same server (ETH Leonhard) and having the same issue.
I changed the Lsfexecutor.groovy script and like @akahles said, it works but we need to maintain our own fork.

I would it be possible to add the suggested option in a future update?

Best,
Joao

**Comment by pditommaso** [comment]
Not very keep on using magic variables for custom deployment. Is there a LSF env variable controlling this feature?

**Comment by akahles** [comment]
Thank you @jpadesousa for picking up this topic again. 

@pditommaso The last time I interacted with our sys-admins, there seemed to be no straightforward generalisable solution to extract this information from the LSF env variables. 

However, I will start another iteration of communication with the admins. @jpadesousa I can loop you in on the ETH side. 

Best,

Andre

**Comment by jpadesousa** [comment]
I understand your reluctance to add a custom variable @pditommaso. If everybody would want a custom change the code, it would end up a frankensteinian mess.

That would be great @akahles!
The only solution I found was add a command in the .bashrc to make a copy of the "lsf.conf" file to a location accessible by all nodes and append the line "RESOURCE_RESERVE_PER_TASK=Y" at the end. Then change the $LSF_ENVDIR to that location. Something like this:

`yes | cp  /cluster/apps/lsf/conf/lsf.conf $WORK/software/config; chmod 777 $WORK/software/config/lsf.conf; echo 'RESOURCE_RESERVE_PER_TASK=Y' >> $WORK/software/config/lsf.conf`

It works, but it's definitely not perfect. It requires that lsf.conf gets copied at every login. The optimal solution would be to have the variable RESOURCE_RESERVE_PER_TASK in the server's lsf.conf.

**Comment by jpadesousa** [comment]
Hi @pditommaso,

I was checking the IBM LSF reference manual and, from what I am reading, what we have in our cluster is the default LSF configuration. The variable RESOURCE_RESERVE_PER_TASK is expected to be defined in `lsb.params` and "This file is installed by default in LSB_CONFDIR/cluster_name/configdir" (https://www.ibm.com/support/knowledgecenter/SSWRJV_10.1.0/lsf_config_ref/lsb.params.5.html)

I don't know if other nextflow users experienced the same issue or if they have RESOURCE_RESERVE_PER_TASK defined in `lsf.conf`. Maybe you could add that the program searches the variable in `lsf.conf` and in `${LSB_CONFDIR}/[any_name]/configdir/lsf.params` or `${LSB_CONFDIR}/${CLUSTER_NAME}/configdir/lsf.params`.

I tried to change the `perTaskReserve` to 'true' in the nextflow.config but didn't change anything. So, having the ability to overwrite `perTaskReserve` would also solve our issues.

Best,
João
