### ISSUE TITLE
Set UTF-8 as default file character encoding

### ISSUE THREAD

**Issue by kiwenlau** [nextflow-io/nextflow#149]
I got  "ERROR ~ Input length = 1" when I tried to hello

**./nextflow run hello**
```
N E X T F L O W  ~  version 0.18.3
Launching 'nextflow-io/hello' - revision: 1b3a2ae053 [master]
ERROR ~ Input length = 1

 -- Check '.nextflow.log' file for details
```

**cat .nextflow.log**
```
May-10 11:10:58.712 [main] DEBUG nextflow.cli.Launcher - $> ./nextflow run hello
May-10 11:10:58.810 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.18.3
May-10 11:10:59.195 [main] DEBUG nextflow.scm.AssetManager - Listing projects in folder: /home/kai/.nextflow/assets
May-10 11:10:59.229 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/kai/.nextflow/assets/nextflow-io/hello/.git/config; branch: master; remote: origin; url: https://github.com/nextflow-io/hello.git
May-10 11:10:59.263 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/kai/.nextflow/assets/nextflow-io/hello/.git/config; branch: master; remote: origin; url: https://github.com/nextflow-io/hello.git
May-10 11:10:59.374 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/kai/.nextflow/assets/nextflow-io/hello/.git/config; branch: master; remote: origin; url: https://github.com/nextflow-io/hello.git
May-10 11:10:59.375 [main] INFO  nextflow.cli.CmdRun - Launching 'nextflow-io/hello' - revision: 1b3a2ae053 [master]
May-10 11:11:00.130 [main] DEBUG nextflow.Session - Session uuid: a8a1bbfd-7fd5-44eb-ba70-1ea85e837da6
May-10 11:11:00.131 [main] DEBUG nextflow.Session - Executor pool size: 2
May-10 11:11:00.140 [main] ERROR nextflow.cli.Launcher - @unknown
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:338)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:203)
	at java.io.BufferedReader.read(BufferedReader.java:279)
	at java.io.Reader.read(Reader.java:140)
	at org.codehaus.groovy.runtime.IOGroovyMethods.getText(IOGroovyMethods.java:884)
	at org.codehaus.groovy.runtime.NioGroovyMethods.getText(NioGroovyMethods.java:422)
	at nextflow.script.ScriptFile.getText(ScriptFile.groovy:66)
	at nextflow.script.ScriptRunner.setScript(ScriptRunner.groovy:111)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:181)
	at nextflow.cli.Launcher.run(Launcher.groovy:380)
	at nextflow.cli.Launcher.main(Launcher.groovy:529)
```

I got the same error on my local host and amazon ec2 host, both run ubuntu 14.04

**Comment by pditommaso** [comment]
Very strage error. Could you please include the output of the is command: 

    nextflow info -dd

**Comment by kiwenlau** [comment]
**nextflow info -dd**

`nextflow info -dd
  Version: 0.18.3 build 3712
  Modified: 09-05-2016 06:45 UTC (15:45 JDT)
  System: Linux 3.16.0-30-generic
  Runtime: Groovy 2.4.5 on OpenJDK 64-Bit Server VM 1.7.0_95-b00
  Encoding: ANSI_X3.4-1968 (ANSI_X3.4-1968)
  File systems: file, jar, s3
  JVM opts:
    -Xverify:none
    -XX:+TieredCompilation
    -XX:TieredStopAtLevel=1
    -Djava.awt.headless=true
    -Djava.library.path=
      /usr/java/packages/lib/amd64
      /usr/lib/x86_64-linux-gnu/jni
      /lib/x86_64-linux-gnu
      /usr/lib/x86_64-linux-gnu
      /usr/lib/jni
      /lib
      /usr/lib
  Capsule:
    capsule.app=nextflow_0.18.3
    capsule.jar=/home/kai/.nextflow/framework/0.18.3/nextflow-0.18.3-one.jar
  Environment:
    CAPSULE_CACHE_DIR=/home/kai/.nextflow/capsule
    COLUMNS=80
    HOME=/home/kai
    JAVA_CMD=/usr/bin/java
    LANG=en_US.UTF-8
    LC_CTYPE=UTF-8
    LESSCLOSE=/usr/bin/lesspipe %s %s
    LESSOPEN=| /usr/bin/lesspipe %s
    LOGNAME=kai
    LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
    MAIL=/var/mail/kai
    NXF_CLI=/usr/local/bin/nextflow info -dd
    NXF_HOME=/home/kai/.nextflow
    NXF_ORG=nextflow-io
    PATH=
      /usr/local/sbin
      /usr/local/bin
      /usr/sbin
      /usr/bin
      /sbin
      /bin
      /usr/games
      /usr/local/games
    PWD=/home/kai
    SHELL=/bin/bash
    SHLVL=1
    SSH_CLIENT=192.168.59.100 56898 22
    SSH_CONNECTION=192.168.59.100 56898 192.168.59.1 22
    SSH_TTY=/dev/pts/2
    TERM=xterm-256color
    USER=kai
    XDG_RUNTIME_DIR=/run/user/1001
    XDG_SESSION_ID=2
  Properties:
    awt.toolkit=sun.awt.X11.XToolkit
    capsule.app=nextflow_0.18.3
    capsule.jar=/home/kai/.nextflow/framework/0.18.3/nextflow-0.18.3-one.jar
    file.encoding=ANSI_X3.4-1968
    file.encoding.pkg=sun.io
    file.separator=/
    java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
    java.awt.headless=true
    java.awt.printerjob=sun.print.PSPrinterJob
    java.class.version=51.0
    java.endorsed.dirs=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/endorsed
    java.ext.dirs=
      /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext
      /usr/java/packages/lib/ext
    java.home=/usr/lib/jvm/java-7-openjdk-amd64/jre
    java.io.tmpdir=/tmp
    java.library.path=
      /usr/java/packages/lib/amd64
      /usr/lib/x86_64-linux-gnu/jni
      /lib/x86_64-linux-gnu
      /usr/lib/x86_64-linux-gnu
      /usr/lib/jni
      /lib
      /usr/lib
    java.runtime.name=OpenJDK Runtime Environment
    java.runtime.version=1.7.0_95-b00
    java.specification.name=Java Platform API Specification
    java.specification.vendor=Oracle Corporation
    java.specification.version=1.7
    java.vendor=Oracle Corporation
    java.vendor.url=http://java.oracle.com/
    java.vendor.url.bug=http://bugreport.sun.com/bugreport/
    java.version=1.7.0_95
    java.vm.info=mixed mode
    java.vm.name=OpenJDK 64-Bit Server VM
    java.vm.specification.name=Java Virtual Machine Specification
    java.vm.specification.vendor=Oracle Corporation
    java.vm.specification.version=1.7
    java.vm.vendor=Oracle Corporation
    java.vm.version=24.95-b01
    line.separator=\n
    os.arch=amd64
    os.name=Linux
    os.version=3.16.0-30-generic
    path.separator=:
    sun.arch.data.model=64
    sun.boot.class.path=
      /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/resources.jar
      /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar
      /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/sunrsasign.jar
      /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jsse.jar
      /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jce.jar
      /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/charsets.jar
      /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rhino.jar
      /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jfr.jar
      /usr/lib/jvm/java-7-openjdk-amd64/jre/classes
    sun.boot.library.path=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64
    sun.cpu.endian=little
    sun.cpu.isalist
    sun.io.unicode.encoding=UnicodeLittle
    sun.java.command=nextflow.cli.Launcher info -dd
    sun.java.launcher=SUN_STANDARD
    sun.jnu.encoding=ANSI_X3.4-1968
    sun.management.compiler=HotSpot 64-Bit Tiered Compilers
    sun.os.patch.level=unknown
    user.country=US
    user.dir=/home/kai
    user.home=/home/kai
    user.language=en
    user.name=kai
    user.timezone=Asia/Tokyo
  Class-path:
    /home/kai/.nextflow/framework/0.18.3/nextflow-0.18.3-one.jar
    /home/kai/.nextflow/capsule/deps/io/nextflow/nextflow/0.18.3/nextflow-0.18.3.jar
    /home/kai/.nextflow/capsule/deps/org/apache/ivy/ivy/2.3.0/ivy-2.3.0.jar
    /home/kai/.nextflow/capsule/deps/io/nextflow/nxf-commons/0.18.3/nxf-commons-0.18.3.jar
    /home/kai/.nextflow/capsule/deps/org/codehaus/groovy/groovy/2.4.5/groovy-2.4.5.jar
    /home/kai/.nextflow/capsule/deps/org/codehaus/groovy/groovy-nio/2.4.5/groovy-nio-2.4.5.jar
    /home/kai/.nextflow/capsule/deps/org/codehaus/groovy/groovy-json/2.4.5/groovy-json-2.4.5.jar
    /home/kai/.nextflow/capsule/deps/org/codehaus/groovy/groovy-templates/2.4.5/groovy-templates-2.4.5.jar
    /home/kai/.nextflow/capsule/deps/org/slf4j/jcl-over-slf4j/1.7.21/jcl-over-slf4j-1.7.21.jar
    /home/kai/.nextflow/capsule/deps/org/slf4j/jul-to-slf4j/1.7.21/jul-to-slf4j-1.7.21.jar
    /home/kai/.nextflow/capsule/deps/org/slf4j/log4j-over-slf4j/1.7.21/log4j-over-slf4j-1.7.21.jar
    /home/kai/.nextflow/capsule/deps/ch/qos/logback/logback-classic/1.1.6/logback-classic-1.1.6.jar
    /home/kai/.nextflow/capsule/deps/ch/qos/logback/logback-core/1.1.6/logback-core-1.1.6.jar
    /home/kai/.nextflow/capsule/deps/org/codehaus/gpars/gpars/1.2.1/gpars-1.2.1.jar
    /home/kai/.nextflow/capsule/deps/ch/grengine/grengine/1.0.3/grengine-1.0.3.jar
    /home/kai/.nextflow/capsule/deps/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
    /home/kai/.nextflow/capsule/deps/com/beust/jcommander/1.35/jcommander-1.35.jar
    /home/kai/.nextflow/capsule/deps/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
    /home/kai/.nextflow/capsule/deps/com/esotericsoftware/kryo/kryo/2.24.0/kryo-2.24.0.jar
    /home/kai/.nextflow/capsule/deps/org/iq80/leveldb/leveldb/0.7/leveldb-0.7.jar
    /home/kai/.nextflow/capsule/deps/org/eclipse/jgit/org.eclipse.jgit/4.3.0.201604071810-r/org.eclipse.jgit-4.3.0.201604071810-r.jar
    /home/kai/.nextflow/capsule/deps/io/nextflow/nxf-s3fs/1.0.0/nxf-s3fs-1.0.0.jar
    /home/kai/.nextflow/capsule/deps/com/google/guava/guava/16.0.1/guava-16.0.1.jar
    /home/kai/.nextflow/capsule/deps/org/codehaus/groovy/groovy-xml/2.4.5/groovy-xml-2.4.5.jar
    /home/kai/.nextflow/capsule/deps/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar
    /home/kai/.nextflow/capsule/deps/org/multiverse/multiverse-core/0.7.0/multiverse-core-0.7.0.jar
    /home/kai/.nextflow/capsule/deps/org/codehaus/jsr166-mirror/jsr166y/1.7.0/jsr166y-1.7.0.jar
    /home/kai/.nextflow/capsule/deps/org/objenesis/objenesis/2.1/objenesis-2.1.jar
    /home/kai/.nextflow/capsule/deps/org/iq80/leveldb/leveldb-api/0.7/leveldb-api-0.7.jar
    /home/kai/.nextflow/capsule/deps/com/jcraft/jsch/0.1.53/jsch-0.1.53.jar
    /home/kai/.nextflow/capsule/deps/com/googlecode/javaewah/JavaEWAH/0.7.9/JavaEWAH-0.7.9.jar
    /home/kai/.nextflow/capsule/deps/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar
    /home/kai/.nextflow/capsule/deps/com/amazonaws/aws-java-sdk-s3/1.9.4/aws-java-sdk-s3-1.9.4.jar
    /home/kai/.nextflow/capsule/deps/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar
    /home/kai/.nextflow/capsule/deps/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
    /home/kai/.nextflow/capsule/deps/com/amazonaws/aws-java-sdk-core/1.9.4/aws-java-sdk-core-1.9.4.jar
    /home/kai/.nextflow/capsule/deps/com/fasterxml/jackson/core/jackson-databind/2.3.2/jackson-databind-2.3.2.jar
    /home/kai/.nextflow/capsule/deps/joda-time/joda-time/2.9.3/joda-time-2.9.3.jar
    /home/kai/.nextflow/capsule/deps/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar
    /home/kai/.nextflow/capsule/deps/com/fasterxml/jackson/core/jackson-core/2.3.2/jackson-core-2.3.2.jar
    /home/kai/.nextflow/capsule/deps/io/nextflow/nxf-extrae/0.18.3/nxf-extrae-0.18.3.jar`

**Comment by pditommaso** [comment]
OK, I've managed to reproduce the problem, however it's not a nextflow issue, it seems more a problem in the underlying groovy runtime related with the file encoding in your system (ANSI_X3.4-1968). 

You should be able to run nextflow using the UTF-8 encoding setting the following environment variable: 

    export NXF_OPTS='-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8'

**Comment by pditommaso** [comment]
Actually I think it's neither a Groovy issue. The problem is that the `hello` pipeline file uses the `UTF-8` encoding, while the default encoding in your system is `ANSI_X3.4-1968` thus nextflow it's unable to read that file. 

Maybe Nextflow should force the UTF-8 encoding as default, wether the local system setting is.

**Comment by kiwenlau** [comment]
Problem solved! Thanks

**Comment by pditommaso** [comment]
Some useful links: 

* http://stackoverflow.com/questions/30479607/explain-the-effects-of-export-lang-lc-ctype-lc-all
* http://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do
* http://stackoverflow.com/questions/11343828/file-encoding-has-no-effect-lc-all-environment-variable-does-it
* http://www.jvmhost.com/articles/locale-breaks-unicode-utf-8-java-tomcat

**Comment by pditommaso** [comment]
Actually it's a bit weird that you have the following settings in your environment: 

    LANG=en_US.UTF-8
    LC_CTYPE=UTF-8

but Java uses `ANSI_X3.4-1968` file encoding by default.

**Comment by pditommaso** [comment]
This condition should be managed by nextflow

**Comment by kiwenlau** [comment]
FYI. I got the same problem when I tried to run nextflow within Docker container based on ubuntu:14.04 image.

**Comment by pditommaso** [comment]
Nextflow uses `UTF-8` as default file encoding whatever the local use configuration is. Make sure to save your nextflow script by using `UTF-8` character encoding.
