### ISSUE TITLE
zsh support

### ISSUE THREAD

**Issue by rspreafico-vir** [nextflow-io/nextflow#1490]
## New feature

Currently nextflow runs on `bash`. This enhancement proposal is to support `zsh`.

## Usage scenario 

There are 3 usage scenarios where `zsh` support would be beneficial:
- macOS, starting with Catalina, switched from `bash` to `zsh` as default shell
- many bioinformaticians working in the Linux world often prefer `zsh` over `bash`
- popular shell extensions such as Oh My Zsh provide further incentive to move to `zsh`

## Suggest implementation 

`zsh` may be found more commonly in the environment executing `nextflow`. It is possible, though uncommon, that `zsh` may be the default shell of a Docker container called by Nextflow. Mixed scenarios with `zsh` used to call `nextflow` and `bash` used by Docker containers may be common. 

With `zsh` being almost a superset of `bash`, the safest option might be to use `bash` syntax, making sure that all commands are also supported by `zsh`.

**Comment by TomKellyGenetics** [comment]
The benefits of zsh mainly pertain to running in interactive sessions. I think this is not necessary as it is still possible to call bash scripts in a zsh shell or use bash as the entrypoint in docker containers.
