### ISSUE TITLE
Limit on run name length

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#1491]
Hi @pditommaso,

Over in https://github.com/seqeralabs/nf-tower/issues/188 we discussed a limit in the length of nextflow run names and I managed to convince you to push the limit up a little, to 80 characters 😉 

Now we've run in to a problem that Nextflow is refusing to run jobs though, before we get to tower. We get the following error message: ('cc @jpfeuffer)

```
Not a valid run name: `nf-core_proteomicslfq-general-pull_request-45069d` -- It must match the pattern ^[a-z](?:[a-z\d]|[-_](?=[a-z\d])){0,39}$
```

This seems to be coming from Nextflow here:

https://github.com/nextflow-io/nextflow/blob/2eb94251622043411e243284939e3c9c1fff0a01/modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy#L279-L280

With this regex:

https://github.com/nextflow-io/nextflow/blob/2eb94251622043411e243284939e3c9c1fff0a01/modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy#L54

..which is limiting run names to 40 characters.

Would it be possible to push this up to 80 characters please, to match tower?

Phil

**Comment by pditommaso** [comment]
Ouch, well spotted!. Just in time for upcoming stable.
