### ISSUE TITLE
A source of ConcurrentModificationException

### ISSUE THREAD

**Issue by karl616** [nextflow-io/nextflow#1494]
This is not so much a question as a piece of documentation. I spent yesterday trying to resolve a ConcurrentModificationException and found it difficult as the error occurs before the job is submitted. As an issue, this can probably be closed immediately, but as this was one of the places I came looking for information, I thought it be good to leave the insights gained here.

Here is a toy example:

```
nextflow.preview.dsl=2

process generate_files {

  input:
  val id

  output:
  val id
  file("${id}.txt")

  script:
  """
  echo ${id} > ${id}.txt
  """
}

process merge_files {

  input:
  val id
  file(files:"file???/*")
  val export_type

  output:
  set export_type, file('concat.txt')

  script:
  """
  echo ${id.join(" ")} > concat.txt
  echo ${id.sort(false).join(" ")} >> concat.txt
  """
}

process merge_files_exception {

  input:
  val id
  file(files:"file???/*")
  val export_type

  output:
  set export_type, file('concat.txt')

  script:
  """
  echo ${id.join(" ")} > concat.txt
  echo ${id.sort().join(" ")} >> concat.txt
  """
}

workflow {

  Channel
    .from( "A1", "B2", "C1")
    .set { ids }

  generate_files(ids)

  Channel
    .from("A", "B", "X", "Y", "Z")
    .set { export_type }

  merge_files(
      generate_files.out[0].collect(),
      generate_files.out[1].collect(),
      export_type
    )

  merge_files_exception(
      generate_files.out[0].collect(),
      generate_files.out[1].collect(),
      export_type
    )
}
```

The merge_files_exception fails, but does so irregularly (probably depending on the order generate_files finishes... failing when the id variable is out of order). The culprit here is the sort function. I had missed that sort() is an in-place sort, hence modifying the input variable. This seems to propagate outside the task itself and conflict with the parallel processes. The solution was to use sort(false), which returns the sorted array and leaves the original untouched.

**Comment by pditommaso** [comment]
Thanks a for contributing this.
