### ISSUE TITLE
Regular expression examples not working (with DSL2)

### ISSUE THREAD

**Issue by FelixKrueger** [nextflow-io/nextflow#1495]
## Bug report 

Examples for Regex Matching in documentation appear to be not working as expected (with DSL2). I include two options that appear to be working, but I couldn't find them in the docs.

### Expected behavior and actual behavior

1. The example code:
```
assert 'foobar' =~ /foo/    // return TRUE
```
throws compilation errors when used with `if (assert...)` or when assigned to a variable. See example below.

2. The example code to genereate a regex.Matcher object only works when the string pattern is defined from start to end. The code example:

```
y = 'some string' =~ /abc/
```
does also not work in my hands. See example below.

`bamfile = "E14_R1_val_1_bismark_bt2_pe.deduplicated.bam"`
`matcher = bamfile =~ /pe/` does **not** work
`matcher = bamfile =~ /.*pe.*/` works fine (not documented)

### Steps to reproduce the problem

Here is a script showing how the two examples in the documentation fail (examples 1) and 2)). I also include 2 further examples that both appear to work but are not mentioned in the documentation, one using a Java matcher.matches() method, the other one using a seeming simply regex expression but without the 'assert'

```nextflow
nextflow.preview.dsl=2

file = "E14_R1_val_1_bismark_bt2_pe.deduplicated.bam"

isPairedEnd(file)

def isPairedEnd(bamfile) {

	println ("\nFile as String is called: " + bamfile)
		
	// 1. From the website:
	println "\nExample #1: assert 'foo' =~ /foo/"
	// if (assert 'foo' =~ /foo/){  // throws compilation error
	// println ("Works")
	// }
	// var = assert 'foo' =~ /foo/  // throws compilation error
	println ("\n")

	// 2. as suggested on the website
	// Use =~ to check whether a given pattern occurs anywhere in a string:
	println "Example #2: Use =~ to check whether a given pattern occurs anywhere in a string:"
	matcher = bamfile =~ /pe/
	println matcher
	if (matcher.matches()){
	  	println ("Found element 'pe' in filename!\n\n")
		println (matcher[0])
	}
	else{
		println ("no match of 'pe' in filename\n\n")
	}
	// fails to detect 'pe' in the file name

	// 3. Pad expression from start to end with wild cards. NOT on the website
	println "Example #3: Use =~, but pad with wildcards from start to end:"
	matcher = bamfile =~ /.*pe.*/
	println matcher
	if (matcher.matches()){
	  	println ("Found element 'pe' in filename!")
		println (matcher[0] + "\n\n")
	}
	else{
		println ("no match of 'pe' in filename\n\n")
	}
	// This now works! Continue with matcher.matches()...

	// 4. 'Standard' RegEx:
	println "Example #4: 'Standard' regex with =~ but without 'assert':"
	if (bamfile =~ /pe/){
		println("Filename contained 'pe'\n")//
	}
	// This also works. But is not documented on the website
}
```

### Program output 

```
File as String is called: E14_R1_val_1_bismark_bt2_pe.deduplicated.bam

Example #1: assert 'foo' =~ /foo/


Example #2: Use =~ to check whether a given pattern occurs anywhere in a string:
java.util.regex.Matcher[pattern=pe region=0,44 lastmatch=]
no match of 'pe' in filename


Example #3: Use =~, but pad with wildcards from start to end:
java.util.regex.Matcher[pattern=.*pe.* region=0,44 lastmatch=]
Found element 'pe' in filename!
E14_R1_val_1_bismark_bt2_pe.deduplicated.bam


Example #4: 'Standard' regex with =~ but without 'assert':
Filename contained 'pe'
```

### Environment 

* Nextflow version: 20.01.0-edge.5246
* Java version:
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

* Operating system: Linux
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

I am fairly new to Nextflow/Java, so please forgive me if these are some trivial questions...

Many thanks! Felix

**Comment by pditommaso** [comment]
The assert keyword verifies a boolen expression, as such, it cannot be used in a boolean expression. 

https://groovy-lang.org/testing.html#_power_assertions

Not sure where you have found `if(assert ..)` in the NF docs. 

Regarding the partial match please see `matches` vs `find` in the Java API https://stackoverflow.com/questions/4450045/difference-between-matches-and-find-in-java-regex

**Comment by FelixKrueger** [comment]
Excellent, many thanks for clearing this up!
