### ISSUE TITLE
`combine` by a function

### ISSUE THREAD

**Issue by cgroza** [nextflow-io/nextflow#1496]
Currently, `combine` allows generating combinations of elements between two channels.
It supports the `by:` argument, which allows combining according to an index of the emitted elements. Could `combine` also take a function that would generalize this use case instead of restricting it to indices in a tuple? Something similar is already implemented in the `cross` operator.

**Comment by pditommaso** [comment]
The `combine` op does not support this feature, but you can achieve the same chaining a `map`, returning the required key, followed by the `combine`.
