### ISSUE TITLE
awsbatch not properly staging shared foreign files

### ISSUE THREAD

**Issue by brooksomics** [nextflow-io/nextflow#1497]
### Expected behavior and actual behavior

Described briefly in this Gitter comment, [here](https://gitter.im/nextflow-io/nextflow?at=5e4640e5b401eb68a5783830), I have a fairly large database in AWS S3 (300 Gb) that I'm mapping hundreds to thousands of samples to using the [snap-aligner](https://github.com/amplab/snap). When running Nextflow version `20.01.0.5266` on an AWS EC2 instance, the `$WORKDIR/stage` appears as intended and the 300 Gb DB is only copied from S3 once to be utilized by the subsequent mapping jobs. If I instead run this on AWS Batch (i.e. `executor = 'awsbatch'` in my `nextflow.config`), the 300 Gb DB is copied from S3 for every mapping job. This is fine for a few mapping jobs but becomes extremely cumbersome for thousands. Some issues have somewhat referenced this (e.g. #686 and [#90](https://github.com/nf-core/methylseq/issues/90)), but I'm confused on whether or not this has been resolved when using awsbatch as the executor?

### Steps to reproduce the problem

*nextflow.config*:
```
manifest.mainScript = 'map_snap.nf'
docker.enabled = true
docker.temp = 'auto'

aws.batch.cliPath = '/home/ec2-user/miniconda/bin/aws'
process {
    executor = 'awsbatch'
    queue = 'nextflow_191229'
}
```

*map_snap.nf excerpt*:
```
/*
 * Step 1. Run SNAP
 */
ref_clusters = file(params.ref, type: 'dir')
Channel
    .fromFilePairs("${params.reads}**/*R{1,2}.fastq.gz")
    .ifEmpty { error "Cannot find any reads matching: ${params.reads}**/*R{1,2}.fastq.gz" }
    .set{ samples_ch }

def getShortIdRead( str ) {
  return str.replaceAll(/_trimmed_no_smallcontams_no_human/, "")
}

process runSnap {
    container 'bbrooks918/snap:1.0.1'
    publishDir "$params.outdir/${getShortIdRead(sampleid)}/", mode: 'copy', overwrite: true, pattern: '*_snap.log'
    memory { 255.GB * task.attempt }
    cpus { 31 * task.attempt }
    errorStrategy 'retry'
    maxRetries 4

    input:
    set sampleid, file(reads) from samples_ch
    file(ref_clusters)

    output:
    file "reads_${getShortIdRead(sampleid)}_to_ref_seqid_90_cvg_95_rep.sam" into sam_out1
    file "reads_${getShortIdRead(sampleid)}_to_ref_seqid_90_cvg_95_rep_snap.log"

    shell:
    """
    RAM=\$(echo "!{task.memory}" | egrep -o "[0-9]+")

    snap-aligner paired \
        ${ref_clusters} \
        -compressedFastq \
        ${reads[0]} \
        ${reads[1]} \
        -F a \
        -o reads_${getShortIdRead(sampleid)}_to_ref_seqid_90_cvg_95_rep.sam &> \
        reads_${getShortIdRead(sampleid)}_to_ref_seqid_90_cvg_95_rep_snap.log
    """
}
```

### Program output 

I've confirmed, by logging into several Batch instances, that they are indeed copying the 300 Gb DB for each job. Also, I cannot find the `$WORKDIR/stage` directory on these Batch instances, but I can when run outside of batch (e.g. on an AWS EC2 instance or on a local machine). In running `pwdx <pid of the aws s3 cp job copying the DB>`, I see that my work is being copied to places like this `/tmp/nxf.SNnJwQD39y`. Perhaps I need to stage this work somewhere else?

### Environment 

* Nextflow version: `20.01.0.5266` and I've tried `19.10.0.5170`
* Java version: 
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```
* Operating system: `Ubuntu 18.04.2 LTS`
* Bash version: `GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)`

**Comment by pditommaso** [comment]
Sorry still not able to replicate the issue. Please specify: 
* The source file(s) complete path
* The pipeline work dir complete path 
* The observed stage path(s)
* The expected stage path(s) 
* The `.nextflow.log` file

**Comment by brooksomics** [comment]
Below is the command I use to launch the NF job and answers your bullet points 1-2: 
```
nextflow run map_snap.nf \
        -work-dir s3://bbrooks-analyses/temp_work/test_snap_nf_200217/ \
        --ref s3://bbrooks-analyses/dbs/linclust_wtm_proteins/snap_index_wtm_proteins_from_scaffolds_min1k_seqid_90_cvg_95_rep_seq/snap_index_wtm_proteins_from_scaffolds_min1k_seqid
_90_cvg_95_rep_seq/ \
        --reads s3://bbrooks-analyses/nextflow_supporting_files/example_data_snap/reads/ \
        --outdir s3://bbrooks-analyses/temp_results/test_snap_nf_200217/ \
        -with-report nf_report_snap_PROJECTID.html \
        -with-trace nf_trace_snap_PROJECTID.txt \
        -with-timeline nf_timeline_snap_PROJECTID.html \
        -with-dag nf_dag_snap_PROJECTID.html -resume
```
For bullets 3-4, I don't provide any staging configuration or information. I think this is likely the answer to my problem. As mentioned above, when I ssh into a Batch instance, in attempts to see where the `aws s3 cp` job is transferring my reference database, I get a path like this `tmp/nxf.TW0FFOUa7R/`. After the DB has been transferred from S3, and the snap-aligner is running, if I run a `find` command and grep for my staged files, I see a path like this: `/var/lib/docker/overlay2/52a8777117a0bc546c4bbb604f5433b050c666d1308992a493f47cac7b8b8dca/merged/tmp/nxf.TW0FFOUa7R/reads_ERS436644_to_ref_wtm_linclust_seqid_90_cvg_95_rep.sam.gz`. Up until this point, not explicitly stating file stage-in/out information has worked beautifully for me using NextFlow on AWS Batch, but this is the first time I've tried using NF with such large file transfers, so perhaps I've been doing something incorrect all along (or perhaps inefficient is a better word, since my results look fine). 

Attached is the `.nextflow.log`: [nextflow_log_200217.txt](https://github.com/nextflow-io/nextflow/files/4216084/nextflow_log_200217.txt)

**Comment by pditommaso** [comment]
> If I instead run this on AWS Batch (i.e. executor = 'awsbatch' in my nextflow.config), the 300 Gb DB is copied from S3 for every mapping job. This is fine for a few mapping jobs but becomes extremely cumbersome for thousands.

I was understanding a different problem. What mentioned above is expected because each Batch job runs in its own container and therefore need to pull all the input data required.

**Comment by brooksomics** [comment]
So it's not possible to stage shared foreign files via the awsbatch executor? Said another way, if I have a massive reference database, is it possible to only transfer that DB once to each Batch node? For my particular use case, this would save thousands of hours of Batch time being redundantly spent on transferring this DB index. 

As mentioned previously, (non-redundant) staging works well when not on Batch, so I may end up running this on a local EC2 instance with NF or look for another approach.

**Comment by FirasSadiyah** [comment]
Just a thought. Create a dummy process which literally copies the file to be staged from its source channel to AWS batch. Then use the output of the dummy channel as input into other processes. Problem solved! 

```
process STAGE_FILE {

    input:
      path(TO_STAGE_FILE)

    output:
      path "${TO_STAGE_FILE}.staged"

    script:
      """
      cp ${TO_STAGE_FILE} ${TO_STAGE_FILE}.staged
      """
}
```

**Comment by namiller2015** [comment]
@brooksomics  
>So it's not possible to stage shared foreign files via the awsbatch executor? Said another way, if I have a massive reference database, is it possible to only transfer that DB once to each Batch node? For my particular use case, this would save thousands of hours of Batch time being redundantly spent on transferring this DB index.
> 
> As mentioned previously, (non-redundant) staging works well when not on Batch, so I may end up running this on a local EC2 instance with NF or look for another approach.

I wanted to follow up and see if you resolved this? I am working on my nextflow pipeline and am going to have the same issue once I get it running in Batch. My reference dataset won't be quite 300Gb but it's large enough I would prefer not to copy it down from the S3 bucket for every sample.

Thanks!

**Comment by brooksomics** [comment]
@namiller2015. No, I never resolved this, since I had to switch projects shortly after. Good luck!
