### ISSUE TITLE
Debug from .command.run with run environment

### ISSUE THREAD

**Issue by danielecook** [nextflow-io/nextflow#1498]
## New feature

When entering a work directory it would be nice to be able to spin up the work environment so you can debug a command.

## Usage scenario 

```bash
cd to work directory
bash .command.run --debug
``` 

This will load the docker/singularity/conda environment, set all relevant variables and do everything *except* running `.command.sh` The user can then debug things manually from there.

## Suggest implementation 

I can take a crack at it if you like, but curious what your thoughts are on the idea first.

**Comment by pditommaso** [comment]
I could see useful to launch the container in interactive mode. Though it would require to manage a separate command line for that. Not sure makes sense to add extra complexity to the wrapper script.

**Comment by danielecook** [comment]
This can be accomplished using a couple of bash aliases.

I will add a function here in the near future to do that.

https://gist.github.com/danielecook/bae19b7b9191b76fb6972bd7ef16718d

**Comment by danielecook** [comment]
Here is a start:

https://gist.github.com/danielecook/084fff96e97a7657b8fd5cc9ed278bcc

I will add singularity and conda as well.
