### ISSUE TITLE
Improved support for CWL by using the CWL reference runner + extras

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#1499]
## New feature

While putting together a [demo on using CWL inside Nextflow](https://github.com/stevekm/nextflow-demos/tree/master/CWL), I found a few modifications to Nextflow that might would make using CWL inside Nextflow a little easier. 

- default to using the CWL reference runner for running the CWL file

-  association of a CWL file with a Nextflow task

- building of input JSON for CWL

## Usage scenario 

Use case: you have CWL's but you want to run them in Nextflow.

## Suggest implementation 

# Default to using the CWL reference runner for running the CWL file

There are some old efforts to get Nextflow to run CWL directly, but I have not seen any updates on them so I am assuming this is not happening any time soon (please correct me on this)

https://github.com/nextflow-io/nextflow/pull/583

https://github.com/nextflow-io/nextflow/issues/545

It seems like it would be easier to just have Nextflow call on the default CWL reference runner to run the CWL file. You can already do that manually inside a Nextflow task. So why not just make that the default way to run a CWL?

### Association of a CWL file with a Nextflow task

Right now, in order to direct my Nextflow task to the correct CWL file to run, I used this method:

```
params.cwl_dir = "cwl"
def cwl_dir = new File("${params.cwl_dir}").getCanonicalPath()

process create_message {
    input:
    val(sampleID) from Channel.from(['Sample1', 'Sample2', 'Sample3', 'Sample4'])

    output:
    set val(sampleID), file("${output_file}") into messages, messages2

    script:
    output_file = "message.txt"
    """
    jq -n --arg message "hello this is ${sampleID}" '{"message":\$message}' > input.json
    cwl-runner "${cwl_dir}/echo.cwl" input.json
    """
}
```

I basically am passing the full path to the CWL file to the `cwl-runner`. 

This is kinda annoying. It would be nice if the CWL files were 'discoverable' by Nextflow the way items in the `bin` dir are, so they could be called directly in the script block like this:

```
script:
"""
cwl-runner echo.cwl input.json
"""
```

Alternatively, it would be *even cooler* if you could just associate the CWL file with the task as a tag or label of some kind. Like this:

```
process create_message {
    cwl "echo.cwl"

    input:
    val(sampleID) from Channel.from(['Sample1', 'Sample2', 'Sample3', 'Sample4'])

    output:
    set val(sampleID), file("message.txt") into messages, messages2
}
```

### Building of input JSON for CWL

In order to pass the Nextflow task `input` to the CWL, I am currently building the JSON input file directly inside the `script` block with `jq`. 

This is really ugly. It would be cool if Nextflow could just do this automatically, converting all the `input` items into a JSON that will exist in the  tasks' `work` dir automatically. 

So instead of this:

```
process create_message {
    input:
    val(sampleID) from Channel.from(['Sample1', 'Sample2', 'Sample3', 'Sample4'])

    output:
    set val(sampleID), file("${output_file}") into messages

    script:
    output_file = "message.txt"
    """
    jq -n --arg sampleID "${sampleID}" '{"sampleID":\$sampleID}' > input.json
    cwl-runner "${cwl_dir}/echo.cwl" input.json
    """

```

it would be more like this:

```
process create_message {
    input:
    val(sampleID) from Channel.from(['Sample1', 'Sample2', 'Sample3', 'Sample4'])

    output:
    set val(sampleID), file("${output_file}") into messages

    script:
    output_file = "message.txt"
    """
    # file 'input.json' automatically created by Nextflow and its contents look like this:
    # { "sampleID": "Sample1" }
    cwl-runner "${cwl_dir}/echo.cwl" input.json
    """
}
```

Maybe this is something that could be implemented with a process directive as well, something like this:

```
process create_message {
    input_json "input.json"

    input:
    val(sampleID) from Channel.from(['Sample1', 'Sample2', 'Sample3', 'Sample4'])

    output:
    set val(sampleID), file("${output_file}") into messages

    script:
    output_file = "message.txt"
    """
    cwl-runner "${cwl_dir}/echo.cwl" input.json
    """
}
```

### All together

Using the process directive tag idea you could even combine both of these, so that you get a Nextflow process that runs a CWL and automatically creates its own input.json;

```
process create_message {
    input_json "input.json"
    cwl "echo.cwl"

    input:
    val(sampleID) from Channel.from(['Sample1', 'Sample2', 'Sample3', 'Sample4'])

    output:
    set val(sampleID), file("${output_file}") into messages
}
```

## Conclusion

I think that combining these small tweaks, the creation of an automatic JSON creation from the Nextflow process inputs and the association of a CWL file with a Nextflow task, and the usage of the CWL reference runner to run CWL, you would be able to run CWL files more easily inside your Nextflow pipeline. Conceptually, it does not seem that different from the current "execution engine" configuration that Nextflow already has. It seems like this would be a lot easier to build than a full-blown CWL parser & executer. Since CWL has its own spec and its own reference runner, it would probably be a lot easier to implement this as well so that changes to CWL spec do not break compatibility in Nextflow. This would also be really nice for users, so they would have not to decide between CWL vs. Nextflow, they could use both natively.

**Comment by KevinSayers** [comment]
It seems like a good idea to me. It has been awhile since I worked with CWL so I can't recall issues we ran into previously anymore. You could have things like a Docker requirement in the CWL that Nextflow would be unaware of, obviously not a major issue but I feel with more complicated workflows other problems may appear. 

It could be a good opportunity to revisit CWL as DSL2 lends itself to more easily mixing and matching too in my opinion. Though I am not sure how many users would utilize this.

**Comment by pditommaso** [comment]
Yes, we have explored the idea of importing CWL tools as NF processes in the task. Now NF has full support for external modules inclusion. 

It could be possible to check the file extension i.e. `.cwl` and parse the CWL descriptor mapping it to an NF task. 

Therefore I'm closing this in favour of #545.
