### ISSUE TITLE
nextflow kuberun defaults to standard profile

### ISSUE THREAD

**Issue by cbmckni** [nextflow-io/nextflow#1507]
## Bug report 

Running Nextflow on Kubernetes does not allow the use of profiles, which are very important to the adaptability of workflows. Using the `-profile` flag does not throw an error, but the workflow's profile defaults to standard, regardless of what profile is passed.

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

(Give an brief description of the expected behavior 
and actual behavior)

We need to override a configuration variable when our workflow is run on Kubernetes.

This was implemented by adding the lines:

```
profiles {
....
  k8s {
    params.input.base_dir = "projects/GEMmaker"
....
  }
```

The command `nextflow kuberun systemsgenetics/gemmaker -profile k8s -v deepgtex-prp -c nextflow.config` does not use the `k8s` profile:

```
$ nextflow kuberun systemsgenetics/gemmaker -profile k8s -v deepgtex-prp -c nextflow.config 
Pod started: high-venter
N E X T F L O W  ~  version 19.07.0
Launching `systemsgenetics/gemmaker` [high-venter] - revision: 845d3f24f4 [master]

===================================
 G E M M A K E R   P I P E L I N E
===================================

Workflow Information:
---------------------
  Project Directory:  /workspace/projects/systemsgenetics/gemmaker
  Launch Directory:   /workspace/cole
  Work Directory:     /workspace/cole/work
  Config Files:       [/workspace/projects/systemsgenetics/gemmaker/nextflow.config, /workspace/cole/nextflow.config]
  Container Engine:   null
  Profile(s):         standard
```

Expected behavior:

```
Workflow Information:
---------------------
  Project Directory:  /workspace/projects/systemsgenetics/gemmaker
  Launch Directory:   /workspace/cole
  Work Directory:     /workspace/cole/work
  Config Files:       [/workspace/projects/systemsgenetics/gemmaker/nextflow.config, /workspace/cole/nextflow.config]
  Container Engine:   null
  Profile(s):         standard, k8s (or maybe just k8s)
```

### Steps to reproduce the problem

(Provide a test case that reproduce the problem either with a self-contained script or GitHub repository)

Run `nextflow kuberun cbmckni/gemmaker -profile k8s -v <namespace>` on a k8s cluster. You do not need any input for this basic test.

The output will contain:
```
Workflow Information:
---------------------
  Project Directory:  /workspace/projects/cbmckni/gemmaker
  Launch Directory:   /workspace/cole
  Work Directory:     /workspace/cole/work
  Config Files:       [/workspace/projects/cbmckni/gemmaker/nextflow.config, /workspace/cole/nextflow.config]
  Container Engine:   null
  Profile(s):         standard
```

### Program output 

(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)

The nextflow.log file does not contain any useful information, as the workflow itself successfully fails. Can provide if requested.

### Environment 

* Nextflow version: nextflow version 20.01.0.5264
* Java version: 8
* Operating system: Linux
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

### Additional context

(Add any other context about the problem here)

This problem should be present with any workflow, feel free to use another to test if profiles can be passed to k8s executor.

**Comment by cbmckni** [comment]
The whole purpose of us using profiles to change variables depending on executor is for a stable fix to this: https://github.com/nextflow-io/nextflow/issues/1050

**Comment by bentsherman** [comment]
@cbmckni I just tested a fix for that issue and it worked for me:
```
Workflow Information:
---------------------
  Project Directory:  /workspace/projects/systemsgenetics/GEMmaker
  Launch Directory:   /workspace/eceftl3
  Work Directory:     /workspace/eceftl3/work
  Config Files:       [/workspace/projects/systemsgenetics/GEMmaker/nextflow.config, /workspace/eceftl3/nextflow.config]
  Container Engine:   null
  Profile(s):         standard

[...]

Software Parameters:
--------------------
  Trimmomatic clip path:      /workspace/projects/systemsgenetics/GEMmaker/files/fasta_adapter.txt
  Trimmomatic minimum ratio:  0.7
```

So it seems that although Nextflow reports that it's still using the standard profile, it did in fact apply the k8s profile because the trimmomatic clip path is correct now.

**Comment by bentsherman** [comment]
Some additional context since I've been running things on k8s again recently. I thought this issue was just a bug of Nextflow not displaying the correct profiles in kubernetes. In reality everything is behaving correctly. When using kuberun, Nextflow "applies" the profiles you specified to the default nextflow.config, and then launches the pipeline on kubernetes with that config and no profiles, as the new config file has the profiles section removed. You can confirm this by checking `nextflow.config` and `.nextflow.log` in the directory where the pipeline is launched on kubernetes, not the local directory where you executed `kuberun`.

I think this comment will reopen this issue, but it can be closed. I don't think I can close it myself.
