### ISSUE TITLE
global configuration for work directory

### ISSUE THREAD

**Issue by wookietreiber** [nextflow-io/nextflow#1509]
Did I miss how to do it in the documentation? If not, please consider this a feature request.

Instead of `nextflow run -w /work/$USER/nextflow` it would be useful to be able to specify this globally on a system/platform in `~/.nextflow/config`:

```
workdir = '/work/$USER/nextflow'

process {
  executor = 'uge'
}
```

---

To explain the motivation: on our cluster, the home directory has a quota, while `/work` doesn't and the underlying file systems also have different performance characteristics.

**Comment by pditommaso** [comment]
This is already possible. Just use `workDir` instead of `workdir`. The configuration can also be applied using the following env variables: 

```
export NXF_WORK=/some/path
export NXF_EXECUTOR=slurm
```

https://www.nextflow.io/docs/latest/config.html#environment-variables

**Comment by wookietreiber** [comment]
Thanks @pditommaso!

Does this work for all command line arguments, i.e. those shown with `nextflow help run`?

**Comment by pditommaso** [comment]
Nope
