### ISSUE TITLE
Add "-o pipefail" for bash scripts

### ISSUE THREAD

**Issue by dvallenet** [nextflow-io/nextflow#151]
In ".command.run", ".command.sh" bash script should be executed with the option pipefail to exit with a non-zero status when a command fails in a pipeline.

/bin/bash -ue -o pipefail ..../.command.sh

**Comment by mfoll** [comment]
We had a chat about it a few weeks ago with @pditommaso and it doesn't seem to be a good idea to set it by default. See https://gitter.im/nextflow-io/nextflow?at=57051ef53f7926d90dd6766d and then https://gitter.im/nextflow-io/nextflow?at=570ccf70ddb5a2cf3bbb8cc7 when I realized it was causing errors. In short you can set it if you want in the config file by adding:
```
process.shell = ['/bin/bash', '-ueo','pipefail' ]
```
But be careful as some bash commands will return a non-zero exit code that nextflow will catch as errors.  For example:
```bash
$ seq 1 100000 | head -1 ; echo $?
1
0
$ set -o pipefail ; seq 1 100000 | head -1 ; echo $?
1
141
``` 
A `head` command can interrupt another one, returning error 141. It can also happen with `grep -q` for example.

**Comment by pditommaso** [comment]
Yes, this cannot be added by default for the reason explained by Matthieu. However you can add it easily to your pipeline writing the `pipefail` option on top of your scripts or in the config file as shown above.

**Comment by dvallenet** [comment]
Ok thanks for this tip. 
But set -e as a default config  could also break some code: 
```
$ grep hacker /etc/passwd ; echo $?
1
$ set -e ; grep hacker /etc/passwd ; echo $?
Connection to xxxx closed.

```
See:
http://wiki.bash-hackers.org/scripting/obsolete
http://mywiki.wooledge.org/BashFAQ/105

**Comment by pditommaso** [comment]
The main problem is that adding now the `-o pipefail` as default it may break existing pipelines.
