### ISSUE TITLE
Partial S3 directory transfer failure does not terminate process

### ISSUE THREAD

**Issue by chrismiddleton** [nextflow-io/nextflow#1512]
## Bug report 

When a directory is being staged by Nextflow from S3 to a working directory on an instance, a failure to transfer some of the files due to storage space limitations does not terminate the process. This seems like it could alternatively lead to a mysterious failure or, potentially, inconsistent output, if the list of files is dynamic and the process were to otherwise continue.

### Expected behavior and actual behavior

Expected: Nextflow terminates the process with an error that the files were not all able to be staged.

Actual: the process continues execution until something further along fails (e.g., a command line tool fails to find the file that was specified on the command line)

The error does show up in the .command.log as so:

download failed: s3://bucket/path/to/dir to dir/file1 [Errno 28] No space left on device
download failed: s3://bucket/path/to/dir to dir/file2 [Errno 28] No space left on device

while some of the files were able to be transferred.

### Steps to reproduce the problem

1. Use a default-sized AWS instance.
2. Run a NF script that stages a directory that includes some files that are too large.
3. Observe that the failed transfers just show up in the log

### Program output 

Relevant part of log:

```
nxf-scratch-dir ip-xxx-xx-xx-xxx:/tmp/nxf.XxxxXxxx
download failed: s3://bucket/path/to/dir/file1 to dir/file1 [Errno 28] No space left on device
download failed: s3://bucket/path/to/dir/file2 to dir/file2 [Errno 28] No space left on device
download failed: s3://bucket/path/to/dir/file3 to dir/file3 [Errno 28] No space left on device
```

### Environment 

* Nextflow version: version 20.01.0 build 5264
* Java version: openjdk version "1.8.0_222"
* Operating system: AWS linux
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)

### Additional context

It sounds like `aws s3 cp --recursive` continues after failing transfer, but maybe sets the exit code to 1?

It sounds like originally `aws s3 cp --recursive` returned 0 on partial transfer, but was fixed back in 2015: https://github.com/aws/aws-cli/issues/1442

Assuming this is true, it looks like the problem might be that the command.run script doesn't check for failure of the s3 cp command?

Though it has a "set -e" at the top, perhaps something is not stopping as it should? This SO post seems to indicate that set -e may not work as expected when subshells are involved:

https://unix.stackexchange.com/a/296536/67823

One way or the other, I would expect that Nextflow could be fixed to detect partial transfer failure and terminate the process, rather than continuing.

Thank you for all your work on this project.

**Comment by mgratigny** [comment]
Hello,
I have a similar problem when I launch a process to concatenate multiple files.
Nextflow has no left space but the process continue and is marked as “completed” but the file generated is corrupted.

In the .command.log file I have this: 
`cat: write error: No space left on device`

Is it possible to ask to nextflow to return an error in this way ? 

I use  nextflow version 20.10.0.5430.
