### ISSUE TITLE
DSL2: come up with good practice to be able to use root/bin directory from any workflow

### ISSUE THREAD

**Issue by kerimoff** [nextflow-io/nextflow#1513]
## New feature
When we use DSL 2, and used `$baseDir` in a module workflow script it will evaluate different pathes depending on which workflow we are running (main or module workflow) and this issue results in a trouble running main.nf and module1.nf independently (if we used `$baseDir` in workflow script.)

I don't know what is the best way to overcome this. creating a e.g. symlink of bin under modules/ directory is not an elegant solution. because it is also common to have publishDir and storeDir depending on baseDir in scripts.

## Usage scenario 
let's say we have a `projRoot/main.nf` and`projRoot/modules/module1.nf` modules and `projRoot/bin/scripts/` scripts we want to use. when we use e.g. `$baseDir/bin/scripts/script.R` in module1.nf and we want to run module1.nf independently using implicit `workflow` keyword,  `$baseDir` will be evaluated as `projDir/modules` which does not have `bin` folder.

## Suggest implementation 
No suggestions

**Comment by pditommaso** [comment]
Thanks for reporting this and, yes, I've found a similar problem in the past. Likely the simplest solution could be to add `moduleDir` implicit variable that resolves the current module location path. 

Another possibility, not necessarily complementary, it could be to add the ability to have a `bin/` folder in the module directory which is automatically added as it happens for the workflow `bin/` folder. Tho it could be more complicated to be implemented.

**Comment by pditommaso** [comment]
Solved by 7832a697.
