### ISSUE TITLE
groupTuple Cannot invoke method add() on null object

### ISSUE THREAD

**Issue by danielecook** [nextflow-io/nextflow#1517]
## Bug report 

I like to pass a map object around that contains all the metadata for a given sample so it is easily accessible. If I execute a groupTuple operation on a map or nested components the groupTuple function sometimes fails. This appears to be dependent on the order in which items flow into the groupTuple, and on the use of nested structures.

For example, below if I `mix` `ch1` with `ch2`, I get an error: `Cannot invoke method add() on null object`.

However, if I do the opposite (`mix` `ch2` with `ch1`)I,  get no error although the resulting channel is nested in a weird way.

```groovy
nextflow.preview.dsl=2

def map_vals = [x: 1,
                             y: 2]

ch1 = Channel.from(map).map { ["patientA", map_vals] }
ch2 = Channel.from(map).map { ["patientA", [1, 2, 3]] }

// This works
ch1.mix(ch2).view().groupTuple().view()

// This does not and throws an error: Cannot invoke method add() on null object
ch2.mix(ch1).view().groupTuple().view()

/*
// Output:
[patientA, 1, 2, 3]
[patientA, [x:1, y:2]]
[patientA, 1, 2, 3]
[patientA, [x:1, y:2]]
[patientA, [1, [x:1, y:2]], [2], [3]]

// Expected:
[patientA, [[x:1, y:2], 1, 2, 3]] or [patientA, [x:1, y:2], 1, 2, 3]
*/

// Additional examples
ch1 = Channel.from(map).map { ["patientA", 8, 9, 10, 11] }
ch2 = Channel.from(map).map { ["patientA", [1, 2, 3, 5]] }

// [patientA, [8, [1, 2, 3, 5]], [9], [10], [11]]
// Reverse (chr2 into 1 does not work)

```

### Environment 

* Nextflow version: 20.01.0
* Java version: "13.0.2" 2020-01-14
* Operating system: macOS
* Bash version: 5.0.11

**Comment by pditommaso** [comment]
Sure, I'm getting this output 

```
[patientA, [x:1, y:2]]
[patientA, [x:1, y:2]]
[patientA, [1, 2, 3]]
[patientA, [1, 2, 3]]
[patientA, [[x:1, y:2], [1, 2, 3]]]
[patientA, [[x:1, y:2], [1, 2, 3]]]
```

**Comment by danielecook** [comment]
It must be related to the version of java that I am using. I think I had a newer version installed at home which was causing the issue. After re-testing on my work it is no longer an issue. Thank you for looking into it.
