### ISSUE TITLE
Invalid parameter conversion

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#1519]
## Bug report 

When passing a parameter value prefixed with a double `--` e.g. `--nogroup`, the string value is interpreted as a boolean value. 

To replicated use 

```
nextflow run test.nf --foo '--nogroup'
```

test.nf 
```
params.foo = 'bar'

println "foo: $params.foo"
```

**Comment by pditommaso** [comment]
Looking better this is not a bug, but a .. *feature*. 

To summarise, when running 

```
nextflow run <script> --this --that 
```

NF interprets `--this` as a flag parameter with an implicit `true` value and `--that` as a second flag parameter.

As a simple workaround use 

```
nextflow run <script> --this=--that 
```

which forces to parse `--that` as value of `--this`.

**Comment by FelixKrueger** [comment]
I think this is another side-effect of the fact that options in Nextflow can either work as flags (TRUE/FALSE) **or** take an argument, and there is real way of enforcing this.

If I need to pass in several parameters, I think your suggestion would have to be:

```
nextflow run <script> --this='--that --clip_r1 10 --clip_r2 15' 
```

is pretty much equivalent to the workaround I have been using already, which is:

```
nextflow run <script> --this "'--that --clip_r1 10 --clip_r2 15'" 
```

(so `""` double quotes which get consumed by the bash shell, with an inner set of `''` single quotes), followed by removing all `'` within the string with a command like: `this.replaceAll(/'/,"")`. Let's hope we won't ever get any options that contain apostrophes ....

As an alternative, do you think it is too late already to enforce options to work either as flags, or  take a certain type of argument such as `str` or `int`?

**Comment by pditommaso** [comment]
Well, the `=` does not require the nested quoting and spares from the stripping the quote later that's pretty nasty. 

> As an alternative, do you think it is too late already to enforce options to work either as flags, or take a certain type of argument such as str or int?

There's no way to do it, because the command line parser is not aware of the params types.

**Comment by FelixKrueger** [comment]
Just to conclude this issue: I have just done a bit of testing, and it does indeed seem to work alright. 

If you only want to pass on only a single flag, no quotes are required, e.g.: 

```
nf_trim_galore *fastq.gz --trim_galore_args=--nextera
```

If you want to pass in either several options, or options that expect arguments, quotes are required:

```
nf_trim_galore *fastq.gz --trim_galore_args="--clip_r1 6 --clip_r2 9 --nextera"
```
Both single `'` and `"` double quotes work equally well for this. I'll settle for this, and will remove all of the `replaceAll` methods I have used so far.

Many thanks for looking into this. Cheers, Felix
