### ISSUE TITLE
Feature Request: Shutdown script/Graceful Termination

### ISSUE THREAD

**Issue by daudn** [nextflow-io/nextflow#1521]
## New feature

After looking into nextflow, I have found out that error handling is not sufficient. Would be nice to have a feature where if your workflow failed, you could perform a "Graceful Termination". This way if the workflow is running in production, there is a way to say "Update a database" or "Mark job as failed" or "flag that workflow as cannot complete"

## Usage scenario 

I am using Nextflow to perform HLA Sequencing. I upload local data to the cloud, and update a database saying, "Cloud: True", "sent_for_processing: True" and when the workflow completes successfully I update the database saying "Processed: True"

However, if my workflow fails at any step I don't have any means to update "Failed:True" without explicitly adding logic to each and every process within the workflow.

I tried doing `nextflow run ... || python failure.py` but that doesn't seem to work when creating subprocesses from within my Python script saying: "Revision not allowed on script"

Point being, graceful termination is essential for performing cleanup or setting flags or updating database. 

Google Cloud Platform has a `shutdown script` with each VM. If a VM is terminated by some unfamiliar event, it triggers the shutdown script. 

I do believe this would help making nextflow even more robust.

## Suggest implementation 

In simple pseudo code:
```
if (workflow_errors_out()):
    run shutdown_script()
```

**Comment by saint7007** [comment]
@daudn Hi, did you manage any work around for this feature?

**Comment by mribeirodantas** [comment]
Hello, @saint7007 and @daudn! 😄 

It's not clear to me why [`onError`](https://www.nextflow.io/docs/latest/metadata.html?highlight=onerror#error-handler) and [`onComplete`](https://www.nextflow.io/docs/latest/metadata.html?highlight=onerror#completion-handler) are not enough for what you want to do. Could you give some examples, please? What limitations of event handlers prevent you from doing what you want?
