### ISSUE TITLE
nexflow (conda) launcher didn't pick java executable correctly under macOS

### ISSUE THREAD

**Issue by telatin** [nextflow-io/nextflow#1523]
### Expected behavior and actual behavior

 `nextflow -version` fails:

```
Unable to find any JVMs matching version "1.8+".
No Java runtime present, try --request to install.
/Users/telatina/miniconda3/bin/nextflow: line 319: /bin/java: No such file or directory
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /bin/java
 NXF_OPTS: 
```
but *java* is in my `$PATH`, as  `java -version` will print:
```                 
openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)
```
### Steps to reproduce the problem

1. Installed *nextflow* using `conda install -y -c conda-forge -c bioconda nextflow` on **macOS Catalina**.
1. I use *Fish shell* by default, but the `nextflow` executable shebang points to Bash (to the actual path, so probably courtesy of Anaconda). My Bash version is "GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)"

### Hack that solved my problem

My Java binary comes with Anaconda, but the system has a `/usr/libexec/java_home` symlink that is apparently not working.

I imagine there was a good reason to have that file checked before `$(which java)`, but for me this would have spared some troubles.

```bash
# Determine the Java command to use to start the JVM.
if [ ! -x "$JAVA_CMD" ] ; then
    if [ -d "$JAVA_HOME" ] ; then
        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
            # IBM's JDK on AIX uses strange locations for the executables
            JAVA_CMD="$JAVA_HOME/jre/sh/java"
        else
            JAVA_CMD="$JAVA_HOME/bin/java"
        fi
    # HACK: COMMENTED THE FOLLOWING TWO LINES
    #elif [ -x /usr/libexec/java_home ]; then
    #    JAVA_CMD="$(/usr/libexec/java_home -v 1.8+)/bin/java"
    else
        JAVA_CMD="$(which java)" || JAVA_CMD=java
    fi
fi
```

### Environment 

* Nextflow version: 20.01.0 build 5264 
* Java version: 1.8.0_152-release
* Operating system: macOS Catalina
* Bash version: I use "fish, version 3.0.2", but my Bash is "GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)"

**Comment by pditommaso** [comment]
> the system has a /usr/libexec/java_home symlink that is apparently not working.

I think this was the problem.

**Comment by mjhipp** [comment]
I had this issue as well when using jenv for my java versions. By replacing the same code block above with `JAVA_CMD="$(which java)"` it fixed the issue.
