### ISSUE TITLE
PBS Script in bash LogIn mode

### ISSUE THREAD

**Issue by VivekTodur** [nextflow-io/nextflow#1525]
Hi,
while initiating pipeline on PBSPro cluster pbs script starts with "#!/bin/bash", instead of this I would like to have this line as "#!/bin/bash -l". Can somebody help me to achive this,

Expected Format of PBS Script,

**#!/bin/bash -l**
#PBS -N ABCDEFGH

**Comment by pditommaso** [comment]
There's no control over it.

**Comment by VivekTodur** [comment]
Hi,

At least is there a hack to achieve it???  For me, it is impossible to run on PBSpro without login mode...("**-l**")

**Comment by stekaz** [comment]
Not sure if I've mis-understood, but perhaps try the following config?

```
process {
  executor = 'pbspro'
  shell = ['/bin/bash', '-l']
}
```

Other "safe" options can be added like so:

```
process {
  executor = 'pbspro'
  shell = ['/bin/bash', '-leuo', 'pipefail']
}
```

**Comment by VivekTodur** [comment]
Thank you @stekaz, its working for me...

**Comment by VivekTodur** [comment]
Thank you @stekaz, it's working for me...
