### ISSUE TITLE
nix/guix environments

### ISSUE THREAD

**Issue by Emiller88** [nextflow-io/nextflow#1526]
## New feature

Hello! I'm thinking about implementing nix/guix environments for a process.

Similar to `conda`, `docker`, etc. 

I found this issue, I think the problem with it was the actual building of nextflow.

https://github.com/nextflow-io/nextflow/issues/1395

This is not for the nextflow builds but the individual process

## Usage scenario 

```nextflow
process foo {
  nix-env 'bwa samtools multiqc'

  '''
  your_command --here
  '''
}
```
## Suggest implementation 

I'll need to look under the hood at the conda implementation.

**Comment by pditommaso** [comment]
How the linked issue is related to this requirement?

**Comment by Emiller88** [comment]
I was explaining how the two were different issues, since the last issue was closed. And to show that I couldn't find a previous issue for this topic.

**Comment by pditommaso** [comment]
Looks stalled. Closing.

**Comment by lindenb** [comment]
Can you please reopen this?

The support for guix would be very useful.  Our sysadmins told us that the "conda partition" is full, they'd like us to use guix instead of the conda/mamba/micromamba ecosystem.

**Comment by pditommaso** [comment]
The use of containers would not be an option for you?

**Comment by lindenb** [comment]
@pditommaso well, our server doesn't allow us to build apptainer images , so we have to build the images on our personal laptop and then we have upload the image on the server. That's not an ideal solution when you want to explore/test things. Meanwhile guix looks very fast.

I don't have much experience with guix. For now I just know how to install a package. But it looks like much more powerful than conda and, as far as I understand, you can "code" your package with a scheme/lisp syntax, and generate a package just like a git project (?) with diff/add/remove etc....

Our sysadmins love this system. They used to work with physicists but now we - the biologists -  are coming with our conda-stuff and it looks like it's a problem.
