### ISSUE TITLE
S3 paths not getting parsed properly fromPath/map/group/tuple

### ISSUE THREAD

**Issue by tamuanand** [nextflow-io/nextflow#1528]
## Bug report 

S3 Paths not parsed properly with fromPath/map/group/tuple. I am using this example as a guide - http://nextflow-io.github.io/patterns/index.html#_process_outputs_into_groups

### Expected behavior and actual behavior
Expected Behaviour
```
record1    s3://<bucket_name>/folder1/folder2/record1-singles.fa.gz
record2    s3://<bucket_name>/folder1/folder2/record2-singles.fa.gz
```
Actual behavior
```
record1    /<bucket_nanme>/folder1/folder2/record1-singles.fa.gz
record2    /<bucket_name>/folder1/folder2/record2-singles.fa.gz
```

### Steps to reproduce the problem
```
fastaDir = 's3://<bucket_nane>/folder1/folder2/*-singles.fa.gz'
println fastaDir

Channel
    .fromPath("${fastaDir}")
    .map { path ->
        def key = path.name.toString().tokenize('_').get(0)
        return tuple(key, path)
     }
    .groupTuple()
    .into { groups_ch; print_groups_ch }

print_groups_ch.subscribe { row -> println "${row}"}

```
### Relevant Text from .nextflow.log

DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: /<complete_s3_path_without_s3://>/; pattern: *-singles.fa.gz; options: [:]
DEBUG nextflow.file.FileHelper - Path matcher not defined by 'S3FileSystem' file system -- using default default strategy

### Environment 

* Nextflow version: 20.01.0
* Java version: openjdk version "1.8.0_242"
* Operating system: Linux
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)

**Comment by pditommaso** [comment]
That's an expected behaviour, due to the underlying API which strips the file scheme. You can use `.toUriString()` to the full URI file path.
