### ISSUE TITLE
Groovy Cheat sheet dead link

### ISSUE THREAD

**Issue by splaisan** [nextflow-io/nextflow#1529]
the link to the 'Groovy Cheat sheet' on https://www.nextflow.io/docs/latest/script.html#script-page seems dead.

I found a doc here that may be the same (no way to check)?

http://www.cheat-sheets.org/saved-copy/rc015-groovy_online.pdf

**Comment by pditommaso** [comment]
That's it! thanks for reporting the broken link. Solved 0a1ec9a9.
