### ISSUE TITLE
Feature request: variable executor configuration settings

### ISSUE THREAD

**Issue by thdpuydt** [nextflow-io/nextflow#1530]
Hi,

I'm using nextflow to automate my pipelines, executed on sge. In the past I used array jobs, giving me the possibility to change several settings on the fly. E.g. at night, when the system is less busy, it's nice to adjust the number of tasks allowed to run together (e.g. ``qalter <job_id> -tc <no_of_tasks>``). To my knowledge this is not possible in nextflow (I'm using ``executor.queueSize`` to limit the number of parallel jobs). Is this indeed currently not possible, and if not, would it be possible to include this option in a future update?

Thanks!

**Comment by KevinSayers** [comment]
Have you looked at `clusterOptions` ? You should be able to set `clusterOptions '-t 1-100 -tc 10'` and then use qalter as you mention. The challenge I think would be modifying your script block. 

There is a related issue here too #1477

**Comment by pditommaso** [comment]
Kevin answer is likely the best solution. Closing this.
