### ISSUE TITLE
Using each tuple results in a compilation error

### ISSUE THREAD

**Issue by chrismiddleton** [nextflow-io/nextflow#1531]
## Bug report

I expected that you could use each on a channel of tuples by doing `each tuple ...` in the process inputs, but that gives a compilation error. I can see how this is more of a feature request, but I filed it as a bug report as the docs didn't seem to indicate any issue with combining each and tuple, though there isn't an example in the docs of doing both at the same time either.

### Expected behavior and actual behavior

Using `each tuple` gives a compilation error, whereas it was expected that you could use each to iterate over all the tuples in a channel.

### Steps to reproduce the problem

Here is a test script:

```
tuples = Channel.fromList([['a', 1], ['b', 2], ['a', 3], ['b', 4]])
        .groupTuple()
letters = Channel.fromList(['c', 'd'])

process TestProcess {
        input:
        each tuple id, numbers from tuples
        letter from letters

        output:
        stdout into result

        script:
        """
        echo "$id" "${numbers.join(',')}" "$letter"
}

result.subscribe { println "$it" }
```

### Program output 

Actual output:

```
N E X T F L O W  ~  version 19.10.0
Launching `test2.nf` [astonishing_mclean] - revision: 0d37231e37
Script compilation error
- file : test2.nf
- cause: expecting '}', found ',' @ line 10, column 15.
   	each tuple id, numbers from tuples
                 ^

1 error
```

Expected output:

```
a 1,3 c
b 2,4 c
a 1,3 d
b 2,4 d
```

### Environment 

* Nextflow version: 19.10.0
* Java version: 1.8.0_181
* Operating system: macOS 10.13.6
* Bash version: 3.2.57

### Additional context

I thought I had a workaround by turning it into a list and then back into a channel, but this gives a different error:

```
tuplesList = Channel.fromList([['a', 1], ['b', 2], ['a', 3], ['b', 4]])
        .groupTuple()
        .toList()
        .collect { [it[0], it[1]] }
println(tuplesList)
tuples = Channel.fromList(tuplesList)

letters = Channel.fromList(['c', 'd'])

process TestProcess {

        input:
        each array from tuples
        letter from letters

        output:
        stdout into result

        script:
        """
        echo "${array[0]}" "${array[1].join(',')}" "$letter"
        """

}

result.subscribe { println "$it" }
```

Error:

```
Invalid method `fromList` invocation with arguments: DataflowVariable(value=[[a, [1, 3]], [b, [2, 4]]]) (groovyx.gpars.dataflow.DataflowVariable) on Channel type

 -- Check script 'test3.nf' at line: 5 or see '.nextflow.log' file for more details
```

I also tried putting parentheses around tuple's contents in case it was an ambiguous parse:

```
each tuple(id, numbers) from tuples
```

but that did not work.

Thank you for all your hard work on Nextflow! It's an awesome tool.

**Comment by pditommaso** [comment]
That is expected, `each` does not composite inputs i.e. `tuple`. Use [combine](https://www.nextflow.io/docs/latest/operator.html#combine) as a workaround.

**Comment by chrismiddleton** [comment]
Thank you so much for your quick reply. Re-reading the docs, although it could be emphasized a little more, I see the intent is that it be used for collections, not channels.

For anyone else encountering this issue, here is a working solution using combine.

```
tuples = Channel.fromList([['a', 1], ['b', 2], ['a', 3], ['b', 4]])
        .groupTuple()
letters = Channel.fromList(['c', 'd'])
tuples_and_letters = tuples.combine(letters)

process TestProcess {
        input:
        tuple id, numbers, letter from tuples_and_letters

        output:
        stdout into result

        script:
        """
        echo "$id" "${numbers.join(',')}" "$letter"
        """
}

result.subscribe { println "$it" }
```
