### ISSUE TITLE
Can't use empty string as path

### ISSUE THREAD

**Issue by chbk** [nextflow-io/nextflow#1532]
### Expected behavior and actual behavior

I have an issue with [this exception](https://github.com/nextflow-io/nextflow/blob/0a1ec9a924ec6d8b0bbe857ad93172f2e8997b5a/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L1646) which outputs "Not a valid path value" when an empty string `''` is given as a path. Prior versions of Nextflow didn't cause this.

I need empty strings as path names to process paired and unpaired reads files together. My process receives file pairs:

```
[a_R1.fq, a_R2.fq]
[b_R1.fq, b_R2.fq]
[c.fq, ]
```

When a file does not have a mate, the second path is an empty string `''`. I can then simply pass those two path values to my script, which treats the input as paired or unpaired based on the number of arguments.

Now the alternative is using `'/'` to indicate an empty path, and then detecting that in the script section, which isn't as elegant.

### Steps to reproduce the problem

```nextflow
Channel.fromPath([
  'a_R1.fq',
  'a_R2.fq',
  'b_R1.fq',
  'b_R2.fq',
  'c.fq'
]).concat(Channel.of('')).set {
  files
}

process test {

  input:
    tuple path(f1), path(f2) from files.buffer(size: 2)

  output:
    stdout into out

  script:
    """
      echo $f1 $f2
    """
}

out.view()
```

Outputs:

```
N E X T F L O W  ~  version 20.01.0
Launching `test-input.nf` [grave_fourier] - revision: 507f0f3a58
[-        ] process > test [  0%] 0 of 2
Error executing process > 'test (3)'

Caused by:
  Not a valid path value: 
```

Hack alternative:

```nextflow
Channel.fromPath([
  'a_R1.fq',
  'a_R2.fq',
  'b_R1.fq',
  'b_R2.fq',
  'c.fq'
]).concat(Channel.of('/')).set {
  files
}

process test {

  input:
    tuple path(f1), path(f2) from files.buffer(size: 2)

  output:
    stdout into out

  script:
    """
      [[ $f2 = null ]] && f2="" || f2=$f2
      echo $f1 \$f2
    """
}

out.view()
```

### Environment 

* Nextflow version: 20.01.0
* Java version: openjdk 12.0.2 2019-07-16
* Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

**Comment by pditommaso** [comment]
Use `.`

**Comment by chbk** [comment]
I tried it and it is evaluated to the current directory, unfortunately.

**Comment by pditommaso** [comment]
It's correct that an empty is reported as an error. It's trick your use case. I can suggest using a special file name to signal a missing file eg. `NONE.fq`
