### ISSUE TITLE
Pipeline tests

### ISSUE THREAD

**Issue by szymonwieloch** [nextflow-io/nextflow#1533]
## New feature

Add tests of pipelines to NF, allow "dry runs"

## Usage scenario 

At the moment writing a pipeline is quick but testing it can take a lot of time. Especially when - like in one of my project - processing the smallest available set of data takes several hours. It is therefore desirable to provide tests and "dry runs" for pipelines to be able to verify them in short time (and also for CI).

## Suggest implementation 

Let's use a metaphor of unit tests. To test a function we need patching, mocks and the test itself. In our analogy:

* mock -> test script pretending to be an application
* patching ->mount the test script in a docker to replace the given command with our own fake command
* test -> dry run of a pipeline with defined input and expected published data.

Let's define a minimal pipeline:
```
input = Channel.fromPath("$params.inputFile")

process grep {
    pubishDir: '.'
input:
file('in') from input
output:
file('out') into output
script:
"""
grep $params.word in > out
"""
}
```

Now, let's write a mock script fake_grep.sh:

```
#!/usr/bin/bash
echo blah blah blah
```

And define a test:
```
test test1 {
    withName grep {
        mock = [
        "/usr/bin/grep": "./fake_grep.sh"   
 ]}
    params {
        inputFile = 'input.txt'
        word = 'blah'
    }
    expect = [
        "./out":"expected/out.txt"
    ]
}
```

after this you could execute tests like this:

```
nextflow runtest test1
```
Tests would of course execute locally. Once the pipeline is finished, NF would verify that published files exists and are identical to provided expected files. The mock scripts can contain assertions to verify the input parameters, input file etc - this would allow easy check in your preferred language.

**Comment by pditommaso** [comment]
keep open
