### ISSUE TITLE
Collect and errorStrategy=ignore produce unexpected results.

### ISSUE THREAD

**Issue by szymonwieloch** [nextflow-io/nextflow#1534]
### Expected behavior and actual behavior

When the following errorStrategy is defined:

```
process {
    errorStrategy = 'ignore'
}
```

The 'collect' operator does not collect all items on error but continues processing.

### Steps to reproduce the problem

Let's define a simple pipeline:
```
in = Channel.fromPath('*.txt')

process a {
input:
file('in.txt') from in
output:
file('out.txt') into afterA
script: 
"""
cmda in.txt out.txt
"""
}

process b {
input:
file('in.txt') from afterA
output:
file('out.txt') into afterB
script: 
"""
cmdb in.txt out.txt
"""
}

collected = afterB.collect()

process merge {
input:
file('in*.txt') from collected
output:
file('out.txt') into merged
script: 
"""
cmdc in*.txt out.txt
"""
}

process doSomething {
input:
file('in.txt') from merged
output:
file('out.txt') into afterB
script: 
"""
cmdd in.txt out.txt
"""
}
```
My understanding of the "ignore" configuration of error strategy is that it is supposed to continue computing as long as possible but it should not generate invalid results. However invalid results are actually common. If proces a or process b fail, the channel afterB will contain only subset of expected files. After that the next two processes (merge and doSomething) are run on the subset of files and therefore generate *invalid* results.

We commonly use the "ignore" strategy to run a pipeline over weekend. This time it run for several days and eventually it stopped with invalid results and an error message about the first process in the pipeline. A lot of time and resources were wasted on invalid computations.

## Possible implementation

Currently when processes result in error, they do not push anything to the output channels. However a special error value could be pushed in this case.

Processes that receive this special value do not run but just forward it to all output channels

Some operators like collect on receiving this special value do not work normally but simply do not output any values. This makes the pipeline stop when not all required data is available.

**Comment by pditommaso** [comment]
TBD
