### ISSUE TITLE
AWS Batch job definition container image problem

### ISSUE THREAD

**Issue by shaze** [nextflow-io/nextflow#1537]
## Bug report 

There may be a problem with job definition creation

### Expected behavior and actual behavior

My current workflow has the following line

`process.container = 'quay.io/h3abionet_org/py3plink'`

When I run nextflow, the job definition gets cr"eated and translates this into the following "container image"
`docker://quay.io/h3abionet_org/py3plink`  (not the "docker:" part -- not put in by me)

The jobs all then fail with `CannotPullContainerError: invalid reference format`

If I use the AWS Console, go into AWS Batch and then manually edit the job definition to delete the "docker:" part, then my jobs run. 

### Steps to reproduce the problem

This is my config file -- I've tested on several NF scripts

```
process.executor = "awsbatch"
process.container = "quay.io/h3abionet_org/py3plink"
process.queue = 'h3a-01'



aws  {
    batch.jobRole = 'arn:aws:iam::XXXXX:role/s3forECS'
    accessKey ='xxxxxx'
    secretKey = 'xxxxx'
    region    ='us-east-1'
}
```

Smae things happen if I delete batch.jobRole (this just gives full S3 access)

### Program output 

The jobs all then fail with `CannotPullContainerError: invalid reference format`

nextflow.log file is not created because the container doesn't start running

### Environment 

* Nextflow version: 20.01.0.5264
* Java version: "1.8.0_242"
* Operating system: CentOS 7.7.1908
* Bash version: ( 4.2.46(2)

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
I'm unable to replicate this. When trying it creates `nf-quay-io-h3abionet_org-py3plink` in my case. 

The relevant code is this 

https://github.com/nextflow-io/nextflow/blob/c20abc117a329e096c0457b9c45289e29b1bf3d1/modules/nextflow/src/main/groovy/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy#L601-L604


Therefore, not understanding what's happening in your case.

**Comment by shaze** [comment]
Hi Paolo,

Thanks for the response. I forgot that in my case there was a default `nextflow.config` file. Sorry about that. After some trial and error I know have as my MWE

My run is `nextflow  run t.nf -bucket-dir s3://shaze-nf`

My `nextflow.config` is

```
process  {
  executor = "awsbatch"
  container = "quay.io/h3abionet_org/py2fastlmm"
  queue = 'h3a-01'
}

aws  {
    aws.batch.cliPath = '/usr/bin/aws'
    batch.jobRole = 'arn:aws:iam::XXXX:role/s3forECS'
    accessKey ='XXXXXX'
    secretKey = 'YYYYYYY'
    region    ='us-east-1'
}

params {
    work_dir                = "/$PWD"
}

profiles {
    singularity.cacheDir = "${HOME}/.singularity"
    singularity {
        autoMounts = true
        enabled = true
        process.executor = 'local'
     }
}

```

The problem line is the `singularity.cacheDir` line. If I delete it, the correct job definition is given (or if I just bring the cacheDir within the scope of the singularity stanza).  But as is, it produces a job description with the "docker:"  insidle the container name.

This is an easy fix for me so I can solve my own problem but it does seem there is a little obscure anomalous behaviour.

Thank you again for the prompt response.

**Comment by pditommaso** [comment]
There's some mess in your config 

the `aws.batch.cliPath = '/usr/bin/aws'` should be `batch.cliPath = '/usr/bin/aws'` because it's defined in the `aws` scope. 

The singularity profile should be contained in a named context ie. 

```
profiles {
   foo {
      singularity {
          cacheDir = "${HOME}/.singularity"
          autoMounts = true
          enabled = true
          process.executor = 'local'
       }
   }
}

```

**Comment by shaze** [comment]
Hi Paolo

Thanks -- yes, I see the issue with aws, and I see what I did wrong with the cache directory.

Using `singularity` as the profile name seems to work and leads to natural names -- is this a dangerous thing to do?

**Comment by pditommaso** [comment]
No, it's not dangerous but then it should be 

```
profiles {
   singularity {
      singularity {
          cacheDir = "${HOME}/.singularity"
          autoMounts = true
          enabled = true
          process.executor = 'local'
       }
   }
}

**Comment by pditommaso** [comment]
Any update on this? still an open issue?
