### ISSUE TITLE
Support for staging files local to the executor

### ISSUE THREAD

**Issue by chrismiddleton** [nextflow-io/nextflow#1539]
## New feature

I would like to propose a new "executor://" URI that would allow you to stage files located locally on the executor, i.e., when the executor not the local system, e.g., a container or an AWS instance, etc. This is in contrast to a file pulled from S3 with "s3://" or a local file reference.

## Usage scenario 

When running a pipeline on AWS batch, there are two main ways to handle the staging of large 
reference files:

(a) Download them from S3 at runtime via the normal NF staging mechanism. This isn't a bad option in many cases, but it may require increasing the boot volume size, which can be a high cost because the lower cost volume types aren't available for a boot volume on AWS, and it also incurs the time and cost of downloading the files from S3 (the latter of which is at least pretty small). Additionally, because the files are downloaded to the container only, they will be duplicated for as many different processes are running, requiring more storage space than would be required if the files were shared among the processes running on one instance.

(b) Preload the data onto an AMI and mount the data into the container using `aws.batch.volumes`. Cost and time wise, this is a pretty great alternative to (a), but it does require such an AMI to be prebuilt, which takes time and effort. It also requires specifying the files in the script block as absolute paths, which conflicts with the way that files are staged as in (a).

Depending on the use case, a pipeline user may want to use whatever data has been preloaded into an AMI, which can be satisfied by (b), but they may instead want to use some new data, either locally or on S3, which can be satisfied by (a).

It is easy enough to write a process block that works in one case or the other, but not both. E.g., in one case, you stage the file, and in the other you write simply write the path in the command without any staging. This is problematic because it requires two different versions of the process depending on where the data is coming from.

E.g., suppose that you want the user to be able to run the pipeline with two different configurations:

```
nextflow run main.nf --ref_dir "s3://bucket/genome"
```

or

```
nextflow run main.nf --ref_dir "executor:///data/genome"
```

If such an executor:// URI was supported, you could just stage the file as normal, and the implementation detail of pulling the file from either S3 or using the file on the executor would not require rewriting the process block:

```
process Example {
    input:
    file("ref.fa"), file("ref.fa.fai") from Channel.value(tuple(
        file("$ref_dir/ref.fa"),
        file("$ref_dir/ref.fa.fai")))

    script:
    """
    # do something with the inputs
    """
```

## Suggest implementation 

Implementation-wise, I think that it would be a matter of checking for "executor://" at the beginning of the path, and then implementing the command.run such that it stages the file by linking it into the current directory, as it would if it were linking from one work directory to another.

**Comment by danielnavarrogomez** [comment]
This will be a really nice functionality which I'm missing right now.

**Comment by chrismiddleton** [comment]
Until such an `executor:///` protocol is supported, there is a sort of workaround. You can implement your own handling of 'executor:///' by having both the path and the file as input, using /dev/null in the case that the file is on the executor and determining the actual value (staged file object or string path) inside of the script block:

```
params.file_to_cat = ''
file_to_cat = Channel.of(params.file_to_cat)
process Test {
	input:
	tuple the_path, file(the_file: 'file') from file_to_cat
		.map { tuple(it, it.startsWith('executor://') ? file('/dev/null') : file(it)) }
	
	output:
	stdout into results
	
	script:
	the_file_to_cat = the_path.startsWith('executor://') ? the_path.replaceAll('^executor://', '') : the_file
	"""
	cat ${the_file_to_cat}
	"""
}

results.view { it }
```

This is similar to what has been suggested for handling of optional file inputs here:

https://github.com/nextflow-io/nextflow/issues/1233#issuecomment-513121438

Also, I think the protocol "executor://" would be better than "container://" since it's more general and would be a valid protocol in all cases (i.e., cases where no container is involved).

**Comment by sunitj** [comment]
Bumping this as I can't seem to find a recommended solution.

**Comment by pditommaso** [comment]
Something similar can be achieved using the [Fusion file system](https://www.nextflow.io/docs/latest/fusion.html) for nextflow either using local or AWS Batch executor
