### ISSUE TITLE
FilePath globbing does not support curly brackets glob with only one entry, trailing comma

### ISSUE THREAD

**Issue by dctrud** [nextflow-io/nextflow#154]
I'm using curly bracket globbing to create a channel emitting multiple files where the files are listed in a string parameter separated by commas.

While playing with this I noticed that Nextflow doesn't recognize curly bracket globs with a single entry and trailing comma. These are actually valid glob patterns. e.g.:

```
{alice.txt,}
```
... is a valid glob pattern matching only ``alice.txt``

It's unusual to have one of these, but I believe nextflow should support them as they are valid. This issue has come up in other software e.g. https://issues.jboss.org/browse/TORQUE-128

I believe that in FileHelper class:

```
static final public Pattern GLOB_CURLY_BRACKETS = Pattern.compile(/(.*)(\{.+,.+\})(.*)/)
```

...correct regex should allow trailing ',' inside the brackets....

```
static final public Pattern GLOB_CURLY_BRACKETS = Pattern.compile(/(.*)(\{.+,.*\})(.*)/)
```

**Comment by pditommaso** [comment]
It makes sense.

**Comment by pditommaso** [comment]
If so, also the following should be recognised at valid glob: 

    {,alice.txt}
    {,}

@dctrud What do you think?

**Comment by dctrud** [comment]
@pditommaso well they are valid with bash/ls. The second one evaluates to nothing...

```
dtrudgian@rop504388:~/test
10:22 PM $ ls {,alice.txt}
alice.txt
dtrudgian@rop504388:~/test
10:22 PM $ ls {,}
alice.txt mary.txt  test      testdir
```

Not sure whether they are valid for the java.nio globbing? I had a look online and couldn't find any complete definition of the globbing syntax that's valid for it.

**Comment by pditommaso** [comment]
Yes, it is. I've added a couple of tests for that. Thanks.
