### ISSUE TITLE
Using DSL2 I would like to better visualize sub-workflows

### ISSUE THREAD

**Issue by Midnighter** [nextflow-io/nextflow#1543]
## New feature

The upcoming DSL2 provides the ability to include entire workflows within other workflows. In the nextflow terminal output this is typically shown as `top-workflow:sub-workflow:process`. I would like to bring this information visually to:

1. The DAG drawn with graphviz. This could look like [this example in the gallery](https://graphviz.gitlab.io/_pages/Gallery/directed/cluster.html), possibly with a better color scheme for the different clusters and nesting of subgraphs/clusters.
2. The automatically generated execution report could provide aggregate stats for the different workflows and only in a second step allow a view on individual processes. I'm just spit balling here but there could even be an interactive drill down feature.

## Usage scenario 

For the first case, I definitely think that displaying workflows as clusters will help to visually organize the drawn DAG and quickly provide orientation for large pipelines.

For the second case, also for large pipelines, it may be enough to get an overview of the different stats per workflow rather than on a per process level.

## Suggest implementation 

If you like this feature request and you can point me to the code that generates the dot file and the report I can try to create a pull request for each.

**Comment by pditommaso** [comment]
Yes, I agree that DAG rendering could be improved in many ways. See also #1056. 

The relevant classes are [DotRenderer](https://github.com/nextflow-io/nextflow/blob/b49e6d74dae782def6be2b087d06fdd8fa6b9291/modules/nextflow/src/main/groovy/nextflow/dag/DotRenderer.groovy) and [DAG](https://github.com/nextflow-io/nextflow/blob/4b5b3c7e94de5bfff9c2bc9de471edd9785629cc/modules/nextflow/src/main/groovy/nextflow/dag/DAG.groovy#L48) which represents the execution graph data structure.

**Comment by pditommaso** [comment]
keep open
