### ISSUE TITLE
Nextflow can't open cache DB error

### ISSUE THREAD

**Issue by ranijames** [nextflow-io/nextflow#1544]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

I am completely new to nextflow, and trying my way to pipeline generation using nextflow. The pipeline used `Ensemble VEP docker image`.
Say, I had a nextflow pipeline and it crashed due to memory issue. Then, I have refactored my `main.nf` hugely in order to make the code run.  Now, when I am trying to re-run the NetFlow using 

It is throwing the following error message,

### Steps to reproduce the problem
`nextflow run main.nf`

### Program output 

```
Launching `main.nf` [friendly_picasso] - revision: 5f537f34cb
Can't open cache DB: /home/Alva.Rani/scripts/test_next/vep-annotation-nf/.nextflow/cache/e9d2caf5-27a5-469b-ad63-acc67ac871c4/db

Nextflow needs to be executed in a shared file system that supports file locks.
Alternatively you can run it in a local directory and specify the shared work
directory by using by `-w` command line option.
 ```

### Environment 

* Nextflow version: 20.01.0
* Java version: openjdk version "11.0.6" 2020-01-14
* Operating system: Ubuntu 
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

Any suggestions would be appreciated. Thanks!

**Comment by KevinSayers** [comment]
If you don't care about cached results or any previous runs, deleting the `.nextflow` folder at `/home/Alva.Rani/scripts/test_next/vep-annotation-nf/.nextflow` may fix it.

**Comment by shycheng** [comment]
I have the same problem too, however the problem still exist after I deleted the .nextflow folder

**Comment by ranijames** [comment]
@KevinSayers , Thanks for the reply.

**Comment by zillurbmb51** [comment]
Hi,

I have a similar issue. Deleting file/folder or using -w parameter did not resolve the issue. Attached is the log file.

Any help?
[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/9683981/nextflow.log.txt)

**Comment by FabianDK** [comment]
Same issue here, I am trying to use ```nextflow clean```:

```
nextflow clean -but thirsty_lumiere -f
Can't open cache DB: /home/.nextflow/cache/9535f072-6563-45a7-8d41-99b792fa1b7a/db

Nextflow needs to be executed in a shared file system that supports file locks.
Alternatively, you can run it in a local directory and specify the shared work
directory by using the `-w` command line option.
```

I tried to chmod 755 the .nextflow folder, but this didn't fix it.
Runs were executed in docker containers on Ubuntu 20.04.2 LTS with custom work dir and log dir set in the config file.

**Comment by DescartesM** [comment]
Same issue here... seems like it has never been fundamentally resolved

**Comment by rashidma** [comment]
Hello,
It seems there is no concrete solution for "Can't open cache DB".
I am facing same issue. I am using HPC Luster file system.

> Linux mu01 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

1. java -version
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
  2. singularity version

> 3.0.2

3. nextflow -version
N E X T F L O W
      version 23.04.3 build 5875
      created 11-08-2023 18:37 UTC (21:37 ADT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io

I run below command through a bash script:

#!/bin/sh

module use /opt/software/modules/modulefiles
module load singularity/3.0.2
module load OpenJDK/jdk-19.0.2


         NXF_VER=22.10.8 nextflow /software-data/nextNEOpi/nextNEOpi.nf \
         --batchFile batch_fastq.csv \
         -config /lustre/rashidma/software-data/nextNEOpi/conf/params.config \
         --outputDir testresult \
         --trim_adapters true \
         --trim_adapters_RNAseq true \
         --use_NetChop false \
         -profile singularity \
         -resume \
         --accept_license

ERROR:
N E X T F L O W  ~  version 22.10.8
Launching `/lustre/software-data/nextNEOpi/nextNEOpi.nf` [goofy_curie] DSL1 - revision: b92e276ac7
Can't open cache DB: /lustre/NRC21R-082-03/Analysis/nextNEOpi/demo/.nextflow/cache/f38db922-d2d9-400e-9538-94c31b2bb209/db

Nextflow needs to be executed in a shared file system that supports file locks.
Alternatively, you can run it in a local directory and specify the shared work
directory by using the `-w` command line option.

Thank you for your time

**Comment by rashidma** [comment]
The issue of "cannot open cache DB" is solved in my case  when i loaded OpenJDK/jdk-20.0.2. I used modules.
I was using OpenJDK/jdk-19.0.2. 
I think a broken jdk installation may lead to this error.
Please try in your case and let us know if it works.

Cheers

**Comment by mbeavitt** [comment]
Anyone else seeing this issue and wondering how to progress, you can just modify the permissions of the cache db (if you have that power) to allow read/write (e.g. chmod 766 db).

**Comment by vappiah** [comment]
Hi all , I have a similar problem when I run nextflow on our computer cluster.   When I run nextflow on the login node, it works perfectly fine. But when I run on any of the compute nodes, then the issue appears.    

Please advice

**Comment by aleighbrown** [comment]
I am having the same issues resuming a run as others, eg

which persists even after adding the '-w' command or changing the permissions on the cache db

```
(nf-env) [annbrown@morecambe2 PRJ25102]$ nextflow run nf-core/rnaseq \
>   --input samplesheet.csv \
>   --outdir /SAN/vyplab/HuRNASeq/ythdf2_ko_mesc/PRJ25102/nfcore_aligned/ \
>   --gtf /SAN/vyplab/vyplab_reference_genomes/annotation/mouse/gencode/gencode.vM38.primary_assembly.annotation.gtf.gz \
>   --fasta /SAN/vyplab/vyplab_reference_genomes/sequence/mouse/gencode/GRCm39.primary_assembly.genome.fa.gz \
>   -profile singularity -c /SAN/vyplab/vyplab_reference_genomes/nextflow_configs/rna_seq.config \
>   --gencode \
>   -resume  -w /SAN/vyplab/HuRNASeq/ythdf2_ko_mesc/PRJ25102/work \
>   --trimmer fastp \
>   --aligner star_salmon \
>   --save_reference \
>   --with_umi \
>   --umitools_extract_method 'string' \
>   --umitools_bc_pattern 'NNNNNNNN'

 N E X T F L O W   ~  version 25.04.7

Launching `https://github.com/nf-core/rnaseq` [maniac_noether] DSL2 - revision: 9738a2df42 [master]

ERROR ~ Can't open cache DB: /SAN/vyplab/HuRNASeq/ythdf2_ko_mesc/PRJ25102/.nextflow/cache/24374bd1-6416-4c9e-aa58-589bfec520e7/db

Nextflow needs to be executed in a shared file system that supports file locks.
Alternatively, you can run it in a local directory and specify the shared work
directory by using the `-w` command line option.

 -- Check '.nextflow.log' file for details
```

current java version
```
 which java
~/.sdkman/candidates/java/current/bin/java
(nf-env) [annbrown@morecambe2 PRJ25102]$ java --version
openjdk 21.0.3 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
```

*solution for other people who might have googled onto the page*

The filespace I was running in had no more storage space, which led me on some crazy debugging steps but that was the problem for this particular case.

**Comment by Bio-finder** [comment]
I hope this can help someone but for me login out and then login in again in the HPC solved the issue...
