### ISSUE TITLE
Support private IP addresses for Google Cloud Life Sciences API executor

### ISSUE THREAD

**Issue by moschetti** [nextflow-io/nextflow#1545]
## New feature

Add support for using VMs without assigning an external IP address when using the Google Cloud Life Sciences API executor.

## Usage scenario 

For large pipelines, the number of VMs being created may exceed a user's quota for external IP addresses (which is almost always lower than the quota for actual VM instances). Google Compute Engine provides a flag to enable a private address instead of giving VMs an external address. This can then be used for tasks that do not rely on external services.

## Suggest implementation 

1) Add `network.setUsePrivateAddress(bool)` in [this part](https://github.com/nextflow-io/nextflow/blob/master/modules/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesHelper.groovy#L179) of the code
2) Update associated tests
3) Put in a Nextflow parameter for users to pass that.
4) Add link in documentation to details about [using Private Google Access](https://cloud.google.com/vpc/docs/configure-private-google-access) which would be needed if a VM does not have an external IP but needs to access external services.

Related info: here's the Life Sciences API docs about [Network](https://cloud.google.com/life-sciences/docs/reference/rpc/google.cloud.lifesciences.v2beta#google.cloud.lifesciences.v2beta.Network)

**Comment by pditommaso** [comment]
Avail since `20.03.0-edge` release.
