### ISSUE TITLE
Nextflow execution aborted - java.lang.OutOfMemoryError: Java heap space submitting 10k jobs

### ISSUE THREAD

**Issue by justinjj24** [nextflow-io/nextflow#1546]
## Bug report (?)

It seems nextflow master JVM might be running out of  memory when attempting to execute a workflow which spreads computation over a very large (10,000) number of parallel processes. 

**nextflow.log**
```
Mar-25 21:07:58.167 [Actor Thread 1101] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOf(Arrays.java:3210)
at java.util.Arrays.copyOf(Arrays.java:3181)
at java.util.ArrayList.toArray(ArrayList.java:376)
.....
......
......
Mar-25 21:10:50.744 [Actor Thread 1101] DEBUG nextflow.Session - Session aborted -- Cause: Java heap space
Mar-25 21:21:35.049 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 9830657.wlm01; id: 513; name: GenomicsDB (513); status: COMPLETED; exit: 0; error: -; workDir: /data/13000026/pipeline/stage/rpd-sg10k-grch38-gatk4-gvcf-freebay
es-vcf_genomicDB-jointcall_workdir/SG10K_10323_gatk4_hg38.mini_vcfhistogram_10kintervals/04/e1e8c76a9bfbaa4089b3c0d9a7615c started: 1585130779028; exited: 2020-03-25T11:54:51Z; ]
Mar-25 22:42:35.762 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 9830678.wlm01; id: 521; name: GenomicsDB (521); status: COMPLETED; exit: 0; error: -; workDir: /data/13000026/pipeline/stage/rpd-sg10k-grch38-gatk4-gvcf-freebay
es-vcf_genomicDB-jointcall_workdir/SG10K_10323_gatk4_hg38.mini_vcfhistogram_10kintervals/18/db7a58cc2649e242e34dd1a55ddcdc started: 1585130779108; exited: 2020-03-25T11:55:43Z; ]
Mar-25 22:44:18.863 [Actor Thread 1101] DEBUG nextflow.Session - The following nodes are still active:
[process] GenomicsDB
status=ACTIVE
port 0: (value) bound ; channel: genome
port 1: (value) bound ; channel: genome_index
port 2: (value) bound ; channel: genome_dict
port 3: (queue) OPEN ; channel: -
port 4: (cntrl) - ; channel: $
[process] ApplyVQSR
status=ACTIVE
port 0: (queue) OPEN ; channel: -
port 1: (cntrl) - ; channel: $

Mar-26 01:31:01.795 [main] DEBUG nextflow.Session - Session await > all process finished
Mar-26 01:32:51.158 [main] DEBUG nextflow.Session - Session await > all barriers passed
Mar-26 01:39:01.289 [Actor Thread 1065] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
at java.util.ArrayList.(ArrayList.java:152)
```

### Some background information about the workflow which triggered this JVM memory consumption issue : 
- we seek to perform gVCF joint-calling following GTAK4 best-practices, the central tenet of which leverage on loading all gVCF files into genomicsDB to then be efficiently read back as a whole on genome-regions slices 
- the very same workflow successfully completed when the `channel` definition will results in  upward of 3000 concurrent `processes` to be translated into scheduler jobs 
- the workflow gets executed as jobs submitted to a PBS scheduler
- having reached some limitation in term of memory available on our HPC cluster nodes, we sought to increase the number of genome-regions slices 
- the channel creation, resulting in either successfully completed 3,000 or failing to complete 10,000 identical tasks is as follows
```
idx = 1
region_list_ch = Channel
     .fromPath(calling_interval_list)
     .splitText().filter{ ! it.startsWith("@") }
     .map{ reg_list -> tuple("r" + idx++, reg_list.split('\t')[0..2]) }
Channel.from(params.sample_name_map.values())
    .flatMap { it -> tuple(file(it), file(it + ".tbi")) }
    .set { gvcfs_ch } 

region_and_gvcf_ch = region_list_ch.combine(gvcfs_ch.collect().toList() )
```
- the process which  uses the channel above as input (and triggers the abortion of the nextflow execution upon seeking a scattering over 10,000+ process) is as follows 
```
process GenomicsDB {
   input:
   file(genome)
   file(genome_index)
   file(genome_dict)
   set region_no, region_list, file(gvcfs) from region_and_gvcf_ch

   output: 
   set region_no, file("ws-reg-${region_no}") into genomicsdb_ch

   script:
   bed_str = region_list.join("\t").replace(",", "\t").replace("-", "\t")
   """
   echo "${bed_str}" > reg-${region_no}.bed;
   echo "${sample_name_map_str}" > sample_map.csv

   gatk --java-options "-Xmx${task.memory.toGiga()}G -XX:ConcGCThreads=${task.cpus} -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=${task.cpus} " \
       GenomicsDBImport --sample-name-map sample_map.csv --genomicsdb-workspace-path ws-reg-${region_no} --intervals reg-${region_no}.bed
   """
}
```

### Why we suspect the error JVM memory consumption issue is triggered at nextflow's master-level rather than tasks-level** : 
- the very same workflow successfully completed when the `channel` definition will results in  upward of 3000 concurrent `processes` to be translated into scheduler jobs 
- nextflow seems to happily proceed and processes are submitted to the scheduler creating 100+  jobs.
The first batch of submitted jobs successfully complete.
- No jobs ever report as failed neither as per `trace.txt` nor as per individual `.command.log` files 

We thus suspect the error
```
...Mar-26 01:39:01.289 [Actor Thread 1065] ERROR nextflow.processor.TaskProcessor - Execution aborted due to an unexpected error
java.lang.OutOfMemoryError: Java heap space
at java.util.ArrayList.(ArrayList.java:152)
```
to be  triggered by nextflow master 

### How we tried but failed to remedy to this issue
- note that the node on which the nextflow master is run has >500Gb or RAM  
- Suspecting the JVM memory consumption issue is triggered at nextflow's master-level rather than tasks-level, we tried alter the amount of memory JAVA is allowed to consume altering 
- - `NXT_OPTS` and `_JAVA_OPTS` in  `~/.bashrc`
**bashrc**
```
###NXF_OPTS="-Xms50m -Xmx50g"
NXF_OPTS="-Xms4g -Xmx80g"
###_JAVA_OPTIONS="-Xms50m -Xmx500m"
_JAVA_OPTIONS="-Xmx80g"
###NXF_OPTS="-Xms1g -Xmx4g"
```
- - in  `nextflow.config`
**nextflow.config**
```
env {
NXF_OPTS="-Xms1g -Xmx80g"
}
```
```
env {
_JAVA_OPTIONS="-Xms1g -Xmx80g"
}
```
- - in nextflow's `profile`
```
executor {
name = 'pbspro'
queueSize = 500
pollInterval = '300 sec'
}
```
```
executor {
name = 'pbspro'
queueSize = 500
pollInterval = '300 sec'
memory = '80 GB'
cpus = 24
}
```
### Environment
```
java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```
```
nextflow
version 18.10.1
```

Thanks in advance for your help and input. Justin

**Comment by justinjj24** [comment]
[nextflow.LOG](https://github.com/nextflow-io/nextflow/files/4390959/nextflow.LOG)

[nextflow.config.TXT](https://github.com/nextflow-io/nextflow/files/4390961/nextflow.config.TXT)
[nscc.config.TXT](https://github.com/nextflow-io/nextflow/files/4390962/nscc.config.TXT)

**Comment by pditommaso** [comment]
This is an insanely old version of nextflow `18.10.1 build 5003`. Impossibile to say.
