### ISSUE TITLE
conda createOptions not available from .yaml file

### ISSUE THREAD

**Issue by nservant** [nextflow-io/nextflow#1554]
The `createOptions` directive is only applied for conda `txt` file, and not for `yaml` file.
See CondaCache.groovy L245

**Comment by pditommaso** [comment]
I fear the `conda env create` command does not support the extra options 

https://github.com/nextflow-io/nextflow/blob/2fe1052c9ba96e69986217a4cf0ecf0102c69052/modules/nextflow/src/main/groovy/nextflow/conda/CondaCache.groovy#L245

**Comment by nservant** [comment]
Can I ask you what is the difference between `conda env create` and `conda create` ?

**Comment by pditommaso** [comment]
Not sure, it's still valid, but at the time it was implemented it was the only way to manage yml recipe files.

**Comment by pditommaso** [comment]
Closing for now. Feel free to re-open if there's a way to specify create options.
