### ISSUE TITLE
Deprecate validExitStatus directive

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#1564]
The directive [validExitStatus](https://www.nextflow.io/docs/latest/process.html#validexitstatus) is hard to support and maintain with cloud executors such as Google Life Sciences, K8s, etc. Moreover makes it difficult to consistently track the status of the tasks on external systems.

As such this directive is going to be deprecated and removed in a future version.  

As a workaround, a Bash `trap` can be used to implement a similar behaviour, eg 

```nextflow
process foo {
  '''
  trap 'if [[ $? == expected_error ]]; then echo OK; exit 0; fi' EXIT
  your_command_that_may_fail
  '''
}

**Comment by ewels** [comment]
Hi @pditommaso,

Is `task.exitStatus` safe from this change? We use this in nf-core for automatic job resubmission if it looks like something was cancelled due to lack of resources (see [template](https://github.com/nf-core/tools/blob/ebf63095ab222e4df987c4e950ce3839e8784d3e/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/conf/base.config#L19)).

Phil

**Comment by pditommaso** [comment]
The `exitStatus` is unrelated by the `validExitStatus`. However, if you are referring the *trap* trick, in that case, yes, the trap will override the `exitStatus` information. 

I've added another workaround using  a `errorStrategy` that does not alter the returned `exitStatus` value.

**Comment by ewels** [comment]
Ok great, thanks 👍

**Comment by stevekm** [comment]
A non-zero exit status does not mean an error actually occurred. For example, any time you use the bash command `timeout` you will get an exit status of 124, which does not indicate an error.

**Comment by NickSwainston** [comment]
Could I please have some help with a workaround from someone who is more experienced with bash and Nextflow? I have a process that has two commands, one that can fail and another that should run even if the first fails. The above trap implementation exits before the second command so I need something that can suppress or change the exit code like so
```nextflow
process foo {
  '''
  trap 'if [[ $? == expected_error ]]; then echo "OK supreesed error"; fi' EXIT
  your_command_that_may_fail
  
  second_command
  '''
} 
```

**Comment by ewels** [comment]
@NickSwainston please raise this on the Nextflow Gitter chat / mailing list / [nf-core Slack](https://nf-co.re/join) and you'll find plenty of people to help 👍🏻
