### ISSUE TITLE
"each" repeater not working with some tuples/multiple channels

### ISSUE THREAD

**Issue by DaGaMs** [nextflow-io/nextflow#1566]
## Bug report 

I have a process that takes in 3 channels: two emit only one value, while one emits many. I therefore ues the `each` repeater to get the input multiple times. However, the following script always gives me an error:

```groovy
#!/usr/bin/env nextflow
nextflow.preview.dsl=2

workflow {
	main:
		channelA = Channel.of(["A", "/etc/hosts"])
		channelB = Channel.of(["1","/etc/bashrc"], ["2", "/etc/aliases"])
		channelC = Channel.of(["setting1": true, "setting2": false, "setting3": "lalala"])

		test(channelA, channelB, channelC) | view
}

process test {
	input:
		each tuple(idA, path(fileA))
		tuple(idB, path(fileB))
		each options
	output:
		tuple val("${idA}-${idB}"), path("output")
	script:
	"""
		echo "$idA $idB ${options.setting3}" > output
		ls -Llh $fileA >> output
		ls -Llh $fileB >> output
	"""
}
```

The output I get is:

```text
N E X T F L O W  ~  version 20.01.0
Launching `test.nf` [curious_stonebraker] - revision: 142ccea4d5
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
No such variable: idA

 -- Check script 'test.nf' at line: 15 or see '.nextflow.log' file for more details
```

Any idea what's going on there? The only way around this was to change the format of my script to take only two input channels, ie only have one `each`:

```groovy
#!/usr/bin/env nextflow
nextflow.preview.dsl=2

workflow {
	main:
		channelA = Channel.of(["A", "/etc/hosts"])
		channelB = Channel.of(["1","/etc/bashrc"], ["2", "/etc/aliases"])
		channelC = Channel.of(["setting1": true, "setting2": false, "setting3": "lalala"])
		/*
		 * THIS NOW WORKS!
		 */
		test(channelA.combine(channelB), channelC) | view
}

process test {
	input:
		tuple(idA, path(fileA), idB, path(fileB))
		each options
	output:
		tuple val("${idA}-${idB}"), path("output")
	script:
	"""
		echo "$idA $idB ${options.setting3}" > output
		ls -Llh $fileA >> output
		ls -Llh $fileB >> output
	"""
}
```

**Comment by pditommaso** [comment]
`each tuple` is not supported ([green box](https://www.nextflow.io/docs/latest/process.html#input-repeaters)) The `combine` is the way to go.

**Comment by DaGaMs** [comment]
I see - I think this is not coming out clearly at all from the documentation at the moment. Would be good to say explicitly that multiple `each` + `tuple` is not possible. Also, if I may, I would think it would be good to add that as a feature request ;-) It just feels inconsistent that some combinations of keywords are not allowed. I don't think an average user will see the logic why `each path(file)` works but `each tuple(id, path(file))` doesn't... Anyway, thanks for the clarification!
