### ISSUE TITLE
How to limit memory usage by Nextflow?

### ISSUE THREAD

**Issue by amayer21** [nextflow-io/nextflow#1567]
Hello,

Thanks for making this amazing tool and coming to teach it to us a few months ago.

We are running Nextflow (currently mainly with nf-core pipelines) on a SLURM cluster. Because our master node is only dedicated to slurm job management, we actually write a small script that's going to launch nextflow from one of the node and send job from there. In that script (see [nfcore-rnaseq.sh.txt](https://github.com/nextflow-io/nextflow/files/4474614/nfcore-rnaseq.sh.txt)), we asked slurm to allocate 1 CPU and 8 Gb memory to nextflow, which I thought should be enough for nextflow to manage our jobs. It actually sometimes works, but sometimes it gets killed by slurm with the following message:
```
slurmstepd: Step 4717680.0 exceeded memory limit (8414616 > 8388608), being killed
slurmstepd: *** STEP 4717680.0 ON ptfgen001 CANCELLED AT 2020-04-07T00:53:38 ***
slurmstepd: Exceeded job memory limit
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: Exceeded step memory limit at some point.
slurmstepd: Exceeded job memory limit at some point.
srun: error: ptfgen001: task 0: Killed
```

I'm not speaking here about the memory used by each process but by nextflow while managing these processes. 

I thought I limited the memory nextflow would use to manage the jobs with `export NXF_OPTS='-Xms1g -Xmx8g'` but it doesn't seem to work.

Do Nextflow really need more than 8Gb to manage jobs? How can I limit the memory it's actually using? 

In case it helps, I also join the config file [nextflow.config.txt](https://github.com/nextflow-io/nextflow/files/4474700/nextflow.config.txt) and slurm log file 
[nfcorernaseq_4717680.log](https://github.com/nextflow-io/nextflow/files/4474703/nfcorernaseq_4717680.log), as well as a few info about environment.

### Environment 
* Nextflow version: 19.10.0
* Java version: jdk1.8.0_66
* Operating system: linux
* Bash version: GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)

Thank you very much!

Best wishes,

Alice

**Comment by pditommaso** [comment]
Hi,  

the amount of mem depends on the pipeline and the actual workflow, but generally, 1-2 GB are enough. 

Launch a slurm job running this command, to make sure the NXF_OPTS is correctly picked. 

```
nextflow info -d
```

**Comment by amayer21** [comment]
Thanks Paolo.  
It seems that it picked it up ([testMEM_4720622.log](https://github.com/nextflow-io/nextflow/files/4475569/testMEM_4720622.log)):
```
JVM opts:
    -XX:+TieredCompilation
    -XX:TieredStopAtLevel=1
    -Xms1g
    -Xmx8g
    -Djava.io.tmpdir=/home/gallia/scratch/u230707/
    -Djava.library.path=
      /cm/shared/apps/slurm/14.11.11/lib64/slurm
      /cm/shared/apps/slurm/14.11.11/lib64
      /usr/java/packages/lib/amd64
      /usr/lib64
      /lib64
      /lib
      /usr/lib
    -Dfile.encoding=UTF-8
    -Djava.awt.headless=true
    -Djava.io.tmpdir=/home/gallia/scratch/u230707/
```

**Comment by pditommaso** [comment]
Then it's weird that slurm kill it. Try increase slurm limit 0.5 GB or decrease NF one 0.5 GB.

**Comment by amayer21** [comment]
OK, will try.  It's true that according to slurm error message, it was using 8.025Gb, which is not so much more than the 8Gb I asked for, so 0.5Gb should make the trick...  

I relaunched it this morning with usual parameters and it's running fine for now, so won't be able to try before that's finished...

When you said "the amount of mem depends on the pipeline and the actual workflow", do you think I'm slowing down the pipeline by restricting it's memory usage to 8Gb? What is NextFlow using the memory for?

I'm using nf-core RNAseq pipeline with 70 samples (140 fastq files). I tried to limit the number of job running in parallele to 8 with `queueSize = 8` but I still have up to 120 jobs sent by Nextflow to the queue at any single time... (but maybe I should open another issue for that?)

**Comment by pditommaso** [comment]
> I'm slowing down the pipeline by restricting it's memory usage to 8Gb? 

It should not. 

> What is NextFlow using the memory for?

Workflow orchestration and metadata tracking 

> but I still have up to 120 jobs

**Comment by nfancy** [comment]
@amayer21 I ended up with the same queuing size issue. I found that it is the maxForks param that limits the numbers of jobs submitted to the cluster per process. and maxForks should go inside the process scope in the config file. I hope this helps.
