### ISSUE TITLE
Dependencies are not found in conda environment 

### ISSUE THREAD

**Issue by sofsta** [nextflow-io/nextflow#1569]
Hi all,  

Not sure if this is more of a nextflow or conda question so apologies if this is not the right place to ask this question :)

I have created a conda environment and installed some dependecies:

The **Dockerfile** looks as follows:

```
FROM continuumio/miniconda3


COPY environment.yml /

RUN conda env create --prefix -f /environment.yml
RUN echo "source activate sofia" > ~/.bashrc
RUN conda env export -n sofia
ENV PATH /opt/conda/envs/sofia/bin:$PATH
```

and the **enivornment.yml**:

```

name: sofia
channels:
  - bioconda
  - anaconda
dependencies:
  - samtools
  - pigz
  - fastqc=0.11.9
  - fastp=0.20.0
  - multiqc
  - kraken2

```
The **nextflow.config** is:

```
profiles {

        conda { process.conda = "$baseDir/environment.yml" }
}
```

The  **main.nf** is:

```
process BamToFastq {
	input:

	output:

	script:
	"""
	samtools do something here
	"""
}

process fastqc {
	input:

	output:

	script:
	"""
	fastqc do something here
	"""
}
```

When I run:

`nextflow run main.nf --reads="data/*.bam" --bam`

 I get the error: `fastqc: command not found`

If I run:

`nextflow run nextflow run main.nf --reads="data/*.bam" --bam -profile conda`

I get the error:

` Caused by:
  Failed to create Conda environment
  command: conda env create --prefix /srv/rs6/sofia/Metoid/Metoid/work/conda/sofia-69a49d4c51b18b52834a801c9d77c743 --file /srv/rs6/sofia/Metoid/Metoid/environment.yml
  status : 127
  message:
    bash: conda: command not found`

Any ideas why might go wrong here?

**Comment by danielecook** [comment]
If you type `which conda` what do you see?

**Comment by pditommaso** [comment]
Conda doesn't look installed or it's not reachable by NF 

```
conda: command not found
```
