### ISSUE TITLE
k8s executor must provide cpu resource requests (and limits)

### ISSUE THREAD

**Issue by alanbchristie** [nextflow-io/nextflow#1570]
### Expected behavior and actual behavior

The k8s executor is not providing Pod resource `request` declarations and compute nodes become over-subscribed with Pods (Jobs) that simply compete with each other for CPU. If a cpu **request** is not provided Kubernetes assumes the corresponding Container needs 0.1 CPU.

For each nextflow **process** I would expect nextflow to set the Pod Container's CPU resources based on the `cpus` declaration in the **process**  block, or `1` if not explicitly defined. i.e.: -

```
spec:
  containers:
    ...
    resources:
      limits:
        cpu: 1
      requests:
        cpu: 1
```

The above will guarantee that the corresponding container is allocated to a compute instance where at least 1 cpu resource is free and can be dedicated to it.

### Steps to reproduce the problem

Use the k8s executor

### Program output 

Workflow runs but compute instances are heavily over-subscribed.

### Environment 

* Nextflow version: `19.10.0`
* Java version: (n/a)
* Operating system: `Kubernetes 1.16.4`
* Bash version: (n/a)

### Additional context

Related to issue #773 which discusses resource limits.

**Comment by pditommaso** [comment]
Related to #773.

**Comment by pditommaso** [comment]
bump

**Comment by pditommaso** [comment]
A bit confused about this, docs say clearly that omitting `request` and specifying `limit`, the scheduler use the same value for both 

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits

Why are you saying it assume 0.1 CPU?

**Comment by KevinSayers** [comment]
It depends on the k8s implementation you are using I believe, as the defaults can be configured for a namespace. For example see GKE https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-resource-requests-and-limits under the "Container Settings" section.

**Comment by pditommaso** [comment]
I see. Then I think the quick fix is to explicitly specify both `request` and `limit`. Then we should think a bit more about how to extend the `cpus` directive to allow people to specify both of them. I would prefer to a general solution than Pod only one.

**Comment by KevinSayers** [comment]
Ok so for now I will update the pod spec so it also has `requests` based on the `cpus` directive. What do you think about having a default if the `cpus` directive isn't present? Default to 1?

**Comment by pditommaso** [comment]
That's the default for all task 

https://github.com/nextflow-io/nextflow/blob/3de45c2287d78a70ac477d705aa9b8a4c019e629/modules/nextflow/src/main/groovy/nextflow/processor/TaskConfig.groovy#L247-L250

Frankly don't remember the reason why was avoid for K8s 

https://github.com/nextflow-io/nextflow/blob/668434f695496644babcc4c1ee198f97fd57d378/modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy#L184-L188

**Comment by pditommaso** [comment]
Ok, I've made the following changes: 

1. Always include the resource requests along with limits,
so that requests==limtis so that the K8s scheduler guarantees such resources. 
Either for CPUs and memory

2. Default to 1 CPUs requests (and limits) when no `process.cpus` directive was
specified by the user in the same manner how it's done for other schedulers

The specification of fractional CPUs will be done in a separate issue.

**Comment by levin8023** [comment]
>is there any way to set it  separately  in main.nf file now ?
