### ISSUE TITLE
sra

### ISSUE THREAD

**Issue by keenhl** [nextflow-io/nextflow#1571]
I ran the following code

Channel
    .fromSRA('SRP253951')
    .println()

I get a list of fastq urls

[SRR11412291, /vol1/fastq/SRR114/091/SRR11412291/SRR11412291.fastq.gz]
[SRR11412292, /vol1/fastq/SRR114/092/SRR11412292/SRR11412292.fastq.gz]

...

But at the end

WARN: Failed to retrieve fastq download URL for accessions: SRR11517737,  ...

Is this because the fastq file doesn't exist?  So, for those files would I need to download the sra and convert to fastq?

Thank you for your help.

**Comment by pditommaso** [comment]
Have you specified the `NCBI_API_KEY` in your environment before running this?

**Comment by pditommaso** [comment]
The problem here is that ftp URL is not available for that accessions from the data provider.
