### ISSUE TITLE
HTML report Tasks table does not sort Human Readable values correctly

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#1573]
### Expected behavior and actual behavior

In the Nextflow HTML report Tasks table, if you have it set to view "Human Readable" values, it does not seem to be able to sort columns such as "Duration" and "Realtime" correctly. 

Here is an example, in this table I have it sorted on "realtime". However, the values shown are as follows;

6h 57m
52m 6s
51m 8s
51m 19s
4h 43m
4h 43m

Also, not shown but much further down there are values such as "1d 6h" as well. 

<img width="746" alt="Screen Shot 2020-04-17 at 9 50 37 AM" src="https://user-images.githubusercontent.com/10505524/79576454-4f767d00-8091-11ea-9fd7-589d8ead9d72.png">

In this example, I know that many tasks too over a day to run but its difficult to find them when the sorting does not work correctly and there are hundreds and thousands of tasks. It appears to be sorting the "Human Readable" values alphabetically, instead of based on the actual time value they represent.

You can of course get correct sorting by changing it to "Raw Values", however you then get values like "259200657", "245164190", "125159819", etc., which are incomprehensible. 

I also tried sorting the Raw Values first, then switching to Human Readable values, but it seems that every time you change those settings it loses the sorting and filtering you had applied to the table.

### Environment 

* Nextflow version: 19.10
* Java version: 8
* Operating system: macOS/Centos 7

**Comment by pditommaso** [comment]
bump
