### ISSUE TITLE
Support custom service account for Google Cloud Life Sciences API executor

### ISSUE THREAD

**Issue by snamburi3** [nextflow-io/nextflow#1575]
## New feature

Presently nextflow uses default service account in the project to run the analysis when the instance runs. It will be great if we could specify a custom service account instead. Google Cloud Life Sciences API executor seems to have an option to [specify a service account](https://cloud.google.com/life-sciences/docs/reference/rest/v2beta/projects.locations.pipelines/run#serviceaccount).

**Comment by pditommaso** [comment]
What's the difference in practical terms?

**Comment by snamburi3** [comment]
@pditommaso, I am thinking this might be very useful for cross-project bucket access or accessing a controlled-accessed bucket hosted by other organizations  - with the custom service account having being authorized to access the data. I might be wrong about this as the default service account could also be used for the same. The default service account in the project has automatically granted "Editor" role, so I am thinking a custom service account will give us the ability to give more granular IAM access.

**Comment by samwachspress** [comment]
+1 for ability to select service accounts

**Comment by pditommaso** [comment]
I think this was added as per this PR https://github.com/nextflow-io/nextflow/pull/2044

**Comment by samwachspress** [comment]
I see via the PR:

Version: 20.05.0-edge
Config option: google.lifeSciences.serviceAccountEmail

Thank you very much!!
Sam Wachspress

From: Paolo Di Tommaso ***@***.***>
Reply-To: nextflow-io/nextflow ***@***.***>
Date: Monday, May 31, 2021 at 11:43 AM
To: nextflow-io/nextflow ***@***.***>
Cc: Sam Wachspress ***@***.***>, Comment ***@***.***>
Subject: Re: [nextflow-io/nextflow] Support custom service account for Google Cloud Life Sciences API executor (#1575)


I think this was added as per this PR #2044<https://urldefense.com/v3/__https:/github.com/nextflow-io/nextflow/pull/2044__;!!Dq0X2DkFhyF93HkjWTBQKhk!HzK2JX3h8jwHH7npChliOlGWzQXe1iNy6gzQZxNe-5Ichoibo-HaXo-AwkkhWQW-yxAkYjRJVkHR$>
