### ISSUE TITLE
Cache issues and suggestions for dump-hashes

### ISSUE THREAD

**Issue by danielecook** [nextflow-io/nextflow#1576]
## Bug report 

Occasionally I run into issues with the cache that I can't seem to figure out. In this case, I run a pipeline to completion and run it a second time to find that the cache has not been maintained.

To figure out what is going on, I wrote a python script to parse the output when running nextflow with `-dump-hashes`, so that I can identify the values that are invalidating the cache.

The script is available [here](https://gist.github.com/danielecook/7fae638ca7745efae4358d0584483255), and requires NumPy and Pandas in order to work.

__[Example output table](https://docs.google.com/spreadsheets/d/1mpgFmbJONExf0qjggjvOUu_N9AfjIeBut1v8qa7Zvq8/edit?usp=sharing)__

The script requires that the tag used for each process is unique for every process submitted. The script does the following:

* Keep process names that are present in both hash files. This restricts the file to only those processes that we can compare.
* Filter out value hashes present with the same process name and same value hash. This leaves only values that are different between two hash-dumped logs.

With these filters in place, we can format and combine the hash files to make it easy to see which cache values are different.

__Here are a couple lines illustrating what the output looks like__

  | filename | process | process_hash | value_hash | value_type | value | rank
-- | -- | -- | -- | -- | -- | -- | --
3827 | dump_hashes5.txt | wf_call:annotate (LTX0001) | ba323a0692892e6ba7faefa73799c7cc | 9c68b6194715fe97bc53d692dfb65ce7 | nextflow.util.ArrayBag | [FileHolder(sourceObj:/Users/dec/Documents/swanton_lab/TRACERx-call-nf/work/7b/9847e0f4444a616b3a9360b0542ae1/variants.tsv, storePath:/Users/dec/Documents/swanton_lab/TRACERx-call-nf/work/7b/9847e0f4444a616b3a9360b0542ae1/variants.tsv, stageName:variants.tsv)]' | 1
1950 | dump_hashes6.txt | wf_call:annotate (LTX0001) | dfba10900c2a71e25b8136103bd40f01 | 5e2ff5ae9d5b1790aab0f6e7f06c6163 | nextflow.util.ArrayBag | [FileHolder(sourceObj:/Users/dec/Documents/swanton_lab/TRACERx-call-nf/work/0b/66bd1299c5305760441fcf6e117d42/variants.tsv, storePath:/Users/dec/Documents/swanton_lab/TRACERx-call-nf/work/0b/66bd1299c5305760441fcf6e117d42/variants.tsv, stageName:variants.tsv)]' | 1

In this instance, the file holders are returning as having different hashes. This may be by design because the source files have different paths. However, every single file listed for `sourceObj` and `storeDir` have identical `md5`'s.

So while those objects appear different despite having the identical underlying data, maybe that is expected. So what else could be driving cache invalidation?

__cache invalidation from `java.util.HashMap$EntrySet`?__

  | filename | process | process_hash | value_hash | value_type | value
-- | -- | -- | -- | -- | -- | --
2544 | dump_hashes5.txt | wf_call:varscan_process (LTX0001_SU_T1-R1--9e327322c42h) | c37ba627d24193c847093df07089221d | b3085df398cf2e1e4c6f1b983ecb18d6 | java.util.HashMap$EntrySet | [workflow.projectDir=/Users/dec/Documents/swanton_lab/TRACERx-call-nf, params.genome=/Users/dec/Documents/swanton_lab/TRACERx-call-nf/_assets/reference/hg19/ucsc.hg19.fasta]'
565 | dump_hashes6.txt | wf_call:varscan_process (LTX0001_SU_T1-R1--9e327322c42h) | 8e595aceae2273eebccaa40977c4fdc4 | d32f38825bd627c05545fba5e2246815 | java.util.HashMap$EntrySet | [workflow.projectDir=/Users/dec/Documents/swanton_lab/TRACERx-call-nf, params.genome=/Users/dec/Documents/swanton_lab/TRACERx-call-nf/_assets/reference/hg19/ucsc.hg19.fasta]'

Here is what I think might be driving cache invalidation. In some cases, the value:

```
[workflow.projectDir=/Users/dec/Documents/swanton_lab/TRACERx-call-nf, params.genome=/Users/dec/Documents/swanton_lab/TRACERx-call-nf/_assets/reference/hg19/ucsc.hg19.fasta]
```

appears to be able to return two different hashes:

`b3085df398cf2e1e4c6f1b983ecb18d6` and `d32f38825bd627c05545fba5e2246815`

Any ideas why these values are returning different values? The reference genome listed there does not change. It is not modified at all.

### Suggestion

The output produced by the script above is a lot easier to work with than the traditional `-dump-hashes` output. A tabular format for the output would make it easier to compare hash-sets from pipeline runs.

### Environment 

* Nextflow version: 20.04.0-edge.5330
* Java version: 1.8.0_242
* Operating system: macOS
* Bash version: 5.0.11

**Comment by danielecook** [comment]
This issue appears to have been due to the use of `groupTuple`, and I was able to resolve it using `groupKey`

**Comment by rmhubley** [comment]
I am not so sure this behavior is always related to groupTuple.  For instance, the following code when run with "-dump-hashes" produces two distinct hashes in relation to the use of $workflow.projectDir:

```
workChan = Channel.from(1,4,6)

process dummy {
  input:
  val(x) from workChan

  script:
  """
  cd ${workflow.projectDir}
  echo $x
  """
}

Run 1:
eabd699f53740cc9e09581d7db0eba90 [java.util.HashMap$EntrySet] [workflow.projectDir=/u1/home/rhubley/projects/DNAMultipleAlignment/tmp/TEForwardEvolve]

Run 2:
0a8449be2e441e16ba6ca0e7daa7f3f9 [java.util.HashMap$EntrySet] [workflow.projectDir=/u1/home/rhubley/projects/DNAMultipleAlignment/tmp/TEForwardEvolve]
```

This issue was posted two months ago here: https://bioinformatics.stackexchange.com/questions/15756/nextflow-why-does-non-local-reference-to-projectdir-break-hash-stability-and-h

The solution this user suggests is to redeclare workflow.projectDir and use that new variable in the process.  That does work, and looking at the hashes dumped there is no longer a hash produced for a java.util.HashMap$EntrySet at all.

```
def projDir = workflow.projectDir

workChan = Channel.from(1,4,6)

process dummy {
  input:
  val(x) from workChan

  script:
  """
  cd ${projDir}
  echo $x
  """
}
```

Finally, if you remove the "def" in the redeclaration the problem returns:

```
projDir = workflow.projectDir

workChan = Channel.from(1,4,6)

process dummy {
  input:
  val(x) from workChan

  script:
  """
  cd ${projDir}
  echo $x
  """
}

Run1:
2c425bee9986bc247cfbfd50847cce14 [java.util.HashMap$EntrySet] [projDir=/u1/home/rhubley/projects/DNAMultipleAlignment/tmp/TEForwardEvolve]

Run2:
e7f5c8131485031c219f32ac6223032f [java.util.HashMap$EntrySet] [projDir=/u1/home/rhubley/projects/DNAMultipleAlignment/tmp/TEForwardEvolve]
```

**Comment by pditommaso** [comment]
I think this problem is related to this issue solved recently https://github.com/nextflow-io/nextflow/issues/2186
