### ISSUE TITLE
k8s: pod metadata too long

### ISSUE THREAD

**Issue by pinin4fjords** [nextflow-io/nextflow#1577]
### Steps to reproduce the problem

Run an nf-core workflow (slightly modified in this case to avoid other issues), like:

```
nextflow kuberun ebi-gene-expression-group/rnaseq -profile test,docker -v nextflow -c nextflow.config
```

### Program output 

We eventually get an error like:

```
Error executing process > 'merge_featureCounts (SRR4238355_subsampAlignedByCoord.out_gene.featureCounts)'

Caused by:
  Request POST /api/v1/namespaces/default/pods returned an error code=422

  {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {
          
      },
      "status": "Failure",
      "message": "Pod \"nf-00ac4cf1c2f58e87428dcdf558dd18e5\" is invalid: metadata.labels: Invalid value: \"merge_featureCounts_SRR4238355_subsampAlignedByCoord.out_gene.featureCounts\": must be no more than 63 characters",
      "reason": "Invalid",
      "details": {
          "name": "nf-00ac4cf1c2f58e87428dcdf558dd18e5",
          "kind": "Pod",
          "causes": [
              {
                  "reason": "FieldValueInvalid",
                  "message": "Invalid value: \"merge_featureCounts_SRR4238355_subsampAlignedByCoord.out_gene.featureCounts\": must be no more than 63 characters",
                  "field": "metadata.labels"
              }
          ]
      },
      "code": 422
  }


Unknown method `toBytes` on String type -- Did you mean?
  getBytes

 -- Check script '/workspace/projects/ebi-gene-expression-group/rnaseq/main.nf' at line: 1775 or see '.nextflow.log' file for more details
```
It seems like the way that field is composed for k8s by Nextflow needs a hard-limit (or maybe just some string encoding/ compression?) to fit it within those 63 characters. 

### Environment 

* Nextflow version: 20.01.0.5264
* Java version: openjdk 11.0.1-internal 2018-10-16
* Operating system: Linux
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
The value for a `tag` is too long and is breaking the limit for pod labels limit 

```
too long `tag` value which result in -> `Invalid value: \"merge_featureCounts_SRR4238355_subsampAlignedByCoord.out_gene.featureCounts\": must be no more than 63 characters"` 
```

**Comment by pinin4fjords** [comment]
Thanks @pditommaso , got that, and I could hack about the nf-core workflow to fix it. But could truncating tags not be something Nextflow could do for k8s to prevent errors like the above? I was poking about in e.g. https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy seeing if I could work out how to implement that, but haven't succeeded so far.

**Comment by pditommaso** [comment]
This is a good candidate 

https://github.com/nextflow-io/nextflow/blob/1d288a3df54bafba29fd2da22954fdd3718a627b/modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy#L238-L243

**Comment by pinin4fjords** [comment]
@pditommaso Actually I did try that:

```
        if( opts.labels ) {
            def keys = opts.labels.keySet()
            if( 'app' in keys ) throw new IllegalArgumentException("Invalid pod label -- `app` is a reserved label")
            if( 'runName' in keys ) throw new IllegalArgumentException("Invalid pod label -- `runName` is a reserved label")
            labels.putAll( opts.labels.collectEntries{ k, v -> [k, v.take(63)] } )
        }
```

... but it didn't seem to solve the issue. Dumb question: but is there anything extra I need to do for compile, other than the standard top-level:

```
make compile
make pack
make install
```

???

**Comment by pditommaso** [comment]
K8s is a mess to test because you should package it into a container, etc etc. 

First, it should be tested with a unit test, look at `PodSpecBuilderTest`. 

For local test I use the K8s distro included with Docker. The use this settings in the NF config 

```
    cleanup = true
    process.executor = 'k8s'
    k8s.autoMountHostPaths = true
    k8s.debug.yaml = true 
```   

Finally, `make compile` and run using `./launch` in place of the `nextflow` command. 

Regarding the implementation, at least a debug line should be produced in the log file. I'll suggest something line 

```
for( Map.Entry<String,String> entry : opts.labels ) {
  if( !entry.key || !entry.value ) {
    log.debug "K8s invalid label entry=$entry"  
  }
  else if( entry.value.size() > 63 ) {
    log.debug "K8s label exceeds allowed size: 63 -- offending entry=$entry"  
    labels.put(entry.key, entry.value.substring(0,63))   
  }
  else {
        labels.put(entry.key, entry.value)    
  }
} 
```

**Comment by pinin4fjords** [comment]
Thanks for that. Sorry, my dusty Java is failing me- how do I make the log variable available within PodSpecBuilder?

**Comment by pditommaso** [comment]
Annotate the class with `@Slf4j` like for example here 

https://github.com/nextflow-io/nextflow/blob/7c80bdb3526e368fc3a9b44e50a796bd83a8bd94/modules/nextflow/src/main/groovy/nextflow/k8s/client/ConfigDiscovery.groovy#L32

with the related import .. 

https://github.com/nextflow-io/nextflow/blob/7c80bdb3526e368fc3a9b44e50a796bd83a8bd94/modules/nextflow/src/main/groovy/nextflow/k8s/client/ConfigDiscovery.groovy#L25
