### ISSUE TITLE
Inconsitent ShifterImage DockerImage

### ISSUE THREAD

**Issue by tsigalko2003** [nextflow-io/nextflow#1579]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

Run nextflow kuberun under 2 different accounts in HPC  with identical kubeconfig and credentials underlying at identical environment,  nf-pod generated difrerent .command.yaml files for image address. 
One is image: docker://793354189448.dkr.ecr.us-east-1.amazonaws.com/scrna-star273:1.0 which can not work with error message 
Warning  Failed         20m (x50 over 30m)   kubelet, ip-10-44-149-25.ec2.internal  Error: InvalidImageName
  Warning  InspectFailed  18s (x140 over 30m)  kubelet, ip-10-44-149-25.ec2.internal  Failed to apply default image tag "docker://793354189448.dkr.ecr.us-east-1.amazonaws.com/scrna-star273:1": couldn't parse image reference "docker://793354189448.dkr.ecr.us-east-1.amazonaws.com/scrna-star273:1": invalid reference format
The other is image: 793354189448.dkr.ecr.us-east-1.amazonaws.com/scrna-star273:1.0 and it run well without any error

### Steps to reproduce the problem

under user A, run nextflow kuberun PfizerRD/ib-k8s -v efs-claim;/mnt
under user B, run nextflow kuberun PfizerRD/ib-k8s -v efs-claim;/mnt

### Program output 
kubectl decribe pod nf-f1d094779ec9ca26e1caa6701e6ffed5
Events:
  Type     Reason         Age                  From                                   Message
  ----     ------         ----                 ----                                   -------
  Normal   Scheduled      55m                  default-scheduler                      Successfully assigned default/nf-f1d094779ec9ca26e1caa6701e6ffed5 to ip-10-44-149-25.ec2.internal
  Warning  Failed         45m (x50 over 55m)   kubelet, ip-10-44-149-25.ec2.internal  Error: InvalidImageName
  Warning  InspectFailed  18s (x256 over 55m)  kubelet, ip-10-44-149-25.ec2.internal  Failed to apply default image tag "docker://793354189448.dkr.ecr.us-east-1.amazonaws.com/scrna-star273:1": couldn't parse image reference "docker://793354189448.dkr.ecr.us-east-1.amazonaws.com/scrna-star273:1": invalid reference format

the other one is 
kubectl describe pod nf-45d4e607f916d72ffc81d3e45a0493d2
  Type    Reason     Age   From                                    Message
  ----    ------     ----  ----                                    -------
  Normal  Scheduled  40s   default-scheduler                       Successfully assigned default/nf-45d4e607f916d72ffc81d3e45a0493d2 to ip-10-44-146-133.ec2.internal
  Normal  Pulled     38s   kubelet, ip-10-44-146-133.ec2.internal  Container image "793354189448.dkr.ecr.us-east-1.amazonaws.com/scrna-star273:1" already present on machine
  Normal  Created    38s   kubelet, ip-10-44-146-133.ec2.internal  Created container nf-45d4e607f916d72ffc81d3e45a0493d2

In fact, If we modify the problematic .command.yaml by removing "### docker://", the pod can run well without any error. 

It seemed that "docker:./" was added by normalizeShifterImageName@nextflow/container/ContainerHandler.groovy. Now for 2 users with identical credential (AWS credential and kubeconfig), one user's job was processed with normalizeShifterImageName and "docker:/./" was added automatically while the other's job does not.  

### Environment 

* Nextflow version: [20.01.0-rc1.5262] 
* Java version: [1.8.0_191]
* Operating system: [Centos7]
* Bash version: (4.2.46)

### Additional context

The kuberun is sent to a EKS cluster, with persistent volume claimed on a EFS volume. Both accounts share the same aws credential and they could access efs/ecr et.a.

**Comment by tsigalko2003** [comment]
A short update, It turned out that the strange behaves is related to config keyword 
singularity.autoMounts = true

So in short, if we set singularity.autoMounts = true, even we only use docker container img, nextflow will apply ShifterImageName and add prefix "docker://" into the img name. It is not what is supposed to do and the pod will not run because of the prefix "docker://" in address. \

-To

**Comment by pditommaso** [comment]
No container setting should be used when using the K8s executor.
