### ISSUE TITLE
New process ErrorStrategy that terminates but completes as much as possible

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#158]
It would be very useful to have a process ErrorStrategy that terminates the current process on an error, but only stops the pipeline after all other processes have finished. The goal is to save the work done in other, long running processes unrelated to the failed process.  Not sure of a good name for this that isn't several words long.  Some ideas: 
* TERMINATE_WHEN_COMPLETE
* TERMINATE_LAZILY
* TERMINATE_WAIT_FOR_OTHERS
* TERMINATE_MAXIMIZE_SUCCESS
* ????

**Comment by pditommaso** [comment]
I agree that it would be useful. For the strategy name we definitely need a quick and easy to remeber name. 

Which of the following could express better the proposed behaviour? 

- terminate
- abort 
- quit 
- (other)

**Comment by mes5k** [comment]
Just throwing some other ideas out there:
* TERMINATE_ON_NEXT
* TERMINATE_GENTLY 
* TERMINATE_POLITELY
* TERMINATE_GRADUALLY

**Comment by dctrud** [comment]
:+1: just launched a web based platform yesterday using nextflow, and in training session I gave this was one of the first questions.

'Lazy' comes to mind as the descriptive word.

**Comment by pditommaso** [comment]
Just working on that. I was more oriented to use `cancel`. What do you think? 

@dctrud Is that web platform public available?

**Comment by dctrud** [comment]
@pditommaso no - the web platform isn't public yet I'm afraid. We hope to release it, but it's not something we can get approved quickly.

**Comment by dctrud** [comment]
To me an error strategy called 'cancel' suggest on error it will cancel execution - which is essentially what the current one does?

Maybe 'finish' - as in finish what I've already started?

**Comment by pditommaso** [comment]
Thanks for the suggestion, `finish` sounds good.

**Comment by pditommaso** [comment]
I've upload a new snapshot which includes this features. It defines a new `errorStrategy 'finish'` which stops the pipeline execution but wait the current pending jobs before exit. 

It's possible to define a workflow handler as shown below to intercept an error event: 

```
workflow.onError {
  // your code 
}
```

If you want to give a try to it define the variable `export NXF_VER=0.20.0-SNAPSHOT` and then run nextflow as usual.

**Comment by mes5k** [comment]
Awesome, will experiment with this shortly!
