### ISSUE TITLE
fromFilePairs fails if the * wildcard is at the end of the path

### ISSUE THREAD

**Issue by DaGaMs** [nextflow-io/nextflow#1580]
## Bug report 

I'm trying to read pairs of vcf files and their corresponding indices (`file.vcf.gz`, `file.vcf.gz.tbi`). `fromFilePairs` returns nothing when I try this:

```groovy
Channel.fromFilePairs("./test.vcf.gz*").view()
```

I tried a custom splitter closure, but no files are even emitted from `fromFilePairs`. I also tried varying the `size` and putting double `*` etc, but to no avail. This seems like a bug?

**Comment by DaGaMs** [comment]
Should have said: `N E X T F L O W  ~  version 20.01.0`

**Comment by DaGaMs** [comment]
bump...

**Comment by pditommaso** [comment]
Need a more concrete test case.

**Comment by alanhoyle** [comment]
Nextflow doesn't seem to be able to create file pairs out of File/FileIndex pairs.

E.g. `genome.fasta` with `genome.fasta.fai` or `sample.bam` with `sample.bam.bai`

Or, maybe the question really is:  How would one create a wildcard to put into `.fromFilePairs()` that would get those?

**Comment by DaGaMs** [comment]
My take since last year, after pouring over the code a bit, is that Nextflow's `fromFilePairs` was very specifically written for fastq pairs where there is exactly one wildcard, and it is placed _before_ the file type extension suffix. Everything else won't work. I think the whole wildcard handling in `fromFilePairs` probably needs an overhaul, but I do appreciate it's a tricky problem to generalise.

**Comment by alanhoyle** [comment]
Thanks for taking the time to go over  this. I appreciate that these kinds of heuristics are a hard thing to handle.  In the meantime, maybe it should be documented that it doesn't handle the file/index pair case?
