### ISSUE TITLE
mac - script output to file not working 

### ISSUE THREAD

**Issue by rollinroy** [nextflow-io/nextflow#1581]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

On the mac, running nextflow with a bash script that redirects stdout to a file should be able to output this file to a channel but it errors out.  It works fine on linux (ubuntu 18.04)

### Steps to reproduce the problem
#!/usr/bin/env nextflow
process randomNum {
   output:
   file 'result.txt' into numbers

   '''
   echo "hello" > result.txt
   '''
}
### Program output 
Error executing process > 'randomNum'
Caused by:
  Missing output file(s) `result.txt` expected by process `randomNum`
Command executed:
  echo "hello" > result.txt
Command exit status:
  0
Command output:
  (empty)

.nextflow.log:
Apr-25 23:07:17.519 [main] DEBUG nextflow.cli.Launcher - $> nextflow -q run examples_output.nf -w ../nextflow_scratch/
Apr-25 23:07:17.814 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.04.1-edge
Apr-25 23:07:17.828 [main] INFO  nextflow.cli.CmdRun - Launching `examples_output.nf` [exotic_mcclintock] - revision: 14dce483c0
Apr-25 23:07:17.850 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /Users/royboy/work/uw/uw-gac/nextflow_work/nextflow.config
Apr-25 23:07:17.851 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Users/royboy/work/uw/uw-gac/nextflow_work/nextflow.config
Apr-25 23:07:17.879 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Apr-25 23:07:18.611 [main] DEBUG nextflow.Session - Session uuid: 1cfa5468-0245-4dbe-8f17-0f92cafc6146
Apr-25 23:07:18.611 [main] DEBUG nextflow.Session - Run name: exotic_mcclintock
Apr-25 23:07:18.611 [main] DEBUG nextflow.Session - Executor pool size: 4
Apr-25 23:07:18.780 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 20.04.1-edge build 5333
  Created: 19-04-2020 17:13 UTC (10:13 PDT)
  System: Mac OS X 10.14.6
  Runtime: Groovy 2.5.11 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_131-b11
  Encoding: UTF-8 (UTF-8)
  Process: 67755@rb-imac.local [10.0.0.26]
  CPUs: 4 - Mem: 32 GB (1.7 GB) - Swap: 0 (0)
Apr-25 23:07:18.796 [main] DEBUG nextflow.Session - Work-dir: /Users/royboy/work/uw/uw-gac/nextflow_scratch [Mac OS X]
Apr-25 23:07:18.796 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /Users/royboy/work/uw/uw-gac/nextflow_work/bin
Apr-25 23:07:18.820 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Apr-25 23:07:18.822 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Apr-25 23:07:18.980 [main] DEBUG nextflow.Session - Session start invoked
Apr-25 23:07:19.116 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-25 23:07:19.140 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: randomNum
Apr-25 23:07:19.228 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Apr-25 23:07:19.228 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Apr-25 23:07:19.233 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Apr-25 23:07:19.239 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=4; memory=32 GB; capacity=4; pollInterval=100ms; dumpInterval=5m
Apr-25 23:07:19.383 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Apr-25 23:07:19.383 [main] DEBUG nextflow.Session - Session await
Apr-25 23:07:19.476 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Apr-25 23:07:19.481 [Task submitter] INFO  nextflow.Session - [de/6049c8] Submitted process > randomNum
Apr-25 23:07:20.242 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: randomNum; status: COMPLETED; exit: 0; error: -; workDir: /Users/royboy/work/uw/uw-gac/nextflow_scratch/de/6049c87dba5e78615a1e58a78fc643]
Apr-25 23:07:20.250 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process `randomNum` is unable to find [UnixPath]: `/Users/royboy/work/uw/uw-gac/nextflow_scratch/de/6049c87dba5e78615a1e58a78fc643/result.txt` (pattern: `result.txt`)
Apr-25 23:07:20.267 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'randomNum'

Caused by:
  Missing output file(s) `result.txt` expected by process `randomNum`

Command executed:

  echo "hello" > result.txt

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /Users/royboy/work/uw/uw-gac/nextflow_scratch/de/6049c87dba5e78615a1e58a78fc643

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
Apr-25 23:07:20.272 [main] DEBUG nextflow.Session - Session await > all process finished
Apr-25 23:07:20.272 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Missing output file(s) `result.txt` expected by process `randomNum`
Apr-25 23:07:20.287 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-25 23:07:20.294 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=686ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Apr-25 23:07:20.349 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Apr-25 23:07:20.388 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

### Environment 

* Nextflow version: [20.04.1-edge.5333 and 20.01.0.5264] 
* Java version: [1.8.0_131-b11]
* Operating system: [macOS v 10.14.6]
* Bash version: 3.2.57(1)

### Additional context
When running the same nextflow file on Ubuntu 18.04/Nextflow version 20.01.0.5264/Java 11.0.7/Bash 4.4.20  it completed without errors.  However the results file was created in one of nextflow's work directories (e.g., ./work/0a/ff9828cc009c31a74b44cfd3c793f3/results.txt).  On the mac, the results file was created in the current working directory ($PWD) but nextflow couldn't find it.

Being new to nextflow, I'm not certain where the results file of the script that redirects stdout to a file.  I was hoping it would go to PWD which is the case on the mac.

Additionally, using "stdout" qualifier for the output works ok; but I was hoping to capture the output into a file at PWD.

**Comment by pditommaso** [comment]
Unable to replicate

**Comment by rollinroy** [comment]
Could you provide me your system info (version of macOS, java, nextflow, and bash)?  tia

**Comment by pditommaso** [comment]
Why?

**Comment by pditommaso** [comment]
I'm using Java 8, Bash 3.2.5, MacOs 10.4.4

(sorry for the previous message, I was thinking it was related to a different thread)

**Comment by rollinroy** [comment]
tx; should the macOS be version 10.14.4 instead of 10.4.4?
cheers, roy

**Comment by pditommaso** [comment]
Yep

**Comment by rollinroy** [comment]
It was my error.  I was using a config file where the std cfg had docker enabled.  Sorry for my bad but thanks for your help.
