### ISSUE TITLE
Space in non-existant filename in file channel causes file existence logic to fail.

### ISSUE THREAD

**Issue by alanhoyle** [nextflow-io/nextflow#1587]
### Expected behavior and actual behavior

When there's a space in a column value that should be a filename, the file detection for the channel doesn't work.  The example below doesn't feed any channels, but it demonstrates the problem.  We normally run in singularity and when this comes up, it creates symbolic links to erroneous paths that don't exist.  

Expected behavior:  Nextflow comes back with a "file not found" when it looks for a file path with a space in it. (or nextflow should trim the whitespace at the beginning/end of a file path

Actual behavior:  Nextflow appends the directory where the workflow was invoked which makes it pass the 'file exists' test, but then throws the workflow name with a space into the file channel, which causes weird things down the line.  

Looking at the "Program output" section below, for line "BLAH1", in a process that consumes the channel, nextflow would create a symbolic link that would literally link to a non-existent file named `/Users/alanh/\ /tmp/nf-input-bug/file-that-is-missing.txt`

### Steps to reproduce the problem

https://github.com/alanhoyle/nf-input-bug

### Program output 
```
nextflow run /tmp/nf-input-bug/test.nf --input /tmp/nf-input-bug/manifest.txt
N E X T F L O W  ~  version 20.01.0
Launching `/tmp/nf-input-bug/test.nf` [shrivelled_ampere] - revision: 88a147f001
[BLAH0, /tmp/nf-input-bug/file-that-exists.txt]
[BLAH1, /Users/alanh/ /tmp/nf-input-bug/file-that-exists.txt]
[BLAH2, /Users/alanh/ /tmp/nf-input-bug/file-that-is-missing.txt]
[BLAH3, /Users/alanh/more bad input /tmp/nf-input-bug/file-that-is-missing.txt]
```
### Environment 

* Nextflow version: tested on 20.01.0.5264 and 19.10.0.5170
* Java version: 11.0.6 on mac, 11.0.4 openJDK on linux
* Operating system: macOS 10.15.4 and CenOS 7.7.1908
* Bash version:  zsh 5.7.1 (x86_64-apple-darwin19.0) and GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by alanhoyle** [comment]
Note that in many file systems, spaces are legal characters to include in a filename (albeit they must be escaped at the command lines).

**Comment by pditommaso** [comment]
You should use the `strip` option to remove leading and trailing blank characters. Have a look at the [splitCsv docs](https://www.nextflow.io/docs/latest/operator.html#splitcsv).

**Comment by alanhoyle** [comment]
@pditommaso : As I said in my previous comment, it is possible for a file that actually exists to have spaces in the file name.  I have updated my git repo above to add a file with spaces that _does_ actually exist and it handles that case properly.  

The bug is that if there's a **space in a filename that does not exist**, nextflow does not handle that properly.  

```
nextflow run /tmp/nf-input-bug/test.nf --input /tmp/nf-input-bug/manifest.txt
N E X T F L O W  ~  version 20.01.0
Launching `/tmp/nf-input-bug/test.nf` [focused_cray] - revision: 88a147f001
[BLAH0, /tmp/nf-input-bug/file-that-exists.txt]
[BLAH1, /private/tmp/nf-input-bug/.git/ /tmp/nf-input-bug/file-that-exists.txt]
[BLAH2, /private/tmp/nf-input-bug/.git/ /tmp/nf-input-bug/file-that-is-missing.txt]
[BLAH3, /private/tmp/nf-input-bug/.git/more bad input /tmp/nf-input-bug/file-that-is-missing.txt]
[BLAH4, /tmp/nf-input-bug/file that also exists.txt]
```

**Comment by pditommaso** [comment]
NF does not check for file existence, therefore I'm not understanding what you are expecting.

**Comment by alanhoyle** [comment]
Hmm.  So it's expected behavior that a filepath that doesn't exist gets the current-working-directory appended to the beginning of the filename?  

I guess I was expecting an error or warning up front at runtime about file existing, rather than having something happen down at the process level.

**Comment by pditommaso** [comment]
You will get an error when a process will try to access that file. But in your snippet there's anything opening the file. The `file` function only resolves the file path against the current directory.

**Comment by alanhoyle** [comment]
I'm guessing the reason why NF doesn't warn about file non-existence issues at workflow initiation time is due to the fact that it would massively complain about such issues when kicked off to run on a cloud provider (AWS/GCP) and some compute cluster systems.  I think it would definitely be worth warning about such issues when the process.executor is local, and most cluster environments, optionally allowing suppression.
