### ISSUE TITLE
LSF jobs stall out but do not die

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#1592]
## Bug report 

We have been having problems on our HPC where Nextflow jobs submitted to LSF stall out indefinitely. So far this has been seen affecting jobs running inside Singularity containers. 

### Expected behavior and actual behavior

Normally, if a job submitted to LSF exceeds the memory limit, the job fails and Nextflow detects the error. 

In some rare cases (a tiny percentage of Nextflow's LSF jobs), Nextflow (`.command.run`) is not detecting that the task has failed due to memory limits, so the job remains running until LSF kills it due to exceeding the time limit. 

The issue is not possible to directly reproduce due to the non-deterministic nature of the bug, but here is a documentation of the behavior that was observed. 

-----

While checking a Nextflow pipeline, I found that it was waiting for a single task to finish running:

```
$ tail logs/2020-04-29_16-42-16/nextflow.log
May-01 08:49:05.842 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor lsf > tasks to be completed: 1 -- pending tasks are shown below
~> TaskHandler[jobId: 35867927; id: 3539; name: RunMsiSensor (Sample1__Sample2); status: RUNNING; exit: -; error: -; workDir: /project/work/af/17da70cdfde589da46976a95cc6b30 started: 1588219314998; exited: -; ]
```

Checking the LSF job for this task, I found that the job was still running:

```
$ bjobs 35867927
           JOBID         USER     JOB_NAME   STAT      QUEUE  FROM_HOST    EXEC_HOST   SUBMIT_TIME    START_TIME  TIME_LEFT
        35867927      kellys5 *7L7_N002_d)    RUN    general       ju23         jy02  Apr 30 00:01  Apr 30 00:01   466:47 L

```

Checking the `work` directory for this task, I found a `core.` file indicating a memory core dump, thus a problem related to memory during task execution:

```
$ ls -ltra /project/work/af/17da70cdfde589da46976a95cc6b30
total 32115
-rw-r--r--  1 kellys5 ci    12554 Apr 30 00:01 .command.run
-rw-r--r--  1 kellys5 ci      192 Apr 30 00:01 .command.sh
-rw-r--r--  1 kellys5 ci        0 Apr 30 00:01 .command.begin
-rw-r--r--  1 kellys5 ci    21453 Apr 30 00:31 .command.log
drwxr-sr-x  2 kellys5 ci     4096 Apr 30 05:19 .
-rw-------  1 kellys5 ci 16076800 Apr 30 05:19 core.51737
drwxr-sr-x 39 kellys5 ci     4096 May  1 01:31 ..
```

However, notice the timestap, the core dump happened at Apr 30 05:19 yet the LSF job was still running as of May-01 08:49. 

Also notice that files indicating that the Nextflow task had finished (`.exitcode`, `.command.out`, `.command.err`, etc.) were not present. Unfortunately in this case, the task was executing on node `/scratch` space, which I did not think to check. However, the `.command.log` did not show any error messages (yet), and looked like this:

```
$ tail /project/work/af/17da70cdfde589da46976a95cc6b30/.command.log
window: 509 done...:2:27712422-28211681
window: 510 done...:2:28219070-28716688
window: 511 done...:2:28719589-29220665
window: 512 done...:2:29223214-29722236
window: 513 done...:2:29724554-30223860
window: 514 done...:2:30226732-30727947
window: 515 done...:2:30727194-31229130
window: 516 done...:2:31234659-31735145
window: 517 done...:2:31738695-32240554
window: 518 done...:2:32238865-32739976
```

I decided to kill the LSF job and see what happens;

```
$ bkill 35867927
Job <35867927> is being terminated
```

Very quickly, Nextflow detected that the task had failed and moved on with the rest of the pipeline

```
$ tail -f logs/2020-04-29_16-42-16/nextflow.log

May-01 09:34:05.924 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor lsf > tasks to be completed: 1 -- pending tasks are shown below
~> TaskHandler[jobId: 35867927; id: 3539; name: RunMsiSensor (Sample1__Sample2); status: RUNNING; exit: -; error: -; workDir: /project/work/af/17da70cdfde589da46976a95cc6b30 started: 1588219314998; exited: -; ]

May-01 09:35:46.043 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[jobId: 35867927; id: 3539; name: RunMsiSensor (Sample1__Sample2); status: COMPLETED; exit: 130; error: -; workDir: /project/work/af/17da70cdfde589da46976a95cc6b30 started: 1588219314998; exited: 2020-05-01T13:35:43Z; ]

May-01 09:35:46.047 [Task monitor] INFO  nextflow.processor.TaskProcessor - [af/17da70] NOTE: Process `RunMsiSensor (Sample1__Sample2)` terminated with an error exit status (130) -- Error is ignored

May-01 09:35:46.570 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [LSF] submitted process SomaticAggregateMetadata (default_cohort) > jobId: 35886855; workDir: /project/work/d6/cd82bed021311d3fb37ad96b4ba0b2
```

Notice the exit code reported here; `exit: 130`. On our system, 130 is the LSF exit code when a task exceeds the memory allocation. 

However, when I checked the task `work` dir, the remaining Nextflow files suddenly appeared

```
$ lt /project/work/af/17da70cdfde589da46976a95cc6b30
total 16M
-rw-r--r--  1 kellys5  13K Apr 30 00:01 .command.run
-rw-r--r--  1 kellys5  192 Apr 30 00:01 .command.sh
-rw-r--r--  1 kellys5    0 Apr 30 00:01 .command.begin
-rw-------  1 kellys5  16M Apr 30 05:19 core.51737
drwxr-sr-x 39 kellys5 4.0K May  1 01:31 ..
-rw-r--r--  1 kellys5  21K May  1 09:35 .command.out
-rw-r--r--  1 kellys5    0 May  1 09:35 .command.err
-rw-r--r--  1 kellys5    0 May  1 09:35 .command.trace
drwxr-sr-x  2 kellys5 4.0K May  1 09:35 .
-rw-r--r--  1 kellys5    3 May  1 09:35 .exitcode
-rw-r--r--  1 kellys5  25K May  1 09:35 .command.log
```

This shows that Nextflow's `.command.run` was still running for the entire duration of the pipeline job

When I check the Nextflow reported exit code, I see the value 130, as indicated in the logs;

```
$ cat /project/work/af/17da70cdfde589da46976a95cc6b30/.exitcode
130
```

However, LSF itself reports the exit code as 7;

```

$ cat /project/work/af/17da70cdfde589da46976a95cc6b30/.command.log
…
…
------------------------------------------------------------
Sender: LSF System <lsfadmin@jy02>
Subject: Job 35867927: <nf-RunMsiSensor_(Sample1__Sample2)> in cluster <juno> Exited

Job <nf-RunMsiSensor_(Sample1__Sample2)> was submitted from host <ju23> by user <kellys5> in cluster <juno> at Thu Apr 30 00:01:49 2020
Job was executed on host(s) <jy02>, in queue <general>, as user <kellys5> in cluster <juno> at Thu Apr 30 00:01:50 2020
</home/kellys5> was used as the home directory.
</project/work/af/17da70cdfde589da46976a95cc6b30> was used as the working directory.
Started at Thu Apr 30 00:01:50 2020
Terminated at Fri May  1 09:35:54 2020
Results reported at Fri May  1 09:35:54 2020

Your job looked like:
…
…
TERM_OWNER: job killed by owner.
Exited with signal termination: 7, and core dumped.

Resource usage summary:

    CPU time :                                   117037.00 sec.
    Max Memory :                                 8 GB
    Average Memory :                             7.88 GB
    Total Requested Memory :                     8.00 GB
    Delta Memory :                               0.00 GB
    Max Swap :                                   -
    Max Processes :                              18
    Max Threads :                                26
    Run time :                                   120845 sec.
    Turnaround time :                            120845 sec.

The output (if any) is above this job summary.
```

Notice the description from LSF here; `Exited with signal termination: 7, and core dumped`. It looks like LSF was aware of the core dump, or likely initiated it. And for some reason it reports the error with exit status of 7, due to my user-initiated termination, instead of the 130 for the memory limit.

The part that is most relevant to Nextflow, and which does not make sense to me, is why Nextflow's `.command.run` continued running the entire time, essentially sitting idle and waiting on the Singularity container process, despite the Singularity container process apparently being killed by LSF. If I had not intervened, this LSF job, and thus the pipeline as a whole, would have lasted another 400 hours until that job's LSF walltime expired.

-----

It might possibly be related to #1561 since the underlying behavior seems similar. In that issue, even when we tried to re-introduce `nxf_kill` and similar process killing commands into `.command.run`, we were unable to shut down the task correctly because the Singularity process which Nextflow pushes to the background could not be correctly controlled or detected. Our correspondence with IBM suggests issues with background process handling in LSF, however their only proposed solution so far has been to issue the `wait` command on the background process (`nxf_launch` in this case), which Nextflow already does; 

```
( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
```

If the background process control on our server is faulty like this for some reason, I am not sure how to deal with the issue inside Nextflow. Maybe if we had a way to avoid pushing the `nxf_launch` process into background we would have better luck with having these failures detected? I am open to any ideas or thoughts on the matter.

-----

### Environment 

* Nextflow version: 19.10.0
* Java version: 8
* Operating system: Centos 7
* Bash version: 4.2.46
* LSF version: 10.1 linux3.10-glibc2.17-x86_64
* Singularity 3.3.0

**Comment by pditommaso** [comment]
This may be related to this issue #1432. Use latest `20.04.1` release.

**Comment by stevekm** [comment]
in our case, we found out that our LSF is dropping these core dump files when it senses that a job is nearing the memory limit, but does not actually kill the job immediately, if at all, for reasons I do not yet completely understand. But suffice it to say that these jobs were not actually stalled and were still running. So I will close this one. Thanks.
