### ISSUE TITLE
Google API - Shutdown on error

### ISSUE THREAD

**Issue by mozack** [nextflow-io/nextflow#1600]
## Bug report 

Hi, I am still seeing cases where Nextflow shuts down on a transient error when running using the Google Lifesciences API

See also: 
https://github.com/nextflow-io/nextflow/issues/1293

### Expected behavior and actual behavior
Expected behavior would be to honor the maxRetries / maxErrors directives and retry on failure.  Actual behavior is that the workflow is shutdown on error (but not always - sometimes Nextflow does retry)

### Steps to reproduce the problem

error.tgz contains the details and logs of the workflow I've seen this in most recently.

### Program output 
```
Command exit status:
  2

Command output:
  (empty)

Command error:
  Execution failed: generic::unknown: action 1: waiting for container: starting container: running ["docker" "start" "-ai" "5d69e91f6dc99742427b5970df1b096b0e6b713689ce2ffdbe7dcb0e1129965e"]: exit status 125

Work dir:
  gs://lccc-informatics-isb/target/nf-work/cnv-call-normals2/SeqCapEZHumanExomeV2/68/37a18dfe0eea364464b0f6c79d02f3

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
May-06 16:38:11.671 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `cnvkit (TARGET-10-PASLZM-10A)` terminated with an error exit status (2)
May-06 16:38:11.743 [Task monitor] DEBUG nextflow.Session - The following nodes are still active:
[process] cnvkit
  status=ACTIVE
  port 0: (value) bound ; channel: cnv_ref
  port 1: (queue) OPEN  ; channel: -
  port 2: (cntrl) -     ; channel: $

May-06 16:38:11.782 [main] DEBUG nextflow.Session - Session await > all process finished
May-06 16:38:11.782 [main] DEBUG nextflow.Session - Session await > all barriers passed
May-06 16:38:11.851 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (12)
May-06 16:38:11.871 [main] DEBUG n.c.g.p.GooglePipelinesTaskHandler - [GPAPI] Killing task > map_tumor (TARGET-10-PAPEFH-14A) - Pipeline Id: 17030850920926712185
May-06 16:38:12.025 [main] DEBUG n.c.g.p.GooglePipelinesTaskHandler - [GPAPI] Killing task > map_tumor (TARGET-10-PAPJIB-14A) - Pipeline Id: 6035351389288088524
<log continues - see attached ...>
```

### Environment 

* Nextflow version: 20.04.1
* Java version: openjdk version "1.8.0_252"
* Operating system: [Linux]
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

In my experience, running Nextflow locally and communicating with the Google API remotely increases the likelihood of these types of errors occurring.

Please see, logs, workflow, config, etc in:
[error.tar.gz](https://github.com/nextflow-io/nextflow/files/4593844/error.tar.gz)

**Comment by pditommaso** [comment]
The log suggests you are using the old `google-pipelines` executor instead of new `google-lifesciences`.

**Comment by mozack** [comment]
Ah, I assumed google-pipelines would automatically use the new API in newer Nextflow versions.  I'll change the executor and retry.  Thanks!
