### ISSUE TITLE
Addition to the DSL module to allow chaining of workflows

### ISSUE THREAD

**Issue by thomasyu888** [nextflow-io/nextflow#1601]
## New feature
Ability to chain workflows together to track what parameters were used with a specific workflow and chain different workflows published on github.

## Usage scenario 
I want to create a pipeline (pseudo code below) where I want to download a bunch of fastq files and run the `nf-core/rnaseq` workflow.  I could write a bunch of python code to download the files that also keeps track of the parameters that I use with `nf-core/rnaseq`, but it would be nice to be able to do:

`nextflow run my_rnaseq_workflow.nf`.

```groovy
process downloadfiles {

    output:
    file "myfastq.fq.gz" into fastq

    script:
    '''
    wget urlto/myfastq.fq.gz
    '''
}

process run_rnaseq {
    input:
    file my_fast from fastq

    script:
    '''
    nextflow -bg run  nf-core/rnaseq -r 1.4.2 -profile docker --reads '$my_fast' --genome GRCh37 --skipAlignment --pseudo_aligner salmon
    '''
}


```

I realize I could just fork the `nf-core/rnaseq` repository and just add steps to it, but that makes the tool less modular.  (not sure if the pseudo code actually works, but thats how I would implement this today)

## Suggest implementation 

Not sure how this would be implemented but perhaps instead of just importing specific processes from a workflow, to just be able to also import the entire workflow.

**Comment by jaeddy** [comment]
Tacking onto @thomasyu888, Nextflow would be significantly more flexible and useful with the ability to import and execute "subworkflows". I don't know that this needs to be as infinitely nest-able as e.g. CWL workflows, but even one level could be a big win.

**Comment by pditommaso** [comment]
It does already 👉  https://www.nextflow.io/docs/edge/dsl2.html#workflow-composition
