### ISSUE TITLE
Installation Documentation Lacking GitHub Package Instuctions

### ISSUE THREAD

**Issue by DarioS** [nextflow-io/nextflow#1602]
The NextFlow website has instructions for using curl to download the package and install it, but GitHub distributes files such as nextflow-20.04.1-all How are those to be installed? I don't see any instructions in the manual about what to do with these files. Please add some instructions about them.

**Comment by KevinSayers** [comment]
It is just a standard binary file. Can be added to the docs though.  

- Download the binary: 
`wget https://github.com/nextflow-io/nextflow/releases/download/v20.04.1/nextflow-20.04.1-all`

- Make it executable:
 `chmod +x nextflow-20.04.1-all` 

- Rename and add it to a folder in your $PATH:
 `mv nextflow-20.04.1-all $HOME/bin/nextflow`

**Comment by DarioS** [comment]
Thanks. I agree that it's worth mentioning for the benefit of first timers to NextFlow.

**Comment by pditommaso** [comment]
TBD

**Comment by ashleethomson** [comment]
Hopefully I'm not too late! First time to Netflow as well and I too had the same problem so thank you for clearing it up, but I'm still having some troubles. I'm using Windows 10 and am attempting to make the file executable. I've attempted going through Ubuntu and Cydwin64, which thankfully don't throw any errors back at me, but nothing happens (see below)

ashle@DESKTOP-G298SLS /cygdrive/c/windows/system32/nextflow
$ chmod +x nextflow-20.04.1-all

ashle@DESKTOP-G298SLS /cygdrive/c/windows/system32/nextflow
$

I've ensured I'm running Java 8 and Bash 3.2. I've also tried xcacls, icacls and every other version of cacls that I've seen recommended to try.

Any help would be gratefully received!!

**Comment by pditommaso** [comment]
@abhi18av maybe we can mention this in the Get started docs

**Comment by abhi18av** [comment]
Definitely @pditommaso, I've created the PR https://github.com/nextflow-io/nextflow/pull/1807 to highlight this  :)

**Comment by abhi18av** [comment]
@ashleethomson, I'm not too familiar with `cygwin` but I do regularly use `nextflow`  on `WSL2` as this is the official native linux experience, so less surprises overall.

As you have WIndows-10, I do suggest that you give a shot to WSL2 setup while getting started with `nextflow` to avoided being stuck later on. 

Here's an official resource https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by ashleethomson** [comment]
@abhi18av Thanks for the reply. I doublechecked I was using WSL2, and it's registering that I am
`C:\windows\system32>wsl -l -v`
`NAME         STATE           VERSION`
`*Ubuntu    Running            2`

but I'm still not getting anything back for any of the nextflow assets. One of the few times I'd love to receive some type of error code haha. 
`ashleejthomson@DESKTOP-G298SLS:/mnt/c/windows/system32/nextflow$ chmod +x nextflow-20.04.1-all`
`ashleejthomson@DESKTOP-G298SLS:/mnt/c/windows/system32/nextflow$ chmod +x nextflow`
`ashleejthomson@DESKTOP-G298SLS:/mnt/c/windows/system32/nextflow$ chmod +x nextflow-0.26.0-all`
`ashleejthomson@DESKTOP-G298SLS:/mnt/c/windows/system32/nextflow$ chmod +x nextflow-20.10.0-all`

I went back over that doc and checked that I had all the settings and installs updated as well.

**Comment by abhi18av** [comment]
@ashleethomson , good news 👍 

Please correct me if I'm wrong about the overall issue here, despite doing `chmod +x nextflow-20.10.0-all` you are not able to run the binary right?

Just to confirm, could you please share the output of `nextflow-20.10.0-all info`? If it prints version reports, than you're all set for moving further. 

In case it doesn't work, please do check the `java -version` is working and the `JAVA_HOME` is set within the WSL.

**Comment by ashleethomson** [comment]
@abhi18av ... I'm an idiot .... my firewall was blocking Ubuntu from connecting to anything. That was why nothing was installing. Now that I have disabled it, Nextflow has installed with no issues. Thank you for your help!! Hopefully I won't have any further problems ...

**Comment by abhi18av** [comment]
Hi @ashleethomson , 

No worries, it happens :) 

In case you come across more issues, you can reach out to the `Nextflow` community on Gitter channel here  https://gitter.im/nextflow-io/nextflow
