### ISSUE TITLE
Logging: File download / container building

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#1607]
## Usage scenario 

We periodically get help requests / bug reports that nf-core pipelines have crashed, where the user tries testing the pipeline on a small dataset (expecting it to complete in a couple of minutes) but it sits there after the initial log for a long time (sometimes hours). This is often because the pipeline is downloading large reference index files from the internet, or downloading + building large singularity containers.

It would be great if Nextflow showed some logs about these processes, so that it's clear that something is happening.

## Suggest implementation 

With the ASCII logging especially, it would be great to have some kind of progress bar for downloads. For example:

```
Downloading (3/16): s3://ngi-igenomes/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/BismarkIndex/genome.fa
[================>                          ] 34% of 1.2 Gb
```

I guess a progress bar is tougher for containers(?) But even a simple status message would be good:

```
Pulling container: nf-core/rnafusion
```

```
Building singularity container: nf-core-rnafusion.simg
```

Thanks!

Phil

**Comment by pditommaso** [comment]
This is a hard one. Consider that the container download can be completely transparent to NF for example when running a job with Batch. Also, with a local docker execution, the pull is done implicitly by the `docker run` command, there's no way to fetch the progress info other the stdout. 

Maybe there is some chance to improve the file transfers feedback

**Comment by ewels** [comment]
Ah that's a good point, I hadn't thought about the fact that the docker pull is done essentially outside of Nextflow. To be honest, the download is the main thing :+1:
