### ISSUE TITLE
Module load problem

### ISSUE THREAD

**Issue by fredericlemoine** [nextflow-io/nextflow#161]
Dear Paolo,

On our cluster, we have version 3.3 of environment modules, (https://sourceforge.net/p/modules/git/ci/master/tree/). 
It appears that with this version, when a module is already loaded, `module load ...` returns 1 as an exit status (0 otherwise).

The nextflow job initialization script `.command.run` then stops just at the line `&& source .../.command.env` with the error: `COUT: unbound variable`, I guess because `on_exit` function is called before `$COUT` and `$CERR` have been initialized. 

Then the workflow stops with several error messages such as `cannot dump error file, file not found, etc...`.

So far I solved the problem by adding `module purge` in my `~/.bashrc`, but I thought is may interest you to know.

Best

**Comment by fredericlemoine** [comment]
By the way the nextflow versio I use is `0.18.0.3662`

**Comment by pditommaso** [comment]
Thanks for reporting this. if I remember well also @emi80 encountered this problem. Any advice how it could be managed in a better way by nextflow?

**Comment by fredericlemoine** [comment]
To ensure that the module environment is clean, would it be possible, if module is specified in the process, to do `module purge` as a first step of the `.command.env` script? I don't know if there could be side effects...

**Comment by pditommaso** [comment]
That could be an option. @emi80 what do you think?

**Comment by dctrud** [comment]
@pditommaso @fredericlemoine module purge is a bit too aggressive. On various clusters, such as ours here you would see something like this:

``` bash
12:32 PM $ module avail matlab

---------------------------- /cm/shared/modulefiles ----------------------------
matlab/2008b matlab/2013b matlab/2014b matlab/2015b
matlab/2013a matlab/2014a matlab/2015a matlab/2016a

12:32 PM $ module purge

12:32 PM $ module avail matlab

12:32 PM $ 
```

Note after the purge the matlab modules aren't available. This is because in the default profile we are loading a module called 'shared'. Without the module named 'shared' loaded you don't have access to to the modules that it provides. This is taking advantage of environment-modules ability to create a hierarchy of modulefiles.... with modules that give access to sets of other modules.

```
12:33 PM $ module show shared
-------------------------------------------------------------------
/cm/local/modulefiles/shared:

module-whatis	 adds shared modules 
module		 use --append /cm/shared/modulefiles 
-------------------------------------------------------------------
```

It's not uncommon for this to be used on large shared clusters, or even by specific labs who want to maintain their own module sets in their own lab-specific space.

How about instead of a plain 'module load' a hacky one liner...

```bash
module list 2>&1 | grep -q 'matlab' || module add 'matlab'
```

**Comment by pditommaso** [comment]
Makes a lot of sense.

**Comment by fredericlemoine** [comment]
Does it work if one wants to load a specific version of a tool, that is different from the one already loaded?

**Comment by pditommaso** [comment]
I've made a couple of tests loading a different version of a module already loaded and it worked with no errors. 

But I'm wondering if this could a problem related to a specific module implementation. Could you please make some test loading a different version of the module that raised this issue?

**Comment by fredericlemoine** [comment]
I don't know if it answers your exact question, but initially, the R/3.2.3 module raised this issue. I tried with R/2.15.2,
```
$ module load R/2.15.2
$ echo $?
0
$ module load R/2.15.2
$ echo $?
1
$ module purge
$ module load R/2.15.2
$ echo $?
0
$ module load R/3.2.3
$ echo $?
0
$ R -—version
R version 3.2.3 (2015-12-10)
$ module purge
$ module load bowtie2/2.1.0
$ echo $?
0
$ module load bowtie2/2.1.0
$ echo $?
1
```

**Comment by pditommaso** [comment]
Looking at 

	$ module load R/2.15.2
	$ echo $?
	0
	$ module load R/2.15.2
	$ echo $?
	1

and

	$ module load R/2.15.2
	$ echo $?
	0
	$ module load R/3.2.3
	$ echo $?
	0

It suggests that an error is returned when trying to load the same version of a module already loaded. So it should be OK, because the proposed change would prevent this. 

Actually @dctrud proposed to use `add` instead of `load`, see: 

    module list 2>&1 | grep -q 'matlab' || module add 'matlab'

Though I don't know exactly what is the different between the two.  @dctrud could you please provide more details about that?

**Comment by EricDeveaud** [comment]
yes loading the same modulefile returns an error. 
let me check if I can change this behaviour in module without breaking anything in module ;-)

FYI module load and module add are just the syntaxic sugar

**Comment by pditommaso** [comment]
It's enough that returns a zero status when loading a different version of the same module. 

if so the proposed patch would solves the problem.

**Comment by EricDeveaud** [comment]
@pditommaso it is already the case

loading different version of the same module returns SUCCESS
loading already loaded version return FAILURE.

see 
''' sh
bic-soft:~ > module list 
No Modulefiles Currently Loaded.
bic-soft:~ > module load R/3.1.2
bic-soft:~ > echo $?
0
bic-soft:~ > module load R/3.1.2
bic-soft:~ > echo $?
1
bic-soft:~ > module list 
Currently Loaded Modulefiles:
  1) R/3.1.2
'''
and 

''' sh
bic-soft:~ > module list 
Currently Loaded Modulefiles:
  1) R/3.1.2
bic-soft:~ > module purge 
bic-soft:~ > module list  
No Modulefiles Currently Loaded.
bic-soft:~ > module load R/3.1.2
bic-soft:~ > echo $?
0
bic-soft:~ > module load R/3.2.3
bic-soft:~ > echo $?
0
bic-soft:~ > module list 
Currently Loaded Modulefiles:
  1) R/3.1.2   2) R/3.2.3
'''

changing the version of some module  is performed via the "module swap" command

''' sh
bic-soft:~ > module list 
No Modulefiles Currently Loaded.
bic-soft:~ > module load R/3.1.2
bic-soft:~ > module list 
Currently Loaded Modulefiles:
  1) R/3.1.2
bic-soft:~ > module swap R/3.1.2 R/3.2.3
bic-soft:~ > echo $?
0
bic-soft:~ > module list 
Currently Loaded Modulefiles:
  1) R/3.2.3
'''

**Comment by pditommaso** [comment]
I'm wondering if nextflow should use a `swap` when a different version of a module is loaded and `load` otherwise.

**Comment by pditommaso** [comment]
I ended up with a bash function like this: 

	nxf_module_load(){
	  local mod=$1
	  local ver=$2 
	  local new_module="$mod/$ver"
	  if [[ ! $(module list 2>&1 | grep $new_module) ]]; then 
		old_module=$(module list 2>&1 | grep -Eo "$mod\/[^\( \n]+")
		if [[ $old_module ]]; then 
		  echo module switch $old_module $new_module
		else 
		  echo module load $new_module 
		fi 
	  fi
	}

To recap, if the module with the specified version, it does nothing. If a module with a different version is loaded it switches to the new version. Otherwise just load it.

**Comment by fredericlemoine** [comment]
It should work!

**Comment by pditommaso** [comment]
OK. I've uploaded a snapshot including this patch. You may want to give a try to it using the following command: 

    NXF_VER=0.19.2-SNAPSHOT nextflow run  ...

**Comment by fredericlemoine** [comment]
It works, thanks!

### Config

.bashrc:
```
module load bowtie/0.12.8
```

main.nf:
```
inputChannel = Channel.from(1,2,3,4,5,6)

process bowtieVersion{
        module 'bowtie/0.12.8'
        input:
        val(i) from inputChannel
        output:
        set val(i), stdout into outputChannel
        shell:
        '''
        #!/usr/bin/env bash
        bowtie --version
        '''
}

outputChannel.subscribe{ println it }
```

### Run with nextflow `0.19.1`

```
nextflow run main.nf
```

Output:
```
Error executing process > 'bowtieVersion (6)'
```

And .nextflow.log:

```
...
mai-26 09:28:22.580 [Thread-2] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: /.../.command.out
mai-26 09:28:22.582 [Thread-2] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /.../.command.err
mai-26 09:28:22.585 [Thread-2] ERROR nextflow.processor.TaskProcessor - Error executing process > 'bowtieVersion (6)'
...
```

### Run with nextflow `0.19.2-SNAPSHOT`:
```
NXF_VER=0.19.2-SNAPSHOT nextflow run  main.nf
```

Output OK:
```
[3, /.../bowtie version 0.12.8 64-bit
...
Options: -O3   -Wl,--hash-style=both -Wall -g  
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
]
...
[1, /.../bowtie version 0.12.8 64-bit
...
Options: -O3   -Wl,--hash-style=both -Wall -g  
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
]
```

Do you want me to close the issue?

Thank you!

**Comment by pditommaso** [comment]
Good. I'm going to release a minor version today. Tx!

**Comment by pditommaso** [comment]
Just released `0.19.2`

**Comment by fredericlemoine** [comment]
Very fast! Thank you

**Comment by pditommaso** [comment]
happy hacking ;)
