### ISSUE TITLE
DSL2: parameters should be prefixed with module instance name

### ISSUE THREAD

**Issue by marcadella** [nextflow-io/nextflow#1610]
## New feature

Assuming I have a module `M` with a parameter `p`.
When importing the module like `import m from M`, I want to be able to set a default value for `p` in `main.nf` like this: `params.m.p = 4`.
This way it is easier to know which parameter belongs to which module instance.

Assuming `p, q, r` parameters of `M` and `m1, m2` instances of `M` it becomes then much clearer to define the parameters:
```
params {
  m1 {
    p = 1
    q = 2
    r = 3
  }
  m2 {
    p = 4
    q = 5
    r = 6
  }
}
```

**Comment by pditommaso** [comment]
Can you already doing this, provided the params are accessed using the fully scoped name eg `params.m1.p` and `params.m2.p`.

**Comment by marcadella** [comment]
Could I get an example? Defining `params.m1.p = 1` in `main.nf` doesn't work.
