### ISSUE TITLE
Docker image doesn't work with docker executor

### ISSUE THREAD

**Issue by marcadella** [nextflow-io/nextflow#1612]
## Bug report 

When attempting to use Nexflow docker image to execute a workflow based on docker executor I get the following error:
`/bin/bash .command.sh: No such file or directory`

Here is how I ran nextflow:
```
docker run --rm -v <pathToRepo>:/workflow -v /var/run/docker.sock:/var/run/docker.sock nextflow/nextflow:20.04.1 nextflow run /workflow
```

**Comment by pditommaso** [comment]
You need to mount the pipeline work directory.

**Comment by marcadella** [comment]
No it is still failing with the same error with `docker run --rm -v <pathToRepo>:/workflow -v <pathToWorkspace>:/home -v /var/run/docker.sock:/var/run/docker.sock nextflow/nextflow:20.04.1 bash -c "cd /home && nextflow run /workflow"`.
Could you please reopen the issue?

**Comment by lizihuang1** [comment]
I encountered the same error when I trying to use nextflow itself as docker...
