### ISSUE TITLE
Specify accelerator in config

### ISSUE THREAD

**Issue by r0f1** [nextflow-io/nextflow#1617]
Hi,
I'd like to move the accelerator specification from the process definition in my `.nf` file to the config file. Is that possible? I would like to write something like this in my `nextflow.config` file:

```
// nextflow.config
process {
    executor = 'google-lifesciences'
    container = '...'
    accelerator 1, type: 'nvidia-tesla-t4'
}
```

**Comment by pditommaso** [comment]
Hi, 

You need to express it as Map, therefore 


```
process {
    executor = 'google-lifesciences'
    container = '...'
    accelerator  = [request: 1, type: 'nvidia-tesla-t4']
}
```

Have a look at the code for details 

https://github.com/nextflow-io/nextflow/blob/624c8e83bb110dce1a210f2c5a1c4c563e9e477f/modules/nextflow/src/main/groovy/nextflow/executor/res/AcceleratorResource.groovy#L31-L62

**Comment by r0f1** [comment]
Thank you, perfect :)

**Comment by xhejtman** [comment]
It should be fixed in documentation then. https://www.nextflow.io/docs/latest/process.html#accelerator
