### ISSUE TITLE
autoload of modules DSL2

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#1619]
## New feature for 
Hi, I think that having a quick way to load every module in a library (i.e.folder) can be a nice feature in the new DSL 2. Something like PhP's autoload for classes. 

```
include * from "${baseDir}/modules/qc/"
```

the namespaces for the workflows will be the same described in the module file.

**Comment by pditommaso** [comment]
This was possible in older versions. See https://github.com/nextflow-io/nextflow/issues/1483.
