### ISSUE TITLE
Native execution doesn't print all output

### ISSUE THREAD

**Issue by mahesh-panchal** [nextflow-io/nextflow#1621]
## Bug report 

Native execution does not appear to print all output.

### Expected behavior and actual behavior

The example given in the documentation for native execution when run does not print the complete output. 

### Steps to reproduce the problem

test_exec.nf:
```
x = Channel.from( 'a', 'b', 'c')

process simpleSum {
    input:
    val x

    exec:
    println "Hello Mr. $x"
}
```

### Program output 

```
$ nextflow run test_exec.nf 
N E X T F L O W  ~  version 20.01.0
Launching `test_exec.nf` [determined_perlman] - revision: 2dd250e302
Hello Mr. b
[-        ] process > simpleSum -
Hello Mr. a
executor >  local (3)
[66/1f8820] process > simpleSum [100%] 3 of 3 ✔

$ nextflow run test_exec.nf 
N E X T F L O W  ~  version 20.01.0
Launching `test_exec.nf` [cheesy_marconi] - revision: 2dd250e302
[-        ] process > simpleSum -
Hello Mr. c
Hello Mr. b
executor >  local (3)
[88/631d95] process > simpleSum [100%] 3 of 3 ✔

```

[nextflow.log](https://github.com/nextflow-io/nextflow/files/4724079/nextflow.log)

### Environment 

* Nextflow version: 20.01.0
* Java version: openjdk 11.0.1 2018-10-16 LTS
* Operating system: macOS
* Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

**Comment by pditommaso** [comment]
This is a side effect of the *ansi* logging rendering. Either disable it or use `log.info` that support it., e.g. 

```
process simpleSum {
    input:
    val x

    exec:
    log.info "Hello Mr. $x"
}
```

**Comment by dennishendriksen** [comment]
@pditommaso I'm new to Nextflow and it took me quite some time to figure out how to log information for debugging purposes while tinkering on my first scripts (up to the point that I almost gave up on Nextflow). Using `log.info` instead of `println` solved the issue. I think updating the documentation would be valuable for new users like me.

**Comment by pditommaso** [comment]
Thanks for pointing this out again. I found a solution to this problem. I'll include it in the next release.
