### ISSUE TITLE
store .nextflow cache to s3 workbucket

### ISSUE THREAD

**Issue by lijingya** [nextflow-io/nextflow#1622]
Hi 
       I am using awsbatch to process my data. I found if my aws clock watch terminate my EC2 once Nextflow process stopped, I could not resume the previous unfinished process any more. I assume the resume function require .nextflow log. If so, is it possible to also upload the .nextflow cache to s3? 

Thanks

**Comment by pditommaso** [comment]
Use [Nextlow Tower](https://tower.nf/) if you need to preserve caching when using cloud execution.
