### ISSUE TITLE
Nextflow trace should use the full task hash 

### ISSUE THREAD

**Issue by marcadella** [nextflow-io/nextflow#1623]
Nextflow trace contains hashes looking like `e9/b2485e` instead of the full hash (corresponding to the path where the task is executed for instance `e9/b2485e3df67811aaed21225200ee2b`).  
This makes it awkward to explore the outputs/stdout of a task since one has to cd into `e9`, then find all the directories starting with `b2485e` and hope that there will be only one match...

Since we are at it, what is the point of the slash? Is it a legacy thing? It doesn't seem necessary and is a bit confusing.

**Comment by pditommaso** [comment]
I've realized that was documented, however, there's a `workdir` field that allows there retrieval of the task execution directory.

**Comment by marcadella** [comment]
I tried to add `println "$workflow.workdir"` in my main.nf (written in DSL2), but I get `Unexpected error [StackOverflowError]`
