### ISSUE TITLE
Pipeline silently exits if emit does not exist (DSL2)

### ISSUE THREAD

**Issue by marcadella** [nextflow-io/nextflow#1628]
## Bug report 

Assuming a process defined as:
```
process Foo {
  ...
  output:
    path 'foo', emit: foo
}
```
and a workflow defined as:
```
workflow Bar {
  emit:
    bar = Foo.out.foo2 //Instead of Foo.out.foo
}
```

then instead of returning an error message saying that `foo2` does not exist, the nextflow silently exits.

### Environment 

* Nextflow version: 20.04.1.5335
* Java version: 1.8.0_252
* Operating system: Linux
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by pditommaso** [comment]
Unable to replicate. The error message `No such variable: foo2` is reported.
