### ISSUE TITLE
publishDir does not overwrite symlinks

### ISSUE THREAD

**Issue by pauca** [nextflow-io/nextflow#163]
The directive "publishDir '/some/path' , mode: 'symlink', overwrite: true " does not overwrite the symlink when pipeline is re-runed and java.nio.file.FileAlreadyExistsException is raised

Example:

file nf.nf :
```
c1 = Channel.from("file.txt")
process p1{
    publishDir '/some/path' , mode: 'symlink', overwrite: true  
    input:
        file c1

    output:
        file c2

    script:      
        c2 = "file2.txt"
        """
        cp $c1 $c2
        """
}

```
nexflow nf.nf
N E X T F L O W  ~  version 0.19.1
Launching nf.nf
[warm up] executor > local
[95/a41e92] Submitted process > p1 (1)

/nextflow  nf.nf
N E X T F L O W  ~  version 0.19.1
Launching nf.nf
[warm up] executor > local
[95/a41e92] Cached process > p1 (1)
ERROR ~ Error executing process > 'p1 (1)'

Caused by:
  /file2.txt

**Comment by pditommaso** [comment]
Fixed in version `0.19.2`
