### ISSUE TITLE
process finishes with exitcode 0 when there is an error but several outputs are redirected

### ISSUE THREAD

**Issue by dgarrimar** [nextflow-io/nextflow#1631]
## Bug report 

It seems that when a script fails but its output is redirected together with others, the overall exitcode may be associated only with one of the commands. I believe this is a `bash` [issue](https://unix.stackexchange.com/questions/217605/bash-how-to-propagate-errors-in-process-substitution), rather than a `nextflow` issue, but it may give trouble to some users.

### Steps to reproduce the problem
```
.
|── bin
│   └── test.sh
└── test.nf
```
* `test.sh`
```bash
#!/bin/bash

madeupcommand
```
* `test.nf`
```
process foo {

    output:
    file("out.txt") into out_ch

    script:
    """
    paste <(echo "Testing...") <(test.sh) > out.txt
    """
}
```

### Program output 

```
$ ./bin/test.sh
bin/test.sh: line 3: madeupcommand: command not found
```
```
$ nextflow run test.nf
N E X T F L O W  ~  version 20.04.1
Launching `test.nf` [silly_baekeland] - revision: e66ee1a098
executor >  crg (1)
[35/7df1da] process > foo [100%] 1 of 1 ✔
```

```
$ cat work/35/7df1da09d5b100249cb4ee004d2586/.command.err
[...]/bin/test.sh: line 3: madeupcommand: command not found
```
```
$ cat work/35/7df1da09d5b100249cb4ee004d2586/.exitcode
0
```

### Environment 

* Nextflow version: 20.04.1
* Java version: 1.8.0_131
* Operating system: Linux
* Bash version: 4.2.46(1)

**Comment by pditommaso** [comment]
Yeah, this is expected: 

```
» paste <(echo "Testing...") <(test.sh) > out.txt
-bash: test.sh: command not found
» echo $?
0
```

To prevent that, prepend your script with `set -o pipefail`. 👍

**Comment by emi80** [comment]
In this case `set -o pipefail` is not helping. I think it is because the bash process substitution runs in a subshell. As answered [here](https://unix.stackexchange.com/questions/217605/bash-how-to-propagate-errors-in-process-substitution), adding `|| kill $$` works.

I think this is quite a bad one, but nothing can be done on Nextflow side to avoid it. It is responsibility of the pipeline developer to code the script correctly.

**Comment by emi80** [comment]
Reopened to go on with the discussion a little bit :smile:

**Comment by pditommaso** [comment]
Good! find a proper solution 😄
