### ISSUE TITLE
Allow user to specify CPU platform in Google Cloud Platform

### ISSUE THREAD

**Issue by hnawar** [nextflow-io/nextflow#1632]
## New feature

When using Google Cloud Life Sciences Executor, user should be able to specify the CPU platform
(What's the main usage case and the deployment scenario addressed by this proposal)
Some tasks would run much faster on Skylake as opposed to Haswell. It would be useful to be able to specify minimum CPU platform for N1 instances

## Suggest implementation 

(Highlight the main building blocks of a possible implementation and/or related components)
The   "cpuPlatform": string parameter that is part of the VM object in the pipeline API allows you to specify the CPU platform, this should be as simple as adding an additional flag

**Comment by pditommaso** [comment]
Solved by afc4375. #1633.
