### ISSUE TITLE
How to use collectFile with a tuple

### ISSUE THREAD

**Issue by marcadella** [nextflow-io/nextflow#1634]
Given a channel containing tuples [id, path], how to use `collectFile` to generate a file with the content of the paths sorted using the id?
Had there been an operator `sort` I would have used it to create a channel of path sorted by id, but it doesn't look there is any (other than `toSortedList`).

**Comment by mahesh-panchal** [comment]
`collectFile` has a `sort` parameter which you can pass a closure to sort your input.
https://www.nextflow.io/docs/latest/operator.html#collectfile

So perhaps something like:
```
id_tuple_ch.collectFile( name:'files.txt', sort: { it[0] ) { it[1] }
```

**Comment by gnxsf** [comment]
This sort strategy is very useful! How can I use the basename of the split files to name the collected file? Adapting from the example in the documentation, I've tried:
```
id_tuple_ch
.collectFile(sort: { it[0] }){ ["${it[1].getBaseName(2)}.txt", it[1] + '\n'] }
```
but I get an error: ```ERROR ~ No such file or directory```

**Comment by mahesh-panchal** [comment]
Please ask the question on the [Seqera community forum](https://community.seqera.io/). It would be useful to describe in more detail what's going into the channel, and the output you would like to be formed.

**Comment by gnxsf** [comment]
Thank you for your suggestion. I've posted it [here](https://community.seqera.io/t/how-can-i-dynamically-name-collectfile-output-based-on-input-file/641).

**Comment by robsyme** [comment]
[Responded](https://community.seqera.io/t/how-can-i-dynamically-name-collectfile-output-based-on-input-file/641/2?u=robsyme_seqera)
