### ISSUE TITLE
How to use `publishDir` on a workflow output?

### ISSUE THREAD

**Issue by marcadella** [nextflow-io/nextflow#1636]
It is possible to use `publishDir` in a process, but it doesn't seem possible to publish a workflow output channel (DSL2).

**Comment by marcadella** [comment]
Why has workflow publish feature been depreciated? That was exactly what I needed.

**Comment by elowy01** [comment]
The same issue here

**Comment by aegaskin** [comment]
Commenting to keep updated on this!

**Comment by aegaskin** [comment]
I've just learned that `publishDir  ${task.process}, pattern: "", mode: 'copy'` publishes named process outputs, with the directory structure `workflow:subworkflow:process` - but I'm open to suggestions and improvements!

**Comment by cjw85** [comment]
I too am wondering this. (See also https://github.com/nextflow-io/nextflow/issues/1540)

After https://github.com/nextflow-io/nextflow/commit/1bd7b4a4b38d69df28e64f3030fa4036caafee40 its not possible to use `publish:`:

    cause: Workflow 'publish' is not supported anymore use process 'publishDir' instead

Its not clear to me how to use `publishDir` without writing another process dedicated to output; that seems wasteful as it good lead to extra cluster jobs, starting containers, etc. etc..

**Comment by cjw85** [comment]
@pditommaso 

I've found comments in gitter from Apr 2020 stating that creating a publishDir in process is the only way to publish files for now, but that "the plan is to have a more flexible mechanisms later".

Are there any timelines on that?

**Comment by mjhipp** [comment]
I am also interested in this feature.
