### ISSUE TITLE
Odd behaviour from nextflow config -a

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#1639]
## Bug report 

I'm trying to use the much maligned `nextflow config` to find information about config profiles and came across this option which sounded perfect:

```
    -a, -show-profiles
       Show all configuration profiles
       Default: false
```

However, running it did not work as expected.

### Expected behavior and actual behavior, steps to reproduce the problem

I was hoping that this would show the config profiles, so that I can offer them to the end user in the `nf-launch` GUI.

However, trying to run `nextflow config -a` on a @nf_core pipeline gives this:

```console
$ nextflow config -a nf-core/rnaseq
ERROR: Environment variable NXF_GLOBAL_CONFIG is missing. Set it to point to global.config file.
WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
No such file: Config file does not exist: https://raw.githubusercontent.com/nf-core/configs/master/conf/conf/test.config
```

* Google has never heard of `NXF_GLOBAL_CONFIG` so I'm not sure what that is.
* The remote URL for the profiles is fine and works normally when running pipelines.
* Running `nextflow config` without the `-a` flag works normally.
* Using `-show-profiles` gives the same behaviour as `-a`.
* Using a local repository instead of remote gives the same behaviour

### Environment 

* Nextflow version: `20.05.0-edge build 5365`
* Java version: `build 1.8.0_144-b01`
* Operating system: macOS
* Bash version: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)`

**Comment by ewels** [comment]
My apologies - I just tracked down where this was coming from and it's nf-core specific (see [code](https://github.com/nf-core/configs/blob/bb7f67e2b556e1deda34b51799d654603d9c8c9f/conf/bi.config#L10-L18)).

Nextflow telling me `No such file: Config file does not exist` was a bit of a red herring, but I think that Nextflow is probably not doing anything wrong here. I'll keep having a play..

Sorry for the spam!

**Comment by pditommaso** [comment]
Hi Phil, yes, I've noticed the same issue when launching nf-pipelines with Tower because it uses the same mechanism to validate the profile names. Let me know if it can be improved on NF side.

**Comment by ewels** [comment]
Moved to a nf-core/configs issue, see nf-core/configs#162 👈
