### ISSUE TITLE
nxf_pstat  printf has extra zero

### ISSUE THREAD

**Issue by pauca** [nextflow-io/nextflow#164]
https://github.com/nextflow-io/nextflow/blob/75006c8369d2fbf6cf5c408b430553a427cae364/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy#L158

it looks like there is an extra Zero in
"%d 0 %.0f

**Comment by pditommaso** [comment]
This is a bit tricky. That row aggregate the processes stats, since the second column contains the process PID is set to `0` by design.
