### ISSUE TITLE
Optional input staging on AWS fails

### ISSUE THREAD

**Issue by apeltzer** [nextflow-io/nextflow#1645]
## Bug report 

We've been using this here https://github.com/nextflow-io/patterns/blob/master/docs/optional-input.adoc to supply optional input files in both nf-core/eager and nf-core/viralrecon recently and this code works fine using local HPC.

### Expected behavior and actual behavior

 Running on Github Actions with docker + local executor works fine too, but on AWS we see errors like this one:

```
Error executing process > 'MAKE_SNPEFF_DB (GCA_009858895.3_ASM985889v3_genomic.200409.fa)'
56Caused by:
57  Can't stage file file:///NO_FILE -- file does not exist
58Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
59Execution cancelled -- Finishing pending tasks before exit
```

### Steps to reproduce the problem

1.) pick one pipeline (eager, viralrecon).
2.) run (e.g. using tower):

`nextflow run 'https://github.com/nf-core/viralrecon.git' -name cranky_wilson -with-tower -r 1.0.0 -profile test_sispa --gff false` 

3.) See error that `file:///NO_FILE` cannot be staged. 

(Provide a test case that reproduce the problem either with a self-contained script or GitHub repository)

### Program output 

(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)

### Environment 

* Nextflow version: 20.05-edge
* Java version: (using Tower)
* Operating system: Linux, I assume (using tower)
* Bash version: (see above, using tower).

**Comment by apeltzer** [comment]
Might be related to  https://github.com/nextflow-io/nextflow/issues/1233

**Comment by apeltzer** [comment]
<img width="797" alt="Bildschirmfoto 2020-06-23 um 17 27 17" src="https://user-images.githubusercontent.com/2359510/85423288-cdb23c80-b576-11ea-80ee-0dc143b2b0d4.png">

**Comment by apeltzer** [comment]
Please let me know if you need more info!

**Comment by pditommaso** [comment]
The optional sentinel file name should contain a S3 path with an a valid bucket name. eg 

```
params.filter = 's3://<PUT YOUR BUCKET HERE>/NO_FILE'
``` 

I know, it's ugly..

**Comment by apeltzer** [comment]
Hm, so I have to tune it for AWS? I'm just thinking that this might break it locally then or is specifying something on s3 just enough?

**Comment by jfy133** [comment]
I agree, this is a bit scary because we can't then tell people making their own AWS profiles that they _need_ it to be set to that...

**Comment by apeltzer** [comment]
We solved it by just using a file that we already had for users (`where_is_my_file.txt`) and staging that from `$baseDir/assets/where_is_my_file.txt`). This worked locally and on AWS :-)

**Comment by ArlindNocaj** [comment]
@apeltzer can you provide an example snippet or more details how you solved it?  How does the file get to `$baseDir/assets/` ?

**Comment by apeltzer** [comment]
See in nf-core template how we solved it 👍 sorry just on mobile right now
