### ISSUE TITLE
accelerator directive limited to GPUs in k8s

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#1647]
## New feature

The [accelerator directive](https://www.nextflow.io/docs/latest/process.html?highlight=accelerator#accelerator) is limited to using GPUs in k8s. Other hardware resources that aren't GPUs (e.g. fpga) either can't be accessed or need to be erroneously identified as GPUs. This is because of [this line](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy#L409).

## Usage scenario 

Not sure how TPUs are identified, but we definitely don't want to identify [DRAGEN fpgas](https://www.illumina.com/products/by-type/informatics-products/dragen-bio-it-platform.html) as GPUs. 

## Suggest implementation 

This is tricky depending on how much backwards compatibility we want to maintain.

First option would just be to delete [this line](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy#L409). This would obviously break pipelines that depend on this feature.

A second option would be to add another key to the accelerator map, maybe `exact_type`, that if specified overrides the `type` key.  

A third option would be to add a `dont_make_assumptions` boolean to the accelerator map that allows `type` to be used directly instead of doing all of [this stuff](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy#L406-L409).

Please weigh in on which option you'd prefer and I'll submit a patch!

**Comment by pditommaso** [comment]
Can you help to make an assessment of possible values of accelerator type identifiers supported by K8s? At the time it was implemented I remember only GPU was documented and therefore that suffix was hardcoded.

**Comment by mes5k** [comment]
Right, so the k8s device plugins you linked to are exactly what we're using to make the DRAGEN fpga a schedule-able resource in k8s. Device plugins are named [according to this](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-registration).  We were thinking of using `illumina.com/dragen-fpga` or something similar.

In the [device plugin examples](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#examples) you can see other examples that don't use an gpu suffix: [fpgas](https://github.com/Xilinx/FPGA_as_a_Service/blob/master/k8s-fpga-device-plugin/server.go#L33) or [rdma](https://github.com/hustcat/k8s-rdma-device-plugin/blob/master/server.go#L17).  Actually the Xilinx example is a bit misleading, because elsewhere in the code they further mangle the identifier by adding date and build info (often necessary for fpgas). 

In an ideal world I'd just want Nextflow to take a `type` name and pass it through to k8s unmodified and then it's on the user to get the resource name correct.  Of course, I understand that people already have code written to expect `/gpu` so you won't want to break that.  I'm open to ideas.  I just don't want to have to hack my device plugin and call it a gpu when it's not.  :)

**Comment by pditommaso** [comment]
I think it's fair to assume if there isn't any `/` it can fall back to the `/gpu` suffix, otherwise, the full resource accelerator has to be specified. What do you think ?

**Comment by mes5k** [comment]
Good idea!  Use the unmodified `type` if it includes a `/` otherwise use the existing logic.  I'll put together a patch!

**Comment by pditommaso** [comment]
Does Aws Batch and/or Google LS provide support for Dragen accelerator?

**Comment by mes5k** [comment]
DRAGEN runs in AWS on their [f1 instances](https://aws.amazon.com/ec2/instance-types/f1/).  I'm not aware of any support at Google.

**Comment by pditommaso** [comment]
I was just wondering if something should be done to support it on Batch. But I would say that's fine 

https://github.com/nextflow-io/nextflow/blob/624c8e83bb110dce1a210f2c5a1c4c563e9e477f/modules/nextflow/src/main/groovy/nextflow/executor/res/AcceleratorResource.groovy#L31-L62

**Comment by mes5k** [comment]
Agreed, AcceleratorResource itself looks fine.  I think we'd handle different [ResourceRequirement](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/batch/model/ResourceRequirement.html) names with profiles depending on how Batch exposes DRAGEN.  At the moment I think we'd control this with different job queues in Batch.  But this is speculation - I haven't experimented.

**Comment by pditommaso** [comment]
Ok, closing. I'll include this into the next release.
