### ISSUE TITLE
Let Nextflow handle sample metadata in PEP format

### ISSUE THREAD

**Issue by nsheff** [nextflow-io/nextflow#1651]
## New feature: PEP compatibility

I would like to request Nextflow to read projects in PEP format. Portable Encapsulated Projects (PEP for short) seeks to make datasets and related software more portable and reusable. PEP does this by providing metadata standarization, metadata validation, and portability modifiers.

## Usage scenario 

Right now, there is no standard way to represent metadata that spans projects and tools. Each dataset is typically annotated in a unique way, and each pipeline, including Nextflow pipelines, typically expects a unique format for sample annotation. This restricts the portability and reusability of annotated datasets and software that processes them.

If Nextflow and other tools all agreed upon a shared standard way to represent metadata, it would make it much easier to apply multiple pipelines to the same project with less data munging, even if the tools are written with different systems and languages.

## Suggest implementation 

PEP APIs have already been written in [Python](https://pypi.org/project/peppy/) and [R](https://cran.r-project.org/web/packages/pepr/index.html). I believe we may need to implement this in groovy, and then adapt Nextflow to use it so that it could read in PEP projects.

You can read further details on what PEP adds in the documentation at [http://pep.databio.org/](http://pep.databio.org/)

**Comment by pditommaso** [comment]
Could you provide a *hello world* style example for PEP format?

**Comment by nsheff** [comment]
> Could you provide a hello world style example for PEP format?

Sure, a [very basic example](https://github.com/pepkit/example_peps/tree/master/example_basic) consists of 2 files, which here describe 2 "samples", each with a data file:

1. `project_config.yaml`

```
pep_version: "2.0.0"
sample_table: sample_table.csv
```


2. and `sample_table.csv`:

```
sample_name,protocol,file
frog_1,anySampleType,data/frog1_data.txt
frog_2,anySampleType,data/frog2_data.txt
```

This example doesn't do much; it's basically nothing more than a simple csv annotation file, but it works just fine as a basic PEP.  From here you can add whatever more powerful features you like. For example, you can use a [derive sample modifier](http://pep.databio.org/en/latest/specification/#sample-modifier-derive) to make the paths portable as shown in the [basic derive example](https://github.com/pepkit/example_peps/tree/master/example_derive):


1. `project_config.yaml`
```
pep_version: "2.0.0"
sample_table: sample_table.csv
output_dir: "$HOME/hello_world_results"

sample_modifiers:
  derive:
    attributes: [file_path]
    sources:
      source1: $HOME/data/lab/project/{organism}_{time}h.fastq
      source2: /path/from/collaborator/weirdNamingScheme_{external_id}.fastq
```

2. and `sample_table.csv`:

```
sample_name,protocol,organism,time,file_path
pig_0h,RRBS,pig,0,source1
pig_1h,RRBS,pig,1,source1
frog_0h,RRBS,frog,0,source1
frog_1h,RRBS,frog,1,source1
```

This project can be moved to a different computing environment without changing the annotation table, which can therefore now be re-used across analyses, computing environments, and tools. There are lots of other features like [project imports](http://pep.databio.org/en/latest/specification/#project-modifier-import), [implied attributes](http://pep.databio.org/en/latest/specification/#sample-modifier-imply), and a [metadata validation framework](http://pep.databio.org/en/latest/howto_validate/) based on JSON-schema.

**Comment by johanneskoester** [comment]
Hey Paolo! For Snakemake, we already have a prototype implementation: https://github.com/snakemake/snakemake/pull/451

Would be great if both systems would support it! This way, data+metadata could be quickly exchanged between snakemake and nextflow pipelines, without the need to adapt anything.

Also cc'ing @naepfel.

**Comment by johanneskoester** [comment]
The format itself is very close to what we have for snakemake since a very long time. YAML for the global structured metadata, csv/tsv for samples, and sequencing units/subsamples. In my experience, it covers everything needed to describe a sequencing experiment.

**Comment by pditommaso** [comment]
I agree, @ewels @drpatelh anybody in the nf-core community interested to give a try, happy to advise.

**Comment by naepfel** [comment]
That is cetainly a good idea. We don't use is so far, but it did attract our attention - not only in the context of workflows

**Comment by oddodaoddo** [comment]
Hello. I will take a crack at this. I have Java skills but not Groovy. From a cursory look at the code, this would be implemen ted in Groovy, yes? Where do I start (as in, being new to Nextflow)? I am assuming there is some portion of the codebase that deals with/allows for adding in logic to support some kind of a pipeline definition format? What would be the place to start looking? :)

**Comment by pditommaso** [comment]
Hi, currently that channel factories logic is defined in the `Channel` class as static method as entry point that delegates the implementation to a specific class. See the `Channel.fromSra` method as an example: 

https://github.com/nextflow-io/nextflow/blob/e94e6877c2dc9bed983e873b62e302a08843c891/modules/nextflow/src/main/groovy/nextflow/Channel.groovy#L586-L609

I think the most complex part is to understand how to fit the PEP format into the NF model based on channel that at the end is a kind of asynchronous tabular schema.

**Comment by oddodaoddo** [comment]
Thank you, it's a good start for me to study and understand. I will be back with more questions.

**Comment by nsheff** [comment]
Can't groovy load java objects?

**Comment by pditommaso** [comment]
A groovy object *is* a java object. If you mean `import Something`, yes, the same as you would do in Java.

**Comment by oddodaoddo** [comment]
I think @nsheff  question is whether the code addition to handle PEP is going to be in Groovy or in Java, correct?

**Comment by pditommaso** [comment]
It would preferable to have it in groovy.

**Comment by oddodaoddo** [comment]
That's what I thought. Thanks!

**Comment by nsheff** [comment]
One approach would be to write a generic tool in Java and then it can be used in Java/Groovy/Scala. Then you would need only some minimal groovy wrappers to use those Java objects, right?

**Comment by pditommaso** [comment]
It could be a possible approach. 👍

**Comment by ewels** [comment]
Hi all! Any progress on a native Java / groovy implementation for a Nextflow Channel generator from PEP files? We're getting closer to having a stab at an implementation of this soon (either Nextflow PR or a pipeline / process workaround) and want to check in to see if anyone has made progress first.

**Comment by nsheff** [comment]
@ewels Here's where we are: https://github.com/pepkit/pepjava

**Comment by nsheff** [comment]
Just to put a note about latest movement in this area:

We now have a new concept called 'eido filters' 

http://eido.databio.org/en/latest/filters/

You can use `eido convert` to convert from one format to another. To see this in practice

```
eido convert https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/samplesheet/v3.1/samplesheet_test.csv -f yaml-samples --st-index sample 
```

Here' we're taking a csv file and converting it into a yaml file.

You can also write a custom filter, so you can get whatever output format you want: http://eido.databio.org/en/latest/writing-a-filter/

So the upshot is... whatever input format Nextflow already wants to read could be accommodated through an eido filter.

**Comment by abhi18av** [comment]
I noticed that there's a java library already for PEP, perhaps this might be a good candidate for a plugin `nf-pep` instead of adding directly to NF? 

Reference: https://www.nextflow.io/docs/edge/plugins.html

**Comment by pditommaso** [comment]
Closing this because it never materialised. Happy to reconsider if somebody in the community is willing to contribute it.

**Comment by bentsherman** [comment]
In case anyone ever does want to revive this effort... it would probably be a good fit for the [nf-prov](https://github.com/nextflow-io/nf-prov) plugin
