### ISSUE TITLE
Invalid GLS path composition in staging directories

### ISSUE THREAD

**Issue by hnawar** [nextflow-io/nextflow#1654]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

Using path as an output for a folder and as an input for the next step. The folder should be copied to the VMof the next process
instead the piepline fails with an error
### Steps to reproduce the problem

(Provide a test case that reproduce the problem either with a self-contained script or GitHub repository)
This happened in step 3 of scflow
https://github.com/combiz/nf-core-scflow

### Program output 

+ cd /[redacted]/fe/0cd4677e6b0d3fe3cd00b1ef31c1d4
+ gsutil -m -q cp gs://[redacted]/[redacted]/fe/0cd4677e6b0d3fe3cd00b1ef31c1d4/.command.run .
+ bash .command.run nxf_stage
CommandException: No URLs matched: gs://[redacted]/[redacted]/c5/a34546b98fea695400c94b695ed7a5/tipif_sce//
CommandException: 1 file/object could not be transferred.

### Environment 

* Nextflow version: 20.04.1
* Java version: [?]
* Operating system: [macOS, Linux, etc] linux
* Bash version: (use the command `$SHELL --version`)

### Additional context
Google Life Science Executor

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Solved e33fff98.
