### ISSUE TITLE
Allow to specify custom location of scm file using environment variable

### ISSUE THREAD

**Issue by zichner** [nextflow-io/nextflow#1657]
## New feature

Currently, the scm file needs to be located at `~/.nextflow/scm`. However, it would be nice to be able to store this file somewhere else and to specify its location via an environment variable.

## Usage scenario 

In a setting with many users that all need to have the same scm configuration, each user needs to copy the scm file from some central location to his/her home directory. This increases the hurdle to use pipelines and is also a source of errors (e.g., if the central file is updated but not every user updated his/her local file). Being able to have one scm file in a central location and setting an environment variable pointing to this would help a lot in this scenarios.

Thank you very much!

**Comment by pditommaso** [comment]
What about using an environment var instead of CLI options. I feel could be more useful to consolidate the config in a specific environment.

**Comment by pditommaso** [comment]
Solved

**Comment by zichner** [comment]
Great. Thank you very much!
