### ISSUE TITLE
Running two nextflow instances on the same machine

### ISSUE THREAD

**Issue by r0f1** [nextflow-io/nextflow#1660]
Hi, 
consider the following scenario. You have a `main.nf` file where you define 3 processes which are daisy chained: The output of the first process is piped to the second. The output of the second process is piped to the third. The first process takes some arguments, let's call them `arg1` and `arg2` and the user supplies those arguments. You start a screen session using the unix command `screen` and then type:
```
nextflow run main.nf --arg1 foo --arg2 bar
```
You exit the current screen session, and open a new one and type:
```
nextflow run main.nf --arg1 bla --arg2 blo
```
Here is my issue: Sometimes (not always though) one of the nextflow instances fails. Could it be that the two nextflow instance somehow interfere with each other?

I tested this with the local executor and with the google-lifesciences executor and I have the issue in both cases. The output of the google-lifesciences executor looks like this:
```
...
Command exit status:
  14
Command output:
  (empty)
Command error:
  Execution failed: worker was terminated
...
```

**Comment by pditommaso** [comment]
I think the execution is terminated because the session is killed. You should run NF using the `-bg` cli options.

**Comment by r0f1** [comment]
Thanks for your answer, but I don't think that this is the issue. I think have the feeling that something with the pipes between the processes and instances goes wrong. When I start the first instance and wait a little while until it has arrived at its third process and then I start the second instance everything works out fine.
However, when I start two instances immediatelly after each other and both instances try to enter, say, their second process, one of them fails. Or when I start two instances in close proximity and the one that was started later catches up with the one that was started earlier, the one that was started later fails.

**Comment by pditommaso** [comment]
Need a test case that replicates the issue.

**Comment by r0f1** [comment]
Sorry, I could not replicate the issue. I am closing this and will reopen another issue once I have figured out how to reliably reproduce it.
