### ISSUE TITLE
fixOwnership causes containers without `ps` to fail.

### ISSUE THREAD

**Issue by xihh87** [nextflow-io/nextflow#1663]
# Bug report 

### Expected behavior and actual behavior

When I activated the fixOwnership option a workflow that ran correctly the workflow failed.

The option fixOwnership should not affect anything other than the ownership of the files and should not be a cause of failure.

### Steps to reproduce the problem

-   Unzip bugreport.zip
-   Run ./setup on the directory.
-   Test both works and does-not-work scripts.

I kept the logs of both my successful and unsuccessful runs so they can be inspected.

[bugreport.zip](https://github.com/nextflow-io/nextflow/files/4866004/bugreport.zip)

### Program output 

```
Command error:
  Command 'ps' required by nextflow to collect task metrics cannot be found
```
[.nextflow.log](https://github.com/nextflow-io/nextflow/files/4865769/default.nextflow.log)

### Environment 

* Nextflow version: nextflow version 20.04.1.5335
* Java version:
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
* Operating system: Linux
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
* Bash version: GNU bash, versión 5.0.16(1)-release (x86_64-pc-linux-gnu)

### Additional context

It seems that the container I use does not include `ps` but the problem does not manifest on a default run.

Nextflow should not require to run the containers as root as that can be abused by a malicious actor.

fixOwnership seems to run the container as root.

The following configuration works as intended:

```
docker {
        enabled = true
        fixOwnership = false
        runOptions = "--user 1000:1000"
}
```

Maybe consider deprecating fixOwnership in favor of running by default with the uid:gid of the current user.

**Comment by pditommaso** [comment]
The `ps` tool is a required dependency.

**Comment by PhilippeNoel1** [comment]
Sorry to reopen this, but I occur the same behaviour and I don't understand why.

If I use `fixOwnership = true`, then `ps command` is required in the container.
With `fixOwnership = false`, I don't need `ps command`. I don't understand why this is a requirement
