### ISSUE TITLE
Problem with outputs in nested workflows DSL2

### ISSUE THREAD

**Issue by edgano** [nextflow-io/nextflow#1667]
### Expected behavior and actual behavior

Problems when the outputs of nested workflows, ```Unknown workflow parameter definition```

### Steps to reproduce the problem

It can be reproduced with the CL

```nextflow run edgano/nf_regressive_modules/main_reg_prog.nf -profile test,docker```

On regressiveAnalysis.nf, 
```
workflow ALIGN_REG {
    take:
        seqs_and_trees
        align_method
        tree_method
        bucket_size

    main:
        align_method = align_method.toString().replace("[", "").replace("]", "")
        println align_method    

        if (align_method == "CLUSTALO"){
            REG_CLUSTALO(seqs_and_trees, bucket_size)

            reg_alignment_method = REG_CLUSTALO.out.alignMethod
            reg_tree_method = REG_CLUSTALO.out.treeMethod
            reg_alignmentFile = REG_CLUSTALO.out.alignmentFile
            reg_bucket = REG_CLUSTALO.out.bucketSize
            reg_homoplasy = REG_CLUSTALO.out.homoplasyFile
            reg_metrics = REG_CLUSTALO.out.metricFile
            flavour = "regressive"
        }    
        reg_alignmentFile.view()

    emmit:  
        reg_alignmentFile
}
workflow REG_ANALYSIS {
  take:
    seqs_and_trees
    refs_ch
    align_method
    tree_method
    bucket_size
    
  main: 
        ALIGN_REG(seqs_and_trees,align_method,tree_method,bucket_size)
        
        //ALIGN_REG.out.reg_alignmentFile.view()
        
}
```
The ```ALIGN_REG.out.reg_alignmentFile.view()``` rise the error.  But inside the ALIGN_REG, the ```reg_alignmentFile.view()``` works as expected.

### Program output 
[nextflow.log](https://github.com/nextflow-io/nextflow/files/4883889/nextflow.log)
### Environment 

* Nextflow version: 20.04.1.5335
* Java version: 11.0.6
* Operating system: macOS
* Bash version: zsh 5.7.1

**Comment by pditommaso** [comment]
`emmit:` ?
