### ISSUE TITLE
file path manip

### ISSUE THREAD

**Issue by huguesfontenelle** [nextflow-io/nextflow#167]
The following snipset
```
bam = new File("/data/NA12882.bam")
bai = new File(bam.absolutePath.split('\\.')[0] + '.bai')
println(bai)
```
works fine in the nextflow REPL

but not as part of a script where it throws:
```
N E X T F L O W  ~  version 0.19.3
Launching cnv.nf
[warm up] executor > local
Error executing process > 'my_process (2)'

Caused by:
  No such property: absolutePath for class: sun.nio.fs.UnixPath
```

**Comment by huguesfontenelle** [comment]
And of course here is the corresponding pipeline:
```
params.bam = "/data/NA12882.bam"
ch = Channel.fromPath(params.bam)

process loop {
    echo true

    input:
    file(bam_file) from ch

    script:
    sample_name = bam_file.name.split('\\.')[0]
    bai_file = new File(bam_file.absolutePath.split('\\.')[0] + '.bai')

"""
echo ${bam_file}
echo ${bai_file}
"""
}
```

**Comment by pditommaso** [comment]
Actually the use of `File` class is discouraged because it a legacy Java API and Nextflow uses `Path`. 

The above snippet can be written instead as shown below: 

    bam = file("/data/NA12882.bam")
    bai = file(bam.split('\\.')[0] + '.bai')
    println(bai)

or 
   
    bam = file("/data/NA12882.bam")
    bai = bam.parent / bam.baseName + '.bai'
    println(bai)

**Comment by pditommaso** [comment]
Also you won't be able to access the `bai_file` in the process in that way. Don't forget with nextflow you need to declare all the input files you need to access in your process. 

For example you can create a channel emitting both the bam and the bai files.

**Comment by huguesfontenelle** [comment]
Is there a typo in
```bai = file(bam.split('\\.')[0] + '.bai')``` ? Can't split a file.

Also you're right about the access to `bai_file`. I was trying to develop a small part of my pipeline in isolation, but it's not so easy

**Comment by pditommaso** [comment]
Oops .. sorry, `split` is a `String` method. Thus `file(bam.toString().split('\\.')[0] + '.bai')` 

I  would suggest to take in consideration the second example.

**Comment by pditommaso** [comment]
I'm closing this issue. If you are still having problems feel free to comment here.
