### ISSUE TITLE
container.envWhitelist

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#1673]
## New feature
Hi,
I'm wondering if a general container.envWhitelist could replace / integrate docker/singulairty.envWhitelist so that it is passed whatever is the container used (with -with-container option) 

Best,

**Comment by pditommaso** [comment]
Cozzutoflow != nextflow 😅

**Comment by lucacozzuto** [comment]
Cozzutoflow >> nextflow :)

**Comment by pditommaso** [comment]
Ok, the consensus is no 😄
