### ISSUE TITLE
DSL2: conda env file should be relative to module

### ISSUE THREAD

**Issue by grst** [nextflow-io/nextflow#1674]
## Bug report 
It should be possible to include a conda `environment.yml` file with a path relative to the module directory. 

### Expected behavior and actual behavior
Given the following folder structure: 
```
.
├── fastqc
│   ├── environment.yml
│   └── fastqc.nf
└── main.nf
```

 * `main.nf` is the main pipeline script. It imports a `FASTQC` process from `fastqc/fastqc.nf`. 
 * `fastqc/fastqc.nf` includes `conda "./environment.yml"`. 

When running `./main.nf` it fails with the following error message: 
```console
N E X T F L O W  ~  version 20.06.0-edge
Launching `./main.nf` [infallible_shaw] - revision: 48e8c91201
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
Error executing process > 'FASTQC'

Caused by:
  Conda environment file does not exist: ./environment.yml
```

### Steps to reproduce the problem

Full repex is here: https://github.com/grst/nextflow-import-repex

### Program output 

[.nextflow.log](https://github.com/nextflow-io/nextflow/files/4919684/default.nextflow.log)

### Environment 

* Nextflow version: 20.06.0-edge
* Java version: openjdk version "11.0.1-internal" 2018-10-16
* Operating system: Arch linux
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

The relative imports make a lot of sense from the perspective of the [nf-core/modules](https://github.com/nf-core/modules) initiative. Each module is atomic and declares its own software dependencies. They should resolve independently of the main workflow. 

CC @ewels, @drpatelh

**Comment by pditommaso** [comment]
You can use implicit moduleDir for that

**Comment by grst** [comment]
That works, thanks Paolo!
