### ISSUE TITLE
Error when parsing params starting with - or -- in quote

### ISSUE THREAD

**Issue by maxulysse** [nextflow-io/nextflow#1675]
## Bug report 

When submitting a params starting with `-` or `--` with quotes, Nextflow thinks it's a Nextflow option, or register it as true respectively. 

### Expected behavior and actual behavior

Actual:
```
≻ nextflow run MaxUlysse/nextflow_params_opt --opt "-foo" 
Unknown option: -foo -- Check the available commands and options and syntax with 'help'

≻ nextflow run MaxUlysse/nextflow_params_opt --opt "--foo"
N E X T F L O W  ~  version 20.05.0-edge
Launching `MaxUlysse/nextflow_params_opt` [reverent_bartik] - revision: 5aa15fb9f0 [master]
executor >  local (1)
[37/01f0a2] process > test [100%] 1 of 1 ✔
true
```
Expected:

```
≻ nextflow run MaxUlysse/nextflow_params_opt --opt "-foo"
N E X T F L O W  ~  version 20.05.0-edge
Launching `MaxUlysse/nextflow_params_opt` [reverent_bartik] - revision: 5aa15fb9f0 [master]
executor >  local (1)
[37/01f0a2] process > test [100%] 1 of 1 ✔
-foo

≻ nextflow run MaxUlysse/nextflow_params_opt --opt "--foo"
N E X T F L O W  ~  version 20.05.0-edge
Launching `MaxUlysse/nextflow_params_opt` [reverent_bartik] - revision: 5aa15fb9f0 [master]
executor >  local (1)
[37/01f0a2] process > test [100%] 1 of 1 ✔
--foo
```

Managed to have the expected behaviour using an `=`:
```
≻ nextflow run MaxUlysse/nextflow_params_opt --opt="-foo" 
N E X T F L O W  ~  version 20.05.0-edge
Launching `MaxUlysse/nextflow_params_opt` [deadly_chandrasekhar] - revision: 5aa15fb9f0 [master]
executor >  local (1)
[ce/d776c8] process > test [100%] 1 of 1 ✔
-foo

≻ nextflow run MaxUlysse/nextflow_params_opt --opt="--foo"
N E X T F L O W  ~  version 20.05.0-edge
Launching `MaxUlysse/nextflow_params_opt` [disturbed_mandelbrot] - revision: 5aa15fb9f0 [master]
executor >  local (1)
[c3/20ee15] process > test [100%] 1 of 1 ✔
--foo
```

### Steps to reproduce the problem

`nextflow run MaxUlysse/nextflow_params_opt --opt "-foo"`
`nextflow run MaxUlysse/nextflow_params_opt --opt "--foo"`

### Program output 

(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)

### Environment 

* Nextflow version: [20.05.0-edge] 
* Java version: [?]
* Operating system: [Linux Mint]
* Bash version: (use the command `zsh 5.4.2 (x86_64-ubuntu-linux-gnu)`)

### Additional context

(Add any other context about the problem here)

**Comment by MaxUlysse** [comment]
reproduced on `GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)`

**Comment by pditommaso** [comment]
I fear this is a .. feature! 😱

**Comment by pditommaso** [comment]
The `"` does nothing here, the quotes are not even passed to the NF runtime. 
 
<img width="473" alt="Screenshot 2020-07-16 at 18 14 24" src="https://user-images.githubusercontent.com/816968/87695926-6d3aa780-c790-11ea-92e9-002a140cf549.png">
 
The logic behind is that an option is followed by a -string, this sequence is interpreted as the following cli params, and the prevision as a boolean params flag implicitly true.

Cannot do anything, other than rewriting the CLI interpreter #556.

**Comment by MaxUlysse** [comment]
Issue still there in `20.11.0-edge`
```
≻ export NXF_VER=20.11.0-edge ; nextflow self-update

      N E X T F L O W
      version 20.12.0-edge build 5459
      created 12-12-2020 09:14 UTC (10:14 CEST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io


Nextflow installation completed. Please note:
- the executable file `nextflow` has been created in the folder: /home/maxime/bin

≻ nextflow run MaxUlysse/nextflow_params_opt --opt "-foo" 

Unknown option: -foo -- Check the available commands and options and syntax with 'help'

≻ nextflow run MaxUlysse/nextflow_params_opt --opt "--foo"

N E X T F L O W  ~  version 20.11.0-edge
Launching `MaxUlysse/nextflow_params_opt` [dreamy_mendel] - revision: 5aa15fb9f0 [master]
executor >  local (1)
[8e/a065c0] process > test [100%] 1 of 1 ✔
true
```
