### ISSUE TITLE
Add doi field to manifest attributes

### ISSUE THREAD

**Issue by MaxUlysse** [nextflow-io/nextflow#1676]
## New feature

It would be great to have doi in the manifest, so we can include that for tag released or anytime it's applicable.

## Usage scenario 

(What's the main usage case and the deployment scenario addressed by this proposal)

## Suggest implementation 

(Highlight the main building blocks of a possible implementation and/or related components)

**Comment by pditommaso** [comment]
Like it 👍

**Comment by pditommaso** [comment]
Done

**Comment by MaxUlysse** [comment]
Thanks a lot :-D
