### ISSUE TITLE
if else statement causes input value to go out of scope

### ISSUE THREAD

**Issue by jhrf** [nextflow-io/nextflow#1677]
[nextflow.log](https://github.com/nextflow-io/nextflow/files/4930895/nextflow.log)
## Bug report 

An if statement used to control the output directory of a process causes a process input value to be unrecognised by nextflow. 

I assume what is happening is that the if statement is somehow pushing the input `val` to be moved out of scope? 

It should be noted that I am using DSL2

### Expected behavior and actual behavior

Expected behaviour:

The if statement triggers successfully and output files are deposited to the correct directory specificed by `publishDir` 

Actual behaviour:

The program fails to run because the valid process input parameter cannot be found. An error is thrown.

### Steps to reproduce the problem

Notice how `process bar` is successfully compiled without an if statement, but the almost identical `process foo` throws an error. 

```
nextflow.preview.dsl=2

workflow {
    sample_id_channel = Channel.from('sample_id')
    input_file_channel = Channel.fromPath('./bar.txt')

    bar(input_file_channel, sample_id_channel)
    foo(input_file_channel, sample_id_channel)
}


process bar{
    
    publishDir "${sample_id}", mode: "copy"

    input:
        file input_file
        val sample_id

    """
    echo "Hello World!"
    """
}

process foo {

    if(true){
        publishDir "${sample_id}", mode: "copy"
    } else {
       publishDir "baz", mode: "copy"
    }

    input:
        file input_file
        val sample_id

    """
    echo "Goodbye World!"
    """
}
```

Command line:

```
nextflow run <path_to_script_above>
```

### Program output 

```
Launching `bug_report.nf` [trusting_ptolemy] - revision: 5714eb608f
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
[-        ] process > bar -
No such variable: sample_id

 -- Check script 'bug_report.nf' at line: 28 or see '.nextflow.log' file for more details

```
### Environment 

* Nextflow version: 20.04.1 build 5335
* Java version: openjdk version "1.8.0_152-release"
* Operating system: macOS 10.15.4
* Bash version: zsh 5.7.1 (x86_64-apple-darwin19.0)

### Additional context

None

**Comment by pditommaso** [comment]
The `publlishDir` should not be included within a condition statement. Use instead a conditional expression, eg. 

```
process foo {
    publishDir "${ true ? sample_id : 'baz' }", mode: "copy"
    input:
        file input_file
        val sample_id

    """
    echo "Goodbye World!"
    """
}
```
