### ISSUE TITLE
Workflow "bin" directory path not bound when using Singularity

### ISSUE THREAD

**Issue by Shellfishgene** [nextflow-io/nextflow#1679]
### Expected behavior and actual behavior

When using Singularity (with nf-core RNASeq for example) all processes that use scripts from ```/home/tb/.nextflow/assets/nf-core/rnaseq/bin``` fail with ```command not found```. AutoMounts is on (as set in the Singularity profile of nf-core RNASeq). The issue can be resolve by adding
```
runOptions = '-B /home/tb/.nextflow/assets/nf-core/rnaseq/bin'
```
to the config file Singularity scope.

Should nextflow not do this automatically? In the processes that use files from ```assets/nf-core/rnaseq/docs```  via a channel this works, the ```-B``` option to Singularity is set in ```.command.run``` for the docs directory as above, just not for bin.

In my case ```.nextflow``` and the directory the workflow runs in are on different file system (home/work), I don't know if that matters.

### Steps to reproduce the problem

```nextflow run nf-core/rnaseq -profile test,singularity -r 1.4.2 -c nextflow.config```

### Program output 

```.command.sh: line 2: markdown_to_html.r: command not found```

### Environment 

* Nextflow version: 20.04.1 build 5335
* Java version: openjdk version "11.0.1"
* Operating system: Linux
* Bash version: 4.2.46

**Comment by FriederikeHanssen** [comment]
I have the same error, when I run `sarek` on AWS. We set everything up using `Tower Forge` with FsX for Lustre as described in `help.tower.nf`. All processes are running through except for `output_documentation` and `get_software_version`. 

Pipeline version: 2.6.1
Config profile: test
Nextflow version (according to tower): 20.09.1-edge build 5428

I tried adding the following to the `Nextflow config file` field:

```
docker.runOptions = '--mount ~/.nextflow/assets/nf-core/sarek/bin'
```

and 

```
docker.runOptions = '--volume ~/.nextflow/assets/nf-core/sarek/bin'
```

Neither worked.
