### ISSUE TITLE
Is it possible to run Nextflow from a singularity container and then use it to run other local singularity containers?

### ISSUE THREAD

**Issue by ink-blot** [nextflow-io/nextflow#1680]
Hello.

Is it possible to run Nextflow from a singularity container and then use it to run other local singularity containers?

I'm testing this on our HPC login node for starters (ie not running a job on our PBS-Pro scheduler)

I can run a singularity container with gatk fine using the command:

```
singularity exec /scratch/daff/mw/gatk_singularity/gatk_latest.sif gatk -h
```

I've created a singularity container containing nextflow:
```
singularity pull docker://nextflow/nextflow
```

I've created a nextflow profile ('troubleshoot.config'):

```
profiles {
	foo {
		autoMounts = true
		docker.enabled = false
		singularity.enabled = true
		singularity.cacheDir = "$PWD"
		process.container = 'file:////scratch/daff/mw/gatk_singularity/gatk_latest.sif'
	}
}
```

I've created a nextflow script ('troubleshoot.nf'):

```
process gatk {
    """
	#!/bin/bash
	gatk -h >/scratch/daff/mw/gatk_snp_pipeline/out.txt
	#echo "=== ENVIRONMENT ===" >>/scratch/daff/mw/gatk_snp_pipeline/out.txt
	#echo `env` >>/scratch/daff/mw/gatk_snp_pipeline/out.txt
    """
}

```

I've tried launching the script above:

```
singularity exec --bind /scratch/daff/mw/nextflow_docker/volume,/sys/fs:/sys/fs /scratch/daff/mw/nextflow_docker/nextflow_latest.sif nextflow -C /scratch/daff/mw/gatk_snp_pipeline/troubleshoot.config run /scratch/daff/mw/gatk_snp_pipeline/troubleshoot.nf --profile foo 
```

I get the following output:
```
N E X T F L O W  ~  version 20.04.1-edge
Launching `/scratch/daff/mw/gatk_snp_pipeline/troubleshoot.nf` [crazy_keller] - revision: 62cf599126
executor >  local (1)
[f1/0cedf9] process > gatk [  0%] 0 of 1
Error executing process > 'gatk'

Caused by:
  Process `gatk` terminated with an error exit status (127)
executor >  local (1)
[f1/0cedf9] process > gatk [100%] 1 of 1, failed: 1 ✘
Error executing process > 'gatk'

Caused by:
  Process `gatk` terminated with an error exit status (127)

Command executed:

  #!/bin/bash
  gatk -h >/scratch/daff/mw/gatk_snp_pipeline/out.txt
  #echo "=== ENVIRONMENT ===" >>/scratch/daff/mw/gatk_snp_pipeline/out.txt
  #echo `env` >>/scratch/daff/mw/gatk_snp_pipeline/out.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: gatk: command not found

Work dir:
  /scratch/daff/mw/gatk_snp_pipeline/work/f1/0cedf92d83bb7d4f1a2662f6e65ef7

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

If I uncomment the 2 echo lines in the nextflow script the error disappears but still there is no output from gatk:

```
N E X T F L O W  ~  version 20.04.1-edge
Launching `/scratch/daff/mw/gatk_snp_pipeline/troubleshoot.nf` [backstabbing_ampere] - revision: dc6b552397
executor >  local (1)
[65/8871aa] process > gatk [100%] 1 of 1 ✔

```

Is what I'm trying to do impossible or is there some chance that I can change something to achieve this? I'm trying to avoid hassling my admin to install NextFlow.

Thanks for your help.

**Comment by pontus** [comment]
I'm not actually if it's possible or not, but that would be a non-suid version which might have other limitations that stops you.

Most of the users I've interfaced with have managed to install nextflow themselves (if you have a modern system with java installed, it will very likely be able to pull what it needs itself if the node is connected to the net).

Conda environments could possibly be another work around, but there are definitely problems with that, and I'd primarily recommend installing nextflow (either by yourself or ask your admins).

**Comment by pditommaso** [comment]
NF can run in a container as any other piece of software. The problem is the interaction with the batch scheduler once you ave containerized it. You should include also the batch scheduler client app in the container, which looks a bad idea.
