### ISSUE TITLE
Add ability to save file containing (final) resolved parameter configuration alongside trace reports

### ISSUE THREAD

**Issue by jfy133** [nextflow-io/nextflow#1682]
## New feature

The tower.nf functionality of seeing the final resolved parameter configuration is really useful for knowing exactly what settings were set - particularly when loading multiple different profiles (e.g. with nf-core configs, given instution-wide, pipeline-specific and personal settings can all be used). This can be particularly useful when writing methods sections of journal articles, when prose based descriptions are still required.

This is currently shipped to to tower (I believe) with the Weblog file.

Currently the only parameters that are reported in physical output files from the pipeline run (e.g. execution_report.html) is the command submitted by the user, and does not include any 'behind the scenes' resolved profiles.

Original gitter discussion started here: https://gitter.im/nextflow-io/nextflow?at=5f16ab06a15ff42fa8e08fc3

## Usage scenario 

Many users may not wish to use tower, and would rather keep this sort of data kept at a run level alongside their results files (possibly to report in run summary reports such as with MultiQC), rather than aggregated in one place (where old run names can be forgotten, and thus not findable, would occur if relying ontower.nf).

The specific information that would be useful is in the `params` block of the Weblog JSON e.g. here https://www.nextflow.io/docs/latest/tracing.html#weblog-started-example-message

## Suggested implementation 

This could either be saved as a standalone file, or integrated into the `execution_report.html`

**Comment by stevekm** [comment]
for this kind of functionality, I have typically been just printing the contents of `params` either to the console log (which gets saved with the output) or otherwise to a file. Example;

```
log.info("workflow params")
log.info("${params}")

**Comment by jfy133** [comment]
Oooh, I was not aware that was possible - thanks @stevekm. I might also use that for a different context as well!
