### ISSUE TITLE
Nextflow is suspending the process after generating a couple of outputs with "WARN: Killing pending tasks (1)" message

### ISSUE THREAD

**Issue by ranijames** [nextflow-io/nextflow#1688]
Hi All,

I have 24 vcf files in as my input files for the process `vep`. Here is my channel definition. When I execute my nextflow pipeline, it generates a couple of outputs for some inputs, and then suspend the run with the warning `WARN: Killing pending tasks (1)`
I am not sure what exactly is happening here. The inputs are not huge it is small files of size range between 152K-44M. Within the process, I have configured the memory and executor, 

```
  memory   '20 GB'
    executor 'local'
```
Here, is the channel for the input vcfs,

```
params.vcf ='/path/tofiles/'
Channel.fromPath("${params.vcf}/*.vcf").map { item ->
    def sampleID = "${item.getName()}".replaceFirst(/.vcf$/, "")
    return([sampleID, item])
}.set { input_vcfs }
```

 And here I  am calling the inputs in the process `vep` like this along with other inputs like references. The `input_vcfs` in 24 files.

```

process vep {
    tag "${sampleID}"
    publishDir "${params.outputDir}/VEP", mode: 'copy'
    memory   '20 GB'
    executor 'local'

    input:
       set val(sampleID), file(vcf),file(ref_dir),val(assembly),file(refFasta), file(GTF), file(GTF_tbi) from input_vcfs.combine(vep_ref_dir_assembly)
       .combine(ref_fa)
        .combine(gtf)
        .combine(gtf_tbi)
       
    output:
        set val(sampleID), file("${output_file}") into vcf_annotated
        file("${output_html}")

    script:
         prefix = "${sampleID}"
         output_file = "${prefix}.vep.vcf"
         output_html = "${vcf}".replaceFirst(/.vcf$/, ".vep.vcf_summary.html"

    """
    vep \
    --fasta "${refFasta}" \
    --format vcf --force_overwrite \
    --dir "${ref_dir}" \
    --assembly "${assembly}" \
    --gtf "${GTF}" \
    --force_overwrite \
    --species homo_sapiens \
    --input_file "${vcf}" \
    --sift b \
    --polyphen b \
    --stats_file "${output_html}" \
    --output_file "${output_file}"
    """
}

```
When I run the above main.nf file, as 

`./nextflow run main.nf --ref_fa /projects/kernels_VEP/Homo_sapiens.GRCh38.dna.primary_assembly.fa --gtf /reference/Homo_sapiens.GRCh38.97.gtf.gz --gtf_tbi /reference/Homo_sapiens.GRCh38.97.gtf.gz.tbi`

The Nextflow is running however, it generates the output only for a couple of files, and then it suspends the run with a WARN message. I have no cluster nor scheduler so I am specifying the executor as local, with available CPUs and 

### Program output 

```
The log file looks like this,
N E X T F L O W  ~  version 19.01.0
Launching `main.nf` [boring_ardinghelli] - revision: 02b2f0f23e
~~~~~~~ VEP Pipeline ~~~~~~~
* Project dir:        /derived/projects/kernels_VEP/vep_SPB_out/vep_ensembl/v2/next
* Launch dir:         /derived/projects/kernels_VEP/vep_SPB_out/vep_ensembl/v2/next
* Work dir:           /UKbiobank/derived/projects/kernels_VEP/vep_SPB_out/vep_ensembl/v2/next/work
* Profile:            standard
* Script name:        main.nf
* Script ID:          02b2f0f23ee763fd620c647e344f52d0
* Container engine:   docker
* Workflow session:   8ddd9216-18e2-4952-8016-7cfefa3c7994
* Nextflow run name:  boring_ardinghelli
* Nextflow version:   19.01.0, build 5050 (22-01-2019 11:19 UTC)
* Launch command:
nextflow run main.nf --ref_fa /derived/projects/kernels_VEP/Homo_sapiens.GRCh38.dna.primary_assembly.fa --gtf /data/reference/Homo_sapiens.GRCh38.97.gtf.gz --gtf_tbi /data/reference/Homo_sapiens.GRCh38.97.gtf.gz.tbi

[warm up] executor > local
[skipping] Stored process > download_ref
[68/7ae1d9] Submitted process > vep (13)
[be/90b7e1] Submitted process > vep (1)
[ae/93e8c0] Submitted process > vep (16)
[26/e0d53e] Submitted process > vep (14)
[fb/7e3d42] Submitted process > vep (10)
[bc/a64b52] Submitted process > vep (15)
WARN: Killing pending tasks (1)
```

### Environment 

* Nextflow version:  nextflow version 19.01.0.5050
* Java version: 
* Operating system: ubuntu 18.04
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

It would be really great if someone can point out the problem here. I am running the whole pipeline in the docker container. 
Thanks

**Comment by pditommaso** [comment]
Please include the `.nextflow.log` file. Also, consider to update to latest version 20.07.1.
