### ISSUE TITLE
cat: write error: Disk quota exceeded

### ISSUE THREAD

**Issue by horta** [nextflow-io/nextflow#1690]
### Expected behavior and actual behavior

- Expected: process to run `.command.sh`.
- Actual: `.command.log` says it has finished "succesfully" without running `.command.sh`. The `.nextflow.log` file tells us that nextflow believes that the corresponding job is in the SUBMITTED state, even thought the LSF cluster has it ended succesfully.

### Steps to reproduce the problem

- Use a LSF cluster
- Run the pipeline https://github.com/EBI-Metagenomics/iseq-profmark issue the following command:
```bash
nextflow run ~/code/iseq-profmark2/main.nf -c ~/code/iseq-profmark2/nextflow.config \
--storageDir /hps/nobackup2/research/stegle/users/horta/db
-profile lsf
-resume
```
- At random chance (it appears), the process [download_genbank_catalog](https://github.com/EBI-Metagenomics/iseq-profmark/blob/600842e62a9eb3e4cc0edf331499849b01c315c8/main.nf#L59) will end "succesfully" but without actually executing the required script.

### Program output 

The work directory (on which the process failed) will have only 3 files:

```bash
% ls -a /hps/nobackup2/research/stegle/users/horta/exp1/work/88/1e3c003e59bdd353d1854f512e2751
.command.log  .command.run  .command.sh
```
The head of `.command.log` gives the clue:

```
cat: write error: Disk quota exceeded

------------------------------------------------------------
Sender: LSF System <lsf@hx-noah-40-03>
Subject: Job 6490831: <nf-download_genbank_fasta_(9)> in cluster <EBI> Done

Job <nf-download_genbank_fasta_(9)> was submitted from host <noah-login-02> by user <horta> in cluster <EBI> at Thu Jul 30 03:15:52 2020
Job was executed on host(s) <hx-noah-40-03>, in queue <research-rh74>, as user <horta> in cluster <EBI> at Thu Jul 30 03:15:53 2020
</homes/horta> was used as the home directory.
</hps/nobackup2/research/stegle/users/horta/exp1/work/88/1e3c003e59bdd353d1854f512e2751> was used as the working directory.
```

as well as its tail

```
(... more ...)
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time :                                   0.01 sec.
    Max Memory :                                 -
    Average Memory :                             -
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              -
    Max Threads :                                -
    Run time :                                   0 sec.
    Turnaround time :                            1 sec.

The output (if any) is above this job summary.
```

Relevant files:

- [command.log](https://danilo-horta.s3.eu-west-2.amazonaws.com/nextflow-bug/command.log)
- [command.run](https://danilo-horta.s3.eu-west-2.amazonaws.com/nextflow-bug/command.run)
- [command.sh](https://danilo-horta.s3.eu-west-2.amazonaws.com/nextflow-bug/command.sh)
- [nextflow.log](https://danilo-horta.s3.eu-west-2.amazonaws.com/nextflow-bug/nextflow.log)

### Environment 

* Nextflow version: 20.07.1.5412
* Java version: openjdk version "1.8.0_161"
* Operating system: Linux 3.10.0-693.5.2.el7.x86_64, cpe:/o:redhat:enterprise_linux:7.4:GA:server
* Bash version: zsh 5.0.2 (x86_64-redhat-linux-gnu)

### Additional context

- The pipeline is being ran **in a shared folder with petabytes of available space**, with **no user quote**.
I can do
```bash
% cd /hps/nobackup2/research/stegle/users/horta/exp1/work/88/1e3c003e59bdd353d1854f512e2751
% dd if=/dev/zero of=test bs=1G count=100 conv=fdatasync
% ls -lh test
Permissions Size User Date Modified Name
.rw-r--r--@ 107G 5007 30 Jul 13:05  test
```
with no problem.
- My home directory is limited to 10G, and right now I'm using 6.6G of it. (and, as said above, I'm not using my home folder for the task)
- I can't find `cat` command being issued on my part.

**Comment by horta** [comment]
It looks to be related to job spooling of LSF clusters:

```
% quota -v horta
Disk quotas for user horta (uid 5007):
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
vnas-ebicluster:/vol/ebi_lsf_spool
                2096980  2097152 2097152            1100  4294967295 4294967295
```

Notice that I'm using 2,096,980 from a total of 2,097,152 blocks. The cluster managers are remove my job logs to sort this out but it would be great (if that is indeed the problem) if Nextflow could detect this as a failed job.

**Comment by pditommaso** [comment]
This is weird: 

```
ls -a /hps/nobackup2/research/stegle/users/horta/exp1/work/88/1e3c003e59bdd353d1854f512e2751
.command.log  .command.run  .command.sh
```

Also `CPU time :  0.01 sec.`. 

It seems it crashed immediately, likely for the reason reported in the log file 

```
cat: write error: Disk quota exceeded
```

**Comment by horta** [comment]
Yeah, it does seem related to job spooling of LSF clusters. You might want to consider it a LSF bug if you wish.
