### ISSUE TITLE
Documentation search leads to empty links

### ISSUE THREAD

**Issue by JoseEspinosa** [nextflow-io/nextflow#1691]
### Expected behavior and actual behavior

When searching for a topic in the left menu the returned links do not work 

### Steps to reproduce the problem

Search for example for "checkIfExists".
Returns the following [https://www.nextflow.io/docs/latest/search.html?q=checkIfExists&check_keywords=yes&area=default#](https://www.nextflow.io/docs/latest/search.html?q=checkIfExists&check_keywords=yes&area=default#). The listed links when clicked return a 404 error.

### Program output 

[https://www.nextflow.io/docs/latest/channelundefined?highlight=checkifexists](https://www.nextflow.io/docs/latest/channelundefined?highlight=checkifexists)

### Environment 

NA

**Comment by pditommaso** [comment]
Was a problem with the sphynx theme. thanks for reporting!
