### ISSUE TITLE
process-specific directives in profiles

### ISSUE THREAD

**Issue by brgew** [nextflow-io/nextflow#1692]
Hi,

I want to set process-specific process directives defined in a profiles block. In particular, at this time, I need to set module directives conditioned on a profile specified on the command line. I use Nextflow version 20.07.1.

I approach this incrementally using a test script, main.nf, that has the text

  process foo {
      output:
      stdout into result
 
 
      script:
      """
      echo "hello world"
      """
  }
 
 
  result
      .view()

and added to the nextflow.config file in the directory where I run the main.nf script

  profiles {
    standard {
      process.$foo.module = 'nomodule'
    }
  }

I run 'nextflow run main.nf' and this does not give an error so I tried adding 'module "no module"' to 'process foo' in main.nf and that gives no error. I decide that there is an error filter on the module directive.

So I try

  process foo {
      cache 'oops'

      output:
      stdout into result

      script:
      """
      echo "hello world"
      """
  }

This gives a warning about unknown cache mode. I remove 'cache "oops"' from main.nf and add 'process.$foo.cache "oops"' to nextflow.config. This runs without error or warning.

I try again using the command

  nextflow run -C nextflow.config test16.nf

and again no error or warning.

I wonder what I am doing wrong.

My goal is to add to the nextflow.config file something like

  profiles {
    profile1 {
      process.$foo1.module = 'python/3.7.7:R/4.0.2'
      process.$foo2.module = 'python/3.7.7:tmux/1.1.2'
      ...
    }
    profile2 {
      process.$foo1.module = 'python/3.6.4:R/3.6.1'
      process.$foo2.module = 'python/3.6.4:tmux/1.0.5'
      ...
    }
    ...
  }

Is this the correct usage for process-specific directives in profiles?

I am grateful for assistance.
Thank you.

**Comment by pditommaso** [comment]
The $ syntax is not supported anymore. You have to use the process selectors `withName` or `withLabel`. See https://www.nextflow.io/docs/latest/config.html#process-selectors.

**Comment by brgew** [comment]
Hi,
I am grateful for the prompt clarification.
Thank you for the valuable software. We have a growing number of long and complex pipelines that depend on it.

**Comment by pditommaso** [comment]
Nice. Please close the issue, if it's solved.

**Comment by brgew** [comment]
Thank you.
