### ISSUE TITLE
Executable containers no longer supported?

### ISSUE THREAD

**Issue by krokicki** [nextflow-io/nextflow#1695]
### Expected behavior and actual behavior

The expected behavior is documented here:
https://www.nextflow.io/docs/latest/en/latest/docker.html#executable-containers

But "container true" doesn't seem to work. Instead it attempts to run a container called "docker://true". 

### Steps to reproduce the problem

demo.nf
```
process runImage {
    container true
    '''
    docker/hello-world
    '''
}
```

nextflow.config:
```
docker.enabled = true
```

Run with `nextflow run demo.nf`

### Program output 

```
$ nextflow run demo.nf
N E X T F L O W  ~  version 20.04.1
Launching `demo.nf` [thirsty_heisenberg] - revision: 1b349df04b
executor >  local (1)
[07/8fb796] process > runImage [100%] 1 of 1, failed: 1 ✘
Error executing process > 'runImage'

Caused by:
  Process `runImage` terminated with an error exit status (125)

Command executed:

  docker/hello-world

Command exit status:
  125

Command output:
  (empty)

Command error:
  Unable to find image 'true:latest' locally
  docker: Error response from daemon: pull access denied for true, repository does not exist or may require 'docker login'.
  See 'docker run --help'.

Work dir:
  /home/tester/work/07/8fb796143eedff8bc6178e770b46a4

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Environment 

* Nextflow version: 20.04.1
* Java version: 1.8.0_102-b14
* Operating system: Linux 3.10.0-514.10.2.el7.x86_64
* Bash version: GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)

### Additional context

The same thing happens when trying to run with Singularity as the container engine: Singularity tries to download docker://true. 

The original commit which introduced this feature is https://github.com/nextflow-io/nextflow/commit/e60a7dddb3ecb7634977016274e927cc175e1e8f, but very little of this code remains in the latest version. In particular, the string "isContainerExecutable" doesn't exist in the codebase. "containerExecutable" is a property of TaskBean, but it's deprecated and unused. 

Was this feature removed? Is there another way to achieve the same thing so that we don't need to repeat the Docker ENTRYPOINT inside the process?

**Comment by pditommaso** [comment]
Yeah, it was removed a long time ago #992. Never noticed the doc is still there.

**Comment by pditommaso** [comment]
Fascinating, the link above is an old copy of the docs. The real one is https://www.nextflow.io/docs/latest/docker.html

**Comment by krokicki** [comment]
FYI, the old docs are what is returned when you google for "nextflow executable containers".
