### ISSUE TITLE
Please mention stdout() in the DSL2 documentation page.

### ISSUE THREAD

**Issue by charles-plessy** [nextflow-io/nextflow#1697]
Hello, thanks a lot for releasing the DSL2.

I was trying to output the standard output of my script command in a DSL2 _process_, but had difficulty to find the correct syntax.  Fortunately, after trying `output: stdout`, nextflow's error message instructed me to use `output: stdout()` instead, but perhaps you can document it directly in the DSL2 page ?

**Comment by pditommaso** [comment]
Please include a replicable test case

**Comment by pditommaso** [comment]
To clarify also `output: stdout` should work.

**Comment by charles-plessy** [comment]
Sorry, I can not reproduce how I got the error message.  But I could find it in the source code: it is: 

```
Process `stdout` output channel should not be specified when using DSL 2 -- Use `stdout()` instead"
```

`stdout` without parentheses works fine with me at the moment, thank you.

Have a nice week-end,

**Comment by maxbates** [comment]
see https://github.com/nextflow-io/tests/blob/master/basic-dsl2.nf

**Comment by pditommaso** [comment]
That's for spotting this out! I confirm that's a leftover of a previous interaction. Parentheses aren't required when using dsl2 final. See dc029c04.
