### ISSUE TITLE
include  function seems not work properly with default parameter

### ISSUE THREAD

**Issue by nongbaoting** [nextflow-io/nextflow#1698]
### Expected behavior and actual behavior

I write a function file `basic_func.nf`, 
```

def check_file(myfile, par_name="your input file"){ 
    if ( myfile ){
        myfile_ = file(myfile)
        if( !myfile_.exists() ) exit 1, "File not found: ${myfile}"

    }else{exit 1, "${par_name} value is null !"}
    return myfile_
}
```

and then I include the function into main 
```
include { check_file } from './scripts/basic_func.nf' 
gtf = check_file(params.gtf)
```

I have to prive two parameters, my `check_file` function actully have a default paramter! I just don't not why?

`gtf = check_file(params.gtf, "--gtf")` this will work, but I was wonder something is wrong, and I worry in the future mistake。could you help me!

### Program output 

```
-> % nextflow run ~/pipe/fcirc_pipe/fcirc.3.nf --genome hg38 --reads "../reads/test_fastq/*.R{1,2}.fastp.fq.gz" -resume
N E X T F L O W  ~  version 20.07.1
Launching `/home/nbt2/pipe/fcirc_pipe/fcirc.3.nf` [prickly_snyder] - revision: 0c0cb79710
wrong number of arguments

 -- Check script '/home/nbt2/pipe/fcirc_pipe/fcirc.3.nf' at line: 33 or see '.nextflow.log' file for more details

```

### Environment 

* Nextflow version: 20.07.1 build 5413
* Java version: openjdk version "1.8.0_222"
* Operating system: Linux
* Bash version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Optional parameters are not supported.

**Comment by multimeric** [comment]
Could we request for them to be supported?

As an aside, I think you can work around this restriction by defining the function in a groovy module, and importing that using the native groovy `import` syntax rather than using `include`. This is a bit tricky to get right, though.
