### ISSUE TITLE
workflow alias

### ISSUE THREAD

**Issue by replikation** [nextflow-io/nextflow#1703]
## New feature, workflow alias
Hi,

Thanks for the work you put into nextflow.
Defining workflows in DS2L makes the code writing and readability really good.
Is it possible to implement some kind of alias (similar to modules) for workflows in DSL2?

* I know you can put workflows in other workflows to "circumvent this" but it gets a bit messy regarding code readability

## Usage scenario 

* simplified (the usage scope would be for larger workflow definitions)

````groovy
// defining one workflow
workflow samtools_wf {
    take:   fasta
    main:  samtools(parser(fasta))
    emit:   samtools.out 
} 

// aliasing it so it can be used two times
samtools_wf().aliasTo { samtools_wf_1; samtools_wf_2 } 

// using it two times
workflow {
samtools_wf_1(fasta_input)
samtools_wf_2(fasta_input)
}

````

## Suggest implementation 

* something like this
````groovy
samtools_wf() .aliasTo { samtools_wf_1; samtools_wf_2 } 
````

or maybe in the workflow?
````groovy
workflow samtools_wf {
    alias:  samtools_wf_1
              samtools_wf_2
    take:   fasta
    main:  samtools(parser(fasta))
    emit:   samtools.out 
} 
````

**Comment by phiweger** [comment]
+1 and similar to modules, import of subworkflows would be awesome, too. I guess these suggestions are really asking the same thing, to be able to treat subworkflows like they were processes.

**Comment by pditommaso** [comment]
This is currently possible while including either `process` and `workflow`. 

https://www.nextflow.io/docs/latest/dsl2.html#module-aliases

**Comment by replikation** [comment]
ah this was not clear from the documentation for me that workflow and process work similar in this manner (both can be included and aliased, I thought it was for the process only). But thanks @pditommaso for clarifying this.
