### ISSUE TITLE
Enable use of Singularity cache dir as repository

### ISSUE THREAD

**Issue by pontus** [nextflow-io/nextflow#1706]
## New feature

It would be nice to be able to provide singularity container files in a directory as a repository, available for other users.

The current logic for pulling images to the singularity cache requires the use of a lock file in the cache directory 
and makes it not possible to have a directory provided without write permissions (e.g. use for running pipelines as a user without being trusted to manage said repository).

## Usage scenario 

A shared directory can be used on HPC systems to reduce data duplication from container images. It would also simplify providing validated pipelines to users of a system.

## Suggest implementation 

It seems the current implementation of a cache dir could be adopted as a repository with minor logical changes, e.g. 

* redo lock so logic is taken only for downloading
* if requested file exists, return directly
* for downloading (`singularity pull`), use another name in the same directory and rename the file to the correct name afterwards

An alternative implementation would be prepopulating  a hashmap that's currently kept to keep state of requested files during the runtime.

It would also be possible to build a completely different repository feature,but I'm not sure what would be the requirements for that.

**Comment by pditommaso** [comment]
I agree that could be useful. I would consider a pull request implementing this feature.

**Comment by marcodelapierre** [comment]
Just wanting to mention that some users in our HPC centre have the same issue.
A direct solution would be useful, but right now this is our suggested workaround for "read-only" users:

1. define a variable with the image repo dir:
```
params.imageDir = 'file:///path/to/images'
```

2. use it in the container definitions:
```
process DoThis {
    container = "${params}/image.sif"
    """"
    commands here 
    """}
```

If willing to maintain generality and portability of the pipeline, some conditional logic can be used to switch between remote pull and local repo in the config.

**Comment by pditommaso** [comment]
Does singularity require some special command-line option to handle a container as a directory?

**Comment by pontus** [comment]
I'm not sure I'm following the trail of thought here, but:

Nothing special should be required for a sandbox (a container as a directory), but sandboxes have various issues in themselves (e.g. a large number of files make them time consuming to backup).

**Comment by pditommaso** [comment]
Solved. See dd92772b.
