### ISSUE TITLE
Using Charliecloud containers

### ISSUE THREAD

**Issue by DavidBrayford** [nextflow-io/nextflow#1707]
Is it possible to use Charliecloud containers and if so is there any documentation on how to use it?

**Comment by pditommaso** [comment]
Charliecloud is not a supported container runtime.

**Comment by tbugfinder** [comment]
I didn't look into charliecloud yet but would you support a PR?

**Comment by pditommaso** [comment]
It depends. What does charliecloud really add to hpc container executions when compared to singularity and podman?

**Comment by DavidBrayford** [comment]
The reason for my question regarding Charliecloud support is the HPC center(www.LRZ.de) I am working at doesn't support Singularity or Podman due to security policies and only supports Charliecloud. Today, I was asked by a user about using nextflow on one of the HPC systems and had to inform them that if it wasn't possible with Singularity.
This might be an issue for other HPC centers with strict security policies.

**Comment by pditommaso** [comment]
Nextflow aims to make pipelines portable across platforms and datacenter and therefore a contribution adding the support for Charliecloud runtime is welcome.

**Comment by pditommaso** [comment]
Charliecloud support has been merged #1809
