### ISSUE TITLE
scratchDir is overwritten by TMPDIR env variable

### ISSUE THREAD

**Issue by pauca** [nextflow-io/nextflow#171]
if TMPDIR is set, scratchDir gets overwriten by TMPDIR

to reproduce
```
c1 = Channel.from( 1)
process A {
    scratch '/home/myuser'
    executor 'sge'
    input:
    val c1   
    output:
    file "out_scratch_dir.txt" into aout
    script:
    """
    touch out_scratch_dir.txt
    echo \"PWD `pwd` \" >> out_scratch_dir.txt
    """
}
```

**Comment by pditommaso** [comment]
I've uploaded a snapshot fixing this problem. You can use it defining the following variable in your env `NXF_VER=0.20.0-SNAPSHOT`

**Comment by pauca** [comment]
Great!
Thanks

2016-06-06 14:51 GMT+02:00 Paolo Di Tommaso <notifications@github.com>:
