### ISSUE TITLE
Duplicate mount destination when using Podman container

### ISSUE THREAD

**Issue by gongyh** [nextflow-io/nextflow#1710]
## Bug report 

Podman containers did not allow mounting the same directory twice, but nextflow will mount twice (workDir and $PWD) if workDir is  one of the longest common paths.

### Expected behavior and actual behavior

If workDir belongs one of the longest common paths, remove it from the mounting list (only mount using "-v $PWD:$PWD").

### Steps to reproduce the problem

when input data and nextflow script put in a different volume (compared with workDir)

### Program output 

Command exit status:
  125

Command output:
  (empty)

Command error:
  Error: /mnt/XXXXXX/podman/work/d6/cfc97c54109d0b42ea49de9dc45aa9: duplicate mount destination

Work dir:
  /mnt/XXXXXX/podman/work/d6/cfc97c54109d0b42ea49de9dc45aa9

### Environment 

* Nextflow version: 20.07.1
* Java version: 1.8.0_74-b02
* Operating system: Linux (CentOS 7)
* Bash version: 4.2.46

### Additional context
// in .command.run
nxf_launch() {
    podman run -i -e "NXF_DEBUG=${NXF_DEBUG:=0}" -v /opt/XXXXXX:/opt/XXXXXX -v **/mnt/XXXXXX/podman/work/d6/cfc97c54109d0b42ea49de9dc45aa9:/mnt/XXXXXX/podman/work/d6/cfc97c54109d0b42ea49de9dc45aa9** -v **"$PWD":"$PWD"** -w "$PWD" --entrypoint /bin/bash --name $NXF_BOXID gongyh/scgs -c "eval $(nxf_container_env); /bin/bash /mnt/XXXXXX/podman/work/d6/cfc97c54109d0b42ea49de9dc45aa9/.command.run nxf_trace"
}

Docker can accept duplicate mount entry but Podman cannot, need proper logic for makeVolumes function in modules/nextflow/src/main/groovy/nextflow/container/ContainerBuilder.groovy (line 216-249).

**Comment by pditommaso** [comment]
Solved by d0cc38de.

**Comment by gongyh** [comment]
Great! waiting for the new release.
