### ISSUE TITLE
Local process kill signal is not propagated to children processes

### ISSUE THREAD

**Issue by huguesfontenelle** [nextflow-io/nextflow#172]
A short script should reproduce the "problem":
```
ch = Channel.from(1, 2, 3)
(chone, chtwo) = ch.into(2)

process fail {
    input:
    val(no) from chone

"""
awk -v min=1 -v max=5 'BEGIN{srand(); print int(min+rand()*(max-min+1))}' | xargs sleep
smurf
"""
}

process success {
    input:
    val(no) from chtwo

"""
sleep 1h
"""
}
```

The pipeline fails because the `smurf` command does not exist.
However the `sleep 1h` keeps running in the background, taking valuable resources!
> granted, in this particular example this is minimal ;-)

Any workaround?

**Comment by huguesfontenelle** [comment]
[no-fail.nextflow.txt](https://github.com/nextflow-io/nextflow/files/300843/no-fail.nextflow.txt)

**Comment by huguesfontenelle** [comment]
[no-fail.ps-fx.txt](https://github.com/nextflow-io/nextflow/files/300844/no-fail.ps-fx.txt)

**Comment by pditommaso** [comment]
I've managed to replicate it. The pipeline does no hang. The problem is that when killing the POSIX processes the kill signal is not propagated to children processes. 

```
58048 pts/36   S      0:00 /bin/bash -ue .command.run
58105 pts/36   S      0:00  \_ tee .command.out
58109 pts/36   S      0:00  \_ tee .command.err
58112 pts/36   S      0:00  \_ /bin/bash -ue /users/cn/ptommaso/scratch/e2/5b4ce8d644041f0b72c8ca2923b82d/.command.sh
58123 pts/36   S      0:00      \_ sleep 1h
58046 pts/36   S      0:00 /bin/bash -ue .command.run
58107 pts/36   S      0:00  \_ tee .command.out
58111 pts/36   S      0:00  \_ tee .command.err
58114 pts/36   S      0:00  \_ /bin/bash -ue /users/cn/ptommaso/scratch/04/889826b6c48ce95d0ac734b6c4a948/.command.sh
58121 pts/36   S      0:00      \_ sleep 1h
58044 pts/36   S      0:00 /bin/bash -ue .command.run
58097 pts/36   S      0:00  \_ tee .command.out
58099 pts/36   S      0:00  \_ tee .command.err
58101 pts/36   S      0:00  \_ /bin/bash -ue /users/cn/ptommaso/scratch/7b/70cc551497057d1f37d8555ad20424/.command.sh
58122 pts/36   S      0:00      \_ sleep 1h
```

**Comment by mes5k** [comment]
I've seen similar issues with docker containers that either don't seem to get killed or are very slow to respond to killing.  I wasn't sure if this was a nextflow problem or simply the commands running within the containers not responding well to signals.

**Comment by pditommaso** [comment]
@huguesfontenelle I've uploaded a patch for this. If you want to give a try to it define the variable `export NXF_VER=v0.20.0` in your env and run nxf as usual. 

@mes5k It should fix the problem for docker as well as.

**Comment by huguesfontenelle** [comment]
Works perfect. No more zombies :-)

**Comment by pditommaso** [comment]
Zombies killed!
