### ISSUE TITLE
Unable to access jarfile

### ISSUE THREAD

**Issue by nilaycan** [nextflow-io/nextflow#1721]
Hello,

In fact I run the pipeline wo a problem, after doing some other modifications, it suddenly started to say:
 
> Error: Unable to access jarfile beagle.24Aug19.3e8.jar

So it basically cannot access to beagle (java software tool). Here, I have it in my env.yml file:
```
    dependencies:
  - beagle=5.1_24Aug19.3e8=0
```
and here is my command in process of concern:

`
java -jar beagle.24Aug19.3e8.jar gt=missing_removed.vcf.gz iterations=${params.iters} phase-states=${params.phase_states} imp-states=${params.imp_states} ne=${params.ne} nthreads=${params.nthreads_SNP} out=snps_imputed.gt`

so why this issue appears, you have any idea? Thanks in advance!

Cheers,
Nilay

**Comment by pditommaso** [comment]
Don't think this is related to nextflow. It looks more Conda issue.

**Comment by nilaycan** [comment]
Yes! I was about to update it but thanks for replying!
Guess it happened because I upgraded it, and will downgrade & give it a try. You think the issue will stay or should we delete it?

**Comment by pditommaso** [comment]
Nice to hear to you fixed. It's enough to close it 😄
