### ISSUE TITLE
Add support for GitHub Container Registry

### ISSUE THREAD

**Issue by hoelzer** [nextflow-io/nextflow#1722]
## New feature

GitHub just announced the GitHub Container Registry (GHCR) to store container images:
https://github.blog/2020-09-01-introducing-github-container-registry/

## Usage scenario 

Besides already supported container repositories such as https://hub.docker.com/, it would be great to also add future support for GHCR. 

Thanks for the hard work on Nextflow!

**Comment by pditommaso** [comment]
Already support. Prefix the container names with that registry name or use the `docker.registry` option https://www.nextflow.io/docs/latest/config.html#config-docker
