### ISSUE TITLE
Different behavior using singularity.

### ISSUE THREAD

**Issue by Lcornet** [nextflow-io/nextflow#1723]
## Bug report 

When I add singularity to my ORPER script, a process crash while it is note the case without the container.

### Expected behavior and actual behavior

nextflow ORPER.nf --refgroup=Nostocales --outgroup=Gloeobacterales --ribodb=/data1/ORPER/ribo/ --companion=/opt/ORPER/ORPER-companion.py --cpu=20 --SSU=Nostocales-silva.fasta --cdhit=no

 E X T F L O W  ~  version 20.07.1
Launching `ORPER.nf` [drunk_minsky] - revision: 9017f39f09
ORPER-INFO: Taxdump not specified -> project dir
ORPER-INFO: Taxdump dir found in project dir -> Used
SSU CD-HIT dereplication not activated
executor >  local (3)
[8d/0cba7b] process > Taxonomy (1)            [100%] 1 of 1 ✔
executor >  local (3)
[8d/0cba7b] process > Taxonomy (1)            [100%] 1 of 1 ✔
[-        ] process > RefSeq (1)              -
[-        ] process > GetRefGenomes           -
[-        ] process > RefGenomesCheckm        -
[-        ] process > RefGenomesRnammer       -
[-        ] process > RefGenomesFilter        -
[-        ] process > RefGenomesDereplication -
[-        ] process > GetRefRelProteomes      -
[-        ] process > GetOutGenomes           -
[-        ] process > OutGenomesCheckm        -
[-        ] process > OutGenomesRnammer       -
[-        ] process > OutGenomesFilter        -
[-        ] process > GetOutRelProteomes      -
[-        ] process > RiboDBFortytwo          -
[-        ] process > AlignmentMafft          -
[-        ] process > ConcatScafos            -
[-        ] process > ReferenceTreeRaxml      -
[95/1f2704] process > SSUDereplication (1)    [100%] 1 of 1 ✔
[-        ] process > ConstrainTreeRaxml      -
[-        ] process > PublicationResults      -

The same command but adding singularity.enabled = true to config file

process.container = '/home/ulg/Documents/program/test-singu/ORPER/ORPER.sif'
singularity.enabled = true

[9d/d75451] process > SSUDereplication (1)    [100%] 1 of 1, failed: 1 ✘
[-        ] process > ConstrainTreeRaxml      -
[-        ] process > PublicationResults      -
Error executing process > 'SSUDereplication (1)'

Caused by:
  Process `SSUDereplication (1)` terminated with an error exit status (1)

Command executed:

  cp SSU.fasta derepliacted-SSU.fasta

Command exit status:
  1

Command output:
  (empty)

Command error:
  cp: cannot stat 'SSU.fasta': No such file or directory

Work dir:
  /data1/ORPER/work/9d/d75451d638d785b1772ebbbe6caad2

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

### Steps to reproduce the problem

The part who fails is just a bash cp

### Program output 

params.SSU = null
if (params.SSU == null) {
	exit 1, "Path to fasta file containing SSU sequences"
} 

ssu_ch = Channel.fromPath(params.SSU)

process SSUDereplication {

    //informations

	//input output
    input:
    file 'SSU.fasta' from ssu_ch
    val cpu from params.cpu
    
    output:
    file 'derepliacted-SSU.fasta' into ssuDereplicated_ch

    //script
    script:
    if (params.cdhit == 'yes'){
        println "SSU CD-HIT dereplication activated"
        """
        cd-hit -i SSU.fasta -o derepliacted-SSU.fasta -c 1.0 -T $cpu
        """
    }
    else {
        println "SSU CD-HIT dereplication not activated"
        """
        cp SSU.fasta derepliacted-SSU.fasta
        """

    }

}

### Environment 

* Nextflow version: 20.07.1
* Java version: openjdk version "11.0.8" 2020-07-14
* Operating system: Linux 18.04
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by tbugfinder** [comment]
Hi, do you have proper bind mounts in place for home and data1?

**Comment by Lcornet** [comment]
Indeed, 

singularity.runOptions = '-B /data1:/tmp' was the solution.

Nevertheless, I have another issue who is also linked to the mount.

I upgrade to latest singularity and NF version and I have the following problem

cat nextflow.config
process.container = '/data1/ORPER/ORPER.sif'
singularity.runOptions = '-B /data1/ORPER:/tmp'
singularity.enabled = true

nextflow ORPER.nf --refgroup=Nostocales --outgroup=Gloeobacterales --ribodb=/tmp/ribo/ --companion=/opt/ORPER/ORPER-companion.py --cpu=20 --SSU=/tmp/Nostocales-silva.fasta --cdhit=no


[1f/e5ba08] process > SSUDereplication (1)    [100%] 1 of 1, failed: 1 ✘
[-        ] process > ConstrainTreeRaxml      -
[-        ] process > PublicationResults      -
Error executing process > 'Taxonomy (1)'

Caused by:
  Process `Taxonomy (1)` terminated with an error exit status (1)

Command executed:

  setup-taxdir.pl --taxdir=/data1/ORPER/taxdump
  echo /data1/ORPER/taxdump > taxdump_path.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  /bin/bash: line 0: cd: /data1/ORPER/work/28/a95b99b789eb19c6c0eb9de4574028: No such file or directory
  /bin/bash: .command.sh: No such file or directory

Work dir:
  /data1/ORPER/work/28/a95b99b789eb19c6c0eb9de4574028

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

The /data1/ORPER/work/28/a95b99b789eb19c6c0eb9de4574028 exist and contains .command.sh:
less /data1/ORPER/work/28/a95b99b789eb19c6c0eb9de4574028/.
./              .command.begin  .command.log    .command.run    .exitcode
../             .command.err    .command.out    .command.sh
