### ISSUE TITLE
Configuring AWS temporary session token in nextflow.config and environment 

### ISSUE THREAD

**Issue by mageshwarm** [nextflow-io/nextflow#1724]
As continuity to https://github.com/nextflow-io/nextflow/pull/1265, please enable us to configure sessionToken in nextflow.config and export AWS_SESSION_TOKEN. Currently aws_session_token supported by ~/.aws/credentials only.

**Comment by pditommaso** [comment]
It should be doable adding add the read the `sessionToken` here 

https://github.com/nextflow-io/nextflow/blob/e94e6877c2dc9bed983e873b62e302a08843c891/modules/nf-commons/src/main/nextflow/Global.groovy#L80-L89


and the corresponding env var (not sure about the exact name) 

https://github.com/nextflow-io/nextflow/blob/e94e6877c2dc9bed983e873b62e302a08843c891/modules/nf-commons/src/main/nextflow/Global.groovy#L91-L96

**Comment by robin-cruk** [comment]
the variable is `AWS_SESSION_TOKEN`

**Comment by kolarji2** [comment]
Hi, what is the status of this issue? Is it supported now? How can I configure nextflow with AWS_SESSION_TOKEN?

**Comment by pditommaso** [comment]
This is *partially* supported when the session token is defined in the AWS credentials file. 

However, the refresh of the session token is not supported. Follow #2295 for details

**Comment by kolarji2** [comment]
Hi, thank you for your quick response. But it is not working for me :-(

I put my credentials to: ~/.aws/credentials
I also put them to nextflow.config  and environment variables:
aws {
    accessKey = "${AWS_ACCESS_KEY_ID}"
    secretKey = "${AWS_SECRET_ACCESS_KEY}"
    sessionToken = "${AWS_SESSION_TOKEN}"
    region = 'us-east-1'
}

But I get: Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId

**Comment by kolarji2** [comment]
I use: nextflow version 22.10.3.5834
And I am sure the credentials are valid. As I can access the files using boto3 directly. That is my current workaround, I pass the file as "val" instead of "path" object and load them from python instead.

**Comment by pditommaso** [comment]
You should be able to check in the `.nextflow.log` file if the token was grabbed. The fact you are passing the file as "val" instead of "path" rings me something wrong

**Comment by kolarji2** [comment]
Thanks, it is working now if I do not set environment variables and I do not set the nextflow.config. Then it is picked from .aws/credentials

However, I need these environment variables later in the script. :-(  Any estimate of when the update will be released? So the environment session token variables will be supported as well?
