### ISSUE TITLE
Limit rate of queries from Channel.fromSRA() method.

### ISSUE THREAD

**Issue by dstrib** [nextflow-io/nextflow#1726]
## New feature

Add an execution-wide rate limit (or individual channel-level delay) on the number of queries to the NCBI API that are produced by the Channel.fromSRA() channel factory.

## Usage scenario 
I am running into the problem with the Channel.fromSRA() method creating multiple channels in parallel in a situation similar to this:
```
orig_sra_ids = ['SRX1234567', 'SRX2345678', ... ]
orig_sra_ids.each { orig_sra_id ->
    Channel.fromSRA(orig_sra_id)
                .map{new_sra_id, fastq -> [orig_sra_id, new_sra_id, fastq]}
                .view()
                //...
}
``` 
This returns multiple errors indicating too frequent of a response, like so: 
`Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entre...`

As far as I am aware, passing the entire list of SRAs successfully retrieves the SRA entries, but does not allow mapping of each output SRA back to the original SRA provided without advance knowledge of the final SRA produced by the query (helpful in output sample naming, etc). 

Adding `sleep(time)` to this loop does not work, I think due to the fact that the queries are not made as the channels are defined. If a global rate limit could be imposed on the number of queries per second, this would be helpful.

## Suggest implementation 

(Harder?) A global tracker could be added to ensure that the number of queries to the NCBI does not exceed a certain rate per time.

(Easier?) A parameter: `maxWait` could be added to the Channel.fromSRA() implementation, that defines a range for a random amount of time the channel will "sleep" before making its query. For instance: 
```Channel.fromSRA(sra, maxWait: 3000)``` would cause each instance of Channel.fromSRA() to wait 0-3000 ms before making its query, effectively distributing the queries across 3 seconds (on average) if they happen to all be instantiated simultaneously.

An alternative to this approach for my specific use case would be to potentially provide an option to include the query SRA used as a component of each returned SRA file (pair).

**Comment by shengw-c** [comment]
I know it's been four years, but I saw the issue pops up again. Any solve please?
