### ISSUE TITLE
Files from a .collect() channel not staged when too many

### ISSUE THREAD

**Issue by phiweger** [nextflow-io/nextflow#1727]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

channel.collect() should stage all 10000 files, however, it only creates a folder which does not contain anything (no staged files/ symlinks)

### Steps to reproduce the problem

Create 10k files (eg with touch) and collect them for some process (eg cat).

### Program output 

.command.log is empty

.command.out has not been created

```
Error executing process > 'create_index'

Caused by:
  Process `create_index` terminated with an error exit status (139)

Command executed:

  sourmash index -k 51 index.sbt.zip --traverse-directory .

Command exit status:
  139

Command output:
  (empty)

Work dir:
 .../work/8e/0cfb1b48cc23f02da8e1d279e100e0

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Environment 

nextflow installed via conda

* Nextflow version: [?] 

```bash
nextflow -version

      N E X T F L O W
      version 20.07.1 build 5412
      created 24-07-2020 15:18 UTC (17:18 CEST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io
```

* Java version: [?]

openjdk 8.0.192

* Operating system: [macOS, Linux, etc]

masOS

* Bash version: (use the command `$SHELL --version`)

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

### Additional context

My guess is that this might have something to do with the number of files (about 10000) and the "Argument list too long" limit, but I see no clear error message that points into any direction.

Thanks!

**Comment by pditommaso** [comment]
I think this happens because the resulting Bash script or command line is too big. Either split the task or increase the Bash limit.

**Comment by phiweger** [comment]
ah, that might explain it. how would you recommend I split the task, using .buffer()?

**Comment by pditommaso** [comment]
It should work!
