### ISSUE TITLE
PBSPro from outside HPC

### ISSUE THREAD

**Issue by andrewjmc** [nextflow-io/nextflow#1730]
## New feature

Enable nextflow co-ordinating process to run on a node outside of HPC and submit jobs via `ssh` into HPC. Filsystem mount point on the co-ordinating node may differ from that within HPC.

## Usage scenario 

Many HPC systems do not allow long-running jobs (i.e. >72 hours). Thus even if individual processes are short, the co-ordinating nextflow process will be terminated at regular intervals and require manual resubmission with `--resume`.

A user could instead access a dedicated machine which runs the Nextflow co-ordinating process (~weeks) and submits jobs to HPC and monitors.

## Suggest implementation 

Add parameters for (e.g.) PBSPro:
- sshAddress
- sshUser
- sshPassword (or may need interactive prompt / more secure way to obtain)
- localWorkdir: mount of work directory on co-ordinating node

**Comment by pditommaso** [comment]
This feature is implemented via Nextflow Tower https://tower.nf/ (currently support LSF and Slurm, PBS needs to be added)

**Comment by andrewjmc** [comment]
Super, thanks. In the meantime, I may just try and hardcode ssh into the PBS executor locally as an experiment :-)
