### ISSUE TITLE
/bin/bash: .command.sh: No such file or directory

### ISSUE THREAD

**Issue by Lcornet** [nextflow-io/nextflow#1732]
## Bug report 

When I activate the singularity container, nextflow crash and tells me that .command.sh don't exist
This appears after an update to singularity 3.6.0

### Expected behavior and actual behavior

nextflow ORPER.nf --refgroup=Nostocales --outgroup=Gloeobacterales --ribodb=/data1/ORPER/ribo/ --companion=ORPER/ORPER-companion.py --SSU=Nostocales-silva.fasta --cdhit=no

This commands and pipeline work well. but is I activate the container with : 

process.container = '/data1/ORPER/ORPER.sif'
singularity.enabled = true

it crash

### Steps to reproduce the problem

but when  I activate the container with : 

process.container = '/data1/ORPER/ORPER.sif'
singularity.enabled = true

it crash

### Program output 

ommand exit status:
  1

Command output:
  (empty)

Command error:
  /bin/bash: line 0: cd: /data1/ORPER/work/17/5e87858643dcc828837406eecff1b8: No such file or directory
  /bin/bash: .command.sh: No such file or directory

Work dir:
  /data1/ORPER/work/17/5e87858643dcc828837406eecff1b8

### Environment 

* Nextflow version: 20.07
* Java version: openjdk 11.0.8 2020-07-14
* Operating system: Linux 18
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by sckinta** [comment]
Is this issue solved? I used most updated nextflow (version 21.10.6.5660), but still have the same error. my singularity version is 3.7.0

**Comment by Lcornet** [comment]
I finally found a solution for our cluster. The config file (nextflow.config) should look like this:

process.container = 'PATH to your container'
singularity.enabled = true
singularity.cacheDir = "$PWD"
singularity.autoMounts = false
singularity.runOptions = '-B <link1> -B <link2>'

the two links can be identified with pwd and readlink -f .

Hope it helps

**Comment by james-guevara** [comment]
When using a singularity container, I have to specify a bind path in the nextflow.config like so:

```
singularity {
    enabled = true
    runOptions = "--bind $PWD"
}
```

where $PWD is the folder with my main.nf file, nextflow.config file, and work folder.
