### ISSUE TITLE
"Process <...> has been already used" when creating a process with only optional outputs

### ISSUE THREAD

**Issue by hartzell** [nextflow-io/nextflow#1733]
## Bug report 

I started [a discussion in the Nextflow gitter](https://gitter.im/nextflow-io/nextflow?at=5f6bb6d9b8a99f4519a1ff42) about this and @pditommaso said: "this looks a kind of bug" so I'm recording it here:

---

I'd like to set up a workflow that starts with a list of things (e.g. directory names, or perhaps sequence ID's or ...) and passes them to a "categorizer" process that examines them (this might be a computationally expensive step, would want to run on e.g. Batch). The "categorizer" would pass the inputs on to different subgraphs of the workflow based on its calculations.

The "categorizer" would run some shell script-ish thing (compiled executable, python script, shell script invoking various applications, ...).

I'd like to use DSLv2 if possible.

Here's a trivial example where things are categorized on color, but in the real world I'll be basing it on more serious bits.

```
                 ┌─────────────────┐
                 │ List of things  │
                 │(paths/names/...)│
                 └─────────────────┘
                          │
                          │
                          ▼
                 ┌─────────────────┐
                 │   Categorizer   │
                 │                 │
                 └─────────────────┘
                        │   │
         ┌──────────────┘   └───────────────┐
         ▼                                  ▼
┌────────────────┐                 ┌────────────────┐
│Process red ones│                 │ Process green  │
│                │                 │      ones      │
└────────────────┘                 └────────────────┘
         │                                  │
         │                                  │
         │                                  │
         ▼                                  ▼
```

### Expected behavior and actual behavior

I believe that the following script should sort the inputs into "valid" and "invalid", but it fails with:

```
$ nextflow run categorizer-2.nf
N E X T F L O W  ~  version 20.07.1
Launching `categorizer-2.nf` [sleepy_sanger] - revision: 7a3e3456b1
Process categorize has been already used -- If you need to reuse the same component include it with a different name or include in a different workflow context

 -- Check script 'categorizer-2.nf' at line: 43 or see '.nextflow.log' file for more details
```

Here's the test case code:

```
nextflow.enable.dsl=2

process categorize {
    input:
        val(name)
    output:
        env valid optional true
        env invalid optional true
    script:
    """
    if [[ $name == /tmp/* ]] ; then
        invalid=$name
    else
        valid=$name
    fi
    """
}

process handle_valid {
    input:
        val(name)
    output:
        val(name)
    """
    /bin/true
    """
}

process handle_invalid {
    input:
        val(name)
    output:
        val(name)
    script:
    """
    /bin/true
    """
}

workflow {
    // tricky, /tmp is *not* in /tmp/*....
    dir = Channel.fromList( [ '/tmp/foo', '/usr/local/bin', '/tmp' ] )
    results = categorize(dir)

    valid_results = handle_valid(results.valid)
    invalid_results = handle_invalid(results.invalid)

    valid_results.view { "$it is valid!" }
    invalid_results.view { "$it is invalid!" }
}
```

### Steps to reproduce the problem

See the test case in the expected and actual behavior section above.

### Program output 

See the expected and actual behavior section above.

### Environment 

* Nextflow version: `N E X T F L O W  ~  version 20.07.1`
* Java version:
  ```
  $ java -version
  openjdk version "1.8.0_252"
  OpenJDK Runtime Environment (build 1.8.0_252-b09)
  OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
  ```
* Operating system: CentOS 7
* Bash version: (use the command `$SHELL --version`)
   ```
   $ bash --version
   GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
   Copyright (C) 2011 Free Software Foundation, Inc.
   License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
   ```

**Comment by stekaz** [comment]
I think part of the problem is that in your example, at least, your 'categorize' outputs don't strictly need to be _optional_. Your if/else statement, by definition, will always set a value. Consider the following using the [branch operator](https://www.nextflow.io/docs/latest/operator.html#branch):

```
nextflow.enable.dsl=2

process categorize {

    tag { name }

    input:
    val name

    output:
    tuple val(name), env(isvalid)

    """
    if [[ $name == /tmp/* ]] ; then
        isvalid="false"
    else
        isvalid="true"
    fi
    """
}

workflow {

    // tricky, /tmp is *not* in /tmp/*....
    dir = Channel.fromList( [ '/tmp/foo', '/usr/local/bin', '/tmp' ] )

    results = categorize(dir).branch { name, isvalid ->
        valid: isvalid == "true"
            return name
        invalid: isvalid == "false"
            return name
    }

    results.valid.view { "$it is valid!" }
    results.invalid.view { "$it is invalid!" }
}
```

Results:

```
[95/8042c9] process > categorize (/tmp) [100%] 3 of 3 ✔
/usr/local/bin is valid!
/tmp/foo is invalid!
/tmp is valid!
```

**Comment by hartzell** [comment]
@stekaz -- Thanks for poking at this.  The solution you shared in [your comment](https://github.com/nextflow-io/nextflow/issues/1733#issuecomment-700384447) is functionally identical to the tuple based answer I posted [in the Gitter thread](https://gitter.im/nextflow-io/nextflow?at=5f6bccda5b75b305ddbf3b0c).

It works, but it involves passing around the tuple and using the branch operator.  Since channels are allowed to be optional, it seems like a cleaner solution to just send the message (pass the value, etc...) down the proper channel and let other remain empty.  Except for the bit where it doesn't work.

**Comment by stekaz** [comment]
@hartzell whoops, sorry about that - I completely missed that one!

Optional outputs are something I would try to avoid as much as possible, especially if you have control over the process that sets these. At least that's the feeling I get from the documentation anyway:

> In most cases a process is expected to generate output that is added to the output channel. However, there are situations where it is valid for a process to not generate output. In these cases optional true may be added to the output declaration, which tells Nextflow not to fail the process if the declared output is not created.

Regardless, the error you get with optional output variables is completely unexpected. I managed to reduce your example case to:

```
nextflow.enable.dsl=2

process test {

    output:
    env(myvalue) optional true

    """
    myvalue=
    """
}

workflow {

    test()
}
```

**Comment by hartzell** [comment]
Well, in the sense of "don't do that, it doesn't work", avoiding optional is good (and appreciated) advice.

On the other hand, coming from the CSP/go channels world, the idiom of process that does some heavy lifting and routes its results down one or another channel is pretty common and powerful.

Relying entirely on proof-by-assertion, I'll claim that it's a clearer way of wiring up this type of network than needing to add a branching channel.

Thanks for thinking about it!
