### ISSUE TITLE
Launch jobs on Alibaba Cloud BatchCompute service

### ISSUE THREAD

**Issue by zhangzhen** [nextflow-io/nextflow#1735]
## New feature

Cromwell from Broad Institute supports launching jobs on Alibaba Cloud BatchCompute service. Is it possible to implement an executor for Alibaba Cloud BatchCompute service?

## Usage scenario 

Our lab is located in China, and Alibaba Cloud is the only option to run workflows on it. We love Nextflow and prefer using it to Cromwell, but without Alibaba Cloud support we would have to switch to Cromwell. Moreover, we believe that most NGS 
labs in China would make the same decision as us.

**Comment by pditommaso** [comment]
This is interesting. Is a new national law requiring to use Alibaba Cloud or other cloud services are never been available?

**Comment by zhangzhen** [comment]
According to the Law, genomic data of Chinese is prohibited to go outside.
View this article "China: concurring regulation of cross-border genomic data sharing for statist control and individual protection", 
URL: https://link.springer.com/article/10.1007/s00439-018-1903-2

**Comment by zhangzhen** [comment]
@pditommaso is there any plan or any progress on that?

**Comment by pditommaso** [comment]
I've drafted a prototype using S3 client to access Alibaba object storage, but unfortunately, it is not 100% compatible with it. This feature is our radar, but I can't bind to any schedule.
