### ISSUE TITLE
skip:0 in the collectFile operator still skips the first line

### ISSUE THREAD

**Issue by zhangzhen** [nextflow-io/nextflow#1736]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

The created file should include the header line, but it didn't.

### Steps to reproduce the problem
```
concat_fastq_ch.into { trimmedFastqFiles; aln_fastq_files }

Channel.from(['RGID','RGSM','RGLB','Lane','Read1File','Read2File'].join(','))
    .set { fastq_list_header }

trimmedFastqFiles.map { row -> [row[0], row[0], 'UnknownLibrary', 1, row[1], row[2]].join(',') }
    .set { fastq_list_body }

fastq_list_header.concat(fastq_list_body)
    .collectFile(name: 'fastq_list.csv', newLine: true, skip: 0)
    .set { fastq_list }
fastq_list.view()
```

### Environment 

* Nextflow version: 20.07.1
* Java version: 8
* Operating system: Centos7
* Bash version: 4.2.46(2)-release

**Comment by zhangzhen** [comment]
The header line is in the created file indeed, but not at line 1 because the sort param defaults to hash. After I disable sorting by setting sort: false, everything works well.

**Comment by stekaz** [comment]
Correct. By default, the output is ordered by the hash number associated with each entry. As you've discovered, you'll need to disable content sorting to ensure that entries are appended as they are produced. E.g.:

```
.collectFile(name: 'fastq_list.csv', newLine: true, sort: false)
```

https://www.nextflow.io/docs/latest/operator.html#collectfile
