### ISSUE TITLE
Google Life Sciences Resource Limit in Zone

### ISSUE THREAD

**Issue by r0f1** [nextflow-io/nextflow#1737]
Hi,
I am using the Google Life Sciences API and some of my processes require a GPU (either P4, T4 or V100, but preferably T4 because they are the cheapest). These GPUs are available in the zones `europe-west4-b` and `europe-west4-c`, so I specified the region `europe-west4`. My `nextflow.config` looks like this:
```
google {
    project = "myproject"
    region = "europe-west4"
    
    lifeSciences {
        bootDiskSize = "200 GB"
        debug = true
        preemptible = false
    }
}
...

process {
    ...
    withLabel: with_gpu {
        accelerator = [request: 1, type: 'nvidia-tesla-t4']
        containerOptions = "--gpus all"
    }
}
```
Today there are no Tesla T4s available and I get the following error during execution:
```
WARN: Google Pipelines > A resource limit has delayed the operation: generic::resource_exhausted: 
The zone 'projects/myproject/zones/europe-west4-b' does not have enough resources available
to fulfill the request.  '(resource type:compute)'.
```

Q1: Will nextflow automatically retry in zone `europe-west4-c`? If not, how can I ask it to do that?
Q2: Is there any easy way of telling nextflow that if T4 GPUs are not available, take P4 GPUs instead?

Thank you, Florian

**Comment by pditommaso** [comment]
> Will nextflow automatically retry in zone europe-west4-c? If not, how can I ask it to do that?

Nope the region is picked by Google, as long as you are not specifying it 

> Is there any easy way of telling nextflow that if T4 GPUs are not available, take P4 GPUs instead?

You can use the usual dynamic directive approach as described here 

https://www.nextflow.io/docs/latest/process.html#dynamic-computing-resources

**Comment by r0f1** [comment]
Thank you!
