### ISSUE TITLE
"pasteFile()" operator:  like "collectFile()" but combines files by columns.  

### ISSUE THREAD

**Issue by alanhoyle** [nextflow-io/nextflow#1739]
## New feature

pasteFile() operator that combines multiple files by appending columns. 

## Usage scenario 

We have several processes that create files that create delimited files where each row is a data point and each column is a the value of that data point in a separate sample.  We would like to merge these files together to add multiple sample columns into a single file to build a single matrix.  

If each file contains the same number and order of rows and the same columns, this is an easy-ish thing to do using the unix `cut` and `paste` commands, but it would be nice to have something integrated that added features like `collectFile()`does.  

For example, this type of file combination comes up in gene expression (each row is a gene, each column is the expression measured) or cross-genome read counts (each row is a genomic region/interval and each column is the number of reads found at each of those interval in the samples).

Expression:  

SAMPLE1.expression.txt:  

Name  |  NumReads
----- | -----
DDX11L1 | 1
WASH7P | 123.34
MIR6859-3  |     54.32
RP11-34P13.3 |   0
MIR1302-9     |  0  

SAMPLE2.expression.txt:  

Name  |  NumReads
----- | -----
DDX11L1 | 3.1415
WASH7P | 9.2653
MIR6859-3  |     0
RP11-34P13.3 |   9876.5
MIR1302-9     |  2.7182

merged.expression.txt:

Name  |  SAMPLE1 | SAMPLE2
----- | ----- | -----
DDX11L1 | 1 | 3.1415
WASH7P | 123.34 | 9.2653
MIR6859-3  |     54.32 | 0
RP11-34P13.3 |   0 | 9876.5
MIR1302-9     |  0  | 2.7182

### BED-like example:

SAMPLE1.bed
chr | start | end | count
--- | --- | --- | --- 
chr1 | 0 |10000 | 1
chr1 | 10000 |20000 | 23
chr1 | 20000 |30000 | 456

SAMPLE2.bed
chr | start | end | count
--- | --- | --- | --- 
chr1 | 0 |10000 | 7
chr1 | 10000 |20000 | 89
chr1 | 20000 |30000 | 1011

merged.bed
chr | start | end | SAMPLE1.bed | SAMPLE2.bed
--- | --- | --- | --- |--- 
chr1 | 0 |10000 | 1 | 7
chr1 | 10000 |20000 | 23 | 89
chr1 | 20000 |30000 | 456 | 1011

## Suggest implementation 

 `collectFile()` provides a good beginning overlay for this implementation.  The key differences would be the number of frozen columns at the beginning of each line (In the above examples, one for expression, and three for BED-like).  

Two additional parameters I think it needs would be:  

`frozenColumns: <string>`:   The columns that would be the same in each file.
`dataColumns: <string>`:  the columns that would be  copied from each file.

In both parameters, the <string> would be defined the same way they are in the unix `cut` command, with comma separated numbers and ranges.  

I think there should also be a parameter for the columnHeader that would be based on the file or sample's name somehow.  

Expression example:  
```
pasteFile(name: "expression.txt", 
    frozenColumns: "1", 
    dataColumns: "2",
    columnHeader: 'filename')
```

Unix equivalent:  `paste <( cut -f 1 SAMPLE1.expression.txt) <(cut -f 2 SAMPLE1.expression.txt) <(cut -f 2 SAMPLE2.expression.txt)`

BED-like example:  
```
pasteFile(name: "merged.bed", 
    frozenColumns: "1-3", 
    dataColumns: "4",
    columnHeader: 'file.name.lastIndexOf(".")')
```

Another possible implementation would be to have a `transposeFile()` which takes a delimited file and turns columns into rows and rows into columns.  Then you could do transposeFile(), collectFile(), and then transposeFile() back, but that might only work well for the simplest cases.

**Comment by alanhoyle** [comment]
transposeFile() could work if there was an "addColumn: '<STRING>'" that let you add a column that contained the same text on every line....

**Comment by pditommaso** [comment]
This a not trivial problem as the size of the collect data grows. it would require the use of a separate.

**Comment by alanhoyle** [comment]
I assume you are going to say "separate process" there.  Even that being the case, it would be a useful feature.

**Comment by pditommaso** [comment]
Oops, I've forgotten some pieces in the reply... I mean, it would require a separate db to track and recreate the columnar structure.

**Comment by stevekm** [comment]
you might be interested in my `concat-tables.py` script for pasting tables together like this;

https://github.com/NYU-Molecular-Pathology/NGS580-nf/blob/master/bin/concat-tables.py

(slightly newer version here that includes handling of `#` header lines e.g. in vcf files https://github.com/mskcc/helix_filters_01/blob/master/bin/concat-tables.py )

I think it does pretty much exactly what you are requesting. As you pointed out, a lot of the functionality is implemented with `collectFile()`. 

For your second issue of adding the same value in a separate column (e.g. adding a SampleID column to a table) you might also want to check out my `paste-col.py` script;  

https://github.com/NYU-Molecular-Pathology/NGS580-nf/blob/master/bin/paste-col.py
