### ISSUE TITLE
storeDir fails accessing globals in DSL2

### ISSUE THREAD

**Issue by loipf** [nextflow-io/nextflow#1748]
### Expected behavior and actual behavior
DSL2: I would expect `storeDir`  to be able to access global parameter `params.data_dir` in 
`storeDir params.data_dir, mode: "copy"`
as it is for
`publishDir params.data_dir, mode: "copy"`
but it fails.

### Steps to reproduce the problem

run nextflow on following main.nf
(files also in appendix with .log output)
[nf_min_example.zip](https://github.com/nextflow-io/nextflow/files/5327734/nf_min_example.zip)

**main.nf:**
```
nextflow.enable.dsl=2

include { 
	TEST_publishDir;
	TEST_storeDir
} from './modules.nf' 

params.data_dir = "$projectDir/data"


workflow {
	TEST_publishDir()
	TEST_storeDir()  // ERROR: Unknown method invocation `toAbsolutePath` on ArrayList type
}

```

**modules.nf:**
```
params.data_dir = "$projectDir/data"   // site question: anyway to avoid the double declaration ? 


process TEST_publishDir {
	publishDir params.data_dir, mode: "copy"

	output:
		path("file_publishDir.txt")
		
	shell:
	'''
        echo 'Hello world!' > file_publishDir.txt
        '''
}


process TEST_storeDir {
	storeDir params.data_dir, mode: "copy"    // <- ERROR SOURCE

	output:
		path("file_storeDir.txt")
		
	shell:
	'''
        echo 'Hello world!' > file_storeDir.txt
        '''
}
```

### Program output 
`Unknown method invocation toAbsolutePath on ArrayList type`

### Environment 

* Nextflow version:   Version: 20.07.1 build 5412
* Java version: openjdk 11.0.8 2020-07-14
* Operating system: Linux
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by stevekm** [comment]
does `storeDir` support `mode: "copy"`? I got the same error (`Unknown method invocation toAbsolutePath on ArrayList type`) when trying to use [another unsupported parameter](https://github.com/nextflow-io/nextflow/issues/1769)
