### ISSUE TITLE
Remove single processed files before the end of the whole process

### ISSUE THREAD

**Issue by basiliscus79** [nextflow-io/nextflow#1754]
Hello Paolo, I aim at using the nf-core/smrnaseq pipeline for analysis of 100 small-RNAseq fastq files.
In an attempt to keep the output size as low as possible during the pipeline I added the following process to the 'main.nf' file:

```
/* REMOVE LARGE FILES
 *
 */
process remove_largefiles {	
    input:
	file sorted_bams from miRBase_bam_del.collect()
	file hairpin_bams from miRBase_hairpin_collapse_bam_del.collect()
	file mature_bams from miRBase_mature_bam_del.collect()
	file bowtie_bams from bowtie_bam_del.collect()
	file bowtie_unmap_bams from bowtie_bam_for_unmapped_del.collect()
	
    shell:
    """
    #!/usr/bin/env bash

    find ${launchDir}/work/ -type f \\
        -o \\( -name "*.mature.bam" -o -name "*.mature.sorted.bam" \\
        -o -name "*.hairpin.bam" -o -name "*.hairpin.sorted.bam" \\
        -o -name "*.genome.bam" -o -name "*.genome.sorted.bam" \\) \\
        | grep "[sorted,genome,mature,hairpin].bam" | xargs rm

    rm -rf ${launchDir}/work/stage/* && rmdir ${launchDir}/work/stage
    
    rm -rf ${params.outdir}/bowtie_ref/*.genome.bam

    rm -rf $PWD/*.bam
    """
}
```

In summary, I duplicated specific/desired outputs and used them as inputs for my custom file removal process so as to make sure that the files I want to remove are not deleted before they are needed in another process.
I tested this on a couple of files and it does work, since I get a 50% reduction in the final output size. Nonetheless, if monitoring the size of the destination folders (mostly work dir) it looks like both files are removed at the very end of the pipeline, only after both of them have been processed by upstream processes.
Of course this is in line with what is written in the code and what I also have written, but my question is the following:
-Is there any way to allow files to be removed individually before the completion of a specific process on all the input files, i.e. as soon as each output file is generated and if it is not marked as input for other processes?
In other words, is there any way to make a downstream process begin anyways on part of the input files even if the collection of the input files is not completed? In my head (and probably/fortunately just over there...) this would allow me i) to begin collection of the first n processed files way before the upstream job has completed on all upstream input files and ii) delete unnecessary files while others are still being processed, thus clearing up storage space for new files to be processed.

I am new to nextflow and probably I am missing some fundamentals of it, so I apologize if am making non-sense questions and thank you a lot for the time you will dedicate to a reply.

Best
Michele

**Comment by pditommaso** [comment]
This is an old issue that still needs to be addressed. See #452. 

So far the best way to mitigate this problem is to set `process.scratch=true` in nextflow.config file which will case NF to use a local scratch directory that automatically deletes all non-input/output files and avoid to use remote data files (ie http:, s3, etc)

**Comment by basiliscus79** [comment]
Thanks so much, I do appreciate it. Nextflow is a fabulous tool!

Michele
