### ISSUE TITLE
workflow.container does not work in a DSL2 module

### ISSUE THREAD

**Issue by sidorov-si** [nextflow-io/nextflow#1758]
## Bug report 

`workflow.container` prints an empty map (`[:]`) instead of a container name if used in a DSL2 module.

### Expected behavior and actual behavior

Print the name of the container used in a module, i. e. `quay.io/biocontainers/fastqc:0.11.9--0` in the example below. Instead, it prints an empty dictionary (`[:]`).

### Steps to reproduce the problem

DSL2 module (`fastqc.nf`):

```
#!/usr/bin/env nextflow

// Specify DSL2
nextflow.enable.dsl=2

// Process definition
process fastqc {

    container 'quay.io/biocontainers/fastqc:0.11.9--0'

    script:
    println("FastQC container: ${workflow.container}")
    """
    fastqc -v
    echo ${workflow.container}
    """
}
```

The main script that calls the module (`main.nf`, in the same directory as `fastqc.nf`):

```
#!/usr/bin/env nextflow

// Define DSL2
nextflow.enable.dsl=2

include { fastqc } from './fastqc.nf'

workflow {
    fastqc()
}
```

Config file (`nextflow.config`, in the same directory as `fastqc.nf` and `main.nf`):

```
docker.enabled = true
```

Command to run the example (invoke in the directory where the scripts are):

```
nextflow run main.nf
```

### Program output 

In `.command.out`:

```
FastQC v0.11.9
[:]
```

In stdout:

```
N E X T F L O W  ~  version 20.07.1
Launching `main.nf` [sleepy_gilbert] - revision: d301af5ec9
FastQC container: [:]
executor >  local (1)
[e8/3206f6] process > fastqc [100%] 1 of 1 ✔
```

Attached please find [.nextflow.log](https://github.com/nextflow-io/nextflow/files/5378292/default.nextflow.log)

### Environment 

* Nextflow version: 20.07.1.5412
* Java version: "11.0.1" 2018-10-16 LTS
* Operating system: macOS
* Bash version: 3.2.57(1)-release (x86_64-apple-darwin17)

### Additional context

I guess that `workflow.container` was introduced in DSL1 to report a container (or a dictionary of containers) from the whole pipeline. But in DSL2 it would be useful to be able to report names of containers from individual modules to log these names as part of a pipeline run summary.

**Comment by pditommaso** [comment]
This is not a DSL2 specific issue. It also happens with 

```
// Process definition
process fastqc {

    container 'bash'

    script:
    println("FastQC container: ${workflow.container}")
    """
    echo ${workflow.container}
    """
}
```

**Comment by KevinSayers** [comment]
`task.container` gives the container for a specific process. This works, and is what you want to use. 

`workflow.container` works if one container is specified for the entire workflow in config `process.container= 'ubuntu'`. There still is a bug if you specify more than one as below, then you still get the empty map. 

```
process {
    withName: foo {
        container = 'ubuntu'
    }
    withName: bar {
        container = 'ubuntu'
    }
}
```

**Comment by pditommaso** [comment]
To access the `container` property in a reflective manner from the process itself, it should be used `task.container`. The property `workflow.container` is mean to collect the container used during the overall execution
