### ISSUE TITLE
OAR Executor: CMD_OUTFILE instead of CMD_LOG

### ISSUE THREAD

**Issue by grafitos** [nextflow-io/nextflow#1761]
## Bug report 

In the OAR executor, 

https://github.com/nextflow-io/nextflow/blob/603343c1f2ddbc7d15594feaf89c8ce5df12753f/modules/nextflow/src/main/groovy/nextflow/executor/OarExecutor.groovy#L45

CMD_OUTFILE is used instead of CMD_LOG

### Program output 

On task error event (in my case): 

.nextflow.log.3:Oct-15 09:50:16.734 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_data_nfs/BIO_INFO/SCRATCH/PUBLIC/anatoleflow/work/bc/33d671b765bfcb5e91d31e95e40360/.command.log

### Environment 

* Nextflow version: 20.04.1-all 
* Java version: 1.8
* Operating system: Centos
* Bash version: 4.2.46(2)-release

**Comment by pditommaso** [comment]
Indeed, you are right. Also, the error should not be there, because that file is written by the task wrapper

https://github.com/nextflow-io/nextflow/blob/603343c1f2ddbc7d15594feaf89c8ce5df12753f/modules/nextflow/src/main/groovy/nextflow/executor/OarExecutor.groovy#L46

Any idea if OAR can redirect both stdout and stderr to the same file?

**Comment by grafitos** [comment]
Hi Paolo,

You are right, this error leaded me to find this issue, but it is not necessary correlated.

"that file is written by the task wrapper": 
do you mean GridTaskHandler.groovy ?

If true, the constructor do not create CMD_LOG:
        this.startFile = task.workDir.resolve(TaskRun.CMD_START)
        this.exitFile = task.workDir.resolve(TaskRun.CMD_EXIT)
        this.outputFile = task.workDir.resolve(TaskRun.CMD_OUTFILE)
        this.errorFile = task.workDir.resolve(TaskRun.CMD_ERRFILE)
        this.wrapperFile = task.workDir.resolve(TaskRun.CMD_RUN)

=> no CMD_LOG ?

About the redirection, I didn't find any option to do that:

 -O  --stdout=<file>           Specify the file that will store the standart
                               output stream of the job.
                               (the %jobid% pattern is automatically replaced)
 -E  --stderr=<file>           Specify the file that will store the standart
                               error stream of the job.
                               (the %jobid% pattern is automatically replaced)


Thanks.

**Comment by pditommaso** [comment]
No, I mean the `.command.out` and `.command.err` are written by the job wrapper created by NF 

https://github.com/nextflow-io/nextflow/blob/671ae6d85df44f906747c16f6d73208dbc402d49/modules/nextflow/src/main/resources/nextflow/executor/command-run.txt#L122-L123

Instead, the cluster should write both stdour and stderr to the .command.log file. Look for example, SGE 

https://github.com/nextflow-io/nextflow/blob/e94e6877c2dc9bed983e873b62e302a08843c891/modules/nextflow/src/main/groovy/nextflow/executor/SgeExecutor.groovy#L40-L41

In this case the `-j y` (join) is the option that does the trick of merging both (out and err). Do you have any chance to interact to with folks of OAR to understand how to manage it properly?

**Comment by pditommaso** [comment]
Any feedback on stdout and stderr merging capability?

**Comment by chrstphdm** [comment]
Why not using the same file with the 2 options ?

``` groovy
result << '-O' << quote(task.workDir.resolve(TaskRun.CMD_LOG))     
result << '-E' << quote(task.workDir.resolve(TaskRun.CMD_LOG))  
```

I had a try with `oarsub` and a small bash script doing good and bad things and it seems to work well...
```bash
oarsub -E "test.log" -O "test.log" -S "./test_oar.sh
cat test.log
this is an echo
./test_oar.sh: line 3: thisisabadcommand: command not found
```

**Comment by grafitos** [comment]
Hi Paolo, 

I was unable to find such option. I have opened an issue (enhancement): https://github.com/oar-team/oar/issues/179

**Comment by pditommaso** [comment]
Nice to see OAR team in on GH! 

> Why not using the same file with the 2 options?

It depends on how it's implemented under the cover, if it's expecting different files it would open both in read-write mode and fail. From what you are observing it seems the check for that. 

If somebody from OAR can confirm, I'm happy to merge the patch you are proposing.

**Comment by pditommaso** [comment]
Is there any update on this?

**Comment by chrstphdm** [comment]
Has been added in the next millestone (25% done).....
in a more personal way, I'm scared 😭  because I don't know when I'll find the time to update OAR

**Comment by pditommaso** [comment]
What we can do is patching it to at least capture one of the `stdout` to the log file and then add the support for the redirect once available. 

Does make sense?

**Comment by npf** [comment]
> If somebody from OAR can confirm, I'm happy to merge the patch you are proposing.

I confirm: the file is opened in append mode for both stdout and stderr. It should just work. If not please reopen the issue at oar-team/oar#179

**Comment by pditommaso** [comment]
Fair enough. Patched.
