### ISSUE TITLE
Escape newlines for env and script fields in trace

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#1765]
## Bug report 

The execution trace now includes the `env` and `script` fields, which provide the environment variables and command script for the task. However these fields can contain newlines which make the trace file unusable. These fields should be sanitized so that newlines are escaped (\n) before they are saved to the trace file.

**Comment by pditommaso** [comment]
Reformatting the script will essentially break it or make it unreadable. 

Theidea for text-based fields is to use them along with a template so that you can reformat as you wish. See 
 https://www.nextflow.io/docs/latest/tracing.html#templates

**Comment by bentsherman** [comment]
I see how this template is used with `nextflow log`, but I fail to see how you would use it when running a workflow. The example template references the script but it cannot reformat the script itself.

It should be possible to escape newlines out of the script without breaking everything else. You only need to to it right before it is appended to the execution trace.

**Comment by bentsherman** [comment]
The weblog is already doing this for both `script` and `env`:
```
  "trace": {
    "task_id": 7,
    "status": "RUNNING",
    "hash": "bc/d286a2",
    "name": "multiqc",
    "exit": 2147483647,
    "submit": 1598626438129,
    "start": 1598626469319,
    "process": "multiqc",
    "tag": null,
    "module": [],
    "container": "gemmaker/multiqc:1.8-1.1",
    "attempt": 1,
    "script": "\n    multiqc       --ignore /workspace/_workflows/5f481cb6fb85351b082b811d/output/GEMs       --ignore /workspace/_workflows/5f481cb6fb85351b082b811d/output/reports       /workspace/_workflows/5f481cb6fb85351b082b811d/output\n    ",
    "scratch": null,
    "workdir": "/workspace/_workflows/5f481cb6fb85351b082b811d/work/bc/d286a2e32d1dba19f831deb0bb4223",
    "queue": null,
    "cpus": 1,
    "memory": 1073741824,
    "disk": null,
    "time": null,
    "env": "PATH=/workspace/projects/systemsgenetics/gemmaker/bin:$PATH\n",
    "native_id": "nf-bcd286a2e32d1dba19f831deb0bb4223"
  }
```

**Comment by pditommaso** [comment]
> The example template references the script but it cannot reformat the script itself.

the template is a *groovy* template, therefore you can use groovy/java expression eg 

```
${script.replace(/\n/,'')}
```

(not tested) 

The weblog does because the field content is serialized to make JSON friendly

**Comment by bentsherman** [comment]
> The weblog does because the field content is serialized to make JSON friendly

That's the point I'm trying to make for the trace file. The script and env fields need to be made CSV-friendly. These fields are available for the execution trace but there is no way to use them without escaping newlines, so why shouldn't Nextflow do that automatically, as it does for the weblog?

I understand what you're saying about the template but I still don't see how you would use it specifically to control the trace file.

**Comment by pditommaso** [comment]
Well, the trace was thought for runtime information. The `script` tends to be a quite large field that was not meant to be included in the trace. Also escaping `\n`, if the script contains a command would still break it.

**Comment by bentsherman** [comment]
In that case it would probably be better to remove them from the list of trace fields. As it stands, `script` and `env` are not usable anyway because they break the trace file.

**Comment by lishengting** [comment]
This issue isn't solved! Any suggestions?
