### ISSUE TITLE
AWS Batch support for retryStrategy

### ISSUE THREAD

**Issue by maxbates** [nextflow-io/nextflow#1780]
## New feature

AWS Batch recently added a feature to define a retryStrategy, so that when a job fails for specified reasons or under specified conditions, it can be automatically restarted.

https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#retryStrategy

## Usage scenario 

This strategy is defined on job submission, and so can only be applied to head nodes. It would be helpful to apply these strategies to process nodes (whose job definitions are defined by nextflow). 

One scenario would be automatically restarting a node running on a spot instance that fails only because the instance terminates. 

It may make sense to circumvent nextflow's retry count or dynamic directives under such circumstances.

## Suggest implementation 

Nextflow should attach the retryStrategy to the job definitions it creates.

Such a strategy may be difficult to specify in the config file or as a process directive...

**Comment by pditommaso** [comment]
Nextflow [maxRetries](https://www.nextflow.io/docs/latest/process.html#maxretries) is already mapped to AWS Batch retry strategy (provided no nextflow `errorStrategy` is specified).

**Comment by astatham** [comment]
@pditommaso as I understand it currently if I wish to use the AWS Batch retry strategy, this means I cannot also use  [automatic RAM scaling](https://www.nextflow.io/blog/2016/error-recovery-and-automatic-resources-management.html), is this correct?

What I think would be useful is a new option to use AWS Batch retries for spot terminations, and NF retry for all other terminations by populating the "evaluateOnExit" array of a jobs retryStrategy- see the "Spot instance interruptions" section of https://aws.amazon.com/blogs/compute/introducing-retry-strategies-for-aws-batch/

Would you be open to a PR contributing code for this?

**Comment by pditommaso** [comment]
> this means I cannot also use automatic RAM scaling, is this correct?

Exactly, because the retry is managed directly by Batch therefore NF is not aware of it. 

> What I think would be useful is a new option to use AWS Batch retries for spot terminations, and NF retry for all other terminations

That can be useful, however still thinking it would be better NF also handle spot termination, because this allows assigning the task a new work directory and discard all previous partial computed results. 

> Would you be open to a PR contributing code for this?

Sure, tho more inclined for the latter solution.

**Comment by MrOlm** [comment]
Just wondering if there's any update on this or if anyone has a workaround- would love to be able to use spot instances and automatic RAM scaling, but currently that's not really an option

**Comment by mribeirodantas** [comment]
Nextflow provides automatic task error handling. You can read more about it [here](https://www.nextflow.io/docs/latest/reference/process.html#errorstrategy). You can also dynamically scale resource requests based on errors. Read more about dynamic directives [here](https://www.nextflow.io/docs/latest/process.html#dynamic-directives).
