### ISSUE TITLE
Nested process composition

### ISSUE THREAD

**Issue by fmorency** [nextflow-io/nextflow#1781]
## New feature

Ability to compose a process using multiple other processes

## Usage scenario 

Consider the following DSL2 pipeline
```
process.scratch = true
 
process foo {
    input:
    path x
 
    output:
    path "bigfile"
 
    script:
    """
    do_something $x > bigfile
    """
}
 
process bar {
    input:
    path bigfile
 
    output:
    path "y"
 
    script:
    """
    do_something_else $bigfile > y
    """
}
 
workflow my_pipeline {
    x = Channel.fromPath("/tmp/foo")
    foo(x) | bar()
}
```

where bigfile is an multi-gigabytes file produced by foo. Launching this workflow will execute the following chain of event

1. Path x will be transferred from storage unit to a compute node A
2. A will process x, resulting in path bigfile on A local disk
3. Path bigfile will be transferred back to storage unit
4. Path bigfile will be transferred from storage unit to a compute node A' (depending on the cluster setup, A' can result being A again)
5. A' will process bigfile, resulting in path y on A' local disk
6. Path y will be transferred back to storage unit.

It would be nice if one could somehow force foo and bar to be executed on the same node, while avoiding

1. transferring bigfile back and forth the storage unit,
2. manually defining a third process foobar, merging foo and bar together, such as
```
process foobar {
    input:
        path x
    output:
        path "y"
    script:
    """
    do_something $x > bigfile
    do_something_else bigfile > y
    """
}
```
The above pipeline wastes unnecessary bandwidth and storage if A' == A. 

Combined with issue #452 this feature could save both storage and bandwidth, especially for big workflows and big datasets. It would also ease code re-usability across pipelines.

## Suggest implementation 

One could think of a DSL2 syntax enhancement that would allow "linking" multiple processes together. A "virtual process" could then be automatically created and submitted to the cluster
```
process foo {
  ...
}
 
process bar {
  ...
}
 
process foobar {
  foo() | bar()
}
 
workflow my_pipeline {
  foobar()
}
```

**Comment by pditommaso** [comment]
You can do this by writing two Bash wrappers for your commands and invoking with the same process.

**Comment by fmorency** [comment]
Thanks for the answer @pditommaso . Is the following the kind of thing you are suggesting?

```
#!/usr/bin/env nextflow
nextflow.enable.dsl=2

process Y {
    input:
    val x

    output:
    path "Y", emit: y

    script:
    """
    emit_y.sh $x
    """
}

process Z {
    input:
    val y

    output:
    path "Z", emit: z

    script:
    """
    emit_z.sh $y
    """
}

process YZ {
    input:
    val x

    output:
    path "Z", emit: zz

    script:
    """
    emit_y.sh $x
    emit_z.sh Y
    """
}

workflow {
    data = Channel.from(1, 2, 3, 4, 5, 6, 7)
    Y(data)
    Z(Y.out.y).view()
    YZ(data).view()
}
```

and where `emit_y.sh` is
```
#!/bin/bash
echo $1 Y > Y
```

and where `emit_z.sh` is
```
#!/bin/bash
echo $(cat $1) Z > Z
```

**Comment by mjhipp** [comment]
I would also be interested in this feature. Either as a nested process as @fmorency suggested above, or a trigger at the workflow level in DSL2. 

```nextflow
workflow foobar {
  singleNode: true // or a better name, default to false
	
  take: x

  main:
	foo(x) | bar()

  emit: bar.out
}

This would allow the user to have certain sub-workflows that they would like to run on one node (I imagine this would be passed down from parent workflows if `true`).

The use case that I am interested in is when I have a very large file and I would like to call several metrics collection processes on that same file. It would be great to have this option rather than download to several nodes or compose one process that calls many tools.
