### ISSUE TITLE
Support for FSx Lustre on AWS Batch

### ISSUE THREAD

**Issue by maxbates** [nextflow-io/nextflow#1783]
## New feature

The executor `awsbatch` errors if you attempt to use a working directory outside of S3:

```
When using `awsbatch` executor a S3 bucket must be provided as working directory either using -bucket-dir or -work-dir command line option
```

As far as I can tell, this prevents the use of FSx Lustre on Batch.

## Usage scenario 

To use FSx Lustre with Nextflow Batch jobs.

## Suggest implementation 

The "enterprise" version of nextflow (at least, using Tower) supports Lustre - could you bring that support to the public release? Or document what configuration changes are necessary to use Lustre on AWS Batch? Thanks!

**Comment by pditommaso** [comment]
The support for FSx is provided by [Seqera Labs](http://seqera.io/) as a commercial plugin for Nextflow or deploying your pipeline through tower.nf. Currently, there's no plan to include it in the main codebase.
