### ISSUE TITLE
Oar executor performance : queueStatusCommand improvement

### ISSUE THREAD

**Issue by chrstphdm** [nextflow-io/nextflow#1785]
Hello,

We are using intensively the OAR executor. Thanks to @valleema  and @pditommaso  for this !
I think we could do better in the `queueStatusCommand()` time call.

Here a quick benchmark with the actual `oarstat`call from `queueStatusCommand` with our small 200 000 jobs database history ( https://github.com/nextflow-io/nextflow/blob/5c131d7ce32d54639c99544a5f6cabbfeef8188d/modules/nextflow/src/main/groovy/nextflow/executor/OarExecutor.groovy#L132) : 

```bash
time oarstat -f | egrep '(Job_Id:|state =)'
[..]
real    0m12.123s
user    0m1.354s
sys     0m0.747s
```

Here a workaround using `awk` (considering it as a part of POSIX and installed by default in all modern unix/linux) : 

```
time oarstat | awk '{print "JobId: " $1 "\nstate = " $2 }' -
[..]
real    0m0.297s
user    0m0.218s
sys     0m0.064s
```

What do you think ?

**Comment by pditommaso** [comment]
Impressive difference! but it's really necessary to fetch all the history?

**Comment by valleema** [comment]
Actually, I got the idea from other schedulers' code : https://github.com/nextflow-io/nextflow/search?q=egrep+%27%28Job+Id%3A%7Cjob_state+%3D%29%27

I just tried it on the cluster I used:

```sh
time oarstat -f | egrep '(Job_Id:|state =)'
[..]
real    0m0.583s
user    0m0.320s
sys     0m0.040s
```
and 
```sh
time oarstat | awk '{print "JobId: " $1 "\nstate = " $2 }' -
[..]
real    0m0.232s
user    0m0.200s
sys     0m0.020s
```

It is not as dramatic as you, but still half.

On my cluster, `oarstat` does not fetch the whole history, only running and pending jobs.

**Comment by pditommaso** [comment]
yeah, but other schedulers do not return ALL executed jobs since the dawn of time .. 😅

**Comment by chrstphdm** [comment]
Actually, the `oarsub -f` command get full informations for all the jobs. The `- f` option generate unused informations and this is it that cause my troubles. man page of the `oarstat` contain advices to print information from a specific job with the `state` option, as it call an minimal query to the database. 

I know well slurm as our old batch scheduler and the `squeue` command [used by the executor](https://github.com/nextflow-io/nextflow/blob/553c3119cc81012c3c4667ba280f174b0a7c7f8b/modules/nextflow/src/main/groovy/nextflow/executor/SlurmExecutor.groovy#L127) do pretty the same thing : it get all the jobs informations available BUT a retention rule in the slurmdbd server keep jobs data for a limited number/period (PurgeJobAfter option).  

So, if the retention rule is too large (because your admin want to keep a big history for traceability purpose or any other reason that would cause him to just bug the developers 🤣 ), you could have the same optimisation problem and i'm pretty sure that people must have come across this optimisation problem without knowing it.

it's a pity because the `squeue`man page advises there again to restrict query by jobid : 
>"Performance of the command can be measurably improved for systems with large numbers of jobs when a single job ID is specified."

I may have a piecemeal view of it all but I can see in the AbstractGridExecutor that functions [checkStartedStatus(jobId, queueName )](https://github.com/nextflow-io/nextflow/blob/553c3119cc81012c3c4667ba280f174b0a7c7f8b/modules/nextflow/src/main/groovy/nextflow/executor/AbstractGridExecutor.groovy#L342) and [checkActiveStatus(jobId, queueName )](https://github.com/nextflow-io/nextflow/blob/553c3119cc81012c3c4667ba280f174b0a7c7f8b/modules/nextflow/src/main/groovy/nextflow/executor/AbstractGridExecutor.groovy#L365) call `getQueueStatus(queueName)`.

In these 2 functions, why not using `jobId` as a parameter as `getQueueStatus(queueName,jobId)`.
In this way, we should be able to be more efficient for all the executors by using specific jobId command when it's possible.

By doing this, in oar case, we could call `oarsub -s -i ${jobId}`
In slurm case it should be `squeue --noheader -o %i %t' -t all -j ${jobId}`
etc.

In the worst case (if no option to select information for a specific jobId is available for an executor), `getQueueStatus(queueName,jobId)` content do not have to be modify.

**Comment by pditommaso** [comment]
Querying for the single job would mean to execute a separate process for *each* single job that can be MANY. Not sure it's a good idea. 

Is it not possible to filter the queue status for a specific user and queue names?

**Comment by chrstphdm** [comment]
It is.
And actual code already manage presence/absence of queue name :
https://github.com/nextflow-io/nextflow/blob/5c131d7ce32d54639c99544a5f6cabbfeef8188d/modules/nextflow/src/main/groovy/nextflow/executor/OarExecutor.groovy#L133
But default queue can be big enought to slow down `queueStatusCommand`

It is possible to filter by user with `oarstat -c --sql "job_user='joe.biden'". 
Note that the option `-c` gives a compact result and `parseQueueStatus` should be adapted.
This is the best solution i've found after doing many tests with other options.

**Comment by pditommaso** [comment]
This sounds good to me, however, I have no means to tests it. I'd suggest you create a patch and make a pull request once you have tested it.
