### ISSUE TITLE
Clarify documentation for local execution and resource management

### ISSUE THREAD

**Issue by ewallace** [nextflow-io/nextflow#1787]
Important information about resource limits for local execution are in github issue tickets, but need to be in the documentation. It took me an hour of googling to find them.

In issue #294, @juliangkr and @pditommaso discussed that for multi-threaded applications in processes, the number of threads spawned may exceed the resources specified in local execution. This is reported to still be a problem by #1548. And I think it's causing my nextflow pipeline to crash.

[Local executor documentation](https://www.nextflow.io/docs/latest/executor.html#local) is minimal.

[Configuration, Scope _executor_](https://www.nextflow.io/docs/latest/config.html#scope-executor) gives examples of local executor settings, but doesn't explain that the resources requested might exceed this.

[FAQs doesn't mention it](https://www.nextflow.io/docs/latest/faq.html?highlight=faqs).

I suggest that this problem is mentioned in both Scope _executor_, and in the Local executor documentation, and explained fully in FAQs, which should be linked to from those.

If you can correct interpretation and location, I can put in a pull request.

### Suggested phrasing (adapted from #294)

For example, to use a local executor with at most 4 cpus and 16GB memory, add to your configuration file: 
```
executor {
    name   = 'local'
    cpus   = 4
    memory = '16GB'
}
```

**Warning:** if your pipeline tasks are specifying a multi-thread application, unless you explicitly specify the task cpus, it is possible that each of them will try to use all the available cpus. In this case, the total number of cpus could exceed the number specified by the executor. Essentially, nextflow only "knows" how many tasks to run, and some of your tasks may request more resources than nextflow expects.

Multi-thread applications usually have a command line option to specify the the max cpus that it must be used. For example, [bowtie2](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml) has the `-p/--threads` option, [cutadapt](https://cutadapt.readthedocs.io/en/stable/guide.html) has the `-j/--cores` option, and so on.

You may need to restrict the resources available to specific processes using the `process` configuration scope, see [Scope _process_](https://www.nextflow.io/docs/latest/config.html#scope-process).

HELP: is it possible for a multi-thread application to request more resources than the `process` configuration scope allows? What should documentation say here?

**Comment by pditommaso** [comment]
>  is it possible for a multi-thread application to request more resources than the process configuration scope allows? What should documentation say here?

Nextflow does not enforce resource allocation or provide resource isolation (neither containers do), therefore if your process declares, for example, 2 cpus and the task uses 20 you will overload the running node.
