### ISSUE TITLE
Problems restarting jobs with increased resources.

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#179]
Hi there,

I'm attempting to get jobs to restart automatically if they fail with lack of time or memory, as described in [Dynamic computing resources](http://www.nextflow.io/docs/latest/process.html#dynamic-computing-resources), but I'm getting some strange behaviour.

I have the following simplified test pipeline to replicate my weird behaviour:

```groovy
#!/usr/bin/env nextflow

process test_resources {
    tag "$code"
    
    memory { 5.MB * task.attempt }
    time { 2.m * task.attempt }
    errorStrategy { task.exitStatus == 143 ? 'retry' : 'terminate' }
    maxRetries 3

    input:
    val code from 'alpha', 'gamma', 'omega'

    output:
    file '*.txt'

    """
    echo "Run attempt ${task.attempt} - $code"
    echo "Run attempt ${task.attempt}" > ${code}.txt
    sleep 3h
    """
}
```

Note that the error code I seem to get for both memory and timeouts with SLURM is `143` instead of the `140` mentioned in the docs..

I get the following `stdout` when running the test pipeline:
```
~/nxtflow_taskattempt » nextflow run nxtflow_taskattempt.nf
N E X T F L O W  ~  version 0.18.3
Launching nxtflow_taskattempt.nf
[warm up] executor > slurm
[6b/d3d59e] Submitted process > test_resources (gamma)
[11/cebebf] Submitted process > test_resources (alpha)
[4b/49b0d1] Submitted process > test_resources (omega)
[67/a57661] Re-submitted process > test_resources (gamma)
[bc/c34c79] Re-submitted process > test_resources (alpha)
Error executing process > 'test_resources (omega)'

Caused by:
  Process 'test_resources (omega)' terminated with an error exit status

Command executed:

  echo "Run attempt 1 - omega"
  echo "Run attempt 1" > omega.txt
  sleep 3h

Command exit status:
  143

Command output:
  Run attempt 1 - omega

Work dir:
  /lupus/home/phil/nxtflow_taskattempt/work/4b/49b0d1dd98a3dd85ff4c7493a682c5

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named: '.command.sh'

WARN: Killing pending tasks (2)
```

See the full working directory here: [nxtflow_taskattempt.zip](https://github.com/nextflow-io/nextflow/files/308680/nxtflow_taskattempt.zip)

One thing I was surprised was that `${task.attempt}` seems to evaluate to `1` in the process even after resubmission:
```
~/nxtflow_taskattempt » cat work/bc/c34c79746339a23329b72242d6613a/.command.sh
#!/bin/bash -ue
echo "Run attempt 1 - alpha"
echo "Run attempt 1" > alpha.txt
sleep 3h
```

So, any idea why the `alpha` and `gamma` jobs re-submit as expected, but not `omega`?  This is the same behaviour that I saw in my main pipeline, where the first two FastQC jobs resubmitted but the third failed.

Cheers,

Phil

**Comment by pditommaso** [comment]
These are two tricky ones: 

> One thing I was surprised was that ${task.attempt} seems to evaluate to 1 in the process even after resubmission

This is counterintuitive but it makes sense. What is happening is that the script is executed as it is i.e. without re-evaluating the interpolated variables in order to guarantee you are re-trying exactly the same task. Thus you won't see the new value of `task.attempt`.

Then: 
> So, any idea why the alpha and gamma jobs re-submit as expected, but not omega? This is the same behaviour that I saw in my main pipeline, where the first two FastQC jobs resubmitted but the third failed

Because no more than process error are allowed by default, independently of the `maxRetries` settings. You can change this behaviour setting the [maxErrors](http://www.nextflow.io/docs/latest/process.html#maxerrors) directive, or even switch if off setting it to `-1`. Note also the difference between `maxErrors` and [maxRetries](http://www.nextflow.io/docs/latest/process.html#maxretries) in the blue box in the previous link. 

Finally: 

> Note that the error code I seem to get for both memory and timeouts with SLURM is 143 instead of the 140 mentioned in the docs..

These error codes are not supposed to be portable. They depends by the cluster implementation. I think I've suggested that in the blog post. I need to check.

**Comment by ewels** [comment]
Ok, I think I get you. So `maxRetries 3` allows the process to resubmit _any file_ three times, but `maxErrors` operates on the process level instead of sample, it killed the entire process on the third exit.

So to confirm, the following would allow each sample to be resubmitted up to three times?
```groovy
errorStrategy { task.exitStatus == 143 ? 'retry' : 'terminate' }
maxRetries 3
maxErrors -1
```

The difference between `process` and `process instance` in the docs is quite subtle! ;)

Thanks for the explanation!

**Comment by pditommaso** [comment]
Yes, but to make things a bit more complex I've just found a bug. `maxErrors -1` seems not working, use a large number instead.

**Comment by ewels** [comment]
Great, will do. Thanks for the clarification!

**Comment by pditommaso** [comment]
It turns out that is not a bug but a Groovy feature i.e. the underlying parser interprets `maxErrors -1` as an arithmetic expression instead of a method call :(

Possible workarounds are: 
  
    maxErrors 10000
    maxErrors (-1)
    maxErrors '-1'
    maxErrors DEFINE_A_CONST_SET_TO_MINUS_1
