### ISSUE TITLE
Install Nextflow with --quiet mode

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#1800]
## New feature

Currently, installing Nextflow using the command `wget -qO- get.nextflow.io | bash` in GitHub Actions generates 5,186 lines of log output: https://github.com/nf-core/methylseq/runs/1418896978#step:6:5186

Whilst this isn't really a problem, it's a very minor annoyance when trying to read the logs.

## Suggest implementation 

Would it be possible to add a "quiet mode" to this installation script that suppresses the majority of console output?

**Comment by pditommaso** [comment]
I think it can be done using 

```
export CAPSULE_LOG=none
```

**Comment by ewels** [comment]
I love it when my desired feature already exists! 😆 🚀 

Works a treat: https://github.com/nf-core/methylseq/pull/179/checks?check_run_id=1422991687#step:6:14

Perfect, thanks!

**Comment by ewels** [comment]
I'm trying to be good and make a PR to the docs each time I find out about an undocumented feature 😁 

Here we go: https://github.com/nextflow-io/nextflow/pull/1801
