### ISSUE TITLE
Support for gogetdata(ggd) is needed

### ISSUE THREAD

**Issue by zhangzhen** [nextflow-io/nextflow#1802]
## New feature
Support for gogetdata(ggd) is needed that makes it easier to install ggd data packages into an environment and use them in a process.
https://gogetdata.github.io/

## Usage scenario 

A command requires a database file such as the reference sequence in the script block of a process. This feature can help 
 to install the database file into a dedicated data package environment, so the database file can be referenced in the command line.

## Suggest implementation 

I suggest creating a ggd directive that will create an environment for data packages and run `ggd install` to install data packages into this environment, a bit like the conda directive thats take an enviroment.yaml as input.

**Comment by abhi18av** [comment]
Hi @zhangzhen, `gogetdata` is an interesting project!

I noticed that the value proposition is similar to online databases like ENA or NCBI, maybe a method like `fromGGD` (similar to `fromSRA` ) might be more suitable. I realize that there's a `ggd show-env` command, which does affect the env variables and therefore the execution context, it'd be an interesting scenario to see how the `conda` directive and `GGD` directive would impact the overall process execution context.

Another approach could be to have a process which wraps the `ggd` CLI and passes along the downloaded data to downstream processes, which allows one to accomodate existing processes seamlessly.
