### ISSUE TITLE
file.isEmpty() does not work on empty gzip file

### ISSUE THREAD

**Issue by fullama** [nextflow-io/nextflow#1803]
### Expected behavior and actual behavior

If a gzip file is empty .isEmpty() detects the file as not empty. 
If an empty file is gzipped it is technically no longer empty even though it is empty when decompressed.

### Steps to reproduce the problem

Create an empty gzip file:
```shell
touch assembly.fa
gzip assembly.fa
```

For example if you had something like:
```
    when:
    !file("assembly.fa.gz").isEmpty()
```
because you dont want the process to run if the assembly file is empty.
The process will run anyway because technically the file is not empty.

Is this something that would be worth adding or maybe there is a better way to check if a gzip file is empty?

**Comment by pditommaso** [comment]
🤷‍♂️

**Comment by fullama** [comment]
unless you think its a bad idea i could try replacing:
```groovy
    static boolean empty( File file ) {
        assert file
        empty(file.toPath())
    }
```

in FileHelper.groovy with something like:
```groovy
import java.util.zip.GZIPInputStream

    static boolean empty( File file ) {
        assert file
        if( file.name.endsWith('.gz') ) {
            return GZIPInputStream(file).read() == -1;
        }
        else {
            empty(file.toPath())
        }
    }
```

**Comment by pditommaso** [comment]
Not sure a custom function will work either, since the file handle should only allow accessing file *metadata* not the content.

**Comment by fullama** [comment]
Fair enough.. Im not sure there is a way to figure it out without reading the file..  if i think of something ill try again..
..anyway it doesnt seem to be a feature that is in great demand as noone has ever brought it up before ;)

**Comment by pditommaso** [comment]
Instead of `when` use [filter](https://www.nextflow.io/docs/latest/operator.html#filter) with your custom function to get rid off the empty files.
