### ISSUE TITLE
[Enhancement]: Allow the beforeScript and afterScript directives to be executed from inside the container

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#1814]
Hi team 👋 

## New feature

There are certain processes which are better suited before/after the main process, hence we have the `beforeScript` and `afterScript` [directives](https://www.nextflow.io/docs/latest/process.html#afterscript). However, as of `Nextflow v20.10.0` these directives are executed in the host system.

My proposal is to allow the user to specify whether to execute them within the container.

## Usage scenario 

The main use-case for these processes is the meta-information which needs to be collected such as `version info`(here's an example in [nf-core/modules](https://github.com/nf-core/modules/blob/e02f0de5146f85de4a42e3505ba91f3488158d6a/software/picard/markduplicates/main.nf#L43)) or staging/finishing steps which need to be done along with the main process.

## Suggest implementation 

It could be implemented with the minimal syntactic change by allowing `afterScript` and `beforeScript` to accept an option.

```
  beforeScript 'source /cluster/bin/setup', container: true
```

OR 

We could simply allow the `*Script` to be executed within the container context as well.

## Extra

This proposal stems from a conversation in the nf-core slack 

![image](https://user-images.githubusercontent.com/12799326/100704561-b865f780-33cb-11eb-867a-c086c15d8d71.png)

**Comment by abhi18av** [comment]
Hi @pditommaso , 

I myself was surprised to see that the `*Script` directives are executed outside the script context, perhaps allowing these directives to run within the same context would be beneficial for users.


Do you think that this would be a sensible addition overall?

**Comment by pditommaso** [comment]
This was done by design because to have a hook to pre or post-process the task execution. What you are referring was discussed here https://github.com/nextflow-io/nextflow/issues/540

**Comment by abhi18av** [comment]
Thanks for the pointer Paolo, I'll give it a look and circle back.

**Comment by abhi18av** [comment]
Closing this feature in favor of #540
