### ISSUE TITLE
Issue pulling git repo using kuberun with Azure AKS

### ISSUE THREAD

**Issue by samcarswell** [nextflow-io/nextflow#1815]
## Bug report 

I have a Kubernetes cluster deployed on Azure with a Persistent Volume with `ReadWriteMany` access using Azure File. I also a have a Persistent Volume Claim bound to this volume.

When using `kuberun` I get the following error:
```zsh
 ✘  ~/workspace/nextflow_k8s  nextflow kuberun nextflow-io/rnatoy -v workflow-volume-claim:/mnt/
Pod started: awesome-miescher
N E X T F L O W  ~  version 20.10.0
Pulling nextflow-io/rnatoy ...
/mnt/projects/nextflow-io/rnatoy/.git/HEAD.lock.817a79c4894e4b35a82c2dd8176b0fa6 -> /mnt/projects/nextflow-io/rnatoy/.git/HEAD.lock: Not supported
```

Attempting to run the same repo a second time gives me the following:
```zsh
 ✘  ~/workspace/nextflow_k8s  nextflow kuberun nextflow-io/rnatoy -v workflow-volume-claim:/mnt/
Pod started: tender-tuckerman
N E X T F L O W  ~  version 20.10.0
Can't find git repository config file -- Repository may be corrupted: /mnt/projects/nextflow-io/rnatoy
```

Manually inspecting the file share displays the expected directory structure with the repo inside. This also seems to occur regardless of the repo I use.

### Expected behavior and actual behavior

Expect the pod to successfully pull the repo and run the Nextflow script.

### Steps to reproduce the problem

Here's the `kubectl describe` output for the `persistentVolume`, `persistentVolumeClaim` and `storageClass`:
```zsh
 ~/workspace/nextflow_k8s  k describe persistentvolume workflow-volume
Name:            workflow-volume
Labels:          type=local
Annotations:     pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    workflow-storage-class
Status:          Bound
Claim:           default/workflow-volume-claim
Reclaim Policy:  Retain
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        5Ti
Node Affinity:   <none>
Message:
Source:
    Type:             AzureFile (an Azure File Service mount on the host and bind mount to the pod)
    SecretName:       azure-file-creds
    SecretNamespace:
    ShareName:        guidingphoenixstorageshare
    ReadOnly:         false
Events:               <none>
 ~/workspace/nextflow_k8s  k describe persistentvolumeclaims workflow-volume-claim
Name:          workflow-volume-claim
Namespace:     default
StorageClass:  workflow-storage-class
Status:        Bound
Volume:        workflow-volume
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Ti
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    awesome-miescher
               dreamy-lamport
               drunk-northcutt
               tender-tuckerman
Events:        <none>
 ~/workspace/nextflow_k8s  k describe storageclasses.storage.k8s.io workflow-storage-class
Name:                  workflow-storage-class
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           kubernetes.io/azure-file
Parameters:            <none>
AllowVolumeExpansion:  True
MountOptions:
  file_mode=0777
  mfsymlinks
  gid=0
  uid=0
  dir_mode=0777
  cache=strict
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>
```

### Program output 

`.nextflow.log`:

```log
Dec-02 19:50:50.232 [main] DEBUG nextflow.cli.Launcher - $> nextflow kuberun nextflow-io/rnatoy -v 'workflow-volume-claim:/mnt/'
Dec-02 19:50:50.972 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials samcarswell:****************************************] -> https://api.github.com/repos/nextflow-io/rnatoy/contents/nextflow.config
Dec-02 19:50:51.549 [main] DEBUG nextflow.config.ConfigBuilder - User config file: https://github.com/nextflow-io/rnatoy/nextflow.config
Dec-02 19:50:51.550 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: https://github.com/nextflow-io/rnatoy/nextflow.config
Dec-02 19:50:51.554 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Dec-02 19:50:52.509 [main] DEBUG nextflow.k8s.K8sConfig - Kubernetes workDir=/mnt//srcarswell/work; projectDir=/mnt//projects; volumeClaims=[workflow-volume-claim]
Dec-02 19:50:52.969 [main] DEBUG nextflow.k8s.K8sDriverLauncher - Created K8s configMap with name: nf-config-71c7bdd7
Dec-02 19:50:58.798 [main] DEBUG nextflow.k8s.K8sDriverLauncher - Wait for pod termination name=tender-tuckerman
```

### Environment 

* Nextflow version: version 20.10.0 build 5430
* Java version: openjdk version "1.8.0_275"
* Operating system: macOS 10.15.7
* Bash version: zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by abotzki** [comment]
Without providing this extensive information for reproducibility, I just wanted to comment that three weeks ago, I experienced the same issue on a comparable environment using Ubuntu 18.04 and bash, openjdk 1.8 and nextflow 20.10. 
I could work around it by manually pulling the git repo after it initially failed and restarting the nextflow run.
If relevant, I could provide more details as above, too.

**Comment by pditommaso** [comment]
Looks similar to #1848

**Comment by crickgit1** [comment]
I had the same issue with kubernetes.io/azure-file storage class in Azure AKS running nexflow kuberun. I spent a lot of time trying to find a workaround to no avail. The problem is due to a limitation on Azure Files service which mounts as an SMB mount to the pod. SMB and Azure Files don't support hardlinks and you need to set the storage class to use mount options to support softlinks. 
mountOptions:
- mfsymlinks
If you use NFS storage class with azure premium storage it should work but it will cost a lot more. 
Here is a link to supported protocols for azure storage.
https://docs.microsoft.com/en-us/azure/storage/files/storage-files-compare-protocols

**Comment by pditommaso** [comment]
I think the last comment should be reported as a separate discussion thread, https://github.com/nextflow-io/nextflow/discussions
