### ISSUE TITLE
--profile --resume vs -profile -resume 

### ISSUE THREAD

**Issue by replikation** [nextflow-io/nextflow#1817]
Hi,
thanks for the great workflow manager. 
(yes i know the difference between `-profile` and a `--profile` from `params.profile` :) )

I observed sometimes that user of a workflow get confused with `-profile` or `-resume` and are writing `--profile` or `--resume`. So one additional `-` because all the params of a workflow are using `--`. This is especially true for user who just want to use workflows and are not part of the "coding" community and know what nextflow does.

Is it possible to "redirect" these params so that `--profile` would work like `-profile` to simplify this to the user? or a "workflow code snippet" that allows all nextflow related options to be called via `--` too ?
Seems simple but it is probably difficult to implement :) 

best and thanks

**Comment by abhi18av** [comment]
Hi @replikation ,

Yes, I too used to run into this confusion with previous version of NF. However, for specifying the `parameters` to any script perhaps a better user experience would be to simply use `-params-file parameters.yml` which allows the users to have all of the core configs in a declarative manner. This could potentially reduce the usage of `--param` by users to almost 0.

You can refer [point-4 of this blog post](https://www.nextflow.io/blog/2020/cli-docs-release.html) to see how it might work out for users.

**Comment by replikation** [comment]
hi @abhi18av  thanks for the suggestion, would help already I think if you are able to add all the params to the file. However, would get quite extensive for some workflows :)

**Comment by abhi18av** [comment]
Better than adding them individually via CLI 😉 

Also, a file might make it easier to distribute the exact params to the users.

**Comment by pditommaso** [comment]
This was a design choice that has some benefits (non-positional cli option) and some drawback (like the one you are describing). 

Don't think, we should have special behaviour for custom parameters. That would make things even more complicated. The proper solution would require to re-implement the command line interface, something that was tried in the past #556 but at the end, we realised that would have had a too big impact on existing tools

**Comment by replikation** [comment]
thanks for the answer
