### ISSUE TITLE
Mount multiple volumes on a Kubernetes cluster

### ISSUE THREAD

**Issue by chbk** [nextflow-io/nextflow#1823]
At the moment, only one volume can be mounted on a Kuberenetes cluster with `storageClaimName`. [Relevant documentation](https://www.nextflow.io/docs/latest/config.html#scope-k8s). This is a problem as volumes are limited in size. Ideally I'd like to mount one volume for input data and one volume for output data.

Syntax proposals:

- Allow lists for `storageClaimName`, `storageMountPath`, and `storageSubPath`.

      storageClaimName = ['volume1', volume2']
      storageMountPath = ['/data/volume1', '/data/volume2']
      storageSubPath = ['/', '/']

- A new `storage` key holding a list of maps with `claimName`, `mountPath` and `subPath` keys.

      storage = [
        [claimName: 'volume1', mountPath: '/data/volume1', subPath: '/'],
        [claimName: 'volume2', mountPath: '/data/volume2', subPath: '/']
      ]

**Comment by lukasjelonek** [comment]
I'd like to use this feature as well. In my case I want to separate the processing data (short-lived) from read-only data (long-lived).

The proposed  second syntax is great. For my case an additional boolean key would also be required: `readOnly`. 

Example:

```groovy
storage = [
  [claimName: 'nf-processing', mountPath: '/nf']
  [claimName: 'databases', mountPath: '/db', readOnly: true]
]
```

This should map to the following pod section:

```yaml
[...]
    volumeMounts:
    - name: nf-processing
      mountPath: "/nf"
    - name: databases
      mountPath: "/db"
      readOnly: true
[...]
```

---

I checked the nf source code and have seen that the underlying model is already able to handle multiple volume claims.

See: 
* https://github.com/nextflow-io/nextflow/blob/cd14c67e1b3716fa2014178a644eec540709e537/modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy#L73
* https://github.com/nextflow-io/nextflow/blob/cd14c67e1b3716fa2014178a644eec540709e537/modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy#L351

---

I am not very familiar with config processing in nf, but by reading the code I assume that it would be sufficient to add some lines of code here to implement your suggestion: https://github.com/nextflow-io/nextflow/blob/cd14c67e1b3716fa2014178a644eec540709e537/modules/nextflow/src/main/groovy/nextflow/k8s/K8sConfig.groovy#L56

```
if( getStorage() ) {
  def additionalClaims = getStorage().collect {
    new PodVolumeClaim(
       it.claimName,
       it.mountPath,
       it.subPath
    )
  }
  this.podOptions.volumeClaims.addAll(additionalClaims)
}
```

For the `readOnly`-option the `PodVolumeClaim` and `PodSpecBuilder`-classes have to be modified.

**Comment by lukasjelonek** [comment]
I checked the test-sources and it seems as if the feature is already implemented:

https://github.com/nextflow-io/nextflow/blob/cd14c67e1b3716fa2014178a644eec540709e537/modules/nextflow/src/test/groovy/nextflow/k8s/K8sConfigTest.groovy#L89-L102

**Comment by lukasjelonek** [comment]
I checked it and it works great. Here is my config file:

```
process.executor = "k8s"
k8s {
        storageClaimName = "nf-pvc"
        storageMountPath = "/nf"
        pod = [ [volumeClaim: "other-pvc", mountPath: "/other" ]]
}
```

Maybe it would be useful to add a note that is possible to mount multiple volumes in k8s and an example to the documenation.
