### ISSUE TITLE
non breaking space throws off script

### ISSUE THREAD

**Issue by reikoch** [nextflow-io/nextflow#1824]
# Bug report
Expected behavior and actual behavior

This is my code:
```
nextflow.enable.dsl=2
 
process sayHello {
  input:
    val cheers
  output:
    stdout

  """
  echo $cheers
  """
}

workflow {
  channel.of('Ciao', 'Hello', 'Hola') | sayHello | view
}
```
Note: there is a non breaking space u00A0 in line 2

## Steps to reproduce the problem
```
nextflow run sayHell0.nf
```
script will stop with following error:
```
N E X T F L O W  ~  version 20.10.0
Launching `sayHell0.nf` [jovial_mirzakhani] - revision: e1097a67f8
Script compilation error
- file : /home/bceuser/kochr4/git/nextflow/sayHell0.nf
- cause: Unexpected input: ' ' @ line 2, column 1.
    
   ^

1 error
```

## Environment
Nextflow version: [20.10]
Java version: [8]
Operating system: [RHEL 7.7]
Bash version:  [4.2.46(2)-release]

## Additional context
commenting out the non breaking space will allow correct execution of the workflow script

**Comment by pditommaso** [comment]
🤷‍♂️
