### ISSUE TITLE
Reduce dependencies such as ps for containerized processes

### ISSUE THREAD

**Issue by toniher** [nextflow-io/nextflow#1825]
For report mode Nextflow needs tools such as ```ps``` to be installed in the system (as described in tracing documentation). IMO, this is assumable in a host installation, but it introduces an additional burden if containers are used for some (if not all) processes. For instance, Debian images do not have _procps_ package installed by default.
Not an easy task, but I wonder if the underlying dependencies might be reduced in the future (e.g, somehow by checking /proc instead of using ps, for instance)

From end comments in #1289

**Comment by pditommaso** [comment]
```
yum install -y procps
``` 

👋

**Comment by pditommaso** [comment]
Unless you want to implement an alternative for it just using the `/proc` pseudo file system 😄

**Comment by pditommaso** [comment]
To summarize: `ps` is needed unless you turn off metrics/trace/report generation.
