### ISSUE TITLE
Add support for cpus throttling when using container execution

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#1832]
Modern container engines are able to limit CPU usage to a specific amount. This is very useful to prevent CPU hog tasks to use more resources than requested and prevent faulty node condition. 

Docker and Podman support this using the `--cpus` option. It should be investigated if also Singularity and Charliecloud allow the same.

**Comment by pditommaso** [comment]
@abhi18av want to give a try to this?

**Comment by abhi18av** [comment]
Yes @pditommaso, I'd like to have a go at this. Though I'd be bothering you a bit about Nextflow internals 😉

**Comment by pditommaso** [comment]
It should not be that hard. You can follow how the support for `memory` is already implemented 

https://github.com/nextflow-io/nextflow/blob/d0cc38de04f9f541e7d5aac12b7294cd62f1616d/modules/nextflow/src/main/groovy/nextflow/container/ContainerBuilder.groovy#L73-L84

**Comment by abhi18av** [comment]
`cpus` throttling support in 
- `docker` https://docs.docker.com/config/containers/resource_constraints/#cpu ✅ 
- `podman` http://docs.podman.io/en/latest/markdown/podman-run.1.html#cpu-quota-limit ✅ 
- `singularity https://sylabs.io/guides/3.3/user-guide/cli/singularity_exec.html?highlight=cpu ✅ 
- `charliecloud` https://hpc.github.io/charliecloud/search.html?q=cpu&check_keywords=yes&area=default ❌

**Comment by abhi18av** [comment]
@pditommaso , I'll be raising PRs for these containers individually ( I prefer smaller PRs) - the first draft for `Singularity` is here.

https://github.com/nextflow-io/nextflow/pull/1833

Could you please confirm if the direction is okay? The tests are passing locally.

Also, I noticed my auto code reformatting generates multiple changes on IntelliJ - do I need to update any settings?

**Comment by pditommaso** [comment]
Come on, three different PR are needed :)

It looks, in the same vein add also the ones for docker and podman. For the formatting check https://github.com/nextflow-io/nextflow/blob/master/CONTRIBUTING.md#ide-settings

**Comment by abhi18av** [comment]
For `docker`, does this mean we'll drop the `--cpuset-cpus` in favor of `--cpus`?

**Comment by pditommaso** [comment]
Nope, that's a different thing.

**Comment by pditommaso** [comment]
Done via #1833
