### ISSUE TITLE
when declaration is skipped 

### ISSUE THREAD

**Issue by pauca** [nextflow-io/nextflow#184]
```
c2 = Channel.from( 1 ,2  )
process p2{
    input:
        val c from c2
    when:
        c=='2' // also without quote does not work
    script:
    println "runned " + c
    """
    ls
    """
} 
```

Output:
N E X T F L O W  ~  version 0.20.0
Launching test.nf
[warm up] executor > local
runned 2
runned 1

**Comment by pditommaso** [comment]
The script is evaluated but it is *not* executed. Indeed, if you will replace `'2'` with `2` (int) you will see: 

```
[warm up] executor > local
runned 2
runned 1
[b3/e19a70] Submitted process > p2 (1)
```

It runs only one task as expected.

**Comment by pauca** [comment]
thanks for the clarification

**Comment by pditommaso** [comment]
welcome
