### ISSUE TITLE
[Feature Request] Support for querying the SRA metadata using AWS Athena and Google BigQuery

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#1842]
## New feature

The recent collaboration between `NCBI` and the cloud providers allows one to query the entire archive based on the metadata in AWS Athena.

Here are some relevant resources for the same

https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/

https://registry.opendata.aws/ncbi-sra/

https://www.ncbi.nlm.nih.gov/sra/docs/sra-athena-examples/

https://www.youtube.com/playlist?list=PLH-TjWpFfWrt5MNqU7Jvsk73QefO3ADwD

NOTE: The same could be done for GCP cloud as well, for now I've not created a separate issue for that.

## Suggested implementation 

I'm sure there must be a more elegant implementation but as an initial draft for this implementation, we could implement this in a couple of ways

1. As a separate method `fromNCBI`, which allows one to pass a closure based query for any particular database from NCBI.

```groovy
def ncbi_query = { db, orgnsm -> 
"""
SELECT *
FROM $db.metadata 
WHERE organism = $orgnsm
limit 10 
"""
}

Channel.fromNcbi ( query: ncbi_query("SRA", "Homo Sapien") )
```

2. Or as a more specialized enhancement of the `fromSRA` method, which allows a closure to be passed to the `query` field. For example,

```groovy
def ncbi_query = { db, orgnsm -> 
"""
SELECT *
FROM $db.metadata 
WHERE organism = $orgnsm
limit 10 
"""
}

Channel.fromSRA ( query: ncbi_query("SRA", "Homo Sapien") )
```

Related https://github.com/nextflow-io/nextflow/issues/1605

**Comment by abhi18av** [comment]
This could overlap with https://github.com/nextflow-io/nextflow/pull/1611

**Comment by abhi18av** [comment]
Update: 

The work is being done on my fork as of now https://github.com/abhi18av/nextflow/tree/abhinav/nf-sraql , with `BigQuery` as the default source.

Once it is presentable, I'll create and link the PR to this repo.

**Comment by pditommaso** [comment]
Cool! Willing to make a PR so changes will be more clear?

**Comment by abhi18av** [comment]
Absolutely, will make a PR by EOD today 👍

**Comment by abhi18av** [comment]
WIP - not stale.

**Comment by abhi18av** [comment]
Whoa, this went under my radar after the health crisis. Confirming @pditommaso  if this is still relevant and I'd be happy to pick this back up and make a push

**Comment by pditommaso** [comment]
Not a priority but surely a nice to have. What's missing?

**Comment by abhi18av** [comment]
I think it is already working for BigQuery, but I needed to accommodate paging issues for large set of results.

**Comment by pditommaso** [comment]
The most useful thing it would be an example in the [readme](https://github.com/nextflow-io/nf-sqldb). without that nobody will even know it exists

**Comment by leipzig** [comment]
is there a way to query sra metadata this way?
I would like to have fetchngs use the sra mirror first instead of ftp.
