### ISSUE TITLE
I downloaded nextflow using wget -qO- https://get.nextflow.io | bash in my current working directory and type nextflow , but it did not give anyoutput and not any error it is not responding. Any suggestion

### ISSUE THREAD

**Issue by tgaire** [nextflow-io/nextflow#1847]
Hi! Thanks for using Nextflow. 

If you need help about Nextflow scripting language, 
configuration options and general Nextflow usage the better 
channels to post this kind of questions are: 

* Google group: https://groups.google.com/forum/#!forum/nextflow
* Gitter channel: https://gitter.im/nextflow-io/nextflow

Also you may also want to have a look at the patterns page 
for common solutions to recurrent implementation problems: 
http://nextflow-io.github.io/patterns/index.html

**Comment by abhi18av** [comment]
Hi @tgaire ,

Without more contextual information such as execution environment and variables, it's a long shot to guess things. However, you can refer the `[edge documentation`](https://www.nextflow.io/docs/edge/getstarted.html#installation) for the updated installation instructions.

**Comment by tgaire** [comment]
I'm using a server, and we use nextflow for running bioinformatics analysis but for some reason when I type nextflow it did not respond (we have installed nextflow in the server folder and I specified a path by .bashrc file) but it did not work. Then I tried to install it in my home directory to test whether it will work but it did not show anything when I typed nextflow

**Comment by pditommaso** [comment]
Closing, since no proper context is provided (and not even a decent formatting).
