### ISSUE TITLE
File paths containing a timestamp are parsed as a Duration object

### ISSUE THREAD

**Issue by huguesfontenelle** [nextflow-io/nextflow#185]
The following pipeline
```
ch = Channel.from( params.bam )

process go {
  echo true

  input:
  val f from ch

  script:
"""
echo $f
"""
}
```

Gets me:

```
$ NXF_VER=0.20.1 ./nextflow tst.nf --bam "/path/to/samples/2016-06-05_21:04:05/sample.bam"
N E X T F L O W  ~  version 0.20.1
Launching tst.nf
[warm up] executor > local
[b1/75cdc4] Submitted process > go (1)
21h 4m 5s
```

I wanted to do some strings manipulations on this parameter, but it's not a string anymore, it's a time!

**Comment by pditommaso** [comment]
Oops.. too magic is happening here. Need to check.

**Comment by pditommaso** [comment]
This issue is fixed in the latest snapshot. You may want to give it a try running: 

    NXF_VER=0.20.2-SNAPSHOT nextflow run ..
