### ISSUE TITLE
publishDir - error when adding parameters

### ISSUE THREAD

**Issue by MattHuff** [nextflow-io/nextflow#1854]
## Bug report 

In the past, I have had no issues with using the `publishDir` directive and additional parameters. I am currently adding Nextflow to a new server in our lab, and now I am unable specify parameters for publishDir without Nextflow failing to run.

### Expected behavior and actual behavior

Expected behavior - the script runs, and copies the output files to the specified directory instead of creating symbolic links.

Actual behavior - Nextflow stops running, and gives an error about an unexpected input '{'.

### Steps to reproduce the problem

nextflow.config:

```
process {
 cpus = 20
}
```

call_variants1.nf

```
#!/usr/bin/env nextflow

params.output = "/pickett/projects/green_ash_genome/version_1/1.4/analysis/SelfIncompatibilityLocus/analysis"

query_path = "/pickett/projects/green_ash_genome/version_1/1.4/analysis/SelfIncompatibilityLocus/raw_data/ash_KochParents/*_R1_001.fastq.gz"
query_data = Channel.fromPath("${query_path}")
     .map { file -> tuple(file.baseName.replaceAll(/_R1/,""), file, file.getParent()/file.getName().replaceAll(/_R1/,"_R2")) }

process TrimInput {
 publishDir = '${params.output}/2_skewer', mode: 'copy'

 input:
 set sampleID, file(R1), file(R2) from query_data
 
 output:
 set sampleID, file("${sampleID}-trimmed-pair1.fastq"), file("${sampleID}-trimmed-pair2.fastq") into trimmed_reads

 script:
 """
 /pickett/software/skewer/skewer -x ${params.output}/all.fa -l 30 ${R1} ${R2} -o ${sampleID} >& ${sampleID}.trim_output
 """
}

```

### Program output 

```
$ ./nextflow -C ~/.nextflow/config run ./call_variants1.nf 
N E X T F L O W  ~  version 20.10.0
Launching `./call_variants1.nf` [voluminous_becquerel] - revision: a17fd12d45
Script compilation error
- file : /pickett/projects/green_ash_genome/version_1/1.4/analysis/SelfIncompatibilityLocus/analysis/nextflow_scripts/call_variants1.nf
- cause: Unexpected input: '{' @ line 9, column 19.
   process TrimInput {
                     ^

1 error

```

### Environment 

* Nextflow version: 20.10.0
* Java version: openjdk 11.0.8
* Operating system: Linux
* Bash version: 4.4.19(1)

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
There should not be `=` in the publishDir

**Comment by MattHuff** [comment]
Removing the `=` from the publishDir has resolved the issue.

**Comment by pditommaso** [comment]
👍
