### ISSUE TITLE
$projectDir not always resolves to the root path of a nextflow project

### ISSUE THREAD

**Issue by junjun-zhang** [nextflow-io/nextflow#1858]
### Expected behavior and actual behavior

Expected the variable `$projectDir` is always resolved to the root path of a Nextflow project, **no matter** where you launch a script within the project.

Actual behavior, `$projectDir` changes as different script at different located is launched (see `Program output` section)

### Steps to reproduce the problem

See the demo code here: https://github.com/junjun-zhang/demo-projectDir

### Program output 

See below, it appears `projectDir` === `baseDir`
```
nextflow run junjun-zhang/demo-projectDir -r main
# projectDir: /Users/junjun/.nextflow/assets/junjun-zhang/demo-projectDir

nextflow run junjun-zhang/demo-projectDir/local_modules/hello.nf -r main
# projectDir: /Users/junjun/.nextflow/assets/junjun-zhang/demo-projectDir/local_modules

nextflow run junjun-zhang/demo-projectDir/local_modules/tests/checker.nf -r main
# projectDir: /Users/junjun/.nextflow/assets/junjun-zhang/demo-projectDir/local_modules/tests
```

### Environment 

* Nextflow version: [20.10.0 build 5430] 
* Java version: [openjdk version "11.0.9" 2020-10-20]
* Operating system: [macOS]
* Bash version: [GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)]

### Additional context

Was hoping to use `$projectDir` as a stable path to include modules into different scripts regardless of their locations, see #1851

**Comment by pditommaso** [comment]
This is expected because the main script defines the project root location.

**Comment by junjun-zhang** [comment]
> This is expected because the main script defines the project root location.

Not sure I understand what you meant, you mean `$projectDir` changes is expected? In my example code, there is only one `main.nf` that is directly under the root dir of the git repository. I was hoping see `$projectDir` is resolved to the git root dir. But it's not, it resolves to different paths depending on which script is run.

As you pointed out below in an other [issue](https://github.com/nextflow-io/nextflow/issues/1851#issuecomment-764491669):

>> $projectDir is always resolved to the directory in which the nextflow launcher script is located.

> This is not correct, the projectDir is the directory where the pipeline main script (main.nf) is located.

So, `$projectDir` should not be always resolved to the launch script dir (ie, `$baseDir`). However, as reported in this issue, that seems to be the current behavior.

**Comment by junjun-zhang** [comment]
As I understand, clearly defining the `projectDir` concept is very important and has implications on other features. Clear definition would allow unambiguous resolution of `projectDir`. Perhaps, a directory containing a configuration file with `manifest` scope qualifies as the project root?

As described in the Nextflow official documentation site, it sounds like `manifest` scope is indeed intended at project level.

> The manifest configuration scope allows you to define some meta-data information needed when publishing your pipeline project
> ```
> manifest {
>     homePage = 'http://foo.com'
>     description = 'Pipeline does this and that'
>     mainScript = 'foo.nf'
>     version = '1.0.0'
> }
> ```

If that works, identifying such directory shouldn't be too difficult even when the search starts from a sub-directory many levels down within a project. It should be very similar to how git finds its root dir. One thing though, there needs to be a way to prevents users from creating multiple such configuration files within a project (unless supporting sub-project is a thing, which I highly doubt).

A corner case is a script not within any project, eg, a one-off script. In such case, it makes sense to resolve `projectDir` as `baseDir` (which seems to be the current behaviour)

**Comment by pditommaso** [comment]
The `projectDir` by definition where the main.nf (or the `nextflow.config` file specifying an alternative name via `manifest.mainScript`) is located.

**Comment by junjun-zhang** [comment]
> The projectDir by definition where the main.nf (or the nextflow.config file specifying an alternative name via manifest.mainScript) is located.

since `manifest.mainScript` is optional (at least appears to be so), what if it's missing from the nextflow.config?

In any case, $projectDir should not change simply because different script is launched, correct?

**Comment by pditommaso** [comment]
> what if it's missing from the nextflow.config?

Then it's the file name you specified on the command line or `main.nf` if you specified a directory path or a repository URL. 

$projectDir is the parent directory of the corresponding pipeline main script. Then it changes if you say `nextflow run /some/path/foo.nf` (it will be `/some/path`)  or  `nextflow run /some/path/nested/main.nf` (it will be `/some/path/nested)

**Comment by junjun-zhang** [comment]
> $projectDir is the parent directory of the corresponding pipeline main script. Then it changes if you say nextflow run /some/path/foo.nf (it will be /some/path) or nextflow run /some/path/nested/main.nf (it will be `/some/path/nested)

In that case, it looks like: `$projectDir === $baseDir`. Maybe this is the intention by design, which is OK.

My followup question is: do we need something representing the whole project level? something like s`$projectRoot`? Conceptually, it's a path holds the whole project. If such variable exists, our use case can certainly make use of it.

**Comment by pditommaso** [comment]
> it looks like: $projectDir === $baseDir

It is! it's an alias, I think I said at the beginning 😅 

> do we need something representing the whole project level? 

Not sure, at least we didn't have much need for it and bit worried it could create confusion with baseDir/projectDir

**Comment by junjun-zhang** [comment]
I am not aware of any use cases that would need such aliases. Could the alias be confusing as well? I think the other way to ask the question is: for what reason `projectDir` was added when `baseDir` was already supported?

A not so related question: one nextflow workflow git repo is one nextflow project, is that right? I mean at least conceptually.

> Not sure, at least we didn't have much need for it and bit worried it could create confusion with baseDir/projectDir

As discussed in #1851, a variable gives the root dir of a project could be used in my use case (although lacking such variable is not a blocker to us). To avoid potential confusion, one possibility is to not make baseDir / projectDir aliases to the other, although I don't have a strong opinion on this.
