### ISSUE TITLE
Timeline.html is not working on Firefox

### ISSUE THREAD

**Issue by SixPlusSeven** [nextflow-io/nextflow#1864]
Hi，

I got the timeline.html generated with nextflow（version 21.01.0-edge）using -with-timeline. 
But when I  display the timeline in Firefox（version84.0.2, 64）,it shows as follow:
![timeline](https://user-images.githubusercontent.com/15373535/105435499-6ab58f00-5c98-11eb-81d0-644d5c6eeb25.jpg)

How to fix it?

Thanks!

**Comment by brandoncazander** [comment]
Are you able to provide a [gist](https://gist.github.com/) of the `timeline.html` file that nextflow generated? Another helpful thing to provide would be the [console output](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console#opening_the_browser_console) from your browser.

**Comment by apeltzer** [comment]
Potentially an issue could be that you are running offline - not entirely sure that the JS libraries used for creating the timeline are loaded from a CDN that might either be not reachable from the machine you are using to open the html file and/or that you are opening the file on a machine that is entirely offline - could this by chance explain the behaviour? 

I've not seen any issues so far with Firefox ...

**Comment by pditommaso** [comment]
There's a PR that may fix this https://github.com/nextflow-io/nextflow/pull/1927

**Comment by pditommaso** [comment]
This should be solved as of version 21.03.0-edge. Feel free to reopen if still happens.
