### ISSUE TITLE
Nextflow in AWS Batch with Alpine Images

### ISSUE THREAD

**Issue by namiller2015** [nextflow-io/nextflow#1865]
Hello,

The following error message is written to the AWS CloudWatch logs for any Alpine based docker image when a nextflow job is submitted to AWS batch.

bash: /home/ec2-user/miniconda/bin/aws: /home/ec2-user/miniconda/bin/python: bad interpreter: No such file or directory

Multiple people have reported this issue in the gitter.im/nextflow discussion hub. The recommended solution is to use a different base Linux image. 

I'm trying to understand what the root error is and if there is a workaround besides using a different Linux base image. 
Is this something to do with the AWS CLI using python?

Thanks!

**Comment by pditommaso** [comment]
This is not a NF issue, is a problem of `aws` dependency with glibc library that's not avail on alpine https://dev.to/asyazwan/moving-away-from-alpine-30n4
