### ISSUE TITLE
Use GitHub Discussions

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#1866]
GitHub recently launched a new feature that they call "Discussions". I wasn't quite sure about it at first, but recently came across another popular repo using them and was quite impressed (https://github.com/willmcgugan/rich/discussions).

I think that using discussions for the Nextflow repo could have two benefits:

* Cut down on the noise in issues - more general questions and requests for help would move to discussions
* Make help threads more visible / accessible. Discussions are never closed (they are answered) and are easier to read when you're looking around due to highlighted "answered" posts and threaded replies.

I'm making this issue as quite often on the nf-core Slack we tell people to "go and ask on the Nextflow gitter" when they have an issue with Nextflow itself. I wonder if Discussions would present an easier interface for some questions and sort of form an unofficial and organic help base.

Worst case scenario, you can always turn it off again if you hate it / no-one uses it 😆 

Phil

**Comment by pditommaso** [comment]
Hi Phill, I think it's an excellent idea to consolidate the community discussion space. Are you using it for nf-core?

**Comment by ewels** [comment]
Not yet - we have lots of different repositories so it’s less clear cut about where it should be. I’ve been thinking about using it for MultiQC though 🤔

**Comment by pditommaso** [comment]
nf-core/discuss project! 😆

**Comment by ewels** [comment]
🤦🏻

**Comment by pditommaso** [comment]
😂

**Comment by pditommaso** [comment]
Enabled! thanks for the suggestion.
