### ISSUE TITLE
Dockers with old version of sleep command do not work in AWS environment

### ISSUE THREAD

**Issue by szymonwieloch** [nextflow-io/nextflow#1867]
### Expected behavior and actual behavior

A pipeline using the quay.io/biocontainers/mageck:0.5.9.4--py38hed8969a_0 docker was run in the AWS environment. The same pipeline runs correctly using slurm and local executors. It failed with the following error:

```
Command wrapper:
  sleep: invalid number '3m'
```

The problem turned out to be caused by how the .command.run file is implemented for the AWS executor:
[command.zip](https://github.com/nextflow-io/nextflow/files/5874929/command.zip). Please notice this line in the .command.run file:

```
sleep $[ ( $RANDOM % 3 ) + 1 ]m
```

This is problematic because not all  implementations of the sleep command support this syntax. The version in the quay.io/biocontainers/mageck:0.5.9.4--py38hed8969a_0 docker does not:

```
sleep --help
BusyBox v1.22.1 (2014-05-23 01:24:27 UTC) multi-call binary.

Usage: sleep N

Pause for N seconds
```

Clearly only integer numbers are supported. This is consistent with this documentation: https://www.gnu.org/software/coreutils/manual/html_node/sleep-invocation.html

> Although portable POSIX scripts must give sleep a single non-negative integer argument without a suffix (...)

### Suggested solution

I think that NextFlow should be compatible with as many dockers and operating systems as possible. Therefore I suggest rewriting the command to use seconds instead of minutes:

sleep $[ (( $RANDOM % 3 ) + 1)*60 ]

I also noticed that the script uses fractions of seconds, these would have to be converted into full seconds too:

**sleep 0.2 -> sleep 1**

Alternatively you can test the platform and check if it supports fractions, then use an optimal time:

```
SLEEPTIME=1
$(sleep 0.001 2>/dev/null)
if [ $? = 0 ]; then
SLEEPTIME=0.2
fi
```

### Steps to reproduce the problem

Run any long command (such as sleep 100) in the mentioned docker in AWS Batch environment.

### Environment 

* Nextflow version: 19.10

**Comment by pditommaso** [comment]
Hello, I was looking at this, but the following code is not generated by NF

```
sleep $[ ( $RANDOM % 3 ) + 1 ]m
```

I suspect that's inject by the pipeline via `beforeScript` directive.

**Comment by zichner** [comment]
Hi @pditommaso, thank you very much for your reply!
You are right. This piece of code was injected through the `beforescript` directive.
Sorry for overlooking this on our end.

This ticket can be closed.

**Comment by pditommaso** [comment]
👍
