### ISSUE TITLE
Singularity containers broken on linux since merge of #1833

### ISSUE THREAD

**Issue by pontus** [nextflow-io/nextflow#1869]
## Bug report 

#1833 added code that normally passes `--vm-cpu` and `--vm-ram` to singularity.  I assume these work on macOS, but on  
Linux, they are not valid (and will try to trigger macOS behaviour with starting a VM for hosting the container instead of).

### Expected behavior and actual behavior

It's expected one can use Singularity containers on Linux.

Instead one get e.g.
```
[-        ] process > RNASEQ:GET_SOFTWARE_VERSIONS                                             -
[-        ] process > RNASEQ:MULTIQC                                                           -
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'RNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)'

Caused by:
  Process `RNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)` terminated with an error exit status (255)

Command executed:

  check_samplesheet.py samplesheet.csv samplesheet.valid.csv

Command exit status:
  255

Command output:
  (empty)

Command error:
  FATAL:   This functionality is not supported. For more information visit: https://sylabs.io/singularity-desktop-macos

Work dir:
  /domus/h1/pontusf-test/nf-core-rnaseq-2.0/work/0b/fa5a39218b11ec4f9ca11a4271e341

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line



```

or e.g.

```
Error executing process > 'fastqc (TF-2589-RIP-EZH2-1_S34_L002)'

Caused by:
  Process `fastqc (TF-2589-RIP-EZH2-1_S34_L002)` terminated with an error exit status (255)

Command executed:

  fastqc --quiet --threads 2 TF-2589-RIP-EZH2-1_S34_L002_R1_001.fastq.gz TF-2589-RIP-EZH2-1_S34_L002_R2_001.fastq.gz

Command exit status:
  255

Command output:
  (empty)

Command error:
  FATAL:   Failed to find hypervisor executable at /usr/libexec/qemu-kvm
```

### Steps to reproduce the problem

Use nextflow with #1833 merged on Linux with singularity containers.

### Program output 

(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)

### Environment 

* Nextflow version: master, ccf5c8b and newer.
* Operating system: Linux

### Additional context

Both `--vm-cpu` and `--vm-ram` seem trigger the problematic behaviour on Linux with at least master of Singularity.

**Comment by pditommaso** [comment]
Damn! cc/ @abhi18av

**Comment by pditommaso** [comment]
@pontus thanks for reporting this issue. Are you aware is the singularity option to limit the cpus and mem usage ?

**Comment by abhi18av** [comment]
Hmm, there might be a change in these since the docs were last published for singularity 26-July-2019, since in the docs there's no indication that the behavior is different on `macOS` or `linux`. 

https://sylabs.io/guides/3.3/user-guide/cli/singularity_exec.html?highlight=cpu

Let me dig deeper and fix this.

**Comment by pontus** [comment]
Behaviour is the same, but the vm support is typically used on Linux (and should not be, for almost all use cases).

**Comment by pontus** [comment]
There is as far as I know no option to pass to singular to limit RAM and cpu usage. But it will inherit/use cgroups values, so setting those is the way to go if one wants that (i.e. similar as for conda).

**Comment by pditommaso** [comment]
Well, we can just drop it if so.

**Comment by abhi18av** [comment]
@pontus , I take it that you are referring to this functionality?
https://sylabs.io/guides/3.7/user-guide/cgroups.html?highlight=cpu

If so, then I think the `--vm-cpu` etc options for singularity are redundant for our use-case.

Anyways, could you please point me to some doc highlighting the use of `vm` in Singularity?

**Comment by abhi18av** [comment]
I've initiated a draft PR, removing the singularity VM related changes. Once we've settled on a course of action, I'll open it up for review and merge.

**Comment by pontus** [comment]
> @pontus , I take it that you are referring to this functionality?
> https://sylabs.io/guides/3.3/user-guide/cgroups.html?highlight=cpu
> 
> If so, then I think the `--vm-cpu` etc options for singularity are redundant for our use-case.

I was not referring to that, although that would be one way to do it. I guess.

Instead, if one doesn't pass something such, it will use the cgroup limits for the environment it's executed in, so configuring that before would be one way to apply limits (and it would then likely be the same as for other, non-container methods).
 
> Anyways, could you please point me to some doc highlighting the use of `vm` in Singularity?

I don't know of any good documentation for it, and my view is that there is not currently a good use case for it either. I believe it was added while they made a push for macOS support that I believe "is no longer a focus area".

The installation documents seems to suggest using vagrant boxes to get Singularity if not on Linux, so I'd say one should not use the `--vm` functionality if one doesn't really have a very specific use case for it.

**Comment by pditommaso** [comment]
Copy that

**Comment by pditommaso** [comment]
Ok, this is already available with release
