### ISSUE TITLE
[Feature request]: Add rclone plugin as an general Blob I/O solution

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#1873]
## Integration of [rclone](https://rclone.org/) as a general blob I/O solution

From the official website

> `rclone is a command line program to manage files on cloud storage. It is a feature rich alternative to cloud vendors' web storage interfaces. Over 40 cloud storage products support rclone including S3 object stores, business & consumer file storage services, as well as standard transfer protocols.

## Usage scenario 

Nextflow has a great integration with standard file transfer protocols and accommodates  a couple of major cloud providers natively. However, at the moment, there is no way to 

1. Add new protocols such as `SFTP` etc
2. Add new storage backends which enhance `fromPath/fromFilePairs` channel factories to accomodate storage only clouds/services such as OneDrive, Google Drive or [Wasabi](https://wasabi.com/), which is a much more economical s3 alternative.

## Suggest implementation 

This could be implemented as a module `nf-rclone` , which allows users to specify the native `rclone` configurations in `nextflow.config` as shown below

```nextflow

rclone {
    drive1 {
        type= s3
        secret= xyz
    }
}
```

Or it could simply support the native `rclone.conf` format and point to it as show below

```nextflow
rclone.configFile = "path/to/rclone.conf"
```

The way I imagine is that, `nf-rclone` would enhance the `fromPath` and `fromFilePairs` channel factories such as other protocols can be natively supported as shown below

```nextflow

my_fastq_reads_ch = Channel.fromFilePairs("$rcloneDriveName://path/to/files/*_{1,2}.fastq.gz")

```

OR 

```nextflow

my_fastq_reads_ch = Channel.fromFilePairs("s3://path/to/files/*_{1,2}.fastq.gz", rclone: "wasabi")

```

I might be off the track a bit, please feel free to update the proposal as you see fit 😊

**Comment by pditommaso** [comment]
👎 rclone is a nice tool, but NF should not depend on external tool whenever possible.

**Comment by Emiller88** [comment]
Since `rclone` was added as a stage out mode, would it be possible to revisist using it as a publishdir mode? Or would it be better to just call it in `onComplete`?
