### ISSUE TITLE
Missing or empty files in processes but after nextflow terminates workdir files look ok

### ISSUE THREAD

**Issue by boulund** [nextflow-io/nextflow#1875]
## Bug report 
I'm experiencing an odd behavior where Nextflow processes die, the called commands complaining about missing or empty files.
I'm running in an HPC environment on network mounted storage (tried on both ceph and nfs just to see if if made a difference).

### Expected behavior and actual behavior
The expected behavior is that all processes should run without issue. 
Actual behavior is that some processes randomly fail and when reviewing the logs the called commands complain about missing or empty input files. 

### Steps to reproduce the problem
The workflow in question is [BACTpipe](https://github.com/ctmrbio/BACTpipe) run with a cluster profile using Slurm and `scratch = true`.  I have tried running a set of 20 samples through the pipeline, and at typically 1-3 samples fail every execution. Rerunning with `-resume` typically works and the entire pipeline completes when it is resumed. It is not always the same samples failing on the first run. 

The problem does not appear if I change the cluster profile to not use scratch (`scratch = false`). I have tried running the same set of 20 samples through the pipeline three times without staging files on the same system and it has never failed once. It seems the issue only appears when scratch is used. 

### Program output 
```
============================================================
executor >  slurm (47)
[ea/aead08] process > FASTP (CCUG-30872)                          [100%] 17 of 17 ✔
[65/e0670c] process > SHOVILL (bask8780_S67_L001)                 [ 35%] 6 of 17
[03/4d7fba] process > ASSEMBLY_STATS (bask9966_S65_L001)          [ 50%] 3 of 6
[6a/3a7379] process > SCREEN_FOR_CONTAMINANTS (bask8780_S67_L001) [ 17%] 1 of 6
[6b/3e7531] process > PROKKA (BURYAT4_S74_L001)                   [  0%] 0 of 1
[-        ] process > MULTIQC                                     -
Error executing process > 'SCREEN_FOR_CONTAMINANTS (bask8890_S64_L001)'

Caused by:
  Process `SCREEN_FOR_CONTAMINANTS (bask8890_S64_L001)` terminated with an error exit status (1)

executor >  slurm (47)
[ea/aead08] process > FASTP (CCUG-30872)                          [100%] 17 of 17 ✔
[91/0cea25] process > SHOVILL (CCUG-30872)                        [100%] 6 of 6
[70/9b67cc] process > ASSEMBLY_STATS (bask8780_S67_L001)          [100%] 3 of 3
[6a/3a7379] process > SCREEN_FOR_CONTAMINANTS (bask8780_S67_L001) [100%] 2 of 2, failed: 1
[-        ] process > PROKKA (BURYAT4_S74_L001)                   -
[-        ] process > MULTIQC                                     -
Error executing process > 'SCREEN_FOR_CONTAMINANTS (bask8890_S64_L001)'

Caused by:
  Process `SCREEN_FOR_CONTAMINANTS (bask8890_S64_L001)` terminated with an error exit status (1)

Command executed:

  sendsketch.sh         in=bask8890_S64_L001_contigs.fa         samplerate=0.1         out=bask8890_S64_L001.sendsketc
h.txt

  # This process yields the main stdout for prokka
  sendsketch_to_prokka.py         bask8890_S64_L001.sendsketch.txt         /mnt/ceph/bactpipe_test/BACTpipe/resources/
gram_stain.txt         bask8890_S64_L001_stain_genus_species.tsv

Command exit status:
  1

Command output:
  (empty)

Command error:
  Adding /mnt/ceph/bactpipe_test/work/conda/env-a640826f9d786459503e77925c215de0/opt/bbmap-38.89-0/resources/blacklist
_refseq_merged.sketch to blacklist.
  0.156 seconds.
  Loaded 1 sketch in 0.214 seconds.
  Total Time:   1.560 seconds.
  Traceback (most recent call last):
    File "/mnt/ceph/bactpipe_test/BACTpipe/bin/sendsketch_to_prokka.py", line 20, in <module>
      genus_two = genus_two_line.split("\t")[11].split(" ")[0]
  IndexError: list index out of range

Work dir:
  /mnt/ceph/bactpipe_test/work/36/f842b5377462cb7735d860e5305bef

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command lin
e
```

Here the python script `sendsketch_to_prokka.py` failed when trying to process an empty file (it cannot split an empty string into 12 sections on the tab character). 

Other common failures include `sendsketch.sh` (from BBMap) earlier in the same process giving exit code 2 due to not being able to process an empty file. 

[.nextflow.log](https://github.com/nextflow-io/nextflow/files/5909891/default.nextflow.log)

### Environment 

* Nextflow version: 21.01.1-edge
* Java version: OpenJDK 11.0.8-internal
* Operating system: CentOS 8 
* Bash version: GNU bash 4.4.19(1)

**Comment by abhi18av** [comment]
@boulund , just wanted to confirm whether this issue is still relevant due to the comment here https://github.com/ctmrbio/BACTpipe/issues/144#issuecomment-775863787 ?

**Comment by boulund** [comment]
I think this issue is no longer relevant.
