### ISSUE TITLE
Failing to write nf-tower plugin to plugins folder

### ISSUE THREAD

**Issue by manu-tej** [nextflow-io/nextflow#1882]
### Expected behavior and actual behavior

I was testing the hosted version of nf-tower and I have added the flag `-with-tower` to the nextflow run command. But it is erroring out as it is unable to write the file to plugins folder

### Steps to reproduce the problem
`nextflow run nf-core/rnaseq -r 3.0 -profile test,docker -name rnaseq_test --max_cpus 70 --max_memory 140.GB -with-tower`
### Program output 

```
N E X T F L O W  ~  version 21.02.0-edge
Launching `nf-core/rnaseq` [rnaseq_test] - revision: 3643a94411 [3.0]
Downloading plugin nf-tower@1.0.1
Failed to write file '/nfs2/nextflowuser/.nextflow/plugins/nf-tower-1.0.1' to plugins folder
```
### Environment 

* Nextflow version: `21.02.0-edge`
* Java version: `openjdk version "1.8.0_282"`
* Operating system: `CentOS 7`
* Bash version: `4.2.46(2)-release (x86_64-redhat-linux-gnu)`

### Log file
[nextflow.log](https://github.com/nextflow-io/nextflow/files/5941465/nextflow.log)

**Comment by pditommaso** [comment]
Thanks for reporting this issue. I think I've identified the problem. 

Please try using this snapshot version as shown below: 

```
NXF_VER=21.03.0-SNAPSHOT nextflow run .. [the usual options]
```

If it still does not solve, please include the generated `.nextflow.log` file

**Comment by manu-tej** [comment]
Thanks @pditommaso! I think it is fixed now
