### ISSUE TITLE
Scratch ignored when using sge executor

### ISSUE THREAD

**Issue by timdiels** [nextflow-io/nextflow#1886]
### Expected behavior and actual behavior
With `sge` executor and `scratch '/some/dir'` or `scratch true`, the sge job should not reference any files outside the scratch dir, but it does (sge_o_workdir, cwd, stdout_path_list).

### Steps to reproduce the problem

`.../a/main.nf`:

```
process blast {
    executor 'sge'
    scratch true
    queue 'short'

    '''
    echo hi
    '''
}
```

Run `nextflow run main.nf`. To get the same error, the work dir should be mounted on the submit node, but not on the worker node. Either way you'll notice sge_o_workdir, cwd, stdout_path_list do not point to scratch.

### Program output 
[nextflow.log](https://github.com/nextflow-io/nextflow/files/5971769/nextflow.log)

SGE tries to chdir to the work dir instead of the scratch dir, the former does not exist on the cluster; it should use the scratch dir which does exist. qstat -j 295485:

```
job_number:                 295485
exec_file:                  job_scripts/295485
submission_time:            Fri Feb 12 13:57:37 2021
owner:                      someuser
uid:                        1234
group:                      somegroup
gid:                        1234
sge_o_home:                 .../home/someuser
sge_o_log_name:             someuser
sge_o_path:                 /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
sge_o_shell:                /bin/bash
sge_o_workdir:              .../a/work/e7/c2904fd540879ffce718eade17f341
sge_o_host:                 somehost
account:                    sge
cwd:                        .../a/work/e7/c2904fd540879ffce718eade17f341
merge:                      y
hard resource_list:         h_stack=128m,h_vmem=512m
mail_list:                  someuser@somehost
notify:                     TRUE
job_name:                   nf-blast
stdout_path_list:           NONE:NONE:.../a/work/e7/c2904fd540879ffce718eade17f341/.command.log
priority:                   -100
jobshare:                   0
hard_queue_list:            short
env_list:                   TERM=NONE,SGE_HVMEM=512m,SGE_HVMEM_BYTES=536870912
script_file:                .command.run
binding:                    NONE
job_type:                   NONE
error reason          1:      02/12/2021 14:57:40 [1234:113586]: error: can't chdir to .../a/work/e7/c2904fd540879ffce718eade17f341: No such file or directory
scheduling info:            Job is in error state
```

### Environment 

* Nextflow version: 20.10.0 build 5430
* Java version: openjdk 11.0.10 2021-01-19
* Operating system: Linux, Ubuntu buster/sid
* Bash version: GNU bash 4.4.20(1)-release (x86_64-pc-linux-gnu)

### Additional context
I also tried

```
scratch '/some/dir'
stageInMode 'copy'
stageOutMode 'copy'
...
```

but same result.

**Comment by timdiels** [comment]
I can work around it for now by doing nextflow run from scratch storage (i.e. everything stored in scratch), but I would like to minimise what the cluster can see in case secrets end up in the work dir.

**Comment by timdiels** [comment]
I forgot to mention our cluster flavour is Son of Grid Engine.

**Comment by pditommaso** [comment]
When setting the `scratch true` what NF does is to `cd` in a subdirectory of the TMDIR path assigned by SGE, symlink input and run the task there, and copy back the results to the task work directory in the shared file system. Not sure what's the problem you are mentioning.

**Comment by timdiels** [comment]
I would like NF to copy the input files to `/some/dir`, run the job and copy the output back. `/some/dir` is an nfs share exported by the VM running nextflow and mounted by the SGE nodes. The `work` dir and `main.nf` are on a different mount, inaccessible by the SGE master/worker nodes.

The directives I use for this:

```
scratch '/some/dir'
stageInMode 'copy'
stageOutMode 'copy'
```

What happens is, NF does not copy the files to /some/dir, it remains empty. The SoGE job tries to cd to the work dir on the worker node but it does not exist there; if I recall correctly the `.command.sh` created by NF contains `-wd` to the NF work dir, not the scratch dir, i.e. not `/some/dir`.

**Comment by timdiels** [comment]
(I assumed `scratch true` would use `$TMPDIR`, but I only provided that as a more minimal example to reproduce as the issue seems the same; SGE `-wd` points to the work dir, not the scratch dir, whichever that may be)

**Comment by pditommaso** [comment]
> The work dir and main.nf are on a different mount, inaccessible by the SGE master/worker nodes.

This cannot work. The input/output files are copied by the job script and therefore the worker nor should be able to access the work dir.

**Comment by timdiels** [comment]
In that case I'll just put any non-SGE secrets on a different mount while leaving the work dir on the SGE mount. So long as I point to secret files in scripts instead of putting a secret in a variable and then using that in a `script:`, I should be able to avoid secrets of my local jobs ending up in the work dir which can then be seen by the SGE jobs. That's good enough for our semi-trusted SGE cluster.

Closing as I can make do without scratch for my use case.
