### ISSUE TITLE
Job name causes SLURM job submission problems

### ISSUE THREAD

**Issue by shaze** [nextflow-io/nextflow#1887]
## Bug report 

Not sure that this is a bug of Nextflow or SLURM but I spent 2 hours this afternoon working out the problem.

When I manually set the job name of a process, the SLURM job submission script generates a job name that my version of SLURM can't handle which causes it to disregard all resource allocation requests

### Expected behavior and actual behavior

I manually set the job name e..g putting this in my nextflow.config `executor.jobName = { "$task.name" }` and run using slurm submission

Expected behaviour -- I set the job name and my job runs respecting all resource requests.

Instead, the  job runs using 2GB of memory and 1 processor

### Steps to reproduce the problem

nexflow.config

```
executor.jobName = { "$task.name" }
process.executor = 'slurm'
process.queue = 'batch'
```

Test script but I think any would do

```
xch = Channel.fromPath("test.nf")

process see {
  cpus 16
  memory '32 GB'
  input:
  file(x) from xch
  output:
  file("see")
  script:
  """                                                                                                     
     touch see                                                                                            
     sleep 39                                                                                             
  """
}

```

### Program output 

I think the problem is these _sbatch_ commands that nextflow produces in the .command.run. Note the space between the "see" and the (1)

```
#!/bin/bash
#SBATCH -D /home/scott/test/work/89/dabdb3b9dcf355f20c9185e5d6433f
#SBATCH -J see (1)
#SBATCH -o /home/scott/test/work/89/dabdb3b9dcf355f20c9185e5d6433f/.command.log
#SBATCH --no-requeue
#SBATCH -c 16
#SBATCH --mem 32768M
#SBATCH -p batch
# NEXTFLOW TASK: see (1)
```

If I manually do an _sbatch_ on this the same problem occurs -- I only get a process with 2GB of RAM and 1 CPU allocated . If I delete the space in the job name then the _sbatch_ works

### Environment 

* Nextflow version: 20.10.0 build 5430
* Java version:OpenJDK Runtime Environment (build 1.8.0_272-b10)
* Operating system: CentOS 7.9
* Bash version: 4.2.46

### Additional context

Using SLURM version 17

**Comment by pditommaso** [comment]
The `jobName` is meant to allow the user to provide a custom job naming strategy which is expected to be compliant with the platform requirements. 

Said in another way, when using it, you should care to avoid invalid chars. From what I see in the above snippet, it's enough removing the line 

```
executor.jobName = { "$task.name" }
```

**Comment by shaze** [comment]
I must be missing something -- I am using the example in the documentation  https://www.nextflow.io/docs/latest/config.html
The documentation gives an example `executor.jobName = { "$task.name - $task.hash" } `

This won't work for SLURM because of the space, so _my_ example given above just has the task name. The problem appears to be that `$task.name` generates a name that has a space embedded in it. (i.e. in the example above `see (1)` the space comes from task.name

It's not a big issue -- minor aesthetic in my eyes -- and have deleted as suggested. Am happy to close this. 

Thanks, Paolo

**Comment by pditommaso** [comment]
Yeah, not the best example in the docs. I should add a warning about that. Happy you have solved it.
