### ISSUE TITLE
Empty process script reports misleading error message

### ISSUE THREAD

**Issue by szymonwieloch** [nextflow-io/nextflow#1888]
### Expected behavior and actual behavior

When script text is empty, NextFlow fails with a message that does not explain what is wrong. I spent some time searching fo the true reason for the following message:

```
Execution aborted due to an unexpected error
```

### Steps to reproduce the problem
```
process emptyScript {
  input:
  val(i) from 5
  output:
  val(i) into output
  script:
  ''
}
```

### Environment 

* Nextflow version: 20.10

**Comment by pditommaso** [comment]
Fair enough. Solved by 3607f84e.
