### ISSUE TITLE
Error on accessing task in errorStratety closure

### ISSUE THREAD

**Issue by szymonwieloch** [nextflow-io/nextflow#1889]
## Bug report 

NextFlow fails with the following error message:

```
Execution aborted due to an unexpected error

 -- Check script 'main.nf' at line: 9 or see '.nextflow.log' file for more details
```

The log states:

```
java.lang.NullPointerException: Cannot get property 'container' on null object
```

This happens when the `task` object is accessed in the errorStrategy callback.

### Steps to reproduce the problem

```
input = Channel.value([[container: 'ubuntu'], 5])
process failingButIgnored {
    input:
    errorStrategy {
        log.info("$task")
        'ignore'
    }

    container "$data.container"
    tuple val(data), val(i) from input
    script:
    """
    echo $i
    exit 5
    """
}

```

The problem disappears when the `log.info("$task")` is commented out. Error line in the log suggests that the dictionary (first element of the input tuple) becomes null once the task object is logged. This seems to happen even before the process is run. It seems that if you just use the task object in the errorStrategy closure - it stops working. But accessing properties of tasks (such as task.attempt) works fine.

Similar error was observed when the `task` object was sent to another channel using bind().

### Environment 

* Nextflow version: 20.10

**Comment by pditommaso** [comment]
I think the process is malformed, directives should go *before* `input:` e.g. 

```
process failingButIgnored {
    errorStrategy { log.info("$task"); return 'ignore' }
    container "$data.container"

    input:
    tuple val(data), val(i) from input
    script:
    """
    echo $i
    exit 5
    """
}
```

**Comment by szymonwieloch** [comment]
Hi!

@pditommaso the bug is present, it was just my mistake in copying the code sample - I am sorry for that.

The following correct code generates the same error:

```
input = Channel.value([[container: 'ubuntu'], 5])
process failingButIgnored {
    errorStrategy {
        log.info("$task")
        'ignore'
    }

    container "$data.container"
    input: 
    tuple val(data), val(i) from input
    script:
    """
    echo $i
    exit 5
    """
}

```

**Comment by pditommaso** [comment]
Got it. It looks like a problem with the resolution of nested properties eg. `$data.container` 

However explicit dynamic syntax works eg. 

```
    container { data.container }
```

instead of 


```
    container "$data.container"
```
