### ISSUE TITLE
Cannot a find a file system provider for scheme: s3

### ISSUE THREAD

**Issue by george-hall-ucl** [nextflow-io/nextflow#1891]
## Bug report 

The latest tagged version (v21.02.0-edge) appears unable to handle files stored in s3 filesystems. Earlier tagged releases (e.g. v21.01.1-edge and earlier) do not have this problem. Looking at the commits since v21.01.1-edge (e.g. [Remove nf-amazon as default](https://github.com/nextflow-io/nextflow/commit/e6810e90bd95665a2a3b41aa734afc7b911491d7)) make me think that this could be intended behaviour, but it is unclear to me how to solve the issue (i.e. what I should do to be able to handle such files). If this is intended behaviour and I have simply not installed something correctly, I apologise for submitting this as a bug report and instead could you please let me know how to fix my problem?

### Expected behavior and actual behavior

Expected behaviour: be able to handle and interact with (e.g. verify the existence of) files stored in an s3 filesystem.

Actual behaviour: Nextflow is unable to handle files stored in an s3 filesystem. Workflow crashes with message "Cannot a find a file system provider for scheme: s3".

### Steps to reproduce the problem

Download nextflow v21.02.0-edge from source from [here](https://github.com/nextflow-io/nextflow/archive/v21.02.0-edge.tar.gz) and compile using `make compile` and `make pack`. Run using `launch.sh`.

Run a main.nf file consisting of the following line:

`file("s3://ngi-igenomes/igenomes//Drosophila_melanogaster/Ensembl/BDGP6/Sequence/WholeGenomeFasta/genome.fa", checkIfExists: true)`

### Program output 

```
N E X T F L O W  ~  version 21.02.0-edge
Launching `main.nf` [grave_newton] - revision: 941c103741
Cannot a find a file system provider for scheme: s3

 -- Check script 'main.nf' at line: 1 or see '.nextflow.log' file for more details
```

I have attached [nextflow.log](https://github.com/nextflow-io/nextflow/files/5982345/nextflow.log).

### Environment 

* Nextflow version: v21.02.0-edge
* Java version: 1.8.0_92
* Operating system: Red Hat Enterprise Linux Server 7.8
* Bash version: 4.2.46(2)

**Comment by pditommaso** [comment]
Hi there, you need to include in your config the snippet 

```
plugins {
  id 'nf-amazon'
}
```

**Comment by george-hall-ucl** [comment]
Hi Paolo,

Many thanks, that fixes it!

Do you know if there is there is somewhere in the docs where this behaviour could be made more obvious (or did I just miss it)? Or are plugins still only on the edge releases and thus currently undocumented? If this is the case, for now perhaps a suggestion in the error message that this might be the problem could be helpful to others who have the same issue?

In either case, I can submit a PR with the change if you want.

**Comment by pditommaso** [comment]
This is a new feature, the docs still need to be written.

**Comment by george-hall-ucl** [comment]
Ok, cool. Thanks again!
