### ISSUE TITLE
InvocationTargetException when function called from script block has an error

### ISSUE THREAD

**Issue by krokicki** [nextflow-io/nextflow#1896]
### Expected behavior and actual behavior

When a DSL2 function has a syntax error and is called from a process script block, the error message is generic and it's not possible to see what is causing the problem. 

### Steps to reproduce the problem

```
nextflow.enable.dsl=2

def function() {
    def var = "a"
    return var2=="a" ? "true" : "false"
}

process test {
    output:
    env VAR
    """
    VAR=${function()}
    """
}

workflow {
    test().view()
}
```

> 

### Program output 

```
N E X T F L O W  ~  version 20.10.0
Launching `test.nf` [deadly_lamarr] - revision: 352b9d7ad9
[-        ] process > test -
[-        ] process > test -
Error executing process > 'test'

Caused by:
  java.lang.reflect.InvocationTargetException

Source block:
  """
      VAR=${function()}
      """

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Environment 

* Nextflow version: 20.10.0 
* Java version: 1.8.0_102
* Operating system: Scientific Linux 7.8
* Bash version:  GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

As a workaround, you can call all functions before starting the script block, e.g.
```
process test {
    output:
    env VAR
    f=function()
    """
    VAR=${f}
    """
}
```

This has output: 
```
N E X T F L O W  ~  version 20.10.0
Launching `test.nf` [infallible_snyder] - revision: 55a8a329d2
No such variable: var2

 -- Check script 'test.nf' at line: 5 or see '.nextflow.log' file for more details
```

**Comment by krokicki** [comment]
As another gotcha, "f=function()" works to print the syntax error, but if you fix that error, it starts failing with "Unknown variable 'f'". Using "def f=function()" outside the script block has all the right behavior, but it's not very obvious why that specific syntax is necessary.

**Comment by pditommaso** [comment]
Thanks for reporting this. Now the error reports a more informative message 

```
Caused by:
  No such variable: var2 -- Check script 't.nf' at line: 5
```

**Comment by krokicki** [comment]
Awesome! Really glad to see these kinds of things get addressed.
