### ISSUE TITLE
Documentation example no longer works

### ISSUE THREAD

**Issue by Jeltje** [nextflow-io/nextflow#1898]
## Bug report 

The example at https://www.nextflow.io/docs/latest/process.html#multiple-output-files under **Output ‘stdout’ special file** uses `channel.subscribe`. In the latest Nextflow version this leads to a warning and an 'Unknown method'

### Expected behavior and actual behavior

The example output is supposed to be
`I say.. Hello world!`

Actual behavior when running the test script:
```
N E X T F L O W  ~  version 20.10.0
Launching `mytest.nf` [mad_jang] - revision: 1bc905a983
WARN: The use of the identifier `channel` as variable name is discouraged and will be deprecated in a future version
I say..  Unknown method invocation `subscribe` on Channel type
```

### Steps to reproduce the problem

```
process echoSomething {
    output:
    stdout channel

    """
    echo Hello world!
    """
}

channel.subscribe { print "I say..  $it" }
```

**Comment by pditommaso** [comment]
Well spotted, fixed in the master branch, see c4b36176. It will be published in a few days.
