### ISSUE TITLE
Implement clean up command 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#19]
Implement a new command that allows the user to selectively clean the work/scratch directory. 

Ideally the user should be able to select which *runs* have to discarded and keep the others. Currently to each pipeline execution is associated a UUID number. The history of all runs is stored in the file ``.nextflow.history`` (in the working directory). It can be viewed with the command ``nextflow history``. It prints a report similar to the following (the oldest run is showed at the top, the latest at the bottom): 

    a77d4b73-8fdc-4111-bb19-31e30a7248d3	nextflow run piper 
    aa4fd46b-fee7-40b4-bff6-e3acd5950254	nextflow run piper  --genome-file /path/to/file
    49685297-1e52-41d5-9e0c-f00d09d1d17a	nextflow run grape --read1 '*_1.fa' --read2 '*_2.fa'
    cbf5e933-f725-4a1f-a714-a0c8715bff74	nextflow run grape --annot /path/to/annotation.gff

It could be possibile to implement a new command ``clean`` command that delete all the files produced by a pipeline execution having a specified UUID number, or before that execution, or after that execution. 

For example: 

`nextflow clean -before <UUID>`
Delete all files produced before the pipeline run with the specified UUID

`nextflow clean -after <UUID>`
Delete all files produced after the pipeline run with the specified UUID

`nextflow clean -run <UUID>`
Delete all files produced by the pipeline run with the specified UUID

`nextflow clean -but <UUID>`
Delete all files expect the ones produced by the runs specified 

`nextflow clean` 
By default delete all files expect the ones produced by the last run.

**Comment by andrewcstewart** [comment]
I'd love to see a process directive to clean up inputs after they are no longer necessary.  This is certainly doable already either within the process script or using afterScript though.

**Comment by pditommaso** [comment]
The problem with you are proposing is that it is not possible to completely clean-up the process outputs before pipeline termination because downstream tasks may require the produced output.

**Comment by stevekm** [comment]
is there up to date documentation on this feature? I am kind of afraid to experiment with it for fear of accidentally deleting results I need to keep...
