### ISSUE TITLE
Handle customised sbatch returning the jobid by itself

### ISSUE THREAD

**Issue by joshuabhk** [nextflow-io/nextflow#190]
Hi,

I tried to run nextflow in NIH biowulf cluster which uses slurm.
It works well when I ran with local executor, but with slurm, it failed to run.
Could you help to fix the problem?

Thank you!

Bong-Hyun

[kimb8@biowulf nextflow]$ nextflow run output_file.nf 
N E X T F L O W  ~  version 0.20.1
Launching output_file.nf
[warm up] executor > slurm
Error executing process > 'splitLetters (1)'

Caused by:
  Invalid SLURM submit response:
20418660

Command executed:

  sbatch .command.run

Command exit status:
  0

Command output:
  20418660

Work dir:
  /gpfs/gsfs4/users/CCBR/user/kimb8/nextflow/work/39/f1af1c47c8ee86d5a1d434026ffd36

Tip: view the complete command output by changing to the process work dir and entering the command: 'cat .command.out'

[kimb8@biowulf nextflow]$ sbatch --version
slurm 15.08.10

**Comment by joshuabhk** [comment]
My trivial nextflow pipeline is the following.

[kimb8@biowulf nextflow]$ cat output_file.nf 
#!/bin/env nextflow

process splitLetters{
	executor 'slurm'
	queue 'ccr'
	time '1h'
	module 'R'
	memory '16 GB'
	cpus 4

	output:
	file 'chunk_*' into letters

	'''
	printf 'Hola' | split -b 1 - chunk_
	'''
}

letters .subscribe {println "File: ${it.name} ==> ${it.text}" }

**Comment by pditommaso** [comment]
You can do the following:

Change into the task working directory reported in the error message.

There you will find the '.command.run' file that is just a script used to
run your SLURM job.

You should be able to launch it using the following command:

sbatch .command.run

Then you should be able to debug why SLURM is failing.

Note: the SLURM directives are at the top on the .command.run file. Likely
there's something there that is not valid for your cluster configuration.

**Comment by pditommaso** [comment]
The user reported: 

> Thank you very much your help!
It looks like the job actually submitted but the standard output of the sbatch is different from what you expected in the nexflow.

> The following is my command line input and output from the sbatch.

> [kimb8@biowulf 786dec80181b63b8dcec95a2fc686b]$ sbatch .command.run 
20430969

> It might be the version issue or our version on biowulf2 cluster has slightly modified version of the output. 
In any case, can you help me to run nextflow on our cluster?

**Comment by pditommaso** [comment]
Yes, nextflow expects that SLURM returns the string `Submitted batch job <JOBID>`. 

Ideally would quite easy to adapt it to handle your output. The relevant code is [this method](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/executor/SlurmExecutor.groovy#L98-L108).

However I'm wondering if there's any option that could be used to restore the default output in your cluster configuration. Could you try to investigate with your sysadmins?

**Comment by joshuabhk** [comment]
Thank you! I already submitted a ticket about it, but somehow they are that
responsive. But at least I can set up my pipeline though this temporary
patch!

**Comment by pditommaso** [comment]
This means they have fixed the issue? How they patched it?

**Comment by joshuabhk** [comment]
No, I asked the admin to look into it. But he has not responded yet.

**Comment by joshuabhk** [comment]
I am planning to compile the temporary fix by myself today.

**Comment by pditommaso** [comment]
That sounds good. If it could manage the standard SLURM output and your one
I could take in consideration a pull request for that.

**Comment by wresch** [comment]
non-responsive sysadmin here - sbatch on our system is a wrapper around SLURM sbatch hence the failure. Not particularly familiar with groovy but looks easy enough to patch.

**Comment by joshuabhk** [comment]
Hi Wolfgang, 

You are actually the most responsive sys admin I've ever met. :)
Thanks a lot for your hard work!

Best,

Bong-Hyun

**Comment by pditommaso** [comment]
@wresch is there a specific reason to drop the default `sbatch` stdout message? Could not it done in an optional manner?

**Comment by wresch** [comment]
@pditommaso  Just outputting the jobid is a convenience that makes things like 
```bash
jobid1=$(sbatch ...)
sbatch --dependency=afterany:$jobid1 ...
```
trivial. 

We could optionally restore the default output but it'd rather adopt the tool to the cluster than the other way around.

OT: I have a couple of questions about the install - is the best place for that the google group?

Thanks for your help, btw

**Comment by pditommaso** [comment]
If so, IMHO to maintain the compatibility with other tools (not just nextflow) you call your wrapper with a different name e.g. `qbatch` (just saying). Doing so a user would have the option to choose which one to use.

If that's not an option I can take in consideration to add the support for your output version.

**Comment by wresch** [comment]
That's not an option. The wrapper does other things we depend on and this would be too confusing for our hundreds of users. I'm fine patching this locally if you'd rather not take the pull request.

**Comment by pditommaso** [comment]
OK. For the immediate I would suggest you patch it locally (let me know if you need help with the build procedure).

Then, let me think a bit if I can find a better alternative to this patch.

**Comment by wresch** [comment]
Sounds good. I have it working locally now. Thanks for your help

**Comment by joshuabhk** [comment]
Thank you so much for both of your helps!
I will present nextflow to my colleagues so that they can use it.

**Comment by pditommaso** [comment]
Fixed the latest snapshot. You may want to give a try running 

    NXF_VER=0.20.2-SNAPSHOT nextflow run ..
