### ISSUE TITLE
K8s pod labels aren't allowed to start with numbers

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#1905]
## Bug report 

Pod labels specified with the `pod` directive for the k8s executor aren't allowed to start with numbers.  When something like: `pod label: 'version' value: '3.6.1'` is specified, the entire string is erased.

### Expected behavior and actual behavior

Pod labels should be allowed to start with any alphanumeric value [a-zA-Z0-9], per the [Kubernetes spec](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set). 

### Steps to reproduce the problem

Just add the `pod label: 'version' value: '3.6.1'` to a process and execute with the k8s executor.  

### Program output 

You should see the label in the generated pod spec appear as an empty string ("").

### Environment 

* Nextflow version: I see this on master.

### Additional context

The fix is a minor change to a `sanitize0` method.  Will have a patch shortly.

**Comment by pditommaso** [comment]
Done 4fd0f444
