### ISSUE TITLE
Nextflow pipeline hangs indefinitely when executing on sge using conda

### ISSUE THREAD

**Issue by anwarMZ** [nextflow-io/nextflow#1924]
Hi, I have been struggling a little with sge executor, any help will be appreciated.

## Nextflow execution hangs using `sge` as executor

I am trying to run a nextflow pipeline on using `sge` as executor. Right after executing the command, the process seems to hang for a very long time. Looking at `.nextflow.log` it seems like nextflow keeps asking status of queue but jobs are not running. However, right after executing the job, I could see `qw` status of jobs but soon after that they were removed from the queue. The same pipeline works on the same system with local executor.  

### Steps to reproduce the problem

I am using [https://github.com/anwarMZ/nf-upcoast-v](https://github.com/anwarMZ/nf-upcoast-v) pipeline with the following command 
`nextflow -trace nextflow.executor run ./main.nf -profile conda,cluster_sge --illumina --directory ./raw_input --prefix SIP_40`

### Program output 
I have attached `.nextflow.log` and 
[nextflow.log](https://github.com/nextflow-io/nextflow/files/6034071/nextflow.log)

from `.nextflow.log` i could see the line - - so I am pasting the contents of `/projects/upcoast_v/nf-upcoast-v/work/e0/3ffb9990f7b6affc5b56a66717694a/.command.log`

`/opt/sge/default/spool/cdc1n8/job_scripts/975476: line 38: syntax error near unexpected token `<'

### Environment 

* Nextflow version: 
* Java version: `20.10.0`
* Operating system: [macOS, Linux, etc] `CentOS Linux`
* Bash version: (use the command `$SHELL --version`)
`GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)`
`Copyright (C) 2011 Free Software Foundation, Inc.`
`License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`
`This is free software; you are free to change and redistribute it.`
`There is NO WARRANTY, to the extent permitted by law.`

Thank you, 
Zohaib

Edit:  I tried to look at #1760 but it seems like the error there was with local executor in general - [https://github.com/nextflow-io/nextflow/issues/1760#issuecomment-756006425](https://github.com/nextflow-io/nextflow/issues/1760#issuecomment-756006425). whereas in my case local executor works well.

**Comment by anwarMZ** [comment]
Hi Just wanted to follow up if there has been any update on this. Thanks

**Comment by bkbx** [comment]
I have the same problem

**Comment by Zethson** [comment]
Me too unfortunately.

**Comment by noamteyssier** [comment]
Hey all,

same for me also - would be happy to help troubleshoot but would appreciate guidance if anybody has ideas on what is causing the issue. 

## Error 
Here is my error message: seems like it is occuring at a different line than yours but with same unexpected token
`/var/spool/sge/wynton/qb3-idgpu10/job_scripts/116311: line 21: syntax error near unexpected token '<' `

### Where the Error Occurs
```bash
nxf_tree() {
    local pid=$1
    declare -a ALL_CHILDREN
    while read P PP; do
        ALL_CHILDREN[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)
## ^^ this is the line thats breaking
}
```
It seems like there is an empty argument to the first `<` and it does seem strange to me that the `pid=` and `ppid=` arguments are missing as well. 

Perhaps an issue with how the function `nxf_tree` is being called where the process id's are not getting passed correctly? 

Like Zohaib's issue this is only happening to me on the `sge` executor and not occurring when running locally. I see that this is tagged with conda but I'm unsure of whether that is truly the cause of the problem as I'm receiving the same issue and I'm not using any conda environments.  

## Versioning
-----------------------------------
Nextflow Version: 21.04.3
Java Version: 1.8.0_301
OS: CentOS Linux
Shell: zsh 5.0.2 (also fails with bash)
-----------------------------------

Cheers,
Noam

**Comment by bkbx** [comment]
信件已收到

**Comment by bkbx** [comment]
信件已收到

**Comment by bkbx** [comment]
信件已收到

**Comment by pditommaso** [comment]
I guess this happens because the job uses `/bin/sh` instead of `/bin/bash` as the default shell. 

Using `clusterOptions = '-S /bin/bash'` should solve.
