### ISSUE TITLE
Missing flag in SLURM squeue call

### ISSUE THREAD

**Issue by wresch** [nextflow-io/nextflow#193]
Hi,
the queueStatusCommand method is defined as follows:
```groovy
protected List<String> queueStatusCommand(Object queue) {
        if( queue )
            log.debug "SLURM executor does not support queue parameter on queue status"

        return ['squeue','-h','-o','%i %t']
}
```

However, squeue by default only returns pending, running, and completed jobs (at least it does so in slurm 15.08.10). To get all jobs the flag 
```
-t all
```
has to be used.  From the squeue man page:
```
    -t <state_list>, --states=<state_list>
              Specify the states of jobs to view.  Accepts a comma separated list of state names or "all". 
              If "all" is specified then jobs of all states will be reported. If no  state  is specified  then  
              pending,  running,  and  completing  jobs  are reported.
```
Therefore failed jobs are misclassified as completed.

**Comment by pditommaso** [comment]
Ok, this makes sense. Thanks to point it out.

**Comment by pditommaso** [comment]
OK, I've included this flag in the snapshot that I've just uploaded. You may want to give a try running 

    NXF_VER=0.20.2-SNAPSHOT nextflow run ..

**Comment by wresch** [comment]
great. thanks

**Comment by pditommaso** [comment]
@wresch I'm wondering if `squeue` returns the jobs of the current user or any users in the cluster? Do you have any idea?

**Comment by wresch** [comment]
I was going to ask you about that at some point - squeue by default returns
all users' jobs. squeue -u <username> will only jobs owned by <uername>.

A related question - nextflow seems to be polling the queue once a second.
If more than a couple of people were to start using nextflow this would
result i a sizable number of RPC calls to the slurm controller daemon.  Are
you planning on making that polling interval configurable?

**Comment by pditommaso** [comment]
> I was going to ask you about that at some point - squeue by default returns
all users' jobs. squeue -u <username> will only jobs owned by <uername>.

OK. I've already added it, I will upload a new snapshot soon. 
 
> A related question - nextflow seems to be polling the queue once a second.
If more than a couple of people were to start using nextflow this would. 

It's 1 second only for the local executor, 30 for clusters based. 

>  Are you planning on making that polling interval configurable? 

It's already. See `queueStatInterval` [here](http://www.nextflow.io/docs/latest/config.html#scope-executor)

**Comment by wresch** [comment]
ah - i was getting the 1s from

https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/executor/AbstractGridExecutor.groovy#L52-L58

which i guess i misunderstood. Thanks for clearing that up and pointing me
towards the docs for queueStatInterval

**Comment by pditommaso** [comment]
um, I'm starting to think that you are right. I was remembering a longer one, but that it the code.

**Comment by pditommaso** [comment]
I've uploaded a new snapshot including that restricts `squeue` output to the current user. If you want to try it use the following command to refresh the snapshot 

```
CAPSULE_RESET=1 NXF_VER=0.20.2-SNAPSHOT nextflow info
```

Then run nextflow with this cmd line 

```
NXF_VER=0.20.2-SNAPSHOT nextflow run .. 
```
