### ISSUE TITLE
Azure Batch Executor: unable to start jobs

### ISSUE THREAD

**Issue by manuelesimi** [nextflow-io/nextflow#1931]
## Bug report 

I'm trying to use the new `azurebatch` executor, but no job ever gets executed.

### Expected behavior and actual behavior

I'm using a very simple pipeline (an extension of the hello pipeline from Nextflow) to play with the new executor. The pipeline takes as input a file, then each of the 4 process appends a line to the file and passes the file to the next process. Finally, inside the onComplete handler, the pipeline prints the content of the file emitted by the last process. 

The pipeline works well with local and sge executors. 

Trying with the new `azurebatch` executor, I get an unexpected behavior. The pool of nodes in the Batch account is correctly created (I've the quota set to 40 VMs for the size I'm requesting) and the nodes go in the running state. The workdir for the first process execution is also correctly created in the blob storage. But then, the first job is submitted but never executed. 

### Steps to reproduce the problem

Here's the project with the pipeline:
https://github.com/manuelesimi/hello-nextflow/tree/azurebatch

**Note**: if you clone it, make sure to switch to the azurebatch branch.

I'm triggering the execution with the following command:
`nextflow run main.nf -w az://<my blob name>/work`

### Program output 

This is the error returned by the first execution:

<pre>
Command output:
executor >  azurebatch (1)
[db/dc5dbd] process > sayHelloInItalian (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > sayHelloInFrench      -
[-        ] process > sayHelloInSpanish     -
[-        ] process > sayHelloInEnglish     -
Error executing process > 'sayHelloInItalian (1)'

Caused by:
  Process `sayHelloInItalian (1)` terminated for an unknown reason -- Likely it has been terminated by the external system
</pre>

### Environment 

* Nextflow version: 21.02.0-edge
* Plugin: nf-azure@0.9.3
* Java version: 1.8.0_131
* Operating system: Mac OS X 10.12.6
* Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

### Additional context

Do note that `.command.run` and `.command.sh` are created in the workdir on the blob storage, but `.command.out`, `.command.err`, `.exitcode` are not. So, it seems the process is submitted to the executor but for some reasons it does not get executed.

Here's the relevant section from the `.nextflow.log`:
<pre>
Feb-25 15:35:13.700 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - [AZURE BATCH] Submitting task: nf-1dab60b3b5bd72aac7b08f268a59911b, cpus=1, mem=-, slots: 1
Feb-25 15:35:13.702 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - Task output path: .exitcode -> az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b
Feb-25 15:35:13.703 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - Task output path: .command.log -> az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b
Feb-25 15:35:13.788 [Task submitter] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Submitted task sayHelloInItalian (1) with taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b)
Feb-25 15:35:13.789 [Task submitter] INFO  nextflow.Session - [1d/ab60b3] Submitted process > sayHelloInItalian (1)
Feb-25 15:35:18.817 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:35:18.819 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:35:28.770 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:35:28.770 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:35:38.783 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:35:38.783 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:35:48.809 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:35:48.809 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:35:58.790 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:35:58.791 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:36:08.789 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:36:08.789 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:36:18.806 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:36:18.806 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:36:28.807 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:36:28.807 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:36:38.789 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:36:38.790 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:36:48.795 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:36:48.796 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:36:58.809 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:36:58.811 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:37:08.798 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:37:08.798 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:37:18.792 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=active
Feb-25 15:37:18.793 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=false
Feb-25 15:37:28.812 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b) state=completed
Feb-25 15:37:28.812 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-1742050b17039dbbc159-sayHelloInItalian, nf-1dab60b3b5bd72aac7b08f268a59911b); running=true
Feb-25 15:37:28.859 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Cannot read exitstatus for task: `sayHelloInItalian (1)` | az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b/.exitcode
Feb-25 15:37:28.860 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: sayHelloInItalian (1); status: COMPLETED; exit: -; error: -; workDir: az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b]
Feb-25 15:37:28.927 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b/.command.out
Feb-25 15:37:28.978 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b/.command.err
Feb-25 15:37:29.027 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b/.command.log
Feb-25 15:37:29.030 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'sayHelloInItalian (1)'

Caused by:
  Process `sayHelloInItalian (1)` terminated for an unknown reason -- Likely it has been terminated by the external system

Command executed [.../NextflowAzure/hello-nextflow/templates/hello.sh]:

  #!/usr/bin/env bash
  hello=Ciao
  output=italian.txt
  previous_file=Welcome.txt
  cat ${previous_file} > $output
  echo "${hello} world!" >> $output

Command exit status:
  -

Command output:
  (empty)

Work dir:
  az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Feb-25 15:37:29.071 [main] DEBUG nextflow.Session - Session await > all process finished
Feb-25 15:37:29.116 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `sayHelloInItalian (1)` terminated for an unknown reason -- Likely it has been terminated by the external system
Feb-25 15:37:29.192 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b/.command.err
Feb-25 15:37:29.294 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b/.command.out
Feb-25 15:37:29.297 [main] DEBUG nextflow.Session - Session await > all barriers passed
Feb-25 15:37:29.350 [main] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b/.command.err
Feb-25 15:37:29.399 [main] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b/.command.out
</pre>

Note: I have replaced the name of the blob with "my blob name".

**Comment by pditommaso** [comment]
Don't tell me you have a container name with blank spaces .. !@ 

```
az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b
```

**Comment by manuelesimi** [comment]
> Don't tell me you have a container name with blank spaces .. !@
> 
> ```
> az://my blob name/work/1d/ab60b3b5bd72aac7b08f268a59911b
> ```

Nope :) 

Read the last line:

Note: I have replaced the name of the blob with "my blob name".

**Comment by pditommaso** [comment]
Can you check task status in the batch portal?

**Comment by manuelesimi** [comment]
The status is Online. 
If it wasn't, I guess the pool would not be even created.

**Comment by pditommaso** [comment]
There must an entry for the task `nf-1dab60b3b5bd72aac7b08f268a59911b` which tell why it's failed.

**Comment by manuelesimi** [comment]
I just noticed it. It's the same for all my failed jobs:

<img width="498" alt="Screen Shot 2021-02-25 at 4 48 14 PM" src="https://user-images.githubusercontent.com/2822686/109223051-18302c80-7788-11eb-8792-2ee1708d6490.png">

Is the task looking for the /root folder?

**Comment by pditommaso** [comment]
Docker public registry does not allow any more anonymous pulls, I guess  [this ](https://github.com/manuelesimi/hello-nextflow/blob/azurebatch/nextflow.config#L1) is failing. Replace with `quay.io/nextflow/bash`.

 Also, the [second line](https://github.com/manuelesimi/hello-nextflow/blob/azurebatch/nextflow.config#L2) should be useless, better to remove.

**Comment by manuelesimi** [comment]
I have switched to the image you suggest and running a test right now. However, I don't think it'd make any difference, as you can see from the nextflow.config, I'm running with docker disabled. I have disabled it because I was having the same problem and tried to exclude docker. I'm now thinking if the missed pulling of the image could be the problem?

Question:
We have most of our pipelines depending on Docker images in a private organization on Docker Hub. Is there any way to configure the docker login on the VMs?

**Comment by abhi18av** [comment]
Hi @manuelesimi 

> We have most of our pipelines depending on Docker images in a private organization on Docker Hub. Is there any way to configure the docker login on the VMs?

For logging into the private registry via docker, perhaps you can make use of the official `login` command reference 
https://docs.docker.com/engine/reference/commandline/login/

I haven't tried it so far myself, but perhaps worth a shot in the meantime.

**Comment by manuelesimi** [comment]
Hi @abhi18av,

We use docker login on our on-prem cluster. That works, of course. The problem here is that the VMs are created on the fly by Nextflow. I was asking if @pditommaso or anybody else has suggestions on how we could do the same in the Batch Pools.

**Comment by manuelesimi** [comment]
> Docker public registry does not allow any more anonymous pulls, I guess [this ](https://github.com/manuelesimi/hello-nextflow/blob/azurebatch/nextflow.config#L1) is failing. Replace with `quay.io/nextflow/bash`.
> 

I have enabled docker and switched to that image. No luck. I got the same error on the /root folder.

**Comment by abhi18av** [comment]
Cool, so there are a few directions we could explore here.

- Do have the required quota for `Standard_DS1_v2` type machines?

The workflow would fail to execute on the azure side if the requisite quota for a _specific family_ of machines is not there. See https://github.com/nextflow-io/nextflow/pull/1916 for reference. 

- To confirm the overall Azure setup, have you tried running the https://github.com/nextflow-io/rnaseq-nf workflow?

You could try allow NF to create the pool with ideal configs and test out the `rnaseq-nf` workflow with the following additions to the `nextflow.config` file 

```nextflow
plugins {
  id 'nf-amazon'
  id 'nf-azure'
}


/* 
 * defines execution profiles for different environments  
 */ 

profiles {

  azbatch {

//----------------------
// NOTE: The reads are from AWS S3 bucket 

    params.reads = 's3://rnaseq-nf/data/ggal/lung_{1,2}.fq'
    params.transcriptome = 's3://rnaseq-nf/data/ggal/transcript.fa'
//----------------------


    process.executor = 'azurebatch'

      azure {

        storage {
          accountName = "FIXME"
          accountKey = "FIXME"
            }

        batch {
          location = 'eastus'
          accountName = 'FIXME'
          accountKey = 'FIXME'
          autoPoolMode = true

          pools {
              auto {
                 autoScale = true
                 vmType = 'Standard_D4_v3'
                 vmCount = 1
                 maxVmCount = 2
              }
            }
          }
        }

    process.container = 'quay.io/nextflow/rnaseq-nf:latest' 
    workDir = 'az://FIXME/work/'
  }


}

```


Then you can run the wf using 

```
// RNASEQ-nf directory

nextflow-21.02.0-edge run main.nf -profile azbatch -with-tower
```

**Comment by manuelesimi** [comment]
> Cool, so there are a few directions we could explore here.
> 
> * Do have the required quota for `Standard_DS1_v2` type machines?
> 
> The workflow would fail to execute on the azure side if the requisite quota for a _specific family_ of machines is not there. See #1916 for reference.

Yes, as I wrote in my initial description of this issue, the pools are correctly created and I've a quota of 40 VMs for Standard_DS1_v2. So that should be taken care of.

Thanks for suggesting to test the executor with rnaseq-nf. I'll give it a try on my batch account and let you know the results.

**Comment by manuelesimi** [comment]
I tried to execute rnaseq-nf. However, it does not find the input reads in the S3 bucked (I assumed they were publicity available...). Hence, the executor does not even reach the point of creating the pool on the batch account.

Here's the related [nextflow.log](https://github.com/nextflow-io/nextflow/files/6047322/nextflow.log)

**Comment by pditommaso** [comment]
I used this config 

```
plugins {
  id 'nf-azure'
}

process {
  executor = 'azurebatch'
  container = 'quay.io/nextflow/bash'
}

azure {
  batch {
    location = 'westeurope'
    accountName = "$AZURE_BATCH_ACCOUNT_NAME"
    accountKey = "$AZURE_BATCH_ACCOUNT_KEY"
    allowPoolCreation = true //Nextflow automatically creates a pool of computing nodes to execute the jobs
    autoPoolMode = true
    deletePoolsOnCompletion = true //The pool is removed when the pipeline execution terminates
    pools {
        auto { //auto pool configuration scope
            autoScale = true
            vmType = 'Standard_D4_v3'
            vmCount = 1
            maxVmCount = 10
        }
    }
  }
  storage {
    accountName = "$AZURE_STORAGE_ACCOUNT_NAME"
    accountKey = "$AZURE_STORAGE_ACCOUNT_KEY"
  }
}
```

Save to a file `az.config` in the same directory run 

```
nextflow -C az.config run nextflow-io/hello -w az://my-data/work
```

Replacing the container/bucker `my-data` with your own. 

This to check it does work: 
* the pool is created correctly and the *Current vCPUs* column is > 0 
* you have enough quota for the select VM type 
* the storage account is in the same location/region of the batch account 
* check the details of the failing task. If should report the reason why it's failed.

**Comment by manuelesimi** [comment]
Thanks @pditommaso for your suggestion.

I've tried the nextflow-io/hello pipeline and with your configuration. Then tweaked mine as well. 

I was able to nail down the problem to its core. Basically, it seems I can't access to my blob storage from my batch account. 

<pre>
Category: UserError
Code: BlobAccessDenied
Message: Access for one of the specified Azure Blob(s) is denied
</pre>

And this happens when the job is trying to access to .command.run in my blob.

<pre>
Name: FilePath

Value:
/mnt/resource/batch/tasks/workitems/job-2a8b931a626103530879-sayHelloInItalian/job-1/nf-5948dd4ae54c45d8fb972b431f7a6954/wd/.command.run
</pre>

This definitely sheds some light, and indeed the problem seems to be on my Azure resources.

So, besides setting up the batch account and the storage account in the same location, are there other requirements to in order to make the blob visible to the jobs?

**Comment by pditommaso** [comment]
May be related to the first point in this comment? 
https://techcommunity.microsoft.com/t5/azure-compute/running-nextflow-data-pipelines-on-azure-batch/bc-p/2162529/highlight/true#M53

**Comment by manuelesimi** [comment]
I don't think so. The storage account is already associated to the batch account.

**Comment by manuelesimi** [comment]
And it's allocated as Batch Service.

**Comment by pditommaso** [comment]
Try this, go into the storage account, look for shared access signature, make sure to enable all and generate a new SAS token

<img width="1039" alt="Screenshot 2021-02-26 at 16 48 47" src="https://user-images.githubusercontent.com/816968/109322515-affa4d00-7852-11eb-9894-5fad425d35b2.png">


Then in the nextflow config, replace the storage `accountKey` and with `sasToken` (make sure to remove the prefix `?` char), and try again.

**Comment by manuelesimi** [comment]
Using the token I made progress. 

Now, the problem is that the first process ends with this error:
<pre>
 sleep: invalid number '0.2'
</pre>

which I can relate to this function in the wrapper script:

<pre>
nxf_parallel() {
    IFS=$'\n'
    local cmd=("$@")
    local cpus=$(nproc 2>/dev/null || < /proc/cpuinfo grep '^process' -c)
    local max=$(if (( cpus>16 )); then echo 16; else echo $cpus; fi)
    local i=0
    local pid=()
    (
    set +u
    while ((i<${#cmd[@]})); do
        local copy=()
        for x in "${pid[@]}"; do
          [[ -e /proc/$x ]] && copy+=($x)
        done
        pid=("${copy[@]}")

        if ((${#pid[@]}>=$max)); then
          sleep 0.2
        else
          eval "${cmd[$i]}" &
          pid+=($!)
          ((i+=1))
        fi
    done
    ((${#pid[@]}>0)) && wait ${pid[@]}
    )
    unset IFS
}
</pre>

The VM where the the job was running is `Standard_DS1_v2` and, more specifically, `microsoft-azure-batch centos-container 7-7 (latest)`

**Comment by pditommaso** [comment]
Please always include the .nextflow.log file

**Comment by manuelesimi** [comment]
Yep. Sorry.

Here's:
[nextflow.log](https://github.com/nextflow-io/nextflow/files/6052587/nextflow.log)

**Comment by pditommaso** [comment]
This looks like an unrelated problem (to be fixed). Use a container not based on busybox eg. `ubuntu:latest` to run the task.

**Comment by manuelesimi** [comment]
Since I was not sure how to avoid busybox with an auto-created pool (suggestions are welcome), I made a few changes to Nextflow. See: https://github.com/nextflow-io/nextflow/pull/1936

Basically, whenever there was a sleep with a decimal, if it fails, I replaced with a sleep of 1 second.

This modified version worked well for me on MacOS, Ubuntu and Azure Batch with Busybox.

**Comment by manuelesimi** [comment]
With the changes in the PR, I'm able to start jobs with the pool created by the batch executor, pass files and values across processes with channels, and publish results on the storage accounts linked to the batch account. 

I'm closing the issue.

**Comment by pditommaso** [comment]
ok, this is good but still the main cause of this problem of this issue was the problem accessing the blob storage. NF generates a temporary SAS token that should work. Instead, you had to generate it manually. 

Since I'm not able to replicate the problem in my env, could you try to apply the patch below to your code of NF source. 

```
diff --git a/plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzHelper.groovy b/plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzHelper.groovy
index 2bbd0a39..6c9213af 100644
--- a/plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzHelper.groovy
+++ b/plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzHelper.groovy
@@ -20,6 +20,7 @@ import java.time.OffsetDateTime
 
 import com.azure.storage.blob.BlobContainerClient
 import com.azure.storage.blob.sas.BlobContainerSasPermission
+import com.azure.storage.blob.sas.BlobSasPermission
 import com.azure.storage.blob.sas.BlobServiceSasSignatureValues
 import groovy.transform.CompileStatic
 import nextflow.cloud.azure.nio.AzPath
@@ -64,10 +65,22 @@ class AzHelper {
             .setTagsPermission(true)
             .setWritePermission(true)
 
+    static BlobSasPermission BLOB_PERMS = new BlobSasPermission()
+            .setAddPermission(true)
+            .setCreatePermission(true)
+            .setDeletePermission(true)
+            .setListPermission(true)
+            .setMovePermission(true)
+            .setReadPermission(true)
+            .setTagsPermission(true)
+            .setWritePermission(true)
+
+
     static String generateSas(BlobContainerClient client, Duration duration) {
         final now = OffsetDateTime .now()
 
         final signature = new BlobServiceSasSignatureValues()
+                .setPermissions(BLOB_PERMS)
                 .setPermissions(CONTAINER_PERMS)
                 .setStartTime(now)
                 .setExpiryTime( now.plusSeconds(duration.toSeconds()) )

```


Then, remove the `sasToken` in your config and restore the `accountKey`. Finally, compile NF and run it using: 

```
make compile
./launch.sh run ... [usual cli opts]
```

**Comment by manuelesimi** [comment]
Amazing! The patch worked!

With the new permissions, I was able to use my blob storage with the key.

**Comment by pditommaso** [comment]
Excellent! tomorrow I'll prepare a new release. Thanks a lot for the collaboration.

**Comment by manuelesimi** [comment]
Please, consider also if the changes to the doc in this PR can be useful for the new release: https://github.com/nextflow-io/nextflow/pull/1939

Thanks!

**Comment by pditommaso** [comment]
To summarise, it was missing the blob permissions 18a33213

**Comment by manuelesimi** [comment]
> To summarise, it was missing the blob permissions [18a3321](https://github.com/nextflow-io/nextflow/commit/18a332135c6dad48bf6b174103776eca099efc38)

Correct, plus the fix on the sleep command for non-integer numbers.

**Comment by vinishgeorge** [comment]
> I have switched to the image you suggest and running a test right now. However, I don't think it'd make any difference, as you can see from the nextflow.config, I'm running with docker disabled. I have disabled it because I was having the same problem and tried to exclude docker. I'm now thinking if the missed pulling of the image could be the problem?
> 
> Question:
> We have most of our pipelines depending on Docker images in a private organization on Docker Hub. Is there any way to configure the docker login on the VMs?

@manuelesimi  where you able to login to the private organization docker hub, i'm facing the same issue not able to configure to pull from a private ACR.

**Comment by manuelesimi** [comment]
@vinishgeorge So far, I've tried to docker login from a start task and directly on the nodes (pre-existing pool), but it didn't work. 

I also tried to configure a container registry (referring to docker.io and with my organization's credentials) in the pool created on the Azure portal, but still it doesn't pull the images. 

My next bet is to create an Azure registry, push my images there and use it as pool's registry.

**Comment by vinishgeorge** [comment]
@manuelesimi  i was able to get it working on azure portal ..my batch service pull's from my private registry . The way i did it was by choosing an image from container category for operating system configuration  for eg:  Ubuntu Server container image. Then in the Container configuration mention the Container type docker compatible and mentioning the Container registries Attributes mainly   username ,password and registry server.
Tutorial that helped me was https://dev.to/kenakamu/use-container-for-azure-batch-service-2mnn

**Comment by manuelesimi** [comment]
Hi @vinishgeorge, thanks for the update. I'm happy to know that it works also with ACR.

I haven't tried the ACR solution yet because I was able to use images from my private organization on Docker Hub. The configuration is similar to the one described in the tutorial you posted. My mistake (that I've now realized) was not to fully qualify the docker image to pull in the container option of the process. It has to be in the form `repository/org/name:tag` and I was missing the repository.

**Comment by manuelesimi** [comment]
@vinishgeorge I made some changes to Nextflow to optionally allow to configure a private container registry from each pool.

See https://github.com/nextflow-io/nextflow/pull/2078

**Comment by vinishgeorge** [comment]
@manuelesimi  I used your workaround of creating a existing Pool with the required credentials to login to the private registry and running the pipeline with the already existing Pool which then has access to all my private container registry images.

@manuelesimi   I would love to try out the changes you have done.
