### ISSUE TITLE
Parameter -queue-size not working for AWS batch

### ISSUE THREAD

**Issue by serverhorror** [nextflow-io/nextflow#1937]
## Bug report 

This is a re-opening of #963 

### Expected behavior and actual behavior

Using `nextflow -queue-size 10 foo.nf -profile aws` limits to at most 10 submitted jobs at a time for AWS batch.

### Steps to reproduce the problem

(Provide a test case that reproduce the problem either with a self-contained script or GitHub repository)

### Program output 

Same thing as described in #963 still hapenning, not sure what to do abou this, it is working with SLURM but seems completely ignored with AWS Batch.

I would expect the command below to submit in batches of at most 50 `files2lfr` processes

```
#nextflow run main.nf --nsamples 0 --credentials ./credentials.json --reportsDir "./xxx.perfTests/nsamples=xxx" -profile aws -queue-size 50

N E X T F L O W  ~  version 20.10.0
Launching `main.nf` [kickass_joliot] - revision: 9aebd9cb12
Uploading local `bin` scripts folder to s3://redacted/nextflow/work/xxx/tmp/39/a4124063079a2797e69a61a98dee27/bin
...
[df/8977cf] process > get_mdr_samples [100%] 1 of 1 ✔
[9d/5474a0] process > files2lfr (23)  [  0%] 0 of 3645
executor >  awsbatch (101)
[df/8977cf] process > get_mdr_samples [100%] 1 of 1 ✔
[81/fc2a75] process > files2lfr (5)   [  0%] 0 of 3571
[-        ] process > data2mxr        
-List of 7
 $ buildTime  : chr "Fri Feb 26 22:44:50 UTC 2021"
 $ tagVersion : chr "14-06eda3be"
 $ environment: chr "test"
 $ gitBranch  : chr "staging"
 $ gitCommit  : chr "0...9"
 $ buildUrl   : chr "https://example.invalid/redacted/"
 $ version    : chr "redacted"

Error executing process > 'files2lfr (3347)'
Caused by:
  Please reduce your request rate. (Service: Amazon S3; Status Code: 503; Error Code: SlowDown; Request ID: E...3; S3 Extended Request ID: I...I=)
```

### Environment 

* Nextflow version: 20.10.0
* Java version: Java/1.8.0_172
* Operating system: Linux
* Bash version:
  ```
  GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
  Copyright (C) 2011 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
  
  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.
  ```

/cc @apeltzer

**Comment by kgutwin** [comment]
You may wish to take a look at issue #1371 and this comment: https://github.com/nextflow-io/nextflow/issues/1371#issuecomment-588386609

If you note carefully, the error "Please reduce your request rate" is coming from S3, not Batch, and you may be able to work around the issue by updating your config to limit the number of parallel threads that are interacting with S3.

**Comment by serverhorror** [comment]
> If you note carefully, the error "Please reduce your request rate" is coming from S3, not Batch, and you may be able to work around the issue by updating your config to limit the number of parallel threads that are interacting with S3.

@kgutwin I saw that, however the problem is that that I do _not_ create massive files _per job_. It happens that nextflow starts hammering S3 because it wants to create a file per job (a couple of thousand of them) and this is extremely surprising to the user.

Apart from that I don't see how I have a sensible way of controlling when nextflow (the controlling instance, not anything in a job -- as far as I can tell) to limit its behaviour or, even better, sensibly implements an exponential back-off.

S3 coming back and telling nextflow to go slower is not something that I should have to deal with if it is outside of my job but inside the framework itself.

**Comment by kgutwin** [comment]
@serverhorror I fully agree, I came to this thread because I experienced the same frustrating problem killing my job mid-stream.

I would ask the Nextflow team to prioritize this issue, since it is a show-stopping problem for anyone who uses AWS Batch at any reasonable scale. It should not be the responsibility of the user to have to search GitHub issues to track down obscure tuning parameters in order to get their job to complete without crashing. Nextflow ought to be able to catch the SlowDown response code from S3 and respond accordingly -- at least retry so that the job doesn't crash.

**Comment by serverhorror** [comment]
> Nextflow ought to be able to catch the SlowDown response code from S3

This!

I wouldn't mind if I got that _inside_ of any of my scripts. It would be, clearly and categorically, my responsibility. But this is happening in a piece of code that is completely outside of my control.

**Comment by serverhorror** [comment]
bump, I'm not sure what to add here. But this is a bug in NextFlow itself, not in the scripts executed within a pipeline.

**Comment by pditommaso** [comment]
The `-queue-size` is not honoured when using AWS batch by design. Bathc compute environment max CPUs should be used instead to cap the max number of jobs that can be launched in parallel instead.

**Comment by robsyme** [comment]
For those that come after, the queueSize configuration is now honoured by the AWS batch executor.
