### ISSUE TITLE
unexpected script compilation error (reopen issue 1925)

### ISSUE THREAD

**Issue by GDCCP** [nextflow-io/nextflow#1938]
## Bug report 

[Issue 1925](https://github.com/nextflow-io/nextflow/issues/1925) is not resolved. I used -dsl2 option, so I need not specify the dsl2 header.

Even after adding the dsl2 header and re-run the command using 'nextflow run main.nf', I still end up with the same error.

I have also pulled down version 20.10.0 with anaconda3 and got the same error.

### Steps to reproduce the problem

[main.nf.txt](https://github.com/nextflow-io/nextflow/files/6058764/main.nf.txt)
1. download the main.nf.txt and rename it to main.nf
2. nextflow run main.nf

### Program output 

log from using nextflow 20.10.0
[nextflow.log](https://github.com/nextflow-io/nextflow/files/6058759/nextflow.log)

### Environment 

* Nextflow version: [20.10.0] 
* Java version: [openjdk 11]
* Operating system: [Centos7]
* Bash version: (4.2.46)

**Comment by brandoncazander** [comment]
It looks like you are pretty close to having this work. This change makes your workflow run for me.

```
-    def delay2="${Math.abs(new Random().nextInt() % dest.length()) + dest.length()}"
+    delay2="${Math.abs(new Random().nextInt() % dest.length()) + dest.length()}"
```

As I understand it, you must omit `def` when the [variable needs to be referenced as an output value](https://github.com/nextflow-io/nextflow/issues/678#issuecomment-386206123), which is true of `dest`, but I'm not entirely sure why the parser here thinks that `dest` is being redeclared in the string interpolation.

**Comment by GDCCP** [comment]
What I do not get is the comment in [issue 678](https://github.com/nextflow-io/nextflow/issues/678). What is the benefit of using 'def' and what exactly is the visibility/lifetime of delay2 or any variable without def defined in a process/workflow?

There are multiple 'instances' of a process/workflow where a non-def variable needs to have different values. If we need not worry about the variable using the wrong value from another instance, what is the point of being defensive and using 'def' when possible?
