### ISSUE TITLE
Azure Batch error: missing plugin nf-azure

### ISSUE THREAD

**Issue by tmuylder** [nextflow-io/nextflow#1946]
We've been very happy with the release of support for Azure Batch !! I started testing it and got stuck now with the following note:
```
N E X T F L O W  ~  version 21.02.0-edge
Launching nf-core-rnaseq/main.nf [tender_raman] - revision: 4b892cc54e
Install is not supported on dev mode - Missing plugin nf-azure
```
Even though the plugin is there ... Any ideas?  

I'm running the following command with version `21.02.0-edge` manually installed on the Azure Cloud Shell (both WSL & MA web): 
```
./nextflow-21.02.0-edge/launch.sh run nf-core-rnaseq/main.nf -profile test,docker -w az://nf-blob-container/work
```  
Resulting in following [nextflow.log](https://github.com/nextflow-io/nextflow/files/6067933/nextflow.log) file

I have been following guidelines in the article + documentation. So `nextflow.config` defines plugin id, azure executor, and other azure settings...

**Comment by pditommaso** [comment]
Don't think the [docs](https://www.nextflow.io/docs/edge/azure.html) mention the use of `launch.sh`, that's only for dev purpose. 

You have to install the latest edge version (as described in the link above) and use the `nextflow` command.

**Comment by tmuylder** [comment]
That results in the following installation:
```
      N E X T F L O W
      version 20.10.0 build 5430
      created 01-11-2020 15:14 UTC
      cite doi:10.1038/nbt.3820
      http://nextflow.io
```
That's why I started installing manually from the [latest tagged release](https://github.com/nextflow-io/nextflow/releases/tag/v21.02.0-edge) and installed with `make compile`.

**Comment by pditommaso** [comment]
ummm, what if you run 


```
NXF_VER= 21.02.0-edge nextflow info
```

**Comment by tmuylder** [comment]
I presume that is (in two steps): 
´´´
NXF_VER=21.02.0-edge
nextflow info
´´´ 
Also nothing:
´´´
  Version: 20.10.0 build 5430
  Created: 01-11-2020 15:14 UTC (16:14 CEST)
  System: Linux 5.4.0-1029-gcp
  Runtime: Groovy 3.0.5 on OpenJDK 64-Bit Server VM 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08
  Encoding: UTF-8 (UTF-8)
´´´
(Tested on Bash of Azure Cloud Shell, but also on a Google Cloud Instance Shell (I know that sounds weird))

**Comment by pditommaso** [comment]
sorry, there was a type in my command, please try the following not the one you have typed.  

```
NXF_VER=21.02.0-edge nextflow info
```

**Comment by tmuylder** [comment]
That works, less or more: 
```
  Version: 21.02.0-edge build 5516
  Created: 01-02-2021 15:34 UTC
  System: Linux 4.15.0-1108-azure
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.9+8-20200922
  Encoding: UTF-8 (UTF-8)
```
Afterward if you ask for `nextflow -v` it goes back to `nextflow version 20.10.0.5430`

**Comment by pditommaso** [comment]
You need to `export` that env variable in your environment 

https://devconnected.com/set-environment-variable-bash-how-to/

**Comment by tmuylder** [comment]
Obviously, however now stuck at: 
```
N E X T F L O W  ~  version 21.02.0-edge
Launching `nf-core-rnaseq/main.nf` [naughty_baekeland] - revision: 4b892cc54e
Downloading plugin nf-azure@0.9.4
Failed to write file '/home/tuur/.nextflow/plugins/nf-azure-0.9.4' to plugins folder
```
This is still in the Azure Cloud Shell though.

**Comment by pditommaso** [comment]
Fear you hit [this issue](https://github.com/nextflow-io/nextflow/issues/1882). I'll include the patch in the next release.

**Comment by tmuylder** [comment]
It didn't work in the beginning, but after re-installing it did! Wonderful & many many thanks @pditommaso ! 

So to summarize (this momentarily solution) for everyone that might see this later, on the **Azure Cloud Shell**: 
```
export NXF_VER=21.03.0-SNAPSHOT
curl get.nextflow.io | bash
```
Test:
```
$ nextflow info   
  Version: 21.03.0-SNAPSHOT build 5521
  Created: 08-02-2021 15:05 UTC
  System: Linux 4.15.0-1108-azure
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.9+8-20200922
  Encoding: UTF-8 (UTF-8)
```
Edit `nextflow.config` file as described [here](https://www.nextflow.io/docs/edge/azure.html). And that should do the trick :)

**Comment by manuelesimi** [comment]
Hi, 
I'm hitting the same problem on the Azure Cloud Shell, even though I have the correct configuration (working from my laptop with a remote Batch service).

This is what the nextflow.log says:
<pre>
Mar-02 17:26:38.546 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-azure version: latest
Mar-02 17:26:39.083 [main] INFO  nextflow.plugin.PluginUpdater - Downloading plugin nf-azure@0.9.4
Mar-02 17:26:40.805 [main] INFO  org.pf4j.util.FileUtils - Expanded plugin zip 'nf-azure-0.9.4.zip' in 'nf-azure-0.9.4'
Mar-02 17:26:40.813 [main] ERROR nextflow.cli.Launcher - @unknown
org.pf4j.PluginRuntimeException: Failed to write file '/home/manuele/.nextflow/plugins/nf-azure-0.9.4' to plugins folder
        at nextflow.plugin.PluginUpdater.download0(PluginUpdater.groovy:170)
        at nextflow.plugin.PluginUpdater.access$0(PluginUpdater.groovy)
        at nextflow.plugin.PluginUpdater$_safeDownload_closure2.doCall(PluginUpdater.groovy:188)
        at nextflow.plugin.PluginUpdater$_safeDownload_closure2.call(PluginUpdater.groovy)
        at nextflow.file.FileMutex.lock(FileMutex.groovy:107)
        at nextflow.plugin.PluginUpdater.safeDownload(PluginUpdater.groovy:188)
        at nextflow.plugin.PluginUpdater.load0(PluginUpdater.groovy:217)
        at nextflow.plugin.PluginUpdater.installPlugin(PluginUpdater.groovy:140)
        at nextflow.plugin.PluginUpdater.prepareAndStart(PluginUpdater.groovy:88)
        at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:194)
        at nextflow.plugin.PluginsFacade.start(PluginsFacade.groovy:199)
        at nextflow.plugin.PluginsFacade.setup(PluginsFacade.groovy:161)
        at nextflow.plugin.Plugins.setup(Plugins.groovy:39)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:272)
        at nextflow.cli.Launcher.run(Launcher.groovy:475)
        at nextflow.cli.Launcher.main(Launcher.groovy:657)
Caused by: java.nio.file.DirectoryNotEmptyException: /tmp/pf4j-update-downloader8742883140718395709/nf-azure-0.9.4
        at java.base/sun.nio.fs.UnixCopyFile.ensureEmptyDir(UnixCopyFile.java:384)
        at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:484)
        at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
        at java.base/java.nio.file.Files.move(Files.java:1421)
        at nextflow.plugin.PluginUpdater.download0(PluginUpdater.groovy:167)
        ... 15 common frames omitted
</pre>
From the stacktrace, it seems to fail when Nextflow is trying to move the decompressed plugin to its final destination.

I (temporarily) granted full permissions on ~/.nextflow to all users, but didn't help.

This is my environment on the console:

<pre>
./nextflow info
  Version: 21.02.0-edge build 5516
  Created: 01-02-2021 15:34 UTC
  System: Linux 4.15.0-1108-azure
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.9+8-20200922
  Encoding: UTF-8 (UTF-8)
</pre>

**Comment by tmuylder** [comment]
It worked for me with a different version @manuelesimi . For this I removed the nextflow folder(!) and then re-installed with the following: 
```
export NXF_VER=21.03.0-SNAPSHOT
curl get.nextflow.io | bash
```
(See my last comment above)

**Comment by manuelesimi** [comment]
Thanks @tmuylder!
I didn't notice the new build info you reported in your latest comment. 
I've updated nextflow to `version 21.03.0-SNAPSHOT build 5521` and it worked like a charm.

Also, thanks to @pditommaso for the patch.

**Comment by pditommaso** [comment]
Version 21.03.0-edge has been released.
