### ISSUE TITLE
Security warning when cleanup

### ISSUE THREAD

**Issue by GuillaumeTh** [nextflow-io/nextflow#1956]
Hi,

We have some security warning in the cleanup part in .command.run. When I run `sudo -n /bin/true` it requiert my password and it trigger automatically a security warning in the linux logs.

I would like to know what is the usecase to use sudo here: https://github.com/nextflow-io/nextflow/blob/ac2c0df9f8840e2de79bd8d8981746efa7a05728/modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy#L408

If it is legacy it could be nice to remove it to don't have any other security warning

**Comment by djdube1** [comment]
I'm working with @GuillaumeTh on the encountered issue. The main problem is that our sysadmin require the `mail_badpass` sudoer configuration on all users for security reasons. When running a reasonably large workload, these failing `sudo` commands can produce hundreds of warning emails in our auditing mailbox. Allowing privileged access just to clear a scratch space is also out of the question of our situation.

It doesn't seem like there's a better way to check for sudo permission that doesn't trigger the badpass condition, but I wonder if these sudo calls are even necessary. If they are for some use cases, would it be possible to implement some sort of configuration or flag to bypass any sudo calls?

Thanks,

**Comment by GuillaumeTh** [comment]
Hi @pditommaso, do you think that I could do a PR removing the sudo part ?

**Comment by pditommaso** [comment]
That's needed when using docker which usually runs as root and therefore files are created with root permission. 

I could make sense to only use sudo when then container engine is docker (I guess you are using you are using singularity)

**Comment by pditommaso** [comment]
Should be fine now.
