### ISSUE TITLE
docker '--cpus' error with nextflow 21.03.0-edge

### ISSUE THREAD

**Issue by skrakau** [nextflow-io/nextflow#1962]
### Expected behavior and actual behavior

When running the recent nextflow edge releases with docker, I get an `invalid argument "1,0" for "--cpus" flag` error for different processes. When using `20.12.0-edge` the error does not occur.

The `.command.run` contains the following docker command:
```
nxf_launch() {
    docker run -i --cpus 1,0 --memory 6144m -e "NXF_DEBUG=${NXF_DEBUG:=0}" -v /Users/skrakau:/Users/skrakau -v "$PWD":"$PWD" -w "$PWD" --entrypoint /bin/bash -u $(id -u):$(id -g) --name $NXF_BOXID nfcore/magbusco:1.2.0 -c "eval $(nxf_container_env); /bin/bash /Users/skrakau/Workspaces/test_mag/work/74/470c0786f121143cab42154daed3bb/.command.run nxf_trace"
}
```

### Steps to reproduce the problem

`nextflow run nf-core/mag -r 1.2.0 -profile docker,test`

### Program output 

```
Command error:
  invalid argument "1,0" for "--cpus" flag: failed to parse 1,0 as a rational number
  See 'docker run --help'.
```

### Environment 

* Nextflow version: 21.03.0-edge, 21.02.0-edge
* Java version: openjdk 11.0.8 2020-07-14 LTS
* Operating system: macOS
* Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

### Log file

[nextflow.log](https://github.com/nextflow-io/nextflow/files/6116541/nextflow.log)

Do you have any idea what could be wrong here?

**Comment by pditommaso** [comment]
Does your system use `,` as decimal separator ?

**Comment by skrakau** [comment]
actually I don't know where they should come from
```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by pditommaso** [comment]
Can you try running this and copy & paste here the result? 

```
echo 'println String.format("%.1f", 1.0)' | nextflow run - 
```

**Comment by pditommaso** [comment]
Ok, it's a problem with the local formatting on NF side.

**Comment by pditommaso** [comment]
Can you please try also this 

```
echo 'println String.format(Locale.ROOT, "%.1f", 1.0)' | nextflow run - 
```

**Comment by skrakau** [comment]
Ok, thanks for the quick answer! 

```
$ echo 'println String.format(Locale.ROOT, "%.1f", 1.0)' | nextflow run -
N E X T F L O W  ~  version 21.03.0-edge
1.0
```

**Comment by pditommaso** [comment]
ok, this seems to provide a patch

**Comment by pditommaso** [comment]
Thanks for reporting and your support to identify the problem. This patch will be included in the next release. In the meanwhile, the only workaround is to set the `.` as the decimal separator in your system.
