### ISSUE TITLE
nf-amazon plugin error with nextflow 21.03.0-edge

### ISSUE THREAD

**Issue by skrakau** [nextflow-io/nextflow#1963]
### Expected behavior and actual behavior

In order to handle files stored on an amazon S3 filesystem with nextflow `21.03.0-edge` I specified the `nf-amazon` plugin in a custom config file (as described in https://github.com/nextflow-io/nextflow/issues/1891), but I get an error.
 
### Steps to reproduce the problem

`nextflow run nf-core/mag -r 1.2.0 -profile cfc_dev,test -c my.config`

`my.config`:
```
plugins {
  id 'nf-amazon'
}

params {
  kraken2_db = "s3://nf-core-awsmegatests/mag/input_data/minikraken_8GB_202003.tgz"
}

process {
  scratch = 'false'
}
```

### Program output 

```
N E X T F L O W  ~  version 21.03.0-edge
Launching `nf-core/mag` [ridiculous_ritchie] - revision: 485c3fa0ba [1.2.0]
Unable to make field private static volatile java.util.List java.nio.file.spi.FileSystemProvider.installedProviders accessible: module java.base does not "opens java.nio.file.spi" to unnamed module @795cd85e
```

### Environment 

* Nextflow version: 21.03.0-edge
* Java version: openjdk 11.0.1 2018-10-16 LTS
* Operating system: CentOS 7.8
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

[nextflow.log](https://github.com/nextflow-io/nextflow/files/6117235/nextflow.log)

Is there anything else apart from adding this `nf-amazon` snippet that I need to consider?

**Comment by pditommaso** [comment]
Not a lucky day. Try upgrading the nextflow launcher eg 

```
nextflow -self-update
```

then try again

**Comment by skrakau** [comment]
Ah great :D that was easy, thanks!

**Comment by skrakau** [comment]
One more question @pditommaso :)

For the nf-core full-size mag test there is data stored on the amazon S3 filesystem, and it would be nice if this could be used when running the `test_full.config` test profile. However, when I add the plugin in this config file, I get
```
N E X T F L O W  ~  version 21.03.0-edge
Launching `/home-link/qeakr01/development/mag/main.nf` [mad_waddington] - revision: f377b362c1
Plugins definition is only allowed in config top-most scope
```

Would it not be possible to add this only for individual test profiles, such as others did for the `igenomes.config` (https://github.com/nf-core/rnaseq/blob/dev/conf/igenomes.config) ?

**Comment by pditommaso** [comment]
I think it's enough to remove it and then it's automatically added when using the aws executor.

**Comment by skrakau** [comment]
So far it was also possible to run this full-size test on non-aws instances. So if possible, it would be nice if this stays enabled in the future.

**Comment by cbioinstilbio** [comment]
Had a similar issue with the nf-amazon plugin. Tried nextflow -self-update but didn't help. Would appreciate any pointers here...

Command line input:
nextflow run nf-core/rnaseq --input samplesheet_nfcore_rnaseq.csv --genome GRCh37 -profile docker -c custom.config

where custom.config looks like this:
plugins {
  id 'nf-amazon'
}

Program output:
N E X T F L O W  ~  version 21.10.1
Launching `nf-core/rnaseq` [high_curran] - revision: 964425e3fd [master]
.nextflow/plr/74ebd415-63fb-4fec-9a46-3ce57da258f7/nf-amazon-1.3.2: Operation not supported

Environment:
Nextflow version: 21.10.1
Operating system: Linux on Azure VM

Nextflow log file:
[nextflow.log](https://github.com/nextflow-io/nextflow/files/7568118/nextflow.log)

**Comment by drernie** [comment]
I'm seeing this same issue.  Is this due to using a newer version of Java?
```
java --version
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
```
cf. https://stackoverflow.com/questions/68404913/illegalaccessexception-when-trying-to-modify-private-static-field
> The code in [Change private static final field using Java reflection](https://stackoverflow.com/questions/3301635/change-private-static-final-field-using-java-reflection) works in Java 1.8 but not in Java 17.

> In Java 17 the jdk.internal.reflect.Reflection class contains a map of classes which should have some or all of their members made invisible to reflection
> This has been the case since Java 12: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8210496

**Comment by Mahendra687** [comment]
nextflow run nf-core/viralrecon -r 2.6.0 -profile singularity \
--max_memory '12.GB' --max_cpus 4 \
--input samplesheet.csv \
--outdir results/viralrecon \
--protocol amplicon \
--genome 'MN908947' \
--primer_set artic \
--primer_set_version 3 \
--skip_kraken2 \
--skip_assembly \
--skip_pangolin \
--skip_nextclade \
--skip_mosdepth \
--skip_asciigenome \
--skip_variants_quast \
--platform illumina \
--fasta MN908947.fasta \
--primer_bed primers.bed \

Output with following error:
Downloading plugin nf-amazon@2.1.4
WARN: Unable to start plugin 'nf-amazon' required by s3://ngi-igenomes/test-data/viralrecon/kraken2_human.tar.gz
ERROR ~ Missing plugin 'nf-amazon' required to read file: s3://ngi-igenomes/test-data/viralrecon/kraken2_human.tar.gz

-- Check script '/home/ms/.nextflow/assets/nf-core/viralrecon/./workflows/illumina.nf' at line: 26 or see '.nextflow.log' file for more details
Can anyone fix this?
