### ISSUE TITLE
Azure complains about wildcard and defining PE reads: path/*{1,2}.fq.gz. Illegal character at index 

### ISSUE THREAD

**Issue by tmuylder** [nextflow-io/nextflow#1969]
## Bug report 

I'm launching a nextflow pipeline from Azure Cloud Shell with data in the Blob Container. Even though it did find my reference genome, it didn't find my files. 

The reads are defined in a separate params file, included in `nextflow.config`. 
```
params {
    reads = "az://nf-blob-container/data/*{1,2}.fq.gz"
    genome = "az://nf-blob-container/data/Drosophila_melanogaster.BDGP6.dna.fa"
    gtf = "az://nf-blob-container/data/Drosophila_melanogaster.BDGP6.85.sample.gtf"
...
}
```

Run pipeline with:
```
nextflow run example-pipeline/dsl2-RNAseq.nf -profile azure,docker -w az://nf-blob-container/data/work
```
Output:
```
...
Illegal character in path at index 29: az://nf-blob-container/data/*{1,2}.fq.gz
```

It does run when I specify one read only (even though it finally also fails because my pipeline expects PE reads...).

### Additional question:
What is best practice to organise your input and output data? All in the blob containers or in file storage (or in cloud shell directory)?

**Comment by pditommaso** [comment]
Please include the .nextflow.log file.

**Comment by tmuylder** [comment]
Nextflow log file: [nextflow.log](https://github.com/nextflow-io/nextflow/files/6139893/nextflow.log)

**Comment by pditommaso** [comment]
I'm not able to replicate this issue. Could you please provide a small test case showing the error?

**Comment by pditommaso** [comment]
This is very useful, thanks

**Comment by tmuylder** [comment]
We're currently benchmarking Azure-Nextflow in our lab, but wasn't sure whether I was supposed to have the input data files in the blob container storages as well. And whether I am calling them correctly. If I need to do it in another way or if I can test something, please let me know.

**Comment by pditommaso** [comment]
Yes, the data is expected to be into a Azure blob container to reduce data transfer. You can try it adding in your config 

```
plugins {
   id 'nf-azure@ 0.9.6'
}
```

**Comment by pditommaso** [comment]
Closing this, feel free to comment below or re-open if necessary

**Comment by tmuylder** [comment]
It seems to still be giving an error (UnexpectedCharacterException). Couldn't find any relateble issues or problems in Gitter, so I'm reopening. 

```
nextflow run example-pipeline/dsl2-RNAseq.nf -profile azure,docker -w az://nf-blob-container/work
```

With output:

```
N E X T F L O W  ~  version 21.03.0-SNAPSHOT
Launching `example-pipeline/dsl2-RNAseq.nf` [tender_gutenberg] - revision: 7ca197513f
Downloading plugin nf-azure@ 0.9.6
Unexpected error [UnexpectedCharacterException]
```

Log file: [nextflow.log](https://github.com/nextflow-io/nextflow/files/6169457/nextflow.2.log)

**Comment by pditommaso** [comment]
I think there's an extra blank `nf-azure@ 0.9.6`, should be `nf-azure@0.9.6`

**Comment by pditommaso** [comment]
Damn, was my mistake in the example above. Corrected.

**Comment by tmuylder** [comment]
Ah, the plugins are new for me, so didn't know the writing conventions. Works like a charm now! 

Once again, many many many thanks for your swift replies & help!!!
