### ISSUE TITLE
Support flexible PBS resource syntax

### ISSUE THREAD

**Issue by tracychew** [nextflow-io/nextflow#1970]
# New feature

The PBS cluster we use does not support the use of `-l select` or `-l nodes`. Instead, `-l ncpus` and `-l mem` is used to determine the number of nodes required.

I suggest having the  `-l select` or `-l nodes` as optional PBS directives to enable more flexible use of nextflow with PBS Pro.

**Comment by marcodelapierre** [comment]
Some more context here: @tracychew and I are trying to have Nextflow up and running at NCI in Canberra, one of Australia's two tier-1 supercomputing facilities.

My current impression is that usage of `-l ncpus` and `-l mem` would be more general as opposed to `-l select` ; however we need to investigate on this statement.

**Comment by marcodelapierre** [comment]
this was discussed in previous issues, e.g. https://github.com/nextflow-io/nextflow/issues/867

**Comment by pditommaso** [comment]
Have you tried both [pbs](https://github.com/nextflow-io/nextflow/blob/914d7cb40bf58ff977717cd137352e7dfe97dbdb/modules/nextflow/src/main/groovy/nextflow/executor/PbsExecutor.groovy) and [pbspro](https://github.com/nextflow-io/nextflow/blob/914d7cb40bf58ff977717cd137352e7dfe97dbdb/modules/nextflow/src/main/groovy/nextflow/executor/PbsProExecutor.groovy) executors?

**Comment by marcodelapierre** [comment]
hi @pditommaso , forgot to update this. 
I investigated with NCI team, they deliberately configured PBS there in a non-standard way, disabling the use of `select`.

The executor `pbspro` can be made to work by patching the Nextflow source and re-building on premises.

At this stage, I don't have any information on whether making `select` optional in the public Nextflow would be compatible with other PBS installations.

**Comment by marcodelapierre** [comment]
I think this can be closed

**Comment by pditommaso** [comment]
OK, thanks Marco
