### ISSUE TITLE
syntax sugar to extract value from a file

### ISSUE THREAD

**Issue by eldadkd** [nextflow-io/nextflow#1978]
## Usage scenario 

sometimes my process script just calculates a number like getting the average read length of reads in a fast file
calculating percentage etc.
I want to pass this result as a val on the channel. 
the workaround I've found is to write this result into a file and on the out-channel, I map the path into val using the getText() method.
like ProcessP.out.map{it.getText()} now I have a channel of val instead of path

## Suggest implementation 

I suggest as a syntax sugar to do this map on the output section in the process, something like this:
process X{

input:
 path(x)

output:
**val(out_file.getText())**

script:
    out_file = "xout"
    """
    # run a script that reads x and write a value to  $out_file
    """
}

**Comment by GDCCP** [comment]
Take a look at ['stdout'](https://www.nextflow.io/docs/latest/process.html#output-stdout-special-file)

**Comment by pditommaso** [comment]
Indeed, use [stdout](https://www.nextflow.io/docs/latest/process.html#output-stdout-special-file) or [env](https://www.nextflow.io/docs/latest/process.html#output-env) output types

**Comment by eldadkd** [comment]
@GDCCP, @pditommaso, Thanks!
