### ISSUE TITLE
Nested params in different scopes overwrite each other

### ISSUE THREAD

**Issue by mjhipp** [nextflow-io/nextflow#1982]
### Expected behavior and actual behavior

When defining nested params in the curly brackets notation, a nested param in a different scope will overwrite ones found before, if they have a similar path.

For example, If I have a `nextflow.config` file:

```nextflow
params {
  foo {
    bar = 'bar1'
  }
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
}
```

**Expected:** I can print out the `config` and see the same thing that I passed in.

**Actual:** When I print out the `config`, I see that `nested.foo.bar` has overwritten `foo.bar` to be `'bar2'`.

#### Files

**`test1.config`**:

```nextflow
params {
  foo {
    bar = 'bar1'
  }
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
}
```

**`printparams.nf`**:

```nextflow
log.info "$params"
```

#### Command

These two commands show the same result in different formats:

```
NXF_VER="21.03.0-edge" nextflow -C test1.config config
```

```
NXF_VER="21.03.0-edge" nextflow -C test1.config run printparams.nf
```

### Program output 

From `config` command:

```
params {
   foo {
      bar = 'bar2'
   }
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar2'
      }
   }
}
```

From `printparams.nf`:

```
N E X T F L O W  ~  version 21.03.0-edge
Launching `printparams.nf` [sad_saha] - revision: 4d4685b5b4
[foo:[bar:bar2], baz:baz1, nested:[baz:baz2, foo:[bar:bar2]]]
```

### Environment 

* Nextflow version: `21.03.0-edge` 
* Java version: `openjdk version "1.8.0_232"`
* Operating system: macOS
* Bash version: `zsh 5.8 (x86_64-apple-darwin20.0)`

### Additional context

Above, using `test1.config`, (**Example 1**), we see that `nested.foo.bar` overwrites `foo.bar`. here are more examples:

#### Example 2

Here, `nested2.foo.bar` overwrites `nested.foo.bar` and `foo.bar`

test2.config:
```nextflow                    
params {
  foo {
    bar = 'bar1'
  }
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
  bar = 'bar3'
  nested2 {
    baz = 'baz3'
    foo {
      bar = 'bar4'
    }
  }
}
```
```
❯ NXF_VER="21.03.0-edge" nextflow -C test2.config config
params {
   foo {
      bar = 'bar4'
   }
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar4'
      }
   }
   bar = 'bar3'
   nested2 {
      baz = 'baz3'
      foo {
         bar = 'bar4'
      }
   }
}
```

#### Example 3

If I list the shallowest scope last, there is no overriding:

test3.config:
```nextflow
params {
  baz = 'baz1'
  nested {
    baz = 'baz2'
    foo {
      bar = 'bar2'
    }
  }
  bar = 'bar3'
  nested2 {
    baz = 'baz3'
    foo {
      bar = 'bar4'
    }
  }
  foo {
    bar = 'bar1'
  }
}
```
```
❯ NXF_VER="21.03.0-edge" nextflow -C test3.config config
params {
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar2'
      }
   }
   bar = 'bar3'
   nested2 {
      baz = 'baz3'
      foo {
         bar = 'bar4'
      }
   }
   foo {
      bar = 'bar1'
   }
}
```

#### Example 4

If I use dot-notation, there is also no unwanted overwriting:

test4.config (equal information as test1.config, different format):
```nextflow
params.foo.bar = 'bar1'
params.baz = 'baz1'
params.nested.baz = 'baz2'
params.nested.foo.bar = 'bar2'
```
```
❯ NXF_VER="21.03.0-edge" nextflow -C test4.config config
params {
   foo {
      bar = 'bar1'
   }
   baz = 'baz1'
   nested {
      baz = 'baz2'
      foo {
         bar = 'bar2'
      }
   }
}
```

**Comment by mjhipp** [comment]
To add, I have tried this with the newest commit on master and get the same results:

❯ ~/git-repos/nextflow/launch.sh -C test1.config run printparams.nf
N E X T F L O W  ~  version 21.04.0-SNAPSHOT
Launching `printparams.nf` [pedantic_sanger] - revision: 4d4685b5b4
[foo:[bar:bar2], baz:baz1, nested:[baz:baz2, foo:[bar:bar2]]]

**Comment by jrm5100** [comment]
I can confirm this bug still exists.

I'd guess the problematic code is here:

https://github.com/nextflow-io/nextflow/blob/73899f3b7967f3bd9bc393749a80ce893368a28e/modules/nextflow/src/main/groovy/nextflow/config/ConfigParser.groovy#L239-L251

Notably, this seems to be somewhat of a workaround (based on the first example):

`test1_workaround.config`

```
foo = {bar = 'bar1'}
nested = {
            baz = 'baz2'
            foo {
                bar = 'bar2'
            }
}

params {
        foo = foo
        baz = 'baz1'
        nested = nested
}
```

Using the latest release (`21.04.3.5560`), `nextflow -C test1_workaround.config config` results in:

```
foo = {bar = 'bar1'}
nested = {
            baz = 'baz2'
            foo {
                bar = 'bar2'
            }
}

params {
   foo = {bar = 'bar1'}
   baz = 'baz1'
   nested = {
            baz = 'baz2'
            foo {
                bar = 'bar2'
            }
}
}
```

Using this workflow:
```
log.info "params.foo = $params.foo"
log.info "params.foo.bar = $params.foo.bar"
log.info "params.baz = $params.baz"
log.info "params.nested = $params.nested"
log.info "params.nested.baz = $params.nested.baz"
log.info "params.nested.foo = $params.nested.foo"
log.info "params.nested.foo.bar = $params.nested.foo.bar"
```

Results in

```
params.foo =
params.foo.bar = bar1
params.baz = baz1
params.nested =
params.nested.baz = baz2
params.nested.foo = [bar:bar2]
params.nested.foo.bar = bar2
```
