### ISSUE TITLE
Make nextflow clone independent of the assets directory

### ISSUE THREAD

**Issue by szymonwieloch** [nextflow-io/nextflow#1986]
## Bug report 

the `nextflow clone` command is written in a way that basically prevents user from obtaining the given version of source code. Some examples:

1. This command should obtain the master branch of the mypipline project. Instead it copies whatever is present in the ~/.nextflow/assets directory (and there was a different branch):

```
nextflow clone pipelines/mypipeline -hub myhub
```

2. This command does not checkout anything - only empty directory and .git subdir:
```
nextflow clone pipelines/mypipeline -hub myhub -r master
```

3. This command works but has side effects - changes whatever is present in the ~/.nextflow/assets directory, therefore is not suitable for scripting:

```
nextflow pull pipelines/mypipeline -hub myhub -r master
nextflow clone pipelines/mypipeline -hub myhub -r master
```

4. This version also works but also has side effects:

```
nextflow drop pipelines/mypipeline
nextflow clone pipelines/mypipeline -hub myhub -r master
```

### Expected behavior and actual behavior

1. `nextflow clone` command should be independent of what is present in the ~/.nextflow/assets directory.
2. It should always dowload the newest version of the given branch (even if the assets dir contains an older version, this is how the git clone works).
3. It should not have any side effects.

### Environment 

* Nextflow version: 20.10.0

**Comment by jorgeaguileraseqera** [comment]
Reading the documentation ( https://www.nextflow.io/docs/latest/cli.html?highlight=pull#clone ) you can read `clone` works into the current dir. If you want to use the assets directory you need to use the pull command


    The clone command downloads a pipeline from a Git-hosting platform 
    into the current directory and modifies it accordingly. 
    For downloading a pipeline into the global cache ~/.nextflow/assets, 
    please refer to the nextflow pull command
