### ISSUE TITLE
nextflow pull gets pipeline metainformation from the master branch - even if other branch is specified.

### ISSUE THREAD

**Issue by szymonwieloch** [nextflow-io/nextflow#1988]
## Bug report 

We had an empty repository in a BitBucket distribution. Following good practices the pipeline was developed on a feature branch. To our surprise it was not possible to pull or clone this branch. It seems that NextFlow obtains some metainformation about the pipeline always from the master branch. In our case the master branch was empty.

Here is an example command execution (URLs changed because of security, but they provide reasonable insights into the source of the problems):

```
> nextflow clone pipelines/mypipeline -hub my_bitbucket -r somebranch
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://bitbucket.ourdomain.com/rest/api/1.0/projects/pipelines/repos/mypipeline/raw/nextflow.config
Remote resource not found: https://bitbucket.ourdomain.com/rest/api/1.0/projects/pipelines/repos/mypipeline/raw/main.nf
```

As you can see, the branch name is not used in the API calls. Clearly NextFlow obtain manifest information from the master branch instead of the branch that was selected.

### Environment 

* Nextflow version: 20.10.0

**Comment by pditommaso** [comment]
The support for this has been added recently. 

https://github.com/nextflow-io/nextflow/commit/6d08ae86eddc3c6c14a1e044d481a13b97c47317


You may want to try version `21.03.0-edge`

**Comment by pditommaso** [comment]
In a nutshell, the problem here is that Nextflow looks into the repository for either for the `nextflow.config` or `main.nf` files irrespective of the revision specified by the user. 

For example: 


```
» nextflow run https://github.com/pditommaso/nf-test-branch -r dev
N E X T F L O W  ~  version 22.04.0
Pulling pditommaso/nf-test-branch ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/pditommaso/nf-test-branch/contents/nextflow.config
Remote resource not found: https://api.github.com/repos/pditommaso/nf-test-branch/contents/main.nf
```

It should be possible to use the revision information to check in the revision branch/tag for those files

**Comment by jorgeaguileraseqera** [comment]
@pditommaso can you create/replicate your `pditommaso/nf-test-branch` into `nextflow-io` organization? 

I would create some tests and I think it's better to have it under `nextflow-io` instead of personal repo

**Comment by pditommaso** [comment]
Makes sense done
