### ISSUE TITLE
ABORTED job getting cached in next run

### ISSUE THREAD

**Issue by anoronh4** [nextflow-io/nextflow#1990]
## Bug report 

We are seeing ABORTED jobs from one run being CACHED in subsequent `resume` runs.

### Expected behavior and actual behavior
We are expecting `ABORTED` jobs to not be cached and instead the task should be reattempted when we resume the run. Instead, the `ABORTED` job registers in the next run as `CACHED`. This leads to failures in the subsequent process. In this case `SplitLanesR2` was originally `ABORTED` (and produces `.exitcode` file with `0` in it) and in the later runs, `AlignReads` step for the sample fails because fastq produced from `SplitLanesR2` is truncated. This doesn't seem to be consistent behavior, as AlignReads was also aborted without an exit code but was reattempted in the latest run. 
```
$ grep -P "^task_id|sampleA" ./trace.txt* | cut -f 1,2,3,4,7,16-20
./trace.txt:task_id	hash	native_id	process	status	submit	start	complete	duration	realtime
./trace.txt:192	7f/930475	67048103	SplitLanesR1	CACHED	2021-02-22 10:20:18.645	2021-02-22 10:20:33.964	2021-02-22 11:28:24.577	1h 8m 6s	1h 7m 22s
./trace.txt:243	cf/7a152d	67048106	SplitLanesR2	CACHED	2021-02-22 10:20:18.808	2021-02-22 10:20:33.977	-	-	-
./trace.txt:617	b6/3d6650	72290307	AlignReads	FAILED	2021-03-22 09:43:15.807	2021-03-22 09:43:27.379	2021-03-22 09:45:28.914	2m 13s	2m 2s
./trace.txt:881	96/4afaf1	72290321	AlignReads	FAILED	2021-03-22 09:45:29.456	2021-03-22 09:45:33.903	2021-03-22 09:48:33.913	3m 4s	3m
./trace.txt:884	36/69a480	72290332	AlignReads	FAILED	2021-03-22 09:48:33.994	2021-03-22 09:48:38.913	2021-03-22 09:51:28.929	2m 55s	2m 50s
./trace.txt:887	e2/0848f7	72290380	AlignReads	FAILED	2021-03-22 09:51:29.022	2021-03-22 09:51:33.927	2021-03-22 09:54:51.249	3m 22s	3m 17s
./trace.txt.1:task_id	hash	native_id	process	status	submit	start	complete	duration	realtime
./trace.txt.1:212	cf/7a152d	67048106	SplitLanesR2	CACHED	2021-02-22 10:20:18.808	2021-02-22 10:20:33.977	-	-	-
./trace.txt.1:259	7f/930475	67048103	SplitLanesR1	CACHED	2021-02-22 10:20:18.645	2021-02-22 10:20:33.964	2021-02-22 11:28:24.577	1h 8m 6s	1h 7m 22s
./trace.txt.1:671	c8/60f6c2	67769148	AlignReads	ABORTED	2021-02-24 13:42:05.804	-	-	-	-
./trace.txt.2:task_id	hash	native_id	process	status	submit	start	complete	duration	realtime
./trace.txt.2:197	7f/930475	67048103	SplitLanesR1	COMPLETED	2021-02-22 10:20:18.645	2021-02-22 10:20:33.964	2021-02-22 11:28:24.577	1h 8m 6s	1h 7m 22s
./trace.txt.2:206	cf/7a152d	67048106	SplitLanesR2	ABORTED	2021-02-22 10:20:18.808	2021-02-22 10:20:33.977	-	-	-
```
The log for the aborted SplitLanesR2 job (which also gave exitcode 0) says:
```
TERM_OWNER: job killed by owner.
Exited with signal termination: 14.
```
And all output files are copied to the `work` directory (we are using `scratch`), including a file that is has been coded to generate after the file that was truncated is generated.

### Steps to reproduce the problem

This problem may not be easily reproducible. However we have for a long time been using:
`beforeScript = "catch_term () { echo 'caught USR2/TERM signal'; set +e; false; on_exit ; } ; trap catch_term USR2 TERM"` to capture TERM signals as errors and produce a non-zero exit code. This has worked well to reduce falsely reported `COMPLETED` tasks in situations where they are not aborted, but obviously not in this case because i have found it a few times in the past few weeks.  

### Program output 

I cannot share the .nextflow.log easily because it contains sensitive information. I will try to follow up shortly with an example that does not have sensitive information. There is nothing in .command.out and .command.err for this step, but the following step `AlignReads` gives a few errors:
```
ERROR: sequence and quality have different length:
@K00121:309:H3CLLBBXY:6:1108:24566:1789 2:N:0:TAGCATGA
TCCCTACATCACTCTCTCGCCCAGCTCCATCCTGCTAGGTTCTTACCAACAGTCTCTGTCTTACTCATACTCC
...
[W::bseq_read] the 2nd file has fewer sequences.
[gzclose] buffer error
```
The file producing the errors is clearly truncated.

### Environment 

* Nextflow version: 20.04.1
* Java version: 8
* Operating system: CentOS7
* Bash version: 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

We are using the `lsf` executor and singularity dockers, and `scratch = true`

**Comment by Nathanrown** [comment]
I have had this problem as well. @bentsherman

**Comment by Nathanrown** [comment]
> 

I have tried it with 23.04.0.  
In fact when I cancel the job, I found that the status of the task was not aborted but succeeded, but the logs and weblog reminded me that it was aborted.

job logs
`WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=1; retriesCount=0; abortedCount=3; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=1; loadMemory=0; peakRunning=4; peakCpus=4; peakMemory=0; ] `

task command
`  ls input.1
  echo input.1 >> output_channel
  cat input.1
  mkdir target_`date +%y%m%d`
  cp input.1 target_`date +%y%m%d`
  echo finish`
task log
` 2023-04-12T04:53:58Z  input.1 
 2023-04-12T04:53:58Z  /project/untitled1.txtfinish `

**Comment by Nathanrown** [comment]
sure! 
[nextflow_.log](https://github.com/nextflow-io/nextflow/files/11250484/nextflow_.log)

**Comment by bentsherman** [comment]
Thank you. I see these tasks were executed with K8s but you originally said you were using LSF, so are you seeing this behavior across multiple executors?

**Comment by bentsherman** [comment]
Also, it says the only cause was SIGTERM, did you cancel it with e.g. Ctrl-C or was it cancelled some other way?

**Comment by bentsherman** [comment]
Whoops, my apologies. In any case, it's definitely an abort rather than a cancel (which would wait for the tasks to finish).

I suspect there is some race condition which affects the final status of an aborted task. Particularly strange is that the OP says an aborted task had an `.exitcode` file with `0`, as if the task finished successfully, but the output was truncated.

Can you provide a minimal example that I can use to reproduce the issue? I think I just need to start a pipeline with some long-running tasks and send it a SIGTERM, but just want to make sure there aren't any extra confounding factors in your case. I don't think K8s is related, so local pipeline should be fine.

**Comment by Nathanrown** [comment]
This is the script file I got from manual.
`params.str = 'Hello world! Hello Nextflow!'

process splitLetters {
  output:
    path 'chunk_*'

  """
  printf '${params.str}' | split -b 6 - chunk_
  echo '${params.str}'
  """
}

process convertToUpper {
  input:
    path x
  output:
    stdout

  """
  echo $x | tr '[a-z]' '[A-Z]'
  echo '${params.str}'
  """
}

workflow {
  splitLetters | flatten | convertToUpper | view { it.trim() }
}`

run this pipeline, when process `convertToUpper` running， stop it with Ctrl +C .
maybe u can get the same log like this 
[nextflow.log](https://github.com/nextflow-io/nextflow/files/11260135/nextflow.log)

**Comment by pditommaso** [comment]
Thanks for reporting this detailed error report. This was indeed a bug. A has been submitted (144e0a8a) and it will be included in next release.
