### ISSUE TITLE
Singularity driver gives bad (empty) values for TMPDIR and TMP if unset

### ISSUE THREAD

**Issue by pontus** [nextflow-io/nextflow#1997]
## Bug report 

When using the singularity container driver, it tries to be nice and forward TMPDIR and TMP so they have similar settings inside the container (https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy#L104).

But if either is unset, it will result in the corresponding value being set to the empty value. Normally, this is likely not a problem but  when using tools respecting `TMPDIR` or `TMP`, it may cause issues (https://github.com/nf-core/clipseq/issues/31).

### Expected behavior and actual behavior

I'd expect to have the same values set inside the container as outside. Actual behaviour is these two are set but empty if unset or without value outside the container.

### Steps to reproduce the problem

```
$ cat test.nf 
#!/usr/bin/env nextflow

process env {
  script:
    """
    if [ -n "\${TMPDIR+isset}" ] && [ -z "\$TMPDIR" ] ; then
       exit 1
    fi
    """
}
$ nextflow run test.nf 
N E X T F L O W  ~  version 20.10.0
Launching `test.nf` [jolly_kowalevski] - revision: 924e0c1356
executor >  local (1)
[ef/c94a53] process > env [100%] 1 of 1 ✔

$  nextflow run test.nf -with-singularity ubuntu_latest.sif 
N E X T F L O W  ~  version 20.10.0
Launching `test.nf` [jolly_swirles] - revision: 924e0c1356
executor >  local (1)
[9d/a0407d] process > env [100%] 1 of 1, failed: 1 ✘
Error executing process > 'env'

Caused by:
  Process `env` terminated with an error exit status (1)

Command executed:

  if [ -n "${TMPDIR+isset}" ] && [ -z "$TMPDIR" ] ; then
     exit 1
  fi

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /home/pontus/work/9d/a0407d78152b9a9a438d5dd15f996a

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

$ 

```

### Program output 

See test case and referenced clipseq issue.

### Environment 

* Nextflow version: 20.10.0
* Java version: OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.10, mixed mode, sharing)
* Operating system: Linux Ubuntu 20.10
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by pditommaso** [comment]
Ok, the patch above should solve. Could you please confirm?

**Comment by pontus** [comment]
Seems to work for my test case. I've asked for confirmation from the one who had the original issue but suspect any remaining issues will be things my analysis didn't catch because of this, so I'm fine with closing this issue.

**Comment by pontus** [comment]
Seems to have solved original issue as well.
