### ISSUE TITLE
nextflow.exception.ProcessFailedException: Process '~~' terminated with an error exit status

### ISSUE THREAD

**Issue by hmkim** [nextflow-io/nextflow#200]
Can you check this?

I don't know what is the problem.

[nf.log.txt](https://github.com/nextflow-io/nextflow/files/360507/nf.log.txt)

**Comment by pditommaso** [comment]
You pipeline execution was stopped by an error when running bwa: 

```
Error executing process > 'mapping (TN1605D1171--CAAGACTA_S11_L002)'

Caused by:
  Process 'mapping (TN1605D1171--CAAGACTA_S11_L002)' terminated with an error exit status

Command executed:

  bwa mem -M -R '@RG\tID:TN1605D1171--CAAGACTA_S11_L002\tSM:TN1605D1171--CAAGACTA_S11_L002\tPL:Illumina' -t 5 /BiO/BioTools/bcbio/data/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa TN1605D1171--CAAGACTA_S11_L002_R1_001.fastq.gz TN1605D1171--CAAGACTA_S11_L002_R2_001.fastq.gz | samblaster | samtools view -u -Sb - | samtools sort - -o TN1605D1171--CAAGACTA_S11_L002.bam
  samtools index TN1605D1171--CAAGACTA_S11_L002.bam

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /BiO/BioPeople/brandon/test_nextflow/qc/work/20/4f63e680b16ec29bb9898a8bed1053
```

What you can do is change into the directory `/../work/20/4f63e680b16ec29bb9898a8bed1053` and re-execute that command to understand what is not working by running `bash .command.run`

**Comment by hmkim** [comment]
In working directory,

$ bash .command.run
samblaster: Version 0.1.22
samblaster: Inputting from stdin
samblaster: Outputting to stdout
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 495050 sequences (50000050 bp)...

$ cat .command.sh
#!/bin/bash -ue
bwa mem -M -R '@RG\tID:TN1605D1182--AAGACGGA_S27_L004\tSM:TN1605D1182--AAGACGGA_S27_L004\tPL:Illumina' -t 5 /BiO/BioTools/bcbio/data/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa TN1605D1182--AAGACGGA_S27_L004_R1_001.fastq.gz TN1605D1182--AAGACGGA_S27_L004_R2_001.fastq.gz | samblaster | samtools view -u -Sb - | samtools sort - -o TN1605D1182--AAGACGGA_S27_L004.bam
samtools index TN1605D1182--AAGACGGA_S27_L004.bam


it has not issue with .command.run  but when I run the nextflow, it has the error.

Can you examine for this problem?

**Comment by pditommaso** [comment]
What's the exist status `bash .command.run` ?

**Comment by hmkim** [comment]
[M::mem_pestat] mean and std.dev: (627.44, 343.84)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 3086)
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_process_seqs] Processed 441132 reads in 114.840 CPU sec, 24.668 real sec
[main] Version: 0.7.15-r1140
[main] CMD: bwa mem -M -R @RG\tID:TN1605D1182--AAGACGGA_S27_L004\tSM:TN1605D1182--AAGACGGA_S27_L004\tPL:Illumina -t 5 /BiO/BioTools/bcbio/data/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa TN1605D1182--AAGACGGA_S27_L004_R1_001.fastq.gz TN1605D1182--AAGACGGA_S27_L004_R2_001.fastq.gz
[main] Real time: 7374.288 sec; CPU: 30816.772 sec
samblaster: Marked 1896661 of 57151316 (3.32%) read ids as duplicates using 1177152k memory in 3M3S(182.668S) CPU seconds and 2H2M55S(7375S) wall time.
[bam_sort_core] merging from 79 files...
/BiO/BioPeople/brandon/test_nextflow/qc/work/31/370ab4d7822fd82465e27d515a4c0d/.command.run.1: line 90: 44220 Terminated              nxf_trace "$pid" .command.trace

exit code is 0.

When the running with command line (.command.run), I saw the BAM file after mapping with raw reads normally.

**Comment by pditommaso** [comment]
Can you upload a tar (or zip) including `.command.*` and `.exitcode` files in that folder?

**Comment by hmkim** [comment]
[data.tar.gz](https://github.com/nextflow-io/nextflow/files/364980/data.tar.gz)

(no FASTQ and result BAM file, just .*)

**Comment by pditommaso** [comment]
I think the problem is this code that you put int the `beforeScript`: 

    set +u; source activate qc; set -u

What is supposed to do? `source` is used to load a BASH script which `activate` is not.

**Comment by hmkim** [comment]
I use the conda (http://conda.pydata.org/docs/) in my workflow.

so, this conda have function of the environment (http://conda.pydata.org/docs/using/envs.html) .

I think this is very useful in many bioinformatics workflows.

First, I tried to run this command ($ source activate qc).
but, my shell command fails with with errors about an "unbound variable".
so, I try to fix  with this commands ( set +u; set -u ).

**Comment by pditommaso** [comment]
Yes, but [source](http://ss64.com/bash/source.html) make no sense used in that way. In best case is doing nothing, in the worst is breaking your pipeline. 

I would suggest to remove it (or use it properly) and re-execute your pipeline.

**Comment by hmkim** [comment]
Thanks, I'll try to use the conda in other methods.
