### ISSUE TITLE
Mitigating kubernetes temporary errors

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#2003]
It seems that if kubernetes executor encounter some error with k8s api, while execution pipeline is terminated.

E.g.: 

Mar-27 22:46:31.222 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'MapReads (MU_a_lgFM-HKYVNDSXY)'

Caused by:
  Request GET /api/v1/namespaces/nf-core/pods/nf-99a476808480052c000113a11e05f4c9/status returned an error code=500

  {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {

      },
      "status": "Failure",
      "message": "etcdserver: leader changed",
      "code": 500
  }

can we specify some retry options?

Similarly:
Mar-28 20:47:19.727 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'VEP (MU_a_lgFM - Manta - Manta_MU_a_lgFM.diploidSV.vcf.gz)'

Caused by:
  K8s undetermined status conditions for pod nf-c233f228a1c1cde88da154da2780c725
[...]
"status": {
          "phase": "Failed",
          "message": "The node was low on resource: ephemeral-storage. ",
          "reason": "Evicted",
          "startTime": "2021-03-28T20:34:25Z"
      }

pod can be restarted on another node.

Can we set some retry options?

**Comment by pditommaso** [comment]
Unable to replicate
