### ISSUE TITLE
Turn on sorting as groupTuple default

### ISSUE THREAD

**Issue by GDCCP** [nextflow-io/nextflow#2006]
## New feature

changing operator groupTuple's sort default value to true or 'hash'

## Usage scenario 

Adding '-resume' supposedly does the magic, yet the current groupTuple() default doesn't sort the list values and as a result '-resume' may restart a previously completed process because of a different order in the list.

I am not sure groupTuple is the only possible culprit. It is just the one I encounter during a test.

## Suggest implementation 

As current implementation doesn't guarantee any order, the modified behaviour should not break any existing implementation.

**Comment by pditommaso** [comment]
NF caching is not affected by the order of the groupTuple items
