### ISSUE TITLE
Use a file in publishDir or have a long running process create it

### ISSUE THREAD

**Issue by lucidv01d** [nextflow-io/nextflow#201]
I have a long running process that creates a file and copies it to a **publishDir**. Two downstream processes require this file. I'd like to be able to skip the long running process if the file exists in the publishDir, and otherwise call the long running process and then the two downstream. It would look something like this:
```
                          B ---  
                         /
(File does not exist)   A  (file saved to publishDir)
                         \ 
                          C --- 

(File exists)             B ---  (use file in publishDir)
                          C ---  (use file in publishDir)
```
I've been trying **watchPath** and ```[-f file ] && TRUE || FALSE``` like tests in the process command, but nothing seems to work. The ```-resume``` cache flag also fails, presumably since the **publishDir** copy happens after the file is created in the long running process's work directory, which may or may not still exist. Any suggestions?

**Comment by lucidv01d** [comment]
One potential but not very elegant solution:

```
process longRunningProcess {
    memory '16 GB'
    publishDir "${params.output}/", mode:'copy'

    input: 
    file raw from raw_data

    output:
    file 'processed_data' into downstreamA
    file 'processed_data' into downstreamB

    shell:
    '''
    if [ -f !{params.output}/processed_data ]; then
        mv !{params.output}/processed_data .
    else
        python $CODE_DIR/process_raw.py \
        -i "!{raw}" \
        -o processed_data
    fi
    '''
}
```

**Comment by pditommaso** [comment]
Directive [storeDir](http://www.nextflow.io/docs/latest/process.html#storedir) is meant for that.

**Comment by pditommaso** [comment]
I'm closing this because there's no feedback. Feel free to continue the discussion if you need.
