### ISSUE TITLE
Cannot parse  "\a" in script 

### ISSUE THREAD

**Issue by kantale** [nextflow-io/nextflow#2017]
## Bug report 

When a script contains the following text:

```text
    """
    \a
    """
```

or the following text:
```text
    '''
    \a
    '''
```

Then the nextflow script cannot be parsed. 

### Expected behavior and actual behavior

If I create a bash script (i.e ```my_script.sh```) with the following content:
```bash
\a
```

And then run:
```bash
bash my_script.sh
```
Then the output is:
```text
test.sh: line 2: \a: command not found
```

Therefore when running the following nextflow script:
```
process PR {

    """
    \a
    """
}
```

With the command:
```
nextflow run workflow.nf
```

I would expect to get the typical nextflow error:
```text
N E X T F L O W  ~  version 20.10.0
Launching `workflow.nf` [curious_jennings] - revision: 91cdcbccd3
executor >  local (1)
[12/d6cd31] process > PR [100%] 1 of 1, failed: 1 ✘
Error executing process > 'PR'

Caused by:
  Process `PR` terminated with an error exit status (127)

Command executed:

  a

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: a: command not found

Work dir:
  /Users/admin/tools/nextflow/work/12/d6cd315e1c9900a986e23777a646cb

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

```

Instead I get the following error:
```
N E X T F L O W  ~  version 20.10.0
Launching `workflow.nf` [goofy_shirley] - revision: f150c1179a
Script compilation error
- file : /Users/admin/tools/nextflow/workflow.nf
- cause: Unexpected input: '{' @ line 5, column 12.
   process PR {
              ^

1 error
```

### Steps to reproduce the problem

Just create a nextflow script with the following content:
```
process PR {

    """
    \a
    """
}
```

Save it in ```workflow.nf``` and run:
```bash
nextflow run workflow.nf
```

### Program output 
```
N E X T F L O W  ~  version 20.10.0
Launching `workflow.nf` [goofy_shirley] - revision: f150c1179a
Script compilation error
- file : /Users/admin/tools/nextflow/workflow.nf
- cause: Unexpected input: '{' @ line 5, column 12.
   process PR {
              ^

1 error
```

### Environment 

* Nextflow version: 20.10.0 
* Java version: java version "11.0.10" 2021-01-19 LTS
* Operating system: macOS
* Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

### Additional context

(Add any other context about the problem here)

**Comment by kantale** [comment]
Just to add why this is important: [I cannot escape alias](https://unix.stackexchange.com/questions/39291/run-a-command-that-is-shadowed-by-an-alias) in a bash script. The following script will also fail:

```
process PR {

    '''
    \ls
    '''
}
```

**Comment by pditommaso** [comment]
`\a` is not a valid escape character like eg `\t` or '\n`, therefore it breaks the parser.
