### ISSUE TITLE
"Invalid method invocation `call` with arguments: 7 (java.lang.Integer) on _runScript_closure1 type" encountered in groupTuple

### ISSUE THREAD

**Issue by GDCCP** [nextflow-io/nextflow#2020]
## Bug report 

I am using nextflow console to test this script:

```
def order = [ "bart", "maggie", "lisa", "homer", "marge" ]
def mysort = { a,b -> return order.indexOf(a[0]) <=> order.indexOf(b[0]) }

println mysort(["homer",4],["maggie",12])
println mysort(["bart",[3,4]],["marge",["xyz",12]])    

def ch = Channel.from(["homer", 5], ["maggie", 2], ["lisa", 10], ["lisa", 3], ["maggie", 7])

ch.groupTuple(sort: mysort).view()

```

### Expected behavior and actual behavior

The last groupTuple gives me the error in title.

### Steps to reproduce the problem

Paste the script in the nextflow console and then hit 'Crtl-r'

### Program output 

1
-1
[homer, [5]]
Invalid method invocation `call` with arguments: 7 (java.lang.Integer) on _runScript_closure1 type

### Environment 

* Nextflow version: 20.07.1
* Java version: 1.8.0
* Operating system: centos 7
* Bash version: 4.2.46

**Comment by pditommaso** [comment]
It could work casting the closure to a comparable eg

```
def mysort = { a,b -> return order.indexOf(a[0]) <=> order.indexOf(b[0]) } as Comparable
```

However, the sort closure is still malformed because it will receive the tuple values ie `2,3,5,7` not the tuple keys.
