### ISSUE TITLE
Unknown method invocation `isEmpty` on Boolean type

### ISSUE THREAD

**Issue by gongyh** [nextflow-io/nextflow#2022]
## Bug report 

"Unknown method invocation `isEmpty` on Boolean type" after version 20.12.0-edge

### Program output 

Apr-08 21:55:14.412 [main] DEBUG nextflow.Session - Work-dir: /mnt/data4/gongyh/github/test/work [xfs]
Apr-08 21:55:14.679 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[GoogleLifeSciencesExecutor, AwsBatchExecutor]
Apr-08 21:55:14.698 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Apr-08 21:55:14.788 [main] ERROR nextflow.cli.Launcher - @unknown
org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: java.lang.Boolean.isEmpty() is applicable for argument types: () values: []
Possible solutions: identity(groovy.lang.Closure), dump(), inspect()

### Environment 

* Nextflow version: [>=20.12.0-edge] 
* Java version: [1.8]
* Operating system: [Linux]
* Bash version: (use the command `$SHELL --version`)

### Additional context

I found that from v20.12.0-edge changed from "nextflow.preview.dsl = 2" to "nextflow.enable.dsl = 2".

**Comment by pditommaso** [comment]
There's no information to replicate the problem
