### ISSUE TITLE
Boolean params are not parsed correctly

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2023]
### Expected behavior and actual behavior

Boolean params (true and false) provided via params file should be parsed as booleans, but they are not. The problem arises particularly when a param is set to true in nextflow.config but set to false via params file.

### Steps to reproduce the problem

nextflow.config:
```
params {
    input_enabled = true

    input {
        enabled = true
    }
}
```

main.nf:
```
process test {
    echo true

    script:
    """
    echo ${params.input_enabled}
    echo ${params.input.enabled}
    """
}
```

params.yaml:
```
input_enabled: false
input.enabled: false
```

params.json:
```
{ "input_enabled": false, "input.enabled": false }
```

### Program output 

All of the following tests should print "false" and "false".

params.yaml:
```
$ nextflow run main.nf -params-file params.yaml
N E X T F L O W  ~  version 21.03.0-edge
Launching `main.nf` [distracted_volta] - revision: a96ae131be
executor >  local (1)
[d3/043cd6] process > test [100%] 1 of 1 ✔
false
true
```

params.json:
```
$ nextflow run main.nf -params-file params.json
N E X T F L O W  ~  version 21.03.0-edge
Launching `main.nf` [magical_shannon] - revision: a96ae131be
executor >  local (1)
[b7/7a5069] process > test [100%] 1 of 1 ✔
false
true
```

CLI arguments:
```
$ nextflow run main.nf --input_enabled=false --input.enabled=false
N E X T F L O W  ~  version 21.03.0-edge
Launching `main.nf` [distraught_heisenberg] - revision: a96ae131be
executor >  local (1)
[83/c0a11e] process > test [100%] 1 of 1 ✔
false
false
```

### Environment 

* Nextflow version: 21.03.0-edge
* Java version: 1.8
* Operating system: Linux
* Bash version: 4.4.19

### Additional context

I'm not really concerned about whether the CLI arguments are parsed correctly because the syntax is ambiguous. However, YAML and JSON both have explicit syntax for booleans so they should be able to be parsed correctly.

EDIT: fixed an error I made in the CLI case, it actually does work as intended

**Comment by bentsherman** [comment]
Additionally, it looks like scoped params aren't applied at all when provided through a params file. If I set both params to false in nextflow.config and true in params.yaml, I get the following:
```
$ nextflow run main.nf -params-file params.yaml
N E X T F L O W  ~  version 21.03.0-edge
Launching `main.nf` [astonishing_wescoff] - revision: a96ae131be
executor >  local (1)
[b4/4ccf17] process > test [100%] 1 of 1 ✔
true
false
```

So `input_enabled` is applied but `input.enabled` is not. Same outcome with params.json. Maybe this should be in a separate issue but I figure I'd mention it here.

**Comment by mjhipp** [comment]
Your CLI input has a typo ("input" -> "params"), that part seems to be working fine:

```
❯ NXF_VER="21.03.0-edge" ./nextflow run main.nf --input_enabled=false --input.enabled=false
N E X T F L O W  ~  version 21.03.0-edge
Launching `main.nf` [nostalgic_watson] - revision: a47d827415
executor >  local (1)
[0f/c313f0] process > test [100%] 1 of 1 ✔
false
false
```

Overriding with a groovy config file works:

```
❯ NXF_VER="21.03.0-edge" ./nextflow run main.nf -c params.config
N E X T F L O W  ~  version 21.03.0-edge
Launching `main.nf` [loving_nobel] - revision: a47d827415
executor >  local (1)
[5e/cb49e9] process > test [100%] 1 of 1 ✔
false
false
```

But I also see your same issue when running the json/yaml files on `21.04.1-edge`:

```
❯ NXF_VER="21.04.1-edge" ./nextflow run main.nf -params-file params.json
CAPSULE: Downloading dependency io.nextflow:nextflow:jar:21.04.1-edge
CAPSULE: Downloading dependency io.nextflow:nf-httpfs:jar:21.04.1-edge
CAPSULE: Downloading dependency io.nextflow:nf-commons:jar:21.04.1-edge
N E X T F L O W  ~  version 21.04.1-edge
Launching `main.nf` [astonishing_legentil] - revision: a47d827415
executor >  local (1)
[ad/3ef91c] process > test [100%] 1 of 1 ✔
false
true


❯ NXF_VER="21.04.1-edge" ./nextflow run main.nf -params-file params.yaml
N E X T F L O W  ~  version 21.04.1-edge
Launching `main.nf` [deadly_marconi] - revision: a47d827415
executor >  local (1)
[c7/2134c2] process > test [100%] 1 of 1 ✔
false
true
```

However, it looks like your params files have improper structure for a nested variable. If I change them to:


params-v2.json:
```
{ "input_enabled": false, "input": { "enabled": false } }
```

params-v2.yaml
```
input_enabled: false
input:
  enabled: false
```

I get the expected results with `21.03.0-edge`:

```
❯ NXF_VER="21.03.0-edge" ./nextflow run main.nf -params-file params-v2.json
N E X T F L O W  ~  version 21.03.0-edge
Launching `main.nf` [cranky_mcclintock] - revision: a47d827415
executor >  local (1)
[55/508c4b] process > test [100%] 1 of 1 ✔
false
false


❯ NXF_VER="21.03.0-edge" ./nextflow run main.nf -params-file params-v2.yaml
N E X T F L O W  ~  version 21.03.0-edge
Launching `main.nf` [crazy_bhaskara] - revision: a47d827415
executor >  local (1)
[3a/3e1189] process > test [100%] 1 of 1 ✔
false
false
```

However the json fails with `21.04.1-edge` (#2109):

```
❯ NXF_VER="21.04.1-edge" ./nextflow run main.nf -params-file params-v2.json
N E X T F L O W  ~  version 21.04.1-edge
Launching `main.nf` [ridiculous_hopper] - revision: a47d827415
WARN: Configuration setting type with key 'input_enabled.input' does not match the parameter with the same key - Config value=[enabled:true]; parameter value=null
[-        ] process > test -
Error executing process > 'test'

Caused by:
  Cannot get property 'enabled' on null object

Source block:
  """
      echo ${params.input_enabled}
      echo ${params.input.enabled}
      """

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

**Comment by mjhipp** [comment]
Json works with the newest version on `main`:

```
❯ ~/git-repos/nextflow/launch.sh run  main.nf -params-file params-v2.json
N E X T F L O W  ~  version 21.05.0-edge
Launching `main.nf` [thirsty_lovelace] - revision: a47d827415
executor >  local (1)
[bc/1a4e1d] process > test [100%] 1 of 1 ✔
false
false
```

**Comment by bentsherman** [comment]
@mjhipp Thank you for catching the simple mistake with the CLI arguments.

Your solution brings up the question of whether the dot syntax used for CLI params should also be understood when used in a params file, even though it would be extraneous. I don't think anyone would ever try to make a param with a dot in its name anyway, but still it could be confusing. Allowing the dot syntax in params file would be great for my current use case but now I'm not sure if I want to push for it.

I will leave this issue open for now in case anyone else has takes on this question...

**Comment by mjhipp** [comment]
See bottom of the page here https://github.com/nextflow-io/nextflow/blob/master/docs/getstarted.rst#pipeline-parameters
