### ISSUE TITLE
Job will be shut down when running multiple subjects using nextflow

### ISSUE THREAD

**Issue by qtalwaysrun** [nextflow-io/nextflow#2024]
Hello,
I am processing data on HPC using the “connectoflow pipeline” developed by Sherbrook Imaging Lab ( https://github.com/scilus/connectoflow） ). To launch this pipeline, I also need Nextflow. I am using Nextflow/19.01.0, java/1.8.0_121, and StdEnv/2018.3 on ComputeCanada.
 
I tested the pipepline, it can work well with processing only 1 subjects; but if I want to process more subjects , the job will always be shut down after finishing the first 4 tasks (considering that the pipepline has to complete 8 tasks in total.) **The weird thing is : when I checked the .nexflow.log or slurm.out files, there were not any errors!**

I am guessing maybe I need to configure the Nextflow server (in the link above they have put nextflow.config, maybe need to change something)? But I am not an expert on Nextflow, could you tell me how to fix it? Thank you in advance!

All the best,
Ting

**Comment by qtalwaysrun** [comment]
I put the nextflow.config here:

process {
    tag = {"$sid"}
    publishDir = {"./results_conn/$sid/$task.process"}
    scratch = true
    stageInMode = 'copy'
    stageOutMode = 'rsync'
}

params {
    help=false
    root=false
    template=false
    labels_list=false
    labels_img_prefix=''
    output_dir="./results_conn/"

    apply_t1_labels_transfo=true

    // **COMMIT options**//
        run_commit=true
        b_thr=50
        nbr_dir=500
        ball_stick=false
        para_diff="1.7E-3"
        perp_diff="0.85E-3 0.51E-3"
        iso_diff="1.7E-3 3.0E-3"

    // **Decompose options**//
        no_pruning=false
        no_remove_loops=false
        no_remove_outliers=false
        min_length=20
        max_length=200
        loop_max_angle=330
        outlier_threshold=0.5

    // **AFD & RD options**//
        run_afd_rd=true
        length_weighting=false
        sh_basis="descoteaux07"

    use_similarity_metric=true
    nbr_subjects_for_avg_connections=50

    // **Number of processes per tasks**//
        processes_register=4
        processes_commit=8
        processes_afd_rd=4
        processes_avg_similarity=8
        processes_connectivity=4
        params.decompose_memory_limit='6 GB'
        params.commit_memory_limit='3 GB'
}

process.publishDir = {"$params.output_dir/$sid/$task.process"}
params.kernel_output_dir = "${params.output_dir}/Compute_Kernel"
params.avg_conn_output_dir = "${params.output_dir}/Average_Connections"

singularity.autoMounts = true

profiles {
    large_dataset {
        params.decompose_memory_limit='12 GB'
    }

    fully_reproducible {
        params.processes_register=1
    }

    macos {
            process.scratch="/tmp"
    }
}

**Comment by pditommaso** [comment]
Sorry, this is not a replicable issue.
