### ISSUE TITLE
Variable `2.d` parsed as double, not day

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#2039]
### Expected behavior and actual behavior

I would expect `2.d` to be parsed as `nextflow.util.Duration` but instead it is parsed as `Double`.

### Steps to reproduce the problem

```nextflow
def  x = 2.d 
assert x instanceof nextflow.util.Duration
```

### Additional context

Likely down to this code:

https://github.com/nextflow-io/nextflow/blob/ac526f388bb824cd6ba89aac041e7b78f6561379/modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy#L471

Issue created on request from @pditommaso after discussion in @nf-core slack: https://nfcore.slack.com/archives/CUC8PPDL2/p1618386518223800?thread_ts=1618386377.220400&cid=CUC8PPDL2

**Comment by pditommaso** [comment]
I think should even parse `20d` as double. @ewels sounds good 4de4670c?

**Comment by ewels** [comment]
Added some comments to the commit, but approach looks good 👍🏻
