### ISSUE TITLE
Consider migrating docs from rst to mkdocs

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#2041]
The markdown format is more is easier to read and the [Material for Mkdocs](https://squidfunk.github.io/mkdocs-material/) projects provide several non-intrusive extension for collapsible, tabs, callouts that make the result documentation much more readable. 

To migrate rst format to markdown the following tools may help

* https://github.com/retext-project/retext
* https://cloudconvert.com/rst-to-md
* https://typora.io/

**Comment by abhi18av** [comment]
About this one, please do let me know if there's a timeline for this - I'd be happy to take this up accordingly.

**Comment by pditommaso** [comment]
Thinking more, current docs just works. We may think to have a new shiny CSS layout.

**Comment by abhi18av** [comment]
Ah, okay. Cool, this makes sense 👍 

The search experience hasn't failed so far for anything I've wanted to look in the NF docs :) 

The only feedback I have is that, perhaps we should provide a visual marker (button/note) for the version, `latest` / `edge`.

**Comment by pditommaso** [comment]
Rewriting the docs would require to much work and introduce errors. Better to look for a nicer HTML them for the current Sphynx generated docs
