### ISSUE TITLE
JRE dies with insufficient memory when recovering a large job amount from caches

### ISSUE THREAD

**Issue by fkaiserbio** [nextflow-io/nextflow#2045]
## Bug report 

We have a rather complex pipeline that runs on local executor without any problems upon the first run. However, on subsequent runs and the use of caches, the JVM dies with an OOME.

```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 2097152 bytes for AllocateHeap
# An error report file with more information is saved as:
# [...]
```

Nextflow executes properly up to this point and dies spontaneously, after a large proportion of the cacheable jobs was already recovered:

```
...
[66/0e216b] process > p1 (166881)       [100%] 166881 of 166881, cached: 166881 ✔
[ba/29cdec] process > p2 (166881)       [100%] 166881 of 166881, cached: 166858  ✔
[5a/1d6b54] process > p3 (9168)         [100%] 9168 of 9168, cached: 9168 ✔
[b2/92040e] process > p4 (9137)         [100%] 9137 of 9137, cached: 9137 ✔
[92/7c43e0] process > p5 (9134)         [100%] 9137 of 9137, cached: 9137 ✔
[4a/a54e36] process > p6 (218711)       [100%] 218712 of 218712, cached: 218712 ✔
...
```

This might be related to #1546 and #1620.

### Expected behavior and actual behavior

Nextflow should restore caches and the calculation of the workflow should terminate normally.

### Steps to reproduce the problem

Run a large pipeline with the `-resume` option.

### Program output 

- `.nextflow.log` does not show any errors

### Environment 

* Nextflow version: `nextflow version 20.10.0.5430`
* Java version: `openjdk 14.0.2 2020-07-14`
* Operating system: `Linux`
* Bash version: `version 5.0.17(1)-release`

### Additional context

- the machine the workflow runs on has 1 TB of RAM
-  `export NXF_OPTS="-Xms50g -Xmx100g"` is used and even more quota results in the same behavior
-  `submitRateLimit = '100 sec'` is used for local executor but does not seem to play a role when recovering from caches (maybe too many parallel jobs are launched in resume mode and thus memory is exceeded?)
-  Singularity containers are used for execution

Thanks for your help :smiley:

**Comment by fkaiserbio** [comment]
Okay, it seems that the issue is somehow related to the JVM version. Using `openjdk version "1.8.0_282"` does resolve the issue for me. Maybe still good to know and helpful for others.

**Comment by pditommaso** [comment]
There are huge improvements with ZGC and Shenandoah GC provided by recent JVM.

**Comment by fkaiserbio** [comment]
Unfortunately the issue is still there, also with OpenJava 1.8. I have tried to enable ZGC for OpenJDK 14 with `NXF_OPTS="-Xmx500g -XX:+UnlockExperimentalVMOptions -XX:+UseZGC` but then Nextflow fails to start at all:


```
./nextflow: line 175: exec: [0.018s][warning][gc]: not found
```

Could you please have a look what is going on here? Is would be great to benefit from proper caching also for large jobs.

**Comment by pditommaso** [comment]
Try using `_JAVA_OPTIONS` instead

**Comment by fkaiserbio** [comment]
Thanks for the comment, but sadly it does not help and results with the same error for Oracle JDK14 and 15 and their respective OpenJDK variants:

```
$ export NXF_OPTS="-Xmx700g"
$ export NXF_DEBUG="0"
$ export _JAVA_OPTIONS="-XX:+UseZGC"
$ ./nextflow 
./nextflow: line 175: exec: [0.020s][warning][gc]: not found
```

**Comment by pditommaso** [comment]
I mean using `_JAVA_OPTIONS` in place of all options in place of `NXF_OPTS`

**Comment by fkaiserbio** [comment]
Sorry, I should have mentioned this, it will not work this way either.

```
$ unset NXF_OPTS
$ export _JAVA_OPTIONS="-Xmx700G -XX:+UseZGC"
$ ./nextflow 
./nextflow: line 175: exec: [0.020s][warning][gc]: not found
```

**Comment by pditommaso** [comment]
```
» export _JAVA_OPTIONS="-Xmx700G -XX:+UseZGC"
» nextflow run nextflow-io/hello
Picked up _JAVA_OPTIONS: -Xmx700G -XX:+UseZGC
N E X T F L O W  ~  version 20.10.0
Launching `nextflow-io/hello` [nostalgic_dalembert] - revision: e6d9427e5b [master]
executor >  local (4)
[e3/52a253] process > sayHello (4) [100%] 4 of 4 ✔
Bonjour world!
Ciao world!
Hello world!
Hola world!

» java --version
Picked up _JAVA_OPTIONS: -Xmx700G -XX:+UseZGC
java 15 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

```

**Comment by fkaiserbio** [comment]
Thanks, for your prompt answer! :smiley:  It does work indeed when running a pipeline, but calling a plain `$ ./nextflow` or `$ ./nextflow log` does not return any output, which is weird. Additionally, the JVM recommends to adjust the memory map size depending on the selected heap size:

```
[0.026s][warning][gc] ***** WARNING! INCORRECT SYSTEM CONFIGURATION DETECTED! *****
[0.026s][warning][gc] The system limit on number of memory mappings per process might be too low for the given
[0.026s][warning][gc] max Java heap size (716800M). Please adjust /proc/sys/vm/max_map_count to allow for at
[0.026s][warning][gc] least 1290240 mappings (current limit is 65530). Continuing execution with the current
[0.026s][warning][gc] limit could lead to a premature OutOfMemoryError being thrown, due to failure to map memory.
```

`$ echo "1290240" > /proc/sys/vm/max_map_count`

I will let you know whether this helped to remedy the issue.

**Comment by fkaiserbio** [comment]
Everything runs as expected now. Thanks for your help!
