### ISSUE TITLE
`Missing process or function with name 'collectFile'` when using `newLine=true` in DSL 2

### ISSUE THREAD

**Issue by multimeric** [nextflow-io/nextflow#2049]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

`collectFile(newLine=true)` should work identically as described in the DSL 1 operator docs: https://www.nextflow.io/docs/latest/operator.html?highlight=view#collectfile.

### Steps to reproduce the problem

Here is the simplest reproduction I have managed:

```groovy
nextflow.enable.dsl=2

process reverse {
    input:
        val str
    output:
        stdout()
    script:
        """
        echo ${str} | rev
        """
}

workflow {
    inputs = Channel.from("ab", "bc", "cd")
    // Reverse each string in parallel
    reverse(inputs)
    //Merge the files
    merged = reverse.out.collectFile(name: "combined.txt", newLine=true)
    merged.view()
}
```

### Program output 
```
N E X T F L O W  ~  version 20.10.0
Launching `collectFile.nf` [trusting_blackwell] - revision: c0d5dc87f4
[-        ] process > reverse -
Missing process or function with name 'collectFile'

 -- Check script 'collectFile.nf' at line: 19 or see '.nextflow.log' file for more details
```
### Environment 

* Nextflow version: 20.10.0 build 5430
* Java version: openjdk 10.0.2 2018-07-17
* Operating system: Ubuntu 18.04
* Bash version: fish, version 3.2.2

### Additional context
Note that, as soon as you remove the `newLine=true` parameter, this works perfectly, and prints out the filepath to the merged file:

```
N E X T F L O W  ~  version 20.10.0
Launching `collectFile.nf` [jovial_yonath] - revision: 79c232fe3b
executor >  local (3)
[7b/cb5682] process > reverse (2) [100%] 3 of 3 ✔
/home/michael/Programming/CollectFiles/work/tmp/a9/e9b20c3c6231929c30a6b0d5bd6421/combined.txt
```
```

**Comment by pditommaso** [comment]
`newLine=true` is an invalid syntax. it's expected to be `newLine: true`

**Comment by multimeric** [comment]
Yep that's all it was! I mistakenly used Python syntax and totally misunderstood the error.
