### ISSUE TITLE
Glob dots notation is not supported

### ISSUE THREAD

**Issue by hmkim** [nextflow-io/nextflow#205]
> Case 1
> reads = 'SRR*.fastq'
> 
> Case 2
> reads = 'SRR9508{76..83}.fastq'
> 

Case1 is ok .

but Case 2  is not work in nextflow.  (maybe for paired file function?)

I want to glob files (SRR950876, SRR950877,SRR950878,...,SRR950882,SRR950883).

**Comment by pditommaso** [comment]
Unfortunately glob dots notation is not supported by the underlying Java file system implementation. 

https://docs.oracle.com/javase/tutorial/essential/io/fileOps.html#glob

**Comment by pditommaso** [comment]
You will need to expand to a comma separated list such as `SRR9508{76,77,78,79,80,81,82,83}.fastq`

**Comment by hmkim** [comment]
Thanks for your reply.
