### ISSUE TITLE
 Pre-existing named pools with Azure 

### ISSUE THREAD

**Issue by manuelesimi** [nextflow-io/nextflow#2050]
## Bug report 

I'm trying to use pre-existing named pools with the Azure executor, but Nextflow does not seem able to properly interface with them. 

### Expected behavior and actual behavior

I've created a fixed named pool with 2 nodes. The nodes are (correctly) in the idle state, waiting for tasks to execute. I configured Nextflow to use the named pool as queue for all the (4) small processes of a dummy pipeline. The first job never gets executed. 

The error message is:
<pre>
Caused by:
  Process `sayHelloInItalian (1)` terminated for an unknown reason -- Likely it has been terminated by the external system
</pre>

### Steps to reproduce the problem
This is the pipeline I'm testing:

https://github.com/manuelesimi/hello-nextflow/tree/azurebatch

I simply run it with:

`nextflow -C nextflow.azure.config run main.nf`

Here's my nextflow.azure.config:
<pre>
docker {
    enabled = true
}

plugins {
  id 'nf-azure'
}

process {
  executor = 'azurebatch'
  container = 'quay.io/nextflow/bash'
  queue = 'TestNoDocker'
}

workDir = 'az://workdir/work'

azure {
  batch {
    location = 'eastus2'
    accountName = '..'
    accountKey = '...'

     pools {
        TestNoDocker   {
            vmType = 'Standard_D4_v3'
            vmCount = 4
        }
    }
  }
  storage {
    accountName = '...'
    accountKey = '...'
  }
}</pre>

_TestNoDocker_ is the name of the pool.

### Program output 

Here's my .nextflow.log related to the execution:

<pre>
Apr-19 17:20:04.714 [main] DEBUG nextflow.cli.Launcher - $> nextflow -C nextflow.azure.config.local run main-azure.nf
Apr-19 17:20:05.177 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 21.04.0-edge
Apr-19 17:20:05.316 [main] INFO  nextflow.cli.CmdRun - Launching `main-azure.nf` [serene_pauling] - revision: bf54e09e5d
Apr-19 17:20:05.353 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Users/manuelesimi/EIPM/hello-nextflow/nextflow.azure.config.local
Apr-19 17:20:05.398 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Apr-19 17:20:07.293 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/Users/manuelesimi/.nextflow/plugins
Apr-19 17:20:07.296 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins declared=[nf-azure]
Apr-19 17:20:07.311 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins local root: .nextflow/plr/ca1fa88cef8b8cdc82db5c5aa548afd7
Apr-19 17:20:07.343 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Apr-19 17:20:07.347 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Apr-19 17:20:07.354 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Apr-19 17:20:07.405 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-azure@0.9.7' resolved
Apr-19 17:20:08.324 [main] DEBUG nextflow.plugin.PluginUpdater - Starting plugin nf-azure version: latest
Apr-19 17:20:08.324 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-azure@0.9.7'
Apr-19 17:20:08.400 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-azure@0.9.7
Apr-19 17:20:08.484 [main] DEBUG nextflow.file.FileHelper - > Added 'AzFileSystemProvider' to list of installed providers [az]
Apr-19 17:20:08.638 [main] DEBUG nextflow.Session - Session uuid: 91cf9bfc-8533-4b0c-a4f6-d9f447144d90
Apr-19 17:20:08.638 [main] DEBUG nextflow.Session - Run name: serene_pauling
Apr-19 17:20:08.639 [main] DEBUG nextflow.Session - Executor pool size: 4
Apr-19 17:20:08.683 [main] DEBUG n.cloud.azure.file.AzPathFactory - Creating Azure path factory
Apr-19 17:20:08.748 [main] DEBUG n.cloud.azure.file.AzPathFactory - + Setting context class loader to=org.pf4j.PluginClassLoader@488b50ec - previous=sun.misc.Launcher$AppClassLoader@6bc7c054
Apr-19 17:20:08.749 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: AzFileSystemProvider
Apr-19 17:20:08.750 [main] DEBUG n.c.azure.nio.AzFileSystemProvider - Creating Azure blob storage client -- accountName=nffiles; accountKey=ZVhV4..
Apr-19 17:20:10.329 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 21.04.0-edge build 5543
  Created: 08-04-2021 09:25 UTC (05:25 EDT)
  System: Mac OS X 10.12.6
  Runtime: Groovy 3.0.7 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_131-b11
  Encoding: UTF-8 (UTF-8)
  Process: 32328@MAC162555 [192.168.1.10]
  CPUs: 4 - Mem: 16 GB (1.1 GB) - Swap: 3 GB (913 MB)
Apr-19 17:20:13.165 [main] DEBUG nextflow.Session - Work-dir: az://workdir/work [Mac OS X]
Apr-19 17:20:13.166 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /Users/manuelesimi/EIPM/hello-nextflow/bin
Apr-19 17:20:13.271 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[AzBatchExecutor]
Apr-19 17:20:13.302 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Apr-19 17:20:13.679 [main] DEBUG nextflow.Session - Session start invoked
Apr-19 17:20:14.525 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Apr-19 17:20:14.569 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: sayHelloInEnglish, sayHelloInFrench, sayHelloInSpanish, sayHelloInItalian
Apr-19 17:20:14.820 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: azurebatch
Apr-19 17:20:14.820 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'azurebatch'
Apr-19 17:20:14.824 [main] DEBUG nextflow.executor.Executor - [warm up] executor > azurebatch
Apr-19 17:20:14.844 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'azurebatch' > capacity: 1000; pollInterval: 10s; dumpInterval: 5m 
Apr-19 17:20:15.115 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: azurebatch
Apr-19 17:20:15.117 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'azurebatch'
Apr-19 17:20:15.129 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: azurebatch
Apr-19 17:20:15.129 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'azurebatch'
Apr-19 17:20:15.149 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: azurebatch
Apr-19 17:20:15.149 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'azurebatch'
Apr-19 17:20:15.170 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Apr-19 17:20:15.170 [main] DEBUG nextflow.Session - Session await
Apr-19 17:20:15.318 [Actor Thread 3] DEBUG n.util.BlockingThreadExecutorFactory - Thread pool name=FileTransfer; maxThreads=12; maxQueueSize=36; keepAlive=1m
Apr-19 17:20:15.519 [FileTransfer-thread-1] DEBUG nextflow.file.FilePorter - Local cache found for foreign file /Users/manuelesimi/EIPM/hello-nextflow/Welcome.txt at az://workdir/work/stage/aa/aadf835ca6632acce536fa6bb64619/Welcome.txt
Apr-19 17:20:16.011 [Task submitter] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Submitting task sayHelloInItalian (1) - work-dir=az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae
Apr-19 17:20:16.287 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - [AZURE BATCH] Checking VM pool id=TestNoDocker; size=AzVmType(name:Standard_D4_v3, maxDataDiskCount:8, memory:16 GB, numberOfCores:4, osDiskSize:1023 GB, resourceDiskSize:100 GB)
Apr-19 17:20:16.287 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - [AZURE BATCH] Executor options=endpoint=null; account-name=cluster; account-key=BoCQe...
Apr-19 17:20:18.940 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - [AZURE BATCH] Submitting task: nf-0adb2739ab57f8f46bec8975c5fdc3ae, cpus=1, mem=-, slots: 1
Apr-19 17:20:18.944 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - Task output path: .exitcode -> az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae
Apr-19 17:20:18.945 [Task submitter] DEBUG n.cloud.azure.batch.AzBatchService - Task output path: .command.log -> az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae
Apr-19 17:20:19.045 [Task submitter] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Submitted task sayHelloInItalian (1) with taskId=nextflow.cloud.azure.batch.AzTaskKey(job-aee0241bcafed6794a34-sayHelloInItalian, nf-0adb2739ab57f8f46bec8975c5fdc3ae)
Apr-19 17:20:19.047 [Task submitter] INFO  nextflow.Session - [0a/db2739] Submitted process > sayHelloInItalian (1)
Apr-19 17:20:24.954 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task: nextflow.cloud.azure.batch.AzTaskKey(job-aee0241bcafed6794a34-sayHelloInItalian, nf-0adb2739ab57f8f46bec8975c5fdc3ae) state=completed
Apr-19 17:20:24.955 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Task status sayHelloInItalian (1) taskId=nextflow.cloud.azure.batch.AzTaskKey(job-aee0241bcafed6794a34-sayHelloInItalian, nf-0adb2739ab57f8f46bec8975c5fdc3ae); running=true
Apr-19 17:20:24.996 [Task monitor] DEBUG n.c.azure.batch.AzBatchTaskHandler - [AZURE BATCH] Cannot read exitstatus for task: `sayHelloInItalian (1)` | az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae/.exitcode
Apr-19 17:20:24.998 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: sayHelloInItalian (1); status: COMPLETED; exit: -; error: -; workDir: az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae]
Apr-19 17:20:25.056 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae/.command.out
Apr-19 17:20:25.091 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae/.command.err
Apr-19 17:20:25.129 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae/.command.log
Apr-19 17:20:25.131 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'sayHelloInItalian (1)'

Caused by:
  Process `sayHelloInItalian (1)` terminated for an unknown reason -- Likely it has been terminated by the external system

Command executed [/Users/manuelesimi/EIPM/hello-nextflow/templates/hello.sh]:

  #!/usr/bin/env bash
  hello=Ciao
  output=italian.txt
  previous_file=Welcome.txt
  cat ${previous_file} > $output
  echo "${hello} world!" >> $output

Command exit status:
  -

Command output:
  (empty)

Work dir:
  az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Apr-19 17:20:25.159 [main] DEBUG nextflow.Session - Session await > all process finished
Apr-19 17:20:25.192 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `sayHelloInItalian (1)` terminated for an unknown reason -- Likely it has been terminated by the external system
Apr-19 17:20:25.277 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae/.command.err
Apr-19 17:20:25.313 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae/.command.out
Apr-19 17:20:25.317 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-19 17:20:25.351 [main] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae/.command.err
Apr-19 17:20:25.390 [main] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: az://workdir/work/0a/db2739ab57f8f46bec8975c5fdc3ae/.command.out
Apr-19 17:20:25.400 [main] INFO  nextflow.Nextflow - Nextflow says: DONE
Apr-19 17:20:25.416 [main] DEBUG n.cloud.azure.batch.AzBatchService - Preserving Azure job with error: job-aee0241bcafed6794a34-sayHelloInItalian
Apr-19 17:20:25.420 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=41ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Apr-19 17:20:25.436 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Apr-19 17:20:25.436 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-azure@0.9.7'
Apr-19 17:20:25.436 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-azure
Apr-19 17:20:25.467 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
</pre>

### Environment 

* Nextflow version: 21.04.0-edge build 5543
* Java version: Java HotSpot(TM) 64-Bit Server VM 1.8.0_131-b11
* Operating system: Mac OS X 10.12.6
* Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

### Additional context

Do note that the same pipeline works on the same batch account when autopooling is enabled.

**Comment by manuelesimi** [comment]
I made some progress in my own on this issue.

I did the following test: I let Nextflow create a pool and keep it alive after the pipeline execution. Then, I used it to submit the next pipeline executions and they all worked. So, pre-existing named pools are indeed supported. 

To understand what was going on, I compared the pool created by Nextflow with the others I was creating "manually". I found several differences that shed tons of light on the issue I was experiencing. There is likely some missing information in the Azure's Nextflow doc page that would help users to properly configure pools without letting Nextflow create them.

I'll run more tests tomorrow to confirm my understanding of the issue and how to work around it.

**Comment by abhi18av** [comment]
Hi @manuelesimi , thanks for highlighting this to us. We're looking forward to your results and would be happy to update the docs accordingly.

**Comment by manuelesimi** [comment]
So, my tests confirmed some missing information in the doc. Mainly: 
* the azcopy command must be available on every and each node of the pool
* the pool must be docker compatible 
* slots and VM cores must match
* the doc wrongly mentions the name of the pool, instead of its ID

In this PR I've added and amended the Azure doc page accordingly:
https://github.com/nextflow-io/nextflow/pull/2056

**Comment by abhi18av** [comment]
I think that this issue was addressed by https://github.com/nextflow-io/nextflow/pull/2056 already, perhaps we can close this one already?

**Comment by manuelesimi** [comment]
@abhi18av Thanks for your reminder.
Indeed, I forgot to close this.
