### ISSUE TITLE
mem_per_cpu directive for SLURM executor

### ISSUE THREAD

**Issue by huguesfontenelle** [nextflow-io/nextflow#2054]
## New feature

The HPC that I am using has a SLURM workload manager that does not support Nextflow's memory directive.
Instead, memory per CPU must be specified in its sbatch file:
```
#SBATCH --mem-per-cpu=2000M
```
As a workaround, I simply use clusterOptions in my process config:
```
clusterOptions = '--account=hugues --mem-per-cpu=2000M'
```
But then that memory per cpu is used for all processes.
I could copy it out of the global config, and write it in each each process, but then I must repeat the account name.

## Usage scenario 

For such SLURM systems, instead of using
```
cpus =  2
time = 2.h
```
together with `clusterOptions = '--account=hugues --mem-per-cpu=2000M'`
I would have
```
mem_per_cpu = 2.GB
cpus =  2
time = 2.h
```

FYI, documentation for my HPC: https://www.uio.no/english/services/it/research/sensitive-data/use-tsd/hpc/job-scripts.html

**Comment by huguesfontenelle** [comment]
bump

**Comment by bentsherman** [comment]
Potential solution would be to add an executor config option e.g. `memPerCpu` (similar to the LSF-specific options) that controls whether the slurm executor uses `mem` or `mem-per-cpu` for the `memory` directive. PRs are welcome.

**Comment by bentsherman** [comment]
Feel free to submit a PR with your contributions 😄 

And yes, I would also like to see a unit test and documentation of the option. You also need to fetch the option from the executor config, see `perJobMemLimit` in the LSF executor:

```groovy
        perJobMemLimit = session.getExecConfigProp(name, 'perJobMemLimit', perJobMemLimit)
```

**Comment by vmkalbskopf** [comment]
Is there any movement on this?
