### ISSUE TITLE
Can't install with openjdk 16

### ISSUE THREAD

**Issue by gailrosen** [nextflow-io/nextflow#2057]
## Bug report 

[gggg@node046 ~]$ java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment 21.3 (build 16+36)
OpenJDK 64-Bit Server VM 21.3 (build 16+36, mixed mode, sharing)
[gggg@node046 ~]$ curl -fsSL get.nextflow.io | bash
ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 or later is installed
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /usr/bin/java
 JAVA_HOME: 

[gggg@node046 ~]$ which java
/usr/bin/java

### Expected behavior and actual behavior

I have Java 16 installed, but it says I don't have 8 or later installed -- why?

**Comment by pditommaso** [comment]
Hi, sorry. JDK 16 was released a few days ago and not yet supported. Try using any Jvm up to 15 (included)

**Comment by gailrosen** [comment]
i doubt my sysadmin wants me using older java.  should i just try to compile from github?

**Comment by abhi18av** [comment]
The instructions for the adventurous souls are mentioned here  https://github.com/nextflow-io/nextflow#build-from-source-1

**Comment by pditommaso** [comment]
it's not needed to build it. It's enough to edit the `nextflow` launcher script.

**Comment by pditommaso** [comment]
Support for Java 16 has been added caace1c5.
