### ISSUE TITLE
AWS batch executor fails to start when using self-contained distribution

### ISSUE THREAD

**Issue by lpantano** [nextflow-io/nextflow#2058]
## Bug report 

I really tried to find information about this, but I didn't succeed. Thank you in advance!

I am getting the following error:

```
When using `awsbatch` executor a S3 bucket must be provided as working directory either using -bucket-dir or -work-dir command line option
```

After trying to run the dummy pipeline `hello` in AWS Batch:

```
nextflow run hello -c  test.config --tracedir './' -work-dir s3://axcella-rna-seq/nextflow/work
```
test.config looks like this:
```
process.executor = 'awsbatch'
process.queue = 'nextflow-default'
aws.region = 'us-east-1'
```

After version nextflow-21.01.1-edge-all (included) I get the error, but with previous versions it gets into the Batch cluster.

### Expected behavior and actual behavior

Get jobs into the AWS Batch

### Steps to reproduce the problem

I gave all the information above.

### Program output 

```
nextflow run hello -c  test.config --tracedir './' -work-dir s3://axcella-rna-seq/nextflow/work
N E X T F L O W  ~  version 21.01.1-edge
Launching `nextflow-io/hello` [high_hugle] - revision: e6d9427e5b [master]
When using `awsbatch` executor a S3 bucket must be provided as working directory either using -bucket-dir or -work-dir command line option
```

### Environment 

* Nextflow version: 21.04.0-edge
* Java version: openjdk version "1.8.0_282"
* Operating system: linux
* Bash version: `GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)`

### Additional context

(Add any other context about the problem here)

**Comment by lpantano** [comment]
Confirmed that this is only an issue with `*-all` releases binary file.

**Comment by pditommaso** [comment]
Thanks, i'll investigate asap

**Comment by pditommaso** [comment]
Thanks for reporting, this was a tricky one. Pushed a patch.

**Comment by pditommaso** [comment]
The above patch solves the problem. It'll be included in the next release. Thanks for reporting it.

**Comment by lpantano** [comment]
Thank you!
