### ISSUE TITLE
task.workDir is null

### ISSUE THREAD

**Issue by birnbera** [nextflow-io/nextflow#2059]
## Bug report 

`task.workDir` is `null` for all tasks.

### Expected behavior and actual behavior

I expected that `task.workDir` would be the directory in which the tasks inputs and outputs are staged. I thought the value of the variable should be something like `{workflow.workDir}/a1/abcdefghi1234567890...`.

In particular, it would be extremely useful if for AWS Batch this were the location in the specified S3 bucket where files for this process are staged, i.e. `task.workDir` would be something like `s3://bucket/prefix/a1/abcdefghi1234567890/`.

### Steps to reproduce the problem

```nextflow
process test {
    echo true

    script:
    """
    echo ${task.workDir}
    """
}
```

### Program output 

```console
N E X T F L O W  ~  version 20.10.0
Launching `test.nf` [sick_hodgkin] - revision: f8f171a35a
executor >  local (1)
[de/443564] process > test [100%] 1 of 1 ✔
null
```

### Environment 

* Nextflow version: 20.10.0 
* Java version: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
* Operating system: Centos 7
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by pditommaso** [comment]
This is exposed by a design choice to prevent tasks to relaying on absolute paths.

**Comment by stevekm** [comment]
I think this is causing `exec` to break randomly when writing out to a file and using `-resume`
