### ISSUE TITLE
AWS Client scope config parameters are not set in some situations

### ISSUE THREAD

**Issue by kytolav** [nextflow-io/nextflow#2071]
### Expected behavior and actual behavior

AWS Client scope allows the user to control the parameters of AWS SDK requests executed by Nextflow. Setting these parameters can be done in any configuration file, e.g.:
```
aws {
    client {
        uploadMaxThreads = 8
        uploadChunkSize = 32.MB
        uploadRetrySleep = 2.s
        maxConnections = 16
        connectionTimeout = 600
        maxErrorRetry = 100
        uploadMaxAttempts = 100
    }
}
```

However, the settings are not applied properly in certain cases where S3 FileHelper object is initialized too early. This causes significant problems with very large workflows since when the default SDK retries (apparently 3) run out, for example due to normal S3 throttling, the run fails immediately. This typically happens when resuming a large run where a large amount of `publishDir` related S3 operations are executed by Nextflow within a very short time.

### Steps to reproduce the problem

Consider the below workflow, configuration file and params file JSON.

*main.nf*
```
nextflow.enable.dsl=2

process cat_file {
    input:
        file input_file

    """
    cat ${input_file}
    """
}

workflow {
    cat_file(Channel.fromPath(params.files))
}
```

*nexflow.config*
```
aws {
    client {
        uploadMaxThreads = 8
        uploadChunkSize = 32.MB
        uploadRetrySleep = 2.s
        maxConnections = 16
        connectionTimeout = 600
        maxErrorRetry = 100
        uploadMaxAttempts = 100
    }
}
```

*input.json*
```
{
    "files": [
        "test.txt",
        "s3://fake_path/file.txt"
    ]
}
```

When executing the above workflow with `nextflow run -params-file input.json main.nf` the execution expectedly fails when the process tries to stage the S3 based input file (since it doesn't really exist). Still, in the `.nextflow.log` we can see that the AWS Client scope params are set correctly:
```
Apr-28 17:18:22.917 [PathVisitor-2] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=..., max_connections=16, upload_max_threads=8, max_error_retry=100, access_key=..., upload_chunk_size=33554432, upload_max_attempts=100, region=eu-west-1, connection_timeout=600, upload_retry_sleep=2000}
```

However, when changing also the input to come from S3, it seems as if the FileHelper object gets initialized too early and the client scope params are never applied: the command `nextflow run -params-file s3://input.json main.nf` results in log message:
```
Apr-28 17:20:05.923 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=..., region=eu-west-1, access_key=...}
```

### Program output 

Full log of the second command from previous section where Nextflow fails to set the parameters is:
```
Apr-28 17:20:04.637 [main] DEBUG nextflow.cli.Launcher - $> nextflow run -params-file 's3://input.json' main.nf
Apr-28 17:20:04.794 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.10.0
Apr-28 17:20:04.816 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [fervent_engelbart] - revision: 0d7da4e75d
Apr-28 17:20:04.888 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /Users/ville.kytolablueprintgenetics.com/projects/tmp/nextflow_bug_aws_client_scope/nextflow.config
Apr-28 17:20:04.889 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Users/ville.kytolablueprintgenetics.com/projects/tmp/nextflow_bug_aws_client_scope/nextflow.config
Apr-28 17:20:04.948 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Apr-28 17:20:05.904 [main] DEBUG nextflow.file.FileHelper - Creating a file system instance for provider: S3FileSystemProvider
Apr-28 17:20:05.912 [main] DEBUG nextflow.Global - Using AWS credentials defined by environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
Apr-28 17:20:05.923 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=..., region=eu-west-1, access_key=...}
```

### Environment 

* Nextflow version: 20.10.0
* Java version: openjdk version "11.0.10" 2021-01-19
* Operating system: Reproducible across systems [MacOS, Linux tested]
* Bash version: E.g. zsh 5.7.1

**Comment by blajoie** [comment]
Following - this looks to still be an issue in the latest version?
