### ISSUE TITLE
Support for assuming AWS IAM roles (without relying on instance profiles)

### ISSUE THREAD

**Issue by BrunoGrandePhD** [nextflow-io/nextflow#2073]
## New feature

As far as I can tell, Nextflow doesn't support AWS CLI profiles where an IAM user assumes an IAM role. For example, I have the following section in my `~/.aws/config` file. If I set `AWS_PROFILE=nextflow-s3-role`, Nextflow is unable to assume the role and benefit from the role's permissions (_e.g._ S3 access). On the other hand, if I set `AWS_PROFILE` to a profile for an IAM user with the same permissions that the role has, things work as expected. 

```
[profile nextflow-s3-user]
region = us-east-1
output = json

[profile nextflow-s3-role]
role_arn = arn:aws:iam::1234567890:role/service-role
source_profile = nextflow-s3-user
```

Note that this feature request is distinct from #422, which concerns instance profiles associated with IAM roles. In our case, we have existing EC2 instances that we can't associate with an IAM role after the fact (or the IAM role exists in another AWS account). 

## Usage scenario 

Our organization uses IAM roles to delegate permissions as per the [AWS Security Best Practices](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#delegate-using-roles). Being able to assume IAM roles using IAM user credentials (_i.e._ AWS access key) would help users to adopt these security best practices. 

## Suggest implementation 

It sounds like Nextflow supports session tokens (#1265), so this might just be a question of allowing Nextflow to generate these session tokens itself. While I can [generate](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html#using-temp-creds-sdk-cli) this session token myself, their duration is limited to 12 hours, which isn't long enough to cover the entire duration of a large workflow. So, it would be ideal if Nextflow could manage the renewal of these session tokens automatically.

**Comment by pditommaso** [comment]
Related to https://github.com/nextflow-io/nextflow/pull/3555

**Comment by pditommaso** [comment]
The support for AWS role is implemented by https://github.com/nextflow-io/nextflow/pull/3498. 

But it remains a weird behaviour to be addressed. It looks like the role to be assumed needs to be defined in the `~/.aws/config` as reported above, e.g.: 

 
```
[profile nextflow-s3-user]
region = us-east-1
output = json

[profile nextflow-s3-role]
role_arn = arn:aws:iam::1234567890:role/service-role
source_profile = nextflow-s3-user
``` 

However, when having this configuration the AWS SDK used by nextflow complains, saying it cannot find the specified profile. If the role config is provided in the `~/.aws/credentials` file instead, as shown below, it works as expected: 

```
[nextflow-s3-role]
role_arn = arn:aws:iam::1234567890:role/service-role
source_profile = nextflow-s3-user
```

Therefore I fear this will create inconsistency. 

Worth mentioning that nextflow just uses the `ProfileCredentialsProvider` provided by the AWS SDK, see here 

https://github.com/nextflow-io/nextflow/blob/43786d72a42d7edb4dba2fc88264006816a4889c/plugins/nf-amazon/src/main/nextflow/cloud/aws/AwsClientFactory.groovy#L276-L279

**Comment by pditommaso** [comment]
@bentsherman any thoughts on [this](https://github.com/nextflow-io/nextflow/issues/2073#issuecomment-1501803981)?

**Comment by pditommaso** [comment]
Likely, indeed the `aws` cli works putting the `role_arn` in both `config` and `credentials` files. 

However, in the docs you linked it says the role should be in the `config`, instead it looks like the SDK refuses to use it unless it's in the `credentials`. 

I'd expected users fail to make it work properly because it works in the opposite way the docs suggest to use it

**Comment by pditommaso** [comment]
Done. I've solved merging the content of the `credentials` and `config` files into a temporary credentials file.
