### ISSUE TITLE
fromSRA using http

### ISSUE THREAD

**Issue by matthpich** [nextflow-io/nextflow#2087]
## New feature
Hi Nextflow-ers! 
I am working behind a company firewall that is quite restrictive (e.g. ftp is forbidden).
I'd appreciate very much being able to choose the protocol fromSRA uses to fetch sequencing data.

## Usage scenario 
- depending on a user's work environment, s/he can choose the protocol that best fits her/his constraints when downloading sequences using fromSRA

## Suggest implementation 
- enable an additional option when fromSRA is called
- line 292 in the getFastqUrl function in nextflow/modules/nextflow/src/main/groovy/nextflow/datasource/SRAExplorer.groovy, prefix the target address with http:// or ftp:// according to the protocol chosen

Thanks for your time considering this request.

**Comment by pditommaso** [comment]
Was not aware, that the ftp host is also serving HTTP protocol. Good idea!

**Comment by pditommaso** [comment]
done
