### ISSUE TITLE
No way to set cpu and memory settings to kuberun pod

### ISSUE THREAD

**Issue by marcadella** [nextflow-io/nextflow#2088]
### Expected behavior and actual behavior

Having this config:

```
process {
  executor = 'k8s'
  cpus = 2
  memory = '2 GB'
}
k8s { ... }
```

and running `nextflow kuberun ...` I expect the nextflow pod driver to have the specified amount of cpu/memory.
But when i describe the pod I see:
```
Limits:
      cpu:     250m
      memory:  200Mi
    Requests:
      cpu:     150m
      memory:  100Mi
```
, which are the default settings on my cluster.

If these settings are only meant to be passed to the child pods, then `kuberun` should accept parameters to set cpu/memory.

### Steps to reproduce the problem

Config above (I cannot provide my k8s settings as it is private), and any main.nf will do (or simply `nextflow kuberun login`).

### Environment 

* Nextflow version: 21.04

**Comment by pditommaso** [comment]
`kuberun` was an experimental feature, as such is not meant to be feature complete.
