### ISSUE TITLE
AWS Batch job running but Nextflow reports failed

### ISSUE THREAD

**Issue by mafreitas** [nextflow-io/nextflow#2090]
## Bug report 

I have an AWS Batch pipeline that reports jobs as failed in nextflow, but they continue to run an complete successfully in AWS Batch

### Expected behavior and actual behavior

When running a pipeline on AWS Batch nextflow will report that a job has failed.  The job will continue to run in batch and complete sucessfully

### Program output 

<img width="666" alt="image" src="https://user-images.githubusercontent.com/3464229/117151603-3e290d00-ad87-11eb-9a74-ca55b7b8af4d.png">

### Environment 

* Nextflow version:
    nextflow version 21.04.0.5552
* Java version: 
    openjdk 11.0.11 2021-04-20 LTS
    OpenJDK Runtime Environment Corretto-11.0.11.9.1 (build 11.0.11+9-LTS)
    OpenJDK 64-Bit Server VM Corretto-11.0.11.9.1 (build 11.0.11+9-LTS, mixed mode)
* Operating system: 
      Amazon Linux 2
* Bash version: 
    GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)

### Additional context

I tried to increase the AWS client connection timeout to 30000, but that did not resolve the problem.

**Comment by pditommaso** [comment]
Not reproducible
