### ISSUE TITLE
JSON params file parsing in 21.04.0 broken

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#2091]
## Bug report 

We just noticed that with the release of 21.04.0 we are no longer able to specify nested parameters in JSON formatted parameter files. We get a `Cannot get property 'name' on null object` error and Nextflow fails.  This only seems to be a problem for JSON files. YAML files still behave correctly.

### Expected behavior and actual behavior

Given this `main.nf`:
```
println(params.title)
println(params.nested.name)
```
and this `params.json`:
```
{
    "title": "something",
    "nested": {
        "name": "Mike"
    }
}

```
I'd expect to see:
```
N E X T F L O W  ~  version 20.10.0
Launching `params_problem.nf` [reverent_mandelbrot] - revision: c9c2e821f4
something
Mike
```
but I actually see
```
N E X T F L O W  ~  version 21.04.0
Launching `params_problem.nf` [elegant_magritte] - revision: c9c2e821f4
something
Cannot get property 'name' on null object

 -- Check script 'params_problem.nf' at line: 3 or see '.nextflow.log' file for more details
```
### Steps to reproduce the problem

Save the Nextflow code above as `main.nf` and the params as `params.json` and run: `nextflow run -params-file params.json main.nf` with version 21.04.0 of Nextflow to see the problem.

Running the same command with Nextflow version 20.10.0 works as expected.

Likewise, running the command with this `params.yaml` file:
```
title: something
nested:
    name: Mike
```
also works as expected.

### Environment 

* Nextflow version: 21.04.0
* Java version: 1.8.0_161
* Operating system: macOS
* Bash version: 5.0.18

**Comment by pditommaso** [comment]
Meh, it breaks starting from `21.04.0-edge`

**Comment by mes5k** [comment]
"Meh" is Catalan for "Oh my this is a terrible bug and we'll rush out a fix as soon as possible."  Right?  :)

**Comment by pditommaso** [comment]
Possibly 😄

**Comment by pditommaso** [comment]
Should be fine 👉  74c1ea12. Please double check

**Comment by pditommaso** [comment]
Solved https://github.com/nextflow-io/nextflow/releases/tag/v21.04.1
