### ISSUE TITLE
Problem with SGE submission of example workflow

### ISSUE THREAD

**Issue by ChandraPedamallu** [nextflow-io/nextflow#210]
Hi,

I am very new to nextflow. 

I have taken the multiple_inputs.nf from "Nextflow examples".

Then, created a nextflow.config file with following lines.

process{
        executor = 'sge'
        queue = 'queue_name'
}

Then ran the following. 

./nextflow run -c nextflow.config ./examples/multiple_inputs.nf                         

Then, it started doing the following
N E X T F L O W  ~  version 0.20.1
Launching ./examples/multiple_inputs.nf
[warm up] executor > sge
[e6/2c4e94] Submitted process > blast (test)
Result saved to file: result.txt

I noticed that this is not submitting jobs to SGE cluster.

Please help me if i am doing anything wrong?

**Comment by pditommaso** [comment]
The log says 

```
executor > sge
```

What make you think that the task wasn't execute in the SGE scheduler?

**Comment by ChandraPedamallu** [comment]
After printing 

N E X T F L O W ~ version 0.20.1
Launching ./examples/multiple_inputs.nf
[warm up] executor > sge
[e6/2c4e94] Submitted process > blast (test)

It hanged there for several minutes

Then printed "Result saved to file: result.txt"

When it was hanged, i did qstat, i don't see any job

**Comment by ChandraPedamallu** [comment]
Can you please provide me with a simple job script and its associated config script? 

So that i can also test it, where the problem is?

**Comment by pditommaso** [comment]
You can try to run the following one lines 

```
nextflow run hello -process.executor sge -process.queue <your-queue-name>
```

**Comment by ChandraPedamallu** [comment]
Here is the log file

Aug-05 10:45:50.172 [main] DEBUG nextflow.cli.Launcher - $> ./nextflow run hello -process.executor sge -process.queue all.q
Aug-05 10:45:50.258 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.21.1
Aug-05 10:45:50.358 [main] DEBUG nextflow.scm.AssetManager - Listing projects in folder: /.nextflow/assets
Aug-05 10:45:50.381 [main] DEBUG nextflow.scm.AssetManager - Git config: /.nextflow/assets/nextflow-io/hello/.git/config; branch: master; remote: origin; url: https://github.com/nextflow-io/hello.git
Aug-05 10:45:50.394 [main] DEBUG nextflow.scm.AssetManager - Git config: /.nextflow/assets/nextflow-io/hello/.git/config; branch: master; remote: origin; url: https://github.com/nextflow-io/hello.git
Aug-05 10:45:50.519 [main] DEBUG nextflow.scm.AssetManager - Git config: /.nextflow/assets/nextflow-io/hello/.git/config; branch: master; remote: origin; url: https://github.com/nextflow-io/hello.git
Aug-05 10:45:50.519 [main] INFO  nextflow.cli.CmdRun - Launching 'nextflow-io/hello' - revision: 6b9515aba6 [master]
Aug-05 10:45:50.529 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: nextflow.config
Aug-05 10:45:50.531 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /softwares/nextflow/nextflow.config
Aug-05 10:45:50.746 [main] DEBUG nextflow.config.ConfigBuilder - Setting config profile: 'standard'
Aug-05 10:45:50.828 [main] DEBUG nextflow.Session - Session uuid: 1bdf1015-9158-4b41-b480-5a989539ab6f
Aug-05 10:45:50.830 [main] DEBUG nextflow.Session - Executor pool size: 16
Aug-05 10:45:50.850 [main] DEBUG nextflow.cli.CmdRun -
  Version: 0.21.1 build 3967
  Modified: 29-07-2016 12:22 UTC (08:22 EDT)
  System: Linux 2.6.32-504.16.2.el6.x86_64
  Runtime: Groovy 2.4.7 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_91-b14
  Encoding: UTF-8 (UTF-8)
  Process: 22944@usnee1-lph001-l001.cm.cluster [157.206.230.33]
  CPUs: 16 - Mem: 94.6 GB (1.5 GB) - Swap: 96 GB (95.6 GB)
Aug-05 10:45:50.866 [main] DEBUG nextflow.Session - Work-dir: /softwares/nextflow/work [nfs]
Aug-05 10:45:50.867 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /.nextflow/assets/nextflow-io/hello/bin
Aug-05 10:45:50.867 [main] DEBUG nextflow.Session - Session start invoked
Aug-05 10:45:50.869 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Aug-05 10:45:50.869 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Aug-05 10:45:51.006 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Aug-05 10:45:51.130 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: sge
Aug-05 10:45:51.130 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'sge'
Aug-05 10:45:51.140 [main] DEBUG nextflow.executor.Executor - Initializing executor: sge
Aug-05 10:45:51.142 [main] INFO  nextflow.executor.Executor - [warm up] executor > sge
Aug-05 10:45:51.148 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'sge' > capacity: 100; pollInterval: 1s; dumpInterval: 5m
Aug-05 10:45:51.150 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: TaskPollingMonitor
Aug-05 10:45:51.151 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: sge)
Aug-05 10:45:51.153 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: sge
Aug-05 10:45:51.154 [main] DEBUG n.executor.AbstractGridExecutor - Creating executor 'sge' > queue-stat-interval: 1m
Aug-05 10:45:51.207 [main] DEBUG nextflow.Session - >>> barrier register (process: sayHello)
Aug-05 10:45:51.220 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > sayHello -- maxForks: 16
Aug-05 10:45:51.244 [main] DEBUG nextflow.script.ScriptRunner - > Await termination
Aug-05 10:45:51.245 [main] DEBUG nextflow.Session - Session await
Aug-05 10:45:51.257 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <sayHello> Poison pill arrived
Aug-05 10:45:51.260 [Actor Thread 2] DEBUG nextflow.processor.StateObj - <sayHello> State before poison: StateObj[submitted: 4; completed: 0; poisoned: false ]
Aug-05 10:45:51.442 [Actor Thread 3] DEBUG nextflow.executor.GridTaskHandler - Launching process > sayHello (2) -- work folder: /softwares/nextflow/work/d2/04391b3fa58b6816b0d33706bbe069
Aug-05 10:45:51.913 [Actor Thread 3] INFO  nextflow.Session - [d2/04391b] Submitted process > sayHello (2)
Aug-05 10:45:51.913 [Actor Thread 5] DEBUG nextflow.executor.GridTaskHandler - Launching process > sayHello (3) -- work folder: /softwares/nextflow/work/f7/4d440c82e729b823c0ecfaaa569cf3
Aug-05 10:45:51.986 [Actor Thread 5] INFO  nextflow.Session - [f7/4d440c] Submitted process > sayHello (3)
Aug-05 10:45:51.986 [Actor Thread 6] DEBUG nextflow.executor.GridTaskHandler - Launching process > sayHello (4) -- work folder: /softwares/nextflow/work/4d/d05c8e82daa4c5e8bb088a0d3838e9
Aug-05 10:45:52.051 [Actor Thread 6] INFO  nextflow.Session - [4d/d05c8e] Submitted process > sayHello (4)
Aug-05 10:45:52.051 [Actor Thread 4] DEBUG nextflow.executor.GridTaskHandler - Launching process > sayHello (1) -- work folder: /softwares/nextflow/work/2d/f924f1be0f940d8671a398673028ac
Aug-05 10:45:52.124 [Actor Thread 4] INFO  nextflow.Session - [2d/f924f1] Submitted process > sayHello (1)
Aug-05 10:45:52.126 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <sayHello> After stop
Aug-05 10:46:22.200 [Actor Thread 2] DEBUG nextflow.processor.TaskProcessor - <sayHello> Sending poison pills and terminating process
Aug-05 10:46:22.201 [Actor Thread 2] DEBUG nextflow.Session - <<< barrier arrive (process: sayHello)
Aug-05 10:46:22.202 [main] DEBUG nextflow.Session - Session await > processes completed
Aug-05 10:46:23.172 [Thread-4] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: sge)
Aug-05 10:46:23.172 [main] DEBUG nextflow.Session - Session await > done
Aug-05 10:46:23.183 [main] DEBUG nextflow.Session - Session destroyed

**Comment by ChandraPedamallu** [comment]
I still have the script waited.. don't see any submission to SGE

**Comment by pditommaso** [comment]
it looks to work perfectly, if it looks to take too much time, it may be due to latencies in your file system. What shared file system is NFS ?

**Comment by ChandraPedamallu** [comment]
Isilion

**Comment by ChandraPedamallu** [comment]
You think, it submitted to SGE? Then, could you please help me to find how to check whether jobs are submitted are not to SGE?

**Comment by pditommaso** [comment]
Execute a longer tasks, so you will have more time to qstat it. For example: 

````
echo "process foo { 'sleep 10000' }" | nextflow run - -process.executor sge -process.queue <your-queue-name>
```

**Comment by ChandraPedamallu** [comment]
Yes, i see now. Thank you very much. I greatly appreciate your kind help and support.

I ran this:

echo "process foo { 'sleep 10000' }" | ./nextflow run - -process.executor sge -process.queue all.q
N E X T F L O W  ~  version 0.21.1
[warm up] executor > sge
[cc/0d4558] Submitted process > foo (1)

At this point it just hangs there. After submitted to queue, it returns back to prompt correct?

**Comment by pditommaso** [comment]
nextflow returns to the problem after the jobs completion. If you want launch it in background you can use the `-bg` option.
