### ISSUE TITLE
Running DSL1 pipelines on Nextflow 21.04 with conda results in unspecific error ` No signature of method: java.lang.Boolean.isEmpty()`

### ISSUE THREAD

**Issue by jfy133** [nextflow-io/nextflow#2105]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

Expected: Running nf-core DSL1 pipelines with conda should run through as normal when using Nextflow 21.04 (as happens with singularity).

 Actual: When running with `conda`, _some_ pipelines crash almost immediately  with the following error:

```
May-11 21:40:52.210 [main] ERROR nextflow.cli.Launcher - @unknown
org.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: java.lang.Boolean.isEmpty() is applicable for argument types: () values: []
Possible solutions: identity(groovy.lang.Closure), inspect(), dump()
```

### Steps to reproduce the problem

```
export NXF_VER=20.10.0
nextflow run nf-core/eager -r 2.3.4 -profile singularity,test_tsv ## WORKS
nextflow run nf-core/eager -r 2.3.4 -profile conda,test_tsv ## WORKS

export NXF_VER=21.04.0
nextflow run nf-core/eager -r 2.3.4 -profile singularity,test_tsv ## WORKS
nextflow run nf-core/eager -r 2.3.4 -profile conda,test_tsv ## FAILS
```

### Program output 

```
🧬 21:57:33 with 6GiB/15GiB in eager/tests on  nf-21-04-issue [!] took 23s ✖  nextflow run nf-core/eager -r 2.3.4 -profile conda,test_tsv ## WORKS
N E X T F L O W  ~  version 21.04.0
Launching `nf-core/eager` [friendly_laplace] - revision: 10bfbdff86 [2.3.4]
Unknown method invocation `isEmpty` on Boolean type

```

Full log here: [nextflow.log](https://github.com/nextflow-io/nextflow/files/6461663/nextflow.log)

### Environment 

* Nextflow version: (see above)
* Java version:
     ```
    openjdk version "11.0.11" 2021-04-20
    OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
    OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
    ```

* Operating system: Ubuntu 20.04.2
* Bash version: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`

### Additional context

- This error occurs before any pipeline code is evaluated. When adding `log` console output to the beginning of the script, this is NOT displayed on screen before the crash and the error above. 
- While nf-core/eager DOES is `isEmpty()` [probably incorrectly], it has been reported in other pipelines without this function the same error occurs. Additionally, it is strange the pipeline runs for singularity and not conda.
- Furthemrore I did a 'trace back' on NXF_VER and it seems the issue starts to occur from `20.12.0-edge` onwards. I suspect it's something to do with the Groovy update mentioned [here](https://github.com/nextflow-io/nextflow/releases/tag/v20.12.0-edge)

**Comment by pditommaso** [comment]
Maybe this? 

https://github.com/nf-core/eager/blob/master/nextflow.config#L292

**Comment by pditommaso** [comment]
Yes, that's the problem. It shoudl be 

```
charliecloud.enabled = false
```

I've added improved the error reporting in future release 68e5ca18

**Comment by drpatelh** [comment]
I knew it has something to do with this! Sorry, been knee deep in stuff today so didn't have the time to respond on Slack but this has been fixed in the latest pipeline template as you can see [here](https://github.com/nf-core/tools/blob/7721f3742fc30a9e6e46d879404bd1366345092d/nf_core/pipeline-template/nextflow.config#L69). Just need to get the latest template sync in and you should be good to go @jfy133 @ypriverol

**Comment by drpatelh** [comment]
But improved error reporting is a bonus!! 😎

**Comment by jfy133** [comment]
Ah crap, that's embarrassing (I must have forgotten to check that when adding to the template :facepalm:). My bad and thanks @pditommaso for the beady eyes. Indeed, improved error reporting is much appreciated!

**Comment by pditommaso** [comment]
> But improved error reporting is a bonus!!

![](https://media1.giphy.com/media/5xtDarrD3UV3Qk6N00E/giphy-downsized-medium.gif)
