### ISSUE TITLE
AZ Executor: assign the same pool Id across executions

### ISSUE THREAD

**Issue by manuelesimi** [nextflow-io/nextflow#2110]
## Bug report 

The same pool Id is assigned to a pool across different executions and this is fine for most cases. However, when `deletePoolsOnCompletion` is set to `true`, the same pipeline cannot be executed until the pool has been completely shut down by Azure batch (the pipeline is asynchronous with respect to this operation).

### Expected behavior and actual behavior

I was expecting to be able to re-run a pipeline as soon as the previous execution is completed (regardless its status). However, when `deletePoolsOnCompletion` is set to `true`, all the subsequent runs of the same pipeline fail because the pool is shutting down and not active. Only when the pool is completely removed from the batch account it's possible to run again the pipeline.

I'd expect that a different Id is assigned to the pool at each execution, allowing the user to immediately restart the pipeline if needed.

### Steps to reproduce the problem

A configuration like the following on any pipeline should reproduce the problem:

<pre>
azure {
  batch {
    location = ''
    accountName = ''
    accountKey = ''
    allowPoolCreation = true
    autoPoolMode = true
    deletePoolsOnCompletion = true
    copyToolInstallMode = 'task'

     pools {
       auto {
             vmType = 'Standard_D4_v3'
             vmCount = 1

       }
    }
  }

  storage {
    accountName = ''
    accountKey = ''
  }

</pre>

Just run the pipeline and when it exits, run it again.

### Program output 
<pre>
[4c/7a226f] process > sayHelloInItalian (1) [100%] 1 of 1, failed: 1
[-        ] process > sayHelloInFrench      -
[-        ] process > sayHelloInSpanish     -
[-        ] process > sayHelloInEnglish     -
Error executing process > 'sayHelloInItalian (1)'

Caused by:
  Azure Batch pool 'nf-pool-57aff74792e19c971c8c9ffed63c0f99-Standard_D4_v3' not in active state

</pre>

[nextflow.log](https://github.com/nextflow-io/nextflow/files/6468723/nextflow.log)

### Environment 

* Nextflow version: 21.05.0-edge
* Java version: openjdk version "1.8.0_171"
* Operating system: Linux
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by pditommaso** [comment]
Need to see better, but I think it's expected.

**Comment by manuelesimi** [comment]
Looking at the source code, it is the expected behavior. My question is if this is intentional. Is there a specific design choice behind this behavior or can it be changed in favor of re-running the pipeline faster?

**Comment by pditommaso** [comment]
If you plan to launch multiple runs with the same pool you should not delete the pool on completion. Likely a better alternative consists using a pool configured with autoscale enabled, which automatically turn off the machine when they are not used.

**Comment by vinishgeorge** [comment]
One use case for this is the way azure billing works is we get the cost for each pool that ran. So i want to create new pools each time i trigger a pipeline using nextflow. But because the AZ Executor: assign the same pool Id across executions we cannot have multiple runs and  processing things parallelly.

**Comment by manuelesimi** [comment]
@vinishgeorge I've also experienced that behavior as well. When I run the pipeline multiple times in parallel, I would have expected different pools for each execution, but that was not the case.

**Comment by pditommaso** [comment]
Maybe here we should just add a note in the documentation. @manuelesimi sounds OK for you?

**Comment by manuelesimi** [comment]
Something like this https://github.com/nextflow-io/nextflow/pull/2483? 
I think it should be sufficient to explain users what happens in between two executions under these conditions.

**Comment by pditommaso** [comment]
I would add a more explicit note about the fact the auto-generated pool ID are expected to be reused across relaunch e.g. 

```
.. warning: 
  When using auto pool mode, Nextflow uses the same pool Id across pipeline executions, if the pool features have not changed. 

  Therefore, where using ``deletePoolsOnCompletion=true``, make sure the pool is completely removed by Azure Batch before re-running the pipeline.
   The following message is returned when the pool is still shutting down ::
```

Feel free to improve

**Comment by manuelesimi** [comment]
Good point. However, this behavior happens also for named pools. See if this commit captures that: https://github.com/nextflow-io/nextflow/pull/2483/commits/220690d46f189729962bc199dc39e8fce2a336d3

**Comment by pditommaso** [comment]
Think this can be closed, right?

**Comment by manuelesimi** [comment]
Absolutely.
