### ISSUE TITLE
Unable to read azure file storage (pipeline worked fine in AWS)

### ISSUE THREAD

**Issue by Lumimar** [nextflow-io/nextflow#2117]
## Bug report
Unable to read azure file storage (pipeline worked fine in AWS)

### Expected behavior and actual behavior
It would be good to get some insight into what might be causing the "Unable to download path:" error on azure batch. Pipeline worked on AWS, the config file with azure batch details is present, azure batch is correctly set up and can run on mock nextflow pipeline (see additional context)
[nextflow.log](https://github.com/nextflow-io/nextflow/files/6499856/nextflow.log)

### Steps to reproduce the problem

this works
//String base_directory="s3://test/"
params.base_dir = base_directory
base_dir_ch = Channel.value( params.base_dir )

this does not work
//String base_directory="az://test/"
params.base_dir = base_directory
base_dir_ch = Channel.value( params.base_dir )

### Program output
see log file, the error seems to be here:
May-18 11:28:32.262 [reactor-http-epoll-2] WARN  r.n.http.client.HttpClientConnect - [id: 0x1a438020, L:/172.22.96.120:46492 - R:genomicsbatchsa.blob.core.windows.net/20.38.106.196:443] The connection observed an error
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

### Environment
* Nextflow version: nextflow version 21.04.0.5552
* Java version: 1.8.0_292
* Operating system: ubuntu 20.04
* Bash version:GNU bash, version 5.0.17(1)-release 

### Additional context

to help/confuse matters, this syntax works
params.filePath = 'az://helloworld/input.txt' //default value
params.str = file(params.filePath).text

**Comment by johnthomaswright** [comment]
I've found a similar issue, since the SAS token created by Azure is at the container level.  Try it with the "work" path in the same container as your inputs/outputs.  If it works, that means needing a feature added so the SAS token is at the storage account level, not the container.
