### ISSUE TITLE
Unknown method invocation `file` on _parse_closure5 type

### ISSUE THREAD

**Issue by daidaiV5** [nextflow-io/nextflow#2125]
Hi!

I have a question about nextflow.config, I would like to rename pipeline_info with the name of gene:
```
params.read1 = "/home/yuping/nextflow/sample/read1.fastq"
def NAME =  file(params.read1).getSimpleName()

timeline {
  enabled = true
  file = "${params.tracedir}/execution_timeline_${NAME}.html"
}
 
```
it return 
```
Unknown method invocation `file` on _parse_closure5 type
```

the method `file(params.read1).getSimpleName() `works well in the main.nf, but it doesn't work in the nextflow.config,
so do you have any idea about how to solve the problem or another method for rename a document in the nextflow.config

**Comment by jennomics** [comment]
what was your solution here?

**Comment by daidaiV5** [comment]
> what was your solution here?

sorry I don't find the solution, I just give up

**Comment by pditommaso** [comment]
The solution is to not use `file` in the config and if you really need use plain Java/groovy `File`api https://docs.oracle.com/javase/7/docs/api/java/io/File.html
