### ISSUE TITLE
Azure batch : Ability to choose the types of user accounts on azure batch for the pipeline to run on.

### ISSUE THREAD

**Issue by vinishgeorge** [nextflow-io/nextflow#2126]
## New feature

Hi ,
Would like to request to add the ability to choose the batch user account the task should run on.
Currently nextflow run each task run using the PoolNonAdmin user identity .

## Usage scenario 

While running task on a docker container as a root user instead of the Azure batch's auto generated user.

## Suggest implementation 

The details of user account can be found below in the azure batch documentation along with code snippet of the way to assign the task the user identity. :
https://docs.microsoft.com/en-us/azure/batch/batch-user-accounts

**Comment by abhi18av** [comment]
Hi @vinishgeorge , 

Could you please elaborate on your use-case. What obstacles are you facing with the current settings in NF? 

I went through the link but hearing your use-case would be of help for sure :)

**Comment by vinishgeorge** [comment]
Hi @abhi18av ,

The issue I am facing is my docker runs using a root user, but when I run the nextflow pipeline it fails due to permission issues and commands not being found. I cloned the same task that nextflow had created and ran it with an Elevated user identity and my Task completed successfully. Hence if I get a configuration to mention what user identity to choose while running the Task it would resolve the issue.

**Comment by abhi18av** [comment]
Thanks for the the context @vinishgeorge  👍  

I'm pinging @manuelesimi here (who has been looking into the azure support recently ), to have a look here and share his thoughts.

**Comment by manuelesimi** [comment]
Hi,

I haven't tried yet, but according to the Azure doc, it should be possible (even if a bit discouraged) to run tasks with elevated access. From the NF's point of view, this could be a per-pool (not per-task) configuration, meaning that all the tasks submitted to that pool would have elevated access. Eventually, this could be set for all the pools, but since it's not an optimal practice, I'd keep it at pool level (with some good warnings in the NF documentation if the user decides enable it).

The batch configuration should be something like:
<pre>
azure {
          batch {
            location = 'eastus2'
            accountName = ''
            endpoint = ''
            accountKey = ''
            allowPoolCreation = true
            autoPoolMode = true
            deletePoolsOnCompletion = true
            copyToolInstallMode = 'task'

            pools {
               auto {
                     runWithElevatedAccess = 'true'
                     vmType = 'Standard_D4_v3'
                     vmCount = 1
               }
            }
          }

          storage {
            accountName = ''
            accountKey = ''
          }

          registry {
            server = 'docker.io'
            userName = ''
            password = ''
          }
        }
    }
</pre> 

@pditommaso Is this something NF is interested to have? Do you see any drawback?

**Comment by manuelesimi** [comment]
Digging a bit more in the Azure SDK, there is also the option to run the task under a specific user (which is in turn can be configured with elevated access).

Hence, the config could be:
<pre>
azure {
          batch {
            location = 'eastus2'
            accountName = ''
            endpoint = ''
            accountKey = ''
            allowPoolCreation = true
            autoPoolMode = true
            deletePoolsOnCompletion = true
            copyToolInstallMode = 'task'

            pools {
               auto {
                     runAs = '<MY USERNAME>' //if not specified, the auto-user is used instead
                     runWithElevatedAccess = 'true' // it works both with the auto-user and the user set with 'runAs'
                     vmType = 'Standard_D4_v3'
                     vmCount = 1
               }
            }
          }

          storage {
            accountName = ''
            accountKey = ''
          }

          registry {
            server = 'docker.io'
            userName = ''
            password = ''
          }
        }
    }
</pre>

**Comment by vinishgeorge** [comment]
@manuelesimi  looks great , exactly what I would want to have . I agree may be it's not the best of practice but some scenario's we may need it. 
I wasn't sure if we could set the elevated user account at pool level I thought it's always related to a task.
Thank you

**Comment by pditommaso** [comment]
Would `runWithElevatedAccess` be the equivalent of docker *priviledged* option?

**Comment by manuelesimi** [comment]
According to the Azure doc, the entire task "runs as a user with elevated access and operates with full Administrator permissions". I guess this is broader than the privileged option with docker and it revolves around what the task can do and/or access on the node. Even if not a best practice, it might be useful to offer to NF users the possibility to make such a choice.

**Comment by manuelesimi** [comment]
> @manuelesimi looks great , exactly what I would want to have . I agree may be it's not the best of practice but some scenario's we may need it.
> I wasn't sure if we could set the elevated user account at pool level I thought it's always related to a task.

Azure lets you do it at task level, but since NF does not have a per-task configuration (for simplicity and homogeneity across executors), we could have the setting at pool level and then propagate it to each task submitted to the pool.

> Thank you

**Comment by vinishgeorge** [comment]
Yes . That makes sense.

**Comment by manuelesimi** [comment]
@pditommaso you didn't express your opinion if nextflow would benefit from adding this optional behavior.

**Comment by pditommaso** [comment]
Yes, I think it would make sense, I would only rename `runWithElevatedAccess` to `privileged`

**Comment by manuelesimi** [comment]
See https://github.com/nextflow-io/nextflow/pull/2157
