### ISSUE TITLE
Adding Execution environment variable on kuberun command is not working

### ISSUE THREAD

**Issue by Trebuac** [nextflow-io/nextflow#2132]
### Expected behavior and actual behavior

The `-e.` of [kuberun command](https://www.nextflow.io/docs/latest/cli.html#kuberun
) doesn't work and returns an exception.

### Steps to reproduce the problem

Run the hello world example with a specified variable to add on execution environment.
`
nextflow kuberun hello -v nextflow-kuberun:/tmp -e.key=value
` 

### Program output 

`
Dynamic parameter expected a value of the form a=b but got:key -- Check the available commands and options and syntax with 'help'
`

### Environment 

* Nextflow version: [21.04.1] 
* Java version: [11]
* Operating system: [ Linux]
* Bash version: GNU bash, version 5.0.17

### Additional context

I noticed this problem when attempting to mount k8s secrets (here AWS credentials) on the kubernetes **driver** pod (only options available on kuberun are mounted volumes). Any workaround or advice will be appreciated :)

**Comment by Trebuac** [comment]
The `-E` option is also not available with nextflow kuberun returning 

`
Option `-E` not supported with Kubernetes deployment
`
Maybe just a documentation issue.

**Comment by Pradyumn** [comment]
@Trebuac I'm encountering the same issue. Have you found any solution?
