### ISSUE TITLE
subscribe and 'Script compilation error'

### ISSUE THREAD

**Issue by Melkaz** [nextflow-io/nextflow#2136]
### Expected behavior and actual behavior

Should print the stdout of a process

### Steps to reproduce the problem

Code from this page: https://www.nextflow.io/docs/latest/dsl2.html

```
nextflow.enable.dsl=2

process sayHello {
    input:
        val cheers
        
    output:
        stdout emit: verbiage

    script: 
        """ 
        echo -n $cheers 
        """
}

workflow {
    things = channel.of('Hello world!', 'Yo, dude!', 'Duck!') 
    greetings = sayHello(things) 
    greetings.verbiage.subscribe {println “$it” }
}
```

Code runs without error if we remove the line with `subscribe`.
Fails when line is included.

### Program output 

```nextflow run workflow.nf
N E X T F L O W  ~  version 21.04.1
Launching `workflow.nf` [jovial_lavoisier] - revision: 4e8b2ce08a
Script compilation error
- file : /scratch2/prototypes/versions/4/workflow.nf
- cause: Unexpected input: '{' @ line 16, column 10.
   workflow {
            ^

1 error
```

### Environment 

* Nextflow version: 21.04.1 build 5556
* Java version: OpenJDK 64-Bit Server VM 11.0.11+9-LTS
* Operating system: Linus
* Bash version: GNU bash, version 4.4.19(1)-release (x86_64-redhat-linux-gnu)

Thank you,

**Comment by Melkaz** [comment]
Ahem...

When copy/pasting the code (https://www.nextflow.io/docs/latest/dsl2.html) I let some weird double quote in my code.

`greetings.verbiage.subscribe {println “$it” }` => `greetings.verbiage.subscribe {println "$it" }`

It would be nice if the error was a bit more informative though, so we know where the syntax issue is.

**Comment by pditommaso** [comment]
Actually, there should not be those `“` in the docs. Re-opening to address that

**Comment by pditommaso** [comment]
Done 4ca00af1
