### ISSUE TITLE
Pulling from GitHub enterprise requires endpoint specification

### ISSUE THREAD

**Issue by jamesbaye** [nextflow-io/nextflow#2148]
The documentation provides some information on [private server configuration](https://www.nextflow.io/docs/latest/sharing.html#private-server-configuration) for pulling nextflow pipelines. When naively following those instructions applied to a Github enterprise domain, an error occurs:
```
nextflow run my/repo -hub myhub
```
`$HOME/.nextflow/scm` file:
```
providers {
    myhub {
        server = 'https://git.***.com'
        platform = 'github'
        user = '***'
        password = '***'
    }
}
```

Outputs:
```
N E X T F L O W  ~  version 21.04.0
Pulling my/repo ...
WARN: Cannot read project manifest -- Cause: Unable to determine the current character, it is not a string, number, array, or object

The current character read is '<' with an int value of 60
Unable to determine the current character, it is not a string, number, array, or object
line number 6
index number 5
<!DOCTYPE html>
^
Unable to determine the current character, it is not a string, number, array, or object
```

The error is fixed by specifying the `endpoint` for GitHub enterprise in the `$HOME/.nextflow/scm` file:
```
providers {
    myhub {
        server = 'https://git.***.com'
        endpoint = 'https://git.***.com/api/v3'
        platform = 'github'
        user = '***'
        password = '***'
    }
}
```

Could this either be specified more clearly in the documentation, or make the defaults endpoint field be compatible with GitHub enterprise?

**Comment by pditommaso** [comment]
Feel free to submit a PR to amend the docs!
