### ISSUE TITLE
`storeDir` checks for the presence of at least one output file instead of all.

### ISSUE THREAD

**Issue by mahesh-panchal** [nextflow-io/nextflow#2151]
### Expected behavior and actual behavior

The expected behavior of a process that uses `storeDir` is that it should check for all files in the output declaration. 
The actual behavior is that the process which uses `storeDir` skips if it finds at least one file in the output declaration.

### Steps to reproduce the problem

Toy example: https://github.com/mahesh-panchal/Nextflow_Conditional_BuildDB

The CHECKDB:BUILDDB process takes the input file `database.txt` and produces `database.{tnt,ttt,tzt}`. The files
`database.{txt,tnt,ttt,tzt}` are specified as output of the process. However, this process skips creating the other files because of the presence of `database.txt` in the `storeDir`.  Running the toy example (`nextflow run main.nf`) should reproduce the problem. 

### Program output 

The BUILDDB process skips even though only the input file is present. 
```
$ ls db/database
database.txt
$ nextflow run main.nf 
N E X T F L O W  ~  version 21.04.0
Launching `main.nf` [ecstatic_descartes] - revision: 0fa85fe346
executor >  local (1)
[skipped  ] process > CHECKDB:BUILDDB [100%] 1 of 1, stored: 1 ✔
[c1/0fc242] process > CHECKDB:QUERYDB [100%] 1 of 1 ✔
[skipping] Stored process > CHECKDB:BUILDDB
total 0
lrwxr-xr-x 1 mahpa906 staff 88 Jun  4 16:45 database.txt -> /Users/mahpa906/Documents/Nextflow/Nextflow_Conditional_BuildDB/db/database/database.txt
lrwxr-xr-x 1 mahpa906 staff 76 Jun  4 16:45 somefile.txt -> /Users/mahpa906/Documents/Nextflow/Nextflow_Conditional_BuildDB/somefile.txt
database.txt: empty
somefile.txt: broken symbolic link to /Users/mahpa906/Documents/Nextflow/Nextflow_Conditional_BuildDB/somefile.txt
```

### Environment 

* Nextflow version: 21.04.0
* Java version: openjdk 11.0.9.1 2020-11-04 LTS
* Operating system: macOS
* Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

**Comment by mahesh-panchal** [comment]
This bug is still present in `21.10.0`.
```nextflow
$ nextflow run main.nf 
N E X T F L O W  ~  version 21.10.0
Launching `main.nf` [disturbed_ritchie] - revision: 0fa85fe346
executor >  local (1)
[skipped  ] process > CHECKDB:BUILDDB [100%] 1 of 1, stored: 1 ✔
[61/1d5be7] process > CHECKDB:QUERYDB [100%] 1 of 1 ✔
[skipping] Stored process > CHECKDB:BUILDDB
total 0
lrwxr-xr-x 1 mahpa906 staff 110 Dec  6 10:36 database.txt -> /Users/mahpa906/Downloads/Nextflow_sandbox/test_stage_db/Nextflow_Conditional_BuildDB/db/database/database.txt
lrwxr-xr-x 1 mahpa906 staff  98 Dec  6 10:36 somefile.txt -> /Users/mahpa906/Downloads/Nextflow_sandbox/test_stage_db/Nextflow_Conditional_BuildDB/somefile.txt
database.txt: empty
somefile.txt: broken symbolic link to /Users/mahpa906/Downloads/Nextflow_sandbox/test_stage_db/Nextflow_Conditional_BuildDB/somefile.txt
```
The process `CHECKDB:BUILDDB` skips executing because one of the output files is there, but it should execute because not all of the output files are in the `storeDir`.

**Comment by gbinux** [comment]
i had the same issue. it works the best if i give the exact name of the output file. using wildcards does not  give me what i expect.

**Comment by mahesh-panchal** [comment]
@bentsherman Something to perhaps add to the Nextflow improvements.

**Comment by bentsherman** [comment]
@mahesh-panchal I think glob outputs have different semantics than what you're trying to do here. When you say `database.{txt,tnt,ttt,tzt}`, you are expecting **all** of these files to be present, but to Nextflow it means that **any** of the files must be present, but not necessarily all of them.

Maybe that is something we should clarify in the documentation somewhere? I would want to review the docs more carefully since globs are used in many places and might be relevant there.

In any case, I think PR #3706 will allow you to achieve the desired behavior by specifying `arity: 4` so that Nextflow requires all four files to be present.
