### ISSUE TITLE
Negative labels do not work as expected

### ISSUE THREAD

**Issue by jordeu** [nextflow-io/nextflow#2155]
## Bug report 

A negated rule will always be applied to a process that has two or more labels, one that matches the rule and one that don't. 

### Expected behavior and actual behavior

Given two config definitions like:

```
withLabel: "local_process" {
    executor = "local"
    maxRetries = 0
}

withLabel: "!local_process" {
    executor = "slurm"
    maxRetries = 3
    container = "debian"    
}
```

and a process:
```
process procOne {
    label "local_process"
    label "big_mem"
}
```

and a process:
```
process procTwo {
    label "big_mem"
    label "local_process"
}
```

Nextflow will solve this to:

```
process procOne {
   executor = "slurm"
    maxRetries = 3
    container = "debian"     
}
```

and:
```
process procTwo {
    executor = "local"
    maxRetries = 0
    container = "debian" 
}
```

The expected behaviour is that the order of the process labels do not affect the result that must be that only the first configuration is applied:

```
process procTwo {
    executor = "local"
    maxRetries = 0
}
```

**Comment by pditommaso** [comment]
Included in release `21.06.0-edge`.
