### ISSUE TITLE
Nextflow takes too long in staging phase with Google Cloud Platform

### ISSUE THREAD

**Issue by Abdelrahman-Galal** [nextflow-io/nextflow#2160]
### Expected behavior and actual behavior

I am trying to run a nextflow pipeline using 'google-lifesciences' executor , the process has an input file of 92GB.
The pipeline create the VM and wait about 50 minutes before starting the real command.
When I ssh to the VM and open _.command.log_ it shows that it still is nxf_stage and the input file has __.gstmp_ extension.
I expect the staging process to take less time than 50 minutes for 92GB.
The input file is stored in GCP bucket.

### Program output 

````
Jun-09 08:00:30.329 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor google-lifesciences > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: SAIGE_STEP_1 (1); status: RUNNING; exit: -; error: -; workDir: gs://nextflow/workdir/5e/05e0dd7dd8023c7cc543d4987b77e7]
Jun-09 08:05:30.339 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor google-lifesciences > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: SAIGE_STEP_1 (1); status: RUNNING; exit: -; error: -; workDir: gs://nextflow/workdir/5e/05e0dd7dd8023c7cc543d4987b77e7]
Jun-09 08:10:30.344 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor google-lifesciences > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: SAIGE_STEP_1 (1); status: RUNNING; exit: -; error: -; workDir: gs://nextflow/workdir/5e/05e0dd7dd8023c7cc543d4987b77e7]
Jun-09 08:15:30.354 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor google-lifesciences > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: SAIGE_STEP_1 (1); status: RUNNING; exit: -; error: -; workDir: gs://nextflow/workdir/5e/05e0dd7dd8023c7cc543d4987b77e7]
````

And .command.log from the VM

````
+ cd /workdir/5e/05e0dd7dd8023c7cc543d4987b77e7
+ gsutil -m -q cp gs://nextflow/workdir/5e/05e0dd7dd8023c7cc543d4987b77e7/.command.run .
+ bash .command.run nxf_stage
````

### Environment 

* Nextflow version:  20.10.0 build 5430
* Java version: openjdk version "1.8.0_292"
* Operating system: Linux 5.4.0-1042-gcp
* Bash version: 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by pditommaso** [comment]
There's a PR that should solve this https://github.com/nextflow-io/nextflow/pull/1973

**Comment by pditommaso** [comment]
An improvement has been committed on the master branch 👉 2da120b9.  It will be included in the next release
