### ISSUE TITLE
Finer grain control of K8S security context

### ISSUE THREAD

**Issue by tdudgeon** [nextflow-io/nextflow#2161]
## New feature

Add ability to define `runAsGroup` and `fsGroup` properties in the `securityContext`.

## Usage scenario 

It is sometimes necessary to have very tight control over the ownership of files that Nextflow creates using the K8S executor.
The k8s scope already provide a `runAsUser` property that gets added to the securityContext of the pod, but it seems that it is not possible to define the `runAsGroup` and `fsGroup` properties. This means we cannot control the file ownership full.

## Suggest implementation 

Add `runAsGroup` and `fsGroup` properties in the same way that `runAsUser` is implemented.

**Comment by tdudgeon** [comment]
Poking this to keep it alive.
What are the chances of the various K8S related issues getting some attention?

**Comment by bentsherman** [comment]
You should be able to do this with the `securityConext` pod option:
```
pod = [
  securityContext: [runAsUser: 1000, runAsGroup: 3000, fsGroup: 2000]
]
```

In looking through the code I saw that this feature is already supported but just isn't documented. I will update the docs. It seems `runAsUser` is directly available as a shortcut, for your case I think simply passing a `securityContext` object will do.

**Comment by bentsherman** [comment]
You can also provide set the `securityContext` in the `k8s` config scope so that it applies to all pods:
```
k8s {
  securityContext = [runAsUser: 1000, runAsGroup: 3000, fsGroup: 2000]
}
```
