### ISSUE TITLE
Boolean variable for new Stub mode

### ISSUE THREAD

**Issue by jmonroynieto** [nextflow-io/nextflow#2164]
**Description**

In a similar fashion to `workflow.resume` it would be useful for a pipeline to be able to operate based on the running mode that was recently introduced (3de45c2287d78a70ac477d705aa9b8a4c019e629) as _stubs_. 

**Main usage case, deployment scenario, and suggested implementation**

Sometimes channel operations, and other workflow management tasks take place outside of any `process` block, The addition of a `workflow.stubRun` or `workflow.stub` variable will bring on better integration for this feature.

**Comment by pditommaso** [comment]
Thanks for suggesting this. It has been added to current master. It will be included in next release.

**Comment by pditommaso** [comment]
Included in release `21.06.0-edge`.
