### ISSUE TITLE
CLI param overwrites nested parameters to null

### ISSUE THREAD

**Issue by jamesbaye** [nextflow-io/nextflow#2166]
### Expected behavior and actual behavior

I am encountering the same issue that should have been solved in #1856 (i.e. CLI nested param overwrites all other nested params to `null`). Defining each nested parameter with its prefix works as described in #1923, albeit not very convenient.

### Steps to reproduce the problem

nextflow.config
```
params {
    nested {
        foo = 'foo'
        bar = 'bar'
    }
    nest_flat.foo = 'foo_flat'
    nest_flat.bar = 'bar_flat'
}
```

main.nf
```
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

workflow {
    println "foo: $params.nested.foo bar: $params.nested.bar"
    println "(flat) foo: $params.nest_flat.foo bar: $params.nest_flat.bar"
}
```

```
nextflow run main.nf --nested.foo "foo_cli" --nest_flat.foo "foo_flat_cli"
```

### Program output 

Observed
```
foo: foo_cli bar: null
(flat) foo: foo_flat_cli bar: bar_flat
```

Expected
```
foo: foo_cli bar: bar
(flat) foo: foo_flat_cli bar: bar_flat
```

### Environment 

* Nextflow version: 21.04.1.5556
* Java version: 1.8.0_282
* Operating system: CentOS Linux release 7.9.2009 
* Bash version: 4.2.46(2)-release

**Comment by wclose** [comment]
+1 to this. I am also running into the same issue.

**Comment by abhi18av** [comment]
A fix has been merged recently for this and would be available in the next `edge` release i.e. `21.12-edge` .
