### ISSUE TITLE
Thousands of orphaned AWS Batch jobs after exiting pipeline

### ISSUE THREAD

**Issue by arondaniel** [nextflow-io/nextflow#2169]
## Bug report 

We have a pipeline that creates several thousand processes that run on an AWS Batch queue. If the pipeline exits early for some reason, some jobs are killed but many jobs are left in the queue in "RUNNABLE" state and will continue running.

### Expected behavior and actual behavior

Exiting pipeline should kill all AWS Batch jobs.

### Steps to reproduce the problem

I believe that any pipeline creating thousands of jobs will fail in this way. Will work on this if necessary. Please see note below, I think I know what the bug is...

### Program output 

Best illustrated by grep.

7128 jobs submitted:
(clarreo) [tomcat@miic1 9gyJ]$ grep -c "submitted >" .nextflow.log.2 
7128

1734 jobs completed:
(clarreo) [tomcat@miic1 9gyJ]$ grep -c "completed >" .nextflow.log.2 
1734

Only 777 jobs killed by NF:
-bash-4.1$ grep -c "killing job" .nextflow.log.2 
777

7128-1734-777= 4617 orphaned jobs

### Environment 

* Nextflow version: 

      N E X T F L O W
      version 21.04.1 build 5556
      created 14-05-2021 15:20 UTC (11:20 EDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io

* Java version: 

openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

* Operating system:

Red Hat Enterprise Linux Server release 6.10 (Santiago)

* Bash version: (use the command `$SHELL --version`)

GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

### Additional context

When writing script to kill orphans, I noticed that Amazon does *NOT* return all jobs in the command "aws batch list-jobs"!!!

It returns only about the first thousand or so. So you need to keep calling it until it returns none!

**Comment by arondaniel** [comment]
Looking at output, possibly the problem is abort not waiting long enough for the AwsBatchTaskHandler to do its job.

From the log below you can see that AwsBatchTaskHandler kills a handful of jobs after the "workflow completed" message. 

Coincidentally about 5 minutes after I killed the pipeline.

So is there some kind of 5-minute shutdown timer somewhere? I can't find it. Still looking...

Jul-14 16:05:14.393 [SIGTERM handler] DEBUG nextflow.Session - Session aborted -- Cause: SIGTERM
...
Jul-14 16:05:14.867 [main] WARN  n.processor.TaskPollingMonitor - Killing pending tasks (14549)
... messages for 1558  jobs killed ...
Jul-14 16:10:17.047 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=178; failedCount=2956; ignoredCount=0; cachedCount=1563; pendingCount=0; submittedCount=14450; runningCount=-14450; retriesCount=0; abortedCount=11593; succeedDuration=80d 4h 30m 28s; failedDuration=0ms; cachedDuration=52d 2h 3m 1s;loadCpus=-693506; loadMemory=0; peakRunning=105; peakCpus=5040; peakMemory=7.9 TB; ]
Jul-14 16:10:17.047 [main] DEBUG nextflow.trace.ReportObserver - Flow completing -- rendering html report
Jul-14 16:10:17.147 [AWSBatch-reaper-93] DEBUG n.c.aws.batch.AwsBatchTaskHandler - [AWS BATCH] killing job=c02fd1ce-4464-4c1d-b0ea-e05e8afef929; response={}
Jul-14 16:10:17.176 [main] DEBUG nextflow.trace.ReportObserver - Execution report summary data:
... pipeline stats ...
Jul-14 16:10:17.332 [AWSBatch-reaper-48] DEBUG n.c.aws.batch.AwsBatchTaskHandler - [AWS BATCH] killing job=6f955d64-dc56-4af5-8905-61d458534386; response={}
Jul-14 16:10:17.542 [AWSBatch-reaper-64] DEBUG n.c.aws.batch.AwsBatchTaskHandler - [AWS BATCH] killing job=93c1e06e-5da6-48d3-9918-f7a75a8433cc; response={}
Jul-14 16:10:17.775 [AWSBatch-reaper-77] DEBUG n.c.aws.batch.AwsBatchTaskHandler - [AWS BATCH] killing job=6f54ad8d-8bc8-460c-a1b3-226a01a0ef34; response={}
Jul-14 16:10:17.950 [AWSBatch-reaper-143] DEBUG n.c.aws.batch.AwsBatchTaskHandler - [AWS BATCH] killing job=826d161d-a03b-4062-b863-25bdba0fb3c2; response={}
Jul-14 16:10:18.060 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Jul-14 16:10:18.060 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-amazon@1.0.5'
Jul-14 16:10:18.060 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-amazon
Jul-14 16:10:18.073 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

**Comment by pditommaso** [comment]
There's no timeout, I think just takes too much time because the AWS API allow allow to terminate one job at time.

**Comment by pditommaso** [comment]
I think the problem here is that the Nextflow shutdown process does not wait for the termination of the Batch job termination spooler.

**Comment by pditommaso** [comment]
Gotcha! You are right there's a  mins timeout! 

http://github.com/nextflow-io/nextflow/blob/1bac3f17b78d681a5967e0d2c43187eeca5b07a0/modules/nextflow/src/main/groovy/nextflow/processor/ParallelPollingMonitor.groovy#L102-L102

**Comment by pditommaso** [comment]
Increased to 1 hour, should be fine now.
