### ISSUE TITLE
When processes run when the expression is null

### ISSUE THREAD

**Issue by viklund** [nextflow-io/nextflow#217]
I was expecting the two processes below to behave similarly. Currently `just_var` will run but not `var_check`, I was expecting both to not run.

This is as simplified as I can make it, but it showed up for me when I tried to have a `when` expression be `params.run_program`, that is, taken directly from the command line.

main.nf:
```groovy
def other_stuff

process just_var {
    when other_stuff
    """
    echo
    """
}

process var_check {
    when other_stuff == true
    """
    echo
    """
}
```

**Comment by pditommaso** [comment]
OK, there are several (syntax) problems here: 

1) the clause `where` requires a [colon](https://www.nextflow.io/docs/latest/process.html#processes), so it must be `where:`
2) when using `where` it's *mandator* to start your script with a `script:` clause
3) the value of `other_stuff` is undefined. You should initialise to a value. 

Solving these, the `when` will work as expected.
