### ISSUE TITLE
OSX with Docker 20.10.7 touch: setting times of '.command.trace': No such file or directory

### ISSUE THREAD

**Issue by heuermh** [nextflow-io/nextflow#2170]
## Bug report 

See
https://github.com/nf-core/viralrecon/issues/208

### Expected behavior and actual behavior

(Give an brief description of the expected behavior 
and actual behavior)

### Steps to reproduce the problem

(Provide a test case that reproduce the problem either with a self-contained script or GitHub repository)

### Program output 

(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)

### Environment 

* Nextflow version: 21.04.1 build 5556
* Java version: openjdk version "11.0.10" 2021-01-19
* Operating system: OSX Big Sur (Darwin 20.5.0)
* Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

### Additional context

Failure does not appear to happen on older OSX and Docker versions.  Will update this issue with further details.

**Comment by pditommaso** [comment]
Think this can be closed, since it looks related to the Docker engine https://github.com/docker/for-mac/issues/5759

**Comment by abhi18av** [comment]
Closing this since the issue seems to be resolved by upgrading to the latest version  https://github.com/docker/for-mac/issues/5759#issuecomment-868822931

```
This works for me now after the most recent Docker Desktop update 

Version: 3.5.1 (66090)
Engine: 20.10.7
```

**Comment by heuermh** [comment]
Thank you, @abhi18av @pditommaso
