### ISSUE TITLE
fromFilePairs able to take in a closure from a channel

### ISSUE THREAD

**Issue by KyleStiers** [nextflow-io/nextflow#2178]
## New feature

I am working on a use-case that I can't seem to find a convenient solution to in nextflow and think it might be generally useful to people. It seems the ability of `fromFilePairs` to take a closure that is constructed from a dataflow variable of glob patterns would be very useful. I know `fromFilePairs` can take a list of glob patterns, but I can't find a trivial conversion from a channel to a list of glob patterns.

## Usage scenario 

For example in a situation where you have a known path to a results folder that has many subdirectories of FASTQ reads, you may want to filter those directories based on some criteria:

```
job_dir_ch
        .filter { it -> file(it.toAbsolutePath() + "/results").exists() == true}
        .set { dirs_to_process_ch }
```
## Suggest implementation 
This could then be super convenient for adding on a glob pattern and finding all of those reads:
```
job_dir_ch
        .filter { it -> file(it.toAbsolutePath() + "/results").exists() == true}
        .fromFilePairs { it -> file(it.toAbsolutePath() + "/results/**/*_R{1,2}*.fastq.gz")}
        .set { reads_to_process_ch }
```

If this is routine already, I apologize, but I have not found a good, nextflow-y solution.

**Comment by pditommaso** [comment]
Sorry for being late here, but `fromFilePairs` actually takes an optional closure that allows the use of custom grouping keys. Tho not sure it matches your expectation. See the docs  

https://www.nextflow.io/docs/latest/channel.html#fromfilepairs
