### ISSUE TITLE
Allow processes to inherit from another process

### ISSUE THREAD

**Issue by nh13** [nextflow-io/nextflow#2187]
## New feature

I would like for a `process` to inherit from another process or implement a "process interface" (i.e. trait).

## Usage scenario 

This would allow centralizing process boilerplate, for example directives like `tag`, `label`, `publishDir`, `container`, `conda`, and so on (see [`fastq` in` nf-core/rnaseq`](https://github.com/nf-core/rnaseq/blob/b3ff92bc54363faf17d820689a8e9074ffd99045/modules/nf-core/software/fastqc/main.nf#L8-L12) for boilerplate).  

## Suggest implementation 

I think conceptually this could be like [`traits`](http://docs.groovy-lang.org/next/html/documentation/core-traits.html) in the groovy language.

**Comment by nh13** [comment]
Still want this!

**Comment by nh13** [comment]
Still want this!

**Comment by bentsherman** [comment]
Hi @nh13 , I think you could implement this now with labels. Assign a label to a process, then put all of the common directives into that label:
```
process {
  withLabel 'foo' {
    // ...
  }
}
```

It seems like labels function like traits in Groovy.

**Comment by nh13** [comment]
@bentsherman thanks for the suggested solution.  Is there a way without having to use labels and configs? This relies upon convention rather than a feature of the DSL.

**Comment by bentsherman** [comment]
Not to my knowledge. Is there a reason why the labels approach doesn't work for you?

**Comment by nh13** [comment]
Its separates the process definition from the declaration of inheritance. This goes against almost very other programming language that has inheritance. And then it moves it to the config (away from the process definition), which is already complex enough and enables it by convention rather than syntax. We like to keep separate concerns separate, but here we have the same concern. Anyhow, the config files are getting extremely complex and their own language so it’s strongly prefer to have it built into the DSL syntax. Hopefully that’s opinionated enough, but I’ll close this issue as there is now a mechanism.
