### ISSUE TITLE
Collecting files from a "fromFilePairs" channel

### ISSUE THREAD

**Issue by hdzierz** [nextflow-io/nextflow#220]
Hi There,

I have a channel that has been initiated using the channel method fromFilePairs(). At the end of the pipe, I would like to collect all files from resulting channel further down the pipeline as a last step. 

Is there a simple way to achieve that using collectFile()? I saw a hint in the FAQ but found that solution looked like a workaround and difficult to implement. A collectFileFromPairs() operator would be great I think. 

Thanks

Helge

P.S.: Great tool BTW

**Comment by pditommaso** [comment]
Hi Helge, if I've understood well, you want to merge with `collectFile` all the file pairs having the same matching prefix. 

Supposing that you have a collection of files ending with the suffix `*-1.txt` or `*-2.txt` you can collect them with the following snippet. 

```
Channel
  .fromFilePairs('file-*-{1,2}.txt') 
  .flatMap { key, files -> [[key], files].combinations() }
  .collectFile()
```

To explain the steps: 
- `fromFilePairs` produces items in the for `[ key, [ file1, file ] ] `, that is a list of files nested in a another list 
- `collectFile` expect inputs in the form `[ key, file ]`
- thus in the middle you need the `flatMap` to transform the nested list into a combination of [key, file] pairs, and produce them as sole items. 

Hope it helps.

**Comment by pditommaso** [comment]
I'm closing this issue. If you need further help, feel free to comment below.
