### ISSUE TITLE
Sort file names after using groupTuple

### ISSUE THREAD

**Issue by zillurbmb51** [nextflow-io/nextflow#2206]
Hi, I have a similar issue https://github.com/nextflow-io/nextflow/issues/347 only have numbers in the file name.
The solution there:
`my_channel.groupTuple().map { chrom,bgen -> tuple( chrom, bgen.sort{it.name})}`
does not resolve the problem, because in my file name there are numbers existed. example: 
`[chr1, [chr1.step10.imputed.chunk0.bgen, chr1.step10.imputed.chunk1.bgen, chr1.step10.imputed.chunk2.bgen, chr1.step10.imputed.chunk3.bgen,.....]]`
After using 
`.map { chrom,bgen -> tuple( chrom, bgen.sort{it.name})}` it is giving me 
`[chr1, [chr1.step10.imputed.chunk0.bgen, chr1.step10.imputed.chunk1.bgen, chr1.step10.imputed.chunk10.bgen, chr1.step10.imputed.chunk11.bgen,.....]]` . As I understand, sorting order was `0,1,10,11,12,...` but I need, `0,1,2,3,4...` That means 

`[chr1, [chr1.step10.imputed.chunk0.bgen, chr1.step10.imputed.chunk1.bgen, chr1.step10.imputed.chunk2.bgen, chr1.step10.imputed.chunk3.bgen,.....]]` . How could I get that after using `groupTuple` ?

**Comment by abhi18av** [comment]
Hi @zillurbmb51 , for questions related to usage of Nextflow, please make use of the [discussions forum](https://github.com/nextflow-io/nextflow/discussions). The issues sections are used for bugs/feature request regarding Nextflow runtime. This is a new functionality of Github and similar to issues, but dedicated to only questions.
