### ISSUE TITLE
-r and -main-script flags are ignored

### ISSUE THREAD

**Issue by marcadella** [nextflow-io/nextflow#2210]
### Expected behavior and actual behavior

`nextflow run` flags `-r` and `-main-script` are not properly parsed.

### Steps to reproduce the problem

`nextflow run -main-script Autoget.nf -r other https://gitlab.com/uit-sfb/autoget-nextflow` prints `Remote resource not found: https://gitlab.com/api/v4/projects/uit-sfb%2Fautoget-nextflow/repository/files/main.nf?ref=master`

showing that both flags are ignored.

I also tried to have the two flags after the repo URL with the same result.

### Environment 

* Nextflow version: 21.04.1
* Java version: 11.0.11
* Operating system: Ubuntu 18.04.5
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by abhi18av** [comment]
Hi @marcadella 

Thanks for reporting this. I tried without the `-main-script` and `r` option and it seems the issue might be related to the gitlab URLs

```
N E X T F L O W  ~  version 21.04.1
Pulling uit-sfb/autoget-nextflow ...
Remote resource not found: https://gitlab.com/api/v4/projects/uit-sfb%2Fautoget-nextflow/repository/files/main.nf?ref=master
```

The `uit-sfb/autoget` ends up being parsed as `/uit-sfb%2Fautoget`

**Comment by abhi18av** [comment]
Perhaps not, since this is an expected behavior in the docs  🤔 

https://github.com/nextflow-io/nextflow/blob/1fab100259bf8e48fce3ec8bbeacb6d47d0672c2/modules/nextflow/src/test/groovy/nextflow/scm/GitlabRepositoryProviderTest.groovy#L109
