### ISSUE TITLE
Are Nextflow's comments the same as Groovy's?

### ISSUE THREAD

**Issue by kojix2** [nextflow-io/nextflow#2217]
Hello, Nextflow developers.

I want to add Nextflow to [tokei](https://github.com/XAMPPRocky/tokei/). 
Tokei is a command line tool that counts the number of lines of code in a directory by programming language.　Currently, tokei cannot detect scripts written in the Nextflow language. In order for tokei to detect the code of the Nextflow language, you need to edit [language.json](https://github.com/XAMPPRocky/tokei/blob/master/languages.json). In language.json, you need to specify the comment idiom and file extension for Nextflow.

```json
    "Groovy": {
      "line_comment": ["//"],
      "multi_line_comments": [["/*", "*/"]],
      "quotes": [["\\\"", "\\\""]],
      "extensions": ["groovy", "grt", "gtpl", "gvy"]
    },
```

Copy and paste the Groovy entry and edit it.

```nextflow
    "Nextflow": {
      "line_comment": ["//"],
      "multi_line_comments": [["/*", "*/"]],
      "quotes": [["\\\"", "\\\""]],
      "extensions": ["nextflow", "nf"]
    },
```

Could you please confirm that this looks OK?

**Comment by kojix2** [comment]
https://github.com/XAMPPRocky/tokei/pull/799

**Comment by pditommaso** [comment]
Yes, that's fine. Not sure however about `quotes`? are that expected to be string quotes? In nextflow (and thefore groovy) can be both `'` and `"` include triple `'''` and `"""`

**Comment by kojix2** [comment]
This was just recently merged into tokei.

```
"""

"""
```

↑ is also recognized as a Nextflow script, but it is acceptable....
