### ISSUE TITLE
Canned ACL's not used

### ISSUE THREAD

**Issue by birnbera** [nextflow-io/nextflow#2218]
### Expected behavior and actual behavior

According to the [documentation](https://www.nextflow.io/docs/latest/config.html#config-aws) the AWS client can be configured to upload files with a canned ACL, such as `BucketOwnerFullControl`. Using a configuration with:

```nextflow
aws {
    client {
        acl = 'BucketOwnerFullControl'
    }
}
```

The files are not written to the destination using the specified canned ACL. 

### Program output 

Nextflow is picking up the settings, however it seems they are not being applied.

```log
Jul-12 22:52:48.669 [main] DEBUG nextflow.file.FileHelper - AWS S3 config details: {secret_key=######.., acl=BucketOwnerFullControl, region=us-east-1, access_key=######..}
```

### Environment 

* Nextflow version: `21.04.1` 
* Java version: `OpenJDK 11.0.8_10`
* Operating system: Centos 7
* Bash version: `4.2.46(2)`

**Comment by jordeu** [comment]
@birnbera I think that there is an error at documentation side and the correct `client` attribute is `s3Acl` instead of `acl`.

Please try with this configuration and let us known if this fixes the issue:
```
aws {
    client {
        s3Acl = 'BucketOwnerFullControl'
    }
}
```

**Comment by jordeu** [comment]
@birnbera it's implemented at `nextflow-s3fs` repo, a Nextflow dependency. Check this commit for more details: https://github.com/nextflow-io/nextflow-s3fs/commit/f3b676919b51de684a0442614be9d293bb2f6c0f
