### ISSUE TITLE
Nested symlinks are not correctly mounted by Docker containers

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#222]
I've run into a confusing issue where a task fails saying that the specified input files are missing, but when I look in the work dir, they're there.  This is running on a local drive, so it's not an NFS issue.  This task runs in a docker container.  Importantly, this task  After much digging, I've come to the conclusion that the generated docker mount points that account for the both symlinked input to the task and the task itself are too parsimonious.  If the input symlinks share the same hash prefix as the current working directory, then the symlinks don't resolve when the container runs. Here's an example:

Current dir is `/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe/1108fdf113d3d4f71d9bf45febcc99` and the symlinks are as follows:

```
lrwxrwxrwx. 1 msmoot employees 150 Sep 15 16:32 A0A0B6YBN9.fa -> /local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe/df9e35bd45aece010c96e000633bd2/genewise_inputs/we03730_nuc_v150325_PM_chr_1/A0A0B6YBN9.fa
lrwxrwxrwx. 1 msmoot employees 151 Sep 15 16:32 we03730_nuc_v150325_PM_chr_1_1505000-1506500-A0A0B6YBN9.gff -> /local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe/df9e35bd45aece010c96e000633bd2/we03730_nuc_v150325_PM_chr_1_1505000-1506500-A0A0B6YBN9.gff
-rw-r--r--. 1 root   root        0 Sep 15 16:33 we03730_nuc_v150325_PM_chr_1_1505000-1506500-A0A0B6YBN9.gff.fa
lrwxrwxrwx. 1 msmoot employees 184 Sep 15 16:32 we03730_nuc_v150325_PM_chr_1_1505000-1506500.fa -> /local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe/df9e35bd45aece010c96e000633bd2/genewise_inputs/we03730_nuc_v150325_PM_chr_1/we03730_nuc_v150325_PM_chr_1_1505000-1506500.fa
```

The important thing to notice is that both the current working dir and directory where the inputs actually live are both in the `/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe` directory.

Now looking at .command.run, I see that the docker mounts are set up as: `-v /local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe:/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe -v "$PWD":"$PWD" -w "$PWD"` which appears to be the nearest common directory of the current dir and all the inputs.

When I execute `bash .command.run` it will fail. If I edit the mount points in .command.run to omit the "/fe" prefix like this: `-v /local_scratch/msmoot/nextflow_eukaryotic_annotation/work:/local_scratch/msmoot/nextflow_eukaryotic_annotation/work -v "$PWD":"$PWD" -w "$PWD"` then the command works.  Likewise, if I simply add `-v /local_scratch/msmoot/nextflow_eukaryotic_annotation/work:/local_scratch/msmoot/nextflow_eukaryotic_annotation/work` to .command.run, then things work.

This seems to be the origin of the problem:  https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/container/DockerBuilder.groovy#L265.  I'm not sure PathTrie is behaving correctly, given that workdir is added here: https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy#L586. It seems that workdir should be the longest _common_ dir.

**Comment by mes5k** [comment]
Here's the .command.run in question.  Let me know if you need anything else.


[bad.command.run.txt](https://github.com/nextflow-io/nextflow/files/481285/bad.command.run.txt)

**Comment by pditommaso** [comment]
The work path is: 

```
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe/1108fdf113d3d4f71d9bf45febcc99
```

While the file are: 

```
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe/df9e35bd45aece010c96e000633bd2/we03730_nuc_v150325_PM_chr_1_1505000-1506500-A0A0B6YBN9.gff 
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe/df9e35bd45aece010c96e000633bd2/genewise_inputs/we03730_nuc_v150325_PM_chr_1/we03730_nuc_v150325_PM_chr_1_1505000-1506500.fa 
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe/df9e35bd45aece010c96e000633bd2/genewise_inputs/we03730_nuc_v150325_PM_chr_1/A0A0B6YBN9.fa
```

Thus the having the following mount should be fine: 
```
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe
```

Indeed, I tried to recreate the same directories structure and it works. 

The error message you reported on gitter was 

```
 No such file or directory: 'we03730_nuc_v150325_PM_chr_2_186000-189000.fa'
```

However I see that only the symlinks for chr1 files are created. What is referencing the file in error message ?

**Comment by mes5k** [comment]
Yes, it certainly _seems_ like it should be working and it _seems_ like 
```
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe
```
should work, but for reasons I don't understand, it doesn't.

To clarify the error message, the error message for the work dir
```
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe/1108fdf113d3d4f71d9bf45febcc9
```
is
```
IOError: [Errno 2] No such file or directory: 'we03730_nuc_v150325_PM_chr_1_1505000-1506500.fa'
```
So the files in the work dir, the files referenced in the .command.run, and the error message are all talking about the same thing.  I have multiple examples of this error that I've been examining, so I think I copy/pasted the wrong error above.

**Comment by mes5k** [comment]
Ah, I think I've figured out why it's failing.

The directory
```
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe/df9e35bd45aece010c96e000633bd2/genewise_inputs
```
which is part of the path to the chromosome file is actually a symlink to:
```
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/4a/36bc454cc2161d35039522274d79b2/genewise_inputs/
```
So 
```
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/4a
```
isn't captured by
```
/local_scratch/msmoot/nextflow_eukaryotic_annotation/work/fe
```

Soooo, I'm not really sure this is a bug - all of the code is functioning as expected, but there's an edge case when the file being referenced contains a symlink, which points to a directory that isn't captured in the paths fed to PathTrie.

**Comment by pditommaso** [comment]
Bingo. Difficult to find an optimal solution here.  Each path should be resolved to the real one, but I think it would introduce an overhead too high. 

Another approach could be to add the top work-dir in any case, but would a partial solution. 

Anyway can you find a workaround for your problem? using for example a hardlink instead of a symlink ?

**Comment by mes5k** [comment]
Yes, I can find a workaround.  Adding the workdir regardless might still be a good idea, but I agree that it would only partially solve this problem.  Feel free to close this ticket or use it as a feature request to add workdir, whichever you prefer!   Thanks!
