### ISSUE TITLE
publishDir enabled as a dynamic directive

### ISSUE THREAD

**Issue by rcannood** [nextflow-io/nextflow#2220]
## Bug report 

I want to create a process for which I can use a dynamic directive to determine whether to publish the output or not. 

```groovy
nextflow.enable.dsl=2

process test_process {
  publishDir "output/$id", mode: 'copy', overwrite: true, enabled: { publish } // <--- dynamic
  input:
    tuple val(id), val(publish)
  output:
    tuple val(id), path("output.txt")
  script:
    """
    echo $id > output.txt
    """
}

workflow {
  Channel.fromList([ ["foo", false], ["bar", true] ])
    | test_process
}
```

### Expected behavior and actual behavior
For the example above, I would expect only `output/bar` to be created. The script above creates both, however:

```bash
$ tree output
output
├── bar
│   └── output.txt
└── foo
    └── output.txt
```

### Steps to reproduce the problem

Save the example shown above as `main.nf` and run `NXF_VER=21.04.1 nextflow run main.nf`.

### Program output 

```
$ NXF_VER=21.04.1 nextflow run main.nf 
N E X T F L O W  ~  version 21.04.1
Launching `main.nf` [ecstatic_turing] - revision: 1ad5fd0bcc
executor >  local (2)
[a6/489402] process > test_process (2) [100%] 2 of 2 ✔
```

### Environment 

* Nextflow version: 21.04.1
* Java version: openjdk version "11.0.11" 2021-04-20
* Operating system: Fedora 33
* Bash version: GNU bash, version 5.0.17

**Comment by pditommaso** [comment]
The expected syntax consists of using an interpolated string value, which is implicitly converted to closure under the hood. 

However, it turns out the string value `"true"` and `"false"` are not correctly converted to boolean values. I've uploaded a patch to solve this problem 651835d2d.

**Comment by rcannood** [comment]
Thanks, this solves the unexpected behaviour to a large extent!
