### ISSUE TITLE
[Operators] view() operator does not print in the single line when newLine: false

### ISSUE THREAD

**Issue by kerimoff** [nextflow-io/nextflow#2224]
## Bug report 

View operator does not print items in the channel in the single line, instead prints each item in a new line (as it is in the default newLine: true) 

### Expected behavior and actual behavior

when I do 
`Channel.from(1,2,3).view(newLine: false)`

I expect something like 
1 2 3 (or 1,2,3)

what actually happens is 
1
2
3

### Steps to reproduce the problem

Run the following code snippet with the provided environment 
`Channel.from(1,2,3).view(newLine: false)`

### Environment 

  Version: 21.04.0 build 5552
  Created: 02-05-2021 16:22 UTC (19:22 EEST)
  System: Mac OS X 10.15.7
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.9.1+1-LTS
  Encoding: UTF-8 (UTF-8)

also tested on 

  Version: 21.04.1 build 5556
  Created: 14-05-2021 15:20 UTC (18:20 EEST)
  System: Linux 3.10.0-1127.19.1.el7.x86_64
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.2+9
  Encoding: UTF-8 (ANSI_X3.4-1968)

### Additional context

In documentation it is noted that it should be possible https://www.nextflow.io/docs/latest/operator.html?highlight=newline#view

**Comment by pditommaso** [comment]
This is a tricky side effect of the interactive logging that only handles lines. if you add the run option `-ansi-log false` it works as expected.

**Comment by pditommaso** [comment]
Marking as a known issue and closing it. Feel free to comment or reopen if needed.
