### ISSUE TITLE
Conda create environment from yml doesn't report errors

### ISSUE THREAD

**Issue by mvanins** [nextflow-io/nextflow#2227]
### Expected behavior and actual behavior

I have been encountering corruption in my local conda cache (this is of course not Nextflow's fault). When I create a conda environment manually, conda displays a "SafetyError", indicating that one of the packages is corrupted. For example:

```
$ conda env create --prefix ./testenv -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: \
SafetyError: The package for kernel-headers_linux-64 located at /mydir/miniconda3/pkgs/kernel-headers_linux-64-2.6.32-h77966d4_13
appears to be corrupted. The path 'x86_64-conda-linux-gnu/sysroot/usr/include/asm-generic/auxvec.h'
has an incorrect size.
  reported size: 218 bytes
  actual size: 0 bytes
```

When Nextflow creates this same environment when executing a pipeline, it proceeds without warning and ultimately the processes fail when they encounter the corrupted package.

It would be helpful to either include these warnings so they can be further investigated as part of the debugging process.

### Environment 

* Nextflow version: 21.04.1 build 5556
* Java version: Groovy 3.0.7 on Java HotSpot(TM) 64-Bit Server VM 12.0.2+10
* Operating system: Linux 3.10.0-1062.1.2.el7.x86_64
* Bash version: GNU bash, version 4.2.46(2)-release

Thanks 😄

**Comment by abhi18av** [comment]
Hi @mvanins ,

Could you please confirm whether `conda` raises any standard error code when it fails?

**Comment by mvanins** [comment]
Hi,

No, `conda` does not raise an error code when this error occurs. I understand that this is probably the reason it's not caught by Nextflow.
