### ISSUE TITLE
Toward a Debian package for nextflow

### ISSUE THREAD

**Issue by pgrt** [nextflow-io/nextflow#2228]
Hi Paolo,

I am working in the Debian-med team, and we aim at packaging several software that are useful for medical care in research.

We would like to package nextflow. Indeed, I have been working on this during my spare cycles in the last few weeks, and I wanted to let you know about my progress in a few bullet points. Maybe you will have some advice based on what is below (I also remember you were in touch with a common knowledge of us in the end of May and that you told him there were some problematic feature for me that you were going to deprecate anyway; I would be glad to hear a bit about it from you):
- my packaging work is based on nextflow 21.04.1;
- I am meeting a lot of groovy syntax issues because in Debian we currently have Groovy 2.24.1 only. Could you give me a rough idea of the range of Groovy versions that should work with nextflow, in your opinion?
- Also I see you are relying on kryo 2.24. In Debian we have packaged 2.21, and we got stuck there because some software (e.g. gradle!) rely on a version of kryo that is older than the many ABI changes that were brought by version 5 of kryo. Do you think I could successfully build and run nextflow against kryo 5?
- The SDKs of Amazon, Azur and Ignite are not in Debian as of today. I expect they deserve a huge packaging effort. Do you think I can build nextflow without the nf-amazon, nf-azure and nf-ignite plugins?

Thanks a lot for reading me, and for your answers if time permits!

Warm greetings,

-- 
Pierre

**Comment by pditommaso** [comment]
Hi Pierre, it depends on what you want to achieve. Nextflow is essentially a [Bash script](https://github.com/nextflow-io/nextflow/blob/65e2a4d056d8514ae427ac6992c6f06cc13d1271/nextflow#L1-L1) that pulls all required (Java) libraries. 

What's your requirement?

**Comment by pgrt** [comment]
Hi Paolo,

Thanks for your quick answer. This is true, I should give details about my aim.

When nextflow (the Bash script) is launched, the nextflow framework (a jar) and dependencies are drawn from the Internet.

My wish is to be able to build the framework jar and to ship it in a Debian package together with the Bash script, so that users would launch the Bash script (as they are used to) and it would call the framework that would be installed in /usr/share/java or maybe in a subdir of /usr/share/nextflow.
Moreover, the dependencies would not be downloaded from the Internet, but instead the Debian packaging tool would get them from the Debian archive after they have been properly listed in Debian control files (this is my work).

This is the Debian way of doing things, in order to have a consistent set of binaries that were all built from Debian packages, so that we can guarantee to the users that all parts of the software they run is free and that they can consult all the sources of what runs on their computers.
Don't get me wrong, I'm not suggesting there is anything insane with the current way nextflow runs and downloads dependencies. I am just explaining the Debian packaging philosophy.

Thus I need to be able to build the framework jar and to ensure Debian-packaged dependencies of nextflow are compatible with it, although some of them differ from the ones you used (hence my questions in the first post).

I hope this is clear now; else don't hesitate to tell me, and any case, thanks for your attention and help!

Best wishes,

-- 
Pierre

**Comment by pditommaso** [comment]
The nextflow makefile container a `pack` command that in some extent does what you are suggesting, that's a self-contained executable bundling all deps into a single file. 

https://github.com/nextflow-io/nextflow/blob/65e2a4d056d8514ae427ac6992c6f06cc13d1271/Makefile#L97-L98

Could this help?

**Comment by pgrt** [comment]
Hello,

Thanks for your new answer.

In fact, what I want to do is slightly different. I indeed want to ship a jar with the nextflow framework but I need to have the dependencies out of it, and to have them installed from the Debian repository.
The nextflow Debian package would be quite light as it would contain the framework jar and the Bash script (basically), and it would depend on other Debian packages that would contain the dependencies and would be installed on-the-fly when the user installs nextflow through the Debian package manager.

And because the currently Debian-packaged versions of some dependencies (say, kryo and the groovy language itself!) differs from the versions that you are depending on when nextflow seeks them from the Internet, I would like to know to what extent the discrepancies in the version numbers are problematic. This is the reason for my questions in the first post of this conversation.

My concern, when I ask those questions, is thus to:
- be able to build the framework jar from dependencies of which version does not match the ones you used for your development;
- ensure the so-build framework jar will consistently run with the above-said dependencies.

Thanks again and have a good day,

-- 
Pierre

**Comment by pditommaso** [comment]
This sounds me a bloodbath .. 😅 How it's the build is managed with other Java-based projects?

**Comment by pgrt** [comment]
Well, I can't say you're wrong, by some aspects :) Admittedly this approach can be cumbersome.

We do the same with other Java-based projects: typically they are made of the project's classes and the jars of the dependencies are bundled aside. We first remove all the jars of the dependencies and then indicate the paths at which they should be found on a Debian system. If a dependency is not in Debian, we package it. For instance, I have recently packaged grengine, capsule, capsule-maven and pf4j in order to prepare the packaging of nextflow.

As you said and as I admit, this can be a lot of work but this guarantees there is no code duplication in Debian and every jar that is used by Debian-packaged programs is built from source on our servers.

I hope you get the sense of it... but yeah, it can be a tough job!

**Comment by pditommaso** [comment]
Yeah, I know about Debian Med philosophy. I've just added to the nextlfow gradle build the ability to create the distribution archive, which essentially creates a zip file with this content 

```
 nextflow-21.06.0-edge
    ├── bin
    │   ├── nextflow
    │   └── nextflow.bat
    └── lib
        ├── JavaEWAH-1.1.6.jar
        ├── activation-1.1.1.jar
        ├── animal-sniffer-annotations-1.14.jar
        ├── checker-compat-qual-2.0.0.jar
        ├── commons-codec-1.10.jar
        ├── commons-lang-2.6.jar
        ├── error_prone_annotations-2.1.3.jar
        ├── gpars-1.2.1.jar
        ├── grengine-1.3.0.jar
        ├── groovy-3.0.8.jar
        ├── groovy-json-3.0.8.jar
        ├── groovy-nio-3.0.8.jar
        ├── groovy-templates-3.0.8.jar
        ├── groovy-xml-3.0.8.jar
        ├── gson-2.2.4.jar
        ├── guava-24.1.1-jre.jar
        ├── j2objc-annotations-1.1.jar
        ├── java-semver-0.9.0.jar
        ├── jcl-over-slf4j-1.7.25.jar
        ├── jcommander-1.35.jar
        ├── jline-2.9.jar
        ├── jsch-0.1.54.jar
        ├── jsoup-1.11.2.jar
        ├── jsr166y-1.7.0.jar
        ├── jsr305-1.3.9.jar
        ├── jul-to-slf4j-1.7.25.jar
        ├── jzlib-1.1.1.jar
        ├── kryo-2.24.0.jar
        ├── leveldb-0.12.jar
        ├── leveldb-api-0.12.jar
        ├── log4j-over-slf4j-1.7.25.jar
        ├── logback-classic-1.1.11.jar
        ├── logback-core-1.1.11.jar
        ├── mail-1.4.7.jar
        ├── multiverse-core-0.7.0.jar
        ├── nextflow-21.06.0-edge.jar
        ├── nf-commons-21.06.0-edge.jar
        ├── nf-httpfs-21.06.0-edge.jar
        ├── objenesis-2.1.jar
        ├── org.eclipse.jgit-5.2.1.201812262042-r.jar
        ├── pf4j-3.4.1.jar
        ├── pf4j-update-2.3.0.jar
        ├── slf4j-api-1.7.25.jar
        └── snakeyaml-1.28.jar

```

That's the launcher file `bin/nextflow` and all required jar files. I think this can be a good start for your odissey. 

Some caveats apply: 
* the `bin/nextflow` is not the same of the stock Nextflow launcher `nextflow` file. Thefore some functionalities can be affected 
* this distribution does not include all features provided via the plugins system i.e. support for cloud and tower. 


However, it should be possible to solve the above limitation hacking in the build script, to make it including the missing components. we can look into this into a second phase, provide the above could be a starting point for your needs. 


To create to above distribution use the command below in the project build directory: 

```
./gradlew nextflow:distZip
```

Then check the file `./modules/nextflow/build/distributions/nextflow-*.zip `

**Comment by pgrt** [comment]
Hello,

Thanks for adding this possibility and for the explanation! For sure I will have a look into this.

I will have you informed of my progress...

Have a good day and thanks again,

-- 
Pierre
