### ISSUE TITLE
AWS Batch - Publishing a large output file (1.2TB) to S3 fails with java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by astatham** [nextflow-io/nextflow#2230]
## Bug report 

When running a workflow on AWS Batch, publishing a large output file (1.2TB) to S3 fails with java.lang.OutOfMemoryError

### Expected behavior and actual behavior

Expected behavior - the file is copied from its S3 working directory to its publishDir
Actual behavior - after a very long time (up to 24 hours) the transfer fails with an OOM error

### Steps to reproduce the problem

Minimal workflow `publish_file.nf`:

```
#!/usr/bin/env nextflow

in_file = file(params.in_file)

process test_publish {
    publishDir params.outdir, mode: params.publish_mode
    container 'ubuntu:20.04'
    label "${params.big_merge_label}"

    input:
    file(in_file) from in_file

    output:
    file "${in_file}.out"

    """
    mv ${in_file} ${in_file}.out
    """
}
```

Nextflow config `minimal.config`:

```
process.shell = ['/bin/bash', '-ueo','pipefail']
process.executor = 'awsbatch'
params.executor = 'awsbatch'
params.publish_mode = 'copy'
aws.batch.cliPath = '/home/ec2-user/miniconda/bin/aws'
aws.region='us-east-1'

process {
    memory = { 10.GB * task.attempt }
    queue = 'dev-queue'
}
```

Invoked from this script `run.sh`:

```
#!/bin/bash -e
export NXF_ANSI_LOG=false
export NXF_OPTS='-Xms512M -Xmx10G'
export OUTDIR=s3://my-s3-bucket/20210713_publish_large_file_test

nextflow -C minimal.config \
    run publish_file.nf \
    --in_file=s3://my-s3-bucket/very_large.bam \
    --executor=awsbatch \
    --outdir=${OUTDIR}/output \
    -w ${OUTDIR}/scratch \
    -resume -with-trace -with-timeline -with-dag -with-report 2>&1
cd ..
```

### Program output 

stdout+stderr:
```
N E X T F L O W  ~  version 21.04.2
Launching `publish_file.nf` [cranky_euler] - revision: 3973236f95
WARN: It appears you have never run this project before -- Option `-resume` is ignored
[fd/0cd25f] Submitted process > test_publish
Waiting files transfer to complete (1 files)
Waiting files transfer to complete (1 files)
Waiting files transfer to complete (1 files)
...
many hours later
...
Waiting files transfer to complete (1 files)
Waiting files transfer to complete (1 files)
Waiting files transfer to complete (1 files)
```

Tail end of `.nextflow.log`:
```
~> TaskHandler[id: 1; name: test_publish; status: RUNNING; exit: -; error: -; workDir: s3://my-s3-bucket/20210713_publish_large_file_test/scratch/fd/0cd25f73eb90292bd2f8ae9bad0db4]
Jul-18 15:29:11.661 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: test_publish; status: COMPLETED; exit: 0; error: -; workDir:s3://my-s3-bucket/20210713_publish_large_file_test/scratch/fd/0cd25f73eb90292bd2f8ae9bad0db4]
Jul-18 15:29:11.755 [Task monitor] DEBUG nextflow.plugin.PluginsFacade - Plugin 'start' is not required in self-contained mode -- ignoring it for plugin: nf-amazon
Jul-18 15:29:11.755 [Task monitor] DEBUG nextflow.file.FileHelper - Started plugin 'nf-amazon' required to handle file: s3://my-s3-bucket/20210713_publish_large_file_test/output
Jul-18 15:29:11.786 [Task monitor] DEBUG n.util.BlockingThreadExecutorFactory - Thread pool name=FileTransfer; maxThreads=144; maxQueueSize=432; keepAlive=1m
Jul-18 15:29:11.794 [main] DEBUG nextflow.Session - Session await > all process finished
Jul-18 15:29:11.870 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jul-18 15:29:16.885 [main] INFO  nextflow.Session - Waiting files transfer to complete (1 files)
Jul-18 15:30:16.886 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
...
many hours later
...
Jul-19 20:10:08.642 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Jul-19 20:11:22.889 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Jul-19 20:16:20.532 [main] DEBUG nextflow.Session - Session aborted -- Cause: Java heap space
Jul-19 20:19:24.319 [main] DEBUG nextflow.Session - Unexpected error while aborting execution
java.lang.OutOfMemoryError: Java heap space
Jul-19 20:19:29.681 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.OutOfMemoryError: Java heap space
```

I have tried increasing heap space with `export NXF_OPTS='-Xms512M -Xmx150G'` and it still fails

### Environment 

* Nextflow version: 21.04.2
* Java version: openjdk version "11.0.6" 2020-01-14
* Operating system: Debian 9 docker container running on Amazon Linux 2
* Bash version: 4.4.12(1)-release

### Additional context

We are running nextflow inside a debian 9 based docker image on an Amazon Linux 2 host on EC2 in the same region as the S3 bucket and where the Batch jobs are being run.

**Comment by abhi18av** [comment]
Hi @astatham,

That's a huge file :) 

Anyways, perhaps you might want to try ` _JAVA_OPTIONS` , to pass these options directly to the JVM.

```
export _JAVA_OPTIONS="-Xmx2G -XX:+UseZGC"   // customize before using

```

**Comment by astatham** [comment]
Thanks for the suggestion - I reran with the following options (which nextflow noted at startup) and after 26h have the same error
```
export _JAVA_OPTIONS="-Xmx15G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC"
export NXF_OPTS='-Xms512M -Xmx15G'
```

```
Jul-21 17:42:32.917 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Jul-21 17:43:37.253 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Jul-21 17:43:59.723 [FileTransfer-thread-1] WARN  nextflow.processor.PublishDir - Failed to publish file: /my-s3-bucket/20210713_publish_large_file_test/big_10g_update/scratch/fd/0cd25f73eb90292bd2f8ae9bad0db4/very_large.bam.out; to: /my-s3-bucket/20210713_publish_large_file_test/big_10g_update/output/very_large.bam.out [copy] -- See log file for details
java.lang.OutOfMemoryError: Java heap space
```

Main thing I noticed while monitoring in `htop` was javas VIRT went up to ~17TB and RES went up to ~50GB

**Comment by abhi18av** [comment]
That's quite strange, would it be possible for you to share the `.nextflow.log` file?

**Comment by astatham** [comment]
Sure thing - here's a `.nextflow.log` (with real s3 paths & filenames obscured) - 
[sanitised.nextflow.log](https://github.com/nextflow-io/nextflow/files/6861117/sanitised.nextflow.log)

I'll try those aws.client settings and let you know the outcome, thanks!

**Comment by abhi18av** [comment]
Wow, the log is full of `Jul-21 17:42:32.917 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)` !

In case that the suggestion regarding `aws` client doesn't work, I'd really recommend that you give a look to other file system such as `FSx lustre` or `EFS`. There's also `Fusion mount` for S3 as mentioned in [points-11, 14 and 15 of Nextflow Tower docs.](https://help.tower.nf/compute-envs/aws-batch/)

For more information about performance of various storage systems on AWS you can refer [this blog](https://seqera.io/blog/optimizing-workflows-with-nextflow/) post.

**Comment by astatham** [comment]
Hi - the `aws.client` settings did not fix the issue, but I did see a new error that is not java heap related (and confirmed that the output file was not published)

```
Jul-23 21:05:48.653 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Jul-23 21:06:48.660 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Jul-23 21:07:48.666 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Jul-23 21:08:28.673 [main] WARN  nextflow.Session - Exiting before FileTransfer thread pool complete -- Some files maybe lost
Jul-23 21:08:28.678 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=1; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=5ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
``

@abhi18av - are `aws.client` settings used in the publishing to s3 part of nextflow? I know they are used inside a jobs `.command.run` when uploading results to s3 (this part is working fine with my 1.2TB file) - are these setting also used in the `nextflow-s3fs` library when publishing to s3 `publishDir`s?

I'll also have a look at those alternative filesystems, thanks.

**Comment by abhi18av** [comment]
> are `aws.client` settings used in the publishing to s3 part of nextflow? 

Yes, these settings are used to tweak the behavior of the underslying `aws` cli through it's native options.

> are these setting also used in the `nextflow-s3fs` library when publishing to s3 `publishDir`s?

@astatham , unfortunately, I don't have a deeper idea about that 😶

**Comment by astatham** [comment]
Hi - I'll try to clarify exactly where the issue is occurring:

* My process that has a 1.2TB output file successfully completed when running on batch, including copying the 1.2TB file to the `work-dir` on S3 (ie  `aws s3 cp` calls in the jobs `.command.run`) - no problem here at all
* Publishing that same output file w/ the [publishDir](https://www.nextflow.io/docs/latest/process.html#publishdir) directive to the output location also on S3 (same bucket) takes >26 hours then fails with a java heap error; I believe this is performed using via the `nextflow-s3fs` library

Does that help narrow down where to look next?

**Comment by blajoie** [comment]
Seeing the same phenotype with a ~100g file.
Using inputs/outputs in the ~80G range seem to work AOK.  Something related to multipart?

It seems to just continue on forever.
`Aug-22 22:04:42.144 [main] INFO  nextflow.Nextflow - -[wholegenomesequencing] Pipeline completed successfully-
Aug-22 22:04:47.151 [main] INFO  nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:05:47.153 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:06:47.155 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:07:47.157 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:08:47.159 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:09:47.162 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:10:47.164 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:11:47.166 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:12:47.168 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:13:47.170 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:14:47.173 [main] INFO  nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:15:47.175 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:16:47.177 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:17:47.179 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:18:47.181 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:19:47.184 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:20:47.186 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:21:47.188 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:22:47.190 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:23:47.192 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:24:47.194 [main] INFO  nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:25:47.197 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:26:47.199 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:27:47.201 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:28:47.203 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:29:47.205 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:30:47.207 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:31:47.210 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:32:47.212 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:33:47.214 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:34:47.216 [main] INFO  nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:35:47.218 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:36:47.220 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:37:47.222 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:38:47.224 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:39:47.226 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:40:47.229 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:41:47.231 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:42:47.233 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:43:47.235 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:44:47.237 [main] INFO  nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:45:47.239 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:46:47.241 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:47:47.243 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:48:47.246 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:49:47.248 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:50:47.250 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:51:47.252 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:52:47.254 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:53:47.256 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:54:47.258 [main] INFO  nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:55:47.260 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:56:47.263 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:57:47.265 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:58:47.267 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)
Aug-22 22:59:47.269 [main] DEBUG nextflow.Session - Waiting files transfer to complete (1 files)`

**Comment by blajoie** [comment]
@abhi18av - I think you will need to increase the aws multipart chunk size.
https://nfcore.slack.com/archives/CE6SDBX2A/p1629672433372600

The suggest conf below, sets chunk size to 10MB * 10000 chunks = 100G limit.
`aws.client.uploadMaxThreads = 4
aws.client.uploadChunkSize = 10485760`
(assuming the unit is bytes)

https://github.com/nextflow-io/nextflow/blob/8ec33b04dd3d9f30d98c36ecc68a33071991d493/docs/config.rst

https://github.com/nextflow-io/nextflow/blob/73899f3b7967f3bd9bc393749a80ce893368a28e/modules/nf-commons/src/test/nextflow/GlobalTest.groovy#L105

If you need 1.2TB, then try setting to ~150Mb per chunk?  Ideally NF would dynamically set this based upon the file it is uploading.

**Comment by abhi18av** [comment]
I think that it might be worth, trying to reproduce it with https://github.com/nextflow-io/nextflow/releases/tag/v21.12.1-edge , the latest edge release contains refactored code for improving the download behavior.

For further information, please refer https://github.com/nextflow-io/nextflow/commit/b7c262de30f17db62ab40d10bd88945ea9239a70

**Comment by blajoie** [comment]
Still seeing the same issue, perhaps the default chunk size should be increased?  100G is not all that uncommon in informatics?

**Comment by abhi18av** [comment]
Quick update, my esteemed colleague @jorgeaguileraseqera  is working on improving the s3 interactions and we would be happy if you could please provide feedback once the changes are releases.
