### ISSUE TITLE
How to get the path of the nf script that is running?

### ISSUE THREAD

**Issue by pwwang** [nextflow-io/nextflow#224]
`getClass().protectionDomain.codeSource.location.path` doesn't work, it returns `/groovy/shell`.
Is there anyway to get from params? The first element of arguments should be the path.

**Comment by pditommaso** [comment]
Use the implicit variable `workflow.scriptFile`. 

https://www.nextflow.io/docs/latest/metadata.html#runtime-metadata

**Comment by pwwang** [comment]
Great thx. @pditommaso
