### ISSUE TITLE
moduleDir is not mounted into docker containers

### ISSUE THREAD

**Issue by grst** [nextflow-io/nextflow#2240]
## Bug report 

I want to use `$moduleDir` to obtain static assets or scripts related to a module (See also #1798). 

### Expected behavior and actual behavior

Actual: `$moduleDir` does not get mounted into the docker container. 
Expected: `$moduleDir` gets mounted. 

### Steps to reproduce the problem

https://github.com/grst/nextflow-module-dir-mounts

### Program output 

[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/6873556/nextflow.log.txt)

```
N E X T F L O W  ~  version 21.04.0
Launching `main.nf` [hungry_galileo] - revision: e29acdc967
WARN: Access to undefined parameter `enable_conda` -- Initialise it to a default value eg. `params.enable_conda = some_value`
executor >  local (1)
[05/097b54] process > CUSTOM_SCRIPT [100%] 1 of 1, failed: 1 ✘
Error executing process > 'CUSTOM_SCRIPT'

Caused by:
  Process `CUSTOM_SCRIPT` terminated with an error exit status (1)

Command executed:

  /home/sturm/projects/2021/nextflow-issue-1798/workflow/./modules/custom_script/bin/hello.py

Command exit status:
  1

Command output:
  (empty)

Command error:
  .command.sh: line 2: /home/sturm/projects/2021/nextflow-issue-1798/workflow/./modules/custom_script/bin/hello.py: No such file or directory

Work dir:
  /home/sturm/projects/2021/nextflow-issue-1798/workflow/work/05/097b540d532b94c32ced2431b86d19

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### Environment 

* Nextflow version: `21.04.0 build 5552`
* Java version: `openjdk version "11.0.8-internal" 2020-07-14`
* Operating system: arch linux
* Bash version: `GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)`

### Additional context

It does work with singularity, but I suppose only because it mounts my entire home directory already anyway.

**Comment by grst** [comment]
Even with the `template` feature working now for modules, I still think this (or https://github.com/nextflow-io/nextflow/issues/1798) should be fixed.

**Comment by grst** [comment]
Bump

**Comment by pditommaso** [comment]
The `moduleDir` is not meant to allow accessing module files by the command script. The use of absolute paths in the task script is considered an anti-pattern in Nextflow and the tool try to prevent it. 

Said that as of version 22.10.0 nextflow supports [module binaries](file:///Users/pditommaso/Projects/nextflow/docs/_build/html/dsl2.html) that should solve this  request.
