### ISSUE TITLE
Request to publish checksum files with each release

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#2242]
I noticed that we already have checksum files in the repositry, corresponding to each release. I suggest that we should start including them as part of the release assets for a release on Github.

This would help end-users confirm data integrity when they rely on the `wget` / `curl` based setup.

We could also update the bash script at https://get.nextflow.io , to automatically check for the `checksum` files and inform the user that this check has been performed.

I'd be happy to implement these changes, with some pointers from the team.

**Comment by abhi18av** [comment]
Bump 🤞

**Comment by abhi18av** [comment]
I think this one is still relevant - @jorgeaguileraseqera , do you think we can simply tweak Gradle behavior for this?

**Comment by jorgeaguileraseqera** [comment]
can you point me to where we are managing these checksums? probably we can use Gradle for it but I would like to review the pipeline

**Comment by abhi18av** [comment]
Sure @jorgeaguileraseqera , every release has this [nextflow.md5](https://github.com/nextflow-io/nextflow/blob/master/nextflow.md5), [nextflow.sha256](https://github.com/nextflow-io/nextflow/blob/master/nextflow.sha256)  and [nextflow.sha1](https://github.com/nextflow-io/nextflow/blob/master/nextflow.sha1) files already but these are not part of the released github assets.

**Comment by jorgeaguileraseqera** [comment]
I think we are doing right now in the task `makeDigest` which is called by the task `upload` so probably we can close this issue (but have jreleaser in our radar)

**Comment by jorgeaguileraseqera** [comment]
Ah ok, 

I think all in Gradle it's done, we need "only" to create a github action who run `make release` (maybe when the commit has some keyword as [release] and branch is master?)

the release task is in publish.gradle and it performs all stuff required to build and upload artifacts

also, this action requires some envs as NXF_AWS_ACCESS and NXF_AWS_SECRET
