### ISSUE TITLE
Adding ending condition for watchPath

### ISSUE THREAD

**Issue by fujimuramasa** [nextflow-io/nextflow#2248]
## New feature

normally, a pipeline ends with all jobs done. It is usable adding condition to make watchPath end in a proper time. 

## Usage scenario 

by default, watchPath waits endlessly. 

waits until reaching triggering limits.
`watchPath("*.fastq", "times: 8")`

waits until deadline.
`watchPath("*.fastq", "duration: 3h")`

**Comment by bentsherman** [comment]
I've gotten around this issue in the past with `until()`. Basically, `watchPath()` wait until a file named `DONE` is received. Meanwhile, the downstream code saves a `DONE` file when it is done.

https://github.com/SystemsGenetics/GEMmaker/blob/9e69f21f79a38a2e4c6f0ec182ee4647be345754/workflows/GEMmaker.nf#L413-L420

**Comment by bentsherman** [comment]
Took another look at this today. You can use the `take` operator to limit the watchPath by number of emitted files:
```groovy
workflow {
    ch = Channel.watchPath("inputs/*").take(3)
    ch.subscribe(
        onNext: { print "emitted: ${it.name}" },
        onComplete: { print "we're done" }
    )

    ch.collect().view { "emitted: ${it.size()} files in total" }
}
```

As for limiting by a timeout, I wonder if anyone would find it useful to have a `timeout` option on watchPath, or more generally, a `timeout` operator that could be applied to any channel?
