### ISSUE TITLE
Problems encountered in the implementation of kuberun

### ISSUE THREAD

**Issue by yangxiao1220** [nextflow-io/nextflow#2249]
Hello, I am currently experiencing a problem, I hope you can help me, I am currently using nextflow in kubernetes, I post multiple tasks at once through nextflow kuberun, and I have configured a failed retry for the task, but this looks like It will cause the pod of app=nextflow to exit unexpectedly. I will write down the error I received below.

```
Caused by:
  Request GET /api/v1/namespaces/default/pods/nf-3f476ac79ec70a226f96fa58170219b9/status returned an error code=404

  {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {

      },
      "status": "Failure",
      "message": "pods \"nf-3f476ac79ec70a226f96fa58170219b9\" not found",
      "reason": "NotFound",
      "details": {
          "name": "nf-3f476ac79ec70a226f96fa58170219b9",
          "kind": "pods"
      },
      "code": 404
  }
```

**Comment by yangxiao1220** [comment]
WARN: Killing pending tasks (37)
The above problems will cause a large number of tasks to be killed

**Comment by pditommaso** [comment]
The issue can't be replicated
