### ISSUE TITLE
Can we include nf script in another nf script?

### ISSUE THREAD

**Issue by pwwang** [nextflow-io/nextflow#225]
```
+ src
  |- main.nf
  |- utils.nf
```

Can we do this in `main.nf`
`include 'utils.nf'` ?

Or is there any other way to do this?

**Comment by pditommaso** [comment]
Currently this is not possible. You can create java/groovy libraries and scripts. But sub-workflows are not supported.

Closing this issue. Feel free to comment if you need further help.
