### ISSUE TITLE
Missing output file(s) in Mac docker, but it works without docker

### ISSUE THREAD

**Issue by dgg32** [nextflow-io/nextflow#2268]
### Expected behavior and actual behavior

Expected behavior: the workflow below should generate two output files in "results" folder

 actual behavior: Nextflow encounters an error "Missing output file(s) `*.fastq.gz` expected by process `fastp (null)` (note: input files are not included in the default matching"

### Steps to reproduce the problem

[nextflow.zip](https://github.com/nextflow-io/nextflow/files/7010663/nextflow.zip)

Run the script in attachment while enable Docker on Mac with:

`nextflow run main.nf --reads '/Users/dgg32/Downloads/data/*_R{1,2}.fastq.gz'`

### Program output 

```
Error executing process > 'fastp (null)'

Caused by:
  Missing output file(s) `*.fastq.gz` expected by process `fastp (null)` (note: input files are not included in the default matching set)

Command executed:

  fastp -i SRR1647585_R1.fastq.gz -I SRR1647585_R2.fastq.gz     -o SRR1647585_trim_R1.fastq.gz -O SRR1647585_trim_R2.fastq.gz

Command exit status:
  0

Command output:
  (empty)

Command error:
  Read1 before filtering:
  total reads: 459478
  total bases: 40257600

```

Original output in attachment

### Environment 

* Nextflow version: 21.04.3
* Java version: Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)
* Operating system: macOS
* Bash version: zsh 5.7.1 (x86_64-apple-darwin19.0)

### Additional context

But the runs were successful when I used the local fastp and comment out either the `container = 'bromberglab/fastp'` or `docker.enabled = true`. It also works for Docker in Linux. So it seems a problem with Docker in Mac.

**Comment by pditommaso** [comment]
As the error message is suggesting input files are not matched by the glob pattern in the output declaration. Therefore the task cannot find any output. 

```
  Missing output file(s) `*.fastq.gz` expected by process `fastp (null)` (note: input files are not included in the default matching set)
```
