### ISSUE TITLE
[config] Allow setting `queueSize` for different `queue`

### ISSUE THREAD

**Issue by Mr-Milk** [nextflow-io/nextflow#2277]
## New feature

Allow setting `queueSize` for different types of `queue` in the executor scope

## Usage scenario 

Our HPC has different types of nodes that have different resource limitations. For example, `type_A` node allows running 3 jobs at the same time and `type_B` node allows 5. If I use the following config:

```
process {
    executor = "slurm"
    queue = "type_A,type_B"
}

executor {
    queueSize = 8
}
```

Nextflow will try to submit all the jobs to the `type_A` node first. Sometimes may cause failure before submit to the `type_B`.

## Suggest implementation 

A possible style for config:

```
process {
    executor = "slurm"
    queue = "type_A,type_B"
}

executor {
    queueSize = "3,5"
}
```

**Comment by pditommaso** [comment]
Unfortunately, this would require a non-trivial redesign of several components.
