### ISSUE TITLE
Support docker container option --shm-size, per process

### ISSUE THREAD

**Issue by maxbates** [nextflow-io/nextflow#2282]
## New feature

Some programs which use large file-based databases, like `jackhmmer`, see a significant performance increase when the database can be loaded into memory using a `shm` (e.g. `/dev/shm`) or `tmpfs` volume. 

I would like to specify the size of a ramdisk, dependent on the memory allocated to the container. E.g. If I allocate 64Gb to the container, I would pass `--shm-size=64g`. 

The size needs to be dynamic, so it matches the memory available to the container. Mounting `/dev/shm` is problematic in this case, because I do not want processes to compete for the host machine's shared memory (i.e. when multiple containers are scheduled onto the same instance). 

on AWS, because nextflow creates job definitions and does not support the process directive `containerOptions`, I do not think it is possible to provision a dynamically sized shared memory volume without manually creating a job definition (which I would like to avoid).

By default, docker allocates 64Mb to `/dev/shm`, but can be configured using `--shm-size` (ref)[https://docs.docker.com/engine/reference/run/]. The size cannot be changed from within the container, as it requires remounting the volume.

AWS supports specifying `sharedMemorySize` in the [job definition](https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#containerProperties), which simply passes through to docker's `--shm-size`

## Usage scenario 

The use of a ramdisk in alphafold's colab notebook for running `jackhmmer` can be see [here](https://github.com/deepmind/alphafold/blob/b1d772d127fcff4cc01d8fa1b4ea6e07da12193d/notebooks/AlphaFold.ipynb) (creating `/tmp/ramdisk`). There is a similar [recommendation on github](https://github.com/soedinglab/hh-suite/issues/281#issuecomment-888689484) for speeding up hhblits.

## Suggest implementation 

Add a process directory `shmSize` and update AWS Batch plugin's `newSubmitRequest(TaskRun task)` [ref](https://github.com/nextflow-io/nextflow/blob/master/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy#L557), and the local container executor.

**Comment by pditommaso** [comment]
Think what could be done here is parsing the `containerOptions` and map selected option to the corresponding Batch API such as `--shm-size`, `--ulimit`, etc

**Comment by maxbates** [comment]
That would absolutely work for me!

**Comment by pditommaso** [comment]
Would this require also the use of `--tmpfs` Docker option

**Comment by pditommaso** [comment]
Solved by #2471
