### ISSUE TITLE
Unknown executor awsbatch

### ISSUE THREAD

**Issue by mehrsaurabh** [nextflow-io/nextflow#2284]
## Bug report 

Getting the following error when trying to use AWSBATCH as an executor with Nextflow version 21.04.3 build 5560:
Unknown executor name: awsbatch

### Expected behavior and actual behavior

Expected behaviour is that AWS Batch should be a built-in executor according to the documentation.

Actual Behaviour getting the following error when trying to use AWSBATCH as an executor with Nextflow version 21.04.3 build 5560:
Unknown executor name: awsbatch

### Steps to reproduce the problem

Use executor as awsbatch in the latest version of Nextflow

### Program output 

(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)

### Environment 

* Nextflow version: [21.04.3 build 5560] 
* Java version: [11.0.10]
* Operating system: [Linux]
* Bash version: (5.0.3)

### Additional context

When we check the latest Nextflow code, we see that the executor "awsbatch" is missing from
/src/main/groovy/nextflow/executor/ExecutorFactory.groovy

Is this a deliberate change and the ways to work with AWS have changed or is it a bug introduced which needs to be fixed?

**Comment by pditommaso** [comment]
Likely this means you are not specifying a s3 path as the pipeline work directory

**Comment by mehrsaurabh** [comment]
I believe when S3 path is not specified then it throws a different error. Can you please check this /src/main/groovy/nextflow/executor/ExecutorFactory.groovy for built-in executors?

**Comment by abhi18av** [comment]
Hi @mehrsaurabh ,

Also worth noting that with the introduction of the `plugin` system in NF, that executor has been moved to https://github.com/nextflow-io/nextflow/blob/master/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchExecutor.groovy 

Could you please try with the `nextflow-VERSION-all` build available here  https://github.com/nextflow-io/nextflow/releases/download/v21.04.3/nextflow-21.04.3-all

**Comment by mehrsaurabh** [comment]
Thanks, will try that.

**Comment by mehrsaurabh** [comment]
After adding the work directory as a S3 bucket, it works. Just the error message was misleading. Thanks for your help @pditommaso

**Comment by pditommaso** [comment]
Still thinking the plugin should be automatically enabled when specifying a s3 URI as work directory. The `all` distribution should not be needed.

**Comment by manuelesimi** [comment]
If I can drop my 2 cents here, I see the executor as the main entry point to enable plugins.

In this case, the plugin should be automatically enabled when the `awsbatch` executor is selected. The same should apply to all executors.

**Comment by pditommaso** [comment]
Gues this was caused by specifying the`-bucket-dir` option which was not triggering the use of nf-amazon plugin. Patched by 6a8c50ad4.
