### ISSUE TITLE
Nextflow doesn't get the EKS IAM Service Account Role when executed in a pod

### ISSUE THREAD

**Issue by santosh0705** [nextflow-io/nextflow#2288]
## Bug report 

Nextflow doesn't get the EKS IAM Service Account Role when executed in a pod. It is getting role of the node instead the defined pod service account role.

### Expected behavior and actual behavior

It should get the service account role defined for the pod running the nextflow.

### Steps to reproduce the problem

Run nextflow batch job inside a pod having a service account set.

### Program output 

```
Caused by:
  User: arn:aws:sts::123456789012:assumed-role/node-role/i-xxxxxxx is not authorized to perform: batch:SubmitJob on resource: arn:aws:b
atch:us-east-1:123456789012:job-definition/xxxx (Service: AWSBatch; Status Code: 403; Error Code: AccessDeniedException;
Request ID: xxxx-xxxx-xxxx)
```

### Environment 

* Nextflow version: latest
* Java version: any
* Operating system: Linux
* Bash version: any

### Additional context

It is getting the role of the eks cluster node instead the pod service account role.

Running AWS CLI version 2 get the correct role: `aws sts get-caller-identity`
![Error](https://user-images.githubusercontent.com/1947598/131798161-780556f9-613e-4811-826e-de05c01b370f.jpg)

**Comment by khanagoudar** [comment]
we are facing exact same issue even though we are giving CLI V2 installation path in config

**Comment by bentsherman** [comment]
Possibly related to #2266

**Comment by Vishwas1976** [comment]
getting a similar issue, was this looked into, using nf-amazon@1.10.0 and nextflow@22.08.0-edge

**Comment by Vishwas1976** [comment]
"To use assume role profiles the aws-java-sdk-sts module must be on the class path.",

**Comment by pditommaso** [comment]
Could you please include the .nextflow.log file as requested in the issue template?

**Comment by bentsherman** [comment]
@Vishwas1976 you are welcome to create a PR with the fix, but you need to fork the nextflow repo and push your changes to a branch on that fork. Then you will be able to create the PR.

**Comment by Vishwas1976** [comment]
hi @bentsherman, created the PR as suggested: https://github.com/nextflow-io/nextflow/pull/3207, have not managed to get a signed commit not sure if thats acceptable, also shared snippet of before and after logs as the entire logs would contain specific account info

**Comment by santosh0705** [comment]
I moved out of the project where we need this fix. It's good to see that it finally working! 
Thanks everyone...

**Comment by khanagoudar** [comment]
Good to see this was fixed, we took alternate approach though
