### ISSUE TITLE
-resume to cache processes with no output

### ISSUE THREAD

**Issue by lucidv01d** [nextflow-io/nextflow#229]
Couldn't find this in the docs, but is it possible to skip processes that successfully complete but have no output with the **-resume** option?

For example, I have a process that runs dozens of times updating a database with different input chunks. If one of these fails, I have to them all with **-resume**, even if they completed successfully previously. Is there a more elegant workaround than `touch`ing dummy output files?

**Comment by pditommaso** [comment]
Yes, of course. If they are re-execute some inputs have changed.

**Comment by lucidv01d** [comment]
OK, I'll double check. Thanks

**Comment by pditommaso** [comment]
I'm closing this issue. If u need further help feel free to comment below.
