### ISSUE TITLE
Remote Caching Support

### ISSUE THREAD

**Issue by jchorl** [nextflow-io/nextflow#2291]
## New feature

Howdy!

On a fresh nextflow install, afaik, it's real difficult to leverage the cache of a previous nf run. This would be valuable though!

## Usage scenario 

Imagine ephemerally spinning up containers to run nf, then shutting them down. Late in a run, a process dies for whatever reason. The container shuts down and you lose all your progress. Same if you need to re-run a pipeline for any other reason.

It would be cool if multiple nextflow's could share a big cache.

## Suggest implementation 

(forgive my lack of expertise with the nextflow internals)

Given that nextflow already uses content-addressable storage for its cache layer, the backend could be shimmed with something like gcs or s3. Any filesystem would do.

And given that nf has support for many storage backends already, the building blocks are already in-place.

So:
1. Abstract fs access in nf caching (maybe this is done already!)
2. Add a flag `-cache-storage-backend` that allows for options like `localfs`, `s3://my-nf-cache/thing`
3. Configure the cache to back onto that fs backend

I'm not sure how caching currently works across nf versions, especially with breaking changes. It's possible you'd want to encode the nf version in the cache paths.

Then, when rebooting nf (or running an entirely new container), it would magically resume from `-cache-storage-backend`. It would be up to the user whether they wanted to separate caches for different pipelines because they could pass different flags here.

**Comment by pditommaso** [comment]
Do you mean caching as for Nextflow task working directory data?

**Comment by jchorl** [comment]
> Do you mean caching as for Nextflow task working directory data?

I mean caching the processes themselves. So if I run a nextflow analysis on one machine, and then run the same analysis on another machine, they both back onto a shared cache, and the cached processes don't get re-run.

Basically, distributed `-resume`.

**Comment by pditommaso** [comment]
Ok, we are talking about the same thing. It's already working like that! just always provide `-resume` and the same bucket for any run, if the process gets the input files, the hash id will be computed and if a result is found it will be taken from the cache.

**Comment by pditommaso** [comment]
Closing since this is expected to be already supported. Feel free to comment below or re-open otherwise
