### ISSUE TITLE
Nextflow changes erase character to ^?

### ISSUE THREAD

**Issue by bas-stringer** [nextflow-io/nextflow#2293]
## Bug report 

Running Nextflow changes the backspace / erase character to `^?`, and several other `stty` settings.

### Steps to reproduce the problem

I have freshly installed Nextflow on a server which I connect to via MobaXTerm. Before (and during) running the `nextflow-io/hello` demo pipeline, the backspace character is `^H`. After running, it has changed to `^?`. It also changes `brkint`, `ixany`, `imaxbel` and `iutf8` settings.

### Program output 

```
$ stty -a > before

$ ./nextflow run hello
N E X T F L O W  ~  version 21.04.3
Launching `nextflow-io/hello` [evil_almeida] - revision: ec11eb0ec7 [master]
executor >  local (4)
[48/10b0eb] process > sayHello (1) [100%] 4 of 4 ✔
Hola world!

Ciao world!

Hello world!

Bonjour world!


$ stty -a > after

$ diff before after
2c2
< intr = ^C; quit = ^\; erase = ^H; kill = ^U; eof = ^D; eol = <undef>;
---
> intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
6,7c6,7
< -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
< -iuclc ixany -imaxbel iutf8
---
> -ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
> -iuclc -ixany imaxbel -iutf8
```

### Environment 

* Nextflow version: 21.04.3
* Java version: 1.8.0_302
* Operating system: CentOS (7-9.2009.1)
* Bash version: 4.2.46(2)
* MobaXTerm version: Personal Edition 21.1

### Update:

The `after` settings appear to be identical to the settings preconfigured as `stty sane`.

```
$ stty -a > before
$ stty sane
$ stty -a > sane
$ ./nextflow run hello
[...]
$ stty -a > after

$ diff sane before
2c2
< intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
---
> intr = ^C; quit = ^\; erase = ^H; kill = ^U; eof = ^D; eol = <undef>;
6,7c6,7
< -ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
< -iuclc -ixany imaxbel -iutf8
---
> -ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
> -iuclc ixany -imaxbel iutf8

$ diff sane after
[No differences.]
```

This leads me to suspect `stty sane` is invoked somewhere during Nextflow's run? Is there a way to configure Nextflow *not* to do this?

**Comment by pditommaso** [comment]
This sounds unusual. It may be related to this https://github.com/nextflow-io/nextflow/blob/a41035e20338ce2b145a2a760c8ed64c925f18e3/nextflow#L32-L39

**Comment by bas-stringer** [comment]
On a fresh shell (same as above), both **if** statements are **true**. 
However, executing these lines on commandline does not cause the `stty sane` behaviour.

**Comment by pditommaso** [comment]
Have you tried running using with `-ansi-log false` option ?

**Comment by bas-stringer** [comment]
I have just now. Running it this way keeps `stty` unchanged!

```
$ stty -a > before
$ nf run -ansi-log false hello
N E X T F L O W  ~  version 21.04.3
Launching `nextflow-io/hello` [sick_khorana] - revision: ec11eb0ec7 [master]
[03/e8e178] Submitted process > sayHello (4)
[59/cb28a1] Submitted process > sayHello (1)
[4e/6d9584] Submitted process > sayHello (3)
[34/27812e] Submitted process > sayHello (2)
Hola world!
Bonjour world!
Hello world!
Ciao world!
$ stty -a > after
$ diff before after
[No differences.]
```

**Comment by pditommaso** [comment]
Really no have idea then

**Comment by rdwrt** [comment]
I have the exact same issue 

```
$ nextflow -version

      N E X T F L O W
      version 21.04.0 build 5552
      created 02-05-2021 16:22 UTC (18:22 CEST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io
```
no issues when I use:
```
run ... -ansi-log false 
```

**Comment by d-jch** [comment]
me too, always
