### ISSUE TITLE
Error "K8s pod image cannot be pulled" terminates entire workflow

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2302]
### Expected behavior and actual behavior

I have a pipeline [bentsherman/minibench](https://github.com/bentsherman/minibench) that I am trying to run on a k8s cluster. However, sometimes a pod will fail with an error like this one:
```
Error executing process > 'minibench (11)'

Caused by:
  K8s pod image cannot be pulled -- Back-off pulling image "localhost:30081/bentsherman/minibench"

WARN: Killing pending tasks (50)
```

The one pod failure causes the entire workflow to terminate even though I have `errorStrategy = "ignore"`. I am not sure why this is the case. It seems Nextflow assumes that this error will always lead to systemic failure, however in my experience it is a transient error that happens to a few pods every now and then. I think this k8s error should respect `errorStrategy` and not terminate the entire workflow by default.

### Environment 

* Nextflow version: 21.04.3
* Java version: 1.8
* Operating system: Linux

**Comment by bentsherman** [comment]
Another variation of the same error:
```
Error executing process > 'minibench (49)'

Caused by:
  K8s pod image cannot be pulled -- rpc error: code = Unknown desc = Error response from daemon: Get http://localhost:30081/v2/bentsherman/minibench/manifests/latest: dial tcp 127.0.0.1:30081: connect: network is unreachable

WARN: Killing pending tasks (50)
```

I think it is related to transient networking issues with the k8s cluster that I use. I might be able to debug the root cause of these weird errors, but first Nextflow should try to finish all of the tasks, even if they all end up failing, rather than terminating immediately,

**Comment by bentsherman** [comment]
Based on my cursory stack tracing, this k8s error is handled alongside all other errors in `resumeOrDie()`:

https://github.com/nextflow-io/nextflow/blob/3a7f4bf5386c844a9e46a2efb71b0feb0c7ecd1a/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L963-L971

The k8s error is a `PodUnschedulableException`, which is a direct subclass of `Exception`. However, the error has to be a `ProcessException` in order to be handled according to the error strategy. So maybe these k8s exception types should be modified to inherit from `ProcessException`.

**Comment by pditommaso** [comment]
It depends if the error condition is permanent does not have much sense trying to re-execute it. It should be inspected the nature of the error in the status response and throw an exception accordingly. The corresponding code should be this 

https://github.com/nextflow-io/nextflow/blob/6a8c50ad46f6fa18279b5d248ac80d7d2aa17d89/modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy#L264-L274

**Comment by bentsherman** [comment]
Here is the error case I am talking about:

https://github.com/nextflow-io/nextflow/blob/6a8c50ad46f6fa18279b5d248ac80d7d2aa17d89/modules/nextflow/src/main/groovy/nextflow/k8s/client/K8sClient.groovy#L279-L284

I think some of the nodes in my cluster are having a problem pulling container images, but only some times. I have verified this by running multiple independent trials on each node. In this situation I would like to be able to either retry with a backoff period or ignore the error so that the entire workflow can finish.

I do not think `ErrImagePull` or `ImagePullBackoff` should be treated as systemic failures. I would make the same argument for the other cases in `checkInvalidWaitingState` as well. The user should at least be able to set `errorStrategy = 'ingore'`, allow the workflow to run to completion, and then investigate the errors.

**Comment by pditommaso** [comment]
I could agree, but it could be useful what's the difference between `ErrImagePull` and `ImagePullBackoff`

**Comment by bentsherman** [comment]
`ImagePullBackOff` means the pod is waiting a bit before trying again. In this situation the pod's status will be `ErrImagePull` for a moment and then switch to `ImagePullBackOff`.

**Comment by pditommaso** [comment]
Ok, makes sense, I'll make `PodUnschedulableException` extending `ProcessExeception`. Thanks!

**Comment by bentsherman** [comment]
@pditommaso Thanks. Is there a way for me to test this change before the next edge release? Is there some kind of nightly build? I could build locally but then I don't know how to make that work on kubernetes.

**Comment by pditommaso** [comment]
Use the `make dockerPack` to build a container image with your nextflow local build, then use it to run your pipeline

**Comment by pditommaso** [comment]
Umm, trying this I could not find the resulting image. Not sure if the changes made to use `docker buildx` command have messed up this. 68c1844 ec87e53

**Comment by bentsherman** [comment]
I was able to build my own nextflow docker image and use it with kuberun. Works great!
