### ISSUE TITLE
Plugin dependency requirement overrides core plugin definition

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#2303]
## Bug report 

When plugin is specified in the configuration file having a dependency with a core plugin that's not included in the config specification, the requirement version overrides the core plugins version. 

For example: 
- NF runtime requires foo@1.2.0
- In the config is add the plugs bar@1.1.0 
- bar@1.1.0 requires >=foo@1.1.0 
- in the config is add 
    ```
     plugins {
       id 'bar@1.1.0'
     } 
    ```
- the resolved plugins are `foo@1.1.0` and `bar@1.1.0` instead of `foo@1.2.0` and `bar@1.1.0`.

**Comment by abhi18av** [comment]
@pditommaso , given that we are now depending upon specific versions of plugins with different versions of nextflow - do you think that it might be worth exploring conda for off-loading all this computation?

This way, any user who'd like to use `nf-amazon` with `nextflow` , they can install it via `conda install nextflow nf-amazon` and we can rely on `conda`'s sophisticated abilities for making sure that these are resolved correctly.

What are your thoughts?

**Comment by pditommaso** [comment]
> conda for off-loading

what do you mean?

**Comment by abhi18av** [comment]
I meant that we can publish the plugins via conda as well, then rely on conda for downloading/managing the plugins.

**Comment by pditommaso** [comment]
Oh no, we have already too many problems 😄
