### ISSUE TITLE
spread operator doesn't connect channels in dag

### ISSUE THREAD

**Issue by msmootsgi** [nextflow-io/nextflow#231]
The spread operator does not connect the two channels in the DAG produced with the ```-with-dag``` argument.  Here is a simple pipeline the shows the problem:

```
Channel
    .from(1,2)
    .into{ chan1 }

Channel
    .from("a","b","c")
    .into{ chan2 }

chan1
    .spread( chan2 )
    .into { chan3 }

process saySomething {

    input:
    set num, let from chan3

    output:
    stdout into chan4

    script:
    """
    echo "num: ${num} let: ${let}"
    """
}

chan4.view()
```

I've attached an image of what the actual dag produced looks like and what I'd expect the dag to look like.  In the actual output there's an extra ```toList``` operator shown, which I'm guessing is implicit in the spread operation.  Ideally it shouldn't be there since it's not reflected in the code, but if it's easier to leave it in, it really won't hurt anything, as long as it then connects to the spread node.

This is what actually gets produced:

![actual_spread_dag_bug](https://cloud.githubusercontent.com/assets/22308243/19174653/3e5c99cc-8be5-11e6-89b4-36090f403b55.png)

This is what *should* get produced:

![expected_spread_dag_bug2](https://cloud.githubusercontent.com/assets/22308243/19174655/4ab84cd4-8be5-11e6-81da-2368672b2c42.png)

**Comment by pditommaso** [comment]
I've uploaded `0.22.3-SNAPSHOT` that fixes this issue. You may want to give it a try.

**Comment by mes5k** [comment]
Tried and looks great.  Many thanks!
