### ISSUE TITLE
First nextflow boot wipes logs

### ISSUE THREAD

**Issue by jchorl** [nextflow-io/nextflow#2316]
## Bug report 

Hello!

So I wrote a simple shell script -

```
#!/bin/bash

echo 'stdout'
>&2 echo "stderr"

./nextflow
```

What I expected to see was:
```
stdout
stderr

<nextflow things>
```

However, with certain docker logging drivers (i.e. aws batch), the first bits are getting wiped.

The first logs I see are `2/2 KB 2/14 KB 3/14 KB 5/14 KB 6/14 KB 7/14 KB 9/14 KB 10/14 KB 11/14 KB ...`

So I ran nf locally (fresh docker image) under `script` to capture escape sequences:
```
script nf.log

./script.sh
```

Here's the resulting `nf.log`, piped through `xxd`:

```
00000000: 5363 7269 7074 2073 7461 7274 6564 206f  Script started o
00000010: 6e20 3230 3231 2d30 392d 3135 2030 323a  n 2021-09-15 02:
00000020: 3538 3a33 392b 3030 3a30 3020 5b54 4552  58:39+00:00 [TER
00000030: 4d3d 2278 7465 726d 2220 5454 593d 222f  M="xterm" TTY="/
00000040: 6465 762f 7074 732f 3022 2043 4f4c 554d  dev/pts/0" COLUM
00000050: 4e53 3d22 3231 3222 204c 494e 4553 3d22  NS="212" LINES="
00000060: 3538 225d 0a23 2073 6372 6970 742e 7368  58"].# script.sh
00000070: 0d0a 7368 3a20 313a 2073 6372 6970 742e  ..sh: 1: script.
00000080: 7368 3a20 6e6f 7420 666f 756e 640d 0a23  sh: not found..#
00000090: 202e 2f73 6372 6970 742e 7368 0d0a 7374   ./script.sh..st
000000a0: 646f 7574 0d0a 7374 6465 7272 0d0a 0d0d  dout..stderr....
000000b0: 322f 3220 4b42 2020 200d 2020 2020 2020  2/2 KB   .      
000000c0: 2020 200d 2020 2020 2020 2020 200d 2020     .         .  
000000d0: 2020 2020 2020 200d 322f 3134 204b 4220         .2/14 KB 
000000e0: 2020 0d33 2f31 3420 4b42 2020 200d 352f    .3/14 KB   .5/
```

With `man ascii`, we can deduce that on line `000000a0`, the `0x72` is the `r`. We see a `0d0a 0d0d` after.

`0d` [is `Moves the cursor to column zero. `](https://en.wikipedia.org/wiki/ANSI_escape_code).

I can only imagine this is wiping the line before issuing the carriage return.

I'm not sure what's being downloaded here, but could it respect the `NXF_ANSI` env var? Or could it not issue a line-delete as the first call? A cheap solution might be to just issue a carriage return first, then you (probably) don't care if it issues the `0d`.

This happens on the latest `master`.

**Comment by pditommaso** [comment]
Not sure if it could be the capsule installer download process creating this problem. Try adding 

```
export CAPSULE_LOG=none
```
