### ISSUE TITLE
Bash Parameter expansion

### ISSUE THREAD

**Issue by Jbrenton191** [nextflow-io/nextflow#2318]
## Bug report 

I found a work around using either rename or basename functions but just wanted to highlight.

### Expected behavior and actual behavior

Expected behaviour: Typical bash parameter expansion: ie:

~/nextflow_pd$ gtf_file=Homo_sapiens.GRCh38.97.gtf
~/nextflow_pd$ echo ${gtf_file%.gtf}
Homo_sapiens.GRCh38.97

Actual behaviour: 
but when placed in a nextflow process it leads to this error:

Script compilation error
- file : /home/jbrenton/nextflow_pd/test_bug.nf
- cause: Unexpected input: '{' @ line 4, column 20.
   process gtf_to_bed {
                      ^

1 error

### Steps to reproduce the problem
-ran the following process with command: nextflow run test_bug.nf
`nextflow.enable.dsl=2

process gtf_to_bed {

echo true

    input:
    path(gtf_file)

    output:
    path("*.bed")

    script:
    """
    echo $gtf_file > ${gtf_file%.gtf}.bed
        """
}
workflow {
gtf_file=file("$projectDir/Homo_sapiens.GRCh38.97.gtf")
gtf_to_bed(gtf_file)
}
`

### Program output 
`Script compilation error
- file : /home/jbrenton/nextflow_pd/test_bug.nf
- cause: Unexpected input: '{' @ line 4, column 20.
   process gtf_to_bed {
                      ^

1 error

`

### Environment 

* Nextflow version: 21.04.0 build 5552
* Java version: 11.0.9.1-internal
* Operating system: Linux: Ubuntu 16.04.7 LTS (Xenial Xerus)
* Bash version: GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

### Additional context

Running on a linux server

**Comment by abhi18av** [comment]
Hi @Jbrenton191 ,

The usage of `$` in the `script`  section is the issue.

```
script:
"""
echo $gtf_file > ${gtf_file%.gtf}.bed
 """
```

Please either 

1. Escape the character for e.g. `echo \$gtf_file ...`
2. Use the `shell` directive which doesn't need these characters to be escaped  https://www.nextflow.io/docs/latest/process.html#shell
