### ISSUE TITLE
Docker tag does not coincide with nextflow version

### ISSUE THREAD

**Issue by schorlton** [nextflow-io/nextflow#2320]
### Expected behavior and actual behavior

Running nextflow from docker should respect the tag version. It looks like it instead defaults to the latest release version? I could set the environment variable in the container to my preferred version, but nextflow should respect the docker tag so I don't need to set it in multiple places. Thanks!

### Steps to reproduce the problem

```
docker run --rm -it nextflow/nextflow:21.08.0-edge bash  
bash-4.2# nextflow info
  Version: 21.04.3 build 5560
  Created: 21-07-2021 15:09 UTC 
  System: Linux 5.10.0-8-amd64
  Runtime: Groovy 3.0.7 on OpenJDK 64-Bit Server VM 11.0.11+9-LTS
  Encoding: UTF-8 (UTF-8)
```

**Comment by pditommaso** [comment]
Thanks for reporting. It should ok now. Make sure to use this version 

```
nextflow/nextflow:21.08.0-edge@sha256:1a7ab4214ab9ce76d4c7c37914b57044bcc95ef3e69d20a9dfa15a39e0805838
```
