### ISSUE TITLE
When using run repo with revision tag -r git_commit, the command must be run twice

### ISSUE THREAD

**Issue by evanfloden** [nextflow-io/nextflow#233]
Minor issue: It appears that when using a revision tag on the first run after a new commit, I get the error:

```
nextflow run skptic/tuxedo-nf -r eab9e15 -profile crg -with-docker -resume
N E X T F L O W  ~  version 0.22.3
Cannot find revision `eab9e15` -- Make sure that it exists in the remote repository `https://github.com/skptic/tuxedo-nf`
-bash-4.2$ nextflow run skptic/tuxedo-nf -r eab9e15 -profile crg -with-docker -resume
N E X T F L O W  ~  version 0.22.3
Launching `skptic/tuxedo-nf` [desperate_borg] - revision: eab9e15af6fdf60fcc865fd772a0420d0fb273c1

```

When executed again, as shown above, the revision is found and the pipeline executes correctly. I guess it must be due to the ordering of the remote lookup vs local execution.

**Comment by pditommaso** [comment]
I think this is somehow expected because NF doesn't pull new changes from the remote origin when using the `run` command. 

However I agree the behaviour is inconsistent, it should either continue to fail or run on the first try.

**Comment by hydriniumh2** [comment]
Pinging this issue as I've been running into this bug as well

**Comment by pditommaso** [comment]
Please provide a reproducible test case.

**Comment by hydriniumh2** [comment]
Would this be ok?
https://github.com/hydriniumh2/nextflow_issue_233

**Comment by pditommaso** [comment]
Possibly. I'll check it. Thanks.
