### ISSUE TITLE
fromSRA retrive suck with error 500/400 for ENA 

### ISSUE THREAD

**Issue by alarawms2** [nextflow-io/nextflow#2346]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

(While running 
channel.fromSRA('SRP043510' the expected result should be SRA archive. The result show error 400/500 from ENA web portal)

### Program output 

(N E X T F L O W  ~  version 21.04.3
Launching `test.nf` [special_cajal] - revision: 7696b09900
WARN: Define the NCBI_API_KEY env variable to use NCBI search service -- Read more https://ncbiinsights.ncbi.nlm.nih.gov/2017/11/02/new-api-keys-for-the-e-utilities/
[-        ] process > fastqc -
[-        ] process > fastqc -
Server returned HTTP response code: 500 for URL: https://www.ebi.ac.uk/ena/portal/api/filereport

)

### Environment 

* Nextflow version: [21.04.3] 
* Java version: [openjdk 15.0.3 2021-04-20]
* Operating system: [Linux]
* Bash version: (GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu))

### Additional context

(Add any other context about the problem here)

**Comment by abhi18av** [comment]
Thanks for reporting this issue @alarawms2 , this is resolved on the dev branch. Please try the edge release to make use of this fix for now.

Related https://github.com/nextflow-io/nextflow/pull/2239
