### ISSUE TITLE
Custom Channel operators without a plugin

### ISSUE THREAD

**Issue by spitz-dan-l** [nextflow-io/nextflow#2347]
## New feature

First off, thank you so much for all your effort on Nextflow! It is a great framework with much promise.

I am trying to implement some custom Channel operators to support a particular usage pattern. At the same time as I'm submitting this issue, I'm also starting work on a plugin that implements these operators.

Ideally, Nextflow would have language-level support for new Channel operators. It currently supports writing Channel-transforming functions via `def`, but using them leads to significantly greater verbosity in the workflow code:

With custom operator:
```
workflow {
    take:
    data

    main:
    output = data | custom_op_1('foo') | my_proc | custom_op_2('bar')

    emit:
    output
}
```

Without (using custom functions):
```
workflow {
    take:
    data

    main:
    x1 = custom_op_1(data, 'foo')
    my_proc(x1)
    output = custom_op_2(my_proc.out, 'bar')

    emit:
    output
}
```

## Usage scenario 

It doesn't seem like a plugin is really the right thing to use for this situation. I don't necessarily expect it to be widely useful for many nextflow users, so making it generally available for installation doesn't seem like a good goal. I am intending for these operators to be used within a small, private team.

Does that mean that my best bet is just to fork the nextflow codebase, and use a custom build internally? For that I'm concerned at how much extra effort it potentially is.

## Suggest implementation 

Language-level support for custom channel operators, perhaps via a new keyword, or an extension to the custom functions.

Another suggestion would just be to make it easier to extend nextflow with custom Groovy code, without having to rebuild the codebase or publish a plugin.

Thank you for your time!

**Comment by bentsherman** [comment]
One solution here is to just create processes with native code (`exec`). A native process is very similar to an operator, and should suit your needs.
