### ISSUE TITLE
Singularity uses python libraries outside container

### ISSUE THREAD

**Issue by grst** [nextflow-io/nextflow#2348]
### Expected behavior and actual behavior

Expected: The process fails, as Biopython is not available in a vanilla python container
Actual: The process succeeds, as the `.local` directory in my home directory gets mounted into the container

This is a problem as pipelines may not be reproducible anymore as a different version of a Python package than 
installed in the container may be used. This may happen with R packages, too. 

### Steps to reproduce the problem

`nextflow.config`
```nextflow
singularity.enabled = true
singularity.autoMounts = true
```

`singularity-nohome.nf` 

```nextflow
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

process test_singularity {

    container = "https://depot.galaxyproject.org/singularity/python%3A3.9"

    script:
    """
    #!/usr/bin/env python

    import Bio 
    """
}

workflow {
    test_singularity()
}
```
**NB:** to reproduce, the python version of the container must match the python version on the system running nextflow

Command executed: 
```bash
pip install --use Biopython
./singularity-nohome.nf -c nextflow.config
```

### Program output 

(Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)

### Environment 

* Nextflow version: `version 21.04.0 build 5552`
* Java version: `openjdk version "11.0.8-internal" 2020-07-14`
* Operating system: Linux
* Bash version: `GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)`
* Singularity version: `singularity version 3.8.3`

### Proposed solution

Always call singularity with the `--no-home` option. 

---
CC @riederd

**Comment by grst** [comment]
bump, as this is very bad for reproducibility.

Linking the related nf-core discussion:
https://nfcore.slack.com/archives/CE5LG7WMB/p1643152746064800

**Comment by Grelot** [comment]
I got the same problem with Rscript. Rscript is located at /usr/bin/ in both my computer and the container. Nextflow seems to load the Rscript from my computer instead of the container. How to solve it ?

**Comment by Grelot** [comment]
I tried to run my nextflow with and without this fix in my `nextflow.config`, unfortunally it changes nothing to the behaviour.
I also tried to run nextflow with `--no-home` option for singularity or by setting singularity.autoMounts = false

It doesn't change anything. This is strange because on a non-DSL2 nextflow, the singularity container is working well with Rscript.
And in my DSL2 nextflow, singularity is working well for dependencies that are not R/python/...

**Comment by grst** [comment]
how do you pass the `--no-home` flag? 
This has worked well for me before: 
https://github.com/icbi-lab/luca/blob/6f2ea7203272b6d6f7e415f7abf0d247c8368ed4/nextflow.config#L11-L12

Setting `autoMounts = false` has no effect on the home directory being mounted.

**Comment by Grelot** [comment]
It fixed my problem ! Indeed I use it only on the concerned modules in `conf/modules.config`. Thank you a lot.
By the way, this remains a temporary fix as I will not be able to use Rscript or python script using external files.

**Comment by grst** [comment]
I still think this should be fixed.

**Comment by pditommaso** [comment]
is it not `containerOptions = "--no-home"` a solution for this?

**Comment by riederd** [comment]
shouldn't be this the default?

**Comment by riederd** [comment]
yes it could, but just as it breaks pipelines that rely on using libraries/tools/software-versions that are packaged into the singularity image. 

I think the question is, what is more important then.

For me, as a pipeline developer, it would be more important that the pipeline is reliably using the software (versions) that I pack into the image, so things remain reproducible.

**Comment by grst** [comment]
Well, you [never know](https://xkcd.com/1172/), but
 * the whole point of containers is to separate the software used by a process from the software available on a system
 * workflows relying on the home directly being mounted in a container are likely doing something wrong (i.e. files not staged into the work dir by nextflow). 
 
Error messages arising due to wrong package versions being used are usually obscure and hard to debug. If a file is not found, it's pretty obvious.

**Comment by GallVp** [comment]
If someone comes looking for why some of their JAVA based programs are failing after the addition of `--no-home`, following java options may help.

```bash
-Djava.util.prefs.userRoot=user_prefs -Duser.home=user_home
```
