### ISSUE TITLE
Java version (OpenJDK 16) isn't recognized as compatible

### ISSUE THREAD

**Issue by unode** [nextflow-io/nextflow#2349]
## Bug report 

Nextflow fails to launch with openjdk 16 showing a misleading error message mentioning Java 8 or later.
OpenJDK 16 was released in March 2021.

### Expected behavior and actual behavior

```
% ./nextflow 
ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 or later is installed
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /nix/store/jspbm99wdr4i46dygadv68zzz2v58kaa-openjdk-16+36/lib/openjdk/bin/java
 JAVA_HOME: /nix/store/jspbm99wdr4i46dygadv68zzz2v58kaa-openjdk-16+36/lib/openjdk

% java --version
openjdk 16 2021-03-16
OpenJDK Runtime Environment (build 16+36-nixos)
OpenJDK 64-Bit Server VM (build 16+36-nixos, mixed mode, sharing)
```

The error indicates Java 8 or newer but OpenJDK 16 (JDK 16) is not recognized as a valid JVM.

### Environment 

* Nextflow version: 21.04.3
* Java version: openjdk 16 2021-03-16
* Operating system: Linux NixOS - `Linux 4.19.196, NixOS, 21.05.git.1172997f5a6 (Okapi)`
* Bash version: 4.4.23(1)-release

**Comment by abhi18av** [comment]
Reading the related  thread https://github.com/nextflow-io/nextflow/issues/2057  it seems that the support was added in May and it should be available in the `edge` releases already.

I noticed you're using the stable release for `21.04` and the next stable release `v21.10` would come out in October.

**Comment by pditommaso** [comment]
Indeed. Java 16 is already supported and tested 

https://github.com/nextflow-io/nextflow/blob/371f858ab59e0d79d19fd4637d0e218140411b86/.github/workflows/build.yml#L21-L21

Look the docs for details how install latest edge version https://www.nextflow.io/docs/latest/getstarted.html#stable-edge-releases
