### ISSUE TITLE
NoSuchFileException after fresh install when running tutorial.nf

### ISSUE THREAD

**Issue by chdem** [nextflow-io/nextflow#235]
Hello,

I'm testing nextflow in order to use it in the place where I'm working (french public hospital).

So, I'm a new nextflow user (pretty exited!) and after a fresh install, I tried to launch the tutorial.nf as described in https://www.nextflow.io/docs/latest/getstarted.html?highlight=hello#your-first-script

I don't want to use docker for now, and my command is simply : `nextflow tutorial.nf`

Here the result of the command : 

> $ nextflow tutorial.nf
N E X T F L O W  ~  version 0.22.3
Launching 'tutorial.nf' [stupefied_shannon] - revision: df5769453e
[warm up] executor > local
[13/65dc82] Submitted process > splitLetters (1)
ERROR ~ Error executing process > 'splitLetters (1)'
Caused by:
  Process 'splitLetters (1)' terminated with an error exit status (1)
Command executed:
  printf 'Hello world!' | split -b 6 - chunk_
Command exit status:
  1
Command output:
  (empty)
Work dir:
  /mnt/isilon_cifs/test/work/13/65dc824352187feabae5bc7612e857
Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option '-resume'
 -- Check '.nextflow.log' file for details

And here the .nextflow.log file (only the usefull part) : 

> Oct-31 18:06:33.627 [Actor Thread 2] INFO  nextflow.Session - [13/65dc82] Submitted process > splitLetters (1)
Oct-31 18:06:33.628 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <splitLetters> After stop
Oct-31 18:06:33.710 [Thread-1] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_cifs/test/work/13/65dc824352187feabae5bc7612e857/.command.out
Oct-31 18:06:33.713 [Thread-1] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_cifs/test/work/13/65dc824352187feabae5bc7612e857/.command.err
Oct-31 18:06:33.715 [Thread-1] ERROR nextflow.processor.TaskProcessor - Error executing process > 'splitLetters (1)'
> 
> Caused by:
  Process 'splitLetters (1)' terminated with an error exit status (1)
>
> Command executed:
>
  printf 'Hello world!' | split -b 6 - chunk_
>
> Command exit status:
  1
>
Command output:
  (empty)
>
Work dir:
  /mnt/isilon_cifs/test/work/13/65dc824352187feabae5bc7612e857
>
Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option '-resume'
Oct-31 18:06:33.719 [Actor Thread 3] DEBUG nextflow.processor.TaskProcessor - <splitLetters> Sending poison pills and terminating process
Oct-31 18:06:33.727 [Thread-1] DEBUG nextflow.Session - Session aborted -- Cause: Process 'splitLetters (1)' terminated with an error exit status (1)
Oct-31 18:06:33.727 [Thread-1] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_cifs/ONCO_DIG/ISILONAUTOCOPY/PGM/2016/PGM-349-160113/fichiers_pour_DVD/TorrentServer/HNPCC/work/13/65dc824352187feabae5bc7612e857/.command.err
Oct-31 18:06:33.727 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <convertToUpper> Poison pill arrived
Oct-31 18:06:33.727 [Actor Thread 3] DEBUG nextflow.Session - <<< barrier arrive (process: splitLetters)
Oct-31 18:06:33.727 [Thread-1] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_cifs/ONCO_DIG/ISILONAUTOCOPY/PGM/2016/PGM-349-160113/fichiers_pour_DVD/TorrentServer/HNPCC/work/13/65dc824352187feabae5bc7612e857/.command.out
Oct-31 18:06:33.728 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <convertToUpper> After stop
Oct-31 18:06:33.728 [Actor Thread 6] DEBUG nextflow.processor.StateObj - <convertToUpper> State before poison: StateObj[submitted: 0; completed: 0; poisoned: false ]

I'm not able to understand what is the error. 
This is true, there is no `.command.err` neither `.command.out` and there is no write problem in the 'work' directory.

Do I miss something ?
Thank you for your help !

**Comment by pditommaso** [comment]
Something strange is happening here. Can you try to run the following basic example: 

```
nextflow run hello
```

What is the output?

**Comment by chdem** [comment]
Sorry for the delay. French holidays ;)
I think this is the same error....

>$ nextflow run hello
>N E X T F L O W  ~  version 0.22.3
>Pulling nextflow-io/hello ...
> downloaded from https://github.com/nextflow-io/hello.git
>Launching `nextflow-io/hello` [sleepy_jang] - revision: 6b9515aba6 [master]
>[warm up] executor > local
>[0a/12fb9e] Submitted process > sayHello (3)
>[8c/830987] Submitted process > sayHello (4)
>[39/965bf3] Submitted process > sayHello (1)
>[60/1fe888] Submitted process > sayHello (2)
>ERROR ~ Error executing process > 'sayHello (3)'
>
>Caused by:
>Process `sayHello (3)` terminated with an error exit status (1)
>
>Command executed:
>
>echo 'Hello world!'
>
>Command exit status:
>  1
>
>Command output:
>  (empty)
>
>Work dir:
>/mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf
>
>Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named: '.command.sh'
>
>-- Check '.nextflow.log' file for details

And in the .nextflow.log : 

>Nov-03 09:47:06.545 [main] DEBUG nextflow.cli.Launcher - Setting HTTP proxy: [X.X.X.X, 3128]
>Nov-03 09:47:06.721 [main] DEBUG nextflow.cli.Launcher - Setting HTTPS proxy: [X.X.X.X, 3128]
>Nov-03 09:47:06.722 [main] DEBUG nextflow.cli.Launcher - Setting http proxy: [X.X.X.X, 3128]
>Nov-03 09:47:06.722 [main] DEBUG nextflow.cli.Launcher - Setting https proxy: [X.X.X.X, 3128]
>Nov-03 09:47:06.722 [main] DEBUG nextflow.cli.Launcher - $> /usr/bin/nextflow run hello
>Nov-03 09:47:06.792 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 0.22.3
>Nov-03 09:47:07.079 [main] DEBUG nextflow.scm.AssetManager - Listing projects in folder: /home/dvdadmin/.nextflow/assets
>Nov-03 09:47:07.095 [main] INFO  nextflow.cli.CmdRun - Pulling nextflow-io/hello ...
>Nov-03 09:47:07.096 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/nextflow-io/hello/contents/nextflow.config
>Nov-03 09:47:08.249 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/nextflow-io/hello/contents/main.nf
>Nov-03 09:47:08.776 [main] DEBUG nextflow.scm.RepositoryProvider - Request [credentials -:-] -> https://api.github.com/repos/nextflow-io/hello
>Nov-03 09:47:08.947 [main] DEBUG nextflow.scm.AssetManager - Pulling nextflow-io/hello -- Using remote clone url: https://github.com/nextflow-io/hello.git
>Nov-03 09:47:10.689 [main] INFO  nextflow.cli.CmdRun -  downloaded from https://github.com/nextflow-io/hello.git
>Nov-03 09:47:10.799 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/dvdadmin/.nextflow/assets/nextflow-io/hello/.git/config; branch: master; remote: origin; url: https://github.com/nextflow-
>io/hello.git
>Nov-03 09:47:10.799 [main] INFO  nextflow.cli.CmdRun - Launching `nextflow-io/hello` [sleepy_jang] - revision: 6b9515aba6 [master]
>Nov-03 09:47:11.300 [main] DEBUG nextflow.Session - Session uuid: 44920c2c-ea6e-4ae9-8f53-f26439c7655c
>Nov-03 09:47:11.301 [main] DEBUG nextflow.Session - Run name: sleepy_jang
>Nov-03 09:47:11.302 [main] DEBUG nextflow.Session - Executor pool size: 24
>Nov-03 09:47:11.337 [main] DEBUG nextflow.cli.CmdRun - 
>  Version: 0.22.3 build 4095
>  Modified: 12-10-2016 09:31 UTC (11:31 CEST)
>  System: Linux 4.2.0-34-generic
>  Runtime: Groovy 2.4.7 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_80-b15
>  Encoding: UTF-8 (UTF-8)
>  Process: 17568@serveur-dev1 [10.9.206.111]
>  CPUs: 24 - Mem: 125.8 GB (9.2 GB) - Swap: 12.1 GB (12.1 GB)
>Nov-03 09:47:11.374 [main] DEBUG nextflow.Session - Work-dir: /mnt/isilon_cifs/test/work [cifs]
>Nov-03 09:47:11.375 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/dvdadmin/.nextflow/assets/nextflow-io/hello/bin
>Nov-03 09:47:11.563 [main] DEBUG nextflow.Session - Session start invoked
>Nov-03 09:47:11.567 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
>Nov-03 09:47:11.568 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
>Nov-03 09:47:11.733 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
>Nov-03 09:47:11.912 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
>Nov-03 09:47:11.913 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
>Nov-03 09:47:11.925 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
>Nov-03 09:47:11.928 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
>Nov-03 09:47:11.932 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus: 24; memory: 125.8 GB; pollInterval: 100ms; dumpInterval: 5m
>Nov-03 09:47:11.937 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
>Nov-03 09:47:11.938 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
>Nov-03 09:47:11.941 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
>Nov-03 09:47:12.024 [main] DEBUG nextflow.Session - >>> barrier register (process: sayHello)
>Nov-03 09:47:12.042 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > sayHello -- maxForks: 24
>Nov-03 09:47:12.076 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
>Nov-03 09:47:12.077 [main] DEBUG nextflow.Session - Session await
>Nov-03 09:47:12.110 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <sayHello> Poison pill arrived
>Nov-03 09:47:12.118 [Actor Thread 2] DEBUG nextflow.processor.StateObj - <sayHello> State before poison: StateObj[submitted: 4; completed: 0; poisoned: false ]
>Nov-03 09:47:12.335 [Actor Thread 5] INFO  nextflow.Session - [0a/12fb9e] Submitted process > sayHello (3)
>Nov-03 09:47:12.335 [Actor Thread 6] INFO  nextflow.Session - [8c/830987] Submitted process > sayHello (4)
>Nov-03 09:47:12.337 [Actor Thread 3] INFO  nextflow.Session - [39/965bf3] Submitted process > sayHello (1)
>Nov-03 09:47:12.342 [Actor Thread 4] INFO  nextflow.Session - [60/1fe888] Submitted process > sayHello (2)
>Nov-03 09:47:12.344 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - <sayHello> After stop
>Nov-03 09:47:12.420 [Thread-3] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.out
>Nov-03 09:47:12.423 [Thread-3] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.err
>Nov-03 09:47:12.425 [Thread-3] ERROR nextflow.processor.TaskProcessor - Error executing process > 'sayHello (3)'
>
>Caused by:
>  Process `sayHello (3)` terminated with an error exit status (1)
>
>Command executed:
>
>  echo 'Hello world!'
>
>Command exit status:
>  1
>
>Command output:
>  (empty)
>
>Work dir:
> /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf
>
>Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named: '.command.sh'
>Nov-03 09:47:12.431 [Thread-3] DEBUG nextflow.Session - Session aborted -- Cause: Process `sayHello (3)` terminated with an error exit status (1)
>Nov-03 09:47:12.431 [Thread-3] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.err
>Nov-03 09:47:12.431 [Thread-3] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.out
>Nov-03 09:47:12.434 [main] DEBUG nextflow.Session - Session await > processes completed
>Nov-03 09:47:12.435 [main] DEBUG nextflow.Session - Session await > done
>Nov-03 09:47:12.435 [main] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.err
>Nov-03 09:47:12.436 [main] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.out
>Nov-03 09:47:12.438 [Thread-3] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
>Nov-03 09:47:12.439 [Actor Thread 7] DEBUG nextflow.processor.TaskProcessor - <sayHello> Sending poison pills and terminating process
>Nov-03 09:47:12.445 [Actor Thread 7] DEBUG nextflow.Session - <<< barrier arrive (process: sayHello)
>Nov-03 09:47:12.606 [main] DEBUG nextflow.Session - Session destroyed

**Comment by pditommaso** [comment]
It looks French holidays are longer that Spanish one! :)

That's something that's not working properly. Please try to execute these commands: 

```
cd /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf
bash -x .command.run 
```

Then please include the printed output.

**Comment by chdem** [comment]
French holidays are longer I think....but too bad, we don't have the sun :)

Here the output : 
>+ set -e
>+ set -u
>+ NXF_DEBUG=0
>+ [[ 0 > 2 ]]
>+ trap on_exit EXIT
>+ trap on_term TERM INT USR1 USR2
>+ [[ 0 > 0 ]]
>+ touch /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.begin
>+ '[' -f /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.env ']'
>+ set +e
>+ COUT=/mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.po
>+ mkfifo /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.po
>mkfifo: cannot create fifo >‘/mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.po’: Operation not permitted
>+ CERR=/mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.pe
>+ mkfifo /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.pe
>mkfifo: cannot create fifo >‘/mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.pe’: Operation not permitted
>+ tee1=17937
>+ tee .command.out
>+ tee2=17938
>+ tee .command.err
>+ pid=17939
>+ wait 17939
>.command.run: line 58: /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.po: >No such file or directory
>.command.run: line 60: /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.pe: >No such file or directory
>+ wait 17937 17938
>+ on_exit
>+ exit_status=1
>+ printf 1
>+ set +u
>+ [[ -n /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.po ]]
>+ rm -f /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.po
>+ [[ -n /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.pe ]]
>+ rm -f /mnt/isilon_cifs/test/work/0a/12fb9effa90e72e90f2c0537e99bcf/.command.pe
>+ exit 1

I think the problem comes from the dir : `/mnt/isilon_cifs/` is a cifs mount and mkfifo is not authorized by default !
So I've added the option `sfu` in my mounting command and everything seems to be OK now !!!

Thank you for showing me how to trace errors in nextflow ! It is very useful !
;)

**Comment by pditommaso** [comment]
Great!
