### ISSUE TITLE
Azure batch: upload corrupts files?

### ISSUE THREAD

**Issue by meowcat** [nextflow-io/nextflow#2353]
## Bug report 

In an azure batch job, I am staging a directory containing a 2gb pickle, a 5gb gzip and a 12gb sqlite database and a few text files. (These act as immutable databases for the workflow.). Note: these files are very sparse and transfer within minutes

My machine running nextflow is an Ubuntu 20.04 workstation. 

The staged files are not binary identical to the source files. I verify this by downloading them by hand from the blob storage from the work/stage directory and running `fc /B` on Windows. (The error was discovered because the pickle can't be unpickled and the gz can't be unzipped). Note that the total file length is equal.

Strikingly, copying the exact same directory to the blob storage by hand does not reproduce the issue: Using `azcopy` obtained via `wget https://github.com/nextflow-io/azcopy-tool/raw/linux_amd64_10.8.0/azcopy`, I can run 

`./azcopy copy MYDIRECTORY "https://MYACCOUNT.blob.core.windows.net/msnovelist-blob/?MYSASKEY" --recursive`

Files copied this way and downloaded via MS Azure Storage Explorer are identical to the original files. If I stage the same directory as part of a Nextflow workflow, the files are reproducibly different (but not always identical. The same file staged twice resulted in two different uploaded versions, one differing after `0x100020D3` and the other differing after `0x10002073`.)

I figure this is something related to some bug handling sparse files?

### Expected behavior and actual behavior

Expected behaviour: the files should be binary identical
Observed behaviour: the files are identical until offset 0x10000000, briefly after (in one example: 0x100020D3; in another example: 0x10002073) they start to differ.

### Steps to reproduce the problem

See below, I added a reprex in the comments

### Environment 

* Nextflow version: 21.04.3.5560
* Java version: openjdk version "11.0.11" 2021-04-20
* Operating system: Ubuntu 20.04
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by meowcat** [comment]
# Reprex

Nextflow workflow, config, and a python script to generate a large file
https://gist.github.com/meowcat/be0f5cdf89b1d9f4cd02ed0b8b8ffd9d (obviously add your own Azure credentials)
Sample file `sample.bin`
https://filesender.switch.ch/filesender2/?s=download&token=99ed3e6d-0c1b-4579-8c99-2241f2b7f72d

# Running
`nextflow run azure_test.nf -w az://YOUR_AZURE_BLOBSTORE/work`

# Output
```

N E X T F L O W  ~  version 21.04.3
Launching `azure_test.nf` [nice_swirles] - revision: 694ffeb531
executor >  azurebatch (1)
[34/52592a] process > dummy_do_something (1) [100%] 1 of 1 ✔
914cc5797cb7a49537b67ece14447a78  uploaded.bin

Waiting files transfer to complete (1 files)

```
# Verification

```
> md5sum sample.bin                                     
939f29331327b525f30bc77d8d0a34b1  sample.bin
> md5sum upload_result/uploaded.bin
914cc5797cb7a49537b67ece14447a78  upload_result/uploaded.bin
```
Expected result: both md5sum should be same; observed result: the md5sums are different.

**Comment by meowcat** [comment]
Also; the download seems to work. Just the upload is not working.

**Comment by meowcat** [comment]
Reproduced on a completely different system and network

**Comment by fbdtemme** [comment]
I have recently experiences the same issue when staging a local gtf and fasta file to the workDir on azure blob storage.
The files get corrupted and are unusable.

**Comment by meowcat** [comment]
This is still not fixed! Just reproduced it on a fresh system and a fresh Azure account.

**Comment by meowcat** [comment]
Still not working on 22.10.4
