### ISSUE TITLE
Resubmit failed pods

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#2361]
Hello,

would it be possible to extend kuberun executor so that failed pods get resubmitted?

It can happen that pod is evicted for some reason, e.g. disk pressure, which is not permanent error and not error of pod itself. In such a case, pod should be resubmitted.

The corresponding error status looks like this:

```
"status": {​​​​​​​
          "phase": "Failed",
          "message": "The node was low on resource: ephemeral-storage. ",
          "reason": "Evicted",
          "startTime": "2021-10-04T11:53:32Z"
}​​​​​​​
```

**Comment by bentsherman** [comment]
Related to #2302 I think.

**Comment by xhejtman** [comment]
It does not seem to as the mentioned patch is already included in 21.09.0 version and it is still happening.

**Comment by pditommaso** [comment]
it will be included in the next release

**Comment by pditommaso** [comment]
Solved by f9db9cc77c718b4e5d9700359e0a2b8858fb4d5d

**Comment by phue** [comment]
I can confirm that `21.09.0-edge` it is not resubmitting evicted pods. This is particularly problematic with SPOT instances on AWS as they can be shutdown anytime

**Comment by xhejtman** [comment]
If the patch `f9db9cc` is changed to use NodeTerminationException instead of ProcessFailedException and this additional patch is applied:
```
diff --git a/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy b/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
index 402cb5d9..3d331028 100644
--- a/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
+++ b/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy
@@ -2111,7 +2111,7 @@ class TaskProcessor {
 
             if( task.type == ScriptType.SCRIPTLET ) {
                 if( task.exitStatus == Integer.MAX_VALUE )
-                    throw new ProcessFailedException("Process `${task.name}` terminated for an unknown reason -- Likely it has been terminated by the external system")
+                    throw new NodeTerminationException("Process `${task.name}` terminated for an unknown reason -- Likely it has been terminated by the external system")
 
                 if ( !task.isSuccess() )
                     throw new ProcessFailedException("Process `${task.name}` terminated with an error exit status (${task.exitStatus})")
```

pipeline survives probably all k8s issues including node reboot.
