### ISSUE TITLE
Task .command.log not saved by k8s executor 

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2364]
## Bug report 

The k8s executor doesn't save `.command.log` for each task. This matters because output from `beforeScript` and `afterScript` are not saved to `.command.out` or `.command.err`, so I can't capture outputs from these directives when using kubernetes. Task logs can be accessed via `kubectl logs <pod>` but pods are deleted upon completion.

I see that this functionality was added recently in the case of pod failures (#699), I think this behaviour should be extended to pod completions as well.

Alternatively we could change `beforeScript` and `afterScript` to also pipe into `.command.out` / `.command.err` but I think that would be more complicated.

### Environment 

* Nextflow version: 21.08-edge
* Java version: 1.8
* Operating system: Linux

**Comment by pditommaso** [comment]
For doing that, think the launcher command should be changed to something like 

```
bash .command.run 2>&1 | tee
```
