### ISSUE TITLE
Changes process directives should invalidate task cache on execution resume

### ISSUE THREAD

**Issue by mahesh-panchal** [nextflow-io/nextflow#2382]
### Expected behavior and actual behavior

When providing configuration settings via `process.ext.<something>`, updating the config and using `-resume` continues to use the cached version instead of the updated `ext.<something>` value. The expected behaviour is that when the config changes, the appropriate process is rerun. 

### Steps to reproduce the problem

`main.nf`:
```nextflow
#! /usr/bin/env nextflow

nextflow.enable.dsl = 2

workflow {

    FOO(params.message)

}

process FOO {

    input:
    val str

    script:
    def prefix = task.ext.prefix ?: 'prefix'
    """
    printf "%s\n", $str > ${prefix}.txt
    """
}
```
nextflow.config:
```nextflow
params.message = 'hello world'
process {
    withName: FOO {
        ext.prefix = 'hello'
    }
}
```

Steps to reproduce:
1. Run `nextflow run main.nf`
2. Update the `nextflow.config` to use `process.ext.prefix = hola`
3. Run `nextflow run main.nf -resume`

### Program output 

```console
$ nextflow run main.nf 
N E X T F L O W  ~  version 21.04.0
Launching `main.nf` [astonishing_mayer] - revision: 9021b457ad
executor >  local (1)
[b6/ca37d6] process > FOO [100%] 1 of 1 ✔

```
(edit `nextflow.config`) then:
```console
$ nextflow run main.nf -resume
N E X T F L O W  ~  version 21.04.0
Launching `main.nf` [nice_mandelbrot] - revision: 9021b457ad
[b6/ca37d6] process > FOO [100%] 1 of 1, cached: 1 ✔

```

### Environment 

* Nextflow version: 21.04.0
* Java version: openjdk 11.0.9.1 2020-11-04 LTS
* Operating system: macOS
* Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

### Additional context

The aim was to try and use `process.ext.args` in nf-core workflows to provide tool-specific parameters. 
See https://github.com/nf-core/rnaseq/pull/701 for more info.

**Comment by pditommaso** [comment]
This has been implemented as an experimental feature 62ded3421. 

The cache is invalidated when any task directive variable is modified by setting a new value via the nextflow config. 


This feature is considered experimental and needs to be enabled by setting the following variable 

```
export NXF_ENABLE_CACHE_INVALIDATION_ON_TASK_DIRECTIVE_CHANGE=true
```

**Comment by mahesh-panchal** [comment]
Is this in a new snapshot or how can I test this?

**Comment by pditommaso** [comment]
Yes, run first this command to refresh your snapshot copy 

```
NXF_VER=21.10.0-SNAPSHOT CAPSULE_RESET=true nextflow info
```

then 

```
NXF_VER=21.10.0-SNAPSHOT nextflow run .. etc
```

**Comment by pditommaso** [comment]
Changed this to default behaviour in the upcoming 21.12.0-edge. Therefore the change of any directive invalidates the tasks cache on resume by default. see 967c1adff.

The NXF_ENABLE_CACHE_INVALIDATION_ON_TASK_DIRECTIVE_CHANGE can still be used to turn this behaviour off.
