### ISSUE TITLE
Pull from Azure DevOps repositories uses project id as repository id 

### ISSUE THREAD

**Issue by sfehrmann** [nextflow-io/nextflow#2384]
## Bug report 

When using a Microsoft Azure DevOps repository, I don't manage to pull the workflow from the repository. As workflow I use a copy of "[Your first script](https://www.nextflow.io/docs/latest/getstarted.html#your-first-script)", see below. From the log, the repository id is misplaced in the path, while the project name is duplicated at the position where the repository id should be, see [MS azure devops REST-API description](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-6.0)

### Expected behavior and actual behavior

Expected  result 
```bash
nextflow run sfehrmann/nextflow-pipeline-prototypes/simple_nextflow_test.nf -r main -hub github

N E X T F L O W  ~  version 21.04.3
Launching `/home/username/scratches/nextflow_repo_testing/simple_nextflow_test.nf` [drunk_crick] - revision: cf654dd89a
executor >  local (3)
[2f/64730e] process > splitLetters       [100%] 1 of 1 ✔
[60/9a9339] process > convertToUpper (1) [100%] 2 of 2 ✔
WORLD!
HELLO
```
Actual result:
```bash
nextflow run ORGANIZATION/PROJECT/REPOSITORY_ID/nextflow_pipelines/simple_nextflow_test.nf -hub azurerepos
N E X T F L O W  ~  version 21.04.3
Pulling ORGANIZATION/PROJECT ...
Remote resource not found: https://dev.azure.com/ORGANIZATION/PROJECT/_apis/git/repositories/PROJECT/items?download=false&includeContent=true&includeContentMetadata=false&api-version=6.0&$format=json&path=REPOSITORY_ID/nextflow_pipelines/simple_nextflow_test.nf
```
Instead the target address should be
```
https://dev.azure.com/ORGANIZATION/PROJECT/_apis/git/repositories/REPOSITORY_ID/items?download=false&includeContent=true&includeContentMetadata=false&api-version=6.0&$format=json&path=nextflow_pipelines/simple_nextflow_test.nf
```

### Workflow to reproduce the problem
`simple_nextflow_test.nf`
```
#!/usr/bin/env nextflow

process splitLetters {

    output:
    file 'chunk_*' into letters

    """
    printf '${params.str}' | split -b 6 - chunk_
    """
}


process convertToUpper {

    input:
    file x from letters.flatten()

    output:
    stdout result

    """
    cat $x | tr '[a-z]' '[A-Z]'
    """
}

result.view { it.trim() }
```
nextflow.config
```
params.str = 'Hello world!'
```

### Environment 

* Nextflow version: 21.04.3
* Java version: openjdk version "11.0.11" 2021-04-20
* Operating system: Ubuntu 20.04
* Bash version: GNU bash, version 5.0.17(1)

### Additional context

[nextflow.public.log](https://github.com/nextflow-io/nextflow/files/7323439/nextflow.public.log)
Please apologize, I had to replace the actual names due to compliance

**Comment by sfehrmann** [comment]
After looking at the source code in [AzureRepositoryProvider.groovy](https://github.com/nextflow-io/nextflow/blob/c78965b4d4fabb89b11357c802776d56f0e2f588/modules/nextflow/src/main/groovy/nextflow/scm/AzureRepositoryProvider.groovy), I thought I could workaround the problem with a custom endpoint in the `scm` file, so I added to azurerepos:

```
endpoint = "https://dev.azure.com/ORGANIZATION"
```
and changed the call to 
```
nextflow run PROJECT/REPOSITORY_ID/nextflow_pipelines/simple_nextflow_test.nf -hub azurerepos
```
but now the `REPOSITORY_ID` is included in the base API address:
```
N E X T F L O W  ~  version 21.04.3
Pulling ORGANIZATION/PROJECT ...
Remote resource not found: https://dev.azure.com/ORGANIZATION/PROJECT/REPOSITORY_ID/_apis/git/repositories/REPOSITORY_ID/items?download=false&includeContent=true&includeContentMetadata=false&api-version=6.0&$format=json&path=nextflow_pipelines/simple_nextflow_test.nf
```
Clearly, I didn't understand how [project](https://github.com/nextflow-io/nextflow/blob/c78965b4d4fabb89b11357c802776d56f0e2f588/modules/nextflow/src/main/groovy/nextflow/scm/AzureRepositoryProvider.groovy#L38) was defined

**Comment by sfehrmann** [comment]
Cool, thanks. I will try and learn, but given my unfamilarity with groovy and the project, this week might be optimistic for a solution from my end...

**Comment by jorgeaguileraseqera** [comment]
ummm, it seems there is some bug in the core when calling the plugin and it requests the resource with the project into the path

let me check

**Comment by jorgeaguileraseqera** [comment]
Can you try prepending with the URL to azure (https://dev.azure.com/), please?

`nextflow run https://dev.azure.com/ORGANIZATION/PROJECT/REPOSITORY/main.nf -hub azurerepos`

**Comment by sfehrmann** [comment]
Hi @jorgeaguileraseqera, tried prepending https://dev.azure.com/ > not working as expected either:

```
nextflow run https://dev.azure.com/ORGANIZATION/PROJECT/REPOSITORY/main.nf -hub azurerepos
N E X T F L O W  ~  version 22.05.0-edge
Pulling ORGANIZATION/PROJECT/REPOSITORY/main.nf ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://dev.azure.com/ORGANIZATION/PROJECT/REPOSITORY/_apis/git/repositories/main.nf/items?download=false&includeContent=true&includeContentMetadata=false&api-version=6.0&$format=json&path=nextflow.config
Remote resource not found: https://dev.azure.com/ORGANIZATION/PROJECT/REPOSITORY/_apis/git/repositories/main.nf/items?download=false&includeContent=true&includeContentMetadata=false&api-version=6.0&$format=json&path=main.nf
```

Tried with the project's main repo (same project/repo name), but an nf subdirectory:
```
nextflow run https://dev.azure.com/SHS-CID-Global/PROJECT/PROJECT/nf/main.nf -hub azurerepos
N E X T F L O W  ~  version 22.05.0-edge
Pulling SHS-CID-Global/PROJECT/PROJECT/nf/main.nf ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://dev.azure.com/SHS-CID-Global/PROJECT/PROJECT/nf/_apis/git/repositories/main.nf/items?download=false&includeContent=true&includeContentMetadata=false&api-version=6.0&$format=json&path=nextflow.config
Remote resource not found: https://dev.azure.com/SHS-CID-Global/PROJECT/PROJECT/nf/_apis/git/repositories/main.nf/items?download=false&includeContent=true&includeContentMetadata=false&api-version=6.0&$format=json&path=main.nf
```

This works as expected:
```
nextflow run ORGANIZATION/PROJECT/nf/main.nf -hub azurerepos
N E X T F L O W  ~  version 22.05.0-edge
Pulling ORGANIZATION/PROJECT ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://dev.azure.com/ORGANIZATION/PROJECT/_apis/git/repositories/PROJECT/items?download=false&includeContent=true&includeContentMetadata=false&api-version=6.0&$format=json&path=nextflow.config
 downloaded from https://dev.azure.com/ORGANIZATION/PROJECT/_git/PROJECT
Launching `https://dev.azure.com/ORGANIZATION/PROJECT` [dreamy_brenner] DSL2 - revision: 77edf5a6d4 [master]
executor >  local (3)
[99/6ab433] process > splitLetters       [100%] 1 of 1 ✔
[2c/82262d] process > convertToUpper (1) [100%] 2 of 2 ✔
WORLD!
HELLO
```

This however, does not
```
nextflow run https://dev.azure.com/ORGANIZATION/PROJECT/nf/main.nf -hub azurerepos
N E X T F L O W  ~  version 22.05.0-edge
Pulling ORGANIZATION/PROJECT/nf/main.nf ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://dev.azure.com/ORGANIZATION/PROJECT/nf/_apis/git/repositories/main.nf/items?download=false&includeContent=true&includeContentMetadata=false&api-version=6.0&$format=json&path=nextflow.config
Remote resource not found: https://dev.azure.com/ORGANIZATION/PROJECT/nf/_apis/git/repositories/main.nf/items?download=false&includeContent=true&includeContentMetadata=false&api-version=6.0&$format=json&path=main.nf
```

It would be great to support subdirectories, fmpov azure devops repositories require a path with three segments. Maybe @t-neumann has different opinion on that?

**Comment by jorgeaguileraseqera** [comment]
As a temporary solution, and as `main.nf` it's the default file that will try to run you can omit it and run

`nextflow run https://dev.azure.com/ORGANIZATION/PROJECT/REPOSITORY -hub azurerepos`

(remember to remove `$HOME/.nextflow/assets/ORGANIZATION` directory)

**Comment by sfehrmann** [comment]
> As a temporary solution, and as `main.nf` it's the default file that will try to run you can omit it and run
> 
> `nextflow run https://dev.azure.com/ORGANIZATION/PROJECT/REPOSITORY -hub azurerepos`

Cool, that works! That is, at least as long as the `main.nf` is in the repository root (which is of course not the case for our principal repo...)
```
nextflow run https://dev.azure.com/ORGANIZATION/PROJECT/REPOSITORY
```
