### ISSUE TITLE
Installation fails to recognize latest Ubuntu java version 17

### ISSUE THREAD

**Issue by myourshaw** [nextflow-io/nextflow#2387]
## Bug report 

(Is there some workaround for using Java 17 with the current version of nextflow?)

### Expected behavior and actual behavior

(Expect installation to recognize latest Ubuntu java version 17. Instead get ERROR)

### Steps to reproduce the problem
(
`curl -s https://get.nextflow.io > nextflow  | bash`
)

### Program output 
(
`ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 or later is installed
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /usr/bin/java
 JAVA_HOME: `
)

### Environment 

* Nextflow version: [21.04.3] 
* Java version: [openjdk version "17" 2021-09-14]
* Operating system: [Linux]
* Bash version: (`5.1.4(1)-release (x86_64-pc-linux-gnu)`)

### Additional context

(The following might be expected to fix the problem, but executing the nextflow script reverts the script to the original versions
`
sed -i.bak 's/9|10|11|12|13|14|15)"/9|10|11|12|13|14|15|16|17)"/' nextflow
`
The nextflow code for v21.08.0-edge goes up to java 16, but java 17 is what Ubuntu will now install.
)

**Comment by pditommaso** [comment]
Support for Java 17 has been added 

https://github.com/nextflow-io/nextflow/blob/c25bc355de078a3e5d3a66b536c5f577e031e47b/nextflow#L303-L303
