### ISSUE TITLE
Tmp directories are not deleted properly under `/dev/shm`

### ISSUE THREAD

**Issue by lukasjelonek** [nextflow-io/nextflow#2395]
### Expected behavior and actual behavior

We observed that nextflow does not remove the temporary directories under `/dev/shm` on our machines, although it should.

### Steps to reproduce the problem

```
# cleanup all previous tmp data
rm -rf /dev/shm/nxf.*

# run any workflow
nextflow run hello

# wait to end and check for files
ls -ll /dev/shm/nxf.*
```

### Program output 

Nothing relevant

### Environment 

* Nextflow version: 21.04.1
* Java version: 15.0.2
* Operating system: Linux
* Bash version: GNU bash, version 5.0.17(1)-release

### Additional context

I checked the generated command run scripts and found that the data is not deleted du to an local marked variable that is used in a global context. By removing the `local` keyword the temporary data is deleted correctly, see: https://github.com/lukasjelonek/nextflow/commit/21ac1c3eace0f7567b675e1e0ea62a68e3b6e66c

I tested the code manually and it worked on my linux machine. As I don't know how to integrate a test for the run script in nextflow it would be good if someone can point out if a test is required and how I can add one to nextflow, perhaps with a pointer to an already existing test for the run script.

**Comment by pditommaso** [comment]
Solved. This patch is available as for version 21.09.1-edge. Thanks for contributing
