### ISSUE TITLE
kuberun executor does not support -entry pipeline parameter

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#2397]
Some pipelines need to specify entry point via -entry cmdline parameter, e.g. scenic pipeline. This option is not supported/implemented in kuberun executor. As this is trival patch, please add it:
```
--- K8sDriverLauncher.groovy.orig	2021-09-30 13:17:44.595213768 +0200
+++ K8sDriverLauncher.groovy	2021-10-18 23:37:14.925102448 +0200
@@ -424,6 +424,7 @@
         addOption(result, cmd.&env )
         addOption(result, cmd.&process )
         addOption(result, cmd.&params )
+        addOption(result, cmd.&entryName )
 
         if( paramsFile ) {
             result << "-params-file $paramsFile"
```

**Comment by pditommaso** [comment]
Feel free to send a pull request

**Comment by xhejtman** [comment]
https://github.com/nextflow-io/nextflow/pull/2525

**Comment by abhi18av** [comment]
Closing this as the linked PR is now merged - thanks for the contribution 🎉 !
