### ISSUE TITLE
nextflow run hello appears not to work

### ISSUE THREAD

**Issue by holtgrewe** [nextflow-io/nextflow#24]
Calling `nextflow run hello` gets stuck with the message `Pulling nextflow-io/hello ...`.

A common problem with my work environment is that I need to configure a proxy. Apparently, nextflow does not pick up the environment variables `HTTP_PROXY` and `HTTPS_PROXY`. How can I configure a proxy to use for the `nextflow run hello` command?

**Comment by tbugfinder** [comment]
Would it also be possible to get/apply NO_PROXY settings?

**Comment by pditommaso** [comment]
Please report as a separate feature request.
