### ISSUE TITLE
New feature `workflow.conda` which works like `workflow.containers`

### ISSUE THREAD

**Issue by mahesh-panchal** [nextflow-io/nextflow#2419]
## New feature

It would be nice if there were a workflow introspection property called `workflow.conda`. It would work in the same way 
as `workflow.container` and return a list of conda environments (paths, strings, yaml file - whatever was supplied to the `process.conda` directive).

There's no way to check from the main script at the moment if a process uses conda.

## Usage scenario 

The primary purpose of this feature is to allow one to check from the main script, that `conda` has been correctly
configured if it's been used. For example, that the channels are in the correct order. Nf-core currently implements a function 
for this (https://github.com/nf-core/tools/blob/b48bce26b7da46cb71e4a8f78b68d9ceac579ca6/nf_core/pipeline-template/lib/Utils.groovy#L12-L39)

## Suggest implementation 

Related: 
- [Container line in WorkflowMetadata.groovy](https://github.com/nextflow-io/nextflow/blob/7f91ecb39618b1327d5dc3d7aac9f9049159baff/modules/nextflow/src/main/groovy/nextflow/script/WorkflowMetadata.groovy#L233)
- [fetchContainers in Session.groovy](https://github.com/nextflow-io/nextflow/blob/7f91ecb39618b1327d5dc3d7aac9f9049159baff/modules/nextflow/src/main/groovy/nextflow/Session.groovy#L1182-L1212)

**Comment by grst** [comment]
How does that relate to @drpatelh's suggestion to have a `conda.enabled` config options? Do we need a separate issue for that?

**Comment by mahesh-panchal** [comment]
Yes, we should have another issue.
