### ISSUE TITLE
AWS Batch fails to override the CPU and Memory of a job when using job-definition:// style

### ISSUE THREAD

**Issue by spitz-dan-l** [nextflow-io/nextflow#2421]
## Bug report 

Recently a Nextflow bug was fixed in which AWS Batch jobs were not having their CPU and Memory correctly overridden by nextflow. This would lead to the following error notices in the AWS Console:

> Configuration conflict
> This value was submitted using containerOverrides.vcpus which has been deprecated and was not used as an override. Instead, the VCPU value found in the job definition’s resourceRequirements key was used instead. More information about the deprecated key can be found in the AWS Batch API documentation. 

That bug appears to have been fixed, but not when the nextflow process container uses the `job-definition://` style.

E.g. in nextflow.config:

```
process.container = 'my_docker_image:latest' // works
process.container = 'job-definition://my_job_definition' // bug is back
```

I need to be able to use the `job-definition://` style.

Thank you!

**Comment by pditommaso** [comment]
Solved by 1cf2c379c
