### ISSUE TITLE
Accessing to a not defined script params should raise an error

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#243]
For example: 

```
x = params.foo 
``` 

Currently if `foo` is not defined `x` will be set to `null`. An error should be raised to avoid undefined behaviour.

**Comment by pditommaso** [comment]
@emi80  @ewels @viklund Comments ?

**Comment by ewels** [comment]
Yup, I think that makes sense. As in [my other comment](https://github.com/nextflow-io/nextflow/issues/242#issuecomment-259977929), as long as you can use `when` in a process to detect undefined `params` (or another mechanism) then raising an error is fine.

Note that at the moment, I'm wrapping processes in big `if` statements, which works but is ugly.

**Comment by pditommaso** [comment]
No, this will raise an exception also in the `when` statement. I think it's a good practice to define all parameters with a default value on top of the script, eg. 

```
params.foo = false
```

**Comment by ewels** [comment]
Ok, thanks for the clarification, makes sense. That's actually what I was doing before, but I ran into the problem in #242.

**Comment by pditommaso** [comment]
Included in version `0.22.5`
