### ISSUE TITLE
Task completion percentage

### ISSUE THREAD

**Issue by cjw85** [nextflow-io/nextflow#2440]
## Bug report 

I freely admit this is a little pedantic! 😄 

### Expected behavior and actual behavior

Nextflow's logging reports a percentage of tasks complete. The percentage is rounded in a way that allows it to become 100% before all tasks have finished, e.g.:

```
[15/cb1229] process > clair3:evaluate_candidates (455)                 [100%] 460 of 461, failed: 3, retries: 3
```

I would argue "100% complete" has rather special meaning and so shouldn't be used until all jobs have completed. The fractional value should be floored so a maximum of 99% is shown until all jobs have completed.

### Environment 

* Nextflow version: 20.10.0 
* Java version: openjdk version "1.8.0_282"
* Operating system: Linux
* Bash version: GNU bash, version 4.3.48(1)-release

### Additional context

None

**Comment by pditommaso** [comment]
Guess. it's a matter of using `floor` instead of `round` 

https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy#L382-L382

**Comment by pditommaso** [comment]
Solved
