### ISSUE TITLE
`cpus` and `clusterOptions` directives do not evaluate 

### ISSUE THREAD

**Issue by huguesfontenelle** [nextflow-io/nextflow#245]
Having a `settings.config` as this:
```
process {
    executor='slurm'

    $mapping {
        clusterOptions = "--account=hugues  --mem-per-cpu=3140"
        time = '1h * task.attempt'
    }
}
```
works as intended.
but
```
cpus = '6 * task.attempt'
```
does not: `ERROR nextflow.processor.TaskProcessor Caused by: For input string: "6 * task.attempt"`
Similarly, `clusterOptions` is sent as string to the executor without evaluation.

**Comment by huguesfontenelle** [comment]
I believe this is explained in `src/main/groovy/nextflow/executor/SlurmExecutor.groovy`:
```
        if( task.config.cpus > 1 ) {
            result << '-c' << task.config.cpus.toString()
        }

        if( task.config.time ) {
            result << '-t' << task.config.getTime().format('HH:mm:ss')
        }
```
where `getTime()` does the job, but there isn't an equivalent `getCpus()`.

**Comment by pditommaso** [comment]
Nope, in groovy `.attribute` implicitly invokes `.getAttribute()` getter. 

The problem is that dynamic directives only works in the config by using the extended syntax i.e. by wrapping in a closure. Thus the following *should* work: 

```
process {
    executor='slurm'

    $mapping {
        clusterOptions = "--account=hugues  --mem-per-cpu=3140"
        time = { '1h * task.attempt' }
    }
}
```

If it doesn't, please comment here because it would be a bug.

**Comment by huguesfontenelle** [comment]
Yes it does, in that form or the one I wrote. But 
```
cpus = '6 * task.attempt'
```
does not.

**Comment by pditommaso** [comment]
Do you mean in the configuration file? 

It should be `cpus = {6 * task.attempt}`. 

Also I realised there was a typo in my comment. It should be `time = { 1h * task.attempt }` without quote

**Comment by huguesfontenelle** [comment]
Thanks for the help. I struggled a bit with typos on this one, but it is now fixed. So the code is right :-)

**Comment by ewels** [comment]
If it helps, I wrote the same thing into our pipeline config today - testing it currently, but seems to work so far. You can see the config file here: https://github.com/ewels/NGI-RNAseq/blob/master/conf/uppmax.config
