### ISSUE TITLE
PublishDir directive not overwriting files

### ISSUE THREAD

**Issue by vpresnyakLM** [nextflow-io/nextflow#2455]
### Expected behavior and actual behavior

I have a set of processes with `publishDir` directives to produce files in a GCP bucket (using GLS executor). Expected behavior is for these to overwrite existing files on first execution of a pipeline, or when `overwrite: true` option is set. Notably, this only occurs with 21.10.0 - using `NXF_VER=21.04.3 nextflow run ...` does not display the same behavior.

### Steps to reproduce the problem

Any process that writes to GCP has been displaying this for me!

### Program output 

Here is a log entry for a sample failed transfer - the error is the same every time:

> Nov-18 15:49:38.185 [FileTransfer-thread-36] WARN  nextflow.processor.PublishDir - Failed to publish file: /default_workdir/bf/52e8193d99fd083b0c2295e79f585e/S02341_coverage.csv; to: /VP_testing/results/clusters/S02341_coverage.csv [copy] -- See log file for details
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 412 Precondition Failed
> POST https://storage.googleapis.com/storage/v1/b/bkt/o/default_workdir%2Fbf%2F52e8193d99fd083b0c2295e79f585e%2FS02341_coverage.csv/rewriteTo/b/bkt/o/VP_testing%2Fresults%2Fclusters%2FS02341_coverage.csv?ifGenerationMatch=0&projection=full
> {
>   "code" : 412,
>   "errors" : [ {
>     "domain" : "global",
>     "location" : "If-Match",
>     "locationType" : "header",
>     "message" : "At least one of the pre-conditions you specified did not hold.",
>     "reason" : "conditionNotMet"
>   } ],
>   "message" : "At least one of the pre-conditions you specified did not hold."
> }
> 	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
> 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
> 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428)
> 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
> 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.rewrite(HttpStorageRpc.java:1030)
> 	at com.google.cloud.storage.spi.v1.HttpStorageRpc.openRewrite(HttpStorageRpc.java:970)
> 	at com.google.cloud.storage.StorageImpl$15.call(StorageImpl.java:636)
> 	at com.google.cloud.storage.StorageImpl$15.call(StorageImpl.java:633)
> 	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
> 	at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
> 	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
> 	at com.google.cloud.storage.StorageImpl.copy(StorageImpl.java:632)
> 	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.copy(CloudStorageFileSystemProvider.java:684)
> 	at nextflow.file.FileHelper.copyPath(FileHelper.groovy:924)
> 	at nextflow.processor.PublishDir.processFileImpl(PublishDir.groovy:371)
> 	at nextflow.processor.PublishDir.processFile(PublishDir.groovy:303)
> 	at nextflow.processor.PublishDir.safeProcessFile(PublishDir.groovy:289)
> 	at jdk.internal.reflect.GeneratedMethodAccessor527.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
> 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
> 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
> 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
> 	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
> 	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
> 	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
> 	at nextflow.processor.PublishDir$_apply1_closure1.doCall(PublishDir.groovy:262)
> 	at nextflow.processor.PublishDir$_apply1_closure1.call(PublishDir.groovy)
> 	at groovy.lang.Closure.run(Closure.java:493)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)

### Environment 

* Nextflow version: 21.10.0.5640 
* Java version: openjdk 11.0.11
* Operating system: Ubuntu 20.04
* Bash version: GNU bash, version 5.0.17(1)-release

### Additional context

Have tried running this from my local Mac or from GCP VMs, same results in both places!

**Comment by pditommaso** [comment]
Hi, thanks for reporting. This looks a problem caused by the recent version of Google Storage library used by NF. Looking for alternatives

**Comment by pditommaso** [comment]
Reported an issue for this in the corresponding project https://github.com/googleapis/java-storage-nio/issues/762
