### ISSUE TITLE
task.stub==true if no `stub:` block is defined.

### ISSUE THREAD

**Issue by lindenb** [nextflow-io/nextflow#2466]
## New feature

Hi all,
in stub-mode, it would be nice to have a boolean variable `${task.stub}` (or workflow.stub ?) set to true if no `stub:` block is defined.

## Usage scenario 

```
process samtobam {
(...)
script:
"""
samtools view -h ${in}  ${task.stub?"  | head -n 10000 ":""} | samtools view -O BAM -o output.bam
"""
/// no stub block defined here.
}
```

that would avoid to copy+paste the `script:` block in a `stub:` block in order to have a similar yet smaller result

**Comment by abhi18av** [comment]
Good point, at the moment it is a bit cumbersome to write two blocks.

However, ths approach highlighted in the opening comment might lead to a convoluted `script` section, no?

Using the `stub`, there is a visual demarcation between these blocks.
