### ISSUE TITLE
Ignore `NXF_EDGE` if edge is older than latest release

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#2467]
## Usage scenario 

In the nf-core CI testing, we want to test pipelines with the absolute latest version of Nextflow to ensure that the pipeline will work with any upcoming releases. So we use `NXF_EDGE` for this. However, sometimes the edge release of Nextflow is actually older than the most recent stable release, which has nasty unintended effects. As such, we're forced to manually comment out and re-comment the `NXF_EDGE` variable in our CI over time as the releases come and go.

## Suggest implementation 

If `NXF_EDGE` is specified, take the latest stable release or the latest edge release - which ever is most recent.

**Comment by pditommaso** [comment]
Hi Phil, this is expected. Edge is meant to be a channel *parallel* to stable, therefore if you are using egde, not necessarily want to update to stable

**Comment by ewels** [comment]
Feature, not a bug.. Hmm ok, any ideas how we can achieve what we're aiming for here? _"Give me the latest version of Nextflow possible"_

We always used to just test on the minimum required and latest stable version, but it's nice to test against the upcoming release if possible to catch things before it drops. And I'd prefer not to run every test against three Nextflow versions for every push if possible...

**Comment by pditommaso** [comment]
> it's nice to test against the upcoming release if possible 

Indeed. Therefore you should a test with latest stable ie. 

```
curl get.nextflow.io | bash
```

and another for latest edge 

```
export NXF_EDGE=1
curl get.nextflow.io | bash
./nextflow -self-update

```

**Comment by ewels** [comment]
..and again with the stated minimum version. Ok, so no way around running more CI tests then. I think we just continue to not test edge unless we have to then.
