### ISSUE TITLE
[DSL2] `include` no longer works for custom methods in 21.10.0+

### ISSUE THREAD

**Issue by ArtemSokolov** [nextflow-io/nextflow#2469]
## Bug report 

It seems that custom methods imported via `include` are no longer being recognized.

### Steps to reproduce the problem

**util.nf**

``` groovy
// Simple test function to import
def test(f) {
    f.getBaseName()
}
```

**main.nf**
``` groovy
nextflow.enable.dsl=2

include {test} from './util'

workflow {
    Channel.fromPath("*.nf")
        .map{ test(it) }
        .view()
}
```

### Program output 

The above example works in 21.04.3, but not in 21.10.0+

``` bash
$ NXF_VER=21.04.3 nextflow main.nf

N E X T F L O W  ~  version 21.04.3
Launching `main.nf` [naughty_kalam] - revision: 116ef3a34f
util
main

$ NXF_VER=21.10.0 nextflow main.nf

N E X T F L O W  ~  version 21.10.0
Launching `main.nf` [stoic_davinci] - revision: 116ef3a34f
Unknown method invocation `test` on process type

 -- Check script 'main.nf' at line: 7 or see '.nextflow.log' file for more details
```

(Same error for `NXF_VER=21.10.3`)

**Comment by pditommaso** [comment]
This looks a regression caused by Groovy runtime. It works as expected when using with NF `21.08.0-edge` which uses `Groovy 3.0.8` instead of the latest `Groovy 3.0.9`. 

Looking for a solution

**Comment by pditommaso** [comment]
I suspects that's a side effect of this change https://github.com/apache/groovy/pull/1577

**Comment by pditommaso** [comment]
Solved by 6adfce099ecf3c835e03d1a2eb98ea81d0540019

**Comment by pditommaso** [comment]
I'll uploaded a new release by tomorrow.

**Comment by pditommaso** [comment]
Here it is https://github.com/nextflow-io/nextflow/releases/tag/v21.10.4
