### ISSUE TITLE
storeDir does not work with S3 targets

### ISSUE THREAD

**Issue by jbyars** [nextflow-io/nextflow#247]
If I set `storeDir 's3://nextflow-output'`, nextflow can correctly check if an output file exists. However, when it comes time to copy output to the `storeDir` location, the end of the .command.run script becomes
```
mkdir -p /nextflow-output
cp -fRL output_files* /nextflow-output || true
```
Naturally, creating a top-level folder without running as root, creates a permissions problem in most situations and is not the intended behavior. Can we please do something about this? 

On a similar note, when using `publishDir` and `scratch true`, there is a similar copy operation back to the work directory before copying to S3. Because the copy is to the shared work directory, there is no permissions error, however the idea in both cases was to not copy large data to the shared work directory.
I understand now the copy back is needed for downstream processing. That should be a conversation for a feature request later. 

Tested on 0.22.4 and 0.22.5-SNAPSHOT build 4113

**Comment by pditommaso** [comment]
Hi Jason, thanks for your feedback. This is clearly a bug. I will provide a patch at my earliest convenience.

**Comment by pditommaso** [comment]
This issue requires #265
