### ISSUE TITLE
Support for Slurm Multi-Clusters feature

### ISSUE THREAD

**Issue by marcodelapierre** [nextflow-io/nextflow#2477]
Hi,

just opening this one not to lose some tweeting that happened today with @pditommaso and @philippbayer .

The Slurm scheduer offers "multi-cluster" capabilities, to submit and monitor jobs across clusters, see
https://slurm.schedmd.com/multi_cluster.html

Here is an in-house hard-coded implementation in Nextflow, to enable submitting to additional clusters:
https://support.pawsey.org.au/documentation/display/US/Hack+Nextflow+for+multi-cluster+workflows

This should be easily generalisable in Nextflow, by adding capability to handle the `--clusters`/`-M` flag for commands like `sbatch`, `squeue` and `scancel`.

**Comment by pditommaso** [comment]
This was already discussed in the past. Just linking relevant issues for context #807 #2101 #2473

**Comment by marcodelapierre** [comment]
I think there are two interesting possible outcomes here:

1. an implementation using `--clusters` for `sbatch`, `squeue` and `scancel`, generalising my hack in the link above - seems small work

2. the implementation of nested `env` definitions within named/tagged processes, as proposed by my colleague @knservis, which could serve wider purposes - question here for @pditommaso , how much work do you estimate for this one?

**Comment by marcodelapierre** [comment]
I think there are two interesting possible outcomes here:

1. an implementation using `--clusters` for `sbatch`, `squeue` and `scancel`, generalising my hack in the link above - seems small work

2. the implementation of nested `env` definitions within named/tagged processes, as proposed by my colleague @knservis, which could be a more flexible, general purpose functionality - question here for @pditommaso , how much work do you estimate here?

**Comment by pditommaso** [comment]
If I remember correctly it's also possible to use the `SLURM_CLUSTERS` environment variable. What's the limit of this approach?

**Comment by knservis** [comment]
Hi @pditommaso ,

I mentioned it in the other ticket. You cannot override Env for a process as far as I can tell.

**Comment by marcodelapierre** [comment]
@pditommaso , when setting `SLURM_CLUSTERS` prior to a Nextflow run, ALL tasks will be submitted in that cluster.

That's quite limiting, in that in a multi-cluster infrastructure, people may need to send some tasks to one cluster, some tasks to another one (for instance, if all GPU nodes are in a specific cluster, or all high-memory nodes).

That's where it gets powerful to have a `cluster` property that is process specific
(which can be implemented with the `--clusters`/`-M` flag for `sbatch`, `squeue` and `scancel`)

**Comment by pditommaso** [comment]
Ok, now understand. This would require changing `sbatch`, `squeue` and `scancel` adding the corresponding cluster option and value, which is doable tho not trivial. 

Does this option alter the output of the `squeue` command afaik? 

What I'm not sure about is the opportunity to add a new `cluster` directive. Looking in the changes made for #807, I've realised there was an implementation that was fetching the `--cluster` option from the [clusterOptions](https://www.nextflow.io/docs/latest/process.html#clusteroptions) directive. See 8c4849012

**Comment by marcodelapierre** [comment]
as far as I know, when using `-M`/`--clusters`, the default output of `squeue` starts with an additional line:
```
CLUSTER: <cluster name>
```

**Comment by knservis** [comment]
@pditommaso I have tried to work around this using this trick:
https://github.com/nextflow-io/nextflow/blob/1b7725a2855074cabac406d17a85cbd3ce426a78/modules/nextflow/src/main/groovy/nextflow/executor/SlurmExecutor.groovy#L194 

That is you can add a fixed string as suffix.

**Comment by pditommaso** [comment]
This makes the thing more complicated because we need to track both job id and cluster name in each Task handler. 

I'll suggest the following:

1. decouple this logic into a separate executor class e.g. SlurmMultiClasterExcutor since I think it would be better to keep as opt-in feature at least the beginning

2. start collecting `squeue` outout and create the corresponding tests for 
   * test queue status, [like this](https://github.com/nextflow-io/nextflow/blob/fix-fileporter-deadlock/modules/nextflow/src/test/groovy/nextflow/executor/SlurmExecutorTest.groovy#L218-L229)
   *  test parse job id, [like this](https://github.com/nextflow-io/nextflow/blob/fix-fileporter-deadlock/modules/nextflow/src/test/groovy/nextflow/executor/SlurmExecutorTest.groovy#L33-L47)  
   * test `scancel`command, etc

**Comment by svandenhaute** [comment]
Any updates on this? I feel like this is hugely important for any mixed CPU-GPU workflow. Isn't it common practice for HPCs to organize GPU-enabled nodes in separate clusters?

**Comment by knservis** [comment]
Hi @svandenhaute , I did not have time to look into this again. I got stuck diagnosing an issue where nextflow loses track of the tasks after a few minutes, but the code was sufficiently complicated that I ran out of time for this.
