### ISSUE TITLE
SLURM partition issues with nextflow version 0.22.5.4102

### ISSUE THREAD

**Issue by rekepalli** [nextflow-io/nextflow#248]
Hi:
I am having trouble with submitting jobs using SLURM scheduler. Executor. queue is not detecting SLURM -p option. Please help.
Thanks,
Bhanu

Config file:

```
executor {
    name = 'slurm'
    queueSize = 10
    queue = 'normal'
    cpus = 24
}
```

Error:
```
nextflow run bwa.nf
N E X T F L O W  ~  version 0.22.5
Launching `bwa.nf` [grave_galileo] - revision: 294dbea91a
[warm up] executor > slurm
ERROR ~ Error executing process > 'bwa (20)'

Caused by:
  Failed to submit job to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  
  -----------------------------------------------------------------
            Welcome to the HIKARI Supercomputer          
  -----------------------------------------------------------------
  
  --> Submission error: all jobs must have a queue name specified with "-p"
 ```

**Comment by pditommaso** [comment]
There's a mistake in your configuration file. It should be: 

```
process {
    name = 'slurm'
    queue = 'normal'
    cpus = 24
}

executor {
    queueSize = 10
}
```

**Comment by rekepalli** [comment]
Hi Paolo,
When I changed my configuration file as you suggested, Nextflow is launching jobs on local node as shown below.
Please advise .
Bhanu

process {
    name = 'slurm'
    queue = 'normal'
    cpus = 24
}

executor {
    queueSize = 10
}
login1.hikari(66)$ /home/01332/brekepal/nextflow/nextflow-0.22.5/nextflow run bwa1.nf 
N E X T F L O W  ~  version 0.22.5
Launching `bwa1.nf` [zen_lichterman] - revision: ca106db96c
WARN: Configuration for directive `name` for process `bwa`
[warm up] executor > local
[3a/199f7b] Submitted process > bwa (8)
[a2/4f5f11] Submitted process > bwa (6)
[e7/4e9e97] Submitted process > bwa (3)

**Comment by pditommaso** [comment]
Oops, my fault in that way is running locally (!) 

Use this: 

```
process {
    executor = 'slurm'
    queue = 'normal'
    cpus = 24
}

executor {
    queueSize = 10
}
```

**Comment by rekepalli** [comment]
thanks, Paolo. 
That fixed the partition problem. Now the scheduler is not identifying total core count. Please see error below.

/home/01332/brekepal/nextflow/nextflow-0.22.5/nextflow run bwa1.nf 
N E X T F L O W  ~  version 0.22.5
Launching `bwa1.nf` [sleepy_engelbart] - revision: ca106db96c
[warm up] executor > slurm
ERROR ~ Error executing process > 'bwa (7)'

Caused by:
  Failed to submit job to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  
  --> Submission error: please define total core count with the "-n" option

**Comment by pditommaso** [comment]
Um, this a requirement specific to your cluster installation. You can provide are extra SLURM settings by using the `clusterOptions` attribute eg: 

process {
    executor = 'slurm'
    queue = 'normal'
    cpus = 24
    clusterOptions = '-n something'
}

executor {
    queueSize = 10
}

**Comment by rekepalli** [comment]
that works, thanks a bunch for your suggestions.
Regards,
Bhanu

**Comment by pditommaso** [comment]
👍

**Comment by pditommaso** [comment]
BTW if you are using a supercomputer, you also give a try to the Ignite executor as described here 
https://www.nextflow.io/blog/2015/mpi-like-execution-with-nextflow.html

**Comment by rekepalli** [comment]
I did not get to Apache Ignite documentation yet, but that is the plan. I am really enjoying reading through the documentation and testing Nextflow. Thanks a lot for sharing the link.

Quick question, all applications I am running on this supercomputer are bioinformatics applications  which are not MPI compatible but have threaded options. 
Does Ignite launch multi-node jobs and does a thread pinning to cores? For example I want to run 100s of BWA runs with 6 threads each on a 24 core node in the cluster. Does apache ignite or Nextflow launch 4 BWA processes per node and distributes jobs across various nodes in a given job?

**Comment by pditommaso** [comment]
Yes, of course. The only requirement is that the node must used exclusively by NF (exactly for the reason you are pointing out).
