### ISSUE TITLE
Replace static Azure machine types with API based discovery

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#2484]
The Azure plugin determines the available machine types by using a set of json files included as plugin static resources. 

https://github.com/nextflow-io/nextflow/tree/master/plugins/nf-azure/src/resources/nextflow/cloud/azure#L263-L263

However, this requires a to periodically update those files and release a new version of the plugin whenever a new machine type is made available. 

The goal of this issue is to replace the JSON files is to retrieve the available machine types using the Azure API, cache this information for some hours (1 day?) in the `$HOME/.nextflow/azure` directory

**Comment by abhi18av** [comment]
Closing this one as it's captured here https://github.com/nextflow-io/nextflow/issues/2994 (with more context).
