### ISSUE TITLE
Support of Amazon EBS

### ISSUE THREAD

**Issue by Galithil** [nextflow-io/nextflow#249]
Nextflow supports EFS, but EFS is not available in eu-central-1 (Germany). EBS is available everywhere, and also, cheaper to use.

Would it be possible to use EBS instead of EFS for AWS based pipelines ?

**Comment by pditommaso** [comment]
EBS support can be useful, but EBS volumes cannot be shared across multiple Ec2 instances, thus you cannot use them as a replacement for EFS storage.

**Comment by Galithil** [comment]
You cannot share them between two running instances, sure, but you could
use it in a linear pipeline. I guess this is too much of an edge case to be
interesting, though.

**Comment by pditommaso** [comment]
What do you mean by a linear pipeline? Using just one instance?

**Comment by Galithil** [comment]
using the same instance multiple times, or using one static instance.

**Comment by pditommaso** [comment]
This would be useful to access public dataset published as EBS volumes. See
https://aws.amazon.com/public-datasets/

**Comment by nephantes** [comment]
How is starcluster mounting EBS to multiple instances?
http://star.mit.edu/cluster/docs/0.93.3/manual/volumes.html
It mounts ebs volumes to all nodes in starcluster.

**Comment by pditommaso** [comment]
StarCluster installs a NFS daemon in a node where the EBS is mounted. But it's a flawed approach, it does not scale.

**Comment by nephantes** [comment]
But it is better then EFS I guess. EFS doesn't scale too. When I start multiple instances write to EFS storage. It fails as well. When I have only one node it works.

**Comment by pditommaso** [comment]
Definitely not. In my experience a NFS daemon in single instance can barely handle 5-10 clients. EFS is supposed to be scaled, but frankly I never tested under heavy loads.

**Comment by tbugfinder** [comment]
IMHO, EFS scales and supports provisioned IOPS.

**Comment by nephantes** [comment]
Don't know, we have tried with ~30 instances that writes different folders on the same EFS. Just "ls" took a couple of minutes. Maybe there were some other problems but this was the experience I got. To test this I started another EFS in another zone and I'll let you know, if it gets better for the same runs.

**Comment by pditommaso** [comment]
I don't think `ls` provides a reliable metric for storage scaling. I have seen this also in on-promise HPC cluster using NFS file system. You should check read/write throughput.

**Comment by nephantes** [comment]
'ls' was just an example. I  meant the other instances made EFS system extremely busy and even 'ls' took time to get the list of a directory. So, EBS performance and speed looks faster when I do the same run using starCluster on amazon. So, this could be due to ignite bug by the way. Ignite might make the storage system busy somehow. I just tell you about my experience.
