### ISSUE TITLE
Process selector of original process name applies to modules included as original name and as aliased name.

### ISSUE THREAD

**Issue by mahesh-panchal** [nextflow-io/nextflow#2490]
## Bug report 

When including a process via `include`, and then configuring it using `withName`, the original process name configuration applies to both the originally named process and the aliased process.

### Expected behavior and actual behavior

The expected behaviour is that the `withName: FOO` configuration, should only apply to `FOO` and not `BAR`.
The actual behaviour is that `withName: FOO` applies to both `FOO` and `BAR`.

### Steps to reproduce the problem

`main.nf`:
```groovy
nextflow.enable.dsl = 2

include { FOO; FOO as BAR } from './foo'

workflow {
    FOO ( 'This is foo' )
    BAR ( 'This is bar' )
}
```
`foo.nf`:
```groovy
process FOO {

    input:
    val message

    script:
    """
    echo $message
    """
}
```
`nextflow.config`:
```groovy
process {
    withName: 'FOO' {
        echo = true
    }
}
```

### Program output 

```console
$ NXF_VER=21.10.5 nextflow run main.nf 
CAPSULE: Downloading dependency io.nextflow:nextflow:jar:21.10.5
CAPSULE: Downloading dependency io.nextflow:nf-commons:jar:21.10.5
CAPSULE: Downloading dependency io.nextflow:nf-httpfs:jar:21.10.5
N E X T F L O W  ~  version 21.10.5 
Launching `main.nf` [confident_babbage] - revision: 06a11bc636
executor >  local (2)
[da/3129d7] process > FOO [100%] 1 of 1 ✔
[05/2f2c5b] process > BAR [100%] 1 of 1 ✔
This is foo

This is bar

```

The issue also occurs if `FOO` is omitted from the workflow ( and only `BAR` is used ).

### Environment 

* Nextflow version: 21.10.0, 21.10.5
* Java version: openjdk 11.0.9.1
* Operating system: macOS
* Bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

**Comment by mjhipp** [comment]
I would like to share a differing opinion. I would expect `withName` to apply to the name defined in the process file. I often import the same process multiple times into a workflow, which requires using different names. I still expect them to behave the same and use the same process selectors.

**Comment by mahesh-panchal** [comment]
As it stands if someone wants use someone else's workflow that's implemented in this way, they have no way of providing finer grain control over 'FOO' without rewriting the workflow themselves.

I think it's also better for coding comprehension if the process selector only applies to processes named in the workflow. 
Applying the same configuration to modules included under different names is still simple:
```groovy
process {
    withName: 'FOO|BAR' {     // To me this explicitly tells me I'm applying to both processes
        // settings
    }
    withName: 'FOO' {             // and then I can have finer grain control over only FOO here, without having to alias/refactor the workflow to add in a new setting at a later date (or custom config).
       // finer settings specific to FOO
    }
}
```
While I understand your perspective, one would have to be aware from the start that selectors apply to both original name and aliased name and design the workflow as such. If this is an intended feature then the documentation should explicitly say this kind of behaviour should be expected as it has important configuration ramifications.

**Comment by mahesh-panchal** [comment]
This is still occurring in version 22.04.0.

**Comment by mahesh-panchal** [comment]
It would be nice this is noted in the documentation if kept as is.
