### ISSUE TITLE
Feature Request: File Cache on AWS Batch

### ISSUE THREAD

**Issue by schorlton** [nextflow-io/nextflow#2526]
## New feature

Thanks for the amazing software.

When running jobs on AWS Batch, I frequently see a job finish, copy the file to S3, `rm -rf` the directory, and then copy that same file back from S3. A similar situation happens when staging in a file (not an output from a previous process) from S3. As process files can be massive, this can occupy a lot of the time of a workflow. I see that has been previously suggested but closed (https://github.com/nextflow-io/nextflow/issues/1497), so I'm reopening for discussion.

It would be really nice if, similar to local file ops, nextflow retained these files on the EC2 instance, and if the next process that launches on this machine uses that same file, it symlinks in the file instead of copying it to the instance. If it's not found, then stage it from the S3 work dir.

## Suggest implementation 

- Don't `rm -rf` the work dir on an EC2 instance after a job completes. Work dir names may need to include longer UUIDs in their name, as I worry about collisions with such short names and so many jobs launching on the same instance.
- When next job launches, check to see if output file of a previous process is in workdir of that process on the EC2 instance. If not, stage it to EC2 instance.
- Handle scenario where file is partially staged from S3 (eg. not process outputs), and another process launches on the same machine looking for that same file. If it hashes the file, it will see that it is incomplete and should possibly stage its own copy of the file or wait if the file is increasing in size (ie. getting downloaded by another process) (this scenario probably requires further consideration)

Thank you for your consideration!

**Comment by manuelesimi** [comment]
As AWS user I see the feature quite appealing.

However, leaving the workdir on the node seems dangerous to me. For instance, our jobs manage files of 200+ GB and each workdir can easily go over 1TB. It won't take long before the file system is full. 
Also, in my experience, in a workflow with tens/hundreds of jobs, chances that the upstream job has been executed on the same EC2 instance are very low.

**Comment by schorlton** [comment]
> As AWS user I see the feature quite appealing.
> 
> However, leaving the workdir on the node seems dangerous to me. For instance, our jobs manage files of 200+ GB and each workdir can easily go over 1TB. It won't take long before the file system is full.

Valid points! There's likely safety nets that could be built for these scenarios. After all, this is basically the default behaviour of nextflow locally if you were to run many massive jobs. The easiest option is to enable/disable this feature as a configuration flag for users. More complicated ideas would be to use lock files or another mechanism and delete process dirs that are no longer in use if space drops below a threshold, or if nextflow sees that the process outputs won't be used in another process. (There's probably even better options here)

>Also, in my experience, in a workflow with tens/hundreds of jobs, chances that the upstream job has been executed on the same EC2 instance are very low.

The probability of a successor process landing on the same instance as it's predecessor is dependent on many factors, including the process hardware requests, Batch queue, number and types of EC2 instances that are running, length of run time of process, etc. I've run 50,000 jobs on Batch via nextflow that are tiny (both in terms of run time and hardware reqs) and many do indeed get the same instance.

Thanks for your thoughtful discussion!

**Comment by manuelesimi** [comment]
You also brought very valid arguments. Each pipeline is different, it's hard to see how many would benefit from such a feature. The ones with big files in the channels and a small execution time per job (like the ones you seem to have) would probably gain the most.

I see another obstacle: I'm not sure about AWS Batch, but it's very likely that a job can't access the file system outside its sandbox. This is the case in Azure Batch. There, I know for sure that this feature would not be doable. 

Also, keep in mind that Nextflow has an execution layer that works across platforms. I'm not 100% sure, but these changes for AWS Batch could break this common layer.

I'm just speculating, of course. The NF folks know better than me and it's better to wait for their feedback.

**Comment by schorlton** [comment]
> I see another obstacle: I'm not sure about AWS Batch, but it's very likely that a job can't access the file system outside its sandbox. This is the case in Azure Batch. There, I know for sure that this feature would not be doable.

I don't know about Azure Batch, but if you set `scratch` for your processes, you can get them to all execute in the same folder. `scratch true` defaults to the temp folder of your server but you can also set your own `scratch`: https://www.nextflow.io/docs/latest/process.html#scratch

On AWS Batch, jobs can access the entire server and we can set `scratch` wherever we want. Will defer to @pditommaso for comments on the internals :smile:

**Comment by pditommaso** [comment]
This is a nice to have feature but I think it's not double just using the Bash launcher script. It would require some kind of agent running in the node.
