### ISSUE TITLE
Azure Batch Executor : support for Service Principal Auth

### ISSUE THREAD

**Issue by KrisJanssen** [nextflow-io/nextflow#2529]
## Usage scenario 

Azure Batch supports multiple usage styles: A Batch Service can have a public endpoint or a private one and nodes can be provisioned in a Batch managed subscription or in the user subscription.

When wanting to use (more secure) private endpoints and user subscription provisioning, key based authentication is not available. AAD Service Principal authentication must be used as per : https://docs.microsoft.com/en-us/azure/batch/batch-aad-auth

## Suggest implementation 

To make NextFlow more usable in these scenarios an option should be added to choose between either key based or SP based authentication.

**Comment by abhi18av** [comment]
Hi @KrisJanssen 

Thanks for raising this request - I'm looking into this and would really appreciate if you could please share further information on your use case w.r.t Azure Batch account settings such as `System Managed Identity` as well as Pool level settings specific to your use-case.

**Comment by pditommaso** [comment]
@abhi18av has not this support implemented by https://github.com/nextflow-io/nextflow/pull/3132 ?

**Comment by abhi18av** [comment]
Yes, this use-case is covered in the PR 👍

**Comment by pditommaso** [comment]
Cool, let's close this

**Comment by KrisJanssen** [comment]
Thanks @pditommaso , @abhi18av !!

**Comment by pditommaso** [comment]
All credits to @abhi18av
