### ISSUE TITLE
NXF_PARAMS_FILE environment variable not working

### ISSUE THREAD

**Issue by nebfield** [nextflow-io/nextflow#2549]
### Expected behavior and actual behavior

I would like to set the path of a params file using an environment variable [as described here](https://www.nextflow.io/docs/latest/config.html?highlight=launchdir#environment-variables) but it doesn't work for me. 

I tested a few other environment variables (e.g. `NXF_WORK`) and they all work OK, so I think it might be a bug!

### Steps to reproduce the problem

`main.nf`:

```
ch_in = Channel.fromPath(params.input)
ch_in.view()
```
`params.json`:
```
{"input": "data.csv"}
```

(`data.csv` is an empty file)

* `nextflow run main.nf --input data.csv` :heavy_check_mark: 
* `nextflow run main.nf -params-file params.json` :heavy_check_mark: 

```
N E X T F L O W  ~  version 21.10.6
Launching `main.nf` [fervent_rubens] - revision: 01e3277465
/home/benjamin/Documents/nxf-bug/data.csv
```
However, I have problems with :x:
```
$ export NXF_PARAMS_FILE=$PWD/params.json
$ echo NXF_PARAMS_FILE
/home/benjamin/Documents/nxf-bug/params.json
$ nextflow run main.nf
```

### Program output 

```
N E X T F L O W  ~  version 21.10.6
Launching `main.nf` [pedantic_kalam] - revision: 01e3277465
WARN: Access to undefined parameter `input` -- Initialise it to a default value eg. `params.input = some_value`
Missing `fromPath` parameter
```

See attached `.nextflow.log`

### Environment 

* Nextflow version: `21.10.6`
* Java version: 

```
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

* Operating system: `Linux dellbuntu 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux` 
* Bash version: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`

### Additional context

Nextflow is awesome and so are you guys! :grinning:

[nextflow.log](https://github.com/nextflow-io/nextflow/files/7840533/nextflow.log)

**Comment by pditommaso** [comment]
You-are-right! just uploaded a patch, thanks for reporting this. 

> Nextflow is awesome and so are you guys! 😀

<img src="https://media1.giphy.com/media/nEMmyUp4hl1QOzovKh/giphy.gif"/>
