### ISSUE TITLE
kuberun does not allow to specify resources

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#2558]
## Bug report 

Hello,

if using kuberun, currently nextflow.config does not allow to specify resources needed for master pod, so it cannot run in namespace that is quota enforcing.

I can provide PR so that one can set something like this in the nextflow.config:
```
k8s {
   namespace = 'default'
   runAsUser = 1000
   memory = "2024Mi"
   cpus = 2
}
```

is it acceptable? Memmory and cpu is applied only to the master/control pod. nf-xx pod resources are pipeline driven.

**Comment by pditommaso** [comment]
Not sure we should allow this since the `k8s` settings are expected to be shared with pipeline jobs and this can create an overlap with the `process.cpus` and `process.memory` setting.

What about adding cpus and mem for K8s driver as command-line option to the `kuberun` launcher?

**Comment by xhejtman** [comment]
something like `--k8scpu` `--k8smemory` ?

**Comment by pditommaso** [comment]
What about `-head-cpus`, `-head-memory` ?

**Comment by xhejtman** [comment]
Ok, will do PR

**Comment by xhejtman** [comment]
https://github.com/nextflow-io/nextflow/pull/2559
