### ISSUE TITLE
Allow multiple `publishDir` directive for a single process

### ISSUE THREAD

**Issue by emi80** [nextflow-io/nextflow#256]
It can be sometimes useful to publish output files into multiple directories.

A use case could be if I have a process that produces two files and I would like to publish them in two different folders based on their names. E.g.:

```groovy
process test {
    publishDir 'foos', pattern: 'foo.*'
    publishDir 'bars', pattern: 'bar.*'
    
    output:
    file('*.txt')

    '''
    echo -e "foo\nbar" | awk '{f=$1".txt"; print ("hello", $1) > f}'
    ''' 
}
```

**Comment by MaxUlysse** [comment]
I'd love to see that too ;-)

**Comment by fmorency** [comment]
+1

**Comment by MaxUlysse** [comment]
It works in fact, if you do something like that:
```
 publishDir '.', saveAs: { it == "foo.*" ? "foos/$it" : "bars/$it" }
```

**Comment by fmorency** [comment]
@MaxUlysse Thanks but my use-case involves outputting the same file in multiple folders

**Comment by Bioninbo** [comment]
+1

**Comment by Bioninbo** [comment]
My work-around for now to publish in two different directories: running the script twice with two different options. This way:
publishDir path: out_option == 'id' ? "path1" : "path2"

**Comment by MaxUlysse** [comment]
I think that you could use the `copyTo` method to copy your file in a second directory without running your script twice.
https://www.nextflow.io/docs/latest/script.html#copy-files

**Comment by Bioninbo** [comment]
Thx Max. I could not make it work with the copyTo method, but it might do the trick indeed.

**Comment by pditommaso** [comment]
I think it's time to give a try to this.

**Comment by pditommaso** [comment]
Available in version `0.29.0-RC1`.

**Comment by stevekm** [comment]
I have a similar issue but a different usecase; I want to publish the same files into two different `publishDir`'s. Is this supported? For example, something like this:

```
process tsv_2_sqlite {
    // convert TSV files into SQLite databases
    tag "${caller}-${sampleID}"
    publishDir "output_per_sample/${sampleID}/${caller}", mode: 'copy', overwrite: true
    publishDir "output/tsv_2_sqlite"

    input:
    set val(caller), val(sampleID), file(sample_tsv) from samples_updated_tsvs

    output:
    set val(caller), val(sampleID), file("${sampleID}.sqlite") into samples_sqlite

    script:
    """
    table2sqlite.py -i "${sample_tsv}" -o "${sampleID}.sqlite" -t variants -d '\t'
    """
}
```

Essentially, I want to have the same set of files but published under two different directory structures. One for a 'per-sample' output directory structure, and another for a 'per-process' output directory structure. 

Not sure how to see what implementation was made in version `0.29.0-RC1`.

**Comment by cguzman-am** [comment]
How is this done in a modules.config file?

**Comment by bentsherman** [comment]
See [this example](https://github.com/nf-core/rnaseq/blob/a10f41afa204538d5dcc89a5910c299d68f94f41/conf/modules.config#L221-L238) from rnaseq
