### ISSUE TITLE
AWS Batch Container vCPUs and Memory Values Not Overridden

### ISSUE THREAD

**Issue by lam-ian** [nextflow-io/nextflow#2561]
## Bug report 

I updated to the most current stable version of Nextflow (version `21.10.6.5660`) from `21.04.3.5560` and noticed that all my jobs submitted to AWS Batch did not have the vCPUs and memory that I had specified in my Nextflow script. 

### Expected behavior and actual behavior
I expect to see jobs with varying vCPUs and memory allocated according to the specification in my Nextflow script.

However when I look at the details for my jobs in the AWS Batch Console, the jobs all have vCPUs of 1 and memory of 1024 with a `Configuration Conflict` warning.

**Example of error from the job detail page on AWS Batch console**:
<img width="442" alt="AWS Batch Console Job Details 1" src="https://user-images.githubusercontent.com/79169800/149592577-0e5bf7db-9dd7-43da-932a-6388d64c02c3.png"> 
<img width="462" alt="AWS Batch Console Job Details 1" src="https://user-images.githubusercontent.com/79169800/149592772-fe9db1f2-ddcf-4654-b4b8-21839a9515e4.png">

### Steps to reproduce the problem

`test.nf`
```
process TESTING {


    cpus 2
    memory '8 GB'

    output:
    path('*.txt')

    script:
    """
    echo "hello" > test1.txt
    echo "hello" > test2.txt
    """
    
}
```

`custom.config`
```
plugins {
    id 'nf-amazon'
}

workDir = 'some/s3/location'

aws.region = 'us-west-2'
aws.batch.cliPath  = '/home/ec2-user/miniconda3/bin/aws'
process.executor = 'awsbatch'
process.queue = 'nextflow-job-queue-all-availabilities'

docker.enabled = true
process.container = "quay.io/biocontainers/picard:2.25.7--hdfd78af_0"
```

Command: `nextflow run test.nf -c custom.config`

### Program output 

The job ran successfully but according to the details in the AWS Batch console page (shown in the picture above), the job was not allocated vCPU of 2 and memory of 8GB.

### Environment 

* Nextflow version: 21.10.6.5660 
* nf-amazon plugin version: 1.3.4
* Java version: java version "1.8.0_311"
* Operating system: macOS Big Sur 11.6.2
* Bash version: zsh 5.8 (x86_64-apple-darwin20.0)

### Additional context

I notice that this problem disappear when the container name doesn't contain a slash. For example, if the value for `process.container` is `ubuntu:18.04`, then my jobs will have the correct vCPUs and memory allocated.

**Comment by lam-ian** [comment]
I changed my test script to the following to further check the number of CPUs within the container:

```
process TESTING {


    cpus 4
    memory '16 GB'

    script:
    avail_mem = task.memory.toGiga()
    """
    nproc
    echo $task.cpus
    echo $avail_mem
    """
    
}
```

The `nproc` command in the script actually outputs 4, so it seems like AWS did allocate the right number of CPUs. It might just be the AWS Batch console page that's not showing the correct value then. Thanks!

**Comment by manuelesimi** [comment]
vCPU = 1 and Memory = 1024 are the default values used when the job is registered in AWS Batch. It's normal that the page of the job definition shows them.
Those values are overridden by the ones specified in the process' directives when the job is executed by NF.

**Comment by pditommaso** [comment]
I think this may also happen if the Job definition *was* created by an old version of NF using the deprecated API and launching a new job with new version. Try cleanup past Job definitions created by NF.

**Comment by manuelesimi** [comment]
Great point @pditommaso 
That's very likely to happen.

**Comment by lam-ian** [comment]
Okay thanks!
