### ISSUE TITLE
Nextflow on Azure Complained about "Unable to download path"

### ISSUE THREAD

**Issue by andy-canexia** [nextflow-io/nextflow#2563]
Hello community members,

I have a simple pipeline working fine on AWS batch, but not so much on Azure. I am hoping if anyone can shed some light.

Context

1/ I have created the batch account, container registry, and storage account on Azure, and have these values proper defined (I think) on nextflow-azure.config file

2/ nextflow version 21.10.6.5660

3/ cmd
```
nextflow -C nextflow-azure.config run main.nf --run_id ASLDKJGSALKDJG --dev -w az://testdata-output/work
```

4/ image has been pushed to Azure container registry, and I confirm I can pull the image to local after uploading

Potential root causes (IMO)

1/ permission issue to the storage account, or ACR, or both
2/ tenant id?

**Comment by abhi18av** [comment]
Hi @andy-canexia ,

To me it seems more like a permission issue, could you please share your `.nextflow.log` file?

**Comment by fbdtemme** [comment]
I have had this issue as well and i worked around it by having my workdir in the same storage container as my input files.

**Comment by andy-canexia** [comment]
[nextflow.log](https://github.com/nextflow-io/nextflow/files/7883670/nextflow.log)

@abhi18av  thank you for offering some investigation. logfile attached.

**Comment by manuelesimi** [comment]
Define your work dir in `az://ch-testdata/work`.

**Comment by manuelesimi** [comment]
Is `az://ch-testdata` the blob where the fastqs are stored? Sorry, I just guessed that from your logs but I might be wrong.

The idea behind my suggestion is to set the work dir inside the same blob storage holding the input files.

**Comment by andy-canexia** [comment]
Correct. the full path 
<img width="1835" alt="Screen Shot 2022-01-18 at 9 35 19 AM" src="https://user-images.githubusercontent.com/75638732/149989021-ae17f462-3b9d-4b74-88bd-0ba0dba3320b.png">

**Comment by manuelesimi** [comment]
Odd.
What if you use `az://ch-testdata/input/work` as workdir?

**Comment by andy-canexia** [comment]
The error message is different this time, I assume this is progress.
<img width="1493" alt="Screen Shot 2022-01-18 at 9 46 48 AM" src="https://user-images.githubusercontent.com/75638732/149991026-83a30dc1-f665-411d-b5ad-e03ddcf5328b.png">

**Comment by manuelesimi** [comment]
Yep, this sounds more like an error in your Python script.

**Comment by manuelesimi** [comment]
@pditommaso I never noticed this, but it seems nf-azure is able to download input files in the workdir only from paths at the same level (and below) of the workdir itself. And only within the same blob storage.

**Comment by andy-canexia** [comment]
Yep. not sure if this is expected as a feature, or an unexpected bug.

**Comment by pditommaso** [comment]
Sorry, not understanding how to replicate the problem

**Comment by abhi18av** [comment]
Regarding this problem, I was also able to confirm the following scenarios: 


1. I have been able to reproduce the initial error using [the following changes](https://github.com/abhi18av/rnaseq-nf/commit/61d02799330ae7c5e20a1c863749949e65450d61) to the standard test pipeline `nextflow-io/rnaseq-nf`  using 3 different blob containers 🔴 
- `nf-workdir`
- `nf-inputdata`
- `nf-outputdata`

2. When `input bucket` == `output bucket` == `workdir bucket`  ✅ 

```yaml
 input  : az://nf-workdir/rnaseq-nf-input/ 
 outdir : az://nf-workdir/rnaseq-nf-output/
```


I'm giving a look to other scenarios and will try out https://github.com/nextflow-io/nextflow/pull/2576 to see if it resolves the issue - thanks @fbdtemme !

**Comment by pditommaso** [comment]
How was this solved?

**Comment by pditommaso** [comment]
Cool, thanks

**Comment by xmzhuo** [comment]
I have similar issue for azure. 
The workflow only run properly when input and workdir at the same blob.
If the the input and work dir in different blob, even under the same storage account, it can not fecth the file.
I also try to using indirect method of treat the input as a local file and allow the nextflow to staging it on the azure. Everything seems work at the begining. But the staging process on azure change the file , very minor change but indeed change the md5sum and cause many downstream issue.

**Comment by tanaes** [comment]
I can confirm that I'm seeing this issue as well on `Nextflow version           : 24.11.0-edge build 5929 (03-12-2024 09:30 UTC)
`

I discovered this issue by googling the error, moved over my source data to the same container as work/output, and boom it's working.

**Comment by Skitionek** [comment]
> I can confirm that I'm seeing this issue as well on `Nextflow version : 24.11.0-edge build 5929 (03-12-2024 09:30 UTC) `
> 
> I discovered this issue by googling the error, moved over my source data to the same container as work/output, and boom it's working.

From reading the code it appears that the issue might have been reintroduced when using managed identity. Is it your case @tanaes ?

https://github.com/nextflow-io/nextflow/pull/3132/changes#r2863852103
