### ISSUE TITLE
allow instances created by nextflow cloud to be tagged

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#257]
Amazon allows EC2 instances to be tagged with simple key/value pairs.  We'd like the ability to add custom tags to instances created by nextflow cloud.  Perhaps something like this in the nextflow cloud config:

```
cloud {
   ...
   instance_tags {
       purpose = 'hard work'
       environment = 'prod'
       any_custom_tag = 'any value'
   }
}
```

**Comment by tbugfinder** [comment]
AWS Batch managed compute environment supports tag-inheritance to instances.
https://aws.amazon.com/about-aws/whats-new/2017/10/tag-your-aws-batch-spot-managed-compute-environments/
