### ISSUE TITLE
Unable to access Azure File Share from task

### ISSUE THREAD

**Issue by valeandri** [nextflow-io/nextflow#2579]
### Expected behavior and actual behavior

I am testing Nextflow Azure integration with a simple pipeline. In the second process I want to list the content of an Azure File Share and then append the result to a file. My file share contains a folder "datafolder", but I don't see it in my result files.

### Steps to reproduce the problem

I attached the pipeline used and the config file. 
[nextflow.config.txt](https://github.com/nextflow-io/nextflow/files/7907219/nextflow.config.txt)
[pipeline.nf.txt](https://github.com/nextflow-io/nextflow/files/7907220/pipeline.nf.txt)

The command to launch the pipeline is the following:

$ nextflow -C ./nextflow.config run pipeline.nf -profile az --indir "az://paralleltestblob" -w "az://paralleltestblob/work" --outdir "az://paralleltestblob/results"

### Program output 

What I see in the output file:

1 first newline
2 
3

### Environment 

* Nextflow version: version 21.10.4 build 5656
* Java version: openjdk version "1.8.0_152-release"
* Operating system: CentOS
* Bash version: version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by manuelesimi** [comment]
Hi,

If the file share is mounted properly, the correct path to ls is:
`/mnt/share/filesharetest/datafolder`

The doc was not very clear about this point, I just added an explanation here: https://github.com/nextflow-io/nextflow/pull/2580

**Comment by valeandri** [comment]
Hello Manuele,

thanks for your explanation!

Unfortynately, I still cannot see the result of my listing. I found the container options of my task on the Azure Portal:

Container run options
-v /etc/ssl/certs:/etc/ssl/certs:ro -v /etc/pki:/etc/pki:ro -v /mnt/resource/batch/tasks/fsmounts/filesharetest:/share/:rw

(I removed /mnt from the mountPath)

**Comment by valeandri** [comment]
Just found that my problem was a missing protocol (SMB 3) on the type of VM I choose for the pool. So definitely not a nextflow bug.

Sorry and thanks again for clarifying the path and developing this really helpful implementation!!

**Comment by manuelesimi** [comment]
Happy it worked out!
Thanks for updating and closing the issue.
