### ISSUE TITLE
Singularity bind issue

### ISSUE THREAD

**Issue by hkaspersen** [nextflow-io/nextflow#2586]
### Discussed in https://github.com/nextflow-io/nextflow/discussions/2567

<div type='discussions-op-text'>

<sup>Originally posted by **hkaspersen** January 18, 2022</sup>
Not sure if it is appropriate to ask this here, as it might be a singularity thing, but I am having some issues with paths and singularity. In my pipeline, I use singularity images, and I tried to make the soft links created by nextflow available to it by adding the `singularity.runOptions = "--bind /cluster:/cluster"` command in the `nextflow.config`, as `/cluster` is the main path on our HPC cluster. However, it does not seem to be able to access the paths or the soft links regardless of this (the program that was run gives the error "file empty"). Am I missing something in the syntax here?
I am using singularity version 3.7.2-1.el7, and nextflow version 21.10.6.
I appreciate any help with this!</div>

**Comment by pditommaso** [comment]
Closing if favour of #2567 thread
