### ISSUE TITLE
GCP: label resources for better cost controlling

### ISSUE THREAD

**Issue by m-rieke** [nextflow-io/nextflow#2588]
## New feature

Hi everyone!
For our use within the company we need to be able to separate costs for different runs. The one possibility is doing that over different projects, but we are doing that by using google resource labels.

## Usage scenario 

(What's the main usage case and the deployment scenario addressed by this proposal)

## Suggest implementation 
Only few modifications are needed. We just had to implement a new configuration item for "google" executor where the labels can be defined. Afterwards these labels just have to be applied to runPipeline method and to VirtualMachine object in createResources method

**Comment by m-rieke** [comment]
Just for letting you know: There is a pull request for adding this functionality: https://github.com/nextflow-io/nextflow/pull/2589

**Comment by dougnukem** [comment]
The GCP labeling being added appears to be done at the Google Lifesciences Pipeline level, for this to apply to the GCP VMs for cost monitoring this needs to be done at the VirtualMachine.labels level.

https://github.com/nextflow-io/nextflow/pull/2853/files#diff-bd0a55afab4a626d773cac6787aef85e2d2756a3a25d438df70bb98ae0127f1fR479

I believe instead this should be applied instead or in addition at the Resource/VirtualMachine level.
https://github.com/nextflow-io/nextflow/blob/58be212862329f3cd8b90a454ed94ea83caa648a/plugins/nf-google/src/main/nextflow/cloud/google/lifesciences/GoogleLifeSciencesHelper.groovy#L195-L199
