### ISSUE TITLE
Summary e-mails

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#260]
Hi Nextflow team! / @pditommaso 😄 

One of the features that I wrote into [Cluster Flow](http://clusterflow.io) that I miss from Nextflow is that of summary e-mails; an automated e-mail that is sent when a pipeline completes. The e-mails look like this when a pipeline finishes with no errors: [example e-mail](http://clusterflow.io/output/email.html) (it has a bunch of red highlights when stuff goes wrong). I find that these e-mails are also a handy record, separate from the compute environment.

I know that Nextflow is a little different in that it's a little less 'set and forget' as it keeps a running process, but I still often have a bunch of `tmux` sessions running with different pipelines and it's a bit of a pain to have to run through them all of the time to see when pipelines finish (especially if they finish early because something went wrong).

Is this something that would be feasible / interesting?

Cheers,

Phil

**Comment by pditommaso** [comment]
What about [this](https://www.nextflow.io/docs/latest/metadata.html#notification-message) ? too rustic? :)

**Comment by ewels** [comment]
Ah nice! You're well ahead of me again :) Looks perfect, I'll give it a go.

I'm always a fan of pretty things, so I might write a HTML template for myself as well. Would you be interested? Could have a `-with-email name@email.com` option or something.

Is there an easy way to scoop up all of the commands used for the workflow to put into this e-mail? Not very important, but would be nice.

**Comment by pditommaso** [comment]
Yes, `workflow.commandLine`. Have a look [here](https://www.nextflow.io/docs/latest/metadata.html#runtime-metadata). That option could just be a script parameter.

**Comment by ewels** [comment]
Sorry, I wasn't very clear - I meant the command used within each process for each file.

**Comment by pditommaso** [comment]
This is possible, but not from the script itself. You will need to use the `nextflow log` command specifying the `-f script` option (and eventually others).

**Comment by ewels** [comment]
ok nice, that's still good to know. Thanks!

**Comment by pditommaso** [comment]
Unfortunately you won't be able to invoke `nextflow log` from the pipeline script. You may need to wrap the pipeline execution + `nextflow log` by a wrapper script.

**Comment by ewels** [comment]
Yup, exactly - that's what I was thinking. We're already (going to shortly) wrap Nextflow in our production environment tool called [NGI_Pipeline](https://github.com/NationalGenomicsInfrastructure/ngi_pipeline), so it should be easy to add stuff like this there.
