### ISSUE TITLE
Parameter not correctly resolved when provided through a configuration profile

### ISSUE THREAD

**Issue by JoseEspinosa** [nextflow-io/nextflow#2608]
### Expected behavior and actual behavior

When a parameter is set within a configuration profile using curly brackets its value is not correctly resolved in the config context, it works if provided as `params.test` see commented code in the example below.

### Steps to reproduce the problem

`main.nf`:
```
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

if (params.test) { 
    println "From main (OK): params.test  => $params.test"  
} else {
    println "From main (bug): params.test => $params.test"
}
```

`nextflow.config`:
```
params.test = false

profiles {
    test { 
        params {
            test = true
        }
        // This works
        // params.test = true
    }
}

if (params.test) { 
    System.out.println "From config (OK):  params.test => $params.test"  
} else {
    System.out.println "From config (bug): params.test => $params.test"
}
```

### Program output 

With the current edge version the parameter is not correctly resolved within the configuration:

```
$ NXF_VER=21.12.1-edge nextflow run main.nf -profile test
N E X T F L O W  ~  version 21.12.1-edge
Launching `main.nf` [irreverent_church] - revision: 0aaff90b7b
From config (bug): params.test => false
From main (OK): params.test => true
```

It works as expected with the last stable version:

```
$ NXF_VER=21.10.3 nextflow run main.nf -profile test
N E X T F L O W  ~  version 21.10.3
Launching `main.nf` [ecstatic_albattani] - revision: 0aaff90b7b
From config (OK): params.test => true
From main (OK): params.test => true
```

### Environment 

* Nextflow version: [21.12.1-edge] 
* Java version: [1.8.0_312]
* Operating system: [Ubuntu 18.04.6 LTS]
* Bash version: [4.4.20(1)-release]

**Comment by pditommaso** [comment]
Config file is not expected to contain execution logic. The value in the script looks consistent.

**Comment by pditommaso** [comment]
Closing this, feel free to comment below if you need more help

**Comment by JoseEspinosa** [comment]
I was finding this problem when using the new syntax of the nf-core `modules.config`, e.g. https://github.com/nf-core/chipseq/blob/5c9a47d4e2740addba60ad1484640d94ecea02a3/conf/modules.config#L481
The toy example was just to illustrate the issue, in the real case scenario the problem was that if the parameter was set in a profile e.g. then the switch in the modules config was not working. If necessary, I could try to reproduce the error again in the real case scenario.
