### ISSUE TITLE
Unable to publish a file into S3 bucket root path

### ISSUE THREAD

**Issue by nebfield** [nextflow-io/nextflow#2611]
### Expected behavior and actual behavior

I would like to be able to set a bucket in `publishDir` using an S3 file store, not hosted on AWS.

I have configured custom object storage in `nextflow.config`. I can read data from object storage OK, but I cannot write data to object storage. I'm able to upload files with the same credentials (`aws cp`) so I don't think it's a permissions issue.  

### Steps to reproduce the problem

`test.nf`:

```
file('s3://intervene-test/').list().each{ println it } 

process test {
  publishDir "s3://intervene-test/"

  input:
  val x from 1

  output:
  file 'x.txt'

  """
  echo $x > x.txt
  """
}
```

### Program output 

```
bash-4.2# nextflow -C aws.config run test.nf 
N E X T F L O W  ~  version 21.12.1-edge
Launching `test.nf` [elated_hugle] - revision: c182fef226
.nextflow.log
helloworld.txt
intervene-test.txt
... (more files)
executor >  local (1)
executor >  local (1)
[90/b1c48f] process > test [  0%] 0 of 1
Error executing process > 'test'

Caused by:
  null (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: tx000000000000007dccc6b-0061f96078-126e86c6-default; S3 Extended Request ID: 126e86c6-default-default; Proxy: null)
```

### Environment 

* Nextflow version: 21.12.1-edge
* Java version: 

```
openjdk 17.0.1 2021-10-19 LTS
OpenJDK Runtime Environment Corretto-17.0.1.12.1 (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.1.12.1 (build 17.0.1+12-LTS, mixed mode, sharing)
```

* Operating system: 

```
Linux pgsc-calc 5.7.16-200.fc32.x86_64 #1 SMP Wed Aug 19 16:58:53 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

* Bash version: (use the command `$SHELL --version`)

```
GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

### Additional context

[nxf-s3-log.txt](https://github.com/nextflow-io/nextflow/files/7980200/nxf-s3-log.txt)

**Comment by pditommaso** [comment]
Try using 

```
  publishDir "s3://intervene-test/foo"
```

instead of 

```
  publishDir "s3://intervene-test/"
```

**Comment by nebfield** [comment]
Strangely, publishing to both paths works with an older version of nextflow (21.10.6).

If I set `NXF_EDGE = 1`, and `nextflow self-update`, I get an error when publishing to a test directory inside the root path:

```
Error executing process > 'test'

Caused by:
  null (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: tx00000000000000d644d56-00620f7130-126e84fb-default; S3 Extended Request ID: 126e84fb-default-default; Proxy: null)
```

[good_log.txt](https://github.com/nextflow-io/nextflow/files/8096208/good_log.txt)
[bad_log.txt](https://github.com/nextflow-io/nextflow/files/8096209/bad_log.txt)

**Comment by nebfield** [comment]
I can confirm this is working with version 22.04.3 😄 thanks for your help troubleshooting!
