### ISSUE TITLE
test fails in system language is not English

### ISSUE THREAD

**Issue by jorgeaguileraseqera** [nextflow-io/nextflow#2614]
## Bug report 

If the language of the system is not English some tests fail due we expect English format

### Expected behavior and actual behavior

The expected behavior : 

run `./gradlew build ` in a system with a language different than English and the build ends ok

Actual behavior: several errors at BoltsTest and SysHelperTest

### Steps to reproduce the problem

`./gradlew build `

### Program output 

Execution failed for task ':nf-commons:test'.
> There were failing tests. See the report at: file:///home/jorge/nextflow/nextflow/modules/nf-commons/build/reports/tests/test/index.html

### Environment 

* Nextflow version: latest
* Java version: 11
* Operating system: Linux
* Bash version: GNU bash, versión 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

Would be nice if we can set the language as parameter

**Comment by pditommaso** [comment]
Interesting, think it would be useful to address each failing test, fixing the corresponding code to make it work irrespective of the configured lang (should not be assumed it's English)

**Comment by pditommaso** [comment]
Solved by #2615
