### ISSUE TITLE
Improve kubernetes documentation

### ISSUE THREAD

**Issue by jorgeaguileraseqera** [nextflow-io/nextflow#2626]
## Pods documentation

There are some configurations for pods not documented

## Usage scenario 

users who want to configure their pods

**Comment by bentsherman** [comment]
@jorgeaguileraseqera which ones?

**Comment by bentsherman** [comment]
Comparing [PodOptions.groovy](https://github.com/nextflow-io/nextflow/blob/51650f8c411ba40f0966031035e7a47c036f542e/modules/nextflow/src/main/groovy/nextflow/k8s/model/PodOptions.groovy#L79-L133) with the [pod directive](https://github.com/nextflow-io/nextflow/blob/master/docs/process.rst#pod) docs, I don't see any discrepancies. Some doc updates haven't been pushed to the nextflow website yet.

Please be more specific about which options are undocumented if you decide to reopen.
