### ISSUE TITLE
Incorrect error message "Access to .... is undefined since process doesn't declare any output"

### ISSUE THREAD

**Issue by ssadedin** [nextflow-io/nextflow#2627]
### Expected behavior and actual behavior

**Expected** An error message matching the problem is printed

**Actual** An error message is printed which seems to state a basic incorrect fact about my pipeline.

### Steps to reproduce the problem

I created a simple pipeline like this:

```groovy
nextflow.enable.dsl = 2

process hello {
    echo true

    output:
        path 'test.txt'

    script:
        """
        echo "Hello World" > test.txt
        """
}

 workflow {
     hello
     hello.out.view()
 }
```

Then I run it with:

```
./nextflow run test.groovy
```

### Program output 

```
N E X T F L O W  ~  version 21.10.6
Launching `...` [awesome_babbage] - revision: fa509e52de
Access to 'hello.out' is undefined since process doesn't declare any output

 -- Check script '....' at line: 20 or see '.nextflow.log' file for more details
```

### Additional context

I'm not quite sure what my real problem is, but whatever the problem, the error message seems misleading since it states my process does not declare an output when it actually does.

**Comment by pditommaso** [comment]
Hi Simon, the problem is that are `()` are missing when invoking `hello`, correct syntax should be 

```
 workflow {
     hello()
     hello.out.view()
 }
```

But I agree that the error message is misleading. I'll leave this open to investigate how improve the error message

**Comment by ssadedin** [comment]
🤦  well I knew it was probably going to be something dumb like that :-) 

But figured if I'm dumb other people will be too so if there's an easy way to make the error more accurate it would be worth doing.

Thanks for the followup!
