### ISSUE TITLE
Config file available in introspection

### ISSUE THREAD

**Issue by shaze** [nextflow-io/nextflow#264]
It would be useful if the configuration file used were available through introspection. Not high priority.

Thanks

Scott

**Comment by pditommaso** [comment]
Could you elaborate your use case? Would you need to access the config file? the text representation of the actual config object?

**Comment by shaze** [comment]
I am automating a report for the analysis (i.e., the last part of the workflow creates a PDF document with the results of the analysis and the key interim steps). Part of the report would be to reflect the conditions that affect the runs and I would like to include as an appendix the contents of the config file. So what I need is the text inside the config file — I don’t need to programmatically modify it.

Cheers,

Scott

**Comment by odoublewen** [comment]
In a similar vein, it would be very useful if workflow introspection could access the full paths to the config files that were loaded.  This would be a list since there may be more than one config.  It wouldn't necessarily need to include nested config files loaded via `includeConfig`.

**Comment by pditommaso** [comment]
@shaze Your original request was to access the config file paths or the content. In case of the latter would the ability of accessing the list of config files a valid alternative?
