### ISSUE TITLE
The execution report is always overwritten

### ISSUE THREAD

**Issue by fmarotta** [nextflow-io/nextflow#2647]
## Bug report 

The execution report is always overwritten, even though the corresponding `overwrite` option is set to false in the config file.

### Expected behavior and actual behavior

I expect that, as stated in the documentation, the report file be rolled when `overwrite = false`, but it is not.

### Steps to reproduce the problem

1. Write the following `main.nf` file (copied from [nextflow-io/hello](https://github.com/nextflow-io/hello)).
```
#!/usr/bin/env nextflow
cheers = Channel.from 'Bonjour', 'Ciao', 'Hello', 'Hola'
process sayHello {
  echo true
  input: 
    val x from cheers
  script:
    """
    echo '$x world!'
    """
}
```
2. Write the following `nextflow.config` file.
```
trace {
    enabled = true
    file = "mytrace.txt"
    overwrite = false
}
report {
    enabled = true
    file = "myreport.html"
    overwrite = false
}
```
3. Run `nextflow run main.nf`; the trace and report files are created.
4. Run again `nextflow run main.nf`; the trace file is rolled, the report is overwritten.

### Program output 

The execution works normally, no errors are generated.

### Environment 

* Nextflow version: 21.10.6.5660
* Java version:
```
openjdk 11.0.9.1-internal 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.9.1-internal+0-adhoc..src, mixed mode)
```
* Operating system: CentOS Linux release 7.9.2009
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

At [this line of code](https://github.com/nextflow-io/nextflow/blob/73899f3b7967f3bd9bc393749a80ce893368a28e/modules/nextflow/src/main/groovy/nextflow/trace/DefaultObserverFactory.groovy#L67) we can see that the `overwrite` option for the `ReportObserver` is hard-coded to `true`, whereas for other tracing files like timeline, dag, or trace, it is set to `it`. If this is the only problem, it looks like an easy fix for which I'm happy to prepare a PR.

**Comment by pditommaso** [comment]
Well spotted. I've uploaded a patch. Thanks for reporting this issue.
