### ISSUE TITLE
Nextflow crashed after setting up iGenomes reference and showed "plugin 'nf-amazon' required to read file"

### ISSUE THREAD

**Issue by Yraemon** [nextflow-io/nextflow#2649]
Hi all,

I am using nextflow to run a pipeline (nf-core/cutandrun).

The pipeline could be executed without any error on the test dataset provided. 
However, after I specified the iGenomes reference for my own data, the pipeline seemed to crash with error message "Missing plugin 'nf-amazon' required to read file", which I found is somehow similar to #2633 but the solution mentioned in that question does not work for me so far.

Please see the log file here [nextflow.log](https://github.com/nextflow-io/nextflow/files/8051864/nextflow.log)

```
nextflow run nf-core/cutandrun \
--input $repo_dir/raw_data/$project_id/design.csv \
--genome GRCh38 \
--outdir $repo_dir/processed_data/$project_id \
-with-singularity $repo_dir/cutandrun_dev.sif \
-c $repo_dir/hpc_config5 \
-profile imperial \
-r 1.1

WARN: Unable to start plugin 'nf-amazon' required by s3://ngi-igenomes/igenomes//Homo_sapiens/NCBI/GRCh38/Sequence/Bowtie2Index/
Missing plugin 'nf-amazon' required to read file: s3://ngi-igenomes/igenomes//Homo_sapiens/NCBI/GRCh38/Sequence/Bowtie2Index/
 -- Check script 'home/.nextflow/assets/nf-core/cutandrun/./workflows/cutandrun.nf' at line: 23 or see '.nextflow.log' file for more details
```
```
Line 23 in cutandrun.nf
for (param in checkPathParamList) { if (param) { file(param, checkIfExists: true) } }
```

nextflow information
```
nextflow info

  Version: 21.10.6 build 5660
  Created: 21-12-2021 16:55 UTC (16:55 BST)
  System: Linux 4.18.0-348.el8.x86_64
  Runtime: Groovy 3.0.9 on Java HotSpot(TM) 64-Bit Server VM 11.0.12+8-LTS-237
  Encoding: UTF-8 (UTF-8)
```

Thank you!

**Comment by pditommaso** [comment]
Please provide a replicate command line, the above contains custom paths

**Comment by Yraemon** [comment]
I solved the plug-in issue today by removing the `.nextflow` directory. After re-installation, I can see proper files in `.nextflow/plr/00adb0b5-4ac5-425c-ab45-72a14964ffd9/nf-amazon-1.3.4`. I think just deleting the plug-in directory and re-run the pipeline could also help.

**Comment by faiksohail** [comment]
Hi Guys,

I am using nextflow to run a pipeline (nf-core/viralrecon).

when I run the command - ```
```
nextflow run nf-core/viralrecon -profile singularity --max_memory '12.GB' --max_cpus 4 --input samplesheet.csv --outdir results/viralrecon --protocol amplicon --genome 'MN908947.3' --primer_set artic --primer_set_version 3 --skip_kraken2 --skip_assembly --skip_pangolin --skip_nextclade --platform illumina --fasta 'MN908947.fasta' --primer_bed MN908947.bed

I first get warnings -
 WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config

WARNING: Could not load nf-core/config/viralrecon profiles: https://raw.githubusercontent.com/nf-core/configs/master/pipeline/viralrecon.config

Then, after execution it says - Downloading plugin nf-amazon@1.11.0

WARN: Unable to start plugin 'nf-amazon' required by s3://ngi-igenomes/test-data/viralrecon/kraken2_human.tar.gz

```
Missing plugin 'nf-amazon' required to read file: s3://ngi-igenomes/test-data/viralrecon/kraken2_human.tar.gz

 -- Check script '/root/.nextflow/assets/nf-core/viralrecon/./workflows/illumina.nf' at line: 26 or see '.nextflow.log' file for more details
```

I am using N E X T F L O W
      version 22.10.1 build 5829
      created 27-10-2022 18:39 UTC (28-10-2022 00:09 IDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io

Please help in addressing the issue.

Thanks

**Comment by bentsherman** [comment]
Could you try again with Nextflow 23.10.0 ?

**Comment by faiksohail** [comment]
@bentsherman  Running with the same issue with the latest Nextflow version 23.10.0 as well.

I would be happy to share any of the details in order to resolve this issue at the earliest.

Thanks

**Comment by bentsherman** [comment]
Can you share your `.nextflow.log`, also can you confirm that the nf-amazon plugin was installed to the directory `~/.nextflow/plugins`

**Comment by bentsherman** [comment]
Based on [this comment](https://github.com/nextflow-io/nextflow/issues/2649#issuecomment-1042251461) you could try deleting the `.nextflow` directory both in your home directory and your launch directory

**Comment by faiksohail** [comment]
Here is my .nextlow.log file 
[.nextflow.log](https://github.com/nextflow-io/nextflow/files/13253327/default.nextflow.log)

**Comment by faiksohail** [comment]
Even Log file highlights
```

 Nov-03 23:34:49.883 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-amazon version: 2.1.4
Nov-03 23:34:49.888 [main] INFO  nextflow.plugin.PluginUpdater - Downloading plugin nf-amazon@2.1.4
Nov-03 23:35:07.549 [main] ERROR o.p.update.DefaultUpdateRepository - Connection refused
java.net.ConnectException: Connection refused
```
strange?

**Comment by bentsherman** [comment]
There is your issue, the plugin failed to download. Nextflow needs to download the plugins index and nf-amazon plugin:
- https://raw.githubusercontent.com/nextflow-io/plugins/main/plugins.json
- https://github.com/nextflow-io/nf-amazon/releases/download/2.1.4/nf-amazon-2.1.4.zip

I would make sure that you are able to download those files from your environment (try to download them with `curl` or `wget`), otherwise there may be a network issue on your end

**Comment by faiksohail** [comment]
@bentsherman is there a way to make Nextflow refer to the installed Plugins as it is not able to download nf-amazon plugin due to some reason. 

I downloaded it directly from GitHub Repository and it resides in Nextflow/plugins.

Please guide accodingly.

Thanks

**Comment by bentsherman** [comment]
You can pin the plugin version in your config file:

```groovy
plugins {
  id 'nf-amazon@2.1.4'
}
```

Github is experiencing some outages right now so could explain why plugin isn't downloading

**Comment by faiksohail** [comment]
It may sound strange but I figured out the issue @bentsherman and the reality is my Network. Even thought it is robust broadband connection but wasn't enough to run to Nextflow pipeline but what is more strange is just by changing to a mobile hotspot connection did the job!

Appreciate your help

Thank You
