### ISSUE TITLE
Set up an errorStrategy for all processes

### ISSUE THREAD

**Issue by pdp10** [nextflow-io/nextflow#2653]
Hi,

I would need to specify an `errorStrategy` and `maxRetries` for my processes. 
This is well documented in https://www.nextflow.io/docs/latest/process.html .

It is not clear to me how I can - if possible - set the same strategy for all my processes. 
For instance, can I use those directives as shown in a block below? 

```
process {
    executor = 'k8s'
    errorStrategy { task.exitStatus in 137..140 ? 'retry' : 'terminate' }
    maxRetries 3

    withName:readTrimming {
        container = "my_docker_image:latest"
    }
    withName:readMapping {
        container = "my_docker_image2:latest"
    }
}
```
If the code above is not valid, could you let me know how I can set this strategy for all my processes, please?

Thank you for your help.

**Comment by bentsherman** [comment]
The only issue I see is that you need to use `=` with each directive. Config syntax is more strict than script syntax:
```
    errorStrategy = { task.exitStatus in 137..140 ? 'retry' : 'terminate' }
    maxRetries = 3
```

Aside from that, your settings should work and apply to all processes.
