### ISSUE TITLE
git checkout of pipeline can be changed mid-execution

### ISSUE THREAD

**Issue by notestaff** [nextflow-io/nextflow#2655]
## Bug report 

If I start a nextflow run on a particular git revision of a pipeline, and then, while this run is executing, do a nextflow pull  or start another nextflow run on a different revision, the pipeline checkout used by the still-executing original run (under ~/.nextflow/assets/scm) will be overwritten, possibly leading to wrong results.    Instead, nextflow should create a separate checkout for each git revision (perhaps using git worktree) for which a pipeline run is started, and keep that checkout immutable throughout the pipeline's run.

**Comment by pditommaso** [comment]
This is a good point. Ideally, this should require having Nextlow to clone the repo as a [bare repository](https://www.saintsjd.com/2011/01/what-is-a-bare-git-repository/). 

Then, when the execution is launched it should check it out into a sub-directory named as the requested versions

**Comment by leonorpalmeira** [comment]
I would have also expected `main.nf` to be read once and kept into RAM (or copied on disk into the execution directory) while nextflow executes the pipeline. Instead, I experience the same issue as above in the following use case:

```
cd MyGitRepo/
git checkout master
nextflow main.nf
git checkout newFeatureBranch
nextflow main.nf
git checkout otherFeatureBranch
```

The execution of the sub-processes will execute the state in which the code is at the time where those processes are run, not the state in which they were when the pipeline was launched. I may be wrong but it seems that the only solution is to have one working repository per execution?

**Comment by bentsherman** [comment]
Seems to be a duplicate of #2870
