### ISSUE TITLE
Add syntax support for Input and output block

### ISSUE THREAD

**Issue by ChenDepp** [nextflow-io/nextflow#2656]
## New feature
@delagoya  
**hi, everyone. i am an newbie for nextflow,  just learn it three month. i like use it construct my analysis pipeline Because of his powerful.but now i found a problem when i construct same pipeline. same process just different input block(maybe share same channel). if input block support same syntax. it will reduce code redundancy.** 

## Usage scenario 
a demo for introduce the feature 
```
flag = true
process Test {
    input:
        if(flag){
          val(x) from Channel.of(1..10)
       }else{
          val(x) from Channel.of(11..20)
      }
       val(y) from Channel.of(21..30)
    
      """
           echo $x $y
      """
}
```
## Suggest implementation 
(Highlight the main building blocks of a possible implementation and/or related components)

**hi, so sorry for it. i am a user of python. don't know groovy and java. so i don't hava any ideal for implementation.
 looking forward your reply. thanks**

**Comment by mahesh-panchal** [comment]
You can do this quite cleanly in the DSL2 syntax with a ternary operator ( and there are other ways too )

```nextflow
#! /usr/bin/env nextflow

nextflow.enable.dsl = 2

params.flag = false

workflow {
    TEST (
        params.flag ? Channel.of( 1..10 ) : Channel.of( 11..20 ),
        Channel.of( 21..30 )
    )
}

process TEST {
    input:
    val x
    val y
    
    script:
    """
    echo "$x $y"
    """
}
```

**Comment by ChenDepp** [comment]
@mahesh-panchal  
       thanks your reply.  it can be solved by dsl2 in my demo, just like calling a function.The number of channels is different，how to solved it. like the example below.
```
flag = true
process Test {
    input:
        if(flag){
          val(x) from Channel.of(1..10)
          val(y) from Channel.of(21..30)
       }else{
          val(x) from Channel.of(11..20)
      }
     script:
       if(flag){
          """
               echo $x $y
          """
     }else{
       """
        echo $x
       }
      """
}
```

**Comment by mahesh-panchal** [comment]
There are a few ways. There is a warning I would like to say first though. When you use channels like this:
```
input:
val x from Channel.of(1..10)
val y from Channel.of(21..30)
```
Be aware that channels are generally asynchronous. This means that if this is in the middle of a pipeline, then there's no guarantee that channel elements come in the order you expect. This means they can be paired up differently ( e.g. using this example ( 1 could be paired with 21, 22, ... or even 30 ).

Now back to the question.
If you make sure your channel elements are paired correctly using a key, then you will use the operator `join`. 
In which case the input will be in the form of a tuple.
```
input:
tuple val(x), val(y)
```
In this case, when you make the `join` you can make y be an empty string `''`.

Another way, if the input pairing does not matter, is you use an empty list `[]`, or empty string `''`, as a value channel.
```nextflow
workflow {
    TEST (
        params.flag ? Channel.of( 1..10 ) : Channel.of( 11..20 ),
        params.flag ? Channel.of( 21..30 ): Channel.value( [] ).
    )
}
```
A value channel means the element will be reused again for the next task, unlike queue type channels, e.g. from `of`.

**Comment by bentsherman** [comment]
Closing since an alternative solution was given.
