### ISSUE TITLE
allow scm information to be specified in nextflow cloud config

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#267]
An scm configuration file is needed for nextflow to fetch projects from private repositories.  At the moment the AMI used for `nextflow cloud` needs to have the `~/.nextflow/scm` file in place before the cluster is created or the scm file needs to be manually added after the cluster is created.  It would be nice if that information could be added to the cloud config file.  Or perhaps through a post-processing hook?

**Comment by pditommaso** [comment]
Yes, this makes sense. I think it could be embedded in the master user-data.
