### ISSUE TITLE
Add Azure Batch to executor directive table in Nextflow docs

### ISSUE THREAD

**Issue by evanfloden** [nextflow-io/nextflow#2674]
## Bug report 

Missing `Azure Batch` directive in the executor directive.

### Expected behavior and actual behavior

Add to the table:

`azurebatch` - The process is executed using the [Azure Batch](https://azure.microsoft.com/en-us/services/batch/) service.

### Steps to reproduce the problem

See [here](https://www.nextflow.io/docs/latest/process.html#executor).

### Additional context

Grazie mile!

**Comment by bentsherman** [comment]
@abhi18av is correct. I fixed this issue as a part of #2600.
