### ISSUE TITLE
Config resolution failure with NF 22.01.0-edge

### ISSUE THREAD

**Issue by drpatelh** [nextflow-io/nextflow#2675]
The latest edge version of NF is failing to resolve the pipeline configuration as expected. We tend to import numerous config files in the pipeline `nextflow.config` for standard resource requests, genomes and module options.

In the example below the [`igenomes.config`](https://github.com/nf-core/methylseq/blob/03972a686bedeb2920803cd575f4d671e9135af0/nextflow.config#L159) isn't being loaded as expected which is why we are getting the error below where `fasta` is `null`. I have seen other, similar issues where other config files defined in `nextflow.config` aren't being loaded up as expected by NF.

```console
$ NXF_VER=22.01.0-edge nextflow run nf-core/methylseq -profile test,docker --genome hg38

N E X T F L O W  ~  version 22.01.0-edge
Pulling nf-core/methylseq ...
 downloaded from https://github.com/nf-core/methylseq.git
Launching `nf-core/methylseq` [wise_sanger] - revision: 03972a686b [master]

------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/methylseq v1.6.1
------------------------------------------------------

Cannot get property 'fasta' on null object

 -- Check script '/home/harshil/.nextflow/assets/nf-core/methylseq/main.nf' at line: 37 or see '.nextflow.log' file for more details
```

`.nextflow.log` is attached below:
[nextflow.log](https://github.com/nextflow-io/nextflow/files/8134719/nextflow.log)

Ping @Emiller88

**Comment by pditommaso** [comment]
The methylseq config is too convoluted. I need your help to create a minimal test case replicating the error.

**Comment by drpatelh** [comment]
Ok. Here you go. I isolated the problem to the evaluation of `params` in a secondary config.

## `main.nf` 

```
#!/usr/bin/env nextflow

log.info "${params.genomes}"
```

## `nextflow.config`

```
includeConfig 'igenomes.config'
```

## `igenomes.config`

```
params {
  genomes {
    'GRCh37' {
      fasta = "${params.igenomes_base}/genome.fa"
      bwa   = "${params.igenomes_base}/BWAIndex/genome.fa"
    }
  }
}
```

## Commands

```
$ NXF_VER=22.01.0-edge nextflow run main.nf --igenomes_base test

[GRCh37:[:]]

$ NXF_VER=21.10.6 nextflow run main.nf --igenomes_base test

[GRCh37:[fasta:test/genome.fa, bwa:test/BWAIndex/genome.fa]]
```

The evaluation of `params.igenomes_base` in `igenomes.config` seems to be causing the problem because if we remove that then it works:

## `igenomes.config` (remove `params.igenomes_base`)

```
params {
  genomes {
    'GRCh37' {
      fasta = "genome.fa"
      bwa   = "BWAIndex/genome.fa"
      //fasta = "${params.igenomes_base}/genome.fa"
      //bwa   = "${params.igenomes_base}/BWAIndex/genome.fa"
    }
  }
}
```

## Commands

```
$ NXF_VER=22.01.0-edge nextflow run main.nf --igenomes_base test

[GRCh37:[fasta:genome.fa, bwa:BWAIndex/genome.fa]]

$ NXF_VER=21.10.6 nextflow run main.nf --igenomes_base test

[GRCh37:[fasta:genome.fa, bwa:BWAIndex/genome.fa]]
```

**Comment by pditommaso** [comment]
This is useful, thanks

**Comment by pditommaso** [comment]
Solved
