### ISSUE TITLE
Boolean evaluation result incorrect for enabled attribute of publishDir

### ISSUE THREAD

**Issue by junjun-zhang** [nextflow-io/nextflow#2677]
## Bug report 

With the following testing script, when an `outdir` params is provided, there is no output folder created.

```
nextflow.enable.dsl=2

params.name = "world"
params.outdir = ""

process test_publishDir {
  publishDir "${params.outdir}/${task.process.replaceAll(':', '_')}", mode: "copy", enabled: params.outdir
  input:
    val name
  output:
    path "*.txt"
  script:
    """
    echo "Hello ${name}!" > hello.txt
    """
}

workflow {
  test_publishDir(params.name)
}
```

### Expected behavior and actual behavior

Expected behavior: run the above process by `nextflow run test_publishDir.nf --outdir out`, I should be able to see the output inside of a folder named as `out`. Previously this worked fine as discussed here: https://github.com/nextflow-io/nextflow/discussions/1933

Actual behavior: no `out` folder created.

### Environment 

* Nextflow version: **21.10.6**
* Java version: openjdk version "17.0.2"
* Operating system: macOS
* shell version: zsh 5.8

### Additional context

* Run the same test using nextflow **21.04.3** works perfectly fine
* With nextflow **21.10.6**, if updated as `enabled: params.outdir ? true : false` then it works as expected.

**Comment by pditommaso** [comment]
Think it's a side effect of this change 

https://github.com/nextflow-io/nextflow/commit/651835d2d741b709c1db663bfea1e58c4adc37a6

However, I think it's still consistent because `enabled` is expected to be a bool. 

Changing the param to the following should work 

```
params.outdir = false
```

**Comment by mjhipp** [comment]
@junjun-zhang Simply changing the enabled part to: `params.outDir as Boolean` fixes the issue. I did this in my project as well, and mentioned in our original discussion: https://github.com/nextflow-io/nextflow/discussions/1933#discussioncomment-1915926

It threw me at first also, but it was a necessary change. Consider:

Before, `enabled` used `as boolean`, which is like this:

```groovy
groovy> "/path/to/output" as boolean // output is defined 
 
Result: true

groovy> "" as boolean // output not defined 
 
Result: false 
```

Now, it uses `parseBoolean()`:

```groovy
groovy> Boolean.parseBoolean("/path/to/output") // output is defined 
 
Result: false

groovy> Boolean.parseBoolean("") // output not defined 
 
Result: false
```

The reason they changed it is because of this:

```groovy
groovy> "false" as boolean 
 
Result: true
```

**Comment by pditommaso** [comment]
The rational of this change is to allow interpreting "true" (string) as `true` (bool) 

https://github.com/nextflow-io/nextflow/issues/2220#issuecomment-880065955

**Comment by pditommaso** [comment]
Inclined to keep in this form. Closing this issue, feel to comment below if needed.
