### ISSUE TITLE
Warning raised : unknown recognition error type

### ISSUE THREAD

**Issue by tamuanand** [nextflow-io/nextflow#2680]
Hi @pditommaso 

This is with reference to the slack message - https://nextflow.slack.com/archives/C02T98A23U7/p1645882378629219?thread_ts=1645831697.830129&cid=C02T98A23U7

This warning pops up 
```
unknown recognition error type: groovyjarjarantlr4.v4.runtime.LexerNoViableAltException
```

When do I see this:
- lets say I have 2 terminal windows
- I launch a NF job with `awsbatch executor` on Terminal 1  -  _**this does Not trigger the warning**_
- When I now launch a NF job with `awsbatch executor` on Terminal 2 - the warning shows up. 

As mentioned by Sateesh Peri, the job runs fine and produces the necessary results. 

### Environment 

* Nextflow version: 21.12.1.edge
* Java version: openjdk version "1.8.0_312"
* Operating system: Amazon Linux 2
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)

**Comment by sateeshperi** [comment]
hi @pditommaso here is a [gitpod](https://gitpod.io/#https://github.com/CDCgov/mycosnp-nf) to replicate my setup. `nextflow run main.nf -profile docker,test` after launch and  you will see the error after configs are printed to terminal

**Comment by pditommaso** [comment]
This looks like something weird in the pipeline code, but it's not accessible 

https://github.com/nf-core/mycosnp/

**Comment by sateeshperi** [comment]
@pditommaso here is the link to repo https://github.com/CDCgov/mycosnp-nf

**Comment by pditommaso** [comment]
To look into this, it's required minimal testing that replicate the problem. This pipeline it's too big for a troubleshooting

**Comment by BrunoGrandePhD** [comment]
For others who stumble upon this issue, I was able to solve it by removing a stray `\` in my process script (_i.e._ the one before `--ncbi-build`): 

```
vcf2maf.pl \
    --input-vcf ${input_vcf} --output-maf output.maf --ref-fasta ${reference_fasta} \
    --vep-data ${vep_data} \--ncbi-build GRCh38 --max-subpop-af 0.0005 \
    --maf-center "Sage Bionetworks"
```
