### ISSUE TITLE
Issue with branch operator

### ISSUE THREAD

**Issue by ggabernet** [nextflow-io/nextflow#2689]
## Bug report 

While testing the `branch` operator for use within a pipeline I encountered a bug. The code as displayed on the Nextflow documentation is not executing properly on the Nextflow console.

```
Channel
    .from(1,2,3,40,50)
    .branch {
        small: it < 10
        large: it > 10
    }
    .set { result }

 result.small.view { "$it is small" }
 result.large.view { "$it is large" }
```

Error:

```
groovy.lang.MissingPropertyException: No such property: result for class: ConsoleScript0
	at ConsoleScript0.runScript(ConsoleScript0:9)
	at nextflow.script.BaseScript.runDsl1(BaseScript.groovy:163)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
```

However the snippet below works as expected:

```
result = Channel
    .from(1,2,3,40,50)
    .branch {
        small: it < 10
        large: it > 10
    }

 result.small.view { "$it is small" }
 result.large.view { "$it is large" }
```

Producing:
```
groovy> result = Channel 
groovy>     .from(1,2,3,40,50) 
groovy>     .branch { 
groovy>         small: it < 10 
groovy>         large: it > 10 
groovy>     } 
groovy>  result.small.view { "$it is small" } 
groovy>  result.large.view { "$it is large" } 
 
1 is small
40 is large
2 is small
50 is large
3 is small
```
### Expected behavior and actual behavior

(Give an brief description of the expected behavior 
and actual behavior)

### Steps to reproduce the problem

Open Nextflow console with `nextflow console`. Type in example from documentation:

```
Channel
    .from(1,2,3,40,50)
    .branch {
        small: it < 10
        large: it > 10
    }
    .set { result }

 result.small.view { "$it is small" }
 result.large.view { "$it is large" }
```

### Program output 

```
groovy.lang.MissingPropertyException: No such property: result for class: ConsoleScript0
	at ConsoleScript0.runScript(ConsoleScript0:9)
	at nextflow.script.BaseScript.runDsl1(BaseScript.groovy:163)
	at nextflow.script.BaseScript.run(BaseScript.groovy:200)
```

### Environment 

* Nextflow version: [21.10.5.5658] 
* Java version: [1.8.0_192]
* Operating system: [macOS]
* Bash version: zsh 5.7.1 (x86_64-apple-darwin19.0)

### Additional context

(Add any other context about the problem here)
![Screenshot 2022-03-02 at 10 34 47](https://user-images.githubusercontent.com/3973503/156335590-68ab83ae-5e90-4e47-b0a4-89a3471b260d.png)

**Comment by ggabernet** [comment]
I get the same error when trying another channel name, e.g. `ch_result`
![Screenshot 2022-03-02 at 10 44 29](https://user-images.githubusercontent.com/3973503/156336593-bfbbb6c0-16cd-4a16-afcf-105de272f34e.png)

**Comment by pditommaso** [comment]
Are you setting `nextflow.enable.dsl=2` ?

**Comment by ggabernet** [comment]
Just tried setting this as well in the console. The result then is that the Script continues executing without outputting the results or any error:
<img width="415" alt="Screenshot 2022-03-02 at 10 48 50" src="https://user-images.githubusercontent.com/3973503/156337552-27662bf0-e6cc-41e7-b2b3-8a5ad8900979.png">

**Comment by ggabernet** [comment]
When I hit `interrupt script`, I get the following:
```
java.lang.InterruptedException
	at groovyx.gpars.dataflow.expression.DataflowExpression.handleInterruption(DataflowExpression.java:325)
	at groovyx.gpars.dataflow.expression.DataflowExpression.getVal(DataflowExpression.java:262)
	at groovyx.gpars.actor.Actor.join(Actor.java:213)
	at groovyx.gpars.dataflow.operator.DataflowProcessor.join(DataflowProcessor.java:164)
	at nextflow.Session.joinAllOperators(Session.groovy:658)
	at nextflow.Session.destroy(Session.groovy:616)
	at nextflow.Session$destroy$5.call(Unknown Source)
	at nextflow.ui.console.Nextflow$_runWith_closure6.doCall(Nextflow.groovy:139)
	at nextflow.ui.console.Nextflow$_runWith_closure6.doCall(Nextflow.groovy)
```

**Comment by ggabernet** [comment]
Right, when using the CLI it works as expected:
```
nextflow.enable.dsl=2
Channel
    .from(1,2,3,40,50)
    .branch {
        small: it < 10
        large: it > 10
    }
    .set { result }

 result.small.view { "$it is small" }
 result.large.view { "$it is large" }
```

```
$ nextflow run main.nf
N E X T F L O W  ~  version 21.10.5
Launching `main.nf` [angry_babbage] - revision: 375e98df15
1 is small
40 is large
2 is small
50 is large
3 is small
```

**Comment by ggabernet** [comment]
Ok so the issue occurs only with the Nextflow console, thanks @pditommaso ! feel free to close it unless it should also be fixed there somehow...
