### ISSUE TITLE
Plugin with id nf-amazon not found in any repository

### ISSUE THREAD

**Issue by onaiv22** [nextflow-io/nextflow#2691]
## Bug report 
Nextflow plugin not downloaded when the pipeline runs in aws environment

### Expected behavior and actual behavior
I expect nextflow plugin to be downloaded when the pipeline is run so as to continue with the pipeline.

when I run this locally on my machine it works fine:

```
bash-4.2# nextflow run $NEXTFLOW_PROJECT         -bucket-dir ${NF_LOGSDIR}         ${NF_OPTS}         --outdir ${NF_WORKDIR}/${AWS_BATCH_JOB_ID}         --reads 's3://tutorial-long-reads-731-sandbox-source/sequence_read/SRR*_{1,2}.filt.fastq.gz'         --genome GRCh37         -resume
``` 

<img width="660" alt="logs-local-env" src="https://user-images.githubusercontent.com/25148408/156527083-f242fb73-f57f-4936-932c-8e682dbfcc92.PNG">

### Steps to reproduce the problem

I submit a job to AWS Batch, which spins up an ec2 instance(ECS), the job definition pulls down a docker image. I have installed nextflow and other packages needed in that image. 
I have also got entrypoint defined where I have set some env variables which are passed in by AWS Batch. 
at run time the pipeline runs with the following:

```bash
nextflow run $NEXTFLOW_PROJECT \
        -bucket-dir ${NF_LOGSDIR} \
        ${NF_OPTS} \
        --outdir ${NF_WORKDIR}/${AWS_BATCH_JOB_ID} \
        --reads 's3://tutorial-long-reads-731-sandbox-source/sequence_read/SRR*_{1,2}.filt.fastq.gz' \
        --genome GRCh37 \
        -resume
``` 

The Nextflow config is : 

```nextflow
workDir = "$NF_WORKDIR"
process.executor = "awsbatch"
process.queue = "$NF_JOB_QUEUE"
aws.batch.cliPath = "/home/ec2-user/miniconda/bin/aws"
aws.client.storageEncryption = "AES256"
aws.batch.maxParallelTransfers = 5
```

### Program output 

```
== Restoring Session Cache ==
== Running Workflow ==
N E X T F L O W  ~  version 21.10.2
Launching `rnaseq-nf/main.nf` [elegant_einstein] - revision: 4ba66eb0c8
Downloading plugin nf-amazon@1.3.3
Plugin with id nf-amazon not found in any repository
```

I also get a similar error when I'm using the latest version of nextflow which seems to attempt to download nf-amazon@1.4.0

### Environment 

* Nextflow version: 21.12.1-edge, 21.10.2
* Java version: openjdk version "17.0.2" 2022-01-18 LTS
* Operating system: docker(Amazon Linux)
* Bash version: (use the command `$SHELL --version`)

### Additional context
I have exec into the container and am able to download the plugin using wget  which seemed to download fine, so not sure if this is a network issue.

This worked fine on the ec2 instance as I am allowing security group traffic on 443 from 0.0.0.0/0:
wget https://github.com/nextflow-io/nf-amazon/releases/download/1.3.3/nf-amazon-1.3.3.zip .
ls -l nf-amazon-1.3.3.zip
<img width="579" alt="logs-nextflow" src="https://user-images.githubusercontent.com/25148408/156417100-8869d56d-3b65-4cb9-a68e-683bb4fb46c1.PNG">

I also can get a 200 from the container running on ec2

```console
$ curl -k https://github.com/nextflow-io/plugins/blob/main/plugins.json -I -L |grep 200`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/2 200
```

As well as a 200 from the downloadable zip url found here https://github.com/nextflow-io/plugins/blob/main/plugins.json  

```console
$ curl -k https://github.com/nextflow-io/nf-amazon/releases/download/1.3.3/nf-amazon-1.3.3.zip -I -L | grep 200
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   658    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 14.9M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
expect-ct: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
HTTP/1.1 200 OK
```

Just tried this from the container, a curl without the -L location flag and I get a 302

```console
$ curl -k  https://github.com/nextflow-io/nf-amazon/releases/download/1.3.3/nf-amazon-1.3.3.zip -I
HTTP/2 302
server: GitHub.com
date: Thu, 03 Mar 2022 09:04:22 GMT
content-type: text/html; charset=utf-8
vary: X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With
permissions-policy: interest-cohort=()
location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/322856279/899c7fc8-6335-4ad6-b144-218220c322b5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIW
NJYAX4CSVEH53A%2F20220303%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220303T090422Z&X-Amz-Expires=300&X-Amz-Signature=1d7b48bcdddbe456b9632cfc8a190a7b9b051283027a4de0d8c694b234b2c1b7&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=322856279&response-content-disposition=attachment%3B%20filename%3Dnf-amazon-1.3.3.zip&response-content-type=application%2Foctet-stream
cache-control: no-cache
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: no-referrer-when-downgrade
expect-ct: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
content-security-policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com objects-origin.githubusercontent.com www.githubstatus.com collector.githubapp.com collector.github.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events translator.github.com wss://alive.github.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com online.visualstudio.com/api/v1/locations raw.githubusercontent.com github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src render.githubusercontent.com viewscreen.githubusercontent.com notebooks.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com collector.github.com github-cloud.s3.amazonaws.com secured-user-images.githubusercontent.com/ *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/
content-length: 658
x-github-request-id: 814E:A887:691A27:76FB5B:62208496
```

(Add any other context about the problem here)
[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/8176931/nextflow.log.txt)

Might also be worth nothing, I am using custom certificate for TLS communication. Just adding this as i can see some conversation here https://gitter.im/nextflow-io/nextflow?at=58b5e6a5872fc8ce6299ad1e

The cert is stored here on the container : /etc/pki/ca-trust/source/anchors/certs.crt

**Comment by pditommaso** [comment]
It would be appreciated if the issue is properly formatted using the usual markdown syntax, to make it readable. tx

**Comment by onaiv22** [comment]
Sorry about that, did this in a hurry, have formatted it now...hope its better

**Comment by pditommaso** [comment]
Please include the `.nextflow.log` file

**Comment by pditommaso** [comment]
I think this is a duplicate of https://github.com/nextflow-io/nextflow/issues/2646. Please try using latest version `22.02.1-edge`
