### ISSUE TITLE
Add leftJoin operator

### ISSUE THREAD

**Issue by heuermh** [nextflow-io/nextflow#27]
While it should be possible to perform a left outer join operation using ```map``` and ```reduce``` operators, it might be useful to include a ```leftJoin``` operator in the DataflowExtensions groovy class.

Here are some simple tests
```groovy
  def testLeftJoin() {
    when:
    def ch1 = Channel.from( 1,2,3 )
    def ch2 = Channel.from( 1,0,0,2,7,8,9,3 )

    // forward
    def result = ch1.leftJoin(ch2)

    then:
    result.val == [1,1]
    result.val == [2,2]
    result.val == [3,3]
    result.val == Channel.STOP
  }

  def testLeftJoin2() {
    when:
    def ch1 = Channel.from( 1,2,3 )
    def ch2 = Channel.from( 1,0,0,2,7,8,9,3 )

    // reverse
    def result = ch2.leftJoin(ch1)

    then:
    result.val == [1,1]
    result.val == [0,null]
    result.val == [0,null]
    result.val == [2,2]
    result.val == [7,null]
    result.val == [8,null]
    result.val == [9,null]
    result.val == [3,3]
    result.val == Channel.STOP

    // alternatively, it would be ok if order was not preserved
    /*
    result.val == [1,1]
    result.val == [2,2]
    result.val == [3,3]
    result.val == [0,null]
    result.val == [0,null]
    result.val == [7,null]
    result.val == [8,null]
    result.val == [9,null]
    result.val == Channel.STOP
    */
  }
```

**Comment by pditommaso** [comment]
At the end, instead of creating a new operator, I've added an optional parameter `remainder` to the `phase` operator. 

When setting `remainder: true` it will empty all incomplete matchers. Actually not only the "left" missing matches but also the "right", but will have the ability to filter them as you need.  

You can read more here 
http://www.nextflow.io/docs/latest/operator.html#phase

**Comment by heuermh** [comment]
That works for me, thank you, @pditommaso

**Comment by pditommaso** [comment]
Great. Actually I modified the phase operator because I realised that its semantic is slightly different from Scala/Spark ``leftJoin``. I'm planning to implement a set of operators compatible with the spark ones in a future release.
