### ISSUE TITLE
Add option to ignore process selector warnings

### ISSUE THREAD

**Issue by drpatelh** [nextflow-io/nextflow#2700]
Warnings are great to let developers know that they are using the correct process selectors e.g. [here](https://github.com/nextflow-io/nextflow/issues/2072#issuecomment-939555813). However, if we are using `if/else` type logic in the main workflow like [here](https://github.com/nf-core/rnaseq/blob/7106bd792b3fb04f9f09b4e737165fa4e736ea81/workflows/rnaseq.nf#L224) then we have to replicate this in any configuration too like [here](https://github.com/nf-core/rnaseq/blob/7106bd792b3fb04f9f09b4e737165fa4e736ea81/conf/modules.config#L155). This becomes quite painful to maintain and ideally we should have an option to turn off the warnings via some sort of configuration option.

Possible suggestions:
* An option that takes a list of process names to ignore but this could get very long for larger pipelines e.g. `ignore_selector_warnings = ['KUNG', 'FOO', 'BAR']`
* A configuration option that can be set within the `process` scope for all processes or individual ones:

```
process {
    ignore_selector_warnings = true

    withName: 'FOO' {
        ignore_selector_warnings = true
    }
}
```

**Comment by pditommaso** [comment]
Think it should be possible to detect the name of the process without adding a special notation, but only one without nested notation. I mean for example `FOO` but not `NF-CORE:SOMETHING:FOO`. 

Could that be a solution for you ?

https://github.com/nextflow-io/nextflow/blob/6930408ba1dba6e70ddcf76fa713d2533a007af5/modules/nextflow/src/main/groovy/nextflow/script/ScriptMeta.groovy#L214-L231

**Comment by pditommaso** [comment]
Yeah, the main problem is that it can be detected the process name even if they are within a branch not executed, but not for the fully qualified name, which requires the evaluation of that piece of code.

**Comment by drpatelh** [comment]
The fully qualified names are where these warnings come in most useful e.g. if you change the name of a sub-workflow or some nesting then the warnings gets you back on the right track. If we use just the process name and change a fully qualified path to a module then we won't get a warning anymore?

**Comment by pditommaso** [comment]
what about adding an option to switch it off this check. At the end is only meant to be useful for development

**Comment by drpatelh** [comment]
Sounds good in principle but sometimes users may use the pipeline with a certain set of params which show the warning that may have been missed by the developers and needs to be fixed in the pipeline. How do you propose adding it and would it be off by default? Having an on/off option would be a good start but maybe not the best longer term option?

**Comment by mahesh-panchal** [comment]
It's also useful for users who mis-spell selector names when providing a custom config to override settings. It would be preferable not to have the warnings disabled. 

Although I do agree that the need for if's in the config is unpleasant. 

Could those particular warnings be shifted to the log only as long the components ( between : ) of the fully qualified name all belong to either process or workflow namespace?

**Comment by pditommaso** [comment]
I've committed 814a2605 that adds the ability to disable the config process names adding in the config 

```
nextflow.enable.configProcessNamesValidation = false
```

Think this can be a quick solution. 

> Could those particular warnings be shifted to the log only as long the components ( between : ) of the fully qualified name all belong to either process or workflow namespace?

Not sure to fully understand the logic. If you can provide an example it may help

**Comment by mahesh-panchal** [comment]
> > Could those particular warnings be shifted to the log only as long the components ( between : ) of the fully qualified name all belong to either process or workflow namespace?
> 
> Not sure to fully understand the logic. If you can provide an example it may help

My initial thought was something like:
```
selector.tokenize(':') in namespace
```
where `namespace` is the list of process and workflow names.

Now I realize that it won't work though because the selector is a pattern, so one needs to deal with stuff like
```
NF_CORE:.*:PROCESS
.*:FOO(BAR|BAZ)
```
etc.

**Comment by pditommaso** [comment]
@drpatelh is this still relevant?

**Comment by drpatelh** [comment]
Nope. I think the config option you added should suffice given that the configuration is going to be updated in future iterations of the DSL anyway. 

Just done a little testing and we could switch this off by default in the top-level of the `nextflow.config` in nf-core pipelines and then have a specific profile called `devel` that allows developers to see the warning during pipeline development.

```nextflow
nextflow.enable.configProcessNamesValidation = false

profiles {
    devel { nextflow.enable.configProcessNamesValidation = true }
}
```
