### ISSUE TITLE
params evaluation in config not working as expected

### ISSUE THREAD

**Issue by drpatelh** [nextflow-io/nextflow#2701]
Finally sat down to figure out why viralrecon is failing to run with the latest edge release of NF. It comes down to an issue with params not being resolved properly in the Nextflow configuration.

I have created a minimal reproducible example.

### `main.nf`

```nextflow
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2
```

### `nextflow.config`

```nextflow
params {
    load_config = null
}

profiles {
    test { includeConfig 'test.config' }
}

if (params.load_config) {
    includeConfig 'process.config'
}
```

### `test.config`

```nextflow
params {
    load_config = true
}
```

### `process.config`

```nextflow
process {
    withName: FOO {
        ext.args = '--quiet'
    }
}
```

### Everything works with `21.10.6`

If we run the latest stable version of Nextflow you will notice that all of the configuration is loaded as expected including the process selector for the `FOO` process:

```console
$ NXF_VER=21.10.6 nextflow config -profile test

params {
   load_config = true
}

process {
   withName:FOO {
      ext {
         args = '--quiet'
      }
   }
}
```

### Doesn't work with `22.02.1-edge`

If we run the latest edge version of Nextflow you will notice that all of the configuration is not loaded as expected and the process selector for the `FOO` process is missing:

```console
$ NXF_VER=22.02.1-edge nextflow config -profile test

params {
   load_config = true
}
```

If I change `nextflow.config` like below then it works again:

```nextflow
params {
    load_config = null
}

profiles {
    test { includeConfig 'test.config' }
}

//if (params.load_config) {     Commenting out the if logic fixes it which indicates that params.load_config isn't being evaluated properly in the configuration
    includeConfig 'process.config'
//}
```

**Comment by jorgeaguileraseqera** [comment]
as a workaround, you can try with

```
if ( profiles.test.params.load_config  ) {
      includeConfig 'process.config'
}
```

**Comment by drpatelh** [comment]
The real-world use case and the reason I went down this is rabbit hole was to use `includeConfig` based on some sort of `params` evaluation rather than using an explicit `profiles` e.g. in the code [here](https://github.com/nf-core/viralrecon/blob/42e38bba3da80484bc480f53d2130642a349e8c6/conf/modules.config#L41-L45) where I want to include a config for either Illumina or Nanopore data depending on the value of `params.platform`.

**Comment by pditommaso** [comment]
Harshil, is all the main problem still related to the config warning messages?

**Comment by drpatelh** [comment]
Nope. In this case, it makes sense to separate the process configuration for the different platforms because they could be using the same module in different ways. 

So I have one configuration file for [Illumina data](https://github.com/nf-core/viralrecon/blob/master/conf/modules_illumina.config) and one for [Nanopore data](https://github.com/nf-core/viralrecon/blob/master/conf/modules_nanopore.config). Easier to maintain this way too depending on which workflow the user wants to run.
