### ISSUE TITLE
PBS Executor  should not have parenthesis

### ISSUE THREAD

**Issue by shaze** [nextflow-io/nextflow#271]
In some circumstances, Nextflow submits jobs to the scheduler with parentheses in their names. This can break things (it seems like a command line break rather than scheduler-specific -- as the error is at the point that the qsub is called. I am using torque 2.5.13)

My process structure is

> process B { 
> 
>      each chip in list
>      ouput:
>         file (vcf) into impute_ch 
> ..... 
> }
> 
> process C {
>      executor 'pbs'
>      ....
> }

The problem is that when Nextflow tries to qsub C, it uses a label that it manufactures, which has parentheses in it (I suppose because B is done in parallel with different versions). Then when Nextflow tries to execute the qsub, the shell gets unhappy because of the parentheses

Caused by:
  Failed to submit job to grid scheduler for execution

Command executed:

  qsub -N nf-impute_(2) .command.run

Command exit status:
  1

Command output:
 

>  sh: -c: line 0: syntax error near unexpected token `('
>   sh: -c: line 0: `/var/spool/pbs/submit_filter -N nf-impute_(2) .command.run >/tmp/qsub.xsui4X'
>   qsub: submit filter returned an error code, aborting job submission. 
>

**Comment by pditommaso** [comment]
Included in version `0.23.1`
