### ISSUE TITLE
issue while configuring nextflow

### ISSUE THREAD

**Issue by Rizwanpervaizgit** [nextflow-io/nextflow#2725]
### Expected behavior and actual behavior

We just started downloading it.

```
wget -qO- https://get.nextflow.io | bash
```

### Program output 

```
unexpected argument `(' to conditional binary operator
syntax error near `(^'
if[[ ! "$PATH" =~(^|:)"$(dirname $1)"(:|$) ]];then'
```

### Environment 
* Java version: ["1.8.0_321"]
* Operating system: [Linux]
* Bash version: (3.2.0(1))

### Additional context
wget -qO- https://get.nextflow.io | bash
after running this command. It started to show the above errors.

**Comment by pditommaso** [comment]
It looks the `PATH` variable in your environment is empty which is unable. try creating 

```
export PATH=foo
wget -qO- https://get.nextflow.io | bash
```

**Comment by pditommaso** [comment]
Ignore the previous comment. I'm not able to replicate the issue.
