### ISSUE TITLE
Document fields available in task object

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2732]
The docs should give a table of the fields that are always available in the `task` object. I think it also will include the values of certain directives if they were provided.

https://www.nextflow.io/docs/latest/script.html#process-implicit-variables

**Comment by pditommaso** [comment]
They are expected to be the same as the directives list

**Comment by Midnighter** [comment]
There are a few more, though, like `task.hash` or `task.workDir` when compared to https://www.nextflow.io/docs/latest/process.html#directives

**Comment by pditommaso** [comment]
You are right
