### ISSUE TITLE
Update documentation to be DSL2-first

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2742]
This idea has been talked about on a few channels but wanted to formalize it into an issue. I think we're ready to make the Nextflow docs DSL2-first now that DSL2 has been is use for a while. This would entail:
- incorporating the "DSL 2" page into the main docs on Nextflow scripting, processes, channels, etc
- adding a "DSL 1" page that describes how pipelines are written in DSL 1 for reference
- probably leave the old channel factories and operators as they since they have deprecation warnings

Let me know if you think we're ready to make this transition, any other necessary changes, etc.

**Comment by abhi18av** [comment]
We might need to implement some redirects for the current `dsl2` page to avoid the 404 issue - should it be to the main landing page of the docs?

**Comment by bentsherman** [comment]
I think that would be fine.

**Comment by bentsherman** [comment]
After discussing with Phil and others on the website overhaul project, I'm going to keep this PR minimal. Just update all pipeline examples to DSL2 and update any specific docs that reference DSL1 behavior. I won't try to revamp the DSL2 page or introductory sections, because we will end up doing that when we merge everything into one docs site.

**Comment by pditommaso** [comment]
Sounds like a plan, the most pressing issue is to update the [process](https://www.nextflow.io/docs/edge/process.html) page using DSL2 and `path` instead of `file`
