### ISSUE TITLE
Integrate Jython support to allow use of Python for scripting

### ISSUE THREAD

**Issue by mattheww95** [nextflow-io/nextflow#2745]
Python is used frequently within bioinformatics and many new programmers first start to learn Python when programming. While groovy is an excellent scripting language, it could serve as an impediment to programmers interested in transitioning to Nextflow-enabled workflows

I know implementation of a new scripting language into the DSL is by no means a trivial task, but as Nextflow makes use of the JVM perhaps a distant version of Nextflow can incorporate Jython (a Java implementation of Python) allowing for the use of Python scripting as an option to Groovy.  In the long-term, this could broaden Nextflow’s user-base, and help people transition from Snakemake to Nextflow.

More information on Jython can be found here: https://www.jython.org/index

**Comment by bentsherman** [comment]
The main issue here is that Jython doesn't support Python 3 yet.

However I'm curious about [GraalVM](https://www.graalvm.org/22.1/reference-manual/python/) which apparently has a similar ability to run Java and Python together.
