### ISSUE TITLE
Add docker builds on non-ARM architectures

### ISSUE THREAD

**Issue by mstone-modulus** [nextflow-io/nextflow#2750]
## New feature

Hi, 

Recent builds (22.x and higher) of the [official nextflow image](https://hub.docker.com/r/nextflow/nextflow/tags) are only built for the arm64 architecture. Would it be possible to additionally provide builds for other architectures, particularly amd64/x86_64? 

Thanks!

## Usage scenario 

Running nextflow on amd64-based machines, such as AWS EC2 instances and non-M1 macs

## Suggest implementation 

Use [docker buildx](https://docs.docker.com/engine/reference/commandline/buildx_build/), as suggested in [official docs](https://www.docker.com/blog/multi-platform-docker-builds/), e.g.

```make
build:
	docker buildx build \
		--platform linux/amd64,linux/arm64,linux/arm/v7 \
		--tag nextflow/nextflow:${version} .
```

**Comment by bentsherman** [comment]
I think you might have it backwards? All of the nextflow docker images I see are for `amd64`. Do you mean you'd like to have `arm64` builds?

**Comment by fortejas** [comment]
Would nextflow run on `arm64` @bentsherman ?

**Comment by bentsherman** [comment]
As far as I can tell, it should be possible. In fact it looks like the idea has been toyed with:

**Comment by bentsherman** [comment]
https://github.com/nextflow-io/nextflow/blob/6b9c52ad5e6cf7a20347367cef39cee6e50198d9/docker/Makefile#L38-L42

**Comment by bentsherman** [comment]
I don't know if anyone else is wanting to run Nextflow on ARM, so I encourage you to try this build yourself using the docker Makefile.
