### ISSUE TITLE
Scratch usage

### ISSUE THREAD

**Issue by Lcornet** [nextflow-io/nextflow#2758]
My script use too much space on the scratch directory.
I am thus trying to point my nextflow script on a specific directory as scratch in the config file:

process .container='/scratch/ulg/GENERA/contams.sif'
process.scratch = '/data/GENERA/'
singularity.enabled = true
singularity.cacheDir = "$PWD"
singularity.autoMounts = false
singularity.runOptions = '-B /scratch/ulg/bioec/lcornet/chime -B /scratch/users/l/c/lcornet/chime'

I have this error:
Command error:
  /bin/bash: line 0: cd: /data/GENERA/nxf.L4BV7pDv5c: No such file or directory
  cat: list: No such file or directory

What should i do to not use the scratch of the cluster anymore but point on a specific directory ?

Thanks

**Comment by bentsherman** [comment]
I think you also need to mount `/data/GENERA` in the singularity run options.
