### ISSUE TITLE
destination is already in the mount point list

### ISSUE THREAD

**Issue by noepozzan** [nextflow-io/nextflow#2764]
Hi there,

So, I am building a pipeline to run some analysis, which has been working quite nicely.
But I have run into a problem I don't quite know how to solve.

The process below is run on singularity with `autoMounts = true` and `executor = 'slurm'`, but it errors out.
The same tool (philosopher freequant) is run in the pipeline before, but I am not sure why that would produce an error.

```
process FREEQUANT_PARALLEL {

    label "philosopher"

    publishDir "${params.philosopher_dir}/freequant_parallel", mode: 'copy', pattern: 'freequant_done'
    publishDir "${params.log_dir}/freequant_parallel", mode: 'copy', pattern: '*.log'

    input:
    val filter_fdr
    val dir

    output:
    val 'freequant_done', emit: freequant_done
    path '*.log', emit: log

    script:
    """
    workd=\$(pwd)
    # Perform label-free quantification via 
    # precursor (MS1) abundances and spectral counting
    cd ${params.workspace}/${dir}
    philosopher freequant \
        --dir . \
        2> ${dir}_freequant.log
    """
}
```

This is the error nextflow gives me:

```
Error executing process > 'MOCK:PHILOSOPHER_PARALLEL:FREEQUANT_PARALLEL (1)'

Caused by:
  Process `MOCK:PHILOSOPHER_PARALLEL:FREEQUANT_PARALLEL (1)` terminated with an error exit status (1)

Command executed:

  workd=$(pwd)
  # Perform label-free quantification via 
  # precursor (MS1) abundances and spectral counting
  cd /dir/workspace/WT_30M_3
     philosopher freequant 		--dir . 		2> WT_30M_3_freequant.log
  
  cp *_freequant.log $workd

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: While bind mounting '/dir/work/f8/52621f07e25418942aa150c6c1e3af:/dir/work/f8/52621f07e25418942aa150c6c1e3af': destination is already in the mount point list

Work dir:
  /dir/work/f8/52621f07e25418942aa150c6c1e3af
```

* Nextflow version: 21.04.0
* Java version: 1.8.0_152-release
* Operating system: centos
* Bash version: 4.2.46
* singularity: 3.8.5-1.el7

I changed the real paths to just "dir", because that is the policy at the lab..
Thanks for any help!

**Comment by gbinux** [comment]
Possibly because the real workdir ‘ ${params.workspace}/${dir}’ is not isolated among jobs running in parallel?

**Comment by noepozzan** [comment]
> Possibly because the real workdir ‘ ${params.workspace}/${dir}’ is not isolated among jobs running in parallel?

Sounds interesting, but I guess I don't really know what you mean. Could you elaborate?

**Comment by pditommaso** [comment]
Can you please include the launcher script named `.command.run` located at `/dir/work/f8/52621f07e25418942aa150c6c1e3af`

**Comment by noepozzan** [comment]
> Can you please include the launcher script named `.command.run` located at `/dir/work/f8/52621f07e25418942aa150c6c1e3af`

Yes, of course!
Here it is:

```
#!/bin/bash
#SBATCH -D /dir/work/c0/38bd4f929430ca9de4868d33ee92ef
#SBATCH -J nf-MOCK_PHILOSOPHER_PARALLEL_FREEQUANT_PARALLEL_(1)
#SBATCH -o /dir/work/c0/38bd4f929430ca9de4868d33ee92ef/.command.log
#SBATCH --no-requeue
#SBATCH --mem 128000M
# NEXTFLOW TASK: MOCK:PHILOSOPHER_PARALLEL:FREEQUANT_PARALLEL (1)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_container_env() {
cat << EOF
export SINGULARITY_DOCKER_USERNAME="noepozzan"
export SINGULARITY_DOCKER_PASSWORD="testpwd47"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /dir/work/c0/38bd4f929430ca9de4868d33ee92ef/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && kill $pid 2>/dev/null
}

nxf_launch() {
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} singularity exec -B /dir/work/c0/38bd4f929430ca9de4868d33ee92ef -B "$PWD" /dir/.singularity/cache/library/philosopher_4.0.0.sif /bin/bash -c "cd $PWD; eval $(nxf_container_env); /bin/bash -ue /dir/work/c0/38bd4f929430ca9de4868d33ee92ef/.command.sh"
}

nxf_stage() {
    true
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /dir/work/c0/38bd4f929430ca9de4868d33ee92ef/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

```

**Comment by gbinux** [comment]
> > Possibly because the real workdir ‘ ${params.workspace}/${dir}’ is not isolated among jobs running in parallel?
> 
> Sounds interesting, but I guess I don't really know what you mean. Could you elaborate?

```
    workd=\$(pwd)
    # Perform label-free quantification via 
    # precursor (MS1) abundances and spectral counting
    cd ${params.workspace}/${dir}
    philosopher freequant \
        --dir . \
        2> ${dir}_freequant.log
```
I was guessing if you issue `cd` in the script section, the working directory will be changed to `${params.workspace}/${dir}`.
If multiple jobs are using the same `${params.workspace}/${dir}` via singularity, it will complain like what was described above???

If that is the issue, is it possible to pass in `--dir` argument as an element in the input channel and avoid changing directory within the process's script section?

**Comment by noepozzan** [comment]
thanks for your suggestion.
Well, instead of `cd ${params.workspace}/${dir}`, I just passed in `--dir cd ${params.workspace}/${dir}`.
But this is not working either.
I guess the error message also tells us to look at `/dir/work/f8/52621f07e25418942aa150c6c1e3af`, but I am still not sure what to do...

**Comment by bentsherman** [comment]
I'm going to go ahead and label as `container/singularity`, but I'm not exactly sure what the root cause is here. I don't think the singularity warning is related to your error, that warning is often logged.

However, I suspect that the singularity container is probably failing because the task script is changing into directories that the container hasn't mounted. In general, it's not good practice to change into a differently directory in the task script, just use the task directory and publish the output files wherever you want.

But if you must change into a different directory during task execution, make sure to mount those directories in your singularity config settings.

**Comment by pditommaso** [comment]
Think this has been addressed by this change https://github.com/nextflow-io/nextflow/commit/9b3c6e31. Please try with the version `22.06.0-edge` or later

**Comment by noepozzan** [comment]
Very nice, sorry for the late answer. I found another solution by downgrading the software this process depended on, but I'll surely give this a try some time!

**Comment by noepozzan** [comment]
Got around to trying my workflow with nextflow 22.08.2-edge. Worked neatly! Thanks again
