### ISSUE TITLE
Get basename of files from channel

### ISSUE THREAD

**Issue by aghozlane** [nextflow-io/nextflow#278]
Hi,
I am wondering how to get filename of ncbi_annotation. I have tried to call bash and basename instead of script but the crash is no explicit. Any idea ?
```
process annotation {
    input:
    set contigsID, file(ncbi_annotation) from blastChannel

    output:
    file("ncbi_annotation.tsv") into annotationChannel mode flatten
    
    script:
    """
    python $baseDir/bin/get_taxonomy.py -i ${ncbi_annotation} -t ${params.gitaxidnucl} -n ${params.names} -d ${params.nodes} -o ${contigsID}_taxonomy.txt
    python $baseDir/bin/ExtractNCBIDB.py -f ${ncbi_annotation} -g ${contigsID}_taxonomy.txt -o ncbi_annotation.tsv -nb ${params.numberBestannotation}  -fc ${params.coverage}
    """
}
```

**Comment by pditommaso** [comment]
Yes use the `baseName` method eg. 

     ${ncbi_annotation.baseName}

**Comment by aghozlane** [comment]
so simple...  I'm still confused with the groovy. Thanks :+1:

**Comment by khusmann** [comment]
Hi, I'm new with groovy as well and for the life of me cannot find where the baseName method is defined. I see getFileName() as a part of Path, but can't find baseName... is it specific to nextflow? Cheers.

**Comment by pditommaso** [comment]
Good question, other to Groovy extension NF adds its own file extension methods that are defined in the `nextflow.extension.FilesEx` class. Look for example the [getBaseName](https://github.com/nextflow-io/nextflow/blob/daded334b2478596d9821fb9049f91e05fc22699/subprojects/nxf-commons/src/main/nextflow/extension/FilesEx.groovy#L335-L349) method.

**Comment by khusmann** [comment]
Ah, there it is -- thanks @pditommaso !

**Comment by FirasSadiyah** [comment]
For the sake of completeness, in case the file is named `sampleId.sorted.bam`, then `${files.baseName}` will produce `sampleId.sorted` (i.e. without .bam), but the elegant `$(files.simpleName)` will produce `sampleId`.

**Comment by pwaltman** [comment]
> nextflow.extension.FilesEx

Thank you for sharing this (I know that this is an old, old issue), but where is this documented (other than in the class definition, itself)?

**Comment by pditommaso** [comment]
here https://www.nextflow.io/docs/latest/script.html#check-file-attributes
