### ISSUE TITLE
Read file

### ISSUE THREAD

**Issue by aghozlane** [nextflow-io/nextflow#279]
Dear nextflow author,

I have one new beginning user question. Inspired from conditional scripts part in the documentation. I tried to count the line in my blast. 
the error is not explicit:
```
Caused by:
  No signature of method: $() is applicable for argument types: (_nf_script_65592d3d$_run_closure3$_closure7$_closure8) values: [_nf_script_65592d3d$_run_closure3$_closure7$_closure8@63808b4f]
Possible solutions: is(java.lang.Object), run(), run(), any(), any(groovy.lang.Closure), use([Ljava.lang.Object;)
```
here is the code: 
```
process vp1 {
    publishDir "$myDir", mode: 'copy'

    input:
    set contigsID, file(contigs), file(vp1blast) from vp1blastChannel
    
    output:
    file("*_{vp1,vp1_contigs}.fasta") into vp1Channel mode flatten
    
    script:
    count = 0
    ${vp1blast}.eachLine { count++ }
    if ( count > 0){
    """
        python $baseDir/bin/extract_sequence.py -q ${contigs} -b ${vp1blast} -o  ${contigsID}_vp1.fasta
        python $baseDir/bin/grab_catalogue_sequence.py -i ${vp1blast} -d ${contigs} -o ${contigsID}_vp1_contigs.fasta
    """
    }
    else{
    """
    #!/bin/bash
    touch !{contigsID}_vp1_contigs.fasta
    """
    }
}
```
Why am I unable to read the file : ${vp1blast}.eachLine { count++ }  ?
Is mandatory that a process generate an ouput for each input file ? Some times my blast identify no hits and there is no sequence to extract. Is there a way to remove the "touch" part ?

**Comment by pditommaso** [comment]
There are two problems here. The first is the syntax: `$varName` or `${varName}` is used to interpolate a variable into a string expression, like in BASH. Therefore the correct syntax is: 
`vp1blast.eachLine { count++ }`. 

However, in the process script context you can only access file metadata (ie. name, size, etc.) not the file content. 

To handle you use case, I would suggest to count the lines with a `wc -l` command and use a BASH `if`statement.

**Comment by aghozlane** [comment]
Thanks for the help ! It solved my problem.
