### ISSUE TITLE
Can't run pre-built singularity image on google-life-sciences

### ISSUE THREAD

**Issue by sereeena** [nextflow-io/nextflow#2797]
## Bug report 

I am running latest nextflow and have built a singularity image to a local file hpc.sif. I can successfully run using the local executor but not on google life sciences. When script is run, nextflow reports   
```
Execution failed: generic::failed_precondition: pulling image: docker pull: running ["docker" "pull" "/home/serena_lien/.singularity/hpc.sif"]: exit status 1 (standard error: "invalid reference format\n")
``` 

### Expected behavior and actual behavior

It should not attempt to pull any images but use the local one - I have tried different combinations for the container config parameter, eg "hpc.sif" or "file:///path/to/hpc.sif" or "file://relative/path/to/hpc.sif". I have also tried setting the cacheDir parameter and putting the singularity image in that folder.   

It should work the same way as the local executor does, which is running correctly? I do not wish to build from a docker image, I would have thought this should work?

### Steps to reproduce the problem
I have tried putting the file hpc.sif in the working directory where nextflow is run, and in the cacheDir
```
export NXF_SINGULARITY_CACHEDIR=~/.singularity
```   

nextflow.config
```
profiles {
   standard {
       process {
          executor = 'local'
          container = 'hpc.sif'
       }
  }
  cloud {
      process {
          executor = 'google-lifesciences'
          container = 'file:///home/serena_lien/.singularity/hpc.sif'
          disk = '50 GB'
       }
  }
}
singularity {
    enabled = true
}
```

### Program output 

[nextflow.log](https://github.com/nextflow-io/nextflow/files/8487321/nextflow.log)

### Environment 

* Nextflow version: latest
* Java version: [?]
* Operating system: Linux
* Bash version: (use the command `$SHELL --version`)

**Comment by bentsherman** [comment]
When you use google life sciences, Nextflow submits a job specification to google cloud which includes which container to use. But google cloud can't access your local filesystem, you have to give it an image URL from a container registry. Also I don't think google cloud can use singularity images...

**Comment by sereeena** [comment]
Oh, I thought if I had installed singularity in the google cloud shell then it would be able to run singularity images via nextflow. I didn't realise google-life-sciences might not support running singularity images, I guess it doesn't then. I don't think it's possible to do a singularity push to push to Google Artifact or Container Registry

**Comment by bentsherman** [comment]
So I guess you could do it, but not through google life sciences:
1. provision a google cloud VM
2. manually upload your singularity image to your VM
3. Login to the VM
4. Install Nextflow and Singularity
5. Run Nextflow with the local executor, specifying your local singularity image

You would just be limited to a single VM. Google Life Sciences automatically provisions a VM for each Nextflow task, so it needs to be able to pull a docker image from a registry. So another option for you is to simply convert your singularity image to a docker image and upload it to dockerhub or google artifact registry.

**Comment by sereeena** [comment]
Thanks for your suggestions. Yes I won't use google life sciences then.   
   
I am already able to run my pipeline with a docker image in Artifact Registry using google life sciences but I wanted to have multiple executors with nextflow (where one is going to be running a batch scheduling system on an internal cluster with singularity, as well as something running on google cloud).   

So to use singularity on gcp I will look into creating a compute engine cluster there with both nextflow and singularity installed on the nodes. A cluster with a batch queuing system is more efficient than using google life sciences at scale anyway, especially when there's lots of parallelization as it's constantly spinning up and shutting down VMs.   

I'm happy to close this issue as it's not due to nextflow (which is great btw).
