### ISSUE TITLE
Channel question on result file in directory result of programe

### ISSUE THREAD

**Issue by biowang** [nextflow-io/nextflow#28]
I don`t know how do I put file into channel, the file lie in a directory.
while directory is a parameter rather than a file.

such as programe "tophat ".
the command line like following:
$ tophat     -o   tophat_out     genome_index    R1.fq   R2.fq
the result like this
================================================
tophat_out/:
accepted_hits.bam  deletions.bed   junctions.bed  prep_reads.info
align_summary.txt  insertions.bed  logs           unmapped.bam
================================================
then I want pass the file "accepted_hits.bam" into a Channel, How should I do?

hearing from you!

**Comment by pprieto** [comment]
Hi 
If you want to pass "accepted_hits.bam" through an output Channel within a process you have to define it in the output declarations as in this example where the acceptem_hits.bam is going to be sent through channel bam

```
process mapping {
input:
...
output:
file "tophat_out/accepted_hits.bam" into bam

"""
tophat2 -p ${task.cpus} --GTF $annotation_file genome.index ${read1} ${read2}
"""
}
```

**Comment by pditommaso** [comment]
There's no distinction between regular files and directory. They can be managed in the same identical way by Nextflow channels. 

You may want to have a look to this RNA-Seq example that uses Tophat at this link
https://github.com/nextflow-io/rnatoy/blob/master/main.nf

Feel free to continue the discussion in the Nextflow forum:
https://groups.google.com/forum/#!forum/nextflow
