### ISSUE TITLE
Allow NF console to resume process executions

### ISSUE THREAD

**Issue by tantrev** [nextflow-io/nextflow#280]
It would just be really nice to specify CLI arguments to NF, like "-resume", from the NF console.

**Comment by tantrev** [comment]
I tried inserting `boolean = true` in the nextflow.config file located in the directory that NF console was executed from, and the following error resulted:
http://pastebin.com/raw/RPCD9iqX

**Comment by pditommaso** [comment]
Fixed in `0.23.3`.

**Comment by tantrev** [comment]
Works great, thank you!
