### ISSUE TITLE
DSL2 plugin extension explicit declaration

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#2804]
### Summary 

The goal of this issue is to define a DSL syntax to explicitly declare the extension methods imported by a Nextflow plugin.

This allows developers to precisely control which extensions are going to be used in the workflow script. It can also help code IDEs to check and validate the script syntax. 

### Context 

As of version `21.08.0-edge` nextflow plugins can provide extension methods that add new operations to create and manipulate channels.   

For example, the [nf-sqldb plugin](https://github.com/nextflow-io/nextflow/blob/abf7776b902c9fa37f2b0642bc07f604f0868e6b/plugins/nf-sqldb#L6-L6) adds the method [fromQuery](https://github.com/nextflow-io/nextflow/blob/abf7776b902c9fa37f2b0642bc07f604f0868e6b/plugins/nf-sqldb/src/main/nextflow/sql/ChannelSqlExtension.groovy#L58-L61) that allows the creation of a nextflow channel from a SQL query and the method and the [sqlInsert](https://github.com/nextflow-io/nextflow/blob/abf7776b902c9fa37f2b0642bc07f604f0868e6b/plugins/nf-sqldb/src/main/nextflow/sql/ChannelSqlExtension.groovy#L95-L95) method that allows inserting the channel data into a SQL table. 

The first is called a *custom factory method* because it allows the creation of a channel and it's expected to be invoked as `channel.sql.fromQuery`. 

The second is called a *custom operator* because it's expected to be invoked on a channel instance crated by another factory or process output. 

More [examples here](https://github.com/nextflow-io/nf-sqldb#available-operations).

A plugin that implements DSL extension is expected to implement the interface [ChannelExtensionPoint](https://github.com/nextflow-io/nextflow/blob/abf7776b902c9fa37f2b0642bc07f604f0868e6b/modules/nextflow/src/main/groovy/nextflow/extension/ChannelExtensionPoint.groovy#L16-L16)

The implementing class should also be marked with a [Scoped](https://github.com/nextflow-io/nextflow/blob/abf7776b902c9fa37f2b0642bc07f604f0868e6b/modules/nf-commons/src/main/nextflow/plugin/Scoped.groovy#L23-L23) annotation which defines the context on which the factory method can be invoked. 

For example `channel.sql` for the [sql plugin](https://github.com/nextflow-io/nextflow/blob/abf7776b902c9fa37f2b0642bc07f604f0868e6b/plugins/nf-sqldb/src/main/nextflow/sql/ChannelSqlExtension.groovy#L26-L26). 

Then, the *public* methods in this class can be invoked from the workflow script provided there's a matching signature. 

The channel operators are expected to have as first argument a value of type `DataflowReadChannel`. See for [here](https://github.com/nextflow-io/nextflow/blob/abf7776b902c9fa37f2b0642bc07f604f0868e6b/modules/nextflow/src/main/groovy/nextflow/extension/ChannelExtensionDelegate.groovy#L119-L119) and [here](https://github.com/nextflow-io/nextflow/blob/abf7776b902c9fa37f2b0642bc07f604f0868e6b/plugins/nf-sqldb/src/main/nextflow/sql/ChannelSqlExtension.groovy#L95-L95)

### Goals 

The goal of this issue is to provide an explicit declaration for the extension methods to be used in the workflow script, using the syntax already existing for loading module components. See [here](https://www.nextflow.io/docs/latest/dsl2.html#modules-include).

A possible syntax could be the following 

```
include { fromQuery } from 'plugin/nf-sqldb'
```

Plugin version can be specified using the `@` qualifier, for example  

```
include { fromQuery } from 'plugin/nf-sqldb@0.4.0'
```

Multiple methods can be imported using the `;` separator. For example 

```
include { fromQuery; sqlInsert } from 'plugin/nf-sqldb@0.4.0'
```
 
The `as` keyword can be used to the extension with a new name. For example

```
include { fromQuery as sqlQuery } from 'plugin/nf-sqldb'
```

### Caveats 

A problem with no trivial solution is how to manage the inclusion of different versions of the same plugins across different modules. 

The Nextflow plugin system does not allow the loading of different versions at the same time, therefore if a module A required the plugin `X@1.0.0` and module B the plugin `X@2.0.0`, the latter will cause the stop and the replacement of the former, which can break the pipeline execution. 

Possible solutions: 

* ~~automatically upgrade the plugin to the latest declared version e.g. `X@2.0.0` in the previous example warn the user~~
* do not allow the declaration of the plugin version at inclusion time, and allow the user to explicitly require it only in th nextflow config file

**Comment by jorgeaguileraseqera** [comment]
I would propose a new syntax to avoid conflicts between modules and plugins :

```
importPluginExtensions {  alias fromQuery as 'sqlQuery';   sqlInsert } from 'nf-sqldb'

channel.sqlQuery('select alpha, delta, omega from SAMPLE', db: 'foo')
```
`importPluginExtensions` seems to me a little "long" but descriptive about the intention of the closure. Other alternatives can be `extensions`, `useExtensions`, `load` ...

**Comment by jorgeaguileraseqera** [comment]
but how the interprete can know when we are trying to import a module or a plugin? checking if the `from` is a `path` ? or if starts as `plugin/`?
