### ISSUE TITLE
Document aws sessionToken for temporary credentials

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2805]
This commit -- https://github.com/nextflow-io/nextflow/commit/15ac3938542f8995f88f04b9b32ff59ec161c040 -- added support for AWS temporary credentials via the `aws.sessionToken` option. Needs to be documented.

**Comment by pditommaso** [comment]
I think `sessionToken` never worked. Better it works, but it's not refreshed automatically, therefore it's quite useless.

**Comment by bentsherman** [comment]
@gwright99 discovered it while trying to help a client with temp credentials. He's still trying to get it to work but I'm not sure if the client in question expects Nextflow to refresh automatically or if they will do it themselves.
