### ISSUE TITLE
NF console prematurely terminates "cross" operation

### ISSUE THREAD

**Issue by tantrev** [nextflow-io/nextflow#281]
When using the NF console, the "cross" operation occasionally fails to execute on all source channel entries.  The behavior seems stochastic - it works sometimes, and fails others. I have uploaded an example script with input files:

http://epilog.bio/files/demo.zip

The behavior seems to only happen in the NF console - it doesn't seem to occur when executing NF via bash.

**Comment by pditommaso** [comment]
This may happen because the execution context is not cleared between different runs. Have you tried to use the `Clear Script Context` in the `Script` menu  ?

**Comment by pditommaso** [comment]
The above suggestion should solve the problem. Feel free to comment below otherwise.
