### ISSUE TITLE
module use command is not taken in account

### ISSUE THREAD

**Issue by aghozlane** [nextflow-io/nextflow#282]
Hi,
I need add a module repository to run my command on the cluster but it seems that the module use command is not taken in account:
beforeScript 'source /local/gensoft2/adm/etc/profile.d/modules.sh;module use /pasteur/projets/policy01/Matrix/modules'
module 'mbma/tars'

I am still getting:
Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: mbma : commande introuvable

Any idea ?

**Comment by pditommaso** [comment]
Use the `module` directive. 

https://www.nextflow.io/docs/latest/process.html#module

**Comment by pditommaso** [comment]
I'm closing this issue because there isn't feedback any more. Feel free to comment and/or reopen if needed.
