### ISSUE TITLE
Add autoMounts option for every containers

### ISSUE THREAD

**Issue by phupe** [nextflow-io/nextflow#2833]
## New feature

Could we add the `autoMounts` option to every container type? As of today, this option is only available for singularity.

## Usage scenario 

Allows the possibility to explicitly control what directories are mounted inside the container using the `runOptions` option.

## Suggest implementation 

Use the same implementation as done in `SingularityBuilder.groovy`.

**Comment by pditommaso** [comment]
It's already implicit for Docker
