### ISSUE TITLE
k8s annotation values should not be sanitized

### ISSUE THREAD

**Issue by tripougnif** [nextflow-io/nextflow#2834]
## Bug report 

As per k8s documentation, annotation values don't have the same restrictions as labels. See https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set. Actually, for labels both the key and the value should be sanitized whereas only the key should be sanitized for annotations.

### Expected behavior and actual behavior

For example:
```
process {
  pod = [ [annotation: "slurm-job.knoc.io/flags", value: "--job-name=tutorial --time=00:05:00"] ]
}
```
sanitizes the value to:
```
job-name_tutorial_--time_00_05_00
```
which is definitely not the expected behaviour.

### Steps to reproduce the problem

IMHO, the example above is self explanatory.

### Program output 

There is no nextflow output as the sanitized annotation value causes the slurm job submission to fail.

### Environment 

* Nextflow version: 22.04.0 build 5697
* Java version: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 17.0.1+12-LTS
* Operating system: Linux
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)

### Additional context

This is using KNoC, implemented using virtual-kubelet. With the appropriate annotation, NodeSelector and toloeration, KNoC impersonates a k8s cluster but actually runs the workload on slurm. I know nextflow has its own slurm executor, but this work in progress potentially allowing better portablilty.

Thank you.

**Comment by pditommaso** [comment]
This a good point, we should look into
