### ISSUE TITLE
Using exec code after script

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2838]
While playing around with iterative processes, I tried once to execute Groovy code after a script block:
```nextflow
process foo {
  input:
    path infiles
    val i
    path outfiles
  output:
    path infiles
    val i_
    path 'out_*.txt', includeInputs: true
  script:
  """
  echo "Task ${i} inputs: ${infiles[i]}" > out_${i}.txt
  """
  i_ = i + 1
}
```

This didn't work, because I think it interpreted the entire thing as an exec block but then still generated a script from the output, so it ended up trying to do `bash -c "1"` (lol).

I'm not sure if I actually want this kind of thing to work or not. Seems kind of sketchy, and there are workarounds, for example:
```nextflow
  script:
  """
  echo "Task ${i} inputs: ${infiles[i]}" > out_${i}.txt
  # ${i_ = i + 1}
  """
```

But it is useful when you want to output a Nextflow variable that is actually computed from the inputs (rather than passing through an input e.g. sample id). And I suppose you could allow it as long as the user explicitly declares a `script` block (otherwise it is ambiguous).

In any case, I made this issue to see what others think but also to make a note to explain this behavior and the above workaround in the docs.

**Comment by bentsherman** [comment]
On further reflection, the current behavior makes total sense because Nextflow simply evaluates the code result as a string and uses that string as the task script. The workaround is probably the best way to do it, but I don't know if it's useful enough to merit adding a tip to the docs. So far, iteration is the only use case I see.

**Comment by bentsherman** [comment]
Another idea is to allow the output definition to actually be an expression, like so:
```nextflow
process foo {
  input:
    path infiles
    val i
    path outfiles
  output:
    path infiles
    val(i + 1)
    path 'out_*.txt', includeInputs: true
  script:
  """
  echo "Task ${i} inputs: ${infiles[i]}" > out_${i}.txt
  """
}
```

I tried it but it didn't work. You can provide a string literal that references input variables, e.g. `val("${i + 1}")` but then you have to convert back and forth between integers and strings.

You can also just put the Groovy code before the script, that seems to work just fine:
```nextflow
process foo {
  input:
    path infiles
    val i
    path outfiles
  output:
    path infiles
    val i_
    path 'out_*.txt', includeInputs: true
  script:
  i_ = i + 1
  """
  echo "Task ${i} inputs: ${infiles[i]}" > out_${i}.txt
  """
}
```

**Comment by jpfeuffer** [comment]
If you don't plan this, how would you then execute groovy code that depends on files that are generated in the script block?

**Comment by bentsherman** [comment]
I think we'll have to make the output section more flexible. I'm imagining something like this:
```groovy
// theoretical
output:
fastq = files('*.fastq')
md5 = files('*.md5')
```

The outputs could be defined like they are in workflows -- just assign a value to a name -- but you would use the `files()` function in the output block to grab files that were produced by the task. Then you could structure the outputs however you want.

**Comment by jpfeuffer** [comment]
Yeah that would be amazing. What I have right now is that my script produces many output files from one input but also associates labels to each of the output files (which I do not want to embed in the filename).
Currently I need to emit one channel with the files and emit another single file with the labels per line (in the same order of the files).
I then need to rearrange all of this outside of the process (i.e. somewhere in the workflow) to end up with the actual simple list of tuples that I would love to emit.

This could be solved by being able to use .splitCsv or any other groovy code after the script to combine labels and files and emit this list of tuples. With this my module would be truly standalone. Right now a user of this module must precisely know the meaning of the different emitted outputs to combine them.

Or am I missing something and this is actually possible. Happy to discuss this somewhere else, too.
