### ISSUE TITLE
Some local tasks get stuck "RUNNING" (1000s of channel entries)

### ISSUE THREAD

**Issue by tantrev** [nextflow-io/nextflow#284]
NF pipeline hangs because some (very fast) local tasks are stuck "RUNNING".  Example .log and a .zip of the "work" folder of one of the commands that was stuck may be found at:

http://epilog.bio/files/.nextflow.log.1
http://epilog.bio/files/ae2f7793cabae9a13ce613beb10231.zip

Perhaps being able to specify a "timeout" parameter could remedy the problem?

**Comment by tantrev** [comment]
Note that I have since updated the original script so that it now use's NF's built-in file.exists() operation, instead of the "test" command. Unfortunately, the same behavior of tasks being stuck in RUNNING still results.

**Comment by pditommaso** [comment]
Can you provide a test case to replicate the issue?

**Comment by tantrev** [comment]
I've been struggling to do that actually!  I could reliably replicate the issue on the cluster I was using, but not on my local machine.   I tried deleting the "work" folder on the cluster and that seems to have helped, however.

Is it possible that some sort of "collision" with folder names is happening?  In that example folder above (ae2f7793cabae9a13ce613beb10231.zip), there are ".command.run" and a ".command.run.1" files.  I'm not sure if that's typical behavior but since NF uses md5, maybe switching to SHA-256 might reduce potential future collisions?

**Comment by pditommaso** [comment]
Nope. The `.command.run.1` is an intermediate wrapper script generated when using the *trace* file feature. Thus I don't think it's task id collision problem. NF uses Murmur128 hashing algorithm. 128 bit numbers are large enough to be considered statistically unique. See [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier).

I've noticed a strage error message in the `.command.err` file included in your attachment. 

```
.command.run.1: line 90: 12748 Terminated              nxf_trace "$pid" .command.trace
```

I would suggest to troubleshoot the problem doing the following. Change into the following dir: 

```
/../work/72/ae2f7793cabae9a13ce613beb10231
```

Then run the following command to replicate the issue: 

```
NXF_DEBUG=4 bash .command.run 
```

Then attach here the produced output. If you have deleted that folder re-launch the pipeline having the `NXF_DEBUG` defined in your system and provide the outputs for the tasks hanging the execution.

**Comment by pditommaso** [comment]
Could you also please check that the following tools are available in the computing node(s) of your cluster: 

* tr
* ps 
* awk 
* sed 
* egrep  
* printf 
* echo

**Comment by pditommaso** [comment]
I'm closing this issue because there feedback any more. If you continue to experience the problem feel free to re-open it.

**Comment by tantrev** [comment]
My apologies for the delayed response, I've been slammed with a crazy number of things this week.  I can confirm that all of those commands are available on the cluster - I eventually just switched over to using built-in java routines for the operations I was doing and that seemed to fix everything.  I seem to have run into a similar issue, however, that I'll upon up a separate ticket for.

Thank you for all of your help!

**Comment by tantrev** [comment]
So I seem to have encountered this error again, except tasks get stuck in "SUBMITTED" through SLURM.  I ran the command you specified in an affected work folder, which may be found [here](http://epilog.bio/files/d9e572d83ab27c7d98db83eac916af.debug.tar.gz).  The NF log file may also may viewed [here](http://epilog.bio/files/.nextflow.log).

**Comment by tantrev** [comment]
I was able to rectify the SLURM error by setting the queueSize to 20 (I had it previously at 100).  It would be nice to be able to use larger queues, though.

**Comment by pditommaso** [comment]
The task output that you attached seems to have run just fine. There's no error and the exist status is 0.

**Comment by veeravalli** [comment]
Yes, exit status is 0 but .command.log has `/gatk4_test/nf_test/work/cc/4bfc67c1fb9b5aafe65a432a229d24/.command.stub: line 99:  6761 Terminated              nxf_trace "$pid" .command.trace`  as last line
No error in the .nextflow logs too

**Comment by pditommaso** [comment]
@veeravalli this discussion is closed. Please open a separate one reporting a detailed description of the problem you are experiencing, the `.nextflow.log` file and some details of the deployment infrastructure.
