### ISSUE TITLE
Add support for label/tags

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#2845]
### Summary 

The goal of this enhancement is to allow users to propagate label/tag annotations to the corresponding cloud execution platform.

This is a recurrent request from Nextflow users. See [here](https://github.com/nextflow-io/nextflow/issues/2817), [here](https://github.com/nextflow-io/nextflow/issues/1764), [here](https://github.com/nextflow-io/nextflow/issues/948) and [here](https://github.com/nextflow-io/nextflow/pull/2589). 

This support could be implemented by extending the semantic of the label directive, in such a way that when a key-value is provided using the syntax `name=value` is implicitly interpreted as key-value pair that needs to be propagated to the corresponding job execution. 

This is expected to be an opt-in feature therefore the user should enabled either using the env variable: `NXF_ENABLE_LABELS_PROPAGATION=true` or setting the attribute `nextflow.enable.labelsPropagation=true` in the nextflow config file. 

### Supported platforms

* AWS Batch 
  - [Job definition](https://docs.aws.amazon.com/batch/latest/APIReference/API_RegisterJobDefinition.html)
  - [Job submit](https://docs.aws.amazon.com/batch/latest/APIReference/API_SubmitJob.html)
* Google LS
  - [Run pipeline](https://cloud.google.com/life-sciences/docs/reference/rest/v2beta/projects.locations.pipelines/run) allow to specified the labels key-value pairs to be used
* Azure batch (it looks like it does not provide any API for tags/labels annotation)
* Kubernets
  - The task pod should include the user-provided key-value pairs pod [labels](https://github.com/nextflow-io/nextflow/blob/3f247518fbd56074a97379bf31de138cc229f499/modules/nextflow/src/main/groovy/nextflow/k8s/K8sTaskHandler.groovy#L178-L178).

### Validation 

Each platform has a slightly different set of validation rules for labels name and values. It's to be defined if nextflow should prevent the use of such of invalid pattern or delegate the check to the target platform

**Comment by kdallen1** [comment]
Is there an estimated time to merge the linked PR?  Looking forward to testing it out :smiley:

**Comment by pditommaso** [comment]
Hey there, this is scheduled for 22.10 release which means the end of this quarter

**Comment by pditommaso** [comment]
Following the internal discussion the decision is to not change the current implementation of [label](https://www.nextflow.io/docs/latest/process.html#label) directive, add instead a new directive named `resourceLabel` to propagate labels and tags to cloud resources. 

The implementation should remain the same. The settings `NXF_ENABLE_LABELS_PROPAGATION` and `nextflow.enable.labelsPropagation=true` are not needed any more

**Comment by jorgeaguileraseqera** [comment]
Implemented in #2853

**Comment by pditommaso** [comment]
But not merged
