### ISSUE TITLE
Slurm Sbatch file too large

### ISSUE THREAD

**Issue by apeltzer** [nextflow-io/nextflow#2852]
## Bug report 

A more detailed description of the issue can be found here already https://github.com/nextflow-io/nextflow/issues/2118 and a preliminary bugfix in Nextflow 22.04.0 wasn't fully effective. The problem arises, when many files are symlinked to a directory by nextflow, thus bloating up the `.command.run` file to be larger than 4MB, which is the default max size allowed by SLURM. The scheduler then  complains about _"too long file names or file size too large"_ and doesn't start the process/job. 

### Expected behavior and actual behavior

Should be possible to run arbitrarily large file numbers. 

### Steps to reproduce the problem

1) Run a job that creates a `.command.run` file > 5MB on any SLURM cluster
2) Watch the above error happen, the job doesn't get scheduled and Nextflow crashes.

Circumvention is possible by using some "hacks", e.g. making the process not produce as many symlinks (e.g. using folders instead of individual files), but that is not always an optimal approach and requires modifying the pipeline itself. One could think about externalizing this step in a separate file, so that the submitted `.command.run` is << 5MB in size and just calls the other externalized script maybe?

Circumvent the issue by running this here: https://github.com/nextflow-io/nextflow/issues/2118#issuecomment-990741937

**Comment by sinamajidian** [comment]
Faced the same issue today. Any updates here?

**Comment by plaquette** [comment]
hey sina - i handle it like this:

- define a channel with a file the contains all the sym-links to the relevant files
- take this file as an input for the process that requires the many files instead of the files


` paths_file_channel = process_1.out.relevantfile.collect().flatten().map{it -> it.toString() }.collectFile(name: 'paths.txt', newLine: true)`

something like this. hope that helps.

**Comment by njspix** [comment]
Hello all, I just encountered an issue similar to this where a `.command.run` file with ~31k lines of `ln` commands in the `nxf_stage()` function caused the executing shell to segfault. If i'm correct, most of the variability in the `.command.run` file size comes from the `nxf_stage()` function. Would it be simple to write the staging commands to a file (e.g. `.command.stage`) and then exec that file?

**Comment by pditommaso** [comment]
Think it was discussed in the past that this could be solved by storing the staging file command into a separate file, instead of the `.command.run`. Do you think this could be a valid solution ?

**Comment by bentsherman** [comment]
Separate script for staging is the best solution I can think of. Ideally conditioned on the number of files to stage/unstage, so that we only create the extra file if we need it.

**Comment by pditommaso** [comment]
Look @apeltzer, solved! 

<img src="https://media2.giphy.com/media/CAxbo8KC2A0y4/giphy.gif"/>

**Comment by bentsherman** [comment]
Hi Gisela, yes you can control the threshold with an environment var:
```bash
NXF_WRAPPER_STAGE_FILE_THRESHOLD='50000'
```

It is not documented but it accepts memory values like `50 KB` like in Nextflow. Also, this threshold applies to the staging script only, not the entire script, so you will want to set it lower than your cluster's limit, e.g. `40 KB`

**Comment by ggabernet** [comment]
perfect, thank you!
