### ISSUE TITLE
a fault occurred in a recent unsafe memory access operation in compiled Java code

### ISSUE THREAD

**Issue by scottgigante-immunai** [nextflow-io/nextflow#2854]
### Expected behavior and actual behavior

My [workflow](https://github.com/openproblems-bio/nf-openproblems/blob/master/main.nf) aborts with an "unsafe memory access operation" on an AWS self-hosted runner, but runs successfully on Github-hosted runners.

### Steps to reproduce the problem

Contained at https://github.com/scottgigante-immunai/openproblems/runs/6316504610?check_suite_focus=true

### Program output 

[nextflow.log](https://github.com/nextflow-io/nextflow/files/8641633/nextflow.log)

### Environment 

* Nextflow version: v22.04.0
* Java version: openjdk 17.0.2 2022-01-18
* Operating system: Ubuntu 20.04
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by vinisalazar** [comment]
I'm having this same issue after interrupting my pipeline halfway. Now I can't get it to resume.

**Comment by vinisalazar** [comment]
This was fixed after I gave it the same amount of memory when resuming. I was trying giving less and it was returning this error.
