### ISSUE TITLE
error with "unbound variable" in .bashrc

### ISSUE THREAD

**Issue by qingpeng** [nextflow-io/nextflow#286]
While I tried to run a simple blast nextflow on HPC, I got an error about "unbound variable" in .bashrc file.

Since this .bashrc file is maintained by the HPC staff directly, there is an variable called "SHIFTER_RUNTIME", which may not be set. 

in the .command.sh file, beacuase of the "-ue" flag, there is the "unbound variable" error. 

I am wondering if there is a way to disable this or if there is any way to set the SHIFTER_RUNTIME variable before run that .command.sh script.

.command.sh
=================
```
#!/bin/bash -ue
blastall -p blastn -i test.2.fa -d ./virus_segment_5k.fa -o blast.m8
```

Error output
====
```
N E X T F L O W  ~  version 0.23.2
Launching `blast.nf` [hungry_lalande] - revision: 7cff9a1e9c
[warm up] executor > local
[0b/664003] Submitted process > get_feature (2)
[b0/000695] Submitted process > get_feature (5)
[17/5b5eb7] Submitted process > get_feature (1)
[06/994d56] Submitted process > get_feature (6)
[51/4159e5] Submitted process > get_feature (4)
[75/b448fc] Submitted process > get_feature (3)
ERROR ~ Error executing process > 'get_feature (2)'

Caused by:
  Process `get_feature (2)` terminated with an error exit status (1)

Command executed:

  blastall -p blastn -i test.2.fa -d ./virus_segment_5k.fa -o blast.m8

Command exit status:
  1

Command output:
  (empty)

Command wrapper:
  /global/homes/q/qpzhang/.bashrc: line 2: SHIFTER_RUNTIME: unbound variable

Work dir:
  /global/homes/q/qpzhang/glob/work/0b/6640038859aceda28e3eb2bc99476e

Tip: view the complete command output by changing to the process work dir and entering the command: 'cat .command.out'

 -- Check '.nextflow.log' file for details
WARN: Killing pending tasks (1)

```

**Comment by pditommaso** [comment]
Stated this is not a NF error but a misconfiguration issue in your system I'm not understanding why the `. bashrc` get invoked by the nextlow. Can you share your script?

**Comment by qingpeng** [comment]
Sure! This is the .nf script: Thanks!

#!/usr/bin/env nextflow


params.out = "./test.fa.m8"
params.segment_file = "./test.fa"
params.chunkSize = 4
params.db = "./virus_segment_5k.fa"
db = Channel.value(params.db)

Channel.fromPath(params.segment_file)
    .splitFasta(by: params.chunkSize, file: true)
    .set { fasta }

process get_feature {

    input:
    file inputfile from  fasta
    val db

    output:
    file 'blast.m8' into m8output

    """
    blastall -p blastn -i ${inputfile} -d ${db} -o blast.m8
    """
}

m8output.collectFile(name: params.out)

**Comment by qingpeng** [comment]
The SHIFTER_RUNTIME is related to "Shifter", which is a container system developed here at NERSC like docker. It is used in the .bashrc file in the beginning

# begin .bashrc/.kshrc
if [[ -z "$SHIFTER_RUNTIME" ]]
then
  [ -e $HOME/.dbgdot ] && echo "entering .bashrc/.kshrc" >&2



Also in the word dir, .command.run

qpzhang@genepool14:~/glob/work/30/664a135ee95b5a638eb67ffcef87c8$ more .command.run
#!/bin/bash
# NEXTFLOW TASK: get_feature (3)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 2 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /global/homes/q/qpzhang/glob/work/30/664a135ee95b5a638eb67ffcef87c8/.exitcode
  set +u
  [[ "$COUT" ]] && rm -f "$COUT" || true
  [[ "$CERR" ]] && rm -f "$CERR" || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /global/homes/q/qpzhang/glob/work/30/664a135ee95b5a638eb67ffcef87c8/.command.begin
[ -f /global/homes/q/qpzhang/glob/work/30/664a135ee95b5a638eb67ffcef87c8/.command.env ] && source /global/homes/q/qpzhang/glob/work/30/664a135ee95b5a638e
b67ffcef87c8/.command.env
[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
rm -f test.3.fa
ln -s /global/u2/q/qpzhang/glob/work/92/6e0b6a5f10e34ee14580a72315b552/test.3.fa test.3.fa


set +e
COUT=$PWD/.command.po; mkfifo "$COUT"
CERR=$PWD/.command.pe; mkfifo "$CERR"
tee .command.out < "$COUT" &
tee1=$!
tee .command.err < "$CERR" >&2 &
tee2=$!
(
/bin/bash -ue /global/homes/q/qpzhang/glob/work/30/664a135ee95b5a638eb67ffcef87c8/.command.sh
) >"$COUT" 2>"$CERR" &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2

**Comment by pditommaso** [comment]
I really do not understand what is executing `/global/homes/q/qpzhang/.bashrc`. However if you define `export SHIFTER_RUNTIME=''` in your env before launching NF you should get rid of that error.

**Comment by pditommaso** [comment]
** you should use triple ` to highlight code block code **

**Comment by pditommaso** [comment]
much better now! 👍

**Comment by qingpeng** [comment]
I tried to "export SHIFTER_RUNTIME='' and now it looks working! Thanks for the quick response!

**Comment by pditommaso** [comment]
But looking at your `.bashrc` I think executes the wring initialisation. Instead of setting that var define the following setting in the `nextflow.config` file. 

```
process.shell = ['/bin/bash','-e']
```

However I would suggest to ask your sysadmins to improve that script.

**Comment by qingpeng** [comment]
Thanks for the advice!
