### ISSUE TITLE
HyperQueue executor 

### ISSUE THREAD

**Issue by Nortamo** [nextflow-io/nextflow#2867]
## New feature

HyperQueue executor to nextflow (https://it4innovations.github.io/hyperqueue/stable/)

(As a side note we are also looking at an executor for https://github.com/flux-framework/flux-core to enable large workflows with mpi components.)

## Usage scenario 

Running large workflows with very many processes on HPC systems ( ~ 10K or more  ).
The current batch executors (especially the slurm one https://www.nextflow.io/docs/latest/executor.html#slurm ) 
are not suitable to due to the usage of individual jobs, and even if jobsteps were to be used, the amount would be to large,
negatively affecting the HPC scheduler stability. 

So the idea for maximum throughput would be to launch HyperQueue using Slurm (I think they also suport PBS), and then start
nextflow.

## Suggest implementation 

Most of the work is just straightforwardly creating a new Executor which extends the  `AbstractGridExecutor`,
e.g `HqExecutor`.  

Main unsolved issue is that HyperQueue requires the submissions script (i.e the `.command.run` file for each process) to be executable, which is currently
not the case. While prototyping I just added `targetWrapperFile().setExecutable(true,true)`  in the `build` method of the `BashWrapperBuilder` class in `modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy `, but this is perhaps not the way you would like this done, and I'm wondering what would be the best way to achieve this?

So far we managed to run some simple toy workflow on 20 nodes (2560 CPU cores) without apparent issues. Also interested in hearing if you think there will be any issues in nextflow (apart from the file count) if the number of parallel processes is increased more.

**Comment by pditommaso** [comment]
This is interesting. If I'm understanding correctly, you are suggesting submitting the nextflow run as a Slurm job, then the workflow tasks would be run via the HyperQueue executor. Is that correct? 

The support for Flux is also interesting, please report it as a separate ticket.

**Comment by Nortamo** [comment]
Yes. 
I'll create a separate issue for the flux use case.

**Comment by pditommaso** [comment]
> Main unsolved issue is that HyperQueue requires the submissions script (i.e the .command.run file for each process) to be executable

There's a similar need also for the Condor executor. You can see it here 

https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/executor/CondorExecutor.groovy#L158-L159

> So far we managed to run some simple toy workflow on 20 nodes (2560 CPU cores) without apparent issues. Also interested in hearing if you think there will be any issues in nextflow (apart from the file count) if the number of parallel processes is increased more.

I would expect to be able to handle 100x more. Happy support this effort on the contrary.

**Comment by spirali** [comment]
> Main unsolved issue is that HyperQueue requires the submissions script (i.e the `.command.run` file for each process) to be executable, which is currently not the case.

Hi, 
The current version of HyperQueue removed this limitation if the submission looks like ``hq submit <SCRIPT>.sh``

**Comment by Kobzol** [comment]
Hi, to expand a bit more on @spirali's answer, HyperQueue treats files in a similar way as bash, so you cannot simply execute a file that is not executable. There are several alternatives to making the file executable itself.
1) Explicitly start the interpreter and give it the file, e.g. `$ hq submit -- /usr/bin/bash <script>.sh`
2) If the script has a shebang, you can submit it directly, like this: `$ hq submit <script>.sh`. Note that this currently does not work if the path to `<script>.sh` is relative or absolute! So `hq submit /a/b/c/script.sh` or `hq submit ../script.sh` will not parse the shebang. It only works if you just submit a name of a script in the current directory.
  We have included this special case because a lot of people were submitting scripts like this. We are thinking about just using the shebang special case for all files ending with `.sh`, regardless of the path given to them, which will probably be more natural for HQ users.

**Comment by pditommaso** [comment]
I've read the docs and I have to say that I love the fresh approach of HyperQueue to distributed tasks computing. It fits perfectly the nextflow model, and I see no problem integrating it. 

@spirali @Kobzol Do you guys have a discussion forum or a chat channel? 

@Nortamo Let me know if you want to contribute the support for HyperQueue to Nextflow. I can help to speed up the integration.

**Comment by Kobzol** [comment]
@pditommaso We currently do not have any public chat channel, but we can create one (e.g. Discord) if there's enough interest. If you want to discuss anything currently, feel free to open a discussion [here](https://github.com/It4innovations/hyperqueue/discussions), at our discussion forum on GH.

**Comment by pditommaso** [comment]
Could not resist drafting the implementation for HyperQueue. A minimal working version is available in [this branch](https://github.com/nextflow-io/nextflow/tree/hyperqueue-dev), see   f1e2b91b32cf7941a0a5c1bd10ee2e4a71c9add8. 

As foreseen, it fits quite nicely into the Nextlow model. There are just a couple of points that should be addressed to have 

### 1. HQ directives are not honoured 

My understanding is that task script can contain directives starting with the `#HQ` prefix to control task options. 

Nextflow is setting the directives shown below. However, it looks like they are not being applied

```
#!/bin/bash
#HQ --name nf-foo
#HQ --log /Users/pditommaso/Projects/nextflow/work/fd/8ebd2447f55bffc62c9db725ebd9f8/.command.log
#HQ --task-dir /Users/pditommaso/Projects/nextflow/work/fd/8ebd2447f55bffc62c9db725ebd9f8
# NEXTFLOW TASK: foo
set -e
set -u
.. JOB CODE HERE ..
```

Any clue what's wrong?  

### 2. Efficient jobs status retrieval 

In order to retry the job status, nextflow runs the command `hq --output-mode=json job list --all`

However, this produces a quite verbose output, which is not scalable when running >> 10k jobs. 

Is there are way to better control the job status output, ideally it should be possible to specify a range of job ids and the required status info, e.g. Job id, status, error message

**Comment by pditommaso** [comment]
Regarding point 1. apparently directives are not processed when the job is submitted like this 

```
hq submit bash task.sh
```

Instead they are applied as expected when is submitted directly 

```
hq submit task.sh
```

However the latter requires the script to be executable

**Comment by Kobzol** [comment]
1) Indeed if you pass `bash` as the command, we can't really know that you want to execute a bash script, so directives are not parsed. If you just pass a script, it can be executed even if it's not executable, but it has to contain a shebang. With the caveat that in the current HQ version, this will only work if the script is passed without any relative/absolute path prefix. From the next HQ version this will work for scripts passed in any way, i.e. with absolute and relative paths.

    I wonder why do you use directives at all though, when you are invoking `HQ` programmatically? You can just execute e.g.
    ```bash
    $ hq submit --name <name> --task-dir <task-dir> ... -- bash foo.sh
    ```

2) You can use `hq job info <job-selector>` to query the status of an individual job by its ID. You can also use a range of job IDs, i.e.
    ```bash
    $ hq job info 1-5,10-12
    ```
    Or you can use `hq job tasks <job-selector>` to display detailed information about tasks of selected jobs.

    I would just like to point out that if multiple invocations of the same command on more files/input data is desired, it would be much better to use [multiple tasks](https://it4innovations.github.io/hyperqueue/stable/jobs/arrays/) inside a single job, rather than launching a large number of jobs.

**Comment by pditommaso** [comment]
>  If you just pass a script, it can be executed even if it's not executable, but it has to contain a shebang

Yes, that works provided the script the suffix is `.sh`. However nextflow uses a different suffix for some historical reason.

Any chance a future version will be able to handle correctly scrip just relying on the shebang header?  

> I wonder why do you use directives at all though, when you are invoking HQ programmatically?

Because having in the script it's important for tracking and debugging purpose. A user can precisely replicate a job execution just using the script create by nextflow. 


> You can use hq job info <job-selector> to query the status of an individual job by its ID.

Yes, I've noticed. That's useful however the resulting json can even be more verbose than `hq job list`. 

I think using `hq job info <range>` piped with `jq` can provide a decent workaround. I think  it would be very useful to add the `job info` or `job list` command the ability to pick the attributes to be returned. 

  
> I would just like to point out that if multiple invocations of the same command on more files/input data is desired, it would be much better to use [multiple tasks](https://it4innovations.github.io/hyperqueue/stable/jobs/arrays/) inside a single job,

Well, we are exploring the support for HyperQueue precisely because it looks more efficient  to handle a large volume of *jobs* without the need to use *task arrays*, which is a concept  not supported by nextflow

**Comment by Kobzol** [comment]
> Any chance a future version will be able to handle correctly scrip just relying on the shebang header?

If I understand it correctly, you want to be able to execute any file/extension if it has a shebang? That sounds reasonable, we'll add support for it, `bash` also works like this. I created an [issue](https://github.com/It4innovations/hyperqueue/issues/418) for this.

> I think using hq job info <range> piped with jq can provide a decent workaround. I think it would be very useful to add the job info or job list command the ability to pick the attributes to be returned.

I see. Have you run into any specific bottlenecks? It shouldn't matter thta much if it outputs a lot of data if it's handled by a program. The JSON output format is not stable yet, and I'm not sure if using the CLI interface for doing complex queries like selecting arbitrary fields of task information is ideal. We have an experimental Python API for more programmatic usage, but I understand that wouldn't be very useful for Nextflow. Maybe we can also design some RPC/Rest API/whatever to allow easier programmatic access to the data of a running HyperQueue instance.

> Well, we are exploring the support for HyperQueue precisely because it looks more efficient to handle a large volume of jobs without the need to use task arrays, which is a concept not supported by nextflow

I see. For the common/manual usage of HyperQueue, users are expected to create task arrays, so HQ is tuned for that usage. We would be interested in how HQ can handle your usecase of a potentially large amount of jobs, let us know if you hit any bottlenecks.

**Comment by pditommaso** [comment]
> If I understand it correctly, you want to be able to execute any file/extension if it has a shebang? That sounds reasonable, we'll add support for it, bash also works like this. I created an https://github.com/It4innovations/hyperqueue/issues/418 for this.

That's nice. Thanks!

> It shouldn't matter thta much if it outputs a lot of data if it's handled by a program.

Well, streaming the output it should be possible to parse a large output, but would not be much efficient for a large number of tasks. 

Still thinking it would be very useful to have `hq job list` showing all *pending* and *running* tasks PLUS jobs completed/failed in the last x minutes/time (specified via cli option). Does it sound reasonable to you? 

> Maybe we can also design some RPC/Rest API/whatever to allow easier programmatic access to the data of a running HyperQueue instance

This sounds interesting in the longer term if you are planning to make HyperQueue more integrable with other services. 

> We would be interested in how HQ can handle your usecase of a potentially large amount of jobs, let us know if you hit any bottlenecks.

That's the plan. Thanks!

**Comment by Kobzol** [comment]
> Still thinking it would be very useful to have hq job list showing all pending and running tasks PLUS jobs completed/failed in the last x minutes/time (specified via cli option). Does it sound reasonable to you?

We will try to add some more (e.g. time based) filters to the job list.

**Comment by Nortamo** [comment]
@pditommaso , I can contribute, very many thanks for the fast response and the mwp.  
Is it preferable to create PRs from my own fork to that branch or copy your implementation, and create a new PR into the master branch?

Some quick notes 

For large multicore HPC workloads it would be nice to pin the processes to the correct cores, Hq can do this 
with just `--pin` question is can we just hardcode this as the default or does nextflow have some sensible abstracted option for this? 

Other features add which are straightforward are memory and accelerator support. Using `--resource mem=` and `--resource gpu=` After that I think all the features are there for this to be super useful. 

I would also like to have a executor specific option (e.g as a configuration option or using an environment variable ) to set the HyperQueue
server dir  ( the option is `--server-dir` , I don't think there is any official environment variable to set this.)
From the point of view of a HPC environment maintainer, we would really want to discourage running job related things on the login nodes. With the option, individual HPC sites can then decide how they want to instruct their users to run. 

On the HQ side it would of course be a nice feature to have some environment variable / build time configuration to change the default server dir away from home and e.g to the current directory + some official environment variable to set the server dir to a specific directory.      
 

> I see. For the common/manual usage of HyperQueue, users are expected to create task arrays, so HQ is tuned for that usage. We would be interested in how HQ can handle your usecase of a potentially large amount of jobs, let us know if you hit any bottlenecks.

I have not run any serious test, but 12800 (100 nodes) concurrent nextflow processes using HQ seemed to work without issues. Also ran some real pipeline with 40K processes also without any issues.

**Comment by pditommaso** [comment]
> , I can contribute, very many thanks for the fast response and the mwp.

**Comment by Nortamo** [comment]
I now created a PR based on your branch, you should have edit access (Allow edit by maintainers checked) #2896 

Did the following changes: 

- Support for setting memory and accelerator
- Changed `--task-dir` to `--cwd` as the previous option has the effect to create a dir and set an environment variable, not change the working directory.
- Overrode the job cancel has HQ seems to expect comma separated jobids when handling multiple jobs. 

I tested that the directives in the file seem to work when using the fixed HQ version from https://github.com/It4innovations/hyperqueue/pull/420.

I could not immediately figure out the best way to use `clusterOptions` for the `--server-dir` (more info in the PR).
but pinning works well.

**Comment by pditommaso** [comment]
Include experimental implementation as part of version `22.05.0-edge`
