### ISSUE TITLE
Why the "Hello world" demo takes 2.8 second?

### ISSUE THREAD

**Issue by shenwei356** [nextflow-io/nextflow#287]
I run the hello world demo on my laptop, but it takes so long and the CPU usage is very high.

Hardware and software:

```
CPU: Intel Core i5-3320M @ 2.60GHz, two cores/4 threads
RAM: DDR3 1600MHz, 12GB
SSD: SAMSUNG 850 EVO 250G, SATA-3
OS: Fedora 25 (Scientific KDE spin), Kernal: 4.9.7-201.fc25.x86_64
JVM: java version "1.8.0_111"
    Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

Command and result:
```
$ cat hello.nf 
process sayHello {

    """
    printf 'Hello world! \n'
    """
}

$ /usr/bin/time -v nextflow run -process.echo true hello.nf
N E X T F L O W  ~  version 0.23.2
Launching `hello.nf` [prickly_goldstine] - revision: fa21bab5e5
[warm up] executor > local
[ca/9a9a86] Submitted process > sayHello (1)
Hello world! 
        Command being timed: "nextflow run -process.echo true hello.nf"
        User time (seconds): 8.24
        System time (seconds): 0.21
        Percent of CPU this job got: 294%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.86
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 219356
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 3
        Minor (reclaiming a frame) page faults: 59415
        Voluntary context switches: 2975
        Involuntary context switches: 2004
        Swaps: 0
        File system inputs: 0
        File system outputs: 128
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

I takes 2.86 seconds and 294% of CPU (4 cores)!!!

```
        Percent of CPU this job got: 294%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.86
```
CPU usage:

![CPU usage](https://i.imgsafe.org/d6d4c21d9a.png)

**Comment by pditommaso** [comment]
It takes 8 seconds also in any following run ?

**Comment by shenwei356** [comment]
@pditommaso It's 2.86s not 8s.

Here's another version: `hello2.nf`

```
process sayHello {

    """
    printf 'Hello world! \n'
    sleep 2;
    printf 'Wake up after 2s. \n'
    """
} 

```

Command and result:

```
$ /usr/bin/time -v nextflow run -process.echo true hello2.nf
N E X T F L O W  ~  version 0.23.2
Launching `hello2.nf` [agitated_babbage] - revision: a466776cb8
[warm up] executor > local
[f1/d6091e] Submitted process > sayHello (1)
Hello world! 
Wake up after 2s. 
        Command being timed: "nextflow run -process.echo true hello2.nf"
        User time (seconds): 9.28
        System time (seconds): 0.26
        Percent of CPU this job got: 192%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:04.95
```

It takes 4.95s. CPU usage:

![image](https://i.imgsafe.org/d6ee4ee528.png)

It seems that a simple `printf` command uses 4 threads (the second peak). And the initial process takes too long, and occupy all CPU cores.

**Comment by pditommaso** [comment]
Nextflow is designed for distributed and parallel job executions in cluster of computers. Therefore even for the execution of a simple *Hello world* it internally requires several threads to run it (task scheduler, dataflow parallelisation, etc) without counting the threads used by the JVM itself (garbage collector, JIT, etc). So the use of multiple threads is expected. 

Reading the execution time a certain startup and task executions overhead is expected. It is important to highlight that NF is designed for corse grain tasks parallelisation and long running pipelines (hours if not days). In this context a startup penalty of 1-2 seconds or a few ms on each task is negligible. 

Said that I've noticed that half the time reported in your test is spent during the execution shutdown and this actually looks weird. I will try to instigate the reason.

**Comment by shenwei356** [comment]
Get it. Thank you very much for detailed explain.
