### ISSUE TITLE
If `NXF_OFFLINE` is a non empty string then offline mode is enabled

### ISSUE THREAD

**Issue by nebfield** [nextflow-io/nextflow#2881]
### Expected behavior and actual behavior

I'm not sure if this a bug or I'm being dumb :smile: 

Offline mode is enabled if `NXF_OFFLINE` is set to any non-empty string (even `false`, which is a bit confusing).

From the documentation:

> When true disables the project automatic download and update from remote repositories (default: false).

The behaviour described below is probably OK, but perhaps the documentation should be clearer?

### Steps to reproduce the problem

:heavy_check_mark: 
```
$ export NXF_OFFLINE=true
$ nextflow run hello
N E X T F L O W  ~  version 22.02.1-edge
Unknown project `nextflow-io/hello` -- NOTE: automatic download from remote repositories is disabled
```
:x:
```
$ export NXF_OFFLINE=false
$ nextflow run hello
N E X T F L O W  ~  version 22.02.1-edge
Unknown project `nextflow-io/hello` -- NOTE: automatic download from remote repositories is disabled
```
:heavy_check_mark:
```
$ export NXF_OFFLINE=""
$ nextflow run hello
N E X T F L O W  ~  version 22.02.1-edge
Pulling nextflow-io/hello ...
 downloaded from https://github.com/nextflow-io/hello.git
...
```
:question: 
```
$ rm -rf ~/.nextflow/assets/
$ export NXF_OFFLINE="coconut"
$ nextflow run hello
N E X T F L O W  ~  version 22.02.1-edge
Unknown project `nextflow-io/hello` -- NOTE: automatic download from remote repositories is disabled
```

**Comment by jorgeaguileraseqera** [comment]
Yes I think it's a bug at

https://github.com/nextflow-io/nextflow/blob/7b1b845e953cdda3d35ade3d29afdcb0b5647d0f/modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy#L223-L223

instead to use `as boolean` we need to use `.toBoolean()`

I'll double-check and create a fix

Thanks

**Comment by pditommaso** [comment]
Solved. Thanks for reporting the problem.
