### ISSUE TITLE
Render -with-dag file before pipeline execution

### ISSUE THREAD

**Issue by drpatelh** [nextflow-io/nextflow#2883]
Any files defined by `-with-dag` will be produced when the pipeline finishes/exited. It would be nice to have the ability to produce this file before the pipeline execution instead.

**Comment by pditommaso** [comment]
I think this has been implemented via preview mode https://github.com/nextflow-io/nextflow/blob/20cfbfd3595270b0a71a32fe95de52936bbd475b/modules/nextflow/src/main/groovy/nextflow/cli/CmdRun.groovy#L240-L240. See aa8f1aa4

**Comment by bentsherman** [comment]
It sure does
