### ISSUE TITLE
Executable files in the `bin` folder are not found when parent path contains a colon char

### ISSUE THREAD

**Issue by biowang** [nextflow-io/nextflow#289]
When you have a working path containing colon characters (:).  execute file in folder bin will be not work.

Since that character is used a path separator, that breaks the `PATH` variable and so your script it's not accessible. 

```
[wangliangliang@dn-23 abc]$ more a.nf
process abc {


    """
    test.sh
    """
}
[wangliangliang@dn-23 abc]$ ll bin/
total 4
-rwxrwxr-x 1 wangliangliang wangliangliang 9 Feb 14 17:34 test.sh
[wangliangliang@dn-23 abc]$ more bin/test.sh
echo xxx
[wangliangliang@dn-23 abc]$ nextflow a.nf
N E X T F L O W  ~  version 0.21.2
Launching a.nf
[warm up] executor > local
[24/39e9a3] Submitted process > abc (1)
Error executing process > 'abc (1)'

Caused by:
  Process `abc (1)` terminated with an error exit status (127)

Command executed:

  test.sh

Command exit status:
  127

Command output:
  (empty)

Command error:

  .command.sh: line 2: test.sh: command not found

Work dir:
  /native/wangliangliang/base_WGC102231D_2017-02-14_10:40:58/abc/work/24/39e9a3df83df5bd5a9fff9e91085ca

Tip: view the complete command output by changing to the process work dir and entering the command: 'cat .command.out'
```

**Comment by pditommaso** [comment]
NF adds the project `bin` folder to the `PATH` environment variable to allow processes to access those executable files. 

However the colon character ie. `:` is meant to be used as separator of multiple paths that can be specified by the `PATH` variable. Thus it cannot be used in a file name path. See [here](http://stackoverflow.com/a/29213487/395921).

The simplest workaround is to avoid to use a work path containing such character. 

Take also in consideration that NF project can be located in a folder other than the launching directory. For example you can store your project files into `/home/user/my-project` which would contains pipeline script(s) and the `bin` directory. Then you can run it from any path with the command `nextflow run /home/user/my-project/script-name.nf`.
