### ISSUE TITLE
No Section In Docs On How/Where To Report Bugs (the second 1/2 now works)+ The First Tutorial Script Has A Dead Link

### ISSUE THREAD

**Issue by iamh2o** [nextflow-io/nextflow#2895]
## Bug report 
The first tutorial script fails to run, and it was not clear where to report this from the docs, I turned to google after also failing to find the correct nf on github directly.

### Expected behavior and actual behavior

For (a). A top level section (and apologies if I missed it) on contacting the community to report problems / bugs....encourage participation :-)

For (b) For the tutorial script to run to completion.

### Steps to reproduce the problem

  > (a) search for reporting bugs, nothing relevant is returned.

  > (b) Go to : [
  > Your First Script](https://www.nextflow.io/docs/latest/getstarted.html#:~:text=self%2Dupdate-,Your%20first%20script,%EF%83%81,-Copy%20the%20following)

  - copy/paste script into emacs term, save.
  - run script.... (AND SUCCESS! Well that has not happened the prior 4 times. ).  
  - So, mostly resolved already, you're fast.  I unfortunately don't have all of the but output b/c I tried in/outside my VPN.  The here was a link out to nf non responsive, this being one of them:
`  https://api.github.com/repos/nextflow-io/tutorial/contents/main.nf`

  
  returning simply:

  ```
  {
  "message": "Not Found",
  "documentation_url": 
   "https://docs.github.com/rest/reference/repos#get-repository-content"
   }
   ```

#### (Provide a test case that reproduce the problem either with a self-contained script or GitHub repository)

Search for how to report bugs in he doc site pages. Also, I'd have been happy to stub something out to start a conversation with real changes, but the docs, unlike other similar repos do not appear to allow for branching edits directly.  [For Example](https://snakemake.readthedocs.io/en/stable/#support) and all pages have an [edit on github](https://github.com/snakemake/snakemake/blob/bbed20f7c1de220353715838716e0de80e694b8e/docs/index.rst) url in the top right, which I've personally found quite nice

#### (Copy and paste here output produced by the failing execution. Please highlight it as a code block. Whenever possible upload the `.nextflow.log` file.)

Lost to a close terminal, and now is running.

### Environment 

* Nextflow version: [?] Using NF version 22/04.0.5697 
* Java version: 
  * openjdk 17.0.3 2022-04-19
  * OpenJDK Runtime Environment (build 17.0.3+7-Ubunt-0ubuntu0.20.04.1)
  * OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

* Operating system: on Ubutu20
* Bash version: 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

####(Add any other context about the problem here)

Looking forward to learning more and contributing!

**Comment by jorgeaguileraseqera** [comment]
Thanks for your comment

about the contact for the community you're right, we don't have in the documentation any link mainly because we have it on the main page of the project (https://www.nextflow.io/) under the community section

about the tutorial, if it fails again please open a new issue and attach the log
