### ISSUE TITLE
Enable running processes on different regions when running on cloud executors

### ISSUE THREAD

**Issue by mbosio85** [nextflow-io/nextflow#2902]
## New feature

It would be great if Nextflow cloud executors (e.g. `awsbatch` ) enable running multiple processes in different regions. 
Currently the executor is specified at the pipeline configuration level, together with the work-dir, which assumes that all the execution will be performed in the same region.

## Usage scenario 

The use case in mind is to process data that cannot be moved outside a specific region together with data residing elsewhere.
By enabling a scenario like:
- Process 1: analyzes data in `eu-central-1` and extracts summary values that can be sent outside
- Process 2: analyzes data in `us-west-1` and extracts summary values that can be sent outside
- Process 3: combines the summary values from 1 and do something with them 

This assumes that the user has access to compute environments, queues and S3 buckets in multiple regions before starting the pipeline.

## Suggest implementation 
Ideally, if the executor properties could be specified at the process level it may be possible to have processing on multiple regions inside the same pipeline.
Or, considering that now Nextflow allows multiple executors inside the same pipeline, if it were possible to create new executors from the  `awsbatch` template with different characteristics, it may address the issue by using the existing capabilities for hybrid processing.

**Comment by jorgeaguileraseqera** [comment]
@bentsherman can you provide a little example script about what are you thinking, please?

**Comment by pditommaso** [comment]
> Rather than have a separate executor per region, it would make more sense for the user to create a separate queue for each region, and assign different processes to different queues accordingly.

The problem of this approach in order to access the queue the AWS client needs the information of the region. 

Essentially everything into AWS (or other cloud) is segregated into a region

**Comment by bentsherman** [comment]
So currently the region is provided via `aws.region` config option or `AWS_DEFAULT_REGION` environment variable. Alternatively or in addition, we could specify a different region for each queue:
```
process {
    executor = 'awsbatch'
    queue = 'my-batch-queue', region: 'us-east-1'
}
```

**Comment by jorgeaguileraseqera** [comment]
ah, ok

our current approach is something similar:

```
process {
    executor = 'awsbatch'
    region = 'us-east-1'
    queue = 'my-batch-queue'
}
```

**Comment by bentsherman** [comment]
That would work as well, currently `region` cannot be specified at the process level.

**Comment by JuliaMcGonigle** [comment]
Was this ever resolved and how? It is super unclear from all the docs how to do this?
