### ISSUE TITLE
Possible NF stream leak

### ISSUE THREAD

**Issue by tantrev** [nextflow-io/nextflow#291]
I think I may have encountered some sort of NF stream leak. It's kind of hard to supply a test case b/c the data I'm using is ~700GB & replicating it seems to take the whole dataset. But the work folder of a problem command is [here](http://epilog.bio/files/ea674b6f06dd65c4c90f509c0f06c1.tar.gz) and my NF script is [here](http://pastebin.com/raw/FB84eezy). Basically when I have something like string = "echo ${var1} ${var1}", I'm getting two different variables put in for var1.

An explicit example of a faulty command produced may also be seen [here](http://pastebin.com/raw/hXas8jMt).

If it would help at all for a test case, I am more than happy to provide remote access.

**Comment by pditommaso** [comment]
Which is the variable/command that's reporting a wrong value in the script you have linked ?

**Comment by tantrev** [comment]
These two code regions are the likely suspects.  Now that I've been thinking about it more though, it's possible that my "transform" operation is the culprit here, instead of NF.

`def picard_AddOrReplaceReadGroups_transform = {  strain,species,ref_fa_filename,run, experiment, study, source, paired, population, read_length, mbytes,mergeid,rgid,rglb,rgpl,rgpu,rgsm ->
                                                 input_dir = "${data_dir}/bam-samples/${source}/${study}/${experiment}/${run}";
                                                 input_bam = "${input_dir}/${run}.Aligned.sortedByCoord.out.bam";

                                                 output_dir = "${data_dir}/bam-processed-samples/${source}/${study}/${experiment}/${run}";
                                                 output_bam = "${output_dir}/${run}.rg_added.Aligned.sortedByCoord.out.bam";

                                                 checkFileString = file("${output_bam}.final").exists().toString();
                                                 if(checkFileString=="false"){
                                                     """
        mkdir -p ${output_dir} && ${java_path} -jar ${picard_path} AddOrReplaceReadGroups I=<(${anaconda_base}/samtools view ${input_bam} -o /dev/null -U - -L ${data_dir}/spike_in/regions.sorted.bed | ${anaconda_base}/samtools view -ht ${ref_fa_filename}.fai - -u) O=${output_bam} RGID=${rgid} RGLB=${rglb} RGPL=${rgpl} RGPU=${rgpu} RGSM=${rgsm} && touch ${output_bam}.final
        """
                                                 }
                                                 else{
                                                     """
        """
                                                 }
}`


`process picard_AddOrReplaceReadGroups{
    errorStrategy "retry"
    maxErrors 99999
    maxRetries 99
    time "4h"
    executor "slurm"
    clusterOptions "--account=${accounty} --nodes=1 --mem-per-cpu=2000"
    module "jdk/1.8.0_25"
    queue "${partition}"

    input:
    val arrayVal1 from ch1c

    output:
    val arrayVal1 into out1

    script:
    work_commands = arrayVal1.stream().map(picard_AddOrReplaceReadGroups_transform).collect().join(" \n ")

    """
    echo -e "${work_commands}" | ${anaconda_base}/parallel --use-cpus-instead-of-cores ::::
    """
}`

**Comment by tantrev** [comment]
I have a sneaking suspicion I'm getting errors because I'm initializing variables within a .map() operation on a stream.  I'm trying to rewrite the code now...

**Comment by pditommaso** [comment]
I would suggest to declare all local variable with `def` prefix eg. 

```
def input_dir = "${data_dir}/bam-samples/${source}/${study}/${experiment}/${run}";
def input_bam = "${input_dir}/${run}.Aligned.sortedByCoord.out.bam";
:
```

including the in `script` section

**Comment by tantrev** [comment]
Thanks, I'll try that right now.

**Comment by tantrev** [comment]
Adding `def` prefixes fixed everything - thanks again for solving yet another of my idiotic mistakes. 😄
