### ISSUE TITLE
Documentation bug or confusion

### ISSUE THREAD

**Issue by jimrybarski** [nextflow-io/nextflow#2931]
In the [Basic concepts](https://www.nextflow.io/docs/latest/basic.html) section of the documentation, there's some text that reads:

> Instead, because the first process defines the channel `top_hits_ch` in its output declarations, and the process `extractTopHits` defines the channel in its input declaration, a communication link is established.

However, `top_hits_ch` does not appear in the code block that the text references. There is a hard-coded filename in the output (`path "top_hits.txt"`) instead. In the input of the function that reads from that output, it uses `path top_hits`. Are the channel names auto-derived or is there an inconsistency here?

**Comment by jorgeaguileraseqera** [comment]
@jimrybarski  you're right. The previous version of this documentation used DSL syntax version 1:

```
process blastSearch {
        input:
        file query from query_ch

        output:
        file "top_hits.txt" into top_hits_ch

        """
        blastp -db $db -query $query -outfmt 6 > blast_result
        cat blast_result | head -n 10 | cut -f 2 > top_hits.txt
        """
    }

    process extractTopHits {
        input:
        file top_hits from top_hits_ch

        output:
        file "sequences.txt" into sequences_ch

        """
        blastdbcmd -db $db -entry_batch $top_hits > sequences.txt
        """
    }
```

and the example was recently migrated to DSL2 but not the explanation you mention

We'll update it. Thanks
