### ISSUE TITLE
Issues running large workflows on GCP

### ISSUE THREAD

**Issue by danielecook** [nextflow-io/nextflow#2936]
## Bug report 

I am using the GCP lifesciences executor. In general, it works well when pipelines are smaller. However, larger pipelines with many jobs can trigger errors.

For example:

```
Error executing process > ***

Caused by:
  Cannot assign requested address (connect failed)
```

Additionally, the cache does not always work. I see warnings like this, and the cache is rerun:

```
WARN: Unable to get file attributes file: *** -- Cause: com.google.cloud.storage.StorageException: All 0 retries failed. Waited a total of 0 ms between attempts
```

If I understand the warning message correctly, it sounds like no retries were performed.

These issues only crop up in the later stages of a pipeline that is already heavily cached, so my guess is lightening up on the requests to GCP could resolve the issue, and performing retries as well.

I am happy to help test/debug. Please let me know how I can help.

### Environment 

* Nextflow version: 22.05.0-edge
* Java version: 11.0.15 2022-04-19
* Operating system: linux
* Bash version:  4.4.20

**Comment by bentsherman** [comment]
Hi @danielecook , you should try out the new [Google Batch executor](https://nextflow.io/blog/2022/deploy-nextflow-pipelines-with-google-cloud-batch.html) in the latest edge release. Supposedly Google Batch provides some better performance and stability over Life Sciences... would be good to see if it actually does 😄 if you would like something to test.

**Comment by danielecook** [comment]
Thanks @bentsherman. I did give the new batch executor and in general pretty good so far. I do see some minor issues (ie I couldn't figure out how to run in multiple regions), but I imagine these will be worked out over time.
