### ISSUE TITLE
Nextflow is trying to use the Java VM with java version "1.8.0_333"

### ISSUE THREAD

**Issue by Mbrick1** [nextflow-io/nextflow#2954]
Hi, I'm trying to install nextflow on windows however I'm getting this error:

>curl -fsSL get.nextflow.io | bash
-bash: line 284: java: command not found
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: java
 NXF_OPTS:

java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)

**Comment by khushishri26** [comment]
Could you please share how this issue was resolved for you?
