### ISSUE TITLE
Allow the use relative paths for symlinks process input files

### ISSUE THREAD

**Issue by LukeGoodsell** [nextflow-io/nextflow#296]
When running a workflow in a directory that may be mounted by multiple systems at different mount-points, the use of absolute paths for the symlinks in both `publishDir` directories and `work/...` subdirectories mean that the input/output symlinks are only valid on the original system.

This situation may be encountered by machines that are working on an NFS mount, or when running workflows within a docker instance and outputting to the host machine's filesystem.

It would be useful in such circumstances to have the option of using relative paths for the symlinks - the symlinks point to the target relative to the directory in which they are found.

**Comment by pditommaso** [comment]
Finally merged, thanks for the contribution @LukeGoodsell and sorry it it took so much time. 

You can test using version `0.31.0-SNAPSHOT` as shown below: 

```
NXF_VER=0.31.0-SNAPSHOT nextflow run .. etc
```
