### ISSUE TITLE
Add compatibility with AWS IMDSv2

### ISSUE THREAD

**Issue by matdoering** [nextflow-io/nextflow#2962]
## New feature: compatibility with AWS EC2 IMDSv2

For security purposes, it is recommended to use the newest version of AWS EC2 metadata service, IMDSv2, which works with session tokens rather than plain HTTP requests via http://169.254.169.254, see [here](https://www.uptycs.com/blog/you-should-be-using-aws-imdsv2-heres-why-and-how-to-do-it) for more information. Currently, Nextflow only supports IMDSv1, as it directly queries the metadata services and doesn't make use of tokens, see the [AmazonClientFactory function fetchIamRole](https://github.com/nextflow-io/nextflow/blob/2fd482880e3adecf7b9612902bf4cb280ecdaf1b/plugins/nf-amazon/src/main/nextflow/cloud/aws/AmazonClientFactory.groovy#L137). Adding support for IMDSv2 would enable running Nextflow in more strict IT environments, where IMDSv1 is typically flagged as a security risk.

## Usage scenario 

The usage scenario is running Nextflow on AWS with an EC2 instance profile setup configured for IMDSv2 for enhanced security. This is currently not possible without specifying access/secret keys explicitly.

## Suggest implementation 

As suggested by the [AWS Guide on IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html), a token needs to be created and used before querying the metadata service. This should be done by all of the nextflow tasks individually to ensure that the token is up to date.

In case that this feature is not implemented, it would be reasonable to change the error message in `fetchIamRole` from a `log.trace` to something more urgent as this really is a big problem and not something that should be hidden in the trace output.

**Comment by bentsherman** [comment]
Closed by #3425
