### ISSUE TITLE
createDirectory should fail specifically if the directory it's asked to create exists.

### ISSUE THREAD

**Issue by pontus** [nextflow-io/nextflow#2968]
For backstory, see https://nextflow.slack.com/archives/C02T97HAV5M/p1655317064553369

It appears there's a likely issue when using s3fs and `createDirectories` in `java.nio.Files` - it expects `createDirectory` from the filesystem provider to raise an `FileAlreadyExistsException` if the directory exists whereas s3fs doesn't check and goes on to do a `putObject`.

I don't know how that's contractually handled for "directories" in AWS s3, but it seems (see backstory) one can at least get a thrown `IOException` because AWS s3 returns a 503 Slowdown when called for the same object "simultaneously". 

There's a fixme at https://github.com/nextflow-io/nextflow-s3fs/blob/master/src/main/java/com/upplication/s3fs/S3FileSystemProvider.java#L469 for this already.

**Comment by pditommaso** [comment]
Moved to Nextflow repo, since the s3 file system now makes part of the amazon plugin in the main project
