### ISSUE TITLE
Apptainer support

### ISSUE THREAD

**Issue by ghuls** [nextflow-io/nextflow#2970]
## New feature

It would be great if Apptainer is natively supported. It should be 99% the same as singularity.

http://apptainer.org/
Singularity has joined the Linux Foundation and is now Apptainer!

## Usage scenario 

Apptainer (as singularity symlink) complains about deprecated usage when it sees SINGULARITYENV env variables.
```
Command error:
WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be
supported in the future, use APPTAINERENV_TMPDIR instead
WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will
not be supported in the future, use APPTAINERENV_NXF_DEBUG instead 
```

## Suggest implementation 

Add APPTAINERENV envs instead of SINGULARITYENV when using apptainer.

**Comment by matthdsm** [comment]
Would it be very involved to add an `apptainer` alias for the `singularity` settings which modifies the env value prefixes?

**Comment by tbugfinder** [comment]
Following the apptainer development it be valuable to add it as its dedicated container engine compared to just "allowing" APPTAINER* ENV variables for singularity binary.

**Comment by pditommaso** [comment]
This is a desirable feature but the community should step in and provide a PR. It should be quite easy to implement the Apptainer support by creating an `AptainerBuilder` as done for singularity 

https://github.com/nextflow-io/nextflow/blob/fdde418f053fd462a54f5ca4b9f3390792ebb9a8/modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy#L30-L30

**Comment by jfy133** [comment]
Looks like it was done here: https://github.com/nextflow-io/nextflow/pull/3345

**Comment by pditommaso** [comment]
It is! already in 22.11.0-edge release

**Comment by matthdsm** [comment]
Can this also be added to the docs?
https://www.nextflow.io/docs/latest/container.html#singularity

**Comment by pditommaso** [comment]
Feel free to provide a PR for that

**Comment by maxulysse** [comment]
@matthdsm no PR for the docs?

**Comment by matthdsm** [comment]
Here we go!
https://github.com/nextflow-io/nextflow/pull/3699
