### ISSUE TITLE
Cannot set maximum runtime for AWS Batch jobs

### ISSUE THREAD

**Issue by TonyWildish-ETX** [nextflow-io/nextflow#2977]
As per the documentation (https://www.nextflow.io/docs/latest/executor.html#aws-batch), AWS batch jobs do not accept the `time` parameter, so any stuck job will run for the maximum duration allowed by the queue definition. It would be great if the time limit could be set per-process, as for some other executors.

**Comment by pditommaso** [comment]
I think it's a glitch in the docs. The `time` directive is actually supported https://github.com/nextflow-io/nextflow/blob/a06b444236164b88218ef548f7bf834727faa33f/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy#L651-L659

**Comment by TonyWildish-ETX** [comment]
you're right! The reason my workflow failed to terminate was that I'd borrowed some code from another workflow that set `params.max_time`, and then used that to set `time` in the profiles, but I'd mangled it and only had the `max_time` there. So my mistake, sorry for the noise.

The documentation could do with updating though :-)
