### ISSUE TITLE
pbspro executor - bad qstat usage

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#2978]
Implementation of pbspro executor uses currently wrong qstat and output parsing.

1. https://github.com/nextflow-io/nextflow/blob/2b6f70a8fa55b993fa48755f7a47ac9e1b584e48/modules/nextflow/src/main/groovy/nextflow/executor/PbsProExecutor.groovy#L91 this command can return shortened PBS server such as:
```
qstat -B
Server             Max   Tot   Que   Run   Hld   Wat   Trn   Ext Status
---------------- ----- ----- ----- ----- ----- ----- ----- ----- -----------
cerit-pbs.cerit*     0 37934   718  1823  1622     0     0     3 Scheduling
```

so parsing should be improved.

2. https://github.com/nextflow-io/nextflow/blob/2b6f70a8fa55b993fa48755f7a47ac9e1b584e48/modules/nextflow/src/main/groovy/nextflow/executor/PbsProExecutor.groovy#L89 this command fails, if the `queue` is routing queue and not execution queue because running job is not in this queue but it is moved to execution queue.

We can fix both just issuing `qstat -f` alone.

**Comment by notestaff** [comment]
I'm seeing this issue too.  On our cluster, PBS Pro sometimes migrates jobs from the execution queue to which they have been submitted to another execution queue, on a different server.  Nextflow treats this as error:
[df/5cc3ad] NOTE: Process `process_ops_tile:READSEQ (47)` terminated for an unknown reason -- Likely it has been terminated by the external system -- Error is ignored

**Comment by bentsherman** [comment]
We have seen this issue with several of the HPC schedulers, so there is now a config option `executor.queueGlobalStatus` ([docs](https://nextflow.io/docs/edge/config.html#scope-executor)) which causes Nextflow to ignore the queue when querying task status. Just keep in mind that it will cause Nextflow to query all jobs, which could be expensive and/or stress the HPC scheduler.
