### ISSUE TITLE
Support for workdir on S3

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#2980]
Creating this issue to track implementation for support workdir on S3.

Are there already any ideas of implementing it for Grid and K8s executors?

**Comment by pditommaso** [comment]
How the task will be able to access to the data in the S3 bucket?

**Comment by xhejtman** [comment]
> How the task will be able to access to the data in the S3 bucket?

I suppose, it will be the same as for AWS driver - data must be staged in/out, I do not expect task to access S3 data directly.

**Comment by pditommaso** [comment]
Not that easy, when deploying with AWS Batch it can be assumed the compute nodes have `aws` CLI installed. 

Not the same for a generic compute environment. Even worst, assuming jobs run into a container, this means the `aws` should be be installed into the container

**Comment by xhejtman** [comment]
Nextflow does not have any s3 lib to do transfers?

**Comment by pditommaso** [comment]
Yes, but it's for data transfer on NF side. Jobs need to take care to download and upload their own files

**Comment by xhejtman** [comment]
So we must relay on some kind of s{3,4,5}cmd tool. For containers, we can use sidecar possibly with `emptyDir`, but I do not see easy solution for e.g., grid executors that do not use containers. 

However, I would assume that s3cmd could be a requirement when want to use s3 work directory.

**Comment by pditommaso** [comment]
one that could be interesting to explore is [rclone](https://rclone.org/) because has the support all major clouds.

Said that I'm still sceptical about the implementation because for real use cases, it would require re-assemble the tasks containers with such tool. Sidecar approach would be complex to manage and only available with K8s

**Comment by xhejtman** [comment]
for Grid, you already need to prepare executing environment carefully using e.g., conda if not using singularity. Perhaps pipeline can have some info whether it supports s3 files or not? 

btw, there is another request for s3 https://github.com/nextflow-io/nextflow/issues/2668

So, do I understand correctly, you do not see any way to support workdir on S3?

**Comment by xhejtman** [comment]
Do you mean you are thinking/preparin own implementation for this?

**Comment by pditommaso** [comment]
Yes

**Comment by schultzm** [comment]
@xhejtman I experienced I think a similar problem and solved it by building custom docker images including `awscli2`. The following lines were added to custom `Dockerfiles` to install `awscli2` into a container:

```
FROM ubuntu:latest

RUN apt-get update && apt-get -y install \
  curl \
  glibc-source \
  groff-base \
  less \
  unzip \
  sudo \

```

**Comment by smplyayush** [comment]
@schultzm [schultzm](https://github.com/schultzm)
Were you able to configure workdir with k8s executor?

**Comment by pditommaso** [comment]
We finally have a solution for this requirement. Nextflow can use S3 as work directory for Kubernetes (and other executors) using [Fusionfs and Wave containers](https://www.nextflow.io/blog/2022/rethinking-containers-for-cloud-native-pipelines.html). 


An example configuration is available at [this link](https://github.com/seqeralabs/wave-showcase/tree/master/example8).
