### ISSUE TITLE
Deprecate tap operator, extend set operator to return input channel

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#2981]
The [tap](https://www.nextflow.io/docs/latest/operator.html#tap) isn't marked as deprecated, but it depends on `Channel.create()` which is deprecated. I tried the top example with `Channel.empty()` instead but it didn't work, which makes sense because you shouldn't be able to just write to a channel like that.

So should we deprecate `tap` ? It seems like we could achieve the same functionality by changing `set` to return itself like `view`. Then you could use `set` in the middle of an operator chain to emit into a new channel while proceeding with other channel operators.

**Comment by pditommaso** [comment]
another option could to allow `tap` to create an new channel by name, e.g. 

```
something.tap('new_channel')
```

but not sure it makes much sense

**Comment by bentsherman** [comment]
Related #1766

**Comment by pditommaso** [comment]
Bump
