### ISSUE TITLE
nextflow kuberun failed because pod with random name already exists

### ISSUE THREAD

**Issue by WryYeti** [nextflow-io/nextflow#2996]
## Bug report 

My team recently had one of our nextflow runs fail because the run name chosen (ex. `maniac_crick`) was already assigned to a pod - the driver pod from a previous pipeline run. So when `nextflow kuberun` attempted to create the new driver pod with the run name (`maniac-crick`), it failed with `pod already exists`- see Program output for the full error. I think this may be a niche issue, as I discuss in the Additional context, but I wanted to bring it up and maybe discuss clean ways of avoiding it.

### Expected behavior and actual behavior

We ran `nextflow kuberun <pipelineName> -profile oke -with-trace trace.txt -with-report report.html -with-timeline timeline.html -with-dag dag.png -latest ...(many pipeline params)`, and expected the pipeline to create the Nextflow driver and then run our workflow.

Instead it almost immediately exited with the `pods \"maniac-crick\" already exists` error (see program output below).

### Steps to reproduce the problem

We've only naturally reproduced the issue once, but this script reproduces it (albeit as a contrived example):
```
create_crash () {
  #Create the pv and claims for the kuberun command
  kubectl apply -f https://k8s.io/examples/pods/storage/pv-volume.yaml
  kubectl apply -f https://k8s.io/examples/pods/storage/pv-claim.yaml
  # Create an nginx pod
  kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml
  # Create a Nextflow pipeline run with name, "nginx"
  nextflow kuberun -name nginx nextflow-io/hello -v task-pv-claim:/mnt/data
}

cleanup () {
  kubectl delete pod nginx
  kubectl delete pvc task-pv-claim
  kubectl delete pv task-pv-volume
}

if [ "$1" == "clean" ]; then cleanup; else create_crash; fi
```
If you save the above as a shell script and run it (or just run the commands in `create_crash`) you should encounter the issue

### Program output 

```May-13 17:49:19.258 [main] DEBUG nextflow.k8s.K8sDriverLauncher - Created K8s configMap with name: nf-config-481534c5
May-13 17:49:19.434 [main] ERROR nextflow.cli.Launcher - @unknown
nextflow.k8s.client.K8sResponseException: Request POST /api/v1/namespaces/default/pods returned an error code=409


  {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {
          
      },
      "status": "Failure",
      "message": "pods \"maniac-crick\" already exists",
      "reason": "AlreadyExists",
      "details": {
          "name": "maniac-crick",
          "kind": "pods"
      },
      "code": 409
  }


        at nextflow.k8s.client.K8sClient.makeRequestCall(K8sClient.groovy:431)
        at nextflow.k8s.client.K8sClient.makeRequest(K8sClient.groovy:389)
        at nextflow.k8s.client.K8sClient.post(K8sClient.groovy:348)
        at nextflow.k8s.client.K8sClient.podCreate(K8sClient.groovy:147)
        at nextflow.k8s.client.K8sClient.podCreate(K8sClient.groovy:161)
        at nextflow.k8s.client.K8sClient$podCreate$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
        at nextflow.k8s.K8sDriverLauncher.createK8sLauncherPod(K8sDriverLauncher.groovy:510)
        at nextflow.k8s.K8sDriverLauncher.run(K8sDriverLauncher.groovy:125)
        at nextflow.cli.CmdKubeRun.run(CmdKubeRun.groovy:75)
        at nextflow.cli.Launcher.run(Launcher.groovy:480)
        at nextflow.cli.Launcher.main(Launcher.groovy:639)
```

### Environment 

* Nextflow version: 22.04.0 build 5697
* Java version: 11.0.15
* Kubernetes version: 1.22
* Operating system: Ubuntu 18.04.6 LTS
* Bash version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

### Additional context

This may be a pretty niche issue, since in many cases the history check to not collide with previous run names or deleting pods soon after runs are complete would avoid name collisions, but our application initiates runs from different folders, and keeps pods for about a week to debug failures. Those choices, combined with bad luck to have two randomly chosen names be identical in the same week, led to the issue.

In any case, it's not that difficult to workaround - we can supply UUIDs to `-name` on calls to`kuberun`, or just retry if we see the exit with this error - but we thought we'd see if there's a method of gracefully working around the issue in Nextflow that the community would support. It might be difficult/unwise to get the list of pod names and pass it to the NameGenerator so it skips those (in addition to skipping previous run names), but maybe a unique ID could be appended to the run name/pod name for `kuberun` commands where no `-name` was given. Or there could be some behavior to optionally retry the driver pod creation with a new name if it fails. If there's agreement on which, if any, approaches to take, I'm happy to submit a PR.

**Comment by bentsherman** [comment]
Personally, I don't think it's worth it to add the extra logic to handle this edge case since it's so rare. Especially for kuberun, which is not intended for production environments anyway. In this situation, the best practice is generate the run names yourself, as you mentioned.

**Comment by WryYeti** [comment]
After doing some math, I think it's actually pretty likely

**Comment by WryYeti** [comment]
Sorry, I clicked the wrong button (clicked Github's Close with commend rather than the dropdown arrow next to it). 

Based on [this formula](https://en.wikipedia.org/wiki/Birthday_problem#A_simple_exponentiation), I think it's relatively likely that collisions will occur with the current set of ~100 names and ~214 names (so a hash space size of 21400). I verified the below numbers with some experiments with Python's random generator, but the end result is I’m pretty sure the probability of getting a collision in a set of:
- 50 runs, 5%
- 100 runs, 20%
- 300 runs, 87%

That certainly seems possible for others to encounter as well, especially for those operating in a shared K8s cluster, or one shared with a CI machine.
Given that, do you think it might be worth fixing/working around? As I said, I'd be happy to submit a PR if we can decide on a solution to pursue.

**Comment by bentsherman** [comment]
I believe it for your situation, considering the scale you're running at and your retention policy for workflow pods. It probably hasn't come up because users and orgs at this scale are typically using an external system to manage Nextflow workflows.

In any case, it's pretty straightforward to supply a UUID as the run name, even for individual users:
```bash
nextflow run -name $(uuidgen) # ...
```

Beyond that, I suppose we could add an option to make Nextflow generate a UUID instead the normal run name generator, for example:
```bash
# new flag
nextflow run -uuid

# or special value to generate new uuid
nextflow run -name uuid
```

**Comment by WryYeti** [comment]
Yeah, I get our situation is a bit unique, and it can definitely be worked around - I just figured I'd suggest a fix (or, maybe more accurately, feature) before implementing a workaround, in case it'll be useful for others as well. Sounds good, I'll try to add a flag like that and open a PR. Thank you.
