### ISSUE TITLE
nextflow kuberun exposes SCM credentials in config maps

### ISSUE THREAD

**Issue by sfehrmann** [nextflow-io/nextflow#2997]
## Bug report 

While `nextflow kuberun login` is a very handy command for testing, it unfortunately exposes scm credentials in clear test in config maps for everyone to see

### Expected behavior and actual behavior

The credential is not viewable by others on the k8s cluster.

### Steps to reproduce the problem

`nextflow kuberun login`
`kubectl describe configmaps` shows scm file

### Environment 

* Nextflow version: nextflow version 22.06.1-edge.5712
* Java version: openjdk version "11.0.15" 2022-04-19
* Operating system: Windows/WSL Ubuntu 20.04
* Bash version: GNU bash, version 5.0.17(1)-release

### Additional context

Azure kubernetes 1.22

**Comment by sfehrmann** [comment]
Mmh, after looking into this for a bit more time and with Ben's [kuberun.sh](https://github.com/seqeralabs/nf-k8s-best-practices/blob/master/kuberun.sh) script as a basis, I'm not sure how to work around this.

Options I thought of:
 - Have the secret as encrypted string in k8s, but then the encryption key needs to be known to the pod and so to all colleagues with access to the cluster
 - Pull the secret from a keyvault (again visible for all colleagues with access to the key vault)

My current workaround is to use a read only token for the git repo to provide to the pod, in mid term create a service principal that has minimal set of permissions on repo, container registry, and k8s cluster to run the workflow

**Comment by bentsherman** [comment]
I think there is a fundamental security limitation with config maps and secrets in K8s, basically there doesn't seem to be any way to secure them beyond securing the cluster itself. To my understanding that is why solutions like hashicorp vault and others exist.

If you find any other options we are happy to consider them.

**Comment by sfehrmann** [comment]
Let's close this until someone somehow comes up with a brilliant idea.
