### ISSUE TITLE
Allow setting polling rate for DirWatcher V2

### ISSUE THREAD

**Issue by matthdsm** [nextflow-io/nextflow#3008]
## New feature

v22.06.0 introduced a new wachter for the watchPath directive. The default polling interval is set to 1s. It would be nice to be able to edit this

## Usage scenario 
Depending on the use case, we only want to periodically check for new files, instead of every second

## Suggest implementation 
Add an argument to watchPath to allow setting the polling rate

xref https://nfcore.slack.com/archives/CE56GDKN0/p1656654336913999

**Comment by bentsherman** [comment]
Looks like you can control the polling interval with an environment variable:

https://github.com/nextflow-io/nextflow/blob/762e93fc333906057a8cda1b1852d6a4dcbc9d5c/modules/nextflow/src/main/groovy/nextflow/file/DirWatcherV2.groovy#L105

**Comment by matthdsm** [comment]
Allright! Missed this completely. Thanks for the tip. 

Is this something that can be added to the docs? Or did I miss that too 😅

**Comment by bentsherman** [comment]
I'm sure it will eventually... we need a bot to detect when Paolo quietly adds new environment variables 😆
