### ISSUE TITLE
Mention in the docs the function overloading is not supported

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3010]
In the DSL2 documentation it should be mention that function overloading or function default parameters is not supported. 

See here for context https://github.com/nextflow-io/nextflow/issues/2447#issuecomment-1171318985

**Comment by cjw85** [comment]
More generically the start of the Nextflow scripting section of the docs needs to be more exact:

![image](https://user-images.githubusercontent.com/3592009/177171491-0dc8fb74-3810-4141-99d3-27c67648cdc4.png)

The phrases:
> The Nextflow scripting language is an extension of the Groovy programming language.

and
> Nextflow can execute any piece of Groovy code or use any library for the JVM platform.

give the impression that Nextflow scripting is a superset of Groovy.

**Comment by pditommaso** [comment]
The plan is to explore the ability to support it #3011

**Comment by pditommaso** [comment]
Ok, we have added the support for default parameters. #3011
