### ISSUE TITLE
Explore the possibility to allow the support function overloading

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3011]
When definition a custom function in a Nextflow module the use of multiple signature for the same function name and default parameters is not allowed. See #3010 for details. 

The goal of this issue is to explore the possibility to support this ability so that Nextflow function can provide the same experience as for Groovy lang.

**Comment by pditommaso** [comment]
Part of the problem is that function (ie. methods) handlers are accessed simply by my name (and kept into a map using the method name as key), see here 

https://github.com/nextflow-io/nextflow/blob/dd7826a0e0137728584041af9f718359ca768046/modules/nextflow/src/main/groovy/nextflow/script/WorkflowBinding.groovy#L91-L91

The second and more complex part of the problem is how to pick the correct method having a *compatible* method signature. For example, let's consider two signatures such as 

```
def foo(Object x) { }

def foo(String x) { }
```

and invocation is done using `foo(1)` for which there isn't an direct type matching for the argument. It's not trivial to choose the correct one for more complete method signatures. 


A possible solution could be to *not* store the method reference in the [FunctionDef](https://github.com/nextflow-io/nextflow/blob/dd7826a0e0137728584041af9f718359ca768046/modules/nextflow/src/main/groovy/nextflow/script/FunctionDef.groovy#L36-L36) handle, and retrieve it using the actual parameter value as done here



https://github.com/nextflow-io/nextflow/blob/dd7826a0e0137728584041af9f718359ca768046/modules/nextflow/src/main/groovy/nextflow/extension/OpCall.groovy#L310-L315

**Comment by jorgeaguileraseqera** [comment]
In 3011-explore-the-possibility-to-allow-the-support-function-overloading branch, I've been playing with your idea and we can write this kind of script:

```
nextflow.enable.dsl = 2


def makeChannel(Map args=[:],  Integer arg1,  Integer arg2) {
    args = [arg3:0] + args
    return [arg1, arg2, args.arg3]
}

def makeChannel( String str ){
    "Hi $str"
}


def makeChannel( ){
    1.2
}

workflow w1 {
    main:
        list = makeChannel(1, 2)
        chn = Channel.from( list )
        chn.view()
}

workflow w2 {
    main:
        list = makeChannel( 'Jorge' )
        chn = Channel.from( list )
        chn.view()

}

workflow w3 {
   main:
      list = makeChannel()
      chn = Channel.from( list )
      chn.view()
}

workflow{
   main:
      w1()
      w2()
      w3()
}


```

**Comment by pditommaso** [comment]
Also when `makeChannel` is "include"ed from another module file?

**Comment by jorgeaguileraseqera** [comment]
> Also when `makeChannel` is "include"ed from another module file?

right now no because

```
protected void addModule0(ComponentDef component, String alias=null) {
        assert component

        final name = alias ?: component.name
        final existing = getComponent(name)
        if (existing) {
            def msg = "A ${existing.type} with name '$name' is already defined in the current context"
            throw new DuplicateModuleIncludeException(msg)
        }

        if( name != component.name ) {
            imports.put(name, component.cloneWithName(name))
        }
        else {
            imports.put(name, component)
        }
    }
```

but can investigate how to include it

**Comment by pditommaso** [comment]
remove it! that's was made to prevent the failty behavior

**Comment by jorgeaguileraseqera** [comment]
Ok, removing the restriction we can call methods from the imported module

also, we can include the same method from different modules but renaming it, i.e.:

util.nf
```
def makeChannel( String str ){
    "Hi $str"
}
def makeChannel( List list ){
    list.reverse()
}

```


another_util.nf
```
def makeChannel( double d ){
   d * 2
}
```

main.nf
```
include { makeChannel } from './modules/util.nf'
include { makeChannel as makeChannelExt } from './modules/another_util.nf'

```

**Comment by pditommaso** [comment]
This sounds nice!
