### ISSUE TITLE
Improvements to S3 storage interface

### ISSUE THREAD

**Issue by marcodelapierre** [nextflow-io/nextflow#3012]
## New feature

As part of testing the Nextflow setup for the BioCommons on our new supercomputer Setonix at Pawsey Centre in Perth, I did some testing on the integration of Nextflow with S3 storage.
The reason is, we now host an on-premises S3 Object Storage service (called "Acacia"), that is based on the CEPH software libraries.

I have identified some desired improvements based on that experience:

- [x] User Docs: document `s3PathStyleAccess` (it is legacy, but still adopted by on-prem platforms)
- [ ] Feature: add a Nextflow config to handle AWS Profiles, e.g. `aws.profile` [edited]
- [ ] User Docs: have a small example for on-prem S3 in the User Docs

## Usage scenario 

As I said above, the main scenario I have in mind is that of an on-premises S3 Object Storage service, but there might be more.

## Suggest implementation 

* For the `aws.profile` feature, the idea is to use the AWS CLI flag `--profile`.
* For user docs on an S3 on-premises, it would be key to describe the use of  `s3PathStyleAccess`, `endpoint` and the proposed `profile` feature (or, if rejected, of the `AWS_PROFILE` shell variable). For reference this is a toy repo I have made myself: https://github.com/marcodelapierre/toy-acacia-nf

**Comment by pditommaso** [comment]
Thanks Marco, this are good suggestion. My understanding is that `AWS_PROFILE` env var is already working. Is that right?

**Comment by marcodelapierre** [comment]
Correct, `AWS_PROFILE` works; however, I think a `profile` config option for Nextflow would represent an improvement (and it would be the one to be documented in the user docs, if implemented)

**Comment by pditommaso** [comment]
I agree, I'd only suggest to keep at top aws scope ie. `aws.profile` instead of `aws.client.profile` as it's done for keys and region

**Comment by marcodelapierre** [comment]
@pditommaso as we were talking of on-prem S3-like object storage, I believe this feature request may be of interest

**Comment by pditommaso** [comment]
You are right! let's see if we manage to unlock this

**Comment by marcodelapierre** [comment]
@pditommaso today I had a look at AWScli functionalities, and at the Nextflow code for this one.

So, the proposed `aws.profile` needs to read two files, `~/.aws/credentials` and `~/.aws/config`, with this contents:
1. `credentials`
    ```
    [default]
    aws_access_key_id=AKIAIOSFODNN7EXAMPLE
    aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    
    [profile1]
    aws_access_key_id=gnfrituhpehnrst
    aws_secret_access_key=jpgieruhptlshktsjhgrtpjn;ojsgrt;n
    
    ...
    ```
2. `config`
    ```
    [default]
    region=us-west-2
    output=json
    
    [profile profile1]
    region=https://acacia.pawsey.org.au
    
    ...
    output=json
    ```
Entries for a profile in the `config` can be missing.
Reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

In Nextflow, the key source file seems to me to be : plugins/nf-amazon/src/main/nextflow/cloud/aws/AmazonClientFactory.groovy

This is were I think two things are needed:
1. a method that, if `aws.profile` exists, checks for the existence of those two files, errors if they don't exist or if the requested profile does not exist, and stores their contents;
2. edit to the initialiser `AmazonClientFactory(Map config)`, so that it uses the info above.

Could you help me with one, in providing a template/example on how to write it in Groovy? I will then draft a PR with that and the rest.

What do you think?

Thanks, Marco

**Comment by pditommaso** [comment]
Hi Marco, sorry if I could look into before. The logic is here 

https://github.com/nextflow-io/nextflow/blob/ae5026685640404cf15c6d7d2263f3dd0ae718e3/modules/nf-commons/src/main/nextflow/Global.groovy#L144-L153

I think it should be enough to check `session.navigate('aws.profile')` before checking the env vars

**Comment by pditommaso** [comment]
Ok, done! dff15ccc

**Comment by marcodelapierre** [comment]
You have beaten by my half a day Paolo!
Had started to look into it yesterday night, but was too tired to continue!

Yet, I have some comments for you (happy to action further edits myself, but first let's see if they make sense lol!)

1. I see a possibly logic inconsistency between `Global.groovy -> getAwsProfile0` (where `aws.profile` has higher priority than `AWS_PROFILE`), and `Global.groovy -> getAwsCredentials0` (where `AWS_ACCESS_KEY`/`AWS_SECRET_KEY` have higher priority than `profile`)

2. I think we need to add the `profile` case in `Global.groovy -> getAwsRegion` as well, because the profile can indeed contain info on the region. At the moment this is used in `FileHelper.groovy` and `AmazonClientFactory.groovy`

3. `plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsOptions.groovy -> AwsOptions(Session session) -> line 117`
    ```
    region = session.config.navigate('aws.region') as String
    ```
    This might need some thinking, too, but I am not sure at this stage. What do you think?

4. `plugins/nf-amazon/src/main/com/upplication/s3fs/S3FileSystemProvider.java -> createFileSystem0 -> lines 924-927`. This uses `NXF_AWS_REGION`, so it is probably unrelated, but I am not sure at this stage. What do you think?


At this stage, I think points 1. and 2. need an action. Once you share your feedback I will proceed, if needed.

Thanks!
Marco

**Comment by pditommaso** [comment]
> I see a possibly logic inconsistency between Global.groovy -> getAwsProfile0 (where aws.profile has higher priority than AWS_PROFILE), and Global.groovy -> getAwsCredentials0 (where AWS_ACCESS_KEY/AWS_SECRET_KEY have higher priority than profile)

Not really, a common pattern in nextflow is that config settings overrides environment settings. The same is for the AWS creds, if you notice before it checks the config, then fallback into the env 

https://github.com/nextflow-io/nextflow/blob/89e93c02847331fc5f70f042352b256372f699bf/modules/nf-commons/src/main/nextflow/Global.groovy#L101-L110

**Comment by marcodelapierre** [comment]
oh sure, config keys come first, but this is the full sequence:
1- lines 101-110: config for key pair
2- lines 114-122: env settings for key pair
3- lines 124-138: config for profile (via getAwsProfile0), which then sets key pairs

My point is that 3 should come before 2.
The rationale is that 3.  is a config setting (for profile) that defines the key pair; hence, as you say, it should override 2., which uses env variables.

**Comment by marcodelapierre** [comment]
What do you think of my point 2. above? Quoting again:

2. I think we need to add the `profile` case in `Global.groovy -> getAwsRegion` as well, because the profile can indeed contain info on the region. At the moment this is used in `FileHelper.groovy` and `AmazonClientFactory.groovy`

**Comment by pditommaso** [comment]
You are right! This 👉 d8947707

**Comment by marcodelapierre** [comment]
Regarding both key pairs and region, can you just clarify for me why you prefer the priority
1. config.options (either keys or region)
2. AWS env vars
3. config.profile

where I would instead have put config.profile as second? 
just trying to understand the logic, thank you!

**Comment by pditommaso** [comment]
Commonly NF follows this pattern: 1) CLI overrides nextflow config 2) nextflow config overrides env variables. The logic is that as a user you can provide some specific settings in the config having some global setting in the environment. 

Not sure what you mean by `config.profile` at point 3

**Comment by marcodelapierre** [comment]
So, let me comment on `Global.groovy` in the commit above, https://github.com/nextflow-io/nextflow/commit/d89477072b19b9585e0811af8aa894cc1027f764.

Let's start with lines 101-139, i.e. those relating to access&secret keys:
https://github.com/nextflow-io/nextflow/blob/d89477072b19b9585e0811af8aa894cc1027f764/modules/nf-commons/src/main/nextflow/Global.groovy#L101-L139

1. from line 101: getting secret&access key values from  `config.accessKey` and `config.accessKey`
2. from line 114: getting keys from AWS env variables, `AWS_ACCESS_KEY ` and `AWS_SECRET_KEY `
3. from line 123: getting keys from the profile, that is
    a. either `config.profile`,
    b. or `AWS_PROFILE`

What I mean is that `config.profile` gets used AFTER the AWS variables for the keys, so it does NOT override them. However, I now realise it is a bit tricky as point 3. also has sub-points a. and b. , which I had not noticed before.

This is what I was thinking as the ideal priority, to comply with the pattern you mentioned in your last message:

1. getting secret&access key values from  `config.accessKey` and `config.accessKey`
3.a getting keys from `config.profile`
2. from `AWS_ACCESS_KEY ` and `AWS_SECRET_KEY `
3.b. from `AWS_PROFILE`

Do you see my point?

**Comment by pditommaso** [comment]
I think it's still consistent with the behavior of the AWS [credentials chains](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) that first checks the AWS keys via env variables and then the config file. 

Nextflow follows the same sequence having the nextflow.config as first check. Let me know if I missed something in you comment

**Comment by pditommaso** [comment]
Umm, point 3 is a good catch. It could a possible inconsistency. But in any case it deserves a separate issue. Can you please open it? 

Point 4. I do not even know why that `NXF_AWS_REGION` is there. The S3 client should be region independent.


Well spotted about the config. I've added like this 66f4669f

**Comment by marcodelapierre** [comment]
Done! opened #3478

**Comment by marcodelapierre** [comment]
OK! Successfully tested the new functionality using my toy pipeline for Pawsey on-prem S3:

https://github.com/marcodelapierre/toy-acacia-nf

For me this is good to go for merging!

**Comment by pditommaso** [comment]
It's already on master this!

<img src="https://media1.giphy.com/media/26vUDLOP9YIc8oxGg/giphy.gif"/>

**Comment by marcodelapierre** [comment]
ahah true!
