### ISSUE TITLE
sge executor runs on local in nextflow 22.04.04

### ISSUE THREAD

**Issue by campanam** [nextflow-io/nextflow#3013]
### Expected behavior and actual behavior
process.executor is set as 'sge' in profile directive of config file. On versions 20.10.0, 20.04.04 and 21.10.6, the processes are submitted as jobs to the cluster as expected. On 22.04.04, the process runs on local instead. It also ignores the storeDir files.

### Steps to reproduce the problem

test.config:
```
profiles {
	test {
              	process.executor = 'sge'
                process.storeDir = 'chkpnt'
                process {
                        withName: test {
                        queue = 'sThC.q'
                        clusterOptions = '-l mres=1M,h_data=1M,h_vmem=1M -S /bin/bash'
                        }
                }
        }
}
```

test.nf:
```
process test {
	publishDir "$baseDir/test"

        output:
        path 'file.txt'

        """
	echo 'test' > file.txt
        """

}
```

Running this command should run on SGE:
nextflow test.nf -c test.config -profile test -dsl1

### Program output 
Instead it runs locally and ignores the storeDir:
```
N E X T F L O W  ~  version 22.04.4
Launching `test.nf` [pedantic_celsius] DSL1 - revision: 43c70768e9
executor >  local (1)
[8e/6b792b] process > test [100%] 1 of 1 ✔
```

### Environment 

* Nextflow version: 22.04.04
* Java version: 1.8 and 1.17
* Operating system: Linux (UGE cluster)
* Bash version: (use the command `$SHELL --version`) 4.2.46(2)-release

### Additional context
This is running on UGE cluster with the SGE directive. The memory allocations are thus being worked around using the clusterOptions line.

**Comment by bentsherman** [comment]
I think the configuration rules have evolved since 21.10 such that your config doesn't work anymore. Basically, the way you specified process settings with both object syntax and closure syntax doesn't work anymore. You have to use one or the other, for example:
```
profiles {
	test {
                process {
              	        executor = 'sge'
                        storeDir = 'chkpnt'

                        withName: test {
                        queue = 'sThC.q'
                        clusterOptions = '-l mres=1M,h_data=1M,h_vmem=1M -S /bin/bash'
                        }
                }
        }
}
```

**Comment by bentsherman** [comment]
Note to self. We have a warning about this issue documented [here](https://www.nextflow.io/docs/latest/config.html#config-profiles) but it is specific to profiles. We should probably replace it with a more general warning [here](https://www.nextflow.io/docs/latest/config.html#config-scopes).
