### ISSUE TITLE
Missing documentation information about poolSize / -pool-size

### ISSUE THREAD

**Issue by mribeirodantas** [nextflow-io/nextflow#3014]
### Expected behavior and actual behavior

I suppose there should have documentation on the `-pool-size` command line parameter and also the `config.poolSize`, that controls the number of threads in the execution pool.

### Steps to reproduce the problem

Check the [documentation](https://www.nextflow.io/docs/latest/index.html) and `nextflow help run`.

### Environment 

* Nextflow version: version 22.04.3 build 5703
* Java version: openjdk version "16.0.1" 2021-04-20
* Operating system: macOS Monterey 12.4
* Bash version: GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)

### Additional context

It's not clear to me how to better describe this on the documentation, so instead of opening a Pull Request I decided to open an issue to make sure this will not be forgotten, as asked by @ewels 😬

**Comment by ewels** [comment]
@pditommaso is this one of those experimental / internal-only features where you'll say that it should remain undocumented and officially unsupported..? Or can we add a short mention into the docs and/or the CLI help?

@bentsherman - you seemed to understand its workings better than most, so maybe you could draft something if Paolo gives the go-ahead? 😀

**Comment by mribeirodantas** [comment]
What's the current decision on that? We should document it or not? 😅

**Comment by bentsherman** [comment]
For now I think we should just un-hide the `-pool-size` option and document it. I wouldn't worry about the `poolSize` config option. But from the slack thread I think we confirmed that it is the only way to force Nextflow to use more threads than CPUs, so we need to make it clear that Nextflow supports this use case.

**Comment by bentsherman** [comment]
Here is the original Slack thread: https://nextflow.slack.com/archives/C02T98A23U7/p1656081406989489

@mribeirodantas If you would like to draft a PR when you have some time, I will review it and make sure it covers everything we wanted.

**Comment by bentsherman** [comment]
Not an urgent thing, just wanted to move some docs issues over to you since you have gained more experience working on the docs.

**Comment by mribeirodantas** [comment]
Great! Thanks, Ben. I added it to my to-do list.

**Comment by ewels** [comment]
@mribeirodantas you ok to come back to this and finish up please?

**Comment by mribeirodantas** [comment]
I can't make it work as we discussed in that thread, @bentsherman (as couldn't either the author at the end of it). I can cap below the number of cores with `-ps` but I can't make it go past the number of available cores. I tried with `-ps` and `-pool-size` in the CLI, and `poolSize` in the configuration file. Both tested on my machine (macOS) and on Gitpod (Linux).

**Comment by mribeirodantas** [comment]
Thanks, @bentsherman !
