### ISSUE TITLE
Regression in K8S pod scheduling failures

### ISSUE THREAD

**Issue by tdudgeon** [nextflow-io/nextflow#3022]
## Bug report 

This relates to how NF handles the situation when there is insufficient capacity in the cluster to to schedule all that pods at once.
In earlier versions this causes the workflow to fail, but by v22.04.4 this seems to have been resolved (pods fail to schedule, but NF copes with this and the workflow completes eventually. But with v22.06.1-edge the behaviour had regressed. The workflow still completes, but some pods enter `Failed` state (and remain in K8s) and that number of failed pods seems to be added to the number of process that have been executed. The workflow still completes successfully, but the information the user receives give the impression something is not right.

### Expected behavior and actual behavior

No pods should be seen in `Error` state and the number of NF processes should be correct.

For example, 1000 processes are supposed to be executed and let's assume 20 fail to get scheduled due to capacity limits

**Correct behaviour**
No failed pods should be seen, the number of processes executed should be 1000

**Incorrect behaviour**
20 pods remain in failed state and we are informed that 1020 processes have been executed

### Steps to reproduce the problem

See #3021 for details

### Program output 

n/a

### Environment 

* Nextflow version: v22.04.4
* Java version: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.15+10-post-Debian-1deb10u1
* Operating system: Linux
* Bash version: GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)

### Additional context

See here for the original discussion on slack: https://nextflow.slack.com/archives/C02T98A23U7/p1655988093222169

**Comment by tdudgeon** [comment]
Please keep this issue alive

**Comment by bentsherman** [comment]
@tdudgeon since this issue appears to be downstream of the quota error in #3021, is this issue resolved now?
