### ISSUE TITLE
Errors during job submission are not logged anywhere

### ISSUE THREAD

**Issue by tgbrooks** [nextflow-io/nextflow#3024]
## Bug report 

Errors that happen during job submission of a cluster job do not appear to be logged anywhere and so they are quite difficult to debug. Moreover, some job submission arguments are not logged in a visible way, making it harder to reproduce.

For example, the [troubleshooting instructions](https://nf-co.re/usage/troubleshooting#manual-debugging-on-clusters-using-schedulers) tell one to rerun the submission command in the work directory. However, the submission command may include other parameters that are not present in the error output shown. In my case at least, for LSF cluster, the arguments to `bsub` (the job-submission command) are documented in the .command.run file in comments that the user cannot be expected to find except by accident. Without including those arguments the error may not happen.

It would be preferable if the error from the failed job submission was reported to the user somehow.

**Comment by tgbrooks** [comment]
Thanks for the reply. I tried `bsub .command.run` on the rnaseq pipeline but it fails since `.command.run` is not executable. `bsub bash .command.run` is what I was using before due to this but then `bsub` can't pick up the arguments. The command listed in the error message is just `bsub` so I think the actual submitted job is passed through standard input to `bsub`. It looks like the right way to simulate this is `bsub < .command.run` which does replicate the actual error. It would be nice to include this command (`bsub < .command.run`) either in the log output (that currently just says `bsub`) or in the troubleshooting instructions I linked to. In any event the output from the `bsub` failure would be really great to include in that log too.

That the troubleshooting guide I linked to refers to SLURM clusters, I suspect that this problem isn't just LSF-specific.

**Comment by bentsherman** [comment]
From a bit of digging, it looks like LSF uses the pipe syntax but some LSF clusters also support the argument syntax.

Nextflow always uses the pipe syntax when submitting LSF jobs: https://github.com/nextflow-io/nextflow/blob/b099d430aa06b350ff63b6f3ae291dd72f49c779/modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy#L128

The error message for failed job submissions is defined here: https://github.com/nextflow-io/nextflow/blob/b099d430aa06b350ff63b6f3ae291dd72f49c779/modules/nextflow/src/main/groovy/nextflow/executor/GridTaskHandler.groovy#L188

It looks like it should print the correct submit command and error message, both to Nextflow's standard error message and the Nextflow log. Do you see anything in your log?

Technically this behavior applies to all grid executors, but I don't have a label for that 😄

**Comment by tgbrooks** [comment]
Similarly to the linked troubleshooting guide, when I run: `nextflow run nf-core/rnaseq --outdir outdir -profile test,singularity` with `process.executor = 'lsf'` I get the following error report:

```
-[nf-core/rnaseq] Pipeline completed with errors-
Error executing process > 'NFCORE_RNASEQ:RNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet_test.csv)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  bsub

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /my/folder/work/3d/f3c8be7c181b1620903f8da4c83421

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

In contrast, when I run: `bsub < .command.run` from the work directory I get:
```
Queue only accepts interactive jobs. Job not submitted.
```
This isn't the most helpful error (the real problem is requesting too much memory) but at least it's something. Funny that the line you link to isn't working, it certainly looks like it's trying to report the error.

**Comment by bentsherman** [comment]
It looks like the command builder isn't including the `< .command.run` part, we'll have to see if we can correct that.

**Comment by bentsherman** [comment]
That is the latest commit, so maybe you should try the latest edge release and see if it works.
