### ISSUE TITLE
Ignore conda directive when running with stubs

### ISSUE THREAD

**Issue by nh13** [nextflow-io/nextflow#3029]
I would like the option to ignore any `conda` directive with `nextflow run -stub .`.  I want rapid feedback on the plumbing and data flow of my pipelines, and don't care that the `conda` environments exist or are activated.  Is there a way to ignore the `conda` directive in process definitions when I run `nextflow run -stub .`?

**Comment by nh13** [comment]
NB: I see `-without-docker` and `-without-podman`, so I am hoping for a `-without-conda`.

**Comment by nh13** [comment]
I wouldn't be opposed to the best practice solution to be (1) moving the `conda` directive out of each process definition, then (2) specifying a `conda` profile where the per-process conda environment is specied, and finally (3) specifying `-profile conda` to utilize conda environments.  To ignore conda environments, just have a dummy "test" profile that's empty.  Is this a valid work around?

**Comment by pditommaso** [comment]
Yeah, in the past we discussed the convenience to add `-with/without-conda` but was decided no. May be we have to reconsider this.

**Comment by bentsherman** [comment]
> I wouldn't be opposed to the best practice solution to be (1) moving the `conda` directive out of each process definition, then (2) specifying a `conda` profile where the per-process conda environment is specied, and finally (3) specifying `-profile conda` to utilize conda environments. To ignore conda environments, just have a dummy "test" profile that's empty. Is this a valid work around?

This approach seems to be standard among the nf-core pipelines, for example in rnaseq:

https://github.com/nf-core/rnaseq/blob/89bf536ce4faa98b4d50a8ec0a0343780bc62e0a/nextflow.config#L140-L147

**Comment by pditommaso** [comment]
I've added a PR implementing this. See #3073. tagging @mribeirodantas @christopher-hakkaart for info. 

Now @drpatelh and @ewels will say that I'm a bad guy because they asked it ages ago #749.

**Comment by ewels** [comment]
![longtime-titanic](https://user-images.githubusercontent.com/465550/181466468-24c0faeb-bbc5-44fc-9f2a-384f44970f79.gif)

**Comment by pditommaso** [comment]
<img src="https://media0.giphy.com/media/Q7ozWVYCR0nyW2rvPW/giphy.gif"/>

**Comment by pditommaso** [comment]
Solved by https://github.com/nextflow-io/nextflow/pull/3073.
