### ISSUE TITLE
Allow overwriting of additional LSF options in nextflow.config

### ISSUE THREAD

**Issue by tgbrooks** [nextflow-io/nextflow#3030]
Similarly to #2862, there are additional properties that are read from the `lsf.conf` file that cannot be overwritten by `nextflow.config`. In my case, that caused a problem because the `lsf.conf` that is present on nodes does not match the one that is present on the head node (I'm not certain if this is a problem with my cluster config and have asked my admin). Being able to set these settings in `nextflow.config` would provide an easy fix to my problem.

The relevant settings in the `lsf.config` file are LSF_UNIT_FOR_LIMITS and LSB_JOB_MEMLIMIT, which were both unset in my `lsf.config` despite needing to be set to `MB` and `Y` respectively for my use. That caused job submission to fail due to requesting incorrect amounts of memory.

**Comment by bentsherman** [comment]
Hi @tgbrooks , [this PR](https://github.com/nextflow-io/nextflow/pull/3009/files) shows how we set up LSF options to be overridden by Nextflow. You're welcome to submit a PR that adds more options following the same pattern.

**Comment by tgbrooks** [comment]
Hmm I tried the obvious thing there and it fails. Just adding the two "NEW" lines below:
```
    @Override
    void register() {
        super.register()
        final conf = parseLsfConfig()

        // lsf mem unit
        // https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.3/lsf_config_ref/lsf.conf.lsf_unit_for_limits.5.html
        if( conf.get('LSF_UNIT_FOR_LIMITS') ) {
            memUnit = usageUnit = conf.get('LSF_UNIT_FOR_LIMITS')
            log.debug "[LSF] Detected lsf.conf LSF_UNIT_FOR_LIMITS=$memUnit"
        }

        memUnit = session.getExecConfigProp(name, 'memUnit', memUnit) // NEW
        usageUnit = session.getExecConfigProp(name, 'usageUnit', usageUnit) // NEW

        // per job mem limit
        // https://www.ibm.com/support/knowledgecenter/SSETD4_9.1.3/lsf_config_ref/lsf.conf.lsb_job_memlimit.5.dita
        if( conf.get('LSB_JOB_MEMLIMIT') ) {
            final str = conf.get('LSB_JOB_MEMLIMIT').toUpperCase()
            perJobMemLimit = str == 'Y'
            log.debug "[LSF] Detected lsf.conf LSB_JOB_MEMLIMIT=$str ($perJobMemLimit)"
        }

        perJobMemLimit = session.getExecConfigProp(name, 'perJobMemLimit', perJobMemLimit)

        // per task reserve https://github.com/nextflow-io/nextflow/issues/1071#issuecomment-481412239
        if( conf.get('RESOURCE_RESERVE_PER_TASK') ) {
            final str = conf.get('RESOURCE_RESERVE_PER_TASK').toUpperCase()
            perTaskReserve = str == 'Y'
            log.debug "[LSF] Detected lsf.conf RESOURCE_RESERVE_PER_TASK=$str ($perTaskReserve)"
        }

        perTaskReserve = session.getExecConfigProp(name, 'perTaskReserve', perTaskReserve)
    }
```
to modules/nextflow/src/main/groovy/nextflow/executor/LsfExecutor.groovy register() function seems like it should work, by analogy to the other config options. Instead, it fails the existing `should apply lsf mem unit` test since `memUnit` is null. I'm afraid this is beyond my knowledge of groovy and nextflow to handle and I have to throw in the towel! Quite unfortunate since this feature would be very helpful for us.
