### ISSUE TITLE
PBS Torque - Node architecture

### ISSUE THREAD

**Issue by Mxrcon** [nextflow-io/nextflow#3034]
## New feature

Hello there :wave:, I'm facing some problems when using nextflow on a PBS/torque node with hybrid architecture (2 nodes on ppc7 + 1 x86 node), and this produces some problems when submitting a job as some tools aren't deployed on ppc7 architecture. 

## Usage scenario 

This proposal would address any other PBS/Torque user which has hybrid cluster nodes with different architectures like x86 and x64

## Suggest implementation 

When nextflow creates a PBS job this is the current header which specifies the required infrastructure:

```
#PBS -q ${queue}
#PBS -l nodes=${node amount}:ppn=${cpus}
#PBS -l mem=${memmory}

```
what I would like to suggest is something like this:
```
#PBS -q ${queue}
#PBS -l nodes=${node amount}:${node architecture}:ppn=${cpus}
#PBS -l mem=${memory}
```
which could be implemented as a new directive `architecture`

I've been using this configuration to override the standard nextflow config: 
```
clusterOptions = "-l nodes=1:x86:ppn=${params.custom_cpus}"
```
Without specifying any cpu usage on each process.

Thank you, for your attention and time. :smile:

**Comment by bentsherman** [comment]
I think this use case could be handled by this PR #3015 , basically making it easier to use `clusterOptions` alongside `cpus` and `memory`. You could do something like this:
```
process {
  clusterOptions = { "-l nodes=1:x86:ppn=${task.cpus}" }
  cpus = 2
}
```

Currently this PR only changes the pbspro executor, but I could also update the pbs executor. Do you think that would work for you?

Side question, do you have to specify the node arch right after `nodes` ?

**Comment by pditommaso** [comment]
This is interesting, besides the workaround suggest by @bentsherman I think we should take into consideration adding an `arch` directive to accommodate those kind of workloads better

**Comment by Mxrcon** [comment]
happy to see that someone is already working on this topic as @bentsherman mentioned, overwriting the cpus would be nice but as @pditommaso already mentioned, this new directive would be 🤩amazing🤩 and useful, I tend to believe that Cluster Options work better as workarounds, a new directive would make easier to write configs and organize them.

**Comment by bentsherman** [comment]
Yeah, I'm generally more hesitant to add new directives for this kind of thing, but it's worth considering. The key question is whether every grid executor has the same understand of "node architecture", as it does for other concepts like cpus, memory, etc.

More broadly, I suspect that my workaround will be useful either way, because even if we add a directive for this, where does it end? Every grid executor has myriad custom options that could be made into directives, but likely won't because of the differences in meaning, so people will always need `clusterOptions` for something, ideally it should be easier to use with the standard directives. Just thinking aloud.

**Comment by bentsherman** [comment]
Hi @Mxrcon actually you might be able to try my workaround right now, because in PBS you don't have to specify all the resources in one line. Basically your cluster options will overwrite the default cpu setting that doesn't have the node arch. Let me know if it works for you.

**Comment by Mxrcon** [comment]
@bentsherman, I've checked your PR and Actually if we only produce one -l line, it'll fix my issue certainly. Also the possibility to access params would completly solve my problem as I'd use this cluster option: `clusterOptions = { "-l nodes=1:${params.architecture}:ppn=${task.cpus}" }` and keep the `memory` directive.

**Comment by bentsherman** [comment]
Well my understanding is that PBS Torque doesn't have the restriction of only one `-l` line, so you might be able to do this already. I would try the `clusterOptions` you proposed and see if it works. Currently my PR only affects PBS Pro, but if you find that PBS Torque has the same issue then we can update the PR.

**Comment by Mxrcon** [comment]
hey @bentsherman, I'm giving attention to this issue again with tests on my production environment (PBS- torche).

Unfortunatedly using `clusterOptions = { "-l nodes=1:${params.architecture}:ppn=${task.cpus}" }` won't work and send jobs to a unwanted node :(


this is the .command.run header which will be sent to PBS:
```
#PBS -l nodes=1:ppn=4
#PBS -l nodes=1:x86:ppn=4
```

Unfortunately, It appears that only the first line is used and the x86 specification for node architecture is ignored.

I could tweak this by using `ext.cpus`

perhaps we could surpass this issue if we didn't generate the first `#PBS -l nodes=1:ppn=4` line

Thank you for your availability to discuss this issue.

**Comment by bentsherman** [comment]
Thanks for testing @Mxrcon , I will update my PR to also apply to PBS/Torque now that we know it behaves the same way.

**Comment by abhi18av** [comment]
Considering that we'd be meeting the group again at the Evandro Chagas, it'd be great if we could review/merge https://github.com/nextflow-io/nextflow/pull/3015.

Happy to provide any other context needed 🤞
