### ISSUE TITLE
Add support for Chinese cloud providers

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#3045]
There is increased interest (#2149, #2795, #3043) for running Nextflow on cloud providers based in China:

- [Alibaba Cloud](https://www.alibabacloud.com/)
- [Huawei Cloud](https://www.huaweicloud.com/intl/en-us/)
- [Tencent Cloud](https://intl.cloud.tencent.com/?lang=en&pg=)

While these platforms can be used now through Kubernetes, it would be more convenient for most users to be able to use the cloud provider directly.

Executors for these clouds can likely be adapted from the existing ones (e.g. AWS, Azure). It would be a good way to expand Nextflow's reach into China. I'm also not sure whether (or to what extent) users in China can access American cloud providers.

**Comment by pditommaso** [comment]
The community should step in and take care of that.

**Comment by jing-memverge** [comment]
This is worth a discussion with our team.  MemVerge has genomics customers in China and we can already run Nextflow with Memory Machine Cloud.  How can we better understand the requirements and the end users who are asking for this?

**Comment by pditommaso** [comment]
This would be very useful. We made some exploration in the past and Alibaba model was very similar to Azue Batch. However, we decided we could not support directly all clouds provided. 

If you are keen to take ownership of this contribution, we would be very happy to advise you on this implementation.

Regarding the requirement I guess are the same for average nextflow users. Deploy data pipelines in a scalable manner.

**Comment by pditommaso** [comment]
Indeed, I was thinking the same. However, it remains the non-trivial problem of accessing the object storage provided by cloud provider. 

Does Alibaba cloud has a S3-like (I mean API-compatible) storage layer?

**Comment by denny-zhao** [comment]
Alibaba' object storage is called OSS (Object Storage Service) . It supports the similar feature set that AWS S3 has. 
There are several differences that might introduce the major extra effort (potentially):
1. For security concerns, OSS supports virtual-host-style requests only, while S3 support both path-style and virtual-host style. 
2. ACL definitions are slightly different. 
Besides, there are slight differences in parameters for individual API. That could be some trivial effort to convert from S3 to OSS API, but not much.

**Comment by pditommaso** [comment]
I believe so. I was wondering if by any chance it's compatible with the S3 API to avoid the need to implement a new client on nextflow side for Alibaba storage

**Comment by bentsherman** [comment]
Closing, see https://github.com/Tencent/nf-tencentcloud
