### ISSUE TITLE
Add support for Google Batch boot disk size

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3049]
The Google Batch API allows the control of the boot disk size via the [following setting](https://github.com/googleapis/googleapis/blob/master/google/cloud/batch/v1/task.proto#L42). 

The Goal of this issue is to add support for it in Nextflow via the configuration setting 

```
google.lifeSciences.bootDiskSize = <size using MemUnit type>
```

**Comment by hnawar** [comment]
Quick question: While in Life Sciences API the default behaviour was the API copied the input files to the Data disk, this is not necessary the case with Batch. At the moment the TaskHandler copies the data to the boot disk and simply processes the data on it.
If Disk directive in the process resizes the boot disk then the bootDiskSize is no longer needed, unless the future plans it to still use two or more separate disks (Boot disk + Data siks(s)) then both would be needed

**Comment by pditommaso** [comment]
The use of gcs mount made by the job facilitates things, but still, the task works in the node scratch storage and copies the result back in the bucket. Therefore the support for `disk` can be useful. 

The boot disk instead can be useful when downloading a fat docker image, that the docker driver stores in the boot volume
