### ISSUE TITLE
installer script fails at mktemp on busybox

### ISSUE THREAD

**Issue by odoublewen** [nextflow-io/nextflow#305]
Bioconda packaging of nextflow is [having a problem](https://github.com/bioconda/bioconda-recipes/pull/4158) during automated testing.   

`mktemp -p` is not a valid option on busybox (which we're using for CI testing) and possibly other platforms.

Can you make the `make_temp()` function more robust to different platforms?

```
function make_temp() {
    local base=${NXF_TEMP:=$PWD}
    if [ "$(uname)" = 'Darwin' ]; then mktemp ${base}/nxf-tmp.XXXXX || exit $?
    else mktemp -t nxf-tmp.XXXXX -p ${base} || exit $?
    fi
}
```

**Comment by pditommaso** [comment]
That's a weird version of `mktemp`. Any chance to upgrade it to GNU mktemp? Also NF requires BASH and busybox does not provide it out of the box.

**Comment by odoublewen** [comment]
@pditommaso Thanks for looking into this.  Yes, the busybox is probably a bit too lean to build nextflow.

BTW, I updated nextflow requirement notes, to reflect Bash req
https://github.com/nextflow-io/nextflow/pull/307

Thanks again

**Comment by pditommaso** [comment]
I this has been solved. Feel free to comment if needed
