### ISSUE TITLE
export bashrc and bash_profile preload to Nextflow env

### ISSUE THREAD

**Issue by fgualdr** [nextflow-io/nextflow#3060]
Hi,

I'm quite new to Nextflow language and configurations.

In the institute where I work we use petaling to compress fastq and to make any pipe able to see the fastqr files (the petaling extension) like a normal fastq we normally export the LD_PRELOAD "/petalink.so" and the PETASUITE_REFPATH "petalink_1.3.15/species".

Currently I am assembling pipelines in Nextflow in DSL2 using singularity containers and PBS-pro, nevertheless I cannot figure out were I should include these exports to make the whole Nextflow pipeline aware and the petalink.so loaded in each environment.

Thanks for the help

Francesco

**Comment by bentsherman** [comment]
I think you could put them in the `env` config scope. That would make them available to each task environment. Or you can put them in your `.bashrc` and they will be included automatically.

**Comment by fgualdr** [comment]
Thank you very much for your quick reply.
I think we found a workaround by adding the envWhitelist for the singularity i.e:
singularity.envWhitelist = 'LD_PRELOAD'
in the config file and it seems to catch the LD_PRELOAD correctly.
Thanks again.

**Comment by bentsherman** [comment]
Right, I missed that you were using singularity. That's exactly what that setting is for. Happy to help.
