### ISSUE TITLE
Unable to reproduce the GCP Batch hello example

### ISSUE THREAD

**Issue by andersgs** [nextflow-io/nextflow#3067]
### Expected behavior and actual behavior

I was trying to reproduce the GCP Batch hello example provided in the blog post announcing Batch support in Nextflow. I get an `invalid JSON payload` error.

### Steps to reproduce the problem

I used the following `nextflow.config` settings (with values changed to be appropriate for my account:

```
process.executor = 'google-batch'
google {
    project = '<PROJECT_ID>'
    locations = 'us-central1'
    batch.spot = true
    batch.debug = true
}
```

I have a Nextflow service principal to run workflows on GCP Life Sciences. I added the IAM role `roles/batch.jobsAdmin` to it. 

I then updated to Edge version of nextflow:

```
export NXF_EDGE=1
nextflow -self-update
```

I then ran the following:

```
nextflow run  https://github.com/nextflow-io/hello -w gs://nxf/hello
```

### Program output 

```
nextflow run  https://github.com/nextflow-io/hello -w gs://nxf/hello
N E X T F L O W  ~  version 22.07.1-edge
Launching `https://github.com/nextflow-io/hello` [awesome_boyd] DSL2 - revision: 4eab81bd42 [master]
[-        ] process > sayHello [  0%] 0 of 4
Error executing process > 'sayHello (2)'

Caused by:
  Request POST https://batch.googleapis.com/v1/projects/onehealth-354818/locations/us-central1/jobs?job_id=nf-9975fac6-1658705278929 returned an error code=400

  {
      "error": {
          "code": 400,
          "message": "Invalid JSON payload received. Unknown name \"instance\" at 'job.allocation_policy': Cannot find field.",
          "status": "INVALID_ARGUMENT",
          "details": [
              {
                  "@type": "type.googleapis.com/google.rpc.BadRequest",
                  "fieldViolations": [
                      {
[99/75fac6] process > sayHello (2) [ 25%] 1 of 4, failed: 1
Error executing process > 'sayHello (2)'

Caused by:
  Request POST https://batch.googleapis.com/v1/projects/onehealth-354818/locations/us-central1/jobs?job_id=nf-9975fac6-1658705278929 returned an error code=400

  {
      "error": {
          "code": 400,
          "message": "Invalid JSON payload received. Unknown name \"instance\" at 'job.allocation_policy': Cannot find field.",
          "status": "INVALID_ARGUMENT",
          "details": [
              {
                  "@type": "type.googleapis.com/google.rpc.BadRequest",
                  "fieldViolations": [
                      {
                          "field": "job.allocation_policy",
                          "description": "Invalid JSON payload received. Unknown name \"instance\" at 'job.allocation_policy': Cannot find field."
                      }
                  ]
              }
          ]
      }
  }
 ```

### Environment 

* Nextflow version: 22.07.1-edge build 5726
* Java version: 11.0.15
* Operating system: macOS
* Bash version: zsh 5.8.1

### Additional context

`.nextflow.log` attached as a zip archive.

[nextflow.log.zip](https://github.com/nextflow-io/nextflow/files/9183651/nextflow.log.zip)

**Comment by pditommaso** [comment]
Thanks for reporting. This is caused by [this issue](https://github.com/nextflow-io/nextflow/issues/3051).

**Comment by andersgs** [comment]
Thank you. I'll close the issue.

**Comment by andersgs** [comment]
@pditommaso for your interest. After I removed the spot instance directive, I was able to run the hello example. I then tried to run my pipeline, which works on GCP Life Sciences. But, had the same error. I could get it to run by commenting on the `machineType` directive. For example:

```
    withLabel:process_low {
        cpus = 2
        //machineType = 'n2-standard-2'
    }  
```

**Comment by pditommaso** [comment]
Thanks for the feedback about the Google Batch executor. This is going to be addressed as well by [this change](https://github.com/nextflow-io/nextflow/pull/3044) that's going to be released hopefully next week. 


You can give a try to an early release using the command below: 


```
NXF_VER=22.08.0-SNAPSHOT nextflow run <your pipeline> [your usual options]
```

**Comment by andersgs** [comment]
@pditommaso a few notes as I test this snapshot out:

1. If I have a step that fails, and the error strategy is to set to ignore, Nextflow continues to run, but the pipeline is shut down on GCP. I have not tried other strategies.

2. I can still not use spot instances – the same error I reported above.

3. I have run into permissions problems when using my service principal, but not when using myself (which raises warnings about API limits, which - of course - is far from ideal given my admin privileges). I have had difficulty narrowing down what are the permissions that seem to be missing. One issue is that logs suggest a FASTQ file could not be found or read (but the correct bucket was mounted to the VM, and the file path is correct). I have storageAdmin role on the service principal, so I am unclear about what might be happening – the error is cryptic in that it only mentions "permission error", and nothing else. Again, when running as myself (full admin) this issue does not come up. It would be good to have similar documentation to what is available for AWS Batch on all the permissions required for a service principal to run on GCP Batch.

Thank you for all the hard work on this. It is coming along well otherwise. I do feel Batch could be a little more stable, but simply having access to VM logs is already a massive bonus over Life Sciences. I hope the above is helpful.

**Comment by pditommaso** [comment]
Thanks for you detailed report. I confirm that using version 22.08.0-edge spot works as expected. 

If you are still experiencing this or any of the other problems reported above, please open a separate issue including a minla example to replicate the issue and the corresponding `.nextflow.log` file
