### ISSUE TITLE
input staging of files/path symlink issue

### ISSUE THREAD

**Issue by fgualdr** [nextflow-io/nextflow#3068]
Hi!

I'm having issues with Nextflow staging symlinks.
Is there a way to remove disallow Nextflow to follow the input symlinks and treat them as files?

In the institute we are using petagene which creates symlinks to fasterq.
Nextflow in the command.run I can see at the nxf_stage()  step that is creating symlinks of symlinks following their entire path instead of treating the input path as a file.

Is there a way to turn this of?

Thanks a lot!

**Comment by bentsherman** [comment]
I think you can use the [stageInMode](https://www.nextflow.io/docs/latest/process.html#stageinmode) directive to control how these input files are staged into the work directory (e.g. copy, symlink, hard link).

But also, is it a problem if you have a symlink of a symlink? I think that still works.

**Comment by smlmbrt** [comment]
> I'm having issues with Nextflow staging symlinks.

I also had this problem! The solution was to make new hardlinks for input instead of pointing to symlinks. It was doing very strange like staging a totally different file in some cases.
