### ISSUE TITLE
Add warning when a NXF_ env variable is set in nextflow.config env scope

### ISSUE THREAD

**Issue by mribeirodantas** [nextflow-io/nextflow#3074]
Nextflow will ignore attempts to set NXF_ variables in env scope of the nextflow.config file. These environment variables should be set outside Nextflow.

The idea is to:
- [x] mention this explicitly in the documentation (https://github.com/nextflow-io/nextflow/pull/3083)
- [x] Make Nextflow throw a warning when an user attempts to set a NXF_ env variable within the env scope https://github.com/nextflow-io/nextflow/pull/3086

**Comment by jorgeaguileraseqera** [comment]
I think there is a typo in your description. Instead of NFX_ is NXF_

**Comment by pditommaso** [comment]
<img src="https://media2.giphy.com/media/3xz2BLBOt13X9AgjEA/giphy.gif"/>

**Comment by mribeirodantas** [comment]
Oh, my. I'm sorry. Paolo corrected me this morning and it happened again 🥲 Just edited. Thanks, @jorgeaguileraseqera.

**Comment by bentsherman** [comment]
Unfortunately the `NXF_` rule isn't perfect:
- the `NXF_DEBUG` variable is intended for tasks, it sets the debug level of the task script
- Nextflow understands other variables as well such as `JAVA_*` options and `*_PROXY` options
- Java options could be for Nextflow or for a task that uses Java

So while I think the docs warning is appropriate, I am reluctant to add a warning to Nextflow itself, as it will have false positives and false negatives.

**Comment by mribeirodantas** [comment]
Good point, @bentsherman. A solution could be having a list of non-task-related environment variables and if any of them is set in the env scope of nextflow.config, a warning would be shown mentioning that those will be ignored. This would fix the false positive/negative situation, even though this list would have to be updated accordingly in the future.

**Comment by pditommaso** [comment]
Even tho is not perfect, I think still makes sense to do. I saw this as a very common error and at least we can warn for `NXF_` vars
