### ISSUE TITLE
AWS Batch failures with 22.04.5

### ISSUE THREAD

**Issue by birnbera** [nextflow-io/nextflow#3091]
## Bug report 

Many of the features in the `v22+` releases are great improvements, such as the ability to forward `containerOptions` to Batch job definitions and parallel staging of directories from S3. However, I have encountered a strange new error after upgrading from `v21.10.6` that has never happened in the past. Now, when executing pipelines on Batch, I almost always have my runs terminated by an ECS error:

```
Essential container in task exited - CannotInspectContainerError: Could not transition to inspecting; timed out after waiting 30s
```

This seems to affect tasks somewhat randomly and doesn't have anything to do with the pipeline code itself. What appears to be happening is that after `.command.run` finishes (including uploading output to the work bucket), the ECS agent is timing out when reaping the container (see [this ECS agent issue](https://github.com/aws/amazon-ecs-agent/issues/2312) for related bug report to AWS).

The surprising part is that this does not happen with the exact same pipeline configuration and Batch queue using `v21.10.6`. I looked through the feature changes/additions between `21.10.6` and `22+` and I didn't see anything jump that would seem to explain how the ECS agent could be configured differently using the two versions. In fact, the `.command.run` scripts are completely identical besides the paths for download/upload from/to the work bucket. The jobs and job definitions that Nextflow generates are also the same between the two versions.

Rerunning with `-resume` bypasses the terminated process since the results are actually in the work bucket and cached. Several invocations with `-resume` usually allows the pipeline to eventually run to completion.

### Program output 

```text
Aug-03 02:57:47.656 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'preprocessWorkflow:fastp'

Caused by:
  Essential container in task exited - CannotInspectContainerError: Could not transition to inspecting; timed out after waiting 30s
```

### Environment 

* Nextflow version: `22.04.5` vs `21.10.6`
* Java version:
  ```console
  openjdk 11.0.15 2022-04-19
  OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
  OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
  ```
* Operating system: Linux, Centos7
* Bash version:
  ```console
  GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
  ```

**Comment by birnbera** [comment]
I now suspect that there may be some unannounced changes to ECS or AWS scheduling policies that are causing this issue. I updated the AMI that I use in my compute environment to the most recent version and I have yet to see `CannotInspectContainerError` with the new AMI, which includes a new ECS agent as well as Docker versions. The new agent changes how it reaps stopped containers, which is why it may bypass this issue. In any case, I did eventually see the error crop up with `21.10.6` and I'm no longer confident that problem was due to changes between `22.04.5` and `21.10.6`.

**Comment by indapa** [comment]
@bentsherman , @birnbera  I am getting this same error with Nextflow ```version 24.04.4```. I launch jobs locally from my  MacBook to run on AWS Batch:

```Nextflow verson 24.04.4```

```
openjdk 11.0.24 2024-07-16
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.24+8-adhoc.admin.jdk11u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 11.0.24+8-adhoc.admin.jdk11u, mixed mode
```

>Rerunning with -resume bypasses the terminated process since the results are actually in the work bucket and cached. Several invocations with -resume usually allows the pipeline to eventually run to completion.

This is the same approach I'm using and eventually I think my workflow will finish. 

The only difference is I am using Seqera  Wave. 

I posted in the community forum [here](https://community.seqera.io/t/cannotinspectcontainererror-when-launching-jobs-from-localhost-to-run-on-aws-batch/1687/7). But I saw this Github issue with the same problem. 

[nextflow.log_1.txt](https://github.com/user-attachments/files/18623309/nextflow.log_1.txt)

I attached my log file and here  are my relevant portions of my  config:

```
process {
    
    executor = 'awsbatch'
    queue = 'my-queue'
    // Default settings for all processes
    memory = '16GB'
    
    withLabel: 'high_memory' {
        memory = '64GB'
        
    }
    
}

aws {
    region = 'us-east-1'
    accessKey = ''
    secretKey = ''
    
    batch {
        cliPath = '/usr/local/aws-cli/v2/current/bin/aws'
    }
    
}

executor {
    queueSize = 10 //  decreased to 10 concurrent jobs
}



workDir = 's3://my-nextflow-logs-prod'
docker.enabled = true
wave.enabled = true

tower {
  accessToken = "$TOWER_ACCESS_TOKEN"
}
```
