### ISSUE TITLE
New feature: bridge executor

### ISSUE THREAD

**Issue by erbon7** [nextflow-io/nextflow#3094]
## New feature

Hi nextflow community. I'd like to propose a new feature for nextflow: a new executor based on the "bridge" scheduler.
Bridge is an abstraction layer to ease batch system and  resource manager usage in heterogeneous HPC environments (see https://github.com/cea-hpc/bridge). It is open source software and can be installed on top of existing classical job schedulers such as Slurm or LSF, or other schedulers. Bridge allows to submit jobs, get information on running jobs, stop jobs, get information on the cluster system, etc. 

## Usage scenario 

Users can manage the bridge executor just like any other executor, e.g.:
```
process.executor = 'bridge'
process.queue = 'milano'
process.time = '10h'
process.clusterOptions = '-A projectX'
```

## Suggest implementation 

Implement a new executor class BridgeExecutor along the others executor classes, extending the base class AbstractGridExecutor. Include the new executor as 'bridge' in the ExecutorFactory class.

**Comment by pditommaso** [comment]
Proposal accepted! feel free to submit a pull request for it.

**Comment by erbon7** [comment]
Thanks ! I'll do that soon.
