### ISSUE TITLE
Improve disk directive for Google Batch

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3095]
The disk directive allows adding a new persistent volume to the underlying VM, with the specified amount of storage. 

However in the current implementation is just ignored, because the nextflow job runs in the scratch local path `/tmp`. 

The disk directive should be used instead to control to size of the boot volume, taking precedence over the config option `google.batch.bootDiskSize`

**Comment by bentsherman** [comment]
I don't understand. Don't we want the disk directive to map to `/tmp` directory as scratch storage? Isn't that what it does for AWS Batch?

**Comment by pditommaso** [comment]
I think [this is](https://github.com/nextflow-io/nextflow/blob/wave-conda/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L169-L176) useless. 

Instead the disk size should have priority over bootDiskSize [here](https://github.com/nextflow-io/nextflow/blob/wave-conda/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L121-L122)
