### ISSUE TITLE
Nextflow image with podman and fuse-overlayfs

### ISSUE THREAD

**Issue by sanderthierens** [nextflow-io/nextflow#3096]
Would it be possible to make a nextflow image available on docker hub containing a Podman and fuse-overlayfs install. As for now the only containerization framework included in the images is Docker. This would allow us to use podman containers while running the nextflow pipeline inside a container (Podman-in-Podman).

**Comment by bentsherman** [comment]
You are welcome to build on the existing Nextflow docker image by installing podman and fuse-overlayfs, if you would like to test it for yourself.
