### ISSUE TITLE
Add `glob()` method for globs in favor of `file()`

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#3109]
Spawned from the language improvements mega-discussion (#3107). The `file()` method can be used to load a single file or multiple files using a glob string, which means this function can return a single path or a list depending on the input. This is bad. See #1236 and #2425 for similar problems.

Instead, there should be a separate function for globs, e.g. `glob()`, and the glob support via `file()` should be deprecated.

**Comment by pditommaso** [comment]
This already exists, it's called `files` 😄 

https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/Nextflow.groovy#L170-L173

**Comment by bentsherman** [comment]
If it's not in the docs then it doesn't exist!

**Comment by bentsherman** [comment]
Are you okay if we rearrange these functions so that `file()` throws a deprecation warning if you give it a glob?

**Comment by pditommaso** [comment]
It's a -1, this would mess up hundreds of pipelines for a problem can be solved just properly document `file` and `files`
