### ISSUE TITLE
Apply other config scopes to specific processes (`withName`, `withLabel`)

### ISSUE THREAD

**Issue by chris-cheshire** [nextflow-io/nextflow#3115]
### Expected behavior and actual behavior

Expected:

```
withLabel: gpu {
        queue = 'gpu'
        clusterOptions = '--gres=gpu:1'
        singularity.runOptions = '--nv'
 }
```

For this when I run `nextflow config` I expect this to display as written

Actual:

I see this:

```
withLabel:gpu {
      queue = 'gpu'
      clusterOptions = '--gres=gpu:1'
}

singularity {
   runOptions = '--nv'
}
```

### Steps to reproduce the problem

Place the above in a nextflow config file and run `nextflow config`

### Environment 

* Nextflow version: [22.04.5.5708] 
* Java version: 
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment Homebrew (build 11.0.15+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.15+0, mixed mode)
* Operating system: [macOS]
* Bash version: [zsh 5.8 (x86_64-apple-darwin20.0)]

**Comment by chris-cheshire** [comment]
Update:

This works for the config

```
 withLabel: gpu {
        queue = 'gpu'
        clusterOptions = '--gres=gpu:1'

        singularity {
            runOptions = '--nv'
        }
    }
```

But, if i then apply that label to a process i get

```
WARN: Unknown directive `singularity` for process `HAMMING`
```

**Comment by bentsherman** [comment]
This does not work because `process` and `singularity` are two different config scopes, so you can't set a `singularity` option inside the `process` scope.

In other words, I don't think it's possible to apply singularity options only to a specific process or label, it must be defined at the top-level or in a profile, and it will apply to all processes.

**Comment by phue** [comment]
I ran into the exact same thing when trying to use GPUs for a subset of processes with singularity.

[`process.containerOptions`](https://nextflow.io/docs/latest/process.html#containeroptions) can be used to achieve that, try:

```
 withLabel: gpu {
        queue = 'gpu'
        clusterOptions = '--gres=gpu:1'
        containerOptions = '--nv'
    }
```

**Comment by chris-cheshire** [comment]
Ahh thanks so much - this is a great solution @phue.

@bentsherman thanks for your reply - It would be really good if we could assign different scopes on a per-process basis. There are lots of use cases for this when tuning pipelines for particular clusters.

**Comment by bentsherman** [comment]
Wouldn't you use profiles to maintain different configurations for different clusters?

**Comment by chris-cheshire** [comment]
yes in a broad sense, but then we have config files that tune specific processes for use on a specific cluster - its finer grained than at the cluster level.
