### ISSUE TITLE
Service account not passed on when using Google Batch #platform/google-batch 

### ISSUE THREAD

**Issue by hnawar** [nextflow-io/nextflow#3118]
## Bug report

VMs still use the default compute service account even though the `google.batch.serviceAccountEmail` is set to a custom service account

<br class="Apple-interchange-newline">

### Expected behavior and actual behavior

Expected behavior:
Custom service account is used in VMs created to execute tasks
Actual Behavior:
Default compute service account is used by VMs which may lack some permissions

### Steps to reproduce the problem

Add the 
google.batch.serviceAccountEmail = [Some custom service account] 
to the bacth profile in the nextflow.config 

<br class="Apple-interchange-newline">

### Program output 
Default compute account is user

**Comment by alexshires** [comment]
The service account is here in the REST API: https://cloud.google.com/batch/docs/reference/rest/v1alpha/projects.locations.jobs#ServiceAccount - although it also says "Service account that VMs will run as. Not yet implemented." @hnawar

**Comment by pditommaso** [comment]
It looks like the service account is now supported https://cloud.google.com/batch/docs/reference/rest/v1/projects.locations.jobs#serviceaccount

**Comment by bentsherman** [comment]
The problem is that it does not exist in the Java SDK yet.

**Comment by hnawar** [comment]
It seems there is a slight delay. I will update the issue once the field is
available
