### ISSUE TITLE
Nextflow is not working with pre-existing named pools.

### ISSUE THREAD

**Issue by sahilhulage** [nextflow-io/nextflow#3119]
Hi,

I am defining to use pre-existing node pool in nextflow.config using process { 'queue = pool1' } after running this i am getting
below error. same pool is created by nextflow script with autopoolmode=true. 

need help here to resolve issue. 

Caused by:
  java.lang.NullPointerException

**Comment by sahilhulage** [comment]
![image](https://user-images.githubusercontent.com/81861149/184495371-a33ba154-9d5f-492e-a70a-90a2698e2445.png)

**Comment by abhi18av** [comment]
Hi @sahilhulage , 

I'm guessing that since you've mentioned `autopoolmode=true` , you're using the Azure Batch executor.

Could you please share your configuration and the `.nextflow.log` file with us? 

I think that the problem might be the pool spawned by Nextflow was deleted at the end of the pipeline.

**Comment by sahilhulage** [comment]
Hi Team,

Please find the attached log files.

Thanks,
Sahil Hulage

**Comment by abhi18av** [comment]
@sahilhulage , the logs are attached if you reply via email (I think) - they're not showing up here.

**Comment by sahilhulage** [comment]
[.nextflow.log](https://github.com/nextflow-io/nextflow/files/9394975/default.nextflow.log)

**Comment by sahilhulage** [comment]
I have added files please check it.

**Comment by sahilhulage** [comment]
Hi Abhinav,

the pools are already there. we are using the custom pool with docker
installed image of ubuntu.

thanks,
sahil

**Comment by abhi18av** [comment]
Hmm, interesting 🤔 

In that case, I think you're missing the following in your configuration for a custom Azure Pool

```
        azure.batch.pools {
          "custom-ubuntu-512-docker" {
            vmType = 'STANDARD_D16_V3' // <-- Replace with your VM type
            privileged = false
          }

```

**Comment by sahilhulage** [comment]
Hi,

Thanks for getting back to me. After adding that the java exception error
gone.

I am getting some error with python3 cant open file.

**Comment by abhi18av** [comment]
@sahilhulage , it's a bit tough to help without minimal reproducible example or log files. That particular error seems to be from the pipeline layer.

If possible could you please create a repo with this minimal use-case (without the sensitive info of course) and I'd be happy to take a deeper look.
