### ISSUE TITLE
Include SLURM partition when checking job status

### ISSUE THREAD

**Issue by dctrud** [nextflow-io/nextflow#312]
We have a hidden queue on our SLURM cluster. Currently nextflow is pulling out job status using squeue with:

    squeue -h -o %i %t, -t all

However, this listing will not show jobs submitted to a hidden queue, so nextflow loses track of the jobs, even though they are actually running. When the user sets the executor to us a specific queue (SLURM partition), the -p <queue> option is needed in order to see the job, e.g.

    squeue -h -o %i %t -t all -p myhidden

Would show jobs on the myhidden queue.

Would it be possible to add this for the SLURM executor? I could prepare a PR but don't have a nextflow build environment setup to test etc.

**Comment by pditommaso** [comment]
I guess that `-p` stands for partition. Yes, it should be possible. I will give a try to it.

**Comment by pditommaso** [comment]
I've uploaded a new snapshot including this patch. Please give it a try confirming that is working properly. 

```
export NXF_VER=0.24.1-SNAPSHOT
nextflow run etc .. 
```

**Comment by dctrud** [comment]
Many thanks! That fixes our issue. Nextflow is able to track the jobs on the hidden queue correctly.

**Comment by pditommaso** [comment]
Nice!
