### ISSUE TITLE
Feature request: store error code of previous attempt in task.previousErrorCode variable

### ISSUE THREAD

**Issue by diego-rt** [nextflow-io/nextflow#3120]
## New feature

Would be nice to be able to access the error code of a previous task attempt. With that, one could dynamically ask for more time if the error was because of a time limit issue, or increase memory if because of a memory issue. In my case, I would like to disable a specific flag in my process' command if the error code is non zero.

## Suggest implementation 

Perhaps it could be stored in a task.errorCode / task.previousErrorCode variable, likewise to task.attempt

**Comment by pditommaso** [comment]
It does already via `task.exitStatus`! See an example here https://www.nextflow.io/docs/latest/process.html#dynamic-computing-resources
