### ISSUE TITLE
Support s3 paths with spacing in nxf_s3_download method

### ISSUE THREAD

**Issue by pjongeneel** [nextflow-io/nextflow#3121]
## New feature

Support s3 paths with spaces using the nxf_s3_download method. Current behavior:

```
nxf_s3_download() {
    local source=$1
    local target=$2
    local file_name=$(basename $1)
    local is_dir=$(aws --region us-west-2 s3 ls $source | grep -F "PRE ${file_name}/" -c)
    if [[ $is_dir == 1 ]]; then
        aws --region us-west-2 s3 cp --only-show-errors --recursive "$source" "$target"
    else
        aws --region us-west-2 s3 cp --only-show-errors "$source" "$target"
    fi
}

>>> nxf_s3_download s3:/bucket/misc/some_file\ with_sapces.JPG some_file\ with_spaces.JPG

Unknown options: with_spaces.JPG
```

The FIX: (add quotes on basename line, and in s3 ls line.)

```
nxf_s3_download() {
    local source=$1
    local target=$2
    local file_name=$(basename "$1")
    local is_dir=$(aws --region us-west-2 s3 ls "$source" | grep -F "PRE ${file_name}/" -c)
    if [[ $is_dir == 1 ]]; then
        aws --region us-west-2 s3 cp --only-show-errors --recursive "$source" "$target"
    else
        aws --region us-west-2 s3 cp --only-show-errors "$source" "$target"
    fi
}

>>> nxf_s3_download s3:/bucket/misc/some_file\ with_sapces.JPG some_file\ with_spaces.JPG
>>> echo $?
0
```

## Usage scenario 

Fixes any issues with s3 paths and spacing

**Comment by pjongeneel** [comment]
FYI - the backslash space in the example s3 path is added by nextflow. My input parameter is this
`params.input_jpeg="s3:/bucket/misc/some_file with_sapces.JPG"

**Comment by pditommaso** [comment]
Blank in the file name should be supported. There are quite a few tests for this 

https://github.com/nextflow-io/nextflow/blob/fd759d0930f5324dec7d0c026dc51b359cf84922/validation/test-complexpaths.nf#L6-L13

**Comment by pjongeneel** [comment]
The issue is in the s3 staging, and not sure that test has a space in the file name and is testing using s3 staging.

Pretty easy to reproduce - try this main.nf on AWS Batch


```
nextflow.enable.dsl=2
workflow {
    main:
        foo(
            params.some_path,
        )
}

process foo {
    cpus = 1
    memory = 2.GB
    container = "ubuntu:18.04"

    input:
    path(input_path)

    script:
    """
    echo ${input_path}
    """
}
```

Just run with awsbatch executor and params.some_path = "s3://bucket/path with a space.txt

**Comment by pditommaso** [comment]
tagging @jorgeaguileraseqera or @bentsherman on this

**Comment by bentsherman** [comment]
The relevant source code is in `S3BashLib`:

https://github.com/nextflow-io/nextflow/blob/fd759d0930f5324dec7d0c026dc51b359cf84922/plugins/nf-amazon/src/main/nextflow/cloud/aws/util/S3BashLib.groovy#L97-L107

So we just need to wrap `\$source` in double quotes.

**Comment by pditommaso** [comment]
I'd like first to include a test case that replicates the problem in your test suite. See [here](https://github.com/nextflow-io/nextflow/issues/3121#issuecomment-1218070599)

**Comment by bentsherman** [comment]
As far as I can tell, `nxf_s3_download` is only used with awsbatch executor to stage input files into a task directory. Since `test-complexpaths.nf` has one process `foo` pass a file with spaces to another process `bar`, I just ran it on aws batch to trigger `nxf_s3_download`.

The command run script produces this line:
```bash
downloads+=("nxf_s3_download s3://nextflow-ci-dev/work/3e/844f1b3fd1fc66f062b4107bb735f5/sample_\(1\ 2\).vcf sample_\(1\ 2\).vcf")
```

And it worked. I was unable to reproduce the original error.

**Comment by pjongeneel** [comment]
I'm wondering if it has to do with the params entity entrypoint. Maybe there's something on the channel side that protects from this? 

Are you able to reproduce with the main.nf script I posted above?

**Comment by bentsherman** [comment]
Sorry I missed your script before. I tried it and it also succeeded, with Nextflow 22.08.0-edge.

**Comment by pjongeneel** [comment]
Super weird, tried with the same version as you and it just fails again. I guess we can try to figure out alternatives, but strange we get different results. 

```
$ nextflow -C test.nextflow.config run test.main.nf
N E X T F L O W  ~  version 22.08.0-edge
Launching `test.main.nf` [nice_joliot] DSL2 - revision: a8198e5562
WARN: The `echo` directive has been deprecated - use to `debug` instead
executor >  awsbatch (1)
[7e/18d8f7] process > foo [100%] 1 of 1, failed: 1 ✘
Error executing process > 'foo'

Caused by:
  Essential container in task exited

Command executed:

  ls *

Command exit status:
  1

Command output:
  (empty)

Command error:
  Unknown options: 2_D.JPG
  Unknown options: QC_Slide,2_D.JPG

Work dir:
  s3://**************/workflows/PATRICK/work/7e/18d8f7ea1489793ba28905dac492f6

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

```
$ cat test.main.nf
nextflow.enable.dsl=2
workflow {
    main:
        foo(
            params.inputs,
        )
}

process foo {
    echo true

    cpus = 1
    memory = 2.GB
    container = "ubuntu:18.04"

    input:
    path(inputs)

    script:
    """
    ls *
    """
}
```

```
$ cat test.nextflow.config
params.inputs = "s3://*********/misc/example-4x/QC_Slide 2_D.JPG"
aws.batch.cliPath = '/opt/aws-cli/bin/aws'
aws.batch.delayBetweenAttempts = 5
aws.client.maxConnections = 50
aws.region = 'us-west-2'
executor.queueSize = 1000
executor.submitRateLimit = '1 sec'
process.executor = 'awsbatch'
process.publishDir.path = 's3://*******/workflows/PATRICK/export/'
process.publishDir.mode = 'copy'
process.publishDir.enabled = true
process.queue = 'arn:aws:batch:us-west-2:********:job-queue/default-*******'
workDir = 's3:/******/workflows/PATRICK/work/'
```

**Comment by bentsherman** [comment]
Can you find the `.command.run` script for that task and post the line that is generated to stage the file from s3? Like the line I posted from before:
```bash
downloads+=("nxf_s3_download ...")
```

**Comment by pjongeneel** [comment]
I see this 
```
nxf_stage() {
    true
    # stage input files
    downloads=(true)
    rm -f QC_Slide\ 2_D.JPG
    rm -f .command.sh
    downloads+=("nxf_s3_download s3:/*******/misc/example-4x/QC_Slide\ 2_D.JPG QC_Slide\ 2_D.JPG")
    downloads+=("nxf_s3_download s3://******/workflows/PATRICK/work/7e/18d8f7ea1489793ba28905dac492f6/.command.sh .command.sh")
    nxf_parallel "${downloads[@]}"
}
```

I noticed that if I run this in bash, I also get that issue above. If you copy the nxf_s3_download function and run
```
nxf_s3_download s3:/*******/misc/example-4x/QC_Slide\ 2_D.JPG QC_Slide\ 2_D.JPG
```

I get the above error. When I modify the nxf_s3_download function to include quotes, I do not. If this is not reproducible on your end, perhaps it's something with the underlying ubuntu docker image we are using? Could try another.

**Comment by pditommaso** [comment]
Check the version of bash in the container

**Comment by pjongeneel** [comment]
```
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

**Comment by pjongeneel** [comment]
I was, you just need to modify the command run script like my first comments, need to add quotes in strategic locations to the download portion. If you're just running a one off, rename your files

**Comment by patrick-betteromics** [comment]
For all that follow this issue, I do see that this also happens with `nxf_unstage` when using Nextflow `22.04.5` if you have spaces in an output directory and stage like so:
```
nxf_unstage() {
    true
    nxf_s3_upload .command.out s3://****/workflows/440c7ef0-2177-4ee7-83eb-d74f47eb940b/work/2a/fdc1a53698bba67165679395613fc1 || true
    nxf_s3_upload .command.err s3://****/workflows/440c7ef0-2177-4ee7-83eb-d74f47eb940b/work/2a/fdc1a53698bba67165679395613fc1 || true
    nxf_s3_upload .command.trace s3://****/workflows/440c7ef0-2177-4ee7-83eb-d74f47eb940b/work/2a/fdc1a53698bba67165679395613fc1 || true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
    uploads=()
    IFS=$'\n'
    for name in $(eval "ls -1d output_folder/* log.txt" | sort | uniq); do
        uploads+=("nxf_s3_upload '$name' s3://****/workflows/440c7ef0-2177-4ee7-83eb-d74f47eb940b/work/2a/fdc1a53698bba67165679395613fc1")
    done
    unset IFS
    nxf_parallel "${uploads[@]}"
}
```
Uploads will only have the file name up to the first space, and the remained of the file name gets ignored. Basically, don't use spaces in the file names

**Comment by bentsherman** [comment]
Seems to be related to @Lehmann-Fabian 's PR #3202 , he found a similar issue but with the local staging/unstaging rather than S3. He said he was only able to reproduce with certain containers:

> I can only reproduce this error with some containers, e.g., the `nfcore/chipseq:1.2.2` one.
> So it has something to do with the installed bash/GNU core utils.
> Adding the quotes, however, makes it also work with this container.

**Comment by patrick-betteromics** [comment]
Question then: Should I perhaps add a PR to add quotes for stage/unstage? I think it's relatively harmless, I'd just need to show all tests pass and problematic containers would then work.

**Comment by patrick-betteromics** [comment]
Noticing all we have to do is put the first path in quotes and the follow (which crashes for Unknown options error) will work.
```nxf_s3_upload output_folder/a space.jpeg s3://*******/workflows/440c7ef0-2177-4ee7-83eb-d74f47eb940b/work/2a/fdc1a53698bba67165679395613fc1
```
