### ISSUE TITLE
Nextflow kuberun Remote origin did not advertise Ref for branch

### ISSUE THREAD

**Issue by tjdurant** [nextflow-io/nextflow#3149]
### Expected behavior and actual behavior

Running nextflow script from a private repository using the `nextlfow kuberun` command produces error:
```
❯ nextflow kuberun <url_to_repo> -hub gitlab -profile docker -r <commit_hash_123>
Pod started: gigantic-sanger
N E X T F L O W  ~  version 22.04.5
Pulling <repo> ...
Remote origin did not advertise Ref for branch refs/tags/v1.0.0~2. This Ref may not exist in the remote or may be hidden by permission settings.
```

However, when I run the same command but with `nextflow run` it works:
```
❯ nextflow run <url_to_repo> -hub gitlab -profile docker -r <commit_hash_123>
N E X T F L O W  ~  version 22.04.5
Pulling <repo> ...
 downloaded from <url_to_repo>
Launching `<url_to_repo>` [condescending_albattani] DSL1 - revision: <commit_hash_123> [<commit_tag>]
executor >  local (2)
[e5/0d82f5] process > lineage_call_clia (<spec_id>) [  0%] 0 of 2
```

Happy to provide additional information as needed.  

Thanks
T

### Environment 

* Nextflow version: version 22.04.5
* Java version: openjdk version "11.0.13" 2021-10-19
* Operating system: macOS
* Bash version: zsh 5.8 (x86_64-apple-darwin20.0)
* Container runtime - docker-desktop

**Comment by pditommaso** [comment]
The kuberun command is going to be deprecated. Consider using the new Wave and Fusion features that are a great and simpler alternative to kuberun https://github.com/seqeralabs/wave-showcase/tree/master/example8
