### ISSUE TITLE
List active operators that may hang the script execution 

### ISSUE THREAD

**Issue by msmootsgi** [nextflow-io/nextflow#315]
We ran into a situation where we refactored some operators and introduced a bug that caused the channel in question to remain open rather than close as we expected.  This open channel caused the whole pipeline to hang.  We saw this warning in the logs:

```
[Thread-1] DEBUG n.processor.TaskPollingMonitor - !! executor local > tasks to be completed: 0 -- first: null 
```

It would be really helpful in this situation to also print a list of open channels.  This would have helped us pinpoint the problem much quicker.

**Comment by pditommaso** [comment]
This is now available in version `0.25.0-RC2`. When the execution is aborted in the log files are reported the processes and operators still active (if any).
