### ISSUE TITLE
Hyperqueue job names must be less than 40 characters

### ISSUE THREAD

**Issue by jemunro** [nextflow-io/nextflow#3151]
However AbstractGridExecutor allows up to 256

https://github.com/nextflow-io/nextflow/blob/76a87c72ed0204b901a613b295fc3202f475cf21/modules/nextflow/src/main/groovy/nextflow/executor/AbstractGridExecutor.groovy#L157-L159

see:
https://github.com/It4innovations/hyperqueue/blob/7d5959d80fcb4e0ec79c818d93dfb3de57b96643/crates/hyperqueue/src/client/commands/submit/command.rs#L715-L723

**Comment by bentsherman** [comment]
Hyperqueue is written in Rust ... I'm in heaven 😄

**Comment by bentsherman** [comment]
Just need to overwrite this method in HyperqueueExecutor.groovy. Feel free to submit a PR or someone fwill get around to it.

**Comment by pditommaso** [comment]
This was an easy one. 👍
