### ISSUE TITLE
Process using exec: fails if using storeDir

### ISSUE THREAD

**Issue by jerdra** [nextflow-io/nextflow#3152]
### Expected behavior and actual behavior

When using a process with an `exec:` block defined and a `storeDir` defined the process always fails to find the file despite it existing in `task.workDir`

### Steps to reproduce the problem

```
import groovy.json.JsonOutput

process foo {

    storeDir "./cache"

    input:
    tuple val(uuid), val(map_value)

    output:
    tuple val(uuid), path("${uuid}.json"), emit: json

    exec:
    def outfile = task.workDir.resolve("${uuid}.json")
    def json_str = JsonOutput.toJson(map_value)
    File out = new File(outfile.toString())
    println outfile
    out.write(json_str)
}

input_channel = Channel.from("1", "2")
    .map {uuid -> [ uuid, [key: "value_${uuid}" ] ] }

workflow {
    foo(input_channel)
}

```
### Program output 

Error suggesting the file "1.json" or "2.json" is missing from the working directory

### Environment 

* Nextflow version: 22.04.5.5708
* Java version: openjdk 11.0.16.1
* Operating system: Linux
* Bash version: 5.1.16

### Additional context

Removing the `storeDir` directive results in the process completing without issue

**Comment by bentsherman** [comment]
Possible duplicate of #2628 . Currently `exec` code runs in the workflow launch directory instead of the task directory.

**Comment by jerdra** [comment]
@bentsherman ah in that case having the `${uuid}.json` file in my working directory should theoretically work (although definitely not a solution)? I guess the mechanism for detecting if the file is available is dependent on whether `storeDir` is specified or not? The file is correctly found in the task work directory if `storeDir` is left unspecified

**Comment by bentsherman** [comment]
Oh I see you are already resolving the JSON file against the task directory. In that case maybe the `NativeTaskHandler` isn't applying the storeDir correctly. Need to investigate further.

**Comment by bentsherman** [comment]
After some digging, looks like `storeDir` does not work with `exec` processes because the `.command.run` script is responsible for "unstaging" the task outputs into the store dir. Since an `exec` process doesn't have this wrapper script, the outputs are never written to the store dir.
