### ISSUE TITLE
overzealous sanitisation of task environment debug log

### ISSUE THREAD

**Issue by ghost** [nextflow-io/nextflow#3153]
https://github.com/nextflow-io/nextflow/blob/6cfb51e78c4a74bb5b195f5bcef3317bb1990f06/modules/nextflow/src/main/resources/nextflow/executor/command-run.txt#L48

The `sed(1)` script used to hide the tail of AWS environment variables not only masks `AWS_SECRET_ACCESS_KEY` (presumably the purpose!), but any variables starting with `AWS` where the value is longer than six characters. See example output below:

```text
============= task environment =============
+ env
+ sort
+ sed 's/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/'
AWS_BATCH_CE_NAME=BatchCxxxxxxxxxxxxx
AWS_BATCH_JOB_ATTEMPT=1
AWS_BATCH_JOB_ID=216603xxxxxxxxxxxxx
AWS_BATCH_JQ_NAME=BatchJxxxxxxxxxxxxx
AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=/v2/crxxxxxxxxxxxxx
AWS_EXECUTION_ENV=AWS_ECxxxxxxxxxxxxx
AWS_MAX_ATTEMPTS=5
AWS_METADATA_SERVICE_NUM_ATTEMPTS=5
AWS_METADATA_SERVICE_TIMEOUT=30
AWS_RETRY_MODE=standaxxxxxxxxxxxxx
CONDA_ENV_NAME=crispr
…
```

Maybe the pattern could be made a bit narrower? The [AWS-provided regexes for access key IDs and secret keys](https://aws.amazon.com/blogs/security/a-safer-way-to-distribute-aws-credentials-to-ec2/) are:

* `(?<![A-Z0-9])[A-Z0-9]{20}(?![A-Z0-9])`
* `(?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=])`

NB they do add this rider:

> We can’t guarantee these regular expressions will work forever (we reserve the right to change the format of access key IDs and secret access keys) but they’re a start.

**Comment by pditommaso** [comment]
Fair enough

**Comment by pditommaso** [comment]
Oh no! that's too easy 😄
