### ISSUE TITLE
-resume does not work if the process have task.memory and/or task.cpu values that have been modified.

### ISSUE THREAD

**Issue by Juke34** [nextflow-io/nextflow#3160]
## Bug report 

The -resume does not work if the process have task.memory and/or task.cpu values that have been modified.

exmaple of process:
```
process sambamba_sort {

    tag "$sample"
    label "sambamba"

    input:
        tuple val(sample), file (bam_file)
        val outpath

    output:
        tuple val(sample), file ('*_sort.bam')

    script:
        """
            sambamba sort -t ${task.cpus} -m ${task.memory.giga}G -o ${bam_file.baseName}_sambamba_sort.bam ${bam_file}
        """
}
```

Where memory and cpu is set (loaded via the profile):
```
    withLabel: 'sambamba' {
        cpus = 4
        memory = '64GB' // Giga
    }
```

### Expected behavior and actual behavior

I thought the resume would make abstraction of the modification related to ressources.

### Environment 

* Nextflow version: 22.04.0
* Java version: openjdk 11.0.8
* Operating system: Linux
* Bash version: bash 4.4.12

### Extra

If the behavior is expected I would love to make a feature request about such feature. Use case: I had 40 samples, 30 samples went well but the 31st crashed because not enough memory. I would love to increase the memory without re-computing the whole samples.

**Comment by bentsherman** [comment]
Interesting, I have always wondered whether the resource settings were included in the task hash.

Aside from this question, as a workaround you can make your resource setting dynamic so that it is automatically increased on extra attempts:
```groovy
process {
    memory = { 8.GB * task.attempt }
}
```

It's a standard practice used by [nf-core pipelines](https://github.com/nf-core/rnaseq/blob/master/conf/base.config) for example. This way you don't have to resume the entire pipeline due to resource-related failures.

**Comment by Juke34** [comment]
Tanh you for the tip ` * task.attempt` it could be enough in numerous cases

**Comment by Zruto** [comment]
> Interesting, I have always wondered whether the resource settings were included in the task hash.
> 
> Aside from this question, as a workaround you can make your resource setting dynamic so that it is automatically increased on extra attempts:
> 
> ```groovy
> process {
>     memory = { 8.GB * task.attempt }
> }
> ```
> 
> It's a standard practice used by [nf-core pipelines](https://github.com/nf-core/rnaseq/blob/master/conf/base.config) for example. This way you don't have to resume the entire pipeline due to resource-related failures.

Because my task contains several processes, each process requires different memory, so if the current process fails, can I dynamically adjust it according to the current memory size, such as this
```
memory = { (50.GB * task.attempt) + task.memory }
```

**Comment by bentsherman** [comment]
That is a recursive definition

**Comment by Zruto** [comment]
If I want to add task.attempt*50GB to the memory used by the current failed process, how should I define it?

**Comment by bentsherman** [comment]
You could use a param:

```groovy
withName: 'foo' {
    memory = { params.foo_initial_memory + (50.GB * (task.attempt - 1)) }
}
```

**Comment by bentsherman** [comment]
The thing is that the `memory` is defining the initial memory size, so it has to be defined there or come from a param. But usually people use the step as the initial size, so `50.GB * attempt` will use 50 GB on the first attempt.

If you want to have different sizes for different processes, the standard practice in nf-core is to define a few presets like small, medium, and large, and use labels to apply them to different processes. See nf-core/rnaseq for an example.
