### ISSUE TITLE
Secrets in local store is in clear text

### ISSUE THREAD

**Issue by tgotzsche** [nextflow-io/nextflow#3165]
## New feature

Hi! Thanks for using Nextflow and submitting the proposal 
for a new feature or the enhancement of an existing functionality. 

Please replace this text providing a short description of your 
proposal.

## Usage scenario 

When using the nextflow secret feature, secrets are stored in clear text in the secrets/store.json file.
Although the file is stored privately in users home folder, it is not optimal.

## Suggest implementation 
Some kind of encryption or at least obfuscation should be done, e.g. like I K8S where they base64 encode secrets.
But some proper AES256 encryption would be desirable,

Can be implemented in the LocalSecretsProvider.groovy file. Probably a flag must be provided to ensure backwards compatibility with existing stores.

**Comment by pditommaso** [comment]
We discussed this problem when implementing this feature. The consensus was to consider it safe as long as the "secret" file is accessible only to the owner user 

https://github.com/nextflow-io/nextflow/blob/f5a5245bf9869355fc60e4e9ce07b74f237d7409/modules/nextflow/src/main/groovy/nextflow/secret/LocalSecretsProvider.groovy#L200-L206

This is a common practice for other linux tools, like SSH client for example.
