### ISSUE TITLE
Trace file is not uploaded in certain conditions

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3183]
I've noticed that when using S3 as target for trace file. The trace is not created. 

To replicated it 

```
nextflow run pditommaso/hello -with-trace s3://nextflow-ci/test/trace.txt
```

No error is reported, however the file is not there.

**Comment by pditommaso** [comment]
I've noticed this happening both is latest edge and also in [this branch](https://github.com/nextflow-io/nextflow/tree/fix-race-condition-on-transfer-pool). 

It would interesting to see if it happens in the 21.10.x series. 

Also there's something wrong in the s3 output stream logic below: 

https://github.com/nextflow-io/nextflow/blob/107ea8e7266e68fa6691a924683c149385daa32f/plugins/nf-amazon/src/main/com/upplication/s3fs/S3OutputStream.java#L275-L295
 

Makes no sense the first buffer is 10K and the other `request.getChunkSize()` (using allocateDirect!) 

Moreover it should be added some unit tests for S3OutputStream logic for single part and multipart version

**Comment by jorgeaguileraseqera** [comment]
I've found that sometimes at the end of the upload we are trying to send a chunk with a length less than the minimum and this abort the upload

```
com.amazonaws.services.s3.model.AmazonS3Exception: Your proposed upload is smaller than the minimum allowed size (Service: Amazon S3; Status Code: 400; Error Code: EntityTooSmall; Request ID: ..; S3 Extended Request ID: DelE...; Proxy: null), S3 Extended Request ID: Del....
```

**Comment by pditommaso** [comment]
Never seen this. I'd start with some unit testing to isolate the issue

**Comment by jorgeaguileraseqera** [comment]
> Never seen this. I'd start with some unit testing to isolate the issue

yes, I'm on it

**Comment by jorgeaguileraseqera** [comment]
I've tested with version `21.10.6` and it seems the error was already present then

I think the issue comes when we call `flush` in an S3OutputStream (for example when TraceObserver writes directly into the stream) and we send to the executor the current buffer to be uploaded without checking if it has the minimum length required and we create an invalid multipart (only checked by AWS at the end)

I'll work on it

FYI: You can send a multipart with only *1 part* with a few bytes

**Comment by jorgeaguileraseqera** [comment]
about 

> Makes no sense the first buffer is 10K and the other request.getChunkSize() (using allocateDirect!)

I'm not sure what's the best approach: always use `ByteBuffer.allocate` or `ByteBuffer.allocateDirect`?

**Comment by pditommaso** [comment]
Let's just use `ByteBuffer.allocate`, direct memory is a mess

**Comment by jorgeaguileraseqera** [comment]
solved in https://github.com/nextflow-io/nextflow/pull/3193

(forget to tag with close in the PR)
