### ISSUE TITLE
Get rid of file name rolling for reports, trace, dag and timeline generation 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3186]
When creating the execution report and other resource files such as timeline, DAG and trace file, nextflow roll the name any existing file with the name. 

https://github.com/nextflow-io/nextflow/blob/3ef915128ee48ba3422cc7b13807c438ed170b4f/modules/nextflow/src/main/groovy/nextflow/trace/TraceFileObserver.groovy#L209-L210

This avoid the user to overwrite accidentally existing files, however, it can be an expensive operation when the file is hosted into a remove bucket repository since renaming it's mapped to a copy & delete operation (up to 10 files!) 

The goal of this issues is to get rid of the file name rolling functionality. 

When nextflow tries to create such files, if a file with such name, a warning should be shown and the corresponding report/trace file should *not* be created. 

If the strict mode is enabled and error should be reported and the execution stopped

**Comment by ewels** [comment]
Yeah, we forged our own way for this in nf-core a while back 😆  From the [template `nextflow.config`](https://github.com/nf-core/tools/blob/bc56cdd35077e408a0a7c90ec07fcdff7c2d1f3b/nf_core/pipeline-template/nextflow.config#L168-L184)

```nextflow
def trace_timestamp = new java.util.Date().format( 'yyyy-MM-dd_HH-mm-ss')
timeline {
    file    = "${params.tracedir}/execution_timeline_${trace_timestamp}.html"
}
```

I think that the main motivation for this was to avoid filename overwriting on AWS for the trace file on s3, which was causing a crash (it was a while back now, so I could be wrong).

@bentsherman I like your suggestion, looks good 👍🏻 Microsecond probably not necessary but not sure it really matters either, as long as the same suffix is used for all files from a given run.

**Comment by bentsherman** [comment]
Okay here is my example amended to match the nf-core convention:
```
nextflow_2022-09-06_14-22-29.log
```

Not that we should try to match nf-core for its own sake, but I happen to like this format.

**Comment by jemunro** [comment]
Would it be possible to create a copy/symlink that points to the most recent log/trace? For the purpose of debugging it's nice to be able to quickly check the latest output, and bash tab completion of filenames with datestamps is painful. The nice thing about the current system is I know that the most recent trace/log is at `trace.txt` and `.nextflow.log`.

e.g.
`ln -s nextflow_2022-09-06_14-22-29.log nextlfow_latest.log`

**Comment by pditommaso** [comment]
We are doing this to support bucket storage such as AWS S3. Those do not allow the use of symlink.

**Comment by pditommaso** [comment]
I'm tempted to use `report-${millis}.html` for this. it would be that bad?

**Comment by ewels** [comment]
What does that look like? A unix timestamp in milliseconds? Not so bad, just not really any added value beyond fixing the bug.

Is there any reason not to use a human-readable timestamp?

**Comment by pditommaso** [comment]
Because at the end also timestamps like this `nextflow_2022-09-06_14-22-29.log` are not very readable.

**Comment by bentsherman** [comment]
Seems pretty readable to me... certainly more readable than a Unix timestamp.

**Comment by ewels** [comment]
It's how I name most things 😅

I think that even if a single filename isn't super easy to read (requires some 🤨 at least), they group nicely and it's very quick to see if things come from different days / weeks / months at a glance. Also it is possible to read with some squinting, whereas a timestamp requires (a) recognising that it's a date and (b) copying into a website to convert into a date.

**Comment by pditommaso** [comment]
My take on this is that the primary goal of this is to prevent file name collisions and not to encode timestamps in the file name. The date can access from the file using a simple `ls -la` or `aws s3 ls` command. Also, nf-core is already using its own naming pattern which is fine. 
 
I've opted for a more compact `report-YYYYMMFF-daymillis.html`. 

Solved by a762ed59.

**Comment by ewels** [comment]
Nice 👍🏻 This is still much more human readable than a unix time stamp so I'm happy. I think we can probably drop the custom filenames in nf-core now.

**Comment by pditommaso** [comment]
Thinking more, should the nextflow "run name" be used instead of the date-millis?

**Comment by ewels** [comment]
That also works 👍🏻 Might be nicer actually.
