### ISSUE TITLE
Docs are out of date, can you republish?

### ISSUE THREAD

**Issue by kevinwuhoo** [nextflow-io/nextflow#3191]
I was reading through the basic concepts and the [Processes and channels](https://www.nextflow.io/docs/latest/basic.html#processes-and-channels) section confused me. The following section seemed incorrect as it was referencing things that didn't seem to exist:

<img width="752" alt="Screen Shot 2022-09-06 at 22 29 04" src="https://user-images.githubusercontent.com/531488/188796052-bc40e2da-cb6b-4100-9112-29ead12f6be2.png">

However, it looks [fixed in the source](https://github.com/nextflow-io/nextflow/blob/master/docs/basic.rst#processes-and-channels) by @jorgeaguileraseqera in https://github.com/nextflow-io/nextflow/commit/be49efdc7aac4aad3fba7dd6ba816ff2992f1bc8.

<img width="1067" alt="Screen Shot 2022-09-06 at 22 30 22" src="https://user-images.githubusercontent.com/531488/188796210-0cb51a93-e15f-4fd2-b843-f349f457c2dc.png">

I think it's worth republishing the docs if it's not difficult so other people aren't also confused. Thanks for the great work ya'll!

**Comment by FloHu** [comment]
I second that, I am currently going through the tutorial "[your first script](https://www.nextflow.io/docs/latest/getstarted.html#your-first-script)" and the descriptions do not match the code shown and when following the instructions I get errors.

**Comment by pditommaso** [comment]
tagging @bentsherman here

**Comment by bentsherman** [comment]
Hi @kevinwuhoo , the stable docs are typically only updated for each major release, which happens every 6 months. The [edge docs](https://www.nextflow.io/docs/edge/basic.html#processes-and-channels) are updated more frequently, and as you can see this example is currently up to date in the edge docs.

Unfortunately we don't currently have a process for backporting changes like this one that also apply to past versions. We are in the process of overhauling the Nextflow website and docs, so some of these issues will be resolved during that transition. In the meantime, you can always refer to the edge docs or the [Seqera training website](https://training.seqera.io/).

@pditommaso On further reflection, I think backporting new changes to previous versions will be more difficult than we thought, and probably won't matter anyway after the website overhaul. Maybe we should just have a single version of the docs that is frequently updated. As long as we add version callouts to new features and behavior, users will always know what to expect for the version of Nextflow they are using.

**Comment by kevinwuhoo** [comment]
Thanks for the response. I'll refer to the edge docs for now.
