### ISSUE TITLE
Ability to use basic authentication using weblog

### ISSUE THREAD

**Issue by di-hardt** [nextflow-io/nextflow#3198]
## New feature

Give users the ability to provide [basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) credentials via the weblog URL. So logs can be posted to a secured server. 

## Usage scenario 

Collecting weblogs on remote server which requires a basic authentication. Nextflow call should look like:
`nextflow run -with-weblog https://user:password@example.com .... main.nf`

## Suggest implementation 
`modules/nextflow/src/main/groovy/nextflow/util/SimpleHttpClient.groovy` already supports basic authentication, but there is no functionality to extract the credentials from the URL or provide it by a separate parameter.

I implemented it in a fork: https://github.com/di-hardt/nextflow/commit/3ef40cc139c81e535ac18b0ab7a6099c61af2591

If no credentials were provided in the URL or a `basicToken` attribute is already set the code will simply do nothing.

**Comment by pditommaso** [comment]
It's out of the scope of the plugin. Consider to user Tower client plugin for that
