### ISSUE TITLE
only one process execute in two parallel channels

### ISSUE THREAD

**Issue by biowang** [nextflow-io/nextflow#32]
Dear Sir,
I have two parallel process, utr corelatted by the miRNA and lncRNA corelatted by the miRNA.
But only corelation of utr and miRNA executted.
== please see the zip attachment "example_nextflow.zip.png" ==

    [llwang@fat01 example_nextflow]$ ./corelation.nf
    == messages == N E X T F L O W  ~  version 0.12.0
    == messages == [warm up] executor > local
    == messages == [3a/f8e09d] Submitted process > val_mir (1)
    == messages == [98/77d5d4] Submitted process > val_lnc (1)
    == messages == [ce/1d8363] Submitted process > val_utr (1)
    == messages == [55/5bc0ca] Submitted process > cor_utr (5)
    == messages == [df/44885b] Submitted process > cor_utr (6)
    == messages == [17/0ce5df] Submitted process > cor_utr (2)
    == messages == [a3/2d4d29] Submitted process > cor_utr (1)
    == messages == [ae/480a17] Submitted process > cor_utr (4)
    ...
    == messages == [ab/976891] Submitted process > cor_utr (99)
    == messages == [db/41a6be] Submitted process > cor_utr (95)
    == messages == [b0/9ff97f] Submitted process > cor_utr (100)
    == messages == Result saved to file: /llwang-works/installation/example_nextflow/utr.cor.result

#####  pipeline  overview 

         ***************      *****************        ******************
         * utr channel *      * miRNA channel *        * lncRNA channel *
         ***************      *****************        ******************
     
            |                      |                         |
         validate               validate                  validate
            |                      |                         |
           \./                    \./                       \./
            .                      .                         .
     
         *****************    *****************        ******************
         * utr val chann *    * mir val chann *        * lnc val chann  *
         *****************    *****************        ******************
     
            |                    |           |                    |
           split                 |           |                  split
            |                    |           |                    |
           \./                  \./         \./                  \./
            .                    .           .                    .
     
         ****************************      ****************************
         * corelation channel       *      * corelation channel       *
         ****************************      ****************************
                     |                                 |    
                  collect                           collect 
                     |                                 |    
                    \./                               \./   
                     .                                 .        
                  file_utr                          file_lnc

**Comment by pditommaso** [comment]
I'm unable to access your script.

**Comment by biowang** [comment]
I provide you two links for example_nextflow.zip:
1. http://pan.baidu.com/s/1o61G4X0
2. http://www.evernote.com/l/AIBXKRCeQ0FCy6IK5Oi6GJ3z9PhY4utrnF4/
3. https://www.dropbox.com/s/1oalkpxqmtdqpvw/example_nextflow.zip?dl=0

**Comment by pditommaso** [comment]
OK, the problem in your script that you are using `first()` twice. Don't forget that operators consume the content of a *channel*, so two the second time that it invoked in the second process it will receive nothing because the channel emit only one value. 

The right way to handle this situation is declaring a variable holding the value you want and use it, in the following two processes. For example" 

    mirValCh_first = mirValCh.first()

Bonus tip: you do not need to use absolute path in your processes, and it is much better to avoid them, to make your script more portable. If you put your external scripts into a folder named "bin" in the project root and give them execute permission, you can invoke them directly. 

I've modified your source to show it. You can find in the zip below 

https://dl.dropboxusercontent.com/u/376524/correlation.zip

**Comment by biowang** [comment]
The problem has been solved. and I benefit from you bonus tip.
this pipeline successfully execute on local, but  hung while submitting the job to the pbs cluster.

/========= message ===========/
[llwang@fat01 example_nextflow]$ nextflow -log pbs.log run corelation.nf
N E X T F L O W  ~  version 0.12.3
[warm up] executor > pbs
[c8/791841] Submitted process > val_mir (1)
[ee/9f4413] Submitted process > val_utr (1)
[08/6763a3] Submitted process > val_lnc (1)

/====================================/

code and log in the zip below:
https://www.dropbox.com/s/fvnvb38d1alb4if/correlation.zip?dl=0
http://www.evernote.com/l/AIChwAgHHZJG2I_rif1QPoeLaO-n-ezfjeY/

**Comment by pditommaso** [comment]
Regarding PBS, are you able to submit a job to the scheduler from this node (without nextflow)? 

Also, and more important, is the folder `/llwang-works/installation/example_nextflow/work/` a network shared folder ? I guess no .. 

When running a pipeline in the cluster it must run in a directory accessible from all cluster nodes.

**Comment by biowang** [comment]
yes, you are right.
Thank you very much
The pbs job successfully finished, after I copied the fold to the shared folder( a disk mounted on the same path of each node of cluster).

**Comment by pditommaso** [comment]
Good. Enjoy it.
