### ISSUE TITLE
Add config option to control DAG level of detail

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#3203]
See this Slack thread: https://nextflow.slack.com/archives/C02T98A23U7/p1662981608103629

It would be nice for the `dag` config scope to have a `verbose` option to control whether extra details like channel names and operators are displayed.

I should note however that toggling operators is not so trivial. Each operator is a node, so you would need to connect it's inputs to it's outputs. Easy enough to implement, but in cases where an operator has multiple inputs and multiple outputs, you might make things messier than before. So consider hiding the operator name but leaving an empty node to preserve the overall shape of the dataflow.

@mribeirodantas Should be a good issue for you when you have time.

**Comment by mribeirodantas** [comment]
When you say _hiding the operator name but leaving an empty node_, the DAG structure wouldn't change. Only the label for operator/channels would be hidden, right?

**Comment by bentsherman** [comment]
Right

**Comment by bentsherman** [comment]
Probably a separate effort, but I think we should also be able to collapse subworkflows into single nodes. That would make the DAG actually usable for real workflows.

As an example, I generated the Mermaid diagram for rnaseq: ![rnaseq](https://user-images.githubusercontent.com/7884825/190516250-50b49e2a-a988-431d-bdd1-dcc62f2ac05a.png)

It's like looking at the logic diagram of an entire CPU -- hilariously impossible. What you really want is something more coarse-grained by default, that you can optionally make more fine-grained as you need it. A config option called e.g. `dag.depth` could control how many levels to show, just like the depth of a TOC tree.

nf-core/rnaseq is a bit weird because the top-level workflow calls `NFCORE_RNASEQ`, which calls `RNASEQ`, which implements the actual workflow. So for rnaseq you would set `dag.depth = 3` to get a level of detail comparable to the diagram [here](https://github.com/nf-core/rnaseq/blob/master/docs/images/nf-core-rnaseq_metro_map_grey.png).

Related issues: #1056 #1543

**Comment by pditommaso** [comment]
LOL. what pipeline is this?

**Comment by bentsherman** [comment]
nf-core rnaseq !
