### ISSUE TITLE
How to config for executor - pbspro to recognize the optionCluster "-J 1-2\n#PBS -o logs/batch.^array_index^.log"

### ISSUE THREAD

**Issue by thehung92** [nextflow-io/nextflow#3210]
Hi, I'm trying to write a nextflow script to submit batchjob to pbspro and write both stdout and stderr to the same file that I can collect later. I know that the PBS script header should look like below

```
#PBS -o logs/batch.^array_index^.log
#PBS -j oe
```

## The issue:

Right now my config file looks like this

```
process {
    executor = 'pbspro'
    queue = 'normal'
    cpus = 1
    time = 5.m
    clusterOptions = { "-J 1-2\n#PBS -o logs/batch.^array_index^.log" }
}
```
my nextflow run will create a .command.run that look like this
```
#!/bin/bash
#PBS -J 1-2
#PBS -o logs/batch.^array_index^.log
#PBS -N nf-TEST_1
#PBS -o /Users/hung/Data/side-project/shareUtils/manage-pbs/work/1b/9bc73895c9cac747e061eede909431/.command.log
#PBS -j oe
#PBS -q normal
#PBS -l select=1:ncpus=1
#PBS -l walltime=00:05:00
```

However the script submitted do not recognize the first -o flag as the output, it only take the 2nd -o flag. Following is the result of qstat -f of the jobs after submitted toi PBS with qsub

```
Job Id: 8669792[].wlm01
    Error_Path = ntu01-ib0:/data/12000454/hung/side-project/temp/nf-TEST_1.e8669792.^array_index^
    Join_Path = oe
    Output_Path = /Users/hung/Data/side-project/shareUtils/manage-pbs/work/1b/9bc73895c9cac747e061eede909431/.command.log
```

Is there a workaround for this? To move the clusterOptions to the end of the PBS line so that PBS will recognize the option that I specified? 

```
"-o logs/batch.^array_index^.log"
```

Or this is a feature that is not yet implemented?

## system info
qstat --version
pbs_version = 19.2.5.20191022141354
nextflow -version
version 22.04.5 build 5708

**Comment by bentsherman** [comment]
Nextflow by default writes the log file to `.command.log` in the task directory, if you look at your headers you'll see it applies this setting after your custom setting, and your setting is overwritten.

In general I don't think it's possible to overwrite the output log. However we could make it work for pbspro by applying `clusterOptions` after Nextflow's default output log setting. @pditommaso what do you think?
