### ISSUE TITLE
Fail to upload the reports file 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3211]
The Tower plugin stores all file paths published by a pipeline execution into a file named `nf-{id}-reports.tsv`. 

It looks like the latest versions introduced a regression by which the file is not correctly uploaded when the pipeline work dir is store in AWS S3. See here 

https://github.com/nextflow-io/nextflow/blob/master/plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerReports.groovy#L64-L101

The problem can be replicated using the [rnaseq-nf](https://github.com/nextflow-io/rnaseq-nf) pipeline

**Comment by jorgeaguileraseqera** [comment]
I think the issue come from this commit

https://github.com/nextflow-io/nextflow/commit/8d2b0587f137561e89100d3d8d70cca7f8251a26

Debugging the pipeline I've found we close the session and all writers and after we received the rest of reports

**Comment by pditommaso** [comment]
Agree on the cause, but the problem is not related to the reports uploaded by the timer task?

**Comment by jorgeaguileraseqera** [comment]
no, I think it is not related, once the session is closed we receive remainders reports but the Agent is not listening and doesn't update the report file
After, once nextflow finish, Tower upload the report but it's incomplete

I'm now reviewing how we are closing the session to identify the error

**Comment by pditommaso** [comment]
Still thinking when the timer is cancelled a final upload it should be made 


https://github.com/nextflow-io/nextflow/blob/master/plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerReports.groovy#L117-L122

after the `reportsFile.close()`

**Comment by pditommaso** [comment]
that callback is invoked by [this](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/Session.groovy#L641-L641). So session and S3 thread pool should be still ok

**Comment by jorgeaguileraseqera** [comment]
I've debugged the pipeline and this is the flow of calls 

```
ScriptRunner.shutdown : 
   -> session.shutdown()
       -> Session.shutdown:
                shutdown0() call notifyFlowComplete
                   TowerClient.flowComplete
                         writer.await()   //// Not all reports are received
   -> FileTransferPool.shutdown(session.aborted)
         sometimes towerClient receives a few remainders reports. If I add sleep it receives all
  -> exit
```

I think the issue happens because we are exiting before processing all pending files but not sure how to proceed

**Comment by pditommaso** [comment]
"//// Not all reports are received" do you mean the publishDir continue to push new files paths ?

**Comment by jorgeaguileraseqera** [comment]
yes, I think so

**Comment by pditommaso** [comment]
That components uses [this](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy#L113-L113) thread pool

which indeed iss shutdown [here](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflo.w/src/main/groovy/nextflow/script/ScriptRunner.groovy#L247-L247) 

instead before it was just before [shutdown0](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/Session.groovy#L641-L641) 

maybe moving back there solves the problem. tho I fear we have some kind of circular dependencies

**Comment by pditommaso** [comment]
Think I've solved this using a different thread pool for the publisDir and the file transfer component. See 9cc4f079. 

it was also essential to save the final reports file on completion.

https://github.com/nextflow-io/nextflow/blob/9cc4f0797c8e9e6f10264fabdf45e6d9b3505d5b/plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerReports.groovy#L115-L135


Please review.

**Comment by jorgeaguileraseqera** [comment]
I've tested with a pipeline with 2 processes that publish a lot of files (28+) and it seems to be working fine

I think we can close this issue
