### ISSUE TITLE
Channel merge still deprecated with dsl2

### ISSUE THREAD

**Issue by Kibubu** [nextflow-io/nextflow#3219]
## Bug report 

Merge was reinstated during discussion #2113 with commit 1649944b19351f6b3f2ba9f5d052e6562cdf1d3d. But the current edge release and build form source still shows `merge` being deprecated for DSL2.

### Expected behavior and actual behavior

Merge of two channels should work.

### Steps to reproduce the problem

```nextflow
workflow{
  a = Channel.from(1, 2, 3)
  b = Channel.from(4, 5, 6)
  a.merge(b).view()
}
```

### Program output 
```shell
N E X T F L O W  ~  version 22.09.3-edge
Launching `merge.nf` [evil_brown] DSL2 - revision: 041b59aee1
Operator `merge` has been deprecated -- it's not available in DSL2 syntax

 -- Check script 'merge.nf' at line: 4 or see '.nextflow.log' file for more details
```

### Environment 

* Nextflow version: 
  N E X T F L O W
  version 22.09.3-edge build 5767
  created 10-09-2022 14:55 UTC (16:55 CEST)
  cite doi:10.1038/nbt.3820
  http://nextflow.io

  and

  Build from source 4a17e198428d315db54f919f8d9f47d6ca4c5cac
* Java version: 
  openjdk version "18.0.2" 2022-07-19
  OpenJDK Runtime Environment (build 18.0.2+0)
  OpenJDK 64-Bit Server VM (build 18.0.2+0, mixed mode)
* Operating system: 
  LSB Version:	n/a
  Distributor ID:	ManjaroLinux
  Description:	Manjaro Linux
  Release:	22.0.0
  Codename:	Sikaris
* Bash version:
  GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2020 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by bentsherman** [comment]
That is strange because there are two other implementations that aren't deprecated:
```groovy
    // NO DAG
    DataflowWriteChannel merge(final DataflowReadChannel source, final DataflowReadChannel... others) {
        new MergeOp(source,others as List).apply()
    }

    // NO DAG
    DataflowWriteChannel merge(final DataflowReadChannel source, final List<DataflowReadChannel> others, final Closure closure=null) {
        new MergeOp(source,others,closure).apply()
    }
```

I assumed the deprecated method was just an old implementation that didn't work in DSL2.

**Comment by Kibubu** [comment]
They aren't deprecated anymore, Paolo removed the deprecation during the referenced discussion. I guess this one just got forgotten, but there might be another reason. I only tested `make test` and this issues example.

1649944b19351f6b3f2ba9f5d052e6562cdf1d3d
