### ISSUE TITLE
Nextflow -with-docker not finding executable program

### ISSUE THREAD

**Issue by chriswyatt1** [nextflow-io/nextflow#3221]
Hi,

I have a working container with an executable called "datasets", which works within docker, but not Nextflow.

You can run the container using the following command:

`docker run -it chriswyatt/ncbi_datasets:version2.0 datasets version`

which results in the following:
```
13.39.1
New version of client (13.40.0) available at https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets
```
When you run with Nextflow (version 22.04.5 build 5708) the following repository:

`https://gitpod.io/#https://github.com/chriswyatt1/jcvi-nextflow`

`nextflow run main.nf -profile docker --input data/Example.csv`

**which creates the following execution line:**
```
nxf_launch() {
    docker run -i --cpus 1.0 -v /workspace/jcvi-nextflow:/workspace/jcvi-nextflow -v "$PWD":"$PWD" -w "$PWD" --entrypoint /bin/bash -u $(id -u):$(id -g) --name $NXF_BOXID chriswyatt/ncbi_datasets:version2.0 -c "eval $(nxf_container_env); /bin/bash -ue /workspace/jcvi-nextflow/work/40/670bc8810326bfcaa1fbf978be46fd/.command.sh"
}
```

**where docker.config:**

```
  withLabel: 'download' {
    container = 'chriswyatt/ncbi_datasets:version2.1'
    cpus = 1
    echo = true
  }
```

**I get the following error:**

```
Command exit status:
  127

Command output:
  (empty)

Command error:
  c229119241af: Pulling fs layer
  efca48bd61d1: Pulling fs layer
  5667b96fd26a: Pulling fs layer
  13131b8ccc34: Pulling fs layer
  4f4fb700ef54: Pulling fs layer
  21797b0c5304: Pulling fs layer
  af0b02954a72: Pulling fs layer
  e71656c1717c: Pulling fs layer
  188fa3526e57: Pulling fs layer
  566b7efb9b31: Pulling fs layer
  21797b0c5304: Waiting
  19d73456d4d1: Pulling fs layer
  4f4fb700ef54: Waiting
  13131b8ccc34: Waiting
  e71656c1717c: Waiting
  19d73456d4d1: Waiting
  af0b02954a72: Waiting
  566b7efb9b31: Waiting
  188fa3526e57: Waiting
  efca48bd61d1: Verifying Checksum
  efca48bd61d1: Download complete
  5667b96fd26a: Download complete
  c229119241af: Download complete
  13131b8ccc34: Download complete
  4f4fb700ef54: Verifying Checksum
  4f4fb700ef54: Download complete
  af0b02954a72: Verifying Checksum
  af0b02954a72: Download complete
  21797b0c5304: Download complete
  e71656c1717c: Verifying Checksum
  e71656c1717c: Download complete
  566b7efb9b31: Download complete
  c229119241af: Pull complete
  efca48bd61d1: Pull complete
  5667b96fd26a: Pull complete
  13131b8ccc34: Pull complete
  4f4fb700ef54: Pull complete
  21797b0c5304: Pull complete
  af0b02954a72: Pull complete
  e71656c1717c: Pull complete
  19d73456d4d1: Verifying Checksum
  19d73456d4d1: Download complete
  188fa3526e57: Verifying Checksum
  188fa3526e57: Download complete
  188fa3526e57: Pull complete
  566b7efb9b31: Pull complete
  19d73456d4d1: Pull complete
  Digest: sha256:af1401f8849cf34634cb010f8b0f1c2c6337b5ac811633b0fb21ee5d9c9465e3
  Status: Downloaded newer image for chriswyatt/ncbi_datasets:version2.1
  .command.sh: line 4: datasets: command not found

Work dir:
  /workspace/jcvi-nextflow/work/40/670bc8810326bfcaa1fbf978be46fd

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### Environment 

* Nextflow version: [version 22.04.5 build 5708] 
* Java version: [openjdk version "11.0.16" 2022-07-19 LTS]
* Operating system: [Linux,Gitpod]
* Bash version: (version 5.0.17(1)-release )

### Additional context

I have tried using singularity and get the same error. I also tried remaking the container with different USER rights etc.

**Comment by chriswyatt1** [comment]
The Dockerfile is as follows:


`FROM mambaorg/micromamba:0.22.0

# build and run as root users since micromamba image has 'mambauser' set as the $USER
USER root
# set workdir to default for building; set to /data at the end
WORKDIR /

# install dependencies; cleanup apt garbage
RUN apt-get update && apt install -y procps g++ && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

COPY conda.yml conda.here.yml

RUN micromamba install -y -n base -f conda.here.yml && \
    micromamba clean --all --yes
`

Maybe I have not built the container correctly to work within Nextflow

**Comment by pditommaso** [comment]
[This](https://github.com/mamba-org/micromamba-docker#advanced-usages) works

**Comment by mribeirodantas** [comment]
I assume you need the ENV in the Dockerfile, @chriswyatt1. That's how I managed to make it work in the training material for micromamba. You don't need that with nextflow-edge, though.

**Comment by chriswyatt1** [comment]
Awesome, thanks. Yes, with the ENV set in the Dockerfile it now works!! 
Cheers. I was using the old code from the nf training, which used to work fine. Glad you checked it out and updated it. I may add some click down comments in that section to explain line by the line the process (maybe this would be helpful)

**Comment by mribeirodantas** [comment]
Great idea! 😄
