### ISSUE TITLE
Inconsistent version number conversion

### ISSUE THREAD

**Issue by tcrespog** [nextflow-io/nextflow#3226]
### Expected behavior and actual behavior

Versions containing dashes (`-`), such as `22.09.4-edge`, end up being reported without the dashes (`22.09.4-edge` becomes `22.09.4.edge`)

### Steps to reproduce the problem

1. Run a pipeline `-with-tower` using a Nextflow `-edge` version.
2. The version that ends up being reported in a Tower run is wrong.

### Program output 

Screenshot of a run detail page in Tower.

![image](https://user-images.githubusercontent.com/10177888/191456855-eba34488-8386-4373-b8f4-1dcc4b9a3b29.png)
### Environment 

* Nextflow version: 22.09.4-edge

### Additional context

The root cause seems to be in the `VersionNumber` class. The [constructor](https://github.com/nextflow-io/nextflow/blob/807a816a5319d06002f13c64ec332aa10cf7ee33/modules/nf-commons/src/main/nextflow/util/VersionNumber.groovy#L42-L44) takes a string as an argument, but calling [`toString()`](https://github.com/nextflow-io/nextflow/blob/807a816a5319d06002f13c64ec332aa10cf7ee33/modules/nf-commons/src/main/nextflow/util/VersionNumber.groovy#L124-L126) may not always return the same string.
```groovy
final versionString = '22.09.04-edge'
assert new VersionNumber(versionString).toString() == versionString // <-- fails
```

**Comment by pditommaso** [comment]
Nice, solved. It should be addressed on Tower side too.
