### ISSUE TITLE
A top-level `bin` folder with hidden files (e.g. `.gitkeep`) results in failure on cloud based runs

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#3227]
### Steps to reproduce: 

1. Create a `bin` directory and add a `.gitkeep` file to instruct git to track it (example here https://github.com/abhi18av/hello/tree/empty-bin) 

2. Run the pipeline on S3 backed work-dir 
(Tested the expected behavior on Azure - which is working)

4. The pipeline fails to start with the following error 

```
Error executing process > 'sayHello (3)'

Caused by:
  Essential container in task exited

Command executed:

  echo 'Hello world!'

Command exit status:
  1

Command output:
  (empty)

Command error:
  chmod: /root/nextflow-bin/*: No such file or directory

Work dir:
  /fusion/s3/bucket/scratch/2BOnOd77jYxcoP/0e/e37d1f5c16cd6ffba31bf2f6b52d75


```

**Comment by jorgeaguileraseqera** [comment]
also, you can use 

```
shopt -s dotglob

change files

shopt -u dotglob
```

**Comment by abhi18av** [comment]
Ah, this is some advanced bash-fu Jorge! 😄

**Comment by pditommaso** [comment]
and it crashes!

**Comment by pditommaso** [comment]
I've patched, don't worry

**Comment by abhi18av** [comment]
<img src="https://media4.giphy.com/media/rBF5LgLnwrF0zCTRUr/giphy-downsized-medium.gif"/>
