### ISSUE TITLE
Stalled Nextflow Execution

### ISSUE THREAD

**Issue by bensesbg** [nextflow-io/nextflow#3241]
Greetings,

While attempting to process some data via the [Nextflow CHIPSEQ workflow](https://github.com/nf-core/chipseq) recently, the Nextflow execution appears to become stalled at a specific point in a deterministic fashion (i.e. re-runs do not solve the issue). The data was originally processed via Nextflow v22.04.4 and seemed to have become stalled at the very end of the execution after all processing had been completed. The stdout.log file for the v22.04.4 run is attached to the ticket (please note that it only represents an excerpt of the first and last 1000 lines from the comprehensive log file).

As per guidance provided in https://github.com/nextflow-io/nextflow/issues/2849, Nextflow was upgraded to v22.08.2-edge in order to attempt to resolve the issue. However, this seemed to cause the execution to stall earlier in the pipeline at the Trimgalore step. Nextflow was then upgraded to v22.09.4-edge, but the execution again became stalled at the same Trimgalore step. The std.out.log and .nextflow.log files for the v22.09.4-edge run are attached, as well as the std.out.log file for the v22.08.2-edge run.

Could you please assist in resolving the issue? Any help you can provide would be very much appreciated.

[CHIP_v1-22.04.4.stdout.log](https://github.com/nextflow-io/nextflow/files/9636397/CHIP_v1-22.04.4.stdout.log)
[CHIP_v1-22.08.2-edge.stdout.log](https://github.com/nextflow-io/nextflow/files/9636407/CHIP_v1-22.08.2-edge.stdout.log)
[CHIP_v1-22.09.4-edge.stdout.log](https://github.com/nextflow-io/nextflow/files/9636410/CHIP_v1-22.09.4-edge.stdout.log)
[CHIP_v1-22.09.4-edge.nextflow.log](https://github.com/nextflow-io/nextflow/files/9636413/CHIP_v1-22.09.4-edge.nextflow.log)

**Comment by pditommaso** [comment]
Sorry, but this should be reported in the [nf-core/chipseq](https://github.com/nf-core/chipseq) repository
