### ISSUE TITLE
Allow authentication to weblog endpoint

### ISSUE THREAD

**Issue by seandavi** [nextflow-io/nextflow#3242]
## New feature

In a cloud environment, there is a need to secure URLs. While one way of doing this is to simply use a VPC, another is to support simple authentication via bearer token, basic auth in a header. 

## Usage scenario 

See above.

## Suggest implementation 

Adding a "header" component in the weblog config block that nextflow includes in the post would address most basic use cases of securing the web endpoint.

**Comment by bentsherman** [comment]
Duplicate of #3198
