### ISSUE TITLE
Azure metadata tags (resource labels) propagation for child jobs

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nextflow#3248]
## New feature

With the recent improvements to resource labelling https://github.com/nextflow-io/nextflow/commit/d64eeffcb0b4c7d2d2773f0492fff15e05399e21  and https://github.com/nextflow-io/nextflow/pull/2853 , it'd be great if the child jobs can be tagged on Azure Batch executor as well.

## Usage scenario 

When submitting jobs to Azure Batch with Nextflow, the tags provided as the process level should be propagated to the generated job definitions.

## Suggest implementation 

We would need to implement the current labelling mechanism within the AzBatchService, by (probably) enhancing the [createPool](https://github.com/nextflow-io/nextflow/blob/master/plugins/nf-azure/src/main/nextflow/cloud/azure/batch/AzBatchService.groovy#L616) implementation. 

The metadata tags would show up at the job metadata menu on the portal

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/12799326/192487949-a84f5769-2e79-473d-b227-03b20e5785a1.png">

**Comment by Takadonet** [comment]
Propagation tags to child resources will allow for cost tracking. Our need is to trace back all cost associated by group, project and individuals which tags enable.

**Comment by pditommaso** [comment]
This should be a quick win. tagging @bentsherman

**Comment by bentsherman** [comment]
Looking at `AzBatchService.getOrCreatePool()`, it looks like Nextflow tries to create a new pool only if an identical one doesn't already exist. So if different resource labels are specified for different processes, Nextflow should create a different pool for each one. Does that mean we need to insert the resource labels as metadata in the `AzVmPoolSpec` class, during `specFromPoolConfig` and `specFromAutoPool` ?

**Comment by abhi18av** [comment]
Judging from the [codebase of `JobOperations` ](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/batch/microsoft-azure-batch/src/main/java/com/microsoft/azure/batch/JobOperations.java) perhaps we should explore tagging at the job level itself and therefore, whichever pool the job gets allocated it would have that metadata 🤔

**Comment by Takadonet** [comment]
Will job level tagging appear in the Cost analysis page for the subscription? Do not believe so. If so, that would be very fine grain knowledge which be awesome.

**Comment by pditommaso** [comment]
I'm wondering if the concept of *metadata* in Azure is the same as tags in AWS ?

**Comment by vsmalladi** [comment]
@abhi18av will take a look at this issue today.

**Comment by abhi18av** [comment]
Thanks mate - happy to collaborate via Nextflow slack.
