### ISSUE TITLE
Nextflow does not support full-open ranges

### ISSUE THREAD

**Issue by Midnighter** [nextflow-io/nextflow#3255]
### Expected behavior and actual behavior

The [Groovy language](https://docs.groovy-lang.org/docs/latest/html/documentation/#Collections-Ranges) allows full-open range notations like `x<..<y`. However, using this in nextflow causes a script compilation error.

### Steps to reproduce the problem

```nextflow
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

workflow {
    def numbers = (1..20).toList()

    println numbers[4<..<6]
}
```

### Program output 

```
N E X T F L O W  ~  version 22.04.5
Launching `main.nf` [ecstatic_boyd] DSL2 - revision: b2660d3ba5
Script compilation error
- file : /home/moritz/Codebase/Sandbox/nf-ranges/main.nf
- cause: Unexpected input: '{' @ line 5, column 10.
   workflow {
            ^

1 error
```

### Environment 

* Nextflow version: 22.04.5
* Java version: openjdk version "11.0.16" 2022-07-19
* Operating system: Linux
* Bash version: GNU bash, version 5.0.17(1)-release

**Comment by Midnighter** [comment]
[.nextflow.log](https://github.com/nextflow-io/nextflow/files/9682464/default.nextflow.log)

**Comment by jorgeaguileraseqera** [comment]
If I'm not wrong open range is a new feature in Groovy 4.x but (by the moment) Nextflow is using Groovy 3.x

**Comment by Midnighter** [comment]
You're right, feature is not documented here https://docs.groovy-lang.org/docs/groovy-3.0.13/html/documentation/#Collections-Ranges
