### ISSUE TITLE
Nextflow cluster scheduler poll rate

### ISSUE THREAD

**Issue by lucidv01d** [nextflow-io/nextflow#326]
How often does nextflow poll the scheduler in a cluster environment?

We're having issues with lockups and my sysadmin is asking me this question, though we don't think nextflow is the culprit.

**Comment by pditommaso** [comment]
One minute. See [queueStatInternal](https://www.nextflow.io/docs/latest/config.html#scope-executor).

**Comment by pditommaso** [comment]
I guess this answered the question. I'm closing the issue.
