### ISSUE TITLE
Catch error: Offline, missing plugin

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#3270]
Originally reported by @aubinthomas, running a pipeline offline with the smaller Nextflow binary threw this error:

```
Launching `workflow/main.nf` [cranky_majorana] DSL1 - revision: 39c073c68c
Class definition not found: com/upplication/s3fs/S3FileSystemProvider
```

This was resolved by downloading the Nextflow `*-all` binary that includes the plugins.

It would be great if Nextflow could catch this kind of error and give a nicer error message explaining what's going wrong.

**Comment by ewels** [comment]
Still valid

**Comment by bentsherman** [comment]
I wrote up a quick PR, but now I think I need some more context. The `-offline` option doesn't actually prevent plugins from being installed, so for the plugin to not be installed, you would have to pin the plugin version.

@aubinthomas can you share more details about how you ran your pipeline offline? Did you have any plugin versions pinned in your config file?
