### ISSUE TITLE
unavailable GPU accelerator for google batch

### ISSUE THREAD

**Issue by mizue31g** [nextflow-io/nextflow#3273]
Looking at [3056](https://github.com/nextflow-io/nextflow/pull/3056) it looks like Google batch GPU support feature has been added. However, GPU can not available yet in Nextflow with Google batch. (Nextflow version: 22.09.7-edge)
Assuming the cause is that the [InstancePolicy and InstancePolicyOrTemplate](https://cloud.google.com/batch/docs/reference/rpc/google.cloud.batch.v1#instancepolicy) are required to use GPUs in Google batch but they have not been implemented yet.
Is the above assumption correct? If yes, do you have any plans to support it?

**Comment by bentsherman** [comment]
Hi @mizue31g , Nextflow does use an InstancePolicy when implementing a job request with GPUs, it is the only way to do it: https://github.com/nextflow-io/nextflow/blob/58f4360abb5133d551efa0ced82f15de9669b540/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L155-L180

So I don't understand your issue. Are you saying that you tried to use google batch with GPUs and it didn't work?

**Comment by mizue31g** [comment]
Hi @bentsherman , Thank you. Yes, I tried to use google batch with GPUs and simple scripts but it didn't work. 
I tried Google Life Sciences as well and it worked fine.
The following is the execution result and configs of google batch, but it seems that the clear cause is not included.

$ nextflow script.nf -c script.config
N E X T F L O W  ~  version 22.09.7-edge
Launching `script.nf` [sleepy_roentgen] DSL2 - revision: 566fbe77b6
Downloading plugin nf-google@1.4.4
executor >  google-batch (1)
[68/e10f82] process > PARABRICKS [100%] 1 of 1, failed: 1 ✘
Error executing process > 'PARABRICKS'

Caused by:
  Process `PARABRICKS` terminated with an error exit status (null)

Command executed:

  pwd
  nvidia-smi

Command exit status:
  null

Command output:
  (empty)

Work dir:
  gs://hcls-jp1-nextflow-uc1/scratch/68/e10f82e19694482be70f60b55b9567

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

$ cat script.nf
#!/usr/bin/env nextflow
process PARABRICKS {
    container 'nvcr.io/nvidia/clara/clara-parabricks:4.0.0-1'
    machineType 'n1-standard-4'
    accelerator 1, type: "nvidia-tesla-t4"
    containerOptions "--gpus all"

    """
    pwd
    nvidia-smi
    """
}
workflow {
    PARABRICKS()
}


$ cat script.config
process.executor = 'google-batch'
workDir = 'gs://hcls-jp1-nextflow-uc1/scratch'
google.project = 'hcls-jp1'
google.location = 'us-central1'
google.batch.network = 'global/networks/default'
google.batch.subnetwork = 'regions/us-central1/subnetworks/default-uc1'

Any advice?

**Comment by pditommaso** [comment]
Can you please include the `.nextflow.log` file?

**Comment by mizue31g** [comment]
Here is .nextflow.log file.

$ cat .nextflow.log
Oct-09 00:10:50.920 [main] DEBUG nextflow.cli.Launcher - $> nextflow script.nf -c script.config -resume
Oct-09 00:10:51.016 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.09.7-edge
Oct-09 00:10:51.044 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/mizue31/.nextflow/plugins; core-plugins: nf-amazon@1.10.7,nf-azure@0.14.2,nf-codecommit@0.1.2,nf-console@1.0.4,nf-ga4gh@1.0.4,nf-google@1.4.4,nf-tower@1.5.4,nf-wave@0.4.4
Oct-09 00:10:51.058 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Oct-09 00:10:51.059 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Oct-09 00:10:51.065 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Oct-09 00:10:51.079 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Oct-09 00:10:51.106 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /home/mizue31/Nextflow/gpu/script.config
Oct-09 00:10:51.107 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/mizue31/Nextflow/gpu/script.config
Oct-09 00:10:51.147 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Oct-09 00:10:51.917 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Oct-09 00:10:51.938 [main] INFO  nextflow.cli.CmdRun - Launching `script.nf` [furious_wright] DSL2 - revision: 51362394dc
Oct-09 00:10:51.939 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[nf-google@1.4.4]
Oct-09 00:10:51.940 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[nf-google@1.4.4]
Oct-09 00:10:51.940 [main] DEBUG nextflow.plugin.PluginUpdater - Installing plugin nf-google version: 1.4.4
Oct-09 00:10:51.959 [main] INFO  org.pf4j.AbstractPluginManager - Plugin 'nf-google@1.4.4' resolved
Oct-09 00:10:51.959 [main] INFO  org.pf4j.AbstractPluginManager - Start plugin 'nf-google@1.4.4'
Oct-09 00:10:52.005 [main] DEBUG nextflow.plugin.BasePlugin - Plugin started nf-google@1.4.4
Oct-09 00:10:52.117 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /home/mizue31/.nextflow/secrets/store.json
Oct-09 00:10:52.133 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@6ae62c7e] - activable => nextflow.secret.LocalSecretsProvider@6ae62c7e
Oct-09 00:10:52.237 [main] DEBUG nextflow.Session - Session UUID: 46828f0f-bfd3-45dd-b565-d96eebf4be14
Oct-09 00:10:52.237 [main] DEBUG nextflow.Session - Run name: furious_wright
Oct-09 00:10:52.238 [main] DEBUG nextflow.Session - Executor pool size: 2
Oct-09 00:10:52.438 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=10; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Oct-09 00:10:52.475 [main] DEBUG nextflow.cli.CmdRun -
  Version: 22.09.7-edge build 5806
  Created: 28-09-2022 09:36 UTC
  System: Linux 5.10.133+
  Runtime: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 11.0.16+8-post-Debian-1deb11u1
  Encoding: UTF-8 (UTF-8)
  Process: 2757@cs-460554858693-default [172.17.0.4]
  CPUs: 1 - Mem: 15.6 GB (15.2 GB) - Swap: 0 (0)
Oct-09 00:10:52.516 [main] DEBUG nextflow.file.FileHelper - Can't check if specified path is NFS (1): gs://hcls-jp1-nextflow-uc1/scratch

Oct-09 00:10:52.517 [main] DEBUG nextflow.Session - Work-dir: gs://hcls-jp1-nextflow-uc1/scratch [null]
Oct-09 00:10:52.517 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/mizue31/Nextflow/gpu/bin
Oct-09 00:10:52.545 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[GoogleLifeSciencesExecutor, GoogleBatchExecutor]
Oct-09 00:10:52.561 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Oct-09 00:10:52.581 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Oct-09 00:10:52.593 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 2; maxThreads: 1000
Oct-09 00:10:52.808 [main] DEBUG nextflow.Session - Session start
Oct-09 00:10:53.054 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Oct-09 00:10:53.119 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: google-batch
Oct-09 00:10:53.120 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'google-batch'
Oct-09 00:10:53.122 [main] DEBUG nextflow.executor.Executor - [warm up] executor > google-batch
Oct-09 00:10:53.132 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'google-batch' > capacity: 1000; pollInterval: 10s; dumpInterval: 5m
Oct-09 00:10:53.153 [main] DEBUG nextflow.cloud.google.GoogleOpts - Google auth via application DEFAULT
Oct-09 00:10:53.156 [main] DEBUG n.c.google.batch.GoogleBatchExecutor - [GOOGLE BATCH] Executor config=BatchConfig[googleOpts=GoogleOpts(projectId:hcls-jp1, credsFile:null, location:us-central1, enableRequesterPaysBuckets:false, credentials:ComputeEngineCredentials{transportFactoryClassName=com.google.auth.oauth2.OAuth2Utils$DefaultHttpTransportFactory})
Oct-09 00:10:53.194 [main] DEBUG n.c.google.batch.client.BatchClient - [GOOGLE BATCH] Creating service client with config credentials
Oct-09 00:10:53.973 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: PARABRICKS
Oct-09 00:10:53.973 [main] DEBUG nextflow.Session - Igniting dataflow network (1)
Oct-09 00:10:53.974 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > PARABRICKS
Oct-09 00:10:53.975 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination
Oct-09 00:10:53.975 [main] DEBUG nextflow.Session - Session await
Oct-09 00:11:01.063 [Task submitter] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] submitted > job=nf-4fef40e1-1665274257359; uid=j-4aefd330-bd09-480b-8c3a-5015a66f1ac5; work-dir=gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79
Oct-09 00:11:01.063 [Task submitter] INFO  nextflow.Session - [4f/ef40e1] Submitted process > PARABRICKS
Oct-09 00:16:03.179 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor google-batch > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: PARABRICKS; status: SUBMITTED; exit: -; error: -; workDir: gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79]
Oct-09 00:21:03.189 [Task monitor] DEBUG n.processor.TaskPollingMonitor - !! executor google-batch > tasks to be completed: 1 -- submitted tasks are shown below
~> TaskHandler[id: 1; name: PARABRICKS; status: SUBMITTED; exit: -; error: -; workDir: gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79]
Oct-09 00:24:03.379 [Task monitor] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Terminated job=nf-4fef40e1-1665274257359; state=FAILED
Oct-09 00:24:04.335 [Task monitor] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Cannot read exitstatus for task: `PARABRICKS` | gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79/.exitcode
Oct-09 00:24:05.974 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: PARABRICKS; status: COMPLETED; exit: null; error: -; workDir: gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79]
Oct-09 00:24:06.166 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79/.command.out
Oct-09 00:24:06.923 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79/.command.err
Oct-09 00:24:07.121 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79/.command.log
Oct-09 00:24:07.124 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'PARABRICKS'

Caused by:
  Process `PARABRICKS` terminated with an error exit status (null)

Command executed:

  pwd

Command exit status:
  null

Command output:
  (empty)

Work dir:
  gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Oct-09 00:24:07.136 [main] DEBUG nextflow.Session - Session await > all processes finished
Oct-09 00:24:07.828 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `PARABRICKS` terminated with an error exit status (null)
Oct-09 00:24:08.146 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79/.command.err
Oct-09 00:24:08.768 [Task monitor] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79/.command.out
Oct-09 00:24:08.770 [main] DEBUG nextflow.Session - Session await > all barriers passed
Oct-09 00:24:09.051 [main] DEBUG nextflow.processor.TaskRun - Unable to dump error of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79/.command.err
Oct-09 00:24:09.722 [main] DEBUG nextflow.processor.TaskRun - Unable to dump output of process 'null' -- Cause: java.nio.file.NoSuchFileException: gs://hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79/.command.out
Oct-09 00:24:09.728 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=10.4s; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=4; peakMemory=15 GB; ]
Oct-09 00:24:09.743 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Oct-09 00:24:09.743 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-google@1.4.4'
Oct-09 00:24:09.743 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-google
Oct-09 00:24:09.757 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

**Comment by pditommaso** [comment]
Unfortunately, there's no much more info. Can you check the Google Batch console if there's some error message related to the job `nf-4fef40e1-1665274257359` ?

**Comment by mizue31g** [comment]
Here is the job description of nf-4fef40e1-1665274257359.

$ gcloud beta batch jobs describe nf-4fef40e1-1665274257359 --location us-central1
allocationPolicy:
  instances:
  - policy:
      accelerators:
      - count: '1'
        type: nvidia-tesla-t4
      machineType: n1-standard-4
  labels:
    goog-batch-job-id: nf-4fef40e1-1665274257359
  location:
    allowedLocations:
    - regions/us-central1
    - zones/us-central1-a
    - zones/us-central1-b
    - zones/us-central1-c
    - zones/us-central1-f
  network:
    networkInterfaces:
    - network: global/networks/default
      subnetwork: regions/us-central1/subnetworks/default-uc1
  serviceAccount:
    email: 955157136126-compute@developer.gserviceaccount.com
createTime: '2022-10-09T00:11:00.891269252Z'
logsPolicy:
  destination: CLOUD_LOGGING
name: projects/hcls-jp1/locations/us-central1/jobs/nf-4fef40e1-1665274257359
status:
  runDuration: 0s
  state: FAILED
  statusEvents:
  - description: Job state is set from QUEUED to SCHEDULED for job projects/955157136126/locations/us-central1/jobs/nf-4fef40e1-1665274257359.
    eventTime: '2022-10-09T00:11:03.841895962Z'
    type: STATUS_CHANGED
  - description: No VM has agent reporting correctly within the time window 600 seconds.
      VM state for instance j-4aefd330-bd09-480b-8c3a-5015a66f1ac5-group0-0-m4gm is
      2022/10/09-00:12:15+0000,agent,start.
    eventTime: '2022-10-09T00:23:09.803670278Z'
    type: OPERATIONAL_INFO
  - description: Job state is set from SCHEDULED to SCHEDULED_PENDING_FAILED for job
      projects/955157136126/locations/us-central1/jobs/nf-4fef40e1-1665274257359.
    eventTime: '2022-10-09T00:23:09.829385800Z'
    type: STATUS_CHANGED
  - description: Job state is set from SCHEDULED_PENDING_FAILED to FAILED for job
      projects/955157136126/locations/us-central1/jobs/nf-4fef40e1-1665274257359.
    eventTime: '2022-10-09T00:23:56.645191898Z'
    type: STATUS_CHANGED
taskGroups:
- name: projects/955157136126/locations/us-central1/jobs/nf-4fef40e1-1665274257359/taskGroups/group0
  parallelism: '1'
  taskCount: '1'
  taskSpec:
    computeResource:
      cpuMilli: '4000'
      memoryMib: '15360'
    runnables:
    - container:
        commands:
        - /bin/bash
        - -o
        - pipefail
        - -c
        - trap "{ cp .command.log /mnt/disks/hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79/.command.log;
          }" ERR; /bin/bash /mnt/disks/hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79/.command.run
          2>&1 | tee .command.log
        imageUri: nvcr.io/nvidia/clara/clara-parabricks:4.0.0-1
        options: --gpus all
        volumes:
        - /mnt/disks/hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79:/mnt/disks/hcls-jp1-nextflow-uc1/scratch/4f/ef40e1c178e1d123f3c6e320066d79:rw
    volumes:
    - gcs:
        remotePath: hcls-jp1-nextflow-uc1
      mountOptions:
      - -o rw,allow_other
      - -implicit-dirs
      mountPath: /mnt/disks/hcls-jp1-nextflow-uc1
uid: j-4aefd330-bd09-480b-8c3a-5015a66f1ac5
updateTime: '2022-10-09T00:23:56.645191898Z'

**Comment by mizue31g** [comment]
Let me share an update. 
I found that I needed to add the batch.states.report permission to the service account, so I gave that Compute Engine Default service account the Editor role. (I understand this is not optimal). And when I ran the same nextflow command, I got an error that the GPU driver could not be selected.
`could not select device driver "" with capabilities: [[gpu]]. `

```
$ ../nextflow script.nf -c script.config
N E X T F L O W  ~  version 22.09.7-edge
Launching `script.nf` [elated_mcclintock] DSL2 - revision: 51362394dc
executor >  google-batch (1)
[85/b5ceeb] process > PARABRICKS [  0%] 0 of 1
Error executing process > 'PARABRICKS'

Caused by:
  Process `PARABRICKS` terminated with an error exit status (null)

Command executed:

  pwd

Command exit status:
  null

Command output:
  4.0.0-1: Pulling from nvidia/clara/clara-parabricks
  d7bfe07ed847: Pulling fs layer
  bbbbd451a669: Pulling fs layer
  773163705c35: Pulling fs layer
  d6949fcf1aef: Pulling fs layer
  3eb73064088b: Pulling fs layer
executor >  google-batch (1)
[85/b5ceeb] process > PARABRICKS [100%] 1 of 1, failed: 1 ✘
Error executing process > 'PARABRICKS'

Caused by:
  Process `PARABRICKS` terminated with an error exit status (null)

Command executed:

  pwd

Command exit status:
  null

Command output:
  4.0.0-1: Pulling from nvidia/clara/clara-parabricks
  d7bfe07ed847: Pulling fs layer
  bbbbd451a669: Pulling fs layer
  773163705c35: Pulling fs layer
  d6949fcf1aef: Pulling fs layer
  3eb73064088b: Pulling fs layer
executor >  google-batch (1)
[85/b5ceeb] process > PARABRICKS [100%] 1 of 1, failed: 1 ✘
Error executing process > 'PARABRICKS'

Caused by:
  Process `PARABRICKS` terminated with an error exit status (null)

Command executed:

  pwd

Command exit status:
  null

Command output:
  4.0.0-1: Pulling from nvidia/clara/clara-parabricks
  d7bfe07ed847: Pulling fs layer
  bbbbd451a669: Pulling fs layer
  773163705c35: Pulling fs layer
  d6949fcf1aef: Pulling fs layer
  3eb73064088b: Pulling fs layer
  a3ac3ab0ee35: Pulling fs layer
  8d88682a5e1d: Pulling fs layer
  d6949fcf1aef: Waiting
  3eb73064088b: Waiting
  a3ac3ab0ee35: Waiting
  8d88682a5e1d: Waiting
  bbbbd451a669: Verifying Checksum
  bbbbd451a669: Download complete
  773163705c35: Verifying Checksum
  773163705c35: Download complete
  d7bfe07ed847: Verifying Checksum
  d7bfe07ed847: Download complete
  d6949fcf1aef: Verifying Checksum
  d6949fcf1aef: Download complete
  3eb73064088b: Verifying Checksum
  3eb73064088b: Download complete
  8d88682a5e1d: Verifying Checksum
  8d88682a5e1d: Download complete
  d7bfe07ed847: Pull complete
  bbbbd451a669: Pull complete
  773163705c35: Pull complete
  d6949fcf1aef: Pull complete
  3eb73064088b: Pull complete
  a3ac3ab0ee35: Verifying Checksum
  a3ac3ab0ee35: Download complete
  a3ac3ab0ee35: Pull complete
  8d88682a5e1d: Pull complete
  Digest: sha256:0170beef24131a23bb63bc36ec059e493df1f04a4a78f9d2c5df9bce1d5d9a35
  Status: Downloaded newer image for nvcr.io/nvidia/clara/clara-parabricks:4.0.0-1
  nvcr.io/nvidia/clara/clara-parabricks:4.0.0-1

Command error:
  docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

Work dir:
  gs://hcls-jp1-nextflow-uc1/scratch/85/b5ceebc6e07cb850eb611cf808bf7e

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

**Comment by mizue31g** [comment]
As I see [the doc](https://cloud.google.com/batch/docs/create-run-job#api_3),  the **installGpuDrivers** field seems to be required. Google batch recently added features to support GPUs. If possible, could you please check with the Google Batch team?

**Comment by hillstub** [comment]
I'm running into the same issue with the same error:
```
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

**Comment by pditommaso** [comment]
tagging @hnawar in the case he has any advice GPU settings with Google Batch

**Comment by bentsherman** [comment]
@hnawar It looks like the `installGpuDrivers` option is available in the REST API: https://cloud.google.com/batch/docs/reference/rest/v1/projects.locations.jobs#instancepolicyortemplate

But not the Java SDK: https://cloud.google.com/java/docs/reference/google-cloud-batch/latest/com.google.cloud.batch.v1.AllocationPolicy.InstancePolicyOrTemplate

Without this option, I don't think Nextflow tasks will be able to use GPUs, because the GPU drivers need to be installed on the VM, and Google Batch (afaik) doesn't let you specify the VM image.
