### ISSUE TITLE
Unable to find java installation

### ISSUE THREAD

**Issue by Michael-Geuenich** [nextflow-io/nextflow#3278]
### Expected behavior and actual behavior

Install nextflow

### Steps to reproduce the problem

I've tried downloading and installing via `curl -s https://get.nextflow.io | bash` as well as through conda. I always end up with the following error:

```
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /bin/java
 NXF_OPTS:
```

### Environment 

I am an a mac M1 and just installed java using homebrew.
```
~ java -version
openjdk version "19" 2022-09-20
OpenJDK Runtime Environment Homebrew (build 19)
OpenJDK 64-Bit Server VM Homebrew (build 19, mixed mode, sharing)

~ which java
/opt/homebrew/opt/openjdk/bin/java

macOS Monterey version 12.0.1

~ $SHELL --version
zsh 5.8 (x86_64-apple-darwin21.0)
```

### Additional context

I've tried setting the `NXF_JAVA_HOME`, `NXF_JAVA_CMD` and `JAVA_CMD` in both my `.bashrc` and `.zshrc` files in different combinations (i.e. first NXF_JAVA_HOME, then NXF_JAVA_HOME and NXF_JAVA_CMD and then all three) as follows:

```
export NXF_JAVA_HOME=/opt/homebrew/opt/openjdk/bin/java
export NXF_JAVA_CMD=/opt/homebrew/opt/openjdk/bin/java
export JAVA_CMD=/opt/homebrew/opt/openjdk/bin/java
```

I sourced both files/reloaded my shell after each time I set a new variable.

I then try to install nextflow using `curl -s https://get.nextflow.io | bash`. I've also saved the script as follows `curl -s https://get.nextflow.io > install_nextflow.sh` and then ran it using `./install_nextflow.sh`, same issue everywhere. Finally, I also tried creating a new conda environment and installing there. The installation completes, but then I get the same error when running `nextflow run hello`.

**Comment by tomouellette** [comment]
Hi Michael,

I faced similar issues when I originally installed nextflow on a mac OS. I resolved it as follows:

```
JAVA_CMD=/Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home/bin/java

wget -qO- https://get.nextflow.io \
    export JAVA_CMD=$JAVA_CMD | \
    bash

chmod +x nextflow
./nextflow
```

Note the placement of the `export` command. Just replace the JAVA_CMD path with your computer's path. If calling `./nextflow` still fails, then it's likely the PATH you're providing to openjdk is an older version (make sure it's valid e.g. 11). The original openjdk path I was providing was actually an earlier version, changing the path to an updated version resolved this issue.

**Comment by Gat2018** [comment]
I also resolved for Mac  M2 with the following.....

#Create environment variable to fit your java environment (dk-21.jdk in my cases)
export JAVA_CMD=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home

#Save changes to terminal profile
source ~/.zshrc (for Mac) or  ~/.bashrc for Linux terminal

#Give permission to nextflow (+x or 777 to be executable )
chmod  +x  nextflow

#Execute nextflow
  ./nextflow 

#Output
Usage: nextflow [options] COMMAND [arg...]

Options:
  -C
     Use the specified configuration file(s) overriding any defaults
  -D
     Set JVM properties
  -bg
     Execute nextflow in background
  -c, -config
     Add the specified file to configuration set
  -config-ignore-includes
     Disable the parsing of config includes
  -h
     Print this help
  -log
     Set nextflow log file path
  -q, -quiet
     Do not print information messages
  -remote-debug
     Enable JVM interactive remote debugging (experimental)
  -syslog
     Send logs to syslog server (eg. localhost:514)
  -trace
     Enable trace level logging for the specified package name - multiple packages can be provided separating them with a comma e.g. '-trace nextflow,io.seqera'
  -v, -version
     Print the program version

Commands:
  clean         Clean up project cache and work directories
  clone         Clone a project into a folder
  config        Print a project configuration
  console       Launch Nextflow interactive console
  drop          Delete the local copy of a project
  help          Print the usage help for a command
  info          Print project and system runtime information
  inspect       Inspect process settings in a pipeline project
  kuberun       Execute a workflow in a Kubernetes cluster (experimental)
  list          List all downloaded projects
  log           Print executions log and runtime info
  plugin        Execute plugin-specific commands
  plugins       Execute plugin-specific commands
  pull          Download or update a project
  run           Execute a pipeline project
  secrets       Manage pipeline secrets (preview)
  self-update   Update nextflow runtime to the latest available version
  view          View project script file(s)

**Comment by mikemc** [comment]
I solved this issue by running 

```
sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
```

as recommended in the output of `brew info java`
