### ISSUE TITLE
Version 22.09.7-edge does not create conda environments

### ISSUE THREAD

**Issue by JoseEspinosa** [nextflow-io/nextflow#3282]
### Expected behavior and actual behavior

Version 22.09.7-edge does not create conda environments

### Steps to reproduce the problem

```nextflow
#!/usr/bin/env nextflow

nextflow.enable.dsl=2

process foo {
    conda "conda-forge::sed=4.7"
    output:
    path '*.txt'

    script:
    """
    touch test.txt
    """
}

workflow {
    foo()
}
```

`NXF_VER=22.04.5 nextflow run main.nf`
`NXF_VER=22.09.7-edge nextflow run main.nf`

### Program output 

A stable release creates the environment:
```
$ NXF_VER=22.04.5 nextflow run main.nf 
N E X T F L O W  ~  version 22.04.5
Launching `main.nf` [evil_colden] DSL2 - revision: ff86817f5c
[-        ] process > foo -
Creating env using conda: conda-forge::sed=4.7 [cache /home/foo/nxf_scratch/conda/env-e9df3e1229ffdcc8b4b9e48f04ba2d94]
```

While the last edge does not:
```
$ NXF_VER=22.09.7-edge nextflow run main.nf 
N E X T F L O W  ~  version 22.09.7-edge
Launching `main.nf` [sick_tuckerman] DSL2 - revision: ff86817f5c
executor >  local (1)
[cb/db2ff4] process > foo [100%] 1 of 1 ✔
```
### Environment 

* Nextflow version:  `22.09.7-edge`
* Java version: `java version "17.0.1" 2021-10-19 LTS`
* Operating system: `Ubuntu 18.04.6 LTS`
* Bash version: `GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)`

**Comment by JoseEspinosa** [comment]
Just discussed the issue above with @pditommaso and this is a new feature, seems like from now on `conda` will need to be enabled. So I close this issue.

**Comment by pditommaso** [comment]
See https://github.com/nextflow-io/nextflow/pull/3073

**Comment by chasemc** [comment]
Thanks for documenting this. It bit me for few minutes today after updating

**Comment by miguelbiron** [comment]
Hi! I'm very new to nextflow and I cannot figure out where in the config file to put `conda.enabled = true`. Could you point me to an example config that includes this line?
