### ISSUE TITLE
k8s namespace from .config is broken  in 22.10.0

### ISSUE THREAD

**Issue by courcelm** [nextflow-io/nextflow#3289]
## Bug report 

Nextflow doesn't use the provided namespace from .config file.

It now outputs the following warning:

WARN: K8s namespace provided in the nextflow configuration does not match with pod namespace.

### Expected behavior and actual behavior

Use the namespace specified in the .config

### Steps to reproduce the problem

Create two namespaces (A and B)

Run nextflow from namespace A with a config file requesting the creation of a pod in B.

Here is my profile from my nextflow.config:

    k8s {

        executor {
            queueSize = 75
        }

        process {
            executor = 'k8s'
            scratch = true
        }

        k8s {
           namespace = "$NEXTFLOW_NAMESPACE"
           pod = [[imagePullSecret: "$PULL_SECRET"]]
           serviceAccount = "$NEXTFLOW_SERVICE_ACCOUNT"
           storageClaimName = "$NEXTFLOW_PVC"
           storageMountPath = '/mnt/nextflow'
        }
    }

### Program output 

WARN: K8s namespace provided in the nextflow configuration does not match with pod namespace
--
Thu, Oct 13 2022 1:55:55 pm | Error executing process > 'predict (3)'
Thu, Oct 13 2022 1:55:55 pm |  
Thu, Oct 13 2022 1:55:55 pm | Caused by:
Thu, Oct 13 2022 1:55:55 pm | Request POST /api/v1/namespaces/production/pods returned an error code=403
Thu, Oct 13 2022 1:55:55 pm |  
Thu, Oct 13 2022 1:55:55 pm | {
Thu, Oct 13 2022 1:55:55 pm | "kind": "Status",
Thu, Oct 13 2022 1:55:55 pm | "apiVersion": "v1",
Thu, Oct 13 2022 1:55:55 pm | "metadata": {
Thu, Oct 13 2022 1:55:55 pm |  
Thu, Oct 13 2022 1:55:55 pm | },
Thu, Oct 13 2022 1:55:55 pm | "status": "Failure",
Thu, Oct 13 2022 1:55:55 pm | "message": "pods is forbidden: User \"system:serviceaccount:production:worker-serviceaccount\" cannot create resource \"pods\" in API group \"\" in the namespace \"production\"",
Thu, Oct 13 2022 1:55:55 pm | "reason": "Forbidden",
Thu, Oct 13 2022 1:55:55 pm | "details": {
Thu, Oct 13 2022 1:55:55 pm | "kind": "pods"
Thu, Oct 13 2022 1:55:55 pm | },
Thu, Oct 13 2022 1:55:55 pm | "code": 403
Thu, Oct 13 2022 1:55:55 pm | }

### Environment 

* Nextflow version: 22.10.0
* Java version: [?]
* Operating system: [macOS, Linux, etc]
* Bash version: (use the command `$SHELL --version`)

### Additional context

(Add any other context about the problem here)

**Comment by courcelm** [comment]
It is related to this commit:
https://github.com/nextflow-io/nextflow/commit/c3364d0f1911963a6f2e468e1704e0e80d843c31


`    protected ClientConfig fromCluster(Map<String,String> env, String cfgNamespace, String serviceAccount) {

        // See https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod

        final host = env.get('KUBERNETES_SERVICE_HOST')
        final port = env.get('KUBERNETES_SERVICE_PORT')
        final server = host + ( port ? ":$port" : '' )

        final cert = path('/var/run/secrets/kubernetes.io/serviceaccount/ca.crt').bytes
        final token = path('/var/run/secrets/kubernetes.io/serviceaccount/token').text
        final namespace = path('/var/run/secrets/kubernetes.io/serviceaccount/namespace').text

        if( namespace && namespace != cfgNamespace )
            log.warn ("K8s namespace provided in the nextflow configuration does not match with pod namespace")

        new ClientConfig( server: server, token: token, namespace: namespace, serviceAccount: serviceAccount, sslCert: cert, isFromCluster: true )
    }`


There is a warning but it doesn't use cfgNamespace.

**Comment by pditommaso** [comment]
Interesting point. should it be allowed the use of a namespace different from the one defined by the pod?

**Comment by courcelm** [comment]
I find that running Nextflow workloads in a different namespace than my primary application is convenient. It allows setting limits for CPU and memory resources at the namespace level for all my concurrent workloads (https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/).

**Comment by pditommaso** [comment]
Yes, you are right. It looks like it does not make much sense that check that was added.

**Comment by pditommaso** [comment]
Solved by 059183f24e613790378fddee3c0e6c283fbabfed
