### ISSUE TITLE
workflow.onStart look partialy integrated

### ISSUE THREAD

**Issue by qclayssen** [nextflow-io/nextflow#3295]
### Expected behavior 

I want to produce a file at the beginning of the workflow. Here a file with the parameters.
thank to @robsyme 
```
import groovy.json.JsonOutput
workflow.onStart {
    out = new File('foo.txt')
    out.text = JsonOutput.toJson(params)
}
```

The file is created but the nextflow fails with an error message

### Program output error

```
Unknown method invocation `onStart` on WorkflowMetadata type -- Did you mean?
  getStart
  setStart

```

Since the foo.txt file is created, it seems that the workflow.onStart exists but it is not fully integrated because it makes the pipeline fail.

### Environment 

* Nextflow version:  22.10.0 build 5826
* Java version: openjdk 11.0.13 2021-10-19
* Operating system: macOS
* Bash version: zsh 5.8.1 (x86_64-apple-darwin21.0)

**Comment by mribeirodantas** [comment]
Hello, @qclayssen. I don't understand why you don't have a process or some Groovy code doing this at the beginning of the pipeline run and want an event handler for that 😅. There is no event handler called `onStart`, or with this purpose. Do you think there should be one?

**Comment by mribeirodantas** [comment]
Hello, @qclayssen. I don't understand why you don't have a process or some Groovy code doing this at the beginning of the pipeline run and want an event handler for that 😅. There is no event handler called onStart, or with this purpose. It's either `onComplete` or `onError` that basically does things after the pipeline has ended (either with success or not).

**Comment by bentsherman** [comment]
I agree with @mribeirodantas , although some users have requested an onStart handler, it is much simpler and cleaner to define a process with this code and execute it at the beginning of your workflow.

**Comment by qclayssen** [comment]
Hello,
Thank you for your answers. I thought maybe onStart existed but it was buggy. 
Since this is not the case, I will add groovy code at the beginning of the workflow.
