### ISSUE TITLE
Extending the SimpleHttpClient

### ISSUE THREAD

**Issue by Midnighter** [nextflow-io/nextflow#3296]
Hi,

I was wondering if you'd consider a pull request that enhances the [SimpleHttpClient](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/util/SimpleHttpClient.groovy). Before finding this client, I had written up [my own class](https://github.com/Midnighter/nextflow-utility-services/blob/main/lib/HTTPRequestsService.groovy) for a very similar purpose.

I think both implementations have their pros and cons so that a combination could yield an overall improved class. I have loosely modelled my implementation after the [Python requests API](https://requests.readthedocs.io/) which is one of the most popular in the Python ecosystem.

What I like better about the `SimpleHttpClient`:

* More complete implementation, i.e., supports user-agent, cookies, special methods for basic and bearer auth
* Has retrying with exponential back-off
* Obviously much better tested and proven in production

What I like better about my implementation:

* Actually returns a [response object](https://github.com/Midnighter/nextflow-utility-services/blob/main/lib/HTTPResponse.groovy) which contains the status code and message body (if any)
* You can set any HTTP header, value pair via named arguments to the method call

What could be a neat addition to both: Instead of a string message body, allow a map object that automatically gets serialized to JSON.

**Comment by pditommaso** [comment]
Wonder what's the use case of this requirement ?

**Comment by Midnighter** [comment]
With regard to the headers, I have an API where I need to set a specific content-type (not just 'application/json'), I also need to set the accept header to choose my response type, and I need to set a non-standard authorization header (basically a token but without the normal `Bearer ` prefix).

I can just keep using my custom class but I thought that maybe you see some advantages in the implementation, too. Hence the offer to extend the class.

**Comment by pditommaso** [comment]
Well, `SimpleHttpClient` is considered an internal implementation. it's not expected to be used by pipeline code

**Comment by Midnighter** [comment]
Sure, no need to change anything if it's not desirable.
