### ISSUE TITLE
Pretty dump helper

### ISSUE THREAD

**Issue by Midnighter** [nextflow-io/nextflow#3297]
I had made a [comment on the PR](https://github.com/nextflow-io/nextflow/pull/3163#issuecomment-1250856511) for the pretty dump at the time but got no reaction. I really think that using a type-based conversion system as demonstrated [here](https://github.com/Midnighter/nextflow-utility-services/blob/main/lib/FormattingService.groovy) is a better approach than the deeply recursive implementation right now. I'm happy to create a PR if you agree.

**Comment by pditommaso** [comment]
How you are planning to specify the formatter with `dump` operator?

**Comment by Midnighter** [comment]
I would just change the implementation of the `DumpHelper` class to be functionally like the implementation in the [FormattingService](https://github.com/Midnighter/nextflow-utility-services/blob/50c5a72d5469a0948d80be07a70facd8f4683b8a/lib/FormattingService.groovy#L36). Keeping the class and method name would mean that nothing else has to change.
