### ISSUE TITLE
Feature request : Compatibility with syslog

### ISSUE THREAD

**Issue by chdem** [nextflow-io/nextflow#330]
Hello !

As I'm planning to launch a lot of different nextflow scripts (differents parameters BUT differents script also) on a cluster (slurm + singularity), I'm thinking about logs management.

I was wondering what could be the best method to : 
- centralize logs information
- monitor nextflow scripts executions (with a status, as in the ```nextflow log``` command)

Do you have any idea ?
Do you think that a NextFlow compatibility with syslog could be a good option ? I think that groovy can do that. We could execute a script with a syslog option and be able to get logs on a specific syslog server.

Thank you !

**Comment by pditommaso** [comment]
I would suggest to execute each script in a separate launch directory. Much easier to debug and re-execute if something is fail. 

The support for Syslog could be easily added, but I'm wondering if that it's not OS level logging service? Won't it sending pipeline log information *spamming* it?

**Comment by chdem** [comment]
I'm agree with the separate launch directory usage pattern but the log centralization could be seen as a complement : when you have a lot of nextflow scripts that have been launched, be able to consult first intention logs in an unique place could be very usefull according to me.

In a second intention (debug, or just consulting), you still can consult more detailed log in the launch directory from the informations logged with syslog.

I imagine only having the same informations as the ```nextflow log``` command can show. This is enough to get first intention informations. 

And concerning syslog, I am not an expert but I think webservers for exemple use this logging method and there are oftently much more verbose that ```nextflow log``` command.

As the syslog server could be a distant one (syslog is only a protocol I think), I imagine using a Virtual Machine with a syslog server and a very simple web page specialized in Nextflow logging history. As an administrator, I could monitor all the nextflow status in only one place, and consult the nextflow logs in launch directories if needed.

It remains to be seen whether this feature could interest other people. In which case, even if I shall need a hand, I'd be happy to help with the development of syslog support.

**Comment by pditommaso** [comment]
I think it makes sense. It would be a great help if you can a find/assemble a Docker container with a syslogd daemon that I can use for development purpose.

**Comment by chdem** [comment]
Ok @pditommaso , I going to work on this ! Thank you !

**Comment by chdem** [comment]
Hello,



During my docker containers debugging investigations, I found an open source project called 'graylog' : this is exactly this kind of tool that I would use to centralize my logs in production ! 
I thus abandoned the container idea and have downloaded a VM (there's also a docker-compose file but it needs a bit more work to be operational) and start, following this : http://docs.graylog.org/en/latest/pages/getting_started.html 

Now, with the VM solution, I'm able to : 
- send a syslog message from any host with the command 
`
logger -sd -n [VM_GRAYLOG_IP] -P 514 -t myapp -p user.notice "HELLO WORLD"
`
- see the logs from the web interface of my graylog VM

I think this could be enough for your development.
@pditommaso, what do you think ?

I am a little bit curious but just for understanding a little how Nextflow works, how you think of making this development? One more time, I'm ready to help !
Is Nextflow uses log4j ? In this case, 'log4j.appender.SYSLOG' in the log4j.properties would be enough ?

Anyway, thank you for your help. I'm sure that this functionality would be useful for other people.



_(I know that it is a little bit irrelevant but after testing several syslogd docker's containers (homemade ones and docker hub ones), I was unable to send any log from the docker host to the docker containers. Nevertheless I imagined that it shall be simple ! I was able to send message only from the docker containers (with docker exec). Anyway, I was not able to understand why, even if I suspect a port forward problem with docker.)_

**Comment by pditommaso** [comment]
Graylog looks nice but I was unable to log messages to it. I have instead managed to have syslogd to work with docker by using the following command: 

```
docker run -d --network="host"  helder/rsyslog
```

The trick is the `--network="host"` which disable the network container isolation. 

> Is Nextflow uses log4j ? In this case, 'log4j.appender.SYSLOG' in the log4j.properties would be enough ?

No, NF uses [Logback](https://logback.qos.ch) for which exists a [syslog appender](https://logback.qos.ch/manual/appenders.html#SyslogAppender) however the no trivial thing is to implement a user friendly way to configure it. 

I will give a try at my earliest convenience.

**Comment by pditommaso** [comment]
Depends on #211

**Comment by statik** [comment]
Hi! I see this has a help wanted label. I'm interested in implementing this support. I'm fairly new to nextflow, and I see that this also depends on #211. @pditommaso do you have a design in mind that you would like someone to try and implement, or should we try to propose something? Any direction you can give is very welcome.

**Comment by pditommaso** [comment]
Hi, it should be straightforward. It would require to add Syslog [appender](https://logback.qos.ch/manual/appenders.html#SyslogAppender) in the NF [log initialisation](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/util/LoggerHelper.groovy#L113-113).  

As I was mentioning we should agree on a friendly way to configure it. The reference to #211 was meant to that, because there was the idea to have a common configuration format for the overall logging. But for now let's just concentrate on this component.

**Comment by pditommaso** [comment]
@crashGoBoom I've made some little changes. Please give a try a your convenience.

**Comment by crashGoBoom** [comment]
@pditommaso hi!  Looks like we need to make a change to get it working after the refactor [here](https://github.com/nextflow-io/nextflow/commit/3d6df91a0731ce1b4f797d53e920466ff4ee606d#diff-700bb0d6d6bbc3fa22fcdc6e62c6ed66R100). `this.syslog = true` should now be `this.syslog = value` since we are using syslog for the conf [here](https://github.com/nextflow-io/nextflow/commit/3d6df91a0731ce1b4f797d53e920466ff4ee606d#diff-700bb0d6d6bbc3fa22fcdc6e62c6ed66R220) as well. Thanks!
