### ISSUE TITLE
task hash only includes top-level executable for binDir entries

### ISSUE THREAD

**Issue by notestaff** [nextflow-io/nextflow#3301]
## Bug report 

When computing a task hash for caching purposes, Nextflow includes top-level third-party executable scripts in a workflow's bin/ directory that are mentioned in the task script.   But it doesn't include the files that these top-level scripts may reference.   E.g. if the top-level script imports a python module from a python file that's also in the bin/ directory, changes to that imported module won't be reflected in the task cache, resulting in possibly invalid cache reuse.

**Comment by pditommaso** [comment]
This is a design choice. The bin directory is meant to be used for self-contained scripts. Scripts having dependencies should be managed via a proper package manager (e.g. Conda) or via containeers
