### ISSUE TITLE
Does 22.10.0 override the Docker `WORKDIR`?

### ISSUE THREAD

**Issue by michaelbarton** [nextflow-io/nextflow#3312]
I encountered an issue when upgrading to [22.10.0](https://github.com/nextflow-io/nextflow/releases/tag/v22.10.0) where the working directory of a docker container seems to have been changed to a per-job directory. Reverting back to 22.9 and rerunning my pipeline seems to result in the container process being run in the `WORKDIR` location.

**Comment by pditommaso** [comment]
Not aware of that. Any chance to provide a replicable test case?

**Comment by pditommaso** [comment]
Closing this. Feel free to comment below or reopen if more help is needed.
