### ISSUE TITLE
Custom trace file rotation/renaming is broken in 22.10.0

### ISSUE THREAD

**Issue by sereeena** [nextflow-io/nextflow#3317]
Previously (eg nextflow version 22.04.4) if nextflow.config has defined a custom trace file (named pipeline_trace.txt), whenever a pipeline is run a new trace file will be created and the old ones rotated/renamed to pipeline_trace.txt.1 etc.

In the latest nextflow build this no longer happens and the pipeline stops with the error "Trace file already exists"

### Steps to reproduce the problem

In my nextflow.config file I have:
```
trace {
   enabled = true
   file = "pipeline_trace.txt"
   fields = "native_id,workdir,name,status,exit,realtime,%cpu,rss,write_bytes"
}
```

### Program output 

```
N E X T F L O W  ~  version 22.10.0
Launching `main.nf` [condescending_sax] DSL2 - revision: 2e4e09d5a0
Trace file already exists: /home/serena/Work/PRSPipeline/pipeline_trace.txt
```

### Environment 

* Nextflow version: 22.10.0
* Java version: [openjdk 11.0.16]
* Operating system: [Linux]

It would be good to have the old functionality back so that deleting the old trace files is not necessary

**Comment by pditommaso** [comment]
This behavior was changed on purpose. See https://github.com/nextflow-io/nextflow/issues/3186. 

You can overwrite the existing file using the setting 

```
trace.overwrite = true
```
