### ISSUE TITLE
Better handle error reporting for syntax errors 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3325]
## Bug report 

When there's an in valid syntax the reported is intelligible. for example:

```
process foo {
  debug true:
  input: path x, 
  """
  echo "foo ${task..index} ${task.workDir}"
  """
}


workflow {
  foo() 
}
```

**Comment by pditommaso** [comment]
See also #2082

**Comment by adkinsrs** [comment]
I encountered a similar syntax issue when using the "take" and "emit" parameters in the DSL2 syntax

My incorrect code snippet for the workflow was 
```
workflow hisat2_build {
    // Only one input channel per "take" and one output channel per "emit"
    take: ref_fasta_file, hisat2_bin_dir
    main:
        run_hisat2_build(
            ref_fasta_file
            , hisat2_bin_dir
            )
    emit: run_hisat2_build.out.index, run_hisat2_build.out.prefix
}
```

... and this gave the `Unexpected input {` error as reported in #2082.  This was quite baffling as the brackets did line up and I had no unmatched brackets elsewhere.

When I corrected the workflow by putting each "take" and "emit" parameter on their own lines, it resolved the issue, though the error message did not really indicate that was the underlying problem.
```
workflow hisat2_build {
    // Only one input channel per "take" and one output channel per "emit"
    take: ref_fasta_file
    take: hisat2_bin_dir
    main:
        run_hisat2_build(
            ref_fasta_file
            , hisat2_bin_dir
            )
    emit: run_hisat2_build.out.index
    emit: run_hisat2_build.out.prefix
}
```

(Off-topic, but the "Workflow" section of the "DSL2" documentation [here](https://www.nextflow.io/docs/latest/dsl2.html#workflow) does not give any examples of how to use "take" and "emit" for 2+ samples, so I had to do trial and error to figure that out)

**Comment by adkinsrs** [comment]
@bentsherman thanks for the heads up on that.

**Comment by ewels** [comment]
Note that using syntax highlighting at least helps a little here:

```nextflow
process foo {
  debug true:
  input: path x, 
  """
  echo "foo ${task..index} ${task.workDir}"
  """
}


workflow {
  foo() 
}
```
