### ISSUE TITLE
Do not use cpus limit requirement with K8s executor

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3329]
There are several community advices reporting the use of `limits` to cap CPU usage is a bad idea, that may even result in poor performance and prevent legit CPU usage spikes task.

See [here](https://blog.netdata.cloud/kubernetes-throttling-doesnt-have-to-suck-let-us-help/?utm_source=pocket_mylist) and [here](https://home.robusta.dev/blog/stop-using-cpu-limits) and [here](https://erickhun.com/posts/kubernetes-faster-services-no-cpu-limits/). 

Currently, nextflow set both `requests` and `limits` which according to the above is not a good practice.  

https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/k8s/model/PodSpecBuilder.groovy#L418-L422  

The goal of this issue is to only use `requests` for CPUs allocation. 

Other resources such as memory should not be affected by this issue.

**Comment by pditommaso** [comment]
Tagging @xhejtman for comments

**Comment by xhejtman** [comment]
Well, it depends. For instance, in case of Grid executors, you have forcibly `requests` `=` `limits`. However, if someone is really conviced that it is helpful to overcommit nodes, I woud not object for config option that allows to set `limits`.

**Comment by xhejtman** [comment]
> This is also true, however I don't think those (ie. Slurm or GridEngine) actively throttle the CPU usage has Kubernetes does

Actually, they do. E.g., openpbs has almost the same system of cgroups that are configured to not overload worker nodes.

**Comment by pditommaso** [comment]
Nice to know

**Comment by xhejtman** [comment]
But I think we could have an option to omit `limits`. I would not do it always forcibly.

**Comment by bentsherman** [comment]
To your point @xhejtman , we have another PR #3027 in review, which will add the request/limit syntax to all resource directives, so users will be able to specify CPU limits if they want to. But for now I will draft a separate PR just for this issue.
