### ISSUE TITLE
Add support for AWS Glacier

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3342]
AWS S3 Glacier is long-term "cold" storage tier provided by AWS much cheaper compared to plain AWS S3. 

Also, a S3 policy can be created to automatically move data files stored in S3 to be moved into the Glacier tier automatically after a pre-defined rule.  

The drawback of this solution is that to access data stored in the Glacier tier needs an explicit API call to restore them into a "accessible" state. 

The goal of this ticket is to automate the retrieval process so that the overall process is completely transparent from a pipeline developer/deployer point of view.

**Comment by bentsherman** [comment]
This [docs page](https://docs.aws.amazon.com/amazonglacier/latest/dev/using-aws-sdk-for-java.html#about-high-level-java-api) shows how to use the Glacier client in the Java SDK.

**Comment by bentsherman** [comment]
It looks like the high-level API ([ArchiveTransferManager](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/glacier/transfer/ArchiveTransferManager.html)) allows you to download an object (aka "archive") directly from Glacier without first moving it to S3 Standard. I assume this API is doing that for you under the hood.
