### ISSUE TITLE
plugin init method is not called if only contains functions

### ISSUE THREAD

**Issue by jorgeaguileraseqera** [nextflow-io/nextflow#3348]
## Bug report 

Calling a function in a plugin without operators defined produces a NullPointerException 

### Environment 

* Nextflow version: 2.10.0

**Comment by Midnighter** [comment]
I tried adding an operator that does nothing

```groovy
    @Operator
    DataflowWriteChannel noop(DataflowReadChannel source) {
        def target = CH.createBy(source)
        final next = {
            target.bind(it)
        }
        final done = {
            target.bind(Channel.STOP)
        }
        DataflowHelper.subscribeImpl(source, [onNext: next, onComplete: done])
        return target
    }

```

and included it in the nextflow script

```nextflow
include { noop; notifySlack } from 'plugin/nf-slack'
```

but that didn't help either. `SlackExtension.init` is still not being called.

**Comment by pditommaso** [comment]
It should be invoked by this 

https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/plugin/extension/ChannelFactoryInstance.groovy#L62-L62

@jorgeaguileraseqera any clue?

**Comment by jorgeaguileraseqera** [comment]
The problem comes because the init is called when the operator is called

I've been working on it and I'll create a PR
