### ISSUE TITLE
Input file is being overwritten when it matches output filename

### ISSUE THREAD

**Issue by mribeirodantas** [nextflow-io/nextflow#3361]
## Bug report 

Nextflow creates a link from the input files to every task folder. If the task outputs a file with the same filename, it will replace the content of the input filename in its original location, as it's a link.

### Expected behavior and actual behavior

Task output files shouldn't change the content of input files outside the task folder (but it does, because input files are links)

### Steps to reproduce the problem

```
process overwrite {
    input:
    tuple val(sample), path(infile)

    output:
    file "${sample}.txt"

    script:
    """
    cat $infile | wc -l > ${sample}.txt
    """
}
```

If the input file is called `mouse.txt`, the output file will also be called `mouse.txt` and thus the input file will be ovewritten.

### Environment 

* Nextflow version: 22.10.0.5826
* Java version: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 17.0.3+7
* Operating system: macOS Ventura
* Bash version: zsh 5.8.1 (x86_64-apple-darwin22.0)

**Comment by mribeirodantas** [comment]
🤣 Yeah, I know what you mean. That's why I mentioned on Slack that it's not really a bug, but it definitely is something that users wouldn't expect. It can be quite annoying to find out you lost your input file(s) because it was overwritten without prior notice 😅

Maybe we could throw an error if such a thing happens, give time for the user to rename the input file(s) and/or change his pipeline script.  Then, we could have a flag to be OK with overwriting input files. What do you think?

**Comment by stitam** [comment]
I see your point, reading from and writing to the same file will overwrite the input file and if this was not intended then this is a silly mistake, sure. :) However in nextflow there are all sorts of complexities around file paths so I think here an output file overwriting an input file with the same name is not super obvious.

I was wondering maybe a directive could be helpful from the user perspective? e.g. a directive called `overwrite` which is false by default and causes the pipeline to terminate with an error message when you would overwrite your input file, but you could explicitly set it to true in which case you could overwrite your input files with just a warning, similarly to `errorStrategy "ignore"`.

**Comment by pditommaso** [comment]
there's very little that can be done. Nextflow does not even know the output file name, since it's created by the task command (Bash) that's resolved at execution time

**Comment by mribeirodantas** [comment]
Hm... Now I understand it. Really tricky 🥲.

What do you think about changing the permission of input files? This way, without a flag (e.g. `-allow-overwriting-inputs`), Nextflow would only have read access to the input file(s) and this way wouldn't be able to overwrite them. Nextflow would `throw` an error.

On the other hand, if the flag is provided, then the permission wouldn't be changed and Nextflow would be able to overwrite it.

**Comment by pditommaso** [comment]
Changing the permission is a mess. However, there's an experimental feature that mounts the inputs in the container in read-only mode using the config setting `docker.readOnlyInputs=true`. 

https://github.com/nextflow-io/nextflow/blob/43380d2bf4ef4d552ac89a3cb982ba01a84bae05/modules/nextflow/src/main/groovy/nextflow/container/ContainerBuilder.groovy#L286-L290

Not sure if it works tho

**Comment by stitam** [comment]
I have considered changing file permissions, but then it's one more manual operation which I may forget sometimes, so it's a bit risky. `docker.readOnlyInputs=true` looks promising, I'll test it, thanks!

**Comment by mribeirodantas** [comment]
Hello, @stitam and @pditommaso ! It worked here.

This is the content of my `nextflow.config` file:
```
profiles {
    standard {
        docker.enabled = 'true'
        docker.readOnlyInputs = 'true'
        process.container = 'ubuntu'
        process.executor = 'local'
        process.cpus = 2
        process.memory = "2 GB"
    }
}
```


When I try to run the pipeline now, I get:

```
➜  nfjob nextflow run ../overwrite/main.nf
N E X T F L O W  ~  version 22.10.1
Launching `../overwrite/main.nf` [determined_sanger] DSL2 - revision: db26900e40
executor >  local (1)
[c8/10c028] process > overwrite (1) [100%] 1 of 1, failed: 1 ✘
[mouse, /Users/mribeirodantas/Downloads/overwrite/nfjob/input/mouse.txt]
Error executing process > 'overwrite (1)'

Caused by:
  Process `overwrite (1)` terminated with an error exit status (1)

Command executed:

  cat mouse.txt | wc -l > mouse.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  .command.sh: line 2: mouse.txt: Read-only file system
```

If I slightly change the pipeline with the following lines (I change the output filename):

```
...
    output:
    file "${sample}.txt2"

    script:
    """
    cat $infile | wc -l > ${sample}.txt2
    """
```

It works.
```
➜  nfjob tree work/91/3d25000297881e10cdddaa48dfdae1/
work/91/3d25000297881e10cdddaa48dfdae1/
├── mouse.txt -> /Users/mribeirodantas/Downloads/overwrite/nfjob/input/mouse.txt
└── mouse.txt2

0 directories, 2 files
```

**Comment by mribeirodantas** [comment]
I will close this issue as we have a solution for the problem, even if it's tied to using Docker.

**Comment by pditommaso** [comment]
Also @jordeu has a plan to implement read-only input files in Fusion file system for nextflow

**Comment by stitam** [comment]
`docker.enabled` + `docker.readOnlyInputs` works on my end as well, thanks! My processes run in singularity containers (I don't have sudo access), I am wondering if the same behaviour could be implemented e.g. as `singularity.readOnlyInputs`?

**Comment by mribeirodantas** [comment]
I'm also curious about Singularity! Can you try and let us know, @stitam? 😬

**Comment by pditommaso** [comment]
not sure singularity allows read-only mount paths

**Comment by mribeirodantas** [comment]
I think it's reasonable to add a `Note` box to [this section](https://www.nextflow.io/docs/edge/process.html#inputs) stating that (a) output filenames matching input filenames for the same process leads to the input file being overwritten and that (b) you can prevent this with Docker using `docker.readOnlyInputs`. What do you think, @pditommaso ?
