### ISSUE TITLE
Tower access token not getting refreshed for datasets

### ISSUE THREAD

**Issue by tcrespog** [nextflow-io/nextflow#3363]
### Expected behavior and actual behavior

The [`XAuthRegistry`](https://github.com/nextflow-io/nextflow/blob/807a816a5319d06002f13c64ec332aa10cf7ee33/modules/nf-httpfs/src/main/nextflow/file/http/XAuthRegistry.groovy#L45-L51) for [Tower](https://github.com/nextflow-io/nextflow/blob/bc16aceb8dca2c9c8831d7dd5ea1e0ae15b23067/plugins/nf-tower/src/main/io/seqera/tower/plugin/TowerFactory.groovy#L69-L72) does not refresh the access token, which ends up causing `401 Unauthorized` responses in long-running pipelines that make use of the Tower datasets feature: requests made to retrieve datasets once the initial access token has expired will fail.

### Steps to reproduce the problem

This sample pipeline allows to reproduce the issue to some extent: https://github.com/tcrespog/nf-sleep-dataset.

Set the `timeout` param to sleep for a longer period than the Tower access token expiration time and the `samples` param pointing to a dataset download URL.

### Program output 

The error manifests in Nextflow logs with lines such as:
```
Nov-01 01:45:27.016 [Actor Thread 6] TRACE n.file.http.XFileSystemProvider - File remote URL: https://api.tower.nf/workspaces/34830707738561/datasets/5CTTPvZrQDKfajQEdWXhOD/v/1/n/atacDevTests_220601.csv
Nov-01 01:45:27.019 [Task monitor] TRACE nextflow.file.FileSystemPathFactory - File system path factories: [nextflow.cloud.aws.file.S3PathFactoryPro@54c11750, nextflow.cloud.aws.util.S3PathFactory@6f96dd64]
Nov-01 01:45:27.032 [Actor Thread 6] TRACE nextflow.file.FileSystemPathFactory - File system path factories: [nextflow.cloud.aws.file.S3PathFactoryPro@54c11750, nextflow.cloud.aws.util.S3PathFactory@6f96dd64]
Nov-01 01:45:27.032 [Actor Thread 6] DEBUG nextflow.util.CacheHelper - Unable to get file attributes file: https://api.tower.nf/workspaces/34830707738561/datasets/5CTTPvZrQDKfajQEdWXhOD/v/1/n/atacDevTests_220601.csv -- Cause: java.io.IOException: Unable to access path: /workspaces/34830707738561/datasets/5CTTPvZrQDKfajQEdWXhOD/v/1/n/atacDevTests_220601.csv
```
Or:
```
java.io.IOException: Unable to access path: /workspaces/34830707738561/datasets/5CTTPvZrQDKfajQEdWXhOD/v/1/n/atacDevTests_220601.csv
	at nextflow.file.http.XFileSystemProvider.readAttributes(XFileSystemProvider.groovy:457)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at nextflow.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:156)
	at nextflow.file.FileHelper.copyPath(FileHelper.groovy:971)
	at nextflow.file.FilePorter$FileTransfer.stageForeignFile0(FilePorter.groovy:299)
	at nextflow.file.FilePorter$FileTransfer.stageForeignFile(FilePorter.groovy:266)
	at nextflow.file.FilePorter$FileTransfer.run(FilePorter.groovy:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

More logs around this [method](https://github.com/nextflow-io/nextflow/blob/55f9c87bb335a836e1a2ce24f3d92fa4dc3d8ba4/modules/nf-httpfs/src/main/nextflow/file/http/XFileSystemProvider.groovy#L474-L484) in order to diagnose the failing responses would be helpful too, as the resulting errors are not very insightful.

### Environment 

* Nextflow version: 22.10.1
* Java version: 11

**Comment by pditommaso** [comment]
I've made a PR for this issue. @tcrespog can you please give it a try ?

**Comment by tcrespog** [comment]
> I've made a PR for this issue. @tcrespog can you please give it a try ?

The [sample pipeline](https://github.com/tcrespog/nf-sleep-dataset) works fine.
 
The long-running testing pipeline provided by @drpatelh (which is designed to run in AWS) ends up failing:
```
Nov-10 08:57:49.367 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'sampleReport (1)'

Caused by:
  Essential container in task exited

Command executed:

  cat atacDevTests_220601.csv lib-atacUniversal-a.json > S2-LB.csv

Command exit status:
  1

Command output:
  (empty)

Command error:
  fatal error: An error occurred (404) when calling the HeadObject operation: Key "scratch/2oEhP23pycvV6b/stage/75/7eb13422eed3dd097f2bb4ec89e4a6/atacDevTests_220601.csv" does not exist
```

I don't know if the error is expected or it is a different kind of bug, but there's no 401 error response this time.

**Comment by pditommaso** [comment]
the last error seems related to S3 access permissions 

```
fatal error: An error occurred (404) when calling the HeadObject operation: Key "scratch/2oEhP23pycvV6b/stage/75/7eb13422eed3dd097f2bb4ec89e4a6/atacDevTests_220601.csv" does not exist
```
