### ISSUE TITLE
Nextflow support for IPv6 Only K8s Cluster

### ISSUE THREAD

**Issue by solarknight** [nextflow-io/nextflow#3364]
## Bug report 

Nextflow k8s client can't process api address when the cluster is IPv6 stack only

### Expected behavior and actual behavior
nextflow/k8s/client/ConfigDiscovery.groovy
```groovy
        final host = env.get('KUBERNETES_SERVICE_HOST')
        final port = env.get('KUBERNETES_SERVICE_PORT')
        final server = host + ( port ? ":$port" : '' )
```

When the cluster is IPv6 only, the server address will be like `2001:db8:42:1::1:443`, not `[2001:db8:42:1::1]:443`, which is the correct address.

### Environment 

Any IPv6 only k8s cluster 

* Nextflow version: till the latest
* Java version: 8/11
* Operating system: Linux

**Comment by pditommaso** [comment]
Thanks for reporting this. Solved by 123fbb648
