### ISSUE TITLE
collectFile doesn't work with watchPath but does with fromPath

### ISSUE THREAD

**Issue by nick297** [nextflow-io/nextflow#338]
I want to use .collectFile to aggregated files from a process which runs from a .watchFile Channel. This doesn't work, is there a setting I need to use? It works as expected when using Channel.fromPath

**Comment by pditommaso** [comment]
I guess the problem is that `watchFile` never stops, thus `collectFile` cannot finalize the file merge operation.

**Comment by nick297** [comment]
OK, thanks, I should probably figure out an alternate method for this

**Comment by pditommaso** [comment]
I'm closing this. Feel free to comment below if needed.
