### ISSUE TITLE
Documentation vs reality: workflow.container

### ISSUE THREAD

**Issue by keiranmraine** [nextflow-io/nextflow#3394]
### Expected behavior and actual behavior

The metadata documentation indicates that `workflow.container` returns a map of **all** containers:

> Docker image used to run workflow tasks. When more than one image is used it returns a map object containing *[process name, image name]* pair entries.

A map is not returned when multiple containers defined, only the top level value when defined (`process.container`).

If top level `process.container` has not been defined we get `[:]`.

nextflow.config
```groovy
params {
    // output folder options
    outdir          = 'results'
    tracedir        = "${params.outdir}/pipeline_info"
}

docker.enabled = true

process {
    container     = 'ubuntu:18.04' // gives this value as result, comment to get `[:]`

    withName: bash_step {
        executor = 'local'
        container = null
    }

    withName: job_a {
        container = 'quay.io/wtsicgp/expansion_hunter:5.0.0'
    }

    withName: job_b {
        container = 'quay.io/wtsicgp/pcap-core:5.7.0'
    }
}
```

main.nf
```groovy
#!/usr/bin/env nextflow
nextflow.enable.dsl=2

process bash_step {
    input:
        val(example)
    output:
        path '*.out', emit: wfl
    script:
        """
        echo ${workflow.container} > ${example}.out
        """
}

process job_a {
    input:
        path(wfl)
    output:
        path '*.out.gz', emit: gzip
    script:
        """
        gzip -c ${wfl} > ${wfl}.gz
        """
}

process job_b {
    input:
        path(wfl)
        path(gzip)
    
    output:
        path 'compress.comp'

    publishDir "${params.tracedir}", mode: "copy"

    shell:
        '''
        echo native: $(wc -c !{wfl}) > compress.comp
        echo compressed: $(wc -c !{gzip}) >> compress.comp
        echo "## content follows ##" >> compress.comp
        cat !{wfl} >> compress.comp
        echo "## EOC ##" >> compress.comp
        '''
}

workflow {
    main:
        bash_step('bob')
        job_a(bash_step.out.wfl)
        job_b(bash_step.out.wfl, job_a.out.gzip)
}
```

Run with:
```
nextflow run -stub-run main.nf
# cat results/pipeline_info/compress.comp
```

Gives:
```
native: 13 bob.out
compressed: 41 bob.out.gz
## content follows ##
ubuntu:18.04
## EOC ##
```

Would expect:

```
[bash_step : null, job_a : 'quay.io/wtsicgp/expansion_hunter:5.0.0', job_b: 'quay.io/wtsicgp/pcap-core:5.7.0']
```

(possibly no entry for `bash_step`)

### Steps to reproduce the problem

As above

### Program output 

As above

### Environment 

* Nextflow version: 22.10.2.5832
* Java version: openjdk version "17.0.5" 2022-10-18
* Operating system: Linux (GitHub CodeSpaces)
* Bash version: GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)

### Additional context

Appears related to #1758, if this is not a suitable way to introspect this value please update documentation.

**Comment by bentsherman** [comment]
The relevant code is here:

https://github.com/nextflow-io/nextflow/blob/a66b0e631b1974cae5cc4adeb50999ed79a3b5f5/modules/nextflow/src/main/groovy/nextflow/Session.groovy#L1270-L1274

However when I inspect the process config at this point, I get the following:
```
process.container = ubuntu:18.04
process.withName:bash_step = [executor:local, container:null]
process.withName:job_a = [container:quay.io/wtsicgp/expansion_hunter:5.0.0]
process.withName:job_b = [container:quay.io/wtsicgp/pcap-core:5.7.0]
```

@pditommaso can you explain the logic here? I don't know what the `$` means, but it doesn't seem to be valid anymore.

**Comment by pditommaso** [comment]
I have to say I have no memory about that. Tho there's even a test for that 

https://github.com/nextflow-io/nextflow/blob/3051cd13da0298eaca142509ac05c7080a1c4328/modules/nextflow/src/test/groovy/nextflow/SessionTest.groovy#L513-L559

**Comment by bentsherman** [comment]
The original container code was added [long ago](https://github.com/nextflow-io/nextflow/commit/74a44d7a21a6caeb6cc64f311d8e4a45ed7e9967) at a time when process names had to have a `$` prefix in the config ([docs](https://github.com/nextflow-io/nextflow/blob/74a44d7a21a6caeb6cc64f311d8e4a45ed7e9967/docs/config.rst#scope-process)).

I will draft a fix.
