### ISSUE TITLE
how pass linux commandline data to nextflow globe variable

### ISSUE THREAD

**Issue by biowang** [nextflow-io/nextflow#34]
I have file a.txt, it has 20 lines.
then I want use variable with value 20 in nextflow process.
I tried using nextflow script below, but failed.
How should I do?

  1 // initialization
  2 x=5
  3
  4 // setting again
  5 x=10
  6
  7 // setting again in process
  8 process set{
  9
 10     script:
 11     x = " wc -l a.txt | awk '{print \$1}' "
 12 }
 13
 14
 15 process get{
 16     echo true
 17
 18
 19     script:
 20     """
 21     echo "variable x in use : "${x}
 22     """
 23 }

**Comment by pditommaso** [comment]
Please post it in the mailing list 
https://groups.google.com/forum/#!forum/nextflow

**Comment by pditommaso** [comment]
Follow-up discussion 
https://groups.google.com/d/msg/nextflow/70GaDu-ZLGU/2fHBLJRUJfgJ
