### ISSUE TITLE
Flux Framework executor support

### ISSUE THREAD

**Issue by vsoch** [nextflow-io/nextflow#3403]
## Usage scenario 

I'd like to propose integration with [Flux Framework](https://flux-framework.org/), which is (on a high level) a job manager akin to slurm or similar. However, it also can be launched in slurm or cloud, so it's quite useful! 

My reasons are a bit selfish - I've already added to reframe and Snakemake, and it's because I'm developing the [Flux Operator](https://flux-framework.org/flux-operator/getting_started/custom-resource-definition.html) (a Kubernetes operator) and I'm interesting in being able to show a nextflow workflow running! :partying_face: As we transition to using Flux for the de-facto scheduler (at least the national labs are going this route and I suspect others might follow) I'd like Nextflow users to be able to still share/use their workflows.

## Suggest implementation 

I believe it would be on the level of an executor: https://www.nextflow.io/docs/latest/executor.html. I don't know much about Groovy or developing NextFlow operators, but probably with some guidance I could at least take a first shot! Thank you!

**Comment by pditommaso** [comment]
This is very welcome, Flux was already mentioned in the past by @Nortamo, great to see this proposal moving on. Also, the Flux operator project looks very interesting. 

I think adding the support for Flux to Nextflow should be not too different from the [SlurmExecutor](https://github.com/nextflow-io/nextflow/blob/daf066ce5df6ad90985d26dd3808dbd94545153e/modules/nextflow/src/main/groovy/nextflow/executor/SlurmExecutor.groovy). 

Essentially, the most important thing to know are the Flux equivalent for `sbatch`, `scancel` and `squeue` respectively to submit, cancel and check a job status. 

Happy provide more support if you want to look into this.

**Comment by vsoch** [comment]
I'd love to take a first shot! I've never written in Groovy before so I suspect this will be fun - as long as I can add to a container with Flux and figure out how to build (and thus test) I should be good to go. Will keep you in the loop (and happy Friday!)

**Comment by pditommaso** [comment]
Can Flux be installed on a local computer for testing?

**Comment by vsoch** [comment]
I'm building a container environment to do this. It technically could, but it has it's own compile and set of dependencies that I wouldn't want to add to my development system. I prefer to work in a containerized environment - what I'll do is provide a Dockerfile that builds it, along with a VSCode .devcontainer that the developer can easily copy into the root to immediately have an environment with Flux too. Testing should also be possible using this container approach!

**Comment by vsoch** [comment]
okay I'm making good progress! I noticed the design (based on slurm) is to generate and submit an sbatch file (with headers) but flux doesn't do that - we just flux submit with flags and the command directly.

So instead of this:

```
#!/bin/bash
 --setattr=cwd= /workspaces/nextflow/docker/flux/work/06/72e83990c91c1c590b686066e0fcd7
 --job-name= nf-sayHello_(1)
 --output= /workspaces/nextflow/docker/flux/work/06/72e83990c91c1c590b686066e0fcd7/.command.log
```
I'm going to try skipping this and just adding the flags to where the command is generated (for slurm "sbatch"). If you have an example executor that does similar please point me to it!

**Comment by vsoch** [comment]
wooo!! That totally worked!!

![image](https://user-images.githubusercontent.com/814322/202832355-e0306a4f-5e88-4071-b87d-81b9a6610307.png)

Okay I need to familiarize with proper docs (I have a README for flux now and just added an entry to executors.rst) and testing, but after that should be able to open up a first shot PR to discuss! I will likely be able to this weekend (probably not tonight, pooping out!)

**Comment by pditommaso** [comment]
<img src="https://media0.giphy.com/media/oYtVHSxngR3lC/giphy.gif"/>
