### ISSUE TITLE
Support for S3-compatible storage APIs

### ISSUE THREAD

**Issue by jtratner** [nextflow-io/nextflow#341]
I noticed support for S3 within nextflow, but I didn't see the ability to support s3-compatible storage APIs. e.g., equivalent in Snakemake is:

```
from snakemake.remote.S3 import RemoteProvider as S3RemoteProvider
import boto
import boto.s3.connection

S3 = S3RemoteProvider(
    host='my-host.example.com',
    access_key='access_key', secret='secret',
    calling_format=boto.s3.connection.OrdinaryCallingFormat())
```

Is that something you folks could support?  Would make it easier to use internal object storage systems that provide an S3-compatible API (e.g. Openstack Swift, Rackspace Files)

**Comment by pditommaso** [comment]
You should be able to do that by specifying the endpoint in the config file eg. 

```
aws.client.endoint = 'provider.host.com'
```

See [here](https://www.nextflow.io/docs/latest/config.html#scope-aws).

**Comment by jtratner** [comment]
ah okay - I skimmed for "host" and missed it - is it possible to specify different clients/configs for different steps? (e.g. if I wanted to transfer between Swift and S3 between steps)

**Comment by pditommaso** [comment]
Unfortunately no, but we are planning to rewrite the S3 client implementation. It would be a nice extension to add tho.

**Comment by jtratner** [comment]
Gotcha - thanks for clarifying!  I'll close this issue then. Would it be worth leaving a ticket open with the request to support multiple S3 hosts?  Possibly that's a very limited use case.

**Comment by pditommaso** [comment]
Yes, it would be nice if you could open a ticket for that, eventually proving one or more endpoints that would be possible to test.
