### ISSUE TITLE
MultiQC error when running via HTCondor: Path 'multiqc_config.yml' does not exist

### ISSUE THREAD

**Issue by amizeranschi** [nextflow-io/nextflow#3428]
Originally opened this on the nf-core/sarek issue tracker, but was told it's a general nextflow problem, so I'm also reporting it here. Any help would be much appreciated.

Please see https://github.com/nf-core/sarek/issues/861#issue-1461428390 and https://github.com/nf-core/sarek/issues/861#issuecomment-1324831706.

**Comment by pditommaso** [comment]
To consider as a Nextflow problem we need a test case to replicate the issue.

**Comment by amizeranschi** [comment]
@pditommaso Thanks for looking into this.

Here's a minimal reproducible example based on 4 samples from 1000 Genomes. When executed on the HTCondor manager node, this took around 10-15 minutes before it ran into the same error as the one reported above.

@maxulysse do you have access to an HTCondor cluster to test this as well? 

[test-1kgenomes.tar.gz](https://github.com/nextflow-io/nextflow/files/10084092/test-1kgenomes.tar.gz)

**Comment by maxulysse** [comment]
Following the Slack discussion here: https://nextflow.slack.com/archives/C02TPSC6NRG/p1669198957127939
I'm suspecting the issue is actually neither Nextflow, nor HTCondor related, but more an issue of sharing the NXF_HOME from the head node with the other nodes.
@amizeranschi is now trying this out

**Comment by amizeranschi** [comment]
Indeed, setting NXF_HOME to point to a shared location between the cluster nodes got things working.

Thanks @maxulysse for your help.

**Comment by maxulysse** [comment]
Glad we solved it
