### ISSUE TITLE
Named input/output sets in process

### ISSUE THREAD

**Issue by baffelli** [nextflow-io/nextflow#343]
Working with shell commands that require several input files and produce several outputs simultaneously made me think that It would be very useful if the qualifier ```set``` would support Mappings in addition to regular lists. This would not require to rely on the correct ordering of inputs and outputs to obtain the correct value for processes defined far apart in the script, where one could easily forget in which order the set elements where produced. Something like:
```
/*
* Generic process
*/
process ifgram{
 
input:
 map file(master:fm), file(slave:fs), val(master_id:idm), val(slave_id:ids) from pairs

output:
 map file(ifgram:if), val(master_id:idm), val(slave_id:ids) into interferogram

shell:
 '''
interf !{fm} !{fm} if 5 5
 '''

}


```
Where the semantics of the ```val```, ```file```,... qualifiers in the ```map``` context would be:
* ```file(name_in_input_mapping:local_variable) ```
    * This would extract the entry 'name_in_input_mapping' from the map received on the corresponding channel into the variable ```local_variable```
* ```file(name_in_output_mapping:localfilename)``` or  ```val(name_in_output_mapping:localvariable)``` 
    * This would insert the file/variable ```localfilename```/```localvariable``` into the output mapping with key ```name_in_output_mapping``` and send it on the channel.

**Comment by pditommaso** [comment]
I was brainstorming around a similar use for map object instead of collections/tuples of items that would allow easily capture data and meta-data produced by a task. 

However in this proposal I'm wondering if it's really needed to rename/remap all input/output keys into to new variables names. Would not that be too verbose?

**Comment by baffelli** [comment]
I agree, remapping would not be necessary at all.

**Comment by baffelli** [comment]
Considering #402 and my proposal, I don't think it needs any new keyword such as `map` or `filemap`. Do we just need each `file` and `val` qualifier to support a keyword?

**Comment by pditommaso** [comment]
The point is that they are similar but different things. #402 would allow to reference files as a map eg 

```
input: 
file my_files_map from something 
script:
"""
my_command --this $my_files_map.foo --that $my_files_map.bar 
"""
```

Instead with the `map` proposal it would be possible to *import* map entries eg 

```
input: 
map file(foo), file(bar) from something 
script:
"""
my_command --this $foo --that $bar 
"""
```

The advantage of the second is that allows any kind of values, instead #402 in the current form it allows only files.

**Comment by emi80** [comment]
I like the proposal from @baffelli to have regular `file` and `val` support a mapping keyword. With this approach it would be possible to just use `set` as a map:

```
input: 
set file(foo:fooFile), file(bar:barFile), val(id:id) from something 

output:
set file(commandOut:out), val(id:id), val(someVar:"something") into outChannel

script:
"""
my_command --this $fooFile --that $barFile --id $id > out
"""
```

**Comment by baffelli** [comment]
> I like the proposal from @baffelli to have regular file and val support a mapping keyword. With this approach it would be possible to just use set as a map:

I thought a bit about it:
 in the command I would prefer ```${something.foo}``` or ```${something['foo']}```. It is verbose but reduces ambiguity and allows you to have several channels as inputs with the same mapping keys and no conflicts.

**Comment by jemunro** [comment]
Hi @pditommaso, is there any update on this? I think this feature would be incredibly useful for producing less ambiguous workflows.

Another suggestion, using a map as an input to a process could expose all map keys as variables within that process. 
e.g. this:

```
process first {
  input:
  file(something) from a_channel

  output:
  map file(foo:fooFile), file(idx:fooFile.idx) into channel_bar

  script:
  """
  command_1 $something -o fooFile -idx fooFile.idx
  """
}

process second {
  input:
  channel_bar

  script:
  """
  command_2 $foo
  """
}
```
would be equivalent to this:
```
process first {
  input:
  file(something) from a_channel

  output:
  set file("fooFile"), file("fooFile.idx") into channel_bar

  script:
  """
  command_1 $something -o fooFile -idx fooFile.idx
  """
}

process second {
  input:
  file(foo), file(idx) from channel_bar

  script:
  """
  command_2 $foo
  """
}
```

**Comment by stevekm** [comment]
I've been thinking about this recently and it seems like there is a disadvantage to this in the way that it reduces the isolation between processes and channels. This might actually end up with more confusing pipelines, since you would end up with less strict requirements on a channel's contents, increasing the ambiguity of what is actually in the channel at any given point (e.g. it could have any number of other items beyond the listed `input` items). Not sure if that is desirable? It also increases the coupling between channels and processes; such a process would now only be usable with channels that have the correct keys, and modifications to your channel contents upstream could break downstream processes in a new way. Maybe its better to stick with more robust channel manipulation before letting it reach the process. Thoughts?

**Comment by pditommaso** [comment]
I agree that this feature would be useful but on the other hand I completely agree with the Steve comment. 

To mitigate this problem it could be implemented an input/output declaration that makes explicit the record fields imported/exported. Maybe something like: 

```
process sample {
  input: 
  record foo, bar from ch1
  output: 
  record this, that into ch2 
 
  """
  the_command
  """
}
```

Where `foo` and `bar` are two keys defined in the associated array emitted by the `ch1` channel and will be defined in the script evaluation scope. 

In the same manned `this` and `that` are two variables defined in the script evaluation context and will be set a entries in a new associative array produced by the `ch2` channel.
