### ISSUE TITLE
`nextflow` installation script yields "Could not parse version" error, OpenJDK 11.0.14.1 from MacPorts

### ISSUE THREAD

**Issue by ernstki** [nextflow-io/nextflow#3430]
## Bug report

Hi everyone, hope you're well. I ran into a problem similar to what's described in #953 (for OpenJDK 10 in that case). As before, the `nextflow` installation script—or, I assume, some Java bit that's called from the installation script—yields the error

    Could not parse version: 11.0.14.1 while processing attribute Min-Java-Version: 1.8.0 

in spite of my installed `java` meeting the requirements stated in the ["Getting started" section](https://nextflow.io/#GetStarted) of the Nextflow home page.

### Expected behavior and actual behavior

Expected: `nextflow` installation script would work with an installed `java`, version 11.x, from MacPorts' `openjdk11` package.

Actual: running the installation script yields an error about being unable to parse the (Java) version.

### Steps to reproduce the problem

1. download [`nextflow` script](https://github.com/nextflow-io/nextflow/releases/download/v22.10.3/nextflow) from the releases page
2. run the script with Bash

### Program output 

```console
$ port echo installed | grep -iE '(java|jdk|jre)'
openjdk11                      @11.0.14.1_4+release+server

$ java -version
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment (build 11.0.14.1+0)
OpenJDK 64-Bit Server VM (build 11.0.14.1+0, mixed mode)

$ bash nextflow
CAPSULE EXCEPTION: Could not parse version: 11.0.14.1 while processing attribute Min-Java-Version: 1.8.0 (for stack trace, run with -Dcapsule.log=verbose)
USAGE: java <options> -jar ../.nextflow/framework/22.10.3/nextflow-22.10.3-one.jar
⋮
```

### Environment 

* Nextflow version: n/a (using latest release script from [22.10.3](https://github.com/nextflow-io/nextflow/releases/download/v22.10.3/nextflow)
* Java version: 11.0.14.1
* Operating system: macOS 10.15.7 (Catalina)
* Bash version: GNU bash, Version 5.1.12(1)-release (x86_64-apple-darwin19.6.0)

### Additional context

Running `bash nextflow -Dcapsule.log=verbose` does not yield any more useful information, as far as I can tell, but I will include its output if you deem it necessary.

Initially, I had a problem with the installation script due to an old `JAVA_HOME` defined in my login scripts, pointing to a JRE that was no longer available (1.8.something). I quickly resolved this, though, started a fresh shell, and did an `rm -rf ~/.nextflow` to be sure that no evidence remained of previous attempts. I currently do not have _any_ `JAVA_HOME` defined in my shell environment, verified with `echo $JAVA_HOME`.

Oddly, I was unable to reproduce this in a CentOS 7 Docker container having `java-11-openjdk-11.0.17.0.8-2.el7_9.x86_64` installed from the official repositories. (It _was_ necessary to install `which` in the container in order for the `nextflow` script to work properly, which is perhaps a separate bug report.)

Thanks for taking a look.

**Comment by manulera** [comment]
Same problem here.

**Comment by manulera** [comment]
My settings:

```
java version "18.0.1.1" 2022-04-22
Java(TM) SE Runtime Environment (build 18.0.1.1+2-6)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```

**Comment by manulera** [comment]
I found a solution in #2856. Setting the variable JAVA_HOME in the bash profile did it for me. Here the instructions for different MacOS versions:

https://mkyong.com/java/how-to-set-java_home-environment-variable-on-mac-os-x/#java-home-and-macos-11-big-sur

@ernstki I guess it's too late, but if you try this and it works for you, feel free to close the issue.

**Comment by ernstki** [comment]
@mhebrard I'll try to have a look when I have access to my Mac again. Patching a regular expression somewhere to check for `(\d+)(\.\d+)+` instead of `(\d+)\.(\d+)\.(\d+)` is probably within my abilities, even though I'm not a "Java programmer."

**Comment by pditommaso** [comment]
Solved via https://github.com/nextflow-io/nextflow/issues/2951

**Comment by ernstki** [comment]
Thanks for your efforts, @pditommaso!

**Comment by pditommaso** [comment]
@ernstki you are welcome!
