### ISSUE TITLE
Add support for custom channels to Conda

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3431]
## Improvements 

The goal of this ticket is to allow the possibility to specify custom channel (and their order) the user specify a Conda package in using the `conda` directive. 

For example adding in the nextflow config 

```
conda {
  enabled = true 
  channels = ['default','bioconda']
}

```

Nextflow should turn this information into the following command 

```
conda install -y -n base -c defaults -c bioconda <CONDA PACKAGE NAME>
```

The above information is ignored when the `conda` directive specifies a Conda recipe file. 

The same behaviour is applied for Wave containers build from Conda

**Comment by pditommaso** [comment]
Tagging @jordeu ☝️

**Comment by abhi18av** [comment]
I guess #3435 closes this issue right?

**Comment by pditommaso** [comment]
Yes
