### ISSUE TITLE
Using CVMFS for storing reference genome data

### ISSUE THREAD

**Issue by amizeranschi** [nextflow-io/nextflow#3434]
## New feature

A nice alternative to iGenomes and RefGenie could be CVMFS, developed by CERN. Here's a description from Galaxy Project's [relevant documentation page](https://training.galaxyproject.org/training-material/topics/admin/tutorials/cvmfs-manual/tutorial.html):

> The CernVM File System provides a scalable, reliable and low-maintenance software distribution service. It was developed to assist High Energy Physics (HEP) collaborations to deploy software on the worldwide-distributed computing infrastructure used to run data processing applications. CernVM-FS is implemented as a POSIX read-only file system in user space (a FUSE module). Files and directories are hosted on standard web servers and mounted in the universal namespace /cvmfs.

## Suggest implementation 

The people behind the Galaxy Project are hosting [their own CVMFS instance](http://datacache.galaxyproject.org/), with plenty of reference genome data already available. For more details about how things are structured in there, see [this page](https://galaxyproject.org/admin/reference-data-repo/#usegalaxyorg-reference-data).

**Comment by pditommaso** [comment]
This is a nice suggestion but has nothing to do with Nextflow. As long as CernVM-FS is POSIX compliant, nextflow already supports it.

**Comment by amizeranschi** [comment]
Pffft, sorry! I meant to post this on the nf-core/sarek tracker. Same goes for [this other issue](https://github.com/nextflow-io/nextflow/issues/3433).
