### ISSUE TITLE
New operator: sample each n-th randomly

### ISSUE THREAD

**Issue by baffelli** [nextflow-io/nextflow#344]
Sometimes, it is useful to randomly keep each 1/Nth value emitted by a channel. It turns out that this can be implemented by using [reservoir sampling](https://en.wikipedia.org/wiki/Reservoir_sampling) without the need of knowing the length of the stream _a priori_. At the moment, I've implemented it 
as a filter like that:
```
//Reservoir sampling to select
//1/N samples from stream
reservoir_sampling =
{
	it, k, reservoir, counter, rng -> 
	//Fill reservoir
	if (counter < k){reservoir << it}
	counter = counter + 1
	//Pick a random number
	i = rng.nextInt(counter)
	if (i < k)
		reservoir[i] = it
		return it
}
```
This is then applied to a channel by using:
```
res_counter = 0
reservoir = []
 n = 100
rng = new Random()
some_channel
.filter({it->reservoir_sampling(it, n, reservoir, res_counter, rng)})
```
I know this solution is not quite elegant, but it seems to to its job quite well. However, I find it useful enough that a new channel operator ```randomSample(n)``` could be defined, that would randomly sample the channel with a probability of ```1/n```.

**Comment by pditommaso** [comment]
That's very nice. It could be surely added. Thanks for the suggestion.

**Comment by baffelli** [comment]
Fantastic, thanks. I could event try to do it mysel, once I understand how operators are defines. Do they all base on .map?

**Comment by pditommaso** [comment]
Not exactly, but it should not be much more difficult. Have a look at [DataflowExtension](https://github.com/nextflow-io/nextflow/blob/88b50012d38b3f1bb1e6c2a7ea8e2e67f685f481/src/main/groovy/nextflow/extension/DataflowExtensions.groovy#L60-L60) which is where (almost) all operators are implemented.

**Comment by baffelli** [comment]
Along the same lines, another operator take_nth could be defined, that deterministically takes each n-th element.

**Comment by pditommaso** [comment]
That can be done with [buffer](https://www.nextflow.io/docs/latest/operator.html#buffer) eg. 

```
ch.buffer( size:1, skip: n) 
```

**Comment by baffelli** [comment]
I was almost sure it was possibile somehow...should have read the doc better!

**Comment by pditommaso** [comment]
Basically the reservoir algorithm fill up a buffer in random order. Right?

**Comment by pditommaso** [comment]
I'm trying to implement it but I have some problem with the `counter` variable in this snippet 

```
reservoir_sampling =
{
	it, k, reservoir, counter, rng -> 
	//Fill reservoir
	if (counter < k){reservoir << it}
	counter = counter + 1
	//Pick a random number
	i = rng.nextInt(counter)
	if (i < k)
		reservoir[i] = it
		return it
}
```

It looks like `counter` is supposed to be increased +1 in each iteration but it declared in the local scope, so I don't see how it can work.

**Comment by baffelli** [comment]
Counter is supposed to be increased, but I'm defining it outside of the scope and passing it to the closure when I first call it.:
```
res_counter = 0
reservoir = []
 n = 100
rng = new Random()
some_channel
.filter({it->reservoir_sampling(it, n, reservoir, res_counter, rng)})
```
Somehow, the algorithm needs to keep track of global state, is is apparently impossible to implement it as a pure function.

**Comment by pditommaso** [comment]
No that's possible, it's enough to not pass `res_counter` as parameter when you are invoking the closure (provided you have defined `res_counter` *before* the closure definition. 

That's my implementation 

```
    private void sampling(it) {

        counter++
        //Fill reservoir
        if (counter <= N){
            reservoir << it
        }
        else {
            //Pick a random number
            int i = rng.nextInt(counter)
            if (i < N)
                reservoir[i] = it
        }

    }
```

What is supposed to be returned when the items emitted are less than the request sample length? the shuffled `reservoir` list  ?

**Comment by baffelli** [comment]
Good question...I did not have the time to think about it too much. I will perhaps test it briefly now and try to understand it.

**Comment by pditommaso** [comment]
I'm uploaded a new snapshot implementing the `randomSample(n)` operator. You may want to give a try by using the following command: 

```
NXF_VER=0.25.0-SNAPSHOT nextflow run .. etc 
```

**Comment by baffelli** [comment]
It seems to work when it test it like that:
```
a = Channel.from((0..500))
a.randomSample(250)
.view()
.count()
.view()
```
Tomorrow I'll test it on my pipeline.
