### ISSUE TITLE
[BUG]: Latest Java version 19 not (yet) supported

### ISSUE THREAD

**Issue by corneliusroemer** [nextflow-io/nextflow#3442]
## Bug report 

Homebrew installed the latest openjdk version 19 and that breaks a tool that uses the system java (epi2me labslauncher) since nextflow only supports up to v18.

It would be nice if nextflow supported v19 which has been released 2 months ago on September 20.

### Expected behavior and actual behavior

Support the latest Java release v19

## Context

Previous seem to have happened earlier in the release cadence, 22.03.0-edge (27 Mar 2022) added support for v18, which was released on 22 March.

**Comment by pditommaso** [comment]
This has been merged recently https://github.com/nextflow-io/nextflow/commit/811e7ca8ed575d4c609b10006a88623c4fb0ffbf
