### ISSUE TITLE
Update to nextflow version 22.11. It can not load the profiles of conda or singularity.

### ISSUE THREAD

**Issue by nttg8100** [nextflow-io/nextflow#3449]
## Bug report: 
Update to nextflow version 22.11. It can not load the profiles of conda or singularity.
## Temp fix:
 Evenly, I tried to add the parameter enable conda. Finally, I have to export the global variable or downgrade version of nextflow to 22.04.5. Finally, it worked.

**Comment by pditommaso** [comment]
Unable to replicate. Please follow the issue template if the problem persists
