### ISSUE TITLE
Modified task properties are not accessible in the command script during task retry 

### ISSUE THREAD

**Issue by santiagorevale** [nextflow-io/nextflow#345]
Hi team!

I'm trying to implement incremental resources when retrying. I've tried it with a simple example but I'm unable to get the incremented resources to be printed properly.

I read in #179 that "task.attempt" always evaluates to 1, but what happens with memory and cpus? I'm running a Java process where I'm specifying "-Xmx${task.memory}", but when checking  ".command.sh" it always used the same value.

Here is an example similar to the one in #179: task.attempt is always 1 and task.memory always 5 MB.

```
#!/usr/bin/env nextflow

ch = Channel.from( 'alpha' )

process test_resources {
  tag "$code"
  echo true
  errorStrategy { task.exitStatus == 1 ? 'retry' : 'finish' }
  maxRetries 4
  maxErrors '-1'
  memory { 5.MB * task.attempt }

  input:
  val code from ch

  """
  echo "  Test code : ${code}"
  echo "Run attempt : ${task.attempt}"
  echo "     Memory : ${task.memory}"
  echo
  if [[ "${code}" == "alpha" ]]; then
      exit 1
  else
      exit 0
  fi
  """
}
```

Any help on how to overcome this or how to use it properly, would be really appreciated.

Thanks in advance.

Best regards,
Santiago

**Comment by pditommaso** [comment]
Interesting point. Here the idea was to re-execute the task as it was, so without re-evaluating the  command script, for this reason the new values of the `task` variables are not accessible. 

Frankly I never encountered this use case, but yes, the need of providing the new memory setting for tools like java makes me think that this should addressed somehow. 

Unfortunately NF does not provide any workaround for now, you may try to check is your batch scheduler provide any special variable that reports the current  allocation of the memory.

**Comment by pditommaso** [comment]
Related https://github.com/nextflow-io/nextflow/issues/258

**Comment by santiagorevale** [comment]
I'm not sure I understand how the "Dynamic computing resources" works, so correct me if I'm wrong. When I have the following in a process:
```
    cpu { 1 * task.attempt }
    memory { 2.GB * task.attempt }
```
it means that it will allocate for the process in the server 1 CPU and 2 GB of memory for the 1st attempt, 2 CPUs and 4 GB of memory for the 2nd, and so on, am I right? But, inside the process, both variables ```task.cpu``` and ```task.memory``` will always be 1 and 2 GB?

Why do you think it wouldn't be appropriate to propagate the updated values (including ```task.attempt```) inside the processes?

**Comment by pditommaso** [comment]
> it means that it will allocate for the process in the server 1 CPU and 2 GB of memory for the 1st attempt, 2 CPUs and 4 GB of memory for the 2nd, and so on, am I right?

yes 

> But, inside the process, both variables task.cpu and task.memory will always be 1 and 2 GB? 

The problem is that those directive are usually used with a batch scheduler (eg. SGE). In this scenario the update values are correctly propagated to the job submit request. (though I would not increase the num of cpus and memory linearly because in this way the mem/cpu would be the same)

> Why do you think it wouldn't be appropriate to propagate the updated values (including task.attempt) inside the processes?

Ideally the task command should be the same, but I see you point that in this way it's not possible to control the mem for tool like java. This is something that we need to fix.

**Comment by santiagorevale** [comment]
Great! Thanks for the clarification, Paolo! It was driving me nuts.
