### ISSUE TITLE
NXF_DEBUG level is not properly handled

### ISSUE THREAD

**Issue by YuxinShi0423** [nextflow-io/nextflow#3455]
### Expected behavior and actual behavior

As suggested in https://www.nextflow.io/docs/latest/config.html#environment-variables
> Defines scripts debugging level: 1 dump task environment variables in the task log file; 2 enables command script execution > tracing; 3 enables command wrapper execution tracing.
Also in https://github.com/nextflow-io/nextflow/blob/77f55262ef75b0bf16afc0b2463a81801c8f581a/modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy#L58-L64

So I assumed that when using `NXF_DEBUG=1`, I shall only have function `nxf_env` triggered which prints the task env in `.command.log`

However, in `.nextflow.log`, the actual cmd line is launched with `-x`
```
Nov-30 17:20:37.678 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -uex .command.run
```

My assumption is that the BASH is set with `-x` when `NXF_DEBUG=1` both on `.command.run` and `.command.sh`

### Steps to reproduce the problem

```
export NXF_DEBUG=1
nextflow clone https://github.com/nextflow-io/hello
nextflow run hello
```

### Program output 

```
Nov-30 17:20:37.678 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -uex .command.run
Nov-30 17:20:37.681 [Task submitter] INFO  nextflow.Session - [31/282f1a] Submitted process > sayHello (1)
```
and `.command.log` like
```
+ set -e
+ set -u
+ NXF_DEBUG=1
+ [[ 1 > 1 ]]
+ NXF_ENTRY=nxf_main
+ nxf_main
+ trap on_exit EXIT
+ trap on_term TERM INT USR2
+ trap '' USR1
+ [[ -n '' ]]
+ NXF_SCRATCH=
+ [[ 1 > 0 ]]
+ nxf_env
+ echo '============= task environment ============='
============= task environment =============
+ env
+ sort
+ sed 's/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/'
...
```

### Environment 

- Nextflow version: 22.10.1.5828
- Java version: openjdk version "16.0.1" 2021-04-20
- Operating system: macOS
- Bash version: zsh 5.8.1 (x86_64-apple-darwin21.0)

**Comment by bentsherman** [comment]
It looks like at some point Paolo changed the code to add `-x` when NXF_DEBUG >= 1, so the docs and comments just need to be updated

**Comment by pditommaso** [comment]
Sorry for the inconvenience. However, this is an internal debugging variable. Semantics can change over time.
