### ISSUE TITLE
Docker input file mounts should be read-only for enforce container security

### ISSUE THREAD

**Issue by zichner** [nextflow-io/nextflow#346]
When running a Nextflow pipeline from `/path/to/a/nextflow/pipeline/` that reads in a file located at `/path/to/some/file` it seems that the directory `/path/to/` gets mapped to the Docker container. I.e., the part of the path that is shared by the working directory and the file to read is accessible from Docker, rather than only the specific directories.

So, in the worst case, a Docker container executed by Nextflow has access to the entire file system, which could be a big security risk.

Did I understand the directory mapping correctly, and if so, is there a way to prevent this?

**Comment by pditommaso** [comment]
Yes, that's true. We could enforce a bit the security mounting that paths at read-only, but a malicious user can easily mont a sensitive path and gaining root access to it in any case. 

If you have this kind of problems you should not avoid using Docker and prefer more safe alternatives as [Singularity](http://singularity.lbl.gov).

**Comment by zichner** [comment]
Mounting paths read-only is a good idea. 
In general, I am less worried about a malicious user but more about a Docker container taken from somewhere else, which might be not set up properly. In the latter case, read-only paths could prevent larger damage.

**Comment by zichner** [comment]
Thanks!
