### ISSUE TITLE
Nextflow REPL console uses DSL1 by default, hangs forever with DSL2

### ISSUE THREAD

**Issue by Jessime** [nextflow-io/nextflow#3461]
### Actual behavior

If I grab the example from the [`set` documentation](https://www.nextflow.io/docs/latest/operator.html#set) and try to run it in the console, I get an error:

```
groovy> Channel.of(10, 20, 30).set { my_channel } 
groovy> my_channel.view() 
 
Exception thrown

groovy.lang.MissingPropertyException: No such property: my_channel for class: ConsoleScript1
	at ConsoleScript1.runScript(ConsoleScript1:2)
	at nextflow.script.BaseScript.runDsl1(BaseScript.groovy:164)
	at nextflow.script.BaseScript.run(BaseScript.groovy:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

More generally, I'm not able to find any case where I can use `set` in the console without immediately hitting the `No such property` error.

### Expected behavior

If, on the other hand, I run from the command-line, I get the expected behavior.

```
10
20
30
```
 
### Environment 

```
❯ nextflow info
  Version: 22.10.3 build 5834
  Created: 21-11-2022 21:37 UTC (14:37 MDT)
  System: Mac OS X 12.5
  Runtime: Groovy 3.0.13 on Java HotSpot(TM) 64-Bit Server VM 17.0.5+9-LTS-191
  Encoding: UTF-8 (UTF-8)
```

```
❯ java --version
java 17.0.5 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
```

* Operating system: [macOS, specifically an M1 Max running Monterey 12.5]
* Bash version: `zsh 5.8.1 (x86_64-apple-darwin21.0)`

### Additional context

This is the exact bug described here https://github.com/nextflow-io/nextflow/issues/2689. 

Running `nextflow.enable.dsl=2` _does not_ improve the situation, and in fact causes several other issues (also described in the issue linked above). 

Thanks! 

cc @brwnj

**Comment by bentsherman** [comment]
Hi @Jessime , thanks for clarifying that the root issue is with `set`. I am seeing this error as well. Probably the `nf-console` plugin is missing something when it executes scripts (see `nextflow.ui.console.Nextflow`), but I'm not sure what.

**Comment by Jessime** [comment]
@bentsherman I'm happy to create a new issue if that's better, but I think we can generalize this issue to:

## nextflow console doesn't support dsl 2

Another demonstration is:

```
samples = Channel.from("XU1")
samples.view()
samples.view()
```

Adding `nextflow.enable.dsl=2` causes the same infinite loop issues as always.

**Comment by bentsherman** [comment]
Thanks @Jessime , I think you are right. It looks like the Nextflow REPL does not set up the same environment (see `Nextflow.newScript()`) as it does with the `run` command (see `ScriptRunner`, `ScriptParser`). That would explain why DSL1 is used by default. Some of these missing extensions are likely causing the infinite hanging with DSL2. I have encountered the same problem while working on tests in the past, because DSL2 uses more lazy execution.

When I have some time, I will review the console code and see if I can get it to work with DSL2 by default.

**Comment by Jessime** [comment]
Sweet! The REPL is a real boost to productivity compared to the overhead of `run` when you're trying to logic through a chain of `Channel` manipulations or whatever. Having full DSL2 would be huge.
