### ISSUE TITLE
cache is not reused if same process with same inputs is called via different workflow

### ISSUE THREAD

**Issue by notestaff** [nextflow-io/nextflow#3471]
If I've run process A through the unnamed workflow in the .nf file, and later call it again through a named workflow in the same .nf file, reuse does not happen.   It seems that the cache key uses a fully qualified process name.  Unfortunately, this prevents reuse in a common case where you want to run the same multi-step workflow with different latter steps, while reusing the earlier step results: reuse of the (computationally heavy) early workflow steps does not happen.

Would it be unsafe to use just the process name, not the fully qualified name, for the cache key?

**Comment by notestaff** [comment]
This issue is still relevant, so commenting to prevent staleness.

**Comment by bentsherman** [comment]
I would argue that the process name need not be included at all.

If I define two processes `foo` and `bar` which are identical except for their name, I see no reason why their cache entries can't be interchangeable.

The essential identity of a task is encoded in its script and inputs, not the name.

**Comment by bentsherman** [comment]
On the other hand, if I run a pipeline with `foo` and `bar` and they invoke identical tasks, that will cause a hash collision as Nextflow will try to create the same directory twice. It could be avoided in resume mode, but there is still a race condition.

**Comment by bentsherman** [comment]
I have created a PR that simply removes the process name. Feel free to play around with it.

Whether we remove the process name or use the process "simple" name, we will need to deal with the race condition where two processes try to create the same task.

**Comment by pditommaso** [comment]
That's why the fully qualified name is there.

**Comment by bentsherman** [comment]
Closing for now, but if someone wants to look for some clever solution they are welcome to try 😄
