### ISSUE TITLE
Ability to define registry property for Singularity

### ISSUE THREAD

**Issue by markpanganiban** [nextflow-io/nextflow#3472]
We would love to have the capability to define the registry for singularity containers.

The point of having a `singularity.registry` variable in our configuration will help us to have a container-service-agnostic (docker/singularity)  configuration just with the container:version and a system/admin managed configuration or profile that defines if the pipeline runs on docker/singularity and from where the containers need to be pulled from. 

**Expected outcome:**
```
singularity.enabled = true
singularity.registry = "XXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com"
process.container = "third-party-tools:latest"
```

**Comment by pditommaso** [comment]
Solved via 37c1aeb9
