### ISSUE TITLE
Add a message warning when input tuple cardinality does not match declared length

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#348]

**Comment by Jokendo-collab** [comment]
Input tuple does not match input set cardinality declared by process `NFCORE_RNAVAR:RNAVAR:PREPARE_GENOME:SAMTOOLS_FAIDX` -- offending value: /ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa
