### ISSUE TITLE
Check if `~/.nextflow` is a symlink instead of exiting with `Unable to load secrets provider`.

### ISSUE THREAD

**Issue by ghuls** [nextflow-io/nextflow#3482]
### Expected behavior and actual behavior

On our HPC systems, the home directory is limited to a quite small size, so we had ~/.nextflow symlinked to another volume which has much larger quota.

With older versions of Nextflow (21.x) this didn't give a problem, with newer versions (22.x) it gives an obscure error message `Unable to load secrets provider` (for which Google didn't return any hit at all).

The problem can be solved by explicitly setting `NXF_HOME` to the directory on the other volume, but it would be nice if NextFlow would detect that the ~/.nextflow dir is a symlink if it can't work with that fact, instead of giving the uninformative `Unable to load secrets provider` error message.

### Steps to reproduce the problem

```bash
# Create NextFlow dir in non default location.
mkdir /tmp/nextflow

# Create a symlink.
ln -s /tmp/nextflow ~/.nextflow 

# Download nextflow.
wget https://github.com/nextflow-io/nextflow/releases/download/v22.10.3/nextflow-22.10.3-all
chmod a+x nextflow-22.10.3-all

# Run a NextFlow command.
./nextflow-22.10.3-all secrets list
```

This results in this error message, which does not give any indication that the problem is caused by the symlink.
```bash
❯  ./nextflow-22.10.3-all secrets list
Unable to load secrets provider
```

Setting `NXF_HOME`, solves the problem. Nextflow 21.10.x worked fine with symlinked dirs.
```
export NXF_HOME=/tmp/nextflow

$ ./nextflow-22.10.3-all secrets list
no secrets available
```

### Environment 

* Nextflow version: `22.10.3`
* Java version: `17.0.2`
* Operating system: `Linux`
* Bash version: `GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)`

**Comment by pditommaso** [comment]
Thanks for reporting this detailed issue. Solved
