### ISSUE TITLE
Issue with staged files from s3

### ISSUE THREAD

**Issue by maxulysse** [nextflow-io/nextflow#3500]
## Bug report 

I think we have an issue when files are coming from s3, often Nextflow wait for quite a long time.
I don't have issue that this happen on the first time, different protocols can have different speed or behavior, but when using -resume, the staged files are still super slow to get.

### Steps to reproduce the problem

input.csv

```
s3://nf-core-awsmegatests/rnaseq/input_data/minimal/GSE110004/SRR6357070_1.fastq.gz
s3://nf-core-awsmegatests/rnaseq/input_data/minimal/GSE110004/SRR6357071_1.fastq.gz
s3://nf-core-awsmegatests/rnaseq/input_data/minimal/GSE110004/SRR6357072_1.fastq.gz
s3://nf-core-awsmegatests/rnaseq/input_data/minimal/GSE110004/SRR6357073_1.fastq.gz
s3://nf-core-awsmegatests/rnaseq/input_data/minimal/GSE110004/SRR6357074_1.fastq.gz
s3://nf-core-awsmegatests/rnaseq/input_data/minimal/GSE110004/SRR6357075_1.fastq.gz
s3://nf-core-awsmegatests/rnaseq/input_data/minimal/GSE110004/SRR6357076_1.fastq.gz
```

input_https.csv (to compare)

```
https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357070_1.fastq.gz
https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357071_1.fastq.gz
https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357072_1.fastq.gz
https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357073_1.fastq.gz
https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357074_1.fastq.gz
https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357075_1.fastq.gz
https://raw.githubusercontent.com/nf-core/test-datasets/rnaseq/testdata/GSE110004/SRR6357076_1.fastq.gz
```

main.nf

```
process STAGE {
    tag { reads }

    input:
    path(reads)

    output:
    path('*.txt'), emit: txt

    script:
    """
    touch ${reads.baseName}.txt
    """
}

workflow {
    params.input = "input.csv"

    Channel.fromPath(params.input)
    | splitCsv()
    | STAGE

    STAGE.out.txt | view
}
```

### Program output 

without resume on the first try:

```
Duration    : 3m 2s
CPU hours   : (a few seconds)
Succeeded   : 7
```

with resume, with all files already cached:

```
Duration    : 2m 4s
CPU hours   : (a few seconds)
Succeeded   : 7
```

with the files from https, it takes seconds.

### Environment 

Tested on github codespace

* Nextflow version: 22.10.4
* Java version: openjdk version "11.0.17" 2022-10-18
* Operating system: Linux Ubuntu
* Bash version: GNU bash, version 5.1.16(1)-release

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Can you please put together a mini project (GH repo) to replicate the problem ?

**Comment by maxulysse** [comment]
I'm on it P

**Comment by maxulysse** [comment]
```
nextflow run maxulysse/nextflow_3500 -r main
```

**Comment by maxulysse** [comment]
From what I can see it takes just as long to resume as to run:
```
> nextflow run maxulysse/nextflow_3500 -r main         
N E X T F L O W  ~  version 22.10.2
Launching `https://github.com/maxulysse/nextflow_3500` [crazy_yalow] DSL2 - revision: ab4fcf2292 [main]
executor >  local (7)
[98/7a2969] process > STAGE (SRR6357076_1.fastq.gz) [100%] 7 of 7 ✔
/home/max/workspace/nextflow_3500/work/ae/70724892be6a2199e557fc37566b03/SRR6357073_1.fastq.txt
/home/max/workspace/nextflow_3500/work/9f/cb78b1e9fd5e115e3fb1d13297ca20/SRR6357070_1.fastq.txt
/home/max/workspace/nextflow_3500/work/85/edc96a9ae8402c81fdaecea92a8429/SRR6357071_1.fastq.txt
/home/max/workspace/nextflow_3500/work/cc/14b31944fb5899bd7af21592f8d164/SRR6357074_1.fastq.txt
/home/max/workspace/nextflow_3500/work/34/b73fd037423634306386b2b18e48aa/SRR6357072_1.fastq.txt
/home/max/workspace/nextflow_3500/work/98/7a2969b84463307e99e1c00a4d7521/SRR6357076_1.fastq.txt
Completed at: 15-Dec-2022 15:40:41
Duration    : 1m 50s
CPU hours   : (a few seconds)
Succeeded   : 7

> nextflow run maxulysse/nextflow_3500 -r main -resume
N E X T F L O W  ~  version 22.10.2
Launching `https://github.com/maxulysse/nextflow_3500` [ridiculous_boyd] DSL2 - revision: ab4fcf2292 [main]
[85/edc96a] process > STAGE (SRR6357071_1.fastq.gz) [100%] 7 of 7, cached: 7 ✔
/home/max/workspace/nextflow_3500/work/98/7a2969b84463307e99e1c00a4d7521/SRR6357076_1.fastq.txt
/home/max/workspace/nextflow_3500/work/cc/14b31944fb5899bd7af21592f8d164/SRR6357074_1.fastq.txt
/home/max/workspace/nextflow_3500/work/9f/cb78b1e9fd5e115e3fb1d13297ca20/SRR6357070_1.fastq.txt
/home/max/workspace/nextflow_3500/work/ae/70724892be6a2199e557fc37566b03/SRR6357073_1.fastq.txt
/home/max/workspace/nextflow_3500/work/a6/0bb888857e57093f120f3c08bc2029/SRR6357075_1.fastq.txt
/home/max/workspace/nextflow_3500/work/85/edc96a9ae8402c81fdaecea92a8429/SRR6357071_1.fastq.txt

Completed at: 15-Dec-2022 15:42:48
Duration    : 1m 50s
CPU hours   : (a few seconds)
Succeeded   : 0
Cached      : 7
```

**Comment by bentsherman** [comment]
I wasn't able to reproduce it... I ran your minimal example (which I see downloads from S3), and for me it took seconds on both initial and resume.

Makes me wonder if I'm getting lower latency because I'm in the US? Is the `s3://nf-core-awsmegatests` in a US region?

**Comment by maxulysse** [comment]
Can you try within the gitpod from the seqera training (https://gitpod.io/#https://github.com/seqeralabs/nf-training-public) or the codespace from the advance training (https://github.com/seqeralabs/nf-training-advanced Code> create codespace on master)
@robsyme had issues with that yesterday I believe

**Comment by bentsherman** [comment]
Okay, I tried again in Codespaces and now I'm seeing the issue. Inital and resumed runs both take ~2 min. After running with `-trace nextflow` and comparing the trace logs, most of the time on the resumed run is spent caching the tasks, basically each cached task takes as long to recover as it did to run in the first place.

Based on the logs, I think these two lines point to the bottleneck:
```
Dec-15 20:44:28.638 [Actor Thread 1] TRACE nextflow.file.FilePorter - Stage foreign files: nextflow.file.FilePorter$Batch@53002412
Dec-15 20:44:39.265 [Actor Thread 1] TRACE nextflow.util.CacheHelper - Hashing file meta: path=/nf-core-awsmegatests/rnaseq/input_data/minimal/GSE110004/SRR6357070_1.fastq.gz; size=2239317, lastModified=1633041615000, mode=STANDARD
```

If you run with trace enabled, you will see these two lines for each input file, followed by a bunch of waiting. While trying to recover a task, the FilePorter will compute some hashes that depend on the input file's attributes:

```java
// CacheHelper::hashFile(hasher, path, mode)
            attrs = Files.readAttributes(path, BasicFileAttributes.class);

// CacheHelper::hashFileMetadata(hasher, file, attrs, mode)
        hasher = hasher.putUnencodedChars( file.toAbsolutePath().toString() );
        if( attrs != null ) {
            hasher = hasher.putLong(attrs.size());
            if( attrs.lastModifiedTime() != null && mode != HashMode.LENIENT ) {
                hasher = hasher.putLong( attrs.lastModifiedTime().toMillis() );
            }
        }
```

Thanks to the `S3FileSystem` that Nextflow injects, the `readAttributes()` turns into an API call to S3 under the hood.

The fact that S3 latency is so much lower on my laptop, even without the cache, makes me think that these cloud dev environments just have generally higher latency to external services like S3. Nextflow still has to ping S3 for metadata in order to recover cached tasks, so I could see this causing slowdowns, especially if the problem is high latency rather than low bandwidth.

I would suggest trying a more basic latency/bandwidth test by downloading some files from S3 with the `aws` CLI. For example, download one of the input files directly, then query its metadata, and compare the walltime.
