### ISSUE TITLE
Unable to use secrets in the includeConfig directive

### ISSUE THREAD

**Issue by markpanganiban** [nextflow-io/nextflow#3502]
We would like to be able to use config from a separate private repository and use it within the includeConfig context. This is possible if we pass the pat/token to the raw URL link but that means exposing the token on the raw text file. We tried to run this using secrets but it doesn't look like the includeConfig directive is able to parse/access the content of the secret.

```
Unable to parse config file: '/Users/mlpanganiban/nf/nextflow.config'

  Illegal character in query at index 85: https://raw.githubusercontent.com/markpanganiban/nf-test/master/ubuntu.config?token=${token}


------


Unable to parse config file: '/Users/mlpanganiban/nf/nextflow.config'

  Compile failed for sources FixedSetSources[name='/groovy/script/Script3B7B1D673C896BC4338945B5D6A2FB78/_nf_config_c782925a']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  /groovy/script/Script3B7B1D673C896BC4338945B5D6A2FB78/_nf_config_c782925a: 51: Unexpected character: '\' @ line 51, column 100.
     aster/ubuntu.config?token=' + \${TOKEN}
                                   ^
```

**Comment by bentsherman** [comment]
You are right, the problem is with comparing group keys to other objects. It works when the groupkey is on the left-hand side but not when it's on the right:

```groovy
v = 'BATCH1'
gk = groupKey(v, 3)

println v == gk // false
println gk == v // true
```

I don't know if there is a way to override the equals from the right-hand side...

**Comment by bentsherman** [comment]
Sorry, commented on the wrong thread...
