### ISSUE TITLE
Use of files in bin folder (third party scripts) on Docker runs

### ISSUE THREAD

**Issue by jameswagner** [nextflow-io/nextflow#3503]
I've been able to follow the instructions for running third party scripts described here https://www.nextflow.io/docs/latest/sharing.html when submitting Nextflow jobs to AWS Batch. However in local runs on docker.enabled = true, where we're pulling the process's Docker image from our ECR repository, I've not been able to get this to work, I consistently get a File not found error. 

Just wanted to confirm are third party scripts supported with Docker runs and there is some configuration or setup I'm missing, or is this only with Cloud systems?

**Comment by pditommaso** [comment]
Yes, this is supposed to work also for local run

**Comment by jameswagner** [comment]
Thanks for confirming. I think I see the issue, when I submitted this job to aws the `main.nf` I was running was in the same folder as `bin`. The local runs were for tests, so I would cd to the directory that contains `bin` and then run a command like `nextflow run ./test/main.nf` 

There a config or parameter I could specify the location of the `bin` directory, since it seems to be looking for it in under `test` in this case?

**Comment by mribeirodantas** [comment]
You can add your custom `bin` location to the `$PATH` using the [scope env in Nextflow](https://www.nextflow.io/docs/latest/config.html#scope-env). You can run the pipeline below to see the `$PATH` you have in your machine right now:
```
process PRINT_PATH {
  debug true
  output:
    stdout
  script:
  """
  echo $PATH
  """
}

workflow {
  PRINT_PATH()
}
```

Then, you can create a `nextflow.config` file in the same directory and add the following content:
```
env.PATH = "$PATH:/my/custom/bin/location"
```

Now, if you run the same pipeline, you'll see `/my/custom/bin/location` added to your path, which means scripts in there will be accessible to Nextflow.
