### ISSUE TITLE
Grid Engine: Nextflow Engine not properly tracking compute job qdel'ed while in qw

### ISSUE THREAD

**Issue by akraymund** [nextflow-io/nextflow#3506]
## Bug report 

We've observed a bug where the nextflow engine is not properly tracking that a task was` qdel`ed while it is in `qw` status. The nextflow engine keeps waiting forever on the` qdel`ed job to be scheduled, but it will never be scheduled, because the job was deleted.

This issue has already been addressed in nextflow tower for submitting the head job.  A similar fix should be applied to nextflow engine for the child jobs.

> Therefore I think the only way to capture this state is to change the status check command from qstat -q <NAME> to qstat only, so that the jobs in qw status are returned and correctly handled.

### Expected behavior and actual behavior

The expected behavior is for the nextflow engine to terminate if one of the child jobs was qdel'ed

### Steps to reproduce the problem

1. Alter the hello-world nextflow pipeline so that the child job has clusterOptions set to something that will cause it to linger in `qw`.  On our cluster this was `-l vf=2000G -l m_mem_free=2000G`.
2. qdel the job that is in `qw`

### Environment 

* Nextflow version: 22.04.4
* Java version: 17.0.3+6-LTS 
* Operating system:  Linux 4.15.0-112-generic

**Comment by pditommaso** [comment]
To keep backward compatibility a possible solution could be to introduce configuration setting e.g. `executor.queueGlobalStatus` that when enabled check the job status for all queues i.e. uses `qstat` instead of `qstat -q <name>`. 

Would that work for you?

**Comment by akraymund** [comment]
Yes, I think that should work for us.

**Comment by pditommaso** [comment]
Excellent. Solved f3339541
