### ISSUE TITLE
xvfb-run waits forever when used in a nextflow process

### ISSUE THREAD

**Issue by TedBrookings** [nextflow-io/nextflow#3512]
### Expected behavior and actual behavior

We wanted to use xvfb-run igv !{batch_file} to allow igv to create a snapshot of an event on a headless AWS instance. Expected behavior is that xvfb-run will create a virtual framebuffer and igv will use it to paint the snapshot. Actual behavior is that xvfb-run waits forever after creating the Xvfb server.

The reason is that Xvfb communicates back by sending SIGUSR1, which should kill a `wait` in `xvfb-run`. But nextflow traps (and ignores) USR1 in `.command.run`, which causes the `wait` to last forever.

### Steps to reproduce the problem

This process file produces the problem, and it should do so with pretty much any input.
[(Provide a test case that reproduce the problem either with a self-contained script or GitHub repository)](https://github.com/pact-pharma/pact-pipeline/blob/7dd51a26c9c6c257e3a1a61f8ac1f39dea513eb4/src/pipeline/nextflow/modules/igv/igv_track.nf)

### Program output 

Under normal circumstances there is NO output to stderr or stdout. If I call `xvfb-run` via `bash -x`, the last executed command is the exec command from this block
```
    trap : USR1
    (trap '' USR1; exec Xvfb ":$SERVERNUM" $XVFBARGS $LISTENTCP -auth $AUTHFILE >>"$ERRORFILE" 2>&1) &
    XVFBPID=$!

    wait || :
```
The `wait` command never ends.

### Environment 

* Nextflow version: 22.04.0
* Java version: 1.8.2
* Operating system: ubuntu 18.04
* Bash version: GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)

**Comment by TedBrookings** [comment]
I should mention that we have a work-around right now: We basically wrote our own version of `xvfb-run`, and replaced the `wait` with `sleep 5`. But it took awhile to figure out the problem and test and implement the work-around.

**Comment by pditommaso** [comment]
This has been done on purpose. See https://github.com/nextflow-io/nextflow/issues/1753#issuecomment-708202196. 

you can remove the trap from within your script. See https://bash.cyberciti.biz/guide/How_to_clear_trap.

**Comment by TedBrookings** [comment]
@pditommaso
This is not correct. As listed in [the documentation for trap](https://man7.org/linux/man-pages/man1/trap.1p.html), traps that are ignored on entry to a subshell _cannot_ be cleared. Here is a very simple example workflow that only requires a linux system with xvfb-run installed
```
nextflow.enable.dsl=2

process waitFor {
    '''
    # clear trap for SIGUSR1
    trap - USR1
    xvfb-run xset -q
    '''
}

workflow {
  waitFor()
}
```
When run in nextflow, this process hangs, despite clearing the USR1 trap. If you manually run the generated `.command.sh`, it will succeed. If you run the `.command.run`, it will fail. If you doubt that the trap is the cause, you can comment out the `trap '' USR1` in `.command.run` and that script will now succeed.

An option to simply never set that trap is required for any process that uses xvfb-run.
