### ISSUE TITLE
Add support for Fusion file system for Singularity containerised task 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3513]
### Context 

The [Fusion file system](https://www.nextflow.io/docs/latest/fusion.html) allows using S3-compatible object storage as the task work directory. 

This feature requires mounting the Fusion driver in the container process via a Fuse device. 

When using docker or podman this can be achieved using the following options 

```
--device /dev/fuse --cap-add SYS_ADMIN 
```

See #3337 for details 

### Goal

The goal of this feature is to allow the use of Fusion driver in containers run via the Singularity and Apptainer engines.

**Comment by pditommaso** [comment]
This issue requires adding in the above snippet the singularity options needed to run the fusion driver with the support for FUSE 

https://github.com/nextflow-io/nextflow/blob/d22337cd9e7391aa9112eb1a4e775103a45659da/modules/nextflow/src/main/groovy/nextflow/container/ContainerConfig.groovy#L87-L96

**Comment by jordeu** [comment]
The current problem is that the way of running fusion with singularity is like:

```
singularity exec <options> docker://<image> /opt/fusion/fusionfs <command>
```
so it's not part of the options, is a pre-command that works as an entrypoint.

**Comment by pditommaso** [comment]
Never a joy

**Comment by pditommaso** [comment]
I think what it could be done is to introduce a `FusionOptions` class in place of using a string here 

https://github.com/nextflow-io/nextflow/blob/827ee97e7132ad64989a68f4a3e30befc71676e4/modules/nextflow/src/main/groovy/nextflow/fusion/FusionHelper.groovy#L53-L53

Then it can be used to customise the exec option by the `SingularityBuilder`. What do you think?

**Comment by jordeu** [comment]
Yes, that seems the less intrusive option. 

An other option can be to undo the [entrypoint](http://github.com/nextflow-io/nextflow/blob/827ee97e7132ad64989a68f4a3e30befc71676e4/modules/nextflow/src/main/groovy/nextflow/container/ContainerBuilder.groovy#L78-L79) deprecation. 

At the end now to use fusion means to use it as entrypoint, in some builders (like docker, podman) the concept exists and we pass it as an option, in the others it means to prepend it before the real command. It should work on all of them in the same way. 

Maybe the only problem of this option is that then the user can override it.

**Comment by pditommaso** [comment]
Yes, all the point was to delegate Wave the handling of the entrypoint

**Comment by jordeu** [comment]
But with singularity we cannot do that because the `singularity exec` ignores the docker image entrypoint and the `singularity run` uses it but then you cannot change the image defined `command` so the command `singularity run docker://...` it is always equivalent to `singularity exec docker://... <docker_entrypoint> <docker_command>`.

See: https://docs.sylabs.io/guides/latest/user-guide/singularity_and_docker.html#cmd-entrypoint-behaviour

**Comment by pditommaso** [comment]
I know but it's a singularity-specific problem not supporting the entrypoint.

**Comment by jordeu** [comment]
Ok, so @pditommaso which approach you think is better:

1. to encapsulate this logic into an options class like `FusionOptions`

2. or, to resurrect the old `entrypoint` attribute and let all the builders use it.

**Comment by pditommaso** [comment]
Think 1 for general design and use 2 only at Singularity level

**Comment by jordeu** [comment]
Ok, I'll give it a try this week.

**Comment by pditommaso** [comment]
Considering Fusion now works as launcher app, I think the `bash -c` (see below) can be replaced by the fusion binary. 

https://github.com/nextflow-io/nextflow/blob/10cf414bc451bf8a43f0776db8f754b2252366c6/modules/nextflow/src/main/groovy/nextflow/fusion/FusionAwareTask.groovy#L63-L63


This would have two befits: 1) avoid having a special CLI command for singularity, and 2) not require any more to set Fusion as the entrypoint in the Wave container. 

@jordeu what do you think?

**Comment by pditommaso** [comment]
Ok. i'll check using 

```
 return ['/opt/fusion/fusion','bash','-o','pipefail','-c', cmd.toString() ] 
```

**Comment by pditommaso** [comment]
WORKS!

**Comment by pditommaso** [comment]
Wait still the wave entrypoint is taking place

**Comment by jordeu** [comment]
> Wait still the wave entrypoint is taking place

What do you mean? `singularity exec` is not using the entrypoint

**Comment by pditommaso** [comment]
NOW REALLY WORKS!

**Comment by jordeu** [comment]
For Singularity? Why?

**Comment by pditommaso** [comment]
For all. Because nextflow adds it to the CLI

**Comment by pditommaso** [comment]
Oops a new problem 

```
java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException: java.io.IOException: Cannot store Singularity image to a remote work directory -- Use a POSIX compatible work directory or specify an alternative path with the `NXF_SINGULARITY_CACHEDIR` env variable
	at nextflow.container.SingularityCache.getCachePathFor(SingularityCache.groovy:354)
	at nextflow.container.ContainerHandler.createSingularityCache(ContainerHandler.groovy:97)
	at nextflow.container.ContainerHandler.normalizeImageName(ContainerHandler.groovy:72)
	at nextflow.container.resolver.DefaultContainerResolver.resolveImage(DefaultContainerResolver.groovy:44)
	at io.seqera.wave.plugin.resolver.WaveContainerResolver.resolveImage(WaveContainerResolver.groovy:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.jav
```
