### ISSUE TITLE
Pipeline mysteriously hanging

### ISSUE THREAD

**Issue by santiagorevale** [nextflow-io/nextflow#352]
Hi there!

I'm working on a pipeline where I cannot understand why it hangs. I reduced it as much as possible to be able to debug it, but I couldn't understand what's going on. Any help would be really appreciate it. It's a simple script calling a JSON configuration file.

Here's how I execute it:
```bash
nextflow run tilt.nf -params-file tilt.json
```

Here's the content of the JSON file:
```json
{
  "mkfastq": [
    { "mkfastqId": "HXXXXXXXX_1", "lane": 1 },
    { "mkfastqId": "HXXXXXXXX_2", "lane": 2 }
  ],
  "count": [
    { "projectId": "ProjectA", "sampleId": "Sample1", "lane": 1, "fastqPath": "" },
    { "projectId": "ProjectA", "sampleId": "Sample2", "lane": 1, "fastqPath": "" },
    { "projectId": "ProjectA", "sampleId": "Sample3", "lane": 2, "fastqPath": "" },
    { "projectId": "ProjectB", "sampleId": "Sample4", "lane": 2, "fastqPath": "" }
  ]
}
```

Here's the code:
```groovy
#!/usr/bin/env nextflow

def ch_mkfastq_in = Channel.create()
params.mkfastq.each { row ->
  ch_mkfastq_in << [row.mkfastqId, row.lane]
}

def ch_params_in = Channel.create()
params.count.each { sample ->
  ch_params_in << [sample.lane, sample.fastqPath, sample.projectId, sample.sampleId]
}

process mkfastq {
  echo true
  input:
    set mkfastqId, lane from ch_mkfastq_in
  output:
    set lane, mkfastqId into ch_mkfastq_out
  script:
    """
    echo "${mkfastqId}"
    """
}

def ch_count_in = Channel.create()
ch_mkfastq_out
  .cross(ch_params_in)
  .map { mkfastq, count ->
    count[1] = mkfastq[1]
    return count
  }
  .into(ch_count_in)

process count {
  echo true
  input:
    set lane, fastqPath, projectId, sampleId from ch_count_in
  output:
    val sampleId
  script:
    """
    echo "${sampleId}"
    """
}

workflow.onComplete {
  println "bye"
}
```

Thank you very much in advance.

Cheers,
Santiago

**Comment by pditommaso** [comment]
The problem is that when you create a channel explicitly, you will need to close it other the dataflow network will never stop. For example: 

```
def ch_mkfastq_in = Channel.create()
params.mkfastq.each { row ->
  ch_mkfastq_in << [row.mkfastqId, row.lane]
}
ch_mkfastq_in.close()
``` 

Said that a more idiomatic (and save way) to handle this use case is the following 

```
ch_mkfastq_in = Channel.from(params.mkfastq) 
```

**Comment by santiagorevale** [comment]
Thanks, Paolo! The .close() do the trick. I thought the problem was related to open channels, but I didn't knew how to handle it.

Could you tell me in my previous example how could I replace both create/close with the Channel.from() way? I tried a few things but couldn't make it work.

By the way, do you have any "good practices" for properly writing pipelines?

Thanks for your quick reply!

**Comment by pditommaso** [comment]
Both `params.mkfastq` and `params.count` are list, thus you can pass as an argument to `Channel.from` as shown in my previous comment, or even better as below: 

```
ch_mkfastq_in  = params.mkfastq.channel()
ch_params_in  = params.count.channel()
```

**Comment by santiagorevale** [comment]
Oh, I understand now what happened. I was using both objects as arrays and after doing the channel thing they ended up as lists. The problem is that when I'm outputting a set from a process (```set lane, mkfastqId into ch_mkfastq_out```) it's creating an array and I'm trying to cross it with a list (```ch_mkfastq_out.cross(ch_params_in)```). 

I understand I can match arrays through the first position and lists using a key. So, what would it be the way to proceed in this case?

**Comment by pditommaso** [comment]
Sorry, I'm not getting the problem any more. Could you provide an example?

**Comment by santiagorevale** [comment]
Sure. In the example I posted on top, my goal is to ```cross``` two channels: ```ch_mkfastq_out``` which is the output of the ```mkfastq``` process, and ```ch_params_in``` which is a list loaded in the beginning from the JSON file. Here is the code:
```groovy
def ch_count_in = Channel.create()
ch_mkfastq_out
  .cross(ch_params_in)
  .map { mkfastq, count ->
    count[1] = mkfastq[1]
    return count
  }
  .into(ch_count_in)
```
However, to be able to cross these two channels, they would need to be of the same type. But ```ch_mkfastq_out``` behaves as an array while ```ch_params_in``` as a list. This is making this part of the code fail. My question then would be how to make this two channels cross easily?

In the original example I replaced
```groovy
def ch_mkfastq_in = Channel.create()
params.mkfastq.each { row ->
  ch_mkfastq_in << [row.mkfastqId, row.lane]
}

def ch_params_in = Channel.create()
params.count.each { sample ->
  ch_params_in << [sample.lane, sample.fastqPath, sample.projectId, sample.sampleId]
}
```
for
```groovy
ch_mkfastq_in = params.mkfastq.channel()
ch_params_in  = params.count.channel()
```

**Comment by pditommaso** [comment]
To cross two channels the emitted items should have a common matching key (not necessarily the first). Given your example: 

```
{
  "mkfastq": [
    { "mkfastqId": "HXXXXXXXX_1", "lane": 1 },
    { "mkfastqId": "HXXXXXXXX_2", "lane": 2 }
  ],
  "count": [
    { "projectId": "ProjectA", "sampleId": "Sample1", "lane": 1, "fastqPath": "" },
    { "projectId": "ProjectA", "sampleId": "Sample2", "lane": 1, "fastqPath": "" },
    { "projectId": "ProjectA", "sampleId": "Sample3", "lane": 2, "fastqPath": "" },
    { "projectId": "ProjectB", "sampleId": "Sample4", "lane": 2, "fastqPath": "" }
  ]
}
```

What is supposed to be the key in `mkfastq` matching the elements in `count`  ?

**Comment by santiagorevale** [comment]
The key between them would be ```lane```. I know I could also cross by a key. But when I tried this
```groovy
def ch_count_in = Channel.create()
ch_mkfastq_out
  .cross(ch_params_in) { it -> it.lane }
  .map { mkfastq, count ->
    count.fastqPath = mkfastq.fastqPath
    return count
  }
  .into(ch_count_in)
```
it threw the following error
```
ERROR ~ No such variable: Exception evaluating property 'lane' for java.util.ArrayList, Reason: groovy.lang.MissingPropertyException: No such property: lane for class: java.lang.Integer
Possible solutions: class
```

**Comment by pditommaso** [comment]
What about the following? 

```
params
    .mkfastq
    .channel()
    .map { row -> [row.lane, row.mkfastqId] }
    .set { mkfastq_ch }

params
    .count
    .channel()
    .map { sample-> [sample.lane, sample.fastqPath, sample.projectId, sample.sampleId] }
    .set { count_ch }
    
    
mkfastq_ch.combine(count_ch, by:0).println()   

```

It prints 

```
[1, HXXXXXXXX_1, , ProjectA, Sample1]
[1, HXXXXXXXX_1, , ProjectA, Sample2]
[2, HXXXXXXXX_2, , ProjectA, Sample3]
[2, HXXXXXXXX_2, , ProjectB, Sample4]
```

**Comment by santiagorevale** [comment]
That is close to the solution. But the problem is that I can't create the combination in advance because that way both processes will be launching at the same time. This is why I need to have the output of process ```mkfastq``` combined with the input from the JSON file.

However, I took your example and tried to adapt it to my case, but somehow is not combining anything. Here is the full code:
```groovy
#!/usr/bin/env nextflow

params
    .mkfastq
    .channel()
    .map { row -> [row.lane, row.mkfastqId] }
    .set { ch_mkfastq_in }

params
    .count
    .channel()
    .map { sample -> [sample.lane, sample.fastqPath, sample.projectId, sample.sampleId] }
    .set { ch_params_in }

process mkfastq {
  echo true
  input:
    set mkfastqId, lane from ch_mkfastq_in
  output:
    set lane, mkfastqId into ch_mkfastq_out
  script:
    """
    echo -e "mkfastqId: ${mkfastqId}\tlane: ${lane}"
    """
}

def ch_count_in = Channel.create()
ch_mkfastq_out
  .combine(ch_params_in, by: 0)
  .map { row ->
    row.removeAt(2)
    return row
  }
  .into(ch_count_in)

process count {
  echo true
  input:
    set lane, fastqPath, projectId, sampleId from ch_count_in
  output:
    val sampleId
  script:
    """
    echo "${sampleId}"
    """
}

workflow.onComplete {
  println "bye"
}
```

**Comment by santiagorevale** [comment]
Amazing! I've been through the code so many times that I forgot we change the order of that input.
Thank you very much for your help!
Cheers,
Santiago
