### ISSUE TITLE
False/impossible name collisions when using .collect() on input channel

### ISSUE THREAD

**Issue by robinfchan** [nextflow-io/nextflow#3526]
### Expected behavior and actual behavior

First time I've encountered something like this and have processed thousands of semi-unique file names in the past.

Basically the simpleName for each FASTQ file is used as prefix for generating a results dir for each process.

E.g. "SSID1115_96PLT2145_D09_AMPL_target_1.fq.gz" -> **analysis_main_()** -> "SSID1115_96PLT2145_D09_AMPL_target_1_editing_outcomes/<result files and sub dirs>"

which is then emitted by the process via:
```
    output:
    path("*_editing_outcomes"), type:'dir', emit: editing_outcomes
```

then passed to the next process:
```
    // experiment-wide results collection
    collect_results_( ch_checked_params.collect(),
                      analysis_main_.out.editing_outcomes.collect(),
                      ch_exp_report
                      )
```

and staged in the `collect_results_` process as:

```
    input:
    path(params_csv)
    path(editing_outcomes, stageAs: "per_sample_results/*")
    path(report)

```

While it is true there are three filename with largely the same prefix, i am 1000000% sure there are ZERO true name collisions. The file names triplets resemble:

```
SSID1115_96PLT2145_D09_AMPL_target_1.fq.gz
SSID1115_96PLT2145_D09_AMPL_target_2.fq.gz
SSID1115_96PLT2145_D09_AMPL_target_3.fq.gz

```

I've also confirmed each `analysis_main_` process completes successfully and DOES write results in it's appropriate scratch dir where the following DO exist in full:

```
<hashed scratch dir>/SSID1115_96PLT2145_D09_AMPL_target_1_editing_outcomes
<hashed scratch dir>/SSID1115_96PLT2145_D09_AMPL_target_2_editing_outcomes
<hashed scratch dir>/SSID1115_96PLT2145_D09_AMPL_target_3_editing_outcomes
```

I cannot figure out where the collision is occurring unless there is some string length restriction for .collect() or there is some bizarre splitting occurring?

Totally lost -- what am I missing? This has not caused issues with similarly formatted filenames in the past.

### Program output 

```
Error executing process > 'workflow_:collect_results_ (1)'

Caused by:
  Process `workflow_:collect_results_` input file name collision -- There are multiple input files for each of the following file names: per_sample_results/SSID1115_96PLT2145_D09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2144_H09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2144_D09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2144_A09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2145_H09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2145_C09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2145_G09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2144_G09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2144_F10_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2144_E09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2144_F09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2145_E10_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2144_E10_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2145_E09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2145_F10_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2145_F09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2144_C09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2145_B09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2144_B09_AMPL_target_1_editing_outcomes, per_sample_results/SSID1115_96PLT2145_A09_AMPL_target_1_editing_outcomes
```

### Environment 

* Nextflow version: 22.06.1.edge build 5712
* Operating system: Amazon Linux / AWS Batch

**Comment by pditommaso** [comment]
Please provide a self-contained example to replicate this

**Comment by robinfchan** [comment]
Sorry, false alarm. Tracked down the issue trying to package up an MRE for you. Long story short because of the highly similar filenames there were pipeline options clashing with one another resulting in soft-matches and thus duplicate DIRs spread across processes.
