### ISSUE TITLE
Kubernetes: outofmemory/cpu pods

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#3543]
Kubernetes version 1.22 and later changed behaviour of planning pods to nodes so a pod can get stuck in state `OutOfMemory` or `OutOfCPU`.  In this state, pod can be deleted only, I think there is no other way to deal with this situation. So, I suggest that nextflow deals with this in k8s executor, i.e., it removes pods in the mentioned state and resubmit. 

Any thoughts?

**Comment by bentsherman** [comment]
We added an automatic retry for these errors in #3239. See the manual commit at the end. Does that address your concern?

**Comment by xhejtman** [comment]
It seems so, but it needs to be backported - as it seems to be in latest version only that does not support dsl1 anymore. Right?

**Comment by pditommaso** [comment]
What version are you using?

**Comment by xhejtman** [comment]
I think 22.10.6 - latest that supports dsl1. But as we use our own docker images, I can backport it on my own.

**Comment by bentsherman** [comment]
Resolved by #3239 , now available in 23.04
