### ISSUE TITLE
Use of `Optional` in groovy classes breaks all caching

### ISSUE THREAD

**Issue by tfenne** [nextflow-io/nextflow#3544]
## Bug report 

I have a groovy class that has fields of type `Optional<Path>`, and when I use this as part of an input tuple to a process, it breaks all caching of the process.  If I change to us a nullable `Path` instead, everything works.

A pared down version of the class looks like:

```groovy
@ValueObject
@AutoClone
@Immutable(copyWith=true, knownImmutables=["r1_fastq", "r2_fastq", "ref_fasta", "aux_fasta"])
class Sample {
    String id
    String name
    Path r1_fastq
    Path r2_fastq
    Path ref_fasta
    Optional<Path> aux_fasta

    static {
        KryoHelper.register(Sample)
    }
}
```

Looking in the logs I find this:

```
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): java.util.Optional
```

In searching for a solution I see that nextflow uses a truly ancient version of kryo - version 2.24.0 published in January 2014.  And that kryo is up to 5.4.0 now.  I have to imagine using even a moderately more recent version probably would solve this, as `Optional` came in with JDK8 also in 2014, and it's usage has been pretty widespread since then.

### Expected behavior and actual behavior

Using the class above works as well as using a class with `Path` attributes, and cache/resume functionality works.

### Steps to reproduce the problem

1. Create a process that takes as one of it's inputs a groovy class that has a member of type `Optional<Path>` (or probably `Optional<String>` would have the same result), and a workflow that runs that process
2. Run the workflow with `-cache`
3. Run it again with `-resume`
4. 
### Program output 

See above 

### Environment 

* Nextflow version: 22.10.4
* Java version: 17.0.3
* Operating system: Linux
* Bash version: 4.2.46

### Additional context

(Add any other context about the problem here)

**Comment by bentsherman** [comment]
Would you be willing to submit a PR? It looks like all you need to do is update the version in `modules/nextflow/build.gradle`. You can build Nextflow locally and try it with your class.

**Comment by bentsherman** [comment]
Hi @tfenne I wasn't able to reproduce your error. Here's my minimal example:
```groovy
@ValueObject
@groovy.transform.AutoClone
@groovy.transform.Immutable(copyWith=true, knownImmutables=["path"])
class Sample {
    String id
    Optional<String> path

    static {
        nextflow.util.KryoHelper.register(Sample)
    }
}

process foo {
    input:
    val object

    """
    id=${object.id}, path=${object.path}
    """
}

workflow {
    obj = new Sample('id', Optional.of('path'))

    foo(obj)
}
```

Can you produce a full minimal example that produces the error?

**Comment by tfenne** [comment]
Thanks @bentsherman - I made a few changes to your example to bring it closer to what I had that was failing.  It started failing when I got to this:

```
@ValueObject
@groovy.transform.AutoClone
@groovy.transform.Immutable(copyWith=true, knownImmutables=["path"])
class Sample {
    String id
    Optional<Path> path

    static {
        nextflow.util.KryoHelper.register(Sample)
    }
}

process foo {
    input:
    tuple val(object), path(fastq)
    
    output:
    tuple val(object), path("*.txt")

    script:
    """
    touch ${object.id}.txt
    """
}

workflow {
    s1 = new Sample('s1', Optional.of(Path.of('/path')))
    s2 = new Sample('s2', Optional.of(Path.of('/path')))
    ch = Channel.of(
      [s1, Path.of("/tmp/some.fq.gz")],
      [s2, Path.of("/tmp/other.fq.gz")],
    )
    foo(ch)
}
```

The last change I made, which brought about the resume failure, was to simultaneously a) add the `output:` directive shown above, and b) swap to a `script:` block that generated an output file.

**Comment by tfenne** [comment]
Thanks for your help pinning this down @bentsherman - will look forward to that PR!

**Comment by bentsherman** [comment]
For posterity since this issue was auto-closed by the stale bot -- this issue will soon be moot anyway with the introduction of record types in Nextflow 26.04

Nextflow 25.10 already has support for nullable type annotations and nullable process inputs, so record types will build on that
