### ISSUE TITLE
Add support for rclone copy tool

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3549]
When a Nextflow pipeline uses a shared file system, the tasks work directory is allocated in the compute nodes local scratch disk, since it's expected to perform faster than the network-based file system. 

In those cases, the task output files are copied from the task scratch directory to the task work directory (ie. shared file system) using the standard `cp` command line tool. 

Other than the `cp` command nextflow allows using the other commands with the [process.stageOutMode](https://www.nextflow.io/docs/latest/process.html?highlight=stageout#stageoutmode) directive. 

The goal of this issue is to add support for [rclone](https://rclone.org/) tool for copying task output files via the use of the `stageOutMode` directive.

**Comment by pditommaso** [comment]
Solved by fde2ac27

**Comment by pditommaso** [comment]
This has been included in edge release [23.01.0-edge](https://github.com/nextflow-io/nextflow/releases/tag/v23.01.0-edge)

**Comment by abhi18av** [comment]
Oh, this is awesome - looking forward to using this feature!

**Comment by pditommaso** [comment]
Thanks Abhi! Bit different from what you were suggesting tho #1873

**Comment by abhi18av** [comment]
No worries P, I think that with the `fusionfs` (and minio) being in the equation now - it makes sense to only rely upon `rclone` as a _local_ file copy tool and have a minimal reliance on other tools.

Reading through the issue description again, maybe it's worth accommodating something like https://github.com/Svetlitski/fcp which is optimized for a filesystem specific copy operation?

**Comment by pditommaso** [comment]
Didn't know about `fcp`! feel free to submit a PR for it

**Comment by abhi18av** [comment]
Oki doki captain 😊
