### ISSUE TITLE
save conda logs

### ISSUE THREAD

**Issue by notestaff** [nextflow-io/nextflow#3551]
When Nextflow creates conda environments, could it pipe the stdout and stderr from the conda create command to some configurable log files, or perhaps to the standard Nextflow log?   This would help with monitoring and debugging the (sometimes error-prone) environment creation process.   Thanks!

**Comment by pditommaso** [comment]
Nextflow is already capturing the process stderr and reporting it in the error log. 

However, it could be that Conda is dumping more info to the stdout. I've improved it a bit to capture both stdout and stderr and report both of them to the error log. 

Solved by 7b19fb03.
