### ISSUE TITLE
Issue with outputting string variables containing equal sign (=)

### ISSUE THREAD

**Issue by HarryHung** [nextflow-io/nextflow#3553]
### Expected behavior and actual behavior

If I use output type `env` and the string variable contains a equal sign `=`, only the part before the `=` will be output, even though the whole string is captured in `.command.env`

I don't think this is the expected behaviour, as standard bash can have string variables containing `=`
```
OUTPUT_VAR='PART1=PART2'
echo $OUTPUT_VAR

PART1=PART2
```

### Steps to reproduce the problem

```
process TEST {
    output:
    env OUTPUT_VAR

    shell:
    '''
    OUTPUT_VAR='PART1=PART2'
    '''
}


workflow {
    TEST().view()
}
```

### Program output 

Terminal output:
```
PART1
```

Expected output:
```
PART1=PART2
```

### Environment 

* Nextflow version: 22.10.4
* Java version: OpenJDK 19.0.1
* Operating system: MacOS 12.6.2
* Bash version: zsh 5.8.1

### Additional context
@pditommaso suggests it is likely related to https://github.com/nextflow-io/nextflow/blob/c492ad227d77b729b3c951767395b83a95d0ff6f/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L1496-L1504

**Comment by pditommaso** [comment]
Solved by 40d56735

**Comment by HarryHung** [comment]
Thanks for the quick turnaround. 
The ETA of 23.04.0 will be April? Thanks.

**Comment by pditommaso** [comment]
yes for the stable release. we do also make a monthly edge release
