### ISSUE TITLE
Enable `executor` as a dynamic directive of a process

### ISSUE THREAD

**Issue by cariaso** [nextflow-io/nextflow#3561]
## New feature

Enable `executor` as a dynamic directive of a process
https://nextflow.io/docs/latest/process.html#dynamic-directives

## Usage scenario 

Ability to run cloud jobs, with heavy weight processes getting their own machines, but small tasks running on the launcher head node.

## Suggest implementation 

Is there any way to mix local and cloud execution? There are some trivial steps in a pipeline where the overhead to create an instance is heavier than the work to be done.  We could start the main nextflow process on a instance which would have access to the bucket.

So something like this:

```nextflow
process {
    executor = { task.attempt == 1 ? 'local' : 'awsbatch' }
    memory = { 6.GB * task.attempt} 
    errorStrategy = { task.exitStatus in 137..140 ? 'retry' : 'finish' }
}
```

Unfortunately under "Dynamic directives" the docs rule out `executor`, `label` and `maxForks`.
https://nextflow.io/docs/latest/process.html#dynamic-directives

What prevents `executor` from being dynamic?

original discussion:
https://nextflow.slack.com/archives/C03L6DMAN/p1673959182619999)

**Comment by mribeirodantas** [comment]
Maybe it's a misunderstanding on my side, but it seems to me you're talking about two different things at the same time.

> Ability to run cloud jobs, with heavy weight processes getting their own machines, but small tasks running on the launcher head node.

You can already do that. I can have tasks from process `FOO`, a very lightweight process, running locally, while tasks from process `BAR`, very heavy, are run on AWS Batch. There's nothing dynamic here, all tasks from process `FOO` will run locally, and all instances of process `BAR` will run on AWS Batch.

The dynamic aspect that is discussed in the documentation is related to the tasks. Run tasks from process `FOO` locally, but if they fail for reason X or Y, run them on AWS Batch, for example. This is a different scenario from what you described in _Usage scenario_, and I'm not sure it's really something people would do. Could you please share with us one use case where that would be necessary?

**Comment by bentsherman** [comment]
@mribeirodantas He's talking about using different executors for different tasks of the same process. See his example -- the first attempt is run locally, and any subsequent attempts are offloaded to AWS Batch.

**Comment by bentsherman** [comment]
I don't see why a dynamic executor wouldn't work, probably just requires some things to be rewired. I could be missing something.

I do wonder about one task depending on an upstream task that used a different executor and resides in a different work directory, but that is true for the static hybrid execution, and it seems to work.

I am mostly curious to see if others would find this feature useful.

**Comment by mribeirodantas** [comment]
Yeah, we followed the discussion on Slack. The confusion here was the difference between some parts of the issue, talking about processes and then tasks and so on. It's clear now and there are some nice examples they shared on the thread. Details here: https://nextflow.slack.com/archives/C03L6DMAN/p1673959182619999

**Comment by ewels** [comment]
Still valid

**Comment by bentsherman** [comment]
For anyone who wants to implement this feature...

Currently the `TaskProcessor` (i.e. each process) has a fixed executor. To make the executor dynamic for each task, you would need to remove the executor from the `TaskProcessor` and retrieve it from `TaskConfig`. The task config part should just work already, but then you have to refactor every place in `TaskProcessor` that uses the executor to instead fetch the executor from a specific task.

**Comment by pditommaso** [comment]
The `executor` cannot be dynamic because task execution logic depends on it, as highlighted by Ben.

**Comment by NishikaGolani** [comment]
This is a real pain point. Submitting a 2-second task to AWS Batch and waiting 45+ seconds for instance provisioning defeats the purpose.

One architectural approach that helps: running your Nextflow head job inside the same Kubernetes cluster that handles execution. With a Slurm-on-K8s setup, lightweight tasks execute on already-warm nodes with sub-second scheduling latency, while heavy tasks trigger Karpenter to provision dedicated spot instances. You get the "local feel" for small tasks with cloud elasticity for big ones — all through a single Slurm executor.

This is how we set things up at Clusterra (https://clusterra.cloud/). The head node runs alongside a small pool of warm nodes for fast-path tasks, and Karpenter handles burst capacity. Avoids the need for the dynamic executor directive entirely since all scheduling goes through one fast path. Happy to share benchmarks on scheduling latency if useful.

Contact : 
mail to : hello@clusterra.cloud
