### ISSUE TITLE
docs on converting to/from MemoryUnit (and similar)

### ISSUE THREAD

**Issue by nick-youngblut** [nextflow-io/nextflow#3567]
## New feature

As far as I can tell, the [Nextflow docs](https://www.nextflow.io/docs/latest/index.html) do not contain any information about converting to/from the `nextflow.util.MemoryUnit` (or similar Nextflow classes). It would be helpful if some official docs were included. 

## Usage scenario 

Is this a good way of converting a `task.memory` value to an integer:

```
task.memory.toString().replaceFirst(/ .+/, '').toInteger()
```

For another example: What is the best way of converting a `file.size()` value (bytes; integer) to a `MemoryUnit`? This is useful to setting the memory for the process job (e.g., set memory required to the size of the reference database file).

***

I would submit a PR, but I do not know the best-practices for such scenarios.

**Comment by bentsherman** [comment]
We will make sure to document the MemoryUnit API as part of the ongoing docs overhaul.

In the meantime, you can extract the numeric value of a MemoryUnit using methods like `toGiga()`, `toMega()`, and `toBytes()`, and you can create a MemoryUnit from bytes value using `MemoryUnit.of(file.size())`

Source: https://github.com/nextflow-io/nextflow/blob/master/modules/nf-commons/src/main/nextflow/util/MemoryUnit.groovy
