### ISSUE TITLE
A function creating a channel can only be a Factory method - Plugins

### ISSUE THREAD

**Issue by nvnieuwk** [nextflow-io/nextflow#3572]
## New feature

For now functions returning a `DataFlow` type are only recognized as factory methods. But I'm trying to create a function that creates a channel from a non-channel input. Is it somehow possible to add a feature for this? Or to let me bypass the checks implemented that cause this function to not be recognized as a function?

## Usage scenario 

To create functions that can create channels in plugins

**Comment by mribeirodantas** [comment]
I'm probably missing something, but why don't you want a function that creates a channel to be a channel factory? 😅

**Comment by nvnieuwk** [comment]
Yeah I noticed that after doing some digging :grin:. I changed it to that but I can't seem to access the channel factory in my test pipeline. Is there some documentation you can link me to for writing plugins? :)

**Comment by nvnieuwk** [comment]
Thank you! I'll do that :)
