### ISSUE TITLE
`TaskPath.name` includes directory from `stageAs:`

### ISSUE THREAD

**Issue by julibeg** [nextflow-io/nextflow#3574]
### Expected behavior and actual behavior

When staging an input file in a subdirectory with `input: path x, stageAs: 'my-dir/*'`, then `x.name` gives `my-dir/filename` instead of just `filename`.

### Steps to reproduce the problem

```
process my_proc {
    input: path x, stageAs: 'my-dir/*'
    script:
    print(x.name)
    """
    """
}

workflow {
    Channel.fromPath('my-file.txt')
    | my_proc
}
```

### Program output 

```
N E X T F L O W  ~  version 22.10.6
Launching `test.nf` [loving_saha] DSL2 - revision: 978d464ef2
executor >  local (1)
[a9/f4d7cf] process > my_proc (1) [100%] 1 of 1 ✔
my-dir/my-file.txt
```

### Environment 

* Nextflow version: 22.10.6
* Java version: openjdk version "17.0.3-internal" 2022-04-19
* Operating system: Ubuntu
* Bash version: GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

**Comment by bentsherman** [comment]
It looks like TaskPath just has a slightly different API from Path. The `getName()` method returns the entire filename. You can get the base name with `x.fileName.name`.

I will make a note to document TaskPath in the Nextflow docs.

**Comment by julibeg** [comment]
I see, thanks for clarifying!

**Comment by julibeg** [comment]
is `x.fileName.name` preferred over `x.alias`?

**Comment by bentsherman** [comment]
Yes, `x.alias` is equivalent to `x.name` so it's not what you want.
