### ISSUE TITLE
Add support for Fusion file system to Google Batch executor

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3575]
The goal of this feature is to add the support for Fusion file system to the Google Batch executor. 

This essentially requires extending the [GoogleBatchTaskHandler](https://github.com/nextflow-io/nextflow/blob/827ee97e7132ad64989a68f4a3e30befc71676e4/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L46-L46) in such a way that it implements the [FusionAwareTask](https://github.com/nextflow-io/nextflow/blob/827ee97e7132ad64989a68f4a3e30befc71676e4/modules/nextflow/src/main/groovy/nextflow/fusion/FusionAwareTask.groovy#L32-L32) trait

**Comment by bentsherman** [comment]
Closed by #3577
