### ISSUE TITLE
Weblog not sent to localhost anymore

### ISSUE THREAD

**Issue by aivo0** [nextflow-io/nextflow#3578]
## Bug report 

Localhost address with a port cannot be used to receive workflow execution metadata.

### Expected behavior and actual behavior

I can send weblogs to localhost on my other machine with the -with-weblog command line option e.g.  `nextflow -with-weblog http://localhost:7700/log`
This however does not work on my newer machine. At the same time sending to an https address works. In the /etc/hosts file localhost is mapped to 127.0.0.1 and substituting localhost with the IP aadress does not help.

Old machine where this works:
Nextflow version: 20.10.0
OS: Linux, Ubuntu 20.04 LTS
Java version: openjdk version 1.8.0_352

### Steps to reproduce the problem

Execute any Nextflow script with the following commandline option `nextflow -with-weblog http://localhost:7700/log` while having a local server listening to POST request on the localhost:7700 port. Probably the environment has to mach also to the one described below.

### Environment 

* Nextflow version: 22.10.5
* Java version: openjdk 11.0.17 2022-10-18
* Operating system: Linux (Pop!_OS 22.04 LTS)
* Bash version: (use the command `$SHELL --version`) GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

**Comment by bentsherman** [comment]
Could you share the error trace from your nextflow log?

Also, does it work if you specify `http://127.0.0.1:7700/log` ?

**Comment by aivo0** [comment]
I updated the issue description, seems I have been using -with-weblog http://localhost:7700/log so using http is not the problem. This is from a codebase I last touched in July last year and now found to not work anymore on the new machine but it still works on the old machine. 

I have no error trace to share as the (automatic speech transcription) workflow completes successfully. It is just that no requests are being made to my localhost server. When I substitute the URL with a public HTTPS address then the request are being sent.

Using http://127.0.0.1:7700/log does not help and I checked that on this machine localhost is mapped to this IP.

**Comment by bentsherman** [comment]
What about `http://0.0.0.0:7700/log` ?

**Comment by aivo0** [comment]
Already tried, same issue. 
I can replicate with a simple Hello World script https://github.com/nextflow-io/hello when running it with the same option.
Of cause, making a curl request to the localhost address works so I'm sure that the web server is working correctly.
Also tried running nextflow with NXF_VER=20.10.0 and upgraded Java to openjdk version "18.0.2-ea" 2022-07-19 so I am quite out of ideas now.

**Comment by bentsherman** [comment]
Okay, I tried to reproduce the problem with Java 17 and Nextflow 22.10.5. I started a web server in one tab and ran the `hello` pipeline in another:
```bash
http-server .
nextflow run hello -with-weblog http://localhost:8080`
```

But my web server did receive the POST requests from Nextflow, so I wasn't able to reproduce your problem.

**Comment by aivo0** [comment]
I was also able to get it working with http-server and after that switched the original web server to 0.0.0.0 and now it receives the weblogs. Thank you for your help!
