### ISSUE TITLE
Is it possible to combine watchPath and fromFilePairs

### ISSUE THREAD

**Issue by chuckpr** [nextflow-io/nextflow#358]
Wondering if you have a recipe for generating a file pairs channel from the `watchPath` channel? 

`DADA2`, for example, requires non-interleaved files but I'd like to trigger a `DADA2` QC pipeline each time a pair of files lands in the directory observed by `watchPath`.

**Comment by pditommaso** [comment]
Yes, it's possible even not directly by using `fromFilePairs` but you will need to chain some operators to mimic what `fromFilePairs` is doing. For example: 

```
params.pairs = 'your/glob/pattern/here'
Channel
    .watchPath( params.pairs )
    .map { path -> 
       def prefix = readPrefix(path, params.pairs)
       tuple(prefix, path) 
    }
    .groupTuple(size: 2, sort: true)
    .println()
```

The secret sauce here the  `readPrefix` function that given a file path and glob pattern string extract the file name prefix that will be used to match and group the file pairs. For example: 

```
def readPrefix( Path actual, template ) {

    final fileName = actual.getFileName().toString()

    def filePattern = template.toString()
    int p = filePattern.lastIndexOf('/')
    if( p != -1 ) filePattern = filePattern.substring(p+1)
    if( !filePattern.contains('*') && !filePattern.contains('?') ) 
        filePattern = '*' + filePattern 
  
    def regex = filePattern
                    .replace('.','\\.')
                    .replace('*','(.*)')
                    .replace('?','(.?)')
                    .replace('{','(?:')
                    .replace('}',')')
                    .replace(',','|')

    def matcher = (fileName =~ /$regex/)
    if( matcher.matches() ) {  
        def end = matcher.end(matcher.groupCount() )      
        def prefix = fileName.substring(0,end)
        while(prefix.endsWith('-') || prefix.endsWith('_') || prefix.endsWith('.') ) 
          prefix=prefix[0..-2]
          
        return prefix
    }
    
    return null
}    
```

This is how the file pairs where grouped where this logic has been consolidated in the `fromFilePairs` operator. See [here](https://github.com/nextflow-io/rnatoy/blob/21308aba42b02679e1dcf6d4d49b20e26d818b6f/main.nf#L53-L62) for example.

**Comment by chuckpr** [comment]
Ah, perfect, thanks! I will give it a shot.

**Comment by pditommaso** [comment]
I'm closing this issue. Feel free to comment below if needed.
