### ISSUE TITLE
Process termination can throw a ConcurrentModificationException hiding the error cause message

### ISSUE THREAD

**Issue by jdidion** [nextflow-io/nextflow#359]
Scenario: Nextflow dies with a ConcurrentModificationException, with no indication as to what is wrong. I go into the log and see several lines before the exception:

May-30 15:36:49.465 [main] DEBUG nextflow.Session - Session aborted -- Cause: Channel `machineMerged` has been used as an input by more than a process or an operator

This message is much more useful than the one that is actually printed. It seems like this "Session aborted" event should through an exception and be printed to the console, rather than the downstream ConcurrentModificationException.

**Comment by pditommaso** [comment]
Well, this is not supposed to happen. Can you include the complete stack trace. Also I've not understood if you solved the problem.

**Comment by jdidion** [comment]
I did solve the problem. It turns out I was using the same channel in two different processes, so it was a bug in my script. But having a more helpful error message could make it easier to diagnose such bugs. The log is attached.

**Comment by jdidion** [comment]
[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/1039524/nextflow.log.txt)

**Comment by pditommaso** [comment]
Oh, this a very unexpected condition that prevented the cause message to be reported correctly. Thanks for your feedback.

**Comment by jdidion** [comment]
I'm very good at generating very unexpected conditions :)

**Comment by pditommaso** [comment]
LOL
