### ISSUE TITLE
Line break in a process tag

### ISSUE THREAD

**Issue by vmikk** [nextflow-io/nextflow#3597]
## Bug report 

Hello!
I have a composite (comma-separated) parameter, which should be supplied to a function via a single argument (e.g., `--x "a,b,c,d,e"`). In Nextflow, I created a channel containing all the values, with every single entry emitted separately.

### Expected behavior and actual behavior

Expected behavior: Nextflow processes each channel value and shows a tag in a screen output.

Actual behavior: If tag is specified, Nextflow fails with error. Without a tag, everithing is OK.

### Steps to reproduce the problem

Simple example:

``` bash
cat > test.nf <<'EOT'
#!/usr/bin/env nextflow

params.x = "a,b,c,d,e"

process proc {

    tag "$ind"

    input:
      val  ind

    output:
      path "res.txt"

    script:
    """

    echo ${ind} > "res.txt"

    """
}

workflow {

  ind_ch = Channel.value( params.x )
    .splitText( { it.split(',') } )
    .distinct()
    .flatten()

  proc(ind_ch)

}

EOT

nextflow run test.nf
```

### Program output 

When running a pipeline, Nextflow fails with the following error:
```
.command.run: line 3: syntax error near unexpected token `)'
```

It happened because there is a line break after a tag name in `.command.run`, and line 3 starts with `)`:
```
#!/bin/bash
# NEXTFLOW TASK: proc (e
)
set -e
set -u
...
```

If we comment out the tag and run the script, everything works as expected:
``` bash
sed 's/tag/\/\/tag/' test.nf > test_ok.nf
nextflow run test_ok.nf
```

### Environment 

* Nextflow version: 22.10.6 build 5843
* Java version: openjdk 17.0.3-internal 2022-04-19
* Operating system: Linux
* Shell version: zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

**Comment by mribeirodantas** [comment]
Hello, @vmikk. [In the documentation](https://www.nextflow.io/docs/latest/operator.html#splittext), it is stated the:

> Text chunks returned by the splitText operator are always terminated by a \n newline character.

So this behavior is expected, not really a bug.

**Comment by mribeirodantas** [comment]
Hello, @vmikk. [In the documentation](https://www.nextflow.io/docs/latest/operator.html#splittext), it is stated the:

> Text chunks returned by the splitText operator are always terminated by a \n newline character.

So this behavior is expected, though `.command.run` should be prepared for that 😬. I think it's fair to consider this a bug, so I will add the tag.
