### ISSUE TITLE
Handle suspended SLURM jobs

### ISSUE THREAD

**Issue by sveint** [nextflow-io/nextflow#36]
I haven't experienced this myself, so this might be invalid, but SLURM can suspend jobs on a cluster if a high-priority job comes in. This might become a real situation for us in the future, which is why I am concerned about this. The job then goes into the suspended state, indicates by the `S` flag, as indicated here https://computing.llnl.gov/linux/slurm/squeue.html.

I looked into the code, and there's no handling of the `S` flag.

I cannot test a fix myself, unfortunately, but to me it seems to be safe to treat the S flag same as running, meaning Nextflow should keep waiting for it to finish?

**Comment by pditommaso** [comment]
Yes, you are right. I'm going to add this in the SLURM executor. 

Thanks for reporting that.

**Comment by pditommaso** [comment]
Support for *suspended* status flag has been added since version `0.12.4`
