### ISSUE TITLE
Nextflow crashes due to empty workdir

### ISSUE THREAD

**Issue by alex-d13** [nextflow-io/nextflow#3610]
### Expected behavior and actual behavior

When I start my nextflow pipeline, it crashes after a few processes, due to a `unknown reason`. When i checked the log files, it seems like the workdir is missing some files, and I dont understand how this can happen.

### Steps to reproduce the problem

Cannot really reproduce the error, I think there might be an issue with my installation or config?

### Program output 

[nextflow.log](https://github.com/nextflow-io/nextflow/files/10613795/nextflow.log)

### Environment 

* Nextflow version: 22.10.1 build 5828
* Java version: 11.0.17 
* Operating system: ubuntu 20.04.5
* Bash version: 5.0.17(1)

### Additional context

I am quite certain that the same setup worked just a few days ago (of course there can always be something I have missed).

I am using nextflow with a Docker container and slurm as executor on a private cloud cluster, so its only myself you is working on it. Still, I am kind of lost why this error is happening, I tried to restart slurm a few times already but that also did not help.
Any help here would be highly appreciated!

Cheers,
Alex

**Comment by bentsherman** [comment]
Most of the errors in your log are downstream of the fact that the task failed. You should inspect the files in the task directory for any clues. You can also run the task script yourself:
```bash
cd /vol/omnideconv/work/15/df7f6318169f2b7f7e744288ab0db3
sbatch .command.run
```

**Comment by pditommaso** [comment]
Unable to replicate
