### ISSUE TITLE
'params.enable_conda true' doesn't work

### ISSUE THREAD

**Issue by DzmitryGB** [nextflow-io/nextflow#3611]
Trying to run sarek pipeline with a custom config. Relevant lines from modified nextflow.config:
```
profiles {
    vm03 {
        params.enable_conda = true
        env.conda = "/home/xxx/miniconda3/condabin/conda"
        conda.cacheDir = "/disk2/xxx/conda_envs/"
    }
}
```
The nextflow itself was installed from conda (version 22.10.4 build 5836), sarek pipeline pulled from github. Trying to run 
```
nextflow run ~/pipelines/sarek/main.nf -profile vm03 --input ~/pipelines/sarek/samplesheet.csv --outdir /disk3/xxx/GATK --genome null --igenomes_ignore --fasta /disk2/xxx/genome/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta --save_reference true --skip_tools baserecalibrator
```
generates errors like '.command.sh: line 2: gatk: command not found'.

Expected behavior would be creating a conda environment first, activating it and then trying to run the module tool. Instead, conda seems to be completely ignored. Content of the .command.sh:
```
#!/bin/bash -euo pipefail
gatk --java-options "-Xmx36g" CreateSequenceDictionary \
    --REFERENCE Homo_sapiens_assembly38.fasta \
    --URI Homo_sapiens_assembly38.fasta \
    --TMP_DIR . \


cat <<-END_VERSIONS > versions.yml
"NFCORE_SAREK:SAREK:PREPARE_GENOME:GATK4_CREATESEQUENCEDICTIONARY":
    gatk4: $(echo $(gatk --version 2>&1) | sed 's/^.*(GATK) v//; s/ .*$//')
END_VERSIONS
```

Config splash at the beginning of the pipeline run confirms that conda is enabled. I've successfully created an example environment from nextflow environment using command `/home/xxx/miniconda3/condabin/conda create --prefix /disk2/xxx/conda_envs/bwa-mem2 bioconda::bwa-mem2=2.2.1`

Any pointers would be very welcome!

**Comment by bentsherman** [comment]
Have you checked with the folks at [nf-core/sarek](https://github.com/nf-core/sarek)?

**Comment by DzmitryGB** [comment]
> Have you checked with the folks at [nf-core/sarek](https://github.com/nf-core/sarek)?

No, I haven't. The reason I think this is not pipeline-specific is that the conda specs live inside nfcore modules, that are re-used by many different pipelines. The example line is `conda (params.enable_conda ? "bioconda::bwa-mem2=2.2.1" : null)`, which should evaluate to `conda bioconda::bwa-mem2=2.2.1` which, in turn, should check if the conda env is available and, if not, create it.

I'll try to test using a different version of nextflow. A much older version used to work for me (different pipeline).

**Comment by bentsherman** [comment]
Okay, we can look into it here if you want. You should check the `.command.run` instead of `.command.sh`, because the former will contain all of the conda boilerplate.

**Comment by DzmitryGB** [comment]
nextflow v21.10.6 creates conda environments fine, using exactly the same pipeline and command as before with v22.10.4

**Comment by bentsherman** [comment]
Can you show the difference between your `.command.run` in both cases? The conda boilerplate should be inserted in the `nxf_main` function at the bottom.

**Comment by mribeirodantas** [comment]
@DzmitryGB Can you try running this pipeline with `-with-conda` at the end?

**Comment by DzmitryGB** [comment]
> Can you show the difference between your `.command.run` in both cases? The conda boilerplate should be inserted in the `nxf_main` function at the bottom.

You're right, it is nf-core issue! I've created a minimal example workflow (something I should have done before posting here, apologies), and v22.10.4 worked fine with `conda.enabled = true` in the config (@mribeirodantas ).

**Comment by mribeirodantas** [comment]
Great to hear, @DzmitryGB ! Thanks for letting us know it works now.

**Comment by hukai916** [comment]
I used Nextflow version `23.10.0.5889` and the nf-core `chipseq` pipeline with `-profile conda`, it failed immediately since "fastqc" can not be found. Add `-with-conda` to the command worked by creating the needed conda environment first. It is mysterious to me why the profile option did not work.

**Comment by bentsherman** [comment]
@hukai916 I would notify the chipseq maintainers that they should use `conda.enabled` instead of `params.enable_conda` in their pipeline
