### ISSUE TITLE
Possible support for fixed paths

### ISSUE THREAD

**Issue by leipzig** [nextflow-io/nextflow#3613]
Hello. I am writing to inquire if there is a way to designate a path as fixed, so it should be treated as a `val` but validated to exist as a path.

## Usage scenario 

[TileDB](https://github.com/TileDB-Inc/TileDB) is designed to append fragments to S3-compliant stores using the multi-part upload API of the AWS C++ SDK. So although the path to a TileDB array is a real S3 path, it should never be copied onto individual nodes or EBS drives.

## Suggest implementation 

`fixed(filePath)` are validated to exist as paths but are not localized to disks.

**Comment by pditommaso** [comment]
My understanding is that you want to use TileDB in a Nextflow process to access directly S3 files. To do so it should be `val` type instead of `path` to bypass the Nextflow file handling mechanism. 

Should that not be enough?

**Comment by leipzig** [comment]
I guess it really just comes down to validation and error checking vs taking a string at face value to be a valid S3 path that gets created and exists. When the empty TileDB array gets created (presumably in a nf task) the output of that task really is an s3 path which should be validated by the runner. I'm not sure just assuming the task always succeeds is good practice.

**Comment by pditommaso** [comment]
I see. However, Nextflow does very little checking on S3 path checking when using `path`, other than accessing it is needed. 

I guess TileDB does support the same ability over POSIX file interface. We are going to release soon a feature to access S3 files without downloading/uploading from/to the bucket.
