### ISSUE TITLE
Do not export user environment when submitting job to SGE-like batch scheduler

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#362]
Currently some batch scheduler executors (SGE, PBS, NGSII) export the all user environment variables when a job is submitted for execution by using the `-V` directive, while others (SLURM, LSF, HTCondor) do not. 

For consistency and to increase task isolation the user environment should not exported by default. User may choose to export by adding the `-V` flag in `clusterOptions` configuration setting.

**Comment by pditommaso** [comment]
@murphycj Snapshot `0.25.0-SNAPSHOT` is already out. You may want to give a try using the this command: 

```bash
NXF_VER=0.25.0-SNAPSHOT nextflow run .. etc
```

**Comment by murphycj** [comment]
Tested with a script with executor set 'sge'. Works!
