### ISSUE TITLE
Add instance template option to google batch

### ISSUE THREAD

**Issue by daigok** [nextflow-io/nextflow#3629]
Google Cloud Batch supports an instanceTemplate option. With this option, batch job will use a specified instance template to create a VM instance. However, current Google Cloud Batch plugin doesn't support this option.

See the details below :
https://cloud.google.com/batch/docs/reference/rest/v1/projects.locations.jobs#instancepolicyortemplate
https://cloud.google.com/batch/docs/create-run-job#create-job-instance-template

**Comment by pditommaso** [comment]
What is the main benefit of this feature? being able to use a custom VM? 

In any case, using this approach, the same template is applied to all processes (ask tasks) executed by the pipeline. This means they all have the same CPUs, mem, and other resource requirements. Not sure this is desirable.

**Comment by daigok** [comment]
The benefit of this feature is we can use a custom image. Sometimes we need an instance template like [https://cloud.google.com/batch/docs/create-run-job?hl=en#create-job-uses-mpi]. Some libraries are not delivered as a docker image, especially for non-open source softwares.

About resource requirements, yes, this option is not flexible.

**Comment by pditommaso** [comment]
I think this feature could be more useful having the possibility to specify this setting at the process level. 

What it could be done is to extend [machineType](https://www.nextflow.io/docs/latest/process.html#machinetype) directly to allow a special syntax to provide the instance template e.g. `process.machineType = 'template://<SOME NAME>` 

This will also make more clear the template overrides other resource settings, mitigating the concerns reported by @bentsherman. 

Thoughts?

**Comment by daigok** [comment]
What do you think about an `installGpuDrivers` option? We still need to add the option, even if we use `machineType`.

**Comment by pditommaso** [comment]
it's a bit out of the nextflow model, but I think it's still valuable to add it to cover the instance template use case.

**Comment by saberiato** [comment]
Any update on finalizing this feature?
I used machineType = 'template://<instance-name>' on Nextflow version 23.05.0-edge and got null error.

**Comment by bentsherman** [comment]
Solved by https://github.com/nextflow-io/nextflow/commit/df7ed294520ad2bfc9ad091114ae347c1e26ae96
