### ISSUE TITLE
Implicit variable `task` is not accessible in cached processes  

### ISSUE THREAD

**Issue by jdidion** [nextflow-io/nextflow#363]
I have enabled caching for all my processes. My workflow exited with an error, which I fixed, and then tried to resume with the '-resume' option. I get the following error:

<pre>
N E X T F L O W  ~  version 0.23.3
Launching `simulated.nf` [backstabbing_golick] - revision: cb2faaccf9
[warm up] executor > slurm
[3e/160787] Cached process > ExtractReads (1)
[0e/cb5b1d] Cached process > ExtractReads (3)
[fb/d3ccbb] Cached process > ExtractReads (2)
ERROR ~ Error executing process > 'Skewer (skewer_16_001_q0)'

Caused by:
  Cannot get property 'tag' on null object
</pre>

This might be due to the fact that I create tag names dynamically, e.g.

`tag { "skewer_${task.cpus}_${err}_q${qcut}" }`

The actual line the error occurs on is within that same process:

`
output:
set val("${task.tag}"), val(err), file(alns), file("${task.tag}.{1,2}.fq.gz")
`

**Comment by pditommaso** [comment]
Please include the error stack trace you can find in the `.nextflow.log` file.

**Comment by jdidion** [comment]
[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/1048382/nextflow.log.txt)

**Comment by pditommaso** [comment]
The problem is that the `task` object is not available when task is resumed. 

You can workaround the issue by declaring a variable for the tag value that you can use as output as well. For example: 

```
process foo {
  tag "$bar" 
  
  output: val(bar) into result_ch 
  script: 
  bar = "skewer_${task.cpus}_${err}_q${qcut}"
  """
  your_task
   """
   
}

**Comment by jdidion** [comment]
That works, thanks!
