### ISSUE TITLE
`rclone` as `stageOutMode` fails "silently" when `rclone` is not installed in the environment where Nextflow is launched

### ISSUE THREAD

**Issue by mribeirodantas** [nextflow-io/nextflow#3639]
## Bug report 

The environment where Nextflow is launched must have `rclone` installed if it's the `stageOutMode` chosen. If it's not installed, Nextflow will throw an error but an error that does not say clearly why it happened. It's possible that an experienced user may connect the dots, but I think we can do better.

### Expected behavior and actual behavior

When the user tries to set `rclone` as `stageOutMode` and `rclone` is not installed, Nextflow should say so.

### Steps to reproduce the problem

I wrote the following Nextflow script (`foo.nf`):
```
process FOO {
  stageOutMode 'rclone'
  scratch '/Users/mribeirodantas/foo'
  input:
    val x
  output:
    path 'FOO_out.txt'
  script:
    """
    echo $x > FOO_out.txt
    """
}

workflow {
  Channel
    .of(1..2)
    | FOO
}
```

### Program output 

Running it with `nextflow run foo.nf` and having `rclone` installed in the launch environment works fine. I get the following output:
```
➜  ~ nextflow run foo.nf
N E X T F L O W  ~  version 23.01.0-edge
Launching `foo.nf` [exotic_solvay] DSL2 - revision: 173540ba08
executor >  local (2)
[19/619cfa] process > FOO (1) [100%] 2 of 2 ✔

➜  ~ tree work
work
├── 07
│   └── d4422fa72c4dd5d8e02b16635326cb
│       └── FOO_out.txt
└── 19
    └── 619cfa4ead1ad2ae07edcdde1ccd6e
        └── FOO_out.txt
```

When I don't have `rclone` installed, I get:
```
➜  ~ nextflow run foo.nf
N E X T F L O W  ~  version 23.01.0-edge
Launching `foo.nf` [elated_babbage] DSL2 - revision: a7411d3ffa
executor >  local (2)
[9e/3763c8] process > FOO (1) [100%] 2 of 2, failed: 2 ✘
Error executing process > 'FOO (2)'

Caused by:
  Missing output file(s) `FOO_out.txt` expected by process `FOO (2)`

Command executed:

  echo 2 > FOO_out.txt

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /Users/mribeirodantas/work/5b/d736b4b1a9c4e511df4bd095589234

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Environment 

* Nextflow version: 23.01.0-edge.5834
* Java version: Groovy 3.0.14 on OpenJDK 64-Bit Server VM 17.0.3+7
* Operating system: macOS Ventura 13.2
* Bash version: zsh 5.8.1 (x86_64-apple-darwin22.0)

### Additional context

I tried creating a Docker container image with `rclone` and providing this image to the `FOO` process with `container myimage1` and it didn't work, confirming my hypothesis that `rclone` must indeed be installed in the head node/job environment.

**Comment by pditommaso** [comment]
This is somehow expected. In principle is user's responsibility to make sure this tool is installed in the compute node. Checking the existence could add too much overhead. 

Surely it should be added a note in the docs highlighting the need for this. 

However, it may be also the case to make the task error when this copy command fails, essentially removing the `|| true` below. Not sure about the rationale to keep it running 

https://github.com/nextflow-io/nextflow/blob/7a3ebc7d3b7be120e953ce21fa318f19ec655dd1/modules/nextflow/src/main/groovy/nextflow/executor/SimpleFileCopyStrategy.groovy#L187-L187

**Comment by mribeirodantas** [comment]
Cool, I think this is a good solution! Definitely, we shouldn't do checks for everything, every time, everywhere, but if a command fails, the user should be aware it failed 😬

**Comment by pditommaso** [comment]
Does not even the change the error message reported?

**Comment by abhi18av** [comment]
Maybe we should allow folks to specify the absolute path to `rclone` as an option? This way, we only have to check a specific path.

For example

```
  stageOutMode 'rclone', location: '/usr/local/bin/rclone'

```

What do you think?

**Comment by pditommaso** [comment]
Not sure. Think Marcel is right, if the copy fails the error should be reported

**Comment by mribeirodantas** [comment]
> Does not even change the error message reported?

No! I was surprised too 😞

**Comment by pditommaso** [comment]
This is a known limitation. Closing
