### ISSUE TITLE
Modification dates on Wave ContainerLayers are updated on every container build, maybe breaking resume

### ISSUE THREAD

**Issue by robsyme-seqera** [nextflow-io/nextflow#3652]
## Bug report 

It looks like Wave changes the way that the bin directory is handled. Instead of copying in the contents of bin into each task, it looks like Wave (cleverly) adds a new layer in the returned container image where the files in bin are copied into /usr/local/bin. This is great because it means one less thing to do in the task via a command line call.

My concern is that every time the bin/* files are copied into a new layer, the modification date of those files also change, which means that the container image fingerprint also changes, and because this container fingerprint is included in the Task hashing, all resume functionality breaks for tasks using Wave containers.

I have a minimal reproducible example at robsyme/nf-test:wave-fingerprint-test. Two runs with -dump-hashes:

[Run A here](https://tower.nf/orgs/seqeralabs/workspaces/testing/watch/4qSnDAR3PYSFLo)
[Resumed (but not cached) run B here](https://tower.nf/orgs/seqeralabs/workspaces/testing/watch/1q0oFQ0R6X7nr5)

### Expected behavior and actual behavior

I would expect the second resumed run to used cached tasks, but in both tasks, it is recalculated afresh.

The `dumpHashes` indicates that the container fingerprint is causing the problem:
![image](https://user-images.githubusercontent.com/120426569/219375789-fb2c1f53-9917-4294-9318-365390bed9b0.png)

The first run (left above), hash container fingerprint `1ae9e708dad5fa0f3f68872dc37e00cf`:

```
Feb-16 02:12:13.854 [Actor Thread 3] DEBUG io.seqera.wave.plugin.WaveClient - Wave request: https://wave.seqera.io/container-token; attempt=1 - request: 
SubmitContainerTokenRequest(
    towerAccessToken:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NjA0IiwibmJmIjoxNjc2NTEzMjQ4LCJyb2xlcyI6WyJ1c2VyIl0sImlzcyI6InRvd2VyLWJhY2tlbmQiLCJleHAiOjE2NzY1MTY4NDgsImlhdCI6MTY3NjUxMzI0OH0.S1By6_ECMoTti-xMqpuhXhotR0xEpsQ1lVEbYn3NLn0, 
    towerRefreshToken:eyJhbGciOiJIUzI1NiJ9.ZjdmNWVkMTYtMjQyOC00YWM3LWJjOTgtMDNmZmE5MGYzZjIw.X0cyRtymj7k-gaqLoDo7WF0FXEQ2RxVK9pOG9RCTOOY, 
    towerWorkspaceId:34830707738561, 
    towerEndpoint:https://api.tower.nf, 
    containerImage:quay.io/biocontainers/perl:5.26.2, 
    containerFile:null, 
    containerConfig:ContainerConfig(
        entrypoint:[/opt/fusion/entrypoint.sh], 
        cmd:null, 
        env:null, 
        workingDir:null, 
        layers:[
            ContainerLayer(
                location:data:H4sIAAAAAAAA/ystLtLPyU9OzNFPyszTLy4tYKA+MDA0MDA3NVUwgAB02sDA2ETB0MTY3NjY0MDYHChuaGJmZMygYEADt2CA0uKSxCIGA4Oi/PwSfOoIyaN7jqqOpB1QVgRHfFJicQYXV2pyRr6CEjAR6CioGCoqDbTbRsEoGAWjYBTQDgAA++4eQAAIAAA=, 
                gzipDigest:sha256:bdd384e7ed2bfd92b28bfc90a90da9be7a63488f9aaf343b32f4427d54acf7ed, 
                gzipSize:143, 
                tarDigest:sha256:740adfd476ddd222914274053fbbb063a0bd279cc274eb0612504d2247100a0a, 
                skipHashing:null
            ), 
            ContainerLayer(
                location:https://fusionfs.seqera.io/releases/pkg/0/6/1/fusionfs-amd64.tar.gz, 
                gzipDigest:sha256:96e3114e585f4531f530ceedadcaaae4c3e65ea522f22d31b51ce6c6b23ed1f1, 
                gzipSize:6188614, 
                tarDigest:sha256:35df22acfd96be7b3973e03ce576bb199bd48285546ac2d6138ad8f033b19191, 
                skipHashing:true
            )
        ]
    ), 
    condaFile:null, 
    containerPlatform:null, 
    buildRepository:null, 
    cacheRepository:null, 
    timestamp:2023-02-16T02:12:13.852311358Z, 
    fingerprint:1ae9e708dad5fa0f3f68872dc37e00cf
)
```

and the run on the right has fingerprint `3b057bd54973b9dd71565365eaa415af`:

```
Feb-16 02:16:55.194 [Actor Thread 3] DEBUG io.seqera.wave.plugin.WaveClient - Wave request: https://wave.seqera.io/container-token; attempt=1 - request: 
SubmitContainerTokenRequest(
    towerAccessToken:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0NjA0IiwibmJmIjoxNjc2NTEzNzY5LCJyb2xlcyI6WyJ1c2VyIl0sImlzcyI6InRvd2VyLWJhY2tlbmQiLCJleHAiOjE2NzY1MTczNjksImlhdCI6MTY3NjUxMzc2OX0.oLR8eA8zfU8kZqWehtnjnnbEiRja385-rmGiaTqwluE, 
    towerRefreshToken:eyJhbGciOiJIUzI1NiJ9.YmUwYTVjZGEtYzNlMy00YjY0LTljOTAtNDdkYWZjNTIxYzk5.ZjpIivL75CkDZ8tzGffaJ1eJD6E9eBxbR5HnreBhuf0, 
    towerWorkspaceId:34830707738561, 
    towerEndpoint:https://api.tower.nf, 
    containerImage:quay.io/biocontainers/perl:5.26.2, 
    containerFile:null, 
    containerConfig:ContainerConfig(
        entrypoint:[/opt/fusion/entrypoint.sh], 
        cmd:null, 
        env:null, 
        workingDir:null, 
        layers:[
            ContainerLayer(
                location:data:H4sIAAAAAAAA/+3SMQ6DMAwF0MycwtCOlfLdJOU8ASGBhEiVkPtTtRuV2oWIxW/xYA/fsnOKeg69n3U3LTrlpzoeGGidI3zsK2AssTWtMcy4M4Htg50iFMjyJafVRwXEENZfc//6++UODVnOpX4fvvNprKqhHwM1rye40ZXr5uxsQgghytkAIgPClAAIAAA=, 
                gzipDigest:sha256:ebc328ec31637cc056b036e4227a435bbe99c29f765d0e5ba06761a9e4cbe851,
                gzipSize:143, 
                tarDigest:sha256:1d4e42655243d147e9b3981bbfe55bec24fa3cb86a0756d95df7dfd2e076ee38, 
                skipHashing:null
            ), 
            ContainerLayer(
                location:https://fusionfs.seqera.io/releases/pkg/0/6/1/fusionfs-amd64.tar.gz, 
                gzipDigest:sha256:96e3114e585f4531f530ceedadcaaae4c3e65ea522f22d31b51ce6c6b23ed1f1, 
                gzipSize:6188614, 
                tarDigest:sha256:35df22acfd96be7b3973e03ce576bb199bd48285546ac2d6138ad8f033b19191, 
                skipHashing:true
            )
        ]
    ), 
    condaFile:null, 
    containerPlatform:null, 
    buildRepository:null, 
    cacheRepository:null, 
    timestamp:2023-02-16T02:16:55.192442551Z, 
    fingerprint:3b057bd54973b9dd71565365eaa415af
)
```

The two ContainerLayers have different data, even though they are pulling from the same repository at the same commit:
![image](https://user-images.githubusercontent.com/120426569/219377283-d4567cf0-b3e6-4941-9f6b-cdf63ccb7b2c.png)

If I take these base64-encoded tar files and compare them, we see that the modification dates have changed. For the run on the left, the `sup` file is modified at `15 Feb 21:12`

```shell
$ data=H4sIAAAAAAAA/ystLtLPyU9OzNFPyszTLy4tYKA+MDA0MDA3NVUwgAB02sDA2ETB0MTY3NjY0MDYHChuaGJmZMygYEADt2CA0uKSxCIGA4Oi/PwSfOoIyaN7jqqOpB1QVgRHfFJicQYXV2pyRr6CEjAR6CioGCoqDbTbRsEoGAWjYBTQDgAA++4eQAAIAAA=
$ tar -tzvf <(echo $data | base64 -d -i -)
-rwxr-xr-x  0 root   root       28 15 Feb 21:12 usr/local/bin/sup
```

And the run on the right is modified at `15 Feb 21:16`
```shell
$ data=H4sIAAAAAAAA/+3SMQ6DMAwF0MycwtCOlfLdJOU8ASGBhEiVkPtTtRuV2oWIxW/xYA/fsnOKeg69n3U3LTrlpzoeGGidI3zsK2AssTWtMcy4M4Htg50iFMjyJafVRwXEENZfc//6++UODVnOpX4fvvNprKqhHwM1rye40ZXr5uxsQgghytkAIgPClAAIAAA=
$ tar -tzvf <(echo $data | base64 -d -i -)
-rwxr-xr-x  0 root   root       28 15 Feb 21:16 usr/local/bin/sup
```

### Steps to reproduce the problem

Run any workflow *on Tower* that includes a bin directory using Wave (the `wave-fingerprint-test` branch of robsyme/nf-test works well) and then resume the run. The task caches will not be used. 

### Environment 

* Nextflow version: [?] 
* Java version: [?]
* Operating system: [macOS, Linux, etc]
* Bash version: (use the command `$SHELL --version`)

**Comment by pditommaso** [comment]
I'm not able to replicate the problem 

```
» nextflow run . -with-docker  -ansi-log false
N E X T F L O W  ~  version 22.10.6
Launching `./main.nf` [romantic_roentgen] DSL2 - revision: f3572fb8ab
[e2/aea20c] Submitted process > Sup (1)
[34/ebac50] Submitted process > Sup (2)
sup, Paolo!
sup, Jordi!


» nextflow run . -with-docker  -ansi-log false -resume
N E X T F L O W  ~  version 22.10.6
Launching `./main.nf` [admiring_boyd] DSL2 - revision: f3572fb8ab
[34/ebac50] Cached process > Sup (2)
[e2/aea20c] Cached process > Sup (1)
sup, Jordi!
sup, Paolo!

» nextflow run . -with-docker  -ansi-log false -resume
N E X T F L O W  ~  version 22.10.6
Launching `./main.nf` [sad_hypatia] DSL2 - revision: f3572fb8ab
[34/ebac50] Cached process > Sup (2)
[e2/aea20c] Cached process > Sup (1)
sup, Jordi!
sup, Paolo!

» nextflow run . -with-docker  -ansi-log false -resume
N E X T F L O W  ~  version 22.10.6
Launching `./main.nf` [marvelous_kare] DSL2 - revision: f3572fb8ab
[e2/aea20c] Cached process > Sup (1)
[34/ebac50] Cached process > Sup (2)
sup, Jordi!
sup, Paolo!

```

Are you on Mac or Linux?

**Comment by pditommaso** [comment]
The fingerprint is computed using the name, size, last update timestamp and permission of each file in the bundle. 

https://github.com/nextflow-io/nextflow/blob/23d47ded0ca33cfe51a78a96940577392fb1fed8/modules/nextflow/src/main/groovy/nextflow/script/bundle/ResourcesBundle.groovy#L166-L175

That metadata should not change overtime, therefore I'm not getting how this can happen

**Comment by robsyme** [comment]
Switching back to my main account.

I'm not able to reproduce it running locally either, but the cache misses when running on Tower.
See run A [dreamy_bartik](https://tower.nf/orgs/seqeralabs/workspaces/testing/watch/4qSnDAR3PYSFLo), and resume B [dreamy_bartik_2](https://tower.nf/orgs/seqeralabs/workspaces/testing/watch/1q0oFQ0R6X7nr5).

Runs should be accessible to Seqera, but logs files are attached here for convenience.

[dreamy_bartik_2.log](https://github.com/nextflow-io/nextflow/files/10774675/dreamy_bartik_2.log)
[dreamy_bartik.log](https://github.com/nextflow-io/nextflow/files/10774676/dreamy_bartik.log)

**Comment by pditommaso** [comment]
Ouch, I know! Because when launching from tower those files are downloaded
in the container each time, and therefore have new timestamp 🤦‍♂️

**Comment by pditommaso** [comment]
Fixed b59fa728 (hopefully). Thanks for the great troubleshooting 👍

**Comment by robsyme** [comment]
Thanks Paolo! I'll looking forward to one day beating you to a fix 😆.

**Comment by pditommaso** [comment]
You did! https://github.com/nextflow-io/nextflow/pull/3466#issuecomment-1427095576 😄
