### ISSUE TITLE
beforeScript not run before conda directive

### ISSUE THREAD

**Issue by dpryan79** [nextflow-io/nextflow#3653]
### Expected behavior and actual behavior

The general purpose of the `beforeScript` directive in a process is to initialize whatever sort of environment might be required before the process itself is run. This step is (quite understandably) run outside of any containers on the host system. However it seems that the `conda` directive is run before `beforeScript`, meaning that one can't use `beforeScript` to initialize conda environments (consider deployments on systems physically removed from the internet where this may be required). Since `beforeScript` is run outside of container environments, I would have expected that the `conda` directive is also handled after it's run.

### Steps to reproduce the problem

The following is an example workflow demonstrating this. Note that `params.CONDA_DIR` would be the directory to some conda installation (i.e., environments would typically be created under ${CONDA_DIR}/envs):

```nextflow 
reads = Channel.fromFilePairs('data/*_{1,2}.fastq.gz')
CONDA_DIR = params.CONDA_DIR

workflow {
  someProcess(reads)
  someProcess.out.someOutput.view()
}

process someProcess {
  beforeScript "$projectDir/conda_env_setup"
  /* beforeScript "touch $projectDir/got_here" */
  conda "${CONDA_DIR}/envs/some_environment"

  input:
    tuple val(sampleName), path(reads)
  output:
    tuple val(sampleName), path("*.txt"), emit: someOutput

  """
    touch ${sampleName}.txt
  """
}
```

Here `$projectDir/conda_env_setup` needs to be run to ensure that `${CONDA_DIR}/envs/some_environment` exists. For the sake of testing, one can uncomment the alternative `beforeScript` to see that `got_here` is not created and therefore the script was not run.

### Program output 

```
Error executing process > 'someProcess (3)'

Caused by:
  Conda prefix path does not exist or is not a directory: /u/dryan/miniconda3/envs/some_environment
```

### Environment 

* Nextflow version: 22.10.4
* Java version: 17.0.3
* Operating system: Linux
* Bash version: 4.4.20

### Additional context

Perhaps I'm missing something simple here :)

**Comment by dpryan79** [comment]
Reading through the code I wonder if this is intended, since the cache is a key that's used in the process hash. I assume this needs to be precomputed due to `-resume`. Should the beforeScript be run regardless of whether the process itself is skipped or should the beforeScript simply not be used to ensure things like conda environments will be available for the main process?

**Comment by pditommaso** [comment]
Consider using Conda packages in container environment via [Wave](https://www.nextflow.io/docs/latest/wave.html#build-conda-based-containers). This would bypass the need to initialize the Conda environment
