### ISSUE TITLE
Azure private registry credentials are not used with Azure Batch (nor NF Tower)

### ISSUE THREAD

**Issue by wikiselev** [nextflow-io/nextflow#3654]
## Bug report 

The pipeline fails with the following error message:
```
One or more container images specified are invalid
```

### Expected behavior and actual behavior

The pipeline should run well using a specified container.

### Steps to reproduce the problem

1. The pipeline worked well with local installations (not using docker).
2. I added Azure container registry credentials (together with all other required Azure credentials) to my Nextflow config following [these instructions](https://www.nextflow.io/docs/latest/azure.html#private-container-registry).
```
azure {
    registry {
        server = 'ACCOUNT.azurecr.io'
        userName = 'USERNAME'
        password = 'PASSWORD'
    }
}
```
3. I then specified my container in the pipeline:
```
process {
    container = 'ACCOUNT.azurecr.io/IMAGE:TAG'
    executor = 'azurebatch'
}
```
4. I ran my pipeline from a command line.

### Program output 

```
One or more container images specified are invalid
```

### Environment 

* Nextflow version: [22.10.6.5843] 
* Java version: [openjdk 11.0.17 2022-10-18]
* Operating system: [ubuntu]
* Bash version: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Additional context

1. Exactly the same error (`One or more container images specified are invalid`) occurs when I run the pipeline on Tower (I added Azure registry credentials to Tower using Tower instructions). After running the pipeline the credentials are shown with the status `Last activity: never`, which means they are not seen by the pipeline.
2. The following commands work well on my local machine:
```
docker login ACCOUNT.azurecr.io
docker pull ACCOUNT.azurecr.io/IMAGE:TAG
```
3. Exactly the same error (`One or more container images specified are invalid`) occurs when I run the pipeline with a non-existing container:
```
process {
    container = 'notreallyacontainer'
}
```

**Comment by pditommaso** [comment]
My understanding this is a problem related to Azure configuration. See for context https://nextflow.slack.com/archives/C02TPRRLCF4/p1676643534938409

**Comment by mahdi-dcs** [comment]
What was the resolution?

**Comment by mahdi-dcs** [comment]
@pditommaso could you please explain what's the solution for azure container registry? 

I have exact same setup as wikiselev mentioned and getting unauthorized error. I have double checked the registry and the credentials. Work just fine locally but seems like nextflow is not using the credentials.

**Comment by pditommaso** [comment]
After one year and half I have no idea about the context and the solution. Please provide a detailed bug reported in a separate issue (provided it's an issue) otherwise consider using community support channels.
