### ISSUE TITLE
Unable to specify  process.queue in HPC  node

### ISSUE THREAD

**Issue by jayramr** [nextflow-io/nextflow#3666]
Hello, 

I'm  running toga analysis using nextflow slurm excecutor -> https://github.com/hillerlab/TOGA/blob/master/nextflow_config_files/extract_chain_features_config.nf

In our HPC node, we don't have the option to specify partition/queue. As it will randomly choosing the partition based on the resources like CPU, Memory, time that we request. 

Please advise how can i run task using grid scheduler without passing the process.queue option. I already tested with commented the directive, I got the below 

```
Caused by:
  Failed to submit process to grid scheduler for execution

Command output:
  sbatch: error: Batch job submission failed: No partition specified or system default partition
```

Please advise 

Thanks
Jay

**Comment by bentsherman** [comment]
Hi @jayramr , that error message is coming directly from SLURM. Nextflow doesn't require the `queue` directive, so if you're getting this error, it means that your SLURM cluster requires a partition to be specified. If you're saying that you aren't allowed to specify a partition, then you should talk to your cluster admin.
