### ISSUE TITLE
Add support for dynamic each

### ISSUE THREAD

**Issue by qobilidop** [nextflow-io/nextflow#367]
This feature request comes from a [post](https://groups.google.com/forum/#!topic/nextflow/-gsJZ6kSgFc) in the Google Group. The idea is to enable using input variable in the `each` statement. For example, when the new feature is added, the following shall be possible:

```groovy
process loop {
    input:
    val n from n_ch
    each i from 1..n
}
```

Currently, this will cause an unknown variable error.

**Comment by qobilidop** [comment]
As a current workaround, instead of

```groovy
ch = Channel
    .from( ['a', 2], ['b', 3] )

process loop {
    input:
    set val(label), val(n) from ch
    each i from 1..n

    exec:
    println "${label}, ${i}"
}
```

one could do

```groovy
ch = Channel
    .from( ['a', 2], ['b', 3] )
    .flatMap {
        label = it[0]
        (1..it[1]).collect {
            [label, it]
        }
    }

process loop {
    input:
    set val(label), val(i) from ch

    exec:
    println "${label}, ${i}"
}
```

**Comment by pditommaso** [comment]
Unfortunately this is not possible because the dataflow model requires all inputs to be resolved in order to trigger the task execution, hence one of them cannot be a partial value.
