### ISSUE TITLE
Add closure functionality to `publishDir.enabled`

### ISSUE THREAD

**Issue by nvnieuwk** [nextflow-io/nextflow#3692]
## New feature

Hi! Thanks for using Nextflow and submitting the proposal 
for a new feature or the enhancement of an existing functionality. 

Please replace this text providing a short description of your 
proposal.

## Usage scenario 

In some cases it is useful to be able to specify a closure with the `publishDir.enabled` attribute. (e.g. I have a meta list in my channel which contains a count of files in one family and I want to only output files that have a count of 1, because the other files will be merged in the next process). Currently the workaround is to use a closure in `publishDir.saveAs` and not outputting anything when the condition isn't met, but this does still create the folder specified in `publishDir.path`. Therefore I think it would be a nice addition to add the option of adding closures to the `publishDir.enabled` attribute. 

Example in a config file:
```nextflow
withName: MODULE {
    publishDir = [
        enabled: { meta.count == 1 },
        path: { "${params.outdir}/${meta.id}" }
    ]
}
```

**Comment by bentsherman** [comment]
For what it's worth, you might be able to specify that condition in both `saveAs` and `path` so that it doesn't always create the folder.

**Comment by pditommaso** [comment]
Closing in favour of https://github.com/nextflow-io/nextflow/issues/4186

**Comment by bentsherman** [comment]
Not sure how #4186 will solve this issue, since this one is about allowing `enabled` to be dynamic where the new issue is about supporting global defaults.

**Comment by pditommaso** [comment]
You are right. Also, considering there's a workaround, I still believe it is preferable to avoid the proliferation of dynamic config settings

**Comment by bentsherman** [comment]
Agreed
