### ISSUE TITLE
Option to only create conda environments

### ISSUE THREAD

**Issue by jeskowagner** [nextflow-io/nextflow#3693]
## Create Conda Environments Only
I would like to propose a feature that only creates any specified conda environments without running the pipeline. Snakemake provides the option `--conda-create-envs-only`, which fulfills this aim.

## Usage scenario 
The main usage scenario is in a HPC environment: suppose I have a YAML that specifies dependencies that can be resolved on a worker but not the submission node, e.g. a library like pytorch-cuda. Conda will only solve this dependency correctly if the node has access to a GPU, which is unusal on a submission node. Currently, this can be circumvented by moving to the worker node, launching nextflow from there, waiting until the the conda environments have been solved, then terminate the process and logout of the node, before rerunning the pipeline from a submission node. While this works, you have to babysit the task to prevent jobs from being sent from the worker node (if that is allowed in your current HPC environment).

## Suggest implementation 
I currently do not have an implementation in mind.

**Comment by notestaff** [comment]
Could you first create a yaml file with all dependencies resolved, by logging into a worker node with a GPU, manually running conda create, then doing conda env export to a yaml, and then giving that yaml to nextflow?  Could this be done as a first step of the pipeline?

**Comment by jeskowagner** [comment]
Sure, I could create a yaml with all dependencies and/or a conda environment that has everything installed while on a GPU node. The issue with this is that nextflow will not recognise that this conda environment should be used, and will instead try to create it from the yaml. (at least I think so?)

**Comment by mribeirodantas** [comment]
I just want to point out that this is the preferred way of running Nextflow. That is, you shouldn't run Nextflow from the head/login node (see point 2 [here](https://www.nextflow.io/blog/2021/5_tips_for_hpc_users.html)). You should submit Nextflow, and then as a submitted job, Nextflow will submit other jobs. If this is not allowed in your HPC settings, then OK, you're left with running Nextflow from the login/head node 😅.

Besides, you can do what you want with a [stub](https://www.nextflow.io/docs/latest/process.html#stub). See the example below:

```
process FOO {
  debug true
  conda 'multiqc'
  script:
  """
  multiqc --help
  """
  stub:
  """
  """
}

workflow {
  FOO()
}
```

If you run this `-with-conda` it will create the conda environemnt and run the script block, as expected. But if you run with `-with-conda -stub` it will just create the conda environment.

**Comment by jeskowagner** [comment]
Thanks for the links! While I can run the job from a compute node, I would specifically need to reserve a GPU node, which is more costly than just running on a CPU compute node. Very cool to see the use of stubs here, but would this create the environment on the submission or the compute node?

**Comment by jeskowagner** [comment]
Right. So if I understand correctly I would

- Log in to a GPU node
- Run the stubbed processes to create the conda environments
- Log out of the GPU node
- Submit the jobs from a submission node

Correct? I suppose that is a good answer to my question. In an ideal world it would be great if nextflow could be given a directive that creates conda environments as a separate job with correct specifications. But I understand that this is likely out of scope and am happy to close this issue accordingly.

**Comment by mribeirodantas** [comment]
🥳
