### ISSUE TITLE
Process with input from non-existing channel doesn't give warning

### ISSUE THREAD

**Issue by sveint** [nextflow-io/nextflow#37]
I just had a situation where I removed some code, removing one of the input channels for a process.
What happened next is that my nextflow script would just sit there at the stage where it would normally launch said process, not giving any warning (that I can find) and not doing anything at all.

I have experienced similar issues before, so I know I had to check my channels, but for a person new to Nextflow such a thing can be quite confusing, or even a dealbreaker.

What I'm talking about is
```
process someProcess {
   input:
    file bam_file from bam_input
    file vcf_file from vcf_input
    file idx_file from idx_input  <-- channel doesn't exist anymore
    
    etc...

```

Can you confirm this behaviour? Is it possible to check consistency upon initialization and raise an exception in those cases?

**Comment by pditommaso** [comment]
I'm a bit confused here. If you reference in the input a not existing channel it will raise an exception. For example: 

    process foo {
      input:
      file x from y
  
      '''
      echo hello
      '''
    }

It throws: 
  
    groovy.lang.MissingPropertyException: Unknown variable 'y'

**Comment by sveint** [comment]
That sounds like proper behavior. However, I am sitting here with a script that I believe references a non-existing channel, yet I get no exception. I tried changing the channel name to something random, and still no exception.

I forgot to mention one perhaps important detail, which is that I am running the script with -resume option, so it skips 3-4 processes before coming to the process I just changed (to remove the channel). To clarify:

- I ran the script with all channels existing.
- One process crashed. I realized I didn't need one of the channels anymore. I removed the creation of that channel from the root of the script, but forgot to remove it from the `input` field in the process.
- I ran the script with -resume. It skipped the previously successful processes, until it came to the previously problematic one.
- As long as the channel that doesn't exist is referenced, the script just hangs, not executing the process at all. Nothing happens. I can't see anything special in the logs either.

I'm not sure I can share the script unfortunately, but the relevant part looks like this:

```
process qc {
    echo true
    clusterOptions "--account=[omitted] --time=3:00:00 --mem-per-cpu=2048 --cpus-per-task=2"
    scratch '$SCRATCH'
    errorStrategy 'retry'
    maxRetries 1

    input:
    file bam_file from bam_qc_input
    file vcf_file from vcf_qc_input
    file idx_file from idx_qc_input <-- Channel which I removed. I can put random name here, doesn't matter.
    output:
    file 'qc_result.json' into qc_result

   """
   bash script here
   """
```

**Comment by sveint** [comment]
I tried to create a simple script to reproduce the problem, but failed, so maybe I am just doing something stupid/illegal somewhere in my script.

**Comment by pditommaso** [comment]
Are you sure that it happens whatever the channel name is ?

**Comment by sveint** [comment]
Did some more testing. It's slightly more weird than I initially thought. I can insert any variable reference (random garbage name) into the process that I want, e.g:

```
process qc {
    asdasdal;sjdlakdajsdasd
    echo true
    clusterOptions "--account=[omitted] --time=3:00:00 --mem-per-cpu=2048 --cpus-per-task=2"
    scratch '$SCRATCH'
    errorStrategy 'retry'
    maxRetries 1

    input:
    file bam_file from bam_qc_input
    file vcf_file from vcf_qc_input
    file idx_file from idx_qc_input_asdlkajsdlashdkjasbdkajsgdkagsdjkhasgd
    output:
    file 'qc_result.json' into qc_result

   """
   bash script here
   """
}
```

and nothing happens. But as soon as I remove the non-existing references, the script works fine.
I also tried the following:

```
process qc {
    println "SOMETEXT"
    echo true
    clusterOptions "--account=[omitted] --time=3:00:00 --mem-per-cpu=2048 --cpus-per-task=2"
    scratch '$SCRATCH'
    errorStrategy 'retry'
    maxRetries 1

    input:
    file bam_file from bam_qc_input
    file vcf_file from vcf_qc_input
    file idx_file from idx_qc_input_asdlkajsdlashdkjasbdkajsgdkagsdjkhasgd
    output:
    file 'qc_result.json' into qc_result

   """
   bash script here
   """
}
```

SOMETEXT is printed once, when launching the script, so at least the code is run. However, in my simple test case, such a line is printed twice into the logs, once upon launching and once when the process is actually run. In my weird case, however, it's only printed once. Not sure what to make of that though.

In either case, this is probably so hard to debug I'm not sure if it's worth spending more time on.

**Comment by sveint** [comment]
Just some more input. Tried to create a simple script:

```
#!/usr/bin/env nextflow

sequences = file('testfile')

/*
 * split a fasta file in multiple files
 */
process test1 {
    echo true

    input:
    file 'whatever' from sequences

    output:
    file 'file1' into records
    file 'file2' into records2

    """
    touch file1
    touch file2
    echo "TEST1"
    """

}

/*
 * Simple reverse the sequences
 */
process test2 {
    println "TEST2 INIT!"

    input:
    file x from records
    file x2 from records2
    file x3 from non_existing

    output:
    stdout result

    """
    echo "TEST2"
    """
}

/*
 * print the channel content
 */
result.subscribe { println it }
```

which gives the following output:

```
N E X T F L O W  ~  version 0.12.0
[warm up] executor > local
TEST2 INIT!
[cb/f593b4] Cached process > test1 (1)
TEST1
ERROR ~ Not such variable: non_existing

 -- Check script 'test.nf' at line: 35 or see '.nextflow.log' file for more details
```

The error of missing variables doesn't seem to trigger until the point when the process is to be launched, which is long after the `println "TEST2 INIT"` taking place. I'm sure you have some explanation for that, but it might also give an indication on where in my code or Nextflow things are going wrong.

**Comment by pditommaso** [comment]
Yes, don't forget the nextflow processes are executed in an asynchronous manner. This mean that what your script execution does is to *parse* the process definitions sequentially but then launch them in parallel.  

I'm starting to think that in your original script there's some blocking code that stop the script before it reaches the `qc` process definition. This would explain why it does not report the error for the missing channel.

Are you using something like ``channel.val`` or ``channel.getVal()`` in your script ?

**Comment by sveint** [comment]
Figured it out. It didn't actually hang, after around 10 minutes it came back with the error. The VM I run it on in the cluster is a bit slow, but usually things are running fine, so this was a bit extreme. I don't do any sleeping in the code, so not sure what's up. When the 'qc' process is working it launches instantly, with no delay at all.

Anyways, sorry for wasting your time, and thanks for the support!

**Comment by pditommaso** [comment]
You are welcome :)
