### ISSUE TITLE
Feature request: Allow selection of multiple profiles

### ISSUE THREAD

**Issue by zichner** [nextflow-io/nextflow#370]
The possibility to define configuration profiles is really useful. However, a limitation is that currently only a single profile can be selected.

It would be great if multiple profiles could be selected, each one belonging to a separate profile set. 
Example:

```
profiles {
    local {
        ...
    }
    cluster {
        ...
    }
}

profiles {
    mouse {
        ...
    }
    human {
        ...
    }
}
```
For each run I would like to select an execution related profile (e.g., local vs cluster) as well as a parameter related profile (e.g., mouse vs human).

Thanks!

**Comment by pditommaso** [comment]
I sound useful, need to check how much is feasible.

**Comment by pditommaso** [comment]
Finally we have this. You may want to give a try using the following command: 

```
NXF_VER=0.28.0-SNAPSHOT nextflow run ...etc
```

**Comment by pditommaso** [comment]
Multiple profiles can be specified separating the names with a comma e.g.: 

```
nextflow run <project> -profile foo,bar
```
