### ISSUE TITLE
Add support for platform architecture and microarchitectures 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3701]
The goal of this task is to add new process directive that allows the user to specify the required platform architecture and microarchitecture that's expected to be used by the job execution. 

This will allow targeting execution platforms other than Intel x86, like for example amd64/Graviton. 

The microarchitecture information can be used to optimise the building of the container via Wave or package with Spack using a specific architecture CPU set e.g. Intel Haswell, broadwell, etc. 

The proposed syntax should look like this: 

```
arch "<ARCHITECTTURE>", target: "<MICRO-ARCHITECTTURE>"
```

Where the `target` component is optional. The `arch` value is expected to match the container platform values, [see here](https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images).

Possible examples are: 

```
 arch 'linux/x86_64', target: 'haswell'
 arch 'linux/x86_64', target: 'broadwell'
 arch 'linux/amd64', target: 'zen2'
```

**Comment by marcodelapierre** [comment]
a couple of little picky notes:

- 3rd line up: `amd64/Graviton` should be `aarch64/Graviton` (Spack convention) or `arm64/Graviton`
- very last line, in code block: `linux/amd64` can simply be `linux/x86_64`, as the two are essentially considered synonims as far as I know (the latter is the one used by Spack, among others)

**Comment by pditommaso** [comment]
I think this is primarily needed for specifying the architecture via the container runtime, so I'd keep it aligned with the docker spec. See below

https://github.com/containerd/containerd/blob/v1.4.3/platforms/database.go#L83

When used with Spack it can be remapped to the spack convention. WDYT?

**Comment by marcodelapierre** [comment]
yep, makes sense!

**Comment by pditommaso** [comment]
This directive will impact the containers provisioned by Wave. More precisely the `arch`  information should be mapped to the [containerPlatform](https://github.com/nextflow-io/nextflow/blob/574d85334023f56d12a720970feb3419a0998b1b/plugins/nf-wave/src/main/io/seqera/wave/plugin/SubmitContainerTokenRequest.groovy#L77-L77) attribute in the spinnet below 


https://github.com/nextflow-io/nextflow/blob/574d85334023f56d12a720970feb3419a0998b1b/plugins/nf-wave/src/main/io/seqera/wave/plugin/WaveClient.groovy#L292-L312

**Comment by bentsherman** [comment]
@marcodelapierre Are you planning to implement this directive after #3786 ? If not then I will start on it soon, but I don't want to step on your toes.

**Comment by marcodelapierre** [comment]
Hi @bentsherman thanks for checking-in!

I was thinking of refraining from any work on this issue/directive until #3786 is approved and merged by Paolo/the team, so as to know that my proposed approach is the one to build on. I won't be back on this until next week any way.

So, if you are planning/keen on taking this, please go ahead. I am happy to chat on it at any time, e.g. for any Spack-related aspects. To this end, earlier today I have reached out to you on the Nextflow slack. Otherwise, if you are busy, I can take it, either way.

If you go ahead, two things:
* have a look at my first implementation of handling a `arch` process attribute on #3786; the (still small) core of it is implemented in `TaskConfig`; it is then usable in a simple and similar way both by `SpackCache` for Spack and by `WaveCleint` for Wave. I believe it might be a good starting point for you;
* regarding requirements for Spack, 

Taking one of the examples above, `arch 'linux/x86_64', target: 'haswell'`, what I will need Spack-wise are both `x86_64` and `haswell`.

**Comment by marcodelapierre** [comment]
List of architectures supported by Docker:  https://github.com/docker-library/official-images#architectures-other-than-amd64

Architectures officially supported by Docker, Inc. for running Docker: (see [download.docker.com](https://download.docker.com/linux/))
* ARMv6 32-bit (`arm32v6`): https://hub.docker.com/u/arm32v6/
* ARMv7 32-bit (`arm32v7`): https://hub.docker.com/u/arm32v7/
* ARMv8 64-bit (`arm64v8`): https://hub.docker.com/u/arm64v8/
* Linux x86-64 (`amd64`): https://hub.docker.com/u/amd64/
* Windows x86-64 (`windows-amd64`): https://hub.docker.com/u/winamd64/

Other architectures built by official images: (but not officially supported by Docker, Inc.)
* ARMv5 32-bit (`arm32v5`): https://hub.docker.com/u/arm32v5/
* IBM POWER8 (`ppc64le`): https://hub.docker.com/u/ppc64le/
* IBM z Systems (`s390x`): https://hub.docker.com/u/s390x/
* MIPS64 LE (`mips64le`): https://hub.docker.com/u/mips64le/
* RISC-V 64-bit (`riscv64`): https://hub.docker.com/u/riscv64/
* x86/i686 (`i386`): https://hub.docker.com/u/i386/

**Comment by marcodelapierre** [comment]
@pditommaso  how does the following become within a config file, instead of within a process definition?

process def: `arch <ARCHITECTTURE>, target: <MICRO-ARCHITECTTURE>`

E.g. is this the right syntax?

config file: `arch = '<ARCHITECTTURE>, target: <MICRO-ARCHITECTTURE>'`

**Comment by pditommaso** [comment]
Good point. it should be managed as map in any case, something like this 

```
arch = [value: '<ARCHITECTTURE>', target: '<MICRO-ARCHITECTTURE>']
```

Where `value` is an arbitrary name that should be interpreted as the arch value. 


Something similar is done for [accelerator](https://www.nextflow.io/docs/latest/process.html#accelerator) that in the DSL you can write 

```
accelerator 4, type: 'nvidia-tesla-k80'
```

but in the config it should be (if I'm not wrong) 

```
accelerator [request: 4, type: 'nvidia-tesla-k80']
```

https://github.com/nextflow-io/nextflow/blob/a74e42d937114b25e855bdb327be6c76d7b454eb/modules/nextflow/src/main/groovy/nextflow/executor/res/AcceleratorResource.groovy#L42-L60

**Comment by marcodelapierre** [comment]
gotcha, thanks @pditommaso !
was using Accelerator as template, and in fact could not make sense of that request attribute, as I had never seen it in any example.

what shall we use for `arch`? `name`?
```
arch = [name: '<ARCHITECTTURE>', target: '<MICRO-ARCHITECTTURE>']
```

I am on it, indeed targeting this week to wrap up the PR on the arch support.

**Comment by pditommaso** [comment]
`name` is good!

**Comment by marcodelapierre** [comment]
@pditommaso  which Docker archs do we want to support out of the official list:
```
var SupportedArches = map[string]OCIPlatform{
	"amd64":    {OS: "linux", Architecture: "amd64"},
	"arm32v5":  {OS: "linux", Architecture: "arm", Variant: "v5"},
	"arm32v6":  {OS: "linux", Architecture: "arm", Variant: "v6"},
	"arm32v7":  {OS: "linux", Architecture: "arm", Variant: "v7"},
	"arm64v8":  {OS: "linux", Architecture: "arm64", Variant: "v8"},
	"i386":     {OS: "linux", Architecture: "386"},
	"mips64le": {OS: "linux", Architecture: "mips64le"},
	"ppc64le":  {OS: "linux", Architecture: "ppc64le"},
	"riscv64":  {OS: "linux", Architecture: "riscv64"},
	"s390x":    {OS: "linux", Architecture: "s390x"},

	"windows-amd64": {OS: "windows", Architecture: "amd64"},
}
```

I assume x86 types, ARM types, incl. Windows (and macOS, which I guess is here implicit within Linux) ...?

**Comment by pditommaso** [comment]
That's what is implemented currently 

```
   @Unroll
    def 'should validate platform' () {
        expect:
        ContainerPlatform.of(PLATFORM) == EXPECTED
        ContainerPlatform.of(PLATFORM).toString() == STRING

        where:
        PLATFORM        | EXPECTED                                      | STRING
        null            | new ContainerPlatform('linux','amd64')        | 'linux/amd64'
        'x86_64'        | new ContainerPlatform('linux','amd64')        | 'linux/amd64'
        'amd64'         | new ContainerPlatform('linux','amd64')        | 'linux/amd64'
        'linux/amd64'   | new ContainerPlatform('linux','amd64')        | 'linux/amd64'
        and:
        'arm'           | new ContainerPlatform('linux','arm','v7')     | 'linux/arm/v7'
        'linux/arm'     | new ContainerPlatform('linux','arm','v7')     | 'linux/arm/v7'
        'linux/arm/7'   | new ContainerPlatform('linux','arm','v7')     | 'linux/arm/v7'
        'linux/arm/v7'  | new ContainerPlatform('linux','arm','v7')     | 'linux/arm/v7'
        'linux/arm/5'   | new ContainerPlatform('linux','arm','v5')     | 'linux/arm/v5'
        'linux/arm/v5'  | new ContainerPlatform('linux','arm','v5')     | 'linux/arm/v5'
        and:
        'arm64'         | new ContainerPlatform('linux','arm64')        | 'linux/arm64'
        'linux/arm64'   | new ContainerPlatform('linux','arm64')        | 'linux/arm64'
        'linux/aarch64' | new ContainerPlatform('linux','arm64')        | 'linux/arm64'
        and:
        'linux/arm64/v8'| new ContainerPlatform('linux','arm64')        | 'linux/arm64'
        'linux/arm64/v7'| new ContainerPlatform('linux','arm64','v7')   | 'linux/arm64/v7'

    }
```

**Comment by marcodelapierre** [comment]
Thanks! hadn't checked for existing validation ;)

**Comment by marcodelapierre** [comment]
Do you want to retain the validation in the backend? (in which case, I will not re-implement it in the frontend)

**Comment by pditommaso** [comment]
>  Wait, this is in the backend, right?

yes

> Do you want to retain the validation in the backend? 

it sounds a good idea

**Comment by marcodelapierre** [comment]
Hi @pditommaso , one question and one comment:

- I am ready to add the sending of that PLATFORM argument to the backend, where shall I put it?
- in the allowed string values, can you please also add the plain `aarch64`, for consistency with the other options?

**Comment by marcodelapierre** [comment]
This issue is addressed by PR #3786

**Comment by pditommaso** [comment]
Question: is it supported by Docker? don't see it [here](https://github.com/docker-library/official-images#architectures-other-than-amd64) or [here](https://docs.docker.com/build/building/multi-platform/)?

**Comment by marcodelapierre** [comment]
No, it is one of the Spack ones, which the backend (and my code, too) then converts to `arm64`, see your big snippet a few comments above.
You have already coded `linux/aarch64`, here I am just suggesting to also add `aarch64` for consistency of user experience with the cases of `x86_64`, `amd64` and `arm`.

**Comment by marcodelapierre** [comment]
I think this can now be closed :)
