### ISSUE TITLE
Add isEmpty operator

### ISSUE THREAD

**Issue by matthdsm** [nextflow-io/nextflow#3713]
## New feature

Would it be possible to add an operator that checks for channel empytness that returns a `bool` or a value instead of a channel?

## Usage scenario 

```groovy
if ( channel.isEmpty(bool: true)) 
    process1()
else {
   process2()
}
```

## Suggest implementation 

Add an argument to `isEmpty` to emit a `bool` instead of a channel (without consuming said channel)

**Comment by bentsherman** [comment]
In general, you can't use channels in `if/else` conditions. If you want to condition on a channel result, you should use the `branch` or `filter` operator.

Here's an example with `branch`:
```groovy
is_empty = channel
    | count
    | branch {
        TRUE: count == 0
        FALSE: count > 0
    }

is_empty.TRUE | process1
is_empty.FALSE | process2
```

The branch operator creates two channels here, `is_empty.TRUE` and `is_empty.FALSE`. One of the channels will contain the original channel count based on whether or not it was 0. You can use `map` to transform the count into something else if you like. Finally, your `process1` and `process2` need to accept a "dummy" or "signal" input that simply accepts the value from its respective `is_empty.*` channel.

**Comment by matthdsm** [comment]
Hi Ben,

Thank you for the quick reply. My current implementation does include the branch logic and is fully functional.
I'm talking more from a code readability standpoint, as it can sometimes be hard to get what exactly is going on when using this pattern, whereas a simple `if` statement is more universally readable.

Hope this clarifies my question
Matthias

**Comment by bentsherman** [comment]
I understand, an `isEmpty` operator could be a convenience over using `count`. But keep in mind that you still can't use if statements here, so it's only slightly more readable:
```groovy
ch_empty = channel
    | isEmpty
    | branch { empty ->
        TRUE: empty
        FALSE: !empty
    }

ch_empty.TRUE | process1
ch_empty.FALSE | process2
```
