### ISSUE TITLE
Warn if params.something is defined twice in a NF script

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#372]
A trap that we've fallen into a few times is to define `params.something` more than once in a pipeline script.

Usually it goes like this:
```groovy
params.foo = 'one'
if (params.bar){
  params.foo = 'two'
}
```
then the expectation of behaviour is the following:
```bash
main.nf                    # foo=one
main.nf --bar              # foo=two
main.nf --foo three        # foo=three
main.nf --bar --foo four   # foo=four
```

However, this doesn't work, as `params.foo` can only be defined in a pipeline script once (unlike regular variables). So you actually get:

```bash
main.nf                    # foo=one
main.nf --bar              # foo=one
```

I think that the existing behaviour is fine as it is, however, it would be nice if a warning could be generated if `params.foo` is defined in a NF script more than once. Currently everything just proceeds silently and the scripts look logical, making it a tricky bug to spot.

Cheers,

Phil

**Comment by emi80** [comment]
+1

**Comment by pditommaso** [comment]
OK, added to `0.25.0-RC3`. Please give it a try with 

```
NXF_VER=0.25.0-RC3 nextflow run .. etc
```

**Comment by ewels** [comment]
Brilliant stuff - thanks!

I'm getting an error when I try that version though:

```
NXF_VER=0.25.0-RC3 nextflow run testmail.nf -profile none
Error: cannot download nextflow required file -- make sure you can connect the internet

Alternatively you can download the file:
    http://www.nextflow.io/releases/v0.25.0-RC3/nextflow-0.25.0-RC3-one.jar
```

That URL then times out for me in a web browser too (`ERR_NAME_NOT_RESOLVED`). I can access the main nextflow.io site without any problems.

**Comment by pditommaso** [comment]
Weird, I've download it right now, at that is hosted on AWS so I'm not in a privileged network . .

**Comment by ewels** [comment]
Strange - I changed from wifi (eduroam) to wired connection and now it works.. 

Anyway, looks great! I got a warning when the conditional was resolved. I guess it's only possible to throw such warnings when those lines of code are actually activated? But that's fine.

Many thanks!

**Comment by pditommaso** [comment]
Yes, it's discovered at runtime. NF doesn't have (yet) a syntax parser :)

**Comment by kemin711** [comment]
Is it good to make the params.foo read only?  You probably should not change the user input?  Making this clear in the doc may help the script to be more predictable.
