### ISSUE TITLE
Uploaded reports do no appear in Tower UI

### ISSUE THREAD

**Issue by cdiener** [nextflow-io/nextflow#3728]
### Expected behavior and actual behavior

I added a `tower.yml` to my project to upload a MultiQC report. 

```yaml
reports:
        "**/multiqc_report.html":
                display: "MultiQC report"
```

I ran the pipeline on a local SLURM cluster and used tower to track the run. The report file exists and based on the logs it is uploaded. However the Tower UI say that no reports have been configured.

### Steps to reproduce the problem

The pipeline can be found [here](https://github.com/Gibbons-Lab/pipelines/blob/master/metagenomics/main.nf).

### Program output 

The logs look good:

```
Mar-07 10:32:47.558 [FileTransfer-4] DEBUG io.seqera.tower.plugin.TowerReports - Adding report [1] **/multiqc_report.html -- /proj/gibbons/2022_metacardis/data/multiqc_report.html
Mar-07 10:33:06.101 [main] DEBUG nextflow.Session - Waiting files transfer to complete (3 files)
Mar-07 10:38:12.761 [Timer-0] DEBUG io.seqera.tower.plugin.TowerReports - Reports file sync to workdir with 1 reports
```

### Environment 

* Nextflow version: 22.04 installed with conda
* Java version: OpenJDK 11.01
* Operating system: Ubuntu 20.04.5
* Bash version: bash 5.0.17

### Additional context

[.nextflow.log](https://github.com/nextflow-io/nextflow/files/10913148/default.nextflow.log)

**Comment by bentsherman** [comment]
I think this is currently the expected behavior. Monitoring-only runs in Tower don't support all of the features that are available for runs launched in Tower, including reports.

**Comment by joseale2310** [comment]
Could you please add this info in the docs? It would be very appreciated.

**Comment by pditommaso** [comment]
Makes sense, thanks for reporint
