### ISSUE TITLE
Azure batch run in Tower gets stuck in Submitted state

### ISSUE THREAD

**Issue by wikiselev** [nextflow-io/nextflow#3735]
### Expected behavior and actual behavior

Expected: Completed run should get either in `Failed` or `Succeeded` state.

Actual: Completed run is stuck in `Submitted` state even though a compute pool corresponding to the run has been auto scaled to 0.

### Steps to reproduce the problem

I created a compute pool using Tower Forge and started a pipeline (private). This created a new run on Tower and auto scaled the newly created pool from 0 to 1 node. Pipeline has failed on the node.

### Program output 

Tower run never received the output of the pipeline and got stuck in `Submitted` state even though the compute has been down scaled to 0 nodes.

### Environment 

Tower

### Additional context

I now have two runs like this (in `Submitted` state). When I try to delete them myself via Tower interface or via Tower CLI (with `--force` option) I get an error like:
```
Oops... Unable to process request - Error ID: 7KbRlVktv3YFwhsR7oAXzk
```
If I get three more runs like this I will hit a limit of concurrent tasks and won't be able to use Tower anymore... I will appreciate your help in deleting them. Thanks!

**Comment by pditommaso** [comment]
Vlad, this is not a nextflow issue, please report in https://github.com/seqeralabs/nf-tower. sorry, closing

**Comment by wikiselev** [comment]
Sorry, Paolo, didn't realise there was a separate issue tracker for Tower. I've resubmitted this bug there.
