### ISSUE TITLE
Safe guard when using publishDir directive

### ISSUE THREAD

**Issue by Phuong-Le** [nextflow-io/nextflow#3754]
## New feature

Hi! Thanks for using Nextflow and submitting the proposal 
for a new feature or the enhancement of an existing functionality. 

Please replace this text providing a short description of your 
proposal.

## Usage scenario 

I made a mistake of doing something like this 

```
process foo {
    publishDir "${params.db}", mode: 'copy'

    input:
    path db

    output:
    tuple path(db), path(some/other/file)

    script:
    """
    some command
    """
}
```

Essentially I accidentally published the directory "db" to itself. If I understand it correctly, then when there's a change in the output then the output will be copied to the published directory? In my case, as the "db" got copied to itself, then it was changed and the process continued, creating something like db/db/db/db/... - until it reached either time limit or memory limit. So I essentially created a virus by doing so...

## Suggest implementation 

It would be great to have a safe guard to prevent users from doing something like this again. Sorry if this is meant to be an issue in Bug report

**Comment by bentsherman** [comment]
So the `path(db)` in your process is a directory that comes from `params.db` ? And the process itself is watching the directory for changes?

I suppose we could add an error or warning if (1) a publish path matches an input path and is a directory and (2) the publish mode is copy.

**Comment by Phuong-Le** [comment]
Thank you for your response and yes that was the case. 

I think add **a warning** or **an error** whenever \
(1) a published path is a directory & \
(2) the publish mode is copy

and **an error** if a publish path matches an input path.

The reason why I think a warning is needed when publish path is directory, is because this is the case for when either the publish dir is nested in the the output dir at any depth or the other way around. Best to do a thorough check whether either is nested within the other - but I understand this might not be straightforward to do.

If possible, the warning message should have a serious tone too, for obvious reason. My mistake took up 18TB of my lab's disk quota before being terminated by the time limit of 12 hours...

**Comment by Phuong-Le** [comment]
Looking at your comment a second time. I was wondering if the input path had anything to do with my case? (I didn't think about that before)

Also I was wondering if this only affects the mode of publish?

**Comment by bentsherman** [comment]
I think we can prevent this problem from happening in the first place by publishing each file in the directory tree instead of publishing the directory, see #3933

**Comment by bentsherman** [comment]
The published directory should have the exact same structure as the original directory. I think the only difference is that if you publish via link, Nextflow will link each individual file instead of the top directory. But you are copying so it will just copy the directory structure.
