### ISSUE TITLE
Missing documentation for subscribe operator

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3761]
The operator [page](https://www.nextflow.io/docs/latest/operator.html) is missing to document the `subscribe` operator, that's mentioned in some examples, e.g. here 

https://www.nextflow.io/docs/latest/operator.html#collectfile

**Comment by bentsherman** [comment]
It is documented on the Channels page: https://nextflow.io/docs/latest/channel.html#subscribe

**Comment by pditommaso** [comment]
Not sure why it's there, but does not make much sense. Also `<<` and `bind` should be removed

**Comment by bentsherman** [comment]
The `bind` and `<<` are removed on master. I always assumed you kept these separate from operators because they don't produce a new channel. But I agree that it makes sense to document subscribe under operators.

**Comment by pditommaso** [comment]
Maybe, but yes, let's move to operators

**Comment by mribeirodantas** [comment]
Ok, so remove `bind`, `<<` and move it from the channel section to the operators section. Agreed?

**Comment by mribeirodantas** [comment]
Oh, ok.
