### ISSUE TITLE
splitCsv returns all values as strings

### ISSUE THREAD

**Issue by mirpedrol** [nextflow-io/nextflow#3763]
Hello,

I am trying to convert the content of a CSV file into a JSON array. When I read the CSV with `splitCSV()` I see that all values are casted as strings.

Is that an expected behaviour? I would expect numbers to be casted as Integers or true/false as booleans, for example. 
And in case it's the expected behaviour, is there a way to automatically cast all these objects to their primitive types?

Thank you!

To reproduce what I see, I have a test.csv:
```
foo,bar
a,1
b,2
```
And this Nextflow code:
```nextflow
import groovy.json.JsonBuilder

def testJSON() {

    fileContent = file("test.csv").splitCsv( header:true, sep:',')

    for (row in fileContent) {
        println("row class: $row.getClass, row: $row")
        for (key in row.keySet()) {
            println("value class: ${row[key].getClass()}, value: ${row[key]}")
        }
    }

    def jsonObj = new JsonBuilder(fileContent)

    println("file content: $fileContent")
    println("json object: $jsonObj")
}

testJSON()
```

**Comment by mirpedrol** [comment]
Thanks for the input @bentsherman I will try to add inferring types :)

**Comment by mirpedrol** [comment]
Hello @bentsherman, I made a PR to add a new option to splitCsv() https://github.com/nextflow-io/nextflow/pull/3831, could you talke a look? Thanks!

**Comment by bentsherman** [comment]
Closing since this issue was handled by the nf-validation plugin
