### ISSUE TITLE
Order of collected files

### ISSUE THREAD

**Issue by johnomics** [nextflow-io/nextflow#377]
I'm trying to merge together the output of a set of files with paste, running nextflow 0.24.4:

```
process idxstats {
    input:
    set val(name), file(bam_file) from bams

    output:
    file "${name}.counts.txt" into count_files

    """
    samtools index ${bam_file}
    samtools idxstats ${bam_file} > ${name}.counts.txt
    """
}

process merge_counts {
    input:
    file "*.counts.txt" from count_files.collect()

    output:
    file 'merged.counts.txt'

    """
    paste *.counts.txt > merged.counts.txt
    """
}
```

This works, but I want to sort the output by original file name, and the output of collect is unsorted. `toSortedList` also doesn't produce a consistent output. It looks like both `collect` and `toSortedList` replace the original file names with `1.counts.txt`, `2.counts.txt` etc, which are assigned according to which job finishes first. The original file name is lost.

I can get the filename into a list of tuples with 

```
set val(name), file("${name}.counts.txt") into count_files
```

in `idxstats` output, and

```
val(namedlist) from count_files.toSortedList({a, b -> a[0] <=> b[0]})
```

in `merge_counts` input, but then can't see how to separate the names and files into two separate lists (sorry, I don't know Groovy).

What's the best way to handle this? Thanks.

**Comment by pditommaso** [comment]
Use just `file "*" from count_files.collect()` to keep the original file name

**Comment by johnomics** [comment]
Fantastic, that works - thank you very much!
