### ISSUE TITLE
Issue with newer version of groovy-yaml

### ISSUE THREAD

**Issue by zachcp** [nextflow-io/nextflow#3780]
## Bug report 

Full issue [here](https://nextflow.slack.com/archives/C02T98A23U7/p1679329499962209)

```groovy
// main.nf

// https://mvnrepository.com/artifact/org.apache.groovy/groovy-yaml
// test.yml: -test

@Grab('org.apache.groovy:groovy-yaml')
// @Grab('org.apache.groovy:groovy-yaml:4.0.8') // this will work fine

def test() {

    def yamlbuilder = new groovy.yaml.YamlBuilder()
    def yamlslurper = new groovy.yaml.YamlSlurper()
    yamlslurper.parse(file("test.yml"))
}

workflow {
    test()
}
```

### Expected behavior and actual behavior

Workflows that use a non-pinned yaml library will crash with an error like: 

'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader, org.yaml.snakeyaml.LoaderOptions)`

Note: we do not expect this to be `snakeyaml`.

### Steps to reproduce the problem

- create a main.nf with the above
- create a simple test.yml yaml file
- run `nextflow run .`

**Comment by jribeiro-pfe** [comment]
I just found the same issue after updating Nextflow to the latest version, and it seems to come from the snakeyaml 2.0. Once I downgrade the version `export NXF_VER=22.10.7`, which uses snakeyaml 1.3, everything runs smoothly.  

As it seems there are some security concerns with snakeyaml 2.0?

**Comment by pditommaso** [comment]
@jribeiro-pfe is your problem related to the use of the `@Grab` annotation?

**Comment by jribeiro-pfe** [comment]
I do use Grab to install groovy-yaml, which produces the following error:

'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'

I am running this on MacOS M1 (13.3.1) and nextflow  23.04.1, openjdk 17.0.6 2023-01-17 OpenJDK Runtime Environment Homebrew (build 17.0.6+0). Once I downgraded to nextflow 22.10.7, everything ran smoothly.

when executing nextflow, I confirmed that the capsule had snakeyaml 1.30, instead of 2.0

"CAPSULE: Downloading dependency org.yaml:snakeyaml:jar:1.30"

**Comment by pditommaso** [comment]
@bentsherman can you please look at this? maybe it should be added `groovy-yaml` as core dependency to nextflow

**Comment by bentsherman** [comment]
Uh... I had the opposite effect 😆 

For me, the pinned grab failed on 23.04.1 and succeeded on 22.10.7, while the unpinned grab failed on 22.10.7 and succeeded on 23.04.1.

For 23.04.0, both grabs worked. So based on my results, the latest releases work best with the unpinned grab.

Here is my console output:

```console
$ cat gh-3780/main.nf

@Grab('org.apache.groovy:groovy-yaml')
// @Grab('org.apache.groovy:groovy-yaml:4.0.8') // this will work fine

def test() {

    // def yamlbuilder = new groovy.yaml.YamlBuilder()
    def yamlslurper = new groovy.yaml.YamlSlurper()
    yamlslurper.parse(file("${projectDir}/test.yml"))
}

workflow {
    println test()
}

$ NXF_VER=22.10.7 nextflow run gh-3780/
N E X T F L O W  ~  version 22.10.7
Launching `gh-3780/main.nf` [admiring_shaw] DSL2 - revision: b6db4fd205
'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader, org.yaml.snakeyaml.LoaderOptions)'

 -- Check script 'gh-3780/main.nf' at line: 9 or see '.nextflow.log' file for more details

$ NXF_VER=23.04.0 nextflow run gh-3780/
N E X T F L O W  ~  version 23.04.0
Launching `gh-3780/main.nf` [nauseous_leakey] DSL2 - revision: b6db4fd205
{foo=bar}

$ NXF_VER=23.04.1 nextflow run gh-3780/
N E X T F L O W  ~  version 23.04.1
Launching `gh-3780/main.nf` [exotic_bhaskara] DSL2 - revision: b6db4fd205
{foo=bar}

$ cat gh-3780/main.nf

// @Grab('org.apache.groovy:groovy-yaml')
@Grab('org.apache.groovy:groovy-yaml:4.0.8') // this will work fine

def test() {

    // def yamlbuilder = new groovy.yaml.YamlBuilder()
    def yamlslurper = new groovy.yaml.YamlSlurper()
    yamlslurper.parse(file("${projectDir}/test.yml"))
}

workflow {
    println test()
}

$ NXF_VER=22.10.7 nextflow run gh-3780/
N E X T F L O W  ~  version 22.10.7
Launching `gh-3780/main.nf` [small_koch] DSL2 - revision: 36de9046d9
{foo=bar}

$ NXF_VER=23.04.0 nextflow run gh-3780/
N E X T F L O W  ~  version 23.04.0
Launching `gh-3780/main.nf` [awesome_goodall] DSL2 - revision: 36de9046d9
{foo=bar}

$ NXF_VER=23.04.1 nextflow run gh-3780/
N E X T F L O W  ~  version 23.04.1
Launching `gh-3780/main.nf` [awesome_tuckerman] DSL2 - revision: 36de9046d9
ERROR ~ 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'

 -- Check script 'gh-3780/main.nf' at line: 9 or see '.nextflow.log' file for more details
```

**Comment by jribeiro-pfe** [comment]
I installed it with Homebrew. For me, everything worked with versions up to 23.04.0 (pinning or unpinning groovy-yaml). If I update to 23.04.1, it fails even if I don't pin the version of groovy-yaml. I deleted my folder within ~/.nextflow to make sure there was nothing affecting the different runs.

**Comment by bentsherman** [comment]
It is strange that we're getting the opposite results. Can you try it with a Java distribution from SDKMAN?

https://nextflow.io/docs/latest/getstarted.html#requirements

**Comment by pditommaso** [comment]
Recent versions of Nextflow ship [groovy-yaml](https://github.com/nextflow-io/nextflow/blob/1dfb621c12ceda4adbfef9adfec560bb36b7df53/modules/nextflow/build.gradle#L25-L25) by default. No need to use `Grab` annotation
