### ISSUE TITLE
Installation man-in-the-middle attack risk

### ISSUE THREAD

**Issue by diekhans** [nextflow-io/nextflow#379]
The install instructions of:
   `curl -fsSL get.nextflow.io | bash`
are unsettling as they could result in an MITM attack running code on the system.

One would feel far better about trying this is it was an HTTPS URL.

**Comment by pditommaso** [comment]
You can specify HTTPS on that url ie. `curl -fsSL https://get.nextflow.io | bash`. Alternatively you can download it from GitHub or install with Conda.

**Comment by diekhans** [comment]
This is a documentation bug, not a search for an alternative.

The problem is that the instructions specifically tell the user
to install it it in an insecure manner.

**Comment by pditommaso** [comment]
Fair enough, I will update the documentation.
