### ISSUE TITLE
Local Git support

### ISSUE THREAD

**Issue by alartin** [nextflow-io/nextflow#38]
I really like the integration of Github to version the pipeline files and hope nextflow to support local Git , not only Github. For example, we have local Gitlab for our internal code management. It could be better to support local Git repository. Thanks!

**Comment by pditommaso** [comment]
It makes sense. I have no experience with Gitlab but from what you are saying it looks enough just supporting the local file system as a Git repository provider to be managed by Nextflow. Isn't it?

**Comment by alartin** [comment]
Hi, Paolo Di
Yes. Thanks.

**Comment by pditommaso** [comment]
@alartin Hi, could you please provide me more details how is organised the directory structure of your local Gitlab repository? 

I'm supposing the following directories organisation: 

    $GIT_REPOSITORIES_ROOT/
        user1/
            project1/
                .git/
                src
                :
            project2/
                .git/
                src
                :
        user2/
            project1/
                .git/
                src
                :
            project2/
                .git/
                src
                :       
      :

I will add the possibility to specify the `$GIT_REPOSITORIES_ROOT` local path as git provider to Nextflow, thus it will possible to pull/run/clone pipelines from your local path using the usual command line. For example: 

    nextflow run user1/project2 


Does it make sense?

**Comment by pditommaso** [comment]
Nextflow now supports private  source code manager servers. See the [related documentation](https://github.com/nextflow-io/nextflow/blob/master/docs/sharing.rst#private-server-configuration).
