### ISSUE TITLE
Files .command.sh and .command.run are not tagged correctly when running with fusion

### ISSUE THREAD

**Issue by cbr7** [nextflow-io/nextflow#3800]
## Bug report 

It seems that the `.command.sh` and `.command.run` files from workflow tasks remain untagged when running with fusionV2 with the latest edge release from nextflow

### Expected behavior and actual behavior

All files related to workflow tasks running with fusion should be tagged correctly.

### Steps to reproduce the problem

1. Run a pipeline on a CE that has fusionV2 enabled.
2. Check the task log files and notice that `.command.sh` and `.command.run` are the only files that are untagged.

### Environment 

* Nextflow version: 23.03.0-edge

### Additional context

See [here](https://github.com/seqeralabs/nf-tower-cloud/pull/4511#issuecomment-1484215147)

**Comment by pditommaso** [comment]
Solved by #4511
