### ISSUE TITLE
New config option: `publishDir.basePath`

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#3805]
## New feature

In @nf-core we prefix every `publishDir` `path` with `params.outdir`. For example, to modify the example in the docs:

```nextflow
publishDir "${params.outdir}/data/chunks"
```

Without this, Nextflow will spit published results into the launch directory, which I think is generally agreed to be a bad idea in most cases (overwriting / ephemeral storage). But to follow best practices of not doing this, the pipeline code needs this arbitrary variable interpolation.

It would be nice to have a new config attribute for `publishDir` called something like `basePath`, which would default to the launch directory (existing behaviour) but if set, works for the _entire_ pipeline run.

This would remove quite a lot of boilerplate code and make it easier for people working with non-nf-core pipelines which don't use this convention.

Could also have this as a command-line flag to easily change at run time, similar to `-work-dir` (`-publish-dir`?)

## Suggest implementation 

* Config: `publishDir.basePath`
* Command line: `-publish-dir`

If provided, prefix this string to the path in [`PublishDir.groovy`](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy)

**Comment by bentsherman** [comment]
Related to #2661

**Comment by pditommaso** [comment]
This has been solved by https://github.com/nextflow-io/nextflow/pull/3942. In a nutshell, relative paths are resolved against the path specified via `NXF_FILE_ROOT` env variable.

**Comment by ewels** [comment]
There's no way to set this from within the workflow though, right? We need to be able to set this with `params.outdir` in nf-core workflows.

**Comment by pditommaso** [comment]
This may be a good candidate for `nextflow.defaults` planned setting https://github.com/nextflow-io/nextflow/issues/4186. Tho it should be verified if it's feasible.

**Comment by ewels** [comment]
Yeah, it's to prefix rather than overwrite 🤔

**Comment by bentsherman** [comment]
This should be addressed by the workflow outputs DSL #4784 which removes the need to specify the base publish path many times
