### ISSUE TITLE
Running -with-docker inside the nextflow dockerized application

### ISSUE THREAD

**Issue by byzantic** [nextflow-io/nextflow#3811]
Hi

I'm having trouble running pipelines using containers from _inside_ the `nextflow/nextflow` docker image ..

That is, I want to run `nextflow` as a containerized server, but I also need to be able to execute pipeline stages in containers as well, since they all require different tools.

I experimented using the simple example in the web documentation. 

* I can successfully run `nextflow` natively on my host server and use `-with-docker <image name>` to run the pipeline
    - `nextflow run /data/analysis/simple.nf -with-docker python:slim`
* I can successfully run the `nextflow/nextflow` image interactively using
    - `docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /data/analysis/:/data nextflow/nextflow bash`
* I can then run a simple workflow inside the image
   - `nextflow run /data/simple.nf`
* But using a container fails:
    - `nextflow run /data/simple.nf -with-docker python:slim`

Here is the failure:
```bash
bash-4.2# nextflow run /ramp/simple.nf -with-docker python:slim
N E X T F L O W  ~  version 23.03.0-edge
Launching `/ramp/simple.nf` [ecstatic_dubinsky] DSL2 - revision: d9112e73c2
executor >  local (1)
[85/814c9d] process > splitLetters   [100%] 1 of 1, failed: 1 ✘
[-        ] process > convertToUpper -
ERROR ~ Error executing process > 'splitLetters'

Caused by:
  Process `splitLetters` terminated with an error exit status (1)

Command executed:

  printf 'Hello world!' | split -b 6 - chunk_

Command exit status:
  1

Command output:
  (empty)

Command error:
  /bin/bash: .command.sh: No such file or directory

Work dir:
  /work/85/814c9dd0cdb56c771217978abf4830

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```
If I look in the `/work` directory created by the run, there is only one (empty) directory, compared to the three created when running normally.

Any ideas? Might be due to:

* `nextflow.config` settings
* user name used inside the `nextflow/nextflow` image (at the moment it's root)
* I have mounted the `docker.sock` volume to expose the host docker service to the image - is this the right way to proceed?
* something that's done in the `entry.sh` script that I'm not doing in the image?

I think I have tried just about everything at this point ..

**Comment by bentsherman** [comment]
Okay, if it's failing with `-dockerize` and `-with-docker` together then there is probably something wrong. How exactly does it fail? Can you share the error message from `.nextflow.log` ?

**Comment by byzantic** [comment]
Ah. OK - I misremembered.

Just trying to use -dockerize fails and gives the following behaviour:
```
nextflow -dockerize run simple.nf
Unable to find image 'nextflow/nextflow:22.10.7' locally
22.10.7: Pulling from nextflow/nextflow
d78505e61525: Pull complete 
cbce6289ce7b: Pull complete 
ba60452dc0e3: Pull complete 
b99b02b8c59e: Pull complete 
b83e016b7357: Pull complete 
8e22f13a109f: Pull complete 
516b75b02306: Pull complete 
Digest: sha256:285e4d77779c693a45a2b7ff8704903b5a4d43a331ac821f9c89d6d1918fccde
Status: Downloaded newer image for nextflow/nextflow:22.10.7
/usr/local/bin/entry.sh: line 46: addgroup: command not found
adduser: group 'docker' does not exist
chown: invalid user: ‘nextflow’
su: user nextflow does not exist
```
so two things to note - firstly, it uses an explicit nextflow/nextflow image, not `:latest`. But the image used is before the 22.11.0-edge tag. If I run `nextflow info`:
```
nextflow info
  Version: 22.10.7 build 5853
  Created: 18-02-2023 20:32 UTC (21:32 CEST)
  System: Linux 5.15.0-58-generic
  Runtime: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 11.0.18+10-post-Ubuntu-0ubuntu120.04.1
  Encoding: UTF-8 (UTF-8)
```
So presumably it tries to pull the version that matches the base installed version?

Secondly - if I look at the `entry.sh` script, I might expect this behaviour if the `NXF_USRMAP` environment variable is not set? However, explicitly setting it does not help.

OK, I now try to force the use of 22.11.0-edge:
```
NXF_VER=22.11.0-edge nextflow -dockerize run simple.nf
Unable to find image 'nextflow/nextflow:22.11.0-edge' locally
22.11.0-edge: Pulling from nextflow/nextflow
68028ec3b506: Pull complete 
d137d2313065: Pull complete 
de4a3a4453a7: Pull complete 
f643153b3a20: Pull complete 
f88c1675f882: Pull complete 
c3be39b40ed3: Pull complete 
c4ca585dfe65: Pull complete 
Digest: sha256:58d56cbe6fce893637421c3e2b491084c11508a36686a4b3ea3a1c37f38f0b70
Status: Downloaded newer image for nextflow/nextflow:22.11.0-edge
N E X T F L O W  ~  version 22.11.0-edge
Launching `simple.nf` [desperate_ekeblad] DSL2 - revision: d9112e73c2
[31/ed9813] Submitted process > splitLetters
[d0/d744aa] Submitted process > convertToUpper (1)
[5e/26e307] Submitted process > convertToUpper (2)
HELLO
WORLD!
```
Success! now lets try to run using `-with-docker`:
```
NXF_VER=22.11.0-edge nextflow -dockerize run simple.nf -with-docker python:slim
N E X T F L O W  ~  version 22.11.0-edge
Launching `simple.nf` [high_nightingale] DSL2 - revision: d9112e73c2
[b0/bdaf21] Submitted process > splitLetters
[7c/cb7fe4] Submitted process > convertToUpper (2)
[9d/5ef335] Submitted process > convertToUpper (1)
WORLD!
HELLO
```
OK, so that all seems to work.

However, I am still running the first command natively on the host (though it is just a launcher which then runs the docker image of nextflow). Ultimately I want to run even that from an image, specifically from a docker-compose file. The reason is that I want to wrap all components of my system which comprise nextflow, a database, a webserver and some microservices, into a docker-compose file. I can then spin up a complete application just by starting the docker-compose file.

It may well just work out of the box - I will need some more time to experiment tomorrow.

Many thanks for your help, that was really great!

**Comment by bentsherman** [comment]
Happy to help. You'll probably have to do some extra work to use the dockerized run in docker compose. You can inspect the docker command generated by `-dockerize` [here](https://github.com/nextflow-io/nextflow/blob/38c8bd335d286ddc3907254b9d6817581f2a67d0/nextflow#L227-L238) and adapt it to your docker compose setup. If you launch Nextflow with `NXF_DEBUG=1` then it will `set -x` and print all of the generated bash code, including the dockerized command.

You could also just use [Tower](https://cloud.tower.nf/) 😄

**Comment by agdiaz** [comment]
Hello @byzantic and all 👋 

This issue has been convenient for my development. I am also building a small frontend for a Nextflow pipeline using Docker-Compose to orchestrate the frontend (Django), the database (postgres) and the async executions (Celery). @bentsherman I gave a chance to Tower however we need something very very small for the final users of our NF pipeline. 

@byzantic I tried to follow the instructions of your latest comment but unfortunately, I could not make it work, but I am close.

My Nextflow service inside my docker-compose file is:

```yaml
  nextflow:
    container_name: nextflow
    image: nextflow/nextflow:22.11.0-edge
    platform: linux/amd64
    volumes:
      - ./media_volume:/app/media
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NXF_DEBUG=1
    command: ["tail", "-F", "anything"]
```

(I keep the service on by including the command `tail -F anything`)

When I launch `NXF_VER=22.11.0-edge nextflow -dockerize run helloworld` from a terminal session inside the dockerized nextflow service it works like a charm! 

However the command `NXF_VER=22.11.0-edge nextflow -dockerize run helloworld -with-docker python:slim` returns an error related to not being able to mount the work directory:

```bash
  + docker run -i --cpu-shares 1024 -v /work/c3/b75595456754b7ddc25ad0b60f874e:/work/c3/b75595456754b7ddc25ad0b60f874e -w /work/c3/b75595456754b7ddc25ad0b60f874e --name nxf-4CXjmteHWhMtdTWb6Cbre0w0 python:slim /bin/bash -uex .command.sh
  docker: Error response from daemon: Mounts denied: 
  The path /work/c3/b75595456754b7ddc25ad0b60f874e is not shared from the host and is not known to Docker.
  You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
  See https://docs.docker.com/desktop/mac for more info.
  time="2024-03-12T17:03:29Z" level=error msg="error waiting for container: context canceled"
```

By chance, have you fixed this issue? Somehow I need to mount the work volume to the inner Docker containers.

Thank you so much in advance for your guidance. 

Kind regards from Brussels to all of you!

**Comment by byzantic** [comment]
@agdiaz Hi, I'm afraid I passed this project over to someone else, and they implemented it in a different way, so I didn't take this any further.

However, this looks like a docker-specific issue to me: getting the mounts correct always seems to require a few iterations!

**Comment by stefanoboriero** [comment]
Hello @byzantic , even if you don't need this anymore I'd like to give you some closure on this issue and hopefully give an answer to anybody else stumbling on this issue.

The root cause that leads to the `.command.sh: No such file or directory` error when starting a nextflow pipeline with containers from another container running nextflow is due to the way the "docker in docker" functionality works. As explained in https://serverfault.com/questions/819369/mounting-a-volume-with-docker-in-docker when you share the docker socket with the container, effectively all the docker command executed from inside the container are sent to the docker server running on the host, so paths for volume mounts issued from the containers will try to be resolved from the host filesystem point of view.

How does Nextflow mount volumes when launching a containerised pipeline? It will try to mount paths according to its current view of the working directory, which might be different from the host one: Nextflow is agnostic of the fact that its being run from inside a container. Let me try to give you a concrete example using your original issue: you run the nextflow docker image with `docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /data/analysis/:/data nextflow/nextflow bash`, so when running `nextflow run /data/simple.nf -with-docker python:slim` nextflow will try to mount the path `/data` as a volume somewhere in the `python:slim` container, because that's the current directory from the container perspective: however given we're sharing the docker socket the path will be resolved to the folder `/data` on the host, but your project on the host is actually in `/data/analysis`.

So, how can you make it work? It's a hack but if you mount the original volume for the nextflow container to the same absolute path where it is in the host, then it should work because the string paths will be the same! Something like `docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /data/analysis/:/data/analysis nextflow/nextflow bash` in your example. This is effectively what running nextflow with the `-dockerise` flag does, if you look at the code that Ben shared you can see it mounts `-v $PWD:$PWD` on the nextflow container.
