### ISSUE TITLE
memory allocation into "virtual-free" not "ram.c" for UGE

### ISSUE THREAD

**Issue by qingpeng** [nextflow-io/nextflow#382]
Hi, In nextflow.config file, I used memory='40GB' to set the memory usage to submit to the queue of our HPC system running UGE, as below
```
process {
  executor='sge'
  memory='40GB'
  queue='high.q'
  time='1h'
}
```

However I got some problems about insufficient memory. When I check the detail of the submitted job, I found out that the "hard resource_list" is 

```
hard resource_list:         48-120.c=TRUE,virtual_free=40G,h_vmem=15G,ram.c=15G,highmemsys.c=TRUE,h_rt=3600
```

So the ram.c is 15G, not 40G. in our HPC system, normally we use ram.c to set the memory usage.

I am wondering if this is normal. 

Thanks!

**Comment by qingpeng** [comment]
I tried to use clusterOptions like
```
clusterOptions = '-l ram.c=40G,h_rt=1:00:00'
```

But while I checked the detail of the submitted job, it looks like the ram.c is still 5.25G, the default value
```
granted_req.          1:    h_vmem=5.250G, ram.c=5.250G
```

**Comment by pditommaso** [comment]
NF does not set `ram.c` requirement. You can inspect the SGE directives specified by NF looking at the `.command.run` job wrapper created in the working directory. 

In my opinion are default provided by your cluster installation. I suggest to contact your cluster sysadmins.

**Comment by pditommaso** [comment]
I'm closing this because it doesn't look a NF issue. Feel free to comment below and reopen if needed.

**Comment by qingpeng** [comment]
Thanks! 
the clusterOptions setting works in my case. It seems that the job could actually use more memory than the 5.26G specified in "granted_req." field.
