### ISSUE TITLE
`InvocationTargetException` instead of bubbling up exception

### ISSUE THREAD

**Issue by jchorl** [nextflow-io/nextflow#3823]
## Bug report 

main.nf:
```groovy
include { getMetadata } from './helpers'

workflow {
    // inputs are string, whatever
    def inputs = Channel.of("file1", "file2", "file3")

    inputs \
        | map { it -> [it, getMetadata(it, params.foo)] } \
        | set { to_pipeline }
}
```

helpers.nf:
```groovy
def getMetadata(input, p) {
    // TODO: replace with real validation on the input and params
    if (true) {
        throw new IllegalArgumentException("${p} validation failure - explanation here")
    }

    [validated: true]
}
```

Command:
```
$ nextflow run main.nf --foo bar
N E X T F L O W  ~  version 22.10.7
Launching `main.nf` [clever_lichterman] DSL2 - revision: 34d0d1604a
Unexpected error [InvocationTargetException]

 -- Check script 'main.nf' at line: 8 or see '.nextflow.log' file for more details
```

### Expected behavior and actual behavior

I would have expected the output to contain `validation failure`.

Instead, this appears:

```
Unexpected error [InvocationTargetException]
```

The actual exception doesn't appear in the logs either.

If I change `if (true)` to `if (false)` (i.e. avoiding the exception), it exits successfully.

### Steps to reproduce the problem

All details provided above

### Environment 

```
$ nextflow info
  Version: 22.10.7 build 5853
  Created: 18-02-2023 20:32 UTC 
  System: Linux 5.15.0-69-generic
  Runtime: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 17.0.6+10-LTS
  Encoding: UTF-8 (UTF-8)
```

### Additional context

A "wont-fix" is fine.

I'm mostly looking for guidance on how to implement the pattern described above. I'd like to do some validations, and see real exceptions printed outside the nextflow process. `InvocationTargetException` is hard to chase down with any non-trivial function implementation.

Thanks as always!!

**Comment by pditommaso** [comment]
Thanks for reporting it. Solved by 16f54a9c
