### ISSUE TITLE
Terminated nxf_trace error

### ISSUE THREAD

**Issue by tantrev** [nextflow-io/nextflow#383]
I've been trying to run some SLURM jobs through NF, and some of them have been failing seemingly inexplicably with this error:

```
Terminated              nxf_trace "$pid" .command.trace
```

The afflicted nextflow script may be found [here](http://epilog.bio/files/example/lumpy_prep_latest.nf) with its configuration [csv](http://epilog.bio/files/example/rgid_nf.csv), the trace file may be found [here](http://epilog.bio/files/example/trace.txt), the log file may be found [here](http://epilog.bio/files/example/.nextflow.log), and the compressed work directory may be found [here](http://epilog.bio/files/example/work.tar.gz).  Any help would be more than appreciated.

**Comment by pditommaso** [comment]
This message is a consequence of the fact that the task has been killed. Indeed all tasks return a `137` error status, which commonly refer to a lack of computing resources. 

I would suggest to troubleshoot the problem debugging one of that tasks in a isolated manner ie. launching the execution manually with the command `sbatch .command.run` and find out why the SLURM kill it.

**Comment by tantrev** [comment]
Thank you!  Turns out it was just a memory problem.  The SLURM memory error showed up in log when I did the manual sbatch submission, but the memory error strangely doesn't show up in the log during automatic job management by NF.

**Comment by pditommaso** [comment]
OK, if so we can close this issue.
