### ISSUE TITLE
Killing Nextflow run does not kill Google Batch VMs

### ISSUE THREAD

**Issue by BeyondTheProof** [nextflow-io/nextflow#3847]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

VMs created by Nextflow are not always killed when aborting the pipeline manually (keyboard interrupt).

### Steps to reproduce the problem

Don't have an MRE, can create one if needed, but this only seems to happen when running certain packages (https://github.com/yanglab-emory/TIGAR), or maybe because of the specific docker images running.

### Program output 

![Screenshot 2023-04-07 at 5 49 13 PM](https://user-images.githubusercontent.com/25111528/230696168-ffd1d7ac-d2b4-4836-a6e9-4d59b552d4bd.png)

![Screenshot 2023-04-07 at 5 49 47 PM](https://user-images.githubusercontent.com/25111528/230696225-fba353c8-9081-4785-955d-a7748d7d0747.png)

```
...
Apr-08 00:39:30.102 [SIGINT handler] DEBUG nextflow.Session - Session aborted -- Cause: SIGINT
Apr-08 00:39:30.117 [SIGINT handler] DEBUG nextflow.Session - The following nodes are still active:
[process] UPLOAD_EQTL_FILES
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] ESTIMATE_HERITABILITY
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] UPLOAD_TWAS_FILES
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

Apr-08 00:39:30.119 [main] DEBUG nextflow.Session - Session await > all processes finished
Apr-08 00:39:30.120 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-08 00:39:30.126 [main] WARN  n.processor.TaskPollingMonitor - Killing running tasks (8)
Apr-08 00:39:30.130 [main] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Oops.. invalid delete action
Apr-08 00:39:30.131 [main] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Oops.. invalid delete action
Apr-08 00:39:30.132 [main] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Oops.. invalid delete action
Apr-08 00:39:30.132 [main] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Oops.. invalid delete action
Apr-08 00:39:30.133 [main] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Oops.. invalid delete action
Apr-08 00:39:30.134 [main] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Oops.. invalid delete action
Apr-08 00:39:30.134 [main] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Oops.. invalid delete action
Apr-08 00:39:30.134 [main] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Oops.. invalid delete action
Apr-08 00:39:30.136 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=40; failedCount=6; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retrie
sCount=6; abortedCount=8; succeedDuration=35d 23h 3m 31s; failedDuration=7d 22h 39m 29s; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=11; peakCpus=510; peakMemory=1.2 TB; ]
Apr-08 00:39:30.136 [main] DEBUG nextflow.trace.ReportObserver - Workflow completed -- rendering execution report
Apr-08 00:39:30.206 [main] DEBUG nextflow.trace.ReportObserver - Execution report summary data:
...
UPLOAD_TWAS_FILES (2)","q3Label":"UPLOAD_TWAS_FILES (2)"},"writes":{"mean":105255,"min":101902,"q1":103578.5,"q2":105255,"q3":106931.5,"max":108608,"minLabel":"UPLOAD_TWAS_FILES (1)","maxLabel":"UPLOAD_TWAS_FILES (2)","q1Label":"UPLOAD_TWA
S_FILES (1)","q2Label":"UPLOAD_TWAS_FILES (1)","q3Label":"UPLOAD_TWAS_FILES (1)"}}]
Apr-08 00:39:30.854 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Apr-08 00:39:30.854 [main] INFO  org.pf4j.AbstractPluginManager - Stop plugin 'nf-google@1.7.1'
Apr-08 00:39:30.854 [main] DEBUG nextflow.plugin.BasePlugin - Plugin stopped nf-google
Apr-08 00:39:30.863 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

### Environment 

* Nextflow version: version 23.03.0-edge build 5851
* Java version: openjdk version "17.0.6" 2023-01-17
* Operating system: Ubuntu
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by bentsherman** [comment]
The error comes from here:

https://github.com/nextflow-io/nextflow/blob/bb8369603fc6d66cce306e2ef0d1aa40f3a4eef1/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L378-L387

Jobs in google batch are automatically deleted upon completion. My guess is that Nextflow is allowing already running jobs to finish even if the workflow was cancelled. Were these jobs eventually cleaned up on their own?

**Comment by BeyondTheProof** [comment]
No, they were not. I had to go in to the Batch console and delete them manually.

**Comment by BeyondTheProof** [comment]
There was no `.exitcode` file written to the work directory. Just the following:
```
-rw-r--r-- 1 jupyter jupyter     0 Apr  7 23:58 .command.begin
-rw-r--r-- 1 jupyter jupyter 13040 Apr  7 23:56 .command.run
-rw-r--r-- 1 jupyter jupyter   332 Apr  7 23:56 .command.sh
```

**Comment by bentsherman** [comment]
No exit code, no log files makes me think the tasks were still running. To confirm whether this issue is real, you'll have to cancel the workflow, wait for the tasks to finish, and then see if the VMs are deleted.

**Comment by Puumanamana** [comment]
With google-batch, I often get work directories without .exitcode, .log when a task exceeds resources and returns with a null exit. code.

**Comment by bentsherman** [comment]
Indeed, these files will not exist if the VM was killed before they could be written. But in that case the VM is deleted, so it cannot be confused with this case of the workflow being cancelled

**Comment by BeyondTheProof** [comment]
I have found that this happens when there are processes that hang on the VM. In these scenarios, I think Batch never gets the OK to shut the VMs down, even though NF thinks they have been shut down. Maybe there is another way of terminating the VMs?

**Comment by bentsherman** [comment]
Nextflow supports the `time` directive for Google Batch, so you could add a time limit if you're worried about processes hanging.

**Comment by BeyondTheProof** [comment]
Yes, I learned about that recently. Unfortunately, `time` is not appropriate here, because each job can take a varying amount of time, which varies by over an order of magnitude. So if you set it too low, jobs will be killed prematurely, and if you set it too high, jobs will be sitting and racking up costs.

Regardless, I figured out what the issue is. There were some processes on the machine that were not being properly killed, namely, `tabix`, which was being spawned by the python processes I was running in a docker image. Because they were not exiting, the machine was not shutting down. 

NextFlow seems to send a kill signal to kill the job to Batch, but it doesn't seem to verify that the job is indeed killed. Is there a way to add such a feature? I've figured it out in this specific case, but I imagine that it would recur in the future. Maybe the user could specify a certain amount of time to wait after the job is sent the kill signal to check and force stop?

**Comment by mribeirodantas** [comment]
It's great to hear you found out what was going wrong, @BeyondTheProof!

About the `time` process directive, though, you can use process selectors with labels (or even with the process name) to make sure there's an appropriate value for `time` for every process you're interested in having this directive.

**Comment by bentsherman** [comment]
Also, not sure if it's what you meant, but the `time` directive is only an upper bound, so it won't force a task to stay alive if it finishes early.

**Comment by BeyondTheProof** [comment]
> It's great to hear you found out what was going wrong, @BeyondTheProof!
> 
> About the `time` process directive, though, you can use process selectors with labels (or even with the process name) to make sure there's an appropriate value for `time` for every process you're interested in having this directive.

Great to know, that may be helpful! 

> Also, not sure if it's what you meant, but the `time` directive is only an upper bound, so it won't force a task to stay alive if it finishes early.

Yes, it won't *force* it to stay alive, but since all the tasks were staying alive anyway, it wouldn't be killing them at an appropriate time. 

I still believe that this is a problem, though. If the NF pipeline is killed, then the jobs should be killed regardless of whether there is a hanging process or not. Do you think this is an issue on the Batch side or Nextflow? If on the side of Batch, what should I tell them?

**Comment by bentsherman** [comment]
Yeah, I would ask the Google Batch folks about it. You would need a way to send a SIGKILL through the Google Batch API to the VM (the existing delete API call probably sends a SIGTERM). Nextflow has no way to do that. But, keep in mind that the Google Batch folks might just respond with "you shouldn't launch processes that don't respect SIGTERM."

On that note, try to replicate the hanging process outside of Nextflow -- launch the Docker container and send it a SIGTERM (e.g. with the `kill` command). You'll need to confirm with the Google Batch folks if that's a realistic emulation of what Google Batch does, but whether it shuts down will help isolate the root cause.

**Comment by bentsherman** [comment]
@BeyondTheProof do you ever have the problem where you don't cancel a workflow and it runs forever because of this `tabix` process? Or is it only a problem when you cancel the workflow?
