### ISSUE TITLE
Process completed but task still running

### ISSUE THREAD

**Issue by Nathanrown** [nextflow-io/nextflow#3850]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

Expect nextflow workflow to error and halt.

Actual behavior is Process completed but task still running
### Steps to reproduce the problem
Here is my bash script, input file is actually a jpg file (a.jpg) but I change it into sh(a.jpg.sh)
```groovy
#!/usr/bin/env nextflow
nextflow.enable.dsl=2

params.file='/test'
params.dir='/test1'

process readfile {
  afterScript 'sleep 1'

  input:
  file input_file
  path input_dir
  """
  cat ${input_file}
  cd ${input_dir};pwd;cd ..;
  """
}

workflow {
  def filepath = Channel.fromPath(params.file)
  def dirpath = Channel.fromPath(params.dir)
  readfile(filepath,dirpath)
}
```

### Program output 

```
Caused by: 
   Input length = 1 
  
 java.nio.charset.MalformedInputException: Input length = 1 
 	at java.base/java.nio.charset.CoderResult.throwException(Unknown Source) 
 	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source) 
 	
 
 Mar-30 17:11:37.018 [main] DEBUG nextflow.Session - Session await > all barriers passed 
 Mar-30 17:11:37.161 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=1; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=1; retriesCount=0; abortedCount=0; succeedDuration=334ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=1; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ] 
 Mar-30 17:11:37.161 [main] DEBUG nextflow.trace.TraceFileObserver - Flow completing -- flushing trace file 
```
succeededCount=1  runningCount=1

### Environment 

* Nextflow version: [ 22.04.0.5697] 
* Java version: [openjdk 11.0.7 2020-04-14]
* Operating system: [Linux version 4.18.0]
* Bash version: (GNU bash, version 5.0.17(1)-release)

### Additional context

(Add any other context about the problem here)

**Comment by bentsherman** [comment]
It looks like Nextflow encountered a low-level IO error but otherwise completed. Can you provide a more complete log? Particularly the stack trace, it looks truncated.

Also can you elaborate on what you're saying here: 
> Here is my bash script, input file is actually a jpg file (a.jpg) but I change it into sh(a.jpg.sh)

**Comment by pditommaso** [comment]
Unable to replicate
