### ISSUE TITLE
`checkIfExists` gives wrong error when used in an included workflow

### ISSUE THREAD

**Issue by nvnieuwk** [nextflow-io/nextflow#3854]
### Expected behavior and actual behavior

When `file("non-existing-file.txt", checkIfExists:true)` is placed inside a script which is included in another script, the following error is thrown (if the file doesn't exist):
```
ERROR ~ Unable to read script: '/home/nvnieuwk/Documents/nextflow/issues/checkexists/./test.nf' -- cause: /home/nvnieuwk/Documents/nextflow/issues/checkexists/non-existing-file.txt
```

while something like this is expected:
```
ERROR ~ No such file or directory: /home/nvnieuwk/Documents/nextflow/issues/checkexists/non-existing-file.txt
```

### Steps to reproduce the problem

Following scripts need to be in the same directory:
1. main.nf
```
include { TEST } from './test.nf'

workflow {
    TEST()
}
```

2. test.nf
```
file("non-existing-file.txt", checkIfExists:true)

workflow TEST {
    Channel.fromPath(params.test_file).view()
}
```

Then execute this command to reproduce the problem (make sure `non-existing-file.txt` isn't inside that folder too):
```
nextflow run main.nf
```

### Environment 

* Nextflow version: 22.05.0 and 23.04.0 were tested
* Java version: openjdk 17.0.6 2023-01-17
* Operating system: Linux
* Bash version: 5.0.17

**Comment by bentsherman** [comment]
Indeed, I think it's a consequence of this code:

https://github.com/nextflow-io/nextflow/blob/9f09e7b0f0e9c0f22d440dbd8d166bea66d936aa/modules/nextflow/src/main/groovy/nextflow/script/ScriptParser.groovy#L202-L217

The `ScriptParser` actually parses and runs the script in the same try-catch block, so parsing errors and runtime errors would be treated the same as "Unable to read script: ...".

@pditommaso shouldn't the ScriptParser just parse the script? And the ScriptRunner should run the script? Maybe that would be clearer overall, and as part of that we could clarify this error as well.

**Comment by pditommaso** [comment]
We should look into the commit history, but there was parser error reported as IOException. However yes, that's too generic

**Comment by pditommaso** [comment]
Well, the log does not help much

https://github.com/nextflow-io/nextflow/commit/52c2780e920188eaa46c02b9474af6f363921385

It would be nice to try narrowing the exception raised by this error condition, to avoid to capture all IOExceptions

**Comment by bentsherman** [comment]
Okay, I will work on a PR for this when I have some time.
