### ISSUE TITLE
Add MaxWallClockTime to Azure batch pools

### ISSUE THREAD

**Issue by Psy-Fer** [nextflow-io/nextflow#3865]
## New feature

When using Azure batch and the existing Azure Cloud advanced settings, there is no way to set the maximum wall time for a job to run. This means the default wall time is used, which can be insufficient when running large genomic datasets through various bioinformatics tools.

Would it be possible to extend the Azure Cloud advanced settings options to include a way to set the
`TaskConstraints.MaxWallClockTime Property`  for a pool.

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.taskconstraints.maxwallclocktime?view=azure-dotnet

## Usage scenario 

When analysing large genomic datasets with pipelines, some steps can take a long time which can exceed the maximum wall time for a task to run. Being able to increase this in the nextflow.config file for a pipeline would allow us to manage this limitation, where currently there isn't a way to do that with nextflow.

## Suggest implementation 

I'm not sure of the details of implementing it into nextflow, but for a user, I could see it available in the config file like this, where `MaxWallClockTime` is an advanced setting in the form `azure.batch.pools.<name>.MaxWallClockTime`

nextflow.config
```groovy
plugins {
  id 'nf-azure'
}

process {
  executor = 'azurebatch'
}

azure {
  registry {
    server = secrets.azure_registry_server
    userName = secrets.azure_registry_username
    password = secrets.azure_registry_password
  }
  batch {
    location = secrets.azure_batch_location
    accountName = secrets.azure_batch_accountName
    accountKey = secrets.azure_batch_accountKey
    allowPoolCreation = true
    pools {
      'default' {
        autoScale = true
        vmCount = 1
        maxVmCount = 4
        vmType = 'Standard_D8_v3'
        sku = 'batch.node.ubuntu 20.04'
        offer = 'ubuntu-server-container'
        publisher = 'microsoft-azure-batch'
        MaxWallClockTime = '48h'
        privileged = true
      }
      'big' {
        autoScale = true
        vmCount = 1
        maxVmCount = 4
        vmType = 'Standard_D32_v3'
        sku = 'batch.node.ubuntu 20.04'
        offer = 'ubuntu-server-container'
        publisher = 'microsoft-azure-batch'
        MaxWallClockTime = '120h'
        privileged = true
      }
    }
  }
```

Thanks
James

**Comment by bentsherman** [comment]
@Psy-Fer do you actually want to set this property on the pool? I was just going to expose it through the `time` directive, so it would be applied to each task.

Also, the docs [here](https://learn.microsoft.com/en-us/java/api/com.microsoft.azure.batch.protocol.models.taskconstraints?view=azure-java-stable#com-microsoft-azure-batch-protocol-models-taskconstraints-withmaxwallclocktime(org-joda-time-period)) say that by default there is no time limit. So have you observed a default time limit killing your jobs prematurely? Can a time limit actually be applied to pools as well?

**Comment by Psy-Fer** [comment]
I have hit limits, though I will admit it can be tricky sometimes to pin down exactly what goes wrong (and expensive to reproduce). 

So this gives us two helpful outcomes. 
1. The ability to get around any limit that might be there causing problems
2. A way to limit a job to some upper maximum so we don't blow all our money on a misbehaving task.

Anyway, thanks for the addition.

**Comment by bentsherman** [comment]
Yes, we ended up adding it at the task level via the `time` directive. Feel free to try it on the next edge release and let us know if it works for you. And if you do discover the source of any time limits, please let us know here, it might be useful for us to document it.
