### ISSUE TITLE
Invalid string comparing using equals operator

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#3873]
The following snipper uses a `!=` operator two compare two strings instead of using `.equals` (notice it's a Java code, not groovy) 

https://github.com/nextflow-io/nextflow/blob/a2f3bb24d7b027e617e6c2b28c4061cf39191bcf/plugins/nf-amazon/src/main/nextflow/cloud/aws/nio/S3Client.java#L586-L587

Also it's not clear the intent of the comparing because for example the expiration would be set of even for non glacier storage class such as `STANDARD`

**Comment by bentsherman** [comment]
My mistake, forgot about that detail in Java. I will submit a fix. I guess that will cause the expiration days to never be set.

The intelligent tiering is not subject to expiration, so it will throw an error if you try to set it, see the docs here: https://docs.amazonaws.cn/en_us/AmazonS3/latest/userguide/batch-ops-initiate-restore-object.html
