### ISSUE TITLE
Spack page is unavailable for latest docs

### ISSUE THREAD

**Issue by mribeirodantas** [nextflow-io/nextflow#3876]
## Bug report 

The spack page on latest ([here](https://www.nextflow.io/docs/latest/spack.html)) is broken, but works fine on edge ([here](https://www.nextflow.io/docs/edge/spack.html)).

### Expected behavior and actual behavior

Both pages should be available.

### Steps to reproduce the problem

Go to [https://www.nextflow.io/docs/latest/spack.html](https://www.nextflow.io/docs/edge/spack.html) or click on Spack from the [docs.nextflow.io](docs.nextflow.io).

**Comment by pditommaso** [comment]
Fixed https://www.nextflow.io/docs/latest/spack.html
