### ISSUE TITLE
Missing documentation page?

### ISSUE THREAD

**Issue by marcodelapierre** [nextflow-io/nextflow#3894]
Hi @pditommaso ,

I see that the Spack environments doc page is visible in the edge docs: https://www.nextflow.io/docs/edge/spack.html
but not in the "latest" ones: https://www.nextflow.io/docs/latest/spack.html ; however, these docs still present it as an item in the left bar. This makes sense to me as nextflow 23.04 had indeed the Spack envs feature.

Do you know what is going on?

**Comment by pditommaso** [comment]
There should be a glitch, I'll check asap

**Comment by pditommaso** [comment]
Sorted 

https://www.nextflow.io/docs/latest/spack.html
