### ISSUE TITLE
Submit jobs in batches to allow easier monitoring

### ISSUE THREAD

**Issue by raimondsre** [nextflow-io/nextflow#3903]
Currently nextflow submits all jobs as individual submissions

However, in most HPC systems you can submit jobs in batches of e.g. 10,  so there will be batch ID and also individual job ID in queue. 

It allows HPC admins to monitor system easier

**Comment by bentsherman** [comment]
You're in luck, we're working on a PR for this. Currently supports AWS Batch and a bunch of HPC schedulers. Let me know if your preferred scheduler isn't covered by the PR, and if it is, please feel free to test the PR in your environment.
