### ISSUE TITLE
get params-file via workflow object

### ISSUE THREAD

**Issue by mattheatley** [nextflow-io/nextflow#3925]
it would be great if we could get the params-file via the workflow introspection like you can with config files, profiles etc (e.g. workflow.paramsFile or something similar). you can get it via workflow.commandLine already but having a separate property in the workflow object would be more convenient for logs etc

**Comment by mattheatley** [comment]
fair question i suppose! i'm generally parsing multiple parameters so it's much easier to store in a file and provide a single params-file input. previously i'd provide the parameters as a separate profile but figured it makes more sense to provide parameters through the parameters option. so instead of -profile docker,settings1 it's now -profile docker -params-file path/to/settings1.json. i could get everything from the params variable in the workflow but then i have to save them again. I thought it makes more sense to just record my original input like you can do with config, profiles etc - it seems a bit odd that this option is the only one missing.

**Comment by bentsherman** [comment]
In general, I think it's safer to just print the `params` object, because you can have params from many different sources -- params file, CLI options, `params` config scope, pipeline script, module scripts -- so you'll want to have the final resolved params object.

**Comment by mattheatley** [comment]
But I’m still at a loss why it’s not possible to access the argument for params-file when it is for others such as config and profile. I think it’s great having flexibility in how parameters can be provided but at the same time it leads to the confusion you mention. it seems more sensible to provide them through a single source and to do so via the dedicated option provided. I get the impression that this is the approach being promoted by the nfcore community.
