### ISSUE TITLE
Better documentation for groupTuple and groupKey

### ISSUE THREAD

**Issue by benbfly** [nextflow-io/nextflow#3935]
I have a scatter/gather workflow and need to gather the files from a particular sample using the groupBy() operator.  The format of my input channel is as follows:

```
[
    {
        "id": "SAMP_0002",
        "single_end": "false"
    },
    "SAMP_0002_0.ubam"
],
[
    {
        "id": "SAMP_0002",
        "single_end": "false"
    },
    "SAMP_0002_1.ubam"
]
```

What I would like to do is wait until all the emissions from the upstream channel have finished and then to merge them with:

```
    reads_sized
        .groupTuple(by: 0)
        .set {reads_grouped}
```

To get a merged channel like this:
```
[
    {
        "id": "SAMP_0002",
        "single_end": "false"
    },
    ["SAMP_0002_0.ubam", "SAMP_0002_1.ubam"]
],
```

It's really unclear to me what happens if you don't specify a `size` parameter to `groupTuple()`. Does it block until the input channel has finished all its emissions?  Is it possible that it will emit multiple tuples with the same key if they come in at different times?

The "tip" suggests that you need to either specify a constant `size` or calculate the sizes of each key in advance and using built in function `groupKey`, but it's not clear to me exactly how `groupKey` works, and I don't see any documentation on groupKey or its inputs and outputs.

I went to the "patterns" example on groupTuple (https://nextflow-io.github.io/patterns/process-into-groups/), but it does not use `groupKey` at all even though the groups would have variable size in that example.

Overall, scatter gather seems like an important pattern and I think people would benefit from reviewing this documentation.  Or is there a better operator to use for my example above?

(Note, the history of `groupKey` seems to be in this issue https://github.com/nextflow-io/nextflow/issues/796 )

**Comment by micans** [comment]
Hi, just in case it's useful, this is a simple example I made to illustrate `groupKey`. I hope it captures enough of what you need. I do believe `groupTuple` blocks if you specify neither `size` nor `groupKey` -- that was the reason for requesting the groupKey feature back in 2018. The `groupKey` invocation is not exactly self-explanatory; I just use it as an idiomatic phrase.

```
Channel.from(['a', [1, 2, 3]], ['b', [4, 5]], ['c', [6, 7, 8]])
   .map { tag, stuff -> tuple( groupKey(tag, stuff.size()), stuff ) }
   .view()
   .transpose()
   .map { tag, num -> [tag, num*num+1 ] }
   .view()
   .groupTuple()
   .view()
   ```

**Comment by bentsherman** [comment]
Thanks for pointing it out. I think the tip under groupTuple could be more clear about what happens when you do or don't specify a group size (be it a constant size or based on groupKey). Also, there are several built-in methods (including groupKey) that aren't documented in a reference-complete manner. I will make a note to add these things.
