### ISSUE TITLE
queueSize does not work at all, always submit 100 jobs

### ISSUE THREAD

**Issue by zillurbmb51** [nextflow-io/nextflow#3936]
Hi,

I have a nextflow script with multiple processes. Some processes want to submit 1000-2000 jobs together. But, it always submit only 100 jobs which is default. No matter how I change the queueSize option, it never submit more than 100 jobs. I tried both inside script using `queueSize=1500` and in the command line `-qs 1500`. None works. Any help?

```
nextflow version: 22.10.6
OS: linux
executor: slurm
```

**Comment by bentsherman** [comment]
Did you try this in your nextflow config?
```groovy
executor {
    queueSize = 1500
}
```

**Comment by zillurbmb51** [comment]
Thank you @bentsherman 
I had to reduce number of cpus and time for each process and now it is working!
