### ISSUE TITLE
Google Batch jobs can be submitted to spot GPUs by default

### ISSUE THREAD

**Issue by ejseqera** [nextflow-io/nextflow#3937]
### Expected behavior and actual behavior

When submitting a job to Google Batch, without Fusion enabled, there is a default list of instances included in a cost correction map in the [MachineTypeSelector ](https://github.com/nextflow-io/nextflow/blob/e0e24bdac40abdd2d72f0cd041f4aa0af1dbf569/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchMachineTypeSelector.groovy) code to prioritize or enable use of faster CPUs. This map includes the `a2-*` instance family of GPU VMs. 

```
private static final Map<String, BigDecimal> FAMILY_COST_CORRECTION = [
            'e2' : 1.0,   // Mix of processors, tend to be similar in performance to N1

            // INTEL
            'n1' : 1.0,   // Skylake, Broadwell, Haswell, Sandy Bridge, and Ivy Bridge ~2.7 Ghz
            ...
            'a2' : 0.9,   // Intel Xeon Platinum 8273CL ~2.9 Ghz
```

Including `a2` in the prioritization can allow for users to submit jobs to spot GPU VMs despite not configuring their workflows to use GPUs with the `accelerator` directive or within a list of `machineTypes` in the config.

With Fusion enabled however, if the user does not provide the list of VMs to use, we default to `DEFAULT_FAMILIES_WITH_SSD = ['n1-*', 'n2-*', 'n2d-*', 'c2-*', 'c2d-*', 'm3-*']` (see relevant line [here](https://github.com/nextflow-io/nextflow/blob/e0e24bdac40abdd2d72f0cd041f4aa0af1dbf569/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchMachineTypeSelector.groovy#L72)).

We should either (1) remove the `a2-*` instance types from `FAMILY_COST_CORRECTION` map, or (2) provide a default list of types to use if Fusion is not enabled.

### Steps to reproduce the problem

Don't have a MRE but below is an example of this occurring on a workflow submitted to Google Batch with spot VMs via Tower. Fusion was not enabled.

### Program output 

Google batch job log (some info redacted) for a task trying to run TrimGalore tool from nf-core/rnaseq pipeline that is submitted to `a2-highgpu-1g` GPU VM.
```
status:
  runDuration: 0s
  state: FAILED
  statusEvents:
  - description: Job state is set from QUEUED to SCHEDULED for job projects/-/locations/us-central1/jobs/nf-a5184529-1683132956567.
    eventTime: '2023-05-03T16:56:00.813633065Z'
    type: STATUS_CHANGED
  - description: Job state is set from SCHEDULED to FAILED for job projects/-/locations/us-central1/jobs/nf-a5184529-1683132956567.
    eventTime: '2023-05-03T16:59:37.378824434Z'
    type: STATUS_CHANGED
  taskGroups:
    group0:
      counts:
        FAILED: '1'
      instances:
      - bootDisk:
          image: projects/batch-custom-image/global/images/batch-cos-stable-official-20230419-00-p00
          sizeGb: '118'
          type: pd-ssd
        machineType: a2-highgpu-1g
        provisioningModel: SPOT
        taskPack: '1'
 runnables:
    - container:
        commands:
        - /bin/bash
        - -o
        - pipefail
        - -c
        - trap "{ cp .command.log /mnt/disks/tower-staging/scratch/ZNU7doi4a2ovY/a5/18452998dea97f172b7388ec14c865/.command.log;
          }" ERR; /bin/bash /mnt/disks/tower-staging/scratch/ZNU7doi4a2ovY/a5/18452998dea97f172b7388ec14c865/.command.run
          2>&1 | tee .command.log
        imageUri: quay.io/biocontainers/trim-galore:0.6.6--0
```

### Environment 
 
(For the example above) 
* Nextflow version: 
```
version 23.04.1 build 5866
Created: 15-04-2023 06:51 UTC 
```
* Java version: `Groovy 3.0.16 on OpenJDK 64-Bit Server VM 17.0.6+10-LTS`
* Operating system: `Linux 5.15.90+`
* Bash version: N/A
Using `plugin nf-google version: 1.7.3`

**Comment by jordeu** [comment]
I thought that the GPU price was included into the machine type price, so then I didn't care to blacklist them.
 But it seems that this is not the case and they charge GPU cost even if you don't "attach" them. So this can be considered a bug.

I think that the best solution is to define a default list similar to the one that we use with Fusion but without the restriction of allowing local SSD disk.

Maybe @ejseqera can suggest what can be a good default if the user do not explicitly define them.

**Comment by pditommaso** [comment]
> I think that the best solution is to define a default list similar to the one that we use with Fusion but without the restriction of allowing local SSD disk


Is it not supposed to be [this](https://github.com/nextflow-io/nextflow/blob/0781988bb28d1d2f53d3399fba070e831410be48/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchMachineTypeSelector.groovy#L50-L65) just removing `a2-*` ?

**Comment by jordeu** [comment]
No, that map is just a cost correction map to give some priority to faster CPUs. The full list of available is fetched from the region [here](https://github.com/nextflow-io/nextflow/blob/0781988bb28d1d2f53d3399fba070e831410be48/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchMachineTypeSelector.groovy#L85) and then we need to filter out the GPU types or just have a default list if the user do not set which do they want.

**Comment by pditommaso** [comment]
I see. @ejseqera can you please find out what would be the best choice of machine types?

**Comment by ejseqera** [comment]
How about these?
```
e2-*    // General purpose, mix of Intel processors
n1-*    // General purpose 1st gen, mix of Intel processors
n2-*    // General purpose 2nd gen, Intel Cascade Lake
n2d-*   // General purpose, AMD EPYC
c2-*    // Compute optimized, Intel Cascade Lake
c2d-*   // Compute optimized, AMD EPYC
m1-*    // Memory optimized, Intel Skylake, Broadwell
```

I'm inclined to leave `n1` types out entirely since `n2` types provide more memory per vCPU and apparently ~20% [better performance](https://www.linkedin.com/pulse/unearthing-gcp-compute-choosing-right-machine-your-product-pathak/) but 🤷‍♀️

**Comment by jordeu** [comment]
I think that I'd also keep `n1` types because we already take the difference of performance into account when we do the cost correction [here](https://github.com/nextflow-io/nextflow/blob/915074a421aaa883a6d6b8577bbb8086722a2723/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchMachineTypeSelector.groovy#L55).

**Comment by jordeu** [comment]
What about `m2` and `m3` ?  I think that not all the locations have these types but this is not a problem because we are filtering out only the available in the given location.

**Comment by ejseqera** [comment]
You're right, I didn't include `m2` and `m3` initially because of limited regional availability but we already control for that by filtering to types in that provided location. So I guess the revised list would be:
```
e2-*    // General purpose, mix of Intel processors
n1-*    // General purpose 1st gen, mix of Intel processors
n2-*    // General purpose 2nd gen, Intel Cascade Lake
n2d-*   // General purpose, AMD EPYC
c2-*    // Compute optimized, Intel Cascade Lake
c2d-*   // Compute optimized, AMD EPYC
m1-*    // Memory optimized, Intel Skylake, Broadwell
m2-*    // Memory optimized, Intel Cascade Lake
m3-*    // Memory optimized, Intel Ice Lake
```
