### ISSUE TITLE
Unable to start plugin 'nf-amazon' required by s3://ngi-igenomes/igenomes/

### ISSUE THREAD

**Issue by bingli2019** [nextflow-io/nextflow#3943]
## Bug report 
ERROR ~ Missing plugin 'nf-amazon' required to read file: s3://ngi-igenomes/igenomes/Arabidopsis_thaliana/Ensembl/TAIR10/Sequence/WholeGenomeFasta/genome.fa
(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

many ways tested , but cant not install (nextflow plugin install nf-amazon) nf-amazon

### Steps to reproduce the problem

nextflow run nf-core/rnaseq --input input.csv --outdir /home/bing/Downloads/rnaseq/output --genome TAIR10 -profile docker --max_cpus 18 --max_memory 60GB 

### Program output 

N E X T F L O W  ~  version 23.04.1
WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
WARNING: Could not load nf-core/config/rnaseq profiles: https://raw.githubusercontent.com/nf-core/configs/master/pipeline/rnaseq.config
WARNING: Could not load nf-core/config profiles: https://raw.githubusercontent.com/nf-core/configs/master/nfcore_custom.config
WARNING: Could not load nf-core/config/rnaseq profiles: https://raw.githubusercontent.com/nf-core/configs/master/pipeline/rnaseq.config
Launching `https://github.com/nf-core/rnaseq` [angry_carlsson] DSL2 - revision: 5671b65af9 [master]

------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/rnaseq v3.11.2-g5671b65
------------------------------------------------------
Core Nextflow options
  revision       : master
  runName        : angry_carlsson
  containerEngine: docker
  launchDir      : /home/bing/Downloads/rnaseq
  workDir        : /home/bing/Downloads/rnaseq/work
  projectDir     : /root/.nextflow/assets/nf-core/rnaseq
  userName       : root
  profile        : docker
  configFiles    : /root/.nextflow/assets/nf-core/rnaseq/nextflow.config, /home/bing/Downloads/rnaseq/nextflow.config

Input/output options
  input          : input.csv
  outdir         : /home/bing/Downloads/rnaseq/output

Reference genome options
  genome         : TAIR10
  fasta          : s3://ngi-igenomes/igenomes/Arabidopsis_thaliana/Ensembl/TAIR10/Sequence/WholeGenomeFasta/genome.fa
  gtf            : s3://ngi-igenomes/igenomes/Arabidopsis_thaliana/Ensembl/TAIR10/Annotation/Genes/genes.gtf
  gene_bed       : s3://ngi-igenomes/igenomes/Arabidopsis_thaliana/Ensembl/TAIR10/Annotation/Genes/genes.bed
  star_index     : s3://ngi-igenomes/igenomes/Arabidopsis_thaliana/Ensembl/TAIR10/Sequence/STARIndex/

Max job request options
  max_cpus       : 18
  max_memory     : 60GB

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/rnaseq for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.1400710

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/rnaseq/blob/master/CITATIONS.md
------------------------------------------------------
WARN: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Multiple config files detected!
  Please provide pipeline parameters via the CLI or Nextflow '-params-file' option.
  Custom config files including those provided by the '-c' Nextflow option can be
  used to provide any configuration except for parameters.

  Docs: https://nf-co.re/usage/configuration#custom-configuration-files
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Downloading plugin nf-amazon@1.16.2
WARN: Unable to start plugin 'nf-amazon' required by s3://ngi-igenomes/igenomes/Arabidopsis_thaliana/Ensembl/TAIR10/Sequence/WholeGenomeFasta/genome.fa
ERROR ~ Missing plugin 'nf-amazon' required to read file: s3://ngi-igenomes/igenomes/Arabidopsis_thaliana/Ensembl/TAIR10/Sequence/WholeGenomeFasta/genome.fa

 -- Check script '/root/.nextflow/assets/nf-core/rnaseq/./workflows/rnaseq.nf' at line: 27 or see '.nextflow.log' file for more details

### Environment 

* Nextflow version: [23.04.1.5866] 
* Java version: [17.0.3-internal]
* Operating system: [Linux]
* Bash version: (use the command `$SHELL --version`)

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Messed formatting -> closing
