### ISSUE TITLE
Google Batch VM issue

### ISSUE THREAD

**Issue by Joaodemeirelles** [nextflow-io/nextflow#3948]
## Bug report 

When using fusion V2, wave and process.scratch = false, I was not able to schedule Google Batch jobs for c2-standard-16 CPUs or higher. 

After talking with Google, it seems the issue is due to Nextflow trying to spawn an c2-standard-16 instance with only 1 local SSD, while the minimum for it is 2. This limits the VM instance to these machines (https://cloud.google.com/compute/docs/disks#localssds ):
N1 : all
N2: up to 10vCPU
N2D: up to 16vCPU
C2: up to 8 vCPU
C2D: up to 16vCPU

Google support also identified it looks like this is hard coded here:
https://github.com/nextflow-io/nextflow/blob/master/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L251

**Comment by pditommaso** [comment]
Good point, tagging @jordeu

**Comment by jordeu** [comment]
Maybe we should fix together with this PR where we add the `type` disk selector: https://github.com/nextflow-io/nextflow/pull/3861

**Comment by pditommaso** [comment]
This is expected to be solved by https://github.com/nextflow-io/nextflow/pull/3861 that will be included in the upcoming edge release
