### ISSUE TITLE
Failure to execute ch-run with current charliecloud version (0.32).

### ISSUE THREAD

**Issue by t-kreitler** [nextflow-io/nextflow#3951]
### Expected behavior and actual behavior

Failure to execute ch-run with current charliecloud version (0.32).

### Steps to reproduce the problem

Given a regular call: 
```nextflow run -without-docker -with-charliecloud ontresearch/wf-pore-c:sha51e5a1f25db6981a781851783e93efd05f8ef266 -ansi-log ...```

### Program output 

Yields:
```
Command exit status:
  64

Command output:
  (empty)

Command error:
  ch-run: unrecognized option '--no-home'
  Try `ch-run --help' or `ch-run --usage' for more information.
```

### Temporary kludge

A ch-run wrapper in the PATH that removes the '--no-home' from the argument list. The workflow completes like charm :)

### Environment 

* Nextflow version: 23.04.1
* Java version: openjdk-17.0.2.8
* Operating system: Linux
* Bash version: 5.1.4

### Additional context

The change was introduced by https://github.com/hpc/charliecloud/pull/1536

Without having tried, it looks to me that `--no-home` should be removed in `CharliecloudBuilder.groovy`, when running current and future versions of charliecloud.

Best,
  Thomas

**Comment by bentsherman** [comment]
I see, they removed `--no-home` because it's the default. Do you know which version of charliecloud did it become the default? If we remove it from Nextflow, we'll have to add a note that some older versions won't work anymore.

**Comment by t-kreitler** [comment]
It was finally removed in 0.32, in 0.31 there was still a deprecation warning.
From the docs I get that setting `runOptions` for charliecloud may cope for a missing `--no-home` when using an older version?

**Comment by bentsherman** [comment]
Okay I made a PR #3956. Feel free to test it. I think I will take this opportunity to install charliecloud and try it out ...
