### ISSUE TITLE
Pretty printing dumped channels modifies channel content

### ISSUE THREAD

**Issue by nebfield** [nextflow-io/nextflow#3952]
### Expected behavior and actual behavior

When dumping a channel (with`pretty: true`) that contains hash maps, it seems that integer values in the hash map are cast to strings.

I don't expect dumping a channel to change the contents of the channel, because this could break my downstream processes.

### Steps to reproduce the problem

```groovy
process foo {
    debug true

    input:
    val x

    script:
    def loud_animal = x.noise > 1
    """
    echo "Buggy process"
    echo "Noise level: $x.noise"
    echo "Loud animal: $loud_animal"
    """
}

process bar {
    debug true

    input:
    val x

    script:
    def loud_animal = x.noise.toInteger() > 1
    """
    echo "Working process"
    echo "Noise level: $x.noise"
    echo "Loud animal: $loud_animal"
    """
}


workflow {
    Channel.of(['animal': 'cat', 'noise': 0], ['animal': 'dog', 'noise': 5])
        .dump(tag: 'test', pretty: true)
        .set { ch_input }

    foo ( ch_input )
    bar ( ch_input )
}
```

### Program output 

By default everything is OK:

```console
$ nextflow run main.nf

Buggy process
Noise level: 0
Loud animal: false
Working process
Noise level: 5
Loud animal: true
Buggy process
Noise level: 5
Loud animal: true
Working process
Noise level: 0
Loud animal: false
```

When dumping channels things get weird:

```console
$ nextflow run main.nf -dump-channels test

[DUMP: test] {
    "animal": "cat",
    "noise": "0"
}
[DUMP: test] {
    "animal": "dog",
    "noise": "5"
}

Buggy process
Noise level: 5
Loud animal: true
Working process
Noise level: 5
Loud animal: true
Buggy process
Noise level: 0
**Loud animal: true** <------- cats should be quiet 
Working process
Noise level: 0
Loud animal: false
```

### Environment 

* Nextflow version: nextflow version 22.10.5.5840
* Java version: openjdk version "18.0.2" 2022-07-19
* Operating system: macOS
* Bash version: zsh 5.9 (x86_64-apple-darwin22.0)

### Additional context

This problem doesn't happen when dumping with `pretty: false`.

**Comment by bentsherman** [comment]
Indeed, when the object is a map, the pretty printer is modifying it instead of copying it. I will draft a PR shortly.
