### ISSUE TITLE
publishDir in process block in nextflow.config

### ISSUE THREAD

**Issue by pdp10** [nextflow-io/nextflow#3966]
## New feature
In the current pipeline I am working on, processes use the following publishDir directive: 
```
process fastq2bam {
    publishDir "${params.output_path}/${task.process.replaceAll(":", "/")}", mode: 'copy', overwrite: true, pattern: '*.bam'

    input:
        tuple path(ch_fastq1), path(ch_fastq2)

    output:
        path "*.bam", emit: ch_bam

    shell:
    """
    touch "my.bam"
    """
}
```
Whilst I find the way published files are organised helpful for debugging as they replicate the pipeline structure, having to replicate the whole directive for each process over and over seems quite odd.

## Usage scenario 

Avoid having to replicate publishDir directive configuration for each process.

## Suggest implementation 

I came across with this post: https://github.com/nextflow-io/nextflow/discussions/3107#discussioncomment-3369326 . 
It would be nice to code the publishDir directive in the process block in nextflow.config, e.g.:
```
process {
    // General publishDir setting
    publishDir = [
        path: { "${params.output_path}/${task.process.replaceAll(":", "/")}" },
        mode: "copy",
        overwrite: true
    ]
}
```
and then the actual process code to be: 
```
process fastq2bam {
    publishDir pattern: '*.bam'     // the rest inherited from the config above

// as code above
}
```

p.s. specifying the patter is redundant in this case as it is the only output file, however it can be helpful in general.

**Comment by bentsherman** [comment]
Closing in favor of #4186
