### ISSUE TITLE
add caching support for file function or filePath operator

### ISSUE THREAD

**Issue by mes5k** [nextflow-io/nextflow#397]
It would be extremely useful if files and directories read with the `file` function or the `fromPath` channel constructor had support for local caching like `storeDir` for processes.  The primary use case is for caching remote files, e.g. from S3 buckets.   Some proposed options include:

add a `storeDir` option to the `file` function:
```
f = file("s3://somebucket", storeDir: "/my/cache")
```

add a `storeDir` option to the `fromPath` channel constructor:
```
Channel.fromPath("s3://somebucket", storeDir: "/my/cache")
```

add a new caching operator:
```
Channel.fromPath("s3://somebucket").cache(storeDir:"/my/cache")
```

I think each option has merit.  I think adding caching to `file` and/or `fromPath` makes a lot of sense because if the file already exists in the cache then we could avoid re-downloading it.   However, adding a `cache` operator might be useful for generated files in addition to those downloaded, but wouldn't solve the problem of re-downloading files that may already exist in cache.

**Comment by pditommaso** [comment]
I tend to prefer the operator because is a more general solution. My proposal is to add a `cachePath` operator which *maps* a generic channel to a channel of cached paths (files or directories)  

```
channel
   .map{ key -> def file = createUniqueLocalFileGiven(key); tuple(key, file) }
   .filter { key, file -> !file.exists() }
   .map { key, file ->
      /* user logic to create the local file */ 
     return file
   }
```
 
One problem is that this would be sequential, thus suboptimal when downloading many S3 files.

**Comment by msmootsgi** [comment]
If I'm following your code, a solution to my problem would be:
```
Channel
    .from("s3://something")            // NOT fromPath instead the path is just a string
    .cachePath(storeDir: "/my/cache")  // downloads/copies/symlinks specified file if it doesn't exist locally
    .set{ my_file }                    // contains the local file
```

Is that right?  `cachePath` would only take a string input and the string should point to a file?  That would work for me, but I don't think I'm following as I'm not providing any `user logic to create the local file`.

**Comment by pditommaso** [comment]
That should be 

```
Channel
    .fromPath("s3://something") // as usual 
    .cachePath(storeDir: "/my/cache") { file, cache -> file.copyTo(cache) }
    .set{ my_file }
```

**Comment by msmootsgi** [comment]
Unfortunately, that wouldn't help me.  If there's no way for me to ___check___ the cache before creating whatever is getting cached, then it's not much help...

**Comment by pditommaso** [comment]
The `cachePath` would check that. The `{ file, cache -> file.copyTo(cache) }` would be invoked only if the `cache` file does not exist.

**Comment by msmootsgi** [comment]
But wouldn't `Channel.fromPath` have already downloaded the file?  I'm trying to avoid re-downloading large files.

**Comment by pditommaso** [comment]
Nope, `Channel.fromPath` just query the S3 client an create a `Path` object holding the S3 file metadata.

**Comment by msmootsgi** [comment]
AH!  Didn't realize `file` behavior was lazy like that.  How would this work for multiple files, like: 

```
Channel.fromPath("s3://something/*.fa")
```

Something like 
```
cachePath("/my/cache"){ files, cache -> files.collect{ it.copyTo(cache) } }
```
??
If so, then `cachePath` sounds fine to me.

**Comment by pditommaso** [comment]
same as before, `collect` is not needed because you have a file for each S3 object matching your pattern.

**Comment by msmootsgi** [comment]
Of course.  Got it.  All sounds good.  Still early here and I haven't had any caffeine yet!

**Comment by mes5k** [comment]
Hi Paolo, can you take a look at this branch: https://github.com/mes5k/nextflow/tree/new_cache and tell me what you think?  If this is close to what you want, then I'll add tests and documentation and then create a proper pull request.

**Comment by pditommaso** [comment]
Hi Mike, the structure is fine but I didn't mention that exists already two (undocumented) caching function. This operator use them. Check [cacheableFile](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/Nextflow.groovy#L297) and [cacheableDir](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/Nextflow.groovy#L272-272)  

The `cachePath` should have `dir` option to specify if you want to cache a file or a directory (default false). Then each channel entry is used a cachebleFile|Dir key. Then

1. If it return a path already existing the closure invocation is skipped
2. If the path does not exist the user closure is invoke passing as argument the original object (ie. the key) and the cache path 

Does it make sense ?

**Comment by fmorency** [comment]
I'm also interested in this feature.

My `work` and `publishDir` are located on a centralized NAS (share) and my compute nodes are using the `scratch` feature to perform the processing using the local node disk. Every time a new process is spawned, the compute node will first download the input files from the shared storage, perform the computation using the local disk and upload the results back on the shared storage. 

It would be interesting to have a caching mechanism that would make use of the compute node local disk so that if a compute node already seen (and downloaded) some file from the remote share, it is taken from the local cache instance instead of re-downloading it from the remote share.

**Comment by msmootsgi** [comment]
Hi Paolo, I finally found a bit of time or look at this again.  I've pushed some changes to my branch: https://github.com/mes5k/nextflow/tree/new_cache.  I now use `cacheableDir` and `cacheableFile`, however I do a couple things differently than you suggest.  

First, there's no `dir` parameter to `cachePath`.  Instead I just test whether the input path is a directory or not and distinguish based on that.  Seems simpler, no?

Second, there's no closure yet. Right now I just do the default behavior of copying the channel entry to the cache.  I can add the closure, but I'm struggling to imagine what the use case is for doing something other than copying the input data to the cache with a `cachePath` operator.

The only feature that I'd still like to add is a `symlink` parameter which will try to symlink the channel entry to the cache if that's possible.  The use case is to avoid unnecessary copying of local files when an input path might either be a local file (which shouldn't need caching) OR an S3 bucket (which would).

Let me know what you think and I can keep iterating.  I'll add tests, documentation, and make sure the branch is tidy once you're comfortable with the code.

**Comment by pditommaso** [comment]
Hi Mike, I think we are in the good direction, but I still think we need `dir` option. The current behaviour could work a default, but there could be the case you still want to cache all your files in single cache *directory*. Also we may want to apply this operator not just to `Path`s but to generic objects. In this case the user should be able to specify the `dir` option. 

Regarding the symlink, could not be a use case for the optional closure? For example: 

```
Channel
    .fromPath("/soemthing/*") // as usual 
    .cachePath() { file, cache -> file.mklink(cache) }
    .set{ my_file }
```

What do you think? 

In any case I think I would start some tests to understand better how it could be used in practice. You can use [this method](https://github.com/nextflow-io/nextflow/blob/master/src/test/groovy/test/TestHelper.groovy#L65-L69) to create an in memory foreign file.

**Comment by pditommaso** [comment]
Hi Mike, do you have an updated branch about this? I can give a try to it.

**Comment by msmootsgi** [comment]
Sorry, I've just had zero time to look at this lately and I haven't made any changes since my last comment.  But I haven't forgotten!  It's still on my todo list.

**Comment by pditommaso** [comment]
No problem. I could work on that if your branch is updated.

**Comment by mes5k** [comment]
I'm going to keep this alive since I apparently put some work into it!
