### ISSUE TITLE
Suggestion: Prettier terminal outputs

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#3976]
A few ideas for making the terminal output from Nextflow a bit prettier / easier to use (taken from a discussion on Slack with @bentsherman):

1. More use of colour
    * For example: Cached = grey, failed but ignored = orange, etc etc. Even small things like the `[` characters in dim / grey. Nextflow version number in grey, etc.
1.  Use of spinners to make it clear that Nextflow hasn't crashed, so that there's always movement even when waiting for stuff.
    * Bonus points: combine with a progress bar when we know the number of expected tasks for a process.
1. _Ambitious:_ ability to show stdout from running commands, but in a truncated rolling tail of 3-4 lines.
    * Example: `docker compose`, which shows the build log output as it goes along, but without taking up the whole terminal.

Just to get the conversation moving, I threw a Nextflow log into a Python script and coloured it using [Rich](https://github.com/Textualize/rich). Gives an idea of the kind of thing I'm thinking of for the colours (I stole the header style from Astro). 

<details>
<summary><code>demo.py</code></summary>

```python
from time import sleep
from random import randint
from rich.console import Console
from rich.progress import Progress, TextColumn, SpinnerColumn, BarColumn, ProgressColumn

console = Console()

log_msg = """
 🚀  [black on green] N E X T F L O W [/]  [dim]~  [/][green]version 23.04.1[/]

 ┃ Launching [magenta]`../main.nf`[/] [dim][[/][bold cyan]boring_montalcini[/][dim]][/] [dim]DSL2 - [/][dim magenta]revision: [/][magenta]d420d96c87[/]

[dim]executor >  local (3)[/]
[dim][[/][blue]89/615a07[/][dim]][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:PREPARE_GENOME:BISMARK_GENOMEPREPARATION[/] [dim]([/][yellow]BismarkIndex/genome.fa[/][dim])[/] [dim][[/][green]100%[/][dim]][/] 1 of 1 [green]✔[/]
[dim][[/][blue]2a/a06065[/][dim]][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:INPUT_CHECK:SAMPLESHEET_CHECK[/][dim]([/][yellow]samplesheet_test.csv[/][dim])[/]               [dim][[/][green]100%[/][dim]][/] 1 of 1, [dim]cached: 1[/] [green]✔[/]
[dim]executor >  local (3)[/]
[dim][[/][blue]89/615a07[/][dim]][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:PREPARE_GENOME:BISMARK_GENOMEPREPARATION[/] [dim]([/][yellow]BismarkIndex/genome.fa[/][dim])[/] [dim][[/][green]100%[/][dim]][/] 1 of 1 [green]✔[/]
[dim][[/][blue]2a/a06065[/][dim]][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:INPUT_CHECK:SAMPLESHEET_CHECK[/] [dim]([/][yellow]samplesheet_test.csv[/][dim])[/]              [dim][[/][green]100%[/][dim]][/] 1 of 1, [dim]cached: 1[/] [green]✔[/]
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:CAT_FASTQ[/]                                                         [dim][[/][blue]  0%[/][dim]][/] 0 of 1
[dim][[/][blue]45/35fba0[/][dim]][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:FASTQC[/] [dim]([/][yellow]SRR389222_sub1[/][dim])[/]                                           [dim][[/][blue]  0%[/][dim]][/] 0 of 1
[dim][[/][blue]88/b2a6c9[/][dim]][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:TRIMGALORE[/] [dim]([/][yellow]SRR389222_sub1[/][dim])[/]                                       [dim][[/][blue]  0%[/][dim]][/] 0 of 1
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:BISMARK:BISMARK_ALIGN[/]                                             -
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:BISMARK:SAMTOOLS_SORT_ALIGNED[/]                                     -
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:BISMARK:BISMARK_DEDUPLICATE[/]                                       -
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:BISMARK:BISMARK_METHYLATIONEXTRACTOR[/]                              -
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:BISMARK:BISMARK_REPORT[/]                                            -
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:BISMARK:BISMARK_SUMMARY[/]                                           -
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:BISMARK:SAMTOOLS_SORT_DEDUPLICATED[/]                                -
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:QUALIMAP_BAMQC[/]                                                    -
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:PRESEQ_LCEXTRAP[/]                                                   -
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:CUSTOM_DUMPSOFTWAREVERSIONS[/]                                       -
[dim][-        ][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:MULTIQC[/]                                                           -
"""
console.print(log_msg, highlight=False)


with Progress(
    TextColumn("{task.description}"),
    SpinnerColumn(),
    TextColumn(
        "[dim][[/][blue]{task.percentage:>3.0f}%[/][dim]][/] {task.completed:>2.0f} of {task.total:>2.0f} "
    ),
    BarColumn(bar_width=10),
) as progress:
    task1 = progress.add_task(
        "[dim][[/][blue]2a/a06065[/][dim]][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:INPUT_CHECK:SAMPLESHEET_CHECK[/] [dim]([/][yellow]samplesheet_test.csv[/][dim])[/]          ",
        total=4,
    )
    task2 = progress.add_task(
        "[dim][[/][blue]45/35fba0[/][dim]][/] [dim]process >[/] [grey]NFCORE_METHYLSEQ:METHYLSEQ:FASTQC[/] [dim]([/][yellow]SRR389222_sub1[/][dim])[/]",
        total=18,
    )
    for i in range(18):
        sleep(randint(2, 4) / 10.0)
        if i < 4:
            progress.update(task1, advance=1)
        progress.update(task2, advance=1)
```

</details>

<img width="1159" alt="CleanShot 2023-05-29 at 11 18 05@2x" src="https://github.com/nextflow-io/nextflow/assets/465550/ce198a8c-0bc0-4880-b440-143d3853c1f7">

Arguably overkill with the colours, but hopefully you get my point - it's easier to scan for key information with this.

..ok and updated with an animated spinner / tiny progress bar to give the impression of animation:

https://github.com/nextflow-io/nextflow/assets/465550/cd25b9ff-0e8f-4610-b547-b1a2982e3682

**Comment by pditommaso** [comment]
That's very beautiful, but not sure exist something so cool as Rich for JVM world

**Comment by ewels** [comment]
_[Edit]: Split a couple of these points out into their own issues as they're slightly different to the topic of terminal logging styles:_ https://github.com/nextflow-io/nextflow/issues/3978 https://github.com/nextflow-io/nextflow/issues/3978

**Comment by ewels** [comment]
> That's very beautiful, but not sure exist something so cool as Rich for JVM world

True - I had a look a few years ago and didn't find anything amazing. But it's always possible to print ANSI codes manually. For nf-core I wrote [this wrapper function](https://github.com/nf-core/rnaseq/blob/5671b65af97fe78a2f9b4d05d850304918b1b86e/lib/NfcoreTemplate.groovy#L283-L349)

This returns a map that can then be used in a [log string](https://github.com/nf-core/rnaseq/blob/5671b65af97fe78a2f9b4d05d850304918b1b86e/lib/NfcoreTemplate.groovy#L369-L371) easily:

```groovy
"""
${colors.blue}        ___     __   __   __   ___     ${colors.green}/,-._.--~\'${colors.reset}
${colors.blue}  |\\ | |__  __ /  ` /  \\ |__) |__         ${colors.yellow}}  {${colors.reset}
${colors.blue}  | \\| |       \\__, \\__/ |  \\ |___     ${colors.green}\\`-._,-`-,${colors.reset}
"""
```

Something like this could be wrapped into the Nextflow logging code I think, and should work ok?

The spinner isn't much more complex, rich just has a [file of unicode characters](https://github.com/Textualize/rich/blob/68224905f5dc7a3c765e04aba0460b75a95f5004/rich/_spinners.py) for spinners, for [example](https://github.com/Textualize/rich/blob/68224905f5dc7a3c765e04aba0460b75a95f5004/rich/_spinners.py#L27), the dots spinner in the video above is just these characters in a loop:

```
⣾⣽⣻⢿⡿⣟⣯⣷
```
_(if you paste into a terminal the characters look more as you'd expect)_

I _think_ you've already done all the hard work by developing the ANSI logger, all that's needed for the above is some templating to introduce additional colour codes.

**Comment by ewels** [comment]
Ah yeah, you already have colours available with the jansi library:
https://github.com/nextflow-io/nextflow/blob/166b3638c29b08f4c1f2b01a0ee930ac31bec4d6/modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy#L29

Looking more, there's also an [`AnsiRenderer` class](https://fusesource.github.io/jansi/documentation/api/org/fusesource/jansi/AnsiRenderer.html) which you can use to give strings with format tags in, just the same as rich:

Rich:
```
[red]Error[/] [black on green]Actually everything is fine[/]
```

Jansi:
```md
@|red Error|@ @|fg_black,bg_green Actually everything is fine|@
```

**Comment by pditommaso** [comment]
Phil. I think this a great opportunity to improve your Groovy skills 😆

**Comment by ewels** [comment]
Another good thing to do would be to be more clever with truncation of the process names.

For example, here:

<img width="555" alt="CleanShot 2023-06-03 at 23 29 22@2x" src="https://github.com/nextflow-io/nextflow/assets/465550/6d3c9073-2b39-47be-a730-53d51f127e5e">

For example, we could do the following:
* Truncate the start or middle of the process name (instead of the end), so we can see the end. This is usually the interesting bit.
* Drop info (`process > `) at certain width breakpoints
* Drop the %age completion at certain width breakpoints
