### ISSUE TITLE
Don't lose log messages in ANSI mode

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#3978]
The ANSI mode clears terminal output for rendering, but this means any log messages that are printed outside of this scope get munched on refresh. It would be good to have some kind of wrapper around the logger / somehow otherwise capture these and keep them present in the ANSI output, if possible.

**Comment by bentsherman** [comment]
Can you find a good test case for us to work with?

**Comment by ewels** [comment]
Yeah I knew you'd say that 😆 Ok I'll try to put together a minimal example..

**Comment by ewels** [comment]
Hmm, ok maybe I'm imagining things. Closing for now, I'll try to keep an eye out for it happening and catch a reproducible example if I come across one. But maybe I'm just seeing things 👻 

Thanks for testing @robsyme 🙇🏻
