### ISSUE TITLE
Terminal logging about pulling containers / staging files

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#3979]
Nextflow often "hangs" when a pipeline first launches because of this for no obvious reason, we often get people asking what's wrong.

Having a log message about any file staging / conda env building / singularity image pulling / docker image pulling would be super helpful. Bonus points for an ANSI progress showing how much is done (comparable to existing process progress).

I have a feeling I've asked for this before and the answer was that it's done at process level and so the main Nextflow job doesn't know about it. But I still wanted to flag it in case there's anything we can do - it would be a good one to solve, especially for new users who aren't expecting it and their first impression is a terminal that seems to have crashed / frozen.

**Comment by bentsherman** [comment]
The conda env and singularity image building are done by Nextflow, and there are already log messages for them. Everything else is done by the task. So I guess it comes down to forwarding the task logs to the Nextflow console output.

How do you envision that? If a pipeline is running 1000 tasks concurrently, how would you concisely display the task logs?

Maybe we could merge all the logs into a single stream and display the trailing N lines. That way it doesn't take up a lot of space, and it basically just shows the user that stuff is happening.

**Comment by pditommaso** [comment]
> Yup, but Nextflow will see the log output from that command, right?

Not really, the docker logs are stored along with the task logs in the `.command.out` file. 

This file is generally stored in a container running in remote computer that the task runner script copies just before the execution complete to the bucket work dir (in a common cloud deployment scenario)

**Comment by ewels** [comment]
Ok if we forget containers for a moment, how about staging data?

**Comment by ewels** [comment]
😞  How about adding a "before" and "after" signal either side of those commands? Something to tell the head job that "I'm starting to stage data now" and "I'm done"? We don't need to know anything more than that.

Otherwise I guess just having a spinner will have to suffice. So that when it sits with `[0 of 142]` you at least see some movement and hope that _something_ is happening somewhere.. 😅

**Comment by bentsherman** [comment]
Nextflow does not communicate directly with its tasks or vice versa, everything happens through the executor API and the work directory. So for a task to signal that it has finished each stage, it would require Nextflow to ping the executor / work directory frequently for small updates, I don't think that would scale very well. A spinner may be the best we can do here to create movement.

**Comment by ewels** [comment]
Spinner it is 👍🏻  Closing, as that's part of https://github.com/nextflow-io/nextflow/issues/3976

Thanks for going through this thought exercise with me nonetheless :)
