### ISSUE TITLE
Optional parameter for set

### ISSUE THREAD

**Issue by fmorency** [nextflow-io/nextflow#399]
`optional true` parameter can only be applied to `file`. It would great if we could also make `set` optional such as

```
set sid, val(tmp), "foo" optional true into bar
```

**Comment by pditommaso** [comment]
@fmorency I've just uploaded `0.25.3-SNAPSHOT` which allows the `optional` parameter for `set`. warning: I had very little time to test it !

**Comment by fmorency** [comment]
@pditommaso I just tested it on a 13 processes pipeline and it works as expected! Thanks a lot!

**Comment by pditommaso** [comment]
@fmorency is it problem if I postpone the new release some days? You should be able to use the latest snapshot, right?

**Comment by fmorency** [comment]
When do you plan on releasing this? I would prefer to deploy an official
release on our cluster :)

**Comment by pditommaso** [comment]
I would like to include a couple of more bug. Hope next week.

**Comment by fmorency** [comment]
All good for me. Thanks a lot for working on this :)

**Comment by pditommaso** [comment]
Released with version `0.25.3`
