### ISSUE TITLE
Singularity Configuration Issue with LSF in nf-core workflow

### ISSUE THREAD

**Issue by IvanWoo22** [nextflow-io/nextflow#3991]
### Description:
I am encountering a singularity configuration issue while running the nf-core workflow using Nextflow. I submit the job script using `bsub`, and the tasks start executing, successfully submitting some tasks as per the settings. However, shortly after, I receive an immediate error:
**env: singularity: No such file or directory**.
Upon investigating, I believe the issue might lie in the following section of the `.command.run` file:
```bash
nxf_launch() {
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} SINGULARITYENV_NXF_DEBUG=${NXF_DEBUG:=0} singularity exec --pid -B /share/home/wangq/wyf/nfmethylseq /share/home/wangq/wyf/nfmethylseq/methylseq/workflow/../singularity-images/depot.galaxyproject.org-singularity-python-3.8.3.img /bin/bash -c "cd $PWD; eval $(nxf_container_env); /bin/bash /share/home/wangq/wyf/nfmethylseq/work/e2/e8995acb272dcf0c46d2c67befadf2/.command.run nxf_trace"
}
```

### P.S.:
These are the settings I added to the default `nextflow.config` file:
```bash
process {
    executor = 'lsf'
    queue = 'serial'
}

executor {
    cpus = 24
}
```
And this is my job submission script:
```bash
export NXF_EXECUTOR=lsf
export NXF_SINGULARITY_CACHEDIR=.
nextflow run methylseq/workflow --input samplesheet.csv --outdir output/. -profile singularity -resume --igenomes_base --fasta Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa --gtf Homo_sapiens.GRCh38.109.gtf --max_cpus 24
```

I would greatly appreciate any assistance or insights into resolving this singularity configuration issue. Thank you in advance for your help.

**Comment by bentsherman** [comment]
It's likely that `singularity` is missing from the `$PATH` environment variable when the launcher script tries to invoke singularity. Check and see where the `singularity` command is located, and make sure it's included in `$PATH` in the environment where you launch Nextflow.

**Comment by IvanWoo22** [comment]
> It's likely that `singularity` is missing from the `$PATH` environment variable when the launcher script tries to invoke singularity. Check and see where the `singularity` command is located, and make sure it's included in `$PATH` in the environment where you launch Nextflow.

Thank you for reply. So how could I export singularity to PATH?

I tried to add `export PATH="$PATH:/usr/local/bin/"` in the submission script but it didn't worked.

```bash
which singularity
/usr/local/bin/singularity
```

**Comment by bentsherman** [comment]
Well, `/usr/local/bin` should already be in your PATH. You can run `echo $PATH` to make sure.

Or to be more specific, modify the `.command.run` script by adding `echo $PATH` right before the singularity command, so that you see what the PATH is right before singularity is executed.

**Comment by IvanWoo22** [comment]
I used
```bash
process {
        executor     = 'lsf'
        queue        = 'serial'
        beforeScript = 'export PATH="$PATH:/usr/local/bin/"'
}

env {
    PATH="$PATH:/usr/local/bin/"
    PYTHONNOUSERSITE = 1
    R_PROFILE_USER   = "/.Rprofile"
    R_ENVIRON_USER   = "/.Renviron"
    JULIA_DEPOT_PATH = "/usr/local/share/julia"
}
```
 and there were
 ```bash
 export PATH="$PATH:/usr/local/bin/"
 ```
 in the `nxf_main()` block and
 ```bash
cat << EOF
export PATH="/share/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/bin:/share/home/wangq/.linuxbrew/sbin:/share/home/wangq/.linuxbrew/bin:/share/home/wangq/bin:/share/home/wangq/share/R/bin:/share/home/wangq/.cargo/bin:/share/home/wangq/share/Python/bin:/share/home/wangq/bin:/share/home/wangq/.local/bin:/share/home/wangq/.linuxbrew/opt/perl/bin:/share/home/wangq/.linuxbrew/bin:/share/home/wangq/.linuxbrew/sbin:/usr/lib64/qt-3.3/bin:/share/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/etc:/usr/local/go/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lpp/mmfs/bin:/opt/ibutils/bin:/share/home/wangq/.local/bin:/share/home/wangq/bin:/usr/local/bin/:/usr/local/bin/:/share/home/wangq/wyf/nfmethylseq/methylseq/workflow/bin"
export PYTHONNOUSERSITE="1"
export R_PROFILE_USER="/.Rprofile"
export R_ENVIRON_USER="/.Renviron"
export JULIA_DEPOT_PATH="/usr/local/share/julia"
EOF
```
in the `nxf_container_env()` block.

But the error remained and I don't know how to run `.command.run` independently.

**Comment by IvanWoo22** [comment]
> You can submit the `.command.run` like a job script to LSF, or if you can get an interactive node, just run it with bash.

I just manually added `echo $PATH` like this:
```bash
nxf_launch() {
    echo "$PATH"
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} SINGULA
RITYENV_NXF_DEBUG=${NXF_DEBUG:=0} singularity exec --pid -B /share/home/wangq/wyf/nfmethylseq /share/home/wangq/wyf
/nfmethylseq/methylseq/workflow/../singularity-images/depot.galaxyproject.org-singularity-python-3.8.3.img /bin/bas
h -c "cd $PWD; eval $(nxf_container_env); /bin/bash /share/home/wangq/wyf/nfmethylseq/work/af/9ce12ad1365b4f05b2dfe
edfda6ed0/.command.run nxf_trace"
}
```
and submit the `.command.run` script.

Output:
```bash
/share/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/bin:/share/home/wangq/miniconda3/condabin:/share/home/wangq/.linuxbrew/sbin:/share/home/wangq/.linuxbrew/bin:/share/home/wangq/bin:/share/home/wangq/share/R/bin:/share/home/wangq/.cargo/bin:/share/home/wangq/share/Python/bin:/share/home/wangq/bin:/share/home/wangq/.local/bin:/share/home/wangq/.linuxbrew/opt/perl/bin:/share/home/wangq/.linuxbrew/bin:/share/home/wangq/.linuxbrew/sbin:/usr/lib64/qt-3.3/bin:/share/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/etc:/usr/local/go/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lpp/mmfs/bin:/opt/ibutils/bin:/share/home/wangq/.local/bin:/share/home/wangq/bin:/usr/local/bin/
env: singularity: No such file or directory
```
I think the PATH included singularity but the error remained

**Comment by bentsherman** [comment]
Strange. Your path already has `/usr/local/bin`, so `env - PATH="$PATH" singularity --help` should work. It just creates a new environment, adds the existing PATH, and runs singularity. Maybe you should ask your sys admin about it? You should be able to show them this isolated piece of code (`nxf_launch`) and they might be able to help you debug it further.

**Comment by IvanWoo22** [comment]
@bentsherman Thank you for your help. I asked our hpcc admin and he gave me another path to singularity(`/opt/singularity-3.7.0`). Although the workflow is not running yet, it is no longer reporting an error at this location.
