### ISSUE TITLE
Error: cannot find Java

### ISSUE THREAD

**Issue by sjackman** [nextflow-io/nextflow#40]
I upgraded 0.12.2 to 0.13.1 and now see the error message "Error: cannot find Java or it's a wrong version". 0.12.2 worked and still works fine. 0.13.1 gives this error message.

```
~ ❯❯❯ nextflow -version
Error: cannot find Java or it's a wrong version -- please make sure that Java 7 or higher it's installed
Note: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home
 JAVA_HOME: 

~ ❯❯❯ java -version                                                           ⏎
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
~ ❯❯❯ brew switch nextflow 0.12.2
Cleaning /usr/local/Cellar/nextflow/0.12.2
Cleaning /usr/local/Cellar/nextflow/0.13.1
1 links created for /usr/local/Cellar/nextflow/0.12.2
~ ❯❯❯ nextflow -version

      N E X T F L O W
      Version 0.12.2 build 2674
      last modified 12-02-2015 11:17 UTC (12:17 CEST)
      http://nextflow.io
```

**Comment by pditommaso** [comment]
Hi,

I need to check it better. But it looks that your JAVA_CMD variable is not
pointing to the right java executable and the JAVA_HOME is missing.

**Comment by pditommaso** [comment]
Yes, you are right. There's a small glitch in the launcher script. I'm going to fix it. 

In the meanwhile you can run is defining the JAVA_HOME variable as shown below (for example): 

    export JAVA_HOME="$(/usr/libexec/java_home -v 1.7+)"


Thanks for reporting the problem.

**Comment by pditommaso** [comment]
Fixed with version 0.13.2

**Comment by sjackman** [comment]
Thanks, Paolo. I've opened a PR at Homebrew-science.

**Comment by pditommaso** [comment]
Great. Thanks for that.
