### ISSUE TITLE
When using git branches nextflow doesn't seem to pull updates for the branch

### ISSUE THREAD

**Issue by msmootsgi** [nextflow-io/nextflow#400]
I'm working on a branch of my pipeline, but when I push changes to the branch, it doesn't seem like the updated branch is getting pulled when nextflow runs. The logs seem to indicate that master gets pulled, but not the branches.

I believe that we just need to call `setRemoteBranchName` somewhere after [this line](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/scm/AssetManager.groovy#L570). 

I'll see if I can put a patch together.

**Comment by msmootsgi** [comment]
Nope.  In trying to come up with a test for my patch, I couldn't recreate this locally and trying again in the cloud had the branch getting pulled correctly.  Not sure what happened earlier, but I'll chalk it up to something I did wrong...

**Comment by hydriniumh2** [comment]
I think this relates to https://github.com/nextflow-io/nextflow/issues/233
