### ISSUE TITLE
Combining same channels giving file name collision error

### ISSUE THREAD

**Issue by zillurbmb51** [nextflow-io/nextflow#4004]
### Discussed in https://github.com/nextflow-io/nextflow/discussions/4002

<div type='discussions-op-text'>

<sup>Originally posted by **zillurbmb51** June  6, 2023</sup>
Hi,

I have a channel of `tuple (val, file)`. I assigned it into two channels `ch1, ch2`. So, both channels have same element and then combined them using `combine` operator. Because, I need the same element twice. But, when I use the combined channel in a process I am getting error that: `input file name collision -- There are multiple files for each of the following file names.` Any help?

Also if I use separately `ch1` and `ch2` like: 
```
input:
tuple val(st1), path(mng1) from ch1
tuple val(st2), path(mng2) from ch2
```
The same message `input file name collision -- There are multiple files for each of the following file names.` comes out. </div>

**Comment by bentsherman** [comment]
Closing in favor of #4002
