### ISSUE TITLE
Not setting Limits for k8s

### ISSUE THREAD

**Issue by xhejtman** [nextflow-io/nextflow#4015]
Hello,

I noticed that not setting CPU limits has landed in mainline. It seems to be just hardcoded. This is unfortunate, because if some default resources are set for a namespace, this is constantly failing as default resources are usualy low, e.g., 100m CPU and 512Mi memory. It causes that Limits are lower then Requests which does not pass API validation - limits must be at least the same value as requests.

Any idea how to resolve this?

**Comment by bentsherman** [comment]
I think this will be fixed by #3027, it will allow users to set an explicit limit for CPU requests.

**Comment by jacobsin** [comment]
Looks same issue as #3898

**Comment by jacobsin** [comment]
> I think this will be fixed by #3027, it will allow users to set an explicit limit for CPU requests.

Any idea when #3027 get merged to main for a release @fisherman? 🙏

**Comment by bentsherman** [comment]
> > I think this will be fixed by #3027, it will allow users to set an explicit limit for CPU requests.
> 
> Any idea when #3027 get merged to main for a release @bentsherman ? 🙏

That is up to @pditommaso 😄
