### ISSUE TITLE
Issues with NF and Azure Gen2 storage accounts

### ISSUE THREAD

**Issue by srhogg** [nextflow-io/nextflow#4016]
### Expected behavior and actual behavior

Using Azure Batch, with a storage account set to Gen2 Data Lake (to be SFTP compatible) the pipelines are completing however the result reports are not being created.  We receive errors stating:

```
Failed to publish file: az://sftp/work/17/b9d1cb00e68a02a575adc9950e703c/MultiQC_multiqc_report_data; to: az://sftp/test
_Result/multiqc/MultiQC_multiqc_report_data [copy] -- See log file for details
```

The log files give us the following details:

```
com.azure.storage.blob.models.BlobStorageException: Status code 400, "<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidInput</Code><Message>One of the request inputs is not valid.
```

There seems to be no issues in accessing the location or the folders, and this all works normally when using an Azure Storage Account without Gen2 Data Lake /Hierarchical Namespace enabled.

### Additional context

Issue discussed in NF Slack channel (https://nextflow.slack.com/archives/C02TPRRLCF4/p1686138328462629) and Venkat Malladi who believes there is an issue with gen2 and normal blob storage.

NextFlow version:  22.04.5
plugin 'nf-azure@0.13.2'

**Comment by benbfly** [comment]
I also had a failure to write reports, and we are also using Azure Gen2 Data Lake / Hierarchical storage.  Our storage is also on a vnet.
We are having a meeting this week internally to turn on logging on our account so that we can get more detailed tracking of these storage errors.
