### ISSUE TITLE
Additional `manifest` config fields

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#4034]
It would be great to have a few new `manifest` config variables to help describe pipelines:

```nextflow
manifest {
    docsURL = "https://mypipeline.com/docs"
    iconURL = "https://mypipeline.com/icon.png"
    icon = "assets/icon.png"
    organisation = "University of Phil"
    license = "MIT"
}
```

**Comment by abhi18av** [comment]
Mmm, interesting suggestion Phil!

Perhaps, it should be kept open-ended like with a `manifest.meta` field so that other tools/plugins could possibly populate or read from that field?

P.S. `"University of Phil"` sounds nice! 😄

**Comment by ewels** [comment]
I don't really understand how anything could (or should) populate it, other than the pipeline developers?

Having a field for an arbitrary map of keys could be nice to have a flexible use case 👍🏻  However, standardisation is nice. We could add that in addition to (some of?) the suggested keys above.

**Comment by abhi18av** [comment]
I was just wondering that since there are some Git related fields within `manifest` like `recurseSubmodules`, `defaultBranch` then it might make sense to logically combine further options together through an open-ended map like 

```nextflow 

manifest {
    homePage = 'http://foo.com'
    description = 'Pipeline does this and that'

    .. existing fields...

    meta {
         documentationUrl = "https://doc.pipeline.com"
         license = "MIT" 
         researchGroup = "some specific research group"

         ...arbitrary fields ...
    }
}

```

Also the idea regarding open-ended metadata stems from https://github.com/nextflow-io/nextflow/issues/2723, which might result in a config which is interchangeable with the JSON format.

**Comment by ewels** [comment]
Ah ok. Following that thread, it might make sense to move _all_ descriptive fields (including current) to a `meta` sub-map then?

```nextflow
manifest {
    defaultBranch
    recurseSubmodules
    mainScript
    name
    nextflowVersion
    version
    meta {
        author
        description
        doi
        homePage
        docsURL
        iconURL
        icon
        organisation
        license
    }
}
```

eg. depreciate `manifest.description` and `manifest.doi` etc, instead replacing with `manifest.meta.description`

**Comment by ewels** [comment]
I think deprecating the old ones and leaving them there for a version or two is probably ok. Like you say, we hopefully have a new config coming one day anyway.. 🤷🏻‍♂️

**Comment by bentsherman** [comment]
I recommend adding the following fields based on my experience with the prov formats:
- license
- map for authors with name, affiliation, email, orcid

**Comment by ewels** [comment]
Good idea with the author map 👍🏻

**Comment by pinin4fjords** [comment]
+1, and can we have manifest.maintainer, please?

**Comment by jfy133** [comment]
For maintainers (and maybe others), I think the CRAN R package manifests are a good guide, particularly when it comes to author/maintainer/contributors, e.g. for dplyr:

https://cran.r-project.org/web/packages/dplyr/index.html

**Comment by pditommaso** [comment]
Discussing this, it looks there consensus to move the new fields into `manifest` e.g. 

manifest {
        author
        description
        doi
        homePage
        docsUrl
        iconUrl
        icon
        organisation
        license
} 
```

**Comment by ewels** [comment]
Yup - adding an extra, plus some notes based on the discussion above:

```nextflow
manifest { 
    author     // String or an array of maps. Maps can contain orcid etc - see comment above
    maintainer // Same as above, new field
    description
    doi
    homePage
    docsUrl
    iconUrl
    icon
    organisation
    license
} 
```

**Comment by pditommaso** [comment]
What's `icon` vs `iconUrl` ?

**Comment by pditommaso** [comment]
We talked, we can use `iconUrl` both for relative path and fully qualified URL

**Comment by ewels** [comment]
Should maybe call it `icon`, but yeah 👍🏻

**Comment by pditommaso** [comment]
@jorgee this is the class involved https://github.com/nextflow-io/nextflow/blob/62e260437fa65c29de5a60d2491ad9aaf6f1886f/modules/nextflow/src/main/groovy/nextflow/config/Manifest.groovy#L1-L1

**Comment by jorgee** [comment]
When running `netxflow info <project_name>`, some of the manifest values are printed out (at least author and description). Which ones of the new values should be printed? I think maintainer, organization and license should be printed.

**Comment by pditommaso** [comment]
That's reasonable but let's keep outside the scope of this issue.

**Comment by ewels** [comment]
Rather than having both `authors` and `maintainers`, could have a single `contributors` with a key `type` that can be author / maintainer / etc.

**Comment by bentsherman** [comment]
BCO models authors and maintainers as a single list of "contributors" with a contribution type:
```json
        "contributors": [
            {
                "name": "Charles Hadley King", 
                "affiliation": "George Washington University", 
                "email": "hadley_king@gwu.edu",
                "contribution": ["createdBy", "curatedBy"],
                "orcid": "https://orcid.org/0000-0003-1409-4549"
            },

            {
                "name": "Eric Donaldson", 
                "affiliation": "FDA", 
                "email": "Eric.Donaldson@fda.hhs.gov",
                "contribution": ["authoredBy"]
            }
        ]
```
