### ISSUE TITLE
Wave containers using Singularity: error at pull phase

### ISSUE THREAD

**Issue by marcodelapierre** [nextflow-io/nextflow#4039]
I have been testing this with a simple Conda Wave container, which works with Docker.

With Singularity the following error arises:

```
$ nextflow run marcodelapierre/toy-cowsay-nf -profile condawavesing

[..]

Command error:
  FATAL:   could not open image wave.seqera.io/wt/02fbaad6eac2/wave/build:b358df7ad0c0ac9281750aa62548302f: failed to retrieve path for wave.seqera.io/wt/02fbaad6eac2/wave/build:b358df7ad0c0ac9281750aa62548302f: lstat wave.seqera.io: no such file or directory

Work dir:
  /home/ubuntu/toy-cowsay-nf/work/0e/03211a96089c9d5530329c74ec07db

```

Nextflow versions: any recent release (tried with May edge), and latest develop.

@pditommaso

**Comment by marcodelapierre** [comment]
Note for follow-up: see https://github.com/seqeralabs/wave/issues/252#issuecomment-1685731170

**Comment by marcodelapierre** [comment]
For follow-up, see these references:

https://github.com/seqeralabs/wave/issues/259
https://github.com/seqeralabs/wave/issues/252

**Comment by pditommaso** [comment]
This has been addressed by supporting Singularity native build in latest Nextflow and Wave version
