### ISSUE TITLE
Execution failure is not reported in the trace file when retry error strategy is used

### ISSUE THREAD

**Issue by msmootsgi** [nextflow-io/nextflow#404]
I just had a pipeline fail because `sbatch` failed to submit the job to the SLURM queue. However, my `nextflow.config` is configured to retry processes that fail:

```
process {
    errorStrategy = "retry"
    maxRetries = 2
    cache = "deep"
    maxErrors = 10
}
```

It would seem that the `sbatch` submission is handled outside of the normal error/retry handling. It would be great if we could handle `sbatch` submission errors just like normal process errors.

Here's some of the nextflow output:

```
Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: error: Batch job submission failed: I/O error writing script/environment to file
```

**Comment by pditommaso** [comment]
Could you include the `.nextflow.log` file ?

**Comment by msmootsgi** [comment]
I've attached the last 1000 lines, which should capture the whole error.
  Let me know if you need anything earlier.  [sbatch.nextflow.log.last.1000.txt](https://github.com/nextflow-io/nextflow/files/1146353/sbatch.nextflow.log.last.1000.txt)

I'm not sure what to make of the "No space left on device" exception.  The launch dir and work dir are both on an EFS partition and I'm not using `scratch`.

**Comment by pditommaso** [comment]
The retry logic is working as expected: 

```
Error submitting process 'hmmscan_gene3d_parse (924)' for execution -- Execution is retried (1)
:
Error submitting process 'hmmscan_gene3d_parse (924)' for execution -- Execution is retried (2)
:
```

**Comment by msmootsgi** [comment]
Hmmm.  The failure didn't make it into my trace file, which is what prompted the question.

**Comment by pditommaso** [comment]
Do you mean the file generate by the `-trace-file` option ?

**Comment by msmootsgi** [comment]
Yes

**Comment by pditommaso** [comment]
Now we have the bug, the task is re-retried but not reported in the trace :/

**Comment by msmootsgi** [comment]
Well, it helped uncover a bug in my pipeline too!  :)  Now I know that I need to use `tempDir` for the `collectFile` operator.  :)

**Comment by pditommaso** [comment]
great ! :)
