### ISSUE TITLE
missing comma causes confusing Script compilation error message

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#4040]
## Bug report 

If you forget the `,` comma in the `emit` directive in the Nextflow process output definition, you get an error such as 

```
ERROR ~ Script compilation error
- file : /home/steve/projects/nextflow-demos/emit/main.nf
- cause: Unexpected input: '{' @ line 3, column 16.
   process DO_FOO {
                  ^
```

Which is extremely unhelpful and confusing. Maybe we can please get a more descriptive error message?

### Steps to reproduce the problem

If you have a working Nextflow script like this;

- `main.nf`

```groovy
nextflow.enable.dsl=2

process DO_FOO {
    output:
    tuple val("hello"), path("foo.txt"), emit: foo_txt

    script:
    """
    touch foo.txt
    """
}

workflow {
    DO_FOO()
    DO_FOO.out.foo_txt.view()
}
```

And you are doing dev work, and you need to add an extra output item, and you try to add a item like this;

```groovy
nextflow.enable.dsl=2

process DO_FOO {
    output:
    tuple val("hello"), path("foo.txt"), val("goodbye") emit: foo_txt

    script:
    """
    touch foo.txt
    """
}

workflow {
    DO_FOO()
    DO_FOO.out.foo_txt.view()
}
```

wherein you mistakenly forget the trailing `,` between the final `output` item and the `emit` keyword, you are greeted with an error message like this;

```
$ nextflow run main.nf
N E X T F L O W  ~  version 23.04.2
Launching `main.nf` [clever_mirzakhani] DSL2 - revision: 38c0186eb2
ERROR ~ Script compilation error
- file : /home/steve/projects/nextflow-demos/emit/main.nf
- cause: Unexpected input: '{' @ line 3, column 16.
   process DO_FOO {
                  ^

1 error


 -- Check '.nextflow.log' file for details
```

This error message is extremely confusing. It suggests that something is wrong on line 3 (`process DO_FOO {`). 

However, the error is actually on line 5, here; 

```
tuple val("hello"), path("foo.txt"), val("goodbye") emit: foo_txt
```

the correct line should obviously be;

```
tuple val("hello"), path("foo.txt"), val("goodbye"), emit: foo_txt
```

(the added comma `,` before `emit`)

This is a very easy mistake to make, and after troubleshooting for some time, it ended up being a very difficult mistake to detect and fix. 

It would be fantastic if we could somehow get a more detailed error message in cases like these, so that we can at least be looking at the correct line to debug our syntax mistakes. 

### Environment 

* Nextflow version: 23.04.2
* Java version: 
```
openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

```

**Comment by bentsherman** [comment]
Closed by #4122
