### ISSUE TITLE
Nextflow history does not include apostrophes

### ISSUE THREAD

**Issue by evanfloden** [nextflow-io/nextflow#405]
When running:

`cat .nextflow/history`

the result does not have the apostrophes of the original command. 

E.g.

`2017-07-19 13:47:01    -    gigantic_heisenberg    -    ea91064aa7974d63ed94dc25e8a314c5    1000d667-ac2a-468d-a861-f8842224a84e    nextflow run kallisto.nf —reads=/data/*_read{1,2}.fastq.gz`

Due to the required glob expansion in `--reads`, this makes it not possible to copy/paste from history.

**Comment by pditommaso** [comment]
Included in version `18.12.0-edge`.
