### ISSUE TITLE
Improve AzFileSystemProvider.getContainerName error by including offending URI 

### ISSUE THREAD

**Issue by benbfly** [nextflow-io/nextflow#4072]
I had a typo in my azure pathname such that it started with "az:///container" rather than "az://container":

```
bampat = "az://" + "/container/*.bam"
newch = Channel.fromPath(bampat, checkIfExists: true)
```

This resulted in the following exception in the .nextflow.log file:
```
Jun-29 08:38:50.388 [PathVisitor-4] ERROR nextflow.Channel - Missing Azure blob storage container name
java.lang.IllegalArgumentException: Missing Azure blob storage container name
	at nextflow.cloud.azure.nio.AzFileSystemProvider.getContainerName(AzFileSystemProvider.groovy:108)
	at nextflow.cloud.azure.nio.AzFileSystemProvider.getFileSystem(AzFileSystemProvider.groovy:314)
	at nextflow.file.FileHelper.getOrCreateFileSystemFor(FileHelper.groovy:672)
	at nextflow.cloud.azure.file.AzPathFactory.getFileSystem(AzPathFactory.groovy:78)
```

It was very difficult to track down which "fromPath()" call was generating this error, since nextflow reported neither a line number in the .nf workflow file, nor the offending URI.  This error could be much more informative if it simply listed the offending URI.

https://github.com/nextflow-io/nextflow/blob/e80032969bb7266c2726468a96837c1de9a9191b/plugins/nf-azure/src/main/nextflow/cloud/azure/nio/AzFileSystemProvider.groovy#L107

**Comment by pditommaso** [comment]
Solved by 0f4d8867. Thanks for reporting

**Comment by benbfly** [comment]
I see that you checked for the one special case that was causing my problem, but my point was more that the error messages thrown in `AzFileSystemProvider.getContainerName()` are not very useful because they do not include the offending URI in the error message.  There are three different error throws in this function, and none of them include the URI in the error message:
throw new IllegalArgumentException("Missing URI scheme")
throw new IllegalArgumentException("Mismatch provider URI scheme: $scheme")
throw new IllegalArgumentException("Missing Azure blob storage container name")

How is one supposed to debug these errors when they occur, since they don't tell you which file/URI is causing the problem.  My point was to include the URI in these throw messages.

Am I not looking at this in the right way?

**Comment by pditommaso** [comment]
Good point feel free to submit a PR to improve the error messages
