### ISSUE TITLE
iterating through a file in a Nextflow process

### ISSUE THREAD

**Issue by AzizHN** [nextflow-io/nextflow#4087]
I am trying to create a process in nextflow where it takes 2 inputs, the krakenfile which will be used directly, and the fungalname which contain multiple lines, every line contain a name of a specie.

I want to do an iteration inside the fungalname file, take it line by line, and for every line/specie I will look for all lines in the krakenfile that contain that name in their 3rd column.

For example If my fungalname contain this:
```
Aspergillus fumigatus
Candida albicans

```
And the krakenfile contain

```
xxxx  548   Aspergillus fumigatus 
zzzz  566   Candida albicans 
aaaa  598   Aspergillus fumigatus
kkk   888   Candida albicans
```
My outputs should be 2 files,ASpergillus_fumigatus_lines.txt and Candida_albicans_lines.txt, every one of them contain 2 lines (as the ewample above)

The problem is that my outputs files always are empty, though I am sure of the format, the localisation of my input files, I think it's a matter of process, can Anyone please help m, this is my code :
```groovy

params.fungaalnames="/home/aziz/pipeline/results/extraction/fungal_species.txt"
params.krakeenfile="/home/aziz/pipeline/results/classification_before_filtration/output.kraken"

fungalnames = file(params.fungaalnames)
krakenfile = file(params.krakeenfile)

process fungal_reads_extraction {
     
     input:
     file fungalnames
     file krakenfile

     output:
     path "*" , emit: reads_extracted_out
     
     script:
     """
     while IFS= read -r species_name; do
       awk -F'\t' '\$3 ~ "'\$species_name'" {print}' $krakenfile > "\${species_name}_lines.txt"
     done < $fungalnames
     """
}

workflow {
  fungalnames_ch = Channel.fromPath(params.fungaalnames)
  krakenfile_ch = Channel.fromPath(params.krakeenfile)
  fungal_reads_extraction(fungalnames_ch, krakenfile_ch) | view
}
```

**Comment by bentsherman** [comment]
Can you check the `.nextflow.log` to see if there were any errors?

Also, have you tested your bash code separately from Nextflow to make sure it works by itself?

Not sure if it's related, but I think these two lines are not needed:
```groovy
fungalnames = file(params.fungaalnames)
krakenfile = file(params.krakeenfile)
```

**Comment by AzizHN** [comment]
Thank you @bentsherman for your reply !
Yes I tested teh script, it works very well on the command line ... I made some changes on it (but it still works)
the new script is (it works very well also on the command line): 
`while IFS= read -r species_name; do   awk -F'\t' -v specie="$species_name" '$3 ~ specie {print}' "$krakenfile" > "${species_name}_lines.txt"; done < "$fungalnames"`

I changed it in nextflow, just adding the \ symbol before $3 : 
`while IFS= read -r species_name; do   awk -F'\t' -v specie="$species_name" '\$3 ~ specie {print}' "$krakenfile" > "${species_name}_lines.txt"; done < "$fungalnames"`

Now it's giving me a null file, I think it's a matter of quotes, But I am not able to resolve it until now !

**Comment by bentsherman** [comment]
I think you also need to escape `\$species_name` since it is a bash variable created by the while loop.

I would change your `file` inputs to `path`, although I don't think it will fix this issue.
