### ISSUE TITLE
docker.fixOwnership recurses through the entire working directory

### ISSUE THREAD

**Issue by briankegerreis** [nextflow-io/nextflow#4089]
## Bug report 

The docker.fixOwnership option recurses through the entire working directory, not just the working directory for the current process. This causes performance degradation in large / busy clusters.

### Expected behavior and actual behavior

Expected: docker.fixOwnership fixes ownership of files generated by the current process
Actual: docker.fixOwnership fixes ownership of every file in Nextflow's working directory

### Steps to reproduce the problem

N/A

### Program output 

Found this command running in the docker container for several minutes after work should have been complete:
`chown -fR --from root <USER>:500 /data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/<FILES> /data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/. /data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/.. /data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/.command.begin /data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/.command.err /data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/.command.log /data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/.command.out /data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/.command.run /data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/.command.sh /data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/.command.trace`

### Environment 

* Nextflow version: 21.04
* Java version: ?
* Operating system: Linux
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by bentsherman** [comment]
Here is the relevant source code:

https://github.com/nextflow-io/nextflow/blob/84f7a61a1f5c763c86cd09fa8f9c4d1a3eb0db99/modules/nextflow/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy#L322

So it's happening because the glob `${workDir}/{*,.*}` also captures `..` 🤦

**Comment by bentsherman** [comment]
I can change the glob to `${workDir}/{*,.[^.]*}` so that it doesn't capture `..` or `.`, but I think we want to fix the ownership of those directories too right? So we really want to fix the parent directory (not recursively), the work directory (recursively), and the dotfiles.

That would require two commands:
```bash
chown -f --from root \$NXF_OWNER ${workDir}/{..,.}
chown -fR --from root \$NXF_OWNER ${workDir}/{*,.[^.]*}

**Comment by pditommaso** [comment]
Are you suggesting it also affects the parent directory? I don't believe so

**Comment by bentsherman** [comment]
It does, see the original comment

**Comment by bentsherman** [comment]
```
/data/sandbox/scratch/nextflow/work/93/291a94dd9dbd3d54817199b0a1fc0e/.. 
```

**Comment by pditommaso** [comment]
I see that, but I don't think it follows it to the parent.

**Comment by bentsherman** [comment]
I don't understand what you mean, that is the parent

**Comment by pditommaso** [comment]
I mean, does it also change all files in the path `/data/sandbox/scratch/nextflow/work/93/` and `/data/sandbox/scratch/nextflow/work/` and `/data/sandbox/scratch/nextflow/work/` .. etc

**Comment by bentsherman** [comment]
No. But even just capturing these bucket directories could cause a slowdown if you have many tasks in each bucket.

@briankegerreis can you inspect the contents of `work/93/291a94dd9dbd3d54817199b0a1fc0e/..`? Are there a lot of files in that directory? Also in the task directory itself, are there directories in your `<FILES>` with lots of nested files?

**Comment by pditommaso** [comment]
Above all, why you are using `fixOwnership`? what's your environment?

**Comment by bentsherman** [comment]
Does it really matter? Either way, the `chmod` command shouldn't be capturing anything outside of the task directory itself

**Comment by pditommaso** [comment]
This is an old trick required when using docker over a shared file system. We should even remove it because there are better solutions

**Comment by briankegerreis** [comment]
> This is an old trick required when using docker over a shared file system. We should even remove it because there are better solutions

docker on shared NFS is the context I was using it in. Fortunately was running docker in a way that made that option redundant, so I could turn it off without any ill effects

**Comment by pditommaso** [comment]
You may also want to consider using Singularity or Podman, which handles permission much better

**Comment by pditommaso** [comment]
@bentsherman think you are right about the chwon parent navigation! I don't think it can be ignored the ownership for `.` and `..` pseudo-files therefore it should be fine the second command.

**Comment by pditommaso** [comment]
The problem with `.[^.]*` is that it does not match file names *starting* with `..` wg. `..foo`

**Comment by pditommaso** [comment]
CHatGPT found the solution! f2a2ea35

**Comment by bentsherman** [comment]
Nice 😎
