### ISSUE TITLE
Name or service not known error when running on EC2

### ISSUE THREAD

**Issue by mhalagan-nmdp** [nextflow-io/nextflow#409]
Running this command on the master node
```
./nextflow run nmdp-bioinformatics/flow-Optitype \
	--with-docker nmdpbioinformatics/flow-OptiType \
	--outfile hli-optitype.csv \
	--bamdir s3://bucket/s3/data \
	--datatype dna
```

Returns the following errors:
```
N E X T F L O W  ~  version 0.25.3-SNAPSHOT
Pulling nmdp-bioinformatics/flow-Optitype ...
 downloaded from https://github.com/nmdp-bioinformatics/flow-OptiType.git
Launching `nmdp-bioinformatics/flow-Optitype` [sleepy_jang] - revision: 6fcb330fe1 [master]

---------------------------------------------------------------
NEXTFLOW OPTITYPE
---------------------------------------------------------------
Input BAM folder   (--bamdir)          : s3://bucket/s3/data
Sequence data type (--datatype)        : dna
Output file name   (--outfile)         : hli-optitype.csv


[warm up] executor > ignite
ERROR ~ ip-xx-xxx-xx-xxx: ip-xx-xxx-xx-xxx: Name or service not known

 -- Check script 'main.nf' at line: 68 or see '.nextflow.log' file for more details
 ```

**Comment by mhalagan-nmdp** [comment]
[nextflow.txt](https://github.com/nextflow-io/nextflow/files/1174153/nextflow.txt)

**Comment by pditommaso** [comment]
It seems it't not able to resolve the domain name 

```
Caused by: java.net.UnknownHostException: ip-10-223-13-100: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:922)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1316)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1492)
```

**Comment by mhalagan-nmdp** [comment]
I'm running the cluster from within a VPC and I provided the nextflow.config with a subnet and security group ID.

**Comment by pditommaso** [comment]
yes, it should be able to resolve the IP. I'm going a test.

**Comment by mhalagan-nmdp** [comment]
I'm using an ubuntu AMI that I created.

**Comment by pditommaso** [comment]
I think this is more a AWS network config problem. Try to have a look [here](https://stackoverflow.com/questions/45157287/ec2-pyspark-java-net-unknownhostexception-name-or-service-not-known)

**Comment by mhalagan-nmdp** [comment]
That makes sense. I'll try that and let you know if it works. Thanks!

**Comment by mhalagan-nmdp** [comment]
It looks like it's failing because it's on an ubuntu AMI. On the ubuntu AMI you can't ping the `hostname` without adding **.ec2.internal** at the end. It would probably work better if it got the IP address instead of the DNS.

**Comment by pditommaso** [comment]
It looks weird, I've tested this with Ubuntu in the past. Also because what it's failing a plain Java API ie. 

```
InetAddress.getLocalHost().getHostAddress()
```

It looks very strange that couldn't be run on Ubuntu.

**Comment by mhalagan-nmdp** [comment]
Actually nevermind, I don't think it's an issue with using Ubuntu. It was an issue with the VPC I was using. The AWS default VPC resolves an instance DNS to _ip-address_.ec2.internal, but I was using one that was modified to return something different at the end. I think it'd be a good idea to use the IP address instead of the DNS, because that's more reliable.

**Comment by pditommaso** [comment]
The API is fetching the IP address, but for some reason it tries to resolve the host name. This means you have solved the problem?

**Comment by pditommaso** [comment]
I assume this is solved. Feel free to comment or re-open if necessary

**Comment by mhalagan-nmdp** [comment]
Yeah, this has been solved. Sorry, for the delayed response.

**Comment by pditommaso** [comment]
Could you please provide a short description of the solution that could be useful for other users?

**Comment by mhalagan-nmdp** [comment]
Go the the AWS [VPC](http://docs.aws.amazon.com/AmazonVPC/latest/GettingStartedGuide/ExerciseOverview.html) page and click on ["DCHP Option Sets"](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html). Make sure the one you are using is being resolved to the default, which is "ec2-internal".
