### ISSUE TITLE
Add option to turn off rendering of single-line JSON of trace report in log files

### ISSUE THREAD

**Issue by jfy133** [nextflow-io/nextflow#4093]
## New feature

It would be to have the option to turn off rendering of the entire trace/execution report as a single-line JSON at the end of `.nextflow.log` runs.

## Usage scenario 

In the cases of particularly large or complex pipelines, this results in a very large  log files and makes them difficult to parse (e.g. grepping for single process name when trying to debug.).

Having the ability to turn off the printing of the JSON to the `.nextflow.log` file will be beneficial for reading logs, also particularly given the information can be saved as an explicit file (e.g. HTML).

For example, trying to grep for the process 'BOWTIE2_PHIX_REMOVAL_BUILD' in the attached log file, still requireslots of scrolling (or grep expression specifications) to get to actually useful information about whether the process was executed correctly. etc.

[nextflow.txt](https://github.com/nextflow-io/nextflow/files/12037009/nextflow.txt)

## Suggest implementation 

I believe the 'offending' section is here:

https://github.com/nextflow-io/nextflow/blob/84f7a61a1f5c763c86cd09fa8f9c4d1a3eb0db99/modules/nextflow/src/main/groovy/nextflow/trace/ReportObserver.groovy#L239-L243

It would be nice to have an option (e.g. in the corresponding configuration scope block) so that the `log.debug` only is used (or just the ${result} included) when requested.

For example 

```groovy
    protected String renderSummaryJson(printToLog) {
        final result = aggregator.renderSummaryJson()

       if ( printToLog ) {
          log.debug "Execution report summary data:\n  ${result}"
       }
       
        return result
    }
```

I would try this myself as it seems like a very small change, but when I looked into it I found I didn't have enough experience to parse through all the layers of functions that end up calling that function, nor how to specify a configuration variable to control for this.

**Comment by bentsherman** [comment]
Maybe we should just change it to `log.trace` instead of `log.debug`

**Comment by jfy133** [comment]
Just to confirm - by putting in log.trace, would it still avoid going in the `.nextflow.log`, even if trace is activated (I'm not familiar with the different `log.*` types)

I ask as nf-core pipelines (where I identified this) turn on 'everything' but to dump to html files and the like (e.g. [here](https://github.com/nf-core/rnaseq/blob/3bec2331cac2b5ff88a1dc71a21fab6529b57a0f/nextflow.config#L281C5-L281C5))

**Comment by bentsherman** [comment]
With `log.trace` it would only be logged if nextflow was launched with `-trace nextflow`. That log level already dumps all sorts of things so adding this report data would be no big deal

**Comment by jfy133** [comment]
Mm, I'm not sure then that would help in my particular case then (if I'm understanding correctly).

I can't find `-trace nextflow` in the latest nor edge documentation, so assuming you mean `-with-trace`?

If so, in nf-core pipelines we still want the trace report, but saved to a [separate file](https://github.com/nf-core/rnaseq/blob/3bec2331cac2b5ff88a1dc71a21fab6529b57a0f/nextflow.config#L289-L292).

If by moving this to `log.trace` then the JSON line is still just printed to the `.nextflow.log` file (assuming that's what you mean by 'logged'?) when `trace = true` in a configuration (or `-with-trace`) - If I'm understanding correctly? This then still doesn't doesn't get around my problem.

Ultimately what I'm looking for is that JSON string to ever not be present in `.nextflow.log` (either by default, or opt-out). I would argue it's redundant to printing within the main `.nextflow.log` given that when you supply `-with-trace` -r `trace = true` then it should go into the separate `trace-<timestamp>.txt` file anyway?

**Comment by bentsherman** [comment]
Trace logging and the trace report are different things. And `-trace` just isn't documented. 😄 So it should work for you.

**Comment by pditommaso** [comment]
In any case it can be just dropped. Not even sure why it's dumped in the log.

**Comment by jfy133** [comment]
Thank you both!!!
