### ISSUE TITLE
Add seed parameter to RandomSample

### ISSUE THREAD

**Issue by baffelli** [nextflow-io/nextflow#410]
I know that it is an oxymoron, but I believe that the ```RandomSample``` operator should have a ```seed``` parameter to set the initial seed for the RNG used for reservoir sampling, so that pipelines using that operator can be sucessfully resumed, because the operator would always return the same _random_ sequence of values.

**Comment by pditommaso** [comment]
I agree. This is a great opportunity for your first pull request! :D

**Comment by baffelli** [comment]
Fair point! I may try this afternoon ;)
