### ISSUE TITLE
Document `watchPath` compatibility with operators

### ISSUE THREAD

**Issue by supermaxiste** [nextflow-io/nextflow#4103]
Hello,

I've been using Nextflow quite a lot recently to automate a pipeline using `watchPath`. It's a very powerful channel factory and I'm extremely grateful that Nextflow supports it 😄 

After several months of use, I realized that many operators in the docs are not compatible with `watchPath` given its open nature. Some personal examples include `join` and `collect`. 

I thought it would be great to explicitly mention operators that are incompatible with `watchPath` in its [docs page](https://www.nextflow.io/docs/latest/channel.html#watchpath).

Have a great day,
Stefan

P.s. here I'm referring to using `watchPath` without any `until` option

**Comment by supermaxiste** [comment]
Hello @bentsherman and thank you for the quick reply!

I guess that using `watchPath` without closing it is not the most popular use case, but to fully automate Nextflow without using other tools it can be quite powerful and it could be useful for other users.

I guess the information would be too specific for the Nextflow docs? One simple option would be to extend the warning in [`watchPath` section](https://www.nextflow.io/docs/latest/channel.html#watchpath).

For other resources I'm aware of [Nextflow patterns](https://nextflow-io.github.io/patterns/) but I'm not sure it fits the style since there needs to be a code example. 

If either of the options above seem reasonable or you could think of other docs/channels related to Nextflow, I'd love to contribute. If the information is too specific, feel free to close the issue.

**Comment by bentsherman** [comment]
I thought about extending the warning to mention blocking operators specifically, but since watchPath will run forever regardless of the downstream operators that consume it, the general advice about using `take` or `until` is sufficient IMO. In any case, thank you for raising the issue.
