### ISSUE TITLE
Invalidate process cache when a referenced external script is modified

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#413]
Sometimes it happens that there is an "aggressive" caching of processes. I usually fix by adding some "echo XXX;" to the command line. But I think it would be nice to have some thing like "-force $PROCESSNAME"

**Comment by baffelli** [comment]
I have the same problem when using binary scripts that i keep in ```./src/bin```. If I change the implementation, the cached result is used because the command string does not change although the command implementation does.

**Comment by pditommaso** [comment]
Yes, the cache invalidation cannot recognise changes to in external scripts. Not sure, this is the case reported by @lucacozzuto

**Comment by baffelli** [comment]
Understandibly. I guess that a possible hack would be to include the script in a channel ;)

**Comment by lucacozzuto** [comment]
Yes. This is exactly the case.

Il 07 ago 2017 14:32, "Paolo Di Tommaso" <notifications@github.com> ha
scritto:

**Comment by pditommaso** [comment]
It's possible to improve to track the changes of any user scripts in the `PROJECT/bin/` folder. 

The process command should be parsed looking for commands that match such scripts and implicitly added as regular inputs. In this way the process cache would be automatically invalidated when an external script is modified. 

Obviously it won't work for tools/scripts outside of that folder or indirect dependencies, but I found this solution fair enough.

**Comment by baffelli** [comment]
That sounds like an excellent plan!

**Comment by lucacozzuto** [comment]
I agree. Very good solution!

Luca

Il 07 ago 2017 17:21, "Simone Baffelli" <notifications@github.com> ha
scritto:

**Comment by pditommaso** [comment]
Now it's only missing a pull request implementing it :)

**Comment by baffelli** [comment]
Well..my current schedule does not leave a lot of time to try advanced groovy magic. But who knows, I may try :grin:

**Comment by baffelli** [comment]
Just to know..where does nextflow compute the hash?

**Comment by pditommaso** [comment]
No hurry, I won't be able to touch this before mid-sept. 

The relevant code is [createTaskHashKey](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L1856-L1878). 

In principle should be so difficult
1) at startup list all files in the `bin` folder
2) create a map holding the hash for each file 
3) for each process parse the command script and list of tokens that match a script in the `bin/` folder 
4) append a hash in the list of items created by `createTaskHashKey` for each script found.
