### ISSUE TITLE
Fetch a supplied property from a config file via the Nextflow CLI

### ISSUE THREAD

**Issue by afishman** [nextflow-io/nextflow#4138]
## New feature

Fetch a named property from a resolved Nextflow config file via the Nextflow CLI. The feature would make it easier for users to utilise config files outside of a nextflow script. 

Note that I originally [suggested this feature on Slack](https://nextflow.slack.com/archives/C02T98A23U7/p1690796177956779), and @ewels recommended I raise a feature request here. 

## Usage scenario 

Retrieving config file properties outside of nextflow scripts, particularly in an automated setting (eg in pre/post-processing routines and testing). For example, our codebase has a number of dev/testing tools that share common parameters with our pipeline, and we would like to centralise these configurations with the nextflow config. 

It would also make it easy for users to quickly lookup values as they are resolved in the pipeline. This is especially useful in complex configs. 

## Suggest implementation 

Modify `CmdConfig.groovy` to accept a new `-property <name>` optional. The `<name>` can reference nested properties using dot syntax:
```console
$ nextflow config -property aws.region
eu-west-1
```

If the property does not exist, an error message with non-zero exit code should be returned. For example:
```console
$ nextflow config -property does.not.exist
Error: does.not.exist does not exist in the config file. 
$ echo $?
2 
```

Evaluation of the property should adhere to the `-profile` optional if defined. For example:
```console
$ nextflow config -property process.executor -profile standard
local
$ nextflow config -property process.executor -profile cluster
sge
```

**Comment by bentsherman** [comment]
Hi Aaron, this looks like a great idea. Would you like to draft a PR? You should be able to add this option to `CmdConfig` and use `config.navigate(property)` to access the property.

**Comment by bentsherman** [comment]
Phil mentioned that I'm working on CLI v2, but don't worry about that. We can add this to the current CLI and then I will update the CLI v2 accordingly.

**Comment by afishman** [comment]
Sounds good, thanks @bentsherman , will give it a go.

**Comment by afishman** [comment]
Hey @bentsherman , where is the navigate method defined? I don't see it on [ConfigObject](https://docs.groovy-lang.org/latest/html/api/groovy/util/ConfigObject.html)

Also, where can I push my branch? Should I prepare my PR via a fork?

**Comment by afishman** [comment]
Trying to figure out how to handle null values. My current thinking is to print null if the user set a property to null, and throw an error if the property does not exist. However `config.navigate` returns null in both cases. Wondering if there is a containsProperty method or similar I can leverage for this

**Comment by afishman** [comment]
ahh actually `config.flatten().containsKey()` works =]

**Comment by bentsherman** [comment]
The `navigate` method is actually defined in `Bolts`, which is an extension module. So this method can be used with any map.

You can push your branch to a fork and make a PR from there.

**Comment by pditommaso** [comment]
but I think @afishman is right, the navigate does not allow you to distinguish between absent setting or the setting having `null` value

**Comment by afishman** [comment]
@bentsherman Just raised a PR for this.

@pditommaso The `flatten()` method allowed me to distinguish between null and missing values. Not sure if there is a better way

**Comment by pditommaso** [comment]
it should be OK
