### ISSUE TITLE
NF fails to pull images hosted in the Singularity Hub

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#414]
This is due to a Singularity bug. See https://github.com/singularityware/singularity/issues/847.

**Comment by gmkurtzer** [comment]
Heya, is this issue fixed now? Thanks!

**Comment by pditommaso** [comment]
I've fixed this on our side as well by using the `SINGULARITY_PULLFOLDER` variable, tho I've not released yet.

**Comment by pditommaso** [comment]
Fixed with release `0.25.5`
