### ISSUE TITLE
failOnMismatch without remainder cannot be set to false in strict mode

### ISSUE THREAD

**Issue by SamStudio8** [nextflow-io/nextflow#4148]
The documentation in edge for Nextflow's strict mode states:

> When using the join operator, the failOnMismatch option is true by default (unless remainder is also true)

This would imply to me that `failOnMismatch` could still be set to `false` by a developer regardless of strict mode, but that is not the case [as the `failOnMismatch` setting is overridden to `true` when in strict mode (if remainder is false)](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/extension/JoinOp.groovy#L67).

```
this.failOnMismatch = params?.failOnMismatch || (!this.remainder && NF.isStrictMode())
```

It is unclear to me whether this is a bug or a design decision? On the one hand, if I have explicitly allowed mismatches with `failOnMismatch: false` I would not expect strict mode to override me and raise an error anyway; but perhaps this was a decision to make a developer explicitly handle mismatches (eg. by keeping a remainder and discarding entries with `null`)?

If the former, in the case of strict mode, Nextflow should not set `failOnMismatch` to `true` if a value of `false` has been explicitly provided by the developer. If the latter, perhaps Nextflow should raise an error when trying to set `failOnMismatch: false` when using strict mode ([similar to what is done when trying to set remainder && failOnMismatch](https://github.com/nextflow-io/nextflow/blob/19a72c402495e72df0140c6af05d299330fa5ba9/modules/nextflow/src/main/groovy/nextflow/extension/JoinOp.groovy#L70)); and the documentation for strict mode should perhaps read:

> When using the join operator, a mismatch is not allowed unless remainder is also true

**Comment by SamStudio8** [comment]
I haven't tested, but presumably `failOnDuplicate` works the same way:
```
this.failOnDuplicate = params?.failOnDuplicate || NF.isStrictMode()
```

**Comment by bentsherman** [comment]
You are right in both cases, that is a more precise description of what strict mode does. I will draft a PR.
