### ISSUE TITLE
Task failure due to empty `.command.run` when using SLURM scheduler

### ISSUE THREAD

**Issue by Mathias-Boulanger** [nextflow-io/nextflow#4154]
Hi Nextflow team,

## Bug report 
I got time to time (totally random) this error when using Nextflow 23.04.1 on SLURM scheduler:
```
Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: error: Batch script is empty!
```

### Expected behavior and actual behavior

When I go to the related working directory, the `.command.run` isn’t empty.
Furthermore, If I re-launch the pipeline or submit the `.command.run` manually, the job is ran successfully...

### Steps to reproduce the problem

It as been a random behavior so far, or I didn't identify a point that make it reproducible.

### Environment 

* Nextflow version: `Nextflow 23.04.1 build 5866`
* Java version: `openjdk 20-internal 2023-03-21`
* Operating system: `CentOS8 (el8, RedHat 8.5)`
* Bash version: `GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu)`

### Additional context

I tried to use the directive `beforeScript 'sleep 10'` but I don't know if this command is run before or after the `sbatch` command.
It could be nice to fsync() the `.command.run` after written and before pass it into `sbatch` command...

Scheduler parameters:
```
executor {
     $slurm {
        queueSize = 500
        submitRateLimit = "10/1sec"
        pollInterval = '10sec'
        exitReadTimeout = "5 min"
    }
    $local {
        cpus = 12
        memory = '16 GB'
    }
}
```
general process parameters:
```
process {
     executor = 'slurm'
     clusterOptions = '--overcommit'
     cache = 'lenient'
     errorStrategy = 'retry'
     afterScript = 'sleep 30'
}
```

Thank you for your help!

**Comment by bentsherman** [comment]
I'm guessing the `.command.run` isn't ready by the time the job is submitted.

I would look into the `executor.retry.*` settings, which pertain specifically to job submissions. By default, it only retries errors with "Socket timed out", but you can change it to match your error or `*` to retry any error. The initial delay is 500ms and I think it doubles after each attempt.

**Comment by bentsherman** [comment]
Also, the beforeScript does indeed run in the job script, so it won't help here.

**Comment by Mathias-Boulanger** [comment]
> I would look into the `executor.retry.*` settings, which pertain specifically to job submissions. By default, it only retries errors with "Socket timed out", but you can change it to match your error or `*` to retry any error. The initial delay is 500ms and I think it doubles after each attempt.

This is exactly the executor parameter that will fix the problem! 
Thank you I wasn't aware of this one (the last one on the doc.. I should finish to read the page before to jump into the code ;) )
