### ISSUE TITLE
staged remote files from github not cacheing correctly

### ISSUE THREAD

**Issue by anoronh4** [nextflow-io/nextflow#4168]
### Expected behavior and actual behavior

Every time i resumed my pipeline the files stored with git lfs the file would be downloaded again and the process would be repeated. my work directory has dozens of the same file copied:

```
find work/stage-8fb899c3-7861-4b25-8a3f-0447d2108878/ -type f | xargs -n 1 basename | sort | uniq -c
     25 blocklist_breakpoints.bedpe
     27 gene_info_20230714.txt
      1 Homo_sapiens.GRCh37.75.cdna.all.fa.gz
     27 v75_gene.bed
```
( the fa.gz is stored at a remote ftp site, the others are stored with a git lfs tracking in my personal github account)

### Steps to reproduce the problem

Unfortunately nextflow downloaded my references so many times that i exhausted my bandwidth and no longer have ready access to any git lfs files. so i'm not sure if i can perfectly reproduce the problem at the moment, and this is my best attempt until my quota resets! 

```
uri_link = params.uri_link
process A {
input:
path(a)
output:
env(file_len)
script:
"""
file_len=\$(cat $a | wc -l)
"""
}
workflow {
A(uri_link).view()
}
```
i tried this with non-lfs git files and there was no problem. 

### Program output 

execution is not failing. I don't seem to get any helpful log info just that the files are being copied:
```
Aug-08 12:46:24.834 [FileTransfer-2] DEBUG nextflow.file.FilePorter - Copying foreign file https://media.githubusercontent.com/media/anoronh4/forte-references/main/GRCh37/v75_gene.bed to work dir: /juno/work/ccs/noronhaa/tools/test_nf-core/forte_change_metafusion_ref/moretesting/work/stage-8fb899c3-7861-4b25-8a3f-0447d2108878/aa/b75896d332fbf1896dca8195c39f58/v75_gene.bed
Aug-08 12:46:24.835 [FileTransfer-3] DEBUG nextflow.file.FilePorter - Copying foreign file https://media.githubusercontent.com/media/anoronh4/forte-references/main/GRCh37/gene_info_20230714.txt to work dir: /juno/work/ccs/noronhaa/tools/test_nf-core/forte_change_metafusion_ref/moretesting/work/stage-8fb899c3-7861-4b25-8a3f-0447d2108878/c3/f50080de047c0ce55ebdb7f54306cd/gene_info_20230714.txt
Aug-08 12:46:24.837 [FileTransfer-4] DEBUG nextflow.file.FilePorter - Copying foreign file https://media.githubusercontent.com/media/anoronh4/forte-references/main/GRCh37/blocklist_breakpoints.bedpe to work dir: /juno/work/ccs/noronhaa/tools/test_nf-core/forte_change_metafusion_ref/moretesting/work/stage-8fb899c3-7861-4b25-8a3f-0447d2108878/13/ca9cbea5c5b0b10eb2bdc7a99530c2/blocklist_breakpoints.bedpe
```

### Environment 

* Nextflow version: 23.04.2
* Java version: 11
* Operating system: CentOS Linux
* Bash version: GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by bentsherman** [comment]
That's strange, it looks like LFS files are just HTTP paths, so should work the same.

If the file is already is present, Nextflow should skip the download, and you should see `Local cache found for foreign file...` in your log file. The local path looks like this:

```groovy
"${workDir}/stage-${sessionId}/${taskHash}/${fileName}"
```

So if we take this log message for example:
```
Aug-08 12:46:24.834 [FileTransfer-2] DEBUG nextflow.file.FilePorter - Copying foreign file https://media.githubusercontent.com/media/anoronh4/forte-references/main/GRCh37/v75_gene.bed to work dir: /juno/work/ccs/noronhaa/tools/test_nf-core/forte_change_metafusion_ref/moretesting/work/stage-8fb899c3-7861-4b25-8a3f-0447d2108878/aa/b75896d332fbf1896dca8195c39f58/v75_gene.bed
```

That means one of:
- the work dir changed
- the session id changed
- the task hash changed
- the file was deleted

Can you compare this file for your initial run and resumed run to see if it changed?

**Comment by anoronh4** [comment]
thanks for your response. i've had some difficulty figuring out whether the file had changed or not, however, when i switched to a different github url that is not lfs tracked i was actually able to easily create a minimal working example.
```
uri = "https://github.com/anoronh4/forte-references/blob/main/GRCh37_test/blocklist_breakpoints.bedpe"

process A {
debug true
input:
val(x)
path(uri)
script:
"""
echo $x
cat $uri | wc -l 
"""
}

workflow { 
ch = Channel.from(1,2)
A(ch,uri)
}
```

if you run this with the `-resume` option twice, do you see the same issue? just `nextflow run test.nf -resume` is sufficient, where the nextflow version is 23.04.2

so it turns out the issue i'm seeing likely has nothing to do with git lfs, although this new link is also a github link.

**Comment by bentsherman** [comment]
I was not able to reproduce the issue with 23.04.2, the file was cached every time.

Can you share the `.nextflow.log` files for (1) an initial run and (2) a resumed run that didn't cache the file? Then I can compare the logs and see what changed.
