### ISSUE TITLE
Virtual threads setting doesn't work in dockerized Nextflow

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#4175]
## Bug report 

When trying to run the Nextflow docker container with virtual threads enabled, you get an error that `--enable-preview` must be applied.

This happens because the `nextflow` script uses the classpath file at `/.nextflow/launch-classpath` when in a container, regardless of whether virtual threads is enabled.

So virtual threads must be enabled at build time, or the classpath has to be deleted before launching Nextflow, to force it to create a new classpath file with the needed options for virtual threads.

```bash
rm -f /.nextflow/launch-classpath
```

**Comment by pditommaso** [comment]
Maybe I'm missing something, but it should happen because the launch classpath is cache by aa unique hash computed here 

https://github.com/nextflow-io/nextflow/blob/3051cd13da0298eaca142509ac05c7080a1c4328/nextflow#L383-L383

**Comment by bentsherman** [comment]
True, but if you look a few lines down, you'll see that this hash is ignored if the dockerized classpath file is already present.

Seems like the dockerized classpath file should also be hashed so that it can be overridden if needed.

**Comment by pditommaso** [comment]
Oops, understand. We should remove that option, not sure it still make sense
