### ISSUE TITLE
Programmatically answer yes to confirm cluster configuration

### ISSUE THREAD

**Issue by mhalagan-nmdp** [nextflow-io/nextflow#418]
``
Please confirm you really want to launch the cluster with above configuration [y/n]
``

Allow a nextflow cloud cluster to be created without having to confirm the cluster configuration.

**Comment by pditommaso** [comment]
Fixed https://github.com/nextflow-io/nextflow/commit/da33d5df5b6fd496e1c8fbe527967ab43d67b2e7

**Comment by pditommaso** [comment]
Released with `0.25.5
