### ISSUE TITLE
maxSpotAttempts is being ignored

### ISSUE THREAD

**Issue by rulixxx** [nextflow-io/nextflow#4184]
## Bug report 

maxSpotAttempts directive is ignored

### Expected behavior and actual behavior

In my config file I've specified 

process {
    executor = 'awsbatch'
    errorStrategy = 'retry'
    maxRetries = 3  
    maxSpotAttempts = 4
}

however when I check the batch status for some of my failed jobs on spot instances I can see that they are being retried 5 times (which is the default)

### Environment 

* Nextflow version: 23.04.2
* Java version: 11.0.19
* Operating system: Linux
* Bash version: 5.1.16

![Screenshot 2023-08-14 at 12 18 00](https://github.com/nextflow-io/nextflow/assets/16779784/93fa80e9-fa7f-48f4-a123-e9175bff472d)

**Comment by bentsherman** [comment]
maxSpotAttempts is an aws batch config option, not a process directive:
```groovy
aws.batch.maxSpotAttempts = 4
```
