### ISSUE TITLE
Resume does not work with "exec:" (i.e. native groovy processes)

### ISSUE THREAD

**Issue by alexandrebouchard** [nextflow-io/nextflow#4220]
### Expected behavior and actual behavior

`-resume` should work with `exec: ...` but it does not.

### Steps to reproduce the problem

Minimal.nf:

```
process testExec {
    exec:
        println()
}

process testStd {
    """
    """
}

workflow {
    testExec()
    testStd()
}
```

### Program output 

```
> ./nextflow run minimal.nf -resume
N E X T F L O W  ~  version 23.04.3
Launching `minimal.nf` [exotic_mercator] DSL2 - revision: 1be12e5277
executor >  local (2)
[ae/5ca330] process > testExec [100%] 1 of 1 ✔
[d9/387d71] process > testStd  [100%] 1 of 1 ✔


> ./nextflow run minimal.nf -resume
N E X T F L O W  ~  version 23.04.3
Launching `minimal.nf` [jolly_easley] DSL2 - revision: 1be12e5277
executor >  local (1)
[41/bb36e7] process > testExec [100%] 1 of 1 ✔
[d9/387d71] process > testStd  [100%] 1 of 1, cached: 1 ✔
```

Note that the process based on `exec:` did not resume.

### Environment 

* Nextflow version: 23.04.3
* Java version: openjdk version "17.0.8" 2023-07-18
* Operating system: macOS
* Bash version: (use the command zsh 5.9 (x86_64-apple-darwin22.0))

### Additional comments

This is not just a corner case, it seems native groovy blocks never get cached. 

Thank you!

**Comment by bentsherman** [comment]
I was able to replicate the issue on 23.04.3, but not on 23.09.1-edge. Closing, feel free to re-open if you encounter this issue with the latest version.

**Comment by bentsherman** [comment]
It appears to work as early as 23.05.0-edge, so if you're curious to figure out what fixed it you can check out the changelog entry for that version. Probably one of those commits fixed it.

**Comment by alexandrebouchard** [comment]
Thanks, I'll have a look!

Relatedly I have noticed that the native groovy processes always get assigned to local (i.e. bypassing e.g. PBS). Do you happen to know if that behaviour was fixed in the same commit?

**Comment by bentsherman** [comment]
Native `exec` tasks are always executed by Nextflow directly, that's how it's always been.

**Comment by alexandrebouchard** [comment]
Thanks for the clarification! It would be helpful to document that behaviour potentially, I don't recall reading it in the (excellent) docs.
