### ISSUE TITLE
sugar coating syntax for mix in the same channel

### ISSUE THREAD

**Issue by maxulysse** [nextflow-io/nextflow#4222]
## New feature

Hi,

I'm often using mix() to add elements in the same original channel such as:

```
ch_versions = ch_versions.mix(MULTIQC.out.versions)
```

I'd like to have something to simplify that, maybe something like:

```
ch_versions.append(MULTIQC.out.versions)
```

**Comment by drpatelh** [comment]
:shakefist:

**Comment by pditommaso** [comment]
I've gave a try to this, but it's more complex than expected. I also believe that this pattern can better addressed via [topic channels](https://github.com/nextflow-io/nextflow/discussions/2842)
