### ISSUE TITLE
 Preempted spot instances in google-batch not caught

### ISSUE THREAD

**Issue by Puumanamana** [nextflow-io/nextflow#4225]
## Bug report 

When using spot instances on GCP, preempted runs fail and do not report the information about the reason why they failed. I also think the exit code is not properly fetched and returned, so it's hard to catch it with errorStrategy directives.

### Expected behavior and actual behavior

Expected behavior: Warning message about the reason for failure, specific exit code
Actual behavior: Unhelpful error message and no exit code

### Steps to reproduce the problem

Since it's due to spot instances preemption, this is hard to reproduce.

### Program output 

nextflow output
```
Aug-25 12:07:48.794 [Task monitor] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Process `ROME_QUANT_HS:SALMON_QUANT (SRR8314967)` - terminated job=nf-c0015eec-1692964816136; state=FAILED
Aug-25 12:07:48.828 [Task monitor] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Cannot read exit status for task: `ROME_QUANT_HS:SALMON_QUANT (SRR8314967)` - gs://nxf-work/scratch/cedric/c0/015eecd3e5b7e884cc968ee0689a3e/.exitcode
Aug-25 12:07:49.679 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 208; name: ROME_QUANT_HS:SALMON_QUANT (SRR8314967); status: COMPLETED; exit: -; error: -; workDir: gs://nxf-work/scratch/cedric/c0/015eecd3e5b7e884cc968ee0689a3e]
Aug-25 12:07:49.680 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=ROME_QUANT_HS:SALMON_QUANT (SRR8314967); work-dir=gs://nxf-work/scratch/cedric/c0/015eecd3e5b7e884cc968ee0689a3e
  error [nextflow.exception.ProcessFailedException]: Process `ROME_QUANT_HS:SALMON_QUANT (SRR8314967)` terminated for an unknown reason -- Likely it has been terminated by the external system
Aug-25 12:07:59.682 [Task monitor] INFO  nextflow.processor.TaskProcessor - [c0/015eec] NOTE: Process `ROME_QUANT_HS:SALMON_QUANT (SRR8314967)` terminated for an unknown reason -- Likely it has been terminated by the external system -- Execution is retried (1)
Aug-25 12:08:01.957 [Task submitter] DEBUG n.c.g.batch.GoogleBatchTaskHandler - [GOOGLE BATCH] Process `ROME_QUANT_HS:SALMON_QUANT (SRR8314967)` submitted > job=nf-6f47c81b-1692965279744; uid=nf-6f47c81b-169296-6845efb3-e4f5-44830; work-dir=gs://nxf-work/scratch/cedric/6f/47c81bc1573550bc2e534b3a7d9077
Aug-25 12:08:01.957 [Task submitter] INFO  nextflow.Session - [6f/47c81b] Re-submitted process > ROME_QUANT_HS:SALMON_QUANT (SRR8314967)
```

google-batch run info
```
$ gcloud batch jobs describe projects/rome-pipeline-engine/locations/us-central1/jobs/nf-c0015eec-1692964816136
status:
  runDuration: 365.510589916s
  state: FAILED
  statusEvents:
  - description: Job state is set from QUEUED to SCHEDULED for job projects/114884310888/locations/us-central1/jobs/nf-c0015eec-1692964816136.
    eventTime: '2023-08-25T12:00:28.956975463Z'
    type: STATUS_CHANGED
  - description: Job state is set from SCHEDULED to RUNNING for job projects/114884310888/locations/us-central1/jobs/nf-c0015eec-1692964816136.
    eventTime: '2023-08-25T12:01:39.374564491Z'
    type: STATUS_CHANGED
  - description: Job state is set from RUNNING to FAILED for job projects/114884310888/locations/us-central1/jobs/nf-c0015eec-1692964816136.
      Job failed due to task failures. For example, task with index 0 failed, failed
      task event description is Task state is updated from RUNNING to FAILED on zones/us-central1-b/instances/1801933062347761379
      due to Spot VM preemption with exit code 50001.
    eventTime: '2023-08-25T12:07:44.885154407Z'
    type: STATUS_CHANGED
```

### Environment 

* Nextflow version: 23.08.0-edge
* Java version: 
```bash
$ java -version
openjdk version "17.0.3-internal" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17.0.3-internal+0-adhoc..src, mixed mode, sharing)
```
* Operating system: [macOS, Linux, etc]
```bash
$ uname -a
Linux nf-tower-main 5.15.0-1027-gcp #34~20.04.1-Ubuntu SMP Mon Jan 9 18:40:09 UTC 2023 x86_64 GNU/Linux
```
* Bash version: (use the command `$SHELL --version`)
```
$ $SHELL --version
zsh 5.8 (x86_64-ubuntu-linux-gnu)
```
### Additional context

(Add any other context about the problem here)

**Comment by bentsherman** [comment]
With Google Life Sciences, Nextflow can get the exit code from an API call, which made it possible to catch spot reclamations. Now I see that Google Batch is not doing same, so Nextflow relies only on the `.exitcode` file, which of course won't be written in the event of a spot reclamation.

@hnawar is there a way to get the exit code of a task through the Google Batch API? Right now it seems we would have to parse the status events and try to find the exit code that way.

**Comment by Puumanamana** [comment]
It seems to be possible in their API (https://cloud.google.com/batch/docs/reference/rest/v1/StatusEvent).
I couldn't quite figure out how to directly get the exit code, but at least it's part of the description field when doing doing a `GET` request at `https://batch.googleapis.com/v1/projects/*/locations/*/jobs/*`

**Comment by bentsherman** [comment]
That's much better, so we should be able to get the exit code from the most recent status event. And we can get the status events from the job status.

**Comment by bentsherman** [comment]
Strange, I tried using `StatusEvent -> getTaskExection() -> getExitCode()` but the status event has no "task execution" part as documented [here](https://cloud.google.com/java/docs/reference/google-cloud-batch/latest/com.google.cloud.batch.v1.StatusEvent#com_google_cloud_batch_v1_StatusEvent_getTaskExecution__)

@hnawar any reason why this API isn't working?

Test branch is [here](https://github.com/nextflow-io/nextflow/tree/4225-fix-google-batch-exit-code)

**Comment by soj-hub** [comment]
@bentsherman - a change to the Batch API has rolled out to populate the taskExecution within the StatusEvent. The preemption error code 50001 and other error codes will populate there.

**Comment by pditommaso** [comment]
Thanks, @soj-hub, this looks useful.

**Comment by bentsherman** [comment]
Hi @soj-hub , I am trying to get the exit code as you described but it is still not showing up. I upgraded the google batch SDK to 0.24.0 which seems to be the latest, but when I log the status events I get:

```
[
description: "Job state is set from QUEUED to SCHEDULED for job projects/770252724889/locations/us-central1/jobs/nf-deaaebd7-1698756993337."
event_time {
  seconds: 1698757012
  nanos: 95226026
}
type: "STATUS_CHANGED"
,
description: "Job state is set from SCHEDULED to RUNNING for job projects/770252724889/locations/us-central1/jobs/nf-deaaebd7-1698756993337."
event_time {
  seconds: 1698757080
  nanos: 649050186
}
type: "STATUS_CHANGED"
,
description: "Job state is set from RUNNING to SUCCEEDED for job projects/770252724889/locations/us-central1/jobs/nf-deaaebd7-1698756993337."
event_time {
  seconds: 1698757090
  nanos: 717582238
}
type: "STATUS_CHANGED"
]
```

The getTaskExecution() method is available but it returns nothing. Am I missing something?

**Comment by soj-hub** [comment]
There is another change we uncovered that is needed before the taskExecution populates as expected for multiple runnable use cases (this may or may not be relevant for Nextflow). In the meantime, is it possible to proceed with parsing the status event?

**Comment by bentsherman** [comment]
Yes, we can just parse the status message for now

**Comment by Puumanamana** [comment]
Regarding this fix, is `task.attempt` incremented when it's a preemption error? Ideally, I'd prefer not to so that it doesn't interfere with dynamic resource directives (e.g., increasing memory with retries)

**Comment by bentsherman** [comment]
Unfortunately it will. Ideally Google Batch should provide a mechanism to retry "under the hood" just like AWS Batch

**Comment by soj-hub** [comment]
Just so we are aware, can you clarify what is missing in Google Batch, or what is meant by "under the hood"? There are [Automatic Task Retries](https://cloud.google.com/batch/docs/automate-task-retries) in Google Batch, but I'm not sure if this is what is being referred to. [Here](https://cloud.google.com/java/docs/reference/google-cloud-batch/latest/com.google.cloud.batch.v1.LifecyclePolicy.ActionConditionOrBuilder) is the java reference. If this suffices then printing the exit code in taskExecution may not be necessary, but let us know if this works.

**Comment by bentsherman** [comment]
This is exactly what we need! I just couldn't find it for some reason. We will implement it in Nextflow.

At this point, printing the exit code is still nice to have because then Nextflow doesn't have to read the exitcode file from GCS, but it is not blocking anything.

**Comment by bentsherman** [comment]
@soj-hub is there an environment variable that we could use in the task environment to detect if the task was automatically retried? For example, AWS Batch has a `AWS_BATCH_JOB_ATTEMPT` environment var, and we use it to reset the task work directory since it is re-used.

**Comment by soj-hub** [comment]
@bentsherman - we're in the process of introducing a variable that will track the number of times a task has been retried. This should be available soon after Thanksgiving.

**Comment by jordeu** [comment]
Hi @soj-hub, I'm interested in using this variable that you mention. It is already available?

**Comment by VasLem** [comment]
Hi, could you please update the documentation? I am not able to see how to use the added directive in it. Thank you in advance!

**Comment by soj-hub** [comment]
The variable is called BATCH_TASK_RETRY_ATTEMPT and shown within https://cloud.google.com/batch/docs/create-run-basic-job#predefined-environment-variables
