### ISSUE TITLE
Support for AWS account profile

### ISSUE THREAD

**Issue by fstrozzi** [nextflow-io/nextflow#423]
Given that Nextflow already supports and uses the AWS configuration file on the command line to retrieve access and security keys, it would be nice if also the support for IAM profiles and role switching could be added. 

This will allow AWS IAM users that have given the permission to switch role to do so also with Nextflow, without the need to use higher privileges accounts or share access keys. This way a user that normally has no rights for example to run EC2 instances, can temporary switch role when submitting jobs via Nextflow or when creating a cluster. 

Using the AWS CLI tool this is normally achieved by specifying the IAM profile in the the ~/.aws/config file and by running commands with the --profile [PROFILE_NAME] option.

Here is the documentation from AWS describing the role switching : http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-cli.html

Update: adding also a link to the AWS Java SDK documentation describing the use of STS temporary credentials to switch role http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/prog-services-sts.html

Thanks!

**Comment by pditommaso** [comment]
IAM instance role is already supported. See [config](https://www.nextflow.io/docs/latest/config.html#scope-cloud) page. This issue refers to the ability to pick a AWS configuration profile and use the associated credentials.

**Comment by tbugfinder** [comment]
Well, as far as I understand IAM instance role is supported for the compute resources however instance roles should also be supported for the S3 and "submit" commands.

**Comment by pditommaso** [comment]
Closing this in favour of #860.
