### ISSUE TITLE
Debug scripts

### ISSUE THREAD

**Issue by jagedn** [nextflow-io/nextflow#4231]
## Debug scripts

Currently scripts are compiled without debug information but it's possible to compiled them with it so using a remote debug session an user can debug, go step by step or inspect variables a pipeline

## Usage scenario 

An user want to debug a pipeline, validating input parameters. 

The user can populate with `println` the script and remove them once depured but it's a dirty solution.

## Suggest implementation 

Use `configuration.debug=true` in `ScriptParser.groovy`

**Comment by pditommaso** [comment]
@jagedn would not this solved by https://github.com/nextflow-io/nextflow/pull/4266 ?
