### ISSUE TITLE
Upstream bug in conda: parallel calls to 'conda create' corrupt packages and cached repo data

### ISSUE THREAD

**Issue by najtin** [nextflow-io/nextflow#4233]
## Bug report 

Conda corrupts data if it is executed in parallel. Nextflow creates environments in parallel for some pipelines. Conda then sometimes fails to create the environment, and therefore also the pipeline fails. This is an upstream bug and it is tracked here: https://github.com/conda/conda/issues/13037 I just think that all nextflow users should be aware of this until it is fixed.  

### Expected behavior and actual behavior

Conda should not corrupt data if it is called in parallel, but actually conda does.

### Steps to reproduce the problem

```bash
# install nextflow
curl -s https://get.nextflow.io | bash
git clone https://github.com/nf-core/rnaseq
mkdir /tmp/testout
./nextflow run rnaseq/main.nf -profile test,conda --max_memory 6.GB --outdir=/tmp/testout
```

### Program output 

```
ERROR ~ Error executing process > 'NFCORE_RNASEQ:RNASEQ:PREPARE_GENOME:MAKE_TRANSCRIPTS_FASTA'

Caused by:
  Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /home/rnaseq-analyzer/work/conda/env-1ebecfb53a17dbda2156b0b602d6d7a8 bioconda::rsem=1.3.3 bioconda::star=2.7.10a
  status : 1
  message:
    CondaError: An error occurred when loading cached repodata.  Executing
    `conda clean --index-cache` will remove cached repodata files
    so they can be downloaded again.



 -- Check '.nextflow.log' file for details
```

### Environment 

* Nextflow version: 23.04.3
* Java version: 11
* Operating system: podman container with ubuntu 22 base image, host ubuntu 22 
* Bash version: 5.1.16(1)-release

### Workaround
The workaround limits conda to execute only one command at a time. 

```pip install filelock psutil``` 

Locate the conda executable with `which conda` on unix systems. Make a backup of it, so you still have the original once the issue is fixed upstream. Delete everything but the first line, then add:
```python3
# -*- coding: utf-8 -*-
import os
import psutil
from filelock import FileLock
import tempfile

def process_exists(pid):
    try:
        process = psutil.Process(pid)
        return True
    except psutil.NoSuchProcess:
        return False

def get_parent_pids():
    pid = os.getpid()
    parent_pids = []
    try:
        process = psutil.Process(pid)
        while process:
            parent_pids.append(process.pid)
            process = process.parent()
    except psutil.NoSuchProcess:
        pass
    
    return parent_pids

import sys

# Before any more imports, leave cwd out of sys.path for internal 'conda shell.*' commands.
# see https://github.com/conda/conda/issues/6549
if len(sys.argv) > 1 and sys.argv[1].startswith('shell.') and sys.path and sys.path[0] == '':
    # The standard first entry in sys.path is an empty string,
    # and os.path.abspath('') expands to os.getcwd().
    del sys.path[0]

conda_lock = tempfile.gettempdir() + "/.conda.lock"
conda_pid = tempfile.gettempdir() + "/.conda.pid"
conda_pid_lock = tempfile.gettempdir() + "/.conda.pid.lock"

if __name__ == '__main__':
    use_lock = True
    if os.path.exists(conda_pid):
        with FileLock(conda_pid_lock):
            with open(conda_pid, "r") as f:
                other_conda_pid = int(f.read())
            if process_exists(other_conda_pid) and other_conda_pid in get_parent_pids():
                use_lock = False
    error = None
    from conda.cli import main
    if use_lock:
        with FileLock(conda_lock):
            with FileLock(conda_pid_lock):
                with open(conda_pid, "w") as f:
                    f.write(str(os.getpid()))
            try:
                exit_code = main()
            except Exception as e:
                error = e
        if error is not None:
            raise error
        sys.exit(exit_code)
    else:
        sys.exit(main())
```

**Comment by bentsherman** [comment]
Sometimes I get a 137 exit code with `Failed to create Conda environment` and no other context, which seems to happen when Nextflow tries to create multiple environments in parallel. I wonder if it's the same bug. I am using Mambaforge which might behave differently.

Rather than patching `conda` itself, we could add a lock to `CondaCache` to ensure that Nextflow creates only one environment at a time. Ideally it should be optional for when it's not needed.

**Comment by najtin** [comment]
I think this could be a temporary fix, but this should really be fixed in conda itself. Nextflow is likely not the only application that is affected. 

>  Ideally it should be optional for when it's not needed.

From what i understand, right now locking is mandatory, because the repo data (index of channels) gets also corrupted.  This is why this should really be fixed upstream. There is right now no way to safely create environments in parallel. 

Regarding the temporary fix, nextflow could simply add a semaphore/mutex here: https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/conda/CondaCache.groovy#L276
