### ISSUE TITLE
"when" directive should not allow staging of input files for a process, if the criteria are not met

### ISSUE THREAD

**Issue by fstrozzi** [nextflow-io/nextflow#424]
Hello,
the "when" directive seems to be allowing staging input files even for processes that are not fulfilling the criteria specified. I think a better behaviour could be to entirely skip the process if the conditions under "when" are not met, given that for certain processes the inputs staging can take up quite some time and resources, especially if the files need to be copied or collected over the network.

Thanks!

**Comment by pditommaso** [comment]
Fantastico, non serve nemmeno autenticarsi nel container per usare `aws s3
.. etc` !



Adesso è tutta in discesa ;)

**Comment by pditommaso** [comment]
related to #265
