### ISSUE TITLE
nextflow pull -r needs to be run twice to pull remote tag

### ISSUE THREAD

**Issue by SamStudio8** [nextflow-io/nextflow#4246]
### Expected behavior

`nextflow pull -r <tag>` checks out a new tag from the remote repository.

### Actual behavior

* `nextflow pull -r <tag>` yields the following error: `Cannot find revision <tag> -- Make sure that it exists in the remote repository`
* A second `nextflow pull -r <tag>` is successful

### Steps to reproduce the problem

```
# Check out a known past tag
nextflow pull -r v1.0.0 epi2me-labs/wf-basecalling
LOCAL_PATH=$(nextflow info epi2me-labs/wf-basecalling | grep 'local path' | sed -nE 's, local path  : (.*),\1,p')
cd ${LOCAL_PATH}
# Nuke a known "future" tag
git tag -d v1.0.1
# Try and check it out with nextflow pull
nextflow pull -r v1.0.1 epi2me-labs/wf-basecalling
# check out again, successfully
nextflow pull -r v1.0.1 epi2me-labs/wf-basecalling
```

### Environment 

* Nextflow version: 23.04.2
* Java version: OpenJDK 64-Bit Server VM Homebrew (build 17.0.3+0, mixed mode, sharing)
* Operating system: macOS
* Bash version: zsh 5.8 (x86_64-apple-darwin21.0)

### Additional context

Running Nextflow pull on an existing asset repo, triggers the following events:
* [AssetManager.download](https://github.com/nextflow-io/nextflow/blob/v23.04.2/modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy#L575)
* [`git.checkout() .setName(revision) .call()`](https://github.com/nextflow-io/nextflow/blob/v23.04.2/modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy#L622), which will fail because the repository has not been fetched yet
* [`checkoutRemoteBranch(revision)`](https://github.com/nextflow-io/nextflow/blob/v23.04.2/modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy#L629C27-L629C47), triggered by the failure of the first `git.checkout()`
* [`fetch.call()`](https://github.com/nextflow-io/nextflow/blob/v23.04.2/modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy#L941), where the remote repository is now fetched
* [A second and fatal `git.checkout()`](https://github.com/nextflow-io/nextflow/blob/v23.04.2/modules/nextflow/src/main/groovy/nextflow/scm/AssetManager.groovy#L942), which fails because it tries to specifically track an upstream `origin/<revision>` branch (but revision is a tag)

When running the command a second time, the repository is successfully updated by the first `git.checkout().setName(revision)`.

Some initial thoughts on how to work around this:
* the repository should always be fetched before attempting the first git.checkout().setName(revision), or
* after failing to track a branch in `checkoutRemoteBranch`, `download` could attempt to checkout the revision as a tag

**Comment by SamStudio8** [comment]
Hey @bentsherman, thanks for the patch on this. Is there a plan to merge 4247?

**Comment by bentsherman** [comment]
Just waiting for @pditommaso to approve

**Comment by SamStudio8** [comment]
@pditommaso 
![cookies](https://github.com/nextflow-io/nextflow/assets/1105722/7539d13e-85ab-486f-a7fa-ad3f218cd403)

**Comment by pditommaso** [comment]
I was testing the associated PR, however I was not able to replicate the reported issue. This command works for me 

```
» nextflow pull -r v1.0.1 epi2me-labs/wf-basecalling
Checking epi2me-labs/wf-basecalling ...
 downloaded from https://github.com/epi2me-labs/wf-basecalling.git - revision: 3047f23c74 [v1.0.1]
```

What am I missing?

**Comment by bentsherman** [comment]
You have to delete the tag from the git repo to force git to pull a remote tag separate from the initial clone, like pulling a new release. See the "steps to reproduce the problem" in the OP
