### ISSUE TITLE
[Question] Configure `autoscale` per process (on AWS)

### ISSUE THREAD

**Issue by thaussma** [nextflow-io/nextflow#425]
Is it possible for `processes` to have different `autoscale` configurations? I'am running `nextflow` on AWS.

E.g. I'd like to autoscale `processA` with:
```
autoscale {
        instanceType = 'm4.large'
        minInstances = 10
        maxInstances = 20
```

And `processB` with:
```
autoscale {
        instanceType = 'm4.16xlarge'
        minInstances = 1
        maxInstances = 4
```

**Comment by pditommaso** [comment]
Currently it's not possible, but it's a feature under development.

**Comment by datnoor** [comment]
Any update on the autoscaling feature AWS?

**Comment by pditommaso** [comment]
Yes, use the built-in support for AS Batch.
