### ISSUE TITLE
[Question] Get system available resource in nextflow

### ISSUE THREAD

**Issue by likelet** [nextflow-io/nextflow#427]
Is there any way/function in nextflow to get the current  available resource such as memory and cpus.
I want to let the script determining the number of threads automatically

Thanks
Qi

**Comment by pditommaso** [comment]
Where are you running your script? workstation or a cluster scheduler?

NF is designed to deploy large workflow with a batch scheduler, is such system the avail resources depends on the job resource reservations.

**Comment by pditommaso** [comment]
I'm closing this issue because there no more feedback. Feel free to comment below if needed.
