### ISSUE TITLE
Subworkflow input: Missing process or function getAt([0])

### ISSUE THREAD

**Issue by defendant602** [nextflow-io/nextflow#4281]
## Bug report 

I am using a subworkflow in a main workflow, and I want to get items from subworkflow input channel by slice index, but I got `Missing process or function getAt([0])` error.

## Expected behavior
get the value of input channel by slice index.
## actual behavior
Missing process or function getAt([0])

### Steps to reproduce the problem

```
workflow test {
    take:
        inputs
    main:
        a = inputs[0]
        println a
    emit:
        a
}

workflow {
    input_ch = Channel.of([1,2,3,4])
    test(input_ch)
}
```

### Program output 

```
N E X T F L O W  ~  version 23.04.3
Launching `test_subworkflow.nf` [loving_gauss] DSL2 - revision: 9e4a8c7e85
Missing process or function getAt([0])

 -- Check script 'test_subworkflow.nf' at line: 16 or see '.nextflow.log' file for more details
```

### Environment 

* Nextflow version: [23.04.3] 
* Java version: [11.0.19]
* Operating system: [Linux]
* Bash version: (5.1.16(1)-release)

**Comment by pditommaso** [comment]
It should be 

```
workflow test {
    take:
        inputs
    main:
        a = inputs[0]
        println a
    emit:
        a
}

workflow {
    input_ch = Channel.of([1,2,3,4])
    test(input_ch)
}
```

but, yes, error message can be improved

**Comment by defendant602** [comment]
> It should be
> 
> ```
> workflow test {
>     take:
>         inputs
>     main:
>         a = inputs[0]
>         println a
>     emit:
>         a
> }
> 
> workflow {
>     input_ch = Channel.of([1,2,3,4])
>     test(input_ch)
> }
> ```
> 
> but, yes, error message can be improved

Thanks for your quick reply, but your code looks exactly the same with mine in the **Steps to reproduce the problem**, did I miss something?

**Comment by pditommaso** [comment]
Apologies, I meant `a = inputs` instead of `a = inputs[0]` (updated the previous comment)

**Comment by defendant602** [comment]
Thanks, if I want to get just the value 1 in the input channel, maybe below is the only way(means you can not get value from a channel by `input_ch[0]`)? 

```
workflow test {
    take:
        inputs
    main:
        a = inputs.map {
           it[0]
        }
        a.view()
    emit:
        a
}

workflow {
    input_ch = Channel.of([1,2,3,4])
    test(input_ch)
}
```
