### ISSUE TITLE
Request: Allow setting cache/history/plugin path

### ISSUE THREAD

**Issue by feiloo** [nextflow-io/nextflow#4283]
## New feature

Please enable setting different paths than `./.nextflow` for the cache/history/plugin folder.

## Usage scenario 

In my experience:

When invoking nextflow from multiple different directories, it leaves multiple '.nextflow' files.
This makes it harder to track them and keep the filesystem clean.

It also means that you have to change to a specific directory to use `nextflow log`.
I guess that the caching then misses too.

## Suggest implementation 

Any one or more configuration options: environment-variable, nextflow-config or commandline would help.

I would prefer having it as an environment variable, along the lines of `NXF_DB_DIR`, because it could be set on an os level, so that nextflow runs can be collected together, and it also eases moving the cache/history from dir to dir or env to env.

i am unsure, but i guess this line is responsible:

[HistoryFile.groovy line40](https://github.com/nextflow-io/nextflow/blob/23c4ec1d551cc55d5c35a70015aa137cfa7d5a56/modules/nextflow/src/main/groovy/nextflow/util/HistoryFile.groovy#L40C51-L40C51)

**Comment by bentsherman** [comment]
You can change the plugins directory using `NXF_PLUGINS_DIR`, which by default is `$NXF_HOME/plugins`.

I propose that we add a `NXF_CACHE_DIR` variable to control the cache directory. That would be useful if you want to have a single cache location and use `nextflow log` from any directory. The cache already maintains separate directories for each session anyway. The history file would just use `$NXF_CACHE_DIR/history`

**Comment by arnaudbore** [comment]
Hi @bentsherman,

Do you know if there is any update on this ?

Thank you in advance
