### ISSUE TITLE
add queue process directive as option for trace file

### ISSUE THREAD

**Issue by msmootsgi** [nextflow-io/nextflow#431]
It would be great if the `queue` process directive could be recorded for each process in the trace file output.  My use case is to track costs by knowing which parts of my pipeline ran in which queue.

**Comment by pditommaso** [comment]
It should not be difficult to add it. The relevant class is [TraceRecord](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/trace/TraceRecord.groovy#L43-43).

It should be enough to add a `queue` field in the [FIELDS](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/trace/TraceRecord.groovy#L61) map. 

Then populate it when the object is created in the [getTraceRecord](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/processor/TaskHandler.groovy#L144-144) method 

Some tests may be updated in `TraceRecordTest`, `TraceFileObserverTest` and `TaskHandlerTest`

**Comment by msmootsgi** [comment]
Awesome, I'll see what I can do!
