### ISSUE TITLE
Use Mermaid output in HTML DAG

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#4316]
Currently, the DAG output implementation for HTML is stand-alone, and needs to be maintained separately. The Mermaid DAG has been improved quite a bit recently (https://github.com/nextflow-io/nextflow/pull/4070). Rather than trying to maintain the two codebases separately, we could just reuse the Mermaid output for the HTML file.

Basically, if HTML is requested - create the Mermaid DAG output file and embed it within a static HTML template. The template should include the relevant Mermaid javascript dependencies and script blocks, as described in the [Mermaid docs](https://mermaid.js.org/intro/n00b-gettingStarted.html#_3-calling-the-javascript-api).

This should give us nicer functionality and less maintenance burden.

Note that the HTML DAG config scopes should probably still stay in place, but would then just forward on to the Mermaid DAG generation code.

👉🏻  Related to https://github.com/nextflow-io/nextflow/issues/4315

**Comment by ewels** [comment]
Some stretch goals from @bentsherman:

> With the HTML renderer I think we could go much farther than simply wrapping around the mermaid diagram. You can attach JS event handlers to nodes in a mermaid diagram, so we could make it interactive, i.e. click to expand/collapse sub-workflows. Also add hyperlinks for operators to the Nextflow docs and processes to their source code

**Comment by pditommaso** [comment]
@bentsherman think you should give a try to this
