### ISSUE TITLE
Document how cache invalidation works

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#4344]
The mechanism that Nextflow uses to decide whether the `-resume` cache should be invalidated or not has changed a couple of times, most recently in https://github.com/nextflow-io/nextflow/issues/2382 and then https://github.com/nextflow-io/nextflow/pull/4339

We should document how this works, which directives can be changed without affecting the cache and which cannot.

How resume works is a common question in the community, with people (still) being pointed these three blog posts on a regular basis:

* [Demystifying Nextflow resume](https://nextflow.io/blog/2019/demystifying-nextflow-resume.html)
* [Troubleshooting Nextflow resume](https://nextflow.io/blog/2019/troubleshooting-nextflow-resume.html)
* [Analyzing caching behavior of pipelines](https://nextflow.io/blog/2022/caching-behavior-analysis.html)

The more information that we can put into the docs to replace these blog posts, the better 🙌🏻

**Comment by pditommaso** [comment]
The first blog post is a great starting point for a proper docs page.

**Comment by bentsherman** [comment]
Related to #4336 , it's about time for a docs page dedicated to cache and resume. I will work with @llewellyn-sl to develop this page. I can create a first draft and have him review 👍
