### ISSUE TITLE
Ability to set bootDiskSize per process for Google Lifesciences/Batch

### ISSUE THREAD

**Issue by dougnukem** [nextflow-io/nextflow#4361]
## New feature

For different processes they may have differing bootDiskSize requirements (e.g. the containers that they are pulling may be small vs large). 

Currently you are only able to set the `bootDiskSize` on the Google executor (LifeSciences or Batch), and not on an individual process level like you can do with `machineType`

> google.batch.bootDiskSize | Set the size of the virtual machine boot disk, e.g 50.GB (default: none).

https://github.com/nf-core/configs/blob/af37a64489a22d077379ad57fde71d4e5a5a6c8d/conf/googlebatch.config#L31C1-L40C2

```
google {
...
    lifesciences.bootDiskSize              = '20 GB'
}

google {
...
    batch.bootDiskSize              = '20 GB'
}

```

## Usage scenario 

Ideally this could be set on the process configuration, e.g. withLabel declaration.

```
  withLabel: largeContainer {
    bootDiskSize = 6000.GB
    machineType='n2d-highmem-64'
    disk='6000 GB'
...
  }
```

## Suggest implementation 

(Highlight the main building blocks of a possible implementation and/or related components)

**Comment by bentsherman** [comment]
The `disk` directive can now be used for this purpose: https://nextflow.io/docs/edge/google.html#process-definition

**Comment by dougnukem** [comment]
@bentsherman That's awesome news, I saw the PR here https://github.com/nextflow-io/nextflow/pull/3861

Do you think that this functionality would be added to the Google Lifesciences executor (I know it's been deprecated) but we have some existing workflows running with that configuration.

**Comment by bentsherman** [comment]
We aren't going to update Life Sciences anymore since it is being removed. Even now I think the web interface is being removed soon. I would simply update your workflows to use Google Batch, it should only require a few changes to your Nextflow config

**Comment by bentsherman** [comment]
Closing since the requested feature is available and Life Sciences will not be updated
