### ISSUE TITLE
Improve cache debugging with `-dump-hashes`

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#4367]
When I want to figure out why a cached task was unexpectedly re-executed, the current approach is to do both runs with `-dump-hashes` and diff the logs. But I have to do a lot of manual work to extract the relevant information from the logs in order to produce a proper diff.

@abhi18av used some bash magic in [this blog post](https://nextflow.io/blog/2022/caching-behavior-analysis.html) to do some of this work:

```bash
cat nextflow.log \
  | grep 'INFO.*TaskProcessor.*cache hash' \
  | cut -d '-' -f 3 \
  | cut -d ';' -f 1 \
  | sort \
  | tee tasks.log
```

But it is only a partial solution, still requires some manual effort to inspect the component hashes.

A simple improvement would be to log the hashes for a task in a single line, that way Abhinav's bash script could produce a diff with the component hashes.

The ideal solution would be to incorporate this bash script into Nextflow itself as some kind of report, or a new command like we did with `nextflow inspect`. Nextflow needs the information from two different runs, so it would be difficult to do in the `run` command, beyond logging separate reports during each run that the user must compare.

On the other hand, if the task cache could contain all the components of a task that are used to compute the task hash, we could reproduce the `-dump-hashes` output by querying the task cache and re-computing the component hashes. It could be a nice extension to `nextflow log` or a new command like `nextflow diff`.

The task cache current cannot do this, but we are planning to add inputs and outputs metadata to the cache as part of #3802 and #3849 , so maybe we can make it work for this purpose as well.

Related: #844

**Comment by pditommaso** [comment]
A better approch could be to re-structure that output 

https://github.com/nextflow-io/nextflow/blob/7d5a21b0a176d60db4576b88620ddb24de083428/modules/nextflow/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L2194-L2204
