### ISSUE TITLE
Paratheses introduced in Slurm job names when using 'tag' process directives not allowed on some HPCs, need an (easy) way to ensure that job names contain alphanumeric chars only (and [- _\.] )

### ISSUE THREAD

**Issue by andreiprodan** [nextflow-io/nextflow#4368]
## New feature

Paratheses are not allowed in SLURM job names on some HPCs. Parantheses are introduced in Slurm job names when using the 'tag' process directive in a process definition. Need an (easy) way to ensure that job names contain alphanumeric chars only and dashes, undescrores, points.

Potential options:

1) a way to prevent the () from being added, or replace () with _ _ or - -

2) a way to switch off 'tag' across all processes from on place in a config file

## Usage scenario 

Would allow nf-core pipelines to run on HPCs where the SLURM schedulers only allows parantheses and "_", ".", "-" in job names

## Suggest implementation 

?

**Comment by barbarahelena** [comment]
yep, seems so... I get error messages of the form:

```
  sbatch: error: Illegal character in job name at position 19. Valid characters are lowercase a to z, uppercase A to Z, numbers 0 to 9, period (.), underscore (_) and hyphen (-).
  sbatch: error: Batch job submission failed: Unspecified error
```

Only occurs when 'invalid characters' are used in job name

**Comment by andreiprodan** [comment]
> Are you saying that the name rules can vary across different SLURM clusters?

Yep, blew my mind too...

**Comment by andreiprodan** [comment]
found a solution:

➜  Downloads cat nextflow.config. Adding the folowing lines to the `nextflow.config` file
process.executor = 'slurm'

```
executor.jobName = {
	fixed_name = "${task.name}" -> fixed_name.replaceAll( '[()\\s]', '_')
}
```

**Comment by andreiprodan** [comment]
This workaround should be usable for any type of manipulartion of the Slurm job names.

**Comment by bentsherman** [comment]
Good catch, I forgot about this option. For anyone else, see the docs [here](https://nextflow.io/docs/edge/config.html#scope-executor).

Also, you can avoid that weird error by using `replace` instead of `replaceAll`:

```groovy
executor.jobName = { task.name.replace('[():\\s]', '_') }
```
