### ISSUE TITLE
Support PE fuidigm

### ISSUE THREAD

**Issue by grendon** [nextflow-io/nextflow#437]
Hi,
I am new to nextflow scripting. My question has to do with processing only a subset of raw reads. 

Suppose the raw reads have this pattern:  

              targetID-BarcodeID_SequencingBarcode_R{1,2}.fastq

where:
targetID could be ITS V3 V4
BarcodeID could be a long list of dozens of barcodes. 

In fact, I have a BarcodeID file for ITS, another one for V3 and another one for V4

How can I selectively read only the filenames  that match the barcodes for ITS/V3/V4 that I included in the corresponding barcode file?

**Comment by pditommaso** [comment]
Well, you can use a more complex glob pattern, eg

```
Channel.fromFilePairs("targetID-BarcodeID_{ITS,V3,V4}_R{1,2}.fastq")
```

If even this is not enough, there several alternatives. For example, you could list all the raw reads and the have and extra filter to fetch only the ones matching the requested list of barcodes. For example: 

```
def list_of_barcodes = [ 'ITS', 'V3', 'V4']
Channel
   .fromFilePairs("targetID-*_R{1,2}.fastq")
   .filter { prefix, reads -> filter in list_of_barcodes } 
   .set { reads_ch } 
```

Then the [filter](https://www.nextflow.io/docs/latest/operator.html#filter) rule can be complex as needed.

**Comment by grendon** [comment]
Thank you for your reply.  
My barcodes are too many and the list changes too much to be assigned via variable of type list like you suggest.  Perhaps a file of barcodes would be more appropriate.   Would something like this work in nextflow??

ITSFile = file('somepath/ITS_barcodes.txt')
ITSbarcodes  = ITSFile.readLines()
Channel
   .fromFilePairs("ITS-*_R{1,2}.fastq")
   .filter { prefix, reads -> filter in ITSbarcodes } 
   .set { reads_ch }

**Comment by pditommaso** [comment]
It should. However I think the prefix contains the file name up to the
matching pattern (not sure, can't check now).

Hence you will need a bit more code to check if belongs to that like.

You may want to use the command `nextflow console` to prototype that
snippet.

**Comment by pditommaso** [comment]
I'm closing this because there's any more feedback. Feel free to comment below if needed.
