### ISSUE TITLE
Document assignment syntax for process directives

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#4372]
The documentation says that process config settings must use an assignment syntax:

```groovy
process {
  cpus = 2
}
```

Whereas process directives in a pipeline script should use command syntax:

```groovy
process FOO {
  cpus 2
}
```

But technically the assignment syntax is also supported in process directives:

```groovy
process FOO {
  cpus = 2
}
```

As far as I can tell from the source code, this syntax is perfectly valid and works just as well as the command syntax. So maybe we should document it as such? @pditommaso what do you think?

Side notes:
- Omitting the `=` in a config setting should lead to a syntax error, but instead it is interpreted as a command expression and usually leads to a non-sensical error. Maybe should be a separate issue...
- The assignment syntax in a process definition can be used to define arbitrary process settings. The [nf-float](https://github.com/MemVerge/nf-float) plugin uses this hack to support a custom directive `extra`, for example. The command syntax doesn't support it because it leads to a method missing error. Not sure if this loophole is intended, but if we decide to close it, we should provide an alternative way for plugins to define custom directives. So that's a whole can of worms...

**Comment by pditommaso** [comment]
> So maybe we should document it as such? @pditommaso what do you think?

I think we should stay with the current syntax because it's less verbose. This is a good point to enforce in the next iteration of the lang iteration.

**Comment by bentsherman** [comment]
Closing since we will remove this syntax in the new parser
