### ISSUE TITLE
Improve error message on missing `=` in config

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#4373]
Spun off from #4372. Consider the following configuration:

```groovy
process {
  cpus = 2
  memory 4.GB // incorrect
}
```

Omitting the `=` in a config setting should lead to a syntax error, but instead it is interpreted as a command expression and usually leads to a non-sensical error:

```
ERROR ~ Unknown method invocation `memory` on _parse_closure5 type -- Did you mean?
  memoize

 -- Check '.nextflow.log' file for details
```

Instead it should be reported as a syntax error. This error happens often because of the different syntax for process config options and process directives.

The error is thrown from here: https://github.com/nextflow-io/nextflow/blob/0bce2be098bfd61bd6d78eb5e5379fd1002fea15/modules/nextflow/src/main/groovy/nextflow/config/ConfigParser.groovy#L446-L451

**Comment by bentsherman** [comment]
The error message is slightly different if the argument is a closure:

```groovy
process {
  memory { 4.GB }
}
```

```
ERROR ~ Unknown config attribute `process.memory` -- check config file: nextflow.config
```

The error is thrown from here: https://github.com/nextflow-io/nextflow/blob/0bce2be098bfd61bd6d78eb5e5379fd1002fea15/modules/nextflow/src/main/groovy/nextflow/config/ConfigBuilder.groovy#L453-L461

**Comment by bentsherman** [comment]
Not sure if it's possible to improve these errors without knowledge of the available config scopes, because there are some legitimate cases for command syntax, like plugins:

```groovy
plugins {
  id 'nf-hello'
}
```

**Comment by pditommaso** [comment]
The config parsing logic it's extremely convoluted. Not sure how much space there's for improving the error message reporting. I'd suggest to focus on the new config subsystem

**Comment by bentsherman** [comment]
Closing in favor of #4744
