### ISSUE TITLE
Set up .nextlow and nextflow.log paths in nextflow.config

### ISSUE THREAD

**Issue by arnaudbore** [nextflow-io/nextflow#4388]
## New feature

It would be nice to have a way to set up the path to `.nextflow` directory as well as `.nextflow.log` the same way we can use **workDir**  in the nextflow.config file

## Usage scenario 

That would be nice to have such option. All my flows have an option to output `results` and `work` directories into a specific folder but people keep asking me to put all the logs in the so called output folder. 

Thank you in advance !

**Comment by bentsherman** [comment]
The log file path can be controlled via `NXF_LOG_FILE`, I think it's just not documented.

Agree that it would be good to be able to set the cache path. See also #4283

**Comment by pditommaso** [comment]
`NXF_LOG_FILE` is documented [here](https://github.com/nextflow-io/nextflow/blob/766f20c3ae2dcceef1d24c093a6c90dc0fda0e43/docs/config.md#L1772-L1773). The cache dir path can be defined via `NXF_CACHE_DIR` variable (See #4283)
