### ISSUE TITLE
Add Jupyter kernel to allow nextflow to work as an interactive notebook

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#439]
The goal is to develop a [kernel](http://jupyter-client.readthedocs.io/en/latest/kernels.html) extension that would allow Nextflow to be used as an interactive [Jupyter](http://jupyter.org/) notebook. 

This would make it possible to easily interact with the Nextflow environment in an interactive manner and, above all, to post-process a pipeline result in the Jupyter notebook. 

Already exist a working [groovy kernel](https://github.com/lappsgrid-incubator/jupyter-groovy-kernel), it should be easily extended to support a Nextflow session.

**Comment by ameintjes** [comment]
I might be able to put some time into this. I use Jupyter daily and nextflow increasingly for some of our pipelines. My hunch is the two would compliment each other but I haven't been able to envisage how the flow would work.

a) call nextflow scripts from within Jupyter cell and have the results accessible. 
b) run a nextflow script externally and explore results within Jupyter. That's sort-of possible already isn't it?
c) some sort of deeper integration of nextflow's concepts (like a process) into Jupyter

I think I'm looking for a simple usage scenario

**Comment by pditommaso** [comment]
Yes, the idea is to allow the execution of NF snippets as Jupyter cell. I think the best thing would be to create a custom [Jupyter kernel](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) that will execute the NF code and send back the result. The [groovy one](https://github.com/lappsgrid-incubator/jupyter-groovy-kernel) can provide a skeleton for such implementation.

**Comment by pditommaso** [comment]
Other interesting resources: 
* http://beakerx.com/
* https://github.com/twosigma/beakerx

**Comment by BoPeng** [comment]
In terms of interesting resource, may I add https://vatlab.github.io/sos-docs/ ? It is a workflow system designed to be interactive.

**Comment by pditommaso** [comment]
The goal of this issue to implement a NF kernel for Jupyter. Not sure to understand how your link is related to this?

**Comment by BoPeng** [comment]
Well SoS is similar to beakerx that you found interesting as a polyglot Jupyter kernel, and it can be more interesting as it is also a workflow engine. I mean, if the goal is to integrate a workflow engine to Jupyter, SoS is an existing workflow engine that is tightly integrated with Jupyter. But if you are looking for a kernel implementation in the java family if languages, beakerX is indeed more relevant.

**Comment by mcapuccini** [comment]
I was trying to get this working on Apache Zeppelin (which has support for Groovy). I can start the interpreter with the NextFlow maven Jar, what classes should I import before I can write the DSL?

**Comment by pditommaso** [comment]
The relevant part for NF DSL execution is in [this part](https://github.com/nextflow-io/nextflow/blob/4f098d3dcb647bbb72c5b9866c48a9e1701f337e/src/main/groovy/nextflow/script/ScriptRunner.groovy#L163-L170). In particular see [parseScript](https://github.com/nextflow-io/nextflow/blob/4f098d3dcb647bbb72c5b9866c48a9e1701f337e/src/main/groovy/nextflow/script/ScriptRunner.groovy#L257-L312) method. 

Also can be useful to see how the `nextflow console` command works. Check it out [this class](https://github.com/nextflow-io/nextflow/blob/daded334b2478596d9821fb9049f91e05fc22699/subprojects/nxf-console/src/main/nextflow/ui/console/Nextflow.groovy#L53).

**Comment by mcapuccini** [comment]
Nice! Another possibility would be to use the shell interpreter in Zeppelin and start the paragraph with `#!/usr/bin/env nextflow`. I'll investigate a bit and let you know, thanks!

**Comment by pditommaso** [comment]
Yes, @evanfloden is using this approach to run NF with Jupyter

**Comment by mcapuccini** [comment]
Nice! @evanfloden did you push any of your NF notebooks on GitHub? I'd like to give it a look.

**Comment by pditommaso** [comment]
(closed by mistake)

**Comment by mcapuccini** [comment]
Alright... I can run something like:

```
%sh
cat << EOF > /tmp/hello.nf
#!/usr/bin/env nextflow
cheers = Channel.from 'Bonjour', 'Ciao', 'Hello', 'Hola'
process sayHello {
  input: 
    val x from cheers
  script:
    """
    echo '$x world!'
    """
}
EOF
./nextflow run /tmp/hello.nf
```

But I was hoping to be able to run in a pure Groovy cell, something like this:
```
%groovy
import nextflow.Channel
import static nextflow.Nextflow.*

echo true
cheers = Channel.from 'Bonjour', 'Ciao', 'Hello', 'Hola'
process sayHello {
  input: 
    val x from cheers
  script:
    """
    echo '$x world!'
    """
}
```

Is this achievable? I thought NF DSL to be pure Groovy code, but perhaps you need to parse it or something?

**Comment by pditommaso** [comment]
It possible but the it requires a NF kernel that evaluates the NF code using the groovy compiler configuration showed [here](https://github.com/nextflow-io/nextflow/blob/4f098d3dcb647bbb72c5b9866c48a9e1701f337e/src/main/groovy/nextflow/script/ScriptRunner.groovy#L274-L308).

**Comment by mcapuccini** [comment]
Good. I think we can get away by extending this class: https://github.com/apache/zeppelin/blob/master/groovy/src/main/java/org/apache/zeppelin/groovy/GroovyInterpreter.java#L68. Adding the configuration should be straightforward.

**Comment by evanfloden** [comment]
I am running Nextflow within cells with:
```
!nextflow run main.nf ...
```
I have jupyter running on a login node and I have handle Nextflow sending jobs to cluster etc. 

I have also tested it with aws batch from my laptop and it works great.

**Comment by SpencerPark** [comment]
Hey guys, just came across this issue. I'm the developer of https://github.com/SpencerPark/jupyter-jvm-basekernel which aims to be the Python base kernel but in Java. I do have a slight bias but it appears to be a project that this endeavor to create a Nextflow kernel could greatly benefit from.

I am using it in the java kernel mentioned earlier by @pditommaso (https://github.com/SpencerPark/IJava) if you are looking for an example.

**Comment by pditommaso** [comment]
Thank the suggestion @SpencerPark. If I'm understanding correctly the jupyter-jvm-basekernel provides backbone for a generic JVM based language and the example in the repository implements a JavaScript kernel based on Nashorn engine. Is that right? Does it support all Jupyter features like for example code completion?

**Comment by SpencerPark** [comment]
@pditommaso correct, one little tweak I would make to the terminology is that is is for a generic JVM based _kernel_. The language is arbitrary but the interpreter is most likely written in some JVM language (like groovy) and the kernel (the process that receives and responds to language related requests) is for sure written in a JVM language.

It is a full implementation of version 5.3 of the messaging spec. You would create a class that extends `BaseKernel` and at the very least, implement the method `DisplayData eval(String)` which evaluates the code (in your case nextflow source code) and potentially returns some rich output (like text, or an image, etc). Then if your interpreter would like to support auto completion override `ReplacementOptions complete(String code, int at)` and so forth to add in functionality for anything your interpreter can support.

The base kernel aims to implement as much functionality as possible without assuming anything about the source language which is why the `eval`, `inspect`, `complete`, etc. methods are not defined and it would be up to the specific kernel implementation to "fill" those in.

**Comment by mcapuccini** [comment]
I am a bit busy at the moment, but I might be able to give it a try in a couple of weeks. If in the meanwhile you get something to work please let me know. I am mostly interested in the Zeppelin interpreper, as it better integrates with Spark and Ignite. My intuition is that it may be enough to override the [open method](https://github.com/apache/zeppelin/blob/master/groovy/src/main/java/org/apache/zeppelin/groovy/GroovyInterpreter.java#L67-L90) and add the configs to the [Groovy shell](https://github.com/apache/zeppelin/blob/master/groovy/src/main/java/org/apache/zeppelin/groovy/GroovyInterpreter.java#L55). Everything else should be ok as it is.

**Comment by pditommaso** [comment]
@SpencerPark I've manage to implement the skeleton of a basic Nextflow kernel using https://github.com/SpencerPark/jupyter-jvm-basekernel. 

However there are some problems handling Nextflow dependencies. My understanding is that the installation script creates a fat jar with all the required deps. Unfortunately this approach mess us the libraries manifest descriptors creating several problems. 

Is there any alternative to the creation of a fat jar? maybe just setting the Java classpath?

**Comment by SpencerPark** [comment]
@pditommaso yep the fat jar worked nicely for IJava but doesn't in all cases. The stuff relating to building the fat jar is specified in the `build.gradle` and is not part of the jupyter plugin.

There is a property of the `jupyter` extension called `kernelResources` ([See configuration options](https://github.com/SpencerPark/Jupyter-kernel-installer-gradle#configuration-options)). This is a FileCollection and you can add anything to there that you want in the installation directory. 

Furthermore you can build whatever jar you wish and set the manifest how you like by configuring gradle's `jar` task. I happened to include all the dependencies in a `shade` configuration but you are free to build the jar how you would like. 

```diff
jar {
-    //Include all shaded dependencies in the jar
-    from configurations.shade
-            .collect { it.isDirectory() ? it : zipTree(it) }

    manifest {
        attributes(
            'Main-class': 'io.github.spencerpark.ijava.IJava',
+            'Class-Path': 'Nextflow class path'
        )
    }
}
```

Or another option is to use the `kernelEnv` property to set an environment variable to the classpath. If you need something more dynamic please raise an issue over at [Jupyter-kernel-installer-gradle](https://github.com/SpencerPark/Jupyter-kernel-installer-gradle/issues) and we can see what we can do.

**Comment by pditommaso** [comment]
Wow! this helped a lot, thanks!

**Comment by mcapuccini** [comment]
Nice! Do you get the workflow to continue working when closing the browser? I remember having this problem with Luigi, when running stuff in the Python kernel.

**Comment by ppericard** [comment]
Hi,
I'm really interested in the possibility of using nextflow within a jupyter notebook. I understand it is still being developed, but is there a way to try the current version, or is it not ready to be beta tested ?

**Comment by pditommaso** [comment]
Hi Pierre, there's a prototype but it's too unstable to release it. However you can use the stock nextflow from Jupyter as any other Bash command. @evanfloden is the guru for this.
