### ISSUE TITLE
Update nextflow logos

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#4395]
The following assets should use the updated nextflow logo 

1. [Notification](https://github.com/nextflow-io/nextflow/blob/dfb5bf092066ea5ac81f3c17ed14e1a42a126366/modules/nextflow/src/main/resources/nextflow/mail/notification.html#L141-L145) email 
2. [Execution report](https://github.com/nextflow-io/nextflow/blob/dfb5bf092066ea5ac81f3c17ed14e1a42a126366/modules/nextflow/src/main/resources/nextflow/trace/ReportTemplate.html#L21-L21)
3. [Timeline report](https://github.com/nextflow-io/nextflow/blob/dfb5bf092066ea5ac81f3c17ed14e1a42a126366/modules/nextflow/src/main/resources/nextflow/trace/TimelineTemplate.html#L21-L21)

**Comment by pditommaso** [comment]
tagging @ewels for visibility

**Comment by bentsherman** [comment]
From where do I source these logos?

**Comment by ewels** [comment]
Seqera Google Drive. But not before Monday 16th 😊 We can sit and do it together at the hackathon @bentsherman

**Comment by bentsherman** [comment]
We currently source the logos from [nextflow-io/trademark](https://github.com/nextflow-io/trademark), so we should either update both repos at the same time or include the logos in the Nextflow repo.

**Comment by pditommaso** [comment]
> We currently source the logos from nextflow-io/trademark

don't believe so, the email is [here](https://github.com/nextflow-io/nextflow/blob/882f369ebf54c821ea1306f7bb1069a7d0f63e60/modules/nextflow/src/main/resources/nextflow/mail/nextflow200x40.png)

The report should be [this](https://github.com/nextflow-io/nextflow/blob/882f369ebf54c821ea1306f7bb1069a7d0f63e60/modules/nextflow/src/main/resources/nextflow/trace/ReportTemplate.html#L96-L97)

**Comment by bentsherman** [comment]
I was talking about the README

**Comment by bentsherman** [comment]
For the trademark repo, do you want to delete the old assets or keep them on master?

**Comment by pditommaso** [comment]
It ca be overridden, in any case Github will store it forever

**Comment by bentsherman** [comment]
One last question... do I have to update the [screenshots](https://github.com/nextflow-io/nextflow/tree/master/docs/images)? 😅

**Comment by pditommaso** [comment]
Uff, maybe we can patch them with the new one

**Comment by ewels** [comment]
Unless any objections, I would suggest that we add a copy of the new logos to the nextflow repo and use these in the readme, instead of loading from the trademark repo. Having them hotlink from another repo seems a bit awkward and fragile to me..
