### ISSUE TITLE
Weirdness when combining multiple implicitly generated output channels of subworkflow

### ISSUE THREAD

**Issue by julibeg** [nextflow-io/nextflow#4396]
### Steps to reproduce the problem

```
process proc {
    input: tuple path(f1), path(f2)
    output: stdout
    script:
    """
    ls
    """
}

workflow sub_wf {
    main:
        v1 = file("file1.txt")
        v2 = file("file2.txt")
    emit:
        v1
        v2
}

workflow {
    sub_wf()
    v1 = sub_wf.out.v1
    v2 = sub_wf.out.v2

    v1.combine(v2)
    | proc
    | view
}

```
The above hangs with the following output
```
N E X T F L O W  ~  version 23.04.2
Launching `test.nf` [fabulous_nightingale] DSL2 - revision: 8e52391ae4
[-        ] process > proc -
```

Looks like something weird is going on with the implicit conversion of the paths to value channels when emitting from the sub-workflow. When I explicitly put them into value channels (e.g. with `v1 = Channel.fromPath("file1.txt").first()` in the sub-workflow), everything works as expected.

### Environment 

* Nextflow version: 23.04.2
* Java version: openjdk 17.0.3-internal 2022-04-19
* Operating system: Linux
* Bash version: 4.3.48(1)-release (x86_64-pc-linux-gnu)

**Comment by mribeirodantas** [comment]
The issue is with your subworkflow main block. Replace
```groovy
  v1 = file("file1.txt")
  v2 = file("file2.txt")
```
with
```groovy
  v1 = Channel.of(file("file1.txt"))
  v2 = Channel.of(file("file2.txt"))
```

and it will work 😉

**Comment by bentsherman** [comment]
I think he shouldn't have to do that though, because they should be wrapped into value channels

**Comment by mribeirodantas** [comment]
I first tried printing the channels (`println`) expecting them to be converted into value channels, but the format was different from the usual, which made sense as things didn't work correctly with that. Please, let me know if you understand what's going on, maybe it's a bug.

**Comment by bentsherman** [comment]
I was wrong, workflow takes/emits are not implicitly converted, only process inputs/outputs. So `v1 and `v2` would still be raw values at the line `v1.combine(v2)`. Closing this issue since there is no bug.

For the record, I think it would be better for operators to be called in a functional style e.g. `combine(v1, v2)` rather than the object style, because this way, raw values could be wrapped in value channels. But this is a more radical solution
