### ISSUE TITLE
Exceptions and `error()` are unusable in onComplete handler

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#4397]
Slack thread: https://nextflow.slack.com/archives/C02T98A23U7/p1696364290193959

Exceptions can't be thrown from the workflow onComplete handler because they are immediately caught by Nextflow and logged as an error:

https://github.com/nextflow-io/nextflow/blob/dfb5bf092066ea5ac81f3c17ed14e1a42a126366/modules/nextflow/src/main/groovy/nextflow/script/WorkflowMetadata.groovy#L391-L398

This also affects the `error()` function, which throws a `WorkflowScriptErrorException` under the hood. Throwing an exception is a useful way to fail the entire run if some final validation does not succeed.

On the other hand, if some unexpected exception is thrown, the current logic prevents the entire run from failing, which can be nice.

A good solution might be to re-throw `WorkflowScriptErrorException` but catch and log all others.

**Comment by pditommaso** [comment]
> A good solution might be to re-throw WorkflowScriptErrorException but catch and log all others.

Sounds good
