### ISSUE TITLE
Bug in getMaxRetries()

### ISSUE THREAD

**Issue by ast-al** [nextflow-io/nextflow#4398]
https://github.com/nextflow-io/nextflow/blob/882f369ebf54c821ea1306f7bb1069a7d0f63e60/modules/nextflow/src/main/groovy/nextflow/processor/TaskConfig.groovy#L310-L314

With `maxRetries 0`, the function returns the default value of `1` instead.
Hypothesis: `get()` returns the value as `int`, whereas the code assumes a `string`.

To reproduce:
```
process process1 {
    errorStrategy 'retry'
    maxRetries 0  // results in one retry, expecting zero; NB: works as expected when specified as "0"
    script:
    """
    exit 42
    """
}

workflow {
    process1()
}
```

**Comment by pditommaso** [comment]
That's expected because `errorStrategy 'retry'` is specified
