### ISSUE TITLE
Include docker container hash when calculating cache key.

### ISSUE THREAD

**Issue by pkaleta** [nextflow-io/nextflow#443]
Right now nextflow doesn't take the docker container hash into account when calculating a hash to cache the outputs. In other words, if just the docker container changes, nextflow will not rerun the process. Instead it will use the cached version, if it exists.

I think it makes sense to include docker container hash when calculating cache hash. The motivation behind this is that process' output, by definition, depends on the container used to run it.

**Comment by fmorency** [comment]
+1. Might as well add this feature to Singularity containers.
