### ISSUE TITLE
Nextflow error - Capsule

### ISSUE THREAD

**Issue by hmmachko** [nextflow-io/nextflow#4431]
### Discussed in https://github.com/nextflow-io/nextflow/discussions/4430

<div type='discussions-op-text'>

<sup>Originally posted by **hmmachko** October 18, 2023</sup>
### Expected behavior and actual behavior
I am attempting to use nextflow for viralrecon on my Mac OS local linux terminal. I am unable to initialize the nextflow environment du to Capsule parse version error.

### Steps to reproduce the problem
I downloaded nextflow with:
`wget -qO- https://get.nextflow.io | bash`
Any command to try and use nextflow, such as `nextflow -h` yields the text shown below in Program output. 

### Program output
`CAPSULE EXCEPTION: Could not parse version: 18.0.1.1 while processing attribute Min-Java-Version: 1.8.0 (for stack trace, run with -Dcapsule.log=verbose)
USAGE: java <options> -jar .nextflow/framework/22.04.5/nextflow-22.04.5-one.jar`

and 

`nextflow -h -Dcapsule.log=verbose` results
`CAPSULE: Jar: /Users/labadmin/.nextflow/framework/22.04.5/nextflow-22.04.5-one.jar
CAPSULE: Platform: macos
CAPSULE: Loading caplet: MavenCapsule
CAPSULE: Applying caplet MavenCapsule
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: nextflow_22.04.5
CAPSULE: Launching app nextflow_22.04.5
CAPSULE: Cleanup
CAPSULE EXCEPTION: Could not parse version: 18.0.1.1 while processing attribute Min-Java-Version: 1.8.0`

###Environment
Nextflow version: nextflow_22.04.5
Java version:
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
Operating system: Mac OS 13.2.1 
Bash version: 5.8.1 (x86_64-apple-darwin22.0)
</div>

**Comment by bentsherman** [comment]
Closing in favor of #4430
