### ISSUE TITLE
Documentation shows that Apptainer's autoMount property defaults to false, but it does not.

### ISSUE THREAD

**Issue by jkaessens** [nextflow-io/nextflow#4432]
## Bug report 

At https://www.nextflow.io/docs/latest/config.html#scope-singularity, the autoMount property is correctly listed as defaulting to `true`, which is a very recent change. The Apptainer configuration still reads `false`, although the ApptainerBuilder directly picks up the SingularityBuilder options, and thus also defaults to `false`.

### Expected behavior and actual behavior

The documentation should correctly show the Apptainer.autoMount property defaulting to `true`.

### Steps to reproduce the problem

None, documentation issue.

### Program output 

None, documentation issue.

### Environment 

* Nextflow version: 23.10.0.5889
* Java version: OpenJDK 20.0.2
* Operating system: CentOS Stream 9
* Bash version: 5.1.8

### Additional context

None

**Comment by pditommaso** [comment]
You are right. Thanks for reporint. Solved by 88226f20
