### ISSUE TITLE
Add support for Singularity OCI-mode

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#4439]
Singularity is a container runtime alternative to Docker, popular in the HPC community. 

It provides it's own image specification and format, and it allows converting Docker images to Singularity image files. However the latter is a slow and error-prone process. 

The version 4 of Singularity allows the run of OCI-based format images in a native manager, with it extremely useful for improving interoperability with existing container images and Wave containers. Read [more here](https://docs.sylabs.io/guides/4.0/user-guide/oci_runtime.html#oci-mode).

The goal of this issue is to add to nextflow the support for OCI container for singularity. 

This requires
1. adding a new configuration setting to enable this feature `singularity.oci = true|false` 
2. when this setting is enabled the `singularity exec` command should include the `--oci` option

**Comment by pditommaso** [comment]
@marcodelapierre you may want to give a try to it

**Comment by marcodelapierre** [comment]
OK, going to comment on the linked PR
