### ISSUE TITLE
Warning about unknown instance type

### ISSUE THREAD

**Issue by stevemmarshall** [nextflow-io/nextflow#444]
I'm running this version of nextflow version 0.25.6.4526 and when I ran nextflow 
nextflow cloud spot-prices, I got this message..

```
WARN: Unknown instance type: m4.10xlarge
WARN: Unknown instance type: m4.4xlarge
WARN: Unknown instance type: r3.xlarge
....
```

thanks
steve

**Comment by pditommaso** [comment]
It looks like Amazon changed the prices file format. I've uploaded a snapshot that should solve the problem. To use it delete the AWS cache in the NF folder as shown below: 

```
rm -rf ~/.nextflow/aws 
``` 

Then define the following var in your environment: 

```
export NXF_VER=0.25.7-SNAPSHOT
```

Then you can use NF as usual, on the first run it will update itself.

**Comment by stevemmarshall** [comment]
Hi @pditommaso 

Thanks for looking into this quickly... I tried that and still got the same error..

cheers
steve

**Comment by pditommaso** [comment]
Can run this command and report here the stdout ?

```
ls -la ~/.nextflow/aws/
```

**Comment by stevemmarshall** [comment]
Looks like a "csv" file has been created... 
drwxrwxr-x 2 ubuntu ubuntu      4096 Sep  5 23:02 .
drwxrwxr-x 7 ubuntu ubuntu      4096 Sep  5 23:02 ..
-rw-rw-r-- 1 ubuntu ubuntu        21 Sep  5 23:02 ec2-instance-types-us-east-1.bin
-rw-rw-r-- 1 ubuntu ubuntu 104774458 Sep  5 23:02 ec2-pricing.csv

**Comment by pditommaso** [comment]
I've uploaded a new snapshot. As before define a variable `NXF_VER=0.25.7-SNAPSHOT` in your env, then run this command: 

```
CAPSULE_RESET=1 nextflow info 
```

Verify it prints 

```
  Version: 0.25.7-SNAPSHOT build 4529
  Modified: 06-09-2017 08:14 UTC (10:14 CEST)
```

Then run NF as usual.

**Comment by stevemmarshall** [comment]
Hi @pditommaso 

Yes, that worked... thanks a lot.

cheers
steve

**Comment by pditommaso** [comment]
This was caused by a breaking change in the AWS price API format

**Comment by lch14forever** [comment]
Hi,

I am facing the same issue here with the latest version of AWS. I am using the latest version of nextflow:

```
| ~> nextflow -version

      N E X T F L O W
      version 19.04.1 build 5072
      last modified 03-05-2019 12:29 UTC (20:29 HKST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io
```
and here is what has been cached:

```
| ~> ls -la ~/.nextflow/aws/
total 671180
drwxrwxr-x 2 lichenhao lichenhao      4096 Jul 26 22:24 .
drwxrwxr-x 6 lichenhao lichenhao      4096 Jul 26 22:19 ..
-rw-rw-r-- 1 lichenhao lichenhao        21 Jul 26 22:24 ec2-instance-types-cn-northwest-1.bin
-rw-rw-r-- 1 lichenhao lichenhao 687268953 Jul 26 22:23 ec2-pricing.csv
```
Interestingly initialising instances works fine in a different region "ap-southeast-1". Any suggestions on what the cause could be?

**Comment by pditommaso** [comment]
Open a separate issue specifying which region is not working.
