### ISSUE TITLE
missing nf-weblog process signals

### ISSUE THREAD

**Issue by tuncayseker** [nextflow-io/nextflow#4448]
## Bug report 

I opened an issue on the nf-weblog repository a couple of weeks ago (https://github.com/nextflow-io/nf-weblog/issues/6). I also wanted to reopen the issue here in case it was overlooked. 

### Expected behavior and actual behavior

As mentioned in the nf-weblog issue, after the 23.06-edge release (latest working release without missing signals), process start/completed signals are not received. 

### Steps to reproduce the problem

logging all the incoming signals in the http-endpoint

### Program output 

-

### Environment 

* Nextflow version: >23.06.0-edge
* Java version: OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
* Operating system: Linux
* Bash version: 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

-

**Comment by bentsherman** [comment]
This issue was [fixed](https://github.com/nextflow-io/nextflow/commit/07582f0b7361745e5ef100598a189c881a033062) in 23.09.0-edge
