### ISSUE TITLE
Error reporting: Catch empty `fromPath` call

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#4453]
Could we capture channel factories that are used without any arguments, giving a nice error message to the end user? For example:

```nextflow
myfile = Channel.fromPath()
println(myfile | view)
```

```console
❯ nextflow run main.nf
N E X T F L O W  ~  version 23.10.0
Launching `main.nf` [festering_chandrasekhar] DSL2 - revision: 428da3dec1
ERROR ~ Could not find which method fromPath() to invoke from this list:
  public static groovyx.gpars.dataflow.DataflowWriteChannel nextflow.Channel#fromPath(java.lang.Object)
  public static groovyx.gpars.dataflow.DataflowWriteChannel nextflow.Channel#fromPath(java.util.Map, java.lang.Object)

 -- Check script 'main.nf' at line: 1 or see '.nextflow.log' file for more details
```

**Comment by pditommaso** [comment]
Not sure this was the problem reported on Slack.

**Comment by pditommaso** [comment]
I think the example should be 


```
Channel.fromPath(null)
```

After #4454 now reports the following  


```
Missing `fromPath` parameter -- Check script 'test.nf' at line: 1 or see '.nextflow.log' file for more details
```


Closing this

**Comment by ewels** [comment]
Not the same issue, no. That was with `null`, this issue is specifically for calling the function without any argument at all (empty brackets). I think that the two things gave a different effect.

**Comment by bentsherman** [comment]
This was not the error reported on Slack, instead it was called with a null argument. Calling with no argument already gives the error message you showed, which is specific enough IMO. It shows the channel factory and the line where the error occurred

**Comment by ewels** [comment]
Fair enough 👍🏻 

Yes they were always two separate things. The one raised by someone in the community was with `null` and when I was trying to make a minimal reproducible example I came across this one, which gave a different error message.

I wasn't saying that this one wasn't informative, just that it is not particularly user friendly. It says that something is wrong at that line, but to the majority of Nextflow developers the next step is to guess what's wrong. `Could not find which method fromPath() to invoke from this list` seems to have nothing to do with an incorrect number of arguments being given to the function.

I was wondering if it'd make an easy quick-win for error reporting (I'm on the hunt for such things).

But I agree that it's not super bad as it is, so happy to leave it as `won't-fix` 👍🏻
