### ISSUE TITLE
Support for Kubernetes persistent volumes

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#446]
Nextflow currently supports only [hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) volume type. This requires the shared file system to be mounted in the hosted environment to be accessible from the kubernetes cluster nodes. 

The goal of this enhancement is to include in nextflow the support for kubernetes [persistent volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) that allow kubernetes pods to access external storage systems. 

In this schema, the nextflow driver application should run as a pod itself, which may require to interact the kubernetes master node by using the [kubernetes api](https://kubernetes.io/docs/concepts/overview/kubernetes-api/) instead of the `kubectl` command line tool.

**Comment by pditommaso** [comment]
cc @aunderwo

**Comment by pditommaso** [comment]
Anybody interested in this feature managed to configure a kubernetes persistent volume using the macOS NFS daemon  ?

**Comment by pditommaso** [comment]
cc @wikiselev @theobarberbany @tdudgeon

**Comment by tdudgeon** [comment]
Using a NFS backed PV yes!
I don't understand the 'macOS NFS daemon' part of this.
And really, NF should really only worry about the PVC, not how they are implemented as PVs.

**Comment by pditommaso** [comment]
> I don't understand the 'macOS NFS daemon' part of this.

I'm struggling to configure K8s (included with Docker for Mac) to mount a folder shared via the Mac NFS server for testing purpose. Tried also a couple of server running in container, no luck :/

> And really, NF should really only worry about the PVC

I agree

**Comment by wikiselev** [comment]
It would be very useful for testing purposes, but if it's too hard to implement I am OK not to have it. Thanks for asking!

**Comment by pditommaso** [comment]
Requires: #468
