### ISSUE TITLE
Feature request: Publish files only when workflow successful

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#4460]
The default Nextflow behaviour is to publish results via `publishDir` as the workflow runs, after each completed task. This generally works great, however one side effect is that if a workflow fails a half-filled results directory is left. This must typically be manually removed before re-running the pipeline, to be completely sure of purely valid results at the end of the completed run.

This issue is to suggest a configurable opt-in option to only _start_ publishing results files at the end of the workflow, when the successful status of the pipeline is guaranteed. This way, if anything goes wrong during execution, no files will be published at all.

Doing this has several downsides, most notably that the publishing is no longer async and parallelised with execution, so may add a significant run-time cost to pipeline runs. However, it may be a compromise worth making in some use cases.

**Comment by pditommaso** [comment]
We cannot do this, a pipeline can produce terabytes of data, postponing at the end it can add hours to the overall execution

**Comment by MattNVstorey** [comment]
It's a common pattern I have seen requested where results are staged and then moved on completion, even on pipelines that produce many terabytes of data. The bandwidth between buckets alleviates this somewhat. This is quite difficult to do with Nextflow (AFAICT) without doing something that feels a bit hacky. Hopefully I'm missing something. Would a lack of a feature to achieve this alienate some of the users that might want to use this in large production/automated systems.

**Comment by bentsherman** [comment]
Related to #3372 

I think the solution we intend to implement is to verify the checksum of a published file to decide whether it needs to be updated. Currently, if the published file merely exists then it will not be re-published, which causes problems when a workflow fails and file publishing is halted abruptly. But if we verify the checksum then the successful retry will overwrite any corrupted files.

**Comment by ewels** [comment]
Yes, on production systems having published data from pipelines that exited in an error state can be a major problem. Having a mixture of valid and invalid results from a resumed workflow could be even worse.

My strong suspicion is that people are _already_ doing this manually, as @MattNVstorey says. So adding hours to the end of the execution is not really a problem in this context. Those hours are already being spent by these users, just in a more complicated manner in custom wrapper scripts around Nextflow with a bunch of wasted data duplication (triplicate: work - staging publish - final manual publish).

I'm definitely not saying that this should be default behaviour.

> But if we verify the checksum then the successful retry will overwrite any corrupted files.

This is a step in the right direction, but it still doesn't resolve two problems:

* Files that shouldn't be there - not part of the second run at all, remnants of faulty run number 1
* Aborted runs with no resume, where we simply want nothing published at all

**Comment by bentsherman** [comment]
What if, instead of waiting to publish files, we add an option to delete all published files if the workflow fails? Actually if you know all the results will be in a single directory (i.e. all nf-core pipelines) you could just add an `onError` handler to delete `params.outdir`. Nextflow just needs to shutdown the publisher before calling the onError handler.

**Comment by ewels** [comment]
That could definitely work 👍🏻  Especially as re-running with `-resume` should publish all files from cached tasks again.

Presumably this will mean that resuming workflows won't work with the new clean-workdirs-as-you-go approach currently being developed? That's probably fine if the end user can opt into either one or the other, but something to bear in mind.

**Comment by pditommaso** [comment]
I am not keen to change this logic, also, deleting files can add a lot of pain over object storage. it's user responsibility to delete them on resume if they think it may be necessary (which in my opening is a very rare condition)

**Comment by bentsherman** [comment]
As a practical matter, my proposed solution can be implemented in the pipeline code:

```groovy
workflow.onError {
  file(params.outdir).deleteDir()
}
```

So users can just do this if they want this behavior

**Comment by ewels** [comment]
Ok, moving to a new issue for the @nf-core template then 👍🏻

**Comment by pditommaso** [comment]
I still argue this should not be done, not even in the pipeline code. It will add a huge delay on pipeline completion for cloud users, resulting in extra costs both for compute and object storage API requests.

**Comment by ewels** [comment]
I guess my point for adding is that people are already doing this, or worse versions of this. Having _all_ pipeline runs output to a staging directory and then copying those results only when the pipeline finishes successfully is slower and more expensive. Doing this only when pipelines fail (hopefully rarely) should be better on most counts ☝🏻 

I don't particularly like it either and it would be an opt-in thing with various warnings in place. But given that it'd be about 4 lines of code it seems like a nice utility for people who want it.

This came out of a single Slack discussion thread (which I can't find now) and I don't have any hard numbers on _how many_ people care about this level of output files trust. So if consensus is that this is too detrimental and not needed then I'm happy to not add it.

**Comment by SPPearce** [comment]
Just to give some perspective from a user. 

> Yes, on production systems having published data from pipelines that exited in an error state can be a major problem. Having a mixture of valid and invalid results from a resumed workflow could be even worse.

Absolutely, this is it. I run pipelines and deposit the (subset of the) results into a set location. Sometimes we rerun the pipeline because of a sample naming issue for instance (say sampleA needs to be renamed as sampleB), and then the results would include bam files called both sampleA and sampleB. This becomes very confusing downstream.

> My strong suspicion is that people are _already_ doing this manually, as @MattNVstorey says. So adding hours to the end of the execution is not really a problem in this context. Those hours are already being spent by these users, just in a more complicated manner in custom wrapper scripts around Nextflow with a bunch of wasted data duplication (triplicate: work - staging publish - final manual publish).

I currently make the files in the scratch directory (local HPC) and then copy that folder over once the workflow is successful. With a very ugly bash script.

> This is a step in the right direction, but it still doesn't resolve two problems:
> 
> * Files that shouldn't be there - not part of the second run at all, remnants of faulty run number 1
> * Aborted runs with no resume, where we simply want nothing published at all

Yes, I also really don't want folders with aborted junk in (often just the very first process directory where it has checked the sample sheet and discovered an error immediately).

**Comment by pditommaso** [comment]
> it would be an opt-in thing with various warnings in place

Makes sense 👍

**Comment by AugustDev** [comment]
I also do this manually, wish proper solution exists
