### ISSUE TITLE
Add `compress` and `decompress` to operators/channel factories

### ISSUE THREAD

**Issue by iferres** [nextflow-io/nextflow#4473]
## New feature

To avoid verbosity in the code, I was wondering if a method to decompress `.gz` files could be added. Already works for `splitXXX()` operators.

## Usage scenario 

Users could stage input files automatically in the format (compressed/uncompressed) required without the need to implement a `process (de)compress{ ... }`, or a complex script inside a process. 

## Suggest implementation 

One possible implementation would be:
```nextflow
myFile = Channel.fromPath("https://url/to/compressed/file.gz", decompress = true)
```

Another option could be:
```nextflow
myFile = Channel.fromPath("https://url/to/compressed/file.gz")
   .decompress()
```

A third option could be:
```nextflow
process myProcess {

   input:
   path(myinputfile, decompress = true)

   ...

}

**Comment by bentsherman** [comment]
I prefer not to do this because the decompression would be performed on the head node. Much better IMO to perform the decompression in a process

**Comment by iferres** [comment]
Ah, I see... The only one I could make sense is something like the third option, but for some reason is the one I dislike the most. Probably because each instance with the same input would gunzip it, and the use case I was thinking was downloading/staging a database file and stream it to many instances/tasks. 
Thanks for your time @bentsherman !

**Comment by bentsherman** [comment]
You could have a separate process to decompress the file and then feed the decompressed output to downstream tasks, if you want to eliminate the duplicate work

**Comment by iferres** [comment]
Yes, of course. That's what I was doing. I just thought a native nextflow implementation, such as in splitXXX() operators, would be a good idea, but you made a very valid point against it.
Bests!
