### ISSUE TITLE
Add `preview` to workflow runtime metadata

### ISSUE THREAD

**Issue by kelly-sovacool** [nextflow-io/nextflow#4478]
## New feature

The `workflow` object has many useful properties, such as `stubRun` to indicate whether the workflow was invoked with the `-stub`/`-stub-run` CLI option. Similarly, it would be useful to access whether `-preview` was used.

## Usage scenario 

This is especially useful in the `onComplete` handler, e.g. to only send an email notification for "real" pipeline runs.

```nextflow
workflow.onComplete {
    if (!workflow.stubRun && !workflow.preview) {
        sendMail(...)
    }
}
```

## Suggest implementation 

Similar logic could be re-used from the other metadata that's populated from the CLI.

**Comment by greenberga** [comment]
If it's okay, I'll take a crack at this feature!
