### ISSUE TITLE
Add gzip (de)compression support to the `collectFile` operator

### ISSUE THREAD

**Issue by maxibor** [nextflow-io/nextflow#4479]
## New feature

This is a reopening of #3071 that has been closed by the stale bot

## Usage scenario 

Collect (de)compressed files (https://github.com/nextflow-io/nextflow/issues/2550) and/or (de)compress the emitted collected file(s).
Right now, this requires to have a dedicated process after a `.collect()` just to `gunzip` and `cat` 

## Suggest implementation 

See https://github.com/nextflow-io/nextflow/issues/484

**Comment by bentsherman** [comment]
Thanks, I will just re-open the old issue to keep the discussion in one place

**Comment by maxibor** [comment]
Hey @bentsherman 
That's what I wanted to do, but you have powers that I do not posses ;)
