### ISSUE TITLE
Nextflow fails to download commons-codec:jar:1.9

### ISSUE THREAD

**Issue by oscarnyangiri** [nextflow-io/nextflow#449]
I am using Nextflow version 0.25.7 with docker to run the analysis described here https://github.com/h3abionet/h3agwas/wiki/Quick-Start
The command is:
nextflow run plink-qc.nf -profile docker

It downloads several files and then fails at commons-codec:jar:1.9 with the following error message:

```
CAPSULE: Downloading dependency commons-codec:commons-codec:jar:1.9
CAPSULE: Transfer failed: capsule.org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact commons-codec:commons-codec:jar:1.9 from/to central (https://repo1.maven.org/maven2/): Range Not Satisfiable (416) (for stack trace, run with -Dcapsule.log=verbose)
CAPSULE EXCEPTION: Error resolving dependencies. while processing attribute Allow-Snapshots: false (for stack trace, run with -Dcapsule.log=verbose)
Unable to initialize nextflow environment
```

My java version details are
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

Has anyone else come across this and what could the solution? Thanks

**Comment by pditommaso** [comment]
I'm unable to replicate this issue. This is likely connection hiccup or transient Maven issue.

**Comment by pditommaso** [comment]
If you are continuing to experience this problem feel free to comment here.
