### ISSUE TITLE
Durations are limited to 32 bits

### ISSUE THREAD

**Issue by muffato** [nextflow-io/nextflow#4495]
## Bug report 

On my HPC, the maximum runtime is 30 days. When setting `params.max_time` of a nf-core pipeline to `30.d` (or `720.h`), Nextflow reports `max_time` to actually be "24d 20h 31m 24s", which I've noticed is 2,147,484,000 (almost exactly 2^31) milliseconds.

### Expected behavior and actual behavior

I'd expect `max_time` to be internally set to whatever value I give it, including values > 2^31 milliseconds.

### Steps to reproduce the problem

```console
$ cat main.nf
params.max_time = 720.h
println params.max_time;
```

### Program output 

```console
$ nextflow run .
N E X T F L O W  ~  version 22.04.0
Launching `./main.nf` [marvelous_golick] DSL2 - revision: ada822a0ee
24d 20h 31m 24s
```

### Environment 

* Nextflow version: Tested on 22.04.0-5697 and 23.10.0-5889
* Java version: openjdk 11.0.16.1
* Operating system: Ubuntu 18.04.6
* Bash version: 4.4.20

**Comment by bentsherman** [comment]
That is perplexing, because the underlying millis value used by durations is a long: https://github.com/nextflow-io/nextflow/blob/d49f02aeb4c44287f64b2df7a5d25a5a073581f8/modules/nf-commons/src/main/nextflow/util/Duration.groovy#L61-L64

Which should always be 64-bit. I assume you are using a 64-bit JVM?

Can you try specifying the duration directly in millis as a long? If that works then it would suggest that the parsing code is using a 32-bit integer somewhere along the line.

**Comment by muffato** [comment]
Yes, my JVM is 64 bits
```
openjdk 11.0.16.1 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+23-CA (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+23-CA (build 11.0.16.1+1-LTS, mixed mode)
```

Same error when setting `max_time` to `3000000000.ms`

**Comment by bentsherman** [comment]
Try it without the suffix: `max_time = 3000000000`

**Comment by muffato** [comment]
Without the suffix, it prints the entire number (3000000000) but there's no unit associated with it, no "Duration" object.

Interestingly, casting as a Duration works
```
params.max_time = 3000000000 as nextflow.util.Duration

$ nextflow run .
N E X T F L O W  ~  version 23.10.0
Launching `./main.nf` [high_laplace] DSL2 - revision: 217d243514
34d 17h 20m
```

**Comment by muffato** [comment]
@bentsherman I think the issue is that Java rounds _double_ as _long_ (https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#round-double-) but _float_ as _int_ (https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#round-float-).

The conversion sub-routine https://github.com/nextflow-io/nextflow/blob/d49f02aeb4c44287f64b2df7a5d25a5a073581f8/modules/nf-commons/src/main/nextflow/util/Duration.groovy#L169-L188 takes a float, therefore `Math.round` makes an _int_ that is then cast as a _long_ but it's too late at this stage.

**Comment by bentsherman** [comment]
You were spot on! PR submitted

**Comment by muffato** [comment]
Thank you very much !
