### ISSUE TITLE
Update support for Singularity 4 - bound to 4.0.2 release

### ISSUE THREAD

**Issue by marcodelapierre** [nextflow-io/nextflow#4506]
We got the Sylabs devs to fix a bug that prevented mouting FUSE devices in OCI mode, see https://github.com/seqeralabs/fusion/issues/288 by @pditommaso  and @jordeu .

TIMELINE for ACTION: when bugfix relase 4.0.2 is released (likely in the week starting 13 November), keep an eye on :

https://github.com/sylabs/singularity/releases

ACTION: Nextflow needs to also add `-B /dev/fuse` when is adding `--oci`.

**Comment by marcodelapierre** [comment]
@pditommaso  is this the correct way to test?
(From https://github.com/seqeralabs/fusion/issues/288)

```
container=$(wave -i ubuntu --freeze --build-repo docker.io/pditommaso/wave-demo --config-file https://fusionfs.seqera.io/releases/v2.2.9-amd64.json  --await)

singularity exec -B /scratch:/tmp --oci docker://$container /usr/bin/fusion ls -la /fusion/s3/nextflow-ci/
```

At the moment I still don't have my own local build of `wave`, so I am starting with posting the process to install the latest Singularity on a Ubuntu box:
```
#!/bin/bash

singularity_ver="4.0.2"

sudo apt update
sudo apt install -y \
   cryptsetup \
   libfuse-dev \
   libglib2.0-dev \
   libseccomp-dev \
   libtool \
   pkg-config \
   runc \
   squashfs-tools \
   squashfs-tools-ng \
   uidmap \
   zlib1g-dev

singularity_deb_file="singularity-ce_${singularity_ver}-jammy_amd64.deb"
wget https://github.com/sylabs/singularity/releases/download/v${singularity_ver}/${singularity_deb_file}
sudo apt install ./${singularity_deb_file}
rm ${singularity_deb_file}
```

**Comment by jordeu** [comment]
You must add `-B /dev/fuse`, without it won't work.

**Comment by jordeu** [comment]
Also I recommend to try to list a public S3 bucket, in this way you don't need to care about permissions.

```
singularity exec -B /scratch:/tmp -B /dev/fuse --oci docker://$container /usr/bin/fusion ls -la /fusion/s3/ngi-igenomes/
```

**Comment by marcodelapierre** [comment]
Thanks Jordi, will do!

@pditommaso now that I realise, all I need to test myself is a way to access a container created via:
```
wave -i ubuntu --freeze --build-repo docker.io/pditommaso/wave-demo --config-file https://fusionfs.seqera.io/releases/v2.2.9-amd64.json  --await
```

would you be able to provide me with it?

**Comment by pditommaso** [comment]
It should be tested via nextflow using [this PR](https://github.com/nextflow-io/nextflow/pull/4508). 

1. change in that branch 
2. `make compile`
3. add `fusion.oci = true` in the nextflow config 
4. run `./launch.sh run hello -w s3://something/work`

**Comment by pditommaso** [comment]
Tested. Works as expected using Singularity 4.0.2
