### ISSUE TITLE
subworkflow input not converted to Channel

### ISSUE THREAD

**Issue by mcolpus** [nextflow-io/nextflow#4507]
## Bug report 

In the documentation (https://www.nextflow.io/docs/latest/workflow.html#workflow-inputs) It says that basic datatypes provided as inputs to a workflow get converted to Channels. However, in my test this doesn't happen.

### Expected behavior and actual behavior

I expected the input to be a Value Channel, but instead it stays as a basic value.

### Steps to reproduce the problem

```
workflow subworkflow {
    take:
    input

    main:
    print(input)
    print(input.getClass())
}

workflow {
    subworkflow(1)
}
```

And run `nextflow test.nf`

### Program output 

```
N E X T F L O W  ~  version 23.10.0
Launching `test.nf` [infallible_maxwell] DSL2 - revision: 40327dc6c0
1
class java.lang.Integer
```

### Environment 

* Nextflow version: 23.0.0
* Java version: 11.0.20.1
* Operating system:  Linux
* Bash version: GNU bash, version 5.1.16

**Comment by bentsherman** [comment]
I believe you are right, from the code it seems that the conversion to value channel only happens at the boundary of process inputs, not workflow inputs. I will submit a PR
