### ISSUE TITLE
Add option to disable google batch vm price query

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#4520]
Google Batch queries `cloudinfo.seqera.io` to fetch VM prices in order to try and find an optimal machine type for the task requirements. While it can always fall back to the default behavior in the event of an error, it can cause delays if Nextflow does not have access to the public internet (e.g. a locked-down enterprise environment).

https://github.com/nextflow-io/nextflow/blob/82e56799654eab43f37fb41ada579b34637f56f6/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchMachineTypeSelector.groovy#L144-L164

We should add a config option to disable this logic, and maybe also disable it automatically if `NXF_OFFLINE` is enabled.

**Comment by pditommaso** [comment]
Use Google batch with `NXF_OFFLINE` 😕 ?

**Comment by bentsherman** [comment]
Another possible solution is to bypass the price query if the cpus and memory are already specified: https://github.com/nextflow-io/nextflow/blob/82e56799654eab43f37fb41ada579b34637f56f6/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchMachineTypeSelector.groovy#L98-L101

**Comment by pditommaso** [comment]
Since it's `@Memoized` it should have a negligible overhead. From where this issue is arising?

**Comment by bentsherman** [comment]
Customer in a locked-down GCP environment. If an exception is thrown in a memoized method, is the exception result also cached?
