### ISSUE TITLE
Docker enabled is failing if the directory contains special characters

### ISSUE THREAD

**Issue by markpanganiban** [nextflow-io/nextflow#4572]
## Bug report 

Customer reported issue. 
Nextflow docker-enabled run encounters an error when the directory used contains special characters.

### Steps to reproduce the problem

To replicate:
1. Clone the project https://github.com/cjw85/wf-fun-times
2. `cd wf-fun-times/fun\(\)times/`
3. `nextflow run main.nf -with-docker ubuntu`

### Program output 

```
ubuntu@ip-x:~/nf/wf-fun-times/fun()times$ ~/nf/nextflow run main.nf
N E X T F L O W  ~  version 23.10.0
Launching `main.nf` [admiring_pare] DSL2 - revision: c64afdbebf
executor >  local (1)
[74/739307] process > echoStuff [100%] 1 of 1 ✔
/home/ubuntu/nf/wf-fun-times/fun()times/work/74/739307ec8921c28e1d55b21ce8fe4c/stuff.txt

ubuntu@ip-x:~/nf/wf-fun-times/fun()times$ ~/nf/nextflow run main.nf -with-docker ubuntu
N E X T F L O W  ~  version 23.10.0
Launching `main.nf` [fervent_franklin] DSL2 - revision: c64afdbebf
executor >  local (1)
[5f/09d425] process > echoStuff [100%] 1 of 1, failed: 1 ✘
ERROR ~ Error executing process > 'echoStuff'

Caused by:
  Process `echoStuff` terminated with an error exit status (127)

Command executed:

  echo.sh > stuff.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: echo.sh: command not found

Work dir:
  /home/ubuntu/nf/wf-fun-times/fun()times/work/5f/09d4257c29b2256c3071f47749d930

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

### Environment 

* Nextflow version: 23.10.0
* Java version: 17.0.6-tem
* Operating system: Ubuntu
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
@bentsherman any progress on this? it would be nice to close asap

**Comment by bentsherman** [comment]
Gonna try to close today

**Comment by pditommaso** [comment]
Hi @cjw85, we have found a workaround for parenthesis, but it looks trickier for blank and other special chars. 

Would a fix for `()` be enough for you?

**Comment by cjw85** [comment]
The precise case we had from an end-user was a path that had both spaces and parentheses 😬 .

@samstudio8 and I came to the conclusion the use of `eval` in `nxf_launch()` was dubious; the root cause being the line endings of `nxf_container_env()` needing to be escaped for that to work. Would it be simpler/less error prone to prepend `.command.sh` with the exports required?

**Comment by pditommaso** [comment]
The problem is that the command script is expected to be interpreted as declared by the shebang header declaration e.g. `#!/bin/env python` and therefore the variables cannot be prepended there

**Comment by pditommaso** [comment]
Solved via https://github.com/nextflow-io/nextflow/pull/4594
