### ISSUE TITLE
The pipeline DAG file cannot be open with the browser

### ISSUE THREAD

**Issue by 0820LL** [nextflow-io/nextflow#4590]
## Bug report 

As shown below, there is a bug when opening the 'pipeline_dag.html' file. I ran the ranseq locally with the singularity and got this DAG file.
![image](https://github.com/nextflow-io/nextflow/assets/7429457/fd581c2d-ea66-46a7-9335-657eb8532ff2)

Here is the DAG file which has been compressed.
[pipeline_dag_2023-12-14_10-29-12.zip](https://github.com/nextflow-io/nextflow/files/13683182/pipeline_dag_2023-12-14_10-29-12.zip)

**Comment by bentsherman** [comment]
The problem seems to be that there are too many edges, but the Mermaid error isn't very informative. The default limit is 500, but you can increase the limit by modifying the HTML file:
```javascript
  mermaid.initialize({ startOnLoad: true, maxEdges: 1000 });
```

For what it's worth, I usually enable these settings with rnaseq to make it less verbose:

```groovy
dag {
    depth = 2
    verbose = true
}
```

**Comment by bentsherman** [comment]
Sorry, that should be `verbose = false`

**Comment by marcodelapierre** [comment]
I trust Ben's suggestion on the extra `dag` config options are addressing this issue. Closing.
