### ISSUE TITLE
Do not limit retries for re-sumbissions with maxErrors

### ISSUE THREAD

**Issue by manuelesimi** [nextflow-io/nextflow#46]
Currently, if maxErrors is set to a value lesser than maxRetries, only up to maxErrrors re-submissions are attempted for a process. From a user's perspective, this is a bit confusing, especially if only maxRetries is set and maxErrors is left to its default value (1). maxErrors should not limit the number of possible resubmissions. 

From outside the box, I see to alternative ways to go:

1. a conventional value (e.g. -1) for maxErrors that tells nextflow to ignore the errors limit. The risk with this option is that a process execution could go on forever with re-submissions. To avoid that, it should be allowed only when maxRetries is also set.

2. when maxRetries is set, maxErrors is ignored, regardless its value. This could be seen as a sort of priority between them. The drawback is that the maximum number of re-submission is determined by maxRetries * number of execution instances.

**Comment by pditommaso** [comment]
I think the first alternative is the best one. Indeed, `maxErrors` should be by default `-1` so it does not check the errors upper limit. 

Also `maxRetries` should by default `1`, in this way the same task can be re-execute only one time, and it's coherent with the re-try semantic. 

Then a user to both `maxErrors` and `maxRetries` to tune the error strategy depending its requirements.

**Comment by pditommaso** [comment]
Now  it is possible to set `maxErrors` to `-1` to ignore it. However the default has not changed.
