### ISSUE TITLE
Channels not isolated between scatter subworkflows

### ISSUE THREAD

**Issue by xubofei1983** [nextflow-io/nextflow#4607]
## Bug report 

```
process chunk_reads {
  input:
  val(msg)

  output:
  path "chunk_nums"

  script:
  """
  echo "$msg" > chunk_nums
  """
}


workflow subworkflow {
  take:
  input_ch

  main:

  chunks = chunk_reads(input_ch).splitJson()

  input_ch.combine(chunks).view()

}

workflow {
  input_ch = Channel.of( "[1]", "[1, 2]")

  subworkflow(input_ch)
}
```

when I give input_ch = Channel.of( "[1]")
output is 
[[1], 1]

when I give input_ch = Channel.of( "[1, 2]")
output is 
[[1, 2], 1]
[[1, 2], 2]

However when I give input_ch = Channel.of( "[1]", "[1, 2]")
[[1], 1]
[[1, 2], 1]
[[1], 1]
[[1, 2], 1]
[[1], 2]
[[1, 2], 2]

### Expected behavior and actual behavior

I would assume subworkflow execution should not impact each other. So
When I give Channel.of( "[1]", "[1, 2]"),  the result should be the addition of Channel.of( "[1]") and Channel.of( "[1, 2]")
[[1], 1]
[[1, 2], 1]
[[1, 2], 2]

### Steps to reproduce the problem

Run above script.

### Program output 

N E X T F L O W  ~  version 23.09.2-edge
Launching `random_test.nf` [confident_albattani] DSL2 - revision: c025b68775
executor >  local (2)
[d8/64a019] process > subworkflow:chunk_reads (2) [100%] 2 of 2 ✔
[[1], 1]
[[1, 2], 1]
[[1], 1]
[[1, 2], 1]
[[1], 2]
[[1, 2], 2]

### Environment 

* Nextflow version: [23.09.2-edge] 
* Java version: [openjdk 11.0.14.1]
* Operating system: [macOS]
* Bash version: (use the command `$SHELL --version`) zsh 5.9 (x86_64-apple-darwin23.0)
* 

### Additional context

(Add any other context about the problem here)

**Comment by robsyme** [comment]
I think the confusion here stems from the behaviour of the `splitJson` operator.

Unless I've misunderstood the question, the same behaviour happens without adding any subworkflows. Would you agree that this simpler example has the same behaviour?

```groovy
process chunk_reads {
    input: val(msg)
    output: path "chunk_nums"
    script: "echo '$msg' > chunk_nums"
}

workflow {
    input_ch = Channel.of("[1]", "[1, 2]")
    chunks = chunk_reads(input_ch).splitJson()
    input_ch.combine(chunks).view()
}
```

**Comment by robsyme** [comment]
In this workflow, the `input_ch` contains two items (two strings to be specific):
- `'[1]'`
- `'[1, 2]'`

The `chunks` channel contains three items (three strings):
- `'1'`
- `'1'`
- `'2'`

When you call the `combine` operator with `input_ch.combine(chunks)`, we get the cartesian product of the two channels. I.e. the first item from `input_ch` (`'[1]'`) emitted with each of the three items from the `chunks` channel, and the second item from `input_ch` (`'[1, 2]'`) emitted with each of the three items from the `chunks` channel. This gives the expected result of six items:

```
[[1], 1]
[[1, 2], 1]
[[1], 1]
[[1, 2], 1]
[[1], 2]
[[1, 2], 2]
```


I think what you are looking for is something like:


```groovy
workflow {
    Channel.of("[1]", "[1, 2]")
    | flatMap { jsonString ->
        array = new JsonSlurper().parseText(jsonString)
        array.collect { [array, it] }
    }
    | view
}
```

... which gives

```
[[1], 1]
[[1, 2], 1]
[[1, 2], 2]
```

**Comment by xubofei1983** [comment]
Thanks @robsyme , I understand your simplified version.   The example is just a simplified version to discuss.  the real `subworkflow` is much more complicated and suppose to be resuable.

This issue really confuses me is the channel in different execution of subworkflow are somehow merged. which is weird.

look at the main workflow
```
input_ch = Channel.of( "[1]", "[1, 2]")

subworkflow(input_ch)
```

The natural understanding to me is that  the running of  ("[1]", "[1, 2]" )  should be two independent execution of ("[1]") and ("[1, 2]" ) ,  and the result should be the simply append them of the two execution, not a product.

**Comment by xubofei1983** [comment]
And do you have an walk-around on the subworkflow level?

**Comment by robsyme** [comment]
When you use the `combine` operator, you are generating the product of the two channels. The [documentation](https://www.nextflow.io/docs/latest/operator.html#combine) for the `combine` operator leads with

> The combine operator combines (cartesian product) the items emitted by two channels

**Comment by robsyme** [comment]
You can use my example in a sub workflow in exactly the same manner:


```groovy
workflow subworkflow {
    take: 
    input_ch

    main:
    input_ch
    | flatMap { jsonString ->
        array = new JsonSlurper().parseText(jsonString)
        array.collect { [array, it] }
    }
    | view
}

workflow {
    input_ch = Channel.of("[1]", "[1, 2]")

    input_ch | subworkflow
}
```

**Comment by xubofei1983** [comment]
yes but  I think it should combine the channels within the subworkflow execution.

My understanding is there should be two subworkflow execution:

first execution of subworkflow: 
 input_ch  = “1”
chunks should be [1]
input_ch.combine(chunks)  should be [[1], 1]


second execution of subworkflow: 
input_ch  = "[1, 2]"
chunks should be [1, 2]
input_ch.combine(chunks)  should be
[[1, 2], 1]
[[1, 2], 2]

Why would the 'combine' product data in channels from different executions?

**Comment by xubofei1983** [comment]
in another word, how can I define a `local` channel with scope only within a subworkflow execution.

**Comment by robsyme** [comment]
The sub workflow is not a function called independently for each element in the channel. There is one invocation of the subworkflow and it passed the channel of elements.

If you need to perform an operation on each element in the channel independent of other items in the channel, you might use the `map` or `flatMap` operators. You can also pass the channel to a process, where a task is invoked for each element in the channel (independently and in parallel where possible).

**Comment by xubofei1983** [comment]
@robsyme, again, I need the "chunk_reads" process, not only for generate a list from input,  the real process take some input data and split them into chunks, it output  this "[1,2,3 ... n]" arbitrarily.   So I need to get this from the output channel of the task.  and for each of them I need pass the combined input params and the chunk index to the next job.


In real example, when I test the subworkflow alone,  with one input sample a time, it works fine.  

However, when I give a list of samples into this subworkflow. it breaks.

**Comment by robsyme** [comment]
I don't think this is a bug - Nextflow is behaving as documented. 

I'm not entirely sure if I understand your description, but this might be what you're looking for:

Let's say you have a channel of "parameter groups":

```nextflow
paramGroups = Channel.of([1], [4], [1,3])
```
which produces a channel with contents:
```
[1]
[4]
[1, 3]
```

We can pass these through a flatMap operator to pull out each element, but we also include the original paramGroup so that we can know which group each element came from:

```nextflow
flatMap { myParams ->  myParams.collect { [it, myParams] } }
```
to produce a channel with contents
```
[1, [1]]
[4, [4]]
[1, [1, 3]]
[3, [1, 3]]
```

Then we can pass this to a process `chunk_reads` which produces a list of files depending on the parameter:

```nextflow
process chunk_reads {
    input: tuple val(singleParam), val(paramGroup)
    output: tuple val(paramGroup), path("*.dat")

    """
    for i in `seq 1 $singleParam`; do
        touch out.\$i.dat
    done
    """
}
```

Passing our channel into this process:
```nextflow
paramGroups
| flatMap { myParams ->  myParams.collect { [it, myParams] } }
| chunk_reads
| view
```
Returns a channel
```
[[1], out.1.dat]
[[1, 3], out.1.dat]
[[1, 3], [out.1.dat, out.2.dat, out.3.dat]]
[[4], [out.1.dat, out.2.dat, out.3.dat, out.4.dat]]
```

Lastly, you may want to make a channel where each of these "dat" files are processed in parallel, but you also want to keep track of the original parameter group. The solution to this problem is shown in the full example below:

```nextflow
process chunk_reads {
    input: tuple val(singleParam), val(paramGroup)
    output: tuple val(paramGroup), path("*.dat")

    """
    for i in `seq 1 $singleParam`; do
        touch out.\$i.dat
    done
    """
}

workflow {
    paramGroups = Channel.of([1], [4], [1,3])

    paramGroups
    | flatMap { myParams ->  myParams.collect { [it, myParams] } }
    | chunk_reads
    | flatMap { paramGroup, datFiles -> 
        datFiles instanceof List
            ? datFiles.collect { file -> [paramGroup, file] } 
            : [[paramGroup, datFiles]]
    }
    | view
}
```

Considering that this is not a Nextflow bug, I'm going to close this issue. If you have other questions about the behaviour of Nextflow, can you ask the question at either:
- The "Nextflow" category at https://community.seqera.io, or
- The #help channel on the [Nextflow slack](https://www.nextflow.io/slack-invite.html).

**Comment by xubofei1983** [comment]
Thanks @robsyme ,  I found a walk-around inspired from your examples.

But I still feel the model of subworkflow in nextflow is not sound.

Let's forget about the detailed implementation of the subworkflow, but look from high-level composition.

From functional programing.
given:
F(a) = r1
F(b) = r2
we should always get
F([a, b]) = [r1, r2]

However, let's denote W for the subworkflow in my example.

W(a) = r1
W(b) = r2
However, 
W([a, b]) != [r1, r2]

**Comment by robsyme** [comment]
Hi Xubo

I'm sorry that my explanation was not sufficiently clear. 

Your subworkflow takes a channels as input. In using `combine` operator, you are explicitly making the elements in the channel interact with each other.

Keep in mind that the subworkflow is given a _channel_ as input. A subworkflow is _not_ a function that is called independently for each element in the channel.

In your example, you say that given
```
F(a) = r1
F(b) = r2
```
that "we should always get"
```
F([a, b]) = [r1, r2]
```

But let's say that function `F` takes the total of the inputs and then returns a new channel where the inputs are added to the total. In pseudocode you might write:
```
def F(inputs):
  total = inputs.sum()
  return inputs.map { element -> element + total }
```

This `F` breaks your assumption that "we should always get" `F([a, b]) = [r1, r2]`. For example, 
 - `F([1])` would return a channel that contains one element, the value 20: `F([1]) = [2]`
 - `F([10])` would return a channel that contains one element, the value 20: `F([10]) = [20]`
 ... but
 - `F([1,10])` would return a channel with two elements, 12 and 21: `F([1, 10]) = [12, 21]` and _not_ `[2, 20]`

Does that make sense?
