### ISSUE TITLE
Hybrid local and azurebatch executor not working

### ISSUE THREAD

**Issue by raylim** [nextflow-io/nextflow#4616]
### Expected behavior and actual behavior

local task should run locally and stage output files to cloud, but instead error occurs.

### Steps to reproduce the problem

Any workflow that has both a local task and an azurebatch task

### Program output 

```
Dec-26 18:23:40.355 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Dec-26 18:23:40.359 [Task submitter] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=getSamples; work-dir=az://test/nftest/65/3faae1692e488d3d64398a44d75884
  error [nextflow.exception.ProcessUnrecoverableException]: Local executor requires the use of POSIX compatible file system — offending path: az://test/nftest/65/3faae1692e488d3d64398a44d75884
```

### Environment 

* Nextflow version: 23.10.0.5889
* Java version: openjdk version "21-internal" 2023-09-19
* Operating system: Linux
* Bash version:  4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by bentsherman** [comment]
Can you provide a minimal pipeline example that produces this error?

**Comment by raylim** [comment]
```
process GET_SAMPLES {
    executor "local"

    output:
    path "samples.csv"

    """
    touch samples.csv
    """
}


process DO_CLOUD_THING {
    executor "azurebatch"

    input:
    path samples

    output:
    path "file"

    """
    touch file
    """
}


workflow {
    GET_SAMPLES | DO_CLOUD_THING
}

**Comment by bentsherman** [comment]
Okay, the problem is that the local task is trying to use the AZ path as the work directory. You have to specify the "bucket directory" as the AZ path using the `-bucket-dir` CLI option ([docs](https://nextflow.io/docs/latest/aws.html#pipeline-execution)). The azure task will use the bucket directory as the work dir and the local task will use the default work directory (or whatever you set it to as long as it's local).

**Comment by raylim** [comment]
Thank you, that seems to do the trick. I don't think this bit of info is in the Azure-related docs.

**Comment by bentsherman** [comment]
Yes we need to document the hybrid execution more comprehensively (#2984)
