### ISSUE TITLE
Add support for Java 9

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#462]
Investigate the changes needed to support latest the latest release of Java which introduces some breaking changes with the existing code base. 

See https://docs.oracle.com/javase/9/migrate/toc.htm

**Comment by richardjdavies** [comment]
The first problem is with the version string check at https://github.com/nextflow-io/nextflow/blob/master/nextflow#L276

This works for Java 8 on Ubuntu 16.04.3 LTS:

```
$ /usr/lib/jvm/java-8-openjdk-amd64/bin/java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```

But fails for Java 9 on Ubuntu 16.04.3 LTS:

```
$ /usr/lib/jvm/java-9-openjdk-amd64/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

**Comment by richardjdavies** [comment]
The error given with Java 9 is:

```
$ wget -qO- get.nextflow.io | bash
Error: cannot find Java or it's a wrong version -- please make sure that Java 7 or higher it's installed
Note: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /usr/bin/java
 JAVA_HOME: 

```

**Comment by pditommaso** [comment]
Thanks for reporting this. We have already a branch supporting Java 9. We are planning to release along with the deprecation of Java 7 with the version following the next (around December).

**Comment by richardjdavies** [comment]
Which is the Java 9 branch, please?

**Comment by pditommaso** [comment]
Just pushed https://github.com/nextflow-io/nextflow/tree/jdk-9

**Comment by pditommaso** [comment]
Included in version `0.26.0-beta5`

**Comment by sjackman** [comment]
Nextflow 0.27.6 prints this message when run with Java 9.
```
WARN: Nextflow support for Java 9 is still in beta stage and some advanced features are not supported
WARN: It is suggested the use of Java version 8
```
Any timeline on when this warning may be removed and Java 9 fully supported?

**Comment by pditommaso** [comment]
I guess in a couple of mounts. It mainly depends when Apache Ignite will ship the support for Java 9. It is expected for upcoming 2.4 release.
