### ISSUE TITLE
Nextflow removing 0 from the start of numeric parameters

### ISSUE THREAD

**Issue by Oliver-Lorenz-dev** [nextflow-io/nextflow#4629]
## Bug report 

Hello,
I've noticed that Nextflow is removing 0s from the start of input parameters. 

I'm not sure if this is a bug or intended behaviour, but in my case the 0 before important. I can work round this if it is intended behaviour, nonetheless it would be easier if nextflow didn't remove the 0.

### Expected behavior and actual behavior

For example:
If I ran `nextflow run . --number 08` and printed out the value of `params.number` it would be 8 (not 08 as I would expect).

The same applies if I run with quotes:
`nextflow run . --number "08"`

### Steps to reproduce the problem
I've set up a toy example to reproduce the problem:

main.nf:
```
#!/usr/bin/env nextflow

workflow {
  println(params.serotype)
}
```

nextflow.config
```
params {
    serotype = ""
}

profiles {
    standard {
        process{
            executor = 'local'
        }
    }
}
```

### Program output
Run with quotes:
```
nextflow run . --serotype "08"
N E X T F L O W  ~  version 23.10.0
Launching `./main.nf` [stupefied_jang] DSL2 - revision: 59fb0f34c7
8 
```

Run without quotes:
```
nextflow run . --serotype 08
N E X T F L O W  ~  version 23.10.0
Launching `./main.nf` [cheeky_planck] DSL2 - revision: 59fb0f34c7
8
```

### Environment 

* Nextflow version: 23.10.0 
* Java version: 11.0.18
* Operating system: Linux
* Bash version: 4.4.20

**Comment by bentsherman** [comment]
You can disable the type casting of CLI params with this environment variable: `NXF_DISABLE_PARAMS_TYPE_DETECTION` ([docs](https://nextflow.io/docs/latest/config.html#environment-variables)). It will simply parse every CLI param as a string and then you can type cast them as you see fit.

**Comment by Oliver-Lorenz-dev** [comment]
Thanks for your help @bentsherman , that's done the trick!
