### ISSUE TITLE
missing commas in output declaration leads to false error message

### ISSUE THREAD

**Issue by sbthandras** [nextflow-io/nextflow#4631]
### Expected behavior and actual behavior

Give an error message about the missing commas between process outputs 

### Steps to reproduce the problem

tuple val(sample_id), path("${sample_id}_report.tsv") path("${sample_id}_report.html")

NOTE: there is no comma between the second and third outputs 

### Program output 
"nextflow.exception.DuplicateProcessInvocation: Process 'QUAST' has been already used -- If you need to reuse the same component, include it with a different name or include it in a different workflow context"

However this is not the correct error message therefore it's misleading

**Comment by bentsherman** [comment]
What's your Nextflow version? I believe this was fixed as of 23.10.0

**Comment by sbthandras** [comment]
23.04.2

Thanks a lot, glad it's fixed now!
