### ISSUE TITLE
Lack of `JAVA_HOME` causes `/bin/java` to be assumed

### ISSUE THREAD

**Issue by jason-seqera** [nextflow-io/nextflow#4653]
## Bug report 

```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

./nextflow: line 289: /bin/java: No such file or directory
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /bin/java
 NXF_OPTS:
```

### Expected behavior and actual behavior

An error about not being able to find Java or `JAVA_HOME` not being set. Not having `No such file or directory` error would be better, with an explanation that the proper environment variable is not set instead.

### Steps to reproduce the problem

Run `nextflow` without `JAVA_HOME` set, or `java` in your `PATH` anywhere, or `JAVA_CMD`, or any other Java related environment variables. And no `java_home` anywhere in the `PATH`, either. Basically an environment of a user that's never had Java before, and perhaps misconfigured installing it, so there's no evidence it's actually installed, or it is not.

### Environment 

* Nextflow version: 23.10.0 build 5889
* Java version: openjdk version "17.0.8" 2023-07-18 LTS
* Operating system: MacOS
* Bash version: GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)

### Additional context

I used `sdkman` for installation, but in this case forgot to source `~/.sdkman/bin/sdkman-init.sh`, so `java` environment variables are not set.

**Comment by marcodelapierre** [comment]
Thanks @jason-seqera , I tend to agree that your suggested message may be preferrable to the currently assumed path. We are going to discuss it internally soon.

**Comment by ewels** [comment]
What do folks think about checking for the existence of this file when we hit this error?

```
~/.sdkman/bin/sdkman-init.sh
```

We could add to the error message if it's found, suggesting that maybe the user forgot to `source` it.

Because this is such a critically important step to get new users onboarded, I'm keen to make any error messages as helpful and actionable as possible.

**Comment by ewels** [comment]
Amazing, thanks @marcodelapierre !

**Comment by marcodelapierre** [comment]
@jason-seqera @ewels  feel free to comment on the PR #4830
