### ISSUE TITLE
The nextflow config priority can be misleading with "Values defined within the pipeline script itself"

### ISSUE THREAD

**Issue by ngochieu642** [nextflow-io/nextflow#4662]
- This is the documentation on nextflow configuration priority: https://www.nextflow.io/docs/edge/config.html#configuration-file
- At the section 7, there is a text said that "Values defined within the pipeline script itself (e.g. main.nf)"

- Now after experimenting with this, I think I finally understand what's the priority, here are my thoughts

## The doc at that point is confusing
  - Firstly, what are "values"? I think you guys mean "params" - please correct me if I'm wrong
  - Secondly, what are the part in the script, is it params, is it workflow, is it process? I think you guys mean params

## There is a "missing" section
- that is the directives defined within the script itself. This section has the highest priority, even higher than what specified from the command line. I think its best to include this to the docs so people don't get confused by this
```groovy
process process_1 {
    cpus 4
    memory 8.GB
}
```

**Comment by bentsherman** [comment]
I believe #4510 will clarify the documentation on config resolution priority. Maybe it would be useful to separate the priority rankings for config files generally vs params and process directives
