### ISSUE TITLE
Add a file in lib that is loaded by default for custom groovy (not only custom classes)

### ISSUE THREAD

**Issue by mahesh-panchal** [nextflow-io/nextflow#4667]
## New feature

I'd like to be able to separate out custom groovy from the main.nf and place it in `lib/`. While custom classes are supported, other things like metaprogramming is not.

## Usage scenario 

For example, I would like to add this merge method to the `Map` class, but have it somewhere other than the `main.nf` to keep it clean. 

Toy example to merge nested maps and return a new Map object.
```nextflow
Map.metaClass.merge = { Map rhs ->
    def lhs = delegate
    lhs.collectEntries { k, v -> rhs[k] instanceof Map ? [ (k): v.merge( rhs[k] ) ] : [ (k): v ] } + rhs.subMap(rhs.keySet()-lhs.keySet())
}

workflow {
    Channel.of( [ id: 'test', settings: [ busco: [ lineages: 'auto' ] ] ].merge( [ settings: [ hifiasm : [ id: 'default', args: '' ] ] ] ) )
        .view()
}
```

## Suggest implementation 

I'm not sure what more would be needed beyond looking for a default file and merging(?) it with the main.nf.

**Comment by bentsherman** [comment]
What is the purpose of your custom merge implementation?

**Comment by bentsherman** [comment]
Doesn't the `+` operator do this for you?

**Comment by bentsherman** [comment]
Instead of a custom type, you could implement a custom method e.g. `mergeDeep` in the `lib` directory and use that on regular maps

**Comment by mahesh-panchal** [comment]
Thanks Ben.

I thought of those ways too, but this just seemed nicer. It seems I can include a groovy file with a one liner, that lets it work (I forgot to do a search before I posted).
```nextflow
evaluate(new File("lib/Map_extended.groovy"))

workflow {
    Channel.of( [ id: 'test', settings: [ busco: [ lineages: 'auto' ] ] ].deepMerge( [ settings: [ hifiasm : [ id: 'default', args: '' ] ], id: 'test2' ] ) )
        .view()
}
```
`lib/Map_extended.groovy`:
```groovy
Map.metaClass.deepMerge = { Map rhs ->
    def lhs = delegate
    lhs.collectEntries { k, v -> rhs[k] instanceof Map ? [ (k): v.deepMerge( rhs[k] ) ] : [ (k): rhs[k]?: v ] } + rhs.subMap(rhs.keySet()-lhs.keySet())
}
```
