### ISSUE TITLE
Support "failOnError" as a global configuration

### ISSUE THREAD

**Issue by markpanganiban** [nextflow-io/nextflow#4674]
## New feature

`failOnError` is supported globally only under "strict" executation. The other restrictions of "strict" conflict with multiple configurations and purposeful undefined variables. Publishing files are critical functions and warant a specific config item versus being lumped into other general restrictions.

Our only other option at this point is to scan people pipelines on runtime and dynamically insert `failOnError` before the Nextflow exectuation.

**Comment by bentsherman** [comment]
The `failOnError` option will default to `true` in the next release 24.03.0-edge. Closing since this addresses the original use case
