### ISSUE TITLE
"String too long. The given string is 65682 Unicode code units long, but only a maximum of 65535 is allowed."

### ISSUE THREAD

**Issue by darachmiller** [nextflow-io/nextflow#4689]
## New feature & sort of a bug

I propose that Nextflow can handle workflows of arbitrary character length.
Because it has a limit :laughing: ...

Very low priority. Posting issue to that it turns up if anyone ever searches for it.

## Usage scenario 

I am a mediocre and occasionally effective programmer. I've been cobbling together a pipeline :japanese_ogre: 
using Nextflow, learning a lot :upside_down_face: , and I found this error that I hope :crossed_fingers: 
is irrelevant for most everyone, but just in case:

```
N E X T F L O W  ~  version 23.04.2                                                                                                                                                           
Launching `main.nf` [big_moriondo] DSL2 - revision: 78ea94e56d                                                                                                                                
ERROR ~ Script compilation error                                                                                                                                                              
- file : {{REDACTED}}/main.nf                                                         
- cause:: -1: String too long. The given string is 65682 Unicode code units long, but only a maximum of 65535 is allowed.                                                                     
 @ line -1, column -1.  
 ```

Hey at least I have a lot of comments!

It appears that the workflow is treated as a string. 
If I put more characters in the workflow it counts those exactly,
and conversely if I take characters out until I'm below the limit.
Taking some code out to separate subworkflows that are reference in the 
main workflow is also an effective option and _**probably what should be done.**_

## Suggest implementation 

Sorry but I don't know anything about Groovy/Java except what I 've learned from using Nextflow (thx!),
but can you use a larger String type to store it? Or stuff it in a list of strings that are concatenated?

Additionally, the idea of having Channels contain named dict/maps instead of ordered tuples would 
eliminate at least half of the characters in the workflow (they're mostly comments to remember what's in
each tuple position at each step!)

Have a good one

**Comment by bentsherman** [comment]
I believe this limit is imposed by the underlying Groovy engine, which we are unlikely to move away from any time soon. You are better off moving subcomponents into separate modules.

- processes and subworkflows can be moved into separate module scripts
- helper functions can be moved to the `lib` directory in your pipeline repository

See the nf-core pipelines for examples of these practices

**Comment by darachmiller** [comment]
Yes, it would be sure suprising if yall were to ditch Groovy.

I just thought it was funny to run into this character limit, so I'll close that and it's there with your recommendations in the search results in case anyone else runs into it.
