### ISSUE TITLE
tuple example from process documentation does not work

### ISSUE THREAD

**Issue by KleinSamuel** [nextflow-io/nextflow#4698]
Hi,

I am currently working through the documentation and had troubles understanding the `tuple` input type.
When trying to execute the given example I get an error.

The documentation section in question:
[https://www.nextflow.io/docs/latest/process.html#input-type-tuple](https://www.nextflow.io/docs/latest/process.html#input-type-tuple)

The example I am trying to run:
```
process tupleExample {
    input:
    tuple val(x), path('latin.txt')

    """
    echo "Processing $x"
    cat - latin.txt > copy
    """
}

workflow {
  Channel.of( [1, 'alpha'], [2, 'beta'], [3, 'delta'] ) | tupleExample
}
```

The error I get:
```
N E X T F L O W  ~  version 23.10.1
Launching `test.nf` [fabulous_roentgen] DSL2 - revision: 950eb1f310
ERROR ~ Error executing process > 'tupleExample (2)'

Caused by:
  Not a valid path value: 'beta.txt'


Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```

Is there an error in the example? What would the expected output be?

As far as I understand the tuple, it consists of two values of which the first is of type `val` with the variable name `x` and the second is of type `path` which gets assigned a fixed name `latin.txt`. Is that correct?
I struggle to understand which values of the tuple are then assigned to these values, shouldnt it be `x = 1` and `alpha` (which is now called `latin.txt` in the currrent context) for the first tuple `[1, 'alpha']`?

Thank you for your help!
~Sam

**Comment by bentsherman** [comment]
This might be because the example originally used a `file` input and was changed to a `path` input without updating the workflow code. Whereas a `file` input would `'beta'` to a file containing that string, `path` simply interprets `beta` as a filename which is not the intended behavior.

I will fix this example in an upcoming batch of docs updates
