### ISSUE TITLE
Better errors for parsing whitespace

### ISSUE THREAD

**Issue by njspix** [nextflow-io/nextflow#4699]
Example script block:
```
    """
        biscuit pileup -@ 32 -g ${chr}:${regions[0]}-${regions[1]} \
             -p ${pileup_flags} \ 
            ${ref} ${bams} | \
            awk '\$0 ~ /^#/ || !(\$5 ~ /[\\.N]/)' | \
            bgzip > ${meta.group}_${chr}_${regions[0]}.vcf.gz
        tabix -p vcf ${meta.group}_${chr}_${regions[0]}.vcf.gz
    """
```

throws this message when executing (but doesn't actually error out)
```
unknown recognition error type: groovyjarjarantlr4.v4.runtime.LexerNoViableAltException
```
Removing the ` ` at the end of line 2 (after the `\`) fixes the error message...

### Environment 

* Nextflow version: version 23.10.1
* Java version:  `openjdk 17.0.9-internal 2023-10-17 `
* Operating system: `Linux 5.14.0-162.6.1.el9_1.0.1.x86_64`
* Bash version: `GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)`

Based on what I heard on the Channels podcast re: improving error messages, not sure if this is possible, but just wanted to mention it.

**Comment by bentsherman** [comment]
This error is documented [here](https://nextflow.io/docs/latest/script.html#multi-line-strings). For now there is no way for us to catch it and provide a better error message, but we are working on some larger improvements to the parsing that should allow us to deals with these errors.

**Comment by njspix** [comment]
Ah sorry - didn't realize it was already doc'd, thanks for following up!
