### ISSUE TITLE
Patch to handle intrinsic Data Managers with LSF

### ISSUE THREAD

**Issue by ashkurti** [nextflow-io/nextflow#471]
While trying out nextflow in  a cluster with an LSF scheduler that has got a Data Manager (typically in these cases the login nodes disk space is separate from the compute nodes disk space) - it did not work out. 
Looking at the script generated by NF in the login node of the cluster that should then be launched through the LSF scheduler I think the problem stands in three points:

1.  There are files generated by that script on the compute nodes, that are later expected on the launching directory. These files would need to be asked back in the script through the directive `bstage out -src file_name` such as `bstage out -src .exitcode` for example.

2.  The remote directory that will contain whatever will be generated by the compute nodes (as per complications of our server) has got the same name of the launching directory except for the second part of the absolute path:` /first/second/third/etc` where `second` should be replaced by `panther`.

3.  The files within the launching directory that will be used from within the script during the execution phase, will need to be referenced within the script and be transferred to the compute nodes through the `#BSUB -data absolute_path_of_file` directive.

Is it possible to integrate these with a patch on NF so as it can be used on similar systems. I will be more than happy to help with testing. Thanks!

**Comment by pditommaso** [comment]
A few questions to understand better the deployment model of your system. Only the login node do not share the file system or also the computing nodes are isolated? NF is running in the login node or it's executed in a computing node as a LSF job? 

Although it doesn't appear to be a trivial, it should be possible to support the LSF data manager with NF. However this looks a corner case and at this stage I need to prioritise other development. 

If you are interested in contributing a pull request I will happy to merge.

**Comment by ashkurti** [comment]
The computing nodes have got a separate disk space from the login nodes. And the task execution happens there. The initial NF script (.command.run and .command.sh) is created in the login node and is launched  to be executed then in the compute nodes as an LSF job. 

I think it is just the three points I mentioned. If things work, I will need to do a few tests and there is a big chance I will be using this for a big project and you will be cited and take further credit with NF. But this big project has got deadlines and I would need this to work within a certain time frame. 

Also, I would be happy to contribute a pull request but I would need some guidance as I do not know the NF code and where to apply the changes.

**Comment by pditommaso** [comment]
I can surely provide some advice. This first thing that you could try to do is to use a `.command.run` launcher script created by NF and modify that script so that you are able to execute successfully in your environment. Then upload here that script reporting the changes needed.

**Comment by ashkurti** [comment]
Ok, I will started from there and update here.
