### ISSUE TITLE
Custom job naming for Google Batch

### ISSUE THREAD

**Issue by soj-hub** [nextflow-io/nextflow#4714]
## New feature

Currently, when Batch is used directly, the job name dictates the naming of the VMs created. For example, the VM name will be the job name appended with additional characters. With Nextflow, the job name/job ID is starts with "nf-" and when trying to map the VM to a specific job or user it is quite difficult.

Users would like friendlier naming of VMs and ultimately may require job ID names to be friendlier.

## Usage scenario

When a Nextflow pipeline is created and goes to Google Batch, it is difficult to identify the VMs and users associated with the submitted pipeline.

## Suggest implementation 

The current Nextflow behavior is defined [here](https://github.com/nextflow-io/nextflow/blob/master/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L91).

**Comment by pditommaso** [comment]
@marcodelapierre we should give a try to this

**Comment by pditommaso** [comment]
Likely something similar to [executur.jobName](https://www.nextflow.io/docs/latest/config.html#scope-executor) can be implemented

**Comment by pditommaso** [comment]
Solved via https://github.com/nextflow-io/nextflow/commit/df40d55f5dffb78d3d8bff4101590f64f086c3d2
