### ISSUE TITLE
Operator splitFasta should allow the creation of chunk having the same size

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#472]
Splitting fasta is a trivial task but doing it in a way that every piece is more or less homogeneous will help to optimize the parallelization step. So I suggest a new parameter for this purpose.

**Comment by pditommaso** [comment]
Should the header counted to determine the chunk size? I would say no.

**Comment by lucacozzuto** [comment]
chunk size should be only referred to the sequence. Thanks!
