### ISSUE TITLE
Feature Request: Nextflow Container Image based on Amzon Linux 2023

### ISSUE THREAD

**Issue by donovat** [nextflow-io/nextflow#4720]
The current container image hosted on platforms like dockerhub are based on `amazoncorretto:17.0.10` which is based on Amazons Linux L2. Although Amazon have promised support for this distribution, many OS packages and especially python packages are not available. Good examples are OpenSSL (i.e. 1.1.1+) etc. 
This makes it difficult to install additional elements, i.e. `nf-core` without a great deal of effort. 
However. Amazons Linux L2023 is their latest OS, and is fully supported with many packages simply installable via `dnf`. 
Amazons container `amazoncorretto:17.0.10-al2023` can be utilised without many changes. I have myself utilised this container for both nextflow & ns-core.

**Comment by bentsherman** [comment]
Agreed. The AL2023 image has newer packages and fewer security vulnerabilities

**Comment by pditommaso** [comment]
Done 3e695ad9
