### ISSUE TITLE
improving splitText

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#473]
It would be very nice to keep in some way the order of pieces when we split a text, so that the joining would keep the order. Something simple like numbering the pieces using numbers and when merging just looking at those numbers.

**Comment by pditommaso** [comment]
A simple workaround for this use case is the following 

```
count=0

Channel
  .from('blah\nblah\nblah\nblah ')
  .splitText()
  .map { chunk -> [count++, chunk] }
  .println()
```

Closing and adding this to the wishlist.
