### ISSUE TITLE
creating splitBed

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#474]
Bed files are another standard heavily used for genomic intervals. Several bioinformatics pipeline to be parallelized properly could benefit of a splitBed operators with the possibility to have homogenous intervals.

**Comment by pditommaso** [comment]
The BED format a little more than a TSV file, optional `track` lines. For example:

```
track name="ItemRGBDemo" description="Item RGB demonstration" itemRgb="On" 
chr7  127471196  127472363  Pos1  0  +  127471196  127472363  255,0,0
chr7  127472363  127473530  Pos2  0  +  127472363  127473530  255,0,0
chr7  127473530  127474697  Pos3  0  +  127473530  127474697  255,0,0
chr7  127474697  127475864  Pos4  0  +  127474697  127475864  255,0,0
chr7  127475864  127477031  Neg1  0  -  127475864  127477031  0,0,255
chr7  127477031  127478198  Neg2  0  -  127477031  127478198  0,0,255
chr7  127478198  127479365  Neg3  0  -  127478198  127479365  0,0,255
chr7  127479365  127480532  Pos5  0  +  127479365  127480532  255,0,0
chr7  127480532  127481699  Neg4  0  -  127480532  127481699  0,0,255
```

What kind of splitting is needed to apply on this format ?

**Comment by pditommaso** [comment]
cc @mfoll

**Comment by lucacozzuto** [comment]
Actually you might want to split in different ways (and keeping the 
header if present):

- per chromosomes (quite simple)
- making homogeneous N groups to balance the workload of each computing 
node (see example below)

Let's make 2 groups starting from:

chr1    100    10000
chr1    1    10
chr2    1    20
chr3    1    100

then you have:
FILE ONE:
chr1    100    10000

FILE TWO:
chr1    1    10
chr2    1    20
chr3    1    100

**Comment by pditommaso** [comment]
Closing because there's no more activity. Added to the wshlist.
