### ISSUE TITLE
Documentation don't mention containers require 'ps'

### ISSUE THREAD

**Issue by gdevenyi** [nextflow-io/nextflow#4743]
## Bug report 

Docs don't mention containers require 'ps'

### Expected behaviour and actual behaviour

Documentation should specify `ps` is required inside the container, as well as provide some standard package names for different container OS' to install to provide it.

### Steps to reproduce the problem

Run a container missing `ps`

The error itself is helpful, but I had to go searching to figure out what provides `ps` in my container OS.

**Comment by gdevenyi** [comment]
Seems one cannot trust the readthedocs search:
![image](https://github.com/nextflow-io/nextflow/assets/3001850/4c1e0d88-0a58-4a7d-af32-d7fe32f75b82)

I remember seeing something but I couldn't find it when I went looking, hence this bug.

I'd still like to request some short suggestions on what package might contain `ps` for various distros.

**Comment by bentsherman** [comment]
Which package to install for each Linux distro strikes me as something that is out of scope for the nextflow docs. There are much better places to go if you want to learn how to maintain your own containers. If you'd rather not think about it, you can also just use [Wave](https://nextflow.io/docs/latest/wave.html)
