### ISSUE TITLE
splitCsv possible separators

### ISSUE THREAD

**Issue by kscott-1** [nextflow-io/nextflow#4771]
Hi all,

I am working with the splitCsv() operator, and I would like to use a whitespace delimiter. The files included a channel being passed to this operator are allowed to be space or tab delimited, but it appears that the splitCsv method can only account for one or the other.

Is there an equivalent to '\s+' for this option?

Trace:
ch.splitCsv(header: true, sep: '\\s+') -> ERROR ~ Not a valid CSV character: \s+

**Comment by bentsherman** [comment]
This is not supported. I suggest you normalize your inputs to have the same csv separator before parsing them

**Comment by kscott-1** [comment]
Thanks for the response. My particular use case is compiling files to be used for meta analysis, some of which are years old and incapable of being edited. It isn't essential per se, but the idea was to parse each file header to make sure there are no naming issues prior to analysis as a sanity check. The software takes anything whitespace delimited, so both can exist.

I take it this is not on the list of things to enhance?

**Comment by bentsherman** [comment]
I don't think we will support splitting on a set of characters. If you just need to check the header, you could do this manually -- read the first line of each file, split on your set of characters, verify the header names.

**Comment by kscott-1** [comment]
Thanks - I will give that a test. Feel free to close.
