### ISSUE TITLE
Is there a commercial license?

### ISSUE THREAD

**Issue by lh3** [nextflow-io/nextflow#478]
A friend of mine from a company is interested in nextflow. However, GPL brings some complications when his company wants to redistribute their own workflows at some point (not right now). Is the GPL license intended? Is there a commercial license for nextflow?

**Comment by pditommaso** [comment]
Yes, it is right. However CRG can provide commercial licence upon request. Tell your friend he can contact us if needed.

**Comment by lh3** [comment]
Thanks! I will let him know.
