### ISSUE TITLE
Add a keepHeader option to collectFile

### ISSUE THREAD

**Issue by baffelli** [nextflow-io/nextflow#479]
In many cases, I want to collect several csv files that share the same structure. The ideal operator would skip their headers while collecting the files and then reattach the first  header it encountered before emitting the collected file.

**Comment by lucacozzuto** [comment]
+1

**Comment by fujimuramasa** [comment]
plus one, some process like BLAST nr database, we can split FASTA and run separately. However, it would cost another process to remove redundant header.

**Comment by davisem** [comment]
👍

**Comment by pditommaso** [comment]
The only problem I see here is how to manage  the splitting of many CSV in many chunks that *may* have different headers. What header is supposed to be applied in the resulting collected files? the first one any case or the last processed ?

**Comment by baffelli** [comment]
Honestly I don't know. I am personally interested in the case where I'm collecting several CSV files that all have the same header. Perhaps a first idea could be to collect all the header, compare them and provide a warning in case they don't match.

**Comment by pditommaso** [comment]
A bit too complicated. I would go with the assumption they are equals and only the first is retained and applied to the collected files.

**Comment by baffelli** [comment]
I'd love that feature!

**Comment by pditommaso** [comment]
And now, the most difficult question: `keepHeaders` or `keepHeader` ? 😄

**Comment by lucacozzuto** [comment]
I would use keepHeader :) But then you have to specify either the number 
of rows or the presence of a character able to identify the header (like #)

L

**Comment by pditommaso** [comment]
`keepHeader` won. 

> you have to specify either the number of rows or the presence of a character able to identify the header

Not sure to understand

**Comment by lucacozzuto** [comment]
Examples:

Name    Surname
Luca    Cozzuto
Paolo    Di Tommaso

So here the header is row 1

Again:

This is the the wonderful format made by some crazy bioinfo
Name    Surname
Luca    Cozzuto
Paolo    Di Tommaso

So here the header is composed by rows 1-2

Finally

# Let's add some variable rows because you know there is
# nothing better than some strange text here
# Name    Surname
Luca    Cozzuto
Paolo    Di Tommaso

So here the variable header is described by a prefix (#).

PS: I hope there won't be a combination of the two situations :)

L

**Comment by pditommaso** [comment]
ummmmmmmmmmm, multi-line headers !

**Comment by pditommaso** [comment]
I think I'm going to have a beer session ..

**Comment by pditommaso** [comment]
Available for test in version 0.27.0-SNAPSHOT.

**Comment by pditommaso** [comment]
This was more tricky than expected. You guys owe me a 🍺 or a ☕️ at your choice. 😄
