### ISSUE TITLE
singularity exec for NF 23.10.1?

### ISSUE THREAD

**Issue by vinjana** [nextflow-io/nextflow#4801]
### Expected behavior and actual behavior

The documentation states

> Changed in version 23.09.0-edge: Nextflow uses the command run to carry out the execution of Singularity containers instead of the exec command. To re-enable the old behavior, set the environment variable NXF_SINGULARITY_RUN_COMMAND to exec.

I'm running 23.10.1 (which is supposedly newer that 23.09.0-edge, right?), and find that Nextflow still uses `exec` rather than `run`.

### Steps to reproduce the problem

I used Nextflow from the following Conda environment:

```
name: test
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - nextflow=23.10.1
  - gradle=7.4
  - openjdk=11
```

I verified that `NXF_SINGULARITY_RUN_COMMAND` is **not** set in the environment.

I then ran a workflow from the commandline.

### Program output 

The workflow produces `.command.run` files with a line like the following:

```bash
$ cat work/10/4397571c139a2b62effe10c1a9901e/.command.run  | grep singularity
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} ${NXF_TASK_WORKDIR:+SINGULARITYENV_NXF_TASK_WORKDIR="$NXF_TASK_WORKDIR"} singularity exec --no-home --pid -B /path/to/code/nf-seq-qc/integration-tests /path/to/nf-seq-qc/cache/singularity/registry.gitlab.com-one-touch-pipeline-workflows-nf-seq-qc-1.2.1.img /bin/bash -ue /path/to/code/nf-seq-qc/integration-tests/work/10/4397571c139a2b62effe10c1a9901e/.command.sh
```

So it seems 23.10.1 (from Conda) still defaults to `singularity exec`.

The problem can be avoided by setting `NXF_SINGULARITY_RUN_COMMAND=run`, which is good. So it seems the default was not changed, as described in the docs.

### Environment 

* Nextflow version: 23.10.1 build 5891
* Java version: Groovy 3.0.19 on OpenJDK 64-Bit Server VM 11.0.9.1-internal+0-adhoc..src
* Operating system: CentOS 7.9; Ubuntu 22.04
* Bash version: 4.2.46(2)-release (CentOS); 5.1.16(1)-release (Ubuntu)

### Additional context

None.

**Comment by marcodelapierre** [comment]
Hi @vinjana , 
thank you for your report. Indeed the default Singularity command is still `exec`. We will fix the inconsistency.

May I ask you which of the two (`exec` or `run`) is the most frequently needed one with the containers you use?

**Comment by vinjana** [comment]
I got my little workflows to run with `singularity exec` (using actually `apptainer exec`). I had some problems though with the conversion: My Docker containers, which served as template from which I built the Apptainer containers with `apptainer build`, were Conda-based and used an `ENTRYPOINT` of the form `["conda", "run", ..., $myEnv]`. This entrypoint was ignored when the container was started with `exec`. Effectively, no Conda was set up in the containers and the jobs did not run. I solved that by moving the environment setup into an `%environment` section containing `conda activate $myEnv` to a `Singularity.def`.

To be honest, I would have preferred to not having to add a `Singularity.def` (and maybe there still is a way, but due to time constraints I did not continue searching for yet another working solution). [As far as I understand](https://apptainer.org/docs/user/1.3/docker_and_oci.html#cmd-entrypoint-behaviour), `apptainer run` would have evaluated the `%runscript` section that Apptainer composes from both the Docker `ENTRYPOINT` and `CMD` directives.

Unless there is something I overlook (which is not unlikely), I would prefer `apptainer run`, but having an option to choose certainly is a good idea.

**Comment by pditommaso** [comment]
That's a glitch in the documentation, we tried to use `singularity run` as default but it was decided to rollback it and continue to use `exec` instead by default. See c1cc60dd48866857460912bd7b20098417c8eb28. 

We noticed some incompatibility between `singularity` exec and biocontainers.

**Comment by marcodelapierre** [comment]
Thanks for your feedbacks @vinjana , much appreciated. I have opened a PR to fix the docs inconsistency.
I also confirm that you can have Nextflow to apply your preferred behaviour by setting 
```
export NXF_SINGULARITY_RUN_COMMAND=run
```
before running your pipelines

**Comment by jeskowagner** [comment]
Does `NXF_SINGULARITY_RUN_COMMAND` still have any effect? A [search](https://github.com/search?q=repo%3Anextflow-io%2Fnextflow%20NXF_SINGULARITY_RUN_COMMAND&type=code) looks like it's only being used in a unit test and at least for me, on version 24.04.2, it does not change `exec` to `run`.

**Comment by pditommaso** [comment]
It does https://github.com/nextflow-io/nextflow/blob/059151a6bad40baedcaaf2b31fa455a951bd420b/modules/nextflow/src/main/groovy/nextflow/container/SingularityBuilder.groovy#L65

**Comment by jeskowagner** [comment]
Interesting, it seems to work from `bash` but not `fish`. Thanks!

**Comment by vinjana** [comment]
Just for completeness: For apptainer the variable is called `NXF_APPTAINER_RUN_COMMAND`. This is not explicitly mentioned in the docs.

**Comment by pditommaso** [comment]
Tagging @christopher-hakkaart for visibility
