### ISSUE TITLE
Error after upgrading to 24.02.0-edge 

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#4810]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

Pipeline works well with version 23.10.1
 With the new nextflow I got:

```
ERROR ~ Error executing process > 'BASECALL:DORADO_BASECALL:baseCall (mod---2)'

Caused by:
  class org.codehaus.groovy.runtime.GStringImpl cannot be cast to class java.lang.String (org.codehaus.groovy.runtime.GStringImpl is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')

Source block:
  """
            dorado basecaller ${params.EXTRAPARS} --emit-fastq ./ > ${idfile}.fastq
            bgzip -@ ${task.cpus} ${idfile}.fastq
      """
````

**Comment by bentsherman** [comment]
Is there a stack trace for this error? It will be difficult to find the source of the error without the trace

**Comment by lucacozzuto** [comment]
do you mean the `.nextflow.log?`

**Comment by lucacozzuto** [comment]
I added another part of the error

**Comment by pditommaso** [comment]
Luca, please include `.nextflow.log` file

**Comment by lucacozzuto** [comment]
[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/14571283/nextflow.log.txt)
Here it goes. Thanks!

**Comment by lucacozzuto** [comment]
You can see the code here:

https://github.com/biocorecrg/BioNextflow/blob/master/subworkflows/basecalling/dorado.nf

Thanks!

**Comment by pditommaso** [comment]
Is there are way to replicate it locally?

**Comment by lucacozzuto** [comment]
Cd mop_preprocess

**Comment by pditommaso** [comment]
You are right, however it fails for other reason 

```
  Unable to find image 'biocorecrg/mopprepr:0.7' locally

```


Are you able to isolate the error in a smaller test case?

**Comment by lucacozzuto** [comment]
I'll try to make a smaller test case. However `-with-docker` should download the image (or with -singularity in case you want it).

**Comment by pditommaso** [comment]
I did it 

```
nextflow run mop_preprocess.nf -with-docker -profile ci
```

**Comment by lucacozzuto** [comment]
Wow. I have a CI that is working on github and is ok :) https://github.com/biocorecrg/MOP2/blob/main/.github/workflows/build.yml

Once I have a simple test case I'll send you. Thanks again

**Comment by lucacozzuto** [comment]
I think I track down where it fails... I have this code in the nextflow.config:

```
clusterOptions = { "-l h_vmem=${task.memory.toString().replaceAll(/[\sB]/,'')}" }
```
removing it fixed the problem.

**Comment by lucacozzuto** [comment]
Hi, thanks for reopening. I'm currently not using nextflow "edge" anymore since I got java errors that are not present in the normal one.

**Comment by pditommaso** [comment]
Duplicate of https://github.com/nextflow-io/nextflow/issues/4931

**Comment by pditommaso** [comment]
Sovled by 74004fbd
