### ISSUE TITLE
What is the expected behavior of file()?

### ISSUE THREAD

**Issue by mhoban** [nextflow-io/nextflow#4815]
I'm trying to parse some of the paths passed as parameters to my workflow before they go into various processes and I've noticed that file() prepends the working directory if the path you pass to it doesn't start with '/'. See this short example:

```nextflow
#!/usr/bin/env nextflow
nextflow.enable.dsl=2

workflow {
  p1 = "/absolute/path"
  p2 = "relative/path"
  p3 = "~/dir/in/home"

  println(file(p1))
  println(file(p2))
  println(file(p3))
}
```

which outputs the following:
```
N E X T F L O W  ~  version 24.01.0-edge
Launching `./ff.nf` [jolly_lamport] DSL2 - revision: 2c00303912
/absolute/path
/drives/storage/users/mykle/test/tmp/relative/path
/drives/storage/users/mykle/test/tmp/~/dir/in/home
```

The second two paths are expanded to prepend the directory the script was launched from, which, in my case, causes parameters passed with values of the third type (beginning with '~/') to fail. This is not a huge issue but I was surprised to see that it does not correctly interpret the tilde as meaning the home directory. Is it supposed to do that?

**Comment by mhoban** [comment]
Oh wait, maybe this is a silly question and the tilde-expansion is carried out by the shell before the path ever gets to nextflow?

**Comment by pditommaso** [comment]
Exaclty

**Comment by mhoban** [comment]
I guess a follow up to that is:

If I pass a parameter to a workflow like this:

```nextflow
$ ./test.nf --param ~/something/in/home
```

The shell expands the tilde. But if I put the same option in a yaml file and pass it using `-params-file`, the tilde will not be expanded.  Should we not be able to put the same value both on the command line and in our params file?

**Comment by bentsherman** [comment]
The tilde is a bash concept, it should only be used on the command-line. This is also why it wasn't expanded correctly in the pipeline script

**Comment by mhoban** [comment]
That's fair. Thanks for the quick replies
