### ISSUE TITLE
Global cap on memory use

### ISSUE THREAD

**Issue by bskubi** [nextflow-io/nextflow#4829]
## New feature

Enable Nextflow to launch new processes only if there is sufficient memory available when the process has a `memory` directive. A clone of [Snakemake's `--resources` feature.](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#snakefiles-resources)

## Usage scenario 

Users wishing to constrain Nextflow to a memory budget could specify `memory` directives for each process in their workflow and a global cap on memory usage. Nextflow would only spawn a process if sufficient memory was available.

## Suggest implementation 

1. Start with a global total of 0 memory consumed and a global memory cap specified by the user or determined from the system.
2. Only launch a process if adding the amount of memory specified in its `memory` directive to the global total would be under the global cap.
3. Every time a process is spawned, add its `memory` to the global total consumed.
4. Every time a process ends, subtract its `memory` from the global total.

You could conceivably partition the processes into process blocks, each with their own memory cap, but that may be unnecessarily complex.

**Comment by robsyme** [comment]
Unless I'm misunderstanding your suggestion, this is already how the `memory` directive works when using a local executor. 

If I have a process that requires 16G of memory:

```groovy
process DoSomething {
  memory '16GB'
  
  input:
  path(reads)

  output:
  path("out.dat")

  script:
  "program $reads --out out.dat"
}
```

When Nextflow launches, it will define the maximum available memory (either the system memory or the `executor.memory` [configuration variable](https://www.nextflow.io/docs/latest/config.html#scope-executor)) and launch only as many `DoSomething` tasks as will fit in that given memory envelope.

For example, If I include this process in a Nextflow workflow running on my laptop with 36GB of RAM, Nextflow will launch at most 2 of these tasks in parallel.

**Comment by bskubi** [comment]
Does Nextflow by default assume that 100% of the system memory is available if `executor.memory` is unspecified? I.e. is there a risk that if I'm using 10 Gb of memory for non-nextflow processes on a 36Gb machine, that nextflow might try to spawn two 16 Gb processes and have one of them fail since the total memory requirement would be (in Gb) 10 + 16 + 16 = 42 > 36?

Thanks for your response!

**Comment by bentsherman** [comment]
Nextflow does not consider the amount of "currently unused" memory, only the total system memory. You can use `executor.memory` to limit it further if you have a particular upper bound in mind.

Also I assume you are just talking about the local executor overall, as it doesn't really make sense to enforce a global memory cap on a distributed cloud/cluster

**Comment by bskubi** [comment]
Thanks @bentsherman, that makes sense. I had Nextflow crash during some testing on my desktop when it launched one too many high-memory processes. Just wanted to make sure the likely explanation was that Nextflow's using installed RAM as the cap, rather than available RAM.
