### ISSUE TITLE
Log warning when nextflow fails because maxErrors is reached

### ISSUE THREAD

**Issue by msmootsgi** [nextflow-io/nextflow#483]
It would be really useful for debugging if nextflow could log a warning indicating that it's exiting not only because process X failed, but also because `maxErrors` was reached for the pipeline.  Right now I need to know to `grep retried .nextflow.log` to figure out whether processes have failed earlier and been retried.

**Comment by pditommaso** [comment]
Could you include the exact message you are greping in the log?

**Comment by msmootsgi** [comment]
When I run `grep retried .nextflow.log` I see:

```
Oct-13 04:30:43.650 [Task monitor] WARN  nextflow.processor.TaskProcessor - Process `runInterproscan (1241)` terminated with an error exit status (143) -- Execution is retried (1)
```

`grep retried .nextflow.log | wc` gives me the rough number of retries that the pipeline has attempted.

I'd just like to be able to see some message from nextflow saying that all retries have been "consumed" and that the pipeline is stopping.  On more than one occasion I've spent time debugging and scratching my head about the process failure that caused nextflow to stop, when it really wasn't the process that was the problem, but simply that the number of retries had been exceeded.

**Comment by pditommaso** [comment]
related to #445

**Comment by pditommaso** [comment]
I see. Makes sense

**Comment by msmootsgi** [comment]
Hopefully this is just a line or two of code... I'm just not sure where those lines should go!  :)

**Comment by pditommaso** [comment]
Maybe a couple more :) around [here](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/processor/TaskProcessor.groovy#L1021-1021). 

I will give a try to it.
