### ISSUE TITLE
Nextflow process output type 'eval' does not work with bash pipes

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#4870]
Testing the new `eval` output type

https://www.nextflow.io/docs/master/process.html#output-type-eval

along with the `topic` channels https://www.nextflow.io/docs/master/channel.html#topic

- `main.nf`

```groovy

nextflow.enable.dsl=2
nextflow.preview.topic = true

process FOO {
    tag "${id}"
    container "quay.io/biocontainers/multiqc:1.14--pyhdfd78af_0"

    input:
    val(id)

    output:
    tuple val(task.process), eval('multiqc --version'), topic: versions

    script:
    """
    """
}

process BAR {
    tag "${id}"
    container "quay.io/biocontainers/multiqc:1.14--pyhdfd78af_0"

    input:
    val(id)

    output:
    tuple val(task.process), eval('multiqc --version | sed -e "s/multiqc, version //g"'), topic: versions

    script:
    """
    """
}

workflow {
    input_ch = Channel.from("Sample1") 

    FOO(input_ch)
    BAR(input_ch)

    channel.topic('versions').view()
}

```

run like this

```
$ NXF_VER=24.02.0-edge nextflow run main.nf

 N E X T F L O W   ~  version 24.02.0-edge

 ┃ Launching `main.nf` [happy_tesla] DSL2 - revision: 432d989a79

executor >  local (2)
[66/012ea3] process > FOO (Sample1) [100%] 1 of 1 ✔
[e2/7aff93] process > BAR (Sample1) [100%] 1 of 1 ✔
[FOO, multiqc, version 1.14]
[BAR, ]

```

I have tried a bunch of different one-liners in the `eval` statement and none of them seem to return any output when there is a bash `|` pipe in the command.

This is surprising since, as far as I can tell, the vast majority of one-liners used for e.g. return process "versions" output require editing with `sed` or similar to clean up the version string. 

Not sure if this is a bug?

**Comment by stevekm** [comment]
after inspecting the `.command.sh` for these tasks, I see this

```bash
nxf_eval_cmd() {
    {
        IFS=$'\n' read -r -d '' "${1}";
        IFS=$'\n' read -r -d '' "${2}";
        (IFS=$'\n' read -r -d '' _ERRNO_; return ${_ERRNO_});
    } < <((printf '\0%s\0%d\0' "$(((({ shift 2; "${@}"; echo "${?}" 1>&3-; } | tr -d '\0' 1>&4-) 4>&2- 2>&1- | tr -d '\0' 1>&4-) 3>&1- | exit "$(cat)") 4>&1-)" "${?}" 1>&2) 2>&1)
}

...

nxf_eval_cmd STDOUT STDERR multiqc --version | sed -e "s/multiqc, version //g"
```

I guess it makes sense now why the `|` does not work, however, this isnt the intended behavior is it?

**Comment by stevekm** [comment]
it seems like you can get it to work by wrapping it like this

```groovy
eval('bash -c "multiqc --version | sed -e \'s/multiqc, version //g\'"')
```

seems kinda like overkill though

**Comment by bentsherman** [comment]
This one is @pditommaso 's baby!

**Comment by stevekm** [comment]
> @marcodelapierre I think the command provided by the user just needs to be wrapped as `bash -c "${cmd}"` if we want to support pipes

yea this works but its kinda... not elegant LOL
I was starting to wonder if maybe it should not just get saved to a file similar to `.command.sh` and treated accordingly

**Comment by bentsherman** [comment]
My point is that the command should be wrapped with `bash -c "..."` under the hood, not by the user

> I was starting to wonder if maybe it should not just get saved to a file similar to .command.sh and treated accordingly

This is exactly what we do. It's also how `env` outputs work. You can accomplish the same eval output by setting an environment var to the desired command in your task script. The `eval` output just hides the step of defining/exporting the environment var

**Comment by stevekm** [comment]
I think one of the goals of using `eval()` is so that you dont need to define things inside the `script` block right?

**Comment by bentsherman** [comment]
Yes exactly

**Comment by marcodelapierre** [comment]
First take here  : https://github.com/nextflow-io/nextflow/pull/4887

**Comment by stevekm** [comment]
thanks, just as a note for posterity, I have updated the example here that utilizes these methods

https://github.com/stevekm/nextflow-demos/tree/master/topic-channels-versions
