### ISSUE TITLE
User Defined Managed Identity Authentication for Azure VM/Batch

### ISSUE THREAD

**Issue by swampie** [nextflow-io/nextflow#4871]
## New feature

Allow Azure Batch VMs to be authenticated with User Assigned Managed Identity when the pool is correctly configured. This will prevent to leak secrets into nextflow configuration and create more granular access control for batch and storage (and secrets)

## Usage scenario 

Will allow azure instances in batch pool to authenticate using a managed identity to batch/storage/secrets features

## Suggest implementation 

1. New configuration snippet for authentication on azure:
```nextflow
azure {
     managedIdentity {
         type: 'USER_ASSIGNED'
         clientId: <client_id>
     }
}
```
2. Use the clientId to instrument the SDK to create a new DefaultCredentials instance: a simple project that make use of this feature can be found [here](https://github.com/swampie/test-managed-identities), the relevant part of the authentication happens [here](https://github.com/swampie/test-managed-identities/blob/f39427c3428bf38ca093586e3b3d86625d733483/src/main/java/io/seqera/azure/Application.java#L20)

**Comment by pditommaso** [comment]
What the `type` is meant for? also would be interesting how the [workload identity client id](https://learn.microsoft.com/en-us/entra/workload-id/workload-identities-overview?source=post_page-----6de99657bbf8--------------------------------) fits here

**Comment by swampie** [comment]
There are two different types of managed identities that could be assigned to vm (system and user): [this](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview#managed-identity-types) page contains a table with the differences. TLDR: system-assigned managed identities are limited to a single azure resource while the user assigned can be tailored to have access to multiple resources. I haven't seen a usecase for system assigned managed identity now but I thought that adding a `type` property now could be useful for extensibility later on. It can also be added in a future iteration, if needed

**Comment by pditommaso** [comment]
@swampie can you please provide a clear path how to replicate your setup and validate the proposed implementation ?

**Comment by swampie** [comment]
the [README](https://github.com/swampie/test-managed-identities:) lists the steps I took to test it. I saw that @adamrtalbot took a similar approach on the PR

**Comment by pditommaso** [comment]
it doesn't tell the most imporant thing ie how to create the Entra managed identity

**Comment by swampie** [comment]
Ok here we go:

- From Azure Portal create a new Manage identity (it is pretty straight forward as it ask for name and region)
- Once it has been created click on it and from the right menu click on Azure Role Assignments
- Add the required roles: for storage access I add the following:
<img width="258" alt="image" src="https://github.com/nextflow-io/nextflow/assets/657223/9080d822-4a50-44d0-93b3-05a98220b61a">
