### ISSUE TITLE
Update Nextflow installation docs on stable branch

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#4877]
The installation docs has been in the [master branch](https://github.com/nextflow-io/nextflow/blob/c9c7032c2e34132cf721ffabfea09d893adf3761/docs/install.md#L7-L35). 

The same changes should be applied to the documentation in the [latest stable branch](https://github.com/nextflow-io/nextflow/tree/STABLE-23.10.x).

**Comment by pditommaso** [comment]
Essentially are saying to default to https://www.nextflow.io/docs/master/

**Comment by bentsherman** [comment]
Yes

**Comment by pditommaso** [comment]
I think it's fine.

**Comment by ewels** [comment]
This is effectively what I did in the navbar change that we merged yesterday :) https://github.com/nextflow-io/website/pull/192

The _Documentation_ link in the navbar on nextflow.io now goes to https://nextflow.io/docs/master/index.html - this is the nightly docs build from the `master` branch of the Nextflow repo. Once there, you can just the dropdown in the sidebar to go to `stable` and `edge`.

**Comment by pditommaso** [comment]
Done also for http://docs.nextflow.io. Closing

**Comment by bentsherman** [comment]
Looks great all around!

Why don't we just change `/docs/latest/` to point to the master branch build?

- `/docs/latest` -> master branch
- `/docs/edge` -> edge release (optional)
- `/docs/stable` -> stable release (optional)

**Comment by bentsherman** [comment]
This way all users will get the update, even if they have the linked bookmarked or auto-suggested (which is me)

**Comment by ewels** [comment]
Works for me 👍🏻 That would leave links in tact which was my main concern. And honestly I think that the URLs are clearer that way.

Not sure if it's just my browser cache or what, but docs.nextflow.io is still going to https://www.nextflow.io/docs/latest/ for me

**Comment by bentsherman** [comment]
It's going to master for me. But now I'm asking to switch it back 😆

**Comment by ewels** [comment]
Implemented in https://github.com/nextflow-io/website/pull/198
