### ISSUE TITLE
Nextflow + GCP: Wave invalid response

### ISSUE THREAD

**Issue by nick-youngblut** [nextflow-io/nextflow#4893]
### Expected behavior and actual behavior

I'm using the GCP setup as described in https://www.nextflow.io/docs/latest/google.html#google-cloud.
I'm using a service account (`GOOGLE_APPLICATION_CREDENTIALS`).
I've checked that the service account does have read/write permissions to the target GCS bucket.

My gcloud config:

```
gcp {
    process.executor       = "google-batch"
    process.errorStrategy  = "retry"
    process.maxRetries     = 3
    params.task_max_cpus       = 36
    params.task_max_memory     = "400.GB"
    params.task_max_time     = "72.h"
    google.project         = "MY_PROJECT"
    google.location        = "MY_LOCATION"
    fusion.enabled         = true
    wave.enabled           = true
    process.scratch        = false
  }
```

The error:

```
Caused by:
  Wave invalid response: [400] {"message":"Container requests made using a SHA256 as tag does not support the 'containerConfig' attribute"}
```

The pipeline works when I run it locally. The pipeline works when I run the pipeline with  `fusion.enabled = false` and `wave.enabled  = false` and `process.scratch = true`.

So, the issue is due to enabling fusion & wave. 

### Steps to reproduce the problem

I doubt that the particular pipeline matters, but I'm using https://github.com/ScaleBio/ScaleRna/tree/master.

See above for the general setup. 

### Program output 

```
Caused by:
  Wave invalid response: [400] {"message":"Container requests made using a SHA256 as tag does not support the 'containerConfig' attribute"}
```

### Environment 

* Nextflow version: `23.10.1.5891`
* Java version: `openjdk 21.0.0`
* Operating system: `Ubuntu 20.04.6`
* Bash version: `5.0.17`

**Comment by nick-youngblut** [comment]
I can start a separate issue, but I've noticed that the [Nextflow GCP docs](https://www.nextflow.io/docs/latest/google.html) do not list the required roles need to use GCP Batch (e.g., `roles/batch.jobsEditor`), and a lack of proper roles for my service account might be the cause the `Wave invalid response` error that I have received (above). It would be helpful if the [Nextflow GCP docs](https://www.nextflow.io/docs/latest/google.html)  included info on how to add the required roles, such as:

```bash
gcloud projects add-iam-policy-binding ${GCP_PROJECT_ID} \
  --member="serviceAccount:${GCP_SERVICE_ACCOUNT_EMAIL}" \
  --role="roles/batch.jobsEditor"
```

**Comment by pditommaso** [comment]
This is not a bug. This error tells you that Wave cannot handle container names specified using sha256 e.g. `myimage@sha256:0ecb2ad60`. You should use either the classic tag of enable the Wave freeze option i.e. `wave.freeze = true`  

See also https://github.com/seqeralabs/wave/issues/331

**Comment by nick-youngblut** [comment]
Thanks @pditommaso for the information!

I thought that the error was due to something with GCP. I didn't see such a warning in the Nextflow docs about how Wave cannot handle container names specified using sha256. Can you please point me to those docs?

>  You should use either the classic tag of enable the Wave freeze option i.e. wave.freeze = true

Maybe it would be helpful to include info on sha256 in the [wave configuration docs](https://www.nextflow.io/docs/latest/config.html#scope-wave)?

Any thoughts about listing the roles required to use GCP services somewhere in the Nextflow docs? Maybe even include a check in the Google plugin to assess whether all of the roles are available for the specified service account?

**Comment by pditommaso** [comment]
> Maybe it would be helpful to include info on sha256 in the [wave configuration docs](https://www.nextflow.io/docs/latest/config.html#scope-wave)?

Yep, we are going to update the docs to reflect it 

> Any thoughts about listing the roles required to use GCP services somewhere in the Nextflow docs?

It should be described [here](https://www.nextflow.io/docs/latest/google.html#credentials) and [here](https://www.nextflow.io/blog/2023/nextflow-with-gbatch.html)

**Comment by nick-youngblut** [comment]
@pditommaso I don't see any specific list of roles required at https://www.nextflow.io/docs/latest/google.html#credentials, and it appears that https://www.nextflow.io/docs/latest/google.html#credentials does not link to https://www.nextflow.io/blog/2023/nextflow-with-gbatch.html, so how is one supposed to know to check through all of the blog posts?

**Comment by pditommaso** [comment]
Feel free to make PR tp improve the docs
