### ISSUE TITLE
Console run is broken

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#4915]
## Bug report 

When launching the `console` run and running a code snippet the following error is reported 

```
groovy.lang.MissingMethodException: No signature of method: nextflow.ui.console.Nextflow.doRun() is applicable for argument types: (Boolean, g.c.u.Console$GroovySourceType, g.c.u.HistoryRecord) values: [false, groovy.console.ui.Console$GroovySourceType@b63de153, groovy.console.ui.HistoryRecord@6a3c800d]
Possible solutions: run(), copy(), cut(), dump(), print(), grep()
```

The above method is defined in the super class `groovy.console.ui.Console`, not clear why the error is reported. it looks related to the upgrade to Groovy 4

**Comment by bentsherman** [comment]
Not sure what's going on here but I wonder if it's related to the custom code to load extension classes: https://github.com/nextflow-io/nextflow/blob/ea8246f65898a76bae38def49bcd39d5880a6041/plugins/nf-console/src/main/nextflow/ui/console/ConsolePlugin.groovy#L45-L54

Aside from that, it might be good to review the current API of the Console class and see if anything needs to be updated / rewritten

**Comment by pditommaso** [comment]
It may be related to https://issues.apache.org/jira/browse/GROOVY-2433 because `doRun` is private and invoked by this [closure](https://github.com/nextflow-io/nextflow/blob/a4518a30bbfe62a8b3ecdbee5457fbeae68105c2/plugins/nf-console/src/main/nextflow/ui/console/Nextflow.groovy#L122-L122)

**Comment by pditommaso** [comment]
But if that's the case, I don't get how it could had worked so far

**Comment by bentsherman** [comment]
I mean that maybe the upgrade to Groovy 4 broke something with the extension class loader

**Comment by pditommaso** [comment]
I've checked that but doesn't see the case

**Comment by pditommaso** [comment]
@jagedn sorry for tagging here, but I feel you are the only one can understand why this error is reported, just in case you have some spare cycles

**Comment by pditommaso** [comment]
Solved by https://github.com/apache/groovy/pull/2084

**Comment by pditommaso** [comment]
For the records, Nextflow uses a custom console build until https://github.com/apache/groovy/pull/2084 is not merged
