### ISSUE TITLE
Issues with PBS scheduler & Singularity

### ISSUE THREAD

**Issue by apeltzer** [nextflow-io/nextflow#492]
Hi! 

I'm trying to run this workflow `https://github.com/qbicsoftware/qbic-wf-megSAP/blob/master/main.nf` using a Singularity container. The container itself works and if I call it correctly with my files in an interactive session on the cluster, it seems to be fine. With Paolos fix, the module is also loaded properly on the cluster, so this should be fine, too. I can't really see whats going on here unfortunately... 

I try to run the whole thing like this:

```
NXF_VER=0.26.0-SNAPSHOT nextflow run -profile cfc qbicsoftware/qbic-wf-megSAP --folder Sample_Project04172015_20150062801 --name CMT_Project04172015_20150062801 --threads 4 --system Sample_Project04172015_20150062801.ini 
```

It doesn't schedule anything, the logfile is showing not really anything telling me whether I made an error... Any idea what might have gone wrong here? 

[nextflow.log.txt](https://github.com/nextflow-io/nextflow/files/1407279/nextflow.log.txt)

[command.env.txt](https://github.com/nextflow-io/nextflow/files/1407267/command.env.txt)
[command.run.txt](https://github.com/nextflow-io/nextflow/files/1407268/command.run.txt)
[command.sh.txt](https://github.com/nextflow-io/nextflow/files/1407269/command.sh.txt)

**Comment by pditommaso** [comment]
Are there any of `.command.err`, `.command.out` or `.command.log` files ?

**Comment by apeltzer** [comment]
Yes, attached to my post (just had to rename them with *.txt for github to be able to upload them) ....

**Comment by pditommaso** [comment]
I see `.env`, `.run` and `.sh` not the ones I've mentioned.

**Comment by apeltzer** [comment]
No, can't find these unfortunately. Neither in the work/* directories nor in the workdir I've started the command

**Comment by pditommaso** [comment]
I see. However this looks a problem on the cluster manager side. What if you change in the task work dir `work/b9/d961304d2b3b7322abbbd645e03193` and launch the execution of the job with `qsub .command.run`? Does it run? what PBS reports?

**Comment by apeltzer** [comment]
When I check with qstat, it does indeed seem to run. No error reports whatsoever

**Comment by pditommaso** [comment]
If so I can hardly help. It cannot fail silently or it runs or it should report an error.

**Comment by apeltzer** [comment]
Indeed, it was a problem with our PBS scheduler. I talked to our sysadmin, and things are ok now on this side

**Comment by pditommaso** [comment]
Best issue ever :)
