### ISSUE TITLE
Slurm: Add config scope for `-A` (account / project)

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#4921]
It would be great to have a config attribute specifically for the slurm account (aka project) to submit jobs to.

See the [Slurm docs](https://slurm.schedmd.com/sbatch.html):
> `-A`, `--account=<account>`
> Charge resources used by this job to specified account. The _account_ is an arbitrary string. The account name may be changed after job submission using the`scontrol` command.

We have [44 different institutional configs](https://github.com/search?q=repo%3Anf-core%2Fconfigs%20-A&type=code) in nf-core doing this by using `clusterOptions` plus a parameter currently. For [example](https://github.com/nf-core/configs/blob/59ac7ecea321f8f4cc6d4cea66985811e29b6259/conf/hasta.config#L23-L26):

```nextflow
process {
    executor = 'slurm'
    clusterOptions = { "-A $params.priority ${params.clusterOptions ?: ''}" }
}
```

It'd be great to remove the need for this workaround as it is so common.

**Comment by pditommaso** [comment]
Something like ?

```
slurm {
  account = 'something'
}
```
