### ISSUE TITLE
Cannot use splitCSV on HTTP files.

### ISSUE THREAD

**Issue by DriesSchaumont** [nextflow-io/nextflow#4966]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

The documentation for [splitCSV](https://www.nextflow.io/docs/latest/script.html#splitting-and-counting-records) (and possibly related methods) states that splitCSV is implemented for `Path`s. This is the relevant this test case: https://github.com/nextflow-io/nextflow/blob/e0e9422721d8d927c58ce2e82a299576f8e827ea/modules/nextflow/src/test/groovy/nextflow/splitter/SplitterExTest.groovy#L339

However, splitCSV does not seems to be implemented for HTTP file objects. Now, HTTP and FTP Path objects are special cases anyway because write and list operations are not supported for HTTP(S) and FTP files. But I am not convised this exception applies here because splitCSV does not list files, nor does it write to files.

### Steps to reproduce the problem

```
workflow {
  Channel.fromList(["https://raw.githubusercontent.com/nf-core/test-datasets/demultiplex/testdata/NovaSeq6000/SampleSheet.csv"])
    | map {file_as_str ->
        file(file_as_str).splitCSV(header: false, sep: ',')
    }
}
```

### Program output 

```
N E X T F L O W  ~  version 23.10.1
Launching `main.nf` [backstabbing_meninsky] DSL2 - revision: 2f52584d6d
ERROR ~ Unknown method invocation `splitCSV` on XPath type

 -- Check script 'main.nf' at line: 4 or see '.nextflow.log' file for more details
```

### Environment 

* Nextflow version: 23.10.1
* Java version: openjdk 21.0.2 2024-01-16
* Operating system: macOS
* Bash version: zsh 5.9

**Comment by bentsherman** [comment]
It should be `splitCsv`, not `splitCSV`

**Comment by DriesSchaumont** [comment]
> It should be `splitCsv`, not `splitCSV`

I should have caught that. My bad! 🙄 Thanks for the quick reply.
