### ISSUE TITLE
Container image pull fails with Singularity 2.4

### ISSUE THREAD

**Issue by apeltzer** [nextflow-io/nextflow#498]
Hi!

I have a `shub://` command issued for a certain process with Singularity 2.4. 
Nextflow pulls the container on the headnode and stores it properly. However, it refers to the image with *.img extension and not with the correct *.simg extension. In the logfile there is a clear indication that the image should end with *.img, thus the process fails. 

I guess this is something rather easy to fix ;-)

**Comment by pditommaso** [comment]
This is the [code causing](https://github.com/nextflow-io/nextflow/blob/c5f638233063c55d567c22403d5b9b3f0379e919/src/main/groovy/nextflow/container/SingularityCache.groovy#L62-L68) the problem. 

I didn't play yet with singularity 2.4. What distinguish a `.img` from a `.simg` ?

**Comment by pditommaso** [comment]
Could you include the log file

**Comment by apeltzer** [comment]
Hi Paolo! sure, no problem. See the attached file. It seems like NF is looking for a *.img file and SHUB downloads a *.simg nowadays with Singularity 2.4

**Comment by pditommaso** [comment]
It looks like a singularity issue. https://github.com/singularityware/singularity/issues/1095

Any chance to use version 2.3 ?

**Comment by apeltzer** [comment]
Not really - but I'll use a pre-pulled image and specify it directly for the time being until they fixed that ;-)

**Comment by pditommaso** [comment]
I'm closing this because it's a singularity bug they are going to address.

**Comment by apeltzer** [comment]
Which they did with Singularity 2.4.1 ;-) 

https://github.com/singularityware/singularity/releases/tag/2.4.1
"Honor the username request when pulling from Singularity Hub"

**Comment by pditommaso** [comment]
No idea. It looks still open 😞  Could you investigate?

**Comment by apeltzer** [comment]
It's been merged, scroll downwards ;-) I'll test once we have the module updated on our cluster here - need the functionality for some stuff. 

https://github.com/singularityware/singularity/issues/1095#issuecomment-339648022

**Comment by pditommaso** [comment]
👍
