### ISSUE TITLE
Commit tag `[ci fast]` is not working anymore

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#4992]
## Bug report 

When tagging a commit with `[ci fast]` integration tests should be skipped, however it looks like they run in any case 

https://github.com/nextflow-io/nextflow/blob/115a39e9df654be835b4c20ede4f6594b5608d47/.github/workflows/build.yml#L111-L111

**Comment by bentsherman** [comment]
Maybe this is the same issue that you have with the e2e test, i.e. push vs pull_request event

**Comment by pditommaso** [comment]
Indeed, solved by https://github.com/nextflow-io/nextflow/commit/a610d05dcb14d3783b273596e7ed38d2a07d3975
