### ISSUE TITLE
feature request: Enable S3 work directory outside of cirrus

### ISSUE THREAD

**Issue by andrewcstewart** [nextflow-io/nextflow#50]
Currently pipelines running on cirrus (or is it gridgain?) have the option of using S3 for the nextflow workdir.  This kind of works outside of cirrus by setting 'nextflow run -w s3://bucket', with nextflow indeed using the designated S3 object as the work directory, except that for some reason pipelines are unable to finish(?).  Why this is the case was discussed briefly in the gitter chat but I forget the cause.

Anyway, this would be a really nice feature to have to complement using S3 for inputs/outputs directly within Nextflow.  An example use-case would be running nextflow on an EC2 cluster (via StarCluster), and running a nextflow pipeline such that all inputs, outputs and contents of the workdir were stored in S3.

**Comment by pditommaso** [comment]
I gave a try to this, but it would add too much complexity to logic of the grid executors. So I'm not going to implement this feature.

However if you need to copy process results to S3 you should take in consideration the new [publishDir](http://www.nextflow.io/docs/latest/process.html#publishdir) directive or even to use a [completion handler](http://www.nextflow.io/docs/latest/metadata.html#completion-handler) to zip the work folder and upload it to a remote storage.
