### ISSUE TITLE
Enhance container interoperability between Docker and Singularity

### ISSUE THREAD

**Issue by KevinSayers** [nextflow-io/nextflow#503]
It doesn't seem that when the Docker engine is specified a container with `docker://` works? It would be nice to be able to write one workflow and execute either on Docker or Singularity purely by specifying `docker.enabled` or `singularity.enabled`.

**Comment by pditommaso** [comment]
Nope. The pseudo-protocol `docker://` is specific of singularity. But I agree with you. The idea is that prefix is automatically added when `singularity.enabled` is specified.
