### ISSUE TITLE
ERROR ~ BUG! exception in phase 'conversion' in source unit 'Script_773b20f0a9f08db0' unexpected NullPointerException

### ISSUE THREAD

**Issue by julibeg** [nextflow-io/nextflow#5039]
### Expected behavior and actual behavior

When using an if-clause in `map` and not emitting anything, this just results in an empty channel
```
workflow {
    Channel.of(1, 2, 3)
    | map { if (it < 0) it }
    | ifEmpty ( "empty" )
    | view
}
// this prints "empty"
```

I'd expect `multiMap` to behave the same, but the below
```
workflow {
    res = Channel.of(1, 2, 3)
    | multiMap {
        squared: it ** 2
        squared_negative_only: if (it < 0) it ** 2
    }
    res.squared_negative_only
    | ifEmpty("empty")
    | view
}
```

fails with
```
ERROR ~ BUG! exception in phase 'conversion' in source unit 'Script_40e50a1fd5c204e0' unexpected NullPointerException
```

### Environment 

* Nextflow version: 24.04.2
* Java version: openjdk 21.0.2-internal 2024-01-16
* Operating system: Ubuntu 20.04
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by bentsherman** [comment]
It's not really semantically correct because you aren't returning a value for the `else` branch. I think Groovy implicitly returns null but it's an edge case I wouldn't rely on. Instead I would do this:
```groovy
workflow {
  res = Channel.of(1, 2, 3)
  res_squared = res | map { it * 2 }
  res_squared_negative = res_squared | filter { it < 0 }

  res.squared_negative
    | ifEmpty("empty")
    | view
}
```
