### ISSUE TITLE
Include process tag in the hoverover of HTML reports

### ISSUE THREAD

**Issue by evanfloden** [nextflow-io/nextflow#504]
When using the hover over feature of the graphs in HTML reports, the process id is shown.

See [here](https://imgur.com/a/7aSJh).

This is redundant and it would be much more useful to see the task tag so you can see which task is using the specified resource.

So in the example above, instead of showing: 

`(default_alignment, 36.5)`

it would be more informative to see 

`(task_specific_tag, 36.5)`

**Comment by pditommaso** [comment]
@ewels I need the help of the report guru :) Any chance to see if it's possible to customise the boxplot hover label with the ones provided by NF?

**Comment by ewels** [comment]
Maybe I'm wrong - possible that a fairly recent update has addressed this: https://github.com/plotly/plotly.js/issues/192#issuecomment-336486507

**Comment by pditommaso** [comment]
Actually I've updated to the latest Plotty version, but I was unable to control the box text display.

**Comment by ewels** [comment]
It should be in the JS library from v1.32 onwards: https://github.com/plotly/plotly.js/releases/tag/v1.32.0 (PR was here: https://github.com/plotly/plotly.js/pull/2094)

**Comment by pditommaso** [comment]
In the master we are using `plotly.js v1.34.0`.

**Comment by ewels** [comment]
Hmm, then you _should_ be able to set the `hoveron: 'points'` property in that case. How did it not work? Just ignored?

**Comment by pditommaso** [comment]
Frankly, I don't remember the tests I've done.

**Comment by pditommaso** [comment]
Nice, I will give a try asap

**Comment by pditommaso** [comment]
Nope, not working :/

**Comment by ewels** [comment]
If there aren't any points now, then it won't.. ;) It enables tooltips on the points themselves, not the boxplot.

**Comment by pditommaso** [comment]
Wait, [there are points](https://github.com/nextflow-io/nextflow/blob/455fcb4f1cda0f6082ec63836604516089121fee/src/main/resources/nextflow/trace/assets/ReportTemplate.js#L35-L42). He get an array [min, q1, q1, median, q3, q3, max].

**Comment by ewels** [comment]
yeah, but not in the plot, to the side of the boxplot I mean.

**Comment by pditommaso** [comment]
I see. I was thinking it was possible to have in place of labels showed over min,q1,etc.

**Comment by ewels** [comment]
Nope, that's not possible. Those values are not task data points, they're distributions of a process. So they can't be labelled with the names of data points, only the process name.
