### ISSUE TITLE
null value in publishDir causes Nextflow to hang without error

### ISSUE THREAD

**Issue by amrei-bp** [nextflow-io/nextflow#5041]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

A spelling mistake in the publishDir directive led to Nextflow hanging and reporting no error even though the process
showed a completed exit code.

### Steps to reproduce the problem

```nextflow
params.outdir = 'output'

workflow {
    DOSOMETHING()
}

process DOSOMETHING {
    publishDir "$param.outdir/something" // <- spelling mistake in variable

    script:
    """
    touch file.ext
    """

    output:
    path "file.ext"
}
```

### Program output 

```console
$ nextflow run test.nf 

 N E X T F L O W   ~  version 24.04.2

Launching `test.nf` [magical_brahmagupta] DSL2 - revision: d43e663ce6

executor >  local (1)
[0b/0aebed] DOSOMETHING | 0 of 1

```
And then stays hung.

### Environment 

* Nextflow version: 24.04.2
* Java version: openjdk 17.0.11-internal 2024-04-16
* Operating system: Linux
* Bash version: GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Thanks for reporting this issue. This is going to be solved by https://github.com/nextflow-io/nextflow/issues/5041
