### ISSUE TITLE
Google Batch Error : Process terminated for an unknown reason -- Likely it has been terminated by the external system

### ISSUE THREAD

**Issue by VasLem** [nextflow-io/nextflow#5048]
## Bug report 
The following errors are not being captured by Nextflow:

[Errors 50002-50006](https://cloud.google.com/batch/docs/troubleshooting#vm_reporting_timeout_50002)

No space left on device error:
![image](https://github.com/nextflow-io/nextflow/assets/18720200/f30973e7-00c1-49e8-9454-e80dc15637d2)

### Expected behavior and actual behavior

Errors 50002-50006, apart from 50005, should be dealt similarly to the preemption 50001 error, as they are irrelevant to the code and dependent on the provider. Error 50005, which has to do with task timing out, and the "No space left on device" should be raised to the user, as they require re-configuration.

The current actual behavior is this uninformative error: `Process terminated for an unknown reason -- Likely it has been terminated by the external system`

### Environment 

* Nextflow version: 24.04.2 
* Operating system: Linux (Google Batch)

**Comment by pditommaso** [comment]
Closing in favour of https://github.com/nextflow-io/nextflow/issues/5136
