### ISSUE TITLE
Bitbucket of different domain

### ISSUE THREAD

**Issue by tburk** [nextflow-io/nextflow#505]
It seems that nextflow recognizes only the public domain of "bitbucket.org" and no alternative domain repositories. Would it be possible to implement recognition of alternative domains that it can be run as:

nextflow run https://bitbucket.mydomain.ac.at/scm/project/repo.git

Thanks,
Thomas

P.S.: If I run the command above with our domain nextflow tries to redirect me to gitbub:

N E X T F L O W  ~  version 0.25.7
Pulling scm/project/test ...
Cannot find `scm/project/test` -- Make sure exists a GitHub repository at this address `https://github.com/scm/project/test`

**Comment by pditommaso** [comment]
See the [Private server configuration](https://www.nextflow.io/docs/latest/sharing.html#private-server-configuration) section in the documentation.

**Comment by tburk** [comment]
Thanks a lot! I missed that somehow... Very sorry.
