### ISSUE TITLE
Using the the unique operator after collect causes the pipeline to stall at pipeline end

### ISSUE THREAD

**Issue by R-Cardenas** [nextflow-io/nextflow#5052]
## Bug report 

When processing a channel with the collect operator followed by unique, the pipeline will run to the end but will hang indefinitely.

### Expected behavior and actual behavior

The pipeline should finish successfully and exit.

### Steps to reproduce the problem

```
test = Channel.of( 'a', 'b', 'c' , ['a', 'b'], 'a')

test
  .collect()
 .unique()
 .view()
```

### Program output 

```
 N E X T F L O W   ~  version 24.04.2

Launching `test.nf` [loving_kare] DSL2 - revision: 4160ee5875

['a', 'b', 'c', 'a', 'b', 'a']
```
[nextflow.log](https://github.com/user-attachments/files/15626387/nextflow.log)

### Environment 

* Nextflow version: 24.04.
* Java version: openjdk version "21-internal" 2023-09-19
* Operating system: Linux
* Bash version: GNU bash, version 5.2.15(1)

**Comment by pditommaso** [comment]
Thanks for opening this issue. This problem is going to be solved by https://github.com/nextflow-io/nextflow/pull/5053. 

Note however, the use of `unique` after `collect` is useless, because the latter returns a sole value by definition and therefore it's not altered by `unique`
