### ISSUE TITLE
file method does not interpret correctly S3 path with globs

### ISSUE THREAD

**Issue by fstrozzi** [nextflow-io/nextflow#509]
Hello,
When an S3 path containing glob characters is passed to the file method, it requires 3 slashes instead of the normal 2.

So this for example works
```
file("s3:///bucket/prefix/*.gz")
```

While this does not work:
```
file("s3://bucket/prefix/*.gz")
```

and raises an error:
```
ERROR ~ The bucket name parameter must be specified when listing objects in a bucket
```

Ideally the ```file()``` method should work with a path specified with just 2 slashes which is the normal way to write an S3 path.

Thanks!!

**Comment by pditommaso** [comment]
Testing a patch. Thanks.
