### ISSUE TITLE
Long living channel

### ISSUE THREAD

**Issue by andremrsantos** [nextflow-io/nextflow#51]
Recently, I have been working on a nextflow pipeline where I need to log all my output of 3 processes into a single file and I have to save the resulting files.

To attend this goal, I have build two Channels:

* One to save the log
* One to copy the files

```
	qc_logger.subscribe { logger(it) }
	qc_copy.subscribe { copyFile(it, read_folder) }
```

I have to repeat the same code for every process.

I have also tried to make a _long living channel_, but after the first process completed the channel was soon closed ignoring the output of others process.

Is there any work around? or include support for a long living __Channel__?

**Comment by pprieto** [comment]
Could you save the log and copy the file at the same time with just one channel? Or you have to do it separately?

**Comment by andremrsantos** [comment]
I can merge them, but yet I will have the same code repeated after each process

**Comment by pditommaso** [comment]
Currently a channel a point to point connection, from a single producer to a single consumer. However what you are proposing makes a lot of sense. In a future release we may try to enhance channel so that they can support multiple producers.

**Comment by andremrsantos** [comment]
To reduce code duplication. I created a closure for copy and log and apply it at the end of each process. You can check the work around at [this project](https://github.com/andremrsantos/next-pipes-lghm/blob/master/small-rna-miseq.nf).

Looking forward for the next updates

**Comment by lucidv01d** [comment]
I really like nextflow, but second this feature request. I have a process that populates a database which other processes require. I'm finding it difficult to signal the dependent processes that the database is done (maybe accomplished with the .separate operator, but this will get ugly for a dozen dependent processes). 

I think this can be done two ways:  
  * Implement a special true/false non-consuming channel:
```
process populateDatabase{
    input:
    file flat_file

    output:
    trigger populationComplete

    """
    python population_script.py
    """
}

process downstream1{
    input:
    waitFor populationComplete

    """
    do something
    """
}

process downstream2{
   input:
   waitFor populationComplete

   """
   do something else
   """
}
```  
  *  Modify the when block to continuously check its requirements:
```
process populateDatabase{
    input:
    file flat_file

    exec:
    populate()
    populationComplete = true
}

process downstream{
    when:
    populationComplete

    """
    do something
    """
}
```   

Maybe I'm missing something fundamental about how nextflow works, so let me know if I'm completely off base here.

Great tool!

**Comment by lucidv01d** [comment]
BTW, as a work around I've been doing this:

```
populationOK = Channel.create()
ok_signal = (1..100000)
process initialPopulation{
    input:
    file flat_file

    output: 
    set ok_signal into populationOK
    
    """
    python populate.py
    """
}
populationOK.flatten().set { populationOK }
```

This trusts that the ok_signal won't be completely consumed by dependent processes.

**Comment by pditommaso** [comment]
I agree that it would a very useful enhancement. I gave it a try a really am hard one. 

Regarding your use case, as far I've understand you need to some processes after the very first one complete. The easiest way to do that is something like this: 

    process populateDatabase{

        output:
        val 'done' into populationComplete1
        val 'done' into populationComplete2

        """
        echo foo
        """
    }

    process downstream1{
        input:
        val foo from populationComplete1

        """
        echo do something
        """
    }

    process downstream2{
        input:
        val foo from populationComplete2

       """
       echo do something else
       """
    }

**Comment by pditommaso** [comment]
The support of multiple output channels in the `into` declaration introduced by #97 can be used as an alternative to this feature request.
