### ISSUE TITLE
add AWS_DEFAULT_REGION environment variable to bash wrapper scripts

### ISSUE THREAD

**Issue by fstrozzi** [nextflow-io/nextflow#512]
When running on the AWS cloud there is the possibility to use S3 [endpoints](https://aws.amazon.com/blogs/aws/new-vpc-endpoint-for-amazon-s3/) to avoid passing through the public internet to retrieve or store data on a bucket. This is particularly useful when instances are running inside a private subnet and in general gives better performances for data transfer. For this to work properly, the AWS_DEFAULT_REGION variable needs to be properly set, otherwise every operation on S3 using the ```aws``` cli tool will try to reach the public internet (if available) resulting in a loss of performance and additional costs for the traffic that will need to pass through a NAT gateway or NAT instance.

This should be an easy fix, since when using AWS with Nextflow the AWS region is already specified in the nextflow.config file, it is just matter to include the variable declaration in the bash environment of the wrapper scripts that will be executed on the cloud

**Comment by pditommaso** [comment]
Included in version `0.26.1-SNAPSHOT build 4732`

**Comment by pditommaso** [comment]
@fstrozzi the `AWS_DEFAULT_REGION` was not applied to the first `aws` command launching the task command. Commit 912c69c should address this problem.
