### ISSUE TITLE
Support more retryable exit codes for Google Cloud Batch

### ISSUE THREAD

**Issue by siddharthab** [nextflow-io/nextflow#5136]
## New feature

According to https://cloud.google.com/batch/docs/troubleshooting, there are more retryable exit codes that we should add to the lifecycle policy of jobs launched by Nextflow. In particular, our jobs are hit by 50002 sometimes. Currently, Nextflow has hardcoded only the exit code 50001 to the lifecycle policy.

https://github.com/nextflow-io/nextflow/blob/572f2116226bca4686c3540be9bd8b81bdded54e/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L269

## Usage scenario 

Usage would be for default invocations of Google Cloud Batch pipelines.

## Suggest implementation 

A simple implementation would be to add the exit codes to the policy directly. An extended implementation would be to parse the exit codes like [here](https://github.com/nextflow-io/nextflow/blob/572f2116226bca4686c3540be9bd8b81bdded54e/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L508) to make retries user configurable for different error conditions.

I am happy to send a PR for either of these implementations if the idea sounds OK to the Nextflow team.

**Comment by VasLem** [comment]
Hi, the issue has also been mentioned [here](https://github.com/nextflow-io/nextflow/issues/5048)

**Comment by siddharthab** [comment]
Maybe 50006? At first I thought 50002 could also be one. But it turns out that, at least in our case, it was because of the machine becoming unresponsive due to memory pressure. So maybe not eligible for automatic retries, at least not without adjusting the resource requirements on the task.

How about I send in a PR to parse these error codes and then the user can mention these error codes in their `process.errorStrategy`? If I understand the purpose of the below code correctly.

https://github.com/nextflow-io/nextflow/blob/572f2116226bca4686c3540be9bd8b81bdded54e/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchTaskHandler.groovy#L508

**Comment by pditommaso** [comment]
Ok, I've created a PR https://github.com/nextflow-io/nextflow/pull/5141 for this. 


The above changes captures all 5000x error codes and allows nextflow to handle using the usual `errorStrategy` instead of reporting the error `Process terminated for an unknown reason -- Likely it has been terminated by the external system`.

**Comment by siddharthab** [comment]
Thank you!

**Comment by siddharthab** [comment]
The merged PR sufficiently addresses this issue, so please feel free to close.
