### ISSUE TITLE
Nextflow is broke on AMI ami-43f49030

### ISSUE THREAD

**Issue by MaxUlysse** [nextflow-io/nextflow#514]
Still trying AWS, and now there's a problem with JAVA on the AMI `ami-43f49030`
```
[max@<MYIP> ~]$ ~/nextflow
ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 is installed
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /usr/lib/jvm/jre/bin/java
 JAVA_HOME: /usr/lib/jvm/jre
```

**Comment by pditommaso** [comment]
NF now requires Java. This AMI has been deprecated. You can either upgrade Java to version 8 or use the new `ami-4b7daa32`. See [here](https://www.nextflow.io/docs/latest/awscloud.html#configuration).

**Comment by MaxUlysse** [comment]
Thanks a lot, you still list `ami-43f49030` in the configuration example.

**Comment by pditommaso** [comment]
Because .. it's an example :) kidding apart already fixed locally, I need to push the changes online.
