### ISSUE TITLE
Parameterize channel topic name with process inputs

### ISSUE THREAD

**Issue by kgalens** [nextflow-io/nextflow#5147]
## New feature

The ability to parameterize the name of topic channels in output declarations with process inputs. Also, optionally "turn-off" adding an output to a topic channel from within a process, similar to `publishDir` functionality.

## Usage scenario 

We can parameterize `publishDir` configuration for a process based off inputs:
```
process example_process {
  publishDir { output_dir == "" ? false : output_dir }

  input:
  val output_dir
...
```

It would be helpful to be able to do something similar with topic channel names:
```
process example_process {
  input:
  val topic_name

  output:
  path("output_file.txt"), topic: "${topic_name}"
```
or
```
  output:
  path("output_file.txt"), topic: { topic_name == "" ? false : topic_name }
```

Currently, if you specify `topic: $topic_name` (i.e. not a string) it looks like this is equivalent to `topic: "$topic_name"`. 

When specifying:
```
path("output_file.txt"), topic: "${topic_name}"
```
I receive an error: `ERROR ~ No such variable: topic_name`

## Suggest implementation 

I would expect this to behave similarly to the publishDir configuration.

**Comment by kgalens** [comment]
It does look like you can use a value from params:
```
output:
path("output-file.txt"), topic: "${params.output_file_topic_name}"
```

Ideally, we could also pass in a value from the calling workflow.

**Comment by bentsherman** [comment]
The topic name should be a string literal. If you want to do dynamic stuff, you should include the relevant variables in the output tuple and use dataflow logic when you get the topic channel:

```groovy
process foo {
  input:
  val topic_name

  output:
  tuple val(topic_name), path("output_file.txt"), topic: 'mytopic'
}

workflow {
  // ...

  Channel.topic('mytopic') | map { topic_name, output_file -> /* ... */ }
}
```

**Comment by kgalens** [comment]
Sorry, maybe I didn't explain my goal well. I was hoping to not hard code the topic name within the task itself as a string literal. For a channel topic to be useful, it should be consistent throughout a single pipeline (i.e. all tasks which push into a topic channel and the workflow which references that topic). For example, if I wanted to change a topic name, I'd have to find all modules which push to that topic name and change that value in `n` places. Also, if this were a variable, if I had a typo in the token name, this would generate an error (if we had static typing, we could get this feedback before runtime). If there was a typo in the string literal, this isn't an error but I would be missing expected values from the topic channel silently.

From my current testing, adding the topic name to the output tuple does not allow me to set the topic name dynamically (it does, however, allow me to add additional information within the output tuple.

**Comment by bentsherman** [comment]
If you feel the need to use dynamic topic names -- even something that is constant within a pipeline but varies across pipelines -- then it is likely not a good use case for topics in the first place. You are probably better off using regular dataflow logic. There are very few cases where it makes sense to use topics, I know of only one or two so far.

**Comment by kgalens** [comment]
Any insight into what you'd consider a good use case here?

In my case, this would be a simplification of some logic. Many of our tasks/processes create a quality metrics file in addition to the primary output (think coverage metrics in addition to the alignment file). A downstream task reads in these metrics files (there could be around 20 or so in our workflow) and creates a single, combined quality metrics file for each sample. 

Without topic channels, this results in a large join of ~20 channels to get the list of metrics files. With topic channels, it's a simplification because we can just send all metrics files to a topic, group the outputs by sample ID and any additional tasks we add which push to this topic will automatically be included (i.e. we don't have to remember to update the large join of channels).

Like you mention above, we could definitely hard code the topic name and call it a day. But this approach is less maintainable, and doesn't easily catch "typo" errors. It also requires that any workflow which uses a specific task to use the same topic names in the same way. 

With a dynamic name, the workflow can decide what the topic name should be, or if a topic should be used at all. This keeps the modules/tasks generic and independent (and ultimately, reusable). This is a very similar approach we use for configuring the `publishDir` directive in our tasks.

**Comment by bentsherman** [comment]
The main use case is to collect tool versions for all processes which is a standard practice in nf-core. We replace all of the version channels with a `versions` topic, which is a simple convention that all nf-core modules and pipelines can converge on.

Topics should ideally be used for some simple universal concept like "versions" in order to justify the fact that you are essentially inserted a global variable into all of your components. This is why I say that if you aren't comfortable with hard-coding the topic name, then the use case might not be universal enough to justify using topics. Otherwise it's better to bite the bullet and use regular channel logic.

We should be able to provide some static analysis in the future to e.g. warn the user if a topic was defined but not used, which would catch typos.

**Comment by kgalens** [comment]
Thanks for the insight. Maybe nf-core will have a similar requirement in the future we'll be able to take advantage of.
