### ISSUE TITLE
Host user and group name should be set by default on Docker run  

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#515]
Docker container run command line should include by default the options `-u $(id -u):$(id -g)` to prevent security issues and to avoid permission problem on files created by the container execution in the host file system. 

It must be noted it could have a side effect on the `HOME` path in the container environment. For example: 

```
$ docker run busybox env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=6a11ebe22d73
no_proxy=*.local, 169.254/16
HOME=/root
```

while: 

```
$ docker run -u $(id -u):$(id -g) busybox env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=00dd7c04313b
no_proxy=*.local, 169.254/16
HOME=/
```

**Comment by pditommaso** [comment]
To make consistent with singularity containers the `USER` and `HOME` variables should be exported eg `-e USER=$USER -e HOME=$HOME `

**Comment by pditommaso** [comment]
This is environment when running with singularity 

```
$ env - PATH=$PATH singularity exec docker://busybox env
$ env - PATH=$PATH singularity exec docker://busybox env | sort
HOME=/home/pditommaso
LD_LIBRARY_PATH=/.singularity.d/libs
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PS1=Singularity> 
PWD=/home/pditommaso
SHLVL=1
SINGULARITY_CONTAINER=busybox
SINGULARITY_NAME=busybox
USER=pditommaso

```

**Comment by apeltzer** [comment]
Also related: https://github.com/nextflow-io/nextflow/pull/1108 (docs for using this)

**Comment by gongyixiao** [comment]
Although I don't fully understand the logic by adding the `-u`, but I notice that by adding `-u` makes Spark not able to run with docker. Removing `-u` option solve this problem. 

https://gatkforums.broadinstitute.org/gatk/discussion/24073/markduplicatesspark-java-io-ioexception-invalid-null-input-name

**Comment by poddarharsh15** [comment]
I don't understand how can I -u ? Do I need to re-install the docker and add -u while performing the codes in bash. I am facing this errors

- [ ] ./nextflow docker -dockerize

- [ ] /usr/local/bin/entry.sh: line 46: addgroup: command not found

- [ ] /usr/local/bin/entry.sh: line 47: adduser: command not found

- [ ] chown: invalid user: ‘nextflow’

- [ ] /usr/local/bin/entry.sh: line 50: su: command not found
