### ISSUE TITLE
Variable with same name within separate functions conflicting with each other

### ISSUE THREAD

**Issue by ashtonteng** [nextflow-io/nextflow#5168]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

```
def get_sample_name_from_gene_exp_fastq_filename(fastq_filename) {
    basename = fastq_filename.name
    mm = basename =~ /^(.*?)_gene_exp_S\d+_L\d+_R\d+_001\.fastq.gz$/
    // if match exists return the first group
    if (m) {
        if (m[0]) {
            return m[0][1]
        }
    }
    return null
}

def get_sample_name_from_crispr_fastq_filename(fastq_filename) {
    basename = fastq_filename.name
    m = basename =~ /^(.*?)_CRISPR_S\d+_L\d+_R\d+_001\.fastq.gz$/
    if (m) {
        if (m[0]) {
            return m[0][1]
        }
    }
    return null
}

workflow {
    gene_exp_fastqs_by_prefix_ch = Channel.fromFilePairs(params.fastqs) {file -> get_sample_name_from_gene_exp_fastq_filename(file)}
        .filter { key, files -> key != null }
        .groupTuple()
        .map { key, files -> [key, files.flatten()] }
        .view()

    crispr_fastqs_by_prefix_ch = Channel.fromFilePairs(params.fastqs) {file -> get_sample_name_from_crispr_fastq_filename(file)}
        .filter { key, files -> key != null }
        .groupTuple()
        .map { key, files -> [key, files.flatten()] }
        .view()
}
```

expected behavior: script runs without error
actual behavior:
```
ERROR ~ index is out of range 0..-1 (index = 0)

 -- Check script 'main.nf' at line: 47 or see '.nextflow.log' file for more details
```

### Steps to reproduce the problem

- Run the script above. Unfortunately I cannot provide the s3 paths to the fastqs, but `params.fastqs` contains many fastq files, which the separate regexes seek to capture subsets of them.
- When I rename the variable `m` in `get_sample_name_from_gene_exp_fastq_filename` to another name, like `n`, the problem goes away, suggesting that the variables within the two function's own scopes are conflicting with each other.

### Program output 

```
ERROR ~ index is out of range 0..-1 (index = 0)

 -- Check script 'main.nf' at line: 47 or see '.nextflow.log' file for more details
```

### Environment 

* Nextflow version: 24.04.2
* Java version: [?]
* Operating system: Linux
* Bash version: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by bentsherman** [comment]
See the warning in the docs section on functions and closures: https://nextflow.io/docs/latest/script.html#closures

You need to declare local variables with `def`, otherwise they will be treated as global variables which can lead to a race condition

We will be removing this foot-gun in the future 😄

**Comment by ashtonteng** [comment]
thanks so much! ill delete
