### ISSUE TITLE
containerOptions directive does not support args with equals sign

### ISSUE THREAD

**Issue by robsyme** [nextflow-io/nextflow#5174]
## Bug report 

The containerOptions directive String `opts` gets parsed into a Map of options with:

```groovy
CmdLineHelper.parseGnuArgs(opts.toString())
```

This `parseGnuArgs` method does not support arguments that use the equals sign.

### Expected behavior and actual behavior

When running on the awsbatch executor, this directive will work

```groovy
process Test {
    containerOptions '--shm-size 256'
    "true"
}
```
but if we use an equals sign, the shm-size is set to `true`

```groovy
process Test {
    containerOptions '--shm-size=256'
    "true"
}
```

[Nextflow.log](https://github.com/user-attachments/files/16396739/nextflow.log) attached.

### Steps to reproduce the problem

Evaluate the following small workflow with `process.exectutor 'awsbatch'`:
```groovy
process Test {
    containerOptions '--shm-size=256m'
    "true"
}

workflow {
    Test()
}
```

**Comment by bentsherman** [comment]
Thanks Rob. Conversation has moved, closing in favor of #5190
