### ISSUE TITLE
Input values into clusterOptions

### ISSUE THREAD

**Issue by PeterJackNaylor** [nextflow-io/nextflow#520]
Hi,

First of all, great job with nextflow! 

Second, I am having an issue with using input parameters in the clusterOptions of a process.

To explain: I have a process that will run 3 jobs and I would like to ensure that they go on different computer when they are assigned, and I can do that with -q all.q@compute-0-18, or with -19 or with -20 and so on... (where the interger is a certain computer)
To ensure this, I assign an integer to each input of this process with a tuple and I would like this value to be accessible in clusterOptions.
[... some process before ... ]
```Groovy
def Assign( file ) {
    disk = file.name.split('_')[1].toInteger()
    if( disk == 2 ) {
        18
    }
    else {
        if( disk == 3 ) {
            19
        }
        else {
            20
        }
    }
}
IMAGE_FOLD  .map { file -> tuple(Assign(file), file) }
                 .set { IMAGE_FOLD_AND_COMP }

process PROCESS_SPECIFIC_COMP {
    maxFork = 3
    input:
    set key, file(path) from IMAGE_FOLD_AND_COMP
    output:
    file '*.txt' into results
    clusterOptions = '-S /bin/bash -l mem_free=20G -q all.q@compute-0-${key}'
    """
    echo 'Done' &> res.txt
    """
}
```

In the older versions, nextflow complains that key is not defined. In the newer version he complains that he can't submit to the scheduler as the scheduler doesn't have a queue named all.q@compute-0-${key}.

The process works if I set -q all.q (but jobs will end up on the same computer)

(If it was still the older version) I guess this problem could be fixed by changing the order in which nextflow analysis the code (but this could be very difficult). Would you have a fix? 

Thank you for your help,

Peter

PS: this the output message

```
ERROR ~ Error executing process > 'CreateTFRecords (2)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  qsub -terse .command.run

Command exit status:
  1

Command output:
  Unable to run job: Job was rejected because job requests unknown queue "all.q@compute-0-${key}".
  Exiting.
```

**Comment by pditommaso** [comment]
Thanks for your kind words. 

The problem is that you are using a single quoted string for the `clusterOptions` directive, hence variable are not evaluated. Read more about strings [here](https://www.nextflow.io/docs/latest/script.html#string-interpolation). 

Also note that directives should go before `input`s and do not require the `=` assignment. The right version should look as: 

```
process PROCESS_SPECIFIC_COMP {
    maxFork 3
    clusterOptions  "-S /bin/bash -l mem_free=20G -q all.q@compute-0-${key}"  
    input:
    set key, file(path) from IMAGE_FOLD_AND_COMP
    output:
    file '*.txt' into results

    """
    echo 'Done' &> res.txt
    """
}
```

**Comment by PeterJackNaylor** [comment]
Hey,
Thanks for the quick reply, ok, sorry for that, I didn't realize their was a difference between them.
Works great, thanks :)
