### ISSUE TITLE
Enable use of conda-lock outputs in `conda` declaration

### ISSUE THREAD

**Issue by pinin4fjords** [nextflow-io/nextflow#5219]
## New feature

It would be great if it were trivial to use `conda-lock` outputs in place of environment yml files in the `conda` declaration of Nextflow processes.

## Usage scenario 

conda-lock is a great tool for completely freezing a Conda environment and skipping dependency resolution on install (all packages are mapped to URIs directly). We have [integrations with Wave](https://docs.seqera.io/wave/cli/build-conda), for example, when building containers. 

What would be really awesome would be if Nextflow could handle these lock file natively, so that people working in Conda could benefit from the frozen environments, without using Docker or Wave.

## Suggest implementation 

See https://github.com/nf-core/modules/pull/5827 for context. Basically it would be great to do:

```
-    conda "${moduleDir}/environment.yml"
+    conda "${moduleDir}/conda-lock.yml"
```

... which doesn't currently seem to work.

**Comment by pditommaso** [comment]
it works like that using an http resource for the lock file e.g. 

```
https://prefix.dev/envs/pditommaso/rnaseq-nf/vrsyqix7g4v6/conda-lock.yml
``` 

But I don't see why it should not work with local lock files. Have you tried it?

**Comment by pinin4fjords** [comment]
I was just looking at the CI in the Edmund's PR above, in which it does not appear to have worked. But I'll do some more local testing if you say it should work.

**Comment by pditommaso** [comment]
Not sure to understand why is not working. The cli is built here 

https://github.com/nextflow-io/nextflow/blob/5eeed5bf096c05d77c79863a6d9e48d09cdd5fcc/modules/nextflow/src/main/groovy/nextflow/conda/CondaCache.groovy#L280-L297

Does it require a specific CLI option?

**Comment by pinin4fjords** [comment]
Ahhh, I bet it's because it's a YAML, so recognised as an environment file! Thanks @pditommaso !

**Comment by pinin4fjords** [comment]
Closing since this seems to be already a thing.

**Comment by pinin4fjords** [comment]
@pditommaso , OK, from local testing I think actually the issue was Edmund's usage of `--platform linux-64`. This creates a lockfile with structure for multi-platform, and you have to do a ['render'](https://github.com/conda/conda-lock?tab=readme-ov-file#basic-usage) to get a lock file you can install with a simple conda command. 

Thanks for the help!

**Comment by pinin4fjords** [comment]
So, possibly the only missing part is the ability to use a multi-platform lock file, which would require usage of the `conda-lock` CLI rather than just `conda env`.

**Comment by pinin4fjords** [comment]
So: for a clearer explanation, the issue is actually 'unified' lock files with content like:

```
version: 1
metadata:
  content_hash:
    linux-64: e871e69948829e729df35a3480f230b6b61416af7bbc6dea5ea47473815c0619
    osx-64: 433ef6656d864f1f6708d944c91ea8845338d0b0886bcc64f58c3937adb14f16
    osx-arm64: 123472036111f78b0ea2d2bd33d78adc10cb364774af68a35f43b0430b913c0c
    win-64: cc584a9a1e786512033c55b475048bfee287408615031f9fc1171b79188a5ceb
  channels:
```

These can't be used to create environments via a simple `conda env create` as Nextflow does, instead requiring `conda-lock`. We actually need explicit, platform-specific ones:

```
@EXPLICIT
https://conda.anaconda.org/conda-forge/osx-64/ca-certificates-2024.7.4-h8857fd0_0.conda#7df874a4b05b2d2b82826190170eaa0f
https://conda.anaconda.org/conda-forge/osx-64/libexpat-2.6.2-h73e2aa4_0.conda#3d1d51c8f716d97c864d12f7af329526
https://conda.anaconda.org/conda-forge/osx-64/libffi-3.4.2-h0d85af4_5.tar.bz2#ccb34fb14960ad8b125962d3d79b31a9
```

**Comment by ewels** [comment]
> We actually need explicit, platform-specific ones:

what does "ones" refer to? The file is unified as you say, so only one lock file needs to be specified?

Should be relatively easy for Nextflow to parse the yaml and look for the `version` and `metadata` keys I guess, neither of which I've ever seen in a regular conda env file. Could then run the applicable command to create the environment instead of the regular one.

**Comment by pinin4fjords** [comment]
> > We actually need explicit, platform-specific ones:
> 
> what does "ones" refer to? The file is unified as you say, so only one lock file needs to be specified?

I mean, we can't currently use unified lock files. We have to use non-unified lock files.

I've proposed something based on file extensions (https://github.com/nextflow-io/nextflow/pull/5221), but if @pditommaso is up for the general principle I'd be happy to do some parsing instead.
