### ISSUE TITLE
Add switch to enable environment modules

### ISSUE THREAD

**Issue by emi80** [nextflow-io/nextflow#522]
At the moment, by just defining `module foo/bar`, either through a process directive or a configure option, the `foo/bar` environment module is loaded when the corresponding process is executed.

I think it would be useful to be able to switch modules on and off by using an `enabled` switch like for docker/singularity. This will allow one to keep the configured module in the config file and activate it only when needed.

**Comment by pditommaso** [comment]
Tho I agree this could be useful and consistent with other configuration settings, changing this behaviour would affect existing application, for this reason I think it's better to keep the `module` in it's current form. 

A possible workaround of the problem suggest is to declare the module usage in a separate configuration profile, eg: 

```
profiles {
  EnvModules {
    process.module = 'the/module:1.2'
  }
}
```

Then activate when needed on the command line: 

```
nextflow run <project> -profile EnvModules
```
