### ISSUE TITLE
Azurebatch does not respect "disk" directive

### ISSUE THREAD

**Issue by qup9** [nextflow-io/nextflow#5245]
### Expected behavior and actual behavior

azurebatch process containers allocate 98GB to working space regardless of configuration.

### Steps to reproduce the problem

I am running Nextflow with AzureBatch. The VM's are created with an OS disk of 1000GB. The containers are created during the workflow with an working disk size of ~90GB. I need the container disks to be 200GB. I have tried:

process {
    executor = 'azurebatch'
    queue = 'arm_pool_standard_d4_v3'
    container = params.container
    errorStrategy = 'ignore'    
    containerOptions = '--storage-opt dm.basesize=200G'
and

process {
    executor = 'azurebatch'
    queue = 'arm_pool_standard_d4_v3'
    container = params.container
    errorStrategy = 'ignore'    
    disk = '200.GB'
and

process {
    executor = 'azurebatch'
    queue = 'arm_pool_standard_d4_v3'
    container = params.container
    errorStrategy = 'ignore'    
    disk = '200 GB'
The result is always: Docker Container: az-pass Filesystem Size Used Avail Use% Mounted on /dev/sdb1 98G 2.5G 91G 3% /mnt/batch/tasks

How do I tell nextflow to create my container with 200GB ?

### Program output 

 az-pass Filesystem Size Used Avail Use% Mounted on 
/dev/sdb1 98G 2.5G 91G 3% /mnt/batch/tasks

### Environment 

* Nextflow version: nextflow version 24.07.0-edge.5923
* Java version: [?]
* Operating system: Linux, Ubuntu
* Bash version:  5.1.16(1)-release 

### Additional context
My process is running fasterq-dump on NCBI accessions. Many accessions are over 5GB. fasterq-dump requires ~18 x accession size to safely complete a task.

**Comment by qup9** [comment]
I think this is a needed feature and should be supported.
This is supported most executors and an Google Batch.
I am trying to control costs by using small cheap processors.
Disk space is what I need for the process tasks.

The VM Disk is not the issue. I can control how much space a VM gets by creating the pool and specifying OS disk.
This issue is how much space a container is allocated on the VM
Right now, that is locked at 98GB. My VM has 1TB storage.
Each containers are only allocated 98GB

**Comment by bentsherman** [comment]
Let's keep this discussion going in the other issue, even if it's slightly different, it's part of the larger problem we need to solve which is getting enough disk storage to the task environment
