### ISSUE TITLE
Report  an error message when a config file contains an unresolved attribute

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#525]
Currently any unknown attribute is quietly resolved to an empty map object ie. `[:]`.

This is can be tricky to detect and potentially harmful. The goal of this issue to report an error message when a config file contains an unresolved attribute.

**Comment by ccario83** [comment]
I was having issues with `toList()` hanging so upgraded to 0.27.0, however something else broke that looks related to this feature which was also introduced in 0.27.0.

The gist is I use a custom attribute to build up a complicated data structure that is shared across several workflows. This attribute sometimes requires null values. Is there a quick work around compatible with this feature? I'd like to build this structure in the config file and pass it as a param to all workflows using that config file. Its probably an abuse of nextflow, but I'd like to generate this structure on the fly using other attributes specified in the config file and not as a separate process.

**Comment by pditommaso** [comment]
Hi there, this change does not prevent to use `null` in config attributes/object. It the use of initialised attributes. Could provide an example of your use case and the related error message (the error full stack trace in the log file) ?

**Comment by ccario83** [comment]
I was able to find another work around, but thanks for the response and
help!

On Mon, Feb 26, 2018 at 11:43 PM, Paolo Di Tommaso <notifications@github.com
