### ISSUE TITLE
Filtering a channel using .filter not equivalent to while statement

### ISSUE THREAD

**Issue by quiestrho** [nextflow-io/nextflow#526]
When filtering, here empty, files from a channel, the while approach does not work as expected:
```
process demuxByPrimers {
    publishDir params.outdir

    input:
    file productFile from products

    output:
    file 'ITS*.fastq' into primers mode flatten

    when: 
    productFile.size() > 0

    script:
    println "Processing ${productFile}"
}
```
instead the filter approach works:
```
process demuxByPrimers {
  publishDir params.outdir

  input:
  file productFile from products.filter{ it.size()>0 }

  output:
  file 'ITS*.fastq' into primers mode flatten

  script:
  println "Processing ${productFile}"
}
```
This is confusing and not consistent. See also [my Q on Stack-overflow](https://stackoverflow.com/questions/47401518/nextflow-is-an-input-file-empty/47402555?noredirect=1#comment81782708_47402555).

**Comment by pditommaso** [comment]
This has been solved by #731. Therefore then `when` and `filter` approach work in the same manner using latest versions
