### ISSUE TITLE
Clarification of null string passed to publishdir directive

### ISSUE THREAD

**Issue by markpanganiban** [nextflow-io/nextflow#5269]
We encounter an issue when using "null" as the publishdir:
```
params.outdir = "null"
```

```
WARN: Process `publishReport` publishDir path contains a variable with a null value
```

I believe a null value is very different than a string that happens to contain the characters "null". Why would there be a warning for a specific value of a string?

**Comment by pditommaso** [comment]
I think it was done on purpose because generally it signal an issue with the `outdir` parameter

https://github.com/nextflow-io/nextflow/blob/5a37e6177f7a0e02b2af922768a0df5984b07b7b/modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy#L145-L145

**Comment by sstrong99** [comment]
ok. for my use it would be nice if this behavior were configurable, because we intentionally use string containing "null"

**Comment by pditommaso** [comment]
A path *containing* the `null` is ok, a path == `null` string is interpreted as an error because it was a common pitfall when having a null parameter defined as this 

```
publishDir "$params.foo"
```

**Comment by sstrong99** [comment]
I dont think that's true. See this MWE below:
```
#!/usr/bin/env nextflow

nextflow.enable.dsl = 2

params.outdir = "test/null"

process TEST {

    publishDir = [
        path: { "${params.outdir}" }
    ]

    output:
    path("*.txt")

    script:
    """
    echo "test" > out.txt
    """
}


workflow {
    TEST()
}
```

In this case, the output directory contains the string "null", but the warning still gets printed:
```
$ nextflow run null_outdir.nf 
Nextflow 24.04.4 is available - Please consider updating your version to it

 N E X T F L O W   ~  version 24.04.2

Launching `null_outdir.nf` [irreverent_euler] DSL2 - revision: c6e4ef898c

executor >  local (1)
[30/b0ad16] process > TEST [100%] 1 of 1 ✔
WARN: Process `TEST` publishDir path contains a variable with a null value
```

**Comment by pditommaso** [comment]
it turns out you are right. it checks for `null` in between word boundaries 

https://github.com/nextflow-io/nextflow/blob/main/modules/nextflow/src/main/groovy/nextflow/processor/PublishDir.groovy#L168-L170

Would it work for you enabling path containing the `null` string but not as a path component. for example 

* `/foo/bar-null` OK
* `/foo/nullbar` OK
* `/null` not ok 
* `/foo/null/bar` not ok

**Comment by sstrong99** [comment]
my use case looks like `/foo/null/bar`. but i understand if you think it makes sense to keep the warning for that case.

**Comment by pditommaso** [comment]
Ok, agree.
