### ISSUE TITLE
 Create a community-owned Vim plugin for Nextflow

### ISSUE THREAD

**Issue by rollf** [nextflow-io/nextflow#5272]
[Disclaimer: I'm happy to close this issue and move it somewhere else if necesary]

There is an [extension](https://github.com/nextflow-io/vscode-language-nextflow) for Visual Studio code owned by nixtflow-io (the GitHub organization). Similarly, I'd like to have a community-owned Vim plugin.

My primary motivation is syntax highlighting support. This [project](https://github.com/LukeGoodsell/nextflow-vim) provides some but it is outdated. Several [forks](https://github.com/LukeGoodsell/nextflow-vim/forks) exists but from what I could see, none is really up to date and none is a super set of the others (i.e. the various authors added different keywords for syntax highlighting).

If someone with the necessary rights could create such a Git repo (i.e. github.com/nextflow-io/nextflow-vim (or vim-nextflow or whatever suits you)) and maybe push the current state of LukeGoodsell's initial plugin, I'm happy to take further action:

* Contact fork authors and ask them to add their changes to the (now official) vim plugin
* Add changes myself (via PRs)
* I'd also take care of requesting a change [here](https://github.com/nf-core/website/blame/e6ad95c266905ab764716b4571a3eb19c38d8b16/sites/docs/src/content/docs/contributing/code_editors_and_styling/editor_plugins.md#L75-L77) in order to link to the new repo

**Comment by bentsherman** [comment]
Hi @rollf , if you are willing to consolidate previous work and maintain the project for a while, I think that would be a great idea.

I was wondering, are there any considerations with supporting vim vs neovim? My understanding is that vim uses vimscript while neovim uses Lua, so I'm assuming that you would need two different plugins to support both

**Comment by bentsherman** [comment]
We have created an "official" repo here: https://github.com/nextflow-io/vim-language-nextflow

I have invited you to be a maintainer. Let me know if you need anything, and let us know when it's ready for wider use so that we can promote it

**Comment by rollf** [comment]
Cool, thank you! As I mentioned, I will initially only look into syntax highlighting and keep this vim/neovim-unspecific.

**Comment by rollf** [comment]
FYI, @LukeGoodsell @varunkas @LokiLuciferase @Mxrcon your syntax highlighting implementations/improvements are now in this official Vim plugin. Feel free to further improve.
