### ISSUE TITLE
`nextflow run` from GitHub fails to override default parameters with command line arguments

### ISSUE THREAD

**Issue by alexdhill** [nextflow-io/nextflow#5285]
## Bug report 

The documented behavior of parameters in nextflow is not consistent when a repository is cloned and run locally, as opposed to being run directly from a GitHub repository.

### Expected behavior and actual behavior

Parameters defined in the `nextflow.config` are not overridden by command line flags when being run from a repository.

### Steps to reproduce the problem

Push dummy pipeline to github:
main.nf empty
nextflow.config:
```
params.test = false
if (params.test) {
  println "Testing"
} else {
  println "Not Testing"
}
```

run `nextflow run user/repo --test`

EDIT: I have created this repo for testing:
`nextflow run alexdhill/DELETE --test`

### Program output 

"Not Testing"

### Environment 

* Nextflow version: 24.04.2
* Java version: 11.0.1
* Operating system: Ubuntu 22.04
* Bash version: 5.1.16(1)

**Comment by alexdhill** [comment]
I've noticed through testing this seems to be a two part issue, when creating my dummy repo above nextflow will print twice. The first pass does NOT respect the command line flags, but the second time will?  
  
Local runs of the pipeline do not seem to process the nextflow.config twice.

**Comment by pditommaso** [comment]
The final configuration is expected to be accessed in the main script, not in the config.
