### ISSUE TITLE
HTML DAG gives syntax error in text

### ISSUE THREAD

**Issue by gregorysprenger** [nextflow-io/nextflow#5301]
### Expected behavior and actual behavior

HTML DAG should be displayed but it is giving the following error:
![image](https://github.com/user-attachments/assets/3aa26d7e-6041-43ea-8736-d9e0975d39b4)

### Steps to reproduce the problem

I haven't went through ALL nf-core pipelines to see if this affects them, but it does effect nf-core/sarek.
Link to nf-core/sarek's DAG: https://nf-co.re/sarek/3.4.4/results/sarek/results-5cc30494a6b8e7e53be64d308b582190ca7d2585/test_aws/pipeline_info/?file=pipeline_dag_2024-09-03_12-08-06.html

### Program output 

Here is the nf-core/sarek HTML dag file. Note I had to convert it to a text file due to HTML files not allowed for upload.

[pipeline_dag_2024-09-03_12-08-06.txt](https://github.com/user-attachments/files/16981153/pipeline_dag_2024-09-03_12-08-06.txt)

### Environment 

FireFox version 115.15.0esr (64-bit)
Chrome version 128.0.6613.138 (64-bit)
Edge version 128.0.2739.67 (64-bit)

**Comment by bentsherman** [comment]
Looks like the same issue we found in nf-prov. Add these options to the embedded JS code:

**Comment by bentsherman** [comment]
Looks like the same issue we found in nf-prov. Add these options to the embedded JS code:
```js
  mermaid.initialize({ startOnLoad: true, maxTextSize: Number.MAX_SAFE_INTEGER, maxEdges: Number.MAX_SAFE_INTEGER });
```

I will make a PR to add these options by default
