### ISSUE TITLE
Direct selection the process output to be published using 'publishDir'

### ISSUE THREAD

**Issue by JoseEspinosa** [nextflow-io/nextflow#532]
For instance in this example, we may want to publish txt and foo outputs but not bar. The idea will be to directly select the processes, something like ```publishDir path: 'results',  process: 'txt bar' ``` will do the trick. 

```bash
process foo {

publishDir path: 'results',  pattern: "*.txt"

input: 
each x from 1,2,3

output: 
file '*.txt' into txt
file '*.foo' into foo
file '*.bar' into bar

"""
touch file_${x}.txt
touch ${x}.foo
touch ${x}.bar
"""
}
```

**Comment by pditommaso** [comment]
I'm not understanding why the `pattern` option won't work in this case. You could do: 

```
process foo {
  publishDir `results`, pattern: '*.{txt,bar}'
  .. 
}

**Comment by pditommaso** [comment]
Support for multiple `publishDir` (see #256) should solve this problem, therefore I'm closing this.
