### ISSUE TITLE
PBS `task.attempt` error

### ISSUE THREAD

**Issue by apeltzer** [nextflow-io/nextflow#533]
Hi! 

**What I did**
I tried running the NGI-RNAseq pipeline on some data to test the output and was able to run it locally and also with a basic configuration on my cluster environment (PBS/Torque) with a very basic configuration, where I don't access any dynamic resource variables at all (e.g. specifying once 20 cores, 160hours and 60GB memory.

** Error case**
I then tried running my own configuration for the cluster and created a profile using the `base` configuration for NGI-RNAseq and combining it with our local cluster config that worked previously. 

This is the config:

```
/*
vim: syntax=groovy
-*- mode: groovy;-*-
 * -------------------------------------------------------------
 *  Nextflow config file for use with Singularity on CFC cluster
 * -------------------------------------------------------------
 * Defines basic usage limits and singularity image id.
 */

singularity {
    enabled = true
}

process {
    executor = 'pbs'
    container = '/path/to/ngi-rnaseq.img'
    queue = 'cfc'
    clusterOptions = { "-l ppn=${process.cpus}:walltime=${process.time}:mem=${process.memory}:cfc" }
}

params {
  max_memory = 60.GB
  max_cpus = 20
  max_time = 140.h
}
```
I furthermore added the profile to the main nextflow.config by adding this, so the base.config from NGI-RNAseq is added with my cfc.config. 
``` 
profiles {

  cfc {
    includeConfig 'conf/base.config'
    includeConfig 'conf/cfc.config'
  }
....
``` 

When I run the project, I get this kind of error message by nextflow when it tries to run the job:

```
[warm up] executor > pbs
ERROR ~ Error executing process > 'trim_galore (QFBPR043A6)'

Caused by:
  No signature of method: java.lang.Integer.multiply() is applicable for argument types: (groovy.util.ConfigObject) values: [[:]]
Possible solutions: multiply(java.lang.Number), multiply(java.lang.Character)

Source block:
  c_r1 = clip_r1 > 0 ? "--clip_r1 ${clip_r1}" : ''
  c_r2 = clip_r2 > 0 ? "--clip_r2 ${clip_r2}" : ''
  tpc_r1 = three_prime_clip_r1 > 0 ? "--three_prime_clip_r1 ${three_prime_clip_r1}" : ''
  tpc_r2 = three_prime_clip_r2 > 0 ? "--three_prime_clip_r2 ${three_prime_clip_r2}" : ''
  if (params.singleEnd) {
      """
      trim_galore --fastqc --gzip $c_r1 $tpc_r1 $reads
      """
  } else {
      """
      trim_galore --paired --fastqc --gzip $c_r1 $c_r2 $tpc_r1 $tpc_r2 $reads
      """
  }
```
My idea was now to figure out what is wrong, by looking at the `base.config` file and trying to determine what is multiplied here: https://github.com/SciLifeLab/NGI-RNAseq/blob/5128216444c338b399a498ca5e75e702ce648a91/conf/base.config#L15

I then added a small statement to the `base.config` to print out the content of `task.attempt` and found it to be set to: `[:]` apparently. 

I guess that 

- either my custom PBS parameters are handled differently (although the cfc.config file worked before without the base.config)
- the task.attempt variable is not set when running on PBS/Torque schedulers

There is no .command.log etc created as the process dies immediately after start when trying to calculate the resources required for running the whole pipeline. 

If I can help to resolve it, I'm more than happy to do some more tests and/or provide some examples etc.

**Comment by pditommaso** [comment]
What version of NF is ?

**Comment by apeltzer** [comment]
Sorry, forgot the version. Its 0.26.1 and Java 8 environment is also installed

**Comment by pditommaso** [comment]
It looks this problem https://github.com/nextflow-io/nextflow/issues/525. 

But still I don't see how `task.attempt`. I need all the files to be able to replicate the issue.

**Comment by apeltzer** [comment]
Indeed I think this could be the case. I attach the base.config, cfc.config which are loaded in nextflow.config as a separate profile (had to attach *.txt endings for GitHub compatibility). 

[base.config.txt](https://github.com/nextflow-io/nextflow/files/1500053/base.config.txt)
[cfc.config.txt](https://github.com/nextflow-io/nextflow/files/1500054/cfc.config.txt)
[nextflow.config.txt](https://github.com/nextflow-io/nextflow/files/1500055/nextflow.config.txt)

Everything else is 1:1 as in https://github.com/SciLifeLab/NGI-RNAseq, also the container is simply a docker2singularity conversion of the docker container they provide and runs fine if tested locally.

**Comment by pditommaso** [comment]
In the `base.config` there a line that's suspect 

```
 System.err.println(task.attempt)
```

Does the error show w/o it?

**Comment by apeltzer** [comment]
Yes. I added that to find out to which value the task.attempt variable was set. If I remove it, the same error rises.

**Comment by pditommaso** [comment]
Could you try the latest snapshot and report if something change: 

```
NXF_VER=0.27.0-SNAPSHOT nextflow run .. etc 
```

**Comment by apeltzer** [comment]
Running it now - seems to be working then :-)

**Comment by apeltzer** [comment]
Jobs are working fine in the environment now - nothing breaking down and the jobs were failing quite quickly so I guess we're good now!

**Comment by apeltzer** [comment]
No, unfortunately, the same error happens. 

```
[warm up] executor > pbs
[6c/78651f] NOTE: Error submitting process 'fastqc (QFBPR057AB)' for execution -- Error is ignored
ERROR ~ Error executing process > 'trim_galore (QFBPR044AE)'

Caused by:
  No signature of method: java.lang.Integer.multiply() is applicable for argument types: (groovy.util.ConfigObject) values: [[:]]
Possible solutions: multiply(java.lang.Character), multiply(java.lang.Number)

Source block:
  c_r1 = clip_r1 > 0 ? "--clip_r1 ${clip_r1}" : ''
  c_r2 = clip_r2 > 0 ? "--clip_r2 ${clip_r2}" : ''
  tpc_r1 = three_prime_clip_r1 > 0 ? "--three_prime_clip_r1 ${three_prime_clip_r1}" : ''
  tpc_r2 = three_prime_clip_r2 > 0 ? "--three_prime_clip_r2 ${three_prime_clip_r2}" : ''
  if (params.singleEnd) {
      """
      trim_galore --fastqc --gzip $c_r1 $tpc_r1 $reads
      """
  } else {
      """
      trim_galore --paired --fastqc --gzip $c_r1 $c_r2 $tpc_r1 $tpc_r2 $reads
      """
  }
```

**Comment by apeltzer** [comment]
I submitted the same configuration on a different cluster system (that does not require the extra config options and it works there).

**Comment by pditommaso** [comment]
So, does it works with the `0.27.0-SNAPSHOT` or not? :)

**Comment by apeltzer** [comment]
Apparently, if I don't specify a custom cluster options it does. If I do (required for our second testing cluster), it does not work.

**Comment by apeltzer** [comment]
So when executing on our bigger cluster - things are fine with 0.27-SNAPSHOT. On the other cluster (the one requiring the custom options), things still fail. Other than the custom Options, nothing different.

**Comment by pditommaso** [comment]
I'm sorry but I'm unable to replicate the issue in this way. You should provide a minimal test (files and command line) that isolate the problem and would allow me to debug and fix it.

**Comment by apeltzer** [comment]
I'll create one and come back to you here within the ticket once I created one.

**Comment by pditommaso** [comment]
I'm closing this issue because there's no feedback anymore. Feel free to comment/reopen if needed.
