### ISSUE TITLE
Limit the rate of staging foreign files onto S3

### ISSUE THREAD

**Issue by logust79** [nextflow-io/nextflow#5335]
I have a process with each job having 50 files to be staged on S3 for AWSBatch processing. However I always hit "Timeout waiting for connection from pool" (.nextflow.log: error [com.amazonaws.SdkClientException]: Unable to execute HTTP request: Timeout waiting for connection from pool).

I assume this is hitting the limit of concurrent file transfers onto S3 (each of those 50 files is large). I wonder if there is a setting to limit the number of files being staged at the same time?

**Comment by logust79** [comment]
I stop getting this error when I limit the number of input files for each job to 10. So this is nothing to do with the rate of staging, but rather with settings on AWSBatch. I will explore further.

**Comment by bentsherman** [comment]
Which versions of Nextflow and Java are you using? There might be another factor involved here

**Comment by logust79** [comment]
> Which versions of Nextflow and Java are you using? There might be another factor involved here
Nextflow version is 24.04.4, java is 21, on Amazon linux 2

I've done some combinations and it seems to trigger this error when input files are on a mounted device. The error stopped showing up after I copied the input files onto local drive.

**Comment by bentsherman** [comment]
> Nextflow version is 24.04.4, java is 21, on Amazon linux 2

That means virtual threads are being enabled by default, which we have recently seen causing file staging issues for some users

You might also try your initial setup with virtual threads disabled:
```bash
export NXF_ENABLE_VIRTUAL_THREADS=false
```

They will be disabled by default in the next stable release

**Comment by logust79** [comment]
Thanks a lot for the tip! I will give it a try and let you know.
