### ISSUE TITLE
Issue with overriding entryPoint using containerOptions for AWS Batch

### ISSUE THREAD

**Issue by ylz0** [nextflow-io/nextflow#5340]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

Trying to run this container in a Nextflow Process: https://hub.docker.com/r/cdcgov/seqsender

process seqsender_prep {
    
    container 'cdcgov/seqsender:latest'
    containerOptions "--entrypoint=''"
    script:
    """
   chmod +x /seqsender/seqsender-kickoff
   micromamba run -n base seqsender-kickoff prep ${getDatabaseFlags()} \\
                   --organism ${params.organism} \\
                   --submission_name ${params.submission_name}_${sample_id} \\
                   --submission_dir ${sample_staging_dir} \\
                   --config_file seqsender_config.yaml \\
                   --metadata_file metadata.csv \\

"""
}

This container has a default entrypoint of tail -f /dev/null
I am trying to override it using containerOptions "--entrypoint=''" (I tried /bin/bash but that did not work when running locally)

The expected behavior is for the script to be executed, but it fails because the entrypoint does not get overriden. This is ONLY for AWS Batch.

### Steps to reproduce the problem

main.nf:

```
#!/usr/bin/env nextflow
nextflow.enable.dsl=2

process seqsender_prep {

    container 'cdcgov/seqsender:latest'
    containerOptions "--entrypoint=''"
    
    script:
    """
    echo "Running seqsender prep"
    micromamba run -n base seqsender-kickoff prep --help

    """

}
workflow{
     seqsender_prep()
}

```

nextflow.config:

```
profiles {
    debug { process.beforeScript = 'echo $HOSTNAME' }
    conda {
        params.enable_conda    = true
        docker.enabled         = false
        singularity.enabled    = false
        podman.enabled         = false
        shifter.enabled        = false
        charliecloud.enabled   = false
    }
    docker {
        docker.enabled         = true
        docker.userEmulation   = true
        singularity.enabled    = false
        podman.enabled         = false
        shifter.enabled        = false
        charliecloud.enabled   = false
    }
    singularity {
        singularity.enabled    = true
        singularity.autoMounts = true
        docker.enabled         = false
        podman.enabled         = false
        shifter.enabled        = false
        charliecloud.enabled   = false
    }
    podman {
        podman.enabled         = true
        docker.enabled         = false
        singularity.enabled    = false
        shifter.enabled        = false
        charliecloud.enabled   = false
    }
    shifter {
        shifter.enabled        = true
        docker.enabled         = false
        singularity.enabled    = false
        podman.enabled         = false
        charliecloud.enabled   = false
    }
    charliecloud {
        charliecloud.enabled   = true
        docker.enabled         = false
        singularity.enabled    = false
        podman.enabled         = false
        shifter.enabled        = false
    }
}

process {
    executor = 'awsbatch'
    queue = 'xxxxxxx'
}
 
aws {
    region = 'us-east-1'
    batch {
        cliPath = '/home/ec2-user/miniconda/bin/aws'
    }
}
```

`nextflow run main.nf -profile docker -work-dir <xxx>`

### Program output 

```
ERROR nextflow.processor.TaskProcessor - Error executing process > 'seqsender_prep (USA-CDC-CAU-B0049)'

Caused by:
  Essential container in task exited


Command executed:

  micromamba run -n base seqsender-kickoff prep --biosample --sra \
                 --organism OTHER \
                 --submission_name C_auris_test_submission_09252024_USA-CDC-CAU-B0049 \
                 --submission_dir C_auris_test_submission_09252024 \
                 --config_file seqsender_config.yaml \
                 --metadata_file metadata.csv \

Command exit status:
  1

Command output:
  (empty)

Command error:
  tail: invalid option -- 'o'
  Try 'tail --help' for more information.

```
### Environment 

* Nextflow version: [24.04.4 build 5917] 
* Java version: [17.0.11]
* Operating system: [WSL]
* Bash version: (5.2.21)

### Additional context

I tried all these different variations based on issues already reported but no luck:

containerOptions "--entrypoint ''"
containerOptions "-entrypoint ''"
containerOptions 'entrypoint' : ''
containerOptions "--entrypoint /bin/bash"
containerOptions "-entrypoint /bin/bash"
containerOptions 'entrypoint' : '/bin/bash'

**Comment by bentsherman** [comment]
Looks like the `--entrypoint` option is not supported by AWS Batch: https://nextflow.io/docs/latest/aws.html#container-options

**Comment by ylz0** [comment]
I see, thanks for sharing. Is that something we can make a feature request for?

> Looks like the `--entrypoint` option is not supported by AWS Batch: https://nextflow.io/docs/latest/aws.html#container-options

**Comment by bentsherman** [comment]
You'll have to take it up with AWS Batch, we have no control over this

**Comment by ylz0** [comment]
> You'll have to take it up with AWS Batch, we have no control over this

Sorry I misunderstood. So you are saying AWS Batch does not support --entrypoint at all, not just through Nextflow. Thank you.
