### ISSUE TITLE
Java critical error when running illumination

### ISSUE THREAD

**Issue by eisele24** [nextflow-io/nextflow#5341]
Hi all!

I am utilizing nextflow to analyze cyclic IF data beginning with the illumination step. Unfortunately, I am getting the recurring error below. Steps I have taken to try and troubleshoot include installing Java 21, increasing my CPU and memory allotment in docker, trying to force a switch from amd64 to arm64 (since I am operating on a new Mac but admittedly I don't know if I was successful in trying to make that switch), and running the code suggested below to allow core dumps. Any input or suggestions you have to navigate this error would be greatly appreciated!

Caprice

(scimap) eisele.24@CC-4406NW ~ % nextflow run labsyspharm/mcmicro --in /Volumes/T7\ Shield/OSU/CCGYN1032EC

 N E X T F L O W   ~  version 24.04.4

Launching `https://github.com/labsyspharm/mcmicro` [stoic_mirzakhani] DSL2 - revision: e67733e288 [master]

executor >  local (14)
[-        ] staging:phenoimager2mc      -
[41/2a793b] illumination (8)            [ 42%] 6 of 14
[-        ] registration:ashlar         -
[-        ] background:backsub          -
[-        ] dearray:coreograph          -
[-        ] dearray:roadie:runTask      -
[-        ] segmentation:roadie:runTask -
[-        ] segmentation:worker         -
[-        ] segmentation:s3seg          -
[-        ] quantification:mcquant      -
[-        ] downstream:worker           -
[-        ] viz:autominerva             -
ERROR ~ Error executing process > 'illumination (10)'

Caused by:
  Process `illumination (10)` terminated with an error exit status (134)

Command executed:

  /opt/fiji/Fiji.app/ImageJ-linux64 --ij2 --headless       --run /opt/fiji/imagej_basic_ashlar.py       'filename="CC1032_Panel08.czi",output_dir=".",experiment_name="CC1032_Panel08.czi"'

Command exit status:
  134

Command output:
  #
  # A fatal error has been detected by the Java Runtime Environment:
  #
  #  Internal Error (safepoint.cpp:388), pid=8, tid=0x00002aab406d6700
  #  guarantee(PageArmed == 0) failed: invariant
  #
executor >  local (14)
[-        ] staging:phenoimager2mc      -
[1f/354852] illumination (13)           [100%] 7 of 7, failed: 1
[-        ] registration:ashlar         -
[-        ] background:backsub          -
[-        ] dearray:coreograph          -
[-        ] dearray:roadie:runTask      -
[-        ] segmentation:roadie:runTask -
[-        ] segmentation:worker         -
[-        ] segmentation:s3seg          -
[-        ] quantification:mcquant      -
[-        ] downstream:worker           -
[-        ] viz:autominerva             -
ERROR ~ Error executing process > 'illumination (10)'

Caused by:
  Process `illumination (10)` terminated with an error exit status (134)

Command executed:

  /opt/fiji/Fiji.app/ImageJ-linux64 --ij2 --headless       --run /opt/fiji/imagej_basic_ashlar.py       'filename="CC1032_Panel08.czi",output_dir=".",experiment_name="CC1032_Panel08.czi"'

Command exit status:
  134

Command output:
  #
  # A fatal error has been detected by the Java Runtime Environment:
  #
  #  Internal Error (safepoint.cpp:388), pid=8, tid=0x00002aab406d6700
  #  guarantee(PageArmed == 0) failed: invariant
  #
  # JRE version: OpenJDK Runtime Environment (8.0_322-b06) (build 1.8.0_322-b06)
  # Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)
  # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
  #
  # An error report file with more information is saved as:
  # hs_err_pid8.log
  #
  # If you would like to submit a bug report, please visit:
  #   http://bugreport.java.com/bugreport/crash.jsp
  #

Command error:
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
  OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
  Sep 26, 2024 7:49:41 PM java.util.prefs.FileSystemPreferences$1 run
  INFO: Created user preferences directory.
  #
  # A fatal error has been detected by the Java Runtime Environment:
  #
  #  Internal Error (safepoint.cpp:388), pid=8, tid=0x00002aab406d6700
  #  guarantee(PageArmed == 0) failed: invariant
  #
  # JRE version: OpenJDK Runtime Environment (8.0_322-b06) (build 1.8.0_322-b06)
  # Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)
  # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
  #
  # An error report file with more information is saved as:
  # hs_err_pid8.log
  #
  # If you would like to submit a bug report, please visit:
  #   http://bugreport.java.com/bugreport/crash.jsp
  #
  qemu: uncaught target signal 6 (Aborted) - core dumped
  .command.sh: line 2:     8 Aborted                 /opt/fiji/Fiji.app/ImageJ-linux64 --ij2 --headless --run /opt/fiji/imagej_basic_ashlar.py 'filename="CC1032_Panel08.czi",output_dir=".",experiment_name="CC1032_Panel08.czi"'

Work dir:
  /Users/eisele.24/work/65/65b42ac9f3daaa2b21f3c1c9debca4

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Comment by eisele24** [comment]
Hi again,

I just wanted to follow up on the issue I had posted yesterday that I still have not been able to resolve. I am happy to try any recommendations or suggestions you may have, and just wanted to make sure that my issue submitted above was still going to be addressed.

Thanks so much!
Caprice

**Comment by pditommaso** [comment]
You issue report is unreadable

**Comment by bentsherman** [comment]
Fixed your comment for readability. In the future please put the log text in a code block so that it is formatted correctly

It looks like the tool you used in the process crashed. The Java error is coming not from Nextflow but from the tool which I assume is running on the JVM

**Comment by eisele24** [comment]
Thank you for the advice! I'm not a very experienced coder so I wasn't aware of how to properly submit an issue. I will make sure to format it that way in the future. Do you have any advice for troubleshooting the Java error? or any work arounds for the issue that might be happening?

**Comment by bentsherman** [comment]
I would talk to whoever maintains this tool:
```bash
/opt/fiji/Fiji.app/ImageJ-linux64 --ij2 --headless --run /opt/fiji/imagej_basic_ashlar.py # ...
```

Maybe your sysadmin or someone else in your organization. I suspect something is misconfigured in your environment but I really don't know

**Comment by eisele24** [comment]
okay thank you! I will look more into that, glad to know that there doesn't seem to be an issue with how I'm running nextflow otherwise.
