### ISSUE TITLE
fromFilePairs 'flat' still includes the grouping key (misunderstanding of the documentation)

### ISSUE THREAD

**Issue by Gullumluvl** [nextflow-io/nextflow#5349]
## Bug report 

Hi, sorry it's a very minor concern:

I am using `Channel.fromFilePairs('basename*{1,2}.ext', flat: true)` and it returns tuples of size 3 that *include the grouping key* such as:

    [basename_aa, /path/to/basename_aa1.ext, /path/to/basename_aa2.ext]

while the documentation states:

> `flat` : When `true` the matching files are produced as **sole** elements in the emitted tuples

(emphasis mine).

https://github.com/nextflow-io/nextflow/blob/324de3d162e476ed3bf58a9c77ae8e95e27cb3ee/docs/reference/channel.md?plain=1#L233

### Expected behavior and actual behavior

Not sure. I think I would prefer the behavior described in the documentation (i.e. remove the grouping key):

    [/path/to/basename_aa1.ext, /path/to/basename_aa2.ext]

### Environment 

* Nextflow version: 24.04.4
* Java version: openjdk version "21.0.5-ea" 2024-10-15
* Operating system: Debian Trixie
* Bash version: 5.2.32

**Comment by bentsherman** [comment]
"sole elements" just means that the list of files is flattened, not that the grouping key is excluded

cc @christopher-hakkaart in case you think there's a better way to describe this

**Comment by bentsherman** [comment]
@Gullumluvl you can achieve what you want by tacking on a map operator:

```groovy
Channel.fromFilePairs('basename*{1,2}.ext', flat: true)
  .map { it -> it.tail() }
```

**Comment by Gullumluvl** [comment]
Aaah my bad, this meaning did not occur to me, sorry!

I was doing the removal like you show in the second block, but thanks for reminding me of `.tail()` as well!

**Comment by bentsherman** [comment]
Okay I'll leave it for now and if it comes up again we can change it
