### ISSUE TITLE
FIxedInputStream raises false error when reading only part of a file

### ISSUE THREAD

**Issue by bentsherman** [nextflow-io/nextflow#5360]
`FixedInputStream` was added to detect truncated files:

https://github.com/nextflow-io/nextflow/blob/324de3d162e476ed3bf58a9c77ae8e95e27cb3ee/modules/nf-httpfs/src/main/nextflow/file/http/FixedInputStream.groovy#L67-L72

However this does not handle the case where only part of a file is read. Consider this example from sarek:

```groovy
// Get first line of a FASTQ file
def readFirstLineOfFastq(path) {
    def line = null
    try {
        path.withInputStream {
            InputStream gzipStream = new java.util.zip.GZIPInputStream(it)
            Reader decoder = new InputStreamReader(gzipStream, 'ASCII')
            BufferedReader buffered = new BufferedReader(decoder)
            line = buffered.readLine()
            assert line.startsWith('@')
        }
    } catch (Exception e) {
        log.warn "FASTQ file(${path}): Error streaming"
        log.warn "${e.message}"
    }
    return line
}
```

It will log this error every time:
```
Read data length does not match expected size - bytes read: 2756; expected: 16013759
```

cc @maxulysse

**Comment by pditommaso** [comment]
Related to https://github.com/nextflow-io/nextflow/pull/5275

**Comment by pditommaso** [comment]
Solved by https://github.com/nextflow-io/nextflow/pull/5405
