### ISSUE TITLE
s3 path is in the saveAs parameter of a publishDir directive are not considered as s3 path

### ISSUE THREAD

**Issue by MaxUlysse** [nextflow-io/nextflow#538]
The following snippet has some problem when used with params `outDir` being an `s3` bucket
```
publishDir '.', saveAs: { it == "${bam}.metrics" ? "${params.outDir}/results/${it}" : "${params.outDir}/metrics/${it}" }, mode: 'copy'
```
The files are saved in the current directory in `s3/bucketname/results/...` or `s3/bucketname/metrics/...`.

I'm guessing that this snippet make more sense as I'm writing this issue
```
publishDir params.outDir, saveAs: { it == "${bam}.metrics" ? "results/${it}" : "metrics/${it}" }, mode: 'copy'
```
and indeed, once the `s3` bucket is specified outside the `saveAs` parameter, it is considered as it should be.

So not exactly an issue and more something like a bad practice people should avoid...
But I figured you might still wanted to know about it.

**Comment by pditommaso** [comment]
Interesting point. The `saveAs` path is resolved agains the main publish path, that is `'.'` in your example. 

So the real question is: should `publishDir '.'` refers to the launch local dir or the pipeline work dir (s3) in this case. I would say the former. 

A workaround is that your return a `file('s3://something')` in your `saveAs` rule.

**Comment by MaxUlysse** [comment]
Oh I see, the `publishDir '.'` is definitively a bad idea...
Thanks for your reply
