### ISSUE TITLE
Consider exposing trace record meta info in the task context

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#5396]
Nextflow collects several task execution metadata modelled as TraceRecord

https://github.com/nextflow-io/nextflow/blob/fba206b586a7629f4f061f8ae3dbb883c90fd8b8/modules/nextflow/src/main/groovy/nextflow/processor/TaskHandler.groovy#L172-L228

These information are stored in the local execution KV store, however are not directly accessible in the execution context. 

There are use cases in which it would be convenient e.g. https://github.com/nextflow-io/nextflow/discussions/5378. 

The goal of this issues is to explore the ability to expose those metadata in the task execution context as it's done for the `task` config object using for example `trace` implicit variable. 

I could see two possible implementation, one accessible that record via TaskHandler reference. Alternatively accessing the trace record via the nextflow [embedded KV store](https://github.com/nextflow-io/nextflow/blob/fba206b586a7629f4f061f8ae3dbb883c90fd8b8/modules/nextflow/src/main/groovy/nextflow/cache/CacheDB.groovy#L80-L80).

**Comment by jorgee** [comment]
I have looked at the code. I think the easier is to modify TaskProcessor.finalizeTask to pass the handler instead of just the TaskRun. Then, generate the record and add it to the context. I would also move the generation of the record and put to the CacheDB in finalizeTask to avoid generating the code twice.

**Comment by pditommaso** [comment]
Interesting, let's give it a try
