### ISSUE TITLE
Accept config from YAML/JSON

### ISSUE THREAD

**Issue by bskubi** [nextflow-io/nextflow#5398]
I am working on a Python-based guided-track tool to let users set config for my Nextflow pipeline. I wrote a parser that can format Python dicts into a nextflow.config file. This is relatively easy as I am starting with a structured object.

However, going in the reverse direction will be harder, if I want to write my own parser for a nextflow.config file. I would like to avoid this. Is there an easy way to convert a nextflow.config file to something more standard, like JSON or YAML? Or could such a feature be implemented? I think an extra benefit is that this would potentially allow Nextflow pipelines with complex config to be "driven" by some other process from arbitrary other programming languages. It would become relatively straightforward to create new user interfaces for building config for a specific pipeline and running it.

**Comment by pditommaso** [comment]
Using `nextflow config -f` print the config as dot property notation. it should be relatively easy to convert to json having that

**Comment by pditommaso** [comment]
I wanted to give a try to this, I've added `-o yaml` and `-o json` output options to the `config` command.

**Comment by bentsherman** [comment]
We are working on a config parser for Nextflow #4744 , but agree that it would be good to support JSON/YAML input/output for integrating with external systems

#5399 will add JSON/YAML output, so beyond that we just need to add JSON/YAML input in the run command

**Comment by bentsherman** [comment]
I think we still need to implement the other direction i.e. accepting JSON/YAML config files as input

**Comment by pditommaso** [comment]
To be discussed. That could be a good option, but it should be considered as a replacement of current config. For that we have https://github.com/nextflow-io/nextflow/issues/2723

**Comment by bentsherman** [comment]
Indeed. I'll add some notes there. @bskubi feel free to follow #2723 for updates
