### ISSUE TITLE
Document `conda.channels` config settings

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#5421]
The `conda.channels` allow specifying the Conda channels that should be used to resolve `conda` packages 

The value can be either a list object eg. 

```
conda.channels = ['bioconda','conda-forge']
```

or comma separated list string eg.

```
conda.channels = 'bioconda,conda-forge'
```

https://github.com/nextflow-io/nextflow/blob/7912bd45b68c3fae087447241d6e62385c51dfd3/modules/nextflow/src/main/groovy/nextflow/conda/CondaConfig.groovy#L50-L59

**Comment by ewels** [comment]
We need to be very clear about order of precedence here, ideally with a corresponding conda `environment.yml` file to match against.
