### ISSUE TITLE
Resume namespace errors

### ISSUE THREAD

**Issue by LouisLeNezet** [nextflow-io/nextflow#5439]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

I'm using a fasta index from a nf-core repository and I would like to resume the processes if it does not change.
However the hashes are different each time the pipeline is ran.
If the file is downloaded locally it doesn't work either but works if the file name is changed.

### Steps to reproduce the problem

First download the files:

```bash
wget https://raw.githubusercontent.com/nf-core/test-datasets/phaseimpute/hum_data/reference_genome/GRCh38.s.fa.gz
wget https://raw.githubusercontent.com/nf-core/test-datasets/phaseimpute/hum_data/reference_genome/GRCh38.s.fa.gz.fai
wget https://raw.githubusercontent.com/nf-core/test-datasets/phaseimpute/hum_data/reference_genome/GRCh38.s.fa.gz.fai -O GRCh383.s.fa.gz.fai
cp GRCh38.s.fa.gz.fai GRCh384.s.fa.gz.fai
```

Then create a `test.nf` file with:

```nextflow
include { SAMTOOLS_FAIDX as FAIDX_1 } from './modules/nf-core/samtools/faidx'
include { SAMTOOLS_FAIDX as FAIDX_2 } from './modules/nf-core/samtools/faidx'
include { SAMTOOLS_FAIDX as FAIDX_3 } from './modules/nf-core/samtools/faidx'
include { SAMTOOLS_FAIDX as FAIDX_4 } from './modules/nf-core/samtools/faidx'

workflow {
    main:
    ch_fasta = Channel.of( [[genome: "GRCh38"],
        "./GRCh38.s.fa.gz"
    ])

    ch_fai = Channel.of([[genome: "GRCh38"],
        "https://raw.githubusercontent.com/nf-core/test-datasets/phaseimpute/hum_data/reference_genome/GRCh38.s.fa.gz.fai"
    ])

    ch_fai2 = Channel.of([[genome: "GRCh38"],
        file("./GRCh38.s.fa.gz.fai")
    ])

    ch_fai3 = Channel.of([[genome: "GRCh38"],
        file("./GRCh383.s.fa.gz.fai")
    ])

    ch_fai4 = Channel.of([[genome: "GRCh38"],
        file("./GRCh384.s.fa.gz.fai")
    ])

    FAIDX_1( ch_fasta, ch_fai)
    FAIDX_2( ch_fasta, ch_fai2)
    FAIDX_3( ch_fasta, ch_fai3)
    FAIDX_4( ch_fasta, ch_fai4)
}
```

And run the following to command

```bash
nextflow -log run1.log run test.nf -profile singularity -dump-hashes json
nextflow -log run2.log run test.nf -profile singularity -dump-hashes json -resume
```

### Program output 

```log
[d4/536b15] FAIDX_1 (GRCh38.s.fa.gz) [100%] 1 of 1 ✔
[d7/0a3ee5] FAIDX_2 (GRCh38.s.fa.gz) [100%] 1 of 1 ✔
[5f/ef5be1] FAIDX_3 (GRCh38.s.fa.gz) [100%] 1 of 1, cached: 1 ✔
[55/b3a08a] FAIDX_4 (GRCh38.s.fa.gz) [100%] 1 of 1, cached: 1 ✔
```

### Environment 

* Nextflow version: 24.04
* Java version: openjdk 17.0.10-internal 2024-01-16
* Operating system: wsl
* Bash version: (use the command `$SHELL --version`): GNU bash, version 5.0.17

### Additional context

(Add any other context about the problem here)

**Comment by LouisLeNezet** [comment]
I agree that this should happen for `FAIDX_1` but why would it happen with `FAIDX_2` ?
The file for `FAIDX_2` is already downloaded locally and copy pasting it make the resume function works.

**Comment by jorgee** [comment]
I have found what is happening. The samtools used in FAIDX are generating a ${fasta}.fai file task. In FAIDX_3 and FAIDX_4, the input fai is different as the generated, but in FAIDX_2, it is the same as the input file. So, it is modifying the file (maybe the content is the same, but the modified date is different). If you run `ls -l` at the end of the execution you will see that the date has been modified.

**Comment by ewels** [comment]
@LouisLeNezet can we set the `cache` mode to `lenient` for this process, so that the file modification timestamps are not taken into consideration for the cache hash?

https://www.nextflow.io/docs/latest/reference/process.html#cache

**Comment by LouisLeNezet** [comment]
Hi,
Thanks for this solution, this should be enough in my case.
Best regards,
Louis
