### ISSUE TITLE
v24.10.0 Grape @Grab install breaking change

### ISSUE THREAD

**Issue by andrew-watchmaker** [nextflow-io/nextflow#5441]
### Expected behavior and actual behavior

Expected: Installation of latest release of nextflow `24.10.0` would work with existing code in backwards-compatible way.

Actual: Received error `ERROR ~ Class definition not found: org/apache/ivy/util/MessageLogger` when executing `nextflow run`.

### Steps to reproduce the problem

Install version `24.10.0`:
`curl -sL https://github.com/nextflow-io/nextflow/releases/download/v24.10.0/nextflow | bash`

Add the following lines to the top of your workflow script:

```groovy
@Grab('com.xlson.groovycsv:groovycsv:0.2')
import com.xlson.groovycsv.CsvParser
```

Execute `nextflow run` against workflow script

### Program output 

`ERROR ~ Class definition not found: org/apache/ivy/util/MessageLogger`

### Environment 

* Nextflow version: 24.10.0
* Java version: `11.0.19`
* Operating system: Linux
* Bash version: `4.4.20`

### Additional context

While searching for additional context on the error, I did come across the release changelog [here](https://github.com/nextflow-io/nextflow/releases/tag/v24.07.0-edge) which briefly mentions `Grape dependencies management via @Grab annotation is not supported anymore. Custom code requiring third parties libraries should be migrated to a custom plugin`.

But I didn't find any other supporting documentation acting as a migration guide or clarification of what is required so I created this issue to act as a means of discussing the process and how getting a requirement of `groovycsv` (or other requirement) as a custom plugin would be undertaken.

**Comment by bentsherman** [comment]
I suggest you move the functionality that depends on the third-party imports into a function or set of functions, then implement those functions in a plugin as described [here](https://nextflow.io/docs/latest/developer/plugins.html#functions).

You might be able to just move the code into a Groovy script in the `lib` directory, but not sure if `@Grab` still works there or not.

**Comment by shenker** [comment]
It doesn't appear that `@Grab` works for groovy scripts in `lib`.

I looked at the plugin documentation you linked and must admit it was not clear to me how to replace a groovy script containing helper functions that I want to ship alongside a nextflow workflow (currently it's a single groovy script file in `$libDir`, where my `nextflow.config` file sets `libDir` to `WORKFLOW_BASE_DIR/lib`), without dealing with the hassle of building, publishing, and maintaining a separate plugin repo.

**Comment by bentsherman** [comment]
You would have to build and maintain the plugin, yes. We are planning to streamline the plugin system and make it easier to develop plugins, but that might be a long way off.

By the way, if the third-party import is a CSV parser, there is a `splitCsv()` function for files that you can use.
