### ISSUE TITLE
workflow, params are null in workflow.onComplete handler

### ISSUE THREAD

**Issue by PikalaxALT** [nextflow-io/nextflow#5445]
## Bug report 

(Please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

`workflow` and `params` should be defined and not null inside the workflow.onComplete closure. instead both are null.

### Steps to reproduce the problem

```
process SAY_HELLO {
  input:
    val greeting
  output:
    eval("echo $greeting, world")
  script:
    """
    sleep 1
    """
}

workflow {
  Channel.of("Hello", "Hallo", "Hola", "Bonjour")
  | SAY_HELLO
  | view

  workflow.onComplete {
    println "workflow is null: ${workflow == null ? 'yes' : 'no'}"
    println "params is null: ${params == null ? 'yes' : 'no'}"
  }
}
```

### Program output 

```
Hello
Hola
Bonjour
Hallo
workflow is null: yes
params is null: yes
```

### Environment 

* Nextflow version: 24.10.0
* Java version: OpenJDK 17.0.1+12-39
* Operating system: Linux
* Bash version: 4.2.46(2)-release (x86_64-linux-gnu)

### Additional context

Unable to share log files due to company data protection policy.

**Comment by bentsherman** [comment]
Duplicate of #5261 , see that issue for some temporary workarounds

**Comment by PikalaxALT** [comment]
Closing for reason: Duplicate.
