### ISSUE TITLE
-stub flag triggers error "Cannot invoke method clone() on null object"

### ISSUE THREAD

**Issue by xuyangyuio** [nextflow-io/nextflow#5456]
## Bug report 

`-stub` flag breaks workflow with error message "Cannot invoke method clone() on null object"

### Expected behavior and actual behavior

- Without `-stub` flag, pipeline completes successfully.
- With `-stub` flag, got error "Cannot invoke method clone() on null object"

### Steps to reproduce the problem
test.nf:
```
process mockup {
    output:
    file "*.vcf"

    script:
    """
    touch "real.vcf"
    """
    
    stub:
    """
    touch "stub.vcf"
    """
}

process continue_run {
    input:
    file infile

    """
    echo success
    """
}

workflow {
  mockup | continue_run
}

```
```
nextflow run test.nf -stub
```
### Program output 

```
ERROR ~ Error executing process > 'continue_run'

Caused by:
  Cannot invoke method clone() on null object



 -- Check '.nextflow.log' file for details
```

### Environment 

* Nextflow version: 24.10.0 (actually since 24.09.1-edge)
* Java version: openjdk version "23" / "21.0.5"
* Operating system: macOS / Linux
* Bash version: zsh 5.9 / bash 5.1.4

### Additional context

(Add any other context about the problem here)

**Comment by GallVp** [comment]
I am experiencing the same issue but without `-stub`.

**Comment by bentsherman** [comment]
@jorgee can you look into this one, might be a regression from the recent changes we made

**Comment by phaverty-ginkgo** [comment]
Are there specific versions of java and nextflow that resolve this bug? Using openjdk 17.0.14 and nextflow 24.10.4 I still see this error when using -stub. Switching back to nextflow 24.04.4 nextflow runs as expected with the -stub flag.

**Comment by jorgee** [comment]
@pditommaso we have not backported it to 24.10.X. I have added a tag to remember in the next one. I didn't label it in the original PR. @phaverty-ginkgo, it should be it 24.11.0-edge and 24.12.0-edge

**Comment by ccdu-bayer** [comment]
I used the  nextflow version 24.04.4.5917, the clone null bug is not shown.
