### ISSUE TITLE
Fargate complains when memory is exactly the minimum required.

### ISSUE THREAD

**Issue by SPPearce** [nextflow-io/nextflow#5471]
## Bug report 

Fargate complains when the memory is exactly the minimum required.

### Expected behavior and actual behavior

Using AWS Fargate, a spurious warning is produced when the minimum memory is provided.

### Steps to reproduce the problem
Run:
```
nextflow run nextflow-io/hello -process.memory "2.GB" \
-bucket-dir '<BUCKET>' 
```

This will give warnings:

### Program output 

```
WARN: Process 'sayHello (4)' memory requirement of 2 GB is below the minimum allowed by Fargate of 2 GB
WARN: Process 'sayHello (1)' memory requirement of 2 GB is below the minimum allowed by Fargate of 2 GB
WARN: Process 'sayHello (3)' memory requirement of 2 GB is below the minimum allowed by Fargate of 2 GB
WARN: Process 'sayHello (2)' memory requirement of 2 GB is below the minimum allowed by Fargate of 2 GB
```

### Environment 

* Nextflow version: 24.10.0

**Comment by SPPearce** [comment]
It looks like this line:
https://github.com/nextflow-io/nextflow/blob/549e7902dc6203a854b4c82732a760d9a0358c14/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchTaskHandler.groovy#L934
```
        if( mega <=slot.min ) {
            log.warn "Process '${task.lazyName()}' memory requirement of ${mem} is below the minimum allowed by Fargate of ${MemoryUnit.of(mega+'MB')}"
```
should be 
```
        if( mega <slot.min ) {
```

**Comment by pditommaso** [comment]
Well spotted! willing to create a PR for it?

**Comment by SPPearce** [comment]
> Well spotted! willing to create a PR for it?
Done.
