### ISSUE TITLE
Add Support for Loading Files Dereferenced from Environmental Variable

### ISSUE THREAD

**Issue by cancan101** [nextflow-io/nextflow#55]
That way this will work:

```
 file('env://MY_INPUT_FILE')
```
and will load whatever the value of `MY_INPUT_FILE` is set to in the environment.

**Comment by pditommaso** [comment]
Environment variables are accessible from a nextflow script. For example you can write: 

    file_in_my_home = file("$HOME/my_input_file.txt")

Does this solve your problem?

**Comment by cancan101** [comment]
Yes, I believe it does.

**Comment by pditommaso** [comment]
Nice. Note that are also available the following two implicit variables: 

* `baseDir`: the path of the folder where the main pipeline script is located. 
* `workDir`: the path to the pipeline working directory i.e. scratch area
