### ISSUE TITLE
Environment variables are not correctly passed into template script bodies in Singularity containers

### ISSUE THREAD

**Issue by jkaessens** [nextflow-io/nextflow#551]
Okay, this is probably quite a niche construction, but Nextflow does not correctly handle environment variables when all of the following is true:
* some environment variables are defined (by using `env.SOMEVAR` in a config file or through the `modules` directive)
* the process shall execute a template script, not a "regular" process body
* the template is called using a "shell:" declaration, not a "script:" one
* a singularity container is used.

Expected:
* `$SOMEVAR` is accessible within the template script

Observed:
* `$SOMEVAR` is not defined, but `!{SOMEVAR}` can be used instead. 

This unfortunately also makes using the `module` directive impossible to use. As modules usually change the `PATH` variable, it is passed into the singularity container as `!{PATH}`, containing the current `PATH` of the caller environment (with the requested additions), not the singularity one.

When not using singularity containers, things work as expected. This also works as expected when using `script:` instead of `shell:`, whether using singularity or not.

Steps to reproduce:
1. Pull some singularity container, i.e. `singularity build test.img docker://ubuntu:latest`
2. Have the configfile, the script file and the template script as below
3. Run `nextflow -c test.config run test.nf` and see that the result is as expected
4. Run `nextflow -c test.config run test.nf -with-singularity test.img` and see that things break
5. Change the `shell:` to `script:` and re-run with singularity. See that things work again.

test.nf
```
process testproc {
   echo true
   shell:
   template "test.sh"
}
```

test.config
```
env.TEST_VAR="somevalue"
```

templates/test.sh
```
#!/bin/sh
echo "Test var: $TEST_VAR"
```

As this is quite complex, I'm not entirely sure whether this behavior is expected but not being able to use modules, templates, singularity and the `shell:` thing altogether is a real problem for me.
Do you have an idea about what I'm trying to describe?

**Comment by pditommaso** [comment]
Thanks for the detailed report. I think this is related to #495. You may want to give a try to version `0.27.0-SNAPSHOT` which includes that patch.

**Comment by jkaessens** [comment]
Thank you, the mentioned snapshot works well.
