### ISSUE TITLE
Conda OverlappingFileLockException may not be resolved?

### ISSUE THREAD

**Issue by jfy133** [nextflow-io/nextflow#5530]
## Bug report 

I am running nf-core/taxprofiler on gitpod with conda.

When I run the basic test profile: `nextflow run nf-core/taxprofiler -profile test,conda --outdir results/`, I get the OverlappingFileLockException error again.

This is despite using the latest patch version of Nextflow, as reported at the top of the console on execution

```
 N E X T F L O W   ~  version 24.10.1
 ```

### Expected behavior and actual behavior

Nextflow can build multiple conda environments simulteanously without any overlapping lock files

### Steps to reproduce the problem

Open nf-core/taxprofiler repo on gitpod.io

Run 

```bash
nextflow run nf-core/taxprofiler -profile test,conda --outdir results/
```

### Program output 

```
Plus 12 more processes waiting for tasks…
Creating env using conda: /workspace/taxprofiler/./workflows/../subworkflows/local/../../modules/nf-core/nonpareil/nonpareil/environment.yml [cache /workspace/taxprofiler/testing/work/conda/env-ad3bc2eba60b0862-96eea98fae0f03231a4ca48234a15efd]
Creating env using conda: /workspace/taxprofiler/./workflows/../subworkflows/local/../../modules/nf-core/bbmap/bbduk/environment.yml [cache /workspace/taxprofiler/testing/work/conda/env-a0f2bf3ebbb3c91a-06878572316a4c4de51f2bdb49c72937]
ERROR ~ Error executing process > 'NFCORE_TAXPROFILER:TAXPROFILER:SHORTREAD_PREPROCESSING:FASTQC_PROCESSED (1)'

Caused by:
  java.nio.channels.OverlappingFileLockException



 -- Check '.nextflow.log' file for details
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

 -- Check '.nextflow.log' file for details
-[nf-core/taxprofiler] Pipeline completed with errors-
WARN: Killing running tasks (5)
```

### Environment 

* Nextflow version: 24.10.1
* Java version: openjdk version "17.0.11-internal" 2024-04-16
* Operating system: Ubuntu 22.04.4 LTS
* Bash version: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by nschan** [comment]
The same issue occurred a while ago in the charliecloud driver, and I am pretty sure that it is caused by nextflow's `FileMutex()`, but I never figured out how / why.

**Comment by jfy133** [comment]
> Please include the full log file 

Sorry I couldn't include that at the time, was having internet issues so the only thing I could get was the console.

I'm away from a computer until Monday, @nschan if you can share a log from your side that'll would be appreciated.

I'll also ask on nf-core if anyone else gets the same thing with other pipelines

**Comment by nschan** [comment]
I do not have logs for this anymore, the problem in charliecloud was fixed a while ago.

**Comment by jfy133** [comment]
I was able to to distract my son for 5 minutes to try again, and I got the same error again (although interestingly @mahesh-panchal was trying independently and did not get it)

Log file here:

[nextflow(1).log](https://github.com/user-attachments/files/17867816/nextflow.1.log)

**Comment by jfy133** [comment]
Note it happens less if I re-run repeatedly (Without resume). So it (subjectively) appears to only happen more often on the first run in a given directory.

**Comment by ewels** [comment]
Makes sense if it's due to Nextflow concurrently creating new Conda environments. Re-runs will use existing envs from previous runs.

**Comment by mahesh-panchal** [comment]
So far I've done 5 runs (of taxprofiler) in Gitpod, sometimes with fresh Gitpod, and other times doing `rm -rf .nextflow* work results`, and haven't got it yet. It's not an easy one to reproduce.

**Comment by jorgee** [comment]
I have the impression it could be a race condition between two processes using the same conda file.

**Comment by nschan** [comment]
Based on my observations with charliecloud, I think this error will occur when two processes that use the same environment try to create it simultaneously and somehow both manage to create the `FileMutex()` file. I am obviously not an expert, but with charliecloud I had 0 success in avoiding this (or implementing any other locking mechanism), I am mainly surprised this only surfaced now in conda and wonder why this does not happen with e.g. singularity, which uses exactly the same logic.

**Comment by jorgee** [comment]
I think the synchronized in this part of code should include the whole method
https://github.com/nextflow-io/nextflow/blob/e025a846ecc471c42277ac17e800a4d59c15611b/modules/nextflow/src/main/groovy/nextflow/conda/CondaCache.groovy#L364C5-L374C14

**Comment by pditommaso** [comment]
Indeed, likely the sync "key" needs to be reviewed

**Comment by jorgee** [comment]
I was wrong, the issue is not the sync. It is happening when the path in the conda is the same but it is passed as a different string. I mean "/nf-core/taxprofiler/workflows/../subworkflows/local/../../modules/nf-core/fastqc/environment.yml" is the same as "/nf-core/taxprofiler/workflows/modules/nf-core/fastqc/environment.yml" but as strings are different. I think it is happening with these three processes: 'NFCORE_TAXPROFILER:TAXPROFILER:FASTQC' , 'NFCORE_TAXPROFILER:TAXPROFILER:SHORTREAD_PREPROCESSING:FASTQC_PROCESSED' and 'NFCORE_TAXPROFILER:TAXPROFILER:LONGREAD_PREPROCESSING:FASTQC_PROCESSED'.

**Comment by pditommaso** [comment]
Then using `path.toAbsolutePath().normalize()` should solve

**Comment by jfy133** [comment]
Thank you all!
