### ISSUE TITLE
standalone-distribution documentation improvement

### ISSUE THREAD

**Issue by doliv071** [nextflow-io/nextflow#5539]
## Bug report 

Documentation for the standalone distribution doesn't work as specified. 

### Expected behavior and actual behavior

Documentation states:

"The installation procedure is the same as for the standard distribution, only using this URL instead of https://get.nextflow.io:"
```
export NXF_VER=24.10.0
curl -s https://github.com/nextflow-io/nextflow/releases/download/v$NXF_VER/nextflow-$NXF_VER-dist
```
using `curl -s` here will not download anything due to a redirect (302), so the `-L` parameter needs to be passed to successfully complete the redirect.

In addition, the documentation states that this url is a direct replacement to the get.nextflow.io url and as such implies the output from curl should be piped to bash as in the standard installation. However, to actually complete the installation, `-o` parameter needs to be passed to curl to produce the `nextflow` file which can then be chmod'd to be executable.

The documentation should remove the text and simply provide the correct set of commands for installing the stand alone version instead of referencing the standard installation procedure.

Corrected documentation:

The installer for the dist distribution can be found on the GitHub releases page, under the "Assets" section for a specific release. The installation procedure is shown below:
```
export NXF_VER=24.10.0
curl -sL https://github.com/nextflow-io/nextflow/releases/download/v$NXF_VER/nextflow-$NXF_VER-dist -o nextflow
chmod +x nextflow
mkdir -p $HOME/.local/bin/
mv nextflow $HOME/.local/bin/
```

### Steps to reproduce the problem

```
export NXF_VER=24.10.0
curl -s https://github.com/nextflow-io/nextflow/releases/download/v$NXF_VER/nextflow-$NXF_VER-dist
```

### Program output 

It doesn't do anything

### Environment 

* Nextflow version: 24.10.0
* Java version: 21
* Operating system: Linux (Ubuntu 22.04.5 LTS)
* Bash version: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Additional context

(Add any other context about the problem here)

**Comment by pditommaso** [comment]
Thanks for reporting this problem, that docs is not correct.

**Comment by pditommaso** [comment]
Solved by https://github.com/nextflow-io/nextflow/issues/5539
