### ISSUE TITLE
No .command.log files present in work directory when using the gcp batch executor 

### ISSUE THREAD

**Issue by rhassaine** [nextflow-io/nextflow#5588]
### Expected behavior and actual behavior

Attempted to use 2 different nf-core pipelines 

1) sarek version 3.17.0, using test profile 
2) oncoanalyser version 1.0.0., using the colo cell line sample 

with the gcp batch executor and in the work directory's subdirectories, I cannot find the .command.log files. All the other .command. files are present. 

Launched from a gcp vm (within a tmux session) & a service account with all the necessary privileges for both the batch api and gcp storage buckets. Input files & output (results + workdir) are located on 2 different buckets defined the config

Launched using the ```nextflow run nf-core/oncoanalyser (nf-core/sarek) -c gcp_batch.config -r 1.0.0 (3.17.0)```

Runs are successful (outputs as expected) and no issues in the nextflow logs - no issues in the gcp logs 

### Steps to reproduce the problem

No "issue" to reproduce, any runs with gcp batch executor of nf-core pipelines seems to encounter this.
Minimal configs (specifying service account, bucket paths, specific resources for certain processes and that's it)

### Program output 

No failures to speak off

### Environment 

*Version: 24.10.2 build 5932
*System: Linux 6.1.0-28-cloud-amd64
*Runtime: Groovy 4.0.23 on OpenJDK 64-Bit Server VM 17.0.10+7
*GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)

### Additional context

I do not have this issue when using other executors (local or k8) & whenever launching with gcp batch, if I manage to connect into the virtual machine spun up for the job, and interactively log into the docker container running there, I can see the .command.log in that container's filesystem and it contains the expected logs. Unsure about the origin of the issue given that all the other files are present (.command files, intermediate files, output etc)

**Comment by pditommaso** [comment]
Correct. Nextflow uploads that file only in case of task error.

**Comment by bentsherman** [comment]
There are some inconsistencies in how different executors handle the command log file. Some of them always upload it, some only upload it on failure, some (I think K8s) don't upload it at all.

**Comment by pditommaso** [comment]
Stating this code the `.command.log` should only be uploaded in case of error 

https://github.com/nextflow-io/nextflow/blob/f8eb89e2b259b30b250785eaa78a09e0c6fcd565/plugins/nf-google/src/main/nextflow/cloud/google/batch/GoogleBatchScriptLauncher.groovy#L180-L182

**Comment by bentsherman** [comment]
Okay and I see now that aws batch does the same, maybe it didn't before:

https://github.com/nextflow-io/nextflow/blob/5c5a810abe0da342c953de2c2909fb903ba716e3/plugins/nf-amazon/src/main/nextflow/cloud/aws/batch/AwsBatchExecutor.groovy#L354-L363

**Comment by pditommaso** [comment]
Made a test and the `.command.log` is uploaded as expected on task failure. 

```
gs ls gs://rnaseq-nf/scratch/d5/9f7c0a60f1e1fff4e9630886084cd4/
gs://rnaseq-nf/scratch/d5/9f7c0a60f1e1fff4e9630886084cd4/.command.begin
gs://rnaseq-nf/scratch/d5/9f7c0a60f1e1fff4e9630886084cd4/.command.err
gs://rnaseq-nf/scratch/d5/9f7c0a60f1e1fff4e9630886084cd4/.command.log
gs://rnaseq-nf/scratch/d5/9f7c0a60f1e1fff4e9630886084cd4/.command.out
gs://rnaseq-nf/scratch/d5/9f7c0a60f1e1fff4e9630886084cd4/.command.run
gs://rnaseq-nf/scratch/d5/9f7c0a60f1e1fff4e9630886084cd4/.command.sh
gs://rnaseq-nf/scratch/d5/9f7c0a60f1e1fff4e9630886084cd4/.exitcode
```

**Comment by rhassaine** [comment]
Thanks for the insights guys, is there any way to overwrite that ? Thanks

**Comment by pditommaso** [comment]
`.command.log` is not a public "interface" and there's no control over it. What's your use case?

**Comment by rhassaine** [comment]
Given that we have custom-built tools (and an nf-core pipeline) - Tool verification & additional quality/sanity checks. The logging explorer of the cloud providers is too much to sieve through for an organization our size

**Comment by pditommaso** [comment]
I see. You may want to use another command marker file.

**Comment by rhassaine** [comment]
My thoughts exactly. Grateful for any suggestions if you have any?

**Comment by pditommaso** [comment]
You can `.command.run` that should exist to run a task or `.exitcode` that should report the task exit status on completion

**Comment by rhassaine** [comment]
Thank you guys for your help! I was also thinking about using the Logs Explorer's API to do this, hopefully it pans out.
