### ISSUE TITLE
Automagically running scripts from github when not found locally might be security risk

### ISSUE THREAD

**Issue by karinlag** [nextflow-io/nextflow#560]
From the documentation:

> When you launch a script execution with Nextflow, it will look for a file with the pipeline name you've
>specified. If that file does not exist, it will look for a public repository with the same name on GitHub
> (unless otherwise specified). If it is found, the repository is automatically downloaded to your computer
> and executed.

Provided nextflow does _exactly_ what is written here, this means that if somebody misspells the name of their nextflow_script.nf file, and there is one to be found on github, this will be downloaded and executed without the user not being notified or warned or given opportunity to stop it. This could represent a way of inserting malicious code into a system. 

While the likelihood of this is small, the consequences could be serious. The risk is increased due to most of us liking having to have code on github. Thus, somebody targeting any of us could look at our repos, create a set of scripts with likely misspellings of our scripts, and get into our systems that way.

I suggest introducing a verification step in this process to ensure that the user gets a chance to look at what will be downloaded, and has a chance to stop it.  I'd also personally like a way to turn this feature permanently off.

**Comment by pditommaso** [comment]
Let me clarify that this does not happen for any generic file name, but only when the user specifies a path in the form `user/project`, then if that paths it's not a local folder NF will lookup for a GitHub repository for the specified user and executes the `main.nf` script (if exits). 

Now, I can understand that this can be perceived as security risk in some context, but I would avoid to add an interactive (verification) step. In most case NF is used in unattended mode, hence the execution would hang. 

What about adding a configuration setting to disable this feature? Sysadmins could define at centralised level to switch this feature. Does it sound a acceptable in your use case?

**Comment by karinlag** [comment]
This makes things quite a bit better. I suggest you update the docs to reflect this. From this description, it seems more unlikely that somebody could try to create a script that could be run accidentally. I also suggest you point this out more clearly up front in the docs so that people are aware of this (could work as a drawing point in that case too).

I think I would be ok with the configuration setting. You might however consider having it the other way around, i.e. off by default, but turn-onable whenever you want. To make it easier, maybe this could be one of the nextflow commands, such as the update one? 

Just to make this clear, my main thoughts consern the combo of unaware user and malignant coder, I am of the school that thinks that people who know what they are doing should be (mostly) allowed to do what they want. Most problems occurr when people do things without being aware of what they're doing.

**Comment by pditommaso** [comment]
OK, I will try to further clarify how does in work in the documentation. 

Regarding the automatic pull, an alternative could be to required the use to specify an extra command line option to automatically pull the script from GitHub is the a matching is not found in the file system.

**Comment by pditommaso** [comment]
I'm postponing this to the next release, because we could reorganise NF having a offline/hoc only distribution which would not allow any remote connection. Therefore it would not able either to download scripts from GitHub.

**Comment by pditommaso** [comment]
Added `-offline` command line option and `NXF_OFFLINE` env variable to disable automatic downloads from remote repos.
