### ISSUE TITLE
Remove Conda defaults channel from documentation or put disclaimer

### ISSUE THREAD

**Issue by oliverdrechsel** [nextflow-io/nextflow#5601]
Hi!

Thanks for developing Nextflow and the complete universe of useful tools around it!

Recently, we got aware that Anaconda Inc. changed its Terms and Conditions for the usage of their "defaults" channel. Institutions larger than 200 employees may get charged quite considerable sums. 
The documentation in https://github.com/nextflow-io/nextflow/blob/master/docs/conda.md lists "defaults" channel. 

Could it be useful to highlight the potential issues in a disclaimer there, make the use of the "defaults" channel optional or remove the "defaults" channel from the examples?

cheers

**Comment by ewels** [comment]
Yes it's fine to remove `defaults`. We've already done this everywhere in the code a while back, I didn't realise that any were left in the docs. We should just remove those lines.
