### ISSUE TITLE
transpose() does not work with groovy ranges (e.g. 0..20)

### ISSUE THREAD

**Issue by danielecook** [nextflow-io/nextflow#5603]
### Expected behavior and actual behavior

The following:

```nextflow
ch1 = Channel.of(["row"])
ch1.map {
    [it, 0..20]
}.transpose().view()
```

Should expand to:

```
["row", 0]
["row", 1]
["row", 2]
etc.
```

__But only the first element is omitted:__

```
[row, 0]
```

But this isn't happening. I wonder if a change in the version of java or groovy may contribute to this change? Because previously I am pretty sure this was not happening...

### Steps to reproduce the problem

Try running the workflow above and see if you observe the same result.

### Program output 

```
[row, 0]
```

### Environment 

* Nextflow version: 24.10.2 (also tried 21.10.4)
* Java version: openjdk 17.0.8
* Operating system: linux
* Bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

**Comment by danielecook** [comment]
I'll note that if I do:

```
ch1 = Channel.of(["row"])
ch1.map {
    [it, 0..20]
}.transpose(by: [1]).view()
```

It __will__ work in this case, but this is not what is specified in the [documentation](By default, every list element is transposed.) (`By default, every list element is transposed.`)

**Comment by bentsherman** [comment]
Did you mean to put `"row"` in a list? That will cause transpose to only emit one value, because it emits as many values as the shortest list in the tuple.

**Comment by danielecook** [comment]
Hmm... I see now:

```
ch1 = Channel.of(["row"])
ch1.flatten().view().map {
    [it, 0..20]
}.transpose().view()
```

Outputs as expected:

```
[row, 0]
[row, 1]
[row, 2]
[row, 3]
[row, 4]
[row, 5]
[row, 6]
[row, 7]
[row, 8]
[row, 9]
[row, 10]
[row, 11]
[row, 12]
[row, 13]
[row, 14]
[row, 15]
[row, 16]
[row, 17]
[row, 18]
[row, 19]
[row, 20]
```

What is puzzling is that this behavior arose from a pipeline I've been using for a long time without changing...so I'm not exactly sure why that happened.
