### ISSUE TITLE
AWS CLI operations with S3 should use the --only-show-errors options

### ISSUE THREAD

**Issue by fstrozzi** [nextflow-io/nextflow#567]
In the current NF version, moving data back and forth from AWS S3 is done using the CLI utility when the job is performed via the Batch service. The current command lines generated by NF scripts to interact with S3 add a ```--quiet``` option which suppress all messages, even warnings and errors. So in case a file or prefix is missing or non retrievable on S3 (e.g. for typos in the NF pipeline or grant/access restrictions on S3) the job ends with an error but the logs are completely empty and it can be difficult to debug the pipeline in these cases.

An alternative could be to switch to the ```--only-show-errors``` option instead of the ```--quiet```, which suppresses all messages but errors and warnings. 

https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html

**Comment by pditommaso** [comment]
@fstrozzi please review a6a0532e3ffa20326b319455152439e1f32c52a2 at your earliest convenice.

**Comment by pditommaso** [comment]
Snapshot `0.27.1-SNAPSHOT` including this patch is available.

**Comment by pditommaso** [comment]
Included in version `0.27.1`
