### ISSUE TITLE
Docker not working with SELinux

### ISSUE THREAD

**Issue by tdudgeon** [nextflow-io/nextflow#572]
It seems that the `-with-docker` option does not work when you are in a selinux environment.
I would imagine this is already known, but I couldn't find any mention of it in the docs or issues.
You get a somewhat misleading error:

```
Command error:
  /bin/bash: .command.sh: Permission denied
```
Nextflow runs fine if you first do:

`setenforce 0`

Most likely this is related to the volume mounts. They need to be created with the Z option. e.g. something like this:

`docker run -it -v $PWD:$PWD:Z busybox sh`

**Comment by pditommaso** [comment]
No, actually it was not known. Actually I didn't either know about the `:Z` mount option. Does it work instead using mounting the docker paths with the `:ro`  (read-only) volume?

**Comment by tdudgeon** [comment]
Its described in more detail here: https://docs.docker.com/engine/admin/volumes/bind-mounts/
And yes, it works in combination with the ro and rw options. You need to separate the options with a comma e.g.

`-v $PWD:$PWD:ro,Z`

**Comment by pditommaso** [comment]
I see, I was wondering if it works only with `:ro` ?

**Comment by tdudgeon** [comment]
No, typically its used in rw mode:

`-v $PWD:$PWD:rw,Z`

or as rw is the default just:

`-v $PWD:$PWD:Z`

I've not seen any problems when specifying this in a  non-selinux environment, but that should be checked a bit more thoroughly.

**Comment by pditommaso** [comment]
We can add a `mountOptions` in the docker setting to allow the user to add the `Z` flag to the mount points.

**Comment by pditommaso** [comment]
Is there a way to check is SELInux is enforced (eg. a system file)?

**Comment by tdudgeon** [comment]
You can probably use the getenforce command:

```
$ getenforce
Enforcing
```
That said, it seems to do no harm to specify the z or Z options when SELinux is not enabled.

**Comment by pditommaso** [comment]
the idea adding a `:Z` is attractive, but I'm bit concerned about this warning. 

> Use extreme caution with these options. Bind-mounting a system directory such as /home or /usr with the Z option renders your host machine inoperable and you may need to relabel the host machine files by hand.

I would to the user to enable this feature.

**Comment by pditommaso** [comment]
The above commit add a new configuration option that allows the specification of custom mount flags, e.g.: 

```
docker.mountFlags = 'Z'
```
