### ISSUE TITLE
Channel with one tuple treats does not treat it as a tuple

### ISSUE THREAD

**Issue by Martinsos** [nextflow-io/nextflow#576]
Hi,
first of all thank you for building nextflow, it is really impressive, especially the wide array of features :)!

I was trying to run Nextflow and had an error where I was expecting a tuple to arrive as an input into my process but I was receiving values one by one, not as a tuple.

Minimal example:
```
pairs = Channel.from([1, 2])

process printPair {
  echo true

  input:
  set a, b from pairs

  shell:
  '''
  echo !{a} !{b}
  '''
}
```

I found out that if I added another tuple, like this:
```
pairs = Channel.from([1, 2], [3, 4])
```
everything works as expected. 
So it seems like in the first case that list is somehow flattened and ignored. I am not sure if that is expected behaviour or not, but it was certainly confusing for me and took me some time to figure it out.
One way I managed to avoid this problem was by wrapping it in one extra list:
```
pairs = Channel.from([[1, 2]])
```
which makes it behave like a couple.

My question would be: is this expected behaviour (feature :)) or is it a bug? If it is a feature, maybe it would be worth mentioning it as a note under the "set": "Watch out if you give it just one tuple it will flatten it, but you can do it by wrapping it in extra array".

Thanks!

**Comment by pditommaso** [comment]
Hi, thanks for your kind words. 

Yes, that's supposed to be a [feature](https://www.nextflow.io/docs/latest/channel.html#from) (see the note box). However it would be better to define it an mistake of the early days. 

Likely at some point we will deprecate `from` and replace it with a different method with a more consistent behaviour. Thanks for reporting that.

**Comment by Martinsos** [comment]
Thanks you for quick response!
Right, I thought it is a feature and I forgot to look it up under the .from documentation. It still may be worth it to mention under the "set" documentation how to put just one tuple in the channel, as a tip?
I will close the issue! Thanks.
