### ISSUE TITLE
Multiple source channels to multiple target channels

### ISSUE THREAD

**Issue by Martinsos** [nextflow-io/nextflow#579]
Hi!
I have channels with alignment tasks and I have aligners. I am doing performance comparison, therefore I want certain aligners to perform certain tasks.
For example, let's say I have A1, A2, ... to A5 tasks (5 total) and also B1, B2, ... to B6 tasks (6 total) . I have aligners X, Y and Z.
I want to execute A? tasks with X, Y and Z, but I want to execute B? tasks only with X and Y (no Z, because it does not support such type of tasks).

What I did is make channel A that has tasks from A1 to A5. I also made channel B that has tasks from B1 to B6.
Next, I did A.into{X; Y; Z}, where I created X, Y and Z before that as empty channels.
Then, I did B.into{X; Y}.
X channel is plugged as input into process alignWithX, and same goes for other aligners.

However, what I got is that only B tasks were executed with X and Y, no A tasks, so I conclude that `into` operation does not add to channel, but instead it writes over it / direct exclusively to it. Is that correct?

What would be the best way to achieve this in elegant way, without creating intermediate channels?

Thanks!

**Comment by Martinsos** [comment]
Hi @pditommaso,
thank you for trying to help out! I maybe made it somewhat too complicated, here is a sketch of what I want to do:
![nextflowmultichannels](https://user-images.githubusercontent.com/1536647/35241678-7670fcda-ffb7-11e7-98c6-853f6e4eb730.png)

So I have channels A, B and C, and I also have channels X, Y and Z. I want A to be input for X, Y and Z, B to be input for X and Y, and C to be input for Y and Z.
Can that be done without creating intermediate channels?

I actually have even more complicated case, where I want to also apply filter when B goes to Y :), but I believe I could figure that out if I get this simpler case nailed down.

Now I am doing this solution, with intermediate channels:
```
(AX, AY, AZ) = A.into(3)
(BX, BY) = B.into(2)
(CY, CZ) = C.into(2)

X = AX.mix(BX)
Y = AY.mix(BY, CY)
Z = AZ.mix(CZ)
```

or if I want to add additional filter between B and Y, I do:

```
(AX, AY, AZ) = A.into(3)
B.tap{BX}.filter{...smt_here...}.tap{BY}
(CY, CZ) = C.into(2)

X = AX.mix(BX)
Y = AY.mix(BY, CY)
Z = AZ.mix(CZ)
```

**Comment by pditommaso** [comment]
If the resulting channel provide the elements you are expecting that's noting wrong in the above snippet.

**Comment by Martinsos** [comment]
Ok, I get what you are aiming at! You are going to having just one channel and then keep the information about the routing in the tuple itself. Ok thanks, I ended up implementing a solution similar to that!

**Comment by pditommaso** [comment]
👍
