### ISSUE TITLE
Default use of  the nextflow.config file in parent directory

### ISSUE THREAD

**Issue by shaze** [nextflow-io/nextflow#580]
I am just checking that (a) I am right and (b) whether this is desired behaviour.

When you do a `nextflow run` command,  the nextflow.config in the parent directory is automatically included if there isn't one in the current directory.

However, if  a `nextflow cloud create` command is done, this doesn't happen. If there's a nextflow.config file in the current directory then  that is included, but the config file from the parent directory is not.

Thanks

Scott

**Comment by pditommaso** [comment]
NF doens *not* check for a config file in the parent directly. It looks `NXF_HOME` directory, then pipeline installation directory, then current directory. The `nextflow cloud create` command is supposed to do the same. 

You can the actual parsed config files in the `.nextflow.log` file. The log in cloud command is disabled by default you can enable it with the `-log` option eg `nextflow -log <name> cloud create`.

**Comment by shaze** [comment]
OK, that's clear to me.  The difference in my case is that when you run `nextflow run`, you provide a NF script (in my case, the script was in the parent directory, and hence the nextflow.config file in the parent directory was included as described); but with `nextflow cloud create` of course you don't provide a script. I missed this point, so all is good. Many thanks for the response  -- all clear and good.

**Comment by pditommaso** [comment]
I always run cloud command in the path where the `nexflow.config` is located.

**Comment by pditommaso** [comment]
OK, I'm closing this. Feel free to comment if needed.
