### ISSUE TITLE
Local process kill signal is not propagated to children processes

### ISSUE THREAD

**Issue by shaze** [nextflow-io/nextflow#581]
This is the issue  that Hugues raised in Issue #172 and using his example (I have my own more complex real examples).

I am using Nextflow 0.27

On a macOS it runs fine (0.27.0). But on Ubuntu 16.04 (Nextflow 0.27.1) and CentOS 7..4 (0.27.0 and 0.27.1) it fails. I first discovered this problem when we had hundreds of zombie processes running on our cluster using pbs mode. However, this happens with direct local execution.

This is quite a serious problem for our cluster. I am pretty sure that this didn't happen on earlier versions 

The version of Java we have installed is OpenJDK Runtime Environment (build 1.8.0_151)

Please let me know if I can provide any further information. 

Many thanks for any help with this

Scott

**Comment by pditommaso** [comment]
Thanks for reporting this! I've uploaded a snapshot solving this problem. You can use it defining the following variable in your env `NXF_VER=0.27.2-SNAPSHOT`, then using NF as usual. 

Please confirm that it works on your side.

**Comment by shaze** [comment]
Paolo

Many thanks for the quick response. I tested it on Hugues' script and it worked fine. That's great.

Scott

**Comment by pditommaso** [comment]
Nice. I will release a new version in a few days.

**Comment by pditommaso** [comment]
Included in version `0.27.2`
