### ISSUE TITLE
Process name does not reflect dynamic tag declaration when a task execution is retried

### ISSUE THREAD

**Issue by rfenouil** [nextflow-io/nextflow#586]
As you suggested, here is some code showing that task.attempt is not dynamically updated when used in process tag:

    myChan=Channel.from(1)

    process P01_test {
      tag "$testValue -- attempt: $task.attempt"

      errorStrategy 'retry' 
      maxRetries 3

      input:
        val testValue from myChan

      script:
        """
        echo ${'value: '+testValue}
        echo ${'attempt: '+task.attempt}
        echo ${'mem: '+task.memory}
        exit 10
        """
    }

I noted that task.memory is potentially affected too when implementing a dynamic resource allocation example found [here](https://www.nextflow.io/blog/2016/error-recovery-and-automatic-resources-management.html).

**Comment by pditommaso** [comment]
Included in version `0.27.3`
