### ISSUE TITLE
Resume does not work for tasks successfully executed in a re-submit attempt 

### ISSUE THREAD

**Issue by skptic** [nextflow-io/nextflow#591]
When using `-resume`, if a task had to be resubmitted in the original execution, the resumed execution will start trying from the task attempt 1, even if task attempt X completed successfully.

This may be due to the task hash being calculated using with the task attempt, effectively breaking the resume functionality in pipelines that utilise multiple task attempts.

**Comment by pditommaso** [comment]
Thanks for assigning it to me :joy:

**Comment by pditommaso** [comment]
Squashed!

**Comment by pditommaso** [comment]
I've uploaded `0.27.4-SNAPSHOT`. Git it a try using:

```
NXF_VER=0.27.4-SNAPSHOT nextflow run .. etc
```

**Comment by skptic** [comment]
Thanks for the quick fix, much appreciated. A++

**Comment by pditommaso** [comment]
Man, we are a super-team ! ;)

**Comment by pditommaso** [comment]
Included in version `0.27.4`
