### ISSUE TITLE
Possible performance issue

### ISSUE THREAD

**Issue by msmootsgi** [nextflow-io/nextflow#595]
At one point in a pipeline I have a groupTuple operator with a sort comparator. It turns out that when you've got 3.2 million entries in the channel it takes about 20 hours to group and sort things. While groupTuple was doing it's thing the pipeline appeared to just be sitting there and it was only because I was busy with other things did I not take the time to kill and restart the pipeline (assuming there was a problem). So, while there don't appear to be any bugs, 20 hours seems like a long time for groupTuple. Is it worth digging into this a bit more?

Here is a pipeline that generates fake data, but performs the exact same channel operations that the actual pipeline does.

```
// Increase this value to test.
params.max_value = 3

Channel
    .from(1..params.max_value)
    .set{ id_list }

process gen_data {

    input:
    val(id) from id_list

    output:
    stdout to score_data

    script:
    """
#!/usr/bin/env python
import random
import string

# be consistent
random.seed(42)

# add some variability to the results
num_expected = random.randint(10,50)

for i in xrange(num_expected):
    # create random results
    bits = random.randint(0,100)
    score = random.uniform(0,1)
    fa = ''.join([random.choice(string.ascii_letters) for n in xrange(5)]) + '.fa'
    gw = ''.join([random.choice(string.ascii_letters) for n in xrange(5)]) + '.gw'

    # this is the data we operate on
    print "a_${id}  %s  %s  %s  %s" % (score,bits,fa,gw)
    """
}

//
// The following operations combine to be very slow when there are many
// results.  We saw problems with a pipeline that generated 3.2 million lines,
// so maybe try --max_value=100000.
//

score_data
    // Split stdout based on newlines into single strings.
    .flatMap{ it.tokenize('\n') }
    // Split single strings into tuples.
    .map{ it.tokenize('  ') }
    // Convert to tuple for grouping.
    .map{ id, s, b, fa_name, gw_name -> [id, [s,  b, file(fa_name), file(gw_name)]] }
    // Group based on id and sort the tuples based on align score, then bits
    // but in REVERSE order putting the highest score first.
    .groupTuple(sort: { a, b -> b[0] <=> a[0] ?: b[1] <=> a[1] } as Comparator )
    //.view()
    .set {
        ordered_score_data
    }
```

I'm running this locally with `--max_value 100000` to see what happens.  Will report back the results!

**Comment by pditommaso** [comment]
I suspects that could be related to the JVM garbage collector overhead. Try to fetch some metrics with memory/cpu usage with Java Mission control or similar tools (VisuamVM, YourKit, etc).

**Comment by msmootsgi** [comment]
I ran this last night with `--max_value 100000` and the last entries to the `trace.txt` file were last night around 17:30 and were for values 99999 and 100000 (as expected) but the __pipeline is still running now!__  Over 15 hours later.  So my test case works.

I'll see if I can capture some profiling data to narrow the problem.
