### ISSUE TITLE
Support for skipping confirmation when shutting down cluster

### ISSUE THREAD

**Issue by Martinsos** [nextflow-io/nextflow#596]
When running `nextflow cloud shutdown` we are asked via prompt to confirm that we are sure we want to do this.
This can be tricky when running it automatically, e.g. from another script, although it can be easily solved with `echo y | nextflow cloud shutdown` or `yes | nextflow cloud shutdown`.
As @pditommaso mentioned, it might be worth adding this as an option (probably `-y`) to make it even easier.

**Comment by pditommaso** [comment]
Requires #556
