### ISSUE TITLE
Running different scripts from github repo

### ISSUE THREAD

**Issue by shaze** [nextflow-io/nextflow#597]
We have one main workflow for one of our projects. But there are two auxiliary workflows. 

When we make a local clone of the project's github repo there's no problem of choosing which workflow to run.

But we really like being able to run directly using github project name -- e.g. nextflow run h3abionet/h3agwas

It would be very nice if the user could specify the manifest.mainScript option from the command line (or even better perhaps from a local nextflow.config file). From my reading of the documentation, this is not possible but perhaps I have missed something.

Or is there a better way of doing things? I really don't want to have separate gitub repots

Many thanks

Scott

**Comment by pditommaso** [comment]
I think it should be possible to specify the `manifest.mainScript` option in a specific `profile`, then you should be able to switch from one to another using the `-profile` cli option.

**Comment by shaze** [comment]
Hi Paolo

Thanks for your response. Tantalising,  but not quite. 

First, there seems to be an unrelated issue that the form `manifest.mainScript = 'blah.nf' `doesn't work. You need a 
```
manifest {
     mainScript = 'blah.nf'
}
```
I experienced this in different ways. If I am using the config on the github repo, if there's no mainScript directive at all, of course, you can't pull or run. If you have `manifest.mainScript='xxx'` then you can pull but not run (you get a `ERROR ~ No such variable: mainScript`).  Also just running locally.

On my query, the suggestion doesn't seem to work. Here is my config file (on the github repo)

```
manifest {
  mainScript = 'show.nf'
}


profiles {
   remote {
      manifest {
         mainScript = 'cleandups.nf'
      }
   }
}
```
 The script `show.nf` runs no matter whether the remote profile is used or not. Similarly if I also have a local config file and run with `-c option.config` it still takes the `show.nf`. (and if you don't have the global mainScript, `nextflow pull` complains because there's no mainScript)

This is a **very** low priority issue for me.

Also a more theoretical response to your query.  We have different profiles for running in different modes (e.g., local, pbs, docker).  With the solution suggested would we have to have an n x m number of profiles?

**Comment by pditommaso** [comment]
Thanks for  your detailed report. 

>  With the solution suggested would we have to have an n x m number of profiles?

Yes, tho I'm investigating a way to allow to compose multiple profiles #370.

**Comment by pditommaso** [comment]
I've just realised that's an easy way to do this, just specify the script file name after the project repository. For example, having a project `nextflow-io/hello` containing `main.nf` and `foo.nf`, you can run the latter with:

```
nextflow run nextflow-io/hello/main.nf
```

**Comment by pditommaso** [comment]
The previous comment should resolve the reported issue. Please feel free to reopen it if this does not solve your problem.

**Comment by maressyl** [comment]
I am also very interested by this feature, however despite the solution you suggest seems to work on Github, it doesn't on our Gitlab instance (private repository https://gitlab.inria.fr/NGS/pipelines/atac-seq, scripts named "ATAC_map.nf" and "ATAC_samples.nf") :

- `nextflow run https://gitlab.inria.fr/NGS/pipelines/atac-seq` works fine, as long as I provide one of the two scripts in `manifest.mainScript` in the repository config file.

- `nextflow run https://gitlab.inria.fr/NGS/pipelines/atac-seq/ATAC_map.nf`
```
N E X T F L O W  ~  version 21.12.1-edge
Pulling NGS/pipelines/atac-seq/ATAC_map.nf ...
WARN: Cannot read project manifest -- Cause: Remote resource not found: https://gitlab.inria.fr/api/v4/projects/NGS%2Fpipelines%2Fatac-seq%2FATAC_map.nf
Remote resource not found: https://gitlab.inria.fr/api/v4/projects/NGS%2Fpipelines%2Fatac-seq%2FATAC_map.nf
```

As @shaze I tried the profile solution you suggest as well, but it seems mainScript is ignored (still looking for "main.nf").

Is there any other option ?
