### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by tiagofilipe12** [nextflow-io/nextflow#599]
Hi all,

I am a "newbie" to nextflow and came across with a doubt. Can we update the docker image somehow, using some command associated to nextflow (similarly to what we do with nextflow pull <github_repo> to update the pipeline)?

The only solution that I have found to use the updated "latest" image from docker hub was to locally update the docker image using `docker` command. And then run nextflow would download the latest imagem from docker hub.

This might be handy for example if we change a version of a program we wish to run in a given pipeline.

**Comment by pditommaso** [comment]
Do you mean to the docker image used by your pipeline? No. I suggest to use an unique tag name when you create/update a docker image. Even better use the docker sha256 image ID as shown [here](https://github.com/CRG-CNAG/CalliNGS-NF/blob/master/nextflow.config#L5).

**Comment by tiagofilipe12** [comment]
sha256 image ID might be safer, however it is harder to read. But using tag name with versioning did the trick. Thanks.
