### ISSUE TITLE
sort a list of files by chromosome_id

### ISSUE THREAD

**Issue by elarsonneur** [nextflow-io/nextflow#601]
Hello,

Is there a shorter solution to get the final sorted list `res` (sorting by chromosome) from the initial unsorted array of list ?
```
 Channel
  .from([10, 'chr10.txt'], [1, 'chr1.txt'], [2, 'chr2.txt'], ['Y', 'chrY.txt'], ['X', 'chrX.txt'])
  .toSortedList( { a, b -> a[0] <=> b[0] } ) 
  .flatten()
  .buffer( size:1, skip:1 )
  .flatMap{it.get(0)}
  .toList()
  .set{res}

res.view()
/*  [chr1.txt, chr2.txt, chr10.txt, chrX.txt, chrY.txt] */
 ```

I used this method in this workflow to merge files : 

 ```
$ cat merge.nf

#!/usr/bin/env nextflow

chromosomes = [1, 10, 22, 'Y', 2,  'X'] 

process echo_by_chr {
  tag { chr }   

  input:
  val chr from chromosomes

  output:
  set chr, file("chr${chr}.txt") into results

  """ 
  echo "${chr}" >  "chr${chr}.txt"
  """ 
}

results
  .toSortedList( { a, b -> a[0] <=> b[0] } ) 
  .flatten()
  .buffer( size:1, skip:1 )
  .flatMap{it.get(0)}
  .toList()
  .set{res}

process merge {
    input:
    file(f) from res 

    output:
    file 'merged.txt'

    script:
    """
    cat ${f} > merged.txt
    """
}

 ```
```
#merge process
$ less .command.sh 
cat chr1.txt chr2.txt chr10.txt chr22.txt chrX.txt chrY.txt > merged.txt
```

Best,
Elise

**Comment by pditommaso** [comment]
The tricky part is the ordering that cannot be done in the file names, right. 

I could do this 
```
chromosomes = [1, 10, 22, 'Y', 2,  'X'] 

process echo_by_chr {
 tag { chr }   

 input:
 each chr from chromosomes

 output:
 set chr, file("chr${chr}.txt") into results

 """ 
 echo "${chr}" >  "chr${chr}.txt"
 """ 
}

results
    .toSortedList { entry -> entry[0] }
    .map { allPairs -> allPairs.collect{ chr, file -> file } }
    .set { res } 


process merge {
   input:
   file(f) from res.view()

   output:
   file 'merged.txt'

   script:
   """
   cat ${f} > merged.txt
   """
}
```

**Comment by elarsonneur** [comment]
Nice,
I wouldn't have thought to use a channel operator inside a closure

Thanks a lot Paolo,
Elise

**Comment by pditommaso** [comment]
You were thinking right. That `collect` is not a channel operator but a list [collect](http://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/Collection.html#collect(groovy.lang.Closure)).

**Comment by elarsonneur** [comment]
Okay, it's a groovy list method. Thanks for this tip.

**Comment by pditommaso** [comment]
I've found a different slight more *elegant* solution, tho I'm not sure I'm able to explain it :)

```
results
    .toSortedList { entry -> entry[0] }
    .transpose()
    .last()
    .set { res } 
```

**Comment by lindenb** [comment]
same current problem today;

 is it ok/good-practice to declare CHROM as **final** ? (i would do this with java8/streams)

```
final CHROMS=["1","2","3","4"]
```

and then

```
(...)
	input:
		val contig_vcf from variant_per_contig_vcf.
			toSortedList{a,b -> CHROMS.indexOf(a[0]) <=> CHROMS.indexOf(b[0]) }.
			flatten().
  			buffer( size:1, skip:1 ).
  			flatMap{it.get(0)}.
  		        toList().
			;
(...)
```

it works so far...

?

**Comment by pditommaso** [comment]
It should be fine the use of final, tho not sure to understand how you like to use java 8 streams here.

**Comment by lindenb** [comment]
I meant, I use "final" when , in java Stream, i need to use a functional interface declared elsewhere, so i assumed it was the same thing with groovy.

**Comment by pditommaso** [comment]
I see. No, that's not needed thought it could be a good practice. Contrary to java lambda a groovy closure can access and modify not final variables.
