### ISSUE TITLE
Project bin path is not recognised when contains a blank character

### ISSUE THREAD

**Issue by wikiselev** [nextflow-io/nextflow#603]
When running NF locally and defining a local path to the pipeline folder, the `bin` folder becomes invisible when `~` is used in the local path or there are spaces in the local path. Feels like this is only MacOS specific (tested on both Sierra and High Sierra).

This does not work (because of `~` in the path):
`nextflow run ~/RNAseq`

This does not work (because of a space in the path):
`nextflow run $HOME/Google\ Drive/RNAseq`

This works:
`nextflow run $HOME/RNAseq`

**Comment by pditommaso** [comment]
Unable to replicate `~` problem. I confirm the issue with a blank in the path.

**Comment by pditommaso** [comment]
The `~` is supposed to be expanded by the shell interpreter so I don't think it's related to NF. The problem with blank character is fixed.

**Comment by pditommaso** [comment]
Feel free to comment below or reopen this issue if needed.
