### ISSUE TITLE
Nextflow specific ENV variable name for JAVA

### ISSUE THREAD

**Issue by senthil10** [nextflow-io/nextflow#607]
Currently `nextlfow` uses (general) `env` variable `JAVA_HOME` or `JAVA_CMD` to figure out which `java` to be used.  Would be much helpful (atleast for us 😉 ) if it uses nextflow specific variable name i.e. with the prefix `NXF` (which will also make it consistent to other variable names nextflow utilizes)

The scenario why this would be helpful is, in a cluster where there are lot of programs installed with one requiring different version of `java`, it would be tricky situation for users to configure appropriate `java` version to the respective programs if they all utilize general environment variable such as `JAVA_HOME`. So having environment variables like `NXF_JAVA_HOME` and `NXF_JAVA_CMD` would come handy on such situation.

If this doesn't sound much convincing, atleast making nextflow to look for such variables would be helpful i.e. I mean something like the following in the `nextflow` script

```
JAVA_HOME=${NXF_JAVA_HOME:-$JAVA_HOME}
JAVA_CMD=${NXF_JAVA_CMD:-$JAVA_CMD}
```

**Comment by pditommaso** [comment]
It makes sense.

**Comment by pditommaso** [comment]
I've uploaded the changes you have suggested. Please give a try using the following `nextflow` launcher script 

```
curl https://www.nextflow.io/releases/v0.28.0-SNAPSHOT/nextflow
```

**Comment by senthil10** [comment]
Awesome!! Works as expected. Thank you @pditommaso 😄 👍 

*Before setting `NXF_JAVA_HOME`:*
```
[senthilp@~$] echo $JAVA_HOME
/home/senthilp/java/x86_64/sun_jdk1.7.0_25
[senthilp@~$] echo $NXF_JAVA_HOME

[senthilp@~$] nextflow -version
ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 is installed
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /sw/comp/java/x86_64/sun_jdk1.7.0_25/bin/java
 JAVA_HOME: /sw/comp/java/x86_64/sun_jdk1.7.0_25
```

*After setting `NXF_JAVA_HOME`:*
```
[senthilp@~$] echo $JAVA_HOME
/home/senthilp/java/x86_64/sun_jdk1.7.0_25
[senthilp@~$] echo $NXF_JAVA_HOME
/home/senthilp/java/x86_64/sun_jdk1.8.0_151
[senthilp@~$] nextflow -version

      N E X T F L O W
      version 0.28.0-SNAPSHOT build 4776
      last modified 14-02-2018 09:42 UTC (10:42 CEST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io
```

**Comment by pditommaso** [comment]
I'm tempted to leave only `NXF_JAVA_HOME` and remove `NXF_JAVA_CMD` since `JAVA_CMD` variable is not standard. What do you think?

**Comment by senthil10** [comment]
Yes, totally works for me :) Like you pointed out `JAVA_HOME` is the crucial one.
