### ISSUE TITLE
'some-dir/*' pattern with collect  causes problem with -resume

### ISSUE THREAD

**Issue by lillamy2012** [nextflow-io/nextflow#610]
Using the`some-dir/*` pattern together with `collect()` causes problems when running pipeline with `-resume` option. The cached processes are not guarantied to be used, instead a finished process is often re-submitted (although not always).

**Comment by pditommaso** [comment]
Fixed in version `0.27.5`.

**Comment by pditommaso** [comment]
@ewels you may be interested in this.

**Comment by ewels** [comment]
Thanks! Yes, I saw the same thing with my mini test script just now but can confirm that updating from `0.27.4` > `0.27.5` fixed it.. 👍
