### ISSUE TITLE
Processes downstream of optional steps (using when)

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#611]
### Use Case
All of our pipelines have MultiQC at the end, which collects all outputs from all processes to generate a report. This is generally fine, except for when one of the processes is empty. Then, that output channel is missing and the MultiQC process is skipped.

The fix we've had in place so far is to use massive `if` /  `else` blocks around conditional processes where we create and close an empty dummy channel. However, it would be much nicer to use `when`, which is designed for this type of scenario.

### Demo Code
Consider the following code:

---

<details>
<summary>Click to expand example script</summary>

```nextflow
#!/usr/bin/env nextflow

process sample_correlation {

    output:
    file "*.{txt,pdf,csv}" into outfile

    when:
    true

    script:
    """
    echo "hello world" > output.txt
    """
}

process multiqc {

    input:
    file ('d/*') from outfile.collect()

    output:
    file "ls.txt" into multiqc_report

    script:
    """
    ls > ls.txt
    """
}
```

</details>

---

This works fine when the `when` clause is `true`:
```
N E X T F L O W  ~  version 0.27.5
Launching `main2.nf` [festering_rosalind] - revision: e216f3f145
[warm up] executor > local
[1b/0fb87a] Submitted process > sample_correlation
[9f/e61dbb] Submitted process > multiqc
```

But the final process doesn't run if `when` is `false`:
```
N E X T F L O W  ~  version 0.27.5
Launching `main2.nf` [mighty_bhaskara] - revision: 59c10943ab
[warm up] executor > local
```

On Gitter, the suggestion was to use `toList()` instead of collect. If `when` is `false` again this seems to do what we want - the final process does still run:

```
N E X T F L O W  ~  version 0.27.5
Launching `main2.nf` [friendly_bhaskara] - revision: 00292087d4
[warm up] executor > local
[c9/0651aa] Submitted process > multiqc
```

However, now the inverse fails - if `when` is `true` then the pipeline hangs before the final process:
```
N E X T F L O W  ~  version 0.27.5
Launching `main2.nf` [mighty_mendel] - revision: 144625ecb3
[warm up] executor > local
[2a/beaac7] Submitted process > sample_correlation
```
_(..hangs..)_

Note that this example script above I made by chopping away at the RNAseq pipeline. When I tried to build a minimal example from scratch it worked fine. So what is special about this particular set of code, I'm not sure...

This version seems to work fine:

---

<details>
<summary>Click to expand example script</summary>

```nextflow
#!/usr/bin/env nextflow

input_one = Channel.from( 1, 11, 111 )
input_two = Channel.from( 2, 22, 222 )

process proc_one {
    input:
    val ione from input_one

    output:
    file '*.txt' into output_one

    script:
    """
    echo $ione > one_${ione}.txt
    """
}

process proc_two {
    input:
    val itwo from input_two
    val num_vals from input_two.length()

    output:
    file '*.{txt,pdf}' into output_two

    when:
    num_vals > 2

    script:
    """
    echo "$itwo" > one_${itwo}.txt
    """
}

process proc_three {
    input:
    file ('one/*') from output_one.toList()
    file ('two/*') from output_two.toList()

    output:
    file "cat.txt" into multiqc_report

    script:
    """
    cat */* > cat.txt
    """
}
```

</details>

---

What the difference is between the two scripts, I have no idea..

Phil

**Comment by pditommaso** [comment]
Thanks for this detailed test case. Quick answer there's bug with the `toList` only when applied to a value channel ie. a channel that produces always the same value like `outfile` in your example: 

A workaround using `collect` is the following: 

```
DUMMY = file('dummy')

process sample_correlation {

    output:
    file "*.{txt,pdf,csv}" into outfile

    when:
    false

    script:
    """
    echo "hello world" > output.txt
    """
}

process multiqc {

    input:
    file ('d/*') from outfile.collect().ifEmpty(DUMMY)

    output:
    file "ls.txt" into multiqc_report

    script:
    """
    ls > ls.txt
    """
}
```

**Comment by pditommaso** [comment]
Related #612.

**Comment by pditommaso** [comment]
What's the status of this bug on your side? If needed I'm going to release a new version containing #612.

**Comment by ewels** [comment]
Hey!

I think that we're good after #612 and the new NF version. Just tried the above example and it was fine, and our RNA pipeline now seems to be working as expected... 👍 This seems cleaner than using the above `DUMMY` workaround (though thanks for that!)

Phil

**Comment by pditommaso** [comment]
👍

**Comment by nilaycan** [comment]
Hey!

How is the implementation of this "dummy" with the DSL-2 syntax? 

I have three outputs in my process and either one, any two or all can be empty due to previous process (just no significant output is produced) and process gives an error like "Missing output files". How to overcome this?

Cheers,
