### ISSUE TITLE
Nextflow is trying to use the Java VM

### ISSUE THREAD

**Issue by vsoch** [nextflow-io/nextflow#613]
I think I"m possibly hitting an issue like https://github.com/nextflow-io/nextflow/issues/607, the documentation says I don't need any other dependencies, but the error message says otherwise! Am I running an outdated command?

```
 wget -qO- get.nextflow.io | bash
/home/vanessa/Documents/Dropbox/Code/scif/examples/rnatoy.scif/nextflow: line 289: -version: command not found
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: 
 NXF_OPTS: 
```
Is it easy / customary to either install nextflow alongside the software it is intended to run (in the same container) or another container? Installing things (not on the host) would be ideal. I'm working on a tutorial for SCIF / nextflow / Singularity / Docker and I'd like to avoid installing things on the host.

**Comment by vsoch** [comment]
Can I just do:

```
docker run nextflow/nextflow
```
or is there a difference? I will be supplying the nextflow.config at runtime (with -C) so I think I would need to bind the directory with that, and then I'm wondering why can't I just package nextflow in the same container as the one I intend to run?

**Comment by vsoch** [comment]
I was able to create a singularity container from the Docker, like this:

```
singularity pull --name nextflow  docker://nextflow/nextflow
./nextflow
```

And now I am getting a cgroups issue, likely because we have two containers here :)

```
./nextflow run vanessa/rnatoy -C nextflow-docker.config -with-docker
OpenJDK 64-Bit Server VM warning: Unable to open cgroup memory limit file /sys/fs/cgroup/memory/memory.limit_in_bytes (No such file or directory)
```

What is the "best" / most reproducible way to do this?

**Comment by vsoch** [comment]
When I remove the `-with-docker` it looks like it wants to clone a github repository (instead of using my container that is built locally as `vanessa/rnatoy`)

```
./nextflow run vanessa/rnatoy -c nextflow-docker.config
OpenJDK 64-Bit Server VM warning: Unable to open cgroup memory limit file /sys/fs/cgroup/memory/memory.limit_in_bytes (No such file or directory)
N E X T F L O W  ~  version 0.27.5
Pulling vanessa/rnatoy ...
Cannot find `vanessa/rnatoy` -- Make sure exists a GitHub repository at this address `https://github.com/vanessa/rnatoy`
```
I think I'm very :confused: :(

**Comment by vsoch** [comment]
Here is what I have so far: https://github.com/vsoch/rnatoy.scif (see the README.md)

**Comment by pditommaso** [comment]
Many questions in this thread I will try to answer all. 

It happens that NF is a JVM application, therefore to run it requires a java installation or to use the pre-build container. 

Maybe it's not enough highlighted, how the [get started](https://www.nextflow.io/docs/latest/getstarted.html#requirements) begin with: 

> Nextflow can be used on any POSIX compatible system (Linux, Solaris, OS X, etc). It requires BASH and Java 8 or higher to be installed 

On using the pre-build container with singularity. That image is optimised to allow the JVM to use the correct cgroup information. I guess you you can just ignore that warning, otherwise you can just build a singularity image removing [this variable](https://github.com/nextflow-io/nextflow/blob/master/docker/Dockerfile#L17) definition.

Finally in the github error message. The run command expects a local script file to be executed or the name of a remote GitHub repository which contains your workflow project. It seems you providing instead a docker image name?

**Comment by vsoch** [comment]
okay second time is the charm! First I will update to java 8 and try the executable again:

```
curl -fsSL get.nextflow.io | bash

      N E X T F L O W
      version 0.27.5 build 4774
      last modified 15-02-2018 12:36 UTC (04:36 PDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io


Nextflow installation completed. Please note:
- the executable file `nextflow` has been created in the folder: /home/vanessa/Documents/Dropbox/Code/scif/examples/rnatoy.scif
- you may complete the installation by moving it to a directory in your $PATH
```
Yes this looks much better :)  And fussing with ordering in the command, I finally got it right:

```
./nextflow -C nextflow-docker.config run main.nf  -with-docker
```
I then added the docker.enabled to my config file, and I could just do:

```
./nextflow -C nextflow-docker.config run main.nf
```
How does it work to map data? It works with nextflow/rnatoy, but doesn't seem to find it for my container. I don't think I need to add it to the container? Or specify a bind? I'm looking here -> https://www.nextflow.io/docs/latest/config.html#scope-docker.

**Comment by vsoch** [comment]
I see in the docs:

>> Nextflow automatically manages the file system mounts each time a container is launched

**Comment by vsoch** [comment]
This might help - here is exactly the docker command that I want to issue:
 - Note that I'm binding the data directory to the container, so it can be found.
 - the scif entrypoint is still the run command (container entrypoint) but I add exec <app> to it to say exceute a command to <app>

```
docker run -v $PWD/data/:/data vanessa/rnatoy exec bowtie bowtie2-build
No input sequence or sequence file specified!
Bowtie 2 version 2.2.7 by Ben Langmead (langmea@cs.jhu.edu, www.cs.jhu.edu/~langmea)
Usage: bowtie2-build [options]* <reference_in> <bt2_index_base>
    reference_in            comma-separated list of files with ref sequences
    bt2_index_base          write bt2 data to files with this dir/basename
*** Bowtie 2 indexes work only with v2 (not v1).  Likewise for v1 indexes. ***
Options:
    -f                      reference files are Fasta (default)
    -c                      reference sequences given on cmd line (as
                            <reference_in>)
    --large-index           force generated index to be 'large', even if ref
                            has fewer than 4 billion nucleotides
    -a/--noauto             disable automatic -p/--bmax/--dcv memory-fitting
    -p/--packed             use packed strings internally; slower, less memory
    --bmax <int>            max bucket sz for blockwise suffix-array builder
    --bmaxdivn <int>        max bucket sz as divisor of ref len (default: 4)
    --dcv <int>             diff-cover period for blockwise (default: 1024)
    --nodc                  disable diff-cover (algorithm becomes quadratic)
    -r/--noref              don't build .3/.4 index files
    -3/--justref            just build .3/.4 index files
    -o/--offrate <int>      SA is sampled every 2^<int> BWT chars (default: 5)
    -t/--ftabchars <int>    # of chars consumed in initial lookup (default: 10)
    --threads <int>         # of threads
    --seed <int>            seed for random number generator
    -q/--quiet              verbose output (for debugging)
    -h/--help               print detailed description of tool and its options
    --usage                 print this usage message
    --version               print version information and quit
[bowtie] executing /scif/apps/bowtie/bin/bowtie2-build 
```

**Comment by pditommaso** [comment]
NF automatically mounts required host paths into an equivalent path in the container when using docker. When using singularity it's assumed that months are system wide defined. The config setting `runOptions` allows you to provide custom container settings, but it's a global setting ie. applied to all container executions.

**Comment by vsoch** [comment]
Okay, here is the command I'd want to execute to the container:

```
docker run -v $PWD/data:/data vanessa/rnatoy exec bowtie bowtie2-build --threads 1 ggal_1_48850000_49020000.Ggal71.500bpflank.fa genome.index
Error: could not open ggal_1_48850000_49020000.Ggal71.500bpflank.fa
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 --threads 1 ggal_1_48850000_49020000.Ggal71.500bpflank.fa genome.index 
[bowtie] executing /scif/apps/bowtie/bin/bowtie2-build --threads 1 ggal_1_48850000_49020000.Ggal71.500bpflank.fa genome.index
Settings:
  Output files: "genome.index.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  ggal_1_48850000_49020000.Ggal71.500bpflank.fa
Total time for call to driver() for forward index: 00:00:00
```
The function I have in main.nf is here:

```
process buildIndex {
    tag "$genome_file.baseName"
    
    input:
    file genome from genome_file
     
    output:
    file 'genome.index*' into genome_index
    
    """
    exec bowtie bowtie2-build --threads ${task.cpus} ${genome} genome.index
    """
}

```

and the error reported is here:

```
Feb-18 07:49:22.821 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Feb-18 07:49:22.829 [Task submitter] INFO  nextflow.Session - [6a/692eb4] Submitted process > buildIndex (ggal_1_48850000_49020000.Ggal71.500bpflank)
Feb-18 07:49:24.228 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: buildIndex (ggal_1_48850000_49020000.Ggal71.500bpflank); status: COMPLETED; exit: 127; error: -; workDir: /home/vanessa/Documents/Dropbox/Code/scif/examples/rnatoy.scif/work/6a/692eb4a8d0c8f6b24089642f0b760b]
Feb-18 07:49:24.322 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'buildIndex (ggal_1_48850000_49020000.Ggal71.500bpflank)'

Caused by:
  Process `buildIndex (ggal_1_48850000_49020000.Ggal71.500bpflank)` terminated with an error exit status (127)

Command executed:

  exec bowtie bowtie2-build --threads 1 ggal_1_48850000_49020000.Ggal71.500bpflank.fa genome.index

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: exec: bowtie: not found

Work dir:
  /home/vanessa/Documents/Dropbox/Code/scif/examples/rnatoy.scif/work/6a/692eb4a8d0c8f6b24089642f0b760b

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```
Internally, I had thought a "run" was being issued to the container (so my exec should work as above) but is something different happening?

**Comment by vsoch** [comment]
oh I think I see, the command is done totally internally to the container (disregarding the entrypoint entirely?) If I add the entrypoint to my "script" it seems to at least hit the same output (but doesn't work still):

```
Caused by:
  Missing output file(s) `genome.index*` expected by process `buildIndex (ggal_1_48850000_49020000.Ggal71.500bpflank)`

Command executed:

  scif exec bowtie bowtie2-build --threads 1 ggal_1_48850000_49020000.Ggal71.500bpflank.fa genome.index

Command exit status:
  0

Command output:
  [bowtie] executing /scif/apps/bowtie/bin/bowtie2-build --threads 1 ggal_1_48850000_49020000.Ggal71.500bpflank.fa genome.index
  Settings:
    Output files: "genome.index.*.bt2"
    Line rate: 6 (line is 64 bytes)
    Lines per side: 1 (side is 64 bytes)
    Offset rate: 4 (one in 16)
    FTable chars: 10
    Strings: unpacked
    Max bucket size: default
    Max bucket size, sqrt multiplier: default
    Max bucket size, len divisor: 4
    Difference-cover sample period: 1024
    Endianness: little
    Actual local endianness: little
    Sanity checking: disabled
    Assertions: disabled
    Random seed: 0
    Sizeofs: void*:8, int:4, long:8, size_t:8
  Input files DNA, FASTA:
    ggal_1_48850000_49020000.Ggal71.500bpflank.fa
  Total time for call to driver() for forward index: 00:00:00

Command error:
  Error: could not open ggal_1_48850000_49020000.Ggal71.500bpflank.fa
  Error: Encountered internal Bowtie 2 exception (#1)
  Command: bowtie2-build --wrapper basic-0 --threads 1 ggal_1_48850000_49020000.Ggal71.500bpflank.fa genome.index 

Work dir:
  /home/vanessa/Documents/Dropbox/Code/scif/examples/rnatoy.scif/work/3f/68d9396e924bf4c6c3808d0312d6ac

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Feb-18 08:00:32.699 [Actor Thread 3] DEBUG nextflow.Session - <<< barrier arrive (process: buildIndex)
Feb-18 08:00:32.707 [Actor Thread 5] DEBUG nextflow.Session - <<< barrier arrive (process: mapping)
Feb-18 08:00:32.721 [Actor Thread 6] DEBUG nextflow.Session - <<< barrier arrive (process: makeTranscript)
Feb-18 08:00:32.723 [main] DEBUG nextflow.Session - Session await > all process finished
Feb-18 08:00:32.727 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Missing output file(s) `genome.index*` expected by process `buildIndex (ggal_1_48850000_49020000.Ggal71.500bpflank)`
Feb-18 08:00:32.788 [main] DEBUG nextflow.Session - Session await > all barriers passed
Feb-18 08:00:32.799 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Feb-18 08:00:32.827 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=0; failedCount=1; ignoredCount=0; cachedCount=0; succeedDuration=0ms; failedDuration=1.6s; cachedDuration=0ms]
Feb-18 08:00:32.973 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Feb-18 08:00:33.058 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
```

I wish I had a sense of what is going on :/

**Comment by pditommaso** [comment]
Frankly I have no idea about what you are trying to do. Look at the script wrapper created by NF. I mean the file: 

```
 /home/vanessa/Documents/Dropbox/Code/scif/examples/rnatoy.scif/work/3f/68d9396e924bf4c6c3808d0312d6ac/.command.run
``` 

It will help you to understand what's going on.

**Comment by vsoch** [comment]
okay, I'm throwing in the towel and giving up. I got it working with the scientific filesystem and docker/singularity, but nextflow is acting in ways I can't figure out. The walkthrough is here: https://github.com/vsoch/rnatoy.scif if anyone else has interest to pick up. The issue is not resolved, but thank you for the brief help.

**Comment by vsoch** [comment]
I think the issue is nextflow trying to be a controller for singularity, when it should really just execute whatever I give it (regardless of container or not). Is that an approach that is possible?

**Comment by pditommaso** [comment]
If you enable the the support for singularity NF prepend each command execution with the `singularity exec` command. If you don't need it, just switch it off putting  in the config file

```
singularity.enabled = false
```

(or omitting that setting at all)

**Comment by pditommaso** [comment]
I'm closing this since there's no more feedback. Feel free to comment below if needed.

**Comment by sisterdot** [comment]
upon 
`singularity exec  nextflow.simg nextflow`

also got the error message:
`OpenJDK 64-Bit Server VM warning: Unable to open cgroup memory limit file /sys/fs/cgroup/memory/memory.limit_in_bytes (No such file or directory)`

bind paths issue in my case

solution on cluster1:
`singularity exec -B /sys:/sys nextflow.simg nextflow`
solution on cluster2:
`singularity exec -B /sys/fs:/sys/fs nextflow.simg nextflow`
