### ISSUE TITLE
Singularity vs. Docker "switch"

### ISSUE THREAD

**Issue by vsoch** [nextflow-io/nextflow#614]
In the example of converting the rnatoy example from Docker to Singularity, the comment is that the flip is just using these two lines:

```
singularity.enabled = true
process.container = '<the image file path>'
```
in the `nextflow.config` I see an (almost equivalent) but slightly different format (braces versus attributes)

```
process {
  container = 'nextflow/rnatoy@sha256:9ac0345b5851b2b20913cb4e6d469df77cf1232bafcadf8fd929535614a85c75'
}
```

So does it follow I can do this for the Docker --> Singularity "switch" ?

```
singularity {
    enabled = true
}

process {
    container = '<the image file path>'
}
```

**Comment by pditommaso** [comment]
NF config files can use either dot notation or curly brackets syntax, there's no difference between the twos. Therefore if you want to use singularity the above config should work.

**Comment by vsoch** [comment]
okay this seems ok! moving conversation to focus on other issue (still having trouble)
