### ISSUE TITLE
Launcher breaks when JAVA_HOME path contains a blank char

### ISSUE THREAD

**Issue by dreavjr** [nextflow-io/nextflow#616]
The installer command `wget -qO- get.nextflow.io | bash` stops if there's a space in `$JAVA_HOME` (which, unfortunately, is the default situation in macOS High Sierra).

Steps to reproduce:
```bash
$ export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
$ wget -qO- get.nextflow.io | bash

./nextflow.sh: line 289: /Library/Internet: No such file or directory
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
 NXF_OPTS: 
```
Broken workarounds: different ways of escaping the space in `$JAVA_HOME`. (Naïve) attempts to quote the variables `$JAVA_HOME` and `$JAVA_CMD` everywhere inside the installer script.

Workaround — symbolic linking Java's path to one without spaces, e.g.:
```bash
$ ln -s "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/" /usr/local/opt/jre8
$ export JAVA_HOME="/usr/local/opt/jre8"
$ wget -qO- get.nextflow.io | bash`
```
System: iMac with macOS High Sierra, GNU bash, version 3.2.57(1).

**Comment by pditommaso** [comment]
Thanks for reporting this but blanks in file paths are really an headache! :)

I've spotted the problem, it's no trivial to patch it, likely the symlink solution is the best workaround in the short term.

**Comment by pditommaso** [comment]
OK, this should be fine. You may want to give a try downloading the launcher at this path: 

```
www.nextflow.io/releases/v0.28.0-SNAPSHOT/nextflow
```

and using as usual

**Comment by ewels** [comment]
Super old issue, but just to note that I ran into this today (maybe due to an update to Big Sur?). The workaround mentioned above seemed to fix it for me too though 👍🏻

**Comment by pditommaso** [comment]
Working to a new "packing" systems that get rid of the current one and related issues, including this.

**Comment by nimarafati** [comment]
I had the same problem today and the solution above just solved the issue!
Thanks!

**Comment by chaochungkuo** [comment]
I am surprised that I ran into the same issue in 2021...

**Comment by dancooke** [comment]
I also hit this problem on macOS Monterey (12.1). My solution was to use Homebrew java:

```shell
% brew install java
% echo 'export PATH="/usr/local/opt/openjdk/bin:$PATH"' >> ~/.zshrc
% source ~/.zshrc
% java -XshowSettings:properties -version 2>&1 >/dev/null | grep java.home | awk '{printf "export JAVA_HOME=\"%s\"\n",$3;}' >> ~/.zshrc
% source ~/.zshrc
% curl -s https://get.nextflow.io | bash                      

      N E X T F L O W
      version 21.10.6 build 5660
      created 21-12-2021 16:55 UTC (13:55 BRST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io


Nextflow installation completed. Please note:
- the executable file `nextflow` has been created in the folder: /Users/dcooke
- you may complete the installation by moving it to a directory in your $PATH

% mv nextflow /usr/local/bin
% nextflow -self-update

      N E X T F L O W
      version 21.10.6 build 5660
      created 21-12-2021 16:55 UTC (13:55 BRST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io


Nextflow installation completed. Please note:
- the executable file `nextflow` has been created in the folder: /usr/local/bin
```

**Comment by mheskett** [comment]
Just adding my experience here as well. Got a new work laptop which is on macos monterey and receiving this same error. I guess ill try the brew install java route as above.

**Comment by NPante** [comment]
> I also hit this problem on macOS Monterey (12.1). My solution was to use Homebrew java:
> 
> ```shell
> % brew install java
> % echo 'export PATH="/usr/local/opt/openjdk/bin:$PATH"' >> ~/.zshrc
> % source ~/.zshrc
> % java -XshowSettings:properties -version 2>&1 >/dev/null | grep java.home | awk '{printf "export JAVA_HOME=\"%s\"\n",$3;}' >> ~/.zshrc
> % source ~/.zshrc
> % curl -s https://get.nextflow.io | bash                      
> 
>       N E X T F L O W
>       version 21.10.6 build 5660
>       created 21-12-2021 16:55 UTC (13:55 BRST)
>       cite doi:10.1038/nbt.3820
>       http://nextflow.io
> 
> 
> Nextflow installation completed. Please note:
> - the executable file `nextflow` has been created in the folder: /Users/dcooke
> - you may complete the installation by moving it to a directory in your $PATH
> 
> % mv nextflow /usr/local/bin
> % nextflow -self-update
> 
>       N E X T F L O W
>       version 21.10.6 build 5660
>       created 21-12-2021 16:55 UTC (13:55 BRST)
>       cite doi:10.1038/nbt.3820
>       http://nextflow.io
> 
> 
> Nextflow installation completed. Please note:
> - the executable file `nextflow` has been created in the folder: /usr/local/bin
> ```

Hi I tried this and I am getting the following error:

```
curl -s https://get.nextflow.io | bash
ERROR: Cannot find Java or it's a wrong version -- please make sure that Java 8 or later (up to 17) is installed
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /opt/homebrew/Cellar/openjdk/18/libexec/openjdk.jdk/Contents/Home/bin/java
 JAVA_HOME: /opt/homebrew/Cellar/openjdk/18/libexec/openjdk.jdk/Contents/Home
```

Any advice? I suppose I've set something up wrong in the install :S

**Comment by dancooke** [comment]
@NPante Homebrew java updated to version 18 - that cextflow doesn't support - after I posted those instructions. You'll now need to explicitly install `openjdk@17`:

```shell
% brew install openjdk@17
% echo 'export PATH="/usr/local/opt/openjdk@17/bin:$PATH"' >> ~/.zshrc
% source ~/.zshrc
% % java -XshowSettings:properties -version 2>&1 >/dev/null | grep java.home | awk '{printf "export JAVA_HOME=\"%s\"\n",$3;}' >> ~/.zshrc
% source ~/.zshrc
% nextflow self-update
```

**Comment by jorgeaguileraseqera** [comment]
I think was resolved in https://github.com/nextflow-io/nextflow/issues/2298

**Comment by rayhendricks** [comment]
Ran into this issue when trying to install nextflow on MacOS 13.2, with brew openjdk17. 

```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

/Users/rayhendricks/Nextflow/nextflow: line 287: /bin/java: No such file or directory
NOTE: Nextflow is trying to use the Java VM defined by the following environment variables:
 JAVA_CMD: /bin/java
 NXF_OPTS:

```

**Comment by rayhendricks** [comment]
Fixed it by using adoptopenJDK aka temurin rather than openJDK that homebrew packages🙃, also you need one release behind the latest JDK for nextflow to work. For anyone else getting the same error, **here is the workaround** for brew on Apple Silicion based Mac (arm64).


Info on the package: 

> ==> temurin17: 17.0.6,10
> https://adoptium.net/
> /opt/homebrew/Caskroom/temurin17/17.0.6,10 (169.4MB)
> From: https://github.com/Homebrew/homebrew-cask-versions/blob/HEAD/Casks/temurin17.rb
> ==> Name
> Eclipse Temurin Java Development Kit
> ==> Description
> JDK from the Eclipse Foundation (Adoptium)
> ==> Artifacts
> OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.6_10.pkg (Pkg) 


Then install it: 
`brew install --cask temurin17
`
