### ISSUE TITLE
env variables not correctly set in container environment

### ISSUE THREAD

**Issue by ODiogoSilva** [nextflow-io/nextflow#618]
I came across an issue where environmental variables defined via the `env` scope are not correctly set in a container environment **unless** the `bin` directory exists. Attached is a minimal example pipeline that should be ready to run ([minimal_example.zip](https://github.com/nextflow-io/nextflow/files/1740753/minimal_example.zip)).

I compared the `.command.run` files when executing the pipeline with or without the `bin` directory and was able to pinpoint the difference causing the issue. In the line that executes the process inside the container, this is what happens when the `bin` directory is absent:

```
docker run -i -e "NXF_DEBUG=${NXF_DEBUG:=0}" -v /home/diogosilva/Diogo/Science/Tests/Nextflow/environment_issue/work/57/a076f63b684b310f0a18d242ca66a5:/home/diogosilva/Diogo/Science/Tests/Nextflow/environment_issue/work/57/a076f63b684b310f0a18d242ca66a5 -v "$PWD":"$PWD" -w "$PWD" --entrypoint /bin/bash --name $NXF_BOXID ummidock/assemblerflow_base:1.0.0 -c "eval $(nxf_taskenv); /usr/bin/env python3 /home/diogosilva/Diogo/Science/Tests/Nextflow/environment_issue/work/57/a076f63b684b310f0a18d242ca66a5/.command.sh"
```

When the `bin` directory is present, the line changes to:

```
docker run -i -e "NXF_DEBUG=${NXF_DEBUG:=0}" -v /home/diogosilva/Diogo/Science/Tests/Nextflow/environment_issue:/home/diogosilva/Diogo/Science/Tests/Nextflow/environment_issue -v "$PWD":"$PWD" -w "$PWD" --entrypoint /bin/bash --name $NXF_BOXID ummidock/assemblerflow_base:1.0.0 -c "eval $(nxf_taskenv); /usr/bin/env python3 /home/diogosilva/Diogo/Science/Tests/Nextflow/environment_issue/work/42/2b9ccd303241fb442c73ebddd42f50/.command.sh"
```

Notice that the mapped volumes change from the process working directory (`/home/diogosilva/Diogo/Science/Tests/Nextflow/environment_issue/work/57/a076f63b684b310f0a18d242ca66a5:/home/diogosilva/Diogo/Science/Tests/Nextflow/environment_issue/work/57/a076f63b684b310f0a18d242ca66a5`) to the project directory (`/home/diogosilva/Diogo/Science/Tests/Nextflow/environment_issue:/home/diogosilva/Diogo/Science/Tests/Nextflow/environment_issue`).

If I change the paths from the `.command.run` to the project directory, it runs successfully. 

This seems to be an issue that is specific to the containerized environment, since this pipeline runs with or without the `bin` directory when executed locally.

**Comment by pditommaso** [comment]
Hi Diogo, I'm unable to replicate this issue. The above paths are different because if you have a `bin` directory in the project, NF mounts the project the project root directly as the lowest common path. But I don't see how this can impact the env.

**Comment by ODiogoSilva** [comment]
Sorry, but when I compressed the example pipeline I commented the `docker.enabled` part in nextflow.config. Could you check if the issue appears when you use docker? 

I performed another test on our slurm/shifter cluster, and the issue does not occur with shifter. In my laptop, if I change from docker to singularity, everything runs fine as well. It seems to be an issue specific of docker?

Here is the output that I get when running the pipeline with docker:

https://pastebin.com/MNcZrHtZ

**Comment by pditommaso** [comment]
Ok, got it. But it's not directly a bug. So what it happens is that you are the variable to a host path and then you are expecting that path to be accessed from the container. 

However docker requires an explicit mount to access host paths. This is done automatically for all declared inputs and other special directories such as `bin`. 

By default NF cannot recognise the path you have set in the env variable, hence it's not accessible from the container. 

When you create a `bin/` directory, NF mount the complete project root in the container therefore python will be able to resolve and access that path.

**Comment by ODiogoSilva** [comment]
I see. But in that case, this would create a consistency issue and pipelines like this would not work with every container engine. Perhaps this could be documented somewhere in the nextflow docs for docker offering the workaround of creating an empty bin for these cases? I could create a pull request with an update to `docker.rst` with this.

Also, is there any particular problem in setting the mount points in the project root even when the bin dirrectory does not exist?

**Comment by pditommaso** [comment]
You are right that this can create a portability problem, however this is a corner case that needs to be taken into account by the user. NF has no way to infer the semantic of env variables and creates a corresponding container mount. 

I agree to add a warning in the docker documentation, but I won't mention directly this particular use case because it's very specific.
