### ISSUE TITLE
warning when using --resume instead of -resume

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#624]
I know that this seem stupid but you cannot understand the frustration when you make this mistake and there is no more option than just wait...  :)
It would be wonderful to have an exit when making this mistake (like reserving this parameter).

**Comment by pditommaso** [comment]
This requires #556.

**Comment by lucacozzuto** [comment]
Yes. But in the meanwhile if there could be hardcoded somewhere something like (if --resume exit and warn "what the hell are you doing???", will be wonderful)

**Comment by pditommaso** [comment]
in the meanwhile, drink more coffee and pay more attention ;)

**Comment by lucacozzuto** [comment]
really, I already learnt the hard way but some people that is using our pipelines are still crying like baby after it :) Maybe I should put it myself ;)

**Comment by pditommaso** [comment]
If it were possible to distinguish between `-resume` and `--resume` to raise a warning, it would be possible to implement to correct behaviour and no warning would be required .. catch 22!

**Comment by lucacozzuto** [comment]
for now I just add:
if (params.resume) exit 1, "Are you making the classical --resume typo? Be careful!!!! ;)"

**Comment by pditommaso** [comment]
👍

**Comment by shaze** [comment]
A slightly more general temporary fix is to do the following -- create a variabel containing your legitimate options and then check  that only  those are given.

```
allowed_params = ["start", "cutoff", "theta","foo"]

params.each { entry ->
  if (! allowed_params.contains(entry.key)) {
      println("The parameter <${entry}.key> is not known");
      System.exit(2);
  }
}    


if (params.help) {
    params.each {
    entry ->
      print "Parameter: <$entry.key>    \t Default: $entry.value"
      help = params_help.get(entry.key)
      if (help) {
          print "\n    $help"
          println ""
      }
  }
  System.exit(0)
}
```
