### ISSUE TITLE
Unexpected scheduler agent error

### ISSUE THREAD

**Issue by dgarrimar** [nextflow-io/nextflow#625]
When using executor = "ignite", even if the pipeline finishes properly, the ignite job keeps running and writing in the log file:
```` 
ERROR ~ === Unexpected scheduler agent error
 -- Check '.nextflow.log' file for details
````
Checking the file .nextflow.log I found repeated thousands of times:
````

feb-25 20:51:09.564 [scheduler-agent] ERROR nextflow.scheduler.SchedulerAgent - === Unexpected scheduler agent error
java.lang.IllegalStateException: Cache has been closed or destroyed: nextflow.cache.pendingtasks
        at org.apache.ignite.internal.processors.cache.GridCacheGateway.enter(GridCacheGateway.java:160)
        at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.onEnter(IgniteCacheProxy.java:2054)
        at org.apache.ignite.internal.processors.cache.IgniteCacheProxy.query(IgniteCacheProxy.java:658)
        at nextflow.scheduler.SchedulerAgent$AgentProcessor.processPendingTasks(SchedulerAgent.groovy:284)
        at nextflow.scheduler.SchedulerAgent$AgentProcessor.run(SchedulerAgent.groovy:149)
````

**Comment by pditommaso** [comment]
Ugly! does this happen always or only with a certain script?

**Comment by dgarrimar** [comment]
I did not check with additional scripts, I'll have a look. It happens with one particular script sometimes, but not always

**Comment by pditommaso** [comment]
Could you please upload the complete log files. There should be a `.nextflow.log` and one or more `.node-nextflow.xxx` (or something similar) files.

**Comment by pditommaso** [comment]
I've gave a look with Emilio to the logs, it seems that is a problem with the temp directory. This to add to your submit script this variable 

```
export NXF_TEMP=$TMPDIR
```

**Comment by dgarrimar** [comment]
[logfiles.tar.gz](https://github.com/nextflow-io/nextflow/files/1763670/logfiles.tar.gz)
Here they go! ``logfiles/`` contains the ``.nextflow/`` folder and the file ``.nextflow_node_1.log`` for the run that failed. I just repeated the run again and now it worked normally.. so it seems that it does not happen all the time, as I pointed out before.

**Comment by pditommaso** [comment]
Hi Diego, have you tried the fix in the comment above ?

**Comment by dgarrimar** [comment]
Yes, thanks a lot, I've just re-run the pipeline with and w/o `` export NXF_TEMP=$TMPDIR  `` and the error appears when the env variable is not set up. However, interestingly I could not reproduce the error when running the same pipeline in a different folder.. Also, is this just a problem of wrapping up the ignite cluster? Because it seems that the results are unaffected. Or this may lead to failures in the pipeline?

**Comment by pditommaso** [comment]
So we can conclude that setting the right `NXF_TEMP` solve the issue, right? I guess it depends on wrong /tmp permissions on some nodes, therefore it fails randomly.

**Comment by dgarrimar** [comment]
Yes, it does. Thank you!
I just wanted to here your opinion about whether to re-calculate results obtained with the pipeline provided that this error happened, but they are as they should be..anyway thanks!

**Comment by pditommaso** [comment]
not sure to have understood your question :D If the pipeline completed successfully, it's fine ;)

**Comment by dgarrimar** [comment]
OK! thanks for the fast (and right) answer :)

**Comment by dgarrimar** [comment]
Ups.. for a small test dataset the solution you proposed worked fine, but I tried now with a different, much larger dataset (now requiring many more nodes for ignite) and found the same problem :( . Some of the tasks ran successfully, some others failed. Here are submission file and the .nextflow logs:
[logfiles.tar.gz](https://github.com/nextflow-io/nextflow/files/1778870/logfiles.tar.gz)

Thanks in advance!

**Comment by pditommaso** [comment]
This time it seems a different problem. In the log file, there's a suspicious `java.lang.OutOfMemoryError: Java heap space` error.

Also there's something odd in your cluster config. The log reports you are running 18 NF instances in the same node 

```
- nodeId=d0332ba2-a1af-4d11-bd11-5698849af3cc; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 18:57; tot-res:[cpus=48; mem=88.1 GB; disk=216.1 GB]; idle=-
- nodeId=677184ed-65e8-4800-b063-57b8e6dd847f; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 18:57; tot-res:[cpus=48; mem=88.1 GB; disk=216.1 GB]; idle=-
- nodeId=e13cdfa9-0203-4e73-8543-a37c4fbc6f56; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 18:57; tot-res:[cpus=48; mem=88.1 GB; disk=214.6 GB]; idle=-
- nodeId=3c027c79-76dc-495a-b4a8-d3179467b466; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 18:57; tot-res:[cpus=48; mem=88.1 GB; disk=216.1 GB]; idle=-
- nodeId=8532453f-a302-4197-8de5-60a7f72cf034; hostname=s03r1b32; instance-id: null; boot-time=07-Feb-2018 10:14; tot-res:[cpus=48; mem=88.1 GB; disk=216.1 GB]; idle=-
- nodeId=ca1f971e-cf24-453a-82cf-62da0ecd115a; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 15:25; tot-res:[cpus=48; mem=88.1 GB; disk=216.1 GB]; idle=-
- nodeId=bc618b19-4a87-4c97-b5ba-7bbab5abefd2; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 21:27; tot-res:[cpus=48; mem=88.1 GB; disk=216 GB]; idle=-
- nodeId=94dfbde7-784d-4664-bc80-bcdab38e44fd; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 18:57; tot-res:[cpus=48; mem=88.1 GB; disk=216.1 GB]; idle=-
- nodeId=2fc06ec9-b0f3-4d91-ab7f-feb2d60ea904; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 15:25; tot-res:[cpus=48; mem=88.1 GB; disk=216.1 GB]; idle=-
- nodeId=242fd47c-3f6a-4d52-b87a-86740a20a1b4; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 18:57; tot-res:[cpus=48; mem=88.1 GB; disk=216.1 GB]; idle=-
- nodeId=d5a368e2-f1a4-40a5-818e-337cbabed630; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 15:48; tot-res:[cpus=48; mem=88.1 GB; disk=212.3 GB]; idle=-
- nodeId=95f8d01c-77a9-4405-83f4-ce2de4d055bc; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 15:48; tot-res:[cpus=48; mem=88.1 GB; disk=215.8 GB]; idle=-
- nodeId=d33a8e34-d0a3-4808-9071-a1e273f873a6; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 18:57; tot-res:[cpus=48; mem=88.1 GB; disk=216 GB]; idle=-
- nodeId=3f056915-9282-45a9-ae81-6ea4ed0cda32; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 18:57; tot-res:[cpus=48; mem=88.1 GB; disk=216.1 GB]; idle=-
- nodeId=d86fd09b-2ca4-43e4-b6f7-1b81e1916e65; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 15:48; tot-res:[cpus=48; mem=88.1 GB; disk=215.9 GB]; idle=-
- nodeId=b2974499-e2ee-4456-89b0-3819edda75c1; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 15:48; tot-res:[cpus=48; mem=88.1 GB; disk=213.8 GB]; idle=-
- nodeId=5573bdd5-2451-4307-89eb-945591b60560; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 18:57; tot-res:[cpus=48; mem=88.1 GB; disk=214.6 GB]; idle=-
- nodeId=286fe8e8-1cda-4e74-a36b-d0b2079ce69c; hostname=s03r1b32; instance-id: null; boot-time=06-Feb-2018 18:57; tot-res:[cpus=48; mem=88.1 GB; disk=216.1 GB]; idle=-
```

I would try the following: 

1) increase the Java heap size 
2) decrease the number of node
3) also, it maybe required to use a different slurm directives to allocate the cluster nodes and make sure it only runs job for node. Have a look to the MN4 manuals there's a `nodes` directive. I would suggest to make a few tests with a dummy bash script before launching the NF pipeline.

**Comment by dgarrimar** [comment]
Uhm, I played around with these options. I ran a short example job which only sometimes it fails. 2) and 3) did not work. I tried to increase the Java heap size and didn't see the error in a few runs (5).. but still may happen that it occurs. It is true the fact that it looks as if there were several instances per node..
It is weird also that exactly the same pipeline, just with a smaller (a subset) input file -but still large to last several hours-, worked fine many times months ago. Actually I never saw this error before opening this issue. Maybe at MN they updated something. I will launch the *big* job to see if the java fix was the good one.

**Comment by pditommaso** [comment]
It turns out that the SLURM at MN mess-up the node `HOSTNAME` environment variable potentially causing problem in the NF cluster deployment. I think @emi80 is assisting you with this, have you managed to solve the issue?

**Comment by dgarrimar** [comment]
Yes, @emi80 is helping a lot with this. He proposed as a temporary solution to add ``unset HOSTNAME`` to the ``srun`` command in the submission script. This allows ignite to work well, we think, at least in our trials. I'll give it a try with the full dataset and let you know. Anyway, do you know if at some point in the future in MN they plan to configure this properly?

**Comment by pditommaso** [comment]
> Anyway, do you know if at some point in the future in MN they plan to configure this properly?

I don't think so. They say that's fine..  😕

**Comment by dgarrimar** [comment]
Uhm I think this solved the issue. However I found another problem that I cannot figure out. I think now is simpler :). Essentially it complains:

````
slurmstepd: error: Exceeded job memory limit at some point.
srun: error: s01r2b24: task 0: Out Of Memory
srun: Terminating job step 1291794.0
slurmstepd: error: Exceeded job memory limit at some point.
````
I am just running a process (i use ignite, as usual) that requires about 30Gb (actually several of those run in parallel). To make it simpler, I tell NF to run at most 8 processes at the same time (in the config file) and ask slurm for 8 nodes (48cores/node * 1.8Gb RAM at our beloved MN).  Do you have any guess about why this could be happenning?. Thanks!

**Comment by pditommaso** [comment]
So I guess it should run a single task per node (that would be NF daemon). How much memory are you asking per slurm task?

**Comment by dgarrimar** [comment]
I just solved it... apparently  ``memory = 40 GB`` in the config file does not work but it does not complain. ``memory = '40 GB'`` is the proper option (my fault :)). So it's running now! If it finishes properly I guess we can close the issue. Thanks a lot!

**Comment by dgarrimar** [comment]
I always sing for victory too early:

```
Exception in thread "tcp-disco-sock-reader-#10%nextflow%" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(ObjectInputStream.java:3363)
        at java.io.ObjectInputStream$BlockDataInputStream.readUTF(ObjectInputStream.java:3183)
        at java.io.ObjectInputStream.readString(ObjectInputStream.java:1863)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1526)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at org.apache.ignite.internal.util.IgniteUtils.readMap(IgniteUtils.java:4950)
        at org.apache.ignite.spi.discovery.tcp.internal.TcpDiscoveryNode.readExternal(TcpDiscoveryNode.java:598)
        at java.io.ObjectInputStream.readExternalData(ObjectInputStream.java:2076)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2025)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at org.apache.ignite.marshaller.jdk.JdkMarshaller.unmarshal(JdkMarshaller.java:102)
        at org.apache.ignite.spi.discovery.tcp.ServerImpl$SocketReader.body(ServerImpl.java:5341)
        at org.apache.ignite.spi.IgniteSpiThread.run(IgniteSpiThread.java:62)
ERROR ~ === Unexpected scheduler agent error

 -- Check '.nextflow_node_38.log' file for details
Exception in thread "tcp-disco-sock-reader-#18%nextflow%" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.jar.Attributes.read(Attributes.java:394)
        at java.util.jar.Manifest.read(Manifest.java:199)
        at java.util.jar.Manifest.<init>(Manifest.java:69)
        at java.util.jar.JarFile.getManifestFromReference(JarFile.java:199)
        at java.util.jar.JarFile.getManifest(JarFile.java:180)
        at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:981)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:450)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.ignite.internal.util.IgniteExceptionRegistry.onException(IgniteExceptionRegistry.java:77)
        at org.apache.ignite.spi.discovery.tcp.TcpDiscoveryImpl.onException(TcpDiscoveryImpl.java:141)
        at org.apache.ignite.spi.discovery.tcp.ServerImpl$SocketReader.body(ServerImpl.java:5546)
        at org.apache.ignite.spi.IgniteSpiThread.run(IgniteSpiThread.java:62)
```

Well this time we arrived quite far, but still some memory problems arise. Now the setting is slightly different. In the initial steps of the pipeline, this ram-hungry processes I told you ran ok. Now, there is a huge split of the computation in tens of thousands of jobs of variable duration and about 2/3Gb of RAM required. Which is the default in ignite/slurm if i do not specify more?  Could this be the cause?

**Comment by dgarrimar** [comment]
Here are the ``.nextflow*`` files, the ``submit.sh`` and the ``nextflow.config`` file i am using:
[logfiles.tar.gz](https://github.com/nextflow-io/nextflow/files/1815414/logfiles.tar.gz)

**Comment by pditommaso** [comment]
> java.lang.OutOfMemoryError: GC overhead limit exceeded

This makes me thing there's something wrong in your pipeline. Do you use any `.splitSomething` ?

**Comment by dgarrimar** [comment]
I use .splitText several times, here is the pipeline
[sQTLseekeR.nf.gz](https://github.com/nextflow-io/nextflow/files/1815455/sQTLseekeR.nf.gz)

**Comment by pditommaso** [comment]
That seems fine however something strange it's happening. I would suggest the following:

1) Add the following option in the JVM settings `-XX:+HeapDumpOnOutOfMemoryError`
2) when it will crash it will create a dump file of the Java memory heap 
3) share with me that file (it's pretty big several GB..)

**Comment by dgarrimar** [comment]
I see. I tried in a smaller run (same scripts and input data, but just 16 nodes * 48 cores/node) with this option and everything worked fine. The big one is queuing, I'll let you know. Could it be that for the big run (50 nodes * 48 cores/node = 2400 cores) I tell nextflow to run 2400 parallel processes (same number as cores, maybe should be bigger)? Or also that a heap of 4G is too big? Anyway let's see what do the dump file tell us.

**Comment by pditommaso** [comment]
The opposite, it could be the heap is too small for the big run (with 50 nodes). Ideally it would be needed to increased the heap memory only for the NF master instance, but unfortunately it's not possible. 

In any case I would try to increase the JVM heap max size to 8G and also to avoid to run the workflow tasks in the NF master instance setting the cli option `-cluster.master.maxCpus 0`

**Comment by dgarrimar** [comment]
Dear Paolo,

I ran the full project with ``-XX:+HeapDumpOnOutOfMemoryError`` and the pipeline ran perfectly, just at the end, when wrapping up, I got: 
```
Cleaning up.. Done.
Cleaning up.. Done.
Cleaning up.. Done.
slurmstepd: error: Exceeded step memory limit at some point.
slurmstepd: error: Exceeded job memory limit at some point.
Cleaning up.. Done.
srun: error: s09r1b11: task 6: Out Of Memory
srun: Terminating job step 1298485.0
slurmstepd: error: *** STEP 1298485.0 ON s06r1b71 CANCELLED AT 2018-03-18T07:57:26 ***
slurmstepd: error: Exceeded step memory limit at some point.
slurmstepd: error: Exceeded job memory limit at some point.
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
Cleaning up.. srun: error: s12r2b24: task 21: Killed
srun: error: s06r1b71: task 0: Killed
```
However all the outputs were there and everything seems to have worked. It actually looks like a slurm error.
Thus, I did one more trial setting a default ``memory`` option in ``nextflow.config``: ``memory = '3 GB'`` and now it works fine.. I do not understand very well why :). 

Keep you posted if I get new errors.

thanks!

**Comment by pditommaso** [comment]
OK. I'm closing this because it's not related anymore to the original problem. 

Also, could you share the launcher script you used for the successful execution?

**Comment by pditommaso** [comment]
@dgarrimar ping !

**Comment by dgarrimar** [comment]
Here it goes!
essentially the original problem was that MN4 had badly defined ``HOSTNAME`` env variable. Adding ``unset HOSTNAME`` before the nextflow command solved the problem.

```
#!/bin/bash
#SBATCH --job-name=sqtlseeker-nf
#SBATCH --output=sqtlseeker-nf.log
#SBATCH --ntasks=50
#SBATCH --cpus-per-task=48
#SBATCH --tasks-per-node=1
export NXF_CLUSTER_SEED=$(shuf -i 0-16777216 -n 1)
export NXF_TEMP=$TMPDIR
export NXF_OPTS=-XX:+HeapDumpOnOutOfMemoryError
module load java
module load intel/2018.1
module load singularity
srun bash -c 'unset HOSTNAME; nextflow run sQTLseekeR.nf -w ~/scratch/work -with-report report.html -with-trace -with-timeline time.html -with-dag flowchart.dot --mode permuted --genotype gtex/snps.tsv --trexp gtex/tq.rsem.tsv.gz --genes gtex/genes.bed --svqtl true --metadata gtex/metadata.tsv --kn 10 -with-mpi'
```
Thanks so much for your help!!!

**Comment by pditommaso** [comment]
Nice! thanks!
