### ISSUE TITLE
Task cache should be invalided when using a different environment module

### ISSUE THREAD

**Issue by ax-ekk** [nextflow-io/nextflow#627]
When not using dockers, changes in nextflow.config does not prompt the affected processes to re-run when nextflow is run with the -resume flag. For e.g. documentation purposes it would be great if what is defined in the config file is guaranteed to be the software used.

**Comment by pditommaso** [comment]
I fear this is a feature, not bug. What's exactly your use case ?

**Comment by ax-ekk** [comment]
Yes, maybe it’s rather a feature request, I wasn’t quite sure.

The thing is that if one makes changes it the config file after having run the pipeline, those do not trigger nextflow to re-run the processes with the e.g. the new software versions. For me it would make sense if it did as otherwise it may look like one software was used (because it is defined in the config file) when indeed a previously defined tool/version was used.



Elin Axelsson
Bioinformatician

Gregor Mendel Institute of Molecular Plant Biology GmbH
Dr. Bohr-Gasse 3, 1030 Vienna, Austria
Phone: +43 1 79044 9891
elin.axelsson@gmi.oeaw.ac.at
http://www.gmi.oeaw.ac.at

[cid:gmisig_231_92997f80-ec0b-4736-9e1e-b20adcb9ca37.png]

 On Mar 5, 2018, at 11:34 AM, Paolo Di Tommaso <notifications@github.com<mailto:notifications@github.com>> wrote:


I fear this is a feature, not bug. What's exactly your use case ?

**Comment by pditommaso** [comment]
Do you mean when using a different [module](https://www.nextflow.io/docs/latest/process.html#module) environment?

**Comment by ax-ekk** [comment]
Sorry for the late reply, got hit by a fever virus. 

Yes, I mean when loading a different module e.g:
module 'kallisto/0.43.1' instead of
module 'kallisto/0.42.4’

this does not trigger the kallisto process to be re-run, which I naively had thought it should. Maybe there should be at least a warning? Guess that is a feature request though. 

Best wishes, 
Elin 


Elin Axelsson
Bioinformatician

Gregor Mendel Institute of Molecular Plant Biology GmbH
Dr. Bohr-Gasse 3, 1030 Vienna, Austria
Phone: +43 1 79044 9891
elin.axelsson@gmi.oeaw.ac.at
http://www.gmi.oeaw.ac.at

**Comment by pditommaso** [comment]
Yes, it makes sense. Changing module should invalidate the task cache.
