### ISSUE TITLE
Singularity pull is executed even when container execution is disabled

### ISSUE THREAD

**Issue by Hammarn** [nextflow-io/nextflow#628]
Toy example:
```
profiles {

  standard {
    includeConfig 'conf/config1'
    includeConfig 'conf/config2'
  }
}
```
config1:
```
singularity {
  enabled = true
}
```
config 2:
```
singularity {
  enabled = false
}
```
with Nextflow v 0.25.1 I get singularity `false` at runtime but with 0.27.6 i get `true`
And I was expecting the earlier behaviour, we have our RNA config files set up with that in mind :
https://github.com/SciLifeLab/NGI-RNAseq/blob/master/nextflow.config#L35

Log from full pipeline
[singularity.nextflow.log](https://github.com/nextflow-io/nextflow/files/1781641/singularity.nextflow.log)

**Comment by pditommaso** [comment]
Unable to reproduce.

**Comment by pditommaso** [comment]
What's the status of this, can be closed ?

**Comment by Hammarn** [comment]
Well, I tried to make a minimal example but it was hard to get to work. 
This issue stops us from running on our production cluster with newer Nextflow versions so I'd rather you keep it open.

**Comment by ewels** [comment]
Minimal example:
[nf-singularity.zip](https://github.com/nextflow-io/nextflow/files/1790960/nf-singularity.zip)

```
$ nextflow -version

      N E X T F L O W
      version 0.27.6 build 4775
      last modified 19-02-2018 08:45 UTC (09:45 CEST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io




$ nextflow run main.nf
N E X T F L O W  ~  version 0.27.6
Launching `main.nf` [small_khorana] - revision: 486b3bbb4c
[warm up] executor > local
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /Users/philewels/GitHub/nf-singularity/work/singularity
Pulling Singularity image docker://scilifelab/ngi-rnaseq [cache /Users/philewels/GitHub/nf-singularity/work/singularity/scilifelab-ngi-rnaseq.img]
ERROR ~ Error executing process > 'testOutput'

Caused by:
  Failed to pull singularity image
  command: singularity pull --name scilifelab-ngi-rnaseq.img docker://scilifelab/ngi-rnaseq > /dev/null
  message:
  bash: singularity: command not found



 -- Check '.nextflow.log' file for details
```

```
$ NXF_VER=0.25.1 nextflow -version

      N E X T F L O W
      Version 0.25.1 build 4460
      last modified 27-06-2017 12:31 UTC (14:31 CEST)
      cite doi:10.1038/nbt.3820
      http://nextflow.io




$  NXF_VER=0.25.1 nextflow run main.nf
N E X T F L O W  ~  version 0.25.1
Launching `main.nf` [stoic_thompson] - revision: 486b3bbb4c
[warm up] executor > local
[e1/0966e2] Submitted process > testOutput
ERROR ~ Error executing process > 'testOutput'

Caused by:
  Process `testOutput` terminated with an error exit status (2)

Command executed:

  multiqc -v > output.txt

Command exit status:
  2

Command output:
  (empty)

Command error:
  Usage: multiqc [OPTIONS] <analysis directory>

  Error: Missing argument "analysis_dir".

  This is MultiQC v1.5.dev0 (5e39ce1)

  For more help, run 'multiqc --help' or visit http://multiqc.info

Work dir:
  /Users/philewels/GitHub/nf-singularity/work/e1/0966e2a2095bc913b7d923f1264a6a

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```


The errors aren't really relevant here - what's important is that in the first example it's trying to use singularity, even thought it should be `false`. In the second example with an older version of nextflow the error message is from MultiQC directly because nextflow _didn't_  try to use singularity.

**Comment by ewels** [comment]
nb: This seems to be specific to the singularity config:

```groovy
singularity {
  enabled = true
}
```

Initially I tried to reproduce with regular variables and they worked fine.

**Comment by pditommaso** [comment]
Squashed! the problem is not the config file/object but the fact the NF tries to download a remote singularity image even when the singularity engine is disabled.

**Comment by ewels** [comment]
Hooray! Thanks for finding & fixing this..

**Comment by pditommaso** [comment]
Thanks you for reporting it.
