### ISSUE TITLE
Resumption of tasks that have never completed succesfully

### ISSUE THREAD

**Issue by evanfloden** [nextflow-io/nextflow#629]
When using `-resume`, if a task has never completed successfully but has been attempted multiple times in a previous execution (ie `$task.attempts > 1`), the resumption starts with `$task.attempt=1` and not the last failed `$task.attempt`.

There could be an option whereby upon retry, the task is attempted from the from the last failed `$task.attempt`.

**Comment by baffelli** [comment]
+1, not having the 'task.attempt' counter reset when using '-resume' would be very useful and could sigificantly speedup pipeline debugging, as the previously failed and ignored task will not be resubmitted again, a problem I ecounter frequently due to lousy data...

**Comment by aunderwo** [comment]
related to this and this is more critical, if there are `$task.attempts > 1` and one of the later `task.attempts` succeeds resume ignores the fact that it succeeded and tries to rerun it.

The reason for initial failure could be many fold e.g spot instance is shut down on AWS, temporary network issue or in my case increasing memory specified on each task attempts and the initial memory is not sufficient for some input data
