### ISSUE TITLE
ifEmpty() Operator Doesn't work on a null channel

### ISSUE THREAD

**Issue by williamdgn** [nextflow-io/nextflow#63]
Hi all,
If you apply this script you will with the print() function consume all the value emitted by a channel.  The channel Type return is null and the ifEmpty function can not work in this condition.  Do you think I used correctly the ifEmpty function.

	#!/usr/bin/env nextflow
	_newChannel = [1, 2, 3, 4, 5, 6, 6, 7, 77, 7777, 7765, 21].channel()
	_stringChannel = ['aa', 'qqq', 'qsas'].channel()
	_newChannel2 = [1, 2, 3, 4, 5, 6, 6, 7, 77, 7777, 7765, 21].channel()
	_empty = [].channel()

	process outputValue {

	input:
	val mavaleur from _newChannel2

	output:
	stdout st into _std

	shell:

	'''
	echo !{mavaleur}
	'''
	}
	
	process MyFile {

	input:
	file data from _std.collectFile(name: "Result_null.txt" , seed: "I am a test \n").flatten()

	output:
	file "MyDuplicate" into _duplicate

	shell:

	'''
	cat !{data} > MyDuplicate
	'''
	}
	
	process MyFile {

	input:
	file data from _stringChannel.view().print().ifEmpty("hello")

	output:
	file "MyDuplicate" into _lawawi

	shell:

	'''
	cat !{data} > MyDuplicate
	'''
	}

**Comment by pditommaso** [comment]
No. Since the `print` operator has no return value, you cannot apply `ifEmpty` (or any other operator) to it. 

Does this answer your question?

**Comment by williamdgn** [comment]
Yes, So in case where a process return an Empty Channel, the ifEmpty()
operator will work?

thanks for your time

**Comment by pditommaso** [comment]
Of course. The point is that `print` returns nothing (that obviously is different from an empty channel)
