### ISSUE TITLE
Config dag.enabled option

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#633]
The timeline, trace and report can all be turned on by default in the Nextflow config. However, I can't see any option to do the same for the DAG. Could the following corresponding scope please be added?

```groovy
dag {
    enabled = true
    file = 'pipeline_dag.png'
}
```

**Comment by ewels** [comment]
Also, is it possible to have multiple DAG file outputs? eg. `PNG` _and_ `SVG`, `html` etc..

**Comment by pditommaso** [comment]
> However, I can't see any option to do the same for the DAG

Yes, it's [supported](https://github.com/nextflow-io/nextflow/blob/881af34727f27c44e09b2f79cfe9ff1d3f03a70d/src/main/groovy/nextflow/Session.groovy#L375). 

> Also, is it possible to have multiple DAG file outputs? 

I would suggest a portable format like svg or dot and then generate the others

**Comment by pditommaso** [comment]
I think this can be closed. Feel free to comment below if needed.
