### ISSUE TITLE
Ability to enable or disable usage of modules

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#636]
If a process includes a [`module`](https://www.nextflow.io/docs/latest/process.html#module) directive, then Nextflow returns an error if run on a system that does not have 'modules' installed. 

On the other hand, if you specify a directive such as [`container`](https://www.nextflow.io/docs/latest/process.html#container), but use a [config](https://www.nextflow.io/docs/latest/config.html#scope-docker) such as `docker.enabled = false`, the `container` directive is ignored, and Nextflow executes without trying to use the container. 

It would be helpful if an 'enable/disable' toggle existed for the `module` directive as well. In the current state, a Nextflow pipeline that includes modules cannot be run on any other system that lacks modules, which impairs portability. For example, our HPC cluster has modules, but other systems do not, meaning the Nextflow pipeline written to use modules available on our HPC cluster cannot be run in any other location, such as other VMs, locally, AWS, etc.

Not sure how hard this would be to implement, since it seems like 'modules' get applied to the task execution at a different time than 'container', such that I end up having to use both `module "singularity/2.4"` and `container "my_container"` in my pipelines since Singularity is itself a module on our system.

**Comment by pditommaso** [comment]
This is a duplicated of #522.
