### ISSUE TITLE
Default singularity cachedir does not work with Slurm

### ISSUE THREAD

**Issue by Hammarn** [nextflow-io/nextflow#637]
See the origninal issue on our repo: https://github.com/SciLifeLab/NGI-RNAseq/issues/200

If the singularity cach directory is not set, then each time a job is submitted to the slurm jobhandler singularity tried to pull and build the image. Nextflow set the cache to the work directory of the pipeline execution, and i was expecting that to work. Especially since that's how I wanted to set up the pipeline. 

I'm guessing that the individual compute nodes have trouble 

If the cache is set then everything works fine.

**Comment by pditommaso** [comment]
Not understanding, how is the container defined in the configuration file?

**Comment by pditommaso** [comment]
Any feedback on this ?

**Comment by Hammarn** [comment]
It's odd to say the least. 
It's not consistent and only happens with this profile:
https://github.com/SciLifeLab/NGI-RNAseq/blob/master/nextflow.config#L40

Container defined here:
https://github.com/SciLifeLab/NGI-RNAseq/blob/master/nextflow.config#L21

**Comment by pditommaso** [comment]
what's the dump of `nextflow config` for that profile ?

**Comment by Hammarn** [comment]
I'm unable to reproduce it now, and after talking to @ewels and our cluster administrators I think that is is actually a file system issue at it's core and not a Nextflow issue.
I'll close the issue now and will re-open it if I  see it again adn can get a log. 
Thanks for trying to help.

**Comment by pditommaso** [comment]
These are my preferred bugs! :)
