### ISSUE TITLE
Option to limit process requirements instead of exiting with error

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#640]
If Nextflow encounters a process that requests resources that are not available on the current system, it fails. For example, if 10 processors are requested and the system only has 8, we exit with an error. This is A Good Thing 👍 

However, when making config files for a pipeline that aim to have generic works-for-most-situations requests, it can be nice to be able to throttle these for small genomes / test datasets / small machines for example.

In most of our pipelines, we now have [this little helper function](https://github.com/nf-core/methylseq/blob/2b2d801bf26bd34bc3ba4c6b9e024b947410dad5/nextflow.config#L105-L136) in `nextflow.config`:

```groovy
// Function to ensure that resource requirements don't go beyond
// a maximum limit
def check_max(obj, type) {
  if(type == 'memory'){
    try {
      if(obj.compareTo(params.max_memory as nextflow.util.MemoryUnit) == 1)
        return params.max_memory as nextflow.util.MemoryUnit
      else
        return obj
    } catch (all) {
      println "   ### ERROR ###   Max memory '${params.max_memory}' is not valid! Using default value: $obj"
      return obj
    }
  } else if(type == 'time'){
    try {
      if(obj.compareTo(params.max_time as nextflow.util.Duration) == 1)
        return params.max_time as nextflow.util.Duration
      else
        return obj
    } catch (all) {
      println "   ### ERROR ###   Max time '${params.max_time}' is not valid! Using default value: $obj"
      return obj
    }
  } else if(type == 'cpus'){
    try {
      return Math.min( obj, params.max_cpus as int )
    } catch (all) {
      println "   ### ERROR ###   Max cpus '${params.max_cpus}' is not valid! Using default value: $obj"
      return obj
    }
  }
}
```

Then, [in each config](https://github.com/nf-core/methylseq/blob/2b2d801bf26bd34bc3ba4c6b9e024b947410dad5/conf/base.config#L20-L22) we wrap the request in the above function, as so:

```groovy
cpus = { check_max( 1 * task.attempt, 'cpus') }
memory = { check_max( 8.GB * task.attempt, 'memory') }
time = { check_max( 2.h * task.attempt, 'time') }
```

This way, the defaults work most of the time. But if you pass `--max_memory "8.GB"` then all processes will use a maximum of `8.GB` and the pipeline will run on your tiny machine. This is really helpful for test datasets and allows us to have a default "base" config file that is throttled by other system-specific configs.

Is this something that could be built into Nextflow as a new feature? Keep the current default behaviour, but have new command line arguments and config scopes to be able to throttle the maximum resources without failing..

Phil

**Comment by ewels** [comment]
As well as / instead of these manually specified limits, there could perhaps be something similar to `errorStrategy`:

```groovy
process {
    notEnoughResources: 'terminate' // default behaviour
    notEnoughResources: 'limit'     // throttle to available resources
    notEnoughResources: {           // limit to specified values
        cpus: 4
        memory: 8.GB
        time: 16.h
    }
}
```

**Comment by pditommaso** [comment]
So, as first thing I would suggest to use this simplified version of `check_max` function that infers that infers the argument type and takes the max value as second argument. 

```
def check_max(obj, max) {
    if( obj instanceof nextflow.util.MemoryUnit ) {
        try {
            def other = max as nextflow.util.MemoryUnit
            return obj.compareTo(other) == 1 ? other : obj
        }   
        catch( all ) {
            println "   ### ERROR ###   Max memory '${max}' is not valid! Using default value: $obj"
            return obj
        }   
    }
    if( obj instanceof nextflow.util.Duration ) {
        try {
            def other = max as nextflow.util.Duration
            return obj.compareTo(other) == 1 ? other : obj
        }   
        catch( all ) {
            println "   ### ERROR ###   Max time '${max}' is not valid! Using default value: $obj"
            return obj
        }         
    }
    if( obj instanceof Integer ) {
        try {
            return Math.min( obj, max as int )
        }   
        catch( all ) {
            println "   ### ERROR ###   Max cpus '${max}' is not valid! Using default value: $obj"
           return obj
        }         
    }    
}
```

Still not sure if the best thing is to add a build-in function like the above or implement a move advanced feature as you are suggesting in the second comment.

**Comment by ewels** [comment]
Ace! Thanks for the improved function, I will use that in the short term at least 👍 

Still think that the core feature would be better though 😉

**Comment by pditommaso** [comment]
also the `try` `catch` should be useless, therefore it could be simplified as: 

```
def check_max(obj, max) {
    if( obj instanceof nextflow.util.MemoryUnit ) {
          def other = max as nextflow.util.MemoryUnit
          return obj.compareTo(other) == 1 ? other : obj
    }
    if( obj instanceof nextflow.util.Duration ) {
          def other = max as nextflow.util.Duration
          return obj.compareTo(other) == 1 ? other : obj     
    }
    if( obj instanceof Integer ) {
          return Math.min( obj, max as int )  
    }    
}
``` 

> Still think that the core feature would be better though

I agree !

**Comment by ewels** [comment]
Aha, because we're now testing the type - nice! But if supplied on the command line, will these not always be strings? I think that's why I was trying to coerce the type (and catching the exception if it failed)..

**Comment by pditommaso** [comment]
I was a bit too optimistic, yes the `try` `catch` is need to handler and invalid *max* value (I was thinking to `obj` instead).

**Comment by ewels** [comment]
Could probably just have one `try`/ `catch` statement wrapping the whole function though at least...

**Comment by pditommaso** [comment]
Yep, but want be able anymore to have specific error message then

**Comment by ewels** [comment]
You could check the type of `obj` to customise it.. ;) But may end up not saving many lines of code..

**Comment by pditommaso** [comment]
lol

**Comment by ewels** [comment]
I can't resist a challenge 😆How about this?

```groovy
def check_max(obj, max) {
    def obj_types = [
        'memory': nextflow.util.MemoryUnit,
        'time': nextflow.util.Duration,
        'cpus': Integer
    ]
    obj_types.each { key, obj_type ->
        try {
            if( obj instanceof obj_type )
                return obj.compareTo(max as obj_type) == 1 ? max as obj_type : obj
        catch( all ) {
            println "   ### ERROR ###   Max $key '${max}' is not valid! Using default value: $obj"
            return obj
        }
    }
    println "   ### ERROR ###   Object type not recognised! Using default value: $obj"
    return obj
}
```

**Comment by pditommaso** [comment]
if it works, it's good :)

**Comment by ewels** [comment]
Haven't tested it yet.. ;)

Copying my main request back down here as we got a bit carried away by function refactoring 😁 

```groovy
process {
    notEnoughResources: 'terminate' // default behaviour
    notEnoughResources: 'limit'     // throttle to available resources
    notEnoughResources: {           // limit to specified values
        cpus: 4
        memory: 8.GB
        time: 16.h
    }
}
```

**Comment by ewels** [comment]
Not sure I totally understand the question. But I was thinking that the syntax could remain the same as it is currently - static values would be limited (modified) at runtime by nextflow if needed to make them smaller, dynamic rules could be used with `task.attempt` etc and then limited if needed.

**Comment by ewels** [comment]
Yup!

**Comment by ewels** [comment]
Proposed syntax after discussion with default value and also a range (minimum and maximum values).

```nextflow
process {
    withName:fastqc {
        memory: { 1.GB * input.size(), range: 8.GB..24.GB },
        time: { 2.4.h * input.size(), range: 16.h..48.h },
        cpus: { 2  * input.size(), range: 4..16 }
    }
}
```

The `input.size()` dynamic computation here is just an example of when we could have a variable default. Here the maximum of the range would prevent the requested resources from going above a sensible default.

Another scenario is when people want to limit the requested resources:

```nextflow
process {
    memory: 4.GB
    withName:fastqc {
        memory: 16.GB, range: 8.GB..24.GB
    }
    withName:star {
        memory: 4.GB, range: 2.GB..6.GB
    }
}
```
Then have `nextflow run --max_memory 8.GB` which would work - using `8.GB` memory for `fastqc` and `4.GB` memory for `star`.

However, doing `nextflow run --max_memory 2.GB` would exit with an error because this is outside the range of `fastqc`.

Phil

**Comment by ewels** [comment]
This is still probably my number-1 feature request issue 😄  The @nf-core `check_max` function is a constant thorn in the side, but it's too useful to remove. Would be great if we could move this functionality into Nextflow 👍

**Comment by pditommaso** [comment]
I agree we need definitively better here, soon I need to tackle this problem.  Pinning this issue.

**Comment by ewels** [comment]
Was it intentional to let this issue be auto-closed @pditommaso?

> I agree we need definitively better here, soon I need to tackle this problem. Pinning this issue.

**Comment by pditommaso** [comment]
It seems the bot ignores the `pinned` label :/

**Comment by ewels** [comment]
This sounds awesome! Couple of quick thoughts:

- If this is going to be used for all pipelines on all systems, then yeah I think renaming `request` to `min` would be good. To me, `request` sounds like the ideal value to aim for rather than a minimum (kind of like the default value that we want). I guess most of the people on HPCs etc won't care about this minimum value so can just ignore it?
- Would the two values inherit through child nodes in the config separately? Based on your example, I'm thinking that we would ideally want to do something like this:
    
    ```nextflow
    params.max_memory = 24.GB
    process {
        memory: 4.GB, limit: params.max_memory
        withName:fastqc {
            memory: 16.GB
        }
        withName:star {
            memory: 4.GB
        }
    }
    ```
    
    So we could continue our [current behaviour](https://github.com/nf-core/configs/blob/e9d93d62e0c4646d0191337d27f1941f8ecfe2c5/conf/uppmax.config#L11-L14) of setting the maximum resources available on different systems via parameters , and the pipeline can request whatever it wants. If the default is more than the `limit` then the `limit` will be used (even if the `limit` is set at global `process` level and the `request` is set at a more specific process level). So running the above with `--max_memory 2.GB` would request 2GB for all jobs. Would that work?

**Comment by bentsherman** [comment]
Hey guys, I've been working on this issue and thinking aloud over at #2903 . Curious for your input.

What I've concluded is that we can't really use `limit` to both enforce system resource limits and map to `limit` in the k8s pod spec. They mean slightly different things. Instead, I think we should use `request` and `limit` only for k8s, and use a separate option called `max` to enforce system limits.

Regarding this use case:
```
process {
    withName:fastqc {
        memory = { 1.GB * input.size(), range: 8.GB..24.GB },
        time = { 2.4.h * input.size(), range: 16.h..48.h },
        cpus = { 2  * input.size(), range: 4..16 }
    }
}
```

If you want to put guardrails around a dynamic computation, you should just use standard Groovy logic since you're already in a closure:
```
        memory: { min(max(8.GB, 1.GB * input.size()), 24.GB) },
```

With that case handled, we don't really need a `min` option to enforce minimums. So I think `request`, `limit`, and `max` are sufficient.

**Comment by bentsherman** [comment]
Don't get me wrong, I am only talking about examples where you might want a minimum threshold. That seems to be a rare case as it is not needed for enforcing system resource limits. I'm thinking we can just add a `max` option for now as a corresponding `min` option might be more complicated. But we will see as I work through this PR.

**Comment by ewels** [comment]
Yup, totally agree 👍🏻 Most configs are not dependent on input file size like your example. That's basically the only use case for a minimum that I can think of..

**Comment by pditommaso** [comment]
Think there are multiple topics in this thread. I think the core point is how to replace the need for the `check_max` custom function. 

The ideal solution would be using the range notion e.g. 

```
process.memory = [range: 8.GB..24.GB]
``` 

The attempt could be inferred automatically, but how to express the increase factor? using another attribute?

**Comment by bentsherman** [comment]
> The attempt could be inferred automatically, but how to express the increase factor? using another attribute?

I would do it like this:
```
process.memory = [min: 8.GB, max: 24.GB, step: 8.GB]
```

**Comment by bentsherman** [comment]
However I don't think we need to go that far, a `max` option would be enough to replace `check_max`. If the user wants to increase on each attempt they can just use a closure:
```
process.memory = { 8.GB * task.attempt, max: 24.GB }
```

They don't need a function for that, it's just that `check_max` is too big to implement inline.

But I bring up the issue of `request` and `limit` for k8s because it is related. We need to be able to distinguish between `limit` used in k8s pod spec and `max` to enforce resource limits like `check_max`.

**Comment by ewels** [comment]
Are the additional attributes (sorry I forget the name in Groovy) inherited separately to the main value? For example, would my process 'foo' here also have a max of `10.GB`?

```nextflow
process.memory = 3.GB, max: 10.GB
process.withName['foo'].memory = 20.GB
```

**Comment by bentsherman** [comment]
I don't plan to implement that kind of behavior at the moment. Are there any other directives that can inherit individual attributes like that? For example I don't think `publishDir` does that.

**Comment by ewels** [comment]
Not that I know of. Would it be acceptable to use a distinct namespace instead to be able to achieve this? eg. Something along the lines of my original suggestion way up there 👆🏻 

https://github.com/nextflow-io/nextflow/issues/640#issuecomment-375120839

```groovy
process {
    notEnoughResources: 'terminate' // default behaviour
    notEnoughResources: 'limit'     // throttle to available resources
    notEnoughResources: {           // limit to specified values
        cpus: 4
        memory: 8.GB
        time: 16.h
    }
}
```

Then it can be defined once to work across an entire workflow (desired behaviour 99% of the time I suspect) but also at process level if more granular control is needed.

**Comment by bentsherman** [comment]
I like this idea. No need to refactor the resource directives, Nextflow just needs to apply these limits before submitting a task. I would make it even simpler:
```
process {
    resourceLimits = null   // default behaviour
    resourceLimits = [      // limit to specified values
        cpus: 4
        memory: 8.GB
        time: 16.h
    ]
}
```

**Comment by ewels** [comment]
Yeah I think the `'limit'` / `// throttle to available resources` thing was me being hopeful about Nextflow auto-detecting available cpus, memory etc I think. But that's probably super problematic as many people will be running Nextflow on a different nodes. So yeah, let's forget about that (could probably do it with closures anyway..?)

So I'm fully behind your suggested syntax 👍🏻  (was `{}` instead of `[]` intentional?)

**Comment by aydemiro** [comment]
Hi,

Would below code in a config file work currently as an alternative to defining a `check_max` function?
```
params.max_memory = 32.GB
memory = { min( 6.GB * task.attempt, params.max_memory ) }
```

**Comment by bentsherman** [comment]
That should work. I believe `check_max()` just adds a bunch of extra logic for type checking and error messages, but your example implements the core logic.

**Comment by pditommaso** [comment]
@bentsherman If I'm understanding correctly https://github.com/nextflow-io/nextflow/pull/2911 does not implement any throttling, and it's a mere config attribute that should be managed by the user via a dynamic rule (closure). Is that correct?

**Comment by bentsherman** [comment]
It does throttle the task resources, see `TaskConfig`

**Comment by pditommaso** [comment]
Maybe we are using throttling with different meaning. Stating the docs 

> Resource limits are a useful way to specify environment-specific limits alongside tasks with [dynamic resources](#dynamic-computing-resources). Normally, if a task requests more resources than can be provisioned (e.g. a task requests 32 cores but the largest node in the cluster has 24), the task will either fail or cause the pipeline to hang forever as it will never be scheduled. If the `resourceLimits` directive is defined with these limits, the task resources will be automatically reduced to comply with these limits before the job is submitted.

I understand this as constraint mechanism. Instead I was expecting throttling as mechanism so increase automatically the resource depending the retry

**Comment by bentsherman** [comment]
It is a constraint mechanism. You could also see it as throttling, though a different form than what you are talking about

**Comment by pditommaso** [comment]
What is preventing to add a third parameter to the `check_max ` function to specify the upper bound? this can be done now and does not require any support at nextflow level. 

Nextflow should aim instead to provide a built-in replacement for the `check_max` thing.

**Comment by ewels** [comment]
> Nextflow should aim instead to provide a built-in replacement for the `check_max` thing.

That's what this issue and PR https://github.com/nextflow-io/nextflow/pull/2911 is about..

**Comment by pditommaso** [comment]
Not really, #2911 adds a directive to allow the specify the upper bound, `check_max` it's meant to stay with that

**Comment by bentsherman** [comment]
Paolo I think you are misunderstanding. #2911 adds a directive to replace `check_max` so that nf-core pipelines are not defining functions in the config file. The upper bound is provided by `params.max_cpus`, `params.max_memory`, etc

**Comment by pditommaso** [comment]
Can you show me an example a process is expected to be written using https://github.com/nextflow-io/nextflow/pull/2911 to automatically increase the memory on a failure

**Comment by pditommaso** [comment]
How the increment is determined? I don't see anything [obvious in the PR](https://github.com/nextflow-io/nextflow/pull/2911/files)

**Comment by bentsherman** [comment]
The increment is independent of the resource limit. The example I just gave means "increase the task memory by 8 GB on each attempt until the system-wide limit of 64 GB is reached"

**Comment by ewels** [comment]
Gotcha, sorry it took @bentsherman explaining your comment to me.

I'd prefer a global level setting rather than continued use of the `check_max` function because it's less verbose. Currently the function has to be specified in every single specification (see [here](https://github.com/nf-core/configs/blob/master/conf/pipeline/rnafusion/hasta.config) for an example 🤢 ). We can clean up that syntax with the upper bound but we'd still need to call the function every time.

I don't think that there's ever a time when you _don't_ want these limits applied, as they're there to prevent Nextflow from crashing due to unsatisfiable requests.

There's also no time when you want the limits to vary on a process-level. They are there to meet computational environment limits so they don't vary by process. If you want to change that, you do it with the regular `process` directives.

So because of this, to me it makes more sense to have a workflow-level setting vs. a function that can be used within multiple process-level directives.

**Comment by ewels** [comment]
Basically instead of this:

```nextflow
process {
    withName:'MYPROCESS_1' {
        memory = { check_max( 72.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 24.h  * task.attempt, 'time'    ) }
        cpus   = { check_max( 4 * task.attempt, 'cpus'  ) }
    }
    withName:'MYPROCESS_2' {
        memory = { check_max( 72.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 24.h  * task.attempt, 'time'    ) }
        cpus   = { check_max( 4 * task.attempt, 'cpus'  ) }
    }
    withName:'MYPROCESS_3' {
        memory = { check_max( 72.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 24.h  * task.attempt, 'time'    ) }
        cpus   = { check_max( 4 * task.attempt, 'cpus'  ) }
    }
}
```

I'd much rather have this:

```nextflow
process {
    resourceLimits = [ memory: 64.GB, time: 24.h, cpus: 12 ]
    withName:'MYPROCESS_1' {
        memory = { 72.GB * task.attempt }
        time   = { 24.h  * task.attempt }
        cpus   = { 4 * task.attempt }
    }
    withName:'MYPROCESS_2' {
        memory = { 72.GB * task.attempt }
        time   = { 24.h  * task.attempt }
        cpus   = { 4 * task.attempt }
    }
    withName:'MYPROCESS_3' {
        memory = { 72.GB * task.attempt }
        time   = { 24.h  * task.attempt }
        cpus   = { 4 * task.attempt }
    }
}
```

**Comment by ewels** [comment]
![](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExY3hoOGt0YmNtb2M0b3N5M3E4NmRxaHVmdHZleXE1cHdrYnk3YXJlYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Ajhi3tsHaGBB6/giphy.gif)
