### ISSUE TITLE
Typo in nextflow: echo_ref 

### ISSUE THREAD

**Issue by drejom** [nextflow-io/nextflow#643]
Looks like a typo at [L321](https://github.com/nextflow-io/nextflow/blob/79d4addaec7983bb7b2fe1bdb4ebe9993352385b/nextflow#L319-L322) of nextflow -- `echo_ref` should be `echo_red` ?

**Comment by pditommaso** [comment]
Oops ! you are right!

**Comment by pditommaso** [comment]
Included in version `0.28.2`.
