### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by baffelli** [nextflow-io/nextflow#644]
Is there any code style guide for nextflow pipelines? 
Are there currently any recommendations on how to name processes, channels and operators?

**Comment by pditommaso** [comment]
There's not official guide, but I'm aware on similar initiative lead by @ewels and @apeltzer of the https://nf-core.github.io/ group. Maybe we can put altogether a shared work?

**Comment by apeltzer** [comment]
We're having also some discussions there - please feel free to join:
https://github.com/nf-core/nf-core.github.io/issues/9

**Comment by baffelli** [comment]
Thanks, I just added my two cents to that discussions.

**Comment by pditommaso** [comment]
I'm closing this and favour the discussion at https://github.com/nf-core/nf-core.github.io/issues/9.
