### ISSUE TITLE
Add support for AWS Batch job timeout

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#648]
The [time](https://www.nextflow.io/docs/latest/process.html#time) directive should be mapped to the Batch Job timeout.
 
https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#timeout

**Comment by andreas-wilm** [comment]
+1

**Comment by pditommaso** [comment]
Done. Please give a try using the following command: 

```
NXF_VER=0.30.0-SNAPSHOT nextflow run .. etc 
```

**Comment by andreas-wilm** [comment]
Super cool. Nkw I owe you (see #198 :) ! Thanks
