### ISSUE TITLE
Add a cleanup feature to delete workflow work dir on completion

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#649]
It could be useful to automatically delete the workflow work directories on workflow (successful) completion. 

A basic implementation can introduce a `cleanup` setting in the config file file to enable it.

**Comment by pditommaso** [comment]
An experimental implementation is available in version `0.29.0-RC1`.

**Comment by stevekm** [comment]
seems similar to this: https://github.com/nextflow-io/nextflow/issues/668

**Comment by BharatPanera** [comment]
The another way is by adding an Process at the end of the Nextflow script to delete the **work dir** and hidden **.nextflow log files**.
Following is the code.

```
process Deleting_work_directory{
    input:
    tuple val(name), path(read) from Variant_calling   //here I gave the input from last process.

    output:
    path CleanUp, optional: true

    script:
    """
    rm -rf /path/of/the/work directory/work
    rm -rf /path/of/the/Hidden Log files/.nextflow*
    """
}
```
