### ISSUE TITLE
Syslogs with runName/sessionId helps logging centralization

### ISSUE THREAD

**Issue by fujimuramasa** [nextflow-io/nextflow#650]
Nextflow running with syslog is pretty helpful for managing a batch of pipelines for me. sometime it could be messy when several pipelines running together, because logs can't be distinguished. Is it possible to add runName or sessionId to every syslogs? Thx.

![snipaste_20180409_125655](https://user-images.githubusercontent.com/12607133/38480250-09c2cb64-3bf7-11e8-9582-fd59f277b042.png)

**Comment by pditommaso** [comment]
Closing because this issue stalled too long.
