### ISSUE TITLE
publishDir mode "copyNoFollow" does not work for directories

### ISSUE THREAD

**Issue by zichner** [nextflow-io/nextflow#658]
The publishDir mode "copyNoFollow" is very useful. Unfortunately, it is not working for symbolic links to directories.

Here is a minimal example:
```
process test {
        publishDir "out", mode: 'copyNoFollow'

        output:
        file ("*") into testoutput

        """
        # Create directory and link to it
        mkdir dir
        ln -s dir dir_link

        # Create file and link to it
        touch file
        ln -s file file_link
        """
}
```

The link to the file gets copied as symbolic link, however, for the link to the directory, the entire directory is copied. (This was tested with Nextflow version 0.28.1)

It would be great if that could be fixed!

**Comment by pditommaso** [comment]
Out for test `0.29.0-SNAPSHOT`.
