### ISSUE TITLE
Problems with  Channel.fromPath

### ISSUE THREAD

**Issue by brunoand** [nextflow-io/nextflow#661]
Hey, I'm having trouble when I use files from the Channel.fromPath and files from Channel.from together:

```
rawreads = Channel.fromPath(params.reads_R1 + '*R1*fastq')

process trim {
      input:
      set file(reads1) from rawreads
      file(adapters) from Channel.from( file(params.adapters) )
      file(artifacts) from Channel.from( file(params.artifacts) )
      file(phix174ill) from Channel.from( file(params.phix174ill) )

        output:
        file("*_trimmed*.fq") into todecontaminate
        file("*_trimmed*.fq") into trimmedreads
        when:
        params.mode == "QC" || params.mode == "complete"
      script:
      """
      echo $reads1 >> output.txt
      """
}
```

The process stop after the first run.

**Comment by pditommaso** [comment]
A process is executed as many as the number of provided provided. Quite surely `adapters`, `artifacts` and `phix174ill` are supposed to be just a single file, right?

**Comment by brunoand** [comment]
Yes, they are. Is there a way to use these files n times? Being n the number of files found in Rawreads?

**Comment by pditommaso** [comment]
Yes, do not declare them as a channel [value](https://www.nextflow.io/docs/latest/channel.html#value) which is done implicitly if you do not use `Channel.from`. 

Therefore replacing the input declaration with the following one, it should work: 

```
      input:
      set file(reads1) from rawreads
      file(adapters) from  file(params.adapters) 
      file(artifacts) from file(params.artifacts) 
      file(phix174ill) from file(params.phix174ill)
```

**Comment by brunoand** [comment]
Thank you for your quick response :)

**Comment by pditommaso** [comment]
Solved ?

**Comment by pditommaso** [comment]
I assume this has been solved.
