### ISSUE TITLE
Nextflow with Singularity 2.4.6 crashes if working directory is below data directory

### ISSUE THREAD

**Issue by zichner** [nextflow-io/nextflow#662]
When using Nextflow with Singularity, two directories are mounted/bound into the container:
1. The top-level directory of all data directories
2. The working directory

If 2 is a subdirectory of 1, the current version of Singularity (2.4.6) exits with an error.
(Here is a discussion regarding this: singularityware/singularity#1469)

Would it be possible to check whether the two directories are overlapping and if so, only mount the top-level one?

Thanks!

**Comment by pditommaso** [comment]
NF does not mount host directories by default, are you using the `autoMounts` option?

**Comment by pditommaso** [comment]
That could be a workaround but in principle should not happen. Could you please include the offending singularity command in the `.command.run` script?

**Comment by zichner** [comment]
Here is the full singularity command:

```
singularity exec -B /data -B "$PWD" /data/images/container.img /bin/bash -c "cd $PWD; eval $(nxf_taskenv); /bin/bash /data/projects/work/95/eb42204aec8398afce77ba0f3c42db/.command.stub"
```

The process reads inputs from `/data/dir1/` and `/data/dir2/`. The working directory is `/data/projects/work`.

**Comment by pditommaso** [comment]
I see, NF does its best to remove duplicate mount binds. In fact `/data/dir1/` and `/data/dir2/` to `/data`, but it also required to mount the current working directory, which may be not know at time of the creation of the launcher script and for this reason is added as `$PWD`. 

I think this has to be fixed in singularity. A possible workaround is to use a work directory for your pipeline in a path other that `/data`.

**Comment by zichner** [comment]
Thanks for the explanation.
Unfortunately, in my setup, all relevant drives/directories are in `/data`, so having the work directory somewhere else is not possible. And currently, it is not clear whether the team of singularity will change how overlapping binds are handled: singularityware/singularity#1469

So, I will try to work around the issue by specifying `singularity.runOptions = '-B /data'` and not using `autoMounts`.

**Comment by rsuchecki** [comment]
Apparently the original issue was fixed in Singularity 2.5.0. However, I've hit a similar problem several times, now on Singularity 3.0.3. Here is very simple example:

`main.nf`:
```
#!/usr/bin/env nextflow

bar = 1

process foo {
input:
  val bar

  script:
  """
  echo $bar
  """
}
```

`nextflow.config`:
```
process.container = 'shub://singularityhub/ubuntu'
singularity {
  enabled = true
  autoMounts = true
}
```

```
Command error:
  FATAL:   container creation failed: unabled to /tmp/c/work/a8/9e1be1885f42f5a8c6f69c3ae6eace to mount list: destination /tmp/c/work/a8/9e1be1885f42f5a8c6f69c3ae6eace is already in the mount point list
```

```
grep singularity /tmp/c/work/a8/9e1be1885f42f5a8c6f69c3ae6eace/.command.run 
set +u; env - PATH="$PATH" SINGULARITYENV_TMP="$TMP" SINGULARITYENV_TMPDIR="$TMPDIR" singularity exec -B /tmp/c/work/a8/9e1be1885f42f5a8c6f69c3ae6eace -B "$PWD" /tmp/c/work/singularity/singularityhub-ubuntu.img /bin/bash -c "cd $PWD; eval $(nxf_taskenv); /bin/bash -ue /tmp/c/work/a8/9e1be1885f42f5a8c6f69c3ae6eace/.command.sh"
```

Is this expected behaviour?

**Comment by pditommaso** [comment]
I would suggest to report this in the singularity repo https://github.com/sylabs/singularity/issues/1469

**Comment by rsuchecki** [comment]
I did just now, but thought there might be something odd about the offending automount being same as `$PWD`. I was wondering why would `task.workDir` be included in `automounts`? Is it there just in case `scratch true` is set in which case could it be skipped if `scratch false`?

**Comment by pditommaso** [comment]
Yes, I guess it's for when using the `scratch` option.

**Comment by sivkovic** [comment]
Hi, we encountered the same problem when our work directory is on one partition and input files are on different one but with singularity 3.0.3 with newest nextflow 19.1.0. For example running nextflow from `/home/ivkovic/work` and input files are located on `/ifs/` with autoMounts: true. Because of the $PWD we get `/home/ivkovic/work/fd/21990f5a7b9c8a065f9ee5028e1e45` specified two times which introduce the error:
```
FATAL:   container creation failed: unabled to /home/ivkovic/work/fd/21990f5a7b9c8a065f9ee5028e1e45 to mount list: destination /home/ivkovic/work/fd/21990f5a7b9c8a065f9ee5028e1e45 is already in the mount point list
```
So just wanted to check the status of this since ticket is closed? Is there a plan for fixing this?

**Comment by pditommaso** [comment]
This is a regression in Singularity. It appears to be fixed in recent versions https://twitter.com/bioinforad/status/1113952376329629696

**Comment by Lcornet** [comment]
I have the same issue with version 3.5.3-1.1.el7:

Command error:
  mkdir /home/users/l/c/lcornet/ORPER-N/taxdump: Read-only file system at /usr/local/share/perl5/Path/Class/Dir.pm line 154.

So I switch to singularity 3.6.0, and I have this issue :  https://github.com/nextflow-io/nextflow/issues/1732

Can you help me with this ?

Luc

**Comment by jimmymathews** [comment]
Sorry, this issue seems to be revived.

I am experiencing:
```
Command error:
  FATAL:   container creation failed: unabled to /dataroot/.../work/3f/f5f7bafdfc84c67544259047c9107d to mount list: destination /dataroot/.../work/3f/f5f7bafdfc84c67544259047c9107d is already in the mount point list
```

This is with
Singularity version: 3.2.0-rc2
Nextflow version: 21.04.3 build 5560

There are a few odd things about this:
- Sometimes it doesn't happen. Same nextflow `.nf` file, same config file, re-run will sometimes work without error.
- I noticed that in one error-free run, some of my `.command.log` files had a `WARNING:` saying something about "*destination is already in the mount point list*". I only noticed this because I am doing some minor parsing of the log files, and the parser failed due to this unexpected warning.

Note: It doesn't seem to matter whether `singularity.autoMounts = true` or not.

Here is the `.command.run` (file paths slightly changed):

```
#!/bin/bash
#BSUB -o /dataroot/path/to/my/working_directory/work/27/d9abeed0670f9f719f8fc431392056/.command.log
#BSUB -J nf-report_version
#BSUB -R "select[hname!=plvimphctrl1]"
# NEXTFLOW TASK: report_version
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /dataroot/path/to/my/working_directory/work/27/d9abeed0670f9f719f8fc431392056/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && kill $pid 2>/dev/null
}

nxf_launch() {
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} singularity exec -B /dataroot/path/to/my/working_directory/work/27/d9abeed0670f9f719f8fc431392056 -B "$PWD" /dataroot/path/to/singularity/images/latest.sif /bin/bash -c "cd $PWD; /bin/bash /dataroot/path/to/my/working_directory/work/27/d9abeed0670f9f719f8fc431392056/.command.sh"
}

nxf_stage() {
    true
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /dataroot/path/to/my/working_directory/work/27/d9abeed0670f9f719f8fc431392056/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
    nxf_stage

    set +e
    local ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
```
