### ISSUE TITLE
attach timeline and report to notification

### ISSUE THREAD

**Issue by tbugfinder** [nextflow-io/nextflow#663]
Hi,
it's not possible to add timeline (-with-timeline) or report (-with-report) is sent using the notification method as the given reports are not available at the time oncomplete is executed.

```
<snip>
        sendMail {
               to 'user@mail.com'
                from 'sender@mail.com'
                subject 'execution'
               attach "/pathto/report.html"
               attach "/pathto/timeline.html"
                body msg

        }


```

**Comment by pditommaso** [comment]
Now, it should not be possible mainly because the mail is sent before the the creation of that report. Also for real world execution (ie. with > 10k jobs) that files would be too big to be included in the mail as attachments.

**Comment by stevekm** [comment]
I am very interested in this kind of feature as well. Maybe it would be possible to first try zipping the attachments if they are too large, then simply not send them but still send the message, maybe updated with a note that attachments were too large to send.

**Comment by pditommaso** [comment]
I don't think it's a good idea to skip the attachment given the file size. Ultimately it's the developer role to manage this. 

This should be the same problem as #626.

**Comment by tbugfinder** [comment]
Considering the possible size, I agree that email might not be the proper option.

**Comment by rsuchecki** [comment]
Agree that mailing large reports may not be a good idea but having access to the report, timeline and dag  in `workflow.onComplete` handler could be really useful. 

This would make it trivial for pipeline developer to package and distribute  workflow metadata perhaps along some results/stats generated by the pipeline. 

This can be done separately e.g. by wrapping NF call in another script but that is a bit of a hack. One can also use raw trace values, but this means re-implementing the report and/or timeline in some form (and probably can't have the dag).

Logically you'd expect these to be available "on complete", am I missing something? I guess the difficulty may come from the fact that ReportObserver uses WorkflowMetadata where onComplete and onError are triggered(?) https://github.com/nextflow-io/nextflow/blob/b49e6d74dae782def6be2b087d06fdd8fa6b9291/modules/nextflow/src/main/groovy/nextflow/script/WorkflowMetadata.groovy#L233-L234
I guess that makes things a bit more complicated, in which case would it be a reasonable to have a  `onReallyActuallyCompletelyDoneNow` (actual event and handler names up for discussion :wink:) triggered after everithing has been done and which would be distinct from the existing onComplete but could access (read) it's fields?

**Comment by pditommaso** [comment]
Closing this in favour of the notification feature provided by Tower https://github.com/seqeralabs/nf-tower/issues/178.
