### ISSUE TITLE
suggestion: Channel.FOFN

### ISSUE THREAD

**Issue by jemunro** [nextflow-io/nextflow#664]
FOFN ("file or file names") is a flexible paradigm for specifying an arbitrary set of files. Typically a FOFN will specify the full path for a set of files, one per line. E.g.:
```bash
$cat my.fofn
/path/to/a.file
/another/path/to/a.file
/final/path/to/a.file
```
This could be used in nextflow as:
```nextflow
my_files = Channel.fromFOFN('my.fofn')
```

This could also be extended to support sets of named files, similar to Channel.fromFilePairs. For example, if my.fofn contained tab delimitted values, it could be interpreted as (key, file_1, file_2, ..., file_n).
For example:
```bash
$cat my.fofn
SRR493366    /my/reads/SRR493366_1.fastq    /my/reads/SRR493366_2.fastq    /my/aln/SRR493366.bam
SRR493367    /my/reads/SRR493367_1.fastq    /my/reads/SRR493367_2.fastq    /my/aln/SRR493367.bam
SRR493368    /my/reads/SRR493368_1.fastq    /my/reads/SRR493368_2.fastq    /my/aln/SRR493368.bam
```
and in nextflow:
```nextflow
Channel
    .fromFOFN('my.fofn')
    .println()
```
would yield:
```
[SRR493366, [/my/reads/SRR493366_1.fastq, /my/reads/SRR493366_2.fastq, /my/aln/SRR493366.bam]]
[SRR493367, [/my/reads/SRR493367_1.fastq, /my/reads/SRR493367_2.fastq, /my/aln/SRR493367.bam]]
[SRR493368, [/my/reads/SRR493368_1.fastq, /my/reads/SRR493368_2.fastq, /my/aln/SRR493368.bam]]
```

**Comment by pditommaso** [comment]
This could be a nice idea, tho it can be implemented quite easily chaining a [splitCsv](https://www.nextflow.io/docs/latest/operator.html#splitcsv) and a [map](https://www.nextflow.io/docs/latest/operator.html#map) operator. Therefore I'm not sure if it makes sense to a specific method just to read plain text file.

**Comment by baffelli** [comment]
I agree with @pditommaso, but I believe your answer highlights the usefulness of some syntactic sugar  permitting to define custom channel operators easily (see #398)
