### ISSUE TITLE
Transfering pipeline results to Windows

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#667]
After pipeline completion, I need to sync the output with a Windows network share so that desktop users can access files. I typically just rsync the entire pipeline directory over, but with Nextflow there are some issues that stand out, concerning the 'work' and 'publishDir' formats;

- symlinks do not work on Windows

- symlinks used by Nextflow appear to be using the absolute file path; upon transferring the pipeline directory to another system, these paths will not work

Obviously copying the file output to the publishDir would solve this, but it brings in the issue of data duplication & storage. This is also compounded by having multiple 'publishDir' directory structures (e.g. per-process, per-sample) as made possible by the [recent updates](https://github.com/nextflow-io/nextflow/issues/256). 

It seems like a solution might be to 

- create Windows-style shortcuts to files in the publishDir

- create links/shortcuts using relative paths

Not sure if either of these are possible. What do you think? Trying to avoid having 3 copies of every file just to make the pipeline + output portable between systems.

**Comment by stevekm** [comment]
I am not very familiar with Windows, I was assuming that it might be something that is not terribly hard to do. Found some reference to it [here](https://unix.stackexchange.com/questions/233286/creating-windows-shortcuts-in-linux).

**Comment by pditommaso** [comment]
Frankly, this is has very low-priority. I can take in consideration a PR creating Windows-style shortcuts.
