### ISSUE TITLE
Multiple 'module' directives do not work in nextflow.config

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#669]
As per the [docs](https://www.nextflow.io/docs/latest/process.html#module), you can "repeat the module directive for each module you need to load". This appears to work inside a Process in the Nextflow script file. However, when you try to do the same inside the `nextflow.config` file, it does not work. For example:

```
profiles {
    standard { 
        process.$mutect2.module = 'samtools/1.3'
        process.$mutect2.module = 'java/1.8'
    }
}
```

Only `'java/1.8'` gets loaded. 

However, this works:

```
profiles {
    standard { 
        process.$mutect2.module = 'samtools/1.3:java/1.8'
    }
}
```
Not sure if this is a bug, or intentional?

**Comment by pditommaso** [comment]
In the config file that's equivalent to an assignment, therefore the value is overridden.

**Comment by maubarsom** [comment]
I would maybe suggest this as a documentation "bug" ? In my experience, I always have issues looking up how to specify specify multi-line directives in the configuration section, such as modules , or publishDir? I found this issue first than the place in the docs that tell me where

**Comment by pditommaso** [comment]
Yes, you are right. It would useful to have an entry in the docs.
