### ISSUE TITLE
Method for capturing Channel items discarded by 'filter'

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#671]
When you use the [`filter`](https://www.nextflow.io/docs/latest/operator.html#filter) operator, entries that do not pass appear to be discarded. However, it would be useful to be able to capture these discarded entries somehow, or redirect them to another Channel. This way, you might be able to keep track of which items did not pass your filter criteria. 

It would also be useful to be able to re-map failed entries, for custom processing. Maybe something like:

```
// Make sure that all files have enough lines
Channel.from([
    ['demo1', file('input/demo1.tsv')],
    ['demo2', file('input/demo2.tsv')],
    ['demo3', file('input/demo3.tsv')]
    ])
    .filter(criteria: { sampleID, sample_tsv ->
                        // count the number of lines
                        long count = sample_tsv.readLines().size()
                        count > 1
                        },
            onFail: { sampleID, sample_tsv ->
                long count = sample_tsv.readLines().size()
                def reason = "Not enough lines"
                return [ sampleID, sample_tsv, count, reason ]
            }.set { failed_tsvs }
        )
    .set { demo_tsvs }

// do a thing with the items that passed filter
demo_tsvs.subscribe { println "[demo_tsvs] ${it}" }

// do something else with the items that didnt pass
failed_tsvs.subscribe { sampleID, sample_tsv, count, reason ->
    println "[failed_tsvs] Sample failed: ${sampleID}\nReason: ${reason} "
}

```

**Comment by pditommaso** [comment]
If I'm understanding well the example, this pattern can be implemented with a [choice](https://www.nextflow.io/docs/latest/operator.html#choice).

**Comment by stevekm** [comment]
Yeah looks like that is it, did not realize this was already a feature.
