### ISSUE TITLE
caching is not working as expected 

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#684]
Hi,
I noticed that the caching is ignoring changes in the "lib" folder containing classes. 

Luca

**Comment by lucacozzuto** [comment]
low???? :)

**Comment by lucacozzuto** [comment]
One more thing.
Could this be because the folder lib is linked? (Ln -s)?

**Comment by pditommaso** [comment]
I don't think so

**Comment by pditommaso** [comment]
Marking as not reproducible.
