### ISSUE TITLE
Output file is not recognised when it's created into a subdir and the name matches an input

### ISSUE THREAD

**Issue by frankyan** [nextflow-io/nextflow#688]
This is a special error. File in a subfolder cannot be correctly detected with wildcards in output when there is a file with the same name in the parent folder.

You can reproduce the error with the following code (create some files in the data folder). 
- If you change `echo "process job $x" >out/${x}` to `echo "process job $x" >out/${x}.txt`, it works.
- If you change  `file "out/*" into letters mode flatten` to `file "out/${x}" into letters mode flatten`, it also works.

```
#!/usr/bin/env nextflow

testfiles = Channel.fromPath( "data/*" )
process splitLetters {
    publishDir "result"
    input:
    file x from testfiles

    output:
    file "out/*" into letters mode flatten

    """
    mkdir out
    echo "process job $x" >out/${x}
    """
}
```

**Comment by pditommaso** [comment]
Released in version `0.29.1`.
