### ISSUE TITLE
templates suggestion

### ISSUE THREAD

**Issue by jemunro** [nextflow-io/nextflow#689]
Hi,

I believe it would be useful if templates could be specified with:
1) The option to not have nextflow parse the file and attempt to insert variables
2) The ability to specify command line arguments, e.g.:
    ```
    script:
    template 'my_script.R' -max=$foo
    ```

This would enable the use generic scripts that may not have been written with nextflow in mind. It is also useful to keep scripts written in other other languages a separate files, so that appropriate syntax highlighting in an IDE can be used.

**Comment by jemunro** [comment]
Where should `my_script.R` be located in this case? I've tried putting it in the templates folder and in the same directory as `main.nf`,  but either way i get this error:
```
ERROR ~ Error executing process > 'test'

Caused by:
  Process `test` terminated with an error exit status (127)

Command executed:

  my_script.R

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: my_script.R: command not found
```

**Comment by pditommaso** [comment]
It needs to be located in the `bin/` directory of your project and grant it execute permissions. https://www.nextflow.io/docs/latest/sharing.html#third-party-scripts

**Comment by jemunro** [comment]
Thank you, that's pretty much what I was looking for.

In this case are the contents of script hashed, such that editing the script will cause relevant process to be re-run when resuming a pipeline? I believe this is currently the case with templates and embedded scripts.

**Comment by pditommaso** [comment]
Yes, changes in scripts located in the `bin` path are detected.

**Comment by pditommaso** [comment]
I assume this is solved, therefore I'm closing it. If it's not, feel free to comment below.
