### ISSUE TITLE
kubepull command

### ISSUE THREAD

**Issue by wikiselev** [nextflow-io/nextflow#694]
Hi Paolo, is there a command to pull an updated pipeline from GitHub? So, for running we have `nextflow kuberun etc`, is there anything like `nextflow kubepull etc`? It would be nice to have all other NF commands available in K8s settings.

**Comment by pditommaso** [comment]
The `kuberun` is a passthrough for the `run` ie. you can use the `-latest` command line option to pull the latest version.
