### ISSUE TITLE
param line args with LSF bsub

### ISSUE THREAD

**Issue by davisem** [nextflow-io/nextflow#704]
Hi,

I noticed some issues when running the nextflow command with LSF bsub.  LSF likes to remove quotes from command line arguments. This becomes a problem when using the `Channel.fromPath` with glob expressions, since the glob expressions need to be in quotes. So for example:

`bsub nextflow run myscript.nf --files "my/files/*.fa"`

get converted to this by the time it's evaluated by nextflow:

`nextflow run myscript.nf --files my/files/*.fa`

If you escape the quotes, LSF leaves the backslash in the command: 

`nextflow run myscript.nf --files \"my/files/*.fa\"`

The work around was to include the glob in the config file.

**Comment by pditommaso** [comment]
This is somehow expected. [Wildcards characters](http://tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm) are expanded by the Bash interpreter. The only way to prevent this is to escape such characters with `\` eg. `--files my/files/\*.fa` or to enclose that path in \*single\*  quotes eg.

```
nextflow run myscript.nf --files 'my/files/*.fa'
```
