### ISSUE TITLE
Add to UGE executor support for native docker integration

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#711]
Univa Grid Engine version 8.5 (and higher) has a built-in support for docker container. 

Container images need to be specified using the `docker` soft resource as shown below: 

```
qsub -soft -l docker,docker_images="*centos:latest*" <your task.sh>
```

**Comment by cjw85** [comment]
@pditommaso 

Have all plans to implement this been dropped?

My understanding is that without this integration individual users have to been members of the docker group and nextflow will execute a `docker run` within the cluster job. Through Nextflow the user will have full control over that command. Correct?

With the integration I believe things are a bit more locked down in that UGE handles the execution of the container, user permissions etc, and drops the cluster job straight into the container.
