### ISSUE TITLE
job  submission behavior on uge cluster

### ISSUE THREAD

**Issue by bayolau** [nextflow-io/nextflow#723]
Dear All,

I'm trying launch a huge number (>600) of jobs on uge cluster, for example with

    process execute {
        executor       'uge'
        cpus           1
        memory         '1 GB'
        clusterOptions '-l h_vmem=1G'
        queue          'all.q'
        penv           'smp'

I might be noticing that not all 600 are submitted at the same time. Is this expected? is there a way around it?

**Comment by pditommaso** [comment]
Yes, by default no more than 100 jobs at time are submitted. Use the command line option `-qs <limit>` or the `executor. queueSize` configuration setting to increase it. See the [doc](https://www.nextflow.io/docs/latest/config.html#scope-executor) for details.

**Comment by pditommaso** [comment]
I'm closing this because I assume it is solved. If it's not the case, feel free to comment below or re-open it.
