### ISSUE TITLE
Singularity pull .simg

### ISSUE THREAD

**Issue by mhebrard** [nextflow-io/nextflow#724]
I saw multiple issues closed about the singularity pull... but I still have a bug

Versions:
Nextflow v0.29.1.4804
Singularity v2.4-dist

Command:
`nextflow run mhebrard/TrimFlow --reads 'data/*_R{1,2}*' `

Expected behavior:

* nextflow pull the workflow files from http://github.com/mhebrard/TrimFlow
* nextflow pull the singularity image from shub://mhebrard/TrimFlow
* nextflow run the workflow inside the singularity image

nextflow.config (section related to singularity)
`process.container = { "shub://mhebrard/TrimFlow:${workflow.revision ? workflow.revision : 'latest'}" }`
`singularity.enabled = true`

Error:
`Failed to pull singularity image`
`command: singularity pull --name mhebrard-TrimFlow-latest.img shub://mhebrard/TrimFlow:latest > /dev/null`
`status : 143`

Investigation:
Apparently the issue come from the extension of the image.
I made multiple test with `singularity pull` and it appears that it ignore the extension of the `--name` tag.
Whatever the name specified, singularity pull a `<name>.simg` file
Then (I guess) nextflow search for a `.img` that do not exist.

Work around:
if after the error of the first command I execute:
`nextflow run mhebrard/TrimFlow -with-singularity ./work/singularity/mhebrard-TrimFlow-latest.simg --reads 'data/*_R{1,2}*' `
(I call manually the image that was pulled by nextflow)
Then the workflow succeed

Suggestion:
nextflow run the command `singularity pull <name>.simg`, then look for use the `.simg` file when execution

**Comment by pditommaso** [comment]
This looks like a know singularity issue #498. You need to use singularity 2.4.1 or higher (or specify the the image file path as you are suggesting).

**Comment by mhebrard** [comment]
Sorry for that, I should have look better.
