### ISSUE TITLE
'Broken pipe' email error and missing attachments

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#726]
I am getting errors with email file attachments in Nextflow version 0.29.0. I have uploaded a full demo of it here: https://github.com/stevekm/nextflow-email-error. 

- when I run the [`email-noError.nf`](https://github.com/stevekm/nextflow-email-error/blob/master/email-noError.nf) pipeline, Nextflow completes succesfully, but does not actually send all of the file attachments.

console output:

```
./nextflow -log .nextflow.noError.log run email-noError.nf
N E X T F L O W  ~  version 0.29.0
Launching `email-noError.nf` [extravagant_joliot] - revision: 4bf004b6ae
[email_attachments_channel2] /ifs/data/molecpathlab/development/demux-nf-demo2/test/email/attachments/RunParameters.tsv
[email_attachments_channel2] /ifs/data/molecpathlab/development/demux-nf-demo2/test/email/attachments/multiqc_report.html
[email_attachments_channel2] /ifs/data/molecpathlab/development/demux-nf-demo2/test/email/attachments/SampleSheet.csv
[email_attachments_channel2] /ifs/data/molecpathlab/development/demux-nf-demo2/test/email/attachments/RTAComplete.txt
[email_attachments_channel2] /ifs/data/molecpathlab/development/demux-nf-demo2/test/email/attachments/Demultiplex_Stats.htm
```

However, only `RunParameters.tsv` and `multiqc_report.html` show up in the email 

- when I run the [`email-brokenPipe.nf`](https://github.com/stevekm/nextflow-email-error/blob/master/email-brokenPipe.nf) pipeline, Nextflow instead quits with an error:

```
./nextflow -log .nextflow.brokenPipe.log run email-brokenPipe.nf
N E X T F L O W  ~  version 0.29.0
Launching `email-brokenPipe.nf` [compassionate_lovelace] - revision: dc5fbf7e44
ERROR ~ Broken pipe

 -- Check script 'email-brokenPipe.nf' at line: 13 or see '.nextflow.brokenPipe.log' file for more details
```

However, the email is still sent. As with the other example, the email only contains files `RunParameters.tsv` and `multiqc_report.html` as attachments. 

The only difference between the pipelines is that in the former, I manually exclude the included file [`demultiplexing_report.html`](https://github.com/stevekm/nextflow-email-error/blob/master/email/attachments/demultiplexing_report.html) from the email attachments. No clue why this makes a difference. I tried a lot of other combinations as well, and each time that I tried to include this particular type of file (e.g. my custom R Markdown HTML report output from pipelines), it breaks the emailer.

**Comment by pditommaso** [comment]
I'm unable to replicate the issue you are reporting. Both emails are sent correctly. Tested both with 0.29.x and 0.30.x, Gmail client and Amazon SES server. 

It could be a problem with your smtp server and or email client (regarding the missing attachments).

**Comment by stevekm** [comment]
Thanks for taking a look at it. All 6 attachments sent when you tested it? Is there a suggested way to test `sendmail` with these attachments without using Nextflow? I had trouble finding clear ainstructions online.

I've also used `mutt` on these systems without issue, not sure if there's an easy way for Nextflow to try sending the mail with `mutt` instead of `sendmail`.

**Comment by pditommaso** [comment]
> Thanks for taking a look at it. All 6 attachments sent when you tested it?

yes

> Is there a suggested way to test sendmail with these attachments without using Nextflow? 

No, also because the mime-message is piped to the `sendmail` command. 

> not sure if there's an easy way for Nextflow to try sending the mail with mutt

No out of the box, but it could be added. This is the part where it should be [handled](https://github.com/nextflow-io/nextflow/blob/dec2f6d8a8f3b0827dac0b7f8afb1dc7ce595b9b/src/main/groovy/nextflow/mail/Mailer.groovy#L428-L440).

**Comment by pditommaso** [comment]
I'm closing this because there's no more feedback. Feel free to comment/reopen it if needed.
