### ISSUE TITLE
Implements a termination option for watchPath channel factory

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#735]
The method [watchPath](https://www.nextflow.io/docs/latest/channel.html#watchpath) continuously check a directory for the event specified and never terminate. 

Currently the only way to stop an application using one or more `watchPath` is to kill it. 

It should be introduce an option to exit from the *watching* phase a gracefully terminate the dataflow network.

**Comment by pditommaso** [comment]
This can be managed using the following idiom: 

```
Channel
      .watchPath('/some/path/*')
      .until { file->file.name == 'SOMETHING' }
      .set { watched_files }
````

**Comment by ArielSSchwartz** [comment]
Is there a way to make the same idiom work when mixing two watchPath channels?

**Comment by pditommaso** [comment]
I dont see anything preventing it. 

ps. maybe the forum is a better place for these kinds of questions https://groups.google.com/forum/#!forum/nextflow
