### ISSUE TITLE
Ability to 'publish' process output to a database

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#743]
I was wondering how feasible it would be for Nextflow to publish data to a database, such as PostgreSQL, MySQL, etc., in lieu of a `publishDir`. It would help greatly in keeping more complex metadata associated with output files, and maintained across the entire pipeline output. I put together a demo workflow trying to do this manually [here](https://github.com/stevekm/nextflow-demos/tree/master/aggregate-db-report), but there is a lot of database-management overhead that would benefit from a more formal interface. Would this be something that could potentially be integrated into Nextflow? If not, are there any suggestions on how to best implement it?

**Comment by fstrozzi** [comment]
That would be extremely useful as well and the same logic could be used to implement the fetch part we were discussing some time ago.

**Comment by stevekm** [comment]
I saw that there appears to be native SQL database support in Groovy
http://groovy-lang.org/databases.html
So maybe it could be done manually already within workflow scripts

**Comment by pditommaso** [comment]
That's possible but it's required to import the `groovy-sql` module for that.

**Comment by baffelli** [comment]
I find it an excellent idea. But that begs the question how to more generally integrate a SQL/NoSQL DB into a nextflow pipeline and  how to ensure reproducibility in these situations. What is the "minimum reproducible unit" A DB row? A table?

**Comment by stevekm** [comment]
My attempts to handle this manually in Nextflow with a naive approach can be found here

https://github.com/stevekm/nextflow-demos/blob/master/aggregate-db-report/people.nf

https://github.com/stevekm/nextflow-demos/blob/master/aggregate-db-report/plots.nf

However the concerns about reproducibility seem valid. If you're going to take a manual approach it might be good to include the `workflow.sessionId` as a field in each DB row. Also if you're using something easy like sqlite maybe also include the db creation as a step in the pipeline to help make sure that you're not accidentally reusing old results on `-resume`

**Comment by pditommaso** [comment]
Reproducibility problems may arise  if you keep the workflow state in a database and this the main reason to not use an external database. However, just storing resulting process outputs into a DB table I don't see how it could impact the pipeline reproducibility.

**Comment by stevekm** [comment]
these seem relevant: https://github.com/qbicsoftware/nextflow-logger-service https://github.com/nf-core/tools/pull/288

**Comment by mes5k** [comment]
Publishing a message to a message queue could be useful too.
