### ISSUE TITLE
Allow AWS Batch to be used along with local/cluster executor 

### ISSUE THREAD

**Issue by tbugfinder** [nextflow-io/nextflow#744]
The AWS Batch Executor should support EFS / NFS (shared storage) as a workdir target in addition to S3.

As discussed within #709 this will reduce the number of API calls especially during the submission phase. EC2 instances have to be prepared for this setup and job-definitions have to configure a proper mount point.

**Comment by pditommaso** [comment]
Released with version `18.10.1`.

**Comment by pjongeneel** [comment]
@pditommaso how exactly can we specify EFS as the workdir? I'm on version 20 and I'm still getting errors "When using `awsbatch` executor a S3 bucket must be provided as working directory either using -bucket-dir or -work-dir command line option"

**Comment by pditommaso** [comment]
@pjongeneel The goal of this feature was to allow the use of AWS Batch executor along with the local/cluster executor each of which uses its own corresponding storage path ie. Batch with a S3 bucket *and* the local/cluster executor in local/shared directory in the same pipeline. 

The ability to use a EFS/FSx shared storage for AWS Batch is currently in beta and only available to https://www.seqera.io/ customers.
