### ISSUE TITLE
Unique operator on a csv file

### ISSUE THREAD

**Issue by rbpisupati** [nextflow-io/nextflow#746]
Hi, 

I am curious on how one can operate unique function when you are using splitCsv. For example, I would like to determine the unique rows just based on columns 1 and 2 below,
```
Channel
    .from( 'id,number,data\n1,20,100\n1,30,90\n1,20,80\n2,20,100' )
    .splitCsv()
    .subscribe { row ->
       println "${row[0]} - ${row[1]}"
}
```

But I would like to have only these rows in the output.

> 1 - 20
> 1 - 30
> 2 - 20
 

Thanks,
Rahul

**Comment by pditommaso** [comment]
Specify the criteria in the `unique` operator ie. 

```
Channel
    .from( 'id,number,data\n1,20,100\n1,30,90\n1,20,80\n2,20,100' )
    .splitCsv()
    .unique { row -> [row[0], row[1]] }
    .subscribe { row ->
       println "${row[0]} - ${row[1]}"
}
```

**Comment by rbpisupati** [comment]
It works..! Thanks :)
