### ISSUE TITLE
"Perl" shouldn't be uppercased on homepage

### ISSUE THREAD

**Issue by Alhadis** [nextflow-io/nextflow#75]
I know this is an insanely trivial issue, but it's something that tends to rub Perl programmers the wrong way:

![screen shot 2015-09-24 at 08 50 00](https://cloud.githubusercontent.com/assets/2346707/10061105/4b83e374-6299-11e5-97c8-c260eb9c7988.png)
[It's not an acronym.](http://c2.com/cgi/wiki?PerlIsNotAnAcronym)

Sorry, that's all. =)

**Comment by pditommaso** [comment]
Best issue ever! Fixed. 

Thanks.
