### ISSUE TITLE
Add nextflow required version in the config manifest 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#752]
A field specifying the minimum nextflow required version should be added in the config file `manifest` section. 

This will allow the implementation of an automatic check when a workflow is expected to verify that the expected nextflow runtime is being used.

**Comment by apeltzer** [comment]
That would be really nice :-)

**Comment by pditommaso** [comment]
yeah, that would prevent to have [this](https://github.com/nf-core/methylseq/blob/235873861dcdce26f49f2ed088ad3d324e427ac3/main.nf#L31-L41.com) .. ;)

**Comment by pditommaso** [comment]
@apeltzer @KevinSayers @ewels How does it looks?  

```
manifest {
   requiredNextflowVersion = '1.2.3'
}
```

too verbose ?

**Comment by ewels** [comment]
Looks brilliant! :tada:

**Comment by pditommaso** [comment]
Should it show a warning or stop the execution  ?

**Comment by KevinSayers** [comment]
Looks good to me! As it says ‘required’ I would say stop execution.

**Comment by pditommaso** [comment]
Umm, thinking to renamed it as 

```
manifest {
   nextflowVersion = '1.2.3'
}
```

**Comment by ewels** [comment]
Maybe `minNextflowVersion`? I think it’s good to indicate that it’s a lower bound only..

**Comment by KevinSayers** [comment]
I think both a min version and an exact version would be useful. Exact could be helpful if you want to lock in a version for reproducibility.

**Comment by pditommaso** [comment]
Refactoring after refactoring current implementation allows the following: 

```
manifest {
   nextflowVersion = '1.2.3'  // exact match
   nextflowVersion = '1.2+'  // 1.2 or later (excluding 2 and later) 
   nextflowVersion = '>=1.2'  // 1.2 or later    
   nextflowVersion = '>=1.2, <=1.5'  // any version in the 1.2 .. 1.5 range  
}
```

**Comment by pditommaso** [comment]
OK, another iteration as above with a little addition, the version requirement string can be prefixed with a `!` character to stop the execution in the case the version specified does not match 
with the current runtime one. For example: 

```
manifest {
  nextflowVersion = '!>=1.2'
}
```
