### ISSUE TITLE
chown --from option unrecognized with non-GNU tools and fixOwnership on for Docker

### ISSUE THREAD

**Issue by rspreafico-sgi** [nextflow-io/nextflow#755]
When Docker containers that do not ship GNU tools are used (e.g. popular lightweight BusyBox, Alpine Linux, Biocontainers) and the `fixOwnership` option is on, `chown` fails due to the `--from` option being unsupported in non-GNU tools. 

Temporary workaround: set UID/GID in the Docker `runOptions`.

Possible fixes:
- have Nextflow set UID/GID for Docker if `fixOwnership` is on (as opposed to changing permissions after the run)
- `chown` all output files, without pre-filtering on those owned by `root` (the Nextflow user should own all files anyway).

Referenced from <https://github.com/nextflow-io/nextflow/issues/499#issuecomment-398461592>.

**Comment by rspreafico-sgi** [comment]
In my case, using UID and GID in runOptions works really well.

**Comment by pditommaso** [comment]
It that will become the default at some point.
