### ISSUE TITLE
when running multiple jobs, one fails inside the workflow but not outiside

### ISSUE THREAD

**Issue by kemin711** [nextflow-io/nextflow#756]
I am testing a pipeline

```
params.inFastqDir = "fastqout/IDT_Run6_Clinical"
params.refinedFastqDir="cleanfastq"
inFastq = Channel.fromFilePairs("${params.inFastqDir}/*_R{1,2}_001.fastq.gz")
params.bwaNumthread=8

process basicExample {
  publishDir params.refinedFastqDir

  input:
  set val(sampleName), file(fqpair) from inFastq

  output:
  set val(sampleName), file("${sampleName}_R1_clean.fastq.gz"), file("${sampleName}_R2_clean.fastq.gz"), file("${sampleName}_single.fastq.gz") into refinedPair, refinedSingle

   script:
   """
   polishpair -q ${fqpair}
   """
}
```

The pipeline will fail: 

```
 polishOnePair working on 2000
  polishOnePair working on 4000
  polishOnePair working on 8000
  polishOnePair working on 16000
  polishOnePair working on 32000
  polishOnePair working on 64000
  polishOnePair working on 128000
  polishOnePair working on 256000
  polishOnePair working on 512000
  polishOnePair working on 1024000
  polishOnePair working on 2048000
  polishOnePair working on 4096000
  .command.sh: line 2:  4804 Segmentation fault      (core dumped) polishpair -q FF10801_Pool3_S8_R1_001.fastq.gz FF10801_Pool3_S8_R2_001.fastq.gz

Work dir:
  /analysisdir/work/62/ec69c563330e9a6b0b7fa61eee42a2

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
WARN: Killing pending tasks (5)
```
=====================
When i got the the work directory and execute the bash .command.run file,
The process run to completion without any problem.  I have tried this 3 times and it is reproducible on my machine.

My question is how do I figure out how to fix the problem. Right now this is a road blocker to our projects.  I am new to nextflow. Can any one give a help?

**Comment by pditommaso** [comment]
The error message is pretty clear. 

```
line 2:  4804 Segmentation fault      (core dumped) polishpair -q FF10801_Pool3_S8_R1_001.fastq.gz FF10801_Pool3_S8_R2_001.fastq.gz
```

This is not a nextflow issue. The task is crashing for some reason. As suggested change in the work dir and troubleshoot the problem running `bash .command.run`.

**Comment by kemin711** [comment]
Not reproducible.  Cd to this directory, and the process run to completion.  I have tried this 4 times, no issues.  There must some some environment setting in the nextflow that caused the crash.  This program has applied to >5000 such runs without any problem in a shell script based pipeline.  Is there any debug setting to display more information about the nextflow pipeline?

**Comment by pditommaso** [comment]
NF just launch the script as it is. Are you using a local execution or a batch scheduler  ?

**Comment by kemin711** [comment]
I thing that I can think of is that nextflow links to some dynamic library that is different from the ones if launched manually.  I am using <em>local</em> executioner.  The .command.run script contains more information.  These setting is making the C++ running to completion.  The question is how do I figure out the difference between this script's setting the those when launched from the master nextflow language.

**Comment by pditommaso** [comment]
I don't this may happen, to double check you may add a `env` command just before the execution of your tool and the compare the two different printed environments.

**Comment by kemin711** [comment]
After I update the workflow to the latest version, now, the nextflow will launch 3 jobs, then fail the one job just after executing it for 5 seconds with no apparent reason.  Now sure what am I doing wrong.

**Comment by kemin711** [comment]
It is really difficult to debug,  I will give up for now.

**Comment by stevekm** [comment]
possibly an issue with running multiple instances of the program concurrently? I had issues like that when the host system did not actually have enough RAM to support multiple instances of the same program.
