### ISSUE TITLE
Add support for K8s volume mount subPath

### ISSUE THREAD

**Issue by tdudgeon** [nextflow-io/nextflow#758]
With the K8S executor we need to be able to use the `pod.spec.containers.volumeMounts.subPath` attribute to specify which sub-directory of a PVC to mount inside the container.

**Comment by pditommaso** [comment]
By the way the name they choose is ugly, that is meant to be the volumePath.

**Comment by alanbchristie** [comment]
`volumePath` does indeed appear to be a more sensible name but unless `volumeClaim` is interpreted by Nextflow as a generic parameter (i.e. not a k8s-specific one) I'd vote on resisting the temptation to use a different name in this abstraction layer. Using k8s field names would avoid any potential confusion with any other parameter that might exist now or in the future. Just my opinion.

**Comment by pditommaso** [comment]
Yes, I tend to agree, it's better to stay consistent with k8s nomenclature.

**Comment by pditommaso** [comment]
Just uploaded snapshot `0.31.0-SNAPSHOT` including this enhancement. Now you can specify: 

```
process {
  pod = [volumeClaim:'pvc-id', mountPath: '/foo', subPath: '/bar']
} 
```

or 

```
k8s {
  pod = [volumeClaim:'pvc-id', mountPath: '/foo', subPath: '/bar']
} 
```

**Comment by alanbchristie** [comment]
Nice. I assume `subPath` is simply a string passed to the Pod, so the leading `/bar` (in our case) will actually be `bar`.

Also ... just for future reference, is the configuration tolerant of whitespace? i.e. can I break the array over multiple lines...

```
k8s {
  pod = [volumeClaim:'pvc-id',
         mountPath: '/foo',
         subPath: '/bar']
}
```

**Comment by pditommaso** [comment]
yes.
