### ISSUE TITLE
Include process name and tag information in process folder 

### ISSUE THREAD

**Issue by emi80** [nextflow-io/nextflow#76]
In my opinion, being able to retrieve process name and tag from the project folder would be useful. The information could be added to `.command.begin` file which is empty at the moment.

**Comment by pditommaso** [comment]
@emi80 what about including the process name/tag on top of the `.command.run` run file ?

It would be little easier and could be useful when debugging the wrapper script. 

Do you need any special *escape* sequence to parse it?

**Comment by pditommaso** [comment]
Fixed in version `0.16.2`
