### ISSUE TITLE
unexpected behavior when reading file-of-S3-files

### ISSUE THREAD

**Issue by githubuserincyte** [nextflow-io/nextflow#760]
Hi,

I'm trying to use the NF capability of downloading files from S3.  When I run a script as here downloading data from S3 , I observe behavior as I expect; I'm able to read the contents of a file from S3:

```
data_line=Channel.fromPath("s3://mybucket/mypath/input.txt")
process adder_process {
        input:
                file in_file from data_line
        """
        set -exu -o pipefail
        echo "Showing the contents of ${in_file} ..." ;
        head ${in_file}
        sleep 10s
        rm -v `readlink -e ${in_file}` && rm -f ${in_file} ;
        """
        }
```

In this case, the single file is downloaded from S3 and the output from the "head" command shows NOT a URL but it shows data.  The behavior that I observe in this case is the behavior I expect.  

However, when I read a file of files, behavior is not as I expect and behavior is not as I hope.  In this case the file of files, the file-of-files is local, but the files in its list are S3 files.

If I try this code, I get an error:

```
in_data_fof=Channel.fromPath("input.txt")
data_line=in_data_fof.splitText().map{ x -> x.trim()}.view(){x -> "trimmed data is $x" }
data_line_p=Channel.fromPath(data_line)

process adder_process {

        input:
                file in_file from data_line_p

        """
        set -exu -o pipefail
        echo "Showing the contents of ${in_file} ..." ;
        head ${in_file}
        sleep 10s
        rm -v `readlink -e ${in_file}` && rm -f ${in_file} ;
        """
        }

[user@host]$ nextflow  -c tiny_config.conf   run script.nf
N E X T F L O W  ~  version 0.30.2
Launching `script.nf` [nostalgic_ritchie] - revision: 27fe30f3b8
trimmed data is s3://mybucket/mydir/data1.txt
trimmed data is s3://mybucket/mydir/data2.txt
ERROR ~ No signature of method: groovyx.gpars.dataflow.DataflowQueue.getFileSystem() is applicable for argument types: () values: []

 -- Check script 'script.nf' at line: 4 or see '.nextflow.log' file for more details


```

I figure the issue is the line with Channel.fromPath(data_line).  The behavior I was expecting is to download a file from S3. 

To try to see if I can get NF to work as I hope I figure that I need to remove the Channel.fromPath being invoked ont the output of splitText/map/view.

If I run the script using commands like the ones below I get a file called input.1 whose contents is a string which is an S3 URL of the file, not the contents of the S3URL.  In other words, I just get a URL back 
and the data is not downloaded from S3.  The behavior I was hoping for is to see the contents of the file in S3 not its URL.

```
in_data_fof=Channel.fromPath("input.txt")
data_line=in_data_fof.splitText().map{ x -> x.trim()}.view(){x -> "trimmed data is $x" }

process adder_process {

        input:
                file in_file from data_line

        """
        set -exu -o pipefail
        echo "Showing the contents of ${in_file} ..." ;
        head ${in_file}
        sleep 10s
        rm -v `readlink -e ${in_file}` && rm -f ${in_file} ;
        """
        }
```

In the .command.out I see lines like : 

```
Showing the contents of input.1 ...
s3://mybucket/mydata/data1.txt
```
and not the contents of the S3 URL.

Is this an issue or bug with NF? an issue with my script? 

How can I feed NF a file-of-S3-files and get it to download them from S3 for a task when the task starts?

I tried a glob in the fromPath but the glob did not pick up any files.  I like the idea of a file-of-S3-files better because I can inspect it before submission to NF to verify that the URLs are correct rather than waiting for NF to run workflows for me to make sure they are correct.

thanks

-nfuser

**Comment by pditommaso** [comment]
This is now allowed 

```
data_line_p=Channel.fromPath(data_line)
```

I think you are looking for this [patter](https://github.com/nextflow-io/patterns/tree/master/process-per-csv-record).

**Comment by githubuserincyte** [comment]
Thank you Paolo!

the following two lines worked as desired.  

```
data_line=in_data_fof.splitText().map{ x -> file(x.trim())}
```
and

```
file in_file from data_line
```

The pattern link you gave was helpful.

Earlier I had done something like that, but instead of "file(x)" I wrote something like "new File(x)" and that had caused an error.

thanks!

-nfuser
