### ISSUE TITLE
Add support for K8s pod labels

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#762]
This enhancement should allow user to provide custom K8s pod labels. For example: 

```
process {
  pod = [label: 'foo', value: 'bar']
}
```

**Comment by pditommaso** [comment]
@tdudgeon @alanbchristie @wikiselev Do you know if K8s allows the definition of multiple pod labels with the same key (and a different value). Is this desiderable?

**Comment by alanbchristie** [comment]
I've just edited a Pod definition and the new label replaces the old so, sadly no, the label has to be unique.

**Comment by pditommaso** [comment]
This simplifies things ;)

**Comment by pditommaso** [comment]
If added the ability to specify custom labels eg. 

```
process {
  pod = [ label: 'FOO', value: 'aaa' ]
}
```

For multiple labels use: 

```
process {
  pod = [
    [ label: 'FOO', value: 'aaa' ],  
    [ label: 'BAR', value: 'bbb']
  ]
}
```

If you test it make sure to use the latest NF docker image snapshot tagged as 

```
0.31.0-SNAPSHOT: digest: sha256:e0f3edb6b7e93c074ff7428a6315cec6c13353ddc0d085070f4f40acae97f896 size: 2620
```

and to use the latest NF snapshot running the following command the very first time: 

```
NXF_VER=0.31.0-SNAPSHOT CAPSULE_RESET=1 nextflow info 
```
