### ISSUE TITLE
jobs hang on pbs cluster

### ISSUE THREAD

**Issue by veeravalli** [nextflow-io/nextflow#763]
Hi Paolo,
Jobs hang on pbs cluster for multi-sample analysis. 
nextflow logs
[log.zip](https://github.com/nextflow-io/nextflow/files/2129703/log.zip)

 Please find the skeleton of nf file as below. 
"HardFilterAndMakeSitesOnlyVcf" jobs get completed and then hangs. 
Skeleton of script under
[vqsr.zip](https://github.com/nextflow-io/nextflow/files/2129708/vqsr.zip)

Please let me know if you need more details. Thanks.

**Comment by pditommaso** [comment]
Very unusual this problem. I've uploaded a new snapshot that should produce more debugging info. Please run it again as 

```
NXF_VER=0.30.3-SNAPSHOT nextflow -trace nextflow run SG10K-bam2gvcf.nf -c nextflow.config -params-file MUX5308_conf.yaml --publishdir MUX5308 -profile nscc -with-report report.html -with-trace -with-dag dag.png -resume
```

**Comment by veeravalli** [comment]
Thanks Paolo. Please find the logs. 
[nextflow_log.zip](https://github.com/nextflow-io/nextflow/files/2129802/nextflow_log.zip)

**Comment by pditommaso** [comment]
Holy crap you found the bug of the year. See #764. 

The problem in your script is that there are many files evaluating to `null`.  At least the following: 

```
hapmap_idx = file(params.references.hapmap) + ".tbi"
omni_idx = file(params.references.omni) + ".tbi"
phase1_snps_idx = file(params.references.phase1_snps) + ".tbi"
```

Add a validation before the first script as shown below: 

```
assert hapmap_idx.exist(), "File $hapmap_idx does not exist"
... 
```

**Comment by veeravalli** [comment]
Sure Thanks. Didn't realize that! Let me fix that.
