### ISSUE TITLE
Report CPU/Memory usage empty with singularity containers

### ISSUE THREAD

**Issue by carrere** [nextflow-io/nextflow#767]
Dear Nextflow team, 
I realise that the report generated using a singularity image is empty for the CPU and Memory usage.
Here is a screenshot of the result on a simple pipeline (bwa mem + samtools) :

![screenshot-2018-6-25 cheesy_lamarck nextflow workflow report](https://user-images.githubusercontent.com/1142779/41847106-2e5a69f0-7879-11e8-86a3-b4695216acd9.png)

I tested on Ubuntu 16.04 and Debian Testing. The report without the use of singularity image is okay.

Sincerely yours,
Sebastien

**Comment by pditommaso** [comment]
What version of NF are you using  ?

**Comment by carrere** [comment]
version 0.30.2

**Comment by carrere** [comment]
.command.out is empty

[.command.err.txt](https://github.com/nextflow-io/nextflow/files/2132910/default.command.err.txt)
[.command.run.txt](https://github.com/nextflow-io/nextflow/files/2132911/default.command.run.txt)
[.command.log.txt](https://github.com/nextflow-io/nextflow/files/2132912/default.command.log.txt)

**Comment by pditommaso** [comment]
Thanks. Please uploaded also the `.command.stub` file.

**Comment by pditommaso** [comment]
Ok, the problem is that the container is missing the `ps` command: 

```
.command.stub: line 45: ps: command not found
```

You need need to include it in the container to have the metrics to work.

**Comment by carrere** [comment]
Thanks ! I thought ps was by default installed on debian ... my mistake !
I close!

Merci
