### ISSUE TITLE
fromFilePairs: Sample ID (grouping key) AFTER read number?

### ISSUE THREAD

**Issue by mohammedkhalfan** [nextflow-io/nextflow#768]
Hello,

I was wondering if it was possible to capture the grouping key _after_ the read number when using `fromFilePairs`. For example, if the files are as so:

```
/path/to/FCID_1_sample_1.fq
/path/to/FCID_2_sample_1.fq
/path/to/FCID_1_sample_2.fq
/path/to/FCID_2_sample_2.fq
/path/to/FCID_1_sample_3.fq
/path/to/FCID_2_sample_3.fq
```

And you use this code:

```
Channel
    .fromFilePairs( "/path/to/FCID_{1,2}_*.fq" )
```

In this case, the grouping key is always `FCID`, which is incorrect. It should be `sample_1`, `sample_2`, etc. 

How to achieve this?

Thank you.

**Comment by pditommaso** [comment]
Unfortunately this is not working but it sounds as a nice improvement. A possibile workaround is to specify the grouping rule as shown below: 

```
def grouping = { file -> file.name.substring(6) }

Channel
    .fromFilePairs( "FCID_{1,2}_*.fq", grouping ) 
    .println()
```

the above grouping simply strips the first 6 characters and return the suffix that should be used to group the pair. You can provide your own implementation.

**Comment by prmac** [comment]
It would be useful o have a fix for this.  I have an issue where often my file names aren't of a constant length and my current workaround is to rename them
