### ISSUE TITLE
Optional tagging of operators 

### ISSUE THREAD

**Issue by baffelli** [nextflow-io/nextflow#769]
Sometimes my pipeline just hangs because of some mysterious reason. After I interrupt it with CTRL+C, ```.nextflow.log``` gives me a list of processes/operator that were still active. So far, it was always due to operators waiting for upstream channels to close. However, as the list of operators is rather long and since I'm using operator of the same type multiple times, it is hard to identify which channel was responsible for keeping them alive. I suggest a way to add a "tag" to the operators; these tags would be dumped in the log at the stage where the still active processes and operators are printed.
 In that manner, one could easily discover which operator are waiting for data and debug their pipeline accordingly.

**Comment by pditommaso** [comment]
This feature would be nice but there's no easy solution on the short term. Therefore I'm closing it and tagging as *whishlist* to remember that it could be a nice-to-have feature at some point.
