### ISSUE TITLE
command line parsing of parameters does not handle some strings properly

### ISSUE THREAD

**Issue by JoeCarlson** [nextflow-io/nextflow#78]
Assuming there is a params.option in a script, invoking a script with an option that ends with a digit followed a letter d, h, m or s:

nextflow <myscript> --option <string>\d[dhms]

(for example, the string "we_live_in_3d"), does not pass the value properly and it takes the value '18d' in the script.

Is the option being coerced into a date-time value?

**Comment by pditommaso** [comment]
Fixed in version `0.15.6`
