### ISSUE TITLE
Scheduling using K8S 

### ISSUE THREAD

**Issue by tdudgeon** [nextflow-io/nextflow#785]
I create this issue to describe some of issues relating to scheduling of NF jobs on K8S. It's really a follow on task to problems 3 and 4 described in #773.

The basic scenario is that a user submits a CPU intensive pipeline to K8S and wants the job to run effectively across all the available nodes. Other jobs might already be running on the nodes. Neither the capacity of the K8S cluster nor the current load will be known to NF when the job is submitted. Ideally NF just submits the job, leaves the scheduling to K8S according to the available CPU and memory and sits back and waits for the job to complete.

I see 3 classes or NF process (considering only the CPU needs):
1. trivial tasks that use minimal amounts of CPU. These can be scheduled anywhere with minimal impact.
2. single threaded tasks that use all of a single core but no more. Ideally you would have as many of these running on each nodes as there are cores on the node. 
3. multi threaded tasks that utilise all the cores on a node. Ideally only one of these jobs would run on each node.

The first class is pretty trivial. They can be submitted without resource limits, or with low resource limits and will only minimally impact other processes.

Considering the second class, K8S has a pretty good way of handling these by specifying resource requests and limits. I've found that if you specify a request of ~0.9 CPU and a limit of ~1.1 CPU the tasks get distributed fairly effectively across the available nodes. With K8S the best approach to this is to use a Job that allows the level of parelellism to be controlled (and adjusted during execution), but the behaviour is much the same when using raw pods. What happens is that pods get started up until there is no CPU capacity left at which points the pods stick in Pending state until CPU capacity becomes available as other pods complete.
Note: this seems to be in contrast to what happens when NF submits pods with CPU limits where submitting the pods causes an error as it couldn't be scheduled, which causes the NF pipeline to throw an error.
In the situation where a previous job is fully utilising the cluster all Pods will presumably be in 'Pending' state until there is capacity. If there is a need to prioritise one type of job over another (e.g. a job from a 'gold' user compared to a 'bronze' user this could probably be handled using labels to distinguish the types. the 'gold' pods will then start in preference to the 'bronze' ones when capacity become available. 

Handling the third class seems more tricky. There does not seem to be a way to specify a CPU resource request of 'all cpus' - only numeric amounts (including fractional amounts) are allowed, and you do not know whether you are running on a machine with 1 core or 72 cores. 
Pod anti-affinity (https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity)  might be one solution to this and this seems to work as described. So you might be able to label this type of task with a label that says 'I need exclusive use of this node' and all NF pods are set to use a `requiredDuringSchedulingIgnoredDuringExecution` anti-affinity rule to make sure that no additional pods are scheduled on any node that is running one of these tasks. In this way the node becomes unschedulable for NF pods until that pod completes, at which time the scheduler is free to schedule whichever new pod(s) it sees fit.

Regarding implementation, handling the second type in NF seems reasonably simple. At the very least allowing `cpus: 1` to get put into the pod definition is needed, but to handle this properly we need to be able to specify fractional amounts and to specify requests and limits separately.

Handling the third type probably needs more thought. Adding support for affinity and anti-affinity could be reasonably complex, and it might be that there are better approaches.

**Comment by tdudgeon** [comment]
Just commenting on this as the issue is still real.
Though this recent issue partly handles it: https://github.com/nextflow-io/nextflow/issues/1570

**Comment by tdudgeon** [comment]
This issue is still real.
@pditommaso Are there any plans for this?

**Comment by pditommaso** [comment]
I think soon we need to improve K8s support including this issue.

**Comment by tdudgeon** [comment]
@pditommaso Happy to help if you need help planning this.

**Comment by tdudgeon** [comment]
Keeping topic alive.

**Comment by pditommaso** [comment]
It will happen! 😄

**Comment by tdudgeon** [comment]
Please keep this open.

**Comment by tdudgeon** [comment]
Please keep this open. @pditommaso What are the chances this can be worked on soon?

**Comment by pditommaso** [comment]
The need here is to allow cpus as millis, isn't it?

**Comment by tdudgeon** [comment]
Allowing cpus as millis would to some extent handle this, but there's also the need to be able to specify both `requests` and `limits`. My view is that this would better be handled by allowing K8S pod properties to be specified e.g. extend the range of properties for the [pod directive](https://www.nextflow.io/docs/latest/process.html#pod). See also #2161 which also needs this. And there are probably many other K8S properties that it would be useful to access.

**Comment by pditommaso** [comment]
Think we can split into two steps: 

1. allows `cpus` to handle millis as float and string notation
2. extend `cpus` with the capability to handle `request` and `limit`

**Comment by bentsherman** [comment]
Hi @tdudgeon I'm going to be taking the lead on Nextflow K8s issues, starting with cpus request / limit.

I already have a proposal for pod affinity at #2390. I needed it to avoid certain GPU types that didn't jive with my application. However, I don't think it would help you here. Based on the discussion [here](https://stackoverflow.com/questions/59007859/how-to-set-pod-to-use-all-available-cpu-cores), you might be able to do it by not specifying a cpu limit and adding a taint to the node so that it only accepts one pod at a time.

**Comment by tdudgeon** [comment]
@bentsherman That's great to hear. Could you also handle #2161 when you get a chance?

**Comment by bentsherman** [comment]
Yes I have the list of all the k8s-related issues. That one looks like one of the easier ones to tackle.

**Comment by bentsherman** [comment]
@tdudgeon Some questions for you:

1. Could you elaborate more on why requesting [0.9, 1.1] cpus per pod improves overall utilization, instead of just 1 cpu per pod? It seems like the number of pods running in parallel would be the same.
2. The `task.cpus` variable needs to be an integer value because it refers to the number of threads or processes a task should use. In this case it's clear that `task.cpus` should be 1, but in general, how do you think it should be determined? This question seems especially non-trivial when a range is requested.

**Comment by tdudgeon** [comment]
1. Assume there were 8 cores available. If I request 1 core then I'm likely to on get 7 jobs scheduled as there will be some kubernetes pods (typically demon sets) running. If I request 0.9 then I might get all 8 scheduled. Also, often you get slightly better throughput if you slightly overcommit and not all pods will be running at 100% all the time.
2. This is why I think for K8S it's better to set this using K8S specific options for limits and requests, and ignoring  `task.cpus` if those are specified.

**Comment by bentsherman** [comment]
I see. I am thinking the best approach for now is to set `task.cpus` to `null` whenever `cpus` is a fractional value or a request/limit range. That way we won't introduce any new behavior aside from your use case, and if someone comes along with a new use case they can advocate for it.

The only other strategy that remotely makes sense to me is to set `task.cpus` to `ceil(cpus.request)` or `floor(cpus.limit)`. But doing one or the other seems arbitrary. For example, if someone requests `cpus = [request: 2, limit: 4]`, do they want to run 2 threads that are CPU-heavy? 4 threads that are light? It's not clear from the resource request what the intention is. Better I think to just leave `task.cpus` as `null`.

**Comment by tdudgeon** [comment]
@bentsherman Just checking what the status of this is. The current docs suggest that CPU `request` and `limit` is not settable as a pod directive (https://www.nextflow.io/docs/latest/process.html#pod) and the cpus directive (https://www.nextflow.io/docs/latest/process.html#cpus) only seems to allow an integer number fo CPUs to be specified.
Is there any way to request a fractional number of CPUs at present?

**Comment by bentsherman** [comment]
The PRs for both have been in review for a while., but I think Paolo is hesitant to merge them and potentially break some existing behavior. In my opinion they are ready.

@pditommaso it would be good to make a decision on #2516 and #3027 one way or the other. At the very least I think the CPU request/limit should be safe to merge.

**Comment by tdudgeon** [comment]
Would be great to get at least the fractional CPU change applied.

**Comment by bentsherman** [comment]
Closing, see https://github.com/nextflow-io/nextflow/issues/773#issuecomment-2087548516
