### ISSUE TITLE
Idea: Automated methods section generation

### ISSUE THREAD

**Issue by apeltzer** [nextflow-io/nextflow#786]
Hi everyone!

while discussing something with @danielhuson he suggested something for nextflow that is really cool in my opinion and wanted to share that, ask for comments and maybe thoughts on how to implement that in Nextflow at some point. 

As far as I know, Nextflow can produce a DAG graph at the end of an execution, to track back what kind of processes were executed at which point. This is very useful for people to figure out what the pipeline was doing, but one idea would also be, to generate an automated methods section out of this information, summarizing the processes that were run with which parameters etc. 

Something like this would be possible for example: 

`Input reads were processed using workflow.name. Reads were initially processed using $process.1 with $script-section, followed by $process.2 with $script-section.2` (sorry, this is very basic but should only illustrate what I mean).

The new version of MEGAN (by @danielhuson) for example does this:
http://ab.inf.uni-tuebingen.de/software/megan6/

Similar to this,  MEGA 6 (maybe 7 too) can do similar things, too. 
https://www.megasoftware.net/

I see some problems when referring to parameters of the respective tool(s), but maybe someone has a smart idea how this would work - could be a cool feature and if this is something integrated in nextflow,  would be benefitial to everyone, too :-) 

Linking some people in here who I think might be interested: @ewels @MaxUlysse @skptic @sven1103

**Comment by pditommaso** [comment]
How does this differ from the tasks report? 
![image](https://user-images.githubusercontent.com/816968/42465352-062fc248-83ac-11e8-9922-fef2ee32e2cd.png)

**Comment by pditommaso** [comment]
Maybe a example of a real execution is a good start to discuss it :)

**Comment by pditommaso** [comment]
Tagging as stable  and closing because this request as no more activity.

**Comment by ewels** [comment]
I guess in a way, this ties in to https://github.com/nf-core/tools/issues/236 where we were discussing having a description of what each tool is doing in the pipeline and automating a similar methods paragraph.

**Comment by pditommaso** [comment]
Being so it would be better covered by #879 or with a custom nf-core tool in the short run.
