### ISSUE TITLE
Error while running compile.sh

### ISSUE THREAD

**Issue by kemin711** [nextflow-io/nextflow#791]
## Bug report 

(If you a reporting a bug please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

running compile got one warning, may not be fatal

### Program output 

compile.sh
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/kzhou/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.4.15/74b7e0b99526c569e3a59cb84dbcc6204d601ee6/groovy-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
warning: [options] bootstrap class path not set in conjunction with -source 8
Note: /home/kzhou/coding/nextflow/subprojects/nxf-commons/src/main/nextflow/util/ServiceDiscover.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
warning: [options] bootstrap class path not set in conjunction with -source 8
Note: /home/kzhou/coding/nextflow/src/main/groovy/nextflow/sort/BigSort.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
warning: [options] bootstrap class path not set in conjunction with -source 8
1 warning

### Steps to reproduce the problem

May be this is specific to my computer's Java install
git pull
compile.sh

My java version is 10

### Environment 

* Nextflow version: Latest from git as today
* Java version: 10
* Operating system: [Linux Uuntu 18] 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pditommaso** [comment]
> Required dependencies
Compiler Java 8

https://github.com/nextflow-io/nextflow#required-dependencies
