### ISSUE TITLE
add container run options with AWS Batch

### ISSUE THREAD

**Issue by tischfis** [nextflow-io/nextflow#793]
useful run option would be to mount volume with docker ( -v) 

Looks like this is currently unsupported for AWS batch
https://www.nextflow.io/docs/latest/process.html#containeroptions

**Comment by pditommaso** [comment]
Not sure to support this request. These options are meant to be used when the container is managed by NF. When using a native container environment such as Batch or K8s container options should rely on that subsystem.

**Comment by pditommaso** [comment]
I see the reason for this request but I don't think custom volumes should be mounted by using the `containerOptions` directive. This is supposed to be a pass-through directive for the target container engine. Currently AWS Batch is using Docker but there's no guarantee that it will be in the future. 

Currently custom volumes can be managed defining a custom job definition in the AWS Batch environment and use it in place of a container name in your workflow configuration.

**Comment by multimeric** [comment]
If AWS Batch stopped using Docker then we wouldn't be able to use it as a target for a portable containerised workflow and we would have much more serious issues than just some configuration not working anymore. I'm a +1 for this issue for its original justification. Specifically I want to be able to pass in environment variables to the batch container.
