### ISSUE TITLE
Output of 'config' broken when interpolating into a list

### ISSUE THREAD

**Issue by TheRealPJC** [nextflow-io/nextflow#801]
The output of the 'config' command is broken when a parameter uses string interpolation in a list of elements.

For example, running the following command:

```
nextflow -C my_config.cnf config
```

on the file 'my_config.cnf' with the following content:

```
CONST = "SOMETHING"
params {
  interpolated_list = ["${CONST}/a", "b", "c"]
}
```
should give this i.e. the config as it is after the interpolation of $CONST into the first element in the list: 

```
CONST = 'SOMETHING'
params {
   interpolated_list = ['SOMETHING/a', 'b', 'c']
}
```

However, the actual output is this: 

```
CONST = 'SOMETHING'
params {
   interpolated_list = [SOMETHING/a, 'b', 'c']
}
```

The difference is that the first item in the list ("SOMETHING/a") has lost its quotation marks, is not treated as a string, and the output is not a valid Nextflow configuration.

Occurs on Linux and Mac with Nextflow 0.30.1.4844

**Comment by pditommaso** [comment]
Included in version `18.12.0-edge`.
