### ISSUE TITLE
SLURM executor fail to submit jobs when cluster option is specified

### ISSUE THREAD

**Issue by matthiasheinig** [nextflow-io/nextflow#805]
Hi,

I am running into a similar problem as discussed in [this issue](https://github.com/nextflow-io/nextflow/issues/190).

I am trying to run nextflow on a slurm system with multiple clusters. I specify the cluster using the "--cluster mpp2" argument to sbatch. So the submit response also contains the info about the cluster (in addition to the job id, see below). I am not sure if this is the default slurm behaviour, but I would guess so. Would it be possible to adapt the regexp in this [method](https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/executor/SlurmExecutor.groovy#L98-L108) to take this into account?

Best,
Matthias

### Program output 

  Invalid SLURM submit response:

```
Submitted batch job 630114 on cluster mpp2
```

### Steps to reproduce the problem

I am submitting this simple test script:

```{bash}
#!/bin/bash
echo "TEST SCRIPT RUNNING IN THE FOLLOWING ENVIRONMENT:"
echo
echo
echo Command args:
echo $@
echo
echo
env > $1
```

### Environment 

* Nextflow version: nextflow version 0.30.2.4867
* Java version: 1.8.0_51
* Operating system: Linux

**Comment by pditommaso** [comment]
How is the `sbatch` output when you specify the option `--cluster mpp2` ?

**Comment by matthiasheinig** [comment]
If I run this outside of NF: 
```{bash}
sbatch --cluster mpp2 test_batch.sh
```
Submitted batch job 630288 on cluster mpp2

**Comment by pditommaso** [comment]
Ah, you have included in the first post, I was missing that.

**Comment by matthiasheinig** [comment]
Thank you for this quick response! 

Could you please quickly tell me how I can access that snapshot? Do i need to build from source?

**Comment by pditommaso** [comment]
Just using the command mentioned above.

**Comment by matthiasheinig** [comment]
Perfect! It's working now.. Thanks again!

**Comment by pditommaso** [comment]
Nice. It will included in the next stable release.
