### ISSUE TITLE
Nextflow cloud automatic aws docker registry login

### ISSUE THREAD

**Issue by aresDeathscythe** [nextflow-io/nextflow#809]
Hi,

according to issue #45 I would like to ask if someone knows an automated way to execute the 'aws ecr-get-login' for docker registry for every nextflow cloud node (master & worker). I am using the Apache Ignite executer and tried several ways like ssm command after cluster creation (could not find a target even though the tags were right). 
I only need a way to get the login on every node that the docker image can be pulled from the registry.

Thanks for help!

**Comment by tbugfinder** [comment]
Are you using an IAM user or an instance profile ?

**Comment by tbugfinder** [comment]
Policy `arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role` includes ECR read access.

**Comment by tbugfinder** [comment]
Don't you use an ECS optimized image as basis for the instance running your container(s)?

**Comment by aresDeathscythe** [comment]
What do you mean by an ECS optimized image? :) I created a fresh EC2 Instance without anything installed. Installed my prerequisites for my pipeline and created an AMI out of it which is used as imageId in my nextflow.config. I also created a docker image for my workflow and pushed it to the ECS in an own registry. The repo ID from the docker image is also used in the nextflow.config. 

I finished my tests & everything is working fine now with this credential-helper. :)

**Comment by tbugfinder** [comment]
AWS provides ECS optimized images which are prepared to run containers.
If those images are customized by e.g. packer such an issue shouldn't come up.
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html

**Comment by aresDeathscythe** [comment]
Oh I did not come over this page during my research, thanks for this :) I will consider trying them out if they work like my configuration is working now. Thanks!

**Comment by pditommaso** [comment]
Excellent.
