### ISSUE TITLE
Add `publishDir` directive which copies outputs to a specified target directory

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#81]
It's a common use case that some or all process output need to be copied a specified target directory. 

Nextflow uses currently are using the `storeDir` directive to active that, but in most cases that's not a good idea because the `storeDir` is meant to work as a long term process cache, modifying the process output files target folder. If not used properly it can produce tricky side effects (for example using the same `storeDir` for multiple processes can result in race condition when creating/accessing output files).

In order to copy process output a new `publishDir` should be introduced. 

By default this directive will create a symlink output files produced by a task to a specified folder. For example: 

    process foo {
      publishDir '/some/path'

      script:
      <job>
    }

The advantage of `publishDir` is that is does not change process target folder and the behaviour of the process caching mechanism. Output files will be created  in the task unique working directory as usual. 

Advanced options. The following options should be supported: 
 
* mode: symlink | link | copy | move 
* pattern: *glob file pattern to select which process outputs to publish* 
* overwrite: `true` overwrite existing file with the same name in the publish folder (default: true)

**Comment by mfoll** [comment]
That will be so useful! Could we also have the option to have multiple `publishDir`directives with different patterns for the same process (in order to copy different output to different folders)?

**Comment by pditommaso** [comment]
Let's adhere at the KISS principle and postone multiple `publishDir` as a possible enhancement.

**Comment by heuermh** [comment]
This would be great.

Here's an example of an explicit ```copy``` method that could be replaced by this directive
https://github.com/heuermh/bdg-nextflow/blob/master/transform.nf#L23

**Comment by pditommaso** [comment]
Yes, I've realised that is a very common use case.

**Comment by pditommaso** [comment]
See the related [documentation](https://github.com/nextflow-io/nextflow/blob/master/docs/process.rst#publishdir)

**Comment by heuermh** [comment]
Awesome, thank you!
