### ISSUE TITLE
AWS Batch executor creates timeline report with missing time data

### ISSUE THREAD

**Issue by RLittinNV** [nextflow-io/nextflow#816]
## Bug report 

When running any nextflow script in AWS batch mode the -with-timeline option does not produce any time data in the outputed html page, meaning that the resulting timeline graph does not display anything.

### Expected behavior and actual behavior

Expect time information in the data section of the timeline html output page, but all "times" data is just empty arrays.

```
{"label": "copy_fastq_from_s3 (NA12878 L003)", "times": []},
{"label": "copy_fastq_from_s3 (NA12878 L002)", "times": []},
{"label": "copy_fastq_from_s3 (NA12878 L001)", "times": []},
{"label": "mapper (NA12878 L003)", "times": []},
```

The rest of the page is ok.
When running the same jobs with -with-report or -with-trace appropriate submit and duration times are produced.

### Program output 

part of the data section in the output html file.

```
{"label": "copy_fastq_from_s3 (NA12878 L003)", "times": []},
{"label": "copy_fastq_from_s3 (NA12878 L002)", "times": []},
{"label": "copy_fastq_from_s3 (NA12878 L001)", "times": []},
{"label": "mapper (NA12878 L003)", "times": []},
```

### Steps to reproduce the problem

Running in AWS batch environment.

### Environment 

* Nextflow version: 0.31.0
* Java version: Groovy 2.4.15 on OpenJDK 64-Bit Server VM 1.8.0_151-b12
* Operating system: Linux 4.4.0-1063-aws

**Comment by pditommaso** [comment]
Thanks for reporting this issue. A patch is available in the latest snapshot, you can give it a try using the following command: 

```
NXF_VER=0.31.1-SNAPSHOT nextflow run ... etc
```

**Comment by RLittinNV** [comment]
Thanks, I will give it a go.
