### ISSUE TITLE
In K8s NF does not have the right $PATH variable in the pod

### ISSUE THREAD

**Issue by wikiselev** [nextflow-io/nextflow#817]
#### Expected

We expect NF to use the PATH of the created pod. When we check PATH inside a running pod:
```
nf-0e4457f87b9548eaad527758415d0bee:# echo $PATH
/opt/conda/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

#### Actual
Running the same command inside the NF process script gives the following:
```
/mnt/gluster/projects/cellgeni/rnaseq-noqc/bin:/mnt/gluster/projects/cellgeni/rnaseq-noqc/utils:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
```
Conda path has been lost and we don't have access to our software.
### Program output 

[nextflow.log](https://github.com/nextflow-io/nextflow/files/2235193/nextflow.log)

### Steps to reproduce the problem

NA

### Environment 

* Nextflow version: [0.30.2.4867] 
* Java version:
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (IcedTea 3.6.0) (Alpine 8.151.12-r0)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
* Operating system: [Alpine Linux v3.7]

**Comment by pditommaso** [comment]
Not sure to understand how the conda environment is supposed to be created.

**Comment by wikiselev** [comment]
Hi Paolo, 

We install conda in the [docker image](https://github.com/cellgeni/rnaseq-noqc/blob/k8s/Dockerfile) which is used for the pipeline (similar to nf-core).

To test the problem above we then run `source activate` in the NF process script:

```
process crams_to_fastq {
...
    script:
    """
    source activate rnaseq1.6dev
    ...
    """
}
```
And we get the following error provided by NF:
/mnt/gluster/ubuntu/work/25/3671041fb267dfb73344d4a49f5b41/.command.sh: line 6: activate: No such file or directory

**Comment by pditommaso** [comment]
Not sure this is a NF issue. In my test it works fine. I would suggest to  create the image adding the tools in the root environment, see [here](https://github.com/nextflow-io/rnaseq-nf/blob/master/docker/Dockerfile#L8) for an example. 

Doing so you won't need to activate the environment with the `source activate` command.

**Comment by wikiselev** [comment]
Hi Paolo, thanks for the solution. We've actually gone through a similar route - defining one docker image per process, instead of one large docker image for the whole pipeline. And because we used biocontainers, e.g. `container = 'quay.io/biocontainers/samtools:1.8--4'`, the installation there is a proper one, so that all of the binaries are located in the root environment already. Thanks again! Vlad

**Comment by pditommaso** [comment]
Good ✌️
