### ISSUE TITLE
possible to override conflicting parameters given on the command line?

### ISSUE THREAD

**Issue by bio15anu** [nextflow-io/nextflow#818]
I am thinking of a case scenario where the user has erroneously specified conflicting parameters on the command line, such as params.one and params.two for example. Is there a mechanism where one can use a simple conditional to override one such parameter if they are found to occur together?

eg.
`if ((params.one == true) && (params.two == true)) {params.two = false}`

I haven't actually tested this but my understanding is that the command line would take priority over the main.nf script here so such a script would essentially be ignored?

**Comment by pditommaso** [comment]
This is not possible because `params` are only be supposed to overridden from the CLI or the config file, not from the script file. 

Best practice are to validate and throw an exception in case of wrong usage, ie: 

```
if ( params.one && params.two ) { error "Params one and two collide" }
```

More similar to your approach you can use an intermediate variable, ie: 

```
two_flag = params.one && params.two ? false : params.two 
```

**Comment by pditommaso** [comment]
Closing  this question. Feel free to comment below if needed.

**Comment by pditommaso** [comment]
thanks!
