### ISSUE TITLE
Add Ignite failure detection timeout configuration parameters

### ISSUE THREAD

**Issue by tdudgeon** [nextflow-io/nextflow#820]
As discussed on the nextflow mailing list (https://groups.google.com/forum/#!topic/nextflow/YtjS3q6XZlM) and then the Ignite mailing list (http://apache-ignite-users.70518.x6.nabble.com/node-becoming-inactive-td23058.html) there might be the need to add timeout parameters for `failureDetectionTimeout` and `clientFailureDetectionTimeout` to the Ignite executor.

**Comment by pditommaso** [comment]
I've just uploaded `0.31.1-SNAPSHOT build 4891` including this patch.
