### ISSUE TITLE
Feature request: Save output of long running process if the process is killed or crash

### ISSUE THREAD

**Issue by czotti** [nextflow-io/nextflow#821]
## Use Case
I'm training neural network model for some tasks with nextflow. The process gets as input a directory and it's given to the script directive.
```
params.input = false
process training_model {
    publishDir "results/training"
    scratch true

    input:
    file(dataset) from Channel.fromPath("${params.input}")

    output:
    set file("checkpoints"), file("model.pt") into output_training

    script:
    """
    train_model.py ${dataset} --batch_size 10 --nb_epochs 20 ...
    """
}
```
The output `checkpoints` is a directory where the script `train_model.py` save the information of the model after each epoch.

My issue is that the training of these models could take a lot of time (several days to weeks). 
In the case of an electric issue, a crash in any case because of memory allocation on GPU or me which see that the model trained long enough and the result on the validation is good I could kill it by hand.
In all these cases I lost my model `checkpoints` which I want to use to be able to test the model on other datasets. The data is not saved into the `work` directory.
In my case, the `scratch true` is necessary because we are working on a remote directory system.

For now, I use a cron job that logs into the cluster and retrieves the `nxf` directories from `/tmp/`.

It could be nice to have nextflow save the outputs from the scratch at least in the `work` directory or elsewhere that can be defined by a directive in the process?

**Comment by fmorency** [comment]
I agree that it would be nice to have the option to periodically save files from currently running processes somewhere "safe" built-in NF.

**Comment by pditommaso** [comment]
Not so sure to back this request, also adding some kind of directive NF would only do on process termination, it won't protect against hard break as you are suggesting. 

The best solution would be to not use `scratch`, what's your remote file system?

**Comment by czotti** [comment]
You're right for the process termination issue, but could it be at periodical intervals as fmorency suggested?
The remote file system is a samba share hosted on FreeNAS.

**Comment by pditommaso** [comment]
This problem could be partially solved declaring the directory where the training model is saved by your script as an output, then NF will copy it to the pipeline work-dir or even a `publishDir`. 

The problem however is that the copy process is only applied when the task is successfully executed. I agree that it can be useful to provide an option to instruct NF to copy output files whatever is the task exit status.

**Comment by fredericlemoine** [comment]
It would be useful indeed. May be linked to #459 ?

**Comment by pditommaso** [comment]
I have to tell the truth, I've never fully understood #459 😅. Is the same as this proposal ?

**Comment by czotti** [comment]
I have done some tests, removing the `scratch` put everything in the `work` directory (which is also on the remote file system) and all the file are accessible in any scenario. Unfortunately, I need to use the `scratch` because the process read really often on disk to load training data. In the case of training one model at a time the loading is kind of okish, but if I run 2 or 3 model at the same time the loading from the remote file system is too slow (1gb ethernet card), and all the processes become really slow.

For this reason, the `scratch` cannot be removed from the configuration for speed issues. 

In this scenario, a checkpoint kind of system could be really useful.

**Comment by pditommaso** [comment]
NF has already an implicit mechanism, the problem is that it get lost when using the `scratch` option. It can be extended in such a way that output files are copied from the scratch to the task work dir, also when the task reports a non-zero exist status.

**Comment by fmorency** [comment]
Extending the NF implicit mechanism when the task reports a non-zero exit
status AND using a scratch directory other than `/tmp` which wouldn't get
deleted after a power failure would probably fix all our cases.
