### ISSUE TITLE
AWS Batch fails if process tag length is too long

### ISSUE THREAD

**Issue by RLittinNV** [nextflow-io/nextflow#822]
## Bug report 

When running in awsbatch a process failed to get queued because its job name was too long. Nextflow modifies the process tag to replace invalid characters but it does not adhere to AWS batch's 128 character length limitation. 

### Expected behavior and actual behavior

Expected: Truncate long process tags to 128 characters when creating AWS batch job name.
Actual: Only modifies illegal characters, leaving length unchanged.

### Program output 

ERROR ~ Error executing process > 'merge_bams (NA12878-100ng-E08A-A06_L002_sorted.bam NA12878-100ng-E08A-A06_L004_sorted.bam NA12878-100ng-E08A-A06_L001_sorted.bam NA12878-100ng-E08A-A06_L003_sorted.bam)'

Caused by:
  Error executing request, Exception : Job name should match valid pattern, RequestId: 1333529f-96a9-11e8-ba20-ff4a80a20d55 (Service: AWSBatch; Status Code: 400; Error Code: ClientException; Request ID: 1333529f-96a9-11e8-ba20-ff4a80a20d55)

### Steps to reproduce the problem

Submit a job with a process that has a tag with more that 128 characters in it.

### Environment 

* Nextflow version: [0.31.1-SNAPSHOT build 4890] 
* Java version: [Groovy 2.4.15 on OpenJDK 64-Bit Server VM 1.8.0_151-b12]
* Operating system: [Linux 4.4.0-1063-aws]

**Comment by pditommaso** [comment]
Fixed `0.31.1-SNAPSHOT.4891`.
