### ISSUE TITLE
A problem about calliNGS.NF

### ISSUE THREAD

**Issue by haidianfarmer** [nextflow-io/nextflow#832]
This problem is about the parameter definition in the nextflow .I don't know where I should place the definition of parameters beter if I have many processes .calliNGS is an example. The problem is that the difference between profile aws.params cluster.params and the params in the main doc. In my wrong opinion the function of the params is only to define the different parameters Which appears only in the front of the main docs.
Thank you!

**Comment by KevinSayers** [comment]
If I understand, you are asking why there are params in the aws and cluster profiles and at the top of the nextflow.config file?

**Comment by haidianfarmer** [comment]
yes!

**Comment by KevinSayers** [comment]
If you do not have params specific to a profile you can just specify them all outside of the profiles. The params in a profile are the same as those at the top of the config file, but they are only used if you specify the profile. You have asked a couple questions regarding the AWS/cluster profiles, are you running your workflow on AWS and a cluster?

**Comment by pditommaso** [comment]
I'm closing this because there's no more feedback.
