### ISSUE TITLE
Metrics collector process may cause the main process to report a false non-zero exit status

### ISSUE THREAD

**Issue by gcollet** [nextflow-io/nextflow#836]
### Expected behavior and actual behavior

In a nextflow process, I launch a PERL script that opens a csv file, cut a part and output what is needed in another (tmp.csv)

nextflow run main.nf 
-> get the file, everything went fine

nextflow run main.nf -with-report report.html 
-> Error .command.stub: line 58: kill: (7658) - No such process

### Program output 

[nextflow.log](https://github.com/nextflow-io/nextflow/files/2287356/nextflow.log)

### Steps to reproduce the problem

https://github.com/gcollet/bug_nextflow

Everything is in the github repo.

The command I launched : nextflow run main.nf -with-report report.html 

### Environment 

* Nextflow version:  0.31.1 build 4886
* Java version: 1.8.0_172
* Operating system: macOS

**Comment by pditommaso** [comment]
What if you execute it without the `-with-report` option  ?

**Comment by pditommaso** [comment]
There was glitch in the background process collecting the task metrics. Thanks for reporting it. 

I've uploaded a snapshot fixing the issue. You may want to give a try using the following command: 

```
NXF_VER=0.32.0-SNAPSHOT nextflow run .. etc
```

**Comment by maxibor** [comment]
it works with this update, thanks ? When will this version 0.32 be released ?

**Comment by pditommaso** [comment]
Likely later this week or no later then next one.
