### ISSUE TITLE
Java NIO2 FileSystemProvider implementation for Azure

### ISSUE THREAD

**Issue by sodic** [nextflow-io/nextflow#839]
I am planning to implement a Java NIO2 `FileSystemProvider` (and other accompanying classes) for the [Azure Blob storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction). From what I understand, this storage plan should be analogous to [AWS S3](https://aws.amazon.com/s3/).

Microsoft does provide a REST API to access and work with the file system, as well as a [Java storage client library](https://docs.microsoft.com/en-gb/java/api/overview/azure/storage/client?view=azure-java-stable). However, they haven't yet provided an implementation for `java.nio` and it is not likely they will any time soon. See [this issue](https://github.com/Azure/azure-storage-java/issues/305) for more details.

The idea is to do this in the same way it was done for DNANexus a few years ago (https://github.com/nextflow-io/jdk7-dxfs). In other words, this `java.nio` implementation would just be a facade over the existing Java API provided by Azure.

An introduction to the existing API can be found [here](https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable).

Does this sound reasonable?

**Comment by pditommaso** [comment]
Sorry for the late reply. Yes, this makes a lot of sense. You may also want to give a look to the implementation for [Google Storage](https://github.com/nextflow-io/nxf-gcloud) (in particular for the tests) and a more advanced one always for Google Storage [at this link](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-contrib/google-cloud-nio).

**Comment by rickle-msft** [comment]
Hi, @sodic. I posted some follow up to the discussion around this over on the [Azure Storage Java SDK repo](https://github.com/Azure/azure-storage-java/issues/305) if you want to take a look and chime in.

**Comment by pditommaso** [comment]
Hi @sodic, with @rickle-msft we are organising a call to discuss how to move on this. Feel free to join the discussion [here](https://gitter.im/Azure-jsr203/Lobby).

**Comment by rickle-msft** [comment]
Just to follow up here, we have begun our work to implement the nio interface on top of Azure Storage Blobs. I will be posting a design doc in the repo soon and have done some work to initialize the FileSystem already. Please reference the link in my original comment if you would like to stay up to date on this.

**Comment by pditommaso** [comment]
Excellent.

**Comment by SHarrySeldon** [comment]
Is there any updates for this feature?

**Comment by pditommaso** [comment]
None on NF side. However, I think MS folks made good progress on the required JSR203 support library.

**Comment by pditommaso** [comment]
keep open

**Comment by pditommaso** [comment]
The support for Azure Batch & Blob Storage is now available https://www.nextflow.io/docs/edge/azure.html
