### ISSUE TITLE
Allow access to manifest scope during workflow execution

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#840]
Over at @nf-core we're trying to establish nice config best practices. With the inclusion of the new `manifest.nextflowVersion` variable, it's making increasing sense to bundle all variables describing the workflow into the `manifest` scope as follows:

```nextflow
manifest {
  name = 'nf-core/rnaseq'
  description = 'Nextflow RNA-Seq analysis pipeline, part of the nf-core community.'
  homePage = 'https://github.com/nf-core/rnaseq'
  author = 'Phil Ewels, Rickard Hammarén'
  pipelineVersion = '1.0dev'
  mainScript = 'main.nf'
  nextflowVersion = '>=0.31.1'
}
```

This is readable and tidy, and works as expected when checking the pipeline config with `nextflow config`. However, it's not possible to access these manifest variables from _within_ the workflow script (`main.nf`). Attempting to do so triggers the following error:
```
ERROR ~ No such variable: manifest
```

Is it possible to make these accessible from within the pipeline script in the same way as other variables? We have discussed this once before (see #597) and I know that we could just use `params.everything` instead, but it doesn't feel as tidy 🤓

**Comment by sven1103** [comment]
My guess is, to pass the `manifest` map to the script binding object instance, which is not yet there. @pditommaso please correct me, I guess I have to make changes in https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/script/ScriptRunner.groovy and https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/script/ScriptBinding.groovy, passing the `manifest` entry from the parsed config file, right?

**Comment by sven1103** [comment]
#841

**Comment by ewels** [comment]
Yay! Thanks to both of you, this may be a small thing but it makes me very happy 😎
