### ISSUE TITLE
Log filter option is misinterpreted when enclosed in double quotes

### ISSUE THREAD

**Issue by KevinSayers** [nextflow-io/nextflow#846]
## Bug report 

Nextflow log filter does not work as expected. 

### Expected behavior and actual behavior

The `-F` log option should allow filtering on a field, but either no filtering occurs or receive the error 'no such variable' for the filter field value. 

### Program output 

```
nextflow log fervent_stone -f "container" -F "container == 'ubuntu'"
ERROR ~ No such variable: ubuntu
```

### Steps to reproduce the problem

Filter on a field 

### Environment 

* Nextflow version: 0.31
* Java version: 1.8
* Operating system: Ubuntu

**Comment by pditommaso** [comment]
It looks like some bash quote chars mess. This should work: 

```
nextflow log fervent_stone -f 'container' -F 'container == "ubuntu"'
```

**Comment by pditommaso** [comment]
It looks the problem is caused by the `nextflow` launcher script when wrapping command line args before invoking the java application. Like at this point: https://github.com/nextflow-io/nextflow/blob/5e1e1814cc1ce5745a2a1db050f5071abcdadff3/nextflow#L134-L137
