### ISSUE TITLE
Specify jobRoleArn for execution on AWS Batch

### ISSUE THREAD

**Issue by sminot** [nextflow-io/nextflow#849]
## Bug report 

In order to execute analyses on AWS Batch, I need to be able to pass along my jobRoleArn, which is then included in the specification for the container properties. I don't see any documented way to specify this in the nextflow config file.

### Expected behavior and actual behavior

Ideally there would be a parameter the user could include in the nextflow config file to set the jobRoleArn, which would then be included in the container properties for the AWS Batch job that is started as part of the workflow.

**Comment by pditommaso** [comment]
A workaround for that is to create your own job definition providing the required jobRoleArn and then specify the the job definition in place of the container name in your pipeline script/config https://www.nextflow.io/docs/latest/awscloud.html#custom-job-definition.

**Comment by sminot** [comment]
Thanks for the suggestion, I'll take a look at that.

**Comment by sminot** [comment]
Any update on whether the jobRoleArn can be used with AWS Batch and Nextflow, @pditommaso ?

**Comment by pditommaso** [comment]
It's surely a useful enhancement but can't provide an ETA, need to prioritise other devs. sorry.

**Comment by sminot** [comment]
Yeah, taking a look now it's clear that the structure for AWS job definitions within NF is tied cleanly to container names, which makes a lot of sense. Probably beyond my skills to make the change on that deep of a level -- ah well!

**Comment by pditommaso** [comment]
Yes, but NF can use any job definition you may have created using it in place of the container name. See [here](https://www.nextflow.io/docs/latest/awscloud.html#custom-job-definition) for details.

**Comment by sminot** [comment]
I added this functionality in the PR #1080 

Looking forward to your review and approval, @pditommaso!

**Comment by pditommaso** [comment]
Thanks a lot for submitting this proposal. I generally agree with these extension, however I will merge it to make these changes uniform with a larger on-going enhancement of the AWS Batch executor.

**Comment by pditommaso** [comment]
Solved by 651eead and included and available since version `19.05.0-edge`.
