### ISSUE TITLE
processDir directive does not resolve variables in the process scope

### ISSUE THREAD

**Issue by heuermh** [nextflow-io/nextflow#85]
transform.nf:
```groovy
#!/usr/bin/env nextflow

params.dir = "${baseDir}/example"

bamFiles = "${params.dir}/**.bam"
bams = Channel.fromPath(bamFiles).map { path -> tuple(path.baseName, path.toRealPath().getParent(), path) }

process transform {
  publishDir parent, mode: 'copy'

  input:
    set sample, parent, file(bam) from bams
  output:
    set sample, parent, file("${sample}.adam") into reads

  """
  adam-submit transform -force_load_bam $bam ${sample}.adam
  """
}
```

```bash
$ nextflow run transform.nf -with-docker heuermh/adam
N E X T F L O W  ~  version 0.16.0
Launching transform.nf
ERROR ~ Not such variable: parent

 -- Check script 'transform.nf' at line: 10 or see '.nextflow.log' file for more details
```

**Comment by pditommaso** [comment]
The above commit solve the problem. However note that like other directives in order to access process local variables they must be enclosed by a closure or *dynamic* string. For example: 

     publishDir "$parent", mode: 'copy'

**Comment by heuermh** [comment]
Thanks!

Is there any difference between ```"$parent"``` and ```"${parent}"```?
And then by closure, would just ```publishDir { parent }, mode: 'copy'``` work?

**Comment by pditommaso** [comment]
No, both `"$parent"` and `"${parent}"` are `GString` object. 

Yes, the syntax `publishDir { parent }, mode: 'copy'` should work as well.

**Comment by pditommaso** [comment]
let me know if it's fixed on your side as well.

**Comment by heuermh** [comment]
Will do, thank you!
