### ISSUE TITLE
 Not able to use environment modules with nextflow

### ISSUE THREAD

**Issue by lconde-ucl** [nextflow-io/nextflow#850]
Hi,

Our cluster runs SGE and the submission scripts need to start with "#!/bin/bash **-l**" (as a login shell) to ensure, among other things, proper handling of the module command.  

We are trying to use nextflow but it fails to load any module since nextflow writes the scripts starting with just "#/bin/bash". We were wondering if there was an easy way to overwrite or configure this (i.e., add the '**-l**' option) so that we could use environment modules with our cluster? 

Many thanks in advance,
Best,
Lucia

**Comment by pditommaso** [comment]
A possible workaround consist sourcing the env files as it's done by the login shell before the module command is invoked. 

This can be done adding in the `nextflow.config` file the following setting: 

```
process.beforeScript = 'source $HOME/.bashrc'
```
