### ISSUE TITLE
How to output paired-end files from single bam file

### ISSUE THREAD

**Issue by mohammedkhalfan** [nextflow-io/nextflow#851]
Hello,

I was wondering how I can output paired-end files from a single bam file, using picard tools sam2fastq for example. 

I tried something like this:

```
output:
file "${unmapped_sam}.R[1,2].fastq" into unmapped_fastq_ch
```
But it seems like only *.R2.fastq is available in the unmapped_fastq_ch.

How would I output a channel like this? 

Thank you.

**Comment by pditommaso** [comment]
I think curly brackets should do the trick. I mean the following: 

```
output:
file "${unmapped_sam}.R{1,2}.fastq" into unmapped_fastq_ch
```

**Comment by pditommaso** [comment]
Closing because there's no feedback any more. Feel free to comment below if needed.
