### ISSUE TITLE
Pipeline parameters on the command line not processed by 'config' action

### ISSUE THREAD

**Issue by TheRealPJC** [nextflow-io/nextflow#852]
## Bug report 

The 'config' action does not read pipeline parameters given on the command line, but instead gives an error.

### Expected behavior and actual behavior

Nextflow parameters can be injected in the command line with a double dash ('--') like this: 

`nextflow -c <config_file> run <workflow.nf> --my_param my_value`

As a result, the value of params.my_param is set to 'my_value' in the pipeline, overwriting the value if set in <config_file>.

However, when running with the 'config' action (instead of the 'run' action) like this: 

`nextflow -c <config> config <workflow.nf> --my_param my_value`

then an error is given: 

`Unknown option: --my_param=my_value -- Check the available commands and options and syntax with 'help'`

I would expect pipeline parameters given on the command line to constitute part of the config, and hence be incorporated into the config given when using the 'config' action. 

Occurs in Nextflow 0.31.1.4886

**Comment by pditommaso** [comment]
The `config` command is meant to inspect the pipeline config defined in the configuration file(s). Does not support the use of pipeline custom params.

**Comment by TheRealPJC** [comment]
I understand, but I think it would be more useful if the config command did include command line pipeline parameters. My use case is that I want to record the fully reconciled config (i.e. merged from several files, with interpolated environment variables) that pipeline was run with for reproducibility/traceability/diagnostics. It is also useful for running workflows from within workflows.  

As far as I can see, the full config is not available via introspection. Hence to retrieve it, I am running the initial command line command (retrieved via introspection) with the 'run' command replaced by the 'config' command. However, this won't work if custom parameters have been set. Is there a better way of doing this?

**Comment by pditommaso** [comment]
The ability to specify the params on the command line is given to quickly test and run the workflow. 

However the recommended way is to include also the pipeline parameters into the config file, eventually with a different way. This way you can version control and track much better then changes. 

Would not that work in your case?

**Comment by TheRealPJC** [comment]
Not quite. As I mentioned, I want to run workflows from workflows, which currently means running a Nextflow command from within a parent Nextflow process, like this: 

```
 process run_subflow{
  inputs:
  file input_file
  file config_file

  process:
  """
  nextflow -C ${config_file} run my_subflow.nf --subflow_input ${input_file}
  """
}
```
The input to the sub-workflow needs to be set dynamically by the parent process - in which case, using a command line argument _really_ convenient. Of course I could generate a fresh config file containing any dynamic inputs for the subflow process, but that seems like an unnecessary shuffle. 

Of course you could say that this is just a hack which will be redundant once native sub-flows are supported - and I would agree with you. (Is that imminent?) However, I would still argue that command line parameters are rather more useful than the 'quick and dirty' situation you describe, and that as part of the config, they should be emitted by the config command.

**Comment by a-solovyev12** [comment]
Totally agree with @TheRealPJC. I'm running into the same problem with nested workflows, and generating config files for subflows dynamically seems like a very cumbersome option.
