### ISSUE TITLE
K8s task pods are not automatically deleted completion 

### ISSUE THREAD

**Issue by wikiselev** [nextflow-io/nextflow#853]
## Bug report 

On K8s when hitting an error NF kills the pending tasks and finishes the execution without waiting for the running pods to finish.

### Expected behavior and actual behavior

On the LSF cluster, in the case of an error, after killing the pending tasks, NF always waits until all of the running processes are finished. So that after the execution is finished there are no leftovers from NF.

### Steps to reproduce the problem

Run NF on K8s with a pipeline that produces an error after sometime.

### Environment 

* Nextflow version: [0.32.0] (snapshot) 
* Java version: [1.8.0_151]
* Operating system: [Linux]

@micans

**Comment by pditommaso** [comment]
> On the LSF cluster, in the case of an error, after killing the pending tasks, NF always waits until all of the running processes are finished. 

I don't think so, the default behaviour is to stop the execution and all pending/running tasks as soon as an error is detected. The behaviour you are mentioning is achieved using the [finish](https://www.nextflow.io/docs/latest/process.html#errorstrategy) error strategy.

**Comment by wikiselev** [comment]
Hmm, in the documentation it says that with `finish` strategy Nextflow is "waiting the completion of any submitted job". And this is what I meant above, and also what we've seen on LSF. On K8s Nextflow does not wait for this, so that the workflow stops completely, but there are still lots of running pods finishing their stuff.

**Comment by pditommaso** [comment]
Can you provide at least a `.nextflow.log` file ?

**Comment by pditommaso** [comment]
As in previous comment, please try snapshot `0.32.0u1-SNAPSHOT`. If the problem persist please provide the log file.

**Comment by wikiselev** [comment]
Hi Paolo, thanks and sorry for the delay, working on it.

**Comment by pditommaso** [comment]
OK, this is a duplicate of #824 therefore I'm closing this issue.

**Comment by wikiselev** [comment]
Hi Paolo, I think it's different. Here the problem is that the pods are running after the workflow is finished. And in #824 the problem is that Nextflow does not wait until the resources become available. I suppose the log file above was confusing, because it has the "not enough resources" error. But in reality this behaviour does not depend on the error in the workflow. Whatever, the error is the pods will still be running, while Nextflow says the workflow has finished. Hope this is clear enough...

**Comment by pditommaso** [comment]
This and the [comment](https://github.com/nextflow-io/nextflow/issues/685#issuecomment-419429293) on the other issue makes me think that the problem is that for some reason task pods and not deleted independently the workflow execution status. 

By default pods are automatically deleted immediately after each pod is successfully executed. This behaviour can be switched off adding `k8s.cleanup = false` in the config file. 

Unfortunately I'm not able to replicate this issue: 

```
$ kubectl get pods
No resources found.

$ nextflow kuberun hello -v vol-pvc
Pod started: gloomy-gilbert
N E X T F L O W  ~  version 0.32.0u2-SNAPSHOT
Launching `nextflow-io/hello` [gloomy-gilbert] - revision: c9b0ec7286 [master]
[warm up] executor > k8s
[6d/5883d8] Submitted process > sayHello (1)
[1c/1426d5] Submitted process > sayHello (2)
[66/36ba06] Submitted process > sayHello (4)
[c3/b80eb2] Submitted process > sayHello (3)
Bonjour world!
Ciao world!
Hola world!
Hello world!

$ kubectl get pods
NAME             READY     STATUS      RESTARTS   AGE
gloomy-gilbert   0/1       Completed   0          32s
``` 

IMO there's something odd in your configuration. First thing I would check if the same happen with a previous version of NF. 

Second check, use the the version `0.32.0u2-SNAPSHOT` and run the basic `hello` workflow using this command: 

```
nextflow -trace nextflow.k8s kuberun hello -v <your pvc volume>
 ```

Then attach here the `.nextflow.log` file created in the main driver pod.

**Comment by wikiselev** [comment]
Ok, Paolo, first of all we will buy you lots of beers when we are in Barcelona. Second of all, we just discovered the `k8s.cleanup` in our config file set to `false`... So sorry for that, it was purely my fault. I turned it off some time ago and completely forgot about it and never noticed it in the config. Sorry for wasting your time... But it also means there is no problem with NF! Hope you can forgive us.

Also, with `k8s.cleanup = true` it looks like NF kills everything after the error or when the user `Ctrl+c` the pipeline.

We are both crying and laughing at the same time, sorry again...

**Comment by pditommaso** [comment]
I'm starting to think I can open a brewery with all these beers I get promised 😂😂😂

Very happy it's solved!

**Comment by apeltzer** [comment]
Got you covered:

![](https://i.imgur.com/BsvE75X.png )

**Comment by apeltzer** [comment]
Good idea - and with all that free beers for you there is nothing else planned for you in the evening I suppose ;-)
