### ISSUE TITLE
Make docker write as user instead of root

### ISSUE THREAD

**Issue by fmalmeida** [nextflow-io/nextflow#857]
## Question

Hello, I am using nextflow with docker containers and, as default, the outputs are being written as `root:root` what makes the files inaccessible to users without root permissions.

There is a way to configure my nextflow pipeline in order to invoke docker as current user instead of root? Like this command:
```bash
docker run -v /home/dan:/home/dan -u `id -u $USER`:`id -g $USER` IMAGE
```

I would appreciate any help

**Comment by pditommaso** [comment]
Yes, add the following line to your `nextflow.config` file 

```
docker.runOptions = '-u $(id -u):$(id -g)'
```

Note the `'` single quotes. See [also](https://www.nextflow.io/docs/latest/config.html#scope-docker).

**Comment by fmalmeida** [comment]
Thanks for the fast answer. It worked just fine.

**Comment by zichner** [comment]
In case there are file access issues due to the usage of multiple user groups, one can also add all groups of the current user to docker:
```
docker.runOptions = '-u $(id -u):$(id -g) $(g=" $(id -G)"; echo ${g// / --group-add })'
```
