### ISSUE TITLE
CPU usage metrics can be wrongly reported

### ISSUE THREAD

**Issue by zichner** [nextflow-io/nextflow#858]
## Bug report 

Using Nextflow v0.31.1, the CPU usage estimates in the HTML report are much higher than they should (a single core process has 30000 to 40000% CPU usage instead of ~100%).
This is likely related to the changes in #499 (running the same pipeline with Nextflow v0.29.0 resulted in normal CPU usage estimates, ie. ~100%).

The pipeline in question is using a Docker container that is based on `continuumio/miniconda:4.4.10`.

This is a screenshot of the CPU usage report when using **Nextflow v0.31.1**:
![grafik](https://user-images.githubusercontent.com/10066078/45221970-68169280-b2b3-11e8-8d46-ae44c3d96114.png)

When running the exact same pipeline using **Nextflow v0.29.0**, the report looks like this:
![grafik](https://user-images.githubusercontent.com/10066078/45221921-46b5a680-b2b3-11e8-924b-496dda9fdd06.png)

### Environment 

* Nextflow version: 0.31.1 
* Java version: OpenJDK 1.8.0_161
* Operating system: Scientific Linux 7.4

**Comment by pditommaso** [comment]
Could you please include the `.nextflow.log` file for the failing report.

**Comment by zichner** [comment]
Here you go. Thanks.

[.nextflow.log](https://github.com/nextflow-io/nextflow/files/2365468/default.nextflow.log)

**Comment by pditommaso** [comment]
```
     "cpu":{  
         "mean":29064.2,
         "min":115.9,
         "q1":33235.1,
         "q2":35883.6,
         "q3":36935.1,
         "max":39151.3,
         "minLabel":"rawcopy (V41)",
         "maxLabel":"rawcopy (V40)",
         "q1Label":"rawcopy (V43)",
         "q2Label":"rawcopy (V39)",
         "q3Label":"rawcopy (V42)"
      },
      "cpuUsage":{  
         "mean":29064.2,
         "min":115.9,
         "q1":33235.1,
         "q2":35883.6,
         "q3":36935.1,
         "max":39151.3,
         "minLabel":"rawcopy (V41)",
         "maxLabel":"rawcopy (V40)",
         "q1Label":"rawcopy (V43)",
         "q2Label":"rawcopy (V39)",
         "q3Label":"rawcopy (V42)"
      },
```

The data included in the json look the same as it's shown in the chart, therefore the problem should be in the collect metrics process.

**Comment by pditommaso** [comment]
Any chance to have the `.command.trace` files in these directories? 

```
Sep-07 12:31:13.815 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process rawcopy (V41) > jobId: 257745; workDir: /data/snpArrayCnvPipeline_nf/testing/testing20b/work/b3/ebf43b764ffbd8b5f1cba4790b6ec4
Sep-07 12:31:13.877 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process rawcopy (V42) > jobId: 257746; workDir: /data/snpArrayCnvPipeline_nf/testing/testing20b/work/a2/aa8407983681d836b02f9d15582cca
Sep-07 12:31:13.924 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process rawcopy (V43) > jobId: 257747; workDir: /data/snpArrayCnvPipeline_nf/testing/testing20b/work/1b/8b134af0a1b7b8a5f3257e4ef2e35c
Sep-07 12:31:13.971 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process rawcopy (V40) > jobId: 257748; workDir: /data/snpArrayCnvPipeline_nf/testing/testing20b/work/e0/ae509191e36f5118810cce6ca28fa7
Sep-07 12:31:14.020 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process rawcopy (V39) > jobId: 257749; workDir: /data/snpArrayCnvPipeline_nf/testing/testing20b/work/7e/c6cb47d4c88f0063ee0061bef8ca95
Sep-07 12:31:13.815 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process rawcopy (V41) > jobId: 257745; workDir: /data/snpArrayCnvPipeline_nf/testing/testing20b/work/b3/ebf43b764ffbd8b5f1cba4790b6ec4
Sep-07 12:31:13.877 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process rawcopy (V42) > jobId: 257746; workDir: /data/snpArrayCnvPipeline_nf/testing/testing20b/work/a2/aa8407983681d836b02f9d15582cca
Sep-07 12:31:13.924 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process rawcopy (V43) > jobId: 257747; workDir: /data/snpArrayCnvPipeline_nf/testing/testing20b/work/1b/8b134af0a1b7b8a5f3257e4ef2e35c
Sep-07 12:31:13.971 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process rawcopy (V40) > jobId: 257748; workDir: /data/snpArrayCnvPipeline_nf/testing/testing20b/work/e0/ae509191e36f5118810cce6ca28fa7
Sep-07 12:31:14.020 [Task submitter] DEBUG nextflow.executor.GridTaskHandler - [SGE] submitted process rawcopy (V39) > jobId: 257749; workDir: /data/snpArrayCnvPipeline_nf/testing/testing20b/work/7e/c6cb47d4c88f0063ee0061bef8ca95
```

**Comment by zichner** [comment]
b3/ebf4...
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
2 0 1159 16 9120404 8366844 9120404 8384584 505006659 107511968 19585 164 1209166336 45056
1918176
```

a2/aa84...
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
4 0 369351 14 7599104 7370248 7599104 7370248 575974134 178589488 23833 5376 325990912 45056
1886266
```

1b/8b13...
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
4 0 332351 14 7531232 7302372 7531232 7302372 517187615 119791360 20172 851 354466304 45056
1697342
```

e0/ae50...
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
4 0 391513 15 7928940 7700084 7928940 7700084 586860862 188846248 24507 6210 354470400 45056
2002980
```

7e/c6cb...
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
4 0 358836 14 7618260 7389400 7618260 7389400 549094558 151996808 22103 3236 354482688 45056
1832364
```

b3/ebf4...
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
2 0 1159 16 9120404 8366844 9120404 8384584 505006659 107511968 19585 164 1209166336 45056
1918176
```

a2/aa84...
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
4 0 369351 14 7599104 7370248 7599104 7370248 575974134 178589488 23833 5376 325990912 45056
1886266
```

1b/8b13...
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
4 0 332351 14 7531232 7302372 7531232 7302372 517187615 119791360 20172 851 354466304 45056
1697342
```

e0/ae50...
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
4 0 391513 15 7928940 7700084 7928940 7700084 586860862 188846248 24507 6210 354470400 45056
2002980
```

7e/c6cb...
```
pid state %cpu %mem vmem rss peak_vmem peak_rss rchar wchar syscr syscw read_bytes write_bytes
4 0 358836 14 7618260 7389400 7618260 7389400 549094558 151996808 22103 3236 354482688 45056
1832364
```

**Comment by pditommaso** [comment]
There's no `ps` in that container. 

```
$ docker run -it continuumio/miniconda:4.4.10 bash
(base) root@b37fb48d8bac:/# ps
bash: ps: command not found
```

**Comment by zichner** [comment]
The container I used is based on `continuumio/miniconda:4.4.10`, but I added `ps` via `apt-get install procps`.
Sorry for not mentioning this earlier.

**Comment by pditommaso** [comment]
Adding the `ps` tool it works fine. Are you able to isolate the issue in a test case ?

**Comment by zichner** [comment]
Here a few more details which might help to understand what is going on:

In order to identify the potential problem, I printed the following values from the `nxf_pcpu()` function for one of the processes with very high cpu usage values:
```
$pid $cpu_usage $proc_time ${prev_time[pid]:-0} $total_time $prev_total $num_cpus
```

In almost all cases, the values look correct (cpu usage at ~100% for the `pid` of the main process). However, at the very end (a few seconds before the ~30min job finished), there is one process using some cpu that never used cpu before:

```
...
17 0.0 0 0 6311665981 6311637055 56
17 0.0 0 0 6311694868 6311665981 56
17 0.0 0 0 6311723797 6311694868 56
17 33388.3 172248 0 6311752687 6311723797 56
17 0.0 172248 172248 6311781637 6311752687 56
17 0.0 172248 172248 6311810537 6311781637 56
```
This causes the max cpu value to be >30 thousand percent.

It seems that the process causing this is `bash`

**Comment by zichner** [comment]
Here is `/proc/$pid/stat` for the entry with the high cpu estimate:
```
17 (bash) S 7 1 1 0 -1 4202496 693 10241485 0 136 0 0 135039 39577 20 0 1 0 113043182 20180992 417 18446744073709551615 4194304 5242124 140725487006480 140725487005112 140051188633594 0 65536 4 65538 18446744071579430854 0 0 17 25 0 0 0 0 0 7341384 7388228 25477120 140725487013357 140725487013493 140725487013493 140725487013870 0
```

What can be seen is that `cutime` and `cstime` are very high. The reason seems to be that the `bash` process gets assigned all the `utime` and `stime` of all child processes as soon as they are finished.
The main process of the execution finished right before that and had the following proc stats:
```
25 (R) R 17 1 1 0 -1 4202496 10129533 83090 127 4 133116 39467 1472 48 20 0 1 0 113043184 1552498688 339053 18446744073709551615 4194304 4197460 140729800447008 140729800342104 140489285138337 0 0 0 7754 0 0 0 17 3 0 0 2 0 0 6294616 6295268 15581184 140729800449085 140729800449230 140729800449230 140729800450012 0
```
(the `utime` of the main process is almost the same as the `cutime` of the `bash` process; same for `stime` and `cstime`).

So, it seems that `cutime` and `cstime` should not be included into the calculation of cpu usage, especially for the `bash` process executing the `.command.sh`.

**Comment by zichner** [comment]
No, with this I meant coming from `timeout 2m dd if=/dev/zero of=/dev/null || true` in `test2`.

`timeout 2m dd if=/dev/zero of=/dev/null || true` is a child process of `bash .command.sh`. As a consequence, as soon as `timeout 2m ...` is finishes, its `utime` and `stime` get assigned to the `bash` process as `cutime` and `cstime`.

**Comment by pditommaso** [comment]
I see, need to check carefully. If you have chances to propose a patch it's welcome.

**Comment by zichner** [comment]
If I understand the trace functions correctly, NF is "walking" through all child processes of `bash .command.sh` (including child processes of child processes, etc). Therefore, it should not be necessary to include `cutime` and `cstime` in the cpu usage estimation.
So, this line

https://github.com/nextflow-io/nextflow/blob/8bc6c99824c22b6a0e94ecf1f0e61267c3176c25/src/main/groovy/nextflow/executor/BashWrapperBuilder.groovy#L215

should be
```
local proc_time=$(2> /dev/null < /proc/$pid/stat awk '{sum=$14+$15; printf "%.0f",sum}' || echo -n 0)
```
(without `+$16+$17`)

**Comment by pditommaso** [comment]
Interesting point. But if you are right, it could also means that keep that fields it would not be required any more to walk through all child processes, making the function much easier. 

Including the man entries for that fields for convenience: 

```
              (14) utime  %lu
                        Amount of time that this process has been scheduled
                        in user mode, measured in clock ticks (divide by
                        sysconf(_SC_CLK_TCK)).  This includes guest time,
                        guest_time (time spent running a virtual CPU, see
                        below), so that applications that are not aware of
                        the guest time field do not lose that time from
                        their calculations.

              (15) stime  %lu
                        Amount of time that this process has been scheduled
                        in kernel mode, measured in clock ticks (divide by
                        sysconf(_SC_CLK_TCK)).

              (16) cutime  %ld
                        Amount of time that this process's waited-for chil‐
                        dren have been scheduled in user mode, measured in
                        clock ticks (divide by sysconf(_SC_CLK_TCK)).  (See
                        also times(2).)  This includes guest time,
                        cguest_time (time spent running a virtual CPU, see
                        below).

              (17) cstime  %ld
                        Amount of time that this process's waited-for chil‐
                        dren have been scheduled in kernel mode, measured in
                        clock ticks (divide by sysconf(_SC_CLK_TCK)).

```

**Comment by zichner** [comment]
The problem with using `cutime` and `cstime` instead of walking through the child processes would be that `cutime` and `cstime` just get updated once a child process is finished. So, one could only estimate the average cpu usage but would not be able to observe shorter cpu usage peaks.

**Comment by pditommaso** [comment]
Not getting this. The process tree is compute by `nxf_pstat` that is invoked periodically in a while loop in the `nxf_trace` function. Why you say that cutime and cstime just get updated once a child process is finished?

**Comment by zichner** [comment]
Here an attempt of clarification :)

I added the following line to the function `nxf_pcpu()':
```
echo $pid $cpu_usage $proc_time ${prev_time[pid]:-0} $total_time $prev_total $num_cpus `cat /proc/$pid/stat`
```

Here is the output for one job that has the cpu usage problem: 
[cpuUsage.log](https://github.com/nextflow-io/nextflow/files/2375282/cpuUsage.log)

pid 17 is the command `bash .command.sh`
pid 25 is an `R` job (the main task of the pipeline).

As you can see, `cutime` and `cstime` is always 0 for pid 17 until pid 25 is finished. Then, `cutime` and `cstime` of pid 17 suddenly increases which leads to a cpu usage estimate of >30 thousand (line 1565 in the log file).

**Comment by pditommaso** [comment]
Ok, I'm merging this on master.
