### ISSUE TITLE
Define a K8s namespace in the config file

### ISSUE THREAD

**Issue by wikiselev** [nextflow-io/nextflow#861]
Would it be possible to add a namespace parameter to the config file to be able to define a [namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/) for NF pods?

**Comment by pditommaso** [comment]
Yes, [k8s.namespace](https://www.nextflow.io/docs/latest/config.html#config-k8s).

**Comment by wikiselev** [comment]
Oh, cool, looks like the documentation has been updated with new cool features! Many thanks!
