### ISSUE TITLE
A misleading message is shown when pulling a project with a invalid config

### ISSUE THREAD

**Issue by bneron** [nextflow-io/nextflow#863]
## Bug report 

(If you a reporting a bug please follow this template replacing the text between parentheses with the requested information)

### Expected behavior and actual behavior

The feature to pull or run a workflow directly from github doesn't work anymore.
I try this feature last week it worked. But from few days, with the same configuration, same computer, 
same nextflow version, it fail with strange message:  

> ... must contain a the script `main.nf` or the file `nextflow.config`

 but nextflow.config exists.

### Program output 

```
nextflow pull gem-pasteur/Integron_Finder
Checking gem-pasteur/Integron_Finder ...
Not a valid Nextflow project -- The repository `https://github.com/gem-pasteur/Integron_Finder` must contain a the script `main.nf` or the file `nextflow.config`
```

the repository https://github.com/gem-pasteur/Integron_Finder contain nextflow.config script

### Steps to reproduce the problem

```
nextflow pull gem-pasteur/Integron_Finder
Checking gem-pasteur/Integron_Finder ...
Not a valid Nextflow project -- The repository `https://github.com/gem-pasteur/Integron_Finder` must contain a the script `main.nf` or the file `nextflow.config`
```
### Environment 

* Nextflow version: [ 0.29.0 - 0.31.0.4885] 
* Java version: [1.8.0_181]
* Operating system: [Linux]

**Comment by pditommaso** [comment]
When pulling a project NF interprets the `nextflow.config` file and [this line](https://github.com/gem-pasteur/Integron_Finder/blob/dev/nextflow.config#L78-L80) causes it to fail. 

You should not include params check in the config file. However I agree the the error message is confusing.

**Comment by bneron** [comment]
Ok thank you.

I did that, because I want to save the trace, timeline and report files in the results directory.
How I can do this?

**Comment by pditommaso** [comment]
Just set that params to a default value instead of checking if it's been provided eg. `params.replicons = 'foo'`
