### ISSUE TITLE
NO_PROXY env variable should be honoured

### ISSUE THREAD

**Issue by tbugfinder** [nextflow-io/nextflow#864]
## Feature Request
Nextflow should allow setting of NO_PROXY, either in configuration files or by evaluating NO_PROXY environment variables.

### Expected behavior and actual behavior

Patterns within NO_PROXY should not use the proxy server.

### Program output 

N/A

### Steps to reproduce the problem

N/A

### Environment 

* Nextflow version: 0.32
* Java version: 1.8
* Operating system: Linux

**Comment by pditommaso** [comment]
It should be doable setting the `http.nonProxyHosts` property. See [here](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html). 

The NO_PROXY setting should be already in place for the [Capsule subsystem](https://github.com/puniverse/capsule-maven/blob/ae872d02ab189eabb50f093d9b886f3d724b526a/src/main/java/capsule/SystemProxySelector.java#L89-L92).
