### ISSUE TITLE
Option checkIfExists should be applied when a glob pattern does not match any file

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#874]
It would be great if the new `checkIfExists` function could also ensure that glob patterns actually match some files.

**Comment by pditommaso** [comment]
Now it's possible to provide multiple patterns in both `fromPath` and `fromFilePairs`, for example: 

```
Channel.formPath([ '*.fastq', '*.fa' ])
```

What it one pattern match one or more files and the other does not? Should the `checkIfExists` raise an error, what do you think?

**Comment by ewels** [comment]
Yes, I think so.. (nb: your example has a typo: `formPath`).

**Comment by pditommaso** [comment]
I agree. Just uploaded a patch in the latest snapshot `0.32.1-SNAPSHOT`. (yes, it's a typo a new method signature 😄)

**Comment by pditommaso** [comment]
Released with version `18.10.1`.
