### ISSUE TITLE
Option to change hashing behavior

### ISSUE THREAD

**Issue by winni2k** [nextflow-io/nextflow#880]
When prototyping new nextflow pipelines I have run into the problem described [here](https://github.com/nextflow-io/nextflow/issues/211#issue-169698184), where long-running jobs are not cached but re-run for no apparent reason or because I refactored some code in the process definition.  This is great behavior for production, but sometimes I just want nextflow to treat all successfully completed jobs as cached and go ahead and run downstream processes.  

Would it be possible to add an "evil" mode where nextflow reverts to something closer to Snakemake behavior, for example only using timestamps and the returncode file for determining if a process result can be treated as cached?

**Comment by pditommaso** [comment]
Not sure it's a good idea to cheat the caching mechanism. Hopefully once #452 is implemented it should provide a solution to your use case.
