### ISSUE TITLE
nextflow config doesn't work with remote workflows

### ISSUE THREAD

**Issue by ewels** [nextflow-io/nextflow#889]
### Expected behavior and actual behavior

I would expect that running `nextflow config [remote-address]` would run and return the config of that pipeline, in the same way that `nextflow run [remote-address]` runs it.

### Program output 
Nada. No output, stdout or stderr, exit status `0`.

```
$ nextflow config nf-core/hlatyping
$
```

Running `nextflow config [local-path]` works as expected.

### Environment 

* Nextflow version: `nextflow version 0.32.0.4897`
* Java version: 
  ```
  java version "1.8.0_151"
  Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
  Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
  ```
* Operating system: macOS

**Comment by pditommaso** [comment]
It took some time, but finally we have it! 😅

**Comment by ewels** [comment]
Amazing! Thank you! This is going to make life so much easier 🥳
