### ISSUE TITLE
Integration of the NCBI Sequence Read Archive (SRA) into Nextflow

### ISSUE THREAD

**Issue by evanfloden** [nextflow-io/nextflow#89]
From Nature:

> A condition of publication in a Nature journal is that authors are required to make materials, data, code, and associated protocols promptly available to readers without undue qualifications. 

Truly reproducible computational analysis relies on the having the exact same software, computational environment and data available. Nextflow along with Docker fulfills the software and environment requirements yet the data is kept distinct.

It now common practice that DNA and RNA sequencing data must be made available in the NCBI Sequence Read Archive (SRA). To date the SRA contains over 4.3 quadrillion bases (Nov '15).

> Sequence Read Archive (SRA) makes biological sequence data available to the research community to enhance reproducibility and allow for new discoveries by comparing data sets. The SRA stores raw sequencing data and alignment information from high-throughput sequencing platforms, including Roche 454 GS System®, Illumina Genome Analyzer®, Applied Biosystems SOLiD System®, Helicos Heliscope®, Complete Genomics®, and Pacific Biosciences SMRT®.
> http://www.ncbi.nlm.nih.gov/sra

Integration of the SRA into Nextflow could allow users to reference, pull and analyse their or others read data in programmatic manner.

As an example, it would be great if a user of pipeline could specify an SRA Study ID, for example the ID SRP003186 and have the mapping performed exactly as is specified in the study.

The SRA study [SRP003186](http://www.ncbi.nlm.nih.gov/sra/?term=SRP003186) is titled "Identification of fusion genes in breast cancer by paired-end RNA-sequencing" and consists of 7 RNA-seq samples in fastq format. We can see that each individual sample contains the following information about the library used:

> Library:
> Name: FIMM-OK-normbr-1
> Instrument: Illumina Genome Analyzer II
> Strategy: WGS
> Source: TRANSCRIPTOMIC
> Selection: cDNA
> Layout: PAIRED

Taking this and other information such as the reference genome, each samples fastq files could be mapped using the information above as parameters and the downstream analysis performed.

Tools for accessing the SRA are available here: https://github.com/ncbi/ngs

Please leave comments if you have any ideas

**Comment by pditommaso** [comment]
Thanks for that Evan. I'm looking at the [examples](https://github.com/ncbi/ngs/tree/master/ngs-java/examples/examples) in the NGS binding toolkit but it looks there's no api to access a *study* as you are suggesting. 

It seems that the API entry point is an [ReadCollection](https://github.com/ncbi/ngs/blob/master/ngs-java/ngs/ReadCollection.java) object, that you will get specifying an accession number. 

Could it be useful for what you are proposing? 

cc @emi80

**Comment by kwrodarmer** [comment]
I mentioned in the NGS thread that the NGS API was developed with the purpose of being applicable to other archives as well as the SRA. As such, we took pains to avoid putting in requirements that weren't universally applicable.

At this time, we are putting together the NCBI-specific extensions to the NGS API which will give access to the unique features of SRA, and will include resolving study accessions, accessing coverages graphs built into SRA objects, etc.

**Comment by pditommaso** [comment]
Thanks for commenting on this. We will begin first a first integration with the current NGS API to access reads from SRA. 

If at some point will be possible to retrieve other features such as studies, coverage graphs, etc. that would be great.

**Comment by durbrow** [comment]
If your interested in resolving SRP's (and SRX's and possibly other things) to SRA runs, here is some python code to do it. It uses NCBI's eutils web service to perform the lookup. Look at the SRARunList function, in particular.
https://github.com/durbrow/efetch.py/blob/master/efetch.py

**Comment by evanfloden** [comment]
Snakemake has the concept of 'remotes' of which the [NCBI](https://bitbucket.org/snakemake/snakemake/src/423ef135d2304e2d2f327bf3bb50378bee084b31/snakemake/remote/NCBI.py?at=master&fileviewer=file-view-default) is one.

A similar approach would be very useful here.

**Comment by pditommaso** [comment]
This is a good topic for the NF hack next month.

**Comment by pditommaso** [comment]
Related http://samtools.github.io/hts-specs/htsget.html

**Comment by wikiselev** [comment]
We would really like to be involved in this! We have just started exploring different options and I found this, really cool!

**Comment by pditommaso** [comment]
Do you mean htsget or SRA archive in general?

**Comment by wikiselev** [comment]
`SRA` at the moment. But `htsget` is also on my radar.

**Comment by wikiselev** [comment]
Very nice, thanks so much for your effort Lukas!

**Comment by pditommaso** [comment]
This looks cool! I'll give a try at my earliest convenience.

**Comment by pditommaso** [comment]
Closing this in favour of #1070
