### ISSUE TITLE
Rename weblog `runStatus` to `event` 

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#892]
The weblog `runStatus` attribute name is inconsistent because it does not represent the execution status but the weblog event type, therefore it should deprecated and replaced by an attribute named `event`.

**Comment by pditommaso** [comment]
@sven1103 thoughts about this? do you agree?

**Comment by sven1103** [comment]
@pditommaso , yes, this makes sense indeed!

**Comment by pditommaso** [comment]
Released with version `18.10.1`.
