### ISSUE TITLE
storeDir and privileges

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#893]
## Bug report 

I found a strange behaviour when using storeDir. I got this error:
```
[21/950f45] NOTE: Cannot access folder: '/nfs/software/bi/biocore_tools/git/nextflow/Qcloud/blastdb' -- Error is ignored
```
### Expected behavior and actual behavior
I fixed this by using afterScript and changing the mode to 777 but the privileges of the stored folder are actually the same than work folder. So I don't know why is complaining.

**Comment by pditommaso** [comment]
I guess this is some kind of mess in the shared file system or made by the container mount. Not enough evidence to replicate it.
