### ISSUE TITLE
Unable to use variable with label directive 

### ISSUE THREAD

**Issue by rsuchecki** [nextflow-io/nextflow#894]
## Bug report 

Given this example:

```
bars = ['bar1', 'bar2']
process foo {
  tag "${bar}"
  label "${bar}"

  input:
    each bar from bars

  exec:
    println ("Current: "+bar)
}
```

### Expected behavior and actual behavior

The value of the variable `bar` is correctly parsed via the `tag` directive but  an error is triggered when using the same variable with the `label` directive.

### Program output 

```
nextflow run labelbug.nf
N E X T F L O W  ~  version 0.32.0
Launching `labelbug.nf` [elated_blackwell] - revision: 4f9c354858
ERROR ~ No such variable: bar

 -- Check script 'labelbug.nf' at line: 4 or see '.nextflow.log' file for more details
```
[.nextflow.log](https://github.com/nextflow-io/nextflow/files/2464139/nextflow.log)

### Steps to reproduce the problem

Execute the provided minimal example:

`nextflow run labelbug.nf`

[gist: labelbug.nf](https://gist.github.com/rsuchecki/23a080b7181ab8bbe0ac6c42d767703e) 

### Environment 

* Nextflow version: 0.32.0
* Java version: OpenJDK 1.8.0_171-b11
* Operating system: Linux

**Comment by pditommaso** [comment]
I think I've got the problem, but I'm wondering what's added value of dynamic label? What's your use case ?

**Comment by rsuchecki** [comment]
In my case this goes hand-in-hand with either using templates or conditional execution of scripts. Depending also on execution profile,  the label allows me to select an appropriate container or module(s) using `withLabel`. This can be useful if we want to either select between tools or use multiple alternative tools to do a job (e.g. for tool evaluation).

Here is an example:

```
tools = ['biokanga','dart','hisat2'] 

process indexGenerator {
   label("${tool}")

   input:
     file ref
     each tool from tools

   output:
     set val(meta), file("${ref}*") into indices

   script:
     meta = [tool: "${tool}", ref: "${ref}"]
     template "${tool}_index.sh" 
}
```

Corresponding container config:
```
process {
    withLabel: biokanga {
      container = 'rsuchecki/biokanga:4.3.9'
    }
    withLabel: dart {
      container = 'rsuchecki/dart:1.3.1'
    }
    withLabel: hisat2 {
      container = 'rsuchecki/hisat2:2.0.5'
    }
}
```

With say, a dozen tools, the main script would be much more concise and would avoid a lot of repetition. Also, particularly  for someone not familiar with NF inserting an additional tool would be much easier, ie. just adding a template, without the need of declaring and operating on additional channels per each new tool.  

I can imagine this flexibility being relevant for other process settings if you want to have them in config files, separated from the process body, especially that, as in my case, they may also depend on execution profile.

**Comment by rsuchecki** [comment]
Any thoughts @pditommaso? Wondering if this is something i could (or should) be aiming for when designing pipelines? Does that look like a major work or a quick fix?

**Comment by pditommaso** [comment]
Yes, your use case makes sense. However I realised the underlying logical issue. What is happening is that to evaluate the dynamic expression it's required to resolve the task input context ie. the task configuration context. As such it requires to resolve the actual task configuration via the annotation. 

Basically it's circular dependency, to resolve the label value it needs the actual label. 

I need to double check if some kind of partial evaluation is possible, but surely it's not an easy patch.

**Comment by rsuchecki** [comment]
Thanks again @pditommaso. Here is a work-around for my use case - may be of interest to some who stumble here. Could be simpler but keeping compatible with label-based config in the hope for a future fix ;-)

```
process indexGenerator {
   label 'index' //still using (static) labels for e.g. mem/cpu requirements spec
   container { this.config.process.get("withLabel:${tool}" as String).get("container") } 
```

**Comment by stoneg64** [comment]
I am having a similar issue trying to pass queue name to a process using the "uge" executor.  Are there any known work arounds to make that directive configurable?

**Comment by DaGaMs** [comment]
This issue is becoming more pressing with DSL2, I think. I now have several "generic" processes, which I need to assign labels to dynamically. For example `alignReads` might require `label: "long"` when I'm aligning against the human genome but `label: "short"` when aligning some bacterial genome. How to solve that with DSL2 modules?

**Comment by jinmingda** [comment]
@DaGaMs This might be a little bit late but I got stumbled on the same problem when I was using DSL2. Since it's unlikely to assign a "dynamic" label directive under the current release as per the anwser above, I realize it's still possible to assign the resources associated with a label dynamically. Here's my solution.

First, use a process-specific label in your DSL2 module. For example in `process/bowtie2/bowtie2.nf`:
```nextflow
process Bowtie2 {
    ...
    label "bowtie2"
    ...
}
```
Then configure the label resource for long and short task in separate config files such as `process/bowtie2/long.config` and `process/bowtie2/short.config` 
```nextflow
process {
  withLabel:bowtie2 {
    time = 12.h
  }
}
```
```nextflow
process {
  withLabel:bowtie2 {
    time = 2.h
  }
}
```

Finally, load the config file selectively in your `nextflow.config`.
```nextflow
if ( params.genome == 'hg19' ) {
  includeConfig "process/bowtie2/long.config"
} else {
  includeConfig "process/bowtie2/short.config"
}
```

Done. The only thing is the dynamic logic will reside in `nextflow.config`. I feel this probably makes it less modular and elegant. So it would still be nice to have a native way to support dynamic label.

**Comment by pditommaso** [comment]
Nice, always favour conditional expressions over control statements, eg 

```
includeConfig (params.genome == 'hg19' ? "process/bowtie2/long.config" : "process/bowtie2/short.config")
```

**Comment by ewels** [comment]
@pditommaso issue is closed as stale, but maybe should be open still?

**Comment by pditommaso** [comment]
The problem with this there's a catch-22 situation with dynamic labels. See https://github.com/nextflow-io/nextflow/issues/894#issuecomment-803989418

**Comment by mjhipp** [comment]
> I need to double check if some kind of partial evaluation is possible, but surely it's not an easy patch.

@pditommaso if you could point me towards the code in question I can see if someone on my team can help find a solution? This type of pattern would be very useful to me going forward:

```
process printlabel {
  label "${ file1.size() < 1000 ? 'small' : 'large' }"

  input:
    path file1

  script:
    log.info("Label: $task.label")
    log.info("File size: ${file1.size()}")
    "echo 'File Size: ${file1.size()}, Label: $task.label'"
}
```

I would like to be able to have the label defined in the process based on the file size, then use my `profiles` params section to define what resources/AWS batch queue etc. to used based on label.

**Comment by pditommaso** [comment]
All task directives are managed by [TaskConfig](https://github.com/nextflow-io/nextflow/blob/914d7cb40bf58ff977717cd137352e7dfe97dbdb/modules/nextflow/src/main/groovy/nextflow/processor/TaskConfig.groovy#L42). However the main problem has been described above https://github.com/nextflow-io/nextflow/issues/894#issuecomment-429737996

**Comment by pditommaso** [comment]
Worth mentioning that the dynamic label resolution is not possible for variable defined in the process scope ie. inputs and reflective `task` attributes. 

However it works when using variable in the global scope e.g. `params`. For example:

```
params.label = 'foo'

process foo {
  debug true
  label "${params.label}"

  exec:
    println "Current: $task.label"
}

workflow { foo() }
```
 

```
» nextflow run sandbox/dyn-lab.nf 
N E X T F L O W  ~  version 22.04.0
Launching `sandbox/dyn-lab.nf` [jovial_mandelbrot] DSL2 - revision: 4a3e86326e
executor >  local (1)
[b8/2a86de] process > foo [100%] 1 of 1 ✔
Current: [foo]

» nextflow run sandbox/dyn-lab.nf --label bar
N E X T F L O W  ~  version 22.04.0
Launching `sandbox/dyn-lab.nf` [nasty_saha] DSL2 - revision: 4a3e86326e
executor >  local (1)
[95/bd97d1] process > foo [100%] 1 of 1 ✔
Current: [bar]
```

**Comment by MikeKroell** [comment]
This would be helpful in our environment as well. We want to have a process check the size of an S3 bucket and choose resources based on the size of the inputs.
