### ISSUE TITLE
New qualifier for getting the content of file(s) 

### ISSUE THREAD

**Issue by lucacozzuto** [nextflow-io/nextflow#896]
Hi,
sometimes in pipelines you can output more parameters that are then required to other steps as command line inputs. So a way to simplify the code could be to have a qualifier that instead of getting the file name / pointer will extract the file content.

Here an example:

```
process parseAfile {

    input:
    file(filename) from files

    output:
    set content("param1.txt"), content("param2.txt") into params2beused

    script:
    """
        parse.py ${filename} > param1.txt
        parse2.py ${filename} > param2.txt
    """
}

```

**Comment by pditommaso** [comment]
Implementing such language extension is quite painful and the usage scope is limited. Above all, the same can be easily done using just `file` and readily the file content with a map. 

Sorry, it's a -1.

**Comment by lucacozzuto** [comment]
Well, I imagine there are other priorities :) however you cannot imagine how many times you face the fact that an output of a process becomes a parameter in the command line of another process.
