### ISSUE TITLE
Singularity 3.0 Support

### ISSUE THREAD

**Issue by apeltzer** [nextflow-io/nextflow#897]
## Bug report 

Out of curiosity, I installed Singularity v3.0.0 which just came out for testing purposes. There are some command that switched behaviour which I'm going to list here for further reference.

### Expected behavior and actual behavior

`singularity pull` should behave similar to before and do this:

```
singularity pull --name test.sif docker://nfcore/rnaseq 
```
(which should create the image as `test.sif`or whatever you call it). This is what nextflow uses to my knowledge to fetch an image. 

However, this happens:
``` 
singularity pull --name test.sif docker://nfcore/rnaseq 
Error: unknown flag: --name
Usage:
  singularity [global options...] pull [pull options...] <URI>
```

### Steps to reproduce the problem

Install Singularity 3.0.0, then pull any image from `shub://` or `docker://` urls. 

### Environment 

* Nextflow version: 0.32.0
* Java version: 11
* Operating system: Archlinux x64

For reference this is the entire help function of the `pull`command:

``` 
singularity pull -h
Pull a container from a URI

Usage:
  singularity pull [pull options...] <URI>

Description:
  The 'pull' command allows you to download or build a container from a given
  URI.  Supported URIs include:

  library: Pull an image from the currently configured library
      library://[user[collection/[container[:tag]]]]

  docker: Pull an image from Docker Hub
      docker://user/image:tag
    
  shub: Pull an image from Singularity Hub to CWD
      shub://user/image:tag

Options:
  -F, --force            overwrite an image file if it exists
  -h, --help             help for pull
      --library string   the library to pull from (default
                         "https://library.sylabs.io")


Examples:
  From Sylabs cloud library
  $ singularity pull library://alpine:latest

  From Docker
  $ singularity pull docker://tensorflow/tensorflow:latest

  From Shub
  $ singularity pull shub://vsoch/singularity-images


For additional help or support, please visit https://www.sylabs.io/docs/

```

**Comment by pditommaso** [comment]
You are [too slow](https://github.com/sylabs/singularity/issues/2217)  😂

**Comment by apeltzer** [comment]
Okay, just wanted to let you know :-)

**Comment by pditommaso** [comment]
Let's keep it open, it may require some changes on our side if they don't restore the `--name` option.

**Comment by pditommaso** [comment]
See also https://github.com/sylabs/singularity/issues/2214,

**Comment by pditommaso** [comment]
This is going to be fixed by next Singularity release, see sylabs/singularity#2214.
