### ISSUE TITLE
iRods integration

### ISSUE THREAD

**Issue by wikiselev** [nextflow-io/nextflow#900]
[iRods](https://irods.org/) is an open source data management solution and I think is used in many places including Sanger. However, the database schema in iRods looks fully customisable and therefore will be different in different places. For example, this is our current irods script: https://github.com/cellgeni/rnaseq-noqc/blob/master/bin/irods.sh

We tried to imagine how this can be integrated into NF in the most general way, but I think we failed... Snakemake allows one to work on iRods files (https://snakemake.readthedocs.io/en/stable/snakefiles/remote_files.html#irods). However, their method is limited to the case when all of your files are located in the same directory, which is not always the case...

Any thoughts and suggestions are welcome.

**Comment by pditommaso** [comment]
Could you provide a more detailed examples in term of command line inputs and outputs. I need to understand exactly what option do you specify and what the command executed returns. 

> However, their method is limited to the case when all of your files are located in the same directory, which is not always the case

Provided also an example for the complex scenario you are mentioning referring to.

**Comment by micans** [comment]
In our case we access the storage back-end with a meta-data front-end that is an Oracle database. I assume that this is a custom set-up, although the interface (`imeta`) is a generic IRODS interface. We use `imeta`, that gets translated to Oracle, and after that things happen in the bowels of IRODS. From our pipeline, these are the lines extracted from scripts where we access irods:
```
# from https://raw.githubusercontent.com/cellgeni/utils/master/myrods.sh
# we use slightly different scripts in our pipeline, but with the same access patterns.
imeta ls -d $d 
imeta qu -z seq -d $part_manualqc id_run = $runid and lane = $laneid and target = 1
imeta qu -z seq -d $part_librarytype $part_studyid sample = $sampleid and $part_manualqc target = 1
imeta qu -z seq -d $part_librarytype $part_manualqc $part_studyid sample = $sampleid and target = 1
```
Those imeta invocations get translated into Oracle queries. There are for us two main modes, one is sampleID + studyID, the other is runID + laneID. However, at some point we experimented with additional selectors as you can see. To me, the current situation is pretty good -- our IRODs access patterns are nicely isolated with a single script, a docker file, and a NF process. I thought that perhaps SRA could be handled similarly -- to be honest, a somewhat general-purpose script would already be gold-dust. I looked at the Snakemake Genbank remote (https://snakemake.readthedocs.io/en/stable/snakefiles/remote_files.html) and the examples are quite finicky and far away from our goal (*Create a pipeline for automated downloading and procession of GEO datasets using SRA ids*). In our ticketing system we have a link to this repository https://github.com/mruffalo/sc-rna-seq-pipeline, it has code for dowloading from SRA, but I have not yet had the time to look. Sorry, this is a bit of a potpourri of information, let me know if you want more/different.

**Comment by pditommaso** [comment]
It would interesting to know if iRods provides an API that could be integrated to replace `imeta` command. Any clue about that?

**Comment by micans** [comment]
No clue .. I've searched the web, and find links like these:
https://irods.org/2015/12/update-irods-client-interfaces/
https://github.com/irods/python-irodsclient
Looking at the last one, 'currently supported' is a very long list. IRODs is quite a general storage mechanism, with many facilities; my hunch (based on what I know from Sanger) is that individual organisations all have different setups with customised access interfaces. I think the fruit is all high up in the tree, but I'm not an expert. I'll ask the local expert we have here.

**Comment by pditommaso** [comment]
Just realised that the proper way to handle this would be through a virtual file system that would allow to access irods like any other file eg. `irods://path/to/your/file.fastq`

**Comment by pditommaso** [comment]
Tricky, but I expect that query could be expressed on the URI eg. `irods://server/some/path?sampleId=xxx` or also a virtual path eg. `irods://server/some/path/samples/<SAMPLE-ID>/*`.

Also have you ever took in consideration to access it through a FUSE mount ?

**Comment by pditommaso** [comment]
BTW [Jargon](https://github.com/DICE-UNC/jargon) is the Java client for IRods.
