### ISSUE TITLE
Improve the error message when singularity pull fails

### ISSUE THREAD

**Issue by sjackman** [nextflow-io/nextflow#902]
The command `singularity pull docker://flowcraft/spades:3.12.0-1` is reproducibly failing for some reason with the older version Singularity 2.4 installed on my host system (it later succeeded with Singularity 2.6). When running Nextflow, I don't see an error message that `singularity pull` failed. Instead, I later on see an error message `ERROR  : Image path doesn't exists` (which has a typo, `exists` should be `exist`). This particular error message would be improved by saying which image file doesn't exist. Even better though, the error message should be displayed earlier when `singularity pull` fails.

#### Observed

```
Workflow execution stopped with the following message:
  ERROR  : Image path doesn't exists
ABORT  : Retval = 255
```

#### Expected

```
Workflow execution stopped with the following message:
  ERROR  : `singularity pull docker://flowcraft/spades:3.12.0-1` failed with the following error message
gzip: /projects/orca/sjackman/singularity/docker/sha256:722b371dbf4f65209e4fa20a230262cb82d3f304b8cd86fbcbda079d3f8364fd.tar.gz: not in gzip format
ABORT  : Retval = 255
```

### Program output 

```
Workflow execution stopped with the following message:
  ERROR  : Image path doesn't exists
ABORT  : Retval = 255
```

### Steps to reproduce the problem

Attempt to use the image `docker://flowcraft/spades:3.12.0-1` with Singularity 2.4.

### Environment 

* Nextflow version: 0.32.0.4897
* Java version: 1.8.0_151
* Operating system: CentOS Linux release 7.2.1511 (Core)
* Singularity: 2.4

**Comment by pditommaso** [comment]
This is essentially a bug in Singularity 2.4 that ignore the `--name` option. See #498. Not so easy to detected on NF side. It should be checked the singularity version, etc. Also considering that's an old version, don't think it's work to add a complicated logic to handle that.

**Comment by sjackman** [comment]
I've asked our systems group to update Singularity to version 3.0. Does Nextflow work with Singularity 3.0?

> Not so easy to detected on NF side.

Can Nextflow run `singularity --version` and fail when it's less than 2.4.1?

**Comment by pditommaso** [comment]
Singularity 3.0 has a similar issue! #897

You should use older or newer but not 2.4 or 3.0. 

> Can Nextflow run singularity --version and fail when it's less than 2.4.1?

I understand that the error message is misleading, but I don't think NF should take care of bugged old versions.

**Comment by sjackman** [comment]
Ergh. Shame that they added an additional positional parameter to `singualrity pull` and broke the backward compatibility of the interface. Glad to hear they've added `--name` back though. I'll patiently wait for Singularity 3.0.1.

**Comment by sjackman** [comment]
> I don't think NF should take care of bugged old versions.

Checking that the requirements/dependencies of a tool are met and failing when they're not is good sense. It prevents unnecessary bug reports being opened by confused users. Ultimately your call though.

**Comment by sjackman** [comment]
I lost track of the original reason for opening this issue. `singularity pull` was exiting with a non-zero exit status, but Nextflow doesn't appear to be checking the exit status of `singularity pull`. Nextflow didn't fail until later when it attempted to run the image, and the image didn't exist.

The error message of `signularity pull` is `gzip: /projects/orca/sjackman/singularity/docker/sha256:722b371dbf4f65209e4fa20a230262cb82d3f304b8cd86fbcbda079d3f8364fd.tar.gz: not in gzip format`
I believe this Singularity pull issue is a different than the `--name` issue that you mentioned.

**Comment by pditommaso** [comment]
Yes, [it does](https://github.com/nextflow-io/nextflow/blob/835b990/src/main/groovy/nextflow/container/SingularityCache.groovy#L235-L236). Note are two different issues #498 and #897.

**Comment by sjackman** [comment]
I must have gotten it wrong then. My best guess is that `singularity pull` was returning a 0 exit status, despite the error message. Our systems group has upgraded Singularity to 2.6.0 to resolve this issue, so I'm not able to reproduce the issue now. Thanks for your help troubleshooting.
