### ISSUE TITLE
Thread tcp-disco-srvr-nextflow is terminated unexpectedly.

### ISSUE THREAD

**Issue by nephantes** [nextflow-io/nextflow#909]
## Bug report 
I started a cluster with a master and a worker node. Cluster is terminated unexpectedly.
The image I used derived from your example image.

### Expected behavior and actual behavior
It shouldn't be terminated.

### Program output 
Logs from master node;
https://galaxyweb.umassmed.edu/logs/test6/master/.nextflow.log
Other logs;
https://galaxyweb.umassmed.edu/logs/test6/master/

Logs from worker node;
https://galaxyweb.umassmed.edu/logs/test6/worker/.node-nextflow.log
Other logs;
https://galaxyweb.umassmed.edu/logs/test6/worker/

### Steps to reproduce the problem
Create 2 nodes cluster with ami-0a60f8f1463a043b4 on eu-west1b.
When I run the pipeline below with more than 20 fastq pairs. I got this error in 2 nodes cluster.
https://galaxyweb.umassmed.edu/logs/test6/test/

### Environment   

* Nextflow version: nextflow version 0.32.0.4897
* Java version:  openjdk version "1.8.0_181"
* Operating system: Amazon Linux AMI release 2018.03

**Comment by pditommaso** [comment]
It looks an Ignite bug. https://issues.apache.org/jira/browse/IGNITE-8751

You may want to try to downgrade to NF 0.31.1 that uses Ignite 2.4.

**Comment by nephantes** [comment]
Sorry, I couldn't find a way to downgrade nextflow. Do you have a link about how to downgrade it? When I downgrade it do I need to do anything about ignite? or it is coming with nextflow.
Thanks

**Comment by nephantes** [comment]
It looks like previous version is working. I didn't get the same error.

**Comment by nephantes** [comment]
Hi Paolo,
This issue looks like resolved. 
https://issues.apache.org/jira/browse/IGNITE-8751
Which nextflow version, we can start using ignites resolved version.
Thanks

**Comment by pditommaso** [comment]
Yes, but it has not yet [released](https://search.maven.org/search?q=ignite). After that it will include in the first version according the new nextflow release [schema](https://www.nextflow.io/blog/2018/goodbye-zero-hello-apache.html). Alternatively you can rollback to an older NF release which uses a previous Ignite version.

**Comment by pditommaso** [comment]
Reverted to Ignite 2.4.

**Comment by pditommaso** [comment]
Included in version `18.12.0-edge`.
