### ISSUE TITLE
PBSPro clusterOptions / additional resources directive

### ISSUE THREAD

**Issue by stekaz** [nextflow-io/nextflow#911]
We have a cluster running PBS Pro where we are able to specify custom resources. Some examples include:

```
$ echo "sleep 30" | qsub -N TEST0 -l select=1:ncpus=1:mem=1mb:host=hpcnode001 -l walltime=1:00:00
$ echo "sleep 30" | qsub -N TEST1 -l select=1:ncpus=1:mem=1mb:chip=Intel -l walltime=1:00:00
$ echo "sleep 30" | qsub -N TEST2 -l select=1:ncpus=1:mem=1mb:ngpus=256 -l walltime=1:00:00
```

However, the `select` statement conflicts with additional resources (other than the `walltime` resource/directive, for some reason). This prevents us from using a `clusterOptions = '-l host=hpcnode001'` directive. For example:

```
$ echo "sleep 30" | qsub -N TEST3 -l select=1:ncpus=1:mem=1mb -l walltime=1:00:00 -l host=hpcnode001
qsub: "-lresource=" cannot be used with "select" or "place", resource is: host
```

Are there any provisions for use cases like this? It would be really great if there was some option that could append a list of additional resources to the `select` statement:

https://github.com/nextflow-io/nextflow/blob/master/src/main/groovy/nextflow/executor/PbsProExecutor.groovy#L64

**Comment by stekaz** [comment]
Thanks Paolo, it looks like that will work only with the full resource request:

```
$ echo "sleep 30" | qsub -N TEST4 -l select=1:ncpus=1:mem=1mb -l walltime=1:00:00 -l select=1:host=hpcnode001
qsub: Job has no memory requested!!! Please submit a job requesting memory...
$ echo "sleep 30" | qsub -N TEST5 -l select=1:ncpus=1:mem=1mb -l walltime=1:00:00 -l select=1:host=hpcnode001:ncpus=2:mem=2mb
26374620.hpcpbs
$ qstat -1n | grep "TEST5"
26374620.hpcpbs stekaz test    TEST5       48844   1   2    2mb 01:00 R 00:00 hpcnode001/0*2
```

Interestingly, this also appears to work as expected:

```
$ echo "sleep 30" | qsub -N TEST6 -l ncpus=2 -l mem=1mb -l walltime=01:00:00 -l host=hpcnode002
26381752.hpcpbs
$ qstat -1n | grep "TEST"
26381752.hpcpbs stekaz test    TEST6       54042   1   2    1mb 01:00 R 00:00 hpcnode002/0*2
```

It looks like it would fit more closely with the PbsExecutor, but the `nodes=1:ppn=` looks like a deal breaker:

```
$ echo "sleep 30" | qsub -N TEST7 -l nodes=1:ppn=3 -l mem=1mb -l walltime=01:00:00 -l host=hpcnode003
26381901.hpcpbs02
$ qstat -1n | grep "TEST"
26381901.hpcpbs stekaz test    TEST7      110351   1   3 1024kb 01:00 R 00:00 hpcnode041/13*3
```

I.e. wrong host

**Comment by stekaz** [comment]
Oh I'm happy for `clusterOptions` to remain a passthrough config setting. This is certainly very useful. I just meant that it would be really nice if there was an extra option (I think this is what you mean by an `affinity` directive, but I just called it 'resourceOptions') then we would have another way of altering the resource request in PBS Pro, at least. It sounds like this might be useful for some of the other schedulers too. I can have a look at adding something like this in the future, but for now I think I will stick with passing in the full `select` string.

**Comment by IdoBar** [comment]
I encountered another behaviour related to this issue - when multiple competing directives are provided, the first one will take effect, so clusterOptions should be appended to the beginning of the PBS directives string, not the end of it (should go at L.47 and not L.75 in [PbsProExecutor.groovy](https://github.com/nextflow-io/nextflow/blob/28a579a90903aa171a9f3eca6d71b17624c6e635/modules/nextflow/src/main/groovy/nextflow/executor/PbsProExecutor.groovy#L75)).
I'll make a PR and test functionality soon.
