### ISSUE TITLE
Warn on re-creation of channel

### ISSUE THREAD

**Issue by winni2k** [nextflow-io/nextflow#915]
When I run this code:
```
q1 = Channel.from([0, 'a'])
q2 = Channel.from([1, 'b'])
q2 = Channel.create() // erroneous re-definition of channel

q1.view().join(q2).view().subscribe { println it }
```

My pipeline hangs:
```
nextflow run test.nf
N E X T F L O W  ~  version 18.10.1
Launching `test.nf` [crazy_shirley] - revision: 93403eb167
0
a
```

I think I just spent three hours troubleshooting a hanging pipeline until I finally figured out that I was redefining one of my channels.  Is there any situation in which one would want to redefine an existing channel? Is there a way for nextflow to emit a warning when this is done?

**Comment by pditommaso** [comment]
This is the same as overriding an existing variable. I  don't think NF should give a special warning for that.

**Comment by winni2k** [comment]
I see where you are coming from, but NF does other things to prevent user error. The requirement that every queue have at most one incoming and one outgoing connecting comes to mind.

Of course, if I am the only new user to have this problem, then this clearly is a silly idea...

**Comment by winni2k** [comment]
Also, @pditommaso, you have not answered my question:

> Is there any situation in which one would want to redefine an existing channel?

**Comment by pditommaso** [comment]
> you have not answered my question 

Sorry! :) Yes, in Sarek they do a lot. Look [here](https://github.com/SciLifeLab/Sarek/blob/master/main.nf#L220-L224).

**Comment by winni2k** [comment]
Thanks :)
