### ISSUE TITLE
Changing the path of .command.sh in .command.run

### ISSUE THREAD

**Issue by tsnowlan** [nextflow-io/nextflow#917]
We are trying to use Singularity with Nextflow on a slurm cluster and are running into some issues.

The working path on the host system is long, ugly and dynamic, so we cannot ensure they exist in the singularity image beforehand and the cluster does not support using overlay. AutoMounts are disabled for this reason. So we're trying to mount it to a nice generic `/data`, but then execution then fails because `.command.run` cannot find `/long/ugly/path/.../.command.sh` instead of `/data/work/.../.command.sh`.

Is there a way to ensure that `.command.run` specifies the internal path? Is the full, external path to `.command.sh` _required_ to also be available inside the image?

**Comment by pditommaso** [comment]
You need to instruct NF to use `/data/` the create each task work dir using the `-w` command line option e.g.

```
nextflow run <something> -w /data/work
```

**Comment by tsnowlan** [comment]
Ah, great. Is it possible to set that on a per-process level? The `.nf` file has a number of processes, but only one currently uses Singularity that needs the work path changed.

**Comment by pditommaso** [comment]
Nope. The work dir is the same for all processes.

**Comment by tsnowlan** [comment]
Okay. Thanks for info. :+1:
