### ISSUE TITLE
Allow a single process to use all available CPUs

### ISSUE THREAD

**Issue by ppericard** [nextflow-io/nextflow#918]
Right now, by default NF will try to run as many parallel processes as there are available CPUs.
In some use cases, a pipeline will have a bottleneck with a single task that needs to be run before all following tasks (e.g. indexing a genome before mapping several sequencing files). In that case, by default this process will be using a single CPU.
It is possible to set the number of CPUs of such a task by using the _cpus_ directive but this value will be hardcoded, either in the process code, or in a configuration file.

Would it be possible to have a new way to automatically give to a process all the available CPUs ?
Something along the lines of:
```
process foo {
    cpus $maxAvailableCPUs

    script:
    """
    index_build --threads $cpus
    """
}
```

Of course, those CPUs would be taken from the pool of CPUs available to NF which wouldn't be able to run any more parallel process in the meantime.

**Comment by rsuchecki** [comment]
I think this can only be relevant when using a local executor 


```
process foo {
    cpus  config.poolSize

    script:
    """
    index_build --threads $cpus
    """
}
```

**Comment by ppericard** [comment]
@rsuchecki I think you're right, but maybe there are more use cases than most people would think.
I'm currently running analysis on cloud VMs, which means that all my runs are using the local executor. And in a cloud context it is common to use different sizes of VM, because of the ressources available at that moment, or because the input data is bigger or smaller. 
I could change the number of cpus available in the config file for each VM, but a more generic solution would be to set the number of CPUs in the config file so that it uses the max number of CPUs available.

**Comment by rsuchecki** [comment]
I'd be interested to see if there are other use cases @ppericard, to summarise at the risk of repeating myself: 

* The concept of `maxAvailableCPUs` works for local executor and the number of available (logical) CPUs can be obtained through `config.poolSize` which I believe comes from `Runtime.runtime.availableProcessors()`. You should be able to set that in a config file e.g. `process.cpus = Runtime.runtime.availableProcessors()` just use [process selectors](https://www.nextflow.io/docs/latest/config.html?highlight=selectors#process-selectors)
to be more specific about the process. 

* When using a scheduler such as SLURM you request a set number of CPUs, or are allocated some default value, so `cpus` is already known and set for a process. In this context, `Runtime.runtime.availableProcessors()` **is not** relevant.

**Comment by ppericard** [comment]
@rsuchecki thanks for the summary, now I understand better your point. Repeating yourself was not lost on me ;-)
So if I understand correctly, I can already use `config.poolSize` in a config file ? And this would be the _best practice_ way to do it in Nextflow ?
I was aware of `Runtime.runtime.availableProcessors()` but this didn't feel very Nextflow-ish.
And of course, this whole argument is null and void when using outside schedulers.

**Comment by rsuchecki** [comment]
Glad it helped @ppericard :-) . 

As far as I know you can use `Runtime...` but not `config.poolSize` in config file - that is not available at that point. Although I am not the best person to ask, this is unlikely to be *best practice*, but may be a *good enough practice* if you only include this in selected [execution profiles](https://www.nextflow.io/docs/latest/config.html#config-profiles) - only ones relying on local executor.

**Comment by pditommaso** [comment]
So far the only way to fetch the avail cpus in the config file is `Runtime.runtime.availableProcessors()`. 

I think what it could be done is just to introduce a shortcut for this value. However still remain the caveat that this makes sense only for local execution. When deploying to a cluster, the actual cpus vary depending the actual exec node.

**Comment by ppericard** [comment]
In terms of use cases, here are a few arguments:

1. We shouldn't underestimate the number of analysis performed on single PCs. Nowadays it is pretty easy and cheap to buy a work machine with 32Go RAM and a very decent CPU, which means that a lot of small to medium size analysis can and are performed on these PCs.

2. For big analysis requiring a lot of computational power, using a cluster is not the only option. There is a growing trend toward using cloud computing. We can see this here in France where some platforms made the choice to transition to 100% cloud computing. But it seems it is also a more general trend, with more analysis now being performed on Amazon or Google clouds which are becoming affordable alternatives. In this context of cloud computing, the number of CPUs is set when starting your instance and then nextflow can be run inside the VM using the local executor.

In any case, this is more of a personal feeling  than a formal analysis. I don't have the numbers to back this but I would be really interested in any data that would confirm or contradict what I just wrote above.

**Comment by pditommaso** [comment]
Won't fix because this would only be possible for local execution.
