### ISSUE TITLE
Splitting and merging a fasta file

### ISSUE THREAD

**Issue by tomas-pluskal** [nextflow-io/nextflow#919]
Hi,
This is not a bug. I am trying to write a nextflow script that would split a fasta file, run a number of annotation procedures on each chunk (e.g., blast), and then merge the annotated chunks into annotation files that would then be sent into a channel for further processing.

I started by imitating this example: https://www.nextflow.io/example3.html

I ran into difficulties with sending the final merged file into a channel. In other words, how can I use the merged blast result as an input for another process?

This is my script so far:
```
#!/usr/bin/env nextflow

params.transcriptome = "transcriptome.fasta"
transcriptomeFile = file(params.transcriptome)


process downloadSprot {
  echo true
  storeDir 'sprot'
  output:
    set file("uniprot_sprot.fasta"), file("uniprot_sprot.fasta.p??")  into sprotDb
  script:
    """
    echo Downloading sprot database
    wget "ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz"
    gunzip uniprot_sprot.fasta.gz
    makeblastdb -in uniprot_sprot.fasta -dbtype prot
    """
}

chunks = Channel
            .fromPath(params.transcriptome)
            .splitFasta(by: 100, file: true)


process sprotBlastxParallel {
  echo true
  cpus 2
  input:
    file chunk from chunks
    set sprotDb, sprotDbIndex from sprotDb
  output:
    file "blastx_out" into sprotBlastxResults
  tag { chunk }
  script:
    """
    echo blasting ${chunk}
    echo database ${sprotDb}
    blastx -query ${chunk} -db ${sprotDb} -num_threads ${task.cpus} -evalue 1e-6 -max_hsps 1 -max_target_seqs 1 -outfmt "6 std stitle" -out blastx_out
    """
}


sprotBlastFinal = sprotBlastxResults.collectFile(name: 'blastx_final.out')

process sprotBlastxMerge {
  publishDir "."
  input:
    file finalBlast from sprotBlastFinal
  output:
    file "blastx_final.out"
  exec:
    println "Merged blastx results into " + finalBlast
}
```

It fails with this error:
```
[55/f37167] Submitted process > sprotBlastxMerge (1)
Merged blastx results into blastx_final.out
ERROR ~ Error executing process > 'sprotBlastxMerge (1)'

Caused by:
 Missing output file(s) `blastx_final.out` expected by process `sprotBlastxMerge (1)`

Source block:
 println "Merged blastx results into " + finalBlast
```

The error message is clear, but I am not sure how I can fix it.

**Comment by rsuchecki** [comment]
I think it is a quirk (feature?/bug?) related to accessing files using native execution. Replace the `exec:` block with 

```
script:
"""
ls -la
"""
```  
to see that content of your files gets collected as intended.

**Comment by pditommaso** [comment]
That may work, but to just print the file does not require a process. Just replace:

```
sprotBlastFinal = sprotBlastxResults.collectFile(name: 'blastx_final.out')
``` 

with: 

```
sprotBlastxResults
   .collectFile(name: 'blastx_final.out')
   .println { "Merged blastx results into " + it }
```

**Comment by tomas-pluskal** [comment]
@pditommaso The script is not yet finished - my goal is not to print the file, but to use it for downstream processing.

I have one additional question: is it possible to run multiple tasks on each chunk? I.e., I would like to run blast and pfam prediction, and would like to run those in parallel on each chunk. How can I code that in nextflow?

**Comment by pditommaso** [comment]
You can replace `println` with a [map](https://www.nextflow.io/docs/latest/operator.html#map). A process is only required if the operation is compute intensive and you want to execute in parallel.

**Comment by pditommaso** [comment]
>  I would like to run blast and pfam prediction, and would like to run those in parallel on each chunk. How can I code that in nextflow?

What's different compared the common pattern of a process executing a user command script?

**Comment by tomas-pluskal** [comment]
> > I would like to run blast and pfam prediction, and would like to run those in parallel on each chunk. How can I code that in nextflow?
> 
> What's different compared the common pattern of a process executing a user command script?

It seems it is not possible to have two different processes run on the same input (chunk). So I will need to split the fasta file twice?

**Comment by pditommaso** [comment]
No, [duplicate the channel](http://nextflow-io.github.io/patterns/index.html#_channel_duplication).

**Comment by tomas-pluskal** [comment]
Smart! Thank you :)
