### ISSUE TITLE
When declaration fails the publishDir

### ISSUE THREAD

**Issue by chansigit** [nextflow-io/nextflow#928]
## Bug report 

If the `when` declaration is put in the front of the script, `publishDir` does not work.

### Expected behavior and actual behavior
The output file should be in the publishDir, but actually not. 

### Program output 

Content of the  `.nextflow.log` file
`
Nov-14 20:17:01.686 [main] DEBUG nextflow.cli.Launcher - $> /data/hca/software/anaconda3/bin/nextflow run bug.nf --condition=true
Nov-14 20:17:01.829 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 18.10.1
Nov-14 20:17:01.840 [main] INFO  nextflow.cli.CmdRun - Launching `bug.nf` [astonishing_feynman] - revision: 2a3bc11813
Nov-14 20:17:01.917 [main] DEBUG nextflow.Session - Session uuid: c9740f7a-e40b-4b11-b94f-928d4e2ac82a
Nov-14 20:17:01.917 [main] DEBUG nextflow.Session - Run name: astonishing_feynman
Nov-14 20:17:01.919 [main] DEBUG nextflow.Session - Executor pool size: 56
Nov-14 20:17:01.936 [main] DEBUG nextflow.cli.CmdRun -
  Version: 18.10.1 build 5003
  Modified: 24-10-2018 14:03 UTC (22:03 CDT)
  System: Linux 3.10.0-693.11.6.el7.x86_64
  Runtime: Groovy 2.5.3 on OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
  Encoding: UTF-8 (UTF-8)
  Process: 28046@n01 [192.168.1.101]
  CPUs: 56 - Mem: 125.6 GB (120.8 GB) - Swap: 64.1 GB (58.3 GB)
Nov-14 20:17:02.024 [main] DEBUG nextflow.Session - Work-dir: /data/hca/chensijie/code/nextflow_test/learning/work [nfs]
Nov-14 20:17:02.024 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /data/hca/chensijie/code/nextflow_test/learning/bin
Nov-14 20:17:02.150 [main] DEBUG nextflow.Session - Session start invoked
Nov-14 20:17:02.157 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Nov-14 20:17:02.158 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Nov-14 20:17:02.658 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Nov-14 20:17:02.755 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Nov-14 20:17:02.755 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Nov-14 20:17:02.761 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Nov-14 20:17:02.763 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Nov-14 20:17:02.768 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=56; memory=125.6 GB; capacity=56; pollInterval=100ms; dumpInterval=5m
Nov-14 20:17:02.772 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Nov-14 20:17:02.773 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Nov-14 20:17:02.775 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Nov-14 20:17:02.961 [main] DEBUG nextflow.Session - >>> barrier register (process: test)
Nov-14 20:17:02.965 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > test -- maxForks: 56
Nov-14 20:17:03.005 [main] DEBUG nextflow.script.ScriptRunner - > Await termination
Nov-14 20:17:03.005 [main] DEBUG nextflow.Session - Session await
Nov-14 20:17:03.191 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Nov-14 20:17:03.197 [Task submitter] INFO  nextflow.Session - [2a/a45af7] Submitted process > test
Nov-14 20:17:03.266 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: test; status: COMPLETED; exit: 0; error: -; workDir: /data/hca/chensijie/code/nextflow_test/learning/work/2a/a45af71c735cc1674568f0fa1aa625]
Nov-14 20:17:03.292 [Actor Thread 2] DEBUG nextflow.Session - <<< barrier arrive (process: test)
Nov-14 20:17:03.293 [main] DEBUG nextflow.Session - Session await > all process finished
Nov-14 20:17:03.351 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Nov-14 20:17:03.351 [main] DEBUG nextflow.Session - Session await > all barriers passed
Nov-14 20:17:03.361 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=1; failedCount=0; ignoredCount=0; cachedCount=0; succeedDuration=4ms; failedDuration=0ms; cachedDuration=0ms]
Nov-14 20:17:03.382 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Nov-14 20:17:03.412 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
`

### Steps to reproduce the problem
bug.nf
`
params.condition=false
process test{
    when:
        params.condition == true
    publishDir "/data/chensijie", mode:"copy"

    output:
        file "haha.txt" into TestChannel
    script:
        """
        touch haha.txt
        """
}
`

Execute the scripts with `nextflow run bug.nf --condition=true`
and you will not find anything in  publishDir
 
### Environment 

* Nextflow version: 18.10.1
* Java version: openjdk version "1.8.0_152-release"
* Operating system: CentOS 7

**Comment by pditommaso** [comment]
This is expected. Directives have to be declared *before* any input/output/when block. See the [docs](https://www.nextflow.io/docs/latest/process.html#processes).
