### ISSUE TITLE
Add support for AWS temporary security credentials

### ISSUE THREAD

**Issue by lilly-nathanamorin** [nextflow-io/nextflow#934]
### Expected behavior and actual behavior

Expected: Nextflow should read file from AWS using temporary AWS credentials stored in `~/.aws/credentials`
Actual: Nextflow returns InvalidAccessKeyId error when using temporary AWS credentials

### Program output 

```
N E X T F L O W  ~  version 18.10.1
Launching `aws_test.nf` [nauseous_montalcini] - revision: 3e1fdbebbe
[warm up] executor > local
ERROR ~ Error executing process > 'test_aws_input'

Caused by:
  The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: XXXX; S3 Extended Request ID: XXXX)

 -- Check '.nextflow.log' file for details
```

See [nextflow.log] (https://github.com/nextflow-io/nextflow/files/2590827/nextflow.log) for full error trace

### Steps to reproduce the problem
Create temporary AWS security credentials (example ~/.aws/credentials file)
```
[default]
aws_access_key_id = ACCESS_KEY
aws_secret_access_key = SECRET_KEY
aws_session_token = TEMPORARY_TOKEN
```
Nextflow Script (aws_test.nf)
```
#!/usr/bin/env nextflow

s3_file_input = file("s3://mys3bucket/somefile.txt")

process test_aws_input {

    input:
    file s3_file from s3_file_input

    """
    echo ${s3_file}
    """
}
```

run ```nextflow aws_test.nf```

### Environment 

* Nextflow version: [18.10.1.5003] 
* Java version: [1.8.0_181]
* Operating system: [macOS]

**Comment by pditommaso** [comment]
Aws temporary credentials are not support, tho it could be a useful addition. Relevant docs https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html.

**Comment by wleepang** [comment]
Would be good to see this supported.  Users that work from development environments like Cloud9 would benefit.

**Comment by wleepang** [comment]
Suggested path is to replace `BasicCredentials` here:
https://github.com/nextflow-io/nextflow/blob/8eeb7f9f1568cc1a2ad21c735e3114e06f12812f/modules/nextflow/src/main/groovy/nextflow/cloud/aws/AmazonCloudDriver.groovy#L29

with a `DefaultCredentialProvider`:
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

**Comment by nkrumm** [comment]
thanks for the suggestion @wleepang -- I'm have to say I'm not very familiar with the the Java AWS SDK, so I could be wrong here, but does `DefaultCredentialProvider` actually take a `SESSION_TOKEN`?

I tried to implement STS/session authentication (see #1248) using [`BasicSessionCredentials`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/BasicSessionCredentials.html) 

I took this basically from the bottom of https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html

**Comment by wleepang** [comment]
@nkrumm - It shouldn't need it explicitly.  The `DefaultCredentialsProvider` follows the chain order described in the documentation for locating credentials which is:

1. Environment Variables
2. Java System Properties
3. Configured Credentials (e.g. ones set after an `aws configure`)
4. Container Credentials
5. Instance Profile

It should automatically locate a session token if it exists in any of the above - which is usually the case with 4 and 5.
