### ISSUE TITLE
Nextflow linter

### ISSUE THREAD

**Issue by LukeGoodsell** [nextflow-io/nextflow#936]
Feature request: Nextflow linter

Aim:
* Identify and suggest better coding standards. E.g. `!{var}` instead of `${var}`
    * These should prevent common mistakes that novices might make and flag potential issues
* Suggest 'standard' coding style/formatting.
    * This would make reviewing PRs and reading each other's code quicker and easier.
* Each item of lint should have a unique ID and be switch-able.
* These should be common to all/most Nextflow workflows and not  #project-specific.

See also:

* [nf-core linter](https://github.com/nf-core/tools/blob/master/nf_core/lint.py)
* [pylint](https://www.pylint.org/)
* [shellcheck](https://www.shellcheck.net/)

**Comment by LukeGoodsell** [comment]
@evanfloden An nfhack18 idea.

**Comment by apeltzer** [comment]
>  !{var} instead of ${var}

Generally like the idea! 

Might be slightly off-topic: Why is this better?

**Comment by LukeGoodsell** [comment]
> Why is this better?

1. More experienced users can forget to escape bash variables

2. Less experienced users might not understand the difference between bash and Nextflow variables and do get frustrated (I have seen this).

3. It's nice to have consistent rules rather than different rules in different contexts - shell scripts should behave like shell scripts.

**Comment by apeltzer** [comment]
Ok, I see! Thanks for the reply, I do see especially 2.) happening frequently.

**Comment by LukeGoodsell** [comment]
Usage:

* given a file or list of files, check for lint; given a directory, recursive check .nf files
* if all files lint free, exit 0; otherwise exit 1
* Print human-readable notifications
* controlled via a .nflintrc file
* exclude via `// nolint [REASON]`
* Extract code blocks and run language-specific linters



Lints:

Code errors:
* Channel not used downstream
* Channel used twice
* Object used without declaration

Code warnings:
* Process name clash/re-use
* Should use shell instead of script


Style:
* (2/4) Spaces/tabs
* Indentation level
* Indentation for input/output/shell/script
* Curly brace on same line as process declaration
* Use of unquoted variables in shell/script
* Double/single quote operator values
* No whitespace-only lines
* Empty line before input/output/shell/script

**Comment by pditommaso** [comment]
This is a great proposal. One first major decision, should this be a NF subproject and live and share the same codebase or a separate tool?

I think this could exist an independent project. What's your idea?

**Comment by zozo123** [comment]
I ended up using https://www.npmjs.com/package/npm-groovy-lint as a linter

1. Install node-js: `sudo apt-get install -y nodejs`
2. Install groovy-lint: `sudo npm install -g npm-groovy-lint`
3. Run on a .nf file and update the file  `npm-groovy-lint --fix -f flow.nf`

**Comment by richelbilderbeek** [comment]
The link to `nf-core linter` in [the first comment](https://github.com/nextflow-io/nextflow/issues/936#issue-383604159) is has changed to [here](https://github.com/nf-core/tools#linting-a-workflow)
