### ISSUE TITLE
Document all the parameters

### ISSUE THREAD

**Issue by apeltzer** [nextflow-io/nextflow#939]
There is a bunch of parameters that still need to be documented in Nextflow core functionality. Just some examples here:

Some examples:

- https://github.com/nextflow-io/nf-hack18/issues/3
- https://github.com/nextflow-io/nf-hack18/issues/4

... and there might be more!

![alt text](https://i.imgflip.com/2n7k8k.jpg)

**Comment by pditommaso** [comment]
Makes sense, I will try to list all undocumented features

**Comment by apeltzer** [comment]
Please add a label too - so that people can join in/find it as we might parallelize these efforts then more easily :-)

**Comment by apeltzer** [comment]
Everyone who's willing to join: Work on your own branch and open a PR against the main nextflow repository then, also copying the URL of this issue here so everyone else knows which has already been worked on :-) 

If stuff remains, I'm taking care even after #nfhack18 :-)

**Comment by apeltzer** [comment]
CCING @edgano :-)

**Comment by apeltzer** [comment]
@pditommaso we need your list :-) Sorry to bug you :-)

**Comment by edgano** [comment]
I was not able to join the session. But I'm still interested to help. Do we split the terms and assign a subgroup to each of us ? To avoid duplicates

**Comment by apeltzer** [comment]
That was the plan @edgano 👍 - Probably even x-ref'ing this issue here so everyone knows whats already worked on :-)
