### ISSUE TITLE
workflow.resume attribute

### ISSUE THREAD

**Issue by biologghe** [nextflow-io/nextflow#94]
Referring to [this thread](https://groups.google.com/forum/#!topic/nextflow/GYBZkWQ5Gg0) it would be nice to have a **workflow.resume** attribute. This attribute should tell if a *real* resume of the pipeline happened or not.
Thanks,
Marc

**Comment by pditommaso** [comment]
Fixed in version `0.17.0`

**Comment by biologghe** [comment]
Tnx !
