### ISSUE TITLE
Allow the implicit import function library in both config and application script

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#940]
The goal of this feature is to allow the definition of custom library of functions that are automatically imported in the global scope of either the nextflow.config file and the main application script. 

This would allow users to define custom helper functions without the hassle to explicitly import then as Java imports. 

Additionally it should allow the usage of implicit nextflow objects i.e. `params`, `workflow`, `baseDir`, `workDir` and `log` when available.

**Comment by thedam** [comment]
still this feature is not valid? (functions inside config)

**Comment by risoms** [comment]
@pditommaso Has this been introduced into Nextflow? I'm coming across the same error.

**Comment by bentsherman** [comment]
The `lib` directory was implemented for scripts but not for config files
