### ISSUE TITLE
Too long process tag name can cause SLURM failure

### ISSUE THREAD

**Issue by grafitos** [nextflow-io/nextflow#941]
## Bug report 

Nextflow generates Slurm job name from the NXF process tag name. If tag name is too long, slurm job failed as Slurm job name has a limit of 1024 chars.

### Program output 

sbatch: error: Batch job submission failed: Pathname of a file, directory or other parameter too long

### Environment 

* Operating system: Linux

**Comment by pditommaso** [comment]
Included in version `18.12.0-edge`.
