### ISSUE TITLE
Launcher fails with Java 10 or later

### ISSUE THREAD

**Issue by ODiogoSilva** [nextflow-io/nextflow#953]
## Bug report 

Installing nextflow via conda on a fresh environment will install nextflow 18.10.1 and openjdk 10.0.2. However, executing nextflow with these versions yields the following:

```
$ nextflow -version 
CAPSULE EXCEPTION: Could not parse version line: openjdk version "10.0.2" 2018-07-17 (for stack trace, run with -Dcapsule.log=verbose)
USAGE: java <options> -jar ../miniconda3/envs/myenv/share/nextflow/framework/18.10.1/nextflow-18.10.1-one.jar

Actions:
  capsule.version - Prints the capsule and application versions.
  capsule.modes - Prints all available capsule modes.
  capsule.jvms - Prints a list of all JVM installations found.
  capsule.help - Prints this help message.
  capsule.tree - Prints the capsule's dependency tree.
  capsule.resolve - Downloads all un-cached dependencies.

Options:
  capsule.mode=<value> - Picks the capsule mode to run.
  capsule.reset - Resets the capsule cache before launching. The capsule to be re-extracted (if applicable), and other possibly cached files will be recreated.
  capsule.log=<value> (default: quiet) - Picks a log level. Must be one of none, quiet, verbose, or debug.
  capsule.java.home=<value> - Sets the location of the Java home (JVM installation directory) to use; If 'current' forces the use of the JVM that launched the capsule.
  capsule.java.cmd=<value> - Sets the path to the Java executable to use.
  capsule.jvm.args=<value> - Sets additional JVM arguments to use when running the application.
  capsule.local=<value> - Sets the path of the local Maven repository to use.
Unable to initialize nextflow environment
```

Is nextflow supposed to support java 10?

### Environment 

* Nextflow version: 18.10.1
* Java version: openjdk 10.0.2
* Operating system: archlinux

### Additional context

(Add any other context about the problem here)

**Comment by jenzopr** [comment]
Confirmed. An easy solution would be to pin openjdk to <10 in bioconda.

**Comment by pditommaso** [comment]
That's weird we have integration tests for JDK 8 up to 11. What's the version string returned by your JDK? 

```
$ java --version
```

**Comment by jenzopr** [comment]
For us, it returns

```
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment Zulu10.3+5 (build 10.0.2+13)
OpenJDK 64-Bit Server VM Zulu10.3+5 (build 10.0.2+13, mixed mode)
```
Best,
Jens

**Comment by jenzopr** [comment]
IMHO, it would definitely add to nextflows popularity if java versions delivered by large and **state of the art** software management tools (e.g. conda, in this case java comes from the [conda-forge](https://conda-forge.org/) channel) would be seamlessly supported by nextflow. I guess there are numerous parsers for version numbers available in groovy (e.g. `org.codehaus.groovy.grails.plugins.VersionComparator`)?

**Comment by pditommaso** [comment]
The problem is not NF but [Capsule](https://github.com/puniverse/capsule) package manager that seems to not recognise the version.

**Comment by pditommaso** [comment]
The Java [spec](https://openjdk.java.net/jeps/223) for version number just for ref.

**Comment by pditommaso** [comment]
Actually this code https://github.com/puniverse/capsule/blob/master/capsule/src/main/java/Capsule.java#L4248-L4262

**Comment by jenzopr** [comment]
Sorry, my bad about blaming nf then 😉 
Is it worthwhile to file an issue upstream then? It looks like only the pattern would need to be updated? Unfortunately, I'm not fluent in groovy, so I can't contribute a minimal example..

**Comment by jenzopr** [comment]
I checked the regex pattern, it recognizes also minor versions easily..?

**Comment by pditommaso** [comment]
I've isolate the code 

```
import java.io.IOException;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * @author Paolo Di Tommaso <paolo.ditommaso@gmail.com>
 */
public class Ver {

    public static void main(String... args) throws IOException {
        getActualJavaVersion();
    }

    private static final Pattern PAT_JAVA_VERSION_LINE = Pattern.compile(".*?\"(.+?)\"");

    private static void getActualJavaVersion() throws IOException  {
        System.out.println("Version property: " + System.getProperty("java.version"));
                
        Process process = new ProcessBuilder("java", "-version").redirectErrorStream(true).start();
        Scanner s = new Scanner(process.getInputStream()).useDelimiter("\n");
        String versionLine = s.hasNext() ? s.next() : "";
        System.out.println("Version string: " + versionLine);

        final Matcher m = PAT_JAVA_VERSION_LINE.matcher(versionLine);
        if (!m.matches()) {
            System.err.println("** Could not parse version line: " + versionLine);
        }
        else {
            final String version = m.group(1);
            System.out.println("Version detected: " + version);
        }
    }
}
``` 

It works for Java 8 and 9 and fails with 10 .. not sure to understand how test can pass on travis ? 😕 

If you want to try it, save the above snippet, then use `javac Ver.java &&  java -cp . Ver`.

**Comment by jenzopr** [comment]
Thanks a lot! I can look into it and eventually propose a fix upstream.

**Comment by pditommaso** [comment]
Ok, looking better at this the regex `.*?\"(.+?)\"` fails because it assumes there's nothing else after the number, instead since java 10, it prints the build date `java version "10" 2018-03-20`. 

However this does not explain why tests with OpenJDK are fine. I think this happens because before checking `java -version`, Capsule tries to infer the version number from the installation path: 

https://github.com/puniverse/capsule/blob/master/capsule/src/main/java/Capsule.java#L4165-L4170

and 

https://github.com/puniverse/capsule/blob/master/capsule/src/main/java/Capsule.java#L4189-L4216

I guess Azul is not recognised by the latter. Could you please check how is the installation path of your Azul JVM ?

**Comment by pditommaso** [comment]
Ahah, it looks conda mess up the Java install path, therefore it tries to use the `java -version` string, causing that issue. 

```
$ which java
/Users/pditommaso/miniconda2/envs/nf-test/bin/java
```

**Comment by jenzopr** [comment]
Thanks for figuring this out! I'm fine with Capsule falling back to `java -version` and changing the pattern to `".*?\"(.+?)\".*?"` solves the issue.

**Comment by dfornika** [comment]
I've submitted this pull request to bioconda to pin openjdk=8 on the current `nextflow-18.10.1` recipe as suggested above by @jenzopr:

https://github.com/bioconda/bioconda-recipes/pull/12493

**Comment by pditommaso** [comment]
Patched in capsule fork [1.0.3.1](https://github.com/nextflow-io/capsule/commits/v1.0.3.1) https://github.com/nextflow-io/capsule/commit/df271ea9ace0fe63a3af4238fac8368b708bb7cc

**Comment by jenzopr** [comment]
Great! We'll give it a try.

**Comment by pditommaso** [comment]
Not yet released it.

**Comment by atongsa** [comment]
> Requires [puniverse/capsule#129](https://github.com/puniverse/capsule/issues/129) and [puniverse/capsule#130](https://github.com/puniverse/capsule/pull/130).

seems java faile to merge this pr; 
i am using nextflow 21; and get the same error; 
i solve it by `mamba install openjdk"=8"`

**Comment by roryk** [comment]
Just ran into this issue as well using bioconda installed nextflow on a google cloud linux box:

```
nextflow -h                                                                          (pythia_dataset) 
CAPSULE EXCEPTION: Could not parse version: 11.0.9.1-internal while processing attribute Min-Java-Version: 1.8.0 (for stack trace, run with -Dcapsule.log=verbose)
USAGE: java <options> -jar ../miniconda3/envs/pythia_dataset/share/nextflow/dist/21.04.0/nextflow-21.04.0-one.jar
Actions:
  capsule.version - Prints the capsule and application versions.
  capsule.modes - Prints all available capsule modes.
  capsule.jvms - Prints a list of all JVM installations found.
  capsule.help - Prints this help message.
  capsule.tree - Prints the capsule's dependency tree.
  capsule.resolve - Downloads all un-cached dependencies.
Options:
  capsule.mode=<value> - Picks the capsule mode to run.
  capsule.reset - Resets the capsule cache before launching. The capsule to be re-extracted (if applicable), and other possibly cached files will be recreated.
  capsule.log=<value> (default: quiet) - Picks a log level. Must be one of none, quiet, verbose, or debug.
  capsule.java.home=<value> - Sets the location of the Java home (JVM installation directory) to use; If 'current' forces the use of the JVM that launched the capsule.
  capsule.java.cmd=<value> - Sets the path to the Java executable to use.
  capsule.jvm.args=<value> - Sets additional JVM arguments to use when running the application.
  capsule.local=<value> - Sets the path of the local Maven repository to use.
Unable to initialize nextflow environment
```

```
openjdk 11.0.9.1-internal 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 11.0.9.1-internal+0-adhoc..src, mixed mode)
```

not sure where the -internal is coming from, but that JDK is from the conda-forge one:

```
openjdk                   11.0.9.1             h5cc2fde_1    conda-forge
```

**Comment by pditommaso** [comment]
Stating [this](https://openjdk.java.net/jeps/223) internal suffix identifies 

> a pre-release identifier. Typically ea, for an early-access release that's under active development and potentially unstable, or internal, for an internal developer build.

Make sure to use a stable Java release.

**Comment by sstadick** [comment]
It's not the `-internal` that is causing it to fail. It's [this](https://github.com/puniverse/capsule/blob/291a54e501a32aaf0284707b8c1fbff6a566822b/capsule/src/main/java/Capsule.java#L4338) regex that is expecting the `update` to be `_<number>` not `.number`.

This broke for me going from `11.0.8-internal` to `11.0.9.1-internal`.

**Comment by pditommaso** [comment]
You are right in this specific case, but depending the java version I've also seen failing for other reasons. For example with Java 9, crash because some Java cli options required by NF are not available with the internal version. Therefore we are not planning to support `-internal` distributions.

**Comment by ArtemSokolov** [comment]
One possible reason could be the number of tokens in the version number.
Users in our lab report having this issue with `11.0.14.1`, but everything seems to work fine on my machine with `11.0.14`.

**Comment by sstadick** [comment]
@ArtemSokolov, as Paolo mentioned, there are a few reasons why this issue pops up. You seem to have hit the same one as me, which is a regex that is expecting the "update" number as `_<number>`. See https://github.com/puniverse/capsule/pull/136/files

**Comment by pditommaso** [comment]
My point `-internal` version should not be used. There a plenty of Java stable distribution and it's dead easy to install with https://sdkman.io/

**Comment by ArtemSokolov** [comment]
I could be wrong, but I don't think that the problem-causing `11.0.14.1` is considered `-internal`.
Based on [JEP 322](https://openjdk.java.net/jeps/322), the fourth token is

> $PATCH - The emergency patch-release counter, incremented only when it's necessary to produce an emergency release to fix a critical issue. (Using an additional element for this purpose minimizes disruption to both developers and users of in-flight update releases.)

which I believe is fair to consider as part of a stable release.

**Comment by pditommaso** [comment]
Then it should be supported.
