### ISSUE TITLE
Add an env variable to control jars installation in Conda recipe

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#954]
Currently the Conda recipe for Nextflow is changing the `NXF_HOME` to the installation path given by Conda. 

However this has the side-effect of changing paths that are expected to be in the user HOME. See for example [here](https://github.com/bioconda/bioconda-recipes/issues/10797#issuecomment-443083244). 

A better solution would be to add a variable `NXF_DIST` that only defines the path where [NF jars are located](https://github.com/nextflow-io/nextflow/blob/c40c71a2f39e1dd89e3a17f9301be9fdfd2de95c/nextflow#L266) and redefined it in the Conda recipe.

Variables `NXF_ASSETS` and `NXF_LAUNCHER` should stay in the user home. Instead `CAPSULE_CACHE_DIR` should go under the path given by Conda.

**Comment by bgruening** [comment]
Thanks @pditommaso for taking care here!

**Comment by pditommaso** [comment]
Added the variable `NXF_DIST` to control the path where the NF main jar is installed.

**Comment by pditommaso** [comment]
Reminder to myself: modify the Conda recipe to set this variable to use the Conda installation path. `NXF_ASSETS`, `NXF_LAUNCHER` and `CAPSULE_CACHE_DIR ` should stay under the user home (default). 

See https://github.com/bioconda/bioconda-recipes/issues/10797#issuecomment-443083244

**Comment by pditommaso** [comment]
This is solved by https://github.com/bioconda/bioconda-recipes/pull/13168
