### ISSUE TITLE
Linux Process Priority Using nice and renice Commands

### ISSUE THREAD

**Issue by nephantes** [nextflow-io/nextflow#956]
## New feature

Setting Linux Process Priority Using nice and renice Commands.

## Usage scenario 

When a machine shared with multiple people or executing multiple nextflow runs on the same machine, having this kind of functionality would prioritize the runs.

## Suggest implementation 
Setting a generic nice value in the config file and for each process as well. 

nice_value=16

while running any command, if nice_value is defined;

nice -n nice_value command

**Comment by nephantes** [comment]
sometimes, you run multiple nextflow runs in a server without any schedular. It would be nice to be able prioritize them while starting a run since, sometimes, some of the runs are more urgent. You don't want to kill the ones you started earlier.

**Comment by pditommaso** [comment]
I see your point. However I think this is very specific use case. I don't nextflow should support this deployment model (at least in the short run). I'm tagging this issue as *whishlist* to mean that is something desirable for some users but it does not fit the current model and it may be implemented in the future.
