### ISSUE TITLE
Installing Nextflow in a specific prefix ?

### ISSUE THREAD

**Issue by mboisson** [nextflow-io/nextflow#959]
Hi,
Is it possible to install Nextflow like any other sensible software package, i.e. in a given self-contained PREFIX ? 

It seems that the `make install` command only copies files in the installer's `$HOME` directory and the `nextflow` script remains in the build directory. 

Thanks

**Comment by pditommaso** [comment]
The command `make install` is meant for developing purpose. The `nextflow` command is a mere bash wrapper that automatically downloads and copies required packages in the `$HOME/.nextflow` directory. You can control that path using the `NXF_HOME` env var.

**Comment by mboisson** [comment]
Mmm, this seems to be a blackbox script which contains binary code. Is this pure java ? does it link against anything (such as libc/libstdc++) ? We typically build from source because libraries are not in standard places on our system, and downloaded binaries tend not to work because they don't find some libraries.

**Comment by pditommaso** [comment]
Dear friend, it's pure java w/o native code. If you don't trust it, unzip it and reverse engineer the build script.
