### ISSUE TITLE
Parameter -queue-size not working for AWS batch

### ISSUE THREAD

**Issue by alneberg** [nextflow-io/nextflow#963]
### Expected behavior and actual behavior

Nextflow would only keep maximum 10 processes going at once if one specifies `-queue-size 10`. Instead ~100 processes are submitted.

### Steps to reproduce the problem

I ran
```bash
nextflow run -queue-size 10 ~/Sarek/germlineVC.nf -profile awsbatch -work-dir s3://mybucket/work --outDir s3://mybucket/results --sample s3://mybucket/results/Preprocessing/Recalibrated/recalibrated.tsv --genome iGRCh38 --genome_base s3://ngi-igenomes/igenomes/Homo_sapiens/GATK/GRCh38 --verbose --tools HaplotypeCaller,Manta,Strelka -resume
```

### Program output 
Log output:
[nextflow.queue_size.log](https://github.com/nextflow-io/nextflow/files/2653406/nextflow.queue_size.log)

### Environment 

* Nextflow version: version 18.10.1 build 5003
* Java version: 
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
* Operating system:
Linux

### Additional context

The processes are executed on AWS batch.

**Comment by apeltzer** [comment]
This also affects us apparently! :-(

**Comment by pditommaso** [comment]
> This also affects us apparently 

@apeltzer Are you meaning Batch as well ?

**Comment by apeltzer** [comment]
Yes, probably even the same use-case (https://github.com/SciLifeLab/Sarek)

**Comment by serverhorror** [comment]
Same thing is still hapenning, not sure what to do abou this, it is working with SLURM but seems completely ignored with AWS Batch.

I would expect the command below to submit in batches of at most 50 `files2lfr` processes

```
#nextflow run main.nf --nsamples 0 --credentials ./credentials.json --reportsDir "./xxx.perfTests/nsamples=xxx" -profile aws -queue-size 50

N E X T F L O W  ~  version 20.10.0
Launching `main.nf` [kickass_joliot] - revision: 9aebd9cb12
Uploading local `bin` scripts folder to s3://redacted/nextflow/work/xxx/tmp/39/a4124063079a2797e69a61a98dee27/bin
...
[df/8977cf] process > get_mdr_samples [100%] 1 of 1 ✔
[9d/5474a0] process > files2lfr (23)  [  0%] 0 of 3645
executor >  awsbatch (101)
[df/8977cf] process > get_mdr_samples [100%] 1 of 1 ✔
[81/fc2a75] process > files2lfr (5)   [  0%] 0 of 3571
[-        ] process > data2mxr        
-List of 7
 $ buildTime  : chr "Fri Feb 26 22:44:50 UTC 2021"
 $ tagVersion : chr "14-06eda3be"
 $ environment: chr "test"
 $ gitBranch  : chr "staging"
 $ gitCommit  : chr "0...9"
 $ buildUrl   : chr "https://example.invalid/redacted/"
 $ version    : chr "redacted"

Error executing process > 'files2lfr (3347)'
Caused by:
  Please reduce your request rate. (Service: Amazon S3; Status Code: 503; Error Code: SlowDown; Request ID: E...3; S3 Extended Request ID: I...I=)
```
