### ISSUE TITLE
Script base path does not exist

### ISSUE THREAD

**Issue by srikarchamala** [nextflow-io/nextflow#967]
What does this message mean? How do I correct this?

Dec-07 13:53:34.816 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/user/next_flow/bin

**Comment by pditommaso** [comment]
It just means that in your project there isn't a `bin/` folder. It's not an issue just a debugging message.

**Comment by kemin711** [comment]
I am getting an error message with the latest version 20.01, just pulled and built with /my/own/binary/dir/bin/bin,  I believe somewhere in the latest version, the bin was appended twice.  My binary programX is located in /my/ownbinary/dir/bin/programX

**Comment by kemin711** [comment]
DEBUG nextflow.Session - Script base path does not exist or is not a directory: /my/own/binary/dir/bin/bin

**Comment by kemin711** [comment]
ERROR nextflow.processor.TaskProcessor - Error executing process > 'programX (P002673_PLT_R)'

**Comment by kemin711** [comment]
DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
There is not information about the execution directory, I looked in the work directory and could not find any log info related to programX

**Comment by kemin711** [comment]
But after a second try it worked.  Could be some system update on my machine.
