### ISSUE TITLE
Killing HPC cluster job breaks Nextflow pipeline shutdown & cleanup

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#968]
## Bug report 

When running Nextflow interactively from the command line, you can hit Control+C to cancel the pipeline. This causes Nextflow to stop all running tasks and cleanly exit (the desired behavior). 

However, if you submit the parent Nextflow process to run inside of an HPC cluster job (e.g. with SLURM, SGE, etc), it becomes difficult to invoke this clean shutdown behavior. Running `scancel` or `qdel` on a cluster job that is running Nextflow causes the job to stop, leaving all Nextflow tasks (e.g. ones that were also submitted as cluster jobs) still running. The only way to get this clean shutdown of Nextflow after submitting it to run as a cluster job is to ssh directly into the node it is running on and run `kill` on its process ID (which you must also ascertain). This is a very awkward process that is not easy to automate cleanly. I am hoping there might be some way to get Nextflow to shutdown cleanly when it is running inside an HPC cluster job like this.

### Expected behavior and actual behavior

Some method to halt an HPC cluster job running Nextflow while still allowing Nextflow to cleanly shut down and halt all its pipeline tasks that are still running. 

### Steps to reproduce the problem

SGE:

```
echo 'nextflow run main.nf' | qsub -wd "$PWD" 
qdel <job_id>
```

SLURM:

```
srun -p cpu_long --ntasks-per-node=1 -c 2 bash -c 'nextflow run  main.nf'
scancel <job_id>
```

**Comment by pditommaso** [comment]
Oh my .. AFAIK both grid engine and slurm send a `USR1` or  `USR2` signal before to abruptly kill the job (ie. `SIGKILL`). 

You wrapper should use a Bash trap to intercept that those signals and send a `SIGTERM` to nextflow.

**Comment by stevekm** [comment]
I am testing that out but so far I am unable to get my script to catch any signals. Its not clear to me if the signals sent by `scancel` are ever actually reaching the `sbatch` script itself, or if they are handled by some other SLURM process.

**Comment by stevekm** [comment]
@pditommaso might need some help with this one, never used traps before, this was the best I could come up with

```
# Makefile

submit:
	printf "#!/bin/bash\n set -x \n \
	trap 'echo caught SIGTERM; kill -s SIGTERM \$$PID' SIGTERM \n \
	trap 'echo caught EXIT, exiting...' EXIT \n \
	./nextflow run  main.nf & PID=\$$!  \n \
	echo \$$PID \n \
	wait \$$PID \n \
	" | sbatch -D "$$PWD" -o "%j.out" -J "trap" -p "cpu_short" --ntasks-per-node=1 -c "1" /dev/stdin
```

I tried using the `-bg` argument for Nextflow but it results in the sbatch job ending immediately. However this method does not fully work either because when I scancel the job, the traps catch the SIGTERM signal but fail to kill Nextflow correctly, its child SLURM jobs remain running.

**Comment by pditommaso** [comment]
The [scancel](https://slurm.schedmd.com/scancel.html) docs reports that it send a `SIGTERM` to kill the job, therefore NF should already cleanup the pending jobs. 

Grid Engine should use instead `SIGUSR1` that's reserved by the JVM therefore it cannot be handled by NF. You need to user wrapper script to intercept and map to a `SIGTERM`.

**Comment by stevekm** [comment]
From my tests with SLURM, the SIGTERM is being detected but Nextflow is not cleaning up.

**Comment by pditommaso** [comment]
[SIGTERM](https://github.com/nextflow-io/nextflow/blob/15ee2f1c5f18062fa3e15aa50eae002247f1c1dc/src/main/groovy/nextflow/Session.groovy#L475) is handled by NF. Are you wrapping NF by another script?

**Comment by stevekm** [comment]
I am generally using a Makefile to generate the `sbatch` command; the one in my production pipeline is here: 

https://github.com/NYU-Molecular-Pathology/NGS580-nf/blob/08db26c0cd8afe32e08363adf282244733d10b77/Makefile#L286

looks like this:

```
submit-bigpurple:
	@touch "$(NXF_SUBMIT)" && \
	printf "#!/bin/bash\n \
	make submit-bigpurple-run TIMESTAMP=$(TIMESTAMP) $(SUBEP)" | \
	sbatch -D "$(ABSDIR)" -o "$(SUBLOG)" -J "$(SUBJOBNAME)" -p "$(SUBQ)" --ntasks-per-node=1 -c "$(SUBTHREADS)" --export=HOSTNAME /dev/stdin | tee >(sed 's|[^[:digit:]]*\([[:digit:]]*\).*|\1|' > '$(NXF_JOBFILE)')
```

This is similar to the other example I posted in my previous comment, which I also use a Makefile recipe to build the sbatch command. 

However maybe it is relevant that sbatch itself requires a 'script' input; you either have to use the `--wrap` arg to give it a command that gets wrapped in a sh script for execution, or you have to give it an actual file to execute, either on disk or from stdin. So in a sense there is always a wrapper script involved, I think.

**Comment by pditommaso** [comment]
NF correctly handler termination signals. I think the problem arise because you are wrapping NF execution by other script, therefore you need to handle to propagation of signals from your script to NF process.

**Comment by stevekm** [comment]
@pditommaso thanks for the help, I think the wrapper script (Makefile recursive execution) was getting in the way. Here is the simple version that works:

```

printf '#!/bin/bash
set -x
echo $SLURMD_NODENAME > "$(NXF_NODEFILE)"
pid=""
kill_func(){
echo TRAP; kill $pid ; wait $pid
}
trap kill_func INT
trap kill_func EXIT
./nextflow run main.nf & pid=$! ; echo "waiting for ${pid}" ; wait $pid
' | \
sbatch -D "${PWD}" --time=5-00:00:00 /dev/stdin
```

**Comment by zhangzhen** [comment]
I have the same problem on grid engine. I submitted "nextflow run <pipeline>" via qsub as follows:

qsub -b y -j y -pe orte 2 -V -o ./ -cwd /share/home/productQC/app/source/nextflow/nextflow -log /share/home/productQC/PROJECT/201218_MyriadProject/analysis_results_v1/test.log run /share/home/productQC/PROJECT/201218_MyriadProject/nf-cetus/main.nf -profile sge  -c /share/home/productQC/PROJECT/201218_MyriadProject/nf-cetus/nextflow.config -w /share/home/productQC/PROJECT/201218_MyriadProject/analysis_results_v1/test_workdir --fastqdir /share/home/rawdata/Fastq/2021/02 --outdir /share/home/productQC/PROJECT/201218_MyriadProject/analysis_results_v1 --sampleinfo /share/home/productQC/PROJECT/201218_MyriadProject/analysis_results_v1/test_copy.csv

And then I used qdel <jobid> to stop this pipeline running. Unexpectedly, the related tasks were stilling running.

Zhen
