### ISSUE TITLE
Singleton list conversion cause quirk behaviour

### ISSUE THREAD

**Issue by apeltzer** [nextflow-io/nextflow#969]
## Bug report 

Minimal example:

```Nextflow
    input:
    file input_files from featureCounts_to_merge.collect()

    output:
    file 'merged_gene_counts.txt'

    script:
    //if we only have 1 file, just use cat and pipe output to csvtk. Else join all files first, and then remove unwanted column names.
    def single = input_files instanceof Path ? 1 : input_files.size()
    def merge = (single == 1) ? 'cat' : 'csvtk join -t -f "Geneid,Start,Length,End,Chr,Strand,gene_name"'
    """
    $merge $input_files | csvtk cut -t -f "-Start,-Chr,-End,-Length,-Strand" | sed 's/Aligned.sortedByCoord.out.markDups.bam//g' > merged_gene_counts.txt
    """
```

### Expected behavior and actual behavior
I expect `input_files.size()` to return the size of the list, e.g. having `n` elements.

Actually, this depends:

- if its just one element, it returns a Path object, so path.size() returns the length of the path as a String
- if its multiple elements, it returns the list size, as expected

### Steps to reproduce the problem

See above testcase

### Environment 

* Nextflow version: 18.10.1 
* Java version: 1.8
* Operating system: no-arch

**Comment by pditommaso** [comment]
What is `bla` in your example? do you mean `input_files` ?

**Comment by apeltzer** [comment]
Updated the post, yes that's what I meant :-)

**Comment by pditommaso** [comment]
OK, this is the problem we discussed right. Therefore with `input_files instanceof Path ? 1 : input_files.size()` you get the list size, right?

**Comment by apeltzer** [comment]
Exactly, I used this now for the [RNAseq](https://github.com/nf-core/rnaseq/blob/613feafa18ca3c702e155673b3f18bf4379e17d7/main.nf#L949) pipeline in that way :-)

**Comment by pditommaso** [comment]
OK. being so I will change the title because it's misleading. The problem is not the `File.size` method but the fact that a list containing a single value is implicitly converted to the element value, causing that quirk behaviour.

**Comment by apeltzer** [comment]
Yes of course :-)
