### ISSUE TITLE
Output into multiple channels

### ISSUE THREAD

**Issue by biologghe** [nextflow-io/nextflow#97]
Hi,
I've noticed that in several nextflow pipelines people often copy channels in order to pipe output to multiple processes. I think the pipeline would become less verbose if one could do something like:

    process foo {
      ...
      output: file 'out.tsv' into fooOut1, fooOut2, fooOut3
      ...
    }

    instead of doing:

    process foo {
      ...
      output: file 'out.tsv' into fooOut 
      ...
    }

    fooOut.into {
      fooOut1
      fooOut2
      fooOut3
    }

**Comment by pditommaso** [comment]
This makes sense. I will give a try to it. Thanks for the contribution.

**Comment by pditommaso** [comment]
Fixed in version `0.17.0`

**Comment by biologghe** [comment]
Fantastic, thank you Paolo.

**Comment by pditommaso** [comment]
Nice idea. Thanks for suggesting it.
