### ISSUE TITLE
Nextflow tries to use bash in Singularity containers that lack bash

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/nextflow#974]
## Bug report 

If I make a Singularity container based on a Linux distro that does not come with `bash` installed and instead uses something like `sh`, Nextflow still tries to invoke `bash` in the `.command.run` file with a command like this:

```
singularity exec -B /gpfs/data/molecpathlab/development/bwa-bench -B "$PWD" /gpfs/data/molecpathlab/development/bwa-bench/./containers/bwa-0.7.17.simg /bin/bash -c "cd $PWD; /bin/bash -ue /gpfs/data/molecpathlab/development/bwa-bench/work/81/76f7fdd9f2e06d8e73504567e0e893/.command.sh"
```

resulting in errors like:

```
Caused by:
  Process `align (null)` terminated with an error exit status (127)

Command executed:

  bwa mem     -M -v 1     -t ${NSLOTS:-${NTHREADS:-1}}     -R '@RG\tID:SeraCare\tSM:SeraCare\tLB:SeraCare\tPL:ILLUMINA'     "hg19/genome.fa"     "SeraCare-1to1-Positive_S2_L001_R1_001.fastq.gz" "SeraCare-1to1-Positive_S2_L001_R2_001.fastq.gz" > "sample.sam"

Command exit status:
  127

Command output:
  (empty)

Command error:
  /.singularity.d/actions/exec: exec: line 9: /bin/bash: not found
```

Obviously `/bin/bash` cannot be found inside the container, because I did not include it due to space concerns. Is there a way to alter the Nextflow behavior to support containers that do not use `bash`?

### Environment 

* Nextflow version: 18.10.1

**Comment by pditommaso** [comment]
Bash is a mandatory dependency.

**Comment by stevekm** [comment]
Even inside of containers?

**Comment by pditommaso** [comment]
Surely if you are using trace, report or timeline files that requires metrics collection. If not you can try to set `process.shell = ['/bin/sh']`

**Comment by stevekm** [comment]
OK. `bash` is only 1MB it seems inside my container so I will just add it, thanks.

**Comment by photocyte** [comment]
Hi there, just a note I am running into this same issue on Nextflow v20.10.0, using Singularity execution of quite thin Docker containers.  Trying to use `sh` instead of `bash` doesn't seem to fix it.  

nextflow.config:
```
process {
    withName:svg_2_pdf {
        container = 'docker://jrbeverly/rsvg:baseimage'
        shell = ['/bin/sh']
    }
}
```

with or without `shell = ['/bin/sh']`:
```
Error executing process > 'svg_2_pdf (14)'

Caused by:
  Process `svg_2_pdf (14)` terminated with an error exit status (127)

Command executed:

  rsvg-convert -f pdf -o {redacted}.dfv.svg.pdf {redacted}.dfv.svg

Command exit status:
  127

Command output:
  (empty)

Command error:
  /.singularity.d/actions/exec: exec: line 21: /bin/bash: not found

Work dir:
  {redacted}/interproscan/work/c7/86a3aa986c2eb6bd4f480c4ed52e10

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

Something to be able to execute containers without the `bash` requirement would be nice. There are a lot of premade containers out there that would be convenient to use!
