### ISSUE TITLE
Missing output file due to special characters in value name

### ISSUE THREAD

**Issue by PhilPalmer** [nextflow-io/nextflow#979]
### Expected behavior and actual behavior

I'm not sure if this a bug or not but I was having this problem in a [pipeline](https://github.com/lifebit-ai/GATK4_Best_Practice/blob/haplotypecaller-gvcf-gatk4/main.nf) I'm working on. I expected for any special characters in a variable used for an output filename to be escaped. I have simplified it to try and make it as clear as possible. 

### Steps to reproduce the problem

`file.txt`:
```
chr1:1-249250621
chr2:1-243199373
chr3:1-198022430
```

`main.nf`:
```nextflow
test = Channel.fromPath(params.test).splitText().map{ it -> it.trim() as Path }

process mk_file {
  tag "$test"

  input:
  val test from test

  output:
  file("${test}.txt") into results

  script:
  """
  echo $test >> ${test}.txt
  """
}
```

Command executed:
```
nextflow run main.nf --test file.txt 
```

### Program output 

```
Unable to find any JVMs matching version "1.8".
N E X T F L O W  ~  version 18.10.1
Launching `split.nf` [cranky_darwin] - revision: 4971bd1330
[warm up] executor > local
[79/031797] Submitted process > mk_file (chr3:1-198022430)
[59/1f4f7b] Submitted process > mk_file (chr2:1-243199373)
[e6/2721ed] Submitted process > mk_file (chr1:1-249250621)
ERROR ~ Error executing process > 'mk_file (chr3:1-198022430)'

Caused by:
  Missing output file(s) `chr3` expected by process `mk_file (chr3:1-198022430)`

Command executed:

  echo chr3:1-198022430 >> chr3:1-198022430.txt

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /Users/phil/Documents/GitHub/test/work/79/031797efd416dbcf878c2902d7e4a5

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```
[nextflow.log](https://github.com/nextflow-io/nextflow/files/2700048/nextflow.log)

It's clear that the `:` is causing the problem however I don't know how to escape it because it's part of a variable name. 

### Environment 

* Nextflow version: 18.10.1
* Java version: [?]
* Operating system: macOS

Thanks

**Comment by stevekm** [comment]
Is your storage device an NFS or NTFS formatted drive? Pretty sure both of those do not support ':' in file names; the filename gets silently truncated after the ':'. Probably best to just not use that character as general practice.

**Comment by stevekm** [comment]
could also consider reformatting your input file; I run into these kinds of issues a lot when dealing with genomic coordinate files and I end up converting it to .bed tab separated format for use through the pipeline then only concatenate it dynamically to 'chr:start-stop' as needed

**Comment by pditommaso** [comment]
Yes, the `:`' character is interpreted as path separator. Therefore it expects two files as output instead of one.
