### ISSUE TITLE
Raw cpu usage provided by nextflow not consistent with the values provided by /usr/bin/time

### ISSUE THREAD

**Issue by phupe** [nextflow-io/nextflow#982]
# To reproduce the issue

Install the program stress:
`sudo apt-get install stress` or `sudo yum install stress`

In the bash script `launch-nextflow.bash`, set the variable `NEXTFLOW_BIN` to your nextflow PATH.

Execute `bash  launch-nextflow.bash`

Files attached (remove .txt extension):
* scripts
* report.html generated by nextflow
* .command.log files

# Tests performed on:

Linux 4.15.0-42-generic 45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# Estimation of raw cpu usage for different tasks

The raw cpu usage generated by nextflow is not consistent with the values provided by the command  `/usr/bin/time -v` which gives values close to theoretical values.

## Task TwoCpus2mnSleep2mnInNf

* Uses 2 cpus during 2mn then sleep in during 2mn

* sleep performed in the nextflow script

* Theoretical raw cpu usage should be 100%

* Nextflow reports raw cpu usage 390%

## TwoCpus4mn

* Uses 2 cpus during 4mn then stops

* Theoretical raw cpu usage should be 200%

* In `.command.log` file,  `/usr/bin/time -v` reports a raw cpu usage of 192%

* Nextflow reports a raw cpu usage of 347%

## TwoCpus2mnSleep2mnInBash

* Uses 2 cpus during 2mn then sleep in during 2mn

* sleep performed in the bash script called by nextflow

* Theoretical raw cpu usage should be 100%

* In `.command.log` file,  `/usr/bin/time -v` reports a raw cpu usage of 95%

* Nextflow reports a raw cpu usage of 565%

# Suggestion

Use `/usr/bin/time -f "%P"` to get the raw cpu usage of each task.

# Environment 

* Nextflow version: 18.10.1
* Java version: openjdk 10.0.2 2018-07-17, OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
* Operating system: Linux 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pditommaso** [comment]
Thanks for reporting this detailed issue report. I think I have identified the problem.

**Comment by phupe** [comment]
Your welcome!

**Comment by pditommaso** [comment]
Included in version `19.01.0-edge`.

**Comment by phupe** [comment]
Great job Paolo!

I have tested the following release: 845e6d1 [origin/master] [release 19.01.0-edge]

The reported metrics for CPU usage (both for Raw usage and % Allocated look perfect).

Thanks.
