### ISSUE TITLE
Issue nextflow error message

### ISSUE THREAD

**Issue by jfourquet2** [nextflow-io/nextflow#990]
Hello,

## Bug report 
I am new in nextflow and I have an issue with message error. I'm trying to do the nextflow hackaton 2018 and I am in the step 2.5 quality control.

### Expected behavior and actual behavior

The expected behavior is to have an error message "Channel `read_pairs_ch` has been used twice as an input by process `fastqc` and process `quantification`" but the actual behavior is that I have just the line "[warm up] executor > local".

### Environment 
* Nextflow version: 18.10.1 build 5003
  Modified: 24-10-2018 14:03 UTC (16:03 CEST)
* Operating system: Linux 4.15.0-43
* Java version: 10.0.2

Do you know what can be the issue ?

Thanks a lot for your help !
Joanna

**Comment by pditommaso** [comment]
Not sure to understand the problem. Could you please provide a more detailed example?

**Comment by jfourquet2** [comment]
Thanks for your answer.

I'm trying to do step by step the hackaton 2018 https://nextflow-io.github.io/nf-hack18/training.html and i am at the step "2.5. Quality control". When I run the script5.nf I must have an error "Channel `read_pairs_ch` has been used twice as an input by process `fastqc` and process `quantification`" but it is not the case, the script not run but I haven't the notification of an error. Is it normal ?

Command line:
nextflow run script5.nf -resume

Result :
N E X T F L O W  ~  version 18.10.1
Launching `script5.nf` [gigantic_meucci] - revision: e509faf0e3
R N A S E Q - N F   P I P E L I N E    
===================================
transcriptome: /home/jfourquet/MIAT/Documents/Projet/1901_Nextflow_tests/nf-hack18/course/data/ggal/transcriptome.fa
reads        : /home/jfourquet/MIAT/Documents/Projet/1901_Nextflow_tests/nf-hack18/course/data/ggal/gut_{1,2}.fq
outdir       : results

[warm up] executor > local

Thanks a lot for your help,
Joanna

**Comment by pditommaso** [comment]
Yes, it is. It says 

```
The script will report the following error message:

Channel `read_pairs_ch` has been used twice as an input by process `fastqc` and process `quantification`
```

You need to replace `set` with `into as explained in the point 2.5.1 to make it work.

**Comment by jfourquet2** [comment]
Thanks for your answer. The issue is that I haven't the error message :
`Channel` `read_pairs_ch` has been used twice as an input by process `fastqc` and process `quantification`
Is it normal ?

**Comment by pditommaso** [comment]
I don't know. Include the script you are using and the command line you are using to run it.

**Comment by jfourquet2** [comment]
The script is:
```
/* 
 * pipeline input parameters 
 */
params.reads = "$baseDir/data/ggal/gut_{1,2}.fq"
params.transcriptome = "$baseDir/data/ggal/transcriptome.fa"
params.multiqc = "$baseDir/multiqc"
params.outdir = "results"

println """\
         R N A S E Q - N F   P I P E L I N E    
         ===================================
         transcriptome: ${params.transcriptome}
         reads        : ${params.reads}
         outdir       : ${params.outdir}
         """
         .stripIndent()

/* 
 * create a transcriptome file object given then transcriptome string parameter
 */
transcriptome_file = file(params.transcriptome)
 
/* 
 * define the `index` process that create a binary index 
 * given the transcriptome file
 */
process index {
    
    input:
    file transcriptome from transcriptome_file
     
    output:
    file 'index' into index_ch

    script:       
    """
    salmon index --threads $task.cpus -t $transcriptome -i index
    """
}


Channel 
    .fromFilePairs( params.reads )
    .ifEmpty { error "Oops! Cannot find any file matching: ${params.reads}"  }
    .set { read_pairs_ch } 

process quantification {
     
    input:
    file index from index_ch
    set pair_id, file(reads) from read_pairs_ch
 
    output:
    file(pair_id) into quant_ch
 
    script:
    """
    salmon quant --threads $task.cpus --libType=U -i $index -1 ${reads[0]} -2 ${reads[1]} -o $pair_id
    """
}

process fastqc {
    tag "FASTQC on $sample_id"

    input:
    set sample_id, file(reads) from read_pairs_ch

    output:
    file("fastqc_${sample_id}_logs") into fastqc_ch


    script:
    """
    mkdir fastqc_${sample_id}_logs
    fastqc -o fastqc_${sample_id}_logs -f fastq -q ${reads}
    """  
}
```

The command line is:
`nextflow run script5.nf`

Thanks a lot again for your help !

**Comment by pditommaso** [comment]
If I executed that script I get the error message as expected:

```
ERROR ~ Channel `read_pairs_ch` has been used twice as an input by process `fastqc` and process `quantification`

 -- Check script 'script5.nf' at line: 62 or see '.nextflow.log' file for more details
```
 
Not sure how to help, make sure your scripts have not been modified. Please use the [workshop github repo](https://github.com/nextflow-io/nf-hack18) for question related to the course/tutorial.
