### ISSUE TITLE
Remove deprecated operator route

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#991]
The operators `groupBy` and `route` have been deprecated and need to be removed.

**Comment by gcornut** [comment]
It would be nice to know why they are deprecated or what to use instead of them. 

What can I use to replace of `groupBy` ?

**Comment by pditommaso** [comment]
Both operators were early days experiments. The problem with `groupBy` is that it introduces a synchronisation point in your pipeline because it needs to gather all the entries before returning the result. Moreover, it uses a Map object while operators/processes tend to work with tuples. Regarding `route` I don't even think there's a real use case for it.

**Comment by gcornut** [comment]
Ok actually for my use case I ended up using `reduce`. It also introduce a synchronization point but it is at the end of the pipeline and it should not accumulate too much data (just lists of files and line count)

**Comment by sminot** [comment]
@pditommaso can you comment on how the utility of `groupBy` can be replaced once it is gone?

**Comment by pditommaso** [comment]
Yes, `groupTuple` provides a better way to achieve the grouping than `groupBy` for the reason explained above. However, there isn't a direct replacement and some coding is required because to handle the different output provided by `groupTuple`. 

However since multiple people have expressed concerns about the removal of `groupBy`, I've decided to keep it for now and just show a deprecation message for now.
