### ISSUE TITLE
Promote ansi logging as default console outout

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#996]
The ANSI console logging it should be promoted as default standard output when a shell terminal is available and NF is not running in background. 

A command line option should be given to disable it.

**Comment by pditommaso** [comment]
Also, completed processes should be marked with a tick on the output line e.g. ✅

**Comment by rsuchecki** [comment]
Some of my pipelines have alternative paths, in which case, for a given run I may have a lot of processes  which will not get run and are displayed with  `[  0%] 0 of 0`. 

Perhaps these  could be presented differently, to make it easier to spot the relevant ones? Having a lot of `[  0%] 0 of 0` in the list makes it harder to spot `[  0%] 0 of N`. For example

```
> process a        [  0%] 0 of 0`
> process a        [  0%] 0 of 0`
> process a        [  0%] 0 of 0`
```

**Comment by pditommaso** [comment]
Do you mean when having a process in a `if` branch? makes sense.

**Comment by rsuchecki** [comment]
I guess this would apply to `if` branching as well, but I tend to prefer to do that with `when:` declarations in processes -   aesthetically much more appealing 😉

**Comment by pditommaso** [comment]
Ah! now I'm understanding because with `if` it should not happen. 

If you want to give a try have a look here https://github.com/nextflow-io/nextflow/blob/ce3bd9d1a2f881d6cb1007319fa328fdedcf5e81/modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy#L245

**Comment by rsuchecki** [comment]
Sure, I'll have a play thanks!

**Comment by rsuchecki** [comment]
Tried a few things, e.g. 

```
> process one   [100%] 4 of 4, cached: 4 ✔
> process three [100%] 2 of 2, cached: 2 ✔
> process five  [100%] 8 of 8, cached: 8 ✔
> process four  [100%] 10 of 10, cached: 10 ✔
> process two          0 of 0 ⛔
```

but really just skipping such processes may be a better solution, especially for larger workflows to prevent polluting the terminal with unnecessary information, so e.g.  https://github.com/nextflow-io/nextflow/blob/ce3bd9d1a2f881d6cb1007319fa328fdedcf5e81/modules/nextflow/src/main/groovy/nextflow/trace/AnsiLogObserver.groovy#L173-L174 could be conditional on the number of tasks 

```
if((entry.value.submitted + entry.value.cached) > 0) {
  term.a(line(entry.key,entry.value)) 
  term.newline() 
}
```

**Comment by photocyte** [comment]
Has the command line option to disable the Ansi logging been implemented yet?  I'm not seeing it on 19.02.0-edge .  The Ansi logging is pretty neat, but it produces a lot of output when the stdout is being piped.  Plus the former version (providing the directory of the job in question) was a useful debugging feature / makes Nextflow less of a black box for first time users.

**Comment by rsuchecki** [comment]
`-ansi-log false` but you are absolutely correct, there are some log messages that still need to be captured for ansi logging to work as intended. As for work dir it can also be retrieved from `.nextflow.log`.

**Comment by pditommaso** [comment]
Ok, pushed a patch as suggested
