### ISSUE TITLE
Timeline and execution reports may contain invalid memory values

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/nextflow#999]
The Memory unit string formatter uses a decimal separator symbol that's local depend. This can cause tricky if not invalid memory string values in the timeline and execution reports.

**Comment by phupe** [comment]
As reported in #986, it seems to be a locale issue:

I have found the problem thanks to your comment! It is a locale issue.

My guess is that you should be able to reproduce the issue if you set export LANG=fr_FR.UTF-8 in the bash environment before launching nextflow.

The decimal point magically appears whether I set export LANG=C, export LANG=, or export LANG=en_US.UTF-8

**Comment by pditommaso** [comment]
Fixed.

**Comment by pditommaso** [comment]
Included in version `19.02.0-edge`.
